### ISSUE TITLE
Stops responding when going to specific nameddest

### ISSUE THREAD

**Issue by wdherndon** [sumatrapdfreader/sumatrapdf#10]
SumatraPDF crashes when the nameddest ABOUT is specified with the attached PDF.
I verified with the following command line:

start sumatrapdf -named-dest ABOUT "JetScribe 5.0 Manual.pdf"

SumatraPDF opens, starts the wait cursor, and stops responding.

The PDF is available here:

http://ge.tt/8XILmp52/v/0?c

I verified that the Acrobat Reader opens to the nameddest without problems:

start acrord32.exe /A nameddest=ABOUT "JetScribe 5.0 Manual.pdf"

works just fine.

**Comment by wdherndon** [comment]
Sorry to bother you again - do you know when the next release will be? I've put code in my company's software to use nameddest with SumatraPDF, and the new code will be released soon. If a new release of SumatraPDF is not planned soon, I want to remove it: it makes a really bad impression when the help function crashes.

**Comment by kjk** [comment]
We don't know when the next release will be, but not any time soon.

**Comment by wdherndon** [comment]
Is any kind of work-around possible? What is holding back a new release, and is there anything I could do to help?

**Comment by kjk** [comment]
I don't think there's a work-around.

We release a new version when we decide there are enough new features implemented and we're not there yet.

**Comment by zeniko** [comment]
Possible work-arounds might involve shipping a prerelease build along your software - available from http://www.sumatrapdfreader.org/prerelease.html - or using a format other than PDF for your documentation - e.g. XPS which also supports destination ids/names or a table of contents (from which SumatraPDF also synthesizes destination names). Sorry for the inconvenience.

**Comment by wdherndon** [comment]
Zeniko: neither is viable for us. Our software uses the users default PDF-Reader, whatever it may be. We will not be shipping a PDF-Reader and we will not be changing the format this late in development. The only options for us are (1) deactivate the nameddest handling for SumatraPDF, or (2) send the user to you guys when they have problems. The project manager has currently opted for (2) at this point.
