### ISSUE TITLE
Printing scaled to about half size

### ISSUE THREAD

**Issue by thany** [sumatrapdfreader/sumatrapdf#100]
I've got a landscape-oriented [document](http://home.thany.nl/browsable/toyooka-kounotorinosato.pdf), 1 page, and printed it on a real printer. I tried twice, once with everything default (Ctrl+P, Enter) and once with setting the printer to landscape orientation. The results are idential. In both cases, the printer spews out an A4 with the documents scaled to about half size, centered in the middle of the page.

As far as I can tell, there's no extra space around the document. My printer is fine: it has printed other PDF's with Sumatra just fine. I'm using a Color Laserjet 1600, latest drivers, on Windows 7, and the currently latest release of Sumatra.

**Comment by ousia** [comment]
Hi @thany, does Adobe Reader print the document right?

From your description, the issue isn’t only that the document is scaled when printed. As far as I can understand, this is a side-effect of SumatraPDF rotating the page.

@kjk, I wonder whether this makes sense, but couldn’t SumatraPDF check paper size (ideally, in each page) and automatically rotate printing to the setting (landscape or portrait) it fits best?

**Comment by ousia** [comment]
@thany, I’m experiencing a weird issue with your document in evince (I have just checked).

If I select ”auto rotate and center”, I get the output you describe (in a print preview, I don’t have a printer here). But if I disable this option, output is as it should be.

There might be something wrong with this file. "/Rotate 0" might be the cause.

@kjk, could "auto rotate and center " be a selectable option in the printing dialog?

**Comment by thany** [comment]
I haven't checked Adobe Reader. And honestly I've installed Sumatra because I don't want Adobe Reader ;)

Anyway, please bear in mind that with the same settings (whatever they are, I just didn't touch them) I can print (and have printed) many other landscape-oriented documents absolutely fine. But from your description I get the feeling it's a glitch in the document?... Would it be possible for SumatraPDF to correct for it?

**Comment by ousia** [comment]
@thany, I’m afraid I’m only an average user (I cannot code).

I guess that this issue could be fixed. But SumatraPDF needs a proper printing dialog (such as the one described in #102).

Unless automatic rotation and centering could be disabled in SumatraPDF (they seem to be enabled by default), you won’t be able to print documents such as this one.

I think this shouldn’t be extremely hard to implement, but people at @sumatrapdfreader may be busy with other things (my guess).

**Comment by ousia** [comment]
@thany, I think that the way to fix this issue may be to ignore page rotation when printing, because it seems that SumatraPDF already automatically rotates the page.

@kjk, if SumatraPDF already rotates automatically the page when printing it, how about ignoring the `/Rotate` key in `/Page` object only when printing? (Otherwise automatic rotation to fit best the page won’t work in some cases.)

**Comment by EpicWolverine** [comment]
Have you tried setting `PrintScale = fit` under `PrinterDefaults` in the Advanced Options configuration file (SumatraPDF-settings.txt)? This fixed a similar problem I had when printing PDFs to OneNote (documents scaled to about half size, centered in the middle of the page).

**Comment by GitHubRulesOK** [comment]
@kjk note that this is not an "issue" simply un-expected behaviour @EpicWolverine  is correct the original is approx A5 thus if not specifically set to "Fit" it will by default print centred appearing as at half size  on an A4 page
