### ISSUE TITLE
Can't open pdf 

### ISSUE THREAD

**Issue by istevenshen** [sumatrapdfreader/sumatrapdf#1001]
I have a pdf in chinese, and it can be opened by google chrome, but when I use SumatraPDF-3.1.2-64, it didn't work.

Here is my pdf: [algorithm.pdf](https://cosdata-1251708715.cos.ap-guangzhou.myqcloud.com/algorithm.pdf).

**Comment by SumatraPeter** [comment]
Neither Firefox nor Edge can open it, while xpdf tools, qpdf etc. all  complain about a missing header, damaged xref table and being unable to find the trailer dictionary among other errors. File is definitely broken.

**Comment by GitHubRulesOK** [comment]
This file is NOT a PDF its MagicID is 62 14 23 65 which is an E-SafeNet encrypted file,
it can only be opened by an E-SafeNet enabled application either google chrome has a suitable helper app included or the computer that opens it has a suitable decryption driver
In either case I repeat although the filename is.PDF it is NOT an adobe structured PDF and this issue can be closed as not relavent to SumatraPDF

**Comment by kjk** [comment]
Closing as we can't support that.
