### ISSUE TITLE
libmupdf？

### ISSUE THREAD

**Issue by ypiker** [sumatrapdfreader/sumatrapdf#1004]
I added a new interface to mupdf, but after compiling libmupdf, I didn't have this interface. why？i hope you can help me。thank you！

**Comment by kjk** [comment]
Not nearly enough detail in the question.

**Comment by ypiker** [comment]
I want to know how libmupdf can transform static libraries to dynamic libraries.   I add an interface  name to pdf_sign_sm2signature   in the mupdf/pdf/crypt.h file， after I compile mupdf ，i can find the interface in the mupdf.lib,but  i compile the libmupdf,  i can't find the interface in the libmupdf.dll. i don't know  the reason.

**Comment by ypiker** [comment]
if i need to add the interface  in the libmupdf.dll , what should i do？
