### ISSUE TITLE
Scanned document results in black display

### ISSUE THREAD

**Issue by Peter0** [sumatrapdfreader/sumatrapdf#1005]
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1902006/test.pdf)

At the attached file there is a scan. When opening with SumatrPDF, it shows a black window. When using PDFXChange, the scanned document is showed correctly.

Thanks so far, Peter

**Comment by Peter0** [comment]
Using Win-7 and SumatraPDF 3.1.2 64bit.

**Comment by Peter0** [comment]
Maybe it the same problem as in #991?

**Comment by kjk** [comment]
It's a mupdf issue. I've tested with mupdf 1.12 and it still doesn't render.

**Comment by GitHubRulesOK** [comment]
I dont think this is exactly the same problem as 991 since that was FAX format and started to decode but failed part-way through resaving the file in another format fixed that behaviour.
This sample is Web optimised JPEG and whilst it can be saved in another format that will render correctly, it was not always visible with the toolkit i tried
In summary similar behaviour (i.e. MuPDF can not decode) however I suspect they are two different issues that may need seperate resolutions on their part. @Peter0 I suggest if you need to open more of these scan format then as recommended in issue 991 you raise this an issue at https://bugs.ghostscript.com/ and report bug report number back here, thanks

@kjk is it possible to flag (lable) MuPdf issues as cant fix by Sumatra unless next MuPDF has resolved?

**Comment by Peter0** [comment]
I don't know what should I write in a Ghostscript issue tracker, because Ghostscript opens this file just fine.

**Comment by GitHubRulesOK** [comment]
@Peter0 
I observed in the #991 thread that ghostscript DOES render these files, however the authors of MuPDF (the pdf software enginefor SumatraPDF) share the same bug reporting list, you need to specifically say it is a **MuPDF bug** (and observe it is not present in Ghostscript)

**Comment by Peter0** [comment]
There is a apart MuPDF bugtracker.
Filed under 699343.
Let's see what happens…

Thanks, Peter

https://bugs.ghostscript.com/show_bug.cgi?id=699343

**Comment by GitHubRulesOK** [comment]
@Peter0 
Thanks for reporting  your files to MuPDF, I note they have replied that the PDF's whilst read by some applications have an error condition that needs to be cleared. I do not expect SumatraPDF will be able to view these files without some pre-processing,
You mention they can be viewed in PDFXchange. I was able to load and save your sample from PDFXEdit7_Portable as a TIFF (without watermark), and there are several options to change quality. 

SumatraPDF can Load TIFF format and SAVE AS PDF (there are many other ways to achieve automatically corrected PDFs but this is the most compatable solution using SumatraPDF itself)
for the result see

![untitled](https://user-images.githubusercontent.com/12754913/40028088-f5131472-57d4-11e8-8619-8118d270f059.PNG)

**Comment by Peter0** [comment]
I am able to view these files.
Without using TIFF export, it look simpler to just use ImageMagick's Convert:
convert test.pdf test2.pdf
The resulting file is somewhat bigger in filesize, but opens just fine with Sumatra.

Maybe it's possible to earn some kind of error state from MuPDF (I asked for some kind of error handling in MuPDF's bug report). In this case, Sumatra could change to phase 2 – starting on the fly a configurable external program (like Convert) and trying to display its stdout instead of using the input file directly.

**Comment by GitHubRulesOK** [comment]
It is unlikely SumatraPDF will correct  these files atomatically even if it was  re-written to to ignor the error state.
you can use the "external viewer" feature to pass the error pdf file to any program such a viewer or if you have a magic correction command and if the final filename stays the same and is under 10Mb sumatrapdf should reload the result in a similar fashion to when using a latex editor.

**Comment by GitHubRulesOK** [comment]
@Peter0 
you have probably done this by now, however for the benefit of others that may need a similar solution.

based on your suggestion I have tested a copy of your sample with a simple modification to the  advanced settings file I changed it to include
ExternalViewers [
	[
		CommandLine = fix.cmd "%1"
		Name = FixPDF
		Filter = *.pdf
	]
]

the file fix.cmd is in the same directory as the files to be fixed so it needs no elaborate prefix path (KISS)

the fix.cmd file contains 3 lines

ren %1 "%~n1.backup%~x1"
magick\convert "%~dpn1.backup%~x1"  %1
pause

NOTE
 I included Magick (with the 4 key GS binary files) as a subdirectory to avoid clutter or messing about with filepath syntax

once tested remove the last "pause" line

1 Open a file if it is good move on to the next
2 if it has spaces (Black screen) pick the FixPDF option
3 after a few seconds it should automatically reopen as per screenshot

![untitled](https://user-images.githubusercontent.com/12754913/40088160-ad6b7000-589d-11e8-9b3d-a74f00a51818.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
since this issue was as a result of "faulty" files (blank characters prior to image), and affects other viewers, I suggest it may be closed as not specific to SumatraPDF

**Comment by kjk** [comment]
Closing as per suggestion.

**Comment by TamirEvan** [comment]
@Peter0
Although mupdf-1.14.0 (released 2018-10-04) still had this bug, [it has been fixed](https://bugs.ghostscript.com/show_bug.cgi?id=699343#c8) since (as of ArtifexSoftware/mupdf@8796a6088b64659eb7eb32fcf0fe9bd9a7673110):

![latest mupdf showing test pdf](https://user-images.githubusercontent.com/1873062/50281552-751d5300-0458-11e9-976e-b62e4ab0b01e.png)

**Comment by GitHubRulesOK** [comment]
Just an update on a positive note to confirm this specific issue is no longer present in new builds

![Untitled](https://user-images.githubusercontent.com/12754913/68896206-e32ed080-0722-11ea-95a2-d662d4b843e3.png)
