### ISSUE TITLE
Is development abandoned?

### ISSUE THREAD

**Issue by AdKiller** [sumatrapdfreader/sumatrapdf#1006]
No update since 2016. Is this the end of sumatrapdf?

**Comment by kjk** [comment]
It's inactive but not abandoned. I'm still here. Before you ask: I make no promises about the future.

**Comment by passboltUser** [comment]
I think you should abandon it and move to an open source operating system like Linux. Win is a proprietary system, without knowledge for other people how things work as no source code is available, so it doesn't even matter if it spies on one or not.

**Comment by AdKiller** [comment]
@passboltUser I would love to move away from Windows and to Linux, but I don't have the required computer science degree and time to learn its quirks.
