### ISSUE TITLE
Background color behind document before print.

### ISSUE THREAD

**Issue by dzmitry-lahoda** [sumatrapdfreader/sumatrapdf#1007]
1. Windows 10 64 bit as Installed.
2. LibreOffice Impress
3. LO I export as PDF.
4. SumatraPDF. Today from Chocolatey. 
5. Open exported.
6. See gray margins or paddings.
Expected: Be slightly lighter as native windows only software.
Actual: To Dark.
![image](https://user-images.githubusercontent.com/757125/38759894-cee1cf4e-3f80-11e8-819e-a742a2f7fd8d.png)

Notes: 
Because people think margins or padding will be printed.
Because native windows only software should look and feel.

**Comment by dzmitry-lahoda** [comment]
на винде есть проги где как бы холст. и где он кончается начинается серый фон
так я создал баг что в проге фон не серый
то есть слишком темный
а должен быть как везде в винде
чтобы юзеров не смущать
ибо программа только для Windows

On Windows there are programs where as though a canvas. and where it ends the gray background begins
so I created a bug that in the background the background is not gray
that is too dark
And should be as everywhere in Windows
so that users do not confuse
because the program is only for Windows

**Comment by GitHubRulesOK** [comment]
@dzmitry-lahoda 
you can change the background colour behind the image using SumatraPDF-settings.txt

from manual "  colors to use for the gradient from top to bottom (stops will be inserted at regular intervals throughout the document); currently only up to three colors are supported; the idea behind this experimental feature is that the background might allow to subconsciously determine reading
    progress; suggested values: #2828aa #28aa28 #aa2828"
    GradientColors = #RRGGBB [#............] [#...........]

 thus the "advanced" setting you probably need is 
GradientColors = #FCFCFC

you can also try UseSysColors

if true, we use Windows system colors for background/text color. Over-rides other settings, default is
UseSysColors = false

**Comment by GitHubRulesOK** [comment]
@kjk 
since there are several options in SumatraPDF-settings.txt to address this issue, I suggest it be closed as not specific to current behaviour

**Comment by kjk** [comment]
Closing as per suggestion.
