### ISSUE TITLE
trying to copy certain characters results in wrongly copying much characters.

### ISSUE THREAD

**Issue by DavidLiu642874264** [sumatrapdfreader/sumatrapdf#1008]
When i am trying to copy chinese date from pdf ,it return an error text。For example, i try to copy "**2014 年  1-6 月**" from pdf  ,it return  "**2014 年 年 1-6 月**" 。There is a extra character "年" in string. 
![default](https://user-images.githubusercontent.com/29088479/38983116-2af0b984-43f6-11e8-9cb9-9c5bf60056d4.png)
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1927459/test.pdf)

**Comment by SumatraPeter** [comment]
Just to rule out that it's a file-specific issue, can you copy properly using any other PDF reader?

**Comment by DavidLiu642874264** [comment]
@SumatraPeter.  I have tried  the adobe pdf ,it is ok. i think it is the Sumatra error when get text from the pdf .
the code is
  text[pageNo - 1] = engine->ExtractPageText(pageNo, L"\n", &coords[pageNo - 1]);
I have saw the point memory in memory , there is a redundant chinese character "年".it is  "2014 年 年 1-6 月" .  when i try to search " 2014 年 1-6 月" ,i will return fail.

**Comment by SumatraPeter** [comment]
In that case you'll have to wait for Sumatra's dev to fix the issue.

**Comment by GitHubRulesOK** [comment]
@kjk 
I may be wrong but I think there has been much improvement in unicode support within MuPDF
here is the same sample file (from above) correctly handled by latest MuPDF 1.13

note this is a composite screen grab of 1=the search 2=the result and 3=the other "about" box

![untitled](https://user-images.githubusercontent.com/12754913/39076489-a014200e-44f3-11e8-8b85-03499e8e362e.PNG)

**Comment by Thinkpositiv** [comment]
Well, I think I also found a copy and paste issue in Sumatra V3.1.2 64bit (on Win10 64bit).
File http://steamforged.com/s/DS-Core-Rules-lores.pdf
On page 19, I selected the bottom paragraph in right column. I now paste it here.
The second sentence has two errors ("Te" instead of "The" and "frst" instead of "first"). For example Microsoft Edge copies this correctly.

> No matter whether the encounter ends in victory
> or defeat, give the First Activation token to the
> player who is next in turn order after the last
> player who activated their character. Te player
> with the First Activation token will activate their
> character frst in the next encounter.

Hope that helps,
Bests, Björn

**Comment by GitHubRulesOK** [comment]
@Thinkpositiv 
your example is a slightly different issue, best raised as a bug at ghostscript site since MuPDF shares the same developers and MuPDF 1.13 (the latest) also has the same failing.

"Te player with the First Activation token will activate their character frst in the next encounter."

HOWEVER using X-PDF (a different common pdf engine) the result is
" e player with the First Activation token will activate their character rst in the next encounter."
this suggesting there is a common problem in translating the underlying characters code or spacing.

**Comment by Thinkpositiv** [comment]
You're right, it is slightly different issue.
But as a standard user I'm not willing to dig deep into such thing, creating multiple accounts on different sites/projects, etc. In the chain of "customers", I'm just the end-users. Imho Sumartra is a "customer" of ghostscript/MuPDF then and should report this bug there. It will most likely have much more audience then a single end-user like me. (Assuming Sumatra supports a copy/paste feature).
I found [a statement](https://bugs.ghostscript.com/show_bug.cgi?id=692395#c4) like this

> The first point is that we don't guarantee *any* ability to cut/paste/search text in the output from pdfwrite. Not at all, not from any input source (PostScript, PDF, XPS, PXL, PCL)

If users are able to select text and a "Copy" option is available, I expect it to work properly. So hmm, I will need to make my thoughts and choices - anyways, thanks for your keep-up!

**Comment by DavidLiu642874264** [comment]
So this bug is hard to be solved !

**Comment by HollenLima** [comment]
I got the same problem, with English text, didn't try other language.

Tried to copy the phrase bellow(highlighted in the image):
"muscles t**h**at d**ev**elop from somites"

and the control+v give this:
"muscles t_ll_at d_l!ll_elop from somites"

![untitled](https://user-images.githubusercontent.com/39095539/39767588-1d7dc922-52b5-11e8-8b53-0b1c0b1de2d8.png)

Another attempt to copy the next phrase, look the image bellow, and appear this "slashes" between the letters:

control+v, give me, exactly, this non-linear misplaced(letters) phrase:
"n
n
e
~
muscles tht
d
~
l
o
p
from the bronchial arche"

instead a linear complete phrase:
"innervate muscles that develop from branchial arches"

**Comment by GitHubRulesOK** [comment]
Just a  follow up for the above 3 samples
The example from @DavidLiu642874264 was "fixed" a long time ago and is still working as expected in current version.

The example flawed PDF linked above by @Thinkpositiv  is now a different link but still needs to be re-written with th's etc. This is a common issue with using non standard / custom encoding.
Using a PDF analyser we can see "WinAnsiEncoding (with differences)" and it is those differences (Ligatures) that are not true windows native characters that creates the issue, even though they were included.
Windows clipboard will not replace a combined single fl (†) glyph  with  f and i so in the clipboard we see " rst" in place of "first" even the analyser is struggling to make sense of †rst
![image](https://user-images.githubusercontent.com/12754913/116747809-62d35c80-a9f6-11eb-801c-f39e1193aa88.png)

The third example from @HollenLima is almost certainly BAD OCR where the operator was either a robot or just too lazy/inexperienced to use an English spell checker. This often results in nonsense words without meaning and or one character per text block objects
