### ISSUE TITLE
different font for document properties window

### ISSUE THREAD

**Issue by ousia** [sumatrapdfreader/sumatrapdf#101]
Would it be possible that the font for document properties wouldn’t be a black or bold font?

Sorry, but I’m afraid that the current black or bold font only makes the text harder to read.

**Comment by andreldm** [comment]
Here it's impossible to read anything, the window is completely black.
I had to install another PDF reader just to know the documents properties :(

**Comment by kjk** [comment]
@andreldm can you post a screenshot? PDF properties window background is supposed to be yellow.

**Comment by andreldm** [comment]
Sure, here it is.
![a](https://cloud.githubusercontent.com/assets/599565/6988024/9a5d55ce-da23-11e4-8c34-51206e481468.jpg)

Here are the settings(except FileStates): http://pastebin.com/PMjeVwKV
I've just updated from 2.4 to 3.0 but no cigar.

**Comment by GitHubRulesOK** [comment]
@kjk the second issue is duplicate of Cannot see PDF properties. #539
where the user has changed the default to MainWindowBackground = #ffffff00
thus unwittingly setting it to pure black such that the black text is not seen

The original issue still stands as a feature request to change the font colour which could be tied to the corresponding font colour in 
FixedPageUI [
	TextColor = #ff0000
which would have potentially avoided the issue of black on black, however that could simply raise other support issues.

**Comment by kjk** [comment]
In current code the color of properties window is not affected by settings, so this is fixed.
For other issues, let's open separate bugs.
