### ISSUE TITLE
My TIF image will not open

### ISSUE THREAD

**Issue by Arlenemack** [sumatrapdfreader/sumatrapdf#1010]
[Tiff will not open in SumatraPDF.docx](https://github.com/sumatrapdfreader/sumatrapdf/files/1933475/Tiff.will.not.open.in.SumatraPDF.docx)
![untitled](https://user-images.githubusercontent.com/38570737/39070913-1f9e48a4-44b3-11e8-8896-cf95f422b068.jpeg)

**Comment by kjk** [comment]
Please provide the file that doesn't open, describe how you were opening it, which version of Sumatra did you use and what software does open it (to make sure it's a valid file).

I don't understand what the attached screenshot of event log entry is showing and how it relates to Sumatra not opening a file.

**Comment by Arlenemack** [comment]
This is the message that I am getting.

[cid:image001.png@01D3D8C1.98892990]

Thank you,
Arlene Mack, IT Associate IV
Gwinnett County, Clerk Of Court
75 Langley Drive
Lawrenceville, GA 30046
770.822.8164 – Phone
arlene.mack@gwinnettcounty.com<mailto:arlene.mack@gwinnettcounty.com>

**Comment by kjk** [comment]
There's nothing I can do without detailed information I asked for.
