### ISSUE TITLE
draw/clip order not respected

### ISSUE THREAD

**Issue by kpym** [sumatrapdfreader/sumatrapdf#1013]
I know that this is a mupdf bug, but:

- I was not able to report it at [bugzilla](bugs.ghostscript.com);
- It result in a bug of sumatrapdf.

**In the attached PDF file the red rectangle should not be visible.**

The original PDF is [clip_draw_bug.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1982556/clip_draw_bug.pdf).

The resulting images are:

- Acrobat : 
  
  ![clip_draw_bug_acrobat.png](https://user-images.githubusercontent.com/3142701/39741245-71722bfc-5299-11e8-9885-6459080ca58c.png)
  
- GhostScript : 
  
  ![clip_draw_bug_gs.png](https://user-images.githubusercontent.com/3142701/39741243-7138d3d4-5299-11e8-92b9-d36b7504a1f6.png)
  
- Mutool : 
  
  ![clip_draw_bug_mudraw.png](https://user-images.githubusercontent.com/3142701/39741242-712027e4-5299-11e8-8f6a-abd069488e69.png)
  
- Mudraw : 
  
  ![clip_draw_bug_mutool.png](https://user-images.githubusercontent.com/3142701/39741244-71565f94-5299-11e8-90f5-8f61fd24c685.png)
  

# mutool (mudraw) do not respect draw/clip order

 The default order the actions on a path are fill/draw/clip.
But `mutool draw` (and the older `mudraw`) do not respect this, they clip first and draw after.

I attach a PDF file and the resulting PNG files obtained by Acrobat, gswin32c, mutool draw (v 1.13.0 -windows) and mudraw.exe (from 2015).

When the correct order is respected the red rectangle should be invisible.

The commands were:

- Acrobat : export to PNG
- GhostScript : `gswin32c -dDownScaleFactor=4 -dSAFER -dBATCH -dNOPAUSE -sDEVICE=pngalpha -r700 -sOutputFile=clip_draw_bug_gs.png clip_draw_bug.pdf`
- mutool : `mutool draw -o clip_draw_bug.png clip_draw_bug.pdf 1`
- mudraw :`mudraw -o clip_draw_bug.png clip_draw_bug.pdf 1`

The PDF file was obtained with xelatex from the following source :

```
\documentclass[tikz,border=7pt]{standalone}
\begin{document}
  \begin{tikzpicture}[line width=2mm]
   \scoped
    \clip[preaction={draw=red}] (-1,-1) rectangle (1,1);
    \draw[blue] (-2,0) -- (2,0);
  \scoped
    \draw[clip] (-1,-1) rectangle (1,1);
     \draw[green] (0,-2) -- (0,2);
  \end{tikzpicture}
\end{document}
```

**Comment by GitHubRulesOK** [comment]
IF IT IS A PROBLEM IN MuPDF then it is their bug (Sumatra uses their engine) 
NOTE MuPDF is a sister product to Ghostscript and you have reported this twice to them
see https://bugs.ghostscript.com/show_bug.cgi?id=699319

@kjk I suggest this be tagged as MuPDF (i.e. awaiting their bug fix)

**Comment by kpym** [comment]
You do not need capital letters to repeat something that is already in the bug request ;) And yes finally my bug report on bugzilla (that I considered as unsuccessful) was published twice :(

**Comment by ousia** [comment]
@kjk, the issue seems to be fixed with [this commit](http://git.ghostscript.com/?p=mupdf.git;h=934c511da4d3585631b4a32a81a16228202f9ec7).

**Comment by GitHubRulesOK** [comment]
@kpym _SORRY_ did not mean to leave CAPS Lock on (my bad) , thanks for your report this would now seem to be addressed as reported by @ousia ( also thanks) 
@kjk any chance you can include latest MuPDF commits to close this Fix (699319: Apply clip path after drawing, not before) and possibly several others tagged MuPDF  ?

**Comment by kjk** [comment]
Unfortunately mupdf code diverged so much from the version in Sumatra that upgrading it is a big task.

**Comment by kpym** [comment]
@kjk A general merge is probably hard, but applying some particular "small" bug correcting patches like [this one](http://git.ghostscript.com/?p=mupdf.git;a=patch;h=934c511da4d3585631b4a32a81a16228202f9ec7) is probably not so hard ?

The position of the code [is not the same anymore](https://github.com/sumatrapdfreader/sumatrapdf/blob/95f60d5359232520e69ed82f9c3a3f70a04f66e0/mupdf/source/pdf/pdf-op-run.c#L917) but the code to be patched is there.

The only thing to check is if the new code do note use new features not present in Sumatra's version. I'm not competent to check this, else I would submit a pull request :(

**Comment by GitHubRulesOK** [comment]
@kjk another one that's fixed by MuPDF update 

![Untitled1013](https://user-images.githubusercontent.com/12754913/68903184-39efd680-0732-11ea-9c9c-27e67439a11c.png)

**Comment by kjk** [comment]
Thanks @GitHubRulesOK 
Fixed in latest build https://www.sumatrapdfreader.org/dailybuilds.html
