### ISSUE TITLE
Copying linear phrases, Getting miss-character words + nonlinear phrases.

### ISSUE THREAD

**Issue by HollenLima** [sumatrapdfreader/sumatrapdf#1014]
Repeating this, my, post(https://github.com/sumatrapdfreader/sumatrapdf/issues/1008) from other issue topic, cause there wasn't this linear to nonlinear phrase

I got the same problem, with English text, didn't try other language.

Tried to copy the phrase bellow(highlighted in the image):
"muscles t**h**at d**ev**elop from somites"

and the control+v give this:
"muscles t_ll_at d_l!ll_elop from somites"

![untitled](https://user-images.githubusercontent.com/39095539/39767588-1d7dc922-52b5-11e8-8b53-0b1c0b1de2d8.png)

Another attempt to copy the next phrase, look the image bellow, and appear this "slashes" between the letters:

![untitled2](https://user-images.githubusercontent.com/39095539/39768385-2be9fbaa-52b7-11e8-8593-983b2510c800.png)

control+v, give me, exactly, this non-linear misplaced(letters) phrase:
"n
n
e
~
muscles tht
d
~
l
o
p
from the bronchial arche"

instead a linear complete phrase:
"innervate muscles that develop from branchial arches"

OBS. I've noticed that all this issues, at my case, come from text inside a table/label content, as my third try to copy from free text around the table/label content works fine.

**Comment by GitHubRulesOK** [comment]
This poor rendering of embedded text is generally not a bug in SumatraPDF it is usually due to a BAD SOURCE (possibly a pirate copy) or a poor author, there are other types of issues when reading foreign characters those need to be reported to GhostScript.com as SumatraPDF only captures whats hidden behind the image

**Comment by GitHubRulesOK** [comment]
@kjk without the above file its difficult to prove if it was a poor pirate copy or bad authoring
However the issue it was linked with in #1008 now behaves correctly in current pre-release
I suggest this issue be closed unless the sample file can be made available for testing
