### ISSUE TITLE
Fit Width, setting options don't work!

### ISSUE THREAD

**Issue by HollenLima** [sumatrapdfreader/sumatrapdf#1015]
Solved in a minute, by curiosity! But there is still a doubt.

This feature don't work when set to open Sumatra with Fit Width mode.
but solved just now.

It only works without automatic layout, need to set both.

But if, Fit Width only works without automatic layout, it should be changed auto for any other layout mode, once that Fit Width didn't change the view with any other layout mode?

I'm new here, cant delete/mark as solved a solved issue! Help ( Solved Too)

**Comment by HollenLima** [comment]
This feature don't work when set to open Sumatra with Fit Width mode.
but solved just now.

It only works without automatic layout, need to set both.

But if, Fit Width only works without automatic layout, it should be changed auto for any other layout mode, once that Fit Width didn't change the view with any other layout mode?

I'm new here, cant delete/mark as solved a solved issue! Help

**Comment by SumatraPeter** [comment]
Since you reopened this, do you still have a doubt?

> It only works without automatic layout, need to set both.

Which menu item corresponds to "automatic layout" according to you?

**Comment by kjk** [comment]
I'm not sure what this issue is asking about.
