### ISSUE TITLE
Opening multiple pdfs at once from Explorer does not preserve order

### ISSUE THREAD

**Issue by corwinburdick** [sumatrapdfreader/sumatrapdf#1017]
This is inconsistent with the File->Open method, which preserves order when opening multiple files at once.

**Comment by GitHubRulesOK** [comment]
@kjk a known long term feature of Windows OS
drag **third** of 3.txt files to an editor and they will open in the order 3.txt 1.txt 2.txt (the dragged file is given priority) drag the first file and they will usually open 1.txt 2.txt 3.txt etc
