### ISSUE TITLE
printing dialog with selectable options

### ISSUE THREAD

**Issue by ousia** [sumatrapdfreader/sumatrapdf#102]
I think that SumatraPDF lacks a very important feature for printing: an options dialog.

This dialog should contain the following options (besides the ones that belong to the Windows GDI [adapted from evince]):

* Layout:

    * Two-sided printing (with portrait and landscape rotation]).

    * All/even/odd pages selection print

    * Percent scaling.

* Paper:

    * Paper size.

    * Page orientation.

* Page handling:

    * Page scaling: none, fit to printable area, shrink to printable area.

    * Auto rotate and center.

    * Select page size using document page size (already reported at #97).

**Comment by kjk** [comment]
We use standard printing dialog. We don't have plans to write a custom print dialog.

**Comment by ousia** [comment]
@kjk, I meant advanced options. At least you implemented three page scaling options and one page handling option.

Enabling duplex printing would be an important feature. At least, in any professional environment.

**Comment by kjk** [comment]
I still don't understand.

We use standard printing dialog. If a printer supports duplex printing, then you should be able to select that option by going to printer preferences and selecting appropriate options and sumatra should honor it.

What kind of options are available depends on the printer and its driver.

In other words, if a given option is not available in printer dialog invoked from other windows applications (like notepad), then it won't be available in Sumatra.

Anything more would require writing a custom print dialog, which we do not plan to do.

**Comment by ousia** [comment]
Duplex printing options are part of the PDF specification ([`/Duplex` entry in viewer preferences dictionary](https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=364)).

They are also implemented in extended printing options in Adobe Reader, evince, okular, Foxit Reader (to name some I know of). Of course, it requires a printer capable of duplex printing.

These options are part of the advanced reader such as _Use original page size_. As commented in #11, _Use original page size_ isn’t a real scaling option, but a page handing option.

The same applies to the duplex printing options.

But let’s discuss issue #11 first.

**Comment by RavenLight** [comment]
I've been using SumatraPDF and I can go into the Preferences of my printer and tell it to print two-sided but when it prints it only prints one side, turns the paper over, and leaves the other side blank.  All other programs I print from will print duplex but not Sumatra.  THAT is what ticks me off.  Even stupid Acrobat will print two sided for me and really, this is the only flaw Sumatra has that I have found.  Irritatingly I have a LOT of documents in pdf that need to be printed on both sides though.

**Comment by SnyderFD** [comment]
... as kjk commented Oct 29, 2015, "If a printer supports duplex printing" 
My HL-2270DW does support duplex. 
However,when I looked at the  "Printer Properties" for this printer on Windows 10, the "Installable Options"  "Duplex Unit" was set to "Not Installed"
When I changed the value to "Installed" the option now shows in the Sumatra Preferences Layout.

**Comment by ousia** [comment]
@SnyderFD, could you add a screenshot of the preferences layout you describe?

**Comment by SnyderFD** [comment]
... screen shots of Duplex Unit Installed ...
[DuplexInstalled.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/131459/DuplexInstalled.pdf)

**Comment by ousia** [comment]
@SnyderFD, many thanks for the images.

I see these are the printing dialog from the printer, not from SumatraPDF itself.

**Comment by GitHubRulesOK** [comment]
for commend line users there is a "duplex" entry but may not always be there/work in some versions
e.g. I am not sure if it was available in version 3.0 which is the fallback version for non-image printing.

**Comment by ousia** [comment]
@GitHubRulesOK, many thanks for your reply,

I really don’t get why this will not be implemented when there is a command line option for that (the same happens to me with #98).
