### ISSUE TITLE
Feature request: undo close tab

### ISSUE THREAD

**Issue by jddcef** [sumatrapdfreader/sumatrapdf#1020]
If I have many PDF's open I would like to undo a tab closed by mistake.. especially when it doesn't appear in the Recent files list...

Or just add the recently closed tab to the File menu list of recent files...

**Comment by benryanau** [comment]
History and bookmark/fav management work would be a great improvement!

**Comment by GitHubRulesOK** [comment]
@jkj duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/788

**Comment by kjk** [comment]
Consolidate as #788
