### ISSUE TITLE
choose background image instad color

### ISSUE THREAD

**Issue by liangpu597** [sumatrapdfreader/sumatrapdf#1022]
I want  let the background to a picture instead of a color . Eg: the BackgroundColor = #E0FFFF but i want to set this  :
![timg](https://user-images.githubusercontent.com/23580110/40154717-52696ccc-59c2-11e8-823c-cd558868b9d5.jpg)
How should I do?

**Comment by kjk** [comment]
This is not possible and there are no plans to allow that.
