### ISSUE TITLE
error in page numbr displayed while printing

### ISSUE THREAD

**Issue by swayo** [sumatrapdfreader/sumatrapdf#1024]
if you select to print page 2 of 3 it will still dispaly -in upper left- youre about to print page 1

**Comment by GitHubRulesOK** [comment]
I see "Printing page 1 of 1" e.g it is a  _**count**_ of the number of selected pages

**Comment by swayo** [comment]
yes, yet it can mislead.

**Comment by kjk** [comment]
Closing per suggestion.
