### ISSUE TITLE
Print Document

### ISSUE THREAD

**Issue by maugust85** [sumatrapdfreader/sumatrapdf#1028]
Printing a pdf from menu is ok, but print a file from windows context menu print (right click + print) doest work, the output is diferent.

I use a non stardard paper (70mm x 80 mm) 

Its like use a A4 paper by default, i need use a special paper.

Link to the file i use.
http://ge.tt/4JC7syp2

**Comment by GitHubRulesOK** [comment]
PLEASE PROVIDE A LINK TO A NON VIRAL SITE
unfortunately ge.tt tries to install an infection of java

**Comment by kjk** [comment]
It looks to me that "print from windows context menu" prints using Windows code, not sumatra  code.

Which would explain why the output is different.

But it's not related to Sumatra.

**Comment by GitHubRulesOK** [comment]
@kjk could you please edit https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports.html
to remove the recommendation for ge.tt since it now tries to install java when requesting a download

**Comment by kjk** [comment]
@GitHubRulesOK sure. Do you have a recommendation for a better site for sharing files? I haven't looked at this field recently.

**Comment by GitHubRulesOK** [comment]
no I even personally avoid one drive etc
I would suggest a generic comment to the effect that the submitter needs to ensure the file is posted on a "safe" site (preferably no ads  / download manager especially NOT flash or java based)

**Comment by kjk** [comment]
Describing an ideal website if one does not exist is not a viable approach. If we ask people to share files, we have to tell them what website to use.

**Comment by GitHubRulesOK** [comment]
Dare I suggest Yandex Disk is one popular site (I frequently download from it without problems) though you can get caught out by rouge uploaders :-)

**Comment by GitHubRulesOK** [comment]
Dropbox still has a free (e-mail sign up required) 2 GB service

**Comment by GitHubRulesOK** [comment]
@kjk keeping my comments separate so they can be edited/deleted by either of us

potential 1st option

I presume users registering with github to report an issue can upload troublesome PDF or screenshot as per https://blog.github.com/2015-09-25-attach-files-to-comments/

**Comment by GitHubRulesOK** [comment]
@kjk melded my comments above any use?

**Comment by kjk** [comment]
We need something that allows free/anonymous sharing.

https://files.fm/ looks decent. 

I'll update the recommendation to first mention adding as attachment to github issues and then files.fm.

**Comment by GitHubRulesOK** [comment]
sorry my link dropped whist looking at files/fm/
interesting site with extracts from Quoran and Exclusive Desktop Erotic Shows Software Windows/MacOS X Freeware :-)

its good for anonymity :) however I would be cautious in suggesting it alone

**Comment by maugust85** [comment]
Its sumatra that print a document.

![imagen](https://user-images.githubusercontent.com/31144853/40783929-5d97a584-64ba-11e8-8d78-d114fe83caaf.png)

**Comment by GitHubRulesOK** [comment]
The Icon is from SumatraPDF as that's the default for file opening (reading),
however the Imprimir context is Windows own print handler so the "system default" settings are used
If you always wish the default to be a fixed page size then you need to change default settings for the printer in device and printers

**Comment by SumatraPeter** [comment]
@kjk I generally upload to zippyshare.com if I need to share something quickly, but there's also anonfile.com if you prefer (their file size limit, speed, retention policy etc. are pretty [generous](https://anonfile.com/faq)).

BTW, might it not be better to move all these comments from here to a staff discussion on the forum?

**Comment by GitHubRulesOK** [comment]
Hi Peter
Agreed best as separate thread, but was thought to be related to OP upload
BTW both zippyshare and anonfile want to download shell ui helper extensions or other unwanted paraphernalia hence the cleaner suggestions above

**Comment by GitHubRulesOK** [comment]
most of the non subscription sites depend on redirecting to paid sponsors, some prior to download some during or after
the safest sites offer small free accounts in the hope you will upgrade to paid, most will try to e-mail you with offers, the exception to enforced sign-up at present is Yandex hence very popular in the East
