### ISSUE TITLE
Please help me. When I download the latest version, I use VS2017 to run the wrong report.

### ISSUE THREAD

**Issue by HuangXT** [sumatrapdfreader/sumatrapdf#1031]
Please help me. When I download the latest version（sumatrapdf-master.zip）, I use VS2017 to run the wrong report.My laptop win10 64 bit，When I unzip the file, open vs2017/SumatraPDF.sln, compile and run error.
----------------------------------ERROR-----------------------------------------------------------
Severity code indicates that item file rows are forbidden to display state.
Error MSB8020 could not find the v141_xp generation tool (platform toolset = "v141_xp"). If you want to use the v141_xp generation tool to generate, install the v141_xp generation tool. Or, you can upgrade to the current Visual Studio tool by selecting the "project" menu or right-click the solution, and then selecting the "redefine solution target". Cmapdump D:\Program\VisualStudio2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets 57

I hope you can teach me how to run it, compile those files, and guide me according to your successful compilation. Thank you.

**Comment by kjk** [comment]
Most likely you need to re-run Visual Studio installer and make sure to install XP toolchain component.

**Comment by HuangXT** [comment]
Thanks,I'll try again.

**Comment by HuangXT** [comment]
Today,when i re-run Visual Studio installer and make sure to install XP toolchain component.
----------------------------------ERROR-----------------------------------------------------------
1>------ Build started: Project: synctex, Configuration: Debug x64 ------
2>------ Build started: Project: mupdf, Configuration: Debug x64 ------
1>synctex_parser.c
1>d:\sumatrapdf-master\ext\synctex\synctex_parser.c(715): error C2220: warning treated as error - no 'object' file generated
1>d:\sumatrapdf-master\ext\synctex\synctex_parser.c(715): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>Done building project "synctex.vcxproj" -- FAILED.
2>pdf-write.c
2>d:\sumatrapdf-master\mupdf\source\pdf\pdf-write.c(2075): error C2220: warning treated as error - no 'object' file generated
2>d:\sumatrapdf-master\mupdf\source\pdf\pdf-write.c(2075): warning C4819: The file contains a character that cannot be represented in the current code page (0). Save the file in Unicode format to prevent data loss
2>Done building project "mupdf.vcxproj" -- FAILED.
3>------ Build started: Project: SumatraPDF, Configuration: Debug x64 ------
3>LINK : fatal error LNK1104: cannot open file 'D:\sumatrapdf-master\dbg64\mupdf.lib'
3>Done building project "SumatraPDF.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 16 up-to-date, 0 skipped ==========
How is this going?

**Comment by HuangXT** [comment]
@kjk  Thanks

**Comment by ilsergente1993** [comment]
If someone else gets this error check out here (https://stackoverflow.com/questions/49516896/how-to-install-build-tools-for-v141-xp-for-vc-2017) on how to solve it.
I know it's not a project related problem but since the default installation of VC2017 doesn't include the "Windows XP support for C++" a message to notify this in the readme file would be nice.
