### ISSUE TITLE
cbr files using rar 5.0 not supported

### ISSUE THREAD

**Issue by Tiedexen** [sumatrapdfreader/sumatrapdf#1032]
Hello
I use Sumatra for reading comic files with rar compression (cbr ending). It worked for me until Sumatra version 3+.
Sumatra 2.5.2 reads cbr files fine, Sumatra 3+ does not. (I just check it)
I get the following error:
Error loading filepath/file.cbr

Greetings
tiedexen

**Comment by GitHubRulesOK** [comment]
@Tiedexen 
from https://github.com/sumatrapdfreader/sumatrapdf/blob/95f60d5359232520e69ed82f9c3a3f70a04f66e0/docs/releasenotes.txt 
3.0 (2014-10-18)
* replaced non-free UnRAR with a free RAR extraction library
(if some CBR files fail to open for you, please download unrar.dll from
http://www.rarlab.com/rar_add.htm and place it alongside SumatraPDF.exe)

NOTE the unrar.dll file is currently the fourth entry and downloads an installer intended for developers
you will need to run it to extract its contents to a temporary location  then find the correct one of two "unrar.dll" files  the x32 bit is the one you will see first BUT if you are running SumatraPDF x64 you will need to find and copy the unrar.dll from the x64 directory
once you have copied the file(s) you need you can delete the temporary folder

Once it is working for you, can you please close this issue

**Comment by GitHubRulesOK** [comment]
@kjk 
since there has been no reply to say this did not work, I suggest this issue be closed as potentially addressed ( innocent until re-proven as guilty )

**Comment by kjk** [comment]
I'll keep it. We need to improve things so that people don't have to manually install unrar.dll

**Comment by GitHubRulesOK** [comment]
OK, I thought unrar allows for distribution with other software per the "without limitations" in below license.txt and cant find any restriction on repacking, although it may be polite to include attribution such as license.txt

      The unrar.dll library is freeware. This means:
   1. All copyrights to RAR and the unrar.dll are exclusively
      owned by the author - Alexander Roshal.
   2. The unrar.dll library may be used in any software to handle
      RAR archives without limitations free of charge.
   3. THE RAR ARCHIVER AND THE UNRAR.DLL LIBRARY ARE DISTRIBUTED "AS IS".
      NO WARRANTY OF ANY KIND IS EXPRESSED OR IMPLIED.  YOU USE AT 
      YOUR OWN RISK. THE AUTHOR WILL NOT BE LIABLE FOR DATA LOSS, 
      DAMAGES, LOSS OF PROFITS OR ANY OTHER KIND OF LOSS WHILE USING
      OR MISUSING THIS SOFTWARE.
      Thank you for your interest in RAR and unrar.dll.
                                            Alexander L. Roshal

**Comment by SumatraPeter** [comment]
If a programmer ever decides to improve the current state of affairs, I wonder if it might not be better to ditch the moribund unarr library altogether and instead substitute it with 7-Zip's DLL or relevant extraction code? (7-Zip has been able to extract RAR5 archives for more than 4 years now, since [15.06 beta released in Aug 2015](https://www.7-zip.org/history.txt).)

**Comment by GitHubRulesOK** [comment]
@kjk I can;t be 100% certain but tried latest build on a .cbr supposedly built with recent 5.0
Since the rar engine has just been updated this "reading 5.0" is presumably now covered ?
The issue of dll placement is cover in https://github.com/sumatrapdfreader/sumatrapdf/issues/1116

**Comment by kjk** [comment]
Yes, I've upgraded to latest version of unrar so it should work now.
