### ISSUE TITLE
Can't create executable

### ISSUE THREAD

**Issue by Netherprovinc3** [sumatrapdfreader/sumatrapdf#1036]
I downloaded the zip of the files and then double clicked the solution and so it opened in Visual Studio.  I then select build -> build solution.  The result is 37 fails, 0 success.

I have never compiled any programs from github so I am new to this.  I assume I am making some big mistakes, or obvious mistakes.

**Comment by kjk** [comment]
Sorry, but to compile Sumatra you need to understand the basics.
