### ISSUE TITLE
mupdf now supports OpenGL backend. can sumatrapdf be benefited from that?

### ISSUE THREAD

**Issue by enihcam** [sumatrapdfreader/sumatrapdf#1038]
mupdf now supports OpenGL backend. can sumatrapdf be benefited from that?

http://git.ghostscript.com/?p=mupdf.git;a=commit;h=e9f86e83bf50f5a80847d45ee5f682fb92f35ba1

**Comment by kjk** [comment]
The viewer part of Sumatra's code is all custom so there's nothing to be gotten from this.
