### ISSUE TITLE
Sumatra 3.1.2 - Preview is not working

### ISSUE THREAD

**Issue by omasseau** [sumatrapdfreader/sumatrapdf#1039]
I installed Sumatra 3.1.2 (32-bit) on Windows 10 (64-bit).
The preview of pdf files in File Explorer does not work. I just get the 'This file can't be previewed' error.

I cannot install the 64-bit version as a 32-bit program (XYPlorer) needs to have a 32-bit previewer.

When checking the preview handlers with ShellExView I can see that SumatraPDF Previewer (C:\Program Files (x86)\SumatraPDF\pdfpreview.dll) is correctly associated to pdf files.

**Comment by GitHubRulesOK** [comment]
Only 32bit preview works on 32bit system and 64bit system only works with 64bit preview
@kjk this can be closed as it a known requirement

**Comment by kjk** [comment]
Closing as per above explanation.
