### ISSUE TITLE
rendering problem : converts stroke to path

### ISSUE THREAD

**Issue by Noomene** [sumatrapdfreader/sumatrapdf#104]
I created the attached PDF file using inkscape. The red/green sinusoid in there are strokes and render correctly as strokes in Inkscape. However when I save a PDF copy of the files and view them in sumatra PDF, sumatra viewer somehow converts the stroke of those sinusoids to paths and renders them as paths, which distorts the shape. When I view the same PDF file in PDF-Xchange viewer they render correctly. So I assume this is a problem with sumatra viewer and not with the PDF file or the Inkscape PDF converter.

Attached is the SVG source file, and the PDF file in question.
Used the Sumatra PDF latest version.

![bug](https://cloud.githubusercontent.com/assets/11027939/6210816/b434933c-b5d3-11e4-9548-c0438eb1a5f6.png)

**Comment by kjk** [comment]
Please also share the PDF file somewhere (e.g. http://ge.tt, GitHub doesn't support attaching PDFs to issues)

**Comment by Noomene** [comment]
Sorry I couldn't post it to ge.tt so I posted it to my dropbox and here is the public link :
https://www.dropbox.com/s/c98pc62olttmb31/MW-induced%20tunneling.pdf?dl=0

**Comment by kjk** [comment]
Sumatra renders the pdf the same way as Chrome's built-in PDF viewer and Preview on Mac.

**Comment by Noomene** [comment]
ok, then I guess that solves the issue.

**Comment by ousia** [comment]
@Noomene, might I have the SVG source?

You can add it here, simply replacing the `.svg` extension with the `.png` extension. (It won’t be displayed, but it will be hosted.)

BTW, which inkscape version did you use to generate the PDF file?

**Comment by Noomene** [comment]
Sure. Attached you'll find the SVG source (with a .png extension)
And I used Inkscape version 0.48.4 r9939

![mw-induced tunneling](https://cloud.githubusercontent.com/assets/11027939/6257487/af2f752a-b7c0-11e4-9bb3-3ec75dfaf2ea.png)

**Comment by ousia** [comment]
@Noomene, I use Inkscape 0.91 r13725 (Feb 14 2015).

And inkscape renders the SVG file exactly as evince and mupdf render the PDF file. PDF-Xchange is wrong here.

Or does your inkscape version display the SVG in different way from the way Sumatra displays the PDF file?

**Comment by Noomene** [comment]
My inkscape displays the SVG the same way PDF-Xchange displays the produced PDF file, i.e. the way I intended the image to be, i.e. without the path distortion (cf. attached pictures). But when the same PDF file is opened in sumatra it shows the distortion, i.e. it shows differently from the source SVG in Inkscape and the PDF in PDF-Xchange.

Attached you will find a screenshot of inkscape (png extension), a screenshot of sumatra (png extension), the SVG source (extension modified to png) and the PDF file (extension modified to png)

![sumatra](https://cloud.githubusercontent.com/assets/11027939/6258808/1a7180fc-b7cc-11e4-9576-ebdb9a2f33c5.png)
![inkscape](https://cloud.githubusercontent.com/assets/11027939/6258807/1a6ab1dc-b7cc-11e4-9757-cc2365742e27.png)
![svg source](https://cloud.githubusercontent.com/assets/11027939/6258810/1a78c74a-b7cc-11e4-88df-398a0716a5ca.png)
![pdf file](https://cloud.githubusercontent.com/assets/11027939/6258809/1a75964c-b7cc-11e4-9e93-185a12e394ed.png)

**Comment by kjk** [comment]
And if you open the .svg file in Chrome (drag&drop from filesystem to Chrome), it renders the way Sumatra, Preview and Chrome's PDF viewer does.

So it's not clear which program renders it incorrectly. You can try to create a minimized test case (remove everything other then that the green thing that renders differently) and can either look at .svg source and determine how it should render from that or test with a few more SVG renderers to get a more complete picture.

**Comment by Noomene** [comment]
ok I'll give that a try.
I probably should also add that you can reproduce in inkscape the way sumatra and chrome render that image. You just need to convert the sinusoid (which is a stroke) to a path and you'll get the same effect, in inkscape. That's what initially made me think that maybe chrome and sumatra were doing one extra step before displaying the file. But now I think this might just be an exception.

Anyway thanks for your help.
