### ISSUE TITLE
fit width 

### ISSUE THREAD

**Issue by czghzc** [sumatrapdfreader/sumatrapdf#1042]
In a PDF file with hundreds of pages, only one or two pages may be horizontal, so when using the fit width mode, most of the vertical pages have a lot of blanks on both sides, and the page appears small, and the view is very Strenuous, can you use the fit width mode for each page?

![2018-07-13_093012](https://user-images.githubusercontent.com/23645596/42668051-2c96d7be-8681-11e8-90bf-a033b05c7c6b.png)
![2018-07-13_093325](https://user-images.githubusercontent.com/23645596/42668059-3525688c-8681-11e8-8192-d5df5631bd36.png)

**Comment by kjk** [comment]
This is the same issue as #152 so closing as duplicate
