### ISSUE TITLE
Settings/Advanced Options/MainWindowBackground not changing background color

### ISSUE THREAD

**Issue by Phaewryn** [sumatrapdfreader/sumatrapdf#1044]
In Settings, Advanced Options, MainWindowBackground does not appear to be changing background color anymore. It did in the past, so I am not sure why it's stopped now. Might be a bug, might just be my luck. I am saving, closing the document, and re-opening it, no changes. I have the latest version according to the update dialogue.

**Comment by GitHubRulesOK** [comment]
there are several "backgrounds" historically Main was the first screen with up to 10 frequently  read and was yellow #80ffff00 the paper space background for fixed page and ebook can be white 
	BackgroundColor = #ffffff
the border around the paper is controlled by GradientColors = #f0f0f0

which one is causing problems which version and on what OS system  eg Win 10x64

**Comment by Aidolii** [comment]
Compiling the latest source, this is still an issue. No matter what you change it to, it stays the same, whether or not UseSysColors is enabled.

**Comment by GitHubRulesOK** [comment]
@kjk this was restored some time ago ?
![image](https://user-images.githubusercontent.com/12754913/73135536-3387b000-403b-11ea-907f-00cfbd495190.png)

**Comment by kjk** [comment]
Yeah, should be fixed in latest daily builds https://www.sumatrapdfreader.org/dailybuilds.html
