### ISSUE TITLE
Can I change the color of the left and right margin of sumatra pdf?

### ISSUE THREAD

**Issue by digdig** [sumatrapdfreader/sumatrapdf#1052]
I know I can change background and text color, is there any option in advanced settings to change the color as illustrated below?
![0jelk](https://user-images.githubusercontent.com/5459093/43463975-7dea672c-950c-11e8-8099-10b44febd361.png)

**Comment by SumatraPeter** [comment]
Try setting the _GradientColors_ value ([add the setting](https://www.sumatrapdfreader.org/settings.html) if it doesn't already exist).
