### ISSUE TITLE
Printing issues

### ISSUE THREAD

**Issue by julian-wells** [sumatrapdfreader/sumatrapdf#1058]
Love the program, light & snappy. Unfortunately, I am having a few issues with printing.  Tried 2 documents on 2 different printers, with results varying between morse code to partial characters. In short nothing usable printed. 

The 2 files are attached.

[WP-Q152-QF2-Technical-Overview.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2296866/WP-Q152-QF2-Technical-Overview.pdf)

[Microsoft_Press_eBook_Introducing_Windows_10.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2296862/Microsoft_Press_eBook_Introducing_Windows_10.pdf)

**Comment by GitHubRulesOK** [comment]
@julian-wells 
There are many factors that can be interfering
MyNotes are at https://github.com/GitHubRulesOK/MyNotes/blob/master/AppNotes/Printing%20Issues
see if any of those may be applicable

Which version of SumatraPDF (is it portable or installed) which OS and bitness ?
Versions prior to 3.1 are more likely to cause the issues you describe have you tried pre-release version

Most likely culprit will be print driver have you tried printing to a virtual printer such as pdf, text or xps
I have no problem printing to Microsoft PDF so I should not have a problem with my physical printer
What are printer brands and type are they local usb or networked (wireless/cable)

**Comment by julian-wells** [comment]
All good questions and thanks for the prompt reply. Will update you on Monday.

Cheers,

Julian

**Comment by julian-wells** [comment]
Thanks for your email.

Using your guide, but couldn't find anything obviously wrong.

Currently testing SumatraPDF v.3.1.2 On a desktop with Windows 7 Enterprise 64-bit & printing over a network to a Xerox Work Centre 8855, & a Xerox Phaser 6700DN.

I added it to a laptop with the same OS etc but no sucess.

Guess it is down to the printer drivers or network priniting.

Tried creating a PDF with doPDF v.9.  That looked fine with the slight bug that a landscape PDF in Sumatra PDF came out as portrait PDF (pages turned anti-clockwise).

JW



________________________________

**Comment by GitHubRulesOK** [comment]
There is a new pre-release with a more robust driver handover - worth a try (but beware may not help if the Xerox driver is kernel based) see https://forum.sumatrapdfreader.org/t/sumatrapdf-prerelease-11040/1452/6 (NOTE there is an open issue over installed EXE size so recommend you use the portable version for now)

Xerox at one time were the best for sending native files through their dedicated RIPs, If I remember you could throw the PDF or PS straight at the print queue and cross fingers it came out on the paper.
SumatraPDF is converting the PDF render to windows DIB and then its down to the driver to handle that as if it came from other apps. So one place to try changes is if the driver allows you to have different settings for RAW EMF etc Under printer properties, print processor, my cheap HP has winprint > RAW, FF appended, 4x NT EMF, TEXT, XPS2GDI I would be trying a few of those to check if default RAW was not behaving. If you find a setting that works you can save as a separate  named printer.

**Comment by GitHubRulesOK** [comment]
@kjk unclear description of output effect as being identical to other xerox drivers however I think this is directly related to similar cause in https://github.com/sumatrapdfreader/sumatrapdf/issues/919
