### ISSUE TITLE
Chinese text shouldn't break on <b> etc.

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1059]
`foo<b>bar</b>foo`, if it were cjk text, shouldn't break on `<b>`.
See https://github.com/sumatrapdfreader/sumatrapdf/pull/1057#issuecomment-414105612 for more details.

**Comment by GitHubRulesOK** [comment]
Sorry crossed edit I think this is not a separate issue unless a problem in non CJK

**Comment by ultranity** [comment]
> I think it might be rather subtle/involved and related to how html is parsed and laid out.

there is no space between CJK  words or sentence unlike English, this difference caused the problem when htmlparser try to handle CJK sentences as words since its usually too long to put all of them in one line.

**Comment by kjk** [comment]
should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/158b13ce7bdb4e80cfdc0822336134042fbd26f7
