### ISSUE TITLE
lost high lighting functionality with latest version x.x.11040

### ISSUE THREAD

**Issue by apollo2mond** [sumatrapdfreader/sumatrapdf#1066]
Hi, just to inform you about the lost hight lighting functionality.
I had to go back to x.x.10766 version  from 2017.

thanks, Uwe

**Comment by GitHubRulesOK** [comment]
@kjk this is a known change in function key
 issue is perhaps now history ?

**Comment by kjk** [comment]
Yes, the key for converting selection to higlight changed from 'h' to 'a'. 'h' is now used for vim-style scrolling.
