### ISSUE TITLE
Desktop app Bug: Tracking pad and arrow keys scrolling

### ISSUE THREAD

**Issue by kaustubhharapanahalli** [sumatrapdfreader/sumatrapdf#1068]
In Notion desktop app, using track pad, does not scroll the page up and down, but navigates to different page selection. Same is the case when using arrow keys also even when none of the pages are selected.

I've attached a link for a video recording of what is happening below:
https://drive.google.com/file/d/1daI-eTr9W63Op9CrlA61TK5mMum0SDHJ/view?usp=sharing

**Comment by kjk** [comment]
Wrong product?

**Comment by kaustubhharapanahalli** [comment]
No

**Comment by kaustubhharapanahalli** [comment]
No. This is the link from which I downloaded the desktop app. 

https://www.notion.so/desktop

**Comment by SumatraPeter** [comment]
@kaustubhharapanahalli: Is this just a blatant attempt to spam for a different app? What does Notion's software have to do with Sumatra PDF Reader?
