### ISSUE TITLE
Collate

### ISSUE THREAD

**Issue by scolland** [sumatrapdfreader/sumatrapdf#107]
Can an option for collation be set in the command line print options?

E.g. collateOn or collateOff or similar?

Thanks

**Comment by ousia** [comment]
:+1: 

@scolland, I think this should be part of a proper printing dialog (#102).

**Comment by scolland** [comment]
I'm printing from the command line so there is no dialog.

You can currently pass a good number of options via the command line, the only two that are missing are collate and color/BW

**Comment by ousia** [comment]
@scolland, many thanks for the info.

Not having a print dialog is a shortcoming when opening the file using the GUI (after all, a viewer is a visual program).

**Comment by kjk** [comment]
Sumatra is not meant to be a PDF printer.

**Comment by wengchi0816** [comment]
I have the same problem
