### ISSUE TITLE
Windows resets default pdf application when SumatraPDF is the default app.

### ISSUE THREAD

**Issue by peace2000** [sumatrapdfreader/sumatrapdf#1074]
Hello! I use SumatraPDF as my default tool to open pdf files. However at times Windows changes / resets default pdf opening application when SumatraPDF is the default app. I have to frequently switch it back. This issue exists on several various machines that I upkeep. Also Windows does not reset default pdf app when some else app is the default. So I think that this could be some kind of incompatibility issue with Windows 10 maybe?

**Comment by kjk** [comment]
This is now tracked by #1248

**Comment by SumatraPeter** [comment]
@kjk: Still needs to be closed...
