### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by darkdragon-001** [sumatrapdfreader/sumatrapdf#1077]
SumatraPDF (portable) works out of the box using `wine-mono` (I tried it on Ubuntu 18.04 with `wine` from PPA).

---

I know that [you don't plan to support it officially](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Why-only-Windows%3F), but I would still like to investigate to see how much work is needed. 

I tried to build it with `msbuild` (successor of `xbuild`), but am missing some files:
* `Microsoft.Cpp.Default.props`
* `Microsoft.Cpp.props`
* `Microsoft.Cpp.targets`

These files should be located in `C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120` or similar. I will try to extract them from Visual Studio on Windows and try to build again. I just don't have a Windows machine at hand. If anyone tries it in the meantime, please keep me updated!

Old issues: #17 #109 #260 #314 #792 #856

**Comment by kjk** [comment]
Sorry, I can't help you with building on Linux.

Like you said, you can use regular build with wine so I'm not sure why you need to build it from source.
