### ISSUE TITLE
Ilegible text

### ISSUE THREAD

**Issue by yaagma** [sumatrapdfreader/sumatrapdf#1082]
Hello,

This PDF contains the rules of a board game:
https://app.box.com/s/c3u4rk2dg59jf7fp3b47amu97w0sw8qi/file/35981946406

Look at pages 7, 12, 13, 17. Text is illegible in some paragraphs (even in portable prerelease).

Thanks for this great reader,
Raúl
PS: And please, add a keyboard shortcut to "Show Pages Continuosly" :)

**Comment by GitHubRulesOK** [comment]
That is a corrupt file so contact the owner Jamey Stegmaier and ask him to upload a clean version for offline use
Continuous shortcut varies for each language in English is Alt-V +p     (for pages) !

**Comment by yaagma** [comment]
Ok. Thanks
