### ISSUE TITLE
Freeze on startup if file from previous session missing

### ISSUE THREAD

**Issue by z0id** [sumatrapdfreader/sumatrapdf#1084]
If I delete a document and re-open the app, when trying to restore the previous session the app freezes on startup. The only way to restore functionality is to remove the temp files to reset the app to default. 

Win 10 X86_64, installed using installer.

**Comment by GitHubRulesOK** [comment]
Using installed Win10x64 (with remember files active), by removing a file that was in the remembered list I cannot reproduce this behaviour.
if the file was truly missing it should not freeze it will just store a marker to say the file is missing and drop it from active list and if returned to the same location and reopened it will resume from the stored data but will not be automatically reopened in tabbed sessions. IF there is a corrupt file reference that it keeps trying to open it is possible it may loop on that but should give up after a time, if there is a bad file that keeps it busy it may crash but should not freeze forever. In all such cases deselecting remember files exiting and re-entering should clear the settings file, worst case is having to delete the settings file. If the rogue file is in the temp directory it is good housekeeping to periodically remove those anyway.   @kjk unless you have a crash report ? or can reproduce a freeze by removing referenced files and without further information, I suggest this is not an unusual event for this type of situation.

**Comment by SumatraPeter** [comment]
Have you looked further into the location(s) of the deleted documents, @z0id? Are they on a network drive? Or perhaps on a secondary drive that has powered down and takes a bit too long to spin back up? Could be various reasons why the app's getting stuck waiting for a response (perhaps separate threads if not currently used might mitigate such an issue @kjk?).
