### ISSUE TITLE
Mac / Ios  /Linux support would need assembly code? 

### ISSUE THREAD

**Issue by AnneTheAgile** [sumatrapdfreader/sumatrapdf#109]
hi! Thank you so much for this wonderful product! I need touch screens for useability, it helps my hands , and SumatraPdf works so wonderfully providing the TOC / headers , jump-to's, easy reading, and the fast startup. 

I am starting to try to consolidate my machines and devices. I see there is a substantial amount of assembly code here [1]. So to port it to another OS it would need new assembly is that right? That probably would be beyond me, but I wanted to ask the question and say thank you !
AnneTheAgile

1.[] Project home / Code language / ASM ; X.Search Results ;; https://github.com/sumatrapdfreader/sumatrapdf/search?l=nasm

**Comment by kjk** [comment]
No, this code is from libjpeg-turbo, which already works on mac and linux. The effort would be in porting all the UI code (which is pretty much all the code in Sumatra that doesn't come from external libraries).

**Comment by AnneTheAgile** [comment]
ty @kjk ! OK, I'll continue happily using SumatraPDF in windows and look into reading the code later on.
