### ISSUE TITLE
Feature Request: Click file path in document properties to open its location

### ISSUE THREAD

**Issue by defiler007** [sumatrapdfreader/sumatrapdf#1091]
Hi!

Is it possible to make available a feature to open a file's location in a new explorer window if the user clicks or double clicks the file path in document properties window? (or just to copy the path to the clipboard)

Thanks in advance,
Ippo

**Comment by GitHubRulesOK** [comment]
There was a similar request https://github.com/sumatrapdfreader/sumatrapdf/issues/911 and you may note I recommend using F2 (rename) shortcut to open the source folder in explorer where you can copy the folder name from the address bar, If that one key function is good enough for your needs (potentially less steps than Alt > File> Properties > or even Control D) can you please close this issue

**Comment by GitHubRulesOK** [comment]
@kjk possibly closed by new feature "show in folder" ?

**Comment by kjk** [comment]
Yeah, this should be adequate alternative.
