### ISSUE TITLE
Bookmark page has wrong color

### ISSUE THREAD

**Issue by juanjosegarciaripoll** [sumatrapdfreader/sumatrapdf#1095]
I have tried changing the main window background, the UI background and reverting to system colors, but on Windows it seems that SumatraPDF refuses to change the background of the bookmarks / index
![captura](https://user-images.githubusercontent.com/2188286/48311562-c60c7280-e5a1-11e8-9358-38bd7111dc8c.PNG)

**Comment by GitHubRulesOK** [comment]
Yes it is always a fixed value (should be white but see problems when it goes black https://github.com/sumatrapdfreader/sumatrapdf/issues/655 it can work with sys colours see my screenshot in https://github.com/sumatrapdfreader/sumatrapdf/issues/787#issuecomment-397837009) there are numerous locations in the code where that is dynamically reset so would be laborious
 to simply replace with one variable but if you are compiling your own copy you could possibly add a new variable to  be reapplied in each piece of code.

**Comment by GitHubRulesOK** [comment]
@kjk now resolved in recent builds
@juanjosegarciaripoll please try a **portable [daily build](https://www.sumatrapdfreader.org/dailybuilds.html)** to see how this is intended to work in the next version

**Comment by kjk** [comment]
This should be fixed.
