### ISSUE TITLE
Inverse search: column number is not filled correctly

### ISSUE THREAD

**Issue by nadya-p** [sumatrapdfreader/sumatrapdf#1098]
I'm setting up an inverse search from SumatraPDF to a LaTeX source code editor via a python script. I specify in Settings -> Options -> Set inverse search common-line:
````connect_to_nvim.py "%f" %l %c````
While debugging this integration, I output the value returned by `%c` into a text file, and obtain a 
MAX_INT (4294967295), no matter the position of the cursor.

Note that without `%c` the integration works correctly.

**Comment by nadya-p** [comment]
This happens even on a [minimalistic pdf file](https://github.com/sumatrapdfreader/sumatrapdf/files/2595966/test.pdf)
produced from the following LaTeX source:
```
\documentclass{article}
\begin{document}
abc

abc

abc
\end{document}
```

**Comment by GitHubRulesOK** [comment]
%c is a maximum value as you have discovered (it was left exposed but not implemented), some syctex code has changed since then and some other apps implementations support hinting, however that is not the case with SumatraPDF only "%f" and %l are useful  the only current use for %c is as a check value if the other two are suspect.

**Comment by GitHubRulesOK** [comment]
@kjk this is a limitation known from the outset of synctex implimentation in most PDF viewers i.e I dont think AdobeReader Evince or Ocular ever used such a variable, It was intended for future enhancement but I understand that method of  position along a line was considered "too variable" to set thus simply left at the max.

**Comment by GitHubRulesOK** [comment]
As this issue is totally dependent on any enhancement to synctex update (and even then %c could require some black ops to work at all ) I am consolidating as potentially covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/841
