### ISSUE TITLE
msi installer

### ISSUE THREAD

**Issue by zippydan** [sumatrapdfreader/sumatrapdf#1099]
I see that you've considered and dismissed the possibility of creating an MSI-based installer at least twice previously, 

http://forums.fofou.org/sumatrapdf/topic?id=3863
http://forums.fofou.org/sumatrapdf/topic?id=3184028

but I'd just like to bring to your attention that OpenVPN, for example, has decided to transition to MSI from NSIS because of security risks with NSIS:

https://community.openvpn.net/openvpn/wiki/NSISBug1125

**Comment by GitHubRulesOK** [comment]
@kjk correct me if I'm wrong but I see no component from NSIS (only historic references to 3rd party documentation and 7zip handle ) Nor any relationship with OVPN at all in SumatraPDF so this issue can be deleted or closed

**Comment by kjk** [comment]
Yeah, we don't use nsis but a  custom written installer.

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: I think @zippydan mentioned NSIS only because that first thread has Krzysztof saying how he prefers it since it "does a good job".

@kjk: For future reference, with which version of Sumatra did you transition from NSIS to your custom installer?

**Comment by GitHubRulesOK** [comment]
@SumatraPeter I think it was early 2011 for 1.3
https://blog.kowalczyk.info/article/8nqb/writing-a-custom-installer-for-windows-software.html
