### ISSUE TITLE
File selection window maximized

### ISSUE THREAD

**Issue by rbaeck** [sumatrapdfreader/sumatrapdf#1100]
The file selection window (for rename) got maximized (probably by erronous click).
File selection for Open and SaveAs are maximized as well.
The window cannot be resized.

Its with Sumatra 3.1.2 (32bit) and Windows 10/1809 (64bit).
Deinstall and reinstall does not help-

**Comment by rbaeck** [comment]
Yes double-clicking does it, thank you. Sorry I didn'tr try it.
System menu did not work because the restore item was grayed out.

**Comment by SumatraPeter** [comment]
You're welcome. Please close the issue if it's resolved.
