### ISSUE TITLE
Update window DPI when drag from 1080p monitor to 4k monitor.

### ISSUE THREAD

**Issue by liziwl** [sumatrapdfreader/sumatrapdf#1101]
When the main monitor is 1080p, drag the window to the 4k monitor.
The window looks blurry in the 4k monitor.

**Comment by kjk** [comment]
Yes, this is a known problem.
We would have to relayout with new DPI when windows is dragged between screens with different DPIs. Unfortunately it's a lot of work and I don't have a 2 monitor setup for testing.

**Comment by liziwl** [comment]
Update some detailed info.
Text scaling
1080P 100%
4K 200%

**Bad screenshot in 4K**
![bl](https://user-images.githubusercontent.com/23000702/49574216-d9311900-f97a-11e8-974a-1a82976fbb6b.png)

**Good screenshot in 4K**
![gl](https://user-images.githubusercontent.com/23000702/49574224-dd5d3680-f97a-11e8-9ed8-4a5e755bd1ec.png)

**Comment by GitHubRulesOK** [comment]
closing as duplicated by https://github.com/sumatrapdfreader/sumatrapdf/issues/1636#
