### ISSUE TITLE
Why the FontName and FontSize in umatraPDF-settings.txt do not work for txt document? 

### ISSUE THREAD

**Issue by major999** [sumatrapdfreader/sumatrapdf#1104]
Why the FontName and FontSize in umatraPDF-settings.txt do not work for txt document? but they work on 

epub and mobi etc. or there was something wrong that I did.

the following things is all my umatraPDF-settings.txt, please give me a help.

# For documentation, see http://www.sumatrapdfreader.org/settings3.2.html

MainWindowBackground = #80fff200
EscToExit = true
ReuseInstance = true
UseSysColors = false
RestoreSession = true

FixedPageUI [
	TextColor = #333333
	BackgroundColor = #dfd8be
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	FontName = Microsoft YaHei
	FontSize = 9
]
EbookUI [
	FontName = Microsoft YaHei
	FontSize = 9
	TextColor = #333333
	BackgroundColor = #dfd8be
	UseFixedPageUI = true
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]
ExternalViewers [
]
ShowMenubar = true
ReloadModifiedDocuments = false
FullPathInTitle = false
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 

4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
CustomScreenDPI = 0

RememberStatePerDocument = true
UiLanguage = en
ShowToolbar = true
ShowFavorites = false
AssociateSilently = false
CheckForUpdates = false
RememberOpenedFiles = true
EnableTeXEnhancements = false
DefaultDisplayMode = automatic
DefaultZoom = fit width
WindowState = 2
WindowPos = 355 0 593 768
ShowToc = true
SidebarDx = 150
TocDy = 0
ShowStartPage = true
UseTabs = true

SessionData [
]
TimeOfLastUpdateCheck = 0 0
OpenCountWeek = 413

# Settings after this line have not been recognized by the current version

**Comment by kjk** [comment]
Sumatra doesn't support text files so I don't understand the question.

**Comment by major999** [comment]
The Sumatra doesn't support text files,then why it can open text files? and there is a text files option in supported documents list.

<img src="https://i.loli.net/2018/12/07/5c0a52b60f9c9.png" alt="BaiduShurufa_2018-12-7_18-56-12.png" title="BaiduShurufa_2018-12-7_18-56-12.png" />

**Comment by kjk** [comment]
Oh, this is only available when you set `UseFixedPageUI = true`

The settings:
```
EbookUI [
    FontName = Microsoft YaHei
    FontSize = 9
```
are still respected but they are not applied immediately i.e. you have to reopen text document for font changes to take effect.

**Comment by major999** [comment]
Thank you!
