### ISSUE TITLE
libjpeg-turbo pretty old

### ISSUE THREAD

**Issue by mkver** [sumatrapdfreader/sumatrapdf#1105]
Helo,

first, let me thank you for investing your time in SumatraPDF. Much appreciated.

Second, I have just noticed that the libjpeg-turbo code is pretty old: SumatraPDF is still on 1.3.1, although the new version is 2.0.1. I just made a quick test with the djpeg.exe (the executables of libjpeg-turbo for decoding) and it seems that 2.0.1 is about 5% faster than 1.3.1 when decoding jpeg's with arithmetic encoding (normal jpeg's are offloaded to something else (maybe even hardware accelerated) if I am not mistaken?). I don't see a reason to forego on such an improvement, even when it might only be little.

Greetings
mkver/Andreas

**Comment by kjk** [comment]
Updated to latest libjpeg-turbo recently.
