### ISSUE TITLE
open multiple pdf files: XP

### ISSUE THREAD

**Issue by uwerohn** [sumatrapdfreader/sumatrapdf#1108]
v3.1 stable will do; even latest prelease won't(crash message, but it did probably render already). All default settings, nothing changed or added via ini or so. BUT if there is an OPEN suma-window and using click on more than 1 highlightend files in explorer (you don't have to drag) it works.
Best regards uwe

**Comment by GitHubRulesOK** [comment]
@kjk 
I am closing this issue since XP is no longer supported with current builds
Last XP version is 3.1.2 available from https://www.sumatrapdfreader.org/download-prev.html
