### ISSUE TITLE
Can't print to network printer

### ISSUE THREAD

**Issue by Janosch123** [sumatrapdfreader/sumatrapdf#111]
At home and in our office we're using CUPS (running under Debian, if that matters) to share our printers on the network.

Unfortunately, SumatraPDF isn't able to print to these printers. The windows printing icon shows, but the printing task never reaches the CUPS queue.

Printing on PDFCreator's printer works.

With this fixed, I could finally get rid of other programs...

**Comment by kjk** [comment]
Is this on command line or from UI?

If from command line, how are you invoking it?

Are other programs on the same machine able to print to that printer?

**Comment by gegu** [comment]
This problem can be fixed changing the call to CreateDC function in Print.cpp
```
// cf. http://blogs.msdn.com/b/oldnewthing/archive/2012/11/09/10367057.aspx
//ScopeHDC hdc(CreateDC(pd.driverName, pd.printerName, pd.portName, pd.devMode));
ScopeHDC hdc(CreateDC(nullptr, pd.printerName, nullptr, pd.devMode));
```
see: https://msdn.microsoft.com/en-us/library/windows/desktop/dd183490%28v=vs.85%29.aspx

If CreateDC() is callled for printing, it's recommended to pass NULL as the 1st (pszDriver ) and 3rd (lpszOutput) parameter.

The doc says the parameters are ignored, but IMO they are NOT.

**Comment by kjk** [comment]
Thanks for the tip, let's hope this will fix the problem for others as well.
