### ISSUE TITLE
Have global hotkeys

### ISSUE THREAD

**Issue by TheGoddessInari** [sumatrapdfreader/sumatrapdf#1110]
It'd be nice if SumatraPDF could enable global hotkeys, at least for changing the page.

Using autohotkey for this isn't all that great as a bunch of games and such will ban even if you're using it for something entirely unrelated.

It'd simply be nice for multitasking/multi-monitor use, as any other solution can result in spurious account flagging.

**Comment by GitHubRulesOK** [comment]
Apps like SumatraPDF generally define local hotkeys and usually follow or do not modify global hotkeys. Global hotkeys are system wide and usually controlled by hardware or a secondary app outside SumatraPDF. 

AutoHotKey is one of many such Global re-mappers and as you point out many apps may search for such interference with the system global hotkeys. Thus it would not be in SumatraPDFs interest to expose yet another vector that could be abused. At best it would raise False Positive Antivirus Alerts much as AHK is subject to.
By far the simples way to change hotkeys on a per app or global basis is to use any system programmable keys available via your keyboard or mouse or use another injector such as xmouse.

**Comment by TheGoddessInari** [comment]
It's not so much that things care about the hotkeys but the macro capability. Already added some code on my local copy to deal with this, just not integrated with configuration.

A keyboard, mouse, or xmouse can't take a specific keypress and direct it to a specific destination window.

 It's not so much that overaggressive anticheat and similar programs care about hotkeys, but about being able to send arbitrary input in automation to their process. Registering a user-specifiable global hotkey via the Win32 API is harmless, a great many media apps do it, and wouldn't be subject to antivirus false positives anymore than any other program.

**Comment by GitHubRulesOK** [comment]
programmable hardware keys or global shortcuts can be set to send a string so with reuse instance SumatraPDF can go to page zoom scroll etc (all the command line interface actions) the reason I mentioned [x-mouse](https://www.highrez.co.uk/downloads/xmousebuttoncontrol.htm) is it can be confined to mapping on a per app basis.

**Comment by TheGoddessInari** [comment]
You can't really "send a string", but you can send a key combo, such as those registered to a global hotkey. :)

**Comment by rothleer** [comment]
Maybe you can try to use Microsoft PowerToys. It can remap hotkey for the only sumatraPDF without affecting other programs.

**Comment by kjk** [comment]
I assume "global hotkeys" means: keyboard shortcut that does something in Sumatra even when Sumatra's window is not the active window.

That is outside of scope of Sumatra.

Also, if there is more than one window, which window should process the key?
