### ISSUE TITLE
When the file name contains a space, the file cannot be opened.

### ISSUE THREAD

**Issue by dyfloveslife** [sumatrapdfreader/sumatrapdf#1112]
For example, there is now a **1 2.pdf** file (Note: there is a space between 1 and 2), When I open with sumatrapdf, it prompts me **Error loading C:\Users\xxx\Desktop\2.pdf**
version:3.1.2 64-bit

**Comment by kjk** [comment]
How are you opening the file? File/Open, drag&drop, something else?

**Comment by dyfloveslife** [comment]
File/Open can open the file, if you right click and select to open with sumatrapdf, this will not open the file.

**Comment by dyfloveslife** [comment]
In addition, it needs to make sure there are no spaces in the entire path to open the file.

**Comment by GitHubRulesOK** [comment]
This is a Standard windows requirement
If calling SumatraPDF from say a python script you need to enclose spaced paths in quotes such as

"C:\…..\Sumatrapdf.exe" "C:\Users\xxx\Desktop\1 2.pdf"

**Comment by GitHubRulesOK** [comment]
If SumatraPDF was installed with installer by default windows will wrap the file when you right click with the necessary quotes. So IF that is not your case you must have interference by either a shortcut or context handler that needs to be set to follow windows convention

**Comment by dyfloveslife** [comment]
![image](https://user-images.githubusercontent.com/22425377/50446428-ddd06800-094f-11e9-9f50-83ef9bfa6499.png)
Thank you very much, it seems that this is related to my previous modification of the registry  ：）

**Comment by GitHubRulesOK** [comment]
That is an unusual location for open with since * means all files. If that is your intent then try
E:\SumatraPDF\SumatraPDF "%1" as only the filename will need to be quoted

**Comment by dyfloveslife** [comment]
Thank you very much, my question has been solved. ：）

GitHubRulesOK <notifications@github.com> 于2018年12月26日周三 下午10:01写道：
