### ISSUE TITLE
text with subscript copied with additional space or newline in sumatrapdf

### ISSUE THREAD

**Issue by simonnier** [sumatrapdfreader/sumatrapdf#1113]
Dear developers,

I found some copy issue that is quite annoying in sumatrapdf.

For example, this pdf https://arxiv.org/pdf/1812.10118

If you copy the title of the paper in sumatrapdf, the chemical fomula will become like this

> Doping evolution of the gap structure and spin-fluctuation pairing
> in Ba(Fe
> 1−x
> Co x ) 2 As 2 superconductors
> 

There are additional space and newline which is not intended.

However, pdf xchange editor has no such problem, it copies like

> Doping evolution of the gap structure and spin-fluctuation pairing 
> in Ba(Fe1−xCox)2As2 superconductors 

And this is the correct format it should be. 

Hope this bug can be fixed soon.

best regards!

**Comment by GitHubRulesOK** [comment]
@kjk resolved in pre-release cycle
 clipboard content is now identical

![image](https://user-images.githubusercontent.com/12754913/73610289-980fb580-45cd-11ea-83ce-71c8f92e3268.png)
