### ISSUE TITLE
SumatraPDF for MacOS

### ISSUE THREAD

**Issue by Hochiss** [sumatrapdfreader/sumatrapdf#1115]
I have been using SumatraPDF since I used LaTex to write my PHD thesis ~10 years ago. I like this concise and powerful yet small&fast PDF reader so much!

I wonder if it is possible to have a MacOS Version? That will beat all the other PDF reader with huge installation package.

**Comment by kjk** [comment]
No plans for mac version. See https://www.sumatrapdfreader.org/docs/Why-only-Windows.html
