### ISSUE TITLE
Wrong visualization for a PDF 

### ISSUE THREAD

**Issue by mbonny** [sumatrapdfreader/sumatrapdf#112]
This file: http://www.alternativacivicacaino.it/files/2015-02-25-assemblea_pubblica.pdf can be viewed correctly by any reader except sumatrapdf.

**Comment by ousia** [comment]
@mbonny, as a general rule it helps to provide an image of the wrong display.

I attach two images from your file displayed with two different viewers. evince-3.10 and mupdf-1.6 display the file right.

Wrong display with pdf.js-1.0.1185:

![with pdf.js](https://cloud.githubusercontent.com/assets/203767/6542723/8700c820-c502-11e4-8126-76e866403102.png)

Wrong display with SumatraPDF-3.0 and wine on Linux:

![screenshot from 2015-03-07 19 52 04](https://cloud.githubusercontent.com/assets/203767/6542750/b035ff70-c503-11e4-9c47-f8993e4d84eb.png)

Could you confirm whether last image matches the display on your computer?

**Comment by mbonny** [comment]
Sorry, you're right.
It's the second one. Windows 7 SP1 64bit. Sumatra PDF 3.0
Correct on 
Chrome PDF Viewer 40
pdf-xchange 2.5
pdf architect 1.0
Thanks

**Comment by gschenck** [comment]
It displays ok in latatest pre-release (http://www.sumatrapdfreader.org/prerelease.html) (win 7)
![zwischenablage01](https://cloud.githubusercontent.com/assets/2298241/6770803/0cd2f28c-d0cc-11e4-9474-8eb71b1f520d.jpg)

**Comment by kjk** [comment]
Thanks again @gschenck, closing as fixed.

**Comment by mbonny** [comment]
Now it's perfect. Thank you @gschenck !
