### ISSUE TITLE
Use CMake instead of premake for the build system

### ISSUE THREAD

**Issue by svaningelgem** [sumatrapdfreader/sumatrapdf#1122]
I changed in this patch the premake build system to a cmake build system:

[0001-Added-CMake-files.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/2752528/0001-Added-CMake-files.zip)

It's easy to add an installer/uninstaller to it as well.
Plus, it's unix-ready out-of-the-box. But before going to unix, I would strongly suggest using wxWidgets or such for your controls. It's much easier to port then to other OS's.

**Comment by kjk** [comment]
Thanks.

I don't plan to switch from premake to cmake because I know premake better and it's already working.

It could be a second build system but I'm also skeptical of short-lived contributions. This would have to be maintained in the future.

**Comment by svaningelgem** [comment]
If there would be a trigger to receive a notification on the premake* files in the root, or the vs2017 directory, I'm willing to maintain this (as that won't take too much efforts).

**Comment by thorade** [comment]
The notification part could probably be done using a CODEOWNERS file:
https://help.github.com/en/articles/about-code-owners

**Comment by kjk** [comment]
Closing this. It would require commited maintainer and submitting changes via pull requests.

**Comment by GitHubRulesOK** [comment]
@kjk 
out of interest I tried abysmally to follow "the idiots guide to build" instructions
however I somehow did manage to get build ALL to prodice a slew of working exes
What I did notice was that after struggling to get over the initial premake stage that there appeared to be a working copy of premake in the Master download thus I could have avoided that challenge ?

**Comment by kjk** [comment]
If all you need is to build the code, you need to download Visual Studio 2019, open `vs2019/SumatraPDF.sln` and hit `F5`. That's it and it's documented in https://github.com/sumatrapdfreader/sumatrapdf/blob/master/readme.md

You only need to deal with premake when you make changes to the code that involve adding or removing source files.
