### ISSUE TITLE
Huge font on editable fields on some PDFs

### ISSUE THREAD

**Issue by matejdro** [sumatrapdfreader/sumatrapdf#1123]
With this PDF: [test_buggy_pdf.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2752941/test_buggy_pdf.pdf)

Sumatra reader v3.1.2 64-bit on Windows will display huge fonts in the "Other Proficiencies & Languages" field and in "Equipment" fields on the bottom left of the first page, making it practically unreadable, since field can display couple of letters at best:

![image](https://user-images.githubusercontent.com/507922/51083618-8be45c00-171d-11e9-8554-69e6ed21a89e.png)

On pretty much every other PDF reader I tested, this works fine. For example this is how Chrome displays it:

![image](https://user-images.githubusercontent.com/507922/51083626-a4ed0d00-171d-11e9-95f3-9e8b2b732259.png)

(I think the blue tint in Chrome is there because field is editable. It disappears when attempting to print the document)

**Comment by GitHubRulesOK** [comment]
@kjk another for closure with next release

![Untitled1123](https://user-images.githubusercontent.com/12754913/68909516-74636e80-0746-11ea-9899-bd08a14c8fd6.png)

**Comment by kjk** [comment]
Thanks for verifying @GitHubRulesOK 
This is now fixed in latest build https://www.sumatrapdfreader.org/dailybuilds.html
