### ISSUE TITLE
display more than 10 books in menu

### ISSUE THREAD

**Issue by Kristinita** [sumatrapdfreader/sumatrapdf#1124]
### 1. Summary

It would be nice, if would be possible increase the value of books that appear in the menu.

![10 books](https://discourse-sumatra-backup.s3.amazonaws.com/original/1X/9da97ebb0b53b5efd32e1b3e4dca6e8422bee57b.png)

### 2. Details

See my [**SumatraPDF forum post**](https://forum.sumatrapdfreader.org/t/question-settings-display-more-than-10-books-in-menu/1401?u=kristinita).

### 3. Not helped

As [**GitHubRulesOK say**](https://forum.sumatrapdfreader.org/t/question-settings-display-more-than-10-books-in-menu/1401/2?u=kristinita), I can use numerous favorites books, but this is not exactly what I need. It would be nice, if would be possible increase number of last books, that I view, not favorites.

Thanks.

**Comment by kjk** [comment]
You can now get a list of all files in [Command Palette](https://www.sumatrapdfreader.org/docs/Command-Palette) (`Ctrl + K`). I thinks it's an acceptable solution to the same problem.
