### ISSUE TITLE
Copying characters from PDFs is off by one

### ISSUE THREAD

**Issue by Bolpat** [sumatrapdfreader/sumatrapdf#1127]
When I try to copy the text in this [Example.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2824876/Example.pdf), the characters are off by one: a becomes b, b becomes c, ..., y becomes z, z becomes A, A becomes B, ..., Z becomes a again. A bit hilarious.

**Comment by coolsurfer** [comment]
This is what happens when using Adobe Reader. So there seems to be an issue with the PDF ?

```
𝑎𝑏𝑐𝑑𝑒𝑓 𝑔ℎ𝑖𝑗𝑘𝑙𝑚𝑛𝑜𝑝𝑞𝑟𝑠𝑡𝑢𝑣𝑤𝑥𝑦𝑧
𝐴𝐵𝐶𝐷𝐸𝐹 𝐺𝐻 𝐼 𝐽 𝐾 𝐿𝑀𝑁 𝑂𝑃𝑄𝑅𝑆𝑇 𝑈 𝑉 𝑊 𝑋 𝑌 𝑍
```

**Comment by GitHubRulesOK** [comment]
@kjk as seen elswhere there are current difficulties with chacter selection in current builds , however as @coolsurfer has checked the problem with this file is there are extra embeded spaces thus SumatraPDF is extracting the characters as embeded by the author or their application.

![Untitled](https://user-images.githubusercontent.com/12754913/69263756-da744980-0bbd-11ea-830a-ed5a062c3bf5.png)

**Comment by GitHubRulesOK** [comment]
Working fine in current pre-release
![image](https://user-images.githubusercontent.com/12754913/86523141-d866ae80-be5f-11ea-82ce-12c2cea1a719.png)
