### ISSUE TITLE
It is recommended to add multi-page merge printing function

### ISSUE THREAD

**Issue by Antecer** [sumatrapdfreader/sumatrapdf#1128]
![image](https://user-images.githubusercontent.com/8684916/52546349-5eaccb80-2df9-11e9-9766-8da04ca5f9ec.png)

As shown, this is the Gaaiho Reader print preview page, which looks very intuitive and convenient.

**Comment by GitHubRulesOK** [comment]
Every Printer has a different interface here is a nice uncluttered page from a HP driver
SumatraPDF primarily sends the selected Print Area or Page range to Windows 
It is Windows Print Drivers that then layout the pages not SumatraPDF.
![image](https://user-images.githubusercontent.com/12754913/75610711-7e4d8980-5b0b-11ea-8f0e-0b2baf030aa2.png)
