### ISSUE TITLE
Typo in wiki page

### ISSUE THREAD

**Issue by Chocobo1** [sumatrapdfreader/sumatrapdf#113]
In this paragraph:
[Getting the sources and compiling](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Contribute-code#getting-the-sources-and-compiling)
We try to standardize on one, latest publicly available version. Currently we're using `20013` Update 4. Other versions might work but we don't test with them.

`20013` should be `2013`

I'm not comfort changing this directly and note that the wiki is currently set to public...

**Comment by kjk** [comment]
Fixed, thanks for letting us know.
