### ISSUE TITLE
Some questions about the document properties

### ISSUE THREAD

**Issue by yyt6801** [sumatrapdfreader/sumatrapdf#1133]
When I opened the document properties, some error occurred.Only a black box,  is there something upexpected?

**Comment by GitHubRulesOK** [comment]
Personally across at least 100 version/variants never seen that one, yes its totally odd so first question is which version 3.1.2 ? second which variant, x64 portable ? where obtained, main site download page ? what OS win 10 x64 ? does it always happen or only some file locations ?

**Comment by yyt6801** [comment]
By rerun in another environments, I found that the problem does not appear, finally I put the setting file deletion, solved this problem . Maybe because I changed the setting  file before.

**Comment by IvarSnaaijer** [comment]
check the MainWindowBackground setting, changed it to #80000000 and the problem went away.
