### ISSUE TITLE
bookmark align right

### ISSUE THREAD

**Issue by jam-luo** [sumatrapdfreader/sumatrapdf#1138]
![Uploading 图片.png…]()
[C波段波导缝隙阵列天线的分析与设计.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3001301/C.pdf)
@kjk  I uploda the PDF file witch align bookmarks right, maby you can find out the way to correct this phenomenon.

**Comment by jam-luo** [comment]
![012](https://user-images.githubusercontent.com/48012723/53403402-8f425700-39ee-11e9-8dd3-226ce25ac2d1.PNG)
this pic show the issue

**Comment by GitHubRulesOK** [comment]
@jam-luo
I am not the developer however have never seen bookmarks like that before although opening thousands of files with bookmarks, so I have to presume the author thought it would be a good idea to go against convention and in the editor set the bookmark to R2L (I have no idea how you could correct that other than using full adobe acrobat or another pdf tool) I tried changing all possible R2L user settings in SumatraPDF without any effect. I guess you would need to add a control into the core code to be able to override that behaviour

@kjk have you any idea, if this is controlable ?

**Comment by kjk** [comment]
First: which version of Sumatra is this?

We do support RTL but it should only apply to languages marked as RTL in https://github.com/sumatrapdfreader/sumatrapdf/blob/master/scripts/trans_langs.py#L26 (see RTL at the end of the list) but it should apply to everything i.e. either everything is RTL or nothing is.

This is the first time someone reports only one part of the UI is RTL and I can't see how this could happen.

The relevant code is here: https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/SumatraPDF.cpp#L560

hwndFavTree is hwnd for the tree control that shows the favorouties. If you have ability to recompile the code and poke in there, that's the place to look.

**Comment by jam-luo** [comment]
> 
> 
> @jam-luo
> I am not the developer however have never seen bookmarks like that before although opening thousands of files with bookmarks, so I have to presume the author thought it would be a good idea to go against convention and in the editor set the bookmark to R2L (I have no idea how you could correct that other than using full adobe acrobat or another pdf tool) I tried changing all possible R2L user settings in SumatraPDF without any effect. I guess you would need to add a control into the core code to be able to override that behaviour
> 
> @kjk have you any idea, if this is controlable ?

Thanks for your replay, I have  tried to open the file in  adobe acrobat, the book marks of this file is aligened left in adobe acrobat. Till now, I did't find out any way to solve this problem, but that is no matter. I belive sumatra pdf will do better, and I will use this masterpiece than adobe acrobat.

**Comment by jam-luo** [comment]
> 
> 
> First: which version of Sumatra is this?
> 
> We do support RTL but it should only apply to languages marked as RTL in https://github.com/sumatrapdfreader/sumatrapdf/blob/master/scripts/trans_langs.py#L26 (see RTL at the end of the list) but it should apply to everything i.e. either everything is RTL or nothing is.
> 
> This is the first time someone reports only one part of the UI is RTL and I can't see how this could happen.
> 
> The relevant code is here: https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/SumatraPDF.cpp#L560
> 
> hwndFavTree is hwnd for the tree control that shows the favorouties. If you have ability to recompile the code and poke in there, that's the place to look.

Thanks for your reply, the version of sumatra pdf is 3.1.2(64-bit), and i didn't good at coding, if you want more detail about this problem, I Am happy to send this PDF file to your email address.

**Comment by TamirEvan** [comment]
@kjk 
> First: which version of Sumatra is this?
> 
> We do support RTL but it should only apply to languages marked as RTL in https://github.com/sumatrapdfreader/sumatrapdf/blob/master/scripts/trans_langs.py#L26 (see RTL at the end of the list) but it should apply to everything i.e. either everything is RTL or nothing is.

Actually that is not - strictly speaking - true.

> This is the first time someone reports only one part of the UI is RTL and I can't see how this could happen.
> 
> The relevant code is here: https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/SumatraPDF.cpp#L560
> 
> hwndFavTree is hwnd for the tree control that shows the favorouties. If you have ability to recompile the code and poke in there, that's the place to look.

Actually, the relevant code is [a few lines before](https://github.com/sumatrapdfreader/sumatrapdf/blob/61eb8a2b427531a2e4c026c2cfefa00987d1ebf7/src/SumatraPDF.cpp#L556), where the direction for the table of contents (which is labeled "Bookmarks") is globally set.

The direction for the table of contents is also set in [src/TableOfContents.cpp:434](https://github.com/sumatrapdfreader/sumatrapdf/blob/61eb8a2b427531a2e4c026c2cfefa00987d1ebf7/src/TableOfContents.cpp#L434). There, the direction is determined by comparing the count of RTL characters in the table of contents to the count of LTR characters.

Investigating this issue further, I found that the submitted PDF file has, in it's table of contents, only 4 characters counted as LTR, but 57 characters counted as RTL. All of those RTL characters are Unicode 0xFEFF (the BOM or ZWNBSP character), which is at the end of [the list of RTL characters](https://github.com/sumatrapdfreader/sumatrapdf/blob/61eb8a2b427531a2e4c026c2cfefa00987d1ebf7/src/TableOfContents.cpp#L393), but isn't really an RTL character.

[Removing 0xFEFF from the RTL list](https://github.com/TamirEvan/sumatrapdf/commit/e44db1699c866f35e7c46cd758f732f4a9a51459), aligns the table of contents ("Bookmarks") to the left:
![SumatraPDF-issue1138-fix](https://user-images.githubusercontent.com/1873062/56479258-268ecc80-64bd-11e9-8f7d-7c26d2636ba0.PNG)

@jam-luo 
If you want to try out my fix, you can download the [32-bit binary](https://ci.appveyor.com/api/projects/TamirEvan/sumatrapdf/artifacts/rel/SumatraPDF.exe?branch=issue-1138-fix), or the [64-bit version](https://ci.appveyor.com/api/projects/TamirEvan/sumatrapdf/artifacts/rel64/SumatraPDF.exe?branch=issue-1138-fix) if you prefer.

**Comment by kjk** [comment]
@TamirEvan excellent analysis. I hope you don't mind that I merged this fix into Sumatra.

**Comment by kjk** [comment]
@jam-luo This should be fixed in pre-release version: https://www.sumatrapdfreader.org/prerelease.html

**Comment by jam-luo** [comment]
Thanks, may you have a good day！ @TamirEvan @kjk
