### ISSUE TITLE
PDF preview panel misses focus

### ISSUE THREAD

**Issue by bwadrochit** [sumatrapdfreader/sumatrapdf#114]
In windows explorer, the PDF preview never gets mouse or keyboard focus. Thus the only way to navigate through the pdf is to use the provided button on the bottom left, using the arrow keys or the mouse wheel always affects the left explorer panel.
In Outlook, the behavior is more erratic : the PDF preview panel get the focus some times (allowing to navigate using the arrow keys and the mouse wheel), but it remains unstable.

Fixing this focus issue would be a great enhancement.
Thanks for the good work.

Results obtained on Windows 7 pro SP1.

**Comment by GitHubRulesOK** [comment]
@kjk 
unsure where some above described behaviour comes from there are NO buttons on bottom left **that is another products viewer**
Current versions of **SumatraPDF previewer simply responds to **_focused_** up down commands** from up down arrows page up/down keys or scroll both win 10 64bit or **win 7 32bit** and no reason to suspect its different in win7 64 bit
I suggest this is as designed and issue closed

**Comment by GitHubRulesOK** [comment]
Closing as functioning per design using scrollbar on the right 
Additional control focused enhancements were requested as part of https://github.com/sumatrapdfreader/sumatrapdf/issues/859
