### ISSUE TITLE
[Feature Request] Open a default PDF at start

### ISSUE THREAD

**Issue by mrddter** [sumatrapdfreader/sumatrapdf#1142]
In some context is useful if we can specify a default custom PDF to open at startup of Sumatra (when is opened without a different file). So a company can specify its own front page template.

Make sense?

**Comment by GitHubRulesOK** [comment]
That should be easily done by add filename to the start-up command line 
There is another possibility using the settings file but would need to know more about why the default method above may not work for you.

**Comment by mrddter** [comment]
when you close all pdfs for example or when you execute the program from Windows Start, or directly exectuted from CMD you don't see a front page. 

Your solution is correct, but -imho- for a company is better deploy-copy a well-known configuration file (SumatraPDF-settings.txt) and a pdf. 

thanks

**Comment by GitHubRulesOK** [comment]
Adding say logo.pdf to the start menu is easy find the startup item in
C:\ProgramData\Microsoft\Windows\Start Menu\Programs
and change target to 
"C:\Program Files\SumatraPDF\SumatraPDF.exe" logo.pdf
where logo.pdf is in the SumatraPDF folder
the problem going further is that does not catch the myriad of other ways users start SumatraPDF and you may  find that your needs ar better suited to modifying registry settings or even modifying the source code to first open a logo.png or instructions.pdf

However I would always ask myself how often am I annoyed when an application starts with an about me logo or other nag screen stopping me from instantly proceeding with the task in hand e.g. in this case reading the selected page of the document I asked for ?

There are ways to "pin" a help document to the start up frequently read screen or even add it to the start sequence, or add it to the file menu but first are you sure that is what your **users** want?

**Comment by mrddter** [comment]
you are making a good point but .. 

sure, you could customize all links in all pc in your company by hand one to one but what if you manage many many pcs? so here why I proposed you this. Is better for me - imho - have possibility to customize / choose what show if nothing is selected or well have a list of documents (works fine too) at startup if nothing is loaded and this is the same that you do now when you show a table with different links like manual, website, forums, devs and so on... but let me ask to you.. are you sure that is what your users want?

Sumatra is well done (i really love it) because have a marvelous settings ini .. why don't use it in enterprise environment?

often the company prepare laptops-workstations for all employess so yes is more simple - and maintainable - to copy two files (for example with a bash/shell script) and not go on every single pc that can have different S.O. and manually change all system shortcuts

if you think that is useless feel free to reject it, I don't want to impose my idea.. i want only drop my idea to you. happy coding
