### ISSUE TITLE
[防落梁混凝土纵向挡块.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/670986/default.pdf)

### ISSUE THREAD

**Issue by GoGoogle** [sumatrapdfreader/sumatrapdf#1145]
[防落梁混凝土纵向挡块.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/670986/default.pdf)
thank u bro,this is my source pdf document.pictures in my pdf looks good with adobe,but it's dim in this.

@kjk

_Originally posted by @GoGoogle in https://github.com/sumatrapdfreader/sumatrapdf/issues/695#issuecomment-269001683_

**Comment by GitHubRulesOK** [comment]
File:防落梁混凝土纵向挡块.pdf
Title: 32m总图新 Model (1)
Author: Administrator
Created: 26/08/2016 19:24:32
Application: pdfFactory Pro www.fineprint.cn
PDF Producer: pdfFactory Pro 3.52 (Windows XP Professional Chinese)
PDF Version: 1.4
File Size: 147.58 KB (151,118 Bytes)
Number of Pages: 1
Page Size: 21.0 x 29.7 cm (A4)

fineprint 通过允许您打印到超大页面来帮助您, 它可以自动重新保存到 a4。您可以裁剪不需要的页面, 此外, 通过复选框, 您可以通过将整个文档更改为灰度并删除所有图形来节省打印时间和墨迹, 而无需更改布局。
FinePrint helps by letting you print to oversize pages which it can automatically rescale to A4. You can cut out unwanted pages and in addition check boxes allow you to save printing time and ink by changing the whole document to grayscale and removing all graphics without changing the layout.

Without FINEprint results should have been set as follows
ISO minimum line widths @ A4 = 0.100 / 0.125 mm

[Anti-Drop beam concrete longitudinal block.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2956532/Anti-Drop.beam.concrete.longitudinal.block.pdf)

**Comment by GoGoogle** [comment]
What did you do with this document?
Make it visible in the sumatrapdf

> File:防落梁混凝土纵向挡块.pdf
> Title: 32m总图新 Model (1)
> Author: Administrator
> Created: 26/08/2016 19:24:32
> Application: pdfFactory Pro [www.fineprint.cn](http://www.fineprint.cn)
> PDF Producer: pdfFactory Pro 3.52 (Windows XP Professional Chinese)
> PDF Version: 1.4
> File Size: 147.58 KB (151,118 Bytes)
> Number of Pages: 1
> Page Size: 21.0 x 29.7 cm (A4)
> 
> fineprint 通过允许您打印到超大页面来帮助您, 它可以自动重新保存到 a4。您可以裁剪不需要的页面, 此外, 通过复选框, 您可以通过将整个文档更改为灰度并删除所有图形来节省打印时间和墨迹, 而无需更改布局。
> FinePrint helps by letting you print to oversize pages which it can **automatically rescale to A4**. You can cut out unwanted pages and in addition check boxes allow you to save printing time and ink by changing the whole document to grayscale and removing all graphics without changing the layout.
> 
> Without FINEprint results should have been set as follows
> ISO minimum line widths @ A4 = 0.100 / 0.125 mm
> 
> [Anti-Drop beam concrete longitudinal block.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2956532/Anti-Drop.beam.concrete.longitudinal.block.pdf)
@GitHubRulesOK 
What did you do with this document?
Make it visible in the sumatrapdf

**Comment by GitHubRulesOK** [comment]
I reset the document to the way the author should have set it 
=Left to Right reading=Landscape
= No invisible lines = ISONORM Line Thickness

**Comment by GoGoogle** [comment]
@GitHubRulesOK 

What software changes are used?

**Comment by GitHubRulesOK** [comment]
Here is a fair comparison of Adobe Reader (without its cheat mode) and SumatraPDF given a valid drawing.
Personally I think they look the same
![Untitled](https://user-images.githubusercontent.com/12754913/54203522-53b58b80-44ca-11e9-9294-01cd125a0faa.png)

**Comment by GoGoogle** [comment]
@GitHubRulesOK 
https://github.com/sumatrapdfreader/sumatrapdf/files/670986/default.pdf
？？

**Comment by GitHubRulesOK** [comment]
Not sure what the last link is supposed to be it looks like the same one from 3 years ago and at the top of this thread. That is a sub standard file I have shown that If the file is standardised and compared with Acrobat in Standard mode there is no difference between the two I cannot speak for all sources of PDF but I suggest you do not accept any that have been produced by FinePrint  unless they have been checked by a craftsman (since FinePrint aims to change the source quality)

**Comment by GoGoogle** [comment]
Thx.
I see.

@GitHubRulesOK
