### ISSUE TITLE
Issue when printing on printer XeroxVersa Link C405

### ISSUE THREAD

**Issue by banbonic** [sumatrapdfreader/sumatrapdf#1146]
In attachment are two files: PDF sent to printer and PDF with scanned result of printing.

[Sent to printer.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2968760/Sent.to.printer.pdf)
[Scanned result of printing.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/2968759/Scanned.result.of.printing.pdf)

If I try to print same PDF on same printer from another PDF reader, the result is normal, without blank lines.

**Comment by GitHubRulesOK** [comment]
This is a common problem primarily with Xerox drivers that has been solved by some users in the driver settings see several successes in https://github.com/sumatrapdfreader/sumatrapdf/issues/417 HOWEVER more often they did not find a suitable "driver setting" and most revert to the old version 3.0  see https://www.sumatrapdfreader.org/dl/SumatraPDF-3.0.zip and switch off the print as image

If you find a PRINTER setting that works for you please let us know, and if using 3.0 is a working fix for you please confirm that too.

**Comment by MarkoD** [comment]
For HP LaserJet Pro MFPs, the option "Print Data Optimization" (found in Advanced) set to "Optimize for Text and Vector" fixed the issue.

**Comment by georgedeath** [comment]
Switching from the latest prerelease down to 3.0, so PrintAsImage = false, solved the problem for me on the same print (Xerox VersaLink C405).

**Comment by GitHubRulesOK** [comment]
@kjk dupe / similar description to https://github.com/sumatrapdfreader/sumatrapdf/issues/919
