### ISSUE TITLE
[Feature Suggestion] replace icon with vectorgraph 

### ISSUE THREAD

**Issue by njZhuMin** [sumatrapdfreader/sumatrapdf#1147]
Hi team:
    Really appreciate all your work for bringing this wonderful app for us. It would be great if you can replace the icons with vectorgraph as a refinement so that this app could offer much nicer support for high DPI screen.
Thank you.

**Comment by GitHubRulesOK** [comment]
@kjk effectively duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1097 both covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/734 and 444

**Comment by kjk** [comment]
closing as dup of #734
