### ISSUE TITLE
Double-click and drag does not match Windows 7+ behavior

### ISSUE THREAD

**Issue by bhajneet** [sumatrapdfreader/sumatrapdf#1148]
If you double-click and drag in Windows, it will highlight by word instead of single characters.

As previously noted, triple click does not work to select the "field"/line/paragraph either #653 

Related #193

**Comment by GitHubRulesOK** [comment]
@kjk duplicates https://github.com/sumatrapdfreader/sumatrapdf/issues/217

**Comment by kjk** [comment]
Closing as dup of #217
