### ISSUE TITLE
directory sumatrapdfcache should be in %LOCALAPPDATA%

### ISSUE THREAD

**Issue by prekageo** [sumatrapdfreader/sumatrapdf#115]
Since sumatrapdfcache is a cache it should be placed preferably in %LOCALAPPDATA% and not in %APPDATA%.

https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/AppTools.cpp#L85

**Comment by kjk** [comment]
Maybe, but changing it at this point would require a stronger reason to out-weight introducing  backwards incompatibility.

**Comment by GitHubRulesOK** [comment]
@kjk 
can one of us remove the wontfix lable just to avoid any confusion ?
