### ISSUE TITLE
Text autocorrect capital I to a lowercase i

### ISSUE THREAD

**Issue by Simbaxo** [sumatrapdfreader/sumatrapdf#1151]
Everytime I type the letter I, notion automatically turns it into a lower case i. Is there any fix for this?

**Comment by GitHubRulesOK** [comment]
keyboard needs fixing aswell as shifting your cases its sending you to wrong site perhaps ?

@kjk I think this may be related to comments in your personal blog page https://blog.kowalczyk.info/

**Comment by kjk** [comment]
Yeah, this is a bug tracker for SumatraPDF, not Notion. 

Here's how to contact Notion team https://www.notion.so/notion/Guides-FAQs-e040febf70a94950b8620e6f00005004 (I don't work there)
