### ISSUE TITLE
PDF saved is mis-formatted

### ISSUE THREAD

**Issue by bobcheese21** [sumatrapdfreader/sumatrapdf#1155]
When "Print as PDF" -> Save as PDF.

Overlap of text and pdf in Notion page

[OrgAssFram_Assignment_RobiLin.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3056647/OrgAssFram_Assignment_RobiLin.pdf)

**Comment by kjk** [comment]
This is not a bug tracker for Notion. You can contact them via https://www.notion.so/notion/Guides-FAQs-e040febf70a94950b8620e6f00005004
