### ISSUE TITLE
EPUB refuse to open if screen orientation changed

### ISSUE THREAD

**Issue by 0xh3LL0** [sumatrapdfreader/sumatrapdf#1156]
quick spec: core2duo, 2gb ram, win xp sp3, sumatrapdf 3.1.2 32bit

step to reproduce:
change screen orientation to portrait
open the epub
close epub, close sumatrapdf
change screen to landscape
open the same epub
it refuse to open, and only show 0/0 page

workaround for now:
change the screen back to portrait
open the same epub
change the screen to landscape without closing epub

**Comment by GitHubRulesOK** [comment]
@0xh3LL0 
I cannot emulate using tablet with testbed spec: celeron, 2gb ram, win 7 x64, sumatrapdf 3.1.2 32bit

It may be an XP issue but I don't have XP kit to test

I am not sure if latest 32 bit general [pre-release](https://www.sumatrapdfreader.org/prerelease.html) will run on XP (may require special compile) you could first see if portable runs on XP and if so see if this problem is resolved

**Comment by 0xh3LL0** [comment]
tried both pre-release and daily build,
it crashed...
![crash](https://user-images.githubusercontent.com/23132217/73806201-6419d780-47fb-11ea-822a-ac064bea7722.jpg)

btw, now i'm using win 10 64 bit
here is the crash info from both of them 
[crashinfo.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4157164/crashinfo.zip)

**Comment by 0xh3LL0** [comment]
@GitHubRulesOK

**Comment by kjk** [comment]
@0xh3LL0 thanks for providing crashinfo.zip

Please try build 12107 or later from https://www.sumatrapdfreader.org/dailybuilds.html (should be available in half an hour; refresh the page if it doesn't show up).

This should fix the crash although I'm not sure what will happen. 

Changing orientation, especially when Sumatra is not running, shouldn't affect things so it's a bit puzzling to me what happens.

I don't have a tablet so no way to test changing orientation.

**Comment by GitHubRulesOK** [comment]
@0xh3LL0 @kjk 
My tablet on win 7 did experience a similar rare closure issue after powerdown while testing other files but whilst testing #1106 I did not have any problems. 
@0xh3LL0 can you supply a public file that causes you problems

**Comment by 0xh3LL0** [comment]
i read many ebooks, mostly pirated,
so idk if pirated content allowed on github but here is it,
maybe you can delete later
[An Archdemon's Dilemma - How to Love Your Elf Bride - Volume 06 Premium Ver.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4158537/An.Archdemon.s.Dilemma.-.How.to.Love.Your.Elf.Bride.-.Volume.06.Premium.Ver.zip)


![crash3](https://user-images.githubusercontent.com/23132217/73828454-d7d7d680-4833-11ea-8e47-621b84e1c26e.jpg)

**Comment by GitHubRulesOK** [comment]
@0xh3LL0 cheers
@kjk I can't delete content. So I suggest you do when seen later

**Comment by GitHubRulesOK** [comment]
@kjk 
as with many tablet tests I encounter many spurious actions trying to navigate by touch when it is not simple scroll through sequential pages :-) P.s. there is no context menu in ebook mode which would be nice to have for single/double page, open/close bookmarks, navigation etc

Tested multiple variants of above e.g. fixed and EbookUI middle of file with text, start of file with images, with and without remember file position, changing order of actions but as close as possible to described sequence.

Win7x64 using 3.2.12094x64 installed (screen scale 100%, which is a nightmare for touch as selections are miniscule and easy to miss with a finger) did not crash nor forget last file position, in short no problems with rotation after closing and reopening

Am unsure what else I can try to cause a crash or described failing to reflow on re-opening. Any clues from crash report about cause ?

**Comment by GitHubRulesOK** [comment]
@kjk 
Ok can confirm crashed on opening file in Landscape without prior actions
placed portable version 12104 on D:drive as per crash report
duplicated settings file from crash report
opened SumatraPDF in landscape
selected file from personal downloads directory
crash
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4159659/sumatrapdfcrash.zip)

**Comment by GitHubRulesOK** [comment]
@kjk 
@kjk 
there could now be two problems
12108 seems to make matters worse as files that did not have a problem do not go past page 0
12104 seems very buggy  when was last significant epub change ?

**Comment by kjk** [comment]
A recent regression. Should be fixed in build 12117 or later.

**Comment by GitHubRulesOK** [comment]
@0xh3LL0 
I think we need to reset all experiences to check current [pre-release]
(https://www.sumatrapdfreader.org/prerelease.html) build 3.2.12118 (or later) 

so taking the example file above into a session **without** old settings file can you see if just opening that file on your hardware causes any issue without screen rotation or does it then fail later when rotating as described
