### ISSUE TITLE
darkmode yaml syntax hides punctuation

### ISSUE THREAD

**Issue by carlsverre** [sumatrapdfreader/sumatrapdf#1157]
It seems that creating a yaml code block with dark mode enabled results in all punctuation being hidden.  I looked at the CSS and it seems like the issue is due to the opacity of punctuation being set to `0.7`.  If I set it to `1.0` the punctuation is visible.

I did not test with light mode so the issue may just be related to yaml.

**Comment by carlsverre** [comment]
Just tested with light mode - the issue does not occur there.

**Comment by GitHubRulesOK** [comment]
Wrong site perhaps this issue seems to sugest Sayr "SumatraPDF aint yaml reader" tagging ? please explain where sumatrapdfreader is expected to read yaml data processing files.

**Comment by carlsverre** [comment]
Sorry about that! I searched google for “notion bug report” and unfortunately the first result is your wiki’s bug report page which due to the domain looks a bit like notions own bug report page. This is the one I am talking about: https://www.notion.so/How-to-submit-bug-reports-c992bbe9c7b14c0eac5b7493228d4ce4

**Comment by kjk** [comment]
Thanks for letting me know.

I've disabled search indexing on those pages so it shouldn't happen in the future.
