### ISSUE TITLE
Hide Tab Bar When Only One File Is Open

### ISSUE THREAD

**Issue by WandersFar** [sumatrapdfreader/sumatrapdf#116]
Not sure if this has been requested before, but could you employ the same setup as Firefox and other browsers—only show the tab bar when there are actually multiple tabs to show? When there’s only one file open, no tab bar is necessary.

**Comment by rememberli** [comment]
Hello, any news now ?

**Comment by kjk** [comment]
I don't have plans to implement that.

**Comment by rememberli** [comment]
Acturally, I already found it : 

UseTabs = false
ShowMenubar = false
