### ISSUE TITLE
[Feature]-add another view mode: thumbnail

### ISSUE THREAD

**Issue by xianghongai** [sumatrapdfreader/sumatrapdf#1162]
Can we display thumbnails of all pages?
![thumbnail](https://user-images.githubusercontent.com/2075006/56939454-0903d780-6b3b-11e9-8615-3cb4b1c2836c.png)

**Comment by GitHubRulesOK** [comment]
Duplicated by identical requests to display all pages at once in https://github.com/sumatrapdfreader/sumatrapdf/issues/146#
