### ISSUE TITLE
PDF exporting is not working correctly when using code block

### ISSUE THREAD

**Issue by roeniss** [sumatrapdfreader/sumatrapdf#1165]
Version: 2.4.21.1.4
OS: Windows 10
Mode: Desktop 1.0.5
Updated: 17 hours ago
---

If page have code block, its lines are collapsed when exported to pdf.

How to reproduce:

1. make new empty page
2. make a code block: 
```
const test = {
	testValue: 1,
	anotherTestValue: 2
}
console.log(test) // { testValue: 1, anotherTestValue: 2 } 
```
here is sample:
![image](https://user-images.githubusercontent.com/26613280/57177021-b90a7500-6e9a-11e9-9b58-56800a68c40b.png)

3. then export it. it comes out like this:
![image](https://user-images.githubusercontent.com/26613280/57177030-c7589100-6e9a-11e9-8554-04a11055ac8f.png)

On the other hand, Some other markdown editor provide exactly what I wrote. for example Typora:
![image](https://user-images.githubusercontent.com/26613280/57177053-0a1a6900-6e9b-11e9-8770-650c86b0323c.png)
![image](https://user-images.githubusercontent.com/26613280/57177074-2f0edc00-6e9b-11e9-9472-099edc74469d.png)

So, Notion team can handle this to right way?

ps. This is my first issue offer. So if I missed or do something wrong, I apologize it. please tell me then I'll correct it. Thank you.

**Comment by GitHubRulesOK** [comment]
This is **SumatraPDF Reader** issues tracker 
we can only advise once you have exported and are using this PDF reader to open such exports
There is no relationship with notion please report above to notion team

**Comment by roeniss** [comment]
I am really sorry. I think I was confused where I was issuing.
Delete this issue if you wish. Sorry again.
