### ISSUE TITLE
How to open pdf file in existing sumatra window.

### ISSUE THREAD

**Issue by OpenWaygate** [sumatrapdfreader/sumatrapdf#1166]
If I double click 1.pdf in explorer, a sumatra window appears with 1.pdf in it, 

Then I click 2.pdf in explorer, the 2.pdf will not show in that existing window where 1.pdf already in, however, a new sumatra window will appear with 2.pdf in it.

How to config it so that  pdf file will be opened in existing sumatra window, when double click it in explorer?

**Comment by GitHubRulesOK** [comment]
When opening files from internal menu
With tab mode off the first file gets replaced by the second
to see two files in one window switch tabbed mode ON

When opened externally
That open second file in one session behaviour is default for tabbed mode  
Whereas the default when opening files with tabs off is provide separate windows

**Comment by 80avin** [comment]
In menu, find `Settings` -> `Options` and select `Use tabs` , if it is not selected already.

**Comment by OpenWaygate** [comment]
OK, solved, thank you.
