### ISSUE TITLE
Incorrect PDF file type association in windows explorer preview pane

### ISSUE THREAD

**Issue by FelixCold** [sumatrapdfreader/sumatrapdf#1168]
Despite while installing Sumatra PDF, I resigned from making it a default application to handle PDF files, Windows explorer preview pane still was hijacked by Sumatra PDF leading to very distorted previews of PDF files in Windows explorer.
Uninstalling Sumatra PDF removed those distorted previews but left preview pane unable to handle PDF files with default application, which then appeared to need complete reinstall to solve this issue.

**Comment by SumatraPeter** [comment]
>Windows explorer preview pane still was hijacked by Sumatra PDF leading to very distorted previews of PDF files in Windows explorer.

This has got nothing to do with making Sumatra your default PDF reader. Did you select _Let Windows show previews of PDF documents_ while installing the app?

![SumatraPDF_Preview_Handler](https://user-images.githubusercontent.com/15380332/57890516-8460cb00-7855-11e9-87aa-43f9da594910.png)

**Comment by FelixCold** [comment]
Likely I've selected this setting while installing Sumatra PDF as well as that other option letting Windows search PDF documents - because I actually need both these options, however I didn't realize that by doing this I don't just enable these features (or rather keep them enabled as they've worked previously), but instead dedicate these functions specifically to Sumatra PDF - what regrettably wasn't clear from feature description, which in regard to preview pane should state something alike:

"Let Sumatra PDF handle preview of PDF documents in Windows",

as well as in case of making Sumatra PDF default PDF viewer in Windows, feature description clearly states this but not something similarly too general alike:

"Let Windows show PDF files".

Anyway, thank you for explanation.

**Comment by GitHubRulesOK** [comment]
Generally have not seen any issues with previews can you explain/expand on  "very distorted" better still did you get a screen grab (not suggesting you go through any similar issues again)  just hope to get better insight to what may be an effect ? screen magnification / dpi ?

**Comment by GitHubRulesOK** [comment]
@kjk now tracked by #1248

**Comment by kjk** [comment]
Consolidate under #1248
