### ISSUE TITLE
search fail because letter size

### ISSUE THREAD

**Issue by Xen-G** [sumatrapdfreader/sumatrapdf#1169]
I just tryed find something in a PDF & surprized as  nothing was the result ( in the web preview contained what I searched for) Changed the keyword from small letters to CAPITAL & I get what looked for. Why cant find if use small letters the CAPITALed words ? When I searching (any progs) just quick type small letters, if need  special SAME  letter by letter search than will,& found no config in the options about it. I think this is an important thing cus easy to get false results :(

**Comment by SumatraPeter** [comment]
The problem most likely is with the PDF itself. Can you share a copy and also the exact search term(s) you used?

**Comment by Xen-G** [comment]
lol NVM didnT moved the mouse over that button, thought just part of the design XD
