### ISSUE TITLE
how to set "open with Adobe reader" software?

### ISSUE THREAD

**Issue by swun90** [sumatrapdfreader/sumatrapdf#1173]
How to assign the software when clicking "open with adobe reader"? I have other PDF software (like Foxit reader) installed, how can I open the current pdf file in SumatraPDF with the software?
I mean, can I custom the software?

And, if the Adobe reader is not installed, there's no option in the menu to open current file with other software. Could other software be assigned?

**Comment by kjk** [comment]
You can add other viewers to that menu via advanced settings https://www.sumatrapdfreader.org/settings.html

See `ExternalViewers` section.

**Comment by SumatraPeter** [comment]
@kjk: While we're discussing the `ExternalViewers` section in **settings.html**, can you please correct the minor typo in the spelling of "number" there?

> command line with which to call the external viewer, may contain %p for page **_numer_** and "%1" for the file name (add quotation marks around paths containing spaces)

**Comment by kjk** [comment]
@SumatraPeter fixed typo in https://github.com/sumatrapdfreader/sumatrapdf/commit/81c38b3056aee160fc6e25efb5d9267ff92da2e1

Might take a while before it propagates to the website

**Comment by swun90** [comment]
@kjk Thank you very much! It worked.

Just a little question: how to set the `CommandLine` correctly so that the external reader opens the file at the same page?
I tried `"readerpath\reader.exe" %p "%1"` and `"readerpath\reader.exe" "%1" %p` but they didn't work.

**Comment by SumatraPeter** [comment]
> Might take a while before it propagates to the website

@kjk: Is the propagation automatic or does it depend on you doing it manually?

**Comment by kjk** [comment]
It's a manual process.
