### ISSUE TITLE
split file states into a seperate file from config

### ISSUE THREAD

**Issue by musm** [sumatrapdfreader/sumatrapdf#1174]
I'd like to sync my config files however this would also sync the file states which I don't want to do.

Proposal: Separate out static configurations from the file states.

**Comment by GitHubRulesOK** [comment]
The only config file here is SumatraPDF-settings.txt I thus think you are on wrong repository and suggest if so you need to delete this thread

**Comment by musm** [comment]
Yes that is what I mean. Split the settings from Sumatra Pdf-settings.txt from the file states that are also saved in the same file.

**Comment by GitHubRulesOK** [comment]
OK I understand you wish to replicate the action of unchecking remember file states, you could do that before syncing them but I am confused why you don't then simply save a stock one with your preferences

**Comment by musm** [comment]
Most software separate out the static  configurations, from states that change locally.

This is advantageous since you can sync the config file globally and changing it locally one one machine sync upstream. The challenge with the current config file, is if computer 1 opens a pdf it changes and screws up `Sumatra Pdf-settings.txt` the recent states for the other computers that also sync it.

**Comment by GitHubRulesOK** [comment]
You are confusing me.  In a multi user environment every user should have 1 modifiable store in their registry or personal appdata (never shared with others) SumatraPDF avoids using the registry in fact each user can each have multiple appdata if you so wish all content is considered dynamic there are no "static" entries, if the file is broken it will be rebuilt as a set of general defaults. All other apps I know of replication is downward from service to user never upwards from user to repository.

**Comment by musm** [comment]
In other words is it OK to have Sumatra Pdf-settings.txt stored in Dropbox and symlinked to APPDATA Sumatra folder on each computer I want to sync with?

**Comment by GitHubRulesOK** [comment]
I would always say do not store any dynamic file in dropbox NEVER edit documents that autosave etc. In addition to this forum I have other experience of drastic losses due to users thinking they can edit files in synchronised folders without understanding the consequences. For runtime compiling editors such as CAD or LaTeX many graphics apps and even office apps there are screams of woe when days (or months) of work get "synced" to nothing

**Comment by musm** [comment]
In general I totally agree. But configurations files should be able to be synced.  

For example this part of the configuration state in `Sumatra Pdf-settings.txt`
```

MainWindowBackground = #80fff200
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
EbookUI [
	FontName = Georgia
	FontSize = 12.5
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = false
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]
ExternalViewers [
]
ShowMenubar = false
ReloadModifiedDocuments = true
FullPathInTitle = false
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
CustomScreenDPI = 0

RememberStatePerDocument = true
UiLanguage = en
ShowToolbar = false
ShowFavorites = false
AssociateSilently = false
CheckForUpdates = false
RememberOpenedFiles = true
InverseSearchCmdLine = "C:\Program Files\Microsoft VS Code\Code.exe" -g "%f:%l"
EnableTeXEnhancements = true
DefaultDisplayMode = automatic
DefaultZoom = fit page
WindowState = 2
WindowPos = 838 -13 973 1160
ShowToc = false
SidebarDx = 363
TocDy = 0
ShowStartPage = true
UseTabs = false

```

should be separate from  `FileStates [ ...`

Right? The file states are independent from the configuration and seem more logical to seperate?

**Comment by GitHubRulesOK** [comment]
It needs someone to rewrite the various locations that historically read / write to a common user settings file. Potentially that means double the trouble for that person maintaining and debugging. 

Off topic and **purely academic** you are using LaTeX enhancement and ideally should have  `ReuseInstance = true` with `UseTabs = true`

**Comment by musm** [comment]
I disable tabs since I hate the UI with the tabs. And it doesn't seem possible to set ReuseInstance to `true` and `Usetabs=false`

**Comment by yashpalgoyal1304** [comment]
also related: #1862

**Comment by kjk** [comment]
Too much work, not enough benefit.

Also don't want to create unnecessary incompatibilities between versions.
