### ISSUE TITLE
when opening 1 pdf sumatra opens every pdf opened previously as well how to disable that?

### ISSUE THREAD

**Issue by samigithub** [sumatrapdfreader/sumatrapdf#1175]
when opening 1 pdf sumatra opens every pdf opened previously as well how to disable that?

how to disable session reloading? I want to open 1 pdf file only then close when finished i dont want sumatra to open every pdf it ever opened every time i open a pdf file. that makes sumatra slower.

**Comment by GitHubRulesOK** [comment]
Its Settings > options > remember opened files 
Just deselect it
