### ISSUE TITLE
Add Actual Size as an opition in default zoom

### ISSUE THREAD

**Issue by sunnyday2006** [sumatrapdfreader/sumatrapdf#1176]
Sumatrapdf is great and fast.

How can I set 'actual size' as the default zoom? Since I cannot find the option among 'Fit Content', 'Fit Page', 'Fit Width'.

Secondly, I find issues about restore closed tabs in the following  https://github.com/sumatrapdfreader/sumatrapdf/issues/788, https://github.com/sumatrapdfreader/sumatrapdf/issues/1020.

That would be awesome and a revolutionary change on the pdf reading experience when tabs-closed mistakenly in the numbers of opening tabs, just as the use of Chrome or Firefox browser. Is there any way to realize it now?

**Comment by TamirEvan** [comment]
@sunnyday2006,
Based on [the definition of ZOOM_ACTUAL_SIZE](https://github.com/sumatrapdfreader/sumatrapdf/blob/81c38b3056aee160fc6e25efb5d9267ff92da2e1/src/GlobalPrefs.h#L8), setting '100%' as the default zoom should have the same effect as setting 'actual size' would have (if it had existed as an option).

**Comment by SumatraPeter** [comment]
@TamirEvan is correct. In the Zoom menu, as soon as you select **Actual Size** then **100%** is also selected, and vice-versa:

![image](https://user-images.githubusercontent.com/15380332/61913207-ffcbb080-af59-11e9-8bfc-5c8738063159.png)

@kjk: Issue seems to be resolved and can be closed.

**Comment by GitHubRulesOK** [comment]
@kjk
 @SumatraPeter confirmed this as not an issue
