### ISSUE TITLE
How to print first page only?

### ISSUE THREAD

**Issue by chengjk84** [sumatrapdfreader/sumatrapdf#1179]
i need a command line argument to allow SumatraPDF to print only page no 1 to printer... i did try some argument as show in document but not seem to work...

eg. 
--page 1
--page "1"

**Comment by GitHubRulesOK** [comment]
SumatraPDF -print-to-default -print-settings "1" target.pdf
should work see https://www.sumatrapdfreader.org/docs/Command-line-arguments.html

**Comment by chengjk84** [comment]
@GitHubRulesOK thanks...
