### ISSUE TITLE
Error updating SumatraPDF-dev

### ISSUE THREAD

**Issue by Dharmainiciativ** [sumatrapdfreader/sumatrapdf#118]
After the upgrade, there are two windows or tabs with errors. Which I have shown in the example ( GIF animation format).
![project001](https://cloud.githubusercontent.com/assets/10089507/6427755/8a1aaf24-bf9b-11e4-89f7-4f6b0f57cf4d.gif)

**Comment by zeniko** [comment]
Thanks for the report. Due to a bug in my build configuration, auto-updating accidentally got disabled for v3.1.10130z. I've fixed this for the next build (which you'll have to download manually to get auto-updating work again).
