### ISSUE TITLE
Feature request: load images in a folder

### ISSUE THREAD

**Issue by SillyBirds** [sumatrapdfreader/sumatrapdf#1185]
It would be great if sumatra could load images from a folder. Example: you have an unzipped folder of images and by loading one of them, you get them all, treating the whole contents of the folder as a single compressed file.

Currently trying that only loads a single image.

**Comment by kjk** [comment]
You can drag&drop a folder with images on Sumatra window and that will happen.

If you opened a single file in a directory, you can navigate between files via Ctrl-shift-left and ctrl-shift-right (see https://www.sumatrapdfreader.org/manual.html)

**Comment by GitHubRulesOK** [comment]
@SillyBirds see how I used this feature to address your previous request, save each page as new scaled image in a folder then "save as PDF" OR use windows to compress to zip and rename the zip as cbz

**Comment by SillyBirds** [comment]
@GitHubRulesOK Thank you for the reply, but reducing the size of the double pages means loss of quality. Plus editing all my files to adapt to a reader is not practical.

**Comment by SumatraPeter** [comment]
Duplicate of #351 for the record.

**Comment by GitHubRulesOK** [comment]
@SillyBirds 
Just for the record I increased width of smaller images (NO loss of quality NO file size increase)
NOT reduce width or quality of wider ones :-)
Disadvantage is increased font size and height but MUCH easier to scroll read all pages as same width.
