### ISSUE TITLE
What can Sumatra learn from PDF-XChange Viewer ? Highligh and coments...

### ISSUE THREAD

**Issue by RENANZG** [sumatrapdfreader/sumatrapdf#1187]

**Comment by SumatraPeter** [comment]
What specifically about "Highligh and coments (sic)"?

@kjk: Perhaps a candidate for closure till some useful details are provided...

**Comment by th3v4n** [comment]
Highlights would be nice. Xodo does this (but is otherwise shite, at least on Windows). The other thing is if tabs could be dragged over and arranged in new windows, but I imagine that might be a lot to code.

**Comment by pegleGrot** [comment]
Basic hiliting can be done in the beta versions:
https://forum.sumatrapdfreader.org/t/highlighting-text/2093

**Comment by GitHubRulesOK** [comment]
Highlights are available and the request for comments (currently work in progress) were both requested in https://github.com/sumatrapdfreader/sumatrapdf/issues/323 so closing this one as a duplicate
