### ISSUE TITLE
Show full name of a file in a tooltip when mouse over tab

### ISSUE THREAD

**Issue by nazar2sfive** [sumatrapdfreader/sumatrapdf#1188]
I work with upto 10-15 pdf opened at a time. Then selection between the pdf becomes difficult as only part of that file is shown.

If it could show the filename and info on mouse hover over it it would be great. 

![image](https://user-images.githubusercontent.com/12841320/62379127-0d8ac280-b566-11e9-96a4-cdb1d47d3da2.png)

Here i have three volumes of a book opened. Vol I, II, III. i get confused which to click to open my desired volume.

**Comment by SumatraPeter** [comment]
@kjk: Both this and #782 can be marked as dupes of #336.

**Comment by kjk** [comment]
Keeping the latest as master bug

**Comment by SumatraPeter** [comment]
That's... strange. Instead of doing that every time a new dupe is posted isn't it better to treat the chronologically oldest one as the master while all new ones are closed?

**Comment by kjk** [comment]
I wouldn't overthink this. Sometimes one version has most information. Sometimes it's better to keep the newer one because it shows up earlier. And sometimes it's just random. In the end, it doesn't matter much as they are all linked.

**Comment by nazar2sfive** [comment]
2 solution would best work for me. 
1. stack tabs (like i have a ABC vol 1.pdf 2.pdf 3.pdf...... if one tab would show me the stacked tabs beneath it like the vivadi browser does.
![image](https://user-images.githubusercontent.com/12841320/62829509-1e4ece80-bc1f-11e9-92a5-4a6bc4aef4a6.png)

2. show tooltip on hover

**Comment by GitHubRulesOK** [comment]
@kjk 
Whilst looking at tabs related code, there is mention of tooltips,
As a first step to aiding users would it be possible to simply add to the `highlight focused tab` the hovering tooltip "display filename with path"
The more complex issue of right click context actions like opening folder is covered by the other issues to list or action for all tabs

**Comment by peremudrilius** [comment]
when this small, but very usefull, feature will be added?

**Comment by zoulja** [comment]
This is the most annoying issue in SumatraPDF so far, please make it fixed

**Comment by GitHubRulesOK** [comment]
Thanks, I see it certainly was not a "Small" question of code :-)
![image](https://user-images.githubusercontent.com/12754913/125605503-134f47f1-4585-4acc-8e4c-8b9bd967fe3a.png)

**Comment by zoulja** [comment]
> Thanks, I see it certainly was not a "Small" question of code :-)
> ![image](https://user-images.githubusercontent.com/12754913/125605503-134f47f1-4585-4acc-8e4c-8b9bd967fe3a.png)

Could you please clarify where we can get this build?

**Comment by GitHubRulesOK** [comment]
@zoulja
Developers will see it in current compile.
Due to a "Hiccup" in the upload sequence the Binaries will only become widely available **from tomorrow** on the Pre-Release Downloads page. You could try https://kjkpub.s3.amazonaws.com/software/sumatrapdf/prerel/SumatraPDF-prerel-13657-64.exe
