### ISSUE TITLE
Add bookmarks icon to toolbar.

### ISSUE THREAD

**Issue by ScottMaclure** [sumatrapdfreader/sumatrapdf#119]
Useful when I'm using only the mouse to browse a PDF.

**Comment by calvin-young** [comment]
This feature would greatly benefit users of modern laptops on which the function keys default to media keys.  As such opening/closing the bookmarks bar requires a two-handed shortcut: Fn+F12.

**Comment by GitHubRulesOK** [comment]
@kjk this issue is **now** addressed by either the mouse right click (or on a touch tablet hold one finger down) for keyboard users it is available via the application or (context) menu key (usually to right of spacebar and/or Alt GR) followed by B (for **B**ookmarks)
