### ISSUE TITLE
Enhancemnet: Support of rar 5.x

### ISSUE THREAD

**Issue by SamTyler** [sumatrapdfreader/sumatrapdf#1191]
Mostly the new cbr/cbz or other files or packed with rar 5.x but cannot be open by SumatraPDF.

**Comment by SumatraPeter** [comment]
Read the following comment for the solution: https://github.com/sumatrapdfreader/sumatrapdf/issues/1032#issuecomment-396040094

**Comment by SumatraPeter** [comment]
Read the following comment for the solution: https://github.com/sumatrapdfreader/sumatrapdf/issues/1032#issuecomment-396040094

@kjk: Recommend this be closed as there's nothing to fix.

**Comment by SamTyler** [comment]
@Peter: will test it asap

**Comment by SamTyler** [comment]
First of all I am using a portable version of SumatraPDF from portableapps.com. So its only the .exe file in the directory. I put the UnRAR.dll ant the UnRAR64.dll in the app dir. The .exe is a 32-bit version because the UnRAR64.dll won't work but the UnRAR.dll works fine, thx.

**Comment by SumatraPeter** [comment]
> First of all I am using a portable version of SumatraPDF from portableapps.com.

Sam, just to let you and others know for future reference - Any version of Sumatra you obtain from third-party sources is not officially supported for obvious reasons. If you need a portable version, official 32 and 64-bit stable versions are available from the website [here](https://www.sumatrapdfreader.org/download-free-pdf-viewer.html), and official pre-release versions are available [here](https://www.sumatrapdfreader.org/prerelease.html).
