### ISSUE TITLE
customize bookmark shortcut

### ISSUE THREAD

**Issue by PierreSaminadin** [sumatrapdfreader/sumatrapdf#1194]
Hi there

thanks for your work,, SumatraPDF is very nice.

as many user i have a laptop with no numpad so i can't use the shortcuts concerning bookmarks : 
<<
Expand a node: Numpad +, →, Shift+Numpad 6
Collapse a node: Numpad -, ←, Shift+Numpad 4
Expand/collapse all child nodes: Numpad */Numpad /
Expand/collapse all bookmarks: Shift+Numpad */Shift+Numpad /
>>

and i have a french keyboard.

it would be nice to be able either : 
- to customize these shortcut 
- to use a FUNCTION key.
- to have a "right clic menu"
- to have a menu option 

all the best !
Pierre

**Comment by GitHubRulesOK** [comment]
@kjk Updated bookmark controls so double OR right click expand and collapse all,
 should basically cover this issue one way or another
_The only shortfall may be later in .vbkm but that is a seperate issue._

**Comment by kjk** [comment]
Agreed. To summarize:
* you can now collapse / expand current node with Left / Right
* there is a context menu in tree view to expand / collapse all
