### ISSUE TITLE
mobi/epub Chinese line wrapping error

### ISSUE THREAD

**Issue by Seryta** [sumatrapdfreader/sumatrapdf#1200]
![image](https://user-images.githubusercontent.com/31036794/64310308-2efe2480-cfd2-11e9-834f-5abd2262350c.png)
As the picture shows, there's a serious problem with the line-up of Chinese books, but I tried it with other readers, not the books themselves. Encountered "，。、" and so on will automatically wrap, very affect reading, wanwang improvement!

**Comment by Seryta** [comment]
[https://github.com/jijinggang/sumatrapdf](url)
This branch solves most of the problems, but the typography is still a little bit of a problem, hoping to make a reference.

**Comment by GitHubRulesOK** [comment]
Closing as without a sample to check this issue is closed by virtue of switch in 3.4 pre-release UI, please raise any fresh foreign character mis handling by providing sample that is mis-rendered in a new issue.
