### ISSUE TITLE
Roadmap or release plan? Is sumatrapdf dead?

### ISSUE THREAD

**Issue by StefanSchroeder** [sumatrapdfreader/sumatrapdf#1202]
Ok, 'dead' is perhaps exaggerated, as sumatrapdf works nicely and is mostly feature complete.
Nevertheless there hasn't been a release in 3 years, but I can see from the commit dates that updates are made. Users cannot benefit from these updates if no new release is published.

So, I guess my issue is: What's the plan for SumatraPDF? Will there be new releases?

**Comment by SumatraPeter** [comment]
The latest [pre-release build](https://www.sumatrapdfreader.org/prerelease.html) is dated April 23rd, so not _that_ old (compared to the stable version at least!).

Only the dev can answer at what point one of these builds will be considered officially stable enough for general public use.

**Comment by blinkenlight** [comment]
I came looking for this exact question - any software with no new release in several years is effectively dead, yet I see commits happening here (even if they seem to be refactoring and minor maintenance ones). So... should we expect basically no further releases anytime soon (which is de facto the same thing as "never")? This is by no means an attempt to demand anything of course, it would simply be nice to know where we stand...

**Comment by Bartwillemsen** [comment]
As long as the maintainer is still active, a project isn't dead, imo. But I agree some kind of small update about what the plans are would be nice. :) Nonetheless, the current stable version still functions correctly even though it's more than 3 years old. It's still my go-to PDF reader on all of my Windows installations.

**Comment by kjk** [comment]
Right now I'm working on updating to latest mupdf (https://github.com/sumatrapdfreader/sumatrapdf/tree/update-mupdf). I'm hopefully I'll finish it relatively soon.

**Comment by Bartwillemsen** [comment]
Thanks for the update, @kjk . I appreciate all the work you do!

**Comment by SumatraPeter** [comment]
That's great news @kjk, thanks for the update!

**Comment by StefanSchroeder** [comment]
I didn't mean to imply that there is anything wrong with the stable release. It's just that it'd be nice to just wrap up the latest developments every once in a while and just push them out the door.
Of course I also do appreciate all the work that has been going into the development of sumatra-pdf. Or else I wouldn't be here.
