### ISSUE TITLE
Application Launcher for Google Drive: "Error loading C:\WINDOWS\system32%*"

### ISSUE THREAD

**Issue by aholland** [sumatrapdfreader/sumatrapdf#1205]
**To reproduce:**
1. Save a PDF file to Google Drive
2. Sync the file your local machine using *Backup and Sync from Google*. This should be automatic assuming *Backup and Sync* is already installed, running and logged in. 
3. Right click on example.pdf and use the "Google Drive" sub-menu to "Copy link to clipboard"
4. Ensure the Google Chrome extension *Application Launcher for Drive (by Google)* is installed and active.
5. Open a tab in Chrome and paste in this link, which should be something like `https://drive.google.com/file/d/<bla bla bla>/view`
6. The PDF document should be displayed in Chrome and just above it a button to *Open with* 
with options for *Apps on your computer*  including *SumatraPDF*. If you don't see the button move the mouse cursor. If you don't see the *Apps on your computer* section when you click the down-arrow, check step 4.

![image](https://user-images.githubusercontent.com/1101312/64744364-9d556080-d557-11e9-8127-f347b71eae0a.png)

7. When I try to open the file, SumartaPDF opens, opening the correct file using the correct local path to the file (on locally synced Google Drive), but it  then opens a second tab (or window, in windowed mode) with the error shown in the below image. (`Error loading C:\WINDOWS\system32%*`) It also fails to take focus and come to the foreground i.e. you have to Alt-Tab to see the window.

**Note 1:** I have tried the latest pre-release version of and it has a similar problem, but actually a bit worse - it gives the same path system32 path and states that it has crashed and needs to close.

**Note 2:** Opening with *Adobe Acrobat Reader DC* works without error, though, to be fair, it also does not get focus and opens "behind" the browser.

![image](https://user-images.githubusercontent.com/1101312/64744495-2cfb0f00-d558-11e9-953a-1f8327ea3f9a.png)

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
I agree this is reminicient of related issue where [Dopus file launcher](https://forum.sumatrapdfreader.org/t/sumatrapdf-directory-opus-open-with-menu-error/586)  appeared to be confused when using the registry entry.
Their issue was resolved by altering their calling method, and I agree if the above extension can/has not a means to change then the long standing registry entries (without problems by most users) should be kept. However a standard windows system shortcut to SumatraPDF can be used more simply as the default opener by any other application such as this extension.
