### ISSUE TITLE
"fit" not work for me or for this document

### ISSUE THREAD

**Issue by Telrik** [sumatrapdfreader/sumatrapdf#1209]
maybe someone can check it please 
i use this command line parameters to print that document that i attached from command line.
-zoom "fit page" -print-to-default -print-settings "fit" "HS7 - CAR FORM.pdf"

i tried use  SumatraPDF-3.1.2 both 64 and 32 bit
also pre release version no matter i tried, this pdf printed being cut from bottom.
like this https://i.imgur.com/3NUQczR.png
(i tried shrink and noscale as well)

P.S. printed normally if from gui.

[HS7 - CAR FORM.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3639774/HS7.-.CAR.FORM.pdf)

**Comment by GitHubRulesOK** [comment]
The source is oversized legal page so I see why you need fit
I can get it to fit to an A4 PDF printer using
sumatrapdf -print-to-default -print-settings "fit,paper=a4" "HS7.-.CAR.FORM.pdf"

1) Avoid mixing zoom or other visual control commands with printing options. they probably block the desired result
2) specify the desired paper size as A4 A3 or letter etc. (We get lots of complaints when users try to force label or plotter sizes.

**Comment by Telrik** [comment]
Thanks Alot! That worked.
did not found paper size config in manual so did not tried it
https://www.sumatrapdfreader.org/docs/Command-line-arguments.html

you are breathtaking!
