### ISSUE TITLE
[Feature request] Hide scrollbar in fullscreen mode

### ISSUE THREAD

**Issue by rotvel** [sumatrapdfreader/sumatrapdf#1211]
Like Adobe Reader hide the scrollbar in fullscreen mode, even if there's scrollable content. 

It's distracting with a scrollbar when immersing in a book or a comic. 

Should probably be an optional feature.

**Comment by SumatraPeter** [comment]
Here's the [developer's response](https://forum.sumatrapdfreader.org/t/add-option-to-hide-scrollbar/966/3?u=sumatrapeter) on the forum to a similar request.

**Comment by GitHubRulesOK** [comment]
SumatraPDF in F5 (single page) mode was introduced as comparable / similar to Adobe Reader Full Screen mode, F11 is an alternative for switching to Fullscreen If you do that in non scrolling state (i.e. single pages) then the scrollbars are "hidden", so I am closing this as it has an existing equivalent feature.
The scrollbars are only shown when required !

**Comment by GitHubRulesOK** [comment]
Hiding scrollbars for non fullscreen has now been added to the current daily pre-release and should be available for most presentation modes including pictures
![image](https://user-images.githubusercontent.com/12754913/86125732-0ac98200-bad5-11ea-8512-101ec2b5f185.png)

**Comment by lukewma** [comment]
Hi, sorry to touch on this again, but is there a reason why the settings option is disabled? I'm using the 3.3 preview, and while the scrollbars can be disabled on a per document basis, they come back on all documents open every time i open a new instance. I was looking through the issue, and maybe i'm misunderstanding something here, but is there a reason why the user setting commit [https://github.com/sumatrapdfreader/sumatrapdf/pull/1647/commits/b7e91e35ae1de66450955faab5091d18132ab2cf](url) isn't used?

**Comment by GitHubRulesOK** [comment]
"scrollbars can be disabled on a per document basis, they come back on all documents open every time i open a new instance."

AFAIK they stay **OFF throughout the session** and also are respected opening another non tabbed instance or tabbed instance  Via CTRL N with/without shift

Only a restart or new session reverts to the initial default behaviour
