### ISSUE TITLE
Horizontal scrolling with mouse wheel

### ISSUE THREAD

**Issue by multicast** [sumatrapdfreader/sumatrapdf#1212]
While zoomed in, horizontal scrolling is possible with the Alt+mouse wheel. However, the default behavior for many programs is the Shift+mouse wheel.

To keep behavior consistent for existing users, Options dialog can provide new checkbox, e.g.:

**[x] Use Shift for horizonal scolling instead of Alt.**

**Comment by SumatraPeter** [comment]
If the de facto standard is to enable horizontal scrolling with Shift+mouse wheel, then I see no reason to over-complicate matters with an extra option. Sumatra should simply switch to Shift+mouse wheel if that is indeed the convention across most (Windows) programs.

[BTW, just discovered while looking into the behavior of other programs that it took Mozilla merely fifteen and a half _years_ or so to implement [this feature](https://bugzilla.mozilla.org/show_bug.cgi?id=143038 "Bugzilla - 143038 - Horizontal Scrolling with Mouse wheel + modifier key")!]

**Comment by GitHubRulesOK** [comment]
Although not in the Manual

Shift + Scroll wheel is already taken in continuous mode by shift the mouse wheel steps up about 20 notches .

Not sure how long that action has been there, as never though to try it, 

I use tilts for horizontal

**Comment by SumatraPeter** [comment]
> I use tilts for horizontal

Yeah, but not everyone has a mouse with a tilt wheel. I guess it would be best if Sumatra used Shift+mouse wheel for horizontal scrolling, and Alt+mouse wheel instead for increasing the wheel's step count.

**Comment by GitHubRulesOK** [comment]
Just for info from source (undated)
    // added: shift while scrolling will scroll by half a page per tick
    //        really usefull for browsing long files

Also I note that more recent MuPDF code is now aligned with X11 actions such as Shift+Wheel = horizontal scroll.

**Comment by SumatraPeter** [comment]
> Also I note that more recent MuPDF code is now aligned with X11 actions such as Shift+Wheel = horizontal scroll.

😕 So you're saying the latest MuPDF does use Shift+scroll wheel for horizontal scrolling, but the updated SumatraPDF builds are overriding that? If MuPDF also follows convention now then all the more reason for Sumatra not to stand out anymore and use the same combo for a non-standard action.

**Comment by GitHubRulesOK** [comment]
I guess it was a SumatraPDF enhancement prior to the MuPDF introduction in their own GL viewer

@kjk
 if it is now part of mupdf coding is it easy to use /absorb that Shift Wheel = horizontal and reassign Alt to  part pages ?

**Comment by kjk** [comment]
Let's focus on what the desired behavior should be for Sumatra. I'm willing to change things to align with other programs.

I'll change `Shift-Mouse Wheel` to horizontal scroll as VS Code and IntelliJ do that.

Possibly will make `Alt-Mouse Wheel` to be faster vertical scroll.

To clarify mupdf situation. Mupd is two things:
* a library for pdf parsing and redering
* mupdf viewer (well, 2 viewers)

Sumatra only uses mupdf, the library. The code related to scrolling in question is in mupdf, the viewer, and is not used in Sumatra.
