### ISSUE TITLE
cbr files encoded with rar v5.0 don't open

### ISSUE THREAD

**Issue by amesman** [sumatrapdfreader/sumatrapdf#1215]
cbr files encoded with a lower version (e.g. rar v2.9) do open properly, but files encoded with rar v5.0 won't open (message simply says "Error loading <filename>.cbr")

**Comment by SumatraPeter** [comment]
Read the following comment for the solution: https://github.com/sumatrapdfreader/sumatrapdf/issues/1032#issuecomment-396040094

@kjk: Duplicate of #1032, #1191 etc.

**Comment by kjk** [comment]
Closing as dup of #1032 1032
