### ISSUE TITLE
Feature request: Document state based on checksum

### ISSUE THREAD

**Issue by Kiwawa** [sumatrapdfreader/sumatrapdf#1216]
More and more often, automaticly generated PDF:s have the same filename, like "Your_ticket.pdf" or "Document.PDF". This causes different documents with the same name to open on wrong pages. It would be nice to have a configuration switch (or perhaps replace the way the document state is saved) to use the checksum of the PDF file as a unique handle for the document state instead.

**Comment by kjk** [comment]
If a file name changes, there is no efficient way to locate a file based on a checksum.
