### ISSUE TITLE
weird Looks on WinXP

### ISSUE THREAD

**Issue by mcwimpy** [sumatrapdfreader/sumatrapdf#122]
Hello!

I noticed that the title window bar is in WinXP default blue and couldn't find a documented option to change that to black, or select something like "use OS Theme colors" ... now if you look at the screenshot you'll see it's kinda weird with that blue bar but black icons on the right top.

I'd appreciate if I could have the regular window mode of previous versions back, instead of the new thing - which is commitedly really shiny and awesome on Win7, but we don't have that (and won't ever have any newer version of Windows) on all PC's. Especially the older PC's run fast with XP and Sumatra :-)

Thx in forward,
your fan McWimpy
![screenshot_18](https://cloud.githubusercontent.com/assets/11300847/6470557/c6dbedce-c1e4-11e4-8c8c-8149721a2142.jpg)

**Comment by kjk** [comment]
You can go back to the old look via `Use Settings/Options... menu to go back to the old UI` (http://www.sumatrapdfreader.org/news.html)

**Comment by mcwimpy** [comment]
Oh ok I see. If i don't insist on the tabbed mode i get back the black window.
Here for you the blue black look:
![screenshot_19](https://cloud.githubusercontent.com/assets/11300847/6470629/43f68404-c1e5-11e4-941c-02624b603ba9.jpg)

**Comment by mcwimpy** [comment]
Ok It seems my screenshot SW is more clever then me :-)
However i find it a good compromise to switch off tabs to get back the original window bar.
Maybe the relationship between tabs and UI mode could be a bit more clear in the news and documentation ;-) In any case :+1:  thumbs up for your great work
here for you how Zune should look. Thanx again, as this was the only SW that bugged us with the WinXP default blue :-)
![screenshot_20](https://cloud.githubusercontent.com/assets/11300847/6470663/89fb61fe-c1e5-11e4-9fd5-8fe3436275e2.jpg)
