### ISSUE TITLE
restore current directory

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1226]
We set it system dir on startup to prevent dll hijacking.
But it's also directory used in file save dialogs.
Restore current directory after loading all dlls or set it Desktop or Downloads directories.

**Comment by GitHubRulesOK** [comment]
@kjk Currently File open / Save As appears to be set to last folder used, even if its network, unclear where it would default, if plug is pulled in my test it reverted to a previously accessible folder

**Comment by GitHubRulesOK** [comment]
@kjk 
did we recently dupe and close https://github.com/sumatrapdfreader/sumatrapdf/issues/2073

**Comment by kjk** [comment]
Yep, this is the same issue.
