### ISSUE TITLE
Text is misplaced in this PDF

### ISSUE THREAD

**Issue by dewi-ny-je** [sumatrapdfreader/sumatrapdf#1227]
The attached PDF has been generated by FidoCadJ and is displayed correctly by Chrome.
In SumatraPDF the text labels are all placed in the upper left corner.
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3829099/test.pdf)

**Comment by GitHubRulesOK** [comment]
@jkj for what its worth, this initially appears to be a mupdf issue since the few apps I tested (other than mupdf) seem to behave as expected

**Comment by kjk** [comment]
I reported it to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=701896
