### ISSUE TITLE
Bug in rendering image with Interpolate option

### ISSUE THREAD

**Issue by rysavyjan** [sumatrapdfreader/sumatrapdf#1229]
Looks like incorrect GDI+ PixelOffsetMode, see https://stackoverflow.com/questions/20776605/missing-half-of-first-pixel-column-after-a-graphics-transform-scale

Adobe Acrobat Reader DC works fine. Also image without Interpolate option enabled works fine. See attached PDFs.

![sumatra_problem](https://user-images.githubusercontent.com/46950152/68784789-6bd34100-063d-11ea-8b5f-dc865d9f90dd.png)

[interpolate_disabled.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3842380/interpolate_disabled.pdf)
[interpolate_enabled.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3842381/interpolate_enabled.pdf)

**Comment by SumatraPeter** [comment]
No longer a problem with MuPDF 1.16.0, so once kjk is [done updating to it](https://github.com/sumatrapdfreader/sumatrapdf/issues/1202#issuecomment-550229312) this bug should be automagically fixed.

**Comment by kjk** [comment]
I just checked and it's fixed in master. Will provide a way to download daily builds soon to allow using / testing the latest code.

**Comment by kjk** [comment]
You can test the fix using latest daily build https://www.sumatrapdfreader.org/dailybuilds.html
Fair warning: this upgrade to latest mupdf required rewriting a fair amount of code so there are likely to be bugs.
