### ISSUE TITLE
Print Fail and Lockup of Xerox Network Printer

### ISSUE THREAD

**Issue by thinksnow247** [sumatrapdfreader/sumatrapdf#123]
I cannot print to our Xerox 6605DN networked printer. The print fails with no error message and locks up the printer queue so no one else can print until the printer queue is cleared at the printer and restarted. 

No problems printing to another Brother printer. I have not had printing problems prior to upgrading to the latest version.

No problems printing from Chrome's built in .pdf viewer.

Window 8.1 Pro, auto-updates enabled
Dell M3800

**Comment by kjk** [comment]
There's nothing we can do without access to that specific printer.
