### ISSUE TITLE
Translations of Window commands

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1230]
Whilst checking latest versions I noted that the translation for the last menu options (windows) is not applied! this seems to happen with ALL languages ?

![Untitled](https://user-images.githubusercontent.com/12754913/68871308-21f96200-06f4-11ea-8a8f-59231c571adc.png)

**P.S.** in RtL languages as above the **previous / next** icon positions get "reversed" I don't use RtL but it may be that other users could find that reversal problematic ?

**Comment by SumatraPeter** [comment]
That's the system menu common to (almost?) all Windows programs (Alt+Space should bring it up). Are you sure that's even subject to translation?

> P.S. in RtL languages as above the previous / next icon positions get "reversed" I don't use RtL but it may be that other users could find that reversal problematic ?

If 'other' i.e. non-RtL users are going to use the program on an RtL language system then they should expect reversal I suppose.

**Comment by GitHubRulesOK** [comment]
Hi peter you are possibly correct that dialog may be set by the system locale thus I only see it in English It would possibly help if a user of a different local language can confirm it is in their own dialect. if so this knee-jerk can be closed.

WRT the "reversal" I do not know how it affects RtL users but if I was on their system I would expect Left to be Previous and Right to be Next but I don't know how they react to such visual cues. It is easy enough to swap the toolbar icons externally and thus no need to "fix" the application, simply provide an alternative reversed bitmap.

**Comment by kjk** [comment]
Yes, this is a system menu that Sumatra has no control over.
