### ISSUE TITLE
Failure to "save as" PDF in latest builds

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1231]
SumatraPDF for as long as i can remember can open image files such as TIF PNG TGA JPG etc. 
This functionality has never been promoted but is extremely useful in both the desktop Icon previewer and main application.

**Enhancement request**
"File open " does not have an option for "Image files" thus it has always been necessary to switch to "all files" in order to select and open the supported image file types.

**BUG**
Prior to latest builds it was possible to open any supported image file and "save as" PDF a most useful feature on its own, however that now induces a hang and crash.
![Untitled](https://user-images.githubusercontent.com/12754913/68876081-c92dc780-06fb-11ea-9ce1-49bcdb905747.png)

As an additional comment the ability to open compressed or non compressed folders of images  and save them as a multi-page PDF / comic book etc has now been now compromised.

**Comment by GitHubRulesOK** [comment]
@kjk odd minor update to this issue
I was testing Ghost-script support and can report x64 SumatraPDF appears to works well with x32 9.5 ghost-script the PS and EPS files I tested appear to load without problem. On a whim I decided to try save as PDF and some converted without a problem, so a question arises is there a difference in (E)PS conversion to PDF (the files were significantly smaller) rather than any larger decompression/manipulation in memory of other image formats. OR is it a result of the other oddity that caught my eye in that the conversion reported in file properties suggested as having been done by ghost-script rather than SumatraPDF.

**Comment by Kvcd12** [comment]
3.2.11301 Portable 64-bit

Don't know if this is related or not, but tried a save as for a PDF.  Was saving to another drive and giving it a new name.  Doesn't occur all the time.  On one PDF, I didn't change the name and the crash occurred.  There must be something about the PDFs that are causing the problem, since it doesn't occur every time.
