### ISSUE TITLE
Failure in latest builds to show bookmarks

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1234]
Using a test example such as https://download.novapdf.com/download/samples/pdf-example-bookmarks.pdf

The bookmarks are not shown in latest build, this also appears to be the case with an epub that includes bookmarks
_P.S. Favourites seems to show OK in lower half of left-hand canvas_

![Untitled](https://user-images.githubusercontent.com/12754913/68888374-ba064400-0712-11ea-983d-63d9bfa98f17.png)

**Comment by GitHubRulesOK** [comment]
UPDATE some bookmarks may be shown, in the following case lower levels of bookmarks are displayed thus it may be an issue related to the index/count of bookmark nesting

![Untitled](https://user-images.githubusercontent.com/12754913/68890679-592d3a80-0717-11ea-802f-23538361b36f.png)

**Comment by kjk** [comment]
This should be fixed now.
