### ISSUE TITLE
Cosmetic loss of feature due to new MuPDF engine

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1235]
Earlier builds respected the coloured boundary box around hyperlinks **which was a useful enhancement / warning** to avoid accidental triggering the hyperlink. the current rendering does not have that enhancement active.

![Untitled](https://user-images.githubusercontent.com/12754913/68892263-7c0d1e00-071a-11ea-9e85-bc681aac827c.png)

**Comment by kjk** [comment]
That bluish border around links is actually only supposed to be present in debug builds, as a helper for development, and can be toggled with Debug -> Highglight menu (again, only available in debug builds).
This option is not present in release builds. Not sure how it ended up in that older pre-release build.

**Comment by GitHubRulesOK** [comment]
@kjk 
So if I understand it correctly this enhancement / "feature" is an option only set by developer choice, However it was an occasional user boon to be able to distinguish "hyperlink areas" (there was much discussion about its pros and cons whilst using Latex Editors), It would be nice to have an enhanced option if there is some way to toggle the display using advanced options true/false
