### ISSUE TITLE
Minor updates to "Manual" page

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1237]
Whilst checking some keyboard behaviours I noted the following

Navigation  |  | 
-- | --
_j/k, Up/Down_ |  _scroll up/down by line_ | 
**in E-book mode the above 4 keys act just like**  |  **next/previous page**

also update needed to add that h/l are yet another alternative to n/p or Page Down/Page Up

...  |  | 
-- | --
_n/p_, **l/h** | _next/previous page_
... | 

Actions  |  | 
--  | --
**< Ctrl > + N** | **open a new window**
**< Ctrl > + < Shift > +N** | **open current document in new window**
_< Ctrl > + O_ |  _open a new document_

I suggest the following F2 action is added

...  |  | 
-- | --
< Ctrl > + S | save as 
**F2** | **rename file and reopen in new name**
... | 

< Ctrl > + Left Mouse | select <strike>text or image</strike> area (can then use with copy, print or +/- zoom) 
-- | --
< Ctrl > + Right Mouse | grab and pan page in any direction
< Alt > + scroll wheel | increase vertical scroll wheel steps (faster)
< Shift > + scroll wheel | pan horizontally with scroll wheel
< Ctrl > + y | show dropdown Zoom control

Viewing state  | corrections | 
--  | --
< Ctrl > + L or <strike>F11</strike> **F5** | <strike>enter</strike> **Toggle** presentation mode (minimal full screen mode)
< Ctrl > < Shift > + L | <strike>enter</strike> **Toggle** full screen mode
<strike>< Shift ></strike> F11 | <strike>enter</strike> **Toggle** full screen mode

**Comment by GitHubRulesOK** [comment]
@kjk if you are happy with the changes APART from the first one which as some issues of its own

Then I have changed the file for  my offline use but can be used to replace the online one

[manual.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4227398/manual.zip)

**Comment by kjk** [comment]
Thanks, I've updates the website with those changes.

**Comment by SumatraPeter** [comment]
@kjk: Left a couple of comments on the commit.

**Comment by kjk** [comment]
@SumatraPeter fixed the issues, thanks
