### ISSUE TITLE
Current build crashes on PDF when resizing zoom

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1238]
@kjk Whilst testing fit page fit-window etc. the attached file causes a crash when I select Zoom > Fit content checked in SumatraPDF-prerelease-11288-64 and-32 on latest win 10

[40001675C.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3853696/40001675C.pdf)

**Comment by kjk** [comment]
Thanks, should be fixed now.
