### ISSUE TITLE
This is not a bug report but my question: Why the latest build file size is much bigger?

### ISSUE THREAD

**Issue by ageback** [sumatrapdfreader/sumatrapdf#1239]
The standalone SumatraPDF.exe file size is about 30MB. It's much bigger than old versions like ver.3.1x. I'm just curious to know why? Could please the Author explain the reason?

**Comment by GitHubRulesOK** [comment]
@ageback I will let @kjk elaborate the full story

However as I understand it traditional pre-release are "much" bigger as they have both the unsupported features such as highlighting and also debugging /stress testing test code built in.

**Comment by kjk** [comment]
The big increase is because of more fonts and similar resources (like cmaps) needed to render more PDF files correctly.

This is unfortunate reality that PDF format is very complicated and those resources are needed to correctly render all possible PDF files.

We've inherited this from mupdf.
