### ISSUE TITLE
Found another one rip off Sumatra

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [sumatrapdfreader/sumatrapdf#124]
“[极速 PDF 阅读器] (http://jisupdf.com/)”(Jisu PDF reader) is created by take SumatraPDF's code, rename it, but they are not mentioned at their website.

To prove they it is a Sumatra rip-off, you can do these things as my way:
* Click the download link (立即下载, download right now) at their homepage to download and install, you can aiso extract JisuPdf.exe by 7-zip.
* Open this app by hex editor, search “Sumatra” and you will find it, this string can also find at SumatraPDF.exe.

**Comment by kjk** [comment]
Thanks for the pointer, unfortunately there's nothing we can do about it.

**Comment by KrasnayaPloshchad** [comment]
You can found ways to contact them from here:
http://www.jisupdf.com/?ac=linkus

**Comment by KrasnayaPloshchad** [comment]
@kjk
Well, you can put a notice into here:
http://www.sumatrapdfreader.org/ripoffs/list-of-sumatrapdf-ripoffs.html
