### ISSUE TITLE
Instant Crash with this file in latest builds

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1240]
The following file is handled well with version 3.2.11133 but will not load in either SumatraPDF-prerelease-11288-64 or -32

[EUROPE-political-map.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3853796/EUROPE-political-map.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk I would suggest to delete some debug reports such as this since the attachment would normally not be needed other than for your "black museum"

**Comment by kjk** [comment]
Not sure I follow. This was a bug I introduced when porting to new mupdf code that caused a crash.

**Comment by GitHubRulesOK** [comment]
I attached a file that I do not know its pedigree (it may not be public domain) but was necessary to illustrate a bug. now that the specific issue is addressed the file is of no general public value

**Comment by kjk** [comment]
I see, good point.

I deleted the file by editing the bug report (I think the creator of the issue could do that too).

**Comment by GitHubRulesOK** [comment]
I could have deleted the file once you acknowledged closure but until you had an oportunity to save was not sure if it was of value for your test suite, I also guess the longer its up there the more likely it is to be archived by trawlers
