### ISSUE TITLE
Latest build does not respect palmdoc bookmarks

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1242]
Probably very low priority as I have not seen anyone complain that they have had an issue :-)
Palm-docs are read correctly however the bookmarks appear to not work

[huckfinn.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3855107/huckfinn.zip)

LATER EDIT
Just to point out that the bookmarks **work in FixedPageUI but don't in ebookUI**

**Comment by kjk** [comment]
Yeah, seems like it always has been like this (i.e. doesn't work in 3.1.2 either).

**Comment by GitHubRulesOK** [comment]
Closing as not an issue in 3.4 pre-release using change to fixed UI
