### ISSUE TITLE
Chinese document code, after copying the symbol will become a half-width symbol

### ISSUE THREAD

**Issue by chen1jie** [sumatrapdfreader/sumatrapdf#1244]
I am learning java programming, using SumatraPDF to open the learning document copy code, the copied symbol will change from half-width symbol to full-width symbol, spacing and decimal point, but the code can not use full-width symbol, so I need to manually replace it with half-width symbol, I suggest I manually choose the alternative symbol format in the settings, I really like your software, if it can improve this problem, it is perfect.
(The above information uses Google Translate)
我正在学习java编程,使用SumatraPDF打开学习的文档复制代码,复制的符号会由半角符号变成全角符号,比如空格和小数点,但是代码并不能使用全角符号,所以我需要手动替换成半角符号,我建议在设置里面自己手动选择默认符号格式,我真的很喜欢你们的软件,如果能够改善这个问题,那就太完美了

**Comment by GitHubRulesOK** [comment]
If any of the following comments are not clear after translation please ask for re-wording.

1) Thank you for your request in English.

2) It will always help our understanding if you can add a sample document.

3) SumatraPDF currently has no programming control for content.

4) The content returned from selection within a document is placed there by the document Author.

5) Any decoding of that content would by necessity be processed by your external application.

**Comment by chen1jie** [comment]
Thanks Reply
After many tests I found that because of the problem with my documentation, not SumatraPDF

**Comment by SumatraPeter** [comment]
>  After many tests I found that because of the problem with my documentation, not SumatraPDF

In that case can you please close this issue?
