### ISSUE TITLE
bookmarks tree view doesn't adapt color in ebook view

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1247]
In 3.1.2 the background color of tree view with bookmarks (table of contents) matches the background color of text.

It regressed in master and is always white.

A test file e.g. in #1242

**Comment by GitHubRulesOK** [comment]
@kjk there were related issues raised that when a user sets the  background  to induce a form of night theme (inversion) that the "bookmarks" "favourites" & Properties etc. areas do not allow for the text content to follow the settings in the main body. Thus potentially leading to the issues of those areas having black text on black background (or low contrast) whilst the document is showing say white text on a black field

**Comment by kjk** [comment]
Thanks @GitHubRulesOK 
I've also synced text color of tree view which should fix this.
