### ISSUE TITLE
Tabs: Activities in non active tabs are lost after app is closed

### ISSUE THREAD

**Issue by pmic** [sumatrapdfreader/sumatrapdf#125]
When i'm reading a pdf file, after a few pages, i open different pdf and then close whole app (second file on top), progress made in first pdf file are lost. If this file is "active", after reopening, position is correct.

**Comment by GitHubRulesOK** [comment]
@kjk I cannot replicate this behaviour in latest pre-release versions such as 3.2.11133 or new build
was it a previous shortcoming ?

**Comment by kjk** [comment]
It's a very old bug report. Let's assume this was an issue at some point and was fixed.
