### ISSUE TITLE
Latest build crashes with a call to mail application

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1254]
@kjk Uncertain if this would affect all users but may affect many

I do not have an e-mail application (I use web mail) so mailto: calls do not work for me I also have noticed that some visible entries appear NOT to be activate (depending how they were constructed)
In fact the calls that worked well in 3.1.2 appear to not be active in latest release. Try email entries on first page of boxes.pdf

Uncertain if it happens in all cases but attempting to click on the mail entry in last page of dvisvgm file causes latest build to crash in x32 and x64 (similar behaviour has occurred in other files)

[boxes.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3865311/boxes.pdf)

**Comment by kjk** [comment]
Thanks, the crash should now be fixed.
Auto-detection of links is indeed busted for now.
