### ISSUE TITLE
Latest build does not respect all hyperlinks

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1255]
Thy hyperlink to a web page on cover page of attached file functions in 3.1.2 but does not work in latest builds
May (or may not) be related to other selection issues such as mailto and comments problems

[lyxmanual-en-2018-10-01.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/3865426/lyxmanual-en-2018-10-01.pdf)

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/23751c5925c3842417346fb0fa70b86e37abafe8
