### ISSUE TITLE
How to reduce libmupdf.dll size?

### ISSUE THREAD

**Issue by mohdimas** [sumatrapdfreader/sumatrapdf#1258]
How do I exclude some of the fonts so the libmupdf.dll size wont be so big? I tried uncommenting this line and below, but it didn't work https://github.com/sumatrapdfreader/sumatrapdf/blob/master/mupdf/include/mupdf/fitz/config.h#L63. Is it possible to do it?

**Comment by kjk** [comment]
That's a mupdf question. I'm sure it's possible to reduce size but I haven't looked into it.

**Comment by kjk** [comment]
In https://github.com/sumatrapdfreader/sumatrapdf/commit/49bb31896dfe9e41cd54919faac9666ee0c3839d I reduced the size by 20 MB by excluding a very large CJK font.

**Comment by mohdimas** [comment]
Thanks, I managed to build the libmupdf.dll without those fonts and it becomes 4-5MB. Here is the commit https://github.com/MailbirdInc/mupdf/commit/3941ef9a7b1d61b197105dcd8ae120e91c7b5aaa, but it's forked from mupdf.
