### ISSUE TITLE
Printing more than 1 copy does not work...

### ISSUE THREAD

**Issue by DimitriGruenwald** [sumatrapdfreader/sumatrapdf#1259]
Unfortunately, printing from the "printdialog" with the number of copies or from the command line with the "-print-settings" parameter does not work if the number is greater than one. Only one copy will ever be printed. I tested with the version 3.1.2 and 3.2.11133. Can you please debug and fix it?

**Comment by GitHubRulesOK** [comment]
I just wasted 2 tree branches testing dialog call to printer with "copies " set to 2 so standard dialog should always be working :-) are you using a command line call to the dialog ?
There have been various differences recently in user experience with command line calling, however you need to provide an example of your specific command call for us to see where it may not be functioning.

**Comment by DimitriGruenwald** [comment]
I have tried several versions. Here are a few examples:

SumatraPDF.exe "test.pdf" -print-to-default -print-settings 3x
SumatraPDF.exe "test.pdf" -print-to-default -print-settings "3x"
SumatraPDF.exe "test.pdf" -print-to-default -print-settings "1,3x"

I have already changed the order of the parameters.
I suspect the parameter devMode->dmCopies in the Printer.cpp is not used.

**Comment by GitHubRulesOK** [comment]
@DimitriGruenwald 
I took your first example and it worked perfectly for me (I got three pages as expected)

D:\SumatraPDF\3.1.2\x32>SumatraPDF.exe "test.pdf" -print-to-default -print-settings 3x

SO at this point I have to sugest it may be either a driver or comms issue.
What type of printer is default, on what operating system and is it on a remote server ?

**Comment by DimitriGruenwald** [comment]
The default printer is the old HP LaserJet 1320, which runs local on Windows 10 64-bit.

**Comment by GitHubRulesOK** [comment]
OK good to hear its local (remote can often be cause of problems)
I tested with a 3.1.2 x32 bit portable copy on an HP printer so will check 64bit portable, however can you double check if that version works with your default printer

**Comment by DimitriGruenwald** [comment]
Unfortunately, no luck. I just tested the 32-bit portable and 64-bit portable versions with the following command.

SumatraPDF.exe "test.pdf" -print-to-default-print-settings 2x

In both cases, only one copy is printed. :(

**Comment by GitHubRulesOK** [comment]
The reason we ask for exact command line is that there can be issues over syntax (Dos CLI is very unforgivving) If you are emulating my simple call and its not working in the same version then I have to stick with the suestion the windows call to driver or the driver is at fault.

at this point I would suggest switching default to another print driver such as "Microsoft Print to PDF" which should raise ONE call to save the output (and oddly build a 2 page file, not wjat most users expect) of course this only proves the 2x is passed and respected by a working driver.

SumatraPDF.exe "test.pdf" -print-to "Microsoft Print to PDF" -print-settings 2x

**Comment by DimitriGruenwald** [comment]
I think it's good that you are so thorough.

Fortunately, I was able to send the same command to various other physical printers. Once on the HP LaserJet P1102 and Brother HL-3172CDW. In both cases, two copies were printed. So the problem is actually with the driver for the HP LaserJet 1320. By the way, it's a PCL5.

I thank you for your help.

**Comment by GitHubRulesOK** [comment]
@DimitriGruenwald  glad to hear you have identified problem, can you please close issue as resolved
