### ISSUE TITLE
Cannot open protected CBR file

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [sumatrapdfreader/sumatrapdf#126]
I have downloaded a CBR file from here (click “View Raw” to download):
https://github.com/abbeycode/UnrarKit/blob/master/Example/protected.cbr

When I open with Sumatra PDF, the interface looks dark, when I open with WinRAR, I found this file is protected by password. Please fix for it.

**Comment by KrasnayaPloshchad** [comment]
I think Sumatra PDF should displaying a dialog to let user input the password if a comic book file is protected by password.

**Comment by KrasnayaPloshchad** [comment]
Sorry, this file was removed from original repository, I found this file from a older commit in there:

https://github.com/abbeycode/UnrarKit/blob/6940b0b221d552c312efaa9c0a521b0bc5019b23/Example/protected.cbr

**Comment by KrasnayaPloshchad** [comment]
#95

**Comment by GitHubRulesOK** [comment]
@kjk 
**Just an observation that there is an error in above cross reference to # 942 where the consolidation was supposed to be a link to # 1264 but for some odd reason it has cross linked here to # 126 !!**

**Comment by kjk** [comment]
This is indeed strange but I'm not sure if it's fixable. Maybe the reference was updated and GitHub cached the old reference.

**Comment by GitHubRulesOK** [comment]
@kjk 
> I'm not sure if it's fixable
I  see it was a bad truncated link on my part, which I just tried to edit and remove but it seems to have stuck, as you suggest it is possibly cached somewhere within the system.
