### ISSUE TITLE
Feature request to seperate ReuseInstance from UseTabs=true

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1260]
ReuseInstance has always been a strength of SumatraPDF (over other PDF viewers) especially for on the fly preview. [update] <strike>There are two current limitations that affect some users (PdfLaTeX editors in particular)

Less of an issue with modern machines and thus could possibly be doubled is the associated file locking memory limit of currently 10Mb.</strike> [Now 32Mb]

Command line control (reasonably) now appears to have depreciated, however the residual issue is that since the introduction of Tabs then the setting ReuseInstance = true has in effect been tied to UseTabs setting also being fixed as "= true"

What I am requesting is that currently calling a file repeatedly will correctly reuse that instance, however to reuse the same instance with another file requires tabs to be active so a second file can be shown in the working window, it would on occasion be useful without tabs active, to in a single working window (instance) replace the first file with a second file.
In order to retain control and compatability the command line call -reuse-instance would still be needed to distinguise from opening a second instance for the second file, much as it was.

**Comment by R-Usher** [comment]
I would prefer profiles like in Firefox.

**Comment by GitHubRulesOK** [comment]
@R-Usher I am not sure that profiles would be any use the idea of reuse-instance is **only one window**(instance)  for ALL FILES, perhaps the oposite to "profiles"

**Comment by SumatraPeter** [comment]
@R-Usher: You can approximate profiles by having multiple unique SumatraPDF-settings.txt files, but of course you'll have to switch them manually.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter & @R-Usher 
There are several ways to controle dual / multiple "instances" such as using the -appdata command
The Issue I am raising here is that Latex users (and others) need a LIMIT such as the -unique option in Ocular where nomater howmany ways the application is called there is one REPLACE old file with new

**Comment by GitHubRulesOK** [comment]
Closing as a duplicate of #1080
