### ISSUE TITLE
Latest daily builds not supporting gradient colors ?

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1262]
3.2.11346
I accept this was always "experimental" but some users found it useful in pre-releases

# Settings after this line have not been recognized by the current version
GradientColors = #2828aa #28aa28 #aa2828

**Comment by kjk** [comment]
It worked for me. When I added:
```
FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	GradientColors = #2828aa #28aa28 #aa2828
]
```
The background for PDF rendering (outside of the page) was a gradient that would change when advancing in the PDF.

I didn't write this originally and I'm not sure how exactly it's supposed to work, but it does changes the background.

**Comment by GitHubRulesOK** [comment]
@kjk Yes **I forgot it is position dependant** and only kept when found in the correct location otherwise if not in the correct place is shuffled to the end.
