### ISSUE TITLE
Java run print command is wrong

### ISSUE THREAD

**Issue by leven0106** [sumatrapdfreader/sumatrapdf#127]
! pdf-fontfile.c:377: fonterror : unsupported encoding (3/3)
- pdf-fontfile.c:528: ignoring face name decoding fonterror
! pdf-fontfile.c:377: fonterror : unsupported encoding (3/3)
- pdf-fontfile.c:528: ignoring face name decoding fonterror
! pdf-fontfile.c:813: couldn't find system font 'STSong-Light'
- pdf-fontfile.c:815: loading non-embedded font 'SimSun' from 'C:\Windows\Fonts\
simsun.ttc'
- font.c:63: not building glyph bbox table for font 'SimSun' with 28762 glyphs

My environment:win 7 x64

**Comment by kjk** [comment]
I don't understand what you're saying here.

**Comment by KrasnayaPloshchad** [comment]
Which file made this error? Can you show this file to us?
