### ISSUE TITLE
My bad :-)  crashed latest build

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1272]
As usuall pushing beyond expectations
I took a known problem file from issue #842
and right click exported bookmarks sometimes worked (with expected non cyrillic characters)
sometimes crashed ? recent 3.2.11399

**Comment by kjk** [comment]
Exported bookmarks a couple of times, didn't get a crash so far. Will keep trying.

**Comment by GitHubRulesOK** [comment]
@kjk possible either chm (chm viewer) or bookmark file (notepad) was open in background, will see if I can replicate

**Comment by GitHubRulesOK** [comment]
@kjk Nope holding files open in background does not appear to be reason tried about a dozon ways to force issue but it randomly crashed only one of those times this not a repeatable problem !!

**Comment by GitHubRulesOK** [comment]
Hmm just tried exporting bookmarks from that file multiple times both x64 and x32 on x64 win 10 without crash perhaps it is not that action after all, but if not then what?
Side issue rightclick export bookmarks shows dialog with OK button, easy to not click that one and have it hidden behind application then repeating action is allowed with a second dialog etc. etc.

**Comment by GitHubRulesOK** [comment]
@kjk see comment re duplication of dialog boxes, however as I cant replicate the prime issue as such you can close for now?
