### ISSUE TITLE
Display the PDF DPI

### ISSUE THREAD

**Issue by 07416** [sumatrapdfreader/sumatrapdf#1273]
Can Sumatra display the current file's DPI, when available? This data isn't shown in file > properties.

**Comment by GitHubRulesOK** [comment]
I am not sure there is anything meaningfull to display here, A PDF alone (may not have) does not really set DPI rather it is using the various "DPI" values of any embeded images translated to the documents dimentions usually calculated as "Points" then re-rendered as screen "DPI"  which can be modified variously by user screen resolution settings. Similarilly for comic books etc the variable JPG PNG etc "DPI" values are in effect irrelevant, at best they may define a nominal page dimension, most simply affecting the percieved quality of zooming in general to a variable value of window/screen high image etc.

@kjk I am guessing this request as it stands falls into "can't" fix as there would be no consistent  measurable output ?

**Comment by GitHubRulesOK** [comment]
Since this duplicates one of the 3 requests in #498 I am closing this as partial duplicate
