### ISSUE TITLE
Get message

### ISSUE THREAD

**Issue by lanhktc** [sumatrapdfreader/sumatrapdf#1274]
Hi, 
how do I get an error message when I run a command using php?

**Comment by GitHubRulesOK** [comment]
? are sure your question is related to SumatraPDF application which does not use PHP as such !

**Comment by SumatraPeter** [comment]
I'm guessing he's trying to call Sumatra with certain command-line params or using DDE commands from his PHP code. In either case @kjk this seems more like a question suited to a PHP programming forum/help site?

**Comment by kjk** [comment]
Sumatra is a windows program. There is no way to return error messages. You can check exit code to see if it's 0 (no problem) or 1 (error). You can also try to capture stdin and stdout to see whatever mupdf and we print there but this is a PHP question and I haven't actually verified this is possible.
