### ISSUE TITLE
Popup preview of PDF links

### ISSUE THREAD

**Issue by alexshtf** [sumatrapdfreader/sumatrapdf#128]
I have been reading a lot of scientific papers lately, and I would like to be able to see a small popup with the linked content when I hover over a PDF link. Usually, when there is a link to an equation of a theorem I don't want to go there, I just want a short reminder and continue reading. I believe that many people who read scientific papers would benefit.

It is something similar to Visual Studio's Peek Definition feature (http://channel9.msdn.com/Series/Visual-Studio-2012-Premium-and-Ultimate-Overview/Peek-Definition)

**Comment by kjk** [comment]
Unfortunately it's too complicated. I don't see us implementing that.
