### ISSUE TITLE
PDFs diplayed without first page

### ISSUE THREAD

**Issue by R-Usher** [sumatrapdfreader/sumatrapdf#1282]
Look at 2 PDFs here: https://1drv.ms/f/s!AKm4ZaWdL2tfgi8
Switch view to tiles and you can see that both files are displayed properly. SumatraPDF 3.1.2 also has no problem, but all builds with new muPDF engine don't display the first page in one PDF.

**Comment by R-Usher** [comment]
Cannot edit the message, so I add that those PDFs contain scans and the first page is displayed blank in no-cover file.

**Comment by GitHubRulesOK** [comment]
@kjk my tests show that the problem file isg MuPDF upto and including version "web optimised" (linearised) and read by Acrobat 9 and some other applications (mainly web orientated, However some desktop readers including Version 1.16 do not display the initial page 
Suggest this issue is taged "MuPDF" and perhaps a bug report raised

**Comment by R-Usher** [comment]
1. There is PDF1.4 standard declared for this PDF. I can convert pdf to epub using old calibre 1.4.8 with no problem so there should be no problem also for other software as it's nothing new here.

2. This PDF has been generated by some scanner software used with default settings. It's highly possible that many users will report similar problems in the future so the bug should be fixed in the nearest future.

I can upload a few more PDFs with this problem, if needed.

**Comment by GitHubRulesOK** [comment]
@R-Usher 
Please try the latest [daily build](https://www.sumatrapdfreader.org/dailybuilds.html) since my recent tests suggest this is now again handled well enough to show the front cover

**Comment by GitHubRulesOK** [comment]
Closing as not a problem in 3.1.2 or 3.2
