### ISSUE TITLE
New build suggestions re Toggle ebook UI

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1284]
@kjk I find the debug option to **"Toggle ebook UI" very useful** (allows opening file with other extensions _kindle.azw3 annotated.txt error.log_ etc.) and **very much hope** it will be included in final release, however some usage / users may raise support questions

[Minor issue over nomenclature]
When I toggle to "true" (my interpretation of checked) then it has changed the settings file to false :-)
that is the UseFixedPageUI = is naturally opposite
 so a suggestion is to lable as perhaps **Toggle ebook UI to FixedPage** or **Set ebook UI to FixedPage** OR perhaps I could reverse my "false" expectatation with a check simply signifying "Use ebook UI" but that means reversing the action ?

[Feature Request]
There is a minor niggle that the setting requires [R] to refresh / reload the setting such that the change takes affect, this will be most pertinent to tablet users where it is difficult to find the hotkey

I Note that an automatic refresh across ALL tabs could cause a cascade of error messages due to the difference in file name support between the two modes see discussion in #849 where extensions such as .epub3 (and others such as .txt .log) are not recognised in ebook UI
Thus either the refresh could be confined to the one tab (BUT it is best to refresh UI across all tabs)  OR autorefresh all open tabs HOWEVER if there are many large ebooks active the regeneration of multiple tabs could be horredously slow

**Comment by R-Usher** [comment]
[Nomenclature]
"Toggle" means - revert current state, always switch to another one. Maybe "Use FixedPage UI for ebooks" will be better?

[Feature]
What about refreshing currently active tab and autorefreshing other tabs only when they are selected?

**Comment by GitHubRulesOK** [comment]
@R-Usher 
[Nomenclature]
I could probably accept / understand your wording
[Feature]
As you suggest Auto refresh by selecting tab would probably be best, but its only needed after switching interface so perhaps an internal status flag set when "UI toggled" would avoid undue refresh when tabs are selected without an interface change.

**Comment by R-Usher** [comment]
It's enough to keep IDs/flags temporarily, during current session only. To avoid flipping UI here-and-there I would rather implement features missing in ebook UI (find, select and mark text, etc.).

**Comment by GitHubRulesOK** [comment]
@R-Usher the extra features in ebook mode are a seperate deeper topic since epub reflowing text is difficult to tie down in position for selection especially highlighting hence the need for "fixed" mode where highlighting search zoom etc are working.

**Comment by GitHubRulesOK** [comment]
Closing as legacy issue, no longer relavant
