### ISSUE TITLE
[Prerelease 11482] Unable to Install

### ISSUE THREAD

**Issue by Xashyar** [sumatrapdfreader/sumatrapdf#1285]
![image](https://user-images.githubusercontent.com/34171942/69999982-30a69c80-156f-11ea-8662-3be87fdc0891.png)

Tried reinstalling and still facing the same error.
Windows 10, 1909

**Comment by kjk** [comment]
Could you describe how did you install and uninstall?

**Comment by Xashyar** [comment]
> 
> 
> Could you describe how did you install and uninstall?

From the Control Panel, but I did get the same error before I uninstalled the previous pre-release.

**Comment by GitHubRulesOK** [comment]
@kjk the "installer" seems to just be the main reader I also note /x default seems to have changed from syswow64 to system32 ??

**Comment by Xashyar** [comment]
Although I gotta add, I couldn't see the yellow uninstall interface buttons clearly (4k, 15.6', 250% scaling) so I hit some tab/space buttons until it got uninstalled and disappeared from the list.

**Comment by SumatraPeter** [comment]
> I couldn't see the yellow uninstall interface buttons clearly

Uh oh, did the manifest not completely fix #1221 @kjk?

**Comment by Xashyar** [comment]
> 
> 
> > I couldn't see the yellow uninstall interface buttons clearly
> 
> Uh oh, did the manifest not completely fix #1221 @kjk?

I experienced the scaling issue with the 11133 pre-release uninstall/install interface, haven't got to try 11482 yet.

**Comment by GitHubRulesOK** [comment]
@Xashyar I suspect since the new downloads are borked your uninstaller was the 11133 build I am reluctant to point you at an older install / uninstall since it could worsen matters
 I am giving kjk the run arround on related issues so he is feveroushly changing things in the backroom
 so will await his return to this topic

**Comment by kjk** [comment]
I did indeed break the installer. Should be fixed in 11486 and later.
