### ISSUE TITLE
Show page location more persistently in Full-Screen mode

### ISSUE THREAD

**Issue by Xashyar** [sumatrapdfreader/sumatrapdf#1286]
In full screen, after pressing `i` on keyboard, page location is displayed on the top left of the screen but it flickers while scrolling and disappears very quickly.
So the request is:
1. Less flicker while scrolling
2. Longer timeout duration or a user assignable value.

**Comment by SumatraPeter** [comment]
**Im**possible? Sure, but only if you don't bother to check the [manual](https://www.sumatrapdfreader.org/manual.html) and read about what pressing **i** does! 😉

**Comment by Xashyar** [comment]
> 
> 
> **Im**possible? Sure, but only if you don't bother to check the [manual](https://www.sumatrapdfreader.org/manual.html) and read about what pressing **i** does! 😉

Thanks!

**Comment by R-Usher** [comment]
Maybe it's closed too early.  Could this feature be persistent or have timeout settable?  Currently it's displayed for a short time.

**Comment by Xashyar** [comment]
> 
> 
> Maybe it's closed too early. Could this feature be persistent or have timeout settable? Currently it's displayed for a short time.

Great Idea I updated the issue by adding to mention the eye stuttering flickers.
