### ISSUE TITLE
Question about latest installer

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1287]
@kjk I am happy/impressed that the work on installer has progress so much recently

Currently the latest installation for a Win10 home user appears to be split between

C:\Users\Username\AppData\Local\SumatraPDF = executables and dlls ?
C:\Users\Username\AppData\Roaming\SumatraPDF = crashdump and settings ?

That raises a question about a shared installation i.e. does each user need a copy of the exe/dll files
Previously 32bit and 64bit were in seperate Program Files [(x86)] 
Which was potentialy useful for multiple users with a 64bit user running 32bit outlook

**Comment by kjk** [comment]
I just changed things so it's always `C:\Users\Username\AppData\Local\SumatraPDF`.

Installing both 32bit and 64bit at the same time is not a supported scenario.

**Comment by SumatraPeter** [comment]
@kjk: Is installing to `%LocalAppdata%\SumatraPDF` simply a testing thing or is that the new permanent location for the program? And if the latter, may I ask why it was changed from the standard Program Files scenario?

**Comment by kjk** [comment]
It's a new location. Writing to program files requires elevation / admin rights which is why a lot of software moved to %LocalAppdata% (Chrome, Visual Studio Code).

**Comment by SumatraPeter** [comment]
AFAIK [Chrome moved back to Program Files](https://groups.google.com/a/chromium.org/forum/#!msg/chromium-discuss/MrfbaVTH4NM/0v_QhBdDmPQJ) more than 7 years ago, and only falls back to AppData if the former fails or the user selects No when prompted by UAC.

I honestly think it's the wrong way to go as a default, but as long as the latest installer still allows the user to change the install location it's _somewhat_ fine I suppose. If there's no such option and the installer simply dumps the app into LocalAppData then I think it's a really, _really_ regressive change. We don't want to follow in MS' stupid footsteps such as with Office CTR for example. Thankfully for now [VS Code has both](https://code.visualstudio.com/docs/setup/windows) user (LocalAppData) and system (Program Files) installers available. It's not ideal (a single installer could have sufficed), but at least it's there for users that prefer one or the other.

I haven't tested the latest installers yet (only checking out the portable daily builds for now), but I sincerely hope you'll revisit this and revert to Program Files as the default, and/or ensure that the installers still allow users the freedom to decide where exactly the app should end up on their systems.

**Comment by kysko** [comment]
My VSCode is in `Program Files`, went there by default.
Might as well make `SumatraPDF` a portable version by default otherwise.

In any case, I'm grateful for the necessary `mupdf` update/upgrade.
