### ISSUE TITLE
Warning for closing Sumutra PDF when mutltiple tabs open

### ISSUE THREAD

**Issue by LeFrench** [sumatrapdfreader/sumatrapdf#129]
Can you introduce an optional warning message for closing multiple tabs when closing Sumutra? I have lost count of the number of times I have closed numerous open tabs instead of shutting the tab I was finished with.

As an aside though - great program!

**Comment by ousia** [comment]
:+1:

**Comment by gschenck** [comment]
Since bd441539257ca5e0d070423ea765c7d56b1fcd1b (prerelease version ~ 10079) there is a feature to automatically restore your session at startup.
You can grab the prerelease at http://www.sumatrapdfreader.org/prerelease.html

**Comment by debjan** [comment]
I'm using prerelease version and wanted to suggest following. 

With this new option turned on, if I open `file1.pdf` and then close SumatraPDF, then open the same `file1.pdf` again, I get two tabs with the same file. IMHO, this enhancement should check if opening file was already opened in restored session and switch if already present. 

Even more I think that restoring session that contains just a single file is unnecessary and I would appreciate if this feature ignores restoring session of single file, or provide option.
For example, if `RestoreSession = auto` then please make it ignore reopening session containing single file, and then if `RestoreSession = on` make it restore sessions with even single file if such feature seems reasonable to others.

Thanks

**Comment by kjk** [comment]
We now re-open all files on startup if window with more than one tab was closed, which should make the warning not needed.
