### ISSUE TITLE
Add "Factory Reset" / "Safe Mode"

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1292]
Whilst testing I can often encounter conditions where attempting  to open new files gives the impression of continous failure to launch SumatraPDF.
It has nothing to do with the new files it is the fact that auto rendering a recent active file/tab is causing the problem, although it behaved well enough when it was last read.

What can be done so as to reset SumatraPDF to a stable state is to delete the settings file, but that results in loosing the good history, The prefered option would be to have a command line option that starts SumatraPDF in "Safe mode" so that each tab can be refreshed in turn to detect and allow for closing the culprit.

**Comment by kjk** [comment]
Doesn't seem like this would be needed by many people.

As a work-around: one can copy the history part, delete settings file and paste the history part at the end.
