### ISSUE TITLE
Sumatra Nightly shows only emtpy squares if one of the 14 base fonts is used and this font is NOT embedded within the PDF

### ISSUE THREAD

**Issue by coolsurfer** [sumatrapdfreader/sumatrapdf#1295]
If PDF uses one of the 14 base fonts

        Uses Base 14 fonts not embedded in document: 
            Helvetica (6 instances)
            Helvetica-Bold (3 instances)

Sumatra Nightly (and also SumatraPDF-prerelease-11515) only shows wired squares instead of "letters". It's working with the RELEASE version SumatraPDF-3.1.2. If the fonts are embedded it's also working fine, but ref to ISO 32000-1:2008(E) they do not have to be embedded.

**Comment by kjk** [comment]
Could you provide a sample document showing a problem?

**Comment by coolsurfer** [comment]
I can. But i cannot provide anywhere where anybody can download it cause it contains sensitive data. I need to be sure that nobody except you ever sees the document :-)

**Comment by kjk** [comment]
I got it, thanks. Will keep it private.
