### ISSUE TITLE
"-print-to" command line not working in 11521

### ISSUE THREAD

**Issue by coolsurfer** [sumatrapdfreader/sumatrapdf#1296]
SumatraPDF-11521-64.exe -print-to "ECOSYS M5526CDW KX" -print-settings "bin=manual,portrait,1x" 1575538704462.pdf

SumatraPDF-11521-64.exe -print-to "ECOSYS M5526CDW KX" -print-settings "bin=manual,landscape,1x" 1575538704462.pdf

called multiple times results in error. Sometimes error occours on first call somtetimes it needs some more until "Printer not found" pops up.

Would be cool if you can take a look into it. Last known working Verison was 11336. Using 32-bit Version results in the same behaviour

**Comment by kjk** [comment]
Thanks, should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/8adbc330bdc46b492a4477b2a58a9df5a7e1a5da
