### ISSUE TITLE
Latest build 11521 crashes on opening epub in FixedUI

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1297]
@kjk If I start and open an epub with the  setting UseFixedPageUI = true
OR toggle EpubUI to use Fixed and refresh
Then SumatraPDF 11521 x64 will crash on even the smallest test book [testbook.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3927235/testbook.zip)

Back testing  11501, 11495 and earlier had problems on larger mobi and some epub files when atempting [R] key refreshing after changing mode bottom bar shows as 

> Formatting the book ... ###pages

 within the session even though I can jump and navigate throuh content so basic issue may have arisen in much earlier commit

**Comment by kjk** [comment]
If you get a crash, could you also:
* press 'Cancel' when a crash notification message box shows
* this should open a default text editor (like Notepad) with crash report
* copy the content of crash report and post as a Gist https://gist.github.com/
* link the gist to the bug report

Alternatively, attach the crash report (it's saved into %LOCALAPPDATA%\SumatraPDF\crashinfo) as a file to the bug.

(the reason to link a gist vs. pasting the content is that GitHub's UI for issues is very narrow, so it's hard to see large files)

**Comment by kjk** [comment]
Thanks, should be fixed now.
