### ISSUE TITLE
Copying text to clipboard is broken (blanks shouldn't be removed)

### ISSUE THREAD

**Issue by Fish-Git** [sumatrapdfreader/sumatrapdf#130]
My PDF file contains the following text stream:

    stream
    BT
    /F0 12 Tf
    18 746.5 Td
    12 TL
    (// JOB PAUSEBG                                                          DATE 03/12/87,CLOCK 14/19/05) Tj T*
    (// PAUSE) Tj T*
    (* THIS IS A TEST) Tj T*
    (*  THIS   IS    YET     ANOTHER      TEST        *) Tj T*
    (* THIS IS A TEST *) Tj T*
    (EOJ PAUSEBG                                                             DATE 03/12/87,CLOCK 14/19/50,DURATION 00/00/45) Tj T*
    ET
    endstream

When I view the PDF using Sumatra and select and copy the second line of text above to the clipboard and then paste it into notepad, I get the following:

    * THIS IS YET ANOTHER TEST *

_This is wrong!_

What _should_ be copied and pasted to/from the clipboard is the following:

    *  THIS   IS    YET     ANOTHER      TEST        *

Some PDF files contain program source code or tables or other text whose specific formatting is _very important_ to the user.

In my opinion all text with the PDF "Tj" order's parentheses should be copied to the clipboard _AS IS_. You should _not_ be arbitrarily removing intervening blanks between words, _NOR_ should you remove any trailing blanks or preceding blanks either.

Text should always be copied to the clipboard _as is_.

Thanks.

Other than that, Sumatra PDF _rocks!_ Thank you for a nice product and keep up the good work.

"Fish" (David B. Trout)
david.b.trout@gmail.com

**Comment by kjk** [comment]
Copying from PDFs is inherently unreliable and we apply heuristics to make it work the way most people expect. What we do currently is a better way most of the time.
