### ISSUE TITLE
Frequently read front screen active and opening a few files leads to a random crash

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1300]
Testing how well favourites work across multiple formats
Mainly on the home page with no tabs active but favorites showing
opening a group of files (or sometimes adding another without any favorites) got a crash
culprit files included in case one is rogue
[collection.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3930269/collection.zip)

crash report
https://gist.github.com/GitHubRulesOK/9c4e193f8f50ad48c8b45eb884907bc6

**Comment by kjk** [comment]
It wasn't caused by the file.
In pre-release builds I have sanity checks that check for conditions that I think shouldn't happen and cause a crash if they do.
Those crashes are not present in release builds.
This particular condition is benign so I just made it not crash there.
