### ISSUE TITLE
Fails to properly display cb7 wth lots of images / large dictionary

### ISSUE THREAD

**Issue by sam896** [sumatrapdfreader/sumatrapdf#1305]
Trying to read a large (~80MB) cb7, it failed and left me with black pages.

It got the right number of pages so it's getting somewhere, but reported a page size of 0 by 0cm.

Experimenting a little, it seems to be a problem using PPMD compression with large dictionary and lots of pages. Changing the compression method or using just a few pages worked.

Sample file [sampleinside.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3934334/sampleinside.zip) (you'll need to extract the cb7 inside the zip - the forum wouldn't allow the file type to be attached directly). This is just one image repeated for each page so that it compresses to a small example, but I got the same sort of result with more typical cb7 files.

**Comment by kjk** [comment]
It works for me with latest daily build https://www.sumatrapdfreader.org/dailybuilds.html

It's just uses ~2 GB of memory while decompressing the file so most likely your computer doesn't have enough memory to unpack the files.

**Comment by GitHubRulesOK** [comment]
The file attached is not a real world example it is less than 1MB compressed and 180MB decompressed however it will convert to a 158MB compressed cbz which reads with no perceptable problems a black page is only shown whilst jumping rapidly from page to page e.g. holding down the space bar.
current pre-release says there are 730 pages of an image 24.92 x 35.27 cm
since each page is identical in a cb7 there is probably only one copy then 729 references of zero dimensions
Best to

**Comment by sam896** [comment]
To confirm... yes, that latest daily build (and the 11669 pre-release) are fine with that sort of cb7, both the small sample I supplied and the larger file I originally tried to view. Whatever changes were made since the 3.1.2 release have fixed the problem.

Presumably wasn't a lack of memory issue as it's the same computer it failed on earlier, which in any case had lots more than 2GB of RAM.

**Comment by GitHubRulesOK** [comment]
@sam896 
Thanks for confirmatory feedback
The 2GB of ram is not the machine total physicalmemory
 it is more the need for that amount of free resource at the time of decompressing which may not be available if other memory hogging applications are also running in the background. Thus may appear only intermittently.
