### ISSUE TITLE
Random crash whilst attempting open/closing a number of files

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1306]
Testing behaviors of opening multiple mixed files
so tried opening as folder
 dropping directory
file open > select first > hold shift > select last
 etc
 using a group of both supported and unsupported files

Yes who would in their right mind do such a thing,?
any way here are the small files in question except for the handful of big ones that were from past issues (location is hinted in folder names from end of settings history)

**Comment by kjk** [comment]
I can't reproduce this locally.

From the crash report it looks like it's caused by one of the PDF files with .jp2 image, but I can't tell which one and none of them are included in mixed.zip

How reliable is the crash? Every time? One out of N? Only happened once?

If you can reproduce it multiple times, can you try to narrow down it to the file that crashes and share that file?

**Comment by GitHubRulesOK** [comment]
ok I suspected it could be related to jp2 but as it was infrequent and random did not know what to exclude I will try to see if I can narrow it down.

**Comment by GitHubRulesOK** [comment]
@kjk sorry the zip only contained one file the others got excluded in trying to isolate the problem 
you may have seen several reported crashes as I tried to segregate groups of files but with no clear culprit even trying multiplying each sub group and now that initial group reasembled is not misbehaving ! What I noted is that after about a dozen files there is a long pause then the remaining 
[mixed.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3935768/mixed.zip)
files appear to open quickly after that?

**Comment by kjk** [comment]
I can reproduce the problem. It happens when dropping 2 or more PDF files with jp2 images in them.

I understand why this happens, still thinking about the best fix.

**Comment by kjk** [comment]
This is somewhat a mupdf issue: https://bugs.ghostscript.com/show_bug.cgi?id=701978

Let's see if they fix it. If not, I can patch mupdf, the fix is easy enough.
