### ISSUE TITLE
Password list for secured PDF files

### ISSUE THREAD

**Issue by IgitBuh** [sumatrapdfreader/sumatrapdf#1308]
I frequently receive PDF files that are encrypted with the same passwords (for each source). Each password is too complicated to manually type in, so I need to copy it manually from a password manager. This makes it rather complicated to open such a PDF file.

SumatraPDF offers the possibility to store a password per file, which doesn't help in my case, but might ba a good starting point.

What I wish for, would be a name/password list in the preferences what is then displayed as a dropdown selection (showing only the names) in a password dialog. Any chance this could be implemented?

**Comment by GitHubRulesOK** [comment]
I think the passwords list stored in the settings file should cover your usage since you say "same passwords (for each source)"

a whitespace separated list of passwords to try when opening a password protected document
(passwords containing spaces must be quoted) (introduced in version 2.4)
DefaultPasswords =

**Comment by IgitBuh** [comment]
Wow, this does indeed work for me!
I didn't think that this kind of feature is already available because I couldn't find it anywhere in the UI. It didn't come to my mind that it might be available as a "hidden" feature by editing the settings file manually.

I now see the [settings file documentation](https://www.sumatrapdfreader.org/settings3.2.html) and am wondering why many settings are not included in the UI. Wouldn't it make sense to have a feature like this in the preferences dialog?

**Comment by GitHubRulesOK** [comment]
SumatraPDF philosophy was always aimed to maximise screen and minimise controls to hot keys, however try using MuPDF without any visual cues and its tough

So add a zoom button and a couple of icons then next thing you know users want to open two views of a file so add tabs and support stupidly encrypted files and then its version 3.123456

As this rarely used feature works for you, can you please consider closing. Thanks

**Comment by IgitBuh** [comment]
I understand the dilemma!
I've installed SumatraPDF on many systems of family and friends already, because it's clean, fast, easy to use, but at the same time it is capable of processing all kinds of PDFs correctly.

In my opinion adding all already available options to the preferences dialog wouldn't cause any harm to the user experience or philosophy, because the actual UI wouldn't be touched at all. In contrast, it would simply make all features accessible to the users.

I'll close this issue, but maybe updating the preferences dialog would be something to think about?

**Comment by GitHubRulesOK** [comment]
@IgitBuh Thanks for closing
@kjk another request to expose deeper settings values via menu Interface
