### ISSUE TITLE
On Windows, v3.0: copy to clipboard does not work correct

### ISSUE THREAD

**Issue by ilyaza** [sumatrapdfreader/sumatrapdf#131]
With
  http://ilyaz.org/fonts/coverage-all.txt%20-%20Notepad%20Unifont%20Smooth%207.0.06--1.141%20(size%2019).pdf
when I do C-a C-c, the resulting clipboard contains a lot of question marks (near the end of clipboard).

Doing the same in AcroRead (where C-a is page-wise!) does not have this problem.  The font in question has ‘uDDDDD’-slyled glyph names.

**Comment by kjk** [comment]
You would have to be more specific:
* which page is this
* screenshot of the text you're selecting
* screenshot of how the text looks when using Adobe Reader to copy&paste
* screenshot of how the text looks when using Sumatra to copy&paste

I tried to copy text from last 2 pages. Both Sumatra and Adobe Reader

**Comment by ilyaza** [comment]
[Your message was not terminated]

I go to the last page, and select from (8) to (0).  Then paste.

SumatraPDF (these are real U+003F):
⑻??????????????????????????????????????
??????????????????????????????????????
???????????????????????????????????????
???????????????????????????????
===================== 0e
⓪

Acrobat (U+10ECB5 etc instead of U+1F800 etc):
⑻􎲵􎲶􎲷􎲸􎲹􎲺􎲻􎲼􎲽􎲾􎲿􎳀􎳁􎳂􎳃􎳄􎳅􎳆􎳇􎳈􎳉􎳊􎳋􎳌􎳍􎳎􎳏􎳐􎳑􎳒􎳓􎳔􎳕􎳖􎳗􎳘􎳙􎳚
􎳜􎳝􎳞􎳟􎳠􎳡􎳢􎳣􎳤􎳥􎳦􎳧􎳨􎳩􎳪􎳫􎳬􎳭􎳮􎳯􎳰􎳱􎳲􎳳􎳴􎳵􎳶􎳷􎳸􎳹􎳺􎳻􎳼􎳽􎳾􎳿􎴀􎴁
􎴂􎴃􎴄􎴅􎴆􎴇􎴈􎴉􎴊􎴋􎴌􎴍􎴎􎴏􎴐􎴑􎴒􎴓􎴔􎴕􎴖􎴗􎴘􎴙􎴚􎴛􎴜􎴝􎴞􎴟􎴠􎴡􎴢􎴣􎴤􎴥􎴦􎴧􎴨
􎴪􎴫􎴬􎴭􎴮􎴯􎴰􎴱􎴲􎴳􎴴􎴵􎴶􎴷􎴸􎴹􎴺􎴻􎴼􎴽􎴾􎴿􎵀􎵁􎵂􎵃􎵄􎵅􎵆􎵇􎵈
===================== 0e
⓪

Both produce garbage indeed.  Can this be fixed?

**Comment by ilyaza** [comment]
Both start producing garbage after U+84ce (32K limit exceeded?).  Page 34, paragraph after (4):


⑷萀萁萂萃萄萅萆萇萈萉萊萋萌萍萎萏萐萑萒萓萔萕萖萗萘萙萚萛萜萝萞萟萠萡萢萣萤营
萦萧萨萩萪萫萬萭萮萯萰萱萲萳萴萵萶萷萸萹萺萻萼落萾萿葀葁葂葃葄葅葆葇葈葉葊葋葌
葍葎葏葐葑葒葓葔葕葖著葘葙葚葛葜葝葞葟葠葡葢董葤葥葦葧葨葩葪葫葬葭葮葯葰葱葲葳
葴葵葶葷葸葹葺葻葼葽葾葿蒀蒁蒂蒃蒄蒅蒆蒇蒈蒉蒊蒋蒌蒍蒎蒏蒐蒑蒒蒓蒔蒕蒖蒗蒘蒙
蒚蒛蒜蒝蒞蒟蒠蒡蒢蒣蒤蒥蒦蒧蒨蒩蒪蒫蒬蒭蒮蒯蒰蒱蒲蒳蒴蒵蒶蒷蒸蒹蒺蒻蒼蒽蒾蒿蓀
蓁蓂蓃蓄蓅蓆蓇蓈蓉蓊蓋蓌蓍蓎????????????????????????
??????????蓱??????????????

⑷菎菏菐菑菒菓菔菕菖菗菘菙菚菛菜菝菞菟菠菡菢菣菤菥菦菧菨菩菪菫菬菭菮華菰菱菲菳
菴菵菶菷菸菹菺菻菼菽菾菿萀萁萂萃萄萅萆萇萈萉萊萋萌萍萎萏萐萑萒萓萔萕萖萗萘萙萚
萛萜萝萞萟萠萡萢萣萤营萦萧萨萩萪萫萬萭萮萯萰萱萲萳萴萵萶萷萸萹萺萻萼落萾萿葀葁
葂葃葄葅葆葇葈葉葊葋葌葍葎葏葐葑葒葓葔葕葖著葘葙葚葛葜葝葞葟葠葡葢董葤葥葦葧
葨葩葪葫葬葭葮葯葰葱葲葳葴葵葶葷葸葹葺葻葼葽葾葿蒀蒁蒂蒃蒄蒅蒆蒇蒈蒉蒊蒋蒌蒍蒎
蒏蒐蒑蒒蒓蒔蒕蒖蒗蒘蒙蒚蒛蓎􇼁􇼂􇼃􇼄􇼅􇼆􇼇􇼈􇼉􇼊􇼋􇼌􇼍􇼎􇼏􇼐􇼑􇼒􇼓􇼔􇼕􇼖􇼗􇼘
􇼙􇼚􇼛􇼜􇼝􇼞􇼟􇼠􇼡􇼢蓱􇼤􇼥􇼦􇼧􇼨􇼩􇼪􇼫􇼬􇼭􇼮􇼯􇼰􇼱

**Comment by kjk** [comment]
We can't do better than Adobe. This PDF is partially malformed and that's why text extraction fails.

**Comment by ilyaza** [comment]
Note that Adobe is BETTER.  It assigns different integers (not Unicode codepoints!) to different glyphs.  In principle, the result MAY BE “decipherable”.

======

The document was created with PDFCreator.  Apparently, it put the second half of 60K-glyphs font into a font subset you called “malformed”.  In your opinion, is it an inherent problem with large fonts, or could PDFCreator do a better job?

Essentially: does it make sense to file a bug report with PDFCreator?

**Comment by kjk** [comment]
I think that if PDFCreator creator created this file, then they have a bug.
