### ISSUE TITLE
fix windows-1252.mobi

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1317]
A sample in https://github.com/bfabiszewski/libmobi/tree/public/tests/samples

The text is completely messed up probably because the encoding is not correctly detected.

See if we can improve it.

**Comment by GitHubRulesOK** [comment]
@kjk the text is odd as it seems to be verse like and seems there are regular hard line feeds possibly based on a set font and page width and not specifically designed for reflow. here is a side by side comparison with STDU viewer at similar zoom etc.
![image](https://user-images.githubusercontent.com/12754913/70763671-cbac2d00-1d4c-11ea-998e-7ac2a0ee5e64.png)

**Comment by SumatraPeter** [comment]
They're ancient Sanskrit verses transliterated using the Latin alphabet. This issue can be closed as there seems to be nothing wrong with the text being displayed.

**Comment by GitHubRulesOK** [comment]
Closing as non issue
