### ISSUE TITLE
Option to keep viewport upon change of page.

### ISSUE THREAD

**Issue by pglpm** [sumatrapdfreader/sumatrapdf#132]
Hi and thank you for SumatraPDF. I think this feature was requested before, but I don't find it among the open requests:

Request: Option to maintain viewport (x,y coordinates of documents with respect to SumatraPDF window borders) as well as zoom level, upon change of page.

Reason: Sumatra has a very convenient "Fit content" (ctrl+3) viewing mode that allows us to view the whole page at maximum possible zoom. But there are many badly-formatted pdfs (40%–50% in my experience) for which this viewing mode does not work well, since SumatraPDF can't discern their "effective" content. For example:

– some pdfs with wrong bounding boxes, for which SumatraPDF shows the empty margins in "fit content" mode, thinking that there's text there;

– pdfs with copyright or other metadata written on the margins, uninteresting for the reader, but yet brought into view by "fit content" mode.

In cases like these the "Fit content" mode won't work as meant – again, not because of SumatraPDF's fault. 

For these cases the best option would be to maintain the viewport coordinates and zoom upon page change, after the user has found the best zoom level and viewport. At the moment SumatraPDF can only maintain the zoom and resets the viewport to the upper-left margin of the document. 

Cheers!

**Comment by GitHubRulesOK** [comment]
Consolidating with the more detailed discussions in `Keep vertical offset after page flip` #1500
