### ISSUE TITLE
11639 a number of changes - 1 the installer

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1320]
[Updated] Please see #1322 by @VictorVG re installer not working however I had tried to see installer options as follows

Installer seems to have dropped all command line options other than -install 
e.g /h does not show any options etc.
thus cant see / test other previously visible options 👎

**Comment by kjk** [comment]
The options were there, just not shown. I've improved this in https://github.com/sumatrapdfreader/sumatrapdf/commit/be51b2fab517a58ae0dabba52f98ac14672b9f67
