### ISSUE TITLE
Installer (SumatraPDF-dll.exe) not copy libmupdf.dll, PdfFilter.dll, PdfPreview.dll to target and installed copy not work

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1322]
Latest changes after SumatraPDF v3.2.11632 in the installer is binary equivalents SumatraPDF-dll.exe) not copy libmupdf.dll and additional DLL PdfFilter.dll, PdfPreview.dll to target system, and if this DLL not exist SumatraPDF can't work. But SumatraPDF v3.2.11621 Git-18c2c025d copy needed DLL and work success...

As best event user see messages about that is installer, but can't resolving problem's w/o manually copy needed DLL.

**Comment by GitHubRulesOK** [comment]
Hi @VictorVG  Thanks for the heads-up

I had not noticed the changed behaviours in 3.2.11639 since I often install each version over previous one until I saw you raise this issue
In 3.2.11639 uninstalling the old one and starting fresh then ONLY the non working file is installed !!!
Thus I have no idea how/where the "updated copy" was finding those supporting files

**Comment by VictorVG** [comment]
I just manually copy this DLL on to ./SumaraPDF/Bin/x64 dir (I write [**SuamtraPDF Toolkit**](https://github.com/VictorVG/Source/releases/tag/SPDFTK-1.4.8) for build) and v3.2.11639 work success.:)

**Comment by kjk** [comment]
This is not a supported scenario.

If you want a single executable, use a portable version.

If you're using an installer, you have to run it to extract and properly install libmupdf.dll etc.

You can also extract those files from the installer with `/x` and copy manually but this is unsupported scenario. It happens to work today but I might change how it works in the future.

I'm not sure what exactly you're doing but it seems like you're just downloading the installer executable and renaming it. That's not supposed to work this way so it doesn't.

**Comment by GitHubRulesOK** [comment]
@kjk thanks for explanation about rename it is a common problem for example with say MiKTeX which  does not warn that it cant find its own versioned name, thus users download a second multimegabyte of installer, perhaps to yet another name ad infinitum.
Many advanced users expect to be able to rename an installer either as a reminder of date/versioning or shortening to simplify calling from a versioned directory.

**Comment by VictorVG** [comment]
Ok! Try test use official SumatraPDF-prerelease-11632-64-install.exe:

1) copy file: SumatraPDF-prerelease-11632-64-install.exe in to empty dir.
2) ls -fr * 
in to comsole see file list:
..
./SumatraPDF-prerelease-11632-64-install.exe

3) SumatraPDF-prerelease-11632-64-install.exe /x

4) ls -fr *

5) in console see file list:
..
./SumatraPDF-prerelease-11632-64-install.exe
./SumatraPDF.exe

also DLL is exists, but I not see it, please, see console scrinshot:

![1](https://user-images.githubusercontent.com/906886/70833689-7bdf6b80-1e09-11ea-872b-3b5ab2cdc717.png)

**Comment by skipik** [comment]
@kjk he's just saying that the new installer (after the latest commits) doesn't contain libmupdf.dll, PdfFilter.dll, PdfPreview.dll. That's a bug. :-)

**Comment by kjk** [comment]
I see, thanks.

There was indeed a bug I introduced in the installer recently. Should be fixed now.

**Comment by VictorVG** [comment]
Simple test:

![1](https://user-images.githubusercontent.com/906886/70838192-29f21200-1e18-11ea-8fdb-f1bf25865f07.png)

Build use MSVC++ v16.4.1.  Also build log attached:

[readme.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/3963078/readme.txt)

**Comment by VictorVG** [comment]
Problem is fixed in to v3.2.11641 Git-301f0bc0d:

![3](https://user-images.githubusercontent.com/906886/70838797-f49af380-1e1a-11ea-81ee-1e8becdd308d.png)

Big thanks!
