### ISSUE TITLE
glitch on toolbar after switch tab

### ISSUE THREAD

**Issue by blackarcher21** [sumatrapdfreader/sumatrapdf#1329]
![2019-12-14_16-35-24](https://user-images.githubusercontent.com/15969210/70845995-e0450e00-1e8f-11ea-8d7a-7becd3a72043.gif)
This issue has been there for long though but I decided to report now in case there will be a solution.
Regards :)

**Comment by SumatraPeter** [comment]
Not able to replicate. Does it happen for you when switching between any 2 PDFs, or only with specific files? If the former, can you mention the exact steps to be followed? (For example, do we need to press the Zoom In/Out buttons after every tab switch?)

**Comment by blackarcher21** [comment]
It does happen when switching between 2 pdf, It mostly happen after clicking button on toolbar (zoom, search, next page, etc) then switching the tab.

**Comment by GitHubRulesOK** [comment]
@blackarcher21 
It may help to know which version you are running since nobody else has reported against long time version 3.1.2
So which version / bitness (32/64) of SumatraPDF and where obtained, Is it installed "normally" / portable and on which bitness (32/64) of which version windows. (XP/7/8/19.25)

**Comment by blackarcher21** [comment]
I use 64-bit SumatraPDF. I just tested again with last time release, 3.1.2. yes, issue is there.
Now I'm using Windows 10 1703. I remember I had this issue when I was using old computer with Windows 8.1 64-bit installed.

Now I just realized it seems it doesn't happen when pdfs have same digits on total pages. pdfs with different digits on total pages (e.g 100 and 1000), the space on toolbar slightly changes and that seems triggered the glitch.

**Comment by SumatraPeter** [comment]
I tested with one PDF having 351 pages ('numbered' a-c, i-viii and 1-340), and another PDF having 570 pages (properly numbered 1-570), both with 64-bit 3.1.2 (installed) and latest daily build (portable). Switched between the two tabs 30-40 times, pressing all sorts of toolbar buttons in between in all sorts of combinations... Still haven't been able to replicate the issue however, so unless you can provide specific files and steps that enable us to replicate, I'm inclined to believe this sort of graphics glitch might have something to do with your specific graphics hardware and current drivers.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter **ironically** whilst just reading this I simply opened a second file and got this
![image](https://user-images.githubusercontent.com/12754913/70935132-694a7980-2037-11ea-86ed-91fc8c14c3c3.png)

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Great, so can you replicate it? Other than that I don't know how it can be fixed unless kjk adds some sort of debug code to possibly detect when that Page label goes blank...

**Comment by GitHubRulesOK** [comment]
My case is different page: and file: is always off 
when I switch due to "Text colour settings" in that configuration
Those parts of menu are constantly adjusted by current language and text color. 
Simple fix dont mess with settings by hand :-)

**Comment by SumatraPeter** [comment]
> Those parts of menu are constantly adjusted by current language and text color.
the text can be black red white and blue (follows main text color not quite sure why ?)

Menu/toolbar text language is expected to change, but not text color! Might want to report your settings that cause this to kjk as a bug.

**Comment by SumatraPeter** [comment]
> Menu/toolbar text language is expected to change, but not text color! Might want to report your settings that cause this to kjk as a separate bug.

Related issue with same text labels reported as #1553.

**Comment by kjk** [comment]
I can't reproduce it in latest daily build https://www.sumatrapdfreader.org/dailybuilds so let's consider it closed.
