### ISSUE TITLE
Import issues from google code

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#133]
Given that google code is completely shutting down (not soon but eventually), import existing issues using https://github.com/arthur-debert/google-code-issues-migrator

**Comment by kjk** [comment]
Or maybe using this process: https://code.google.com/p/support-tools/wiki/IssueExporterTool

**Comment by GitHubRulesOK** [comment]
@kjk 
I guess this is now a dead issue "cant fix"?

**Comment by kjk** [comment]
Yeah, not going to happen
