### ISSUE TITLE
New Feature Request: Enabling highlight and Underline

### ISSUE THREAD

**Issue by erukumk** [sumatrapdfreader/sumatrapdf#1332]
Hi,

It would be great to have highlighting and underlining abilities to the tool, it would be of great help.

Thanks!

**Comment by SumatraPeter** [comment]
@kjk: Consolidate as #747?

@erukumk: Current status is reflected by the following:

https://github.com/sumatrapdfreader/sumatrapdf/issues/1304
https://forum.sumatrapdfreader.org/t/highlighting-problem-in-prerelease-version/2496

**Comment by kjk** [comment]
Covered by #747
