### ISSUE TITLE
Laggy/jittery scrolling when using "Show Pages Continuously" mode?

### ISSUE THREAD

**Issue by leosmileyface** [sumatrapdfreader/sumatrapdf#1333]
Anyone else gets this? I like to read my manga all in one strip and just scroll down, but when using SumatraPDF, it's super laggy/jittery, hurts my eyes after a little. My PC is decently beefy, I doubt it's a problem with my specs. Any fixes?

**Comment by kjk** [comment]
I can't reproduce the problem. Maybe if you can make a screen recording that shows the problem and provide more information (what version of sumatra, what windows version, CPU speed of the computer, is it happening with all files or just some of them; if only some of them, what is the compression format of the archive, what is the image format and sizes of files in the archive etc.)

**Comment by leosmileyface** [comment]
> I can't reproduce the problem. Maybe if you can make a screen recording that shows the problem and provide more information (what version of sumatra, what windows version, CPU speed of the computer, is it happening with all files or just some of them; if only some of them, what is the compression format of the archive, what is the image format and sizes of files in the archive etc.)

I did end up finding the problem, I think the file sizes are too much. I like to read full vols at a time, so around 300+ images in one .cbz file. I tried putting in one chapter which is about 16 images and the scroll was not choppy at all.

Guess I have to chop them up into chapters... some how.

**Comment by GitHubRulesOK** [comment]
@leosmileyface 
cbz is png in zip keep the master and renam a copy of the cbz to zip, expand into an unpacked folder 
use irfanview batch mode to reduce colour/bit bepth for comics 16 colors huffman dithered better than 256 (gif like) also look at dropping resolution the screen is notionally 96dpi so no need for 300 dpi print quality all the time. 192 dpi is often a good target value. resave as zip and rename to .cbz

File size should drop such that all images respond much much quicker quicker 
200 images or more should be no problem

**Comment by SumatraPeter** [comment]
>  cbz is png in zip

Or generally, any image format in zip.
