### ISSUE TITLE
Icons for all file types

### ISSUE THREAD

**Issue by andrecool-68** [sumatrapdfreader/sumatrapdf#1338]
sumatrapdf has only one icon for all file types, can add the option of individual icons for each supported file type?
can make a similar set of icons

![Sumatra ICO](https://user-images.githubusercontent.com/3471892/71239140-794fab00-230e-11ea-8069-1dc3be84bfb2.png)

**Comment by GitHubRulesOK** [comment]
SumatraPDF can actually display many dozens of file types and the simple use of one coloured extensions is good

Other types include
Adobe Illustrator (AI), OpenXPS (OXPS), Amazon Word (AzW), Palm reader (PRC) Fiction Book 2 uncompressed and zip compressed (FB2, FBZ) Many image types (GIF, AGIF, TIFF, TGA etc etc) the list includes .log .txt xml htm html etc.

**Comment by SumatraPeter** [comment]
@andrecool-68: I suggest closing this issue and posting instead in #600, after going through it carefully first.
