### ISSUE TITLE
Feature Request: double click to go to Full Screen

### ISSUE THREAD

**Issue by KetoShoku** [sumatrapdfreader/sumatrapdf#134]
Greetings.

I love the speed of Sumatra. I use it daily.

A nice feature would be to double click in middle of opened file (middle of screen anywhere) would go to full screen. I use Full Screen all the time and although F11 works fine, I'm often far from the keyboard but have mouse in hand.

Cheers.

**Comment by stufkan** [comment]
Currenty double click performs the command entered in Menu -> Settings -> Options -> Set inverse search command-line

A button in the toolbar along with Fit width and Fit in single page might be a better option (?)

**Comment by KetoShoku** [comment]
Thanks for feedback.

I'm confused about your meaning of "Menu -> Settings -> Options -> Set
inverse search command-line".
I don't find anything like that under Options.
Is that something in Advanced Options? (I don't find anything like that
there either.)

But a button on the toolbar for going to Fullscreen would be great too.
Currently I use F11, but would prefer a button. And would prefer even more
just to double click in the middle of the screen to make it go to
Fullscreen. And double click to go back down to regular.

Thanks again. A very fine piece of software.


On Wed, May 13, 2015 at 3:12 AM, Stefan Micheelsen <notifications@github.com

**Comment by kjk** [comment]
I don't think double-click is the right action to invoke full screen.
