### ISSUE TITLE
Current instability with UsefixedpageUI

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1341]
setting ebooukUI to UsefixedpageUI =true 
without debug toggle ebookUI usually results in a crash on loading
with toggle on fails to open simple.epub stating "error opening"

setting chmUI to UsefixedpageUI =true 
usually results in a crash on loading simple.chm

**Comment by kjk** [comment]
Could you add a crash report (e.g. post as gist.github.com and link to it)?

**Comment by GitHubRulesOK** [comment]
@kjk should be repeatable with attached
 crash reports included

[SumatraPDF-chm crash with debug toggle ui checked.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3990140/SumatraPDF-chm.crash.with.debug.toggle.ui.checked.zip)
[epub crash with debug toggle active.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3990156/epub.crash.with.debug.toggle.active.zip)

**Comment by GitHubRulesOK** [comment]
@kjk sorry still crashed with fresh prerelease-11744
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3990525/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
This crash doesn't seem to be related to the original issue. It's a crash with .chm file and apparently caused by reload.

**Comment by kjk** [comment]
I've opened https://github.com/sumatrapdfreader/sumatrapdf/issues/1342 for this
