### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1343]
Currently one selling feature of SumatraPDF is the lack of automated features such as running SWF JavaScript etc.

Generally the only animated image support (reading GIF and MultipageTiff) is restricted to static images thus the user has to press the space bar and in order to loop need to manually return to start.

This principly emulates the old fashioned thumbook / flipbook / flickbook feature that works across many formats thus ideal for stepped presentations (but does not need to be confined to full screen)

Animation of sorts is ONLY supported by the CHM format in ChmUI 
Extract the sample from this zip to see potential
[Animations.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3991894/Animations.zip)

It would be nice if SumatraPDF could step through standard GIF and TIFF and all others such as mobi epub etc etc. (where one frame is on each page) with an optional return to start (Loop) and a variable timer for page transitions.

Likewise the same step and repeat on a timer would be very useful for LaTeX beamer.PDF presentations for a sample file see https://github.com/cfiandra/Beamer2Thesis/raw/master/doc/basic_guide/beamer2thesis.pdf

**Comment by VFDan** [comment]
http://www.eprg.org/pdfcorner/pdfdoodles/ Animated Logo and Progress Monitor here also don't work in SumatraPDF, they just skip to the last one.

**Comment by GitHubRulesOK** [comment]
Oh well since I suggested it be done this way for others I answered my own question the issue is simply how to set a small timer in the caller such as VBS vba or any other language your using.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/5785d27c-90e2-45dd-bfca-ad1743144537)

**Comment by GitHubRulesOK** [comment]
@VFDan 

The progress bar and book ar possibly slow showing overlays and the open so fast in slow acrobat there is no real difference between that and superfast in ablink SumatraPDF the radial works just as well in both by zoom in.

Even the noughts and crosses functions in sumatraPDf since all of those use page replacements as does my GIF above
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/0e8c0fcc-a0bb-4e93-91af-1080725bc85f)
