### ISSUE TITLE
v3.2.11771 Git-b0505ee8f - Pressing any of the buttons on the installation stat screen leads to the endless selection of the target directory for installation.

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1345]
It’s a funny phenomenon, but I’m watching it on non-skittish cars:

pressing any of the buttons on the installation start screen leads to the endless selection of the target directory for installation. It is also pointless to press other buttons - all turned out to be “closed” to the dialog for selecting the target installation directory. It seems that after 10768 a typo crept somewhere that addresses all resources to a single “universal” object, although I may be mistaken, but now this hypothesis seems most suitable to me.

**Comment by GitHubRulesOK** [comment]
@kjk I can confirm installer 3.2.11768 worked but 11771 does not

**Comment by VictorVG** [comment]
This phenomena is exist started v3.2.11769 Git 0dc6efd5d. 

simple test use IDE VS2019 v16.4.2 build CFG=x64 Release:

md test & cd /d sumatrapdf/source & сp -f ./out/rel64/sumatrapdf-dll.exe ../../../../test/sumatrapdf-install.exe & cd test & ls -fR *

> SumatraPDF-install.exe

SumatraPDF-install.exe /x && ls -fR *

> PdfFilter.dll  PdfPreview.dll  SumatraPDF-install.exe  SumatraPDF.exe  libmupdf.dll

**Comment by VictorVG** [comment]
@kjk 

Big thanks! Test succes.

P.S.

Find in net:

![1](https://user-images.githubusercontent.com/906886/71387120-4a358400-2603-11ea-88c6-8ef16152648a.jpg)

Settled. :)
