### ISSUE TITLE
Installer 3.2.11781 & 11782 again refuse to install looping on select folder

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1346]
Similar to https://github.com/sumatrapdfreader/sumatrapdf/issues/1345
We either wait for Santa to awaken after all his hard work 😄

OR for the more adventurous see above issue for a temporary workaround

**Comment by skipik** [comment]
Yeah, same here.

**Comment by kjk** [comment]
Thanks, should be fixed again.
