### ISSUE TITLE
Interesting behaviours of NEW window

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1347]
Understandable but odd
Using Favourites in second window drives file change and pages in first window ? 
however bookmarks only affect their own window

switching modes in second window INITIALLY only affects second windows thus an epub in first window with usefixedUI = true will open in second window in that mode
However  if settings are changed to false the second window will change **as desired** whilst first window continues in fixedUI mode untill manually refreshed.
Personally I would prefer that oddity to continue as it allows comparison of both modes, however should it be noted as a "Feature" rather than a bug?
![image](https://user-images.githubusercontent.com/12754913/71419921-28231c80-266a-11ea-8eef-f184336a4bab.png)

**Comment by kjk** [comment]
Let's consider this "working as designed". The things in Debug menu are "best effort" so don't expect a polished behavior there.

**Comment by GitHubRulesOK** [comment]
@kjk this "Feature" is potentially a hidden boon
It allows a convenient setup for dual screen presentations
where the driving screen can have the "favourites" for each page alongside the presenters script in pdf or text format
clicking favorites for the pages/images are then showing without buttons etc on the projection screen
remember to set viewing favourites ON first then close them on the presentation screen

The down-side is the need to store the full list of pages/slides as "favorites" within the settings.txt file, it does not work if they are "bookmarks"
