### ISSUE TITLE
Support filling forms

### ISSUE THREAD

**Issue by prasannavl** [sumatrapdfreader/sumatrapdf#135]
The title says it. Any chance its on the RoadMap? That's the only reason I have to have Adobe's software installed. 

Simple forms, and attaching digital signatures.

**Comment by gl-bars** [comment]
+1

If performance/security is a concern, make the forms support switchable in the options (or even an optional component at the installation stage).

Related feature request:
[Issue 1704: Support PDF form editing, adding comments and other interactive features](http://code.google.com/p/sumatrapdf/issues/detail?id=1704)

**Comment by kjk** [comment]
Dup of issue 48
