### ISSUE TITLE
Add a translation feature

### ISSUE THREAD

**Issue by Mrzhang06** [sumatrapdfreader/sumatrapdf#1351]
Hello, I hope you will embed the word translation function in the next version, or provide an access interface for translation, such as access to the Google Translation platform, or Baidu translation platform.

**Comment by SumatraPeter** [comment]
Online translation has been rejected earlier due to lack of a free API: #771.

@kjk: I guess this one and #871 can be consolidated with #771 as the master, in case an appropriate API ever becomes available in future.

**Comment by GitHubRulesOK** [comment]
All these requests for a short phrase lookup could be addressed in a very simple fashion if the selected word or sentance string is exposed for use in the external viewers commands
Length may need to be limited to minimise exceeding a valid working command line length (say 180-200 chars max?)

Such a string can easily be proceesed by online translators that accept browser search queries
again could thus be consolidated with the open request for adhoc browser look-up functions such as dictionary, thesaurus, spell check, etc.

**Comment by Mrzhang06** [comment]
Do you know the translation plug-in in interlij IDEA, there's a plugin called "Translate" inside
, that plug-in is accessed by default to Google Translate, while providing access toYouDao translation and Baidu translation, 
I very much suggest that this software can be made like VS Code can install plug-ins

**Comment by Mrzhang06** [comment]
Do you know the translation plug-in in interlij IDEA, there's a plugin called "Translate" inside
, that plug-in is accessed by default to Google Translate, while providing access toYouDao translation and Baidu translation,
I very much suggest that this software can be made like VS Code can install plug-ins

**Comment by SumatraPeter** [comment]
>  I very much suggest that this software can be made like VS Code can install plug-ins

Good idea, but creating an entire plugin framework for third-party contributions is far easier said than done.

**Comment by GitHubRulesOK** [comment]
select a FREE piece of text such as 
Hello World or And%20there%20it%20is
append it to a simple shortcut like
https://translate.google.com/?hl=en&tab=TT#view=home&op=translate&sl=auto&tl=fr&text=

Et voilà

**Comment by bahusoid** [comment]
Try [QTranslate](https://quest-app.appspot.com/home) It should cover all your online translation needs

**Comment by GitHubRulesOK** [comment]
@kjk 
This requirement to send selection to a translator app or web query could be consolidated with #1280

**Comment by kjk** [comment]
Consolidate under #1280

**Comment by kjk** [comment]
I've started on this functionality in d710475

Still more to do, you can track progress / add ideas in #1280
