### ISSUE TITLE
Version not changed

### ISSUE THREAD

**Issue by Avtroman** [sumatrapdfreader/sumatrapdf#1353]
When compile new version (for example, last hour changed), after run I got message "you version is xx" "Download new version YY ?

**Comment by kjk** [comment]
What is the exact value of 'xx' and 'yy'?
Can you post a screenshot?

**Comment by Avtroman** [comment]
> What is the exact value of 'xx' and 'yy'?
> Can you post a screenshot?

https://cloud.mail.ru/public/4xgp/3K71qwcPo
