### ISSUE TITLE
unable to run -stress-test

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1355]
@kjk sorry if you got a high number of sequential crashes but i seem not to be able to run

SumatraPDF.exe -console -n 2 -rand -stress-test D:\SumatraPDF\Samples\PDF\Image 
or 
SumatraPDF.exe -console  -stress-test D:\SumatraPDF\Samples\PDF\Image 

any reasons for this function not working ? 
it starts on a few files but then fails rapidly

[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4007649/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
It looks like it happens when there's .vbkm file. I don't quite understand why this happens but maybe this will fix it.

**Comment by kjk** [comment]
Or maybe not, other crashes happen with other files.

**Comment by kjk** [comment]
This only happens if you have reuseInstance set. Stress test is not compatible with it. I've fixed so that it doesn't crash but it's still not compatible so don't expect stress test to work with reuseIntance.

**Comment by kjk** [comment]
So the real fix is https://github.com/sumatrapdfreader/sumatrapdf/commit/dae4569f6639aa45f10e114428bf797cedaf8722 and it probably was not related to reuseInstance.

**Comment by GitHubRulesOK** [comment]
@kjk wow its hypnotique I dont know how pany pages were rendered in a second under 2 minutes but it was impresively fast, there should be an epilepsy health warning **not to watch the screen during test**
