### ISSUE TITLE
unexpected behaviour of TOC editor

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1360]
When adding /appending a third file to an existing .vbkm with two files the previous files become a different "nest" level to the third, how can that be controlled?. Also whilst saving the .vbkm extension is appended again and again. (caught me out a few times :-)

![image](https://user-images.githubusercontent.com/12754913/71607851-cfc1b280-2b74-11ea-9f0b-472862cbf5f9.png)

**Comment by kjk** [comment]
Yeah, working on existing .vbkm is not handled well yet.

**Comment by GitHubRulesOK** [comment]
@kjk since neither of above appears to be still present in latest pre-release I am closing these issue
