### ISSUE TITLE
SumatraPDF keeps crashing when open this file

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#1362]
Crash file: C:\Users\Administrator\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.txt
Exe: C:\Program Files\SumatraPDF\SumatraPDF.exe
BuiltOn: 2019-12-30
Type: dll
Ver: 3.2.11842 pre-release 64-bit
Git: 4ebe8c16a76510fdc538ff881272ac9e2ec30f56 (https://github.com/sumatrapdfreader/sumatrapdf/commit/4ebe8c16a76510fdc538ff881272ac9e2ec30f56)
OS: Windows 10 build 17763 64-bit
Number Of Processors: 8
Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
Physical Memory: 15.89 GB
Commit Charge Limit: 18.26 GB
Memory Used: 35%
Machine: Please change family name REV:1.0
Lang: zh CN
Graphics driver 0
  DriverDesc:         Intel(R) HD Graphics 630
  DriverVersion:      23.20.16.4982
  UserModeDriverName: C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_fe73d2ebaa05fb95\igdumdim64.dll
Graphics driver 1
  DriverDesc:         NVIDIA GeForce GTX 1060
  DriverVersion:      26.21.14.4166
  UserModeDriverName: C:\Windows\System32\DriverStore\FileRepository\nvmii.inf_amd64_192a837d20a82ea6\nvldumdx.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FF7BB99D918 01:000000000017C918 sumatrapdf.exe!PdfEngineImpl::GetProperty+0x4c8 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1648
Fault reading address 0000000000000000

Registers:
RAX:0000000000000000  RBX:0000019D76648810  RCX:00000000FFFFFFFF
RDX:0000000000000000  RSI:0000000000000000  RDI:0000000000000000
R8: 0000000000008000
R9: 00000000000000BB
R10:0000006B4AAFE590
R11:0000006B4AAFE9C0
R12:0000019D76691AB0
R13:0000019D76691AB0
R14:0000000000000000
R15:00007FF7BB8F0844
CS:RIP:0033:00007FF7BB99D918
SS:RSP:002B:000000004AAFE630  RBP:766921B0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Crashed thread:
00007FF7BB99D918 01:000000000017C918 sumatrapdf.exe!PdfEngineImpl::GetProperty+0x4c8 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1648
00007FF7BB926C16 01:0000000000105C16 sumatrapdf.exe!SetFrameTitleForTab+0xa6 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+932
00007FF7BB927938 01:0000000000106938 sumatrapdf.exe!LoadDocIntoCurrentTab+0xa18 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+1114
00007FF7BB929D86 01:0000000000108D86 sumatrapdf.exe!LoadDocument+0x9b6 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+1636
00007FF7BB938A63 01:0000000000117A63 sumatrapdf.exe!LoadOnStartup+0x73 C:\Users\kjk\src\sumatrapdf\src\SumatraStartup.cpp+240
00007FF7BB93B503 01:000000000011A503 sumatrapdf.exe!WinMain+0x1693 C:\Users\kjk\src\sumatrapdf\src\SumatraStartup.cpp+984
00007FF7BB9E27EE 01:00000000001C17EE sumatrapdf.exe!__scrt_common_main_seh+0x106 d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl+288
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2e90
00007FFD2CFAF7E4 01:000000000009E7E4 ntdll.dll!ZwWaitForSingleObject+0x14
00007FFD293B8403 01:0000000000037403 kernelbase.dll!WaitForSingleObjectEx+0x93
00007FF7BB8EF681 01:00000000000CE681 sumatrapdf.exe!DumpExceptionHandler+0x71 C:\Users\kjk\src\sumatrapdf\src\CrashHandler.cpp+331
00007FFCE868AACA 01:00000000001A9ACA sogoupy.ime!ImeDestroy+0xf537a
00007FFCF896F416 01:000000000018E416 picface64.dll!UnInitializeBundle+0x148366
00007FFD29406C9C 01:0000000000085C9C kernelbase.dll!UnhandledExceptionFilter+0x1bc
00007FFD2CFB81CB 01:00000000000A71CB ntdll.dll!memset+0x1c8b
00007FFD2CF9FD56 01:000000000008ED56 ntdll.dll!_C_specific_handler+0x96
00007FFD2CFB477F 01:00000000000A377F ntdll.dll!_chkstk+0x11f
00007FFD2CF14BEF 01:0000000000003BEF ntdll.dll!RtlWalkFrameChain+0x14bf
00007FFD2CFB34EE 01:00000000000A24EE ntdll.dll!KiUserExceptionDispatcher+0x2e
00007FF7BB99D918 01:000000000017C918 sumatrapdf.exe!PdfEngineImpl::GetProperty+0x4c8 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1648
00007FF7BB926C16 01:0000000000105C16 sumatrapdf.exe!SetFrameTitleForTab+0xa6 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+932
00007FF7BB927938 01:0000000000106938 sumatrapdf.exe!LoadDocIntoCurrentTab+0xa18 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+1114
00007FF7BB929D86 01:0000000000108D86 sumatrapdf.exe!LoadDocument+0x9b6 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+1636
00007FF7BB938A63 01:0000000000117A63 sumatrapdf.exe!LoadOnStartup+0x73 C:\Users\kjk\src\sumatrapdf\src\SumatraStartup.cpp+240
00007FF7BB93B503 01:000000000011A503 sumatrapdf.exe!WinMain+0x1693 C:\Users\kjk\src\sumatrapdf\src\SumatraStartup.cpp+984
00007FF7BB9E27EE 01:00000000001C17EE sumatrapdf.exe!__scrt_common_main_seh+0x106 d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl+288
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 4b58
00007FFD2CFB30D4 01:00000000000A20D4 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFD2CF601F4 01:000000000004F1F4 ntdll.dll!RtlReleaseSRWLockExclusive+0x2c4
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2380
00007FFD2CFB30D4 01:00000000000A20D4 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFD2CF601F4 01:000000000004F1F4 ntdll.dll!RtlReleaseSRWLockExclusive+0x2c4
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2dd0
00007FFD2CFB30D4 01:00000000000A20D4 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFD2CF601F4 01:000000000004F1F4 ntdll.dll!RtlReleaseSRWLockExclusive+0x2c4
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 1318
00007FFD2CFAF7E4 01:000000000009E7E4 ntdll.dll!ZwWaitForSingleObject+0x14
00007FFD293B8403 01:0000000000037403 kernelbase.dll!WaitForSingleObjectEx+0x93
00007FF7BB913B7C 01:00000000000F2B7C sumatrapdf.exe!RenderCache::RenderCacheThread+0xcc C:\Users\kjk\src\sumatrapdf\src\RenderCache.cpp+603
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 3fa0
00007FFD2CFAFDE4 01:000000000009EDE4 ntdll.dll!NtDelayExecution+0x14
00007FFD293B96F1 01:00000000000386F1 kernelbase.dll!SleepEx+0xa1
00007FFCE89BCD00 01:00000000004DBD00 sogoupy.ime!ImeDestroy+0x4275b0
00007FFCE8958D21 01:0000000000477D21 sogoupy.ime!ImeDestroy+0x3c35d1
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 1b1c
00007FFD2CFAFDE4 01:000000000009EDE4 ntdll.dll!NtDelayExecution+0x14
00007FFD293B96F1 01:00000000000386F1 kernelbase.dll!SleepEx+0xa1
00007FFCE8632E65 01:0000000000151E65 sogoupy.ime!ImeDestroy+0x9d715
00007FFCE8958D99 01:0000000000477D99 sogoupy.ime!ImeDestroy+0x3c3649
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 3420
00007FFD2CFAF7E4 01:000000000009E7E4 ntdll.dll!ZwWaitForSingleObject+0x14
00007FFD293B8403 01:0000000000037403 kernelbase.dll!WaitForSingleObjectEx+0x93
00007FFCE8653DA2 01:0000000000172DA2 sogoupy.ime!ImeDestroy+0xbe652
00007FFCE8958D99 01:0000000000477D99 sogoupy.ime!ImeDestroy+0x3c3649
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Thread: 3bf0
00007FFD2CFAF7E4 01:000000000009E7E4 ntdll.dll!ZwWaitForSingleObject+0x14
00007FFD293B8403 01:0000000000037403 kernelbase.dll!WaitForSingleObjectEx+0x93
00007FFCE873641B 01:000000000025541B sogoupy.ime!ImeDestroy+0x1a0ccb
00007FFCE87361A7 01:00000000002551A7 sogoupy.ime!ImeDestroy+0x1a0a57
00007FFD2C947974 01:0000000000016974 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD2CF7A271 01:0000000000069271 ntdll.dll!RtlUserThreadStart+0x21

Module: 00007FF7BB820000 929000 SumatraPDF.exe   C:\Program Files\SumatraPDF\SumatraPDF.exe
Module: 00007FFD2CF10000 1ED000 ntdll.dll        C:\Windows\SYSTEM32\ntdll.dll
Module: 00007FFD2C930000 0B3000 KERNEL32.DLL     C:\Windows\System32\KERNEL32.DLL
Module: 00007FFD29380000 293000 KERNELBASE.dll   C:\Windows\System32\KERNELBASE.dll
Module: 00007FFD2CA00000 197000 USER32.dll       C:\Windows\System32\USER32.dll
Module: 00007FFD28FD0000 020000 win32u.dll       C:\Windows\System32\win32u.dll
Module: 00007FFD196E0000 279000 COMCTL32.dll     C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.17763.914_none_05b346b2072102f2\COMCTL32.dll
Module: 00007FFD2CC20000 029000 GDI32.dll        C:\Windows\System32\GDI32.dll
Module: 00007FFD2C350000 09E000 msvcrt.dll       C:\Windows\System32\msvcrt.dll
Module: 00007FFD29060000 199000 gdi32full.dll    C:\Windows\System32\gdi32full.dll
Module: 00007FFD29200000 0A0000 msvcp_win.dll    C:\Windows\System32\msvcp_win.dll
Module: 00007FFD29880000 0FA000 ucrtbase.dll     C:\Windows\System32\ucrtbase.dll
Module: 00007FFD2C460000 32C000 combase.dll      C:\Windows\System32\combase.dll
Module: 00007FFD2B750000 122000 RPCRT4.dll       C:\Windows\System32\RPCRT4.dll
Module: 00007FFD2BC00000 127000 COMDLG32.dll     C:\Windows\System32\COMDLG32.dll
Module: 00007FFD29620000 07E000 bcryptPrimitives.dll C:\Windows\System32\bcryptPrimitives.dll
Module: 00007FFD2CC50000 0A8000 shcore.dll       C:\Windows\System32\shcore.dll
Module: 00007FFD0C830000 089000 WINSPOOL.DRV     C:\Windows\SYSTEM32\WINSPOOL.DRV
Module: 00007FFD2BE60000 052000 SHLWAPI.dll      C:\Windows\System32\SHLWAPI.dll
Module: 00007FFD28F80000 011000 kernel.appcore.dll C:\Windows\System32\kernel.appcore.dll
Module: 00007FFD2A250000 14F4000 SHELL32.dll      C:\Windows\System32\SHELL32.dll
Module: 00007FFD292A0000 026000 bcrypt.dll       C:\Windows\System32\bcrypt.dll
Module: 00007FFD28FF0000 04A000 cfgmgr32.dll     C:\Windows\System32\cfgmgr32.dll
Module: 00007FFD28490000 03D000 IPHLPAPI.DLL     C:\Windows\SYSTEM32\IPHLPAPI.DLL
Module: 00007FFD25A40000 1A9000 PROPSYS.dll      C:\Windows\SYSTEM32\PROPSYS.dll
Module: 00007FFD299E0000 74D000 windows.storage.dll C:\Windows\System32\windows.storage.dll
Module: 00007FFD2CE10000 0C4000 OLEAUT32.dll     C:\Windows\System32\OLEAUT32.dll
Module: 00007FFD2A150000 09E000 sechost.dll      C:\Windows\System32\sechost.dll
Module: 00007FFD2CD60000 0A3000 advapi32.dll     C:\Windows\System32\advapi32.dll
Module: 00007FFD28FA0000 024000 profapi.dll      C:\Windows\System32\profapi.dll
Module: 00007FFD28F20000 05D000 powrprof.dll     C:\Windows\System32\powrprof.dll
Module: 00007FFD29040000 017000 cryptsp.dll      C:\Windows\System32\cryptsp.dll
Module: 00007FFD2B8F0000 155000 ole32.dll        C:\Windows\System32\ole32.dll
Module: 00007FFD2C900000 02E000 IMM32.DLL        C:\Windows\System32\IMM32.DLL
Module: 00007FFD27180000 09C000 uxtheme.dll      C:\Windows\system32\uxtheme.dll
Module: 00007FFD274C0000 02E000 dwmapi.dll       C:\Windows\system32\dwmapi.dll
Module: 00007FFD296A0000 1DB000 CRYPT32.dll      C:\Windows\System32\CRYPT32.dll
Module: 00007FFD28F00000 012000 MSASN1.dll       C:\Windows\System32\MSASN1.dll
Module: 00007FFD2BEC0000 008000 normaliz.dll     C:\Windows\System32\normaliz.dll
Module: 00007FFD09860000 25B000 uiautomationcore.dll C:\Windows\system32\uiautomationcore.dll
Module: 00007FFD23F40000 05C000 Bcp47Langs.dll   C:\Windows\SYSTEM32\Bcp47Langs.dll
Module: 00007FFD1B470000 1ED000 dbghelp.dll      C:\Windows\system32\dbghelp.dll
Module: 00007FFD21B00000 02A000 dbgcore.DLL      C:\Windows\SYSTEM32\dbgcore.DLL
Module: 00007FFD1F9D0000 1A5000 gdiplus.dll      C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.17763.914_none_369e399761b37cc0\gdiplus.dll
Module: 00007FFD25280000 007000 msimg32.dll      C:\Windows\system32\msimg32.dll
Module: 00007FFD1D1F0000 1D7000 urlmon.dll       C:\Windows\system32\urlmon.dll
Module: 00007FFD1F690000 2A8000 iertutil.dll     C:\Windows\SYSTEM32\iertutil.dll
Module: 00007FFD28940000 00C000 CRYPTBASE.DLL    C:\Windows\SYSTEM32\CRYPTBASE.DLL
Module: 00007FFD16D00000 00A000 version.dll      C:\Windows\system32\version.dll
Module: 00007FFD22330000 1B8000 windowscodecs.dll C:\Windows\system32\windowscodecs.dll
Module: 00007FFD19090000 4E1000 wininet.dll      C:\Windows\system32\wininet.dll

-------- Log -----------------

Starting SumatraPDF
CmdLine: "C:\Program Files\SumatraPDF\SumatraPDF.exe" "D:\Downloads\2016年06月妊娠合并心脏病的诊治专家共识.pdf" 
before LoadOnStartup: 'D:\Downloads\2016年06月妊娠合并心脏病的诊治专家共识.pdf'
LoadDocument: 'D:\Downloads\2016年06月妊娠合并心脏病的诊治专家共识.pdf', tid=11920
CreateControllerForFile: 'D:\Downloads\2016年06月妊娠合并心脏病的诊治专家共识.pdf'
LoadDocument: !forceReuse, created win->currentTab at 0x0000019D76691AB0
SubmitCrashInfo: gSymbolPathW: 'C:\Users\Administrator\AppData\Local\SumatraPDF\crashinfo'

----- Settings file ----------

﻿# For documentation, see https://www.sumatrapdfreader.org/settings3.2.html

MainWindowBackground = #80fff200
EscToExit = true
ReuseInstance = false
UseSysColors = false
RestoreSession = true
TabWidth = 300

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
EbookUI [
	FontName = Georgia
	FontSize = 12.5
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = false
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]
ExternalViewers [
]
ShowMenubar = true
ReloadModifiedDocuments = true
FullPathInTitle = false
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
AnnotationDefaults [
	HighlightColor = #ffff60
	SaveIntoDocument = true
]
CustomScreenDPI = 0

RememberStatePerDocument = true
UiLanguage = cn
ShowToolbar = true
ShowFavorites = false
AssociateSilently = false
CheckForUpdates = true
RememberOpenedFiles = false
EnableTeXEnhancements = false
DefaultDisplayMode = continuous
DefaultZoom = fit width
WindowState = 2
WindowPos = 556 -9 976 869
ShowToc = true
SidebarDx = 430
TocDy = 0
ShowStartPage = true
UseTabs = true

FileStates [
]
SessionData [
]
TimeOfLastUpdateCheck = 30785308 -320180809
OpenCountWeek = 469

# Settings after this line have not been recognized by the current version
PrereleaseSettings [
	TabWidth = 300
]
[2016年06月妊娠合并心脏病的诊治专家共识.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4012171/2016.06.pdf)

**Comment by kjk** [comment]
This has already been fixed in latest pre-release: https://www.sumatrapdfreader.org/prerelease.html
fix: https://github.com/sumatrapdfreader/sumatrapdf/commit/092220b48d2101aa6ebafb48ca2a6e74395709e4
