### ISSUE TITLE
Page reference shows as (null)

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1363]
I was going to report attached crashfiles including pdf, however on checking latest portable build the file now appears without crash BUT the page numbering looks "wrong"
![image](https://user-images.githubusercontent.com/12754913/71618986-138adb00-2bba-11ea-9c52-a6852c4a8639.png)
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4012458/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
Fixed, most likely by https://github.com/sumatrapdfreader/sumatrapdf/commit/2191fb2161d8b053035d3dc728b9ee40ef954464
