### ISSUE TITLE
Current pre-release does not write highlights to pdf when SaveIntoDocument = true

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1364]
@kjk I have raised this as a seperate issue to 1304 which was closed for writing xps.smx and pdf.smx
after 3.2.11856 the SaveIntoDocument = true is sucessful as a target.pdf.smx when previously it was an appendix/extension of the former.pdf

**Comment by kjk** [comment]
I believe I fixed this in https://github.com/sumatrapdfreader/sumatrapdf/commit/7cc641d06852a384c2d530eac8afbc0b0cccbd2a

**Comment by GitHubRulesOK** [comment]
@kjk I specially tested with https://github.com/sumatrapdfreader/sumatrapdf/commit/7cc641d06852a384c2d530eac8afbc0b0cccbd2a and initial result ewas it ignored my = true
I will re-test several methods

**Comment by GitHubRulesOK** [comment]
@kjk the failure was not with a standard pdf file so you are correct the issue should be closed
HOWEVER my failure was when attempting to save annotation in this file which has an common attachment !
[CLASSICDAB ISSUE.1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4013731/CLASSICDAB.ISSUE.1.pdf)

**Comment by kjk** [comment]
It should now work for that file.

**Comment by GitHubRulesOK** [comment]
@kjk Thanks solve for several pdf types (it was not just attachement but others with TOC too)
