### ISSUE TITLE
Window can be focused while content is not

### ISSUE THREAD

**Issue by t-ye** [sumatrapdfreader/sumatrapdf#1366]
When the SumatraPDF window regains focus, the main content may not regain focus, i.e. the tabs remain grey:

![image](https://user-images.githubusercontent.com/19561516/71637815-a94a5880-2c02-11ea-87c3-9bf5f621fc4d.png)

The main content regains focus only when it is clicked on. This implies that the window can be moved around by keyboard commands, but I can't use keyboard commands to scroll through the current PDF after I, say, use Alt+Tab to switch focus to SumatraPDF. It would be nice if the main content recovered the focus it had before the window lost focus. I am running SumatraPDF 3.1.2 64-bit through Wine in Linux/ChromeOS.

**Comment by kjk** [comment]
I can't reproduce this with latest build https://www.sumatrapdfreader.org/dailybuilds.html: when I alt-tab back to main window it does have focus.

Also, it could be Wine.

**Comment by t-ye** [comment]
It was indeed a problem with Wine; I didn't do my homework on it. I found the following post which fixed this problem for me: https://forum.winehq.org/viewtopic.php?t=20646#p92758 For posterity, here is the exact procedure that worked on my system:

- Run `regedit` in the Linux terminal - `regedit` comes with Wine in Linux and emulates the Windows Registry.
- Navigate to `HKEY_CURRENT_USER\Software\Wine\X11 Driver` . If there isn't an `X11 Driver` in `Wine`, then create a new key (Edit > New > Key) so there is.
-  Create a new string value (Edit > New > String Value) called `UseTakeFocus`. Change the value data of `UseTakeFocus` to `N` (right click it > Modify).
