### ISSUE TITLE
Problem with broken toc

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1367]
Whilst testing some old issues the sample in issue #416   [user_guide.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4014069/user_guide.pdf) 
proved to be a poorly constructed PDF from pages 29/534 to 42/534 , nevertheless MuPDF will simply bypass rendering those pages **the bulk of the file is valid** thus in MuPDF and previous SumatraPDF releases the bookmarks were functional (apart from the bad section)
![image](https://user-images.githubusercontent.com/12754913/71641647-8ddd5d00-2c97-11ea-9c59-20f6a45af1d9.png)

**Comment by kjk** [comment]
This is a broken document and mupdf apparently got more strict about this.

in `pdf_load_page_tree_imp` `type` is null and mupdf throws an error.

mupdf 1.16 doesn't load the outline either.

Should be reported to mupdf.

**Comment by GitHubRulesOK** [comment]
Closing as broken file
