### ISSUE TITLE
Scaling when saving as PDF

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1368]
Great that save as PDF is back 
(so removing last release blocker we should now be back from alpha to beta status 😹 )
 
Comparing with past behaviours there are some noticable differences related to scaling.
This is partly natural as some image formats have differing notional dpi related to 72ppi and 96dpi

As an example a GIF based image that was previously measured and saved as 5.29 cm wide may now be saved as a pdf 7.06 cm wide

**A PNG image previously measured and saved as A4 page 21cm wide is now saved as 28 cm wide**

![image](https://user-images.githubusercontent.com/12754913/71642994-77410100-2cab-11ea-8443-8e2df84fd4e2.png)

**Comment by kjk** [comment]
Thanks, for catching this, should be fixed.
