### ISSUE TITLE
Qestion: v3.2.11881 Git-1a03e5d93 is dispaly CHM as blank page, but v3.2.11872 Git-1bccab01e display here succes

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1369]
I suppose my mistake, but what I see - the test on my set passed correctly, but if I open CHM from another directory that does not have Cyrillic or spaces in the names, then CHM is displayed as a blank page, and the system HH.exe (I had to pull it out of WinXP - in Win7 no CHM support, ridiculous, but what is). Here is what we will see in the screenshots.

![spdf1](https://user-images.githubusercontent.com/906886/71666251-33b0ca80-2d71-11ea-9fd7-e5c00583e1da.png)

![spdf2](https://user-images.githubusercontent.com/906886/71666252-33b0ca80-2d71-11ea-9423-2d077c2fa7c7.png)

Testing use this CHM - [Contents.chm.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4015793/Contents.chm.zip)

What is there to do?

**Comment by GitHubRulesOK** [comment]
@kjk I can confirm there is an issue with 11881 that was not there in 11874  32/64 bit
![image](https://user-images.githubusercontent.com/12754913/71668092-81bcd280-2d5f-11ea-92a8-433d93c75f3e.png)

![image](https://user-images.githubusercontent.com/12754913/71667860-bd0ad180-2d5e-11ea-8f1f-dede62ba5ef6.png)

**Comment by kjk** [comment]
By default we show .chm files using embedded IE control. IE has security rules and considers some files unsafe for display in which case you would get a blank page.

I forgot the exact rules but I think files on network drives are considered unsafe, files downloaded from the internet are considered unsafe etc.

When using `UseFixedPageUI = true` we don't use IE control but render the html ourselves, so it doesn't have this problem.

I'm not sure if there's a way to over-ride IE.

Maybe I'll switch to UseFixedPageUI for .chm by default.

**Comment by GitHubRulesOK** [comment]
@kjk the files behaviour has changed only with latest commit ?

**Comment by kjk** [comment]
Yes, I can reproduce this. Looking into it.

**Comment by kjk** [comment]
Thanks for catching this, should be fixed.

**Comment by SumatraPeter** [comment]
> and the system HH.exe (I had to pull it out of WinXP - in Win7 no CHM support, ridiculous, but what is)

@VictorVG: Why would you need to copy hh.exe from XP? Are you sure your system's not corrupted? .CHM is very much supported still even in Win10 and I have an updated hh.exe in my Windows directory. It was WinHelp (.HLP) that was deprecated after XP, although it can be restored in Vista-Win8.1 with an official download from MS.

**Comment by VictorVG** [comment]
There is no Win7 HH.exe in the MSDN image, I now don’t remember exactly where this binary for VHD was taken from, but in my opinion with WinXP OEM CD-ROM. The main thing is that CHM works, but on BSD I have KDE Okular dealing with them, which completely suits me. It would still be on Android 8 for a tablet, but I had to run around there in search of a suitable reader and as a result I settled on ReadEra due to the fact that it can and the fundamental lack of advertising that gets on the tablet no worse than heavy artillery.

**Comment by VictorVG** [comment]
@kjk 

Big thanks! I was sick of it and was sitting at home, but last year on New Year I took such photos on Manezhnaya Square in Moscow. May they delight us all - the New Year is a holiday, which means we must give each other joy.

![IMG_20190110_224205](https://user-images.githubusercontent.com/906886/71699552-21667900-2dd1-11ea-86cd-c9a2188aa410.jpg)

![IMG_20190110_224346](https://user-images.githubusercontent.com/906886/71699553-21667900-2dd1-11ea-931f-ce76907ff5e0.jpg)

**Comment by GitHubRulesOK** [comment]
> 
> 
> There is no Win7 HH.exe in the MSDN image, I now don’t remember exactly where this binary for VHD was taken from, but in my opinion with WinXP OEM CD-ROM. The main thing is that CHM works, 
There is a shareware (Help Explorer Viewer) standalone and api that can open .hlp .chm and .hxs works on windows and linux see https://www.linux.com/news/chm-viewers-linux/

**Comment by VictorVG** [comment]
Ok, but I use any tools.

**Comment by SumatraPeter** [comment]
> There is no Win7 HH.exe in the MSDN image

You're saying MS has specifically removed hh.exe and CHM support from the official Win7 image on MSDN? Why would they do that, especially when CHM is still a supported format even in newer versions of the OS? 😖

P.S. Beautiful photos! I'm sure it would have been a real sight to behold up close and in person. 🙂

**Comment by VictorVG** [comment]
Fuck you chickpeas! :) I mistook the support for the MS Help 1.x and CHM - e formats, ISO itself is not needed because Win7 in VirtualBox starts up, and the machine itself runs under BSD UNIX and was convinced that it was right. Confused, I apologize for the inaccuracy.
