### ISSUE TITLE
Toc editor controls not always visible

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1370]
More often than not the TOC editor controls cannot be seen, they are generally below the screen edge.

This is due to currently using a lo-res widescreen laptop (5/8 of my screens are only 700-800 dpi high)

Since the buttons are at the bottom of their window the TOC editor needs to be maximised to full-screen for them to definitely appear on current screen however they are then hidden by the taskbar

Re-sizing does not help as the controls are at a fixed height instead of at the top

**Comment by GitHubRulesOK** [comment]
@kjk I think it helps a bit that they are not behind taskbar or off the screen but resizing the window still intantly chops them off

![image](https://user-images.githubusercontent.com/12754913/71740682-cd9d7380-2e54-11ea-8406-12f277b062b1.png)

**Comment by kjk** [comment]
Should be better now in that the buttons at the bottom should be of fixed size and the tree view will use the remaining space.

**Comment by GitHubRulesOK** [comment]
@kjk Much better it is only an issue if I park it in a top corner (Auto tiling)
![image](https://user-images.githubusercontent.com/12754913/71757565-cd21ce80-2e8e-11ea-824e-c0923c0dd540.png)

**Comment by GitHubRulesOK** [comment]
@kjk Thanks that realy is much better
