### ISSUE TITLE
Interesting observation #1 re current vbkm behaviours

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1373]
A virtual document (made from multiple files concatenated in the Fixed User Interface) has some unusual behaviours (at present ?)

The Bookmarks appear to work well since they open the combined documents at the required named destination however each document expects links to itself 

So an internal hyperlink that should jump to the contents as page 2 of second document may jump to page 2 in the first document  BOTH are page 2 of 6 (see next comment about numbering)
![Untitled1](https://user-images.githubusercontent.com/12754913/71705378-5bd31480-2dd7-11ea-86d0-27dc40c325db.png)

**Oddly the source document page numbers are used per section see comment on left**
I will raise the observed problem with hyperlink scaling as a seperate Issue

![untitled3](https://user-images.githubusercontent.com/12754913/71705510-0a775500-2dd8-11ea-81da-ec06d05021af.png)

**Comment by kjk** [comment]
This functionality is abandoned.
