### ISSUE TITLE
Scrolling with thinkpad trackpoint is difficult

### ISSUE THREAD

**Issue by amosbird** [sumatrapdfreader/sumatrapdf#138]
I need to press hard on trackpoint in order to start scrolling. But this will lead to a fast scroll which is not wanted.

**Comment by kjk** [comment]
This is not really related to Sumatra. The sensitivity of scrolling can probably be adjusted in the driver for your device but Sumatra scrolls as fast as we're asked to. If we change it, it'll change the speed for everyone else.
