### ISSUE TITLE
Suggestion about nomenclature

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1380]
Can I suggest vbkm keeps causing me to misspell many ways VirtualBookMarK etc
It also is migrating to a Virtual Compendium of Documents with Bookmarks

My suggestion is to reconsider the extension to a more symbolic TLA such as 
.CDF for combined Document Format or Compendium of Document Files
or
 SDF (SumatraPDF Document File/Format) or 
 SCF (Sumatra Combined/Compendium File/Format)

even VBM is easier but since we are calling it a TOC editor the files could be **.toc**

which leads to the next suggestion that in the editor the buttons currently say add PDF and save as Virtual PDF but the supported formats are wider / broader and save as could be **save as .whatever**

**Comment by kjk** [comment]
This functionality is abandoned.
