### ISSUE TITLE
Bookmark are offset from expectation

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1385]
There are a few issues where the comment is that SumatraPDF does not follow the expected position of bookmarks and whilst reviewing .vbkm I note SumatraPDF frequently shows a 2 page span for location
This sample file may illustrate the problem.
In Acrobat each bookmark shows the text for the top of each page so Bookmark1=Page 1 etc.
In sumatraPDF set to single page the second and third show the bottom of the previous page
[Icecream bookmarks.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4023603/Icecream.bookmarks.pdf)

**Comment by kjk** [comment]
It would be interesting to see screenshot from Acrobat.

As far as I can tell, Sumatra does the right thing. Here's the bookmarks:
```
"New bookmark 1" page:1 destkind:scrollTo destname:"#1,0,-7" destpage:1 destrect:0.000000,-7.000000,-999.900000,-999.900000
"New bookmark 2" page:1 destkind:scrollTo destname:"#1,0,842" destpage:1 destrect:0.000000,842.000000,-999.900000,-999.900000
"New bookmark 3" page:2 destkind:scrollTo destname:"#2,0,842" destpage:2 destrect:0.000000,842.000000,-999.900000,-999.900000
```

`#1,0,842"` is the value recorded in PDF and it's the bottom (y=842) of 1st page. Maybe Acrobat has heuristic logic that says "if it's the bottom of page N, go to page N+1"

**Comment by GitHubRulesOK** [comment]
@kjk just to confirm downloaded above file and opened in Acrobat 9 and seleted Bookmark3 

![image](https://user-images.githubusercontent.com/12754913/71786652-90c4ae80-3005-11ea-8e82-24a6fbeaa689.png)

If you are correct that Adobe uses a heuristic method that would potentially explain why the converse is often reported that a bookmark at end of page sometimes shows the next page see descripion in  https://github.com/sumatrapdfreader/sumatrapdf/issues/1075

**Comment by GitHubRulesOK** [comment]
@kjk close this issue I juct double checked and it is the same behaviour in Acrobat single page
