### ISSUE TITLE
Open cbr cbz

### ISSUE THREAD

**Issue by lon0** [sumatrapdfreader/sumatrapdf#139]
Hi, in win-7-64bit I can't plan the automatic opening of cbr and cbz files with Sumatra as default, while in win-7-32bit I can do it. Could be added a menu for choosing which extensions to open with Sumatra please?

**Comment by GitHubRulesOK** [comment]
@kjk this was a separate request to support issues with user setting file type permissions in win-7 x64 (which still plagues win 10 users) however in light of impending MS "End of Life" declaration for win 7
I am reluctantly suggesting this simply be considered a dupe of  https://github.com/sumatrapdfreader/sumatrapdf/issues/615#

**Comment by kjk** [comment]
This is now tracked by #1248
