### ISSUE TITLE
Curent build fails on file that was not a previous problem

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1391]
@kjk Fresh install and opening an.epub file that has behaved well throught testing caused crash
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4030409/sumatrapdfcrash.zip)
worked in 11922 fails in 11938+

**Comment by kjk** [comment]
Looking at crash report, it looks like it's caused by associated .bkm or .vbkm file. Could you share that file as well?

I can't get it to crash without it or with a newly exported bookmarks file.

**Comment by GitHubRulesOK** [comment]
@kjk luckily or un-luckily 😃 
[accessible_epub_3.epub.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4031766/accessible_epub_3.epub.zip)
in this case I had not deleted them

**Comment by GitHubRulesOK** [comment]
{update] similar to #1390 = bad bkm file
