### ISSUE TITLE
Larger PS files will not load in SumatraPDF

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1392]
This is a bug report for an issue raised in the forum under https://forum.sumatrapdfreader.org/t/postscript-filesize-limitations/2594

> Whenever i open a .ps file that is bigger than 20MB i get an error saying “error loading \filepath\file.ps”

**Comment by GitHubRulesOK** [comment]
@kjk a GS command such as follows (irrespetive of file size) runs without problem when started in program files the input was 33 Mb and result is 26 Mb and the output file is readable, thus GS appears to be functioning

gswin64c -q -dSAFER -dNOPAUSE -dBATCH -dEPSCrop -sOutputFile="D:\Samples\ePS\foo.pdf" -sDEVICE=pdfwrite -f "D:\Samples\ePS\file.eps"
GPL Ghostscript 9.50 (2019-10-15)
Copyright (C) 2019 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.

So I am stumped as to why SumatraPDF can not read the output unless there is a user conflict in memory or access location. The one related thing I did note was that I think the error was quicker to appear than the time taken to write the PDF to disk.

**Comment by GitHubRulesOK** [comment]
@kjk sorry to report that if doubling the timer did work then in current build 11973 both previously good small eps and large ps cause crash
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4037279/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
Thanks for testing. That was just a bad logging I've just added. Should be fixed.

And the bug overall should be fixed by recent change to increase ps => pdf conversion timeout from 10 sec to 20 sec.

**Comment by GitHubRulesOK** [comment]
@kjk yes just to confirm my 33Mb test.ps file works
 oddly it feels like under 10 seconds 👍

**Comment by GitHubRulesOK** [comment]
Summary of some comments on forum
**per kjk**

> I increased the timeout from 10 sec to 20 sec.
> Let me know if you have documents that take even more than that. I can increase it even more.

> Also, as a last resort, you can set SUMATRAPDF_NO_GHOSTSCRIPT_TIMEOUT env variable to disable timeout completely.

I tested a 30Mb file (described above) and it worked with the 20 second default (sorted 👍 )
I downloaded a 300 Mb.ps and set the environmental value in system

> Ok I got success with 300 Mb ps file after about 8 minutes (much too long a time frame) but this is a 1/2 tread coal powered laptop so in SumatraPDF I save as a 30Mb PDF and now it loads in 5 seconds wow! no waiting next time. (result 👍 )
> 
> As mentioned above I set the no_timeout in system settings and checked it is always there after boot


![image](https://user-images.githubusercontent.com/12754913/72111597-2d06f200-3333-11ea-9cc0-953a4cb16f45.png)
