### ISSUE TITLE
Show more document properties

### ISSUE THREAD

**Issue by StephanBusch** [sumatrapdfreader/sumatrapdf#1394]
Please add some more document properties to SumatraPDF.
I would like to see more information about content like this:

file size: 10.000.000 bytes (7.500.000 bytes are images, 2.000.000 bytes are text, 500.000 bytes are fonts)

or in percentage:

file size: 10.000.000 bytes (75% are images, 20% are text, 5% are fonts)

or with image format info:

file size: 10.000.000 bytes (75% are images (60% JPG, 15% PNG), 20% are text, 5% are fonts)

This would make SumatraPDF more unique as no other free tool seems to support that.
What do you think?

**Comment by GitHubRulesOK** [comment]
The number of bytes for a pdf is to a degree meaningless
the filesize might be 100 KB but the images of shown text are 400 KB whilst plain text content may be 1 KB rendered by glph streams that are compressed to 50 Kb but expand to 100 KB
what value are any of those raw or worse converted to totally irrelevant percentages

Analyse any single page with one PDF tool and you will get a different set of values when compared with another, similarily for epub and images.

**Comment by kjk** [comment]
The specific information you ask for is impossible to calculate given how PDF format works.
