### ISSUE TITLE
Wine: Tabs are not working correctly

### ISSUE THREAD

**Issue by BrendonIrwan** [sumatrapdfreader/sumatrapdf#1395]
*NOTE: Take this as a low-priority issue, as the problem could lie on Wine itself. In case you're not aware, Wine is a Windows compatibility layer for Unix systems.*

Anyways, the problem is that the way tabs are highlighted is broken. I move my mouse cursor to one tab just to see another that is highlighted. With that, clicking activates the highlighted tab. Oddly, this is not the case for the first tab which works perfectly fine.

This is a [[known bug](https://appdb.winehq.org/objectManager.php?sClass=version&iId=35681#knownbugs)] on their end.

I can see some TODOs in the GUI source code, but I dunno whether it has something to do with this problem.

Disabling tabs makes the program pretty much working perfect as it does on Windows.

I have my reasons to use SumatraPDF on my Linux system (especially MuPDF!).

SumatraPDF 3.1.2, Wine 4.0

**Comment by SumatraPeter** [comment]
@kjk: Since [both](https://bugs.winehq.org/show_bug.cgi?id=38823) the [bugs](https://bugs.winehq.org/show_bug.cgi?id=42877) seem to be Wine-related, not sure anything can be done at your end?

**Comment by kjk** [comment]
I don't test under wine so not much I can do (assuming it can even be fixed in application code).
