### ISSUE TITLE
-reuse-instance -page <pageNo> not working in daily/prerelease 

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#1397]
Tested today in Win10 with 
`SumatraPDF-prerelease-11951-64.exe` and 
`SumatraPDF-prerelease-11967-64.zip`

Example 
`SumatraPDF.exe C:\test\a.pdf -reuse-instance -page 5`
This should go to page 5 in the SumatraPDF window where `a.pdf` is already open.
But instead the command closes SumatraPDF.

**Comment by GitHubRulesOK** [comment]
@kjk confirmed 
I did not check -reuse recently in current builds but I think it worked a month ago in 11561 and presumably previous builds

**Comment by nod5** [comment]
Confirming that `-reuse-instance -page` works again in daily build `SumatraPDF-prerelease-11972-64.zip`
