### ISSUE TITLE
"Remember opened files" option freezes interface when file(s) not available

### ISSUE THREAD

**Issue by EverEve** [sumatrapdfreader/sumatrapdf#1399]
Hello, I'm an affectionate user of the program and I've experienced an issue for the first time: when the "Remember opened files" option is selected (the default setting, I think) and one of the last opened files is on a path currently not available (such as a network share), the program opens but is unresponsive and there is no way to make it work. 

I think that a sort of timeout could be introduced before the file is marked unavailable and the GUI can open normally.

Thanks for your attention.

**Comment by GitHubRulesOK** [comment]
@kjk sounds similar to #1126 (and #1084 ) could be consolidated ?

**Comment by EverEve** [comment]
Hello, it seems the same error to me. Sorry, I tried to search but I didn't find them.

Thanks, you can close the thread.

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Consolidate as mentioned above?
