### ISSUE TITLE
Remember Document position only by filename and not by path.

### ISSUE THREAD

**Issue by Joachim-Otahal** [sumatrapdfreader/sumatrapdf#14]
I often read .PDF's from zip/rared packages.
Each time I open the same PDF it has a different temporary path, so Sumatra PDF cannot remember the position I was on.
Solution would be:
Keep the history of reading positions only by using the file name, and not the path.
As an optimization: To distinguish between two documents which use the same name use the file size. I know, the PDF file size is not yet stored ; ).

(Created as suggested in http://forums.fofou.org/sumatrapdf/topic?id=3184549&comments=1 )

**Comment by rolandbeck** [comment]
Wouldn't it be an option to store a short checksum of the document? Then it could be recognized even if the name changed.

A workaround for you issue would be to use a program which uses a defined temp path. In 7-ZIP (www.7-zip.org) you can configure that - maybe that might help you.

**Comment by ivan866** [comment]
Long-reading pdfs are often renamed or moved. It's a pity to loose track of your reading progress just because of some folder in its path was renamed. Sometimes I reread whole chapters before I can recall what I've already read.
