### ISSUE TITLE
fail to display this pdf since v2.5

### ISSUE THREAD

**Issue by jjzz** [sumatrapdfreader/sumatrapdf#140]
Get notblack.pdf here: https://www.dropbox.com/s/fhpj9w4j63jh4i0/notblack.pdf?dl=0
The pdf contains only an embedded image.

Tested on Sumatrapdf v2.1 to v3.0 @winxp and @debian7 through wine,
before ver2.4, sumatrapdf could display the page correctly
after ver2.5, there is only a full black page.

BTW, when opening with Sumatrapdf v3.0 @wine@debian7 from console, it outputs some error log below,
```
- filter-jbig2.c:101: jbig2dec error: prevent DOS while decoding height classes (segment 0)
- filter-jbig2.c:103: jbig2dec warning: Garbage beyond end of file (segment -1)
warning: ... repeated 5 times ...
! filter-jbig2.c:71: jbig2_page_out failed
- mupdf/fitz/stream.h:238: read error; treating as end of file
- image.c:246: padding truncated image
warning: ... repeated 11 times ...
```
It mentioned something about mupdf. Then I tried mupdf/xpdf/evince/... on debian7, but all these stuffs open notblack.pdf correctly.

**Comment by gschenck** [comment]
It displays ok in latatest pre-release (http://www.sumatrapdfreader.org/prerelease.html)

**Comment by kjk** [comment]
Thanks @gschenck for verifying. Closing as it's been fixed.
