### ISSUE TITLE
Minor issue with .vbkm last page number

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1403]
Have not recently experienced a long hang but on occasion slow loading of large ToC entries, I expect this may get worse on this slower laptop as more entries are added to be processed.

What is a consistent fail is not seeing the last page number as shown in the second lower image.

Again whilst testing with the #1400 example how useful .bkm is for user corrections
**I was impressed that I can edit** page 6 AND the incorrect Page 10 and Page 11 entries
![untitled](https://user-images.githubusercontent.com/12754913/72198028-391cad80-3420-11ea-9017-e9ff928e9428.png)

however, when saving as .vbkm the last entry causes a problem see attached with .vbkm
[Sumatra.PDF.Bookmarks.Issue.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4048913/Sumatra.PDF.Bookmarks.Issue.zip)
![image](https://user-images.githubusercontent.com/12754913/72198149-f6a7a080-3420-11ea-9017-f907c7784796.png)

**Comment by kjk** [comment]
This functionality is abandoned.
