### ISSUE TITLE
.bkm changes

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1407]
Trying not to raise too many side issues whilst bookmarks are clearly under development.
[I have edited below to update them to current status]

Many requests /issues are answered by the one-on-one approach of having a .bkm (i.e. side-car file)

The potential of correcting erroneous native bookmarks and adding fresh ones is apparent.

What features may be worth considering now are the following. 

**[edited to reflect more recent changes]**

<strike>1) if any object to be opened such as a.pdf, b.cbz djvu (?epub) etc. has a valid **.bkm it be given priority over "Default"** bookmarks **or replace** the need for them e.g. as has been done for a .cbx that could be expanded to say include plain .txt files ?</strike> Partly changed as now does NOT select default but shows the field as Blank for user seslection ?

2) The structure of a .bkm should be as simple as possible so as not to cause any confusion etc.
however currently the first unedited line is
version: 998
that "4 character Magic Signature" of "vers" could be fixated to a unique ID and I would suggest "SBkm version" or "SToC version" would clearly identify the pedigree of the following lines as Sumatra or a Substitute Table of Contents.

<strike>3) at present I see no reason **except for folders** to include the path for the third line **file:** it seems not to matter for .bkm files)
If reserving it is for future expansion that could simply be added to the line in the future as additionally **path:**</strike>

4) There are some file states currently not stored in settings that could be added early such as 
a) Full document view overide e.g. **rotate:** [0,90,180,270]
b) Auto opening actions without using javascript such as a **default:** **goto page:** (and scrollto?)
c) other user prefered over-ride states for documents e.g. for a comic **zoom:** fit content

5) .bkm files would lend themselves to enhancements that would reduce the demands on the one settings history
thus could include individual page numbers to be rotated independent of full document rotation

**Comment by kjk** [comment]
This functionality is abandoned.
