### ISSUE TITLE
Crash on unexpected bkm/vbkm behavior

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1413]
I think it is easier to illustrate with screen grabs if you need more info let me know

![image](https://user-images.githubusercontent.com/12754913/72555641-e5cdb380-3894-11ea-95e7-0eec72a6ef65.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
this seems to happen most frequently 
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4084251/sumatrapdfcrash.zip)
when files with .bkm WERE active and THEN files are closed such that the last man standing at the time of the crash is only the.vbkm

**Comment by GitHubRulesOK** [comment]
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4185850/sumatrapdfcrash.zip)

just confirming this is a repeatable crash
open any pdf with bookmarks
save its bookmarks as bmk file
save and include bookmarks as part of a new.vbmk
close sumatrapdf for that days session

return later to open any pdf (with any attendant .bkm)
reopen a .vbkm and note there is a secondary "default view"
attempt bookmark navigation = crash

**Comment by GitHubRulesOK** [comment]
@kjk the second part of this issue is still a frequent problem whilst testing (the first part seems better/fixed)
Using multiple tabs I am very likely to have both a .bkm and a .vbkm open sometime in the same session. Usually clicking in the .vbkm TOC will trigger closure

**Comment by GitHubRulesOK** [comment]
@kjk 
slightly better in latest builds but still causes occasional crash

**Comment by kjk** [comment]
Hopefully fixed now.
