### ISSUE TITLE
Security problems with 2 user install

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1414]
Totally clean installation of windows 10 thus no history
Install SumatraPDF for First user no problems
That's an admin account, So install for a secondary user, expecting all first user pointers would be ignored, Install appeared to go well I should have twigged that I did not need to select options as they were "ALREADY" selected !

![image](https://user-images.githubusercontent.com/12754913/72573102-81bee580-38bc-11ea-8492-4946bd26ac3d.png)

It took hours to fully untangle the registry settings, remove the first user install and revert to "Program Files" for both users
see comment https://github.com/sumatrapdfreader/sumatrapdf/issues/1287#issuecomment-561455503 by @sumatrapeter :-)

**Comment by GitHubRulesOK** [comment]
@kjk ping
I have given this some thought
I had no problems as a single user with the current installer
I had no problems as a multi-user with the main app in program files

There were/are countless support problems with related apps such as MiKTeK which tries to  offer installs  for both admin and non admin users without making it obvious of the pitfalls related to dual installation.

My suggestion is at first install to offer 2 simple either or selection boxes (NOT hidden by options)
"Single user on this PC" (user app data)
"Multiple users on this PC" (Program Files and user app data)

When running 1 user uninstall it MUST clear all previous historic references to any exe locations

Thus the worst case is on uninstall failure we can say assuming the have not forgotten account access

Re-install for the original single user, then uninstall for that same original single user 
then fresh installation for all users.
Draconian Armageddon alternative is to fully delete the master single user account

**Comment by kjk** [comment]
This is not a supported scenario. It's just getting complicated and very time consuming to test the installer. No plans to improve this.
