### ISSUE TITLE
.bkm failing to handle some help files

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1417]
To check chm handling including utf-8 characters I use Windows 10 System Help files for other languages. That does not mean they are error free, but they should be reasonable?

Since chm can used in two modes I tested in both and with these files there are the expected differences in page numbers per mode.

However, what was unexpected was missing entries after some bookmarks.
 And secondly this was more evident in FixedPageUI
The different behaviours including in the English file suggest it may not be simply down to rogue characters but some other cause.

[chm.bkm from fixedUI-false.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4080493/chm.bkm.from.fixedUI-false.zip)
[chm.bkm from fixedUI-true.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4080497/chm.bkm.from.fixedUI-true.zip)

**Comment by kjk** [comment]
I've disabled .bkm / .vbkm support for non-pdf files but I checked those .chm files with latest code by exporting .bkm file and it seems have the same toc tree view.
