### ISSUE TITLE
Bookmark fonts seem at variance with expectation

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1418]
@kjk 
Whilst testing some bookmarks handling I noticed Bold and Italic fonts as used by Tracker software do not reflect what is shown in SumatraPDF, unclear which is right but Acrobat agrees with Tracker?
Test sample [Tracker bookmarks.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4081926/Tracker.bookmarks.pdf)
The difference appears to be due to a reversal in code (there may be more but the obvious ones are)

    src/BaseEngine.h approx line 205
    None = 0x0,
    Bold = 0x1,
    Italic = 0x2,

     src/PdfEngine.cpp  approx line 1700
    // TODO: not sure about the mappings yet
    if (flags & 0x1) {
        res = res | TocItemFlags::Italic;
    }
    if (flags & 0x2) {
        res = res | TocItemFlags::Bold;
    }
    if ((flags & ~0x3) != 0) {
        // TODO: is there more?
        CrashMe();

![image](https://user-images.githubusercontent.com/12754913/72671454-549c3f80-3a42-11ea-87df-0baf89b9d0e6.png)

**Comment by GitHubRulesOK** [comment]
@kjk just tested that commit and it now got worse
![image](https://user-images.githubusercontent.com/12754913/72694558-42e39680-3b2d-11ea-8d59-9632939726c1.png)

**Comment by kjk** [comment]
Thanks, good catch, should be fully fixed now.
