### ISSUE TITLE
Sometimes opens in German and loses my settings?

### ISSUE THREAD

**Issue by AshTex** [sumatrapdfreader/sumatrapdf#142]
Hi,

I'm using sumatra in conjunction with the LatexTools package on Sublime Text 2. When I haven't got sumatra opened and I build from sublime Sumatra opens in German. However if I open Sumatra from my start menu then it opens in English.

Furthermore if I open it in English then my inverse search functionality works (i.e. shows me where in my ST2 document the reference is), however if I do the same in the german version it just opens the corresponding .tex file in notepad.  

This computer is running win7.

**Comment by kjk** [comment]
I suspect you're executing two different copies of Sumatra, using two different configuration files. Double-check your settings.
