### ISSUE TITLE
ebooks in reflo mode cause .vbkm crash

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1423]
@kjk 
.vbkm supports many file types including e-books in FixedPageUI mode
The ToC editor will generate a .vbkm whilst the file is in reflowable UI however will crash on any attempt to load such a file
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4088817/sumatrapdfcrash.zip) is for mobi 

but similar result with FB2
[KudrinXO.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4088846/KudrinXO.zip)

obviously a 1 page .epub does not crash but 4pages will
[epub.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4088859/epub.zip)

**Comment by kjk** [comment]
Yeah, reflowable documents are not supported by EngineMulti, because the page number is not fixed. No plans to address this and currently .vkbm is limited to .pdf files.
