### ISSUE TITLE
.xps saved as .vbkm causes crash

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1426]
@kjk Possibly related to #1423

.xps seem to use a less conventional contents moniker than usual
[xps crash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4094353/xps.crash.zip)

note that if the .vbkm has similar contents to the corresponding .pdf it works without crashing

```
pages: 7
"PDFTron Licenses Coverpage" page:1 destkind:scrollTo destname:#1,0,-4 pos:0,-4
"PDFTron Enterprise CPU License Agreement" page:2 destkind:scrollTo destname:#2,0,-4 pos:0,-4
"PDFTron Web Application CPU License Agreement" page:5 destkind:scrollTo destname:#5,0,-4 pos:0,-4
```

**Comment by kjk** [comment]
For now .vbkm is only supported for .pdf files but this .xps file had a crash due to a link that couldn't be resolved and now that's fixed.

**Comment by GitHubRulesOK** [comment]
I had noted that currently .vbkm is focused on PDF;s that already have ToCs
 but its usage for files including comic books / epub / txt or others such as chm / xps / djvu is of much interest
