### ISSUE TITLE
Documentation on compiling SumatraPDF and differences between versions

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#1428]
**Request 1: Add documentation on how official SumatraPDF releases are compiled**

**Request 2: Add documentation on the differences between release, prerelease, debug and other builds**

**Background:** I can see that compiled Debug versions have support for making annotations. But they differ from prerelease versions hosted on the website (e.g. they have debug menu items). Do they also differ in other ways? Are there any reasons against running a compiled debug version for day to day use as long as it doesn't crash etcetera? For example are there some memory/file security aspects that differ when using the Debug version?

The build alterantives in Visual Studio 2019 CE are 
`Debug , Release , ReleaseAnalyze` and 
`Win32 , x32_asan , x32_xp , x64`

**Currently available information on SumatraPDF website and GitHub**

From readme.md at https://github.com/sumatrapdfreader/sumatrapdf
```
To compile you need Visual Studio 2019. Free Community edition works.
[---]
Open vs2019/SumatraPDF.sln when using Visual Studio 2019

You need at least version 16.4 of Visual Studio 2019.
```

https://www.sumatrapdfreader.org/docs/Join-the-project-as-a-developer.html
This seems outdated:
```
You’ll need Visual Studio 2017 or 2015. A free Community edition will work.
```

https://www.sumatrapdfreader.org/docs/Our-build-system.html
```
How official builds are made
I use Go program tools\build\main.go. You can read it for details of operation.
```
The file `main.go` mentions `ReleasePrefast` which doesn't seem to be an option in Visual Studio 2019 CE when opening `vs2019/SumatraPDF.sln`

**Comment by kjk** [comment]
I've updated info in https://www.sumatrapdfreader.org/docs/Our-build-system.html
