### ISSUE TITLE
#new feature, splitting with a second window

### ISSUE THREAD

**Issue by apollo2mond** [sumatrapdfreader/sumatrapdf#143]
hi, i really would like an option to open a second window that e.g. i could read and compare two different documents.

i like sumatapdf, thanks for your great work!

**Comment by GitHubRulesOK** [comment]
@kjk as you know this has always been possible and still is shown here using current pre-release

![image](https://user-images.githubusercontent.com/12754913/70576368-a4186180-1ba0-11ea-8803-968270132355.png)

@apollo2mond and any other user, **simply dont use tabs i.e switch them off / uncheck in options**.

If you DO want two tabbed windows then see my answer in https://github.com/sumatrapdfreader/sumatrapdf/issues/18#issuecomment-561709625

**Comment by wishinghand** [comment]
Having multiple tabbed windows would be best. The workaround to get them is fairly tedious.

**Comment by GitHubRulesOK** [comment]
@kjk I think both of the above requests are answered by Cntrl N (**and the two of same file using shift**)

**Comment by kjk** [comment]
Agreed, latest pre-release (https://www.sumatrapdfreader.org/prerelease.html) supports multiple windows with "File / New Window"
