### ISSUE TITLE
SumatraPDF!jbig2_huffman_get+0x52 uninitialized memory usage

### ISSUE THREAD

**Issue by expend20** [sumatrapdfreader/sumatrapdf#1431]
tag: 3.1.2rel

Use of uninitialized memory happens in `jbig2_huffman_get()`. `table` param is dereferenced, but memory pointed by that memory is never initialized. 

Allocation of structure `Jbig2TextRegionParams` pointed by local variable `tparams` happens inside of `jbig2_decode_symbol_dict()`, then `tparams` is passed to `jbig2_decode_text_region()` as `params` parameter. That function will dereference it `params->SBHUFFRSIZE` and pass to `jbig2_huffman_get()`.

![](https://i.imgur.com/yvxtB0T.png)

[id_000016_00.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4111447/id_000016_00.pdf)

**Comment by kjk** [comment]
I couldn't reproduce this in master. There's been a lot of changes. Could you see if it still reproduces for you with code in the master branch?

**Comment by expend20** [comment]
Yeah, this case is not reproducible in master (but 3.1.2rel is still the latest officially released version). Feel free to close this. Thanks.
