### ISSUE TITLE
UAF at SumatraPDF!jbig2_decode_symbol_dict+0x1341

### ISSUE THREAD

**Issue by expend20** [sumatrapdfreader/sumatrapdf#1432]
tag: 3.1.2rel

![](https://i.imgur.com/VMeERCn.png)

Crash happens in function `jbig2_decode_symbol_dict()` just before `jbig2_sd_release()` call when the code is dereferencing `refagg_dicts[0]`. Eventually `refagg_dicts` points to already free'd memory.

This is actually quite simple bug, you only need to hit next branch.

![](https://i.imgur.com/R0vsSdJ.png)

Memory pointed by `refagg_dicts` will be free'd and jump to `cleanup4` happens. At `cleanup4` code checks if `refagg_dicts != NULL` and access it and free again, but crash happens earlier.

[id_000000_00.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4111460/id_000000_00.pdf)

**Comment by kjk** [comment]
I couldn't reproduce this in master. There's been a lot of changes. Could you see if it still reproduces for you with code in the master branch?

**Comment by expend20** [comment]
Yeah, this case is not reproducible in master. Feel free to close this. Thanks.
