### ISSUE TITLE
32bit support

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1434]
With the removal of artefacts and 32bit pre-releases (3.2.12063 prerel reports it is the latest and 12073 was last daily accessible) there is no means to download an updated 32 bit version other than the last 3.1.2 release. (Aug 2016)

Whilst I appreciate there are now many derivative branches to manage it has been helpful on occasion to run any security improved such as 3.2.12085 32bit compatible version **especially an XP portable one**

I still have 32bit machines running daily that can only run 32bit windows

I also note that web related trackers such as [filehorse](https://www.filehorse.com/download-sumatra-pdf-32/old-versions/) monitor the pre-release page thus going forward there will be disproportionately many copies of a less stable 32bit build compared to 64bit

**Comment by kjk** [comment]
Only daily builds have no 32bit, pre-release builds do

**Comment by micwoj92** [comment]
Hi, where can I see download pre-releases? When I visit https://www.sumatrapdfreader.org/prerelease.html I see no links to download, tried on Firefox, Chrome, Internet Explorer and Palemoon browsers

**Comment by GitHubRulesOK** [comment]
@micwoj92 your link is working for me are you behind some javascript firewall ?

**Comment by kjk** [comment]
Most likely you've turned off JavaScript or have an extension that blocks those links. Post a screenshot of the page as you see it, that might offer some clue.
