### ISSUE TITLE
.txt support and crash report (only applies to pre-release for now)

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1436]
I spend so much time in pre-releases I forgot that there is no support for .txt files in any formal release version. This also means a feature I use frequently of having a txt.smx is not supported in the formal releases.
Currently the trigger condition is 
ChmUI [
	UseFixedPageUI = true
]
![image](https://user-images.githubusercontent.com/12754913/73220945-89ea1100-4157-11ea-89b4-f1d4add577dd.png)

**BookMarKs would be nice** (only numpages gets listed)
[SumatraPDF-settings.txt.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4119757/SumatraPDF-settings.txt.zip)

and currently attempting new.vbkm causes a crash

[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4119747/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
This crash should be fixed now.
