### ISSUE TITLE
Some regression in character support after MuPDF updates

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1437]
@kjk 
This file is from unknown source (possibly an old issue but suggest it be removed) it fails in Acrobat but worked fine in 3.1.2 up to pre-rel 11133 
[sample.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4120166/sample.zip)

![5](https://user-images.githubusercontent.com/12754913/73227986-32ef3680-416d-11ea-8866-c050a9e4b9d6.png)

**Comment by SumatraPeter** [comment]
Was it due to commit https://github.com/sumatrapdfreader/sumatrapdf/commit/49bb31896dfe9e41cd54919faac9666ee0c3839d I wonder?

**Comment by kjk** [comment]
Yeah, I think it's a good guess. Clearly a chinese font is missing.

**Comment by GitHubRulesOK** [comment]
@kjk ping
possibly red herring but downloadable droid sans are not showing as valid ttf

**Comment by GitHubRulesOK** [comment]
@kjk
Unsure which is the cause since similar to #317 this file was not well-defined and passing through a similar open and save process in an editor the fonts get re-solved thus this smaller cleaner file now works
[sample mod.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4128015/sample.mod.zip)

so although this file highlighted there could potentially be an issue with newer droidsansfallback
I will close this issue as simply another bad file and  have removed  first file

**Comment by SumatraPeter** [comment]
> passing through a similar open and save process in an editor the fonts get re-solved thus this smaller cleaner file now works

Are you sure the re-saved file still refers to the exact same font(s) as the original? Perhaps the editor 'fixed' things by switching to a different font altogether, one that exists on your system?

P.S. What's the big deal with deleting the file? It's an almost 4 year old tour voucher, but if it's really privacy you're concerned about then just deleting the traveller's name and booking reference number and leaving the rest untouched should suffice, in case the file is ever needed again to check rendering in future versions of Sumatra.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
I decided that the file was buggy thus not a valid example to prove poor font handling by SumatraPDF since Acrobat itself could not resolve the file only showing blank pages.
Yes it was somehow handled by earlier version of MuPDF and not by more recent ones which may or may not be due to fallback for a missing  font, overall when "fixed" I felt it was not fair to present as evidence of change.
What I and others can't fathom is when does droidsans substitution kick in and how since the latter versions of MuPDF appear NOT to be using the two font files that themselves appear to be invalid as  ttf's in their more recent libraries ?

**Comment by SumatraPeter** [comment]
All very interesting questions... Hopefully kjk will shed light on the mystery of the broken and unused fonts! 😄

**Comment by kjk** [comment]
Yeah, according to mupdf this file is buggy and one of the issues is that it refers to a font with empty name.

It's possible that with more recovery hacks in mupdf it would work but or maybe it's a regression in mupdf. Either way, maybe you could submit this to mupdf noting that it used to work and it might be bad file and let them decide.

It's not a font issue because it doesn't work in mupdf-gl either (which includes all the fonts).
