### ISSUE TITLE
Epub related feature request

### ISSUE THREAD

**Issue by henryxrl** [sumatrapdfreader/sumatrapdf#144]
Hi,
I just want to say that I love SumatraPdf!

A few requests related to epub files:
1. Able to set SumatraPdf as the default epub reader;
2. Support css styles and embedded fonts, please~~~
3. Consider rename SumatraPdf to SumatraReader? :)

Thanks!

Henry

**Comment by GitHubRulesOK** [comment]
@kjk
request 1 superseeded by https://github.com/sumatrapdfreader/sumatrapdf/issues/1248#
number 2 superseeded by https://github.com/sumatrapdfreader/sumatrapdf/issues/849#
number 3 no comment ?

**Comment by kjk** [comment]
Closing as duplicate
