### ISSUE TITLE
missing document properties

### ISSUE THREAD

**Issue by pulbitz** [sumatrapdfreader/sumatrapdf#1440]
Since certain versions, I can't see some document properties.

Created: 
Application: 
PDF Producer: 

Is this a bug?
Please take a look at the screenshot.

![image](https://user-images.githubusercontent.com/58905725/73459828-dda86480-43ba-11ea-8c1c-a821b4b9f4c4.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
this is only seems to be in commits since update 12085 https://github.com/sumatrapdfreader/sumatrapdf/commit/a20ca64420385eea5aa4b4c6812b5fc6d71dcd75

**Comment by kjk** [comment]
Well spotted @GitHubRulesOK  It was indeed a regression introduced in that commit.
