### ISSUE TITLE
Continuous colours in vector graphic

### ISSUE THREAD

**Issue by Zetison** [sumatrapdfreader/sumatrapdf#1443]
The following file illustrates the bug. It works fine in Adobe but not in Sumatra.
[test3.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4138292/test3.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk needs to be tagged as MuPDF as do the following
This type of surface definition is similar to the problems in #595 and #98 so all 3 could be consolidated

![image](https://user-images.githubusercontent.com/12754913/73536042-f184b280-441c-11ea-8104-f7402d119259.png)

Top line Acrobat (Left) renders ok MuPDF (centre) has had issue for years, Image based viewers fail
Bottom Line Browsers usually dont bother, Editors often OK, SumatraPDF is good with images

**Comment by kjk** [comment]
Reported to mupdf as https://bugs.ghostscript.com/show_bug.cgi?id=702075

**Comment by SumatraPeter** [comment]
> Bottom Line Browsers usually dont bother

FF is fine, and this is one instance where the new ChrEdge does a far better job than the old LEdge.

**Comment by GitHubRulesOK** [comment]
Hoorah
![image](https://user-images.githubusercontent.com/12754913/104673234-37dc2b80-56d9-11eb-9226-0bb2e97667f2.png)
closed in 3.3.13250 todays (15/jan/2021) daily version

**Comment by GitHubRulesOK** [comment]
@kjk 
you should be able to close https://bugs.ghostscript.com/show_bug.cgi?id=702075 ??
