### ISSUE TITLE
Advanced Options does not open SumatraPDF-settings.txt

### ISSUE THREAD

**Issue by kdzmcqn** [sumatrapdfreader/sumatrapdf#1447]
I have downloaded the SumatraPDF app from Microsoft Store in Windows 10.

It installed the app or the SumatraPDF.exe file in

C:\Program Files\WindowsApps\45288PavelKislov.SumatraPDF_1.0.9.0_x64__91mp82afftkgm\win32

I cannot create nor find the .txt file for the advance settings. It's not in the %appdata%

I can't write on the win32 folder for I have to change all the permissions in my PC which I can't, and if I could, it would take hours and might cause problems for me.

For the meantime, I might download and install from the official website. Thanks.

**Comment by GitHubRulesOK** [comment]
Closing as there is no support for cloned copies paid or unpaid
