### ISSUE TITLE
Error loading a fairly large PDF (3.0)

### ISSUE THREAD

**Issue by MarkLeone** [sumatrapdfreader/sumatrapdf#145]
I get "Error loading" this pdf (which is 4.2 MB):  http://ge.tt/2RTVmtC2/v/0?c

**Comment by gschenck** [comment]
The file is probably damaged. It opens neither in Acrobat Reader nor in PDF-XChange Editor.

**Comment by kjk** [comment]
I agree, doesn't open in Preview on mac either.
