### ISSUE TITLE
Epub current crash status

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1453]
@kjk 
since latest fix resets epub to working again I am opening this as fresh issue (however has on occasion been a past problem)

after 3.2.12117 I generally get a crash in Epub
 on attempting to save bookmarks in Ebook UI

**Comment by kjk** [comment]
I'm  re-dong virtual bookmarks so at the moment it's mostly broken for all file types.

But please be more specific: I'm not sure what "attempting to save bookmarks" refers to exactly. Is it "Export bookmarks" context menu item?

**Comment by GitHubRulesOK** [comment]
@kjk aware that you are busy on this area I accept its shakey especially if not deleting old edited .bkm files, Yes my fist action is to refresh any old bkm by requesting a fresh" export bookmarks" using right click context
