### ISSUE TITLE
display flicker

### ISSUE THREAD

**Issue by KarelKlapka** [sumatrapdfreader/sumatrapdf#1454]
First of all - thank you very much for this wonderful piece of usefull software!!!

Sorry if this was already reporterd, I searched "flicker" "blink" keywords with no result.

I experience very often display flicker, when zooming to bigger then default zoom level. In stable release with same files it is not happening. I started to use pre-release, because I like very much the new multiwindow feature, and I'm experiencing it on all several last pre-releases I tried. See attached screen video captures and one of the many files it can exhibits the problem (I don't think it is file specific.). It looks, like continuous redisplay periodical offset shift, so I don't think it is realated to graphic card. Maybe some combination of redisplay with rounding error? When the zoom is returned to smaller value, everything goes back to normal. I usually zoom with right mouse button and wheel, but same behaviour can be seen when entering the value from keyboard and "CTRL+" or "CTRL -".

http://ge.tt/1qo1HB13

Windows 10 Pro, i5-8250U, 16GB

Thank you!!!

**Comment by GitHubRulesOK** [comment]
Hmmm! 
Agreed jitter was not present in 3.1.2 with the given file
Testing 12118 at max zoom it will stop at 6400 then drop back to 4800 then up to 6400
my kit is slow so it takes a while to step in and out, thus I don't normally see it as jitter **unless holding and rolling the mouse wheel quickly** at the same time.
Yes it is highly noticeable in other recent pre-release **when holding down CTRL +** in any file even a single page image


@kjk
As there are no pages of differing width I can say it appears not to be related to other similar width refitting issues, so am considering as unique new issue. When max zoom is reached additional requests to zoom in should be ignored ?

**Comment by KarelKlapka** [comment]
What I'm talking is not the jitter, that is present when you try to zoom even when you are at the largest zoom level. Yes, this is also "undesirable", but acutally, it is not a big issue, yes, max after zoom additional zoom requests should be ignored.

The jitter/flicker I'm talking is happeing at any zoom level below the max at any file, it is not a cosmetic problem, but I realized, that it is happening only at certain occasions. When I opened the file as a single one, everything was ok. And maybe therefore you did not see it as well and look only at the max zoom condition, I don't know. But now I realize, that I expereienced this flicker when more different files were open. So I thought mabye it is happenning under some memory load? I tried to reproduce it via two tests:
1] First one using only the the original test file SUMATRAPDFREADER-prerelease3-2-12118-64b_FLICKERBUG_TP218_zony30.pdf I sended in previous post. After opening I gues 5th copy of the file in same window it starts to flicker (seen at around 00:00:30 of the older video capture), I tried to close the windows one after another, to see if the jitter disappear, but the program crashed.

2] I took the original test file SUMATRAPDFREADER-prerelease3-2-12118-64b_FLICKERBUG_TP218_zony30.pdf and then to simulate the memory load I took some bigger 500MB PDF file SUMATRAPDFREADER-prerelease3-2-12118-64b_FLICKERBUG_Demos_Katalog_kovani_2019_bookmarked.pdf . It seemed to me, that the flicker/jitter appeared sooner, but I'm not sure. I tried to close one window after another, and it seemed to me, that after releaving the load, the issue disappeared, and could be seen only at bigger zoom, later program crashed.
The flicker starts to be seen at aroung 00:01:29 of the later video capture.

I send the two test video captures, with their crashinfos and another bigger pdf test file in the foloowing link (the ge.tt has already low limit for storage for this post):

https://www.uschovna.cz/zasilka/UVMA94KR7BMFPTC6-C77/

**Comment by kjk** [comment]
For easy access I've posted crash info as https://gist.github.com/kjk/3688aa3b5d785af3383ee795bb731d48

The crash is in:
```
bool RenderCache::DropCacheEntry(BitmapCacheEntry* entry) {
    ScopedCritSec scope(&cacheAccess);
    CrashIf(!entry);
    if (!entry) {
        return false;
    }
    CrashIf(entry->cacheIdx < 0);
    CrashIf(entry->cacheIdx >= cacheCount);
    CrashIf(entry->refs <= 0);  <---- CRASH
```

Looks like a bug in render cache, probably triggered by a frequent changes due to low memory.

I couldn't reproduce the flicker which suggests this is triggered by low memory or opening many files which fills the cache.

From the log in crash report it does look like a page is being re-painted in a loop which would explain flicker.

Things to try:
* run under asan and try to trigger this condition to catch the root cause of the crash earlier
* add more logging to the cache
* add run time switches to make cache trigger such scenario more easily

**Comment by KarelKlapka** [comment]
Thank you once more for all the effort!!!

For me it is easy to reproduce when you open more bigger files and possibly in more windows (that's how I actually started to see it - I had two windows opened, each with several files). Though i see it also in one window mode. I can even see, that the flicker disappears, when files in other windows are closed.

**Comment by kjk** [comment]
I can reproduce this by opening 10 PDF files and choosing continuous book view so that we show 4 pages at a time for each PDF.

Zoom is not important here but number of pages shown at the same time across all tabs. Zooming out helps because that way we show more pages at a time.

**Comment by kjk** [comment]
Same as #1711

**Comment by kyeongsoo** [comment]
> I can reproduce this by opening 10 PDF files and choosing continuous book view so that we show 4 pages at a time for each PDF.
> 
> Zoom is not important here but number of pages shown at the same time across all tabs. Zooming out helps because that way we show more pages at a time.

I confirmed the same with the prelease version (v3.2 64-bit with git commit fc8f35a) on 64-bit Windows 10.
As kjk described above, it happens only when I set "show pages continuously". BTW, facing or book view seems not important; I observed in both modes. Also, it is consistent through any PDF documents.

**Comment by kyeongsoo** [comment]
> > I can reproduce this by opening 10 PDF files and choosing continuous book view so that we show 4 pages at a time for each PDF.
> > Zoom is not important here but number of pages shown at the same time across all tabs. Zooming out helps because that way we show more pages at a time.
> 
> I confirmed the same with the prelease version (v3.2 64-bit with git commit [fc8f35a](https://github.com/sumatrapdfreader/sumatrapdf/commit/fc8f35a2d0581735ea361990dc65c674b3cd2dcb)) on 64-bit Windows 10.
> As kjk described above, it happens only when I set "show pages continuously". BTW, facing or book view seems not important; I observed in both modes. Also, it is consistent through any PDF documents.

Sorry, but one fix to my previous post: The version is a stable one (i.e., v3.2) not a prelease one.

**Comment by GitHubRulesOK** [comment]
@kyeongsoo this thread was moved fixed and closed in 26 Jul 2020 please check using current Daily version from https://www.sumatrapdfreader.org/dailybuilds.html

**Comment by kyeongsoo** [comment]
> @kyeongsoo this thread was moved fixed and closed in 26 Jul 2020 please check using current Daily version from https://www.sumatrapdfreader.org/dailybuilds.html

Many thanks for the update!
In fact, I also found that it is fixed with the prelease version I just downloaded.
