### ISSUE TITLE
[regression] wrong display of non-ASCII chars in attached files

### ISSUE THREAD

**Issue by pr-apes** [sumatrapdfreader/sumatrapdf#1457]
[This PDF document](https://github.com/sumatrapdfreader/sumatrapdf/files/4204032/b.pdf) contains the following code:

```
23 0 obj
<<
  /Names [ <312DCEB1CEB2CEB3CEB42E706466> 2 0 R <322DCEB1CEB2CEB3CEB42E706466>
      5 0 R <332DCEB1CEB2CEB3CEB42E706466> 7 0 R <342DCEB1CEB2CEB3CEB42E706466>
      9 0 R <352DCEB1CEB2CEB3CEB42E706466> 11 0 R ]
>>
endobj

26 0 obj
<<
  /EmbeddedFiles 23 0 R
  /Type /Names
>>
endobj
````

SumatraPDF 3.1.2 displays attachment names fine:

![3 1 2-ok](https://user-images.githubusercontent.com/51094960/74523812-22d1a800-4f1e-11ea-8bc1-d29cefa26585.png)

Sumatra nightly build 12145 doesn't handle the names right:

![daily-wrong](https://user-images.githubusercontent.com/51094960/74523807-21a07b00-4f1e-11ea-8316-29d8bf06d6d8.png)

This is a clear regression. Many thanks for your help.

**Comment by kjk** [comment]
dev note: the code is `pdf_load_attachments`. The strings comes from `pdf_to_name`. 
Looks like an encoding issue. I tried using `pdf_new_utf8_from_pdf_string` on that string but it didn't help.
Can't see 3.1.2 doing anything different so maybe mupdf changed?

**Comment by kjk** [comment]
I suspect this is incorrectly created PDF in that /Names property here is in utf-8.

It should either be in PDF encoding or utf-8 prefixed with 239, 137, 191 sequence.

That being said, Sumatra 3.1.2 changed mupdf to add a work-around with badly encoded utf8 text.

I restored that work-around but I'm not sure I'll keep it. I don't want to maintain a fork of mupdf.

**Comment by kjk** [comment]
I've opened https://bugs.ghostscript.com/show_bug.cgi?id=702127 asking mupdf to incorporate similar fix.
