### ISSUE TITLE
[feature request] add support for .ps file

### ISSUE THREAD

**Issue by EAirPeter** [sumatrapdfreader/sumatrapdf#1458]
Is there any plan to add support for .ps (PostScript) file? It would be very helpful when viewing old papers.

**Comment by EAirPeter** [comment]
Sorry I was so careless that did not read documentation.

**Comment by GitHubRulesOK** [comment]
No problem as yo have closed it but it may help you or other to read https://forum.sumatrapdfreader.org/t/postscript-filesize-limitations/2594/25
