### ISSUE TITLE
.vbkm adding siblings and children creates a cracking combination

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1459]
Nice to see this step implemented (just need to also add filename.pdf without inherent bookmarks 🙂 )

Open or drag'n'drop to shortcut or open window works well with a simple edited.vbkm file such as enclosed Part1&Part2. However, if I edit siblings and children the resulting .vbkm seems to crash SumatraPDF instantly (perhaps it is the entries left "hanging")
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4208426/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
For now one rule that needs to be observed is that PDF files cannot be nested (i.e. cannot add a PDF in the middle of another PDF).

My checks in toc editor were not good enough so I allowed creating that. I plugged one hole but there are still more.

I'm still experimenting with what is allowed and how the UI works.

**Comment by GitHubRulesOK** [comment]
I still experience some other related open issues and in testing try to avoid actions that compound those so often rebuild .vbkm from scratch.
It is early days in attempting to predict what a user may require but the most obvious is inserting current page as child or sibling into .bkm or.vbkm . The main issue here is that opening TOC editor is not offering to add the current viewer focus, I am guessing that is work in progress, however to add my own choice of destinations, the edit options need to include a seeded page destination field possibly with scrollto: as preset from current cursor selection or screen coords.

**Comment by kjk** [comment]
I've fixed a bunch of bugs in .vbkm / toc editor handling so this might be fixed. Please open a new bug if you still see bugs.

**Comment by GitHubRulesOK** [comment]
I saw the new page number option which worked well in fixing the bad scrollto bottom of page by delete page entry and reinsert a fresh sibling
All that is missing :-) is adding a scroll to

**Comment by kjk** [comment]
Could you expand on this? Adding "scroll to" where?

**Comment by GitHubRulesOK** [comment]
In ToC editor we can remove a page destination (one that may be incorrect)
We can replace that by deleting  a page entry and replace with a fresh entry.

We may have a ToC entry goes to top of a page but really want to keep returning to the paragraph at end of the page before.

Replacing those entries with a plain page number does not recreate the higher precision of a named destination

For example in TOC editor we add a fourth sequential sibling but the destination will be top of page by default 
```
version: 998
name: default view
file: F:\Data\Samples\PDF\bookmarks\Tracker.bookmarks1.pdf
pages: 1
Tracker.bookmarks1.pdf page:1 open-default
  "Sample in bold" font:bold color:#ff0000 page:1 destkind:scrollTo destname:#1,0,100 destvalue:"Sample in bold" pos:0,100
  "Sample in Italic" font:italic color:#00ff00 page:1 destkind:scrollTo destname:#1,0,200 destvalue:"Sample in Italic" pos:0,200
  "Sample bold italic" font:italic,bold color:#a52a00 page:1 destkind:scrollTo destname:#1,300,-1 destvalue:"Sample bold italic" pos:0,300
  "Last entry at 400 down" color:#ff00dd page:1

```
