### ISSUE TITLE
current problems with TOC Parent Child relationships

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1465]
In the first case 
When attempting to display a Child but not its Parent I see neither, it makes sense but then I have to wait until I can elevate (drag up) the child as a parent's sibling 

The second case is even more problematic When trying to suppress page 1 The Root entry needs to be showing (Page 1 by default) even if I don't want it to

![image](https://user-images.githubusercontent.com/12754913/74788630-35dfd180-52aa-11ea-9e91-c84ccffe0949.png)

**Comment by kjk** [comment]
The first case is by design: I don't think it would be expected to show a child of a hidden parent.

I'll probably add a way to edit destination page to allow adding / changing / removing destination.
