### ISSUE TITLE
F1 Suggestion

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1467]
It is helpful to be able to refer to the extensive list of shortcuts (and links) as shown on the "manual" page. Currently, that can be called via <kbd>ALT</kbd><kbd>H</kbd><kbd>M</kbd> (when using English) in a browser from the menu.

In portable mode that may not always be possible and I would prefer a "local" copy to pop up in a new window.

The file could be PDF format, located relative to and alongside SumatraPDF-settings.txt, so it works installed or portable.

The file would of course need updating at intervals to reflect web based changes.

A nice feature update would be that I can press F1 which would check if the PDF copy is in position and if exists open it as a PDF in a new window but if not then attempt to call the web version.

**P.S.** just realized it would be even better if the default for F1 was to open a help.vbkm which could be expanded if desired by adding other pdf files after the default of manual.pdf
![image](https://user-images.githubusercontent.com/12754913/74892101-97726f80-5380-11ea-9a47-244d746167e5.png)

**Comment by SumatraPeter** [comment]
If the Manual, Help etc. PDFs are separate optional downloads then fine, but personally I wouldn't want them to be bundled so that they make the portable version downloads more bloated.

As you rightly say there's also the headache of keeping the files updated, unless perhaps that can be automated.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
yes bloat would be 400kb as per this mock up which is more up to date than the web one
[Manual.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4228149/Manual.pdf)

**Comment by SumatraPeter** [comment]
If something has to be included then I'd much rather that the "home" page of the app, that displays the About dialog content when no files are open and the MRU thumbnails list is turned off, instead display the list of KB shortcuts. Yes, that'll have to be updated as well when required, but it ought to be easy enough to do so when code for new/modified shortcuts is added.

**Comment by kjk** [comment]
`Help / Manual` is adequate. I don't think it happens often that people don't have internet connection.
