### ISSUE TITLE
.vbkm Bookmark scrollto's seem to be horizontally challenged

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1468]
Perhaps adjusting scrolling function has upset scrollto but in .vbkm vertical seems working whilst horizontal seems to be ignored

**Comment by kjk** [comment]
Unfortunately this is not for every tree view, for now it's only for the bookmarks.

**Comment by GitHubRulesOK** [comment]
@kjk command line -scroll x,y works for vertical but not horizontal value ?

**Comment by GitHubRulesOK** [comment]
In general the above issue has now been resolved
