### ISSUE TITLE
I cannot click drop-down menu in a PDF file

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [sumatrapdfreader/sumatrapdf#147]
Please fix for it.

https://savannah.gnu.org/bugs/download.php?file_id=33212

**Comment by pdgessler** [comment]
The linked PDF does not actually have a drop-down menu in it—it's just an image of the drop-down box with text overlaid.

**Comment by kjk** [comment]
Like @pdgessler said, there is no bug.
