### ISSUE TITLE
Another Manual addition

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1471]
Noticed that recently added 

< Ctrl > + B  add current page to favorites

is missing

**Comment by GitHubRulesOK** [comment]
@kjk
I see this "Action" has been allocated on Manual page to Bookmarks however it adds **Favorites**
I left a suggestion or two via Notion but could not see any way to call up this manual page

**Comment by kjk** [comment]
Good catch, moved to Actions section.
