### ISSUE TITLE
Qestion - Exception: C0000005 ACCESS_VIOLATION if try testing x64 v3.2.12216 Git-a9748039b - is my error???

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1472]
At the end of the build process, I get a warning LINK: warning LNK4199: for / DELAYLOAD: d2d1 and Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 0033E4D7 01: 0029D4D7 sumatrapdf.exe
Fault writing address 00000000

for the AMD64 assembly, and during testing it crashes with AV. x86 assembly builds and works without errors. I assumed that the error in the working copy, deleted and re-cloned it with Git, but the phenomenon is reproduced on two machines. The test crashes while reading example.fb2. It is possible that the error is somehow related to my machines, but I got confused and cannot figure out where to look for its cause. Also, I don’t understand why the second test cycle, which should output a colored background, displays a white background as if it ignores the settings specified in the config ...

In to attach have links for:

https://www.upload.ee/files/11183780/SumatraPDF_v3.2.12216_Git-a9748039b.zip.html - all build files, include .PDB and crash logs;

https://www.upload.ee/files/11183795/SumatraPDF_testkit.7z.html - my used test kit

[spdftest.cmd.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4249862/spdftest.cmd.zip) - my used test script

https://www.upload.ee/files/11183800/SPDF_toolkit.tar.xz.html - my used build toolkit

**Comment by kjk** [comment]
Please try to reproduce this with latest daily build from https://www.sumatrapdfreader.org/dailybuilds.html and narrow it down to a reproducible test case: a single file and a sequence of actions to trigger the crash.

It's a significant effort for me to reverse engineer your setup to be able to re-run those tests.

**Comment by VictorVG** [comment]
I try build commit 0125904 use MS VS2019 v16.4.5 and have two error log - both for x86 and AMD64 build. For AMD64  

> Error	LNK1104	cannot open file '..\out\rel64\libmupdf.exp'	libmupdf	G:\dev\SumatraPDF\source\vs2019\LINK	1	
> Warning	LNK4070	/OUT:libmupdf.dll directive in .EXP differs from output filename '..\out\rel64\libmupdf-reg.dll'; ignoring directive	libmupdf-reg	G:\dev\SumatraPDF\source\vs2019\libmupdf.exp	1	
> Warning	LNK4070	/OUT:libmupdf.dll directive in .EXP differs from output filename '..\out\rel64\libmupdf-reg.dll'; ignoring directive	libmupdf-reg	G:\dev\SumatraPDF\source\vs2019\libmupdf.exp	1	
> Warning	LNK4199	/DELAYLOAD:d2d1.lib ignored; no imports found from d2d1.lib	SumatraPDF	G:\dev\SumatraPDF\source\vs2019\LINK	1	
> Warning	LNK4199	/DELAYLOAD:d2d1.lib ignored; no imports found from d2d1.lib	SumatraPDF-dll	G:\dev\SumatraPDF\source\vs2019\LINK	1

Both build log's is attached:

[**Output-Build_AMD64.txt**](https://github.com/sumatrapdfreader/sumatrapdf/files/4263593/Output-Build_AMD64.txt)
[**Output-Build-x86.tx**t](https://github.com/sumatrapdfreader/sumatrapdf/files/4263594/Output-Build-x86.txt)

Falls are still being saved, I think that due to errors during linking, there seems to be nothing more to cause a failure ...

**Comment by VictorVG** [comment]
Debugger show:

![1](https://user-images.githubusercontent.com/906886/75481254-d07b9700-59b3-11ea-99ce-88b926b8297f.png)

**Comment by kjk** [comment]
This should be fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/44e9962d7d91c8d78e0039d2e99677d5059bf263

Let me know if you see a crash after that.

**Comment by VictorVG** [comment]
@kjk 

Thanks! Crash fixed, saved only warning:

> Warning LNK4199 /DELAYLOAD:d2d1.lib ignored; no imports found from d2d1.lib SumatraPDF G:\dev\SumatraPDF\source\vs2019\LINK 1
> Warning LNK4199 /DELAYLOAD:d2d1.lib ignored; no imports found from d2d1.lib SumatraPDF-dll G:\dev\SumatraPDF\source\vs2019\LINK 1 

but since the program does not crash, they can be "not noticed". :)
