### ISSUE TITLE
Some pdf file can't show correct.

### ISSUE THREAD

**Issue by teraStars** [sumatrapdfreader/sumatrapdf#1473]
I found some pdf file can't show correct.
Sample pdf:
http://iis.aastocks.com/20190430/003482954-0.PDF

sumatrapdf version:3.2.12，and i have test the newest prerelease version built on 2020-02-20,the bug still exist.

**Comment by GitHubRulesOK** [comment]
@kjk regression is highly noticeable


![image](https://user-images.githubusercontent.com/12754913/75258207-036c3200-57de-11ea-8665-4d8803efbd9d.png)


potentially related  to https://github.com/sumatrapdfreader/sumatrapdf/issues/1443#

**Comment by SumatraPeter** [comment]
Sample file can be added to https://bugs.ghostscript.com/show_bug.cgi?id=702075 as well I suppose... Haven't seen much movement however on any of the MuPDF bugs filed by kjk so far. Wonder what their devs are up to? 🤔

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
Whilst the rendering outcome is equally bad the sources are different e.g. this one is Adobe In Design
So I guess the cause and effect may be different I have submitted as https://bugs.ghostscript.com/show_bug.cgi?id=702158

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Perhaps you can mention the older bug 702075 too? Maybe if someone picks up 702158 this might prompt them to investigate and fix the other one as well.

**Comment by GitHubRulesOK** [comment]
Wow! That is the fastest mupdf fix I ever saw, I had not bothered checking back as "too soon" shame it doues not resolve any other open ones
