### ISSUE TITLE
Debug crash on launch due to zoom being 0 (works in 12152)

### ISSUE THREAD

**Issue by th3v4n** [sumatrapdfreader/sumatrapdf#1475]
Am I doing this right?

[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/4268469/sumatrapdfcrash.txt)

[Hegel. Encyklopädie der philosophischen Wissenschaften im Grundrisse (1830).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4268470/Hegel.Encyklopadie.der.philosophischen.Wissenschaften.im.Grundrisse.1830.pdf)

**Comment by kjk** [comment]
The crashing callstack:
```
00007FF7CD6A9C27 01:0000000000188C27 sumatrapdf.exe!EnginePdf::Transform+0x57 D:\a\sumatrapdf\sumatrapdf\src\EnginePdf.cpp+1107
00007FF7CD5F1D88 01:00000000000D0D88 sumatrapdf.exe!DisplayModel::CvtToScreen+0xd8 D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+813
00007FF7CD5F43BA 01:00000000000D33BA sumatrapdf.exe!DisplayModel::SetScrollState+0x8a D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+1542
00007FF7CD5F232C 01:00000000000D132C sumatrapdf.exe!DisplayModel::SetViewPortSize+0xfc D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+957
00007FF7CD6527F1 01:00000000001317F1 sumatrapdf.exe!WindowInfo::UpdateCanvasSize+0x231 D:\a\sumatrapdf\sumatrapdf\src\WindowInfo.cpp+134
00007FF7CD5E77D9 01:00000000000C67D9 sumatrapdf.exe!WndProcCanvas+0x379 D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1538
```

It's the debug crash due to zoom being 0. Seen it before, need to investigate more.

**Comment by kjk** [comment]
Maybe fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/99be84d214206a2308adfa926b9730598121a7e7
