### ISSUE TITLE
High CPU% when marking text with the mouse

### ISSUE THREAD

**Issue by finsor** [sumatrapdfreader/sumatrapdf#1477]
Marking text in a document (basically left-click and dragging the mouse continuously) can easily get the thread to utilize 100% of its CPU time. The bigger the window, the more drastic it is.

Windows10 1809
SumatraPDF 3.1.12 64bit

**Comment by GitHubRulesOK** [comment]
Helps if you confirm which windows platform and which version SumatraPDF

**Comment by finsor** [comment]
@GitHubRulesOK edited OP

**Comment by finsor** [comment]
@GitHubRulesOK edited OP

**Comment by GitHubRulesOK** [comment]
Version seems to be wrong please check "help about" recent pre-release builds are 3.2.12192 or later
and confirm it is an official download from https://www.sumatrapdfreader.org

**Comment by kjk** [comment]
I can't reproduce this in latest builds https://www.sumatrapdfreader.org/dailybuilds.html

It's possible you have a really large monitor that simply re-painting the document takes so much time.

Please re-open if it happens in latest build and you can provide more information, such as:
* size / resolution of the monitor
* does it happen with every document or just one / few
* what is the layout setting
* a recording of task manager showing CPU usage
