### ISSUE TITLE
Background settings not working as described in Presentation mode

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1478]
Manual says

. | in presentation mode, change background to black
-- | --
w | in presentation mode, change background to white

In my case whole screen goes black or white and calling a page defaults back to white page on black background
If the intent is to provide a blank white or black screen the description would be best saying 
**change screen to all**  ...
Others have requested border follows a user choice such as is provided by GradientColors

**Comment by kjk** [comment]
I'm tempted to remove those. I didn't add them and I don't quite get why they are there.

**Comment by GitHubRulesOK** [comment]
I first thought they were dysfunctional but then realized some users doing a "presentation" may need to have a means to blank the screen one way or the other so reconsidered the wording as misleading
