### ISSUE TITLE
Remove annotation under mouse from external tool with windows message

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#1479]
Requesting a method that external tools (and SumatraPDF itself) can use to remove any annotation under the mouse. More precisely put remove any annotation whose rectangle contains the X Y pt under the mouse.

Here is my attempt at adding such a function and windows message
https://gist.github.com/nod5/0092e749ff7b8991ece69fcb1d7f5feb

~~Problems with my attempt:~~
- ~~I have to call the function twice for it to have effect (no idea why yet)~~
- ~~I have not found a way to make the annotation removal to be immediately reflected in the UI view.~~

Edit: It was a small mistake in my code, fixed now. The annotation removal is now reflected quickly in the UI.

Note: The above request is related to the more general topic of adding more methods for external tools to interact with SumatraPDF in #1411 . See comment https://github.com/sumatrapdfreader/sumatrapdf/issues/1411#issuecomment-590618613 there for my latest code attempts at several such methods .

**Comment by nod5** [comment]
GIF showing SumatraPDF with the gist code above added called from an external AutoHotkey script  https://imgur.com/a/pEVYHKv 

Quick thoughts on more things that could be added to the function (via parameter options):
- option to remove all annotation on page number N (used if LParam value int >0)
- option to remove annotation under mouse only if it has a certain color (used if LParam value if COLORREF)

**Comment by nod5** [comment]
Updated gist code to have two different features: If lParam is an integer > 0 then consider that a page number and remove all annotations on that page. Else remove annotations under cursor.

@kjk any thoughts on this and the other attempts?

**Comment by kjk** [comment]
@nod5 It looks good.

To set expectations: annotations are still experimental and I plan to work on them after 3.2 release.

That will most likely significantly change the current code so I'm not that crazy about adding more code today that will have to be changed later on.

Ideally, the things you want to achieve would be possible by configuring sumatra (via a combination of being able to define new keyboard shortcuts and bind them to snippets of JavaScript code to perform operations).

**Comment by nod5** [comment]
@kjk Ok, that makes sense.

I assume that a >3.2 release with your reworked annotations code is a at least some months away. Correct?

Then in the meantime I will
- Keep the default mode in HighlightJump compatible with your SumatraPDF Prereleases. That mode works ok today. (With one exception, see 1. below.) So anyone who wants to test some extra annotation features right now can do that while using the Prerelease version.
- Keep on experimenting on my own with the second, better mode that requires compiling SumatraPDF with the kind of C++ modifications I've linked to here.

I personally use the second mode when reading/highlighting PDFs near daily and also have fun learning some C++, so will keep at it 😃. I won't release custom binaries. So only those interested enough to compile themselves will use that second, experimental mode. Likely few.

Hopefully my experiments can serve as illustrations / ideas for the upcoming SumatraPDF annotation rework.

Given the above, and taking as a given from now on that you won't add much new annotation code in the near future, I shift gears to **two more modest requests**:

**1. Include the pagenumber under the mouse to SumatraPDF's "m" position notification.**
Because there is no way to get that information in the current SumatraPDF Prereleases. With that in place I can fix one big shortcoming in default mode HighlightJump when it comes to removing highlights one one specific page when multiple pages are visible. It seems the only edit needed is to change [SumatraPDF.cpp#L1887](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/SumatraPDF.cpp#L1887) from 
```
AutoFreeWstr posInfo(str::Format(L"%s %s", _TR("Cursor position:"), posStr.get()));
``` 
to
```
    int pageNo = win->AsFixed()->GetPageNoByPoint(pos);
    AutoFreeWstr posInfo(str::Format(L"%s %s %s %d", _TR("Cursor position:"), posStr.get(), _TR("Page:"), pageNo));
```
We then see e.g. ` Page: 5` at the end of the position notification. The pagenumber updates correctly as the mouse moves to another page. It shows `Page: -1` when mouse is not over any page.
![position_notification](https://user-images.githubusercontent.com/11015788/75719715-8c4f0600-5cd5-11ea-9118-e737afd6ff32.png)

**2. Document the difference between steps to compile Debug versions and the Prerelease/Daily versions you publish.**
Requested earlier in #1428 . One very noticeable difference is that the `Menu > Debug > Highlight Link` option is on after each start of the Debug binary but off at the start of Prerelease binaries. I assume there are other differences. It would be useful to have steps on how to start with the GitHub master, add in some C++ edits and then compile a binary that is in other respects (Highlight Link off etcetera) similar to the Prerelease/Daily. For personal use and testing, I will not publish custom binaries.

**Comment by GitHubRulesOK** [comment]
The many different changes mean this requirement for historic annotations has been covered via a different method.
