### ISSUE TITLE
[feature request] Integrate FileState with some cloud platforms to remember last page across devices

### ISSUE THREAD

**Issue by mlt** [sumatrapdfreader/sumatrapdf#148]
It is common to read same files from different devices and thus problem arise how to recall last opened page. For example, [Acrobat suggests to use acrobat.com](http://blogs.adobe.com/acrobat/reader11-0-1updates-page-syncing/). AFAIK [some people place sumatrapdf config on Dropbox and place a symbolic link back](http://forums.fofou.org/sumatrapdf/topic?id=3183717). This would work for files residing in Dropbox with same path across devices.
I'm not familiar with sumatrapdf code much, but [it looks like FileState stores MD5 sum of a file](https://github.com/sumatrapdfreader/sumatrapdf/blob/71e41092ed0c8b10335725cf7e958571857d2bde/src/SettingsStructs.h#L186). For simple reading MD5 would stay same if a file is unchanged. This could be integrated with, e.g., [Dropbox Datastore API](https://www.dropbox.com/developers/datastore/tutorial/http) to use as a key to look up other FileState structure fields if available. At least zoom, scrollpos, and page could be of interest.

**Comment by Kaylakaze** [comment]
I was coming here about the same issue. I haven't taken a look at the SumatraPDF code yet (gotta go to work in a few minutes) but I may see about starting work on it this weekend. Chances are though, I wouldn't integrate Cloud, but separate FileStates into its own (or folder that stores a single file per book) and then have path aliases assigned in the main config. For example, the Filepath string could either be an absolute path like it is now, or, if the file is in an aliased folder, it would be something like "$!IT_BOOKS!$\subfolder\book.pdf". Then the FileState file or folder can be linked in your Dropbox, GDrive, OneDrive, or whatever sync folder. This allows the user to use any provider they want.

**Comment by kjk** [comment]
We don't have plans to work on that.
