### ISSUE TITLE
(New Feature Request) Multi-open the PDF reader

### ISSUE THREAD

**Issue by b4imetu** [sumatrapdfreader/sumatrapdf#1482]
(New Feature) Hope to have a Multi-Mode which allows user to multi-open the software.
Because so many Tabs is so annoying and impossible to switch quickly.

**Comment by kjk** [comment]
In latest builds (https://www.sumatrapdfreader.org/dailybuilds.html) we already have:
* File / New Window option
* when you drag&drop file from explorer on sumatra, if you hold Shift, it'll open in new window
* for cmd-line use, add `-new-window` option to open in a new window

I think those options cover this.

**Comment by GitHubRulesOK** [comment]
@b4imetu 
In current version if you go Settings > Options > Use Tabs and uncheck then you can have multi files in multi windows
And in new pre-release the CTRL SHIFT N will still open a copy of that file in a separate window
