### ISSUE TITLE
WorkInProgress sort order is not persistant

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1486]
I am intrigued how useful sorting may be 

Observed that sorting is not persistent since here color was active but on returning to that tab the colors are not sorted by color
![image](https://user-images.githubusercontent.com/12754913/76119580-a5aec580-5fe7-11ea-9671-f206ccb2ed5a.png)

**Comment by kjk** [comment]
This functionality is abandoned.
