### ISSUE TITLE
ToC Save as PDF niggle 1

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1487]
When using Save as PDF the extension is not automatically added
The file is valid and can be viewed but does not show up in file open (since that requires changing to "All Files" in order to list it)

![image](https://user-images.githubusercontent.com/12754913/76145139-b8280e00-607e-11ea-8442-00141392c520.png)

**Comment by kjk** [comment]
This functionality is abandoned.
