### ISSUE TITLE
ToC Save as PDF Niggle 2

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1488]
Having changed the order of pages (and saved the .vbkm)
![image](https://user-images.githubusercontent.com/12754913/76147182-8c625380-6091-11ea-884b-e29fc5d6d09f.png)

The expectation is the contents of the new pdf would be shuffled, but they are not (yet?)

**Comment by kjk** [comment]
This functionality is abandoned.
