### ISSUE TITLE
.vbkm has problems displaying correct page

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1489]
When manually building / adding new pages. The resulting "bookmarks" do not behave.
This is most obvious when real bookmarks are not present.

In this simplified case all bookmarks have been added but only the ones for the first pdf are respected
when selecting those for the second entry they (logically but unexpectedly) point to pages in the combined file.
[2files.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4302182/2files.zip)

This feels like a duplicate of an issue raised earlier but can't remember if it is open or was closed

**Comment by GitHubRulesOK** [comment]
This issue can be frustrating when trying to compose a larger set of single page PDFs or a mixture.
Every page is page 1 and requires avoiding the TOC editor so as to manually increment each page number.

**Comment by kjk** [comment]
This functionality is abandoned.
