### ISSUE TITLE
Is there a plan for mac osx version of SumatraPDF?

### ISSUE THREAD

**Issue by ifmihai** [sumatrapdfreader/sumatrapdf#149]
In my opinion, 
SumatraPDF is the best pdf reader, 
but moving to mac, I wondered if osx will be supported in the future.

**Comment by kjk** [comment]
No, we don't have plans for mac version. See https://github.com/sumatrapdfreader/sumatrapdf/wiki/Why-only-Windows%3F

**Comment by sn0wyfall** [comment]
It's sad because Mac alternatives for SumatraPDF suck.
