### ISSUE TITLE
Web page difference

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1490]
There is an extra web page tab for version history 
that only appears on the forum page (not on any of the other tabs)

![image](https://user-images.githubusercontent.com/12754913/76178630-d9d4e280-61af-11ea-93fb-a733b0de1b81.png)

And depending on browser the Banner is still intrusively misleading on the four other tabs

![image](https://user-images.githubusercontent.com/12754913/76178932-ff162080-61b0-11ea-9b0f-08e3ebeb464a.png)
![image](https://user-images.githubusercontent.com/12754913/76179233-13a6e880-61b2-11ea-8674-339bc59c6cea.png)

**Comment by kjk** [comment]
Fixed
