### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by yozhic** [sumatrapdfreader/sumatrapdf#1491]
Just scrolling [this pdf](https://archive.org/download/1923AmericanTypeFoundersSpecimenBookCatalogue/1923ATFSpecimenBook.pdf) from start to finish, starting on page one. Look at how much memory uses Sumatra v3.2.12205 Git-43892bdbe:

![4GB memory using](https://funkyimg.com/i/332bA.png)

4 Gb!  
Sumatra v3.2 Git-4207ab7ab wasn't so «greedy»:

![350 Mb memory using](https://funkyimg.com/i/332c1.png)

Only 350 Mb. The same pdf on the same machine. I only changed the version of the Sumatra.

I am testing on Windows 8.1 x64 virtual machine (under Parallels Desktop on Mac OSX host).

**Comment by kjk** [comment]
Was just aggressive caching.

**Comment by Dharmainiciativ** [comment]
Unfortunately, it only got worse. Upon reaching 202 pages of the test document above Sumatra just hangs, eating about 281 mb

**Comment by yozhic** [comment]
Ooops... Windows 8.1 x64
![Sumatra Hangs](https://funkyimg.com/i/333ta.png)

**Comment by kjk** [comment]
That was unrelated regression in logging that would lock up. Should be fixed now.

**Comment by SumatraPeter** [comment]
@kjk: [Here's another report from the forum](https://forum.sumatrapdfreader.org/t/regression-or-giant-memory-leak-in-spdf-3-2/3353) of a high res PDF that 3.1.2 could handle but seems to overwhelm 3.2+ (tested with SumatraPDF-prerel-13136-64 also), to such an extent that the entire system hangs and requires a hard reset. Link to sample file can be found in the forum thread. Anything that can be done to improve the situation in this case?
