### ISSUE TITLE
Latest build is struggling with Simple 2.0 file

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1493]
Attached file was not a problem for 3.1.2. 
But hangs in current 12315 build
[Simple PDF 2.0 file.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4326488/Simple.PDF.2.0.file.pdf)

**Comment by kjk** [comment]
Logging would lock up. Fixed
