### ISSUE TITLE
Reduce pdf text search memory use

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1494]
There is a feeling something may still be off with balancing memory (using 12316)
I am peaking at 50%CPU and 3GB memory (about as much as this laptop has) whilst attempting to very slowly search an 80MB file certainly a bad heavyweight file for this charcoal driven underpowered kit.
![image](https://user-images.githubusercontent.com/12754913/76568784-857c7c00-64a9-11ea-9baa-f5cdbe01a49c.png)

It is so slow and taking so long I think I  will go and have a tea break and see if it found something in half an hour or so.

**Comment by GitHubRulesOK** [comment]
Possibly not fair to compare such a file that appears to render compressed pages slowly
However a search from page 1 to page 211 took just 40 seconds including page render in 32bit version 3.1.2. only peaking at 500MB

**Comment by kjk** [comment]
There's probably a way to optimize text search, but after 3.2.

Dev notes:
* can use bug #1491 file for testing
* in `EnginePdf::ExtractPageText` (and then `fz_new_display_list_from_page` we decompress / cache images, which probably can be avoided
* alternatively, re-write the text search completely
