### ISSUE TITLE
Lazy load tabs to speed up the startup time

### ISSUE THREAD

**Issue by fatjing** [sumatrapdfreader/sumatrapdf#1497]
The startup performance lacks severely if the program is configured to load the previous session on start, especially when a lot of tabs need to be restored.
It'd be nice to have only the foreground tab restored at startup, and lazy load those background tabs upon switching.

**Comment by jddcef** [comment]
It loads pretty fast for me the last year or so, using the 3.5 etc pre-release versions.

**Comment by kjk** [comment]
I've implemented loading on background threads, so slow documents no longer block the main thread (i.e. you get fast startup time).

**Comment by jddcef** [comment]
Just realised, why is it called a "pre-release", if it's actually AFTER the last release. 

A pre-release sounds older, as if it's before (pre) the actual release, therefore outdated!

p.s. the website's page is missing links to download on https://www.sumatrapdfreader.org/prerelease

**Comment by kjk** [comment]
Well, it's before the next release. But I see how this might be confusing.

> p.s. the website's page is missing links to download

You must have JavaScript enabled.

**Comment by hpvd** [comment]
follow up on optimizing startup time incl. approach see https://github.com/sumatrapdfreader/sumatrapdf/issues/4803
