### ISSUE TITLE
[Feature Request] Add Smooth Scrolling To the Software

### ISSUE THREAD

**Issue by wanzzhehe** [sumatrapdfreader/sumatrapdf#1498]

**Comment by GitHubRulesOK** [comment]
Closing as undefined duplicate of either
https://github.com/sumatrapdfreader/sumatrapdf/issues/1083
or https://github.com/sumatrapdfreader/sumatrapdf/issues/873
or https://github.com/sumatrapdfreader/sumatrapdf/issues/248
consolidated with https://github.com/sumatrapdfreader/sumatrapdf/issues/606
