### ISSUE TITLE
Increase default/maximum tab size to at least 800 pixel.

### ISSUE THREAD

**Issue by JouMxyzptlk** [sumatrapdfreader/sumatrapdf#15]
My case looks like this, two (or more) documents opened which follow this naming style:
Long writer name - long series name - book title.pdf
Which appears as tab:
[Long artist name - long series n...X]
So I can't see which tab contains which document, making me switch around tabs more often than needed.
800 pixel looks to me like "big enough maximum tab size", but simply making the tab as large as possible would work too if that is simpler to implement.

**Comment by GitHubRulesOK** [comment]
@kjk this feature is active in pre-release but not official releases, I have never seen a problem using this setting, perhaps it can be mirated to official release ?
