### ISSUE TITLE
Copy+paste fails to correctly handle non-BMP Unicode

### ISSUE THREAD

**Issue by a741526163** [sumatrapdfreader/sumatrapdf#150]
Trying to copy and paste from http://www.unicode.org/charts/PDF/U20000.pdf results in clipped output: Instead of the expected U+20A3B 𠨻 and U+267E6 𦟦, U+0A3B ਻ and U+67E6 柦 ends up on the clipboard. Copy and paste works as expected (no funky clipboard contents) in Adobe Reader.

**Comment by ousia** [comment]
> Trying to copy and paste from http://www.unicode.org/charts/PDF/U20000.pdf results in clipped output: Instead of the expected U+20A3B 𠨻 and U+267E6 𦟦, U+0A3B ਻ and U+67E6 柦 ends up on the clipboard. Copy and paste works as expected (no funky clipboard contents) in Adobe Reader.

@a741526163, many thanks for your report.

To reproduce the issue, it is extremely helpful to have the page number. I guess you are copying the char from page 46 (numbered as page 45 in the PDF file), aren’t you?

In that case, evince-3.10.3 (using poppler-0.24.3) can search and copy the first character you mentioned.

**Comment by a741526163** [comment]
I am using Windows XP, and the page number doesn't really matter because the PDF is quite literally full of non-BMP Unicode characters; the ones given were simple examples.

**Comment by GitHubRulesOK** [comment]
@kjk I feel this is a system issue outside of SumatraPDF's control
On windows 10 even notpad using default font will recieve the expected characters from the clipboard

![untitled](https://user-images.githubusercontent.com/12754913/69280245-dbb56e80-0bdd-11ea-86f4-e5c8a89403c6.png)

**Comment by kjk** [comment]
It seems to work for me on Win 10 as well.
