### ISSUE TITLE
Keep vertical offset after page flip

### ISSUE THREAD

**Issue by ossapandra** [sumatrapdfreader/sumatrapdf#1500]
Hello! A page can be manually panned (moved), but after a page flip (next page), only the horizontal offset is kept and the vertical offset is lost.

The attached image shows three instances of Sumatra stacked on top of each other, from left to right. The first one shows the page normally. In the second Sumatra, I panned the page so that all useless space is cropped for optimal viewing. The third Sumatra shows the same page after I clicked NextPage (Ctrl+Right) and PrevPage (Ctrl+Left): Notice how only the horizontal positioning is kept and the vertical is reset to default. I would really appreciate if there'd be an option to keep the vertical offset/panning/movement/positioning during page flip.

Thank you, bye!

![grafik](https://user-images.githubusercontent.com/9304388/76760697-63774800-678e-11ea-9769-9b02eca4f52a.png)

**Comment by GitHubRulesOK** [comment]
As you state in this case both
horizontal position across page (bottom slidebar)
and zoom level should stay the same when rolling from **start** of one page to **start** of the next

So what you are asking for here is that the use can scroll to a user variable vertical (fixed horizontal) position
Each user would want a different offset system and this was requested in the past for reading say music scores where the required part could be a set distance down the page.

It would be possible to add an application macro to automate a button for moving down a page
such as provided by AutoHotKey however since this is a per user requirement why not just use the existing built-in commands

You need to decide how much you want each fresh page to move (you can use the measure tool)
then write an `ExternalViewers ` scrollto shortcut to reopen the current page at that position
Then after you change each page run that shortcut

**Comment by ossapandra** [comment]
By adding the following code to the advanced options file, a new menu item gets added to Sumatra, which basically re-opens the file and scrolls to the position I want. But this solution is very uncomfortable. You have to manually change the options-file for every new offset, practically is restricted to one-instance-only setup, and requires additional software to implement a shortcut (at least I did not find a "shortcut" entry in the docs).

But I wonder why this seems to be a trouble for the devs at all? The horizontal offset is kept automatically already, so why not also keep the vertical offset too? At least optionally.

Bye!

```
ExternalViewers [
	[
		CommandLine = "C:\Program Files\SumatraPDF\SumatraPDF.exe" -reuse-instance -scroll 47,58
		Name = Brutalscroll
		Filter = *.pdf
	]
]
```

**Comment by GitHubRulesOK** [comment]
@ossapandra 
I am very pleased to see you followed my suggestion it is a **personal_kludge_** which you can vary and helps you see some of the underlying requirement about the way horizontal position is / not  held by zoom width etc
Which is in no way related to scrolling to a horizontal and vertical offset (sometimes they may coincide)

To make it a shortcut put & in front e.g. &Brutalscroll then the shortcut will be ALT +F + B

**Comment by GitHubRulesOK** [comment]
@kjk 
Whilst this may seem to be a bit of a niche requirement (**setting a top left off set per page**)

It is required by users who need to simply know they will be positioned at the same relative location from page to page e.g. wind section of a music score or top left avoiding borders

to be most effective it would need to take up screen-space possibly like the CTRL + Y zoom pop-up

**Comment by ossapandra** [comment]
Firstly, I thank you for all the information.

But I really struggle to see this as a "niche" feature at all. "Zoom to content" is a must-have function of every decent PDF reader, and the vertical offset is the option to manually optimize its automatic result. The zoom-to-content does remove white space, but many documents have other static, but useless elements on their perimeters, which prevents the zoom-to-content to do a good job. Perhaps people with 32" screens underestimate the value of this functionality ;)

**Comment by GitHubRulesOK** [comment]
@kjk 
I find in some cases this idea of jumping to a given page (scroll) position is quite useful and suggest that if implemented it could perhaps be assigned to ALT(ernative) PageUp/PageDown

It is ideally used with a given zoom factor (initially set by the user "fitting" width) thus the settings could best be added to CTRL Y dialog and then that in turn could be renamed to Scroll & Zoom ?

**Comment by chrisemb** [comment]
The current version (3.3.3) has a checkbox at/for:
(menu icon)->View->Show Pages Continuously

I suggest to make the two-option-checkbox a three-option radio button:
- “normal” (like today, when unchecked; I didn’t find a good name right now)
- “Show Pages Continuously” (like today, when checked)
- “Keep Viewport” (new, fixes the viewport or the top left corner, depending on what makes more sense in case the window is resized)

Is this feasible?

**Comment by kjk** [comment]
I understand the issue but it seems very esoteric i.e. not many people would use it and I don't know of any other program that does that. Realistically, given all other issue, I will never get to it.
