### ISSUE TITLE
Error Loading message displayed when opening:  SysadminsRuledTheEarth.epub 

### ISSUE THREAD

**Issue by Ferretaa** [sumatrapdfreader/sumatrapdf#1501]
When opening SysadminsRuledTheEarth.epub the message Error Loading is displayed. 
Have attempted opening the file with:
Versions:  3.1.2, 3.2 & SumatraPDF-prerel-12382-64.exe built on 2020-03-18

When Sysadmins Ruled the Earth: .mobi and .epub | Cory Doctorow's craphound.com: 
[https://craphound.com/overclocked/2014/01/14/when-sysadmins-ruled-the-earth-mobi-and-epub-2/](url)

[SysadminsRuledTheEarth.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4346933/SysadminsRuledTheEarth.zip)

**Comment by GitHubRulesOK** [comment]
Crap-non original copy fails in all readers I tested
get the original from the source it works perfectly
https://craphound.com/overclocked/Cory_Doctorow_-_Overclocked_-_When_Sysadmins_Ruled_the_Earth.epub
