### ISSUE TITLE
v3.3.12383 Git-d79a014b3 - thats it???? 

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1503]
Then run v3.3.12383 Git-d79a014b3 I see only this screen: 

![v3 3 12383 Git-d79a014b3](https://user-images.githubusercontent.com/906886/77063528-e72f6f80-69ee-11ea-8f77-6e153015969b.png)

If run SumatraPDF <file_name> also show only this screen....

thats it????

**Comment by VictorVG** [comment]
I also try test Your [**SumatraPDF-prerel-12383-64.exe**](https://www.sumatrapdfreader.org/dailybuilds.html) - equivalents screen....

**Comment by GitHubRulesOK** [comment]
@VictorVG 
Looks like the development / experimental code got mixed into master.
I guess @kjk is now sleeping so will be awhile before he sees this

**Comment by VictorVG** [comment]
Thanks! I rewrite my build toolkit - https://github.com/VictorVG/Source/releases/tag/SPDFTK-1.7.0 and also retest it.:)

**Comment by GitHubRulesOK** [comment]
@VictorVG 
I **never** did understand what your toolkit does 
Is it a way of running SumatraPDF on unix without Wine ?

Also I note 1.6.#

Recommend use for build SumatraPDF v3.3 or **never**

Is that word supposed to be **newer** ?

**Comment by VictorVG** [comment]
This is a set of scripts that I use to build SumatraPDF from source. In version 1.7, I threw out unnecessary intermediate operations and directories. The cp, mv, rm utilities can be taken from either UNIX, LINUX, or the UNIX utilities package from Msys (Msys2) or CygWin. Testing is carried out by another script using a set of test files, after which the spub.cmd script prepares a commit. This is done to reduce the likelihood of errors or skipping operations.
