### ISSUE TITLE
[regression] wrong/unexpected settings file location

### ISSUE THREAD

**Issue by MayanKoyote** [sumatrapdfreader/sumatrapdf#1504]
Release 3.2 store SumatraPDF-settings.txt in %LOCALAPPDATA%\SumatraPDF\ instead of %APPDATA%\SumatraPDF\
This break inheritance of settings (including history, etc) from previous installed version and expected work in the environment of roaming profiles.

**Comment by GitHubRulesOK** [comment]
Duplicate of #1502
