### ISSUE TITLE
Error on start page while scroll mouse and press shift and +

### ISSUE THREAD

**Issue by spam-receiver** [sumatrapdfreader/sumatrapdf#1509]
Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FF75B5751C0 01:00000000001141C0 sumatrapdf.exe!FrameOnCommand+0x1ba0 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+4354
Fault reading address 0000000000000000

I have no such directory C:\Users\kjk

[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/4358280/sumatrapdfcrash.txt)

**Comment by kjk** [comment]
For future reference: could be reproduces with `Ctrl - +` (keyboard shortcut fro IDT_VIEW_ZOOMIN).
