### ISSUE TITLE
Crash when trying to navigate a reloaded PDF's bookmarks

### ISSUE THREAD

**Issue by d125q** [sumatrapdfreader/sumatrapdf#151]
Consider the following file:
```tex
\documentclass{article}
\usepackage{blindtext}
\usepackage{hyperref}

\begin{document}
\section{Sec1}
\blindtext[1]
\section{Sec2}
\blindtext[1]
\end{document}
```
Make sure you compile it properly so that `hyperref` generates PDF bookmarks. Open the file in SumatraPDF. Everything's OK. Now, change the file in the following manner (adding a new section will also do):
```tex
\documentclass{article}
\usepackage{blindtext}
\usepackage{hyperref}

\begin{document}
\section{Sec1}
\blindtext[1]
\section{Sec2Edited}
\blindtext[1]
\end{document}
```
Recompile the file properly. SumatraPDF will update the file (make sure you still have it opened), as expected. Now, try to navigate the second bookmark, and SumatraPDF will crash.

(Running a 64-bit compile of the latest Git version)

**Comment by kjk** [comment]
Since you seem to have compiled the code, can you post the crash callstack, preferably using a debug build ?
