### ISSUE TITLE
Pre-release / Daily build - Looks like the Website script is not functioning today

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1510]

**Comment by GitHubRulesOK** [comment]
@kjk unsure if it has fixed pre-release until you cycle through a pre-rel update certainly the daily is accessible

**Comment by GitHubRulesOK** [comment]
@kjk normal service does seem to be restored with Pre-rel 12402

**Comment by kjk** [comment]
thanks for verifying
