### ISSUE TITLE
Access Violation in try use Manga mode for not Commics Books files for v3.2 or never

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1511]
If user try us Manga mode for not Commics books files like PDF, DjVu, CHM, ePub, FB2, e.t.c. then SumatraPDF is crashed in to RtlUserThreadStart() then try read address 0x00000000. I copy part WinDbg disassembler output:

```
RtlUserThreadStart:
0000000077863820 48 83 EC 48          sub         rsp,48h  
0000000077863824 4C 8B C9             mov         r9,rcx  
0000000077863827 48 8B 05 5A F4 0D 00 mov         rax,qword ptr [Kernel32ThreadInitThunkFunction (077942C88h)]  
000000007786382E 48 85 C0             test        rax,rax  
0000000077863831 74 0C                je          RtlUserThreadStart+1Fh (07786383Fh)  --- crash point
0000000077863833 4C 8B C2             mov         r8,rdx  
0000000077863836 48 8B D1             mov         rdx,rcx  
0000000077863839 33 C9                xor         ecx,ecx  
000000007786383B FF D0                call        rax  
000000007786383D EB 1A                jmp         RtlUserThreadStart+39h (077863859h)  
000000007786383F 48 8B CA             mov         rcx,rdx  
0000000077863842 41 FF D1             call        r9  
```
and attach [**crashinfo.zip**](https://www.upload.ee/files/11303525/crashinfo.zip.html) include crash-report, .dump, .map and .pdb files for crashed version.

Idea for resolving this problem - use extensions/file type filter for disable/hide Manga mode for unsupported file type.

P.S.

_Sorry, but my debugger can't decode dump and show source code - I have maximum only disassembler code then this dump analyses ..._

**Comment by GitHubRulesOK** [comment]
Confirmed with
sumatrapdf-prerel-12387.exe

- open pdf
- select view Manga Mode
- zoom = crash

**Comment by VictorVG** [comment]
Big thanks!
