### ISSUE TITLE
Crash in template_affine_N_near_fa0 on extreme zoom

### ISSUE THREAD

**Issue by AakaFosfor** [sumatrapdfreader/sumatrapdf#1514]
Happened when zooming (if I remember correctly).
Report: https://gist.github.com/AakaFosfor/5dd14a18ce0908e2bf9ed7c99b236835
Loaded file: http://www.hygpraha.cz/Admin/_upload/files/1/SZU-osvetove%20materialy-spravne%20techniky-hygiena%20rukou/SZU-hygiena%20rukou-navodne%20samolepky.pdf
Let me know if something more should be provided.

**Comment by kjk** [comment]
I couldn't reproduce the crash locally. I tried zooming in and out.

If you can reproduce the crash reliably, it would be helpful to know a deterministic list of step to get the crash.

**Comment by GitHubRulesOK** [comment]
@kjk 
I had tried to fail on that file in 64 bit without issue
tried 32bit portable took lots of time messing about with views and zooms but did eventually crash
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4363614/sumatrapdfcrash.zip)

**Comment by AakaFosfor** [comment]
Crashed again here:
https://gist.github.com/AakaFosfor/26d64b3083175ffcfd106c3ad61a062b
Try to zoom in to the arrow head in the step 7:
[![sumatrapdfcrash.png](https://i.postimg.cc/qRBXgbHR/sumatrapdfcrash.png)](https://postimg.cc/Z9gyMLRt)

**Comment by GitHubRulesOK** [comment]
@kjk 
confirmed extensive zooming into that location with 64 bit daily SumatraPDF-prerel-12398-64
oddly that version did not download debug files **I get failed to download message**

[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4363665/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
Thanks for additional information, I can repro it as well.

It's a tough one as it happens in mupdf.

**Comment by kjk** [comment]
The problem is in `fz_paint_image_imp`:
```
    dp = dst->samples + (unsigned int)((y - dst->y) * dst->stride + (x - dst->x) * dst->n);
```
`x - dst->x` is negative, which is cast to a very large unsigned number, this makes `samples` point to invalid address which then will be accessed in `template_affine_N_near_fa0`

**Comment by kjk** [comment]
https://bugs.ghostscript.com/show_bug.cgi?id=702243

**Comment by SumatraPeter** [comment]
[Local copy of file](https://github.com/sumatrapdfreader/sumatrapdf/files/4364112/SZU-hygiena.rukou-navodne.samolepky.pdf) in case it disappears from that site.

**Comment by kjk** [comment]
Just a note that I just tried to reproduce it again by zooming around arrowhead in step 7 and it didn't crash for me.

Not saying it's fixed, just that I couldn't reproduce it.

It's not entirely unexpected. While mupdf devs seemingly didn't look at the crash report, mupdf code did change since then so maybe it got fixed.

Would be good to know if anyone can reproduce the crash with latest daily build https://www.sumatrapdfreader.org/dailybuilds

**Comment by GitHubRulesOK** [comment]
@kjk 
You may have seen crash reports for 64bit 3.2 and both 32bit/64bit pre-release SumatraPDF-prerel-13112

However I was unable to crash using similar zooms in current Daily, so who knows, but may be worth updating both the pre-releases to more recent code.?

**Comment by GitHubRulesOK** [comment]
@kjk
> dp = dst->samples + (unsigned int)((y - dst->y) * dst->stride + (x - dst->x) * dst->n);

looks like that line may have now changed to (whatever this means, I have no clue if its better :-)

`dp = dst->samples + (y - dst->y) * (size_t)dst->stride + (x - dst->x) * (size_t)dst->n;

Thus your bug report about  "unsigned" may have been addressed obliquely , so perhaps, both this and bugzilla could be snoozed until the next crash?

**Comment by kjk** [comment]
Let's assume this is fixed.

**Comment by sebras** [comment]
Just for the record I believe this issue was fixed in [this upstream commit](http://git.ghostscript.com/?p=mupdf.git;a=commitdiff;h=04b2f4f751e47a8915c5961b8b1da4af91adad71;hp=f7109d2f35a785193c464bc1c3f0b8653faef567).
