### ISSUE TITLE
Tooltips no longer displayed for URLs in Sumatra 3.2

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#1517]
Tootltips displaying where exactly links lead to are crucial so that users can be careful and know what it is they are opening. Sumatra 3.1.2 used to display these tooltips, but 3.2 doesn't.

Screenshot from 3.1.2 displaying both relative and absolute links:

![Sumatra_3 1 2_URL_Tooltips](https://user-images.githubusercontent.com/15380332/77236728-33dd9b00-6be7-11ea-9470-a4bb91eca34a.png)

**Comment by GitHubRulesOK** [comment]
Think this was fixed after 3.2 see https://github.com/sumatrapdfreader/sumatrapdf/commit/59ffe7bbe3e73b5fe455905436cc10eb77e627c1

**Comment by kjk** [comment]
Yeah, as @GitHubRulesOK says, it's fixed

**Comment by tobidelbruck** [comment]
I think it is broken still. SumatraPDF no longer shows annotation tooltips that should pop up as they do in Adobe Reader or Acrobat.  SumatraPDF version 3 showed them fine.

Here is Acrobat view of the tooltip "Background Activity Filter"

![2021-07-31_193732](https://user-images.githubusercontent.com/10061874/127748089-8133f63f-91df-4cca-82ad-0f5acb6a8496.png)

SumatraPDF v3.3.3 does not show the tip
![2021-07-31_193908](https://user-images.githubusercontent.com/10061874/127748134-b97241bb-e38a-46ff-8d6f-9dd121bd2488.png)

**Comment by tobidelbruck** [comment]
See https://www.overleaf.com/read/rwfgbpdphfkx for overleaf project that generates a test PDF with embedded popup tooltip

**Comment by kjk** [comment]
@tobidelbruck  there are indeed some issues with annotations but please open a new bug for this. This is completely different issue

**Comment by tobidelbruck** [comment]
Thanks, will do so, sorry about the hassle
