### ISSUE TITLE
Filetype are not registered

### ISSUE THREAD

**Issue by TedBax** [sumatrapdfreader/sumatrapdf#1518]
(sorry, bad english)

v3.2

If I use in SumatraPDF-settings.txt:   AssociatedExtensions = .pdf .epub
the sumatrapdf did not register the epub-filetype.

**Comment by kjk** [comment]
What did you expect to happen and what happened?
Which version of windows?

See https://www.sumatrapdfreader.org/docs/Configuring-as-default-PDF-viewer-on-Windows-10.html for the best way to make Sumatra a default reader for file types.

**Comment by kjk** [comment]
In 3.4 we just register for all extensions sumatra understands.
