### ISSUE TITLE
Change SVG toolbar icons scale

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1519]
With version 3.2 and before it was easy to scale the bmp toolbar by adding a custom one
This I found useful to allow touching larger icons on a tablet (which by default were too small)

![image](https://user-images.githubusercontent.com/12754913/77252024-aa12e980-6c49-11ea-8380-96cada85fb50.png)

I agree vectors auto-scale nicely for dpi scale settings (lower example below) but I was able to replace bitmap (upper example below) with my own rescaled images to suit

![image](https://user-images.githubusercontent.com/12754913/77271132-ca709180-6ca5-11ea-8e6c-a77e724fb5f7.png)

It would be useful to have an advanced scale setting over-ride (+ and -)
e.g.
SvgToolbarPercent = 150
or better yet if tied to integers
SvgToolbarPels = 24

**Comment by Andreas-Kainz** [comment]
as the toolbar images are very blured, if needed I can submit svg icons whatever you want. 

Do icon stuff for LibreOffice (colibre icons which are used to fit windows 10), but I was also (kde) Breeze and (kde) oxygen maintainer. Elementary icons I also draw in the past.

**Comment by GitHubRulesOK** [comment]
@Andreas-Kainz 
The toolbar images are not blurred by SumatraPDF as such, they depended on the user customisation matching the screen resolution e.g. the user needed to calculate each set according to their hardware dpi.

With svg that is not exactly the same problem it is the amount of antialiasing per svg stroke, so again its windows NOT the icons that cause the issue. if the stroke is 1.6 pixels it will be blured at most scales especially when changed by + or - until you hit the "sweet spot"

**Comment by Andreas-Kainz** [comment]
oxygen draw in the kde4 times the icon images (png) in 4x icons size (so 4 x 24 px).

However if you need some icon, work, let me know.

**Comment by GitHubRulesOK** [comment]
Closing as now possible in pre-release 3.4.14458
ToolbarSize = 36
![image](https://user-images.githubusercontent.com/12754913/163695225-35aa1d9a-cd11-4942-9f64-12576ddd0c68.png)
