### ISSUE TITLE
Add AVIF support to comic book files

### ISSUE THREAD

**Issue by jfveronelli** [sumatrapdfreader/sumatrapdf#1520]
Official C encoding/decoding library: https://github.com/AOMediaCodec/libavif

**Comment by GitHubRulesOK** [comment]
It does not seem to offer any advantages that I can see
I tested a 521mm x 346mm translucent png = 437 KB (1969 x 1307 x 32bit)
I <strike>waited</strike> wasted 6 minutes of my life until it was encoded to a phenomenal 1,206,685 bytes thats over 2 1/2 times the storage and I have no idea how long it takes to decode as I am not going to bother looking for one

Every so often we see problems with users complaining sumatraPDF is "slow" to decode this or that file. the file is either stupidly large and heavily compressed. A **Reading** page of colour print needs 150 dpi MAX only needs to be higher if its use is for currency or high quality glossy photo printing.

So the above page size is efficient quick simple and easily produced / printed / converted to other formats
A zip full of png files is perfect for that medium hence .CBZ

**Comment by jfveronelli** [comment]
Thanks for the quick response. Just to give some context, I mainly use WebP format to store scanned documents, comic books, etc. As an example, I usually reconvert comic books (CBZ with JPGs) and I end up with 50-60% of the original file size with no noticeable visual issues.

I haven't tested AVIF enough, just a few samples using [go-avif](https://github.com/Kagami/go-avif), which is a bit dated, and with the default quality setting it did give me smaller sizes than my preferred setting for encoding WebPs, with comparable visual quality. I was able to open the encoded files with the latest XViewMP, and with MSPaint (after installing the AV1 Video Extension from Microsoft Store).

But again, I haven't tested enough and I do agree that the encoding process is far slower.

**Comment by SumatraPeter** [comment]
As long as the AV1 extension's installed Paint can display AVIF files just fine, even on older Win10 versions (I just tested with both 1909 and 1809).

Given that AOMedia has Amazon, Apple, ARM, Cisco, Facebook, Google, IBM, Intel, Microsoft, Mozilla, Netflix, Nvidia, Samsung, Tencent etc. throwing their weight behind AV1, this definitely seems to be the future in terms of video at least. Frankly I'd say even the image format AVIF has a much better shot at popularity than WebP, but whether it makes sense to add support for it now to Sumatra is for kjk to decide.

**Comment by kjk** [comment]
To set expectations: I'll probably add .avif support, because it's probably not hard.

At the same time, it has a low priority now because it's not yet a widely used format.

**Comment by Lw960201** [comment]
你好！很喜欢你的程序，不知道能不能添加"添加标签的功能"？
Hello! Very like your program, I do not know if you can add "add the function of the label" ?

**Comment by GitHubRulesOK** [comment]
@Lw960201 
**This topic is for AVIF still image file format** , It is not clear why AVIF image needs **label**s
AVIF video may support subtitling
However, zip folder images are normally just identified / tagged by the changing filenames.

**Comment by jfveronelli** [comment]
Maybe he meant "add the function on the title" of the issue?

**Comment by GitHubRulesOK** [comment]
@jfveronelli 
With the .vbkm format (virtual pdf) we could edit all image names if we want to
As you know all cbx images in general look like this
![image](https://user-images.githubusercontent.com/12754913/77443386-f04f8080-6de2-11ea-8307-95431a3b83dc.png)
there it is down to the compositor to label the filenames for each image and its containing archive folder the additional use of archive comments or ASDF data & even including x(ht)ml indexes have all had their own problems.
With Sumatrapdf .(v)bkm support we can already call them what we like
![image](https://user-images.githubusercontent.com/12754913/77445674-47eeeb80-6de5-11ea-99a4-7096c9d27727.png)

**Comment by SumatraPeter** [comment]
@kjk: Just a small note with regards to the thread title - Shouldn't it simply be, "Add AVIF support"? Comic book files need not be mentioned because just like with other formats like JPG or WEBP, AVIF images too should be supported either when opened directly or no matter the container format - be they embedded within ebooks, PDFs, CBx files etc.

**Comment by kjk** [comment]
Let's not overthink things. I just don't like "Feature request" in the title, because it's redundant.

**Comment by SumatraPeter** [comment]
I don't understand where the overthinking part came in? I just wanted to say that "Add AVIF support to comic book files" makes it seem like the support will be specific to the CBx format only, whereas obviously the support should be for the app as a whole regardless of format, that's all.

**Comment by GitHubRulesOK** [comment]
@jfveronelli just a comment **not related to AVIF** however in case you are interested / unaware you now have the additional option to use HEIC images in cbx see https://github.com/sumatrapdfreader/sumatrapdf/issues/2196

**Comment by jfveronelli** [comment]
@GitHubRulesOK nice! Thanks a lot for the heads-up!

**Comment by kjk** [comment]
Added in latest pre-release

**Comment by GitHubRulesOK** [comment]
@kjk 
may need a bit of polishing

I opened a folder of images and filename filtering does not show file.avif

When attempting to save it offers .heic as a default extension (and currently cannot view those)
 but attempts save then throws up, even when set to all files

![image](https://user-images.githubusercontent.com/12754913/171162405-0f2eb854-21f9-4625-8c90-8fab32bf3316.png)

**Comment by kjk** [comment]
@GitHubRulesOK thanks, both issues should be fixed
