### ISSUE TITLE
v3.3.12426 Git-39fbf0ee3 - installer: not work Options and Install buttons and jump to bookmark (second(?) phenomena)

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1522]
Found in to v3.3.12425 Git-c983817e30? possible regression started in commit 9e6fc5f1223c (?) "refactor ButtonCtrl to not use SubclassParent()". Whats I see& - then try install and press any Install or Options button in to first installer screen process not started possible my START command is loss.

Also I see this phenomena in to v3.3.12426 Git-39fbf0ee3.

**Comment by GitHubRulesOK** [comment]
@kjk confirmed this issue seems to be present in current daily installer

**Comment by VictorVG** [comment]
Also not work jump in to bookmark (menu F12), but this menu work success in v3.3.12416 Git-b8bfd1c8c

**Comment by GitHubRulesOK** [comment]
@kjk 
waiting for recompile to test 
however, second observation re bookmark handling highlights multiple knock on problems

**Comment by VictorVG** [comment]
Thanks! Installer is fixed, but jump use bookmarks (menu F12) not work.
