### ISSUE TITLE
Impacts on tree control

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1523]
@kjk 
Recent round of changes has had an impact on bookmark handling both in functionality and context control
![image](https://user-images.githubusercontent.com/12754913/77746204-7f8faa80-7014-11ea-8147-b3f1e4f56869.png)
@VictorVG has mentioned F12 but I also see .vbkm content is not displayed and expand/collapse context is missing

**Comment by GitHubRulesOK** [comment]
@kjk 
Those issues appear to be fixed

**Comment by VictorVG** [comment]
Thanks!

**Comment by VictorVG** [comment]
I build [**v3.3.12428 Git-a75dbb392**](https://github.com/VictorVG/Software/releases/tag/SPDF-a75dbb392) and test and confirmed whats both Issues #1522 and #1523 is fixed.

Big thanks!
