### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by metedinler** [sumatrapdfreader/sumatrapdf#1524]
Hello there
I use sumatra with pleasure. However, it makes it difficult to use at some points. If you make improvements at these points, it will be a very good program. Meanwhile, it takes up little space and low memory consumption. I sincerely thank every pouch who programmed and contributed.

1. I often change the filename. For this reason, I request that a keyboard shortcut be assigned to the Change name command. Also, if you do this on the screen with a button, it would be much more beautiful.

2. File names are usually a few lines and only the first line in the sumatra. in fact, more than one line selected is in memory. this line may be due to the skip command. I want to paste the other lines into the change name menu by putting a space.

**Comment by GitHubRulesOK** [comment]
Change name is <kbd>F2</kbd>

it is a windows operating system function the line length is limited by windows not SumatraPDF

it should be short enough to distinguish one file from another in the format **123456~8.ext**

LFN (Long File Names) cause issues in Windows if deep nested with long strings, that is a historic windows limitation

![image](https://user-images.githubusercontent.com/12754913/77754235-cf756e00-7022-11ea-8eee-f43f2bfbbdae.png)
