### ISSUE TITLE
Add vim-like "mark a page"

### ISSUE THREAD

**Issue by TomJansen** [sumatrapdfreader/sumatrapdf#1527]
In Vim, you have the option to set line marks with m+[A-Z]. Then when you press '+the letter, it jumps to the marked line. See https://vim.fandom.com/wiki/Using_marks for more.

Such behavior (but for pages) would be really handy in sumatra pdf, as you can quickly jump between specific pages in a pdf file.

**Comment by GitHubRulesOK** [comment]
In principle the pages are "marked" using 2 key shortcut <kbd>Ctrl</kbd>+<kbd>**B** *ookmark*</kbd>or with mouse you can right click and store as "favorites" simply hit the key a - z to add your own label, however to jump to them you need to use in english version<kbd>Alt</kbd><kbd>A</kbd> then the appropriate key pair for the lables so for a-z <kbd>c</kbd><kbd>a</kbd> to <kbd>c</kbd><kbd>z</kbd>
or quicker click on the navigator pane <kbd>Alt</kbd><kbd>A</kbd><kbd>S</kbd>

**Comment by GitHubRulesOK** [comment]
in principle this request is similar enough to be consolidated with Bookmarks: navigating like in a real book #545
