### ISSUE TITLE
Remove test code from release builds

### ISSUE THREAD

**Issue by CharlesMengCA** [sumatrapdfreader/sumatrapdf#1528]
1. Using Conditional Compilation for those test codes. When I  removed those test codes and recompile, the binaries size reduced from 16M to 13M. For a public release version, those test codes should not be included.

2. Move the installation code  to a separate project would be also good idea. We may install it every couple of months or never. but the the reader is used daily.

Regards,

**Comment by kjk** [comment]
Removed test code from release which dropped the size to just 14 MB

The installer used to be a separate app / project but the way it's now is much better for development (me).
