### ISSUE TITLE
Bookmark doesn't work in new windows

### ISSUE THREAD

**Issue by kenkangxgwe** [sumatrapdfreader/sumatrapdf#1531]
Use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>n</kbd> to open up a new window with pdf. Clicking on the bookmarks in the new window doesn't have any response.

**Comment by GitHubRulesOK** [comment]
You need to provide at least a version number to help
it works perfectly in current version
![image](https://user-images.githubusercontent.com/12754913/78020807-06f95880-734a-11ea-8e04-c2a12d4e3185.png)

**Comment by kenkangxgwe** [comment]
I can reproduce the pdf you gave with v3.3.12434 64bit. It works for the first time I create a new window but doesn't work if I close the second window and re-create another one.

**Comment by GitHubRulesOK** [comment]
@kjk 
I can confirm with the example file above there is odd behaviour on subsequent usage
