### ISSUE TITLE
Unresponsive after word search multiple times

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#1532]
The first few times was fast and precise, and then suddenly it became unresponsive and crashes after I click Find Next too many times.

The file has to be big, though, like over 50 MB or something.

I'm using version 3.3.12434, but the problem still exists even after I downgraded it to 3.2 official public release.

This problem is not in version 3.1.2.

**Comment by GitHubRulesOK** [comment]
@kjk
may be related to observation around https://github.com/sumatrapdfreader/sumatrapdf/issues/1494

**Comment by 775405984** [comment]
It gets better with the latest version 3.3.12444, but it doesn't fix the problem.
I'm reading a Chinese book with SumatraPDF, when you search a certain rare word, say "Ozark", it freezes after 1 click. @kjk @GitHubRulesOK 
[Text PDF file](https://www.dropbox.com/s/lxm3fphm3b8sutu/Test%20File.pdf?dl=0)

**Comment by GitHubRulesOK** [comment]
@kjk 
so as not to have two issues open, I also have problems with the fix not speeding up search for my example which is smaller but has more heavily compressed laurapages, my case seems to be MUCH slower than this one, suggesting it is possibly overall number of compressed pages having a bearing

**Comment by GitHubRulesOK** [comment]
@kjk 
for reference the file in #1494 was https://archive.org/download/newmoviemagazine10weir/newmoviemagazine10weir.pdf and search term was foy which will eventually find a hit

**Comment by GitHubRulesOK** [comment]
@kjk 
Wow, that's a lot faster than in the past

**Comment by GitHubRulesOK** [comment]
@kjk 
I did not see any issue with my simple search in my large reference file, However depending on the search in the above linked "Test PDF" I do encounter an issue where it freezes after a number of search hits (which may or may not be file related) e.g. when I simply do a search on QU and rapidly go to find next
