### ISSUE TITLE
Regression in 3.2 - ResuseInstance appears not to be working

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1533]
see https://forum.sumatrapdfreader.org/t/opened-files-create-new-window/2807
unlike previous versions up to 3.1.2 and prior to new-window
opening a file twice only opened one instance
this was always needed for renewing /refreshing the file whilst editing in LaTeX

Recent 3.2 apparently does not follow that previous behaviour

**Comment by kjk** [comment]
I executed `.\SumatraPDF-3.2-64.exe .\files\4-19AW04_Moreno_Bachmann.pdf` twice and it works the same as with 3.1.2.

Which scenario behaves differently in 3.2 than in 3.1.2? (there are multiple ways to open a file).

**Comment by GitHubRulesOK** [comment]
@kjk 
yes the difference in call behaviour with old tabs info is possibly what I overlooked 
It looks like I did not clear tab history first in each case
3.12  3.2 & 3.3x are the same if I start them afresh

can thus close issue
