### ISSUE TITLE
Remove sumatra icon in the PDF shell preview hanlder

### ISSUE THREAD

**Issue by musm** [sumatrapdfreader/sumatrapdf#1534]
![image](https://user-images.githubusercontent.com/4319522/78104709-a0ae1d80-73bd-11ea-948f-34d864802467.png)

Example left: proposal
Example right: current situation.

The sumatra icon on the lower right, shouldn't be there.

**Comment by GitHubRulesOK** [comment]
It seems to vary in some Windows 10 !! Versions 
"All ten are equal, but some are more equal than others." [Animal Farm by G.Orwell]
![image](https://user-images.githubusercontent.com/12754913/78136480-93278080-741b-11ea-8b91-bc5a55774d2d.png)

**Comment by musm** [comment]
oh wow... thank you
