### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by BunyaminBozdagli** [sumatrapdfreader/sumatrapdf#1535]
Can you add    switch  beetween two pdf tabs ( for compare two pdf ) with  shortcut key.

**Comment by GitHubRulesOK** [comment]
To switch between two pdf tabs use 
<kbd>Alt</kbd> + 1 | go to tab 1. Use 2, 3 etc. up to 8 to go to n-th tab
-- | --

To open two copies of **same or different** files
Have you tried CTRL + SHIFT + N or just CTRL + N in version 3.2 ?
