### ISSUE TITLE
Crash after opening Epub.

### ISSUE THREAD

**Issue by cyrilregal** [sumatrapdfreader/sumatrapdf#1542]
The software launch normaly.
Screen froze on opening epub.
Crash file: C:\Users\Cyril\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.txt
Exe: C:\Users\Cyril\AppData\Local\SumatraPDF\SumatraPDF.exe
BuiltOn: 2020-03-14
Type: dll
Ver: 3.2 64-bit
Git: fc8f35a2d0581735ea361990dc65c674b3cd2dcb (https://github.com/sumatrapdfreader/sumatrapdf/commit/fc8f35a2d0581735ea361990dc65c674b3cd2dcb)
OS: Windows 8 build 9200 64-bit
Number Of Processors: 4
Processor: AMD Phenom(tm) II X4 965 Processor
Physical Memory: 8.00 GB
Commit Charge Limit: 10.62 GB
Memory Used: 47%
Machine: To Be Filled By O.E.M.
Lang: fr FR
Graphics driver 0
  DriverDesc:         AMD Radeon (TM) R7 370 Series
  DriverVersion:      26.20.15029.15007
  UserModeDriverName: C:\WINDOWS\System32\DriverStore\FileRepository\c0353065.inf_amd64_536cb9e978acbc9b\B353014\aticfx64.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FF6D5A168ED 01:00000000001758ED sumatrapdf.exe!HtmlFormatter::HtmlFormatter+0x27d C:\Users\kjk\src\sumatrapdf\src\HtmlFormatter.cpp+196
Fault reading address 0000000000000000

Registers:
RAX:000002090A3636F8  RBX:000002090B875270  RCX:0000000000000000
RDX:000002090A3636F8  RSI:000002090B8754A0  RDI:000002090A363690
R8: 000002090B874970
R9: 00007FFBC814C7E0
R10:00000083F1AFD390
R11:000002090A4D16F0
R12:000002090A3638C8
R13:0000000000000000
R14:000002090A3638A8
R15:00007FF6D596F094
CS:RIP:0033:00007FF6D5A168ED
SS:RSP:002B:00000000F1AFD4D0  RBP:00000000
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010202

Crashed thread:
00007FF6D5A168ED 01:00000000001758ED sumatrapdf.exe!HtmlFormatter::HtmlFormatter+0x27d C:\Users\kjk\src\sumatrapdf\src\HtmlFormatter.cpp+196
00007FF6D5974A02 01:00000000000D3A02 sumatrapdf.exe!Doc::CreateFormatter+0xc2 C:\Users\kjk\src\sumatrapdf\src\Doc.cpp+235
00007FF6D5976B4A 01:00000000000D5B4A sumatrapdf.exe!RenderFirstDocPageToBitmap+0x13a C:\Users\kjk\src\sumatrapdf\src\EbookController.cpp+598
00007FF6D59772F0 01:00000000000D62F0 sumatrapdf.exe!EbookController::CreateThumbnail+0xe0 C:\Users\kjk\src\sumatrapdf\src\EbookController.cpp+676
00007FF6D59A79CF 01:00000000001069CF sumatrapdf.exe!CreateThumbnailForFile+0x28f C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+764
00007FF6D59AB753 01:000000000010A753 sumatrapdf.exe!LoadDocument+0xa33 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+1744
00007FF6D59B036E 01:000000000010F36E sumatrapdf.exe!OnMenuOpen+0x5de C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+3075
00007FF6D59B5146 01:0000000000114146 sumatrapdf.exe!FrameOnCommand+0x1b26 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+4645
00007FF6D59B5B0E 01:0000000000114B0E sumatrapdf.exe!WndProcFrame+0x52e C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+4695
00007FFC23A05C0D 01:0000000000014C0D user32.dll!CallWindowProcW+0x3bd
00007FFC23A058DE 01:00000000000148DE user32.dll!CallWindowProcW+0x8e
00007FFC1611B079 01:000000000006A079 comctl32.dll!DefSubclassProc+0x129
00007FFC1611AFC7 01:0000000000069FC7 comctl32.dll!DefSubclassProc+0x77
00007FFC1611B079 01:000000000006A079 comctl32.dll!DefSubclassProc+0x129
00007FFC1611AEA2 01:0000000000069EA2 comctl32.dll!DSA_GetItem+0x2162
00007FFC23A05C0D 01:0000000000014C0D user32.dll!CallWindowProcW+0x3bd
00007FFC23A0521C 01:000000000001421C user32.dll!SendMessageW+0x38c
00007FFC23A04F88 01:0000000000013F88 user32.dll!SendMessageW+0xf8
00007FF6D59667B6 01:00000000000C57B6 sumatrapdf.exe!OnMouseLeftButtonUpAbout+0x96 C:\Users\kjk\src\sumatrapdf\src\Canvas.cpp+1291
00007FF6D5966B64 01:00000000000C5B64 sumatrapdf.exe!WndProcCanvasAbout+0x1f4 C:\Users\kjk\src\sumatrapdf\src\Canvas.cpp+1366
00007FF6D5967681 01:00000000000C6681 sumatrapdf.exe!WndProcCanvas+0x1e1 C:\Users\kjk\src\sumatrapdf\src\Canvas.cpp+1586
00007FFC23A05C0D 01:0000000000014C0D user32.dll!CallWindowProcW+0x3bd
00007FFC23A05602 01:0000000000014602 user32.dll!DispatchMessageW+0x1f2
00007FF6D59BD2D9 01:000000000011C2D9 sumatrapdf.exe!WinMain+0x2009 C:\Users\kjk\src\sumatrapdf\src\SumatraStartup.cpp+1149
00007FF6D5A6FD66 01:00000000001CED66 sumatrapdf.exe!__scrt_common_main_seh+0x106 d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl+288
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2108
00007FFC2541C144 01:000000000009B144 ntdll.dll!NtWaitForSingleObject+0x14
00007FFC22D38BC3 01:0000000000037BC3 kernelbase.dll!WaitForSingleObjectEx+0x93
00007FF6D596DD83 01:00000000000CCD83 sumatrapdf.exe!DumpExceptionHandler+0xa3 C:\Users\kjk\src\sumatrapdf\src\CrashHandler.cpp+341
00007FFC22E0006A 01:00000000000FF06A kernelbase.dll!UnhandledExceptionFilter+0x1ea
00007FFC25424B32 01:00000000000A3B32 ntdll.dll!memset+0x1b32
00007FFC2540C6D6 01:000000000008B6D6 ntdll.dll!_C_specific_handler+0x96
00007FFC2542121F 01:00000000000A021F ntdll.dll!_chkstk+0x11f
00007FFC253EA289 01:0000000000069289 ntdll.dll!RtlRaiseException+0x399
00007FFC2541FE8E 01:000000000009EE8E ntdll.dll!KiUserExceptionDispatcher+0x2e
00007FF6D5A168ED 01:00000000001758ED sumatrapdf.exe!HtmlFormatter::HtmlFormatter+0x27d C:\Users\kjk\src\sumatrapdf\src\HtmlFormatter.cpp+196
00007FF6D5974A02 01:00000000000D3A02 sumatrapdf.exe!Doc::CreateFormatter+0xc2 C:\Users\kjk\src\sumatrapdf\src\Doc.cpp+235
00007FF6D5976B4A 01:00000000000D5B4A sumatrapdf.exe!RenderFirstDocPageToBitmap+0x13a C:\Users\kjk\src\sumatrapdf\src\EbookController.cpp+598
00007FF6D59772F0 01:00000000000D62F0 sumatrapdf.exe!EbookController::CreateThumbnail+0xe0 C:\Users\kjk\src\sumatrapdf\src\EbookController.cpp+676
00007FF6D59A79CF 01:00000000001069CF sumatrapdf.exe!CreateThumbnailForFile+0x28f C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+764
00007FF6D59AB753 01:000000000010A753 sumatrapdf.exe!LoadDocument+0xa33 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+1744
00007FF6D59B036E 01:000000000010F36E sumatrapdf.exe!OnMenuOpen+0x5de C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+3075
00007FF6D59B5146 01:0000000000114146 sumatrapdf.exe!FrameOnCommand+0x1b26 C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+4645
00007FF6D59B5B0E 01:0000000000114B0E sumatrapdf.exe!WndProcFrame+0x52e C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+4695
00007FFC23A05C0D 01:0000000000014C0D user32.dll!CallWindowProcW+0x3bd
00007FFC23A058DE 01:00000000000148DE user32.dll!CallWindowProcW+0x8e
00007FFC1611B079 01:000000000006A079 comctl32.dll!DefSubclassProc+0x129
00007FFC1611AFC7 01:0000000000069FC7 comctl32.dll!DefSubclassProc+0x77
00007FFC1611B079 01:000000000006A079 comctl32.dll!DefSubclassProc+0x129
00007FFC1611AEA2 01:0000000000069EA2 comctl32.dll!DSA_GetItem+0x2162
00007FFC23A05C0D 01:0000000000014C0D user32.dll!CallWindowProcW+0x3bd
00007FFC23A0521C 01:000000000001421C user32.dll!SendMessageW+0x38c
00007FFC23A04F88 01:0000000000013F88 user32.dll!SendMessageW+0xf8
00007FF6D59667B6 01:00000000000C57B6 sumatrapdf.exe!OnMouseLeftButtonUpAbout+0x96 C:\Users\kjk\src\sumatrapdf\src\Canvas.cpp+1291
00007FF6D5966B64 01:00000000000C5B64 sumatrapdf.exe!WndProcCanvasAbout+0x1f4 C:\Users\kjk\src\sumatrapdf\src\Canvas.cpp+1366
00007FF6D5967681 01:00000000000C6681 sumatrapdf.exe!WndProcCanvas+0x1e1 C:\Users\kjk\src\sumatrapdf\src\Canvas.cpp+1586
00007FFC23A05C0D 01:0000000000014C0D user32.dll!CallWindowProcW+0x3bd
00007FFC23A05602 01:0000000000014602 user32.dll!DispatchMessageW+0x1f2

Thread: 18ec
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2478
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2530
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 3550
00007FFC2541C144 01:000000000009B144 ntdll.dll!NtWaitForSingleObject+0x14
00007FFC22D38BC3 01:0000000000037BC3 kernelbase.dll!WaitForSingleObjectEx+0x93
00007FF6D59958FC 01:00000000000F48FC sumatrapdf.exe!RenderCache::RenderCacheThread+0xcc C:\Users\kjk\src\sumatrapdf\src\RenderCache.cpp+604
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 154
00007FFC2541CC14 01:000000000009BC14 ntdll.dll!NtWaitForMultipleObjects+0x14
00007FFC22D580F7 01:00000000000570F7 kernelbase.dll!WaitForMultipleObjectsEx+0x107
00007FF6D59E6F84 01:0000000000145F84 sumatrapdf.exe!FileWatcherThread+0x84 C:\Users\kjk\src\sumatrapdf\src\utils\FileWatcher.cpp+283
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2d60
00007FFC2541CC14 01:000000000009BC14 ntdll.dll!NtWaitForMultipleObjects+0x14
00007FFC22D580F7 01:00000000000570F7 kernelbase.dll!WaitForMultipleObjectsEx+0x107
00007FFC234CB50B 01:000000000009A50B combase.dll!CoIncrementMTAUsage+0x65b
00007FFC234CB390 01:000000000009A390 combase.dll!CoIncrementMTAUsage+0x4e0
00007FFC234CB1BC 01:000000000009A1BC combase.dll!CoIncrementMTAUsage+0x30c
00007FFC234CB13C 01:000000000009A13C combase.dll!CoIncrementMTAUsage+0x28c
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 91c
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 219c
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 1bd4
00007FFC23109A84 01:0000000000008A84 win32u.dll!NtUserMsgWaitForMultipleObjectsEx+0x14
00007FFC23A11CAD 01:0000000000020CAD user32.dll!MsgWaitForMultipleObjectsEx+0x9d
00007FFC244AC4D7 01:000000000000B4D7 shcore.dll!SHTaskPoolQueueTask+0x1627
00007FFC244AC218 01:000000000000B218 shcore.dll!SHTaskPoolQueueTask+0x1368
00007FFC244AACB1 01:0000000000009CB1 shcore.dll!SHTaskPoolGetCurrentThreadLifetime+0x161
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2408
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2be0
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 24b4
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 688
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: f1c
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 29ac
00007FFC2541C744 01:000000000009B744 ntdll.dll!NtDelayExecution+0x14
00007FFC22D46951 01:0000000000045951 kernelbase.dll!SleepEx+0xa1
00007FFC036F3E37 01:0000000000032E37 ocoverlays.dll!RemotePathChecker::IsMonitoredPath+0x29a2b
00007FFC036EECAB 01:000000000002DCAB ocoverlays.dll!RemotePathChecker::IsMonitoredPath+0x2489f
00007FFC036EDD49 01:000000000002CD49 ocoverlays.dll!RemotePathChecker::IsMonitoredPath+0x2393d
00007FFC037A1CD0 01:00000000000E0CD0 ocoverlays.dll!RemotePathChecker::IsMonitoredPath+0xd78c4
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 86c
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 77c
00007FFC2541FA54 01:000000000009EA54 ntdll.dll!NtWaitForWorkViaWorkerFactory+0x14
00007FFC253B4060 01:0000000000033060 ntdll.dll!RtlInitializeResource+0x710
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 3008
00007FFC2541CC14 01:000000000009BC14 ntdll.dll!NtWaitForMultipleObjects+0x14
00007FFC22D580F7 01:00000000000570F7 kernelbase.dll!WaitForMultipleObjectsEx+0x107
00007FFC231F8F46 01:0000000000047F46 crypt32.dll!CryptSIPGetSignedDataMsg+0x116
00007FFC23BA7BD4 01:0000000000016BD4 kernel32.dll!BaseThreadInitThunk+0x14
00007FFC253ECED1 01:000000000006BED1 ntdll.dll!RtlUserThreadStart+0x21

Module: 00007FF6D58A0000 948000 SumatraPDF.exe   C:\Users\Cyril\AppData\Local\SumatraPDF\SumatraPDF.exe
Module: 00007FFC25380000 1F0000 ntdll.dll        C:\WINDOWS\SYSTEM32\ntdll.dll
Module: 00007FFC23B90000 0B2000 KERNEL32.DLL     C:\WINDOWS\System32\KERNEL32.DLL
Module: 00007FFC22D00000 2A3000 KERNELBASE.dll   C:\WINDOWS\System32\KERNELBASE.dll
Module: 00007FFC20470000 08F000 apphelp.dll      C:\WINDOWS\SYSTEM32\apphelp.dll
Module: 00007FFBC8100000 492000 AcLayers.DLL     C:\WINDOWS\SYSTEM32\AcLayers.DLL
Module: 00007FFC25200000 09E000 msvcrt.dll       C:\WINDOWS\System32\msvcrt.dll
Module: 00007FFC239F0000 194000 USER32.dll       C:\WINDOWS\System32\USER32.dll
Module: 00007FFC23100000 021000 win32u.dll       C:\WINDOWS\System32\win32u.dll
Module: 00007FFC24FC0000 026000 GDI32.dll        C:\WINDOWS\System32\GDI32.dll
Module: 00007FFC22310000 194000 gdi32full.dll    C:\WINDOWS\System32\gdi32full.dll
Module: 00007FFC22FB0000 09E000 msvcp_win.dll    C:\WINDOWS\System32\msvcp_win.dll
Module: 00007FFC23300000 0FA000 ucrtbase.dll     C:\WINDOWS\System32\ucrtbase.dll
Module: 00007FFC251A0000 052000 SHLWAPI.dll      C:\WINDOWS\System32\SHLWAPI.dll
Module: 00007FFC23430000 336000 combase.dll      C:\WINDOWS\System32\combase.dll
Module: 00007FFC23770000 120000 RPCRT4.dll       C:\WINDOWS\System32\RPCRT4.dll
Module: 00007FFC22C80000 080000 bcryptPrimitives.dll C:\WINDOWS\System32\bcryptPrimitives.dll
Module: 00007FFC24D50000 0A3000 ADVAPI32.dll     C:\WINDOWS\System32\ADVAPI32.dll
Module: 00007FFC24550000 097000 sechost.dll      C:\WINDOWS\System32\sechost.dll
Module: 0000020903870000 003000 sfc.dll          C:\WINDOWS\SYSTEM32\sfc.dll
Module: 00007FFC0D7F0000 089000 WINSPOOL.DRV     C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
Module: 00007FFC22250000 011000 kernel.appcore.dll C:\WINDOWS\System32\kernel.appcore.dll
Module: 00007FFC23400000 026000 bcrypt.dll       C:\WINDOWS\System32\bcrypt.dll
Module: 00007FFC1EC00000 0EF000 PROPSYS.dll      C:\WINDOWS\SYSTEM32\PROPSYS.dll
Module: 00007FFC24340000 0C4000 OLEAUT32.dll     C:\WINDOWS\System32\OLEAUT32.dll
Module: 00007FFC244A0000 0A9000 shcore.dll       C:\WINDOWS\System32\shcore.dll
Module: 00007FFC217C0000 03A000 IPHLPAPI.DLL     C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
Module: 00007FFC0A860000 011000 sfc_os.DLL       C:\WINDOWS\SYSTEM32\sfc_os.DLL
Module: 00007FFC035A0000 011000 SortWindows61.dll C:\WINDOWS\SYSTEM32\SortWindows61.dll
Module: 00007FFC23890000 02E000 IMM32.DLL        C:\WINDOWS\System32\IMM32.DLL
Module: 00007FFC238C0000 0D0000 COMDLG32.dll     C:\WINDOWS\System32\COMDLG32.dll
Module: 00007FFC24600000 6E5000 SHELL32.dll      C:\WINDOWS\System32\SHELL32.dll
Module: 00007FFC160B0000 285000 COMCTL32.dll     C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.720_none_e6beb5c51314836b\COMCTL32.dll
Module: 00007FFC1EED0000 5C0000 d2d1.dll         C:\WINDOWS\SYSTEM32\d2d1.dll
Module: 00007FFC22C30000 04A000 cfgmgr32.dll     C:\WINDOWS\System32\cfgmgr32.dll
Module: 00007FFC224B0000 780000 windows.storage.dll C:\WINDOWS\System32\windows.storage.dll
Module: 00007FFC222E0000 023000 profapi.dll      C:\WINDOWS\System32\profapi.dll
Module: 00007FFC22290000 04A000 powrprof.dll     C:\WINDOWS\System32\powrprof.dll
Module: 00007FFC22240000 010000 UMPDC.dll        C:\WINDOWS\System32\UMPDC.dll
Module: 00007FFC23130000 017000 cryptsp.dll      C:\WINDOWS\System32\cryptsp.dll
Module: 00007FFC240C0000 157000 ole32.dll        C:\WINDOWS\System32\ole32.dll
Module: 00007FFC205C0000 099000 uxtheme.dll      C:\WINDOWS\system32\uxtheme.dll
Module: 00007FFC20910000 02D000 dwmapi.dll       C:\WINDOWS\system32\dwmapi.dll
Module: 00007FFC245F0000 008000 normaliz.dll     C:\WINDOWS\System32\normaliz.dll
Module: 00007FFC01630000 270000 uiautomationcore.dll C:\WINDOWS\system32\uiautomationcore.dll
Module: 00007FFC0F200000 1F4000 dbghelp.dll      C:\WINDOWS\system32\dbghelp.dll
Module: 00007FFC0F1D0000 02A000 dbgcore.DLL      C:\WINDOWS\SYSTEM32\dbgcore.DLL
Module: 00007FFC0BE10000 1A3000 gdiplus.dll      C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.18362.720_none_17a9a8aa6da6fd39\gdiplus.dll
Module: 00007FFC09C90000 007000 msimg32.dll      C:\WINDOWS\system32\msimg32.dll
Module: 00007FFC17340000 1D5000 urlmon.dll       C:\WINDOWS\system32\urlmon.dll
Module: 00007FFC17640000 2A6000 iertutil.dll     C:\WINDOWS\SYSTEM32\iertutil.dll
Module: 00007FFC21C80000 00C000 CRYPTBASE.DLL    C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
Module: 00007FFC1B130000 00A000 version.dll      C:\WINDOWS\system32\version.dll
Module: 00007FFC1DA80000 1AF000 windowscodecs.dll C:\WINDOWS\system32\windowscodecs.dll
Module: 00007FFC145D0000 4D5000 wininet.dll      C:\WINDOWS\system32\wininet.dll

-------- Log -----------------

Starting SumatraPDF
CmdLine: "C:\Users\Cyril\AppData\Local\SumatraPDF\SumatraPDF.exe" 
StartMonitoringDirForChangesAPC() C:\Users\Cyril\AppData\Local\SumatraPDF
LoadDocument: 'C:\Users\Cyril\Desktop\L'électronique pour les nuls.epub', tid=8456
CreateControllerForFile: 'C:\Users\Cyril\Desktop\L'électronique pour les nuls.epub'
LoadDocument: !forceReuse, created win->currentTab at 0x000002090AD55DE0
LoadDocument: after LoadDocIntoCurrentTab win->currentTab is 0x000002090AD55DE0, path: 'C:\Users\Cyril\Desktop\L'électronique pour les nuls.epub'
StartMonitoringDirForChangesAPC() C:\Users\Cyril\Desktop
HttpGet: url: 'https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/rel/SumatraPDF-3.2-64.pdb.lzsa'
StartMonitoringDirForChangesAPC() C:\Users\Cyril\AppData\Local\SumatraPDF
StartMonitoringDirForChangesAPC() C:\Users\Cyril\AppData\Local\SumatraPDF

----- Settings file ----------

﻿# For documentation, see https://www.sumatrapdfreader.org/settings/settings3.2.html

MainWindowBackground = #80fff200
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true
TabWidth = 300

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
EbookUI [
	FontName = Georgia
	FontSize = 12.5
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = false
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]
ExternalViewers [
]
ShowMenubar = true
ReloadModifiedDocuments = true
FullPathInTitle = false
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
CustomScreenDPI = 0

RememberStatePerDocument = true
UiLanguage = fr
ShowToolbar = true
ShowFavorites = false
AssociateSilently = false
CheckForUpdates = true
RememberOpenedFiles = true
EnableTeXEnhancements = false
DefaultDisplayMode = automatic
DefaultZoom = fit page
WindowState = 1
WindowPos = 0 0 0 0
ShowToc = true
SidebarDx = 0
TocDy = 0
ShowStartPage = true
UseTabs = true

FileStates [
]
SessionData [
]
TimeOfLastUpdateCheck = 0 0
OpenCountWeek = 483

# Settings after this line have not been recognized by the current version

**Comment by kjk** [comment]
Does it happen for every .epub file or just a specific file?

If it's only for a specific file, there's not much I can do without access to the file. For non-public files, you can e-mail them to me at kkowalczyk@gmail.com (as described in https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports.html)

**Comment by kjk** [comment]
Can't do anything without a file that causes a crash.

**Comment by GitHubRulesOK** [comment]
@kjk 
Black Herring ?

```
FixedPageUI [
TextColor = #0
```
