### ISSUE TITLE
Minor updates to manual page

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1547]
To reduce confusion under Actions add missing shifted S

< Ctrl > + S | Save (current document) As (...same or alternate format)
-- | --
< Ctrl > < Shift >+ S | Save a System Shortcut to the current document

Since rotate clockwise and anticlockwise are much easier as
**rotate left  [  and  ] rotate right** it may be worth adding those
also rotate can be achieved on some numeric keyboards using 
**rotate left  /  and  * rotate right**

**Comment by SumatraPeter** [comment]
@kjk: Don't see any point in opening an entirely new issue for something this minor - the spelling of "contin**U**ous" needs to be fixed in 2 places in this line:

https://github.com/sumatrapdfreader/sumatrapdf/blob/0dcbfab3df9e668f871a0fe92f6d4fbef5cb90c2/website/manual.html#L205

**Comment by kjk** [comment]
Thanks @SumatraPeter , fixed
