### ISSUE TITLE
'Check for Updates' feature does not find version 3.2 is released

### ISSUE THREAD

**Issue by matthiastummers** [sumatrapdfreader/sumatrapdf#1548]
I am running sumatra build v3.2.1 64-bit on a Windows 10 Pro. When using the check for updates feature (Menu -> Help -> Check for Updates) I am prompted that I have the latest version. Which is not the case.

**Comment by GitHubRulesOK** [comment]
3.1.2 is the current Release

**Comment by matthiastummers** [comment]
Yes I meant 3.1.2 sorry.
Ok sorry about the trouble didn't think of reading that part of the doc.
Thank's for answering anyway!

**Comment by GitHubRulesOK** [comment]
No problem Hopefully we are near to an official roll out as the major wrinkles seem to have be commented on

**Comment by matthiastummers** [comment]
mmh I think there is something wrong with the current stable release candidate 3.2 64-bit installer... It seams to not install Sumatra PDF on my PC

**Comment by GitHubRulesOK** [comment]
The installer should work just not the way some users expect. so there have been changes such as to command line usage by administrators
For a single user there were several changes
