### ISSUE TITLE
Could not build some projects due to character code pages

### ISSUE THREAD

**Issue by wmjordan** [sumatrapdfreader/sumatrapdf#1549]
While building the solution with VS 2019 in a Chinese system, some warnings were reported by the compiler, all of them were quite alike the following:

> warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss (compiling source file ..\ext\harfbuzz\src\hb-ft.cc)

I opened the code file and suspected that the character which _cannot be represented in the current code page_ was the copyright character within the comment at the beginning of the code file. That type of warnings were treated as error and prevented the compilation.

Most cases of the code page issue were related to the copyright character, except the following two places: synctex_parse.c (line 716) and ttobjs.c (line 1035). I examined the lines in the latter two code files and did not found anything wrong.
It seems that the projects can be actually compiled correctly since the copyright characters are all in the comments and the two exceptional places aforementioned have nothing significantly affect the compilation.

Unfortunately there is no way to change code file default encoding in VS.

Hereby, could you add C4819 to the `DisableSpecificWarnings` in the vcxproj files so we can compile the solution without modifying code files?

**Comment by SumatraPeter** [comment]
Isn't it possible as suggested to save the file as Unicode? Perhaps the following might help?

- [Encodings and line endings](https://docs.microsoft.com/en-us/visualstudio/ide/encodings-and-line-breaks?view=vs-2019)
- [Save and open files with encoding](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-save-and-open-files-with-encoding?view=vs-2019)

**Comment by wmjordan** [comment]
Thank you for providing the info.

It is not so good to change the codepage of code files since it can cause some trouble when merging with future versions.
I also tried modifying the .editorconfig file. But the warnings still emerged.

However, the solution somehow **got compiled**, although with the same errors.

**Comment by zkosk** [comment]
/utf-8 works fine. Check [https://github.com/sumatrapdfreader/sumatrapdf/issues/1854](url)
