### ISSUE TITLE
Selected paragraph doesn't highlight in full 

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#1550]
This is a scanned PDF, I cropped it into a smaller file so you can reproduce the problem.
[Test File2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4465121/Test.File2.pdf)
After I updated to 12459, here is what happens when I select a paragraph.
![Screenshot_2](https://user-images.githubusercontent.com/7196377/79051550-6832fd00-7c63-11ea-959e-5df634e03c21.jpg)
Here is 12434's normal look.
![Screenshot_3](https://user-images.githubusercontent.com/7196377/79051554-6d904780-7c63-11ea-97a2-47d2456640b8.jpg)

@kjk

**Comment by GitHubRulesOK** [comment]
@kjk 
regression occurred as a result of https://github.com/sumatrapdfreader/sumatrapdf/commit/85927f160cdde859a4b9b9a2eaff54392a2cf0ed
![image](https://user-images.githubusercontent.com/12754913/79118402-c22be380-7d85-11ea-9822-15f649f9c765.png)
