### ISSUE TITLE
Add "Show Bookmarks" in toolbar

### ISSUE THREAD

**Issue by Bambooin** [sumatrapdfreader/sumatrapdf#1554]
"Show Bookmarks" is hides in menu and it's usage is relatively frequent, so maybe it's better added to toolbar, thought "F8" shortcut can show bookmarks.

**Comment by GitHubRulesOK** [comment]
@Bambooin 
The toolbar width is not always available for extra icons especially on narrow tablets
Along with `Favorites` the `Bookmarks` feature was recently added to the context menu to make it much easier to access especially useful for tablet users
![image](https://user-images.githubusercontent.com/12754913/79369392-c6542e80-7f48-11ea-9a6b-5e480f0fc651.png)

**Comment by kjk** [comment]
No plans to add more items to the toolbar.
