### ISSUE TITLE
[Feature Request] Scroll bar background color changes by color of BackgroundColor

### ISSUE THREAD

**Issue by Bambooin** [sumatrapdfreader/sumatrapdf#1555]
It will be nice to change scroll bar background color with setting of BackgroundColor for dark theme setting.

Firefox is an example, you can try it on this link.

https://duckduckgo.com/settings#theme

The scroll bar background color changes with different themes.

**Comment by kjk** [comment]
Windows doesn't allow customizing scrollbars easily. No plans to do that.
