### ISSUE TITLE
Restore handling of embedded files / attachments in PDF

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1557]
Lost in https://github.com/sumatrapdfreader/sumatrapdf/commit/683babb7e0f8ae41e49d19e758664c467747d563 due to mupdf hiding a function we used

**Comment by GitHubRulesOK** [comment]
Attachments 
such as documents that were visible in SumatraPDF-prerel-12459-64 (but could not be extracted)
[CustomizingTableOfContents.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4489405/CustomizingTableOfContents.pdf)


and contents of portfolios (which partially worked)
[acro9_10.08.01.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4489419/acro9_10.08.01.pdf)

are no longer visible in the bookmarks section
in addition to those that did not show in that version
[1455 add.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4489417/1455.add.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk 

Just a suggestion that any nested attachment should just simply be offered to "Sava AS" this was the way it generally worked in the past and ensures it is down to user to apply another secured application to open the embodiment e.g. swf or vba driven doc/xls etc.

The exception is then PDF within PDF e.g. portfolio which is depreciated in version 2.0 but possibly could be addressed at a basic level by new-window ?

**Comment by ousia** [comment]
After upgrading to SumatraPDF-3.2 (with MuPDF-1.17 inside), I noted that attachments don’t work anymore (either file attachment annotations, or embedded files).

This feature is important for usability. Would it be possible that it could be implemented?

File attachment annotations should be opened when double-clicking on them, when the attached file is a PDF document. This would also restore the previous behavior.

It would be great that embedded files could be displayed separated from bookmarks, on another tab or similar. In my experience, mixing bookmarks and attachments is misleading info in some contexts for most users.

I would also  suggest that embedded PDF documents could be opened directly when double-clicking on their file names.

Many thanks for your help.

**Comment by SumatraPeter** [comment]
> This feature is important for usability. Would it be possible that it could be implemented?

@ousia: I agree with you - both this one _and_ #1336 are definitely important for usability. Since 3.2.1 is a minor bug-fix release, hopefully both issues are on kjk's roadmap for 3.3 (and it'll arrive sometime this year).

**Comment by ousia** [comment]
@SumatraPeter, many thanks for your reply.

If this will take longer than the next release, we must switch back to version 3.1.2 at work. Otherwise, we cannot check which are the documents that have been attached (by other coworkers).

**Comment by SumatraPeter** [comment]
@ousia: I'm with you. I have to keep an additional portable copy of 3.1.2 everywhere just so I can save and play embedded SWFs/MP4s (or use another viewer that can play them inline).

**Comment by ousia** [comment]
@SumatraPeter, I had to downgrade to version 3.1.2 at work, because I need to access attachments by double-clicking.

I’m afraid that also annotation icons are huge and partially hide text.

**Comment by GitHubRulesOK** [comment]
@ousia 
re: your comment "annotation icons are huge"
can you supply an example since SumatraPDF is tied by the way MuPDF shows those icons
Thus they are a fixed size which will appear larger than normal if the page is smaller than normal
![image](https://user-images.githubusercontent.com/12754913/83195139-a8760e00-a131-11ea-97fe-8e5810dc957e.png)

**Comment by ousia** [comment]
@GitHubRulesOK, since the issue is not related specifically related to attachment annotations, I’m opening a new issue with annotation icons.

**Comment by GitHubRulesOK** [comment]
@ousia ok as you have copied my comment over I have deleted it above If we each remove these two the link should be enough

**Comment by GitHubRulesOK** [comment]
@ousia 
Forgive me using your example as a means to raise a point.
@kjk
I fully agree with Ousia that embeded files should be saved, that is a fundimental behaviour that Adobe instigated and is now expected (but in many ways is depreciating as a potential risk for the unwary)
I do agree that embedded PDF (i.e. portfolio PDF) or other SumatraPDF supported formats could be run as if opened directly by SumatraPDF itself. I am concerned that those or other requests (e.g. the wish to run XLS on demand) may need some OPTIONAL check in place.
Acrobat secured and SumatraPDF 3.1.2 do not download and **automatically** run contents apart from PDF in the system, Here is a modification to the above file to show why this would be unwise.
Save the embedment then run it as if it was automatically invoked with impunity.

[1455 add - Save Me from Myself.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4706819/1455.add.-.Save.Me.from.Myself.pdf)

**Comment by kjk** [comment]
Restored ability to save embedded files, but the UI is different.
Before all one had to do was to click on the attachement entry in table of contents.
Now those options are added to context menu in table of contents:
* `Save Embedded File...` for files of all types
* `Open Embedded PDF` - only for PDF files, opens embedded PDF in a new tab

This doesn't cover clicking on attachment icon (opened #1602 for that)

**Comment by SumatraPeter** [comment]
@kjk: In the process of testing with various PDFs. First up is CustomizingTableOfContents.pdf from above. The last 2 entries in the ToC are for embedded DOCX files, yet their context menu displays `Open Embedded PDF` (which naturally gives an error when selected). Shouldn't the entry be hidden if it's to be displayed for embedded PDFs only?

BTW, saving the 2 DOCXs worked fine. 👍

**Comment by SumatraPeter** [comment]
2\)
>  Before all one had to do was to click on the attachement entry in table of contents.

Will this functionality be restored? I'm asking because the context menu options aren't easily discoverable by the average user.

Testing with acro9_10.08.01.pdf from above I see that both opening and saving the 3 embedded PDFs seems to work fine, however by default the file only displays "For the best experience, open this PDF portfolio in Acrobat 9 or Adobe Reader 9, or later. Get Adobe Reader Now!" Seeing that many users might simply conclude that Sumatra cannot handle such files.

One minor issue with this file is that the TOC selection/highlight seems to get reset every time. What I mean is, every time one right-clicks and opens one of the 3 embedded PDFs, then switches back to the tab with the portfolio file i.e. acro9_10.08.01.pdf, the first TOC entry i.e. contacts1.pdf is highlighted again whereas the entry for the embedded file that was last opened should remain highlighted.

**Comment by ousia** [comment]
> @ousia
> Forgive me using your example as a means to raise a point.

@GitHubRulesOK, I don’t understand what you makes you apologize.
 
As far as I can tell, there is nothing wrong in your usage of the files I submitted.

In any case, many thanks for your help and your contributions to improve SumatraPDF.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
Since your valid comments re portfolios may be missed in this now closed thread can I suggest they be placed under more relevant "Improve handling of PDF attachments" #1361

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Duplicated the comments there as per your suggestion.
