### ISSUE TITLE
Search Selected Text With Google Search In Default Browser.

### ISSUE THREAD

**Issue by saqibsoftwares** [sumatrapdfreader/sumatrapdf#156]
Hello, Sumatra PDF is my favorite PDF reader many Thanks for it.
I want to request a new feature in upcoming version that user will be able to search selected text with google.
an option should be added in right click context menu like "Search With Google".
After selecting some Text, this option should search the selected text in the default web browser of the user.

Example Search Url: http://www.google.com/search?q=[Selected+Text+Here].

Thank You.

**Comment by kjk** [comment]
We don't have plans to implement that. Maybe some day we'll have accessibility support which would enable doing that by any 3rd party program.

**Comment by SumatraPeter** [comment]
This was closed, but later duplicates such as #420 and #877 have been left open...
