### ISSUE TITLE
invert-colors screws up page numbering 

### ISSUE THREAD

**Issue by sheephunt2000** [sumatrapdfreader/sumatrapdf#1563]
See below:

![image](https://user-images.githubusercontent.com/39414927/79725638-83cb8280-82b7-11ea-907a-361bed709133.png)

Running on v3.2., windows 10.

**Comment by GitHubRulesOK** [comment]
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1553
