### ISSUE TITLE
Silent uninstall missing in v3.2

### ISSUE THREAD

**Issue by J-U-B** [sumatrapdfreader/sumatrapdf#1567]
With version 3.2 the installer and uninstaller have obviously been changed.
Now I miss the option of a silent uninstall. There is no `uninstall.exe /S` anymore. 
`SumatraPDF.exe -uninstall` requires an interaction.
However, the silent uninstaller is urgently needed in an managed environment.

Thank you in advance.

**Comment by J-U-B** [comment]
Okay, I just found the corresponding Thread in the [Discussion Forum](https://forum.sumatrapdfreader.org/t/silent-uninstall-does-not-work/2761/12)
But the pre-release builds are of course not ready for production...

**Comment by GitHubRulesOK** [comment]
Technically the issue has been addressed.
So am closing as no longer an open issue.
It should/will be functional in yet to be released Formal Update from 3.1.2 (+3.2 rc  and earlier users)
