### ISSUE TITLE
Add keyboard shortcut for "Open in Adobe Reader"

### ISSUE THREAD

**Issue by Mo-Gul** [sumatrapdfreader/sumatrapdf#1574]
Could there be added a keyboard shortcut for "Open in Adobe Reader". If not directly then maybe "manually" by editing the `SumatraPDF-settings.txt` file?

(This would be handy until issue #595 is closed. Currently it is very annoying to execute that command either by using the mouse or keyboard every time I TeX a file that doesn't render as the Adobe Reader does.)

**Comment by GitHubRulesOK** [comment]
`Open in Adobe Reader` 
is one of several settings that **may** get activated and automatically added to the settings file during installation . It depends on there being exactly the right object detected in the registry at the time. (it could be full Acrobat.exe or old reader AcroRd32.exe) A problem may arise with newer versions of Acrobat not using either of those filenames.

If it is added automatically the shortcut within SumatraPDF will be <kbd>ALT</kbd> + <kbd>F</kbd> + <kbd>A</kbd>

If not automatically added to the file menu then it can be added by including it manually in `ExternalViewers` section

So first check from any desktop acrobat shortcut what command your system uses to open Acrobat Viewer then add that to settings . In my case it is a portable copy I use to render 3D files

```
ExternalViewers
[
	[
		CommandLine = "F:\Apps\Adobe Reader 9.5\Reader\AcroRd32.exe" /A page=%p "%1"
		Name = &Acrobat Reader for 3D Animations
		Filter = *.pdf
	]
]
```

it is the ampers& in front of **A** that determines the **F**ile shortcut

**Comment by GitHubRulesOK** [comment]
Since this is a variation on https://github.com/sumatrapdfreader/sumatrapdf/issues/980# I am consolidating by cross-reference and closing this duplicate issue as there is already a mechanism to add shortcut for Acrobat Reader (however it may need updating along with the other viewer detections)
