### ISSUE TITLE
About box

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1576]
While testing a compiled version 3.3x
perhaps unsurprisingly the links were not valid for Programming / Translations / licenses as they point to https://github.com/sumatrapdfreader/sumatrapdf/blob/3.3rel/AUTHORS etc

On checking 3.2 they surprisingly are also dead links pointing to
https://github.com/sumatrapdfreader/sumatrapdf/blob/3.2rel/AUTHORS etc.

looks like it is due to ELSE
https://github.com/sumatrapdfreader/sumatrapdf/blob/dcd556fff8446bb3a547d4cdaa36b78546f3b023/src/SumatraAbout2.cpp#L114

**Comment by SumatraPeter** [comment]
Also, while we're at it why not assign F1 as a keyboard shortcut for this dialog like many apps do?
