### ISSUE TITLE
Search is buggy on large documents (~1000pages)

### ISSUE THREAD

**Issue by matmay** [sumatrapdfreader/sumatrapdf#1577]
Search is buggy on large (~1000 pages)  documents. It's okay that it is slow, but there should be a way to stop the running search. Also it would be nice to set the direction. And a progress bar would also be nice.

**Comment by GitHubRulesOK** [comment]
Buggy is usually down to the under layer of text, most documents I build (or OCR) I test for compatibility
 e.g. a common failing in some editors is using one ligature for fi thus filename can become ?lename
another failing is character spacing causing spaces between `g ly p h s`
Agreeably this is more noticeable recently in SumatraPDF reading modern Unicode especially when built using LaTeX systems

Which version are you using? There were massive improvements in recent daily builds

The point about setting direction is valid, but after the initial automatic "find" you simply use shortcuts or icons to change direction. Progress position in document is shown by continuous mode scrollbar. 
Anything like lookahead / total count / all entries in scrollbar would likely make searching noticeably slower.

**Comment by kjk** [comment]
Please limit to one thing per issue.

I'm sure we already have issues for improving search UI.

As to buggy search: the only way we can fix it is if you provide a document that shows the problem and describe what happens and what you expect to happen.
