### ISSUE TITLE
Bug Report: file paths with comma inside break "open document folder" function

### ISSUE THREAD

**Issue by petrabaum3** [sumatrapdfreader/sumatrapdf#1578]
Hi and thanks for the program.

One of my document folders contains a comma in its name. Unfortunately, this breaks the "open document folder" function. Normally, this opens the folder containing the pdf, but with a comma in the path, a blank explorer window is opened.
I'm using v3.2 x64 on Windows 10 (Version 10.0.18363.778).

Let me know if you need any further info.
Greetings

**Comment by GitHubRulesOK** [comment]
@kjk 
Above description appears to be the file > "show in folder" function (verified)

Interesting that **the old F2 (rename) method to show file in folder** does work correctly
![image](https://user-images.githubusercontent.com/12754913/81224066-030ec500-8fdf-11ea-8f99-9a8e58ae45ee.png)
