### ISSUE TITLE
request :page color range be separated from affecting images when inverting the range using custom settings

### ISSUE THREAD

**Issue by Methatronc** [sumatrapdfreader/sumatrapdf#1579]
Hello,
Is it possible, for the pdf, to do :
_"TextColor" and "BackgroundColor" in "FixedPageUI [" in advanced settings only concerns text and to leave the images as they are.
_changes in "MainWindowBackground" in advanced settings leaves the documents preview unaltered, and the text below the said documents to be visible,( maybe by highlighting in the invert colour of the one used for the police?), since if we use a black background nothing is visible, as you can see below. 
![image](https://user-images.githubusercontent.com/58328740/81473397-6e82ad80-91fe-11ea-9862-7c76a110f70b.png)

Thanks a lot for your time.

**Comment by GitHubRulesOK** [comment]
If I understand your question correctly 
Primarily you are asking can page color range be separated from affecting images when inverting the range using custom settings to change the limits
Short answer is NO see open issue https://github.com/sumatrapdfreader/sumatrapdf/issues/1275

**Comment by Methatronc** [comment]
You are right, I hope that it will be added in a foreseeable future then..
