### ISSUE TITLE
add/save annotation issue in SumatraPDF-prerel-12511-64.exe

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#1581]
Two related annotation issues in prerelease `SumatraPDF-prerel-12511-64.exe`.
- open a pdf that does not have any annotations (no .smx file)
- select a word and press A to highlight yellow
- right click > save annotations
- select another word and press A
Problem 1: the first highlight now disappears from view. Gif: https://imgur.com/a/AvHlfrp . The annotation still exists in the .smx file though, so R (refresh) shows it again.
Problem 2: But if we instead of refresh do right click > save annotation on the second highlight then the first highlight disappears also from the .smx file.

**Comment by GitHubRulesOK** [comment]
Mia Culpa !
Looks like it happened as a side effect of a fix 
"Current builds highlight again active but not visible" #1559 (https://github.com/sumatrapdfreader/sumatrapdf/commit/c66cfecdfacaf4f09f31db7682832c3b50bb62ad)

**Comment by GitHubRulesOK** [comment]
@kjk 
The above odd behaviour does still cause confusion during incremental editing sessions since extensive previous mods can suddeny dissapear without warning

**Comment by GitHubRulesOK** [comment]
@nod5 
I am closing this issue as it was primarily related to the now redundant smx behaviour
Pressing A in current versions prompts the user to edit the highlight and retains info on each application.

**@kjk 
NOTE the underlying sequence can still result in a similar removal of PDF annotation objects but that will likely be raised by others as a new issue.**
