### ISSUE TITLE
Fat bug: Search does nothing

### ISSUE THREAD

**Issue by Elmue** [sumatrapdfreader/sumatrapdf#1582]
I have Sumatra 3.2 - 64 bit

I click in the menu "Go To" --> "Find" and absolutely nothing happens.
I would expect a window to open.

**Comment by kjk** [comment]
Find UI is in toolbar:

![SumatraPDF-dll_B6yvwnfD6h](https://user-images.githubusercontent.com/7935/81897123-d6245a00-956a-11ea-867d-531be7ac5b3a.png)

Just start typing and Sumatra will start searching. You can then use 'Find next', 'Find prev' buttons to navigate if there are multiple search results.
