### ISSUE TITLE
Crash in some cases when annotation window is left active

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1583]
It is possible to close SumatraPDF application whilst edit annotation window is left open
in that odd scenario a crash will ensue
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4631727/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
The crash is:
```
Crashed thread:
00007FF79D53596C 01:00000000000E496C sumatrapdf-prerel-12573-64.exe!EditAnnotationsWindow::`scalar deleting destructor'+0x4c
00007FF79D57A944 01:0000000000129944 sumatrapdf-prerel-12573-64.exe!TabInfo::~TabInfo+0x134 D:\a\sumatrapdf\sumatrapdf\src\TabInfo.cpp+46
```

**Comment by GitHubRulesOK** [comment]
@kjk
I can not replicate failing in more recent builds (abnormal closure seems to work without noticable problem)
i.e **forcing** closure of main window also closes annotation window
was this "fixed" ?

**Comment by kjk** [comment]
I couldn't reproduce this. If it no longer happens, then let's assume it was fixed.
