### ISSUE TITLE
Crash in some cases when Annotation window is closed first

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1584]
oposite to previous crash in this case a file with old edits was opened and edit annotation was active whilst adding a highlight and saving it then pressing R to confirm it stuck after refresh.
As the editor did not show the new entry the intent was to close and reopen edit annotations to see the new entry at that point it crashed
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4631770/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
The crash is:
```
Crashed thread:
00007FF65FBA5A67 01:00000000000E4A67 sumatrapdf-prerel-12574-64.exe!Annotation::`scalar deleting destructor'+0x37
00007FF65FBA596A 01:00000000000E496A sumatrapdf-prerel-12574-64.exe!EditAnnotationsWindow::`scalar deleting destructor'+0x5a
00007FF65FDFAAD6 01:0000000000339AD6 sumatrapdf-prerel-12574-64.exe!wndProcCustom+0x166 D:\a\sumatrapdf\sumatrapdf\src\wingui\Window.cpp+431
```

**Comment by GitHubRulesOK** [comment]
@kjk 
You have changed some aspects of dialog handling and I have not repeated these crashes, so is this possibly addressed ?

**Comment by kjk** [comment]
Yeah, I haven't see a crash like this so let's consider it's fixed.
