### ISSUE TITLE
免费开源的小说API https://github.com/yuenov/reader-api

### ISSUE THREAD

**Issue by yuenov** [sumatrapdfreader/sumatrapdf#1587]
https://github.com/yuenov/reader-api

**Comment by GitHubRulesOK** [comment]
@kjk !

**Comment by SumatraPeter** [comment]
As far as I can tell it's an API to interface with your reader app? If so, why should Sumatra care?

**Comment by GitHubRulesOK** [comment]
@SumatraPeter looks like they are "advertising" on every related github "reader" app

@kjk can you delete this thread ?
