### ISSUE TITLE
Issue Printing to PDFCreator (2MB to 270MB)

### ISSUE THREAD

**Issue by goldbag** [sumatrapdfreader/sumatrapdf#159]
Hi, 

When I print a 2MB document to a PDF Virtual Printer, I get a document of 270 MB in the queue and it never ends.

The same manipulation was completed with Nitro PDF in 5 seconds.

I'm using Sumatra downloaded from official site yesterday in combination with Win8.1 

Best Regards

**Comment by vvermi** [comment]
Hi, same problem with a "real" printer.
pdf : 53Ko . 
print with adobe : 433Ko in queue
print with sumatrapdf : 36.6Mo in queue

**Comment by kjk** [comment]
It's a known issue but extremely hard to improve. We don't have plans to work on that.
