### ISSUE TITLE
Unable to change FontName property in advanced

### ISSUE THREAD

**Issue by thatshubham** [sumatrapdfreader/sumatrapdf#1590]
![image](https://user-images.githubusercontent.com/58162610/82846809-b3723980-9eb8-11ea-8eed-e2eeb72a2a9a.png)

The above is my setting block. Setting `UseFixedPageUI = True` solves it, and I'm trying to figure out why it doesn't work on being set to `False`. Thanks.

**Comment by GitHubRulesOK** [comment]
It should work on both
![image](https://user-images.githubusercontent.com/12754913/82847006-8e46f080-9ee3-11ea-8a0a-49e1f486fc51.png)
![image](https://user-images.githubusercontent.com/12754913/82847016-a585de00-9ee3-11ea-96df-4779b69b4630.png)
