### ISSUE TITLE
KiCAD PDF line & font thickness rendering issue

### ISSUE THREAD

**Issue by bumcyk** [sumatrapdfreader/sumatrapdf#1591]
Sumatra PDF 3.2 Win64. File generated by KiCAD EESchema, it renders fine with pdf.js and Adobe Reader, but not Sumatra PDF. Most of the text and many lines are rendered with 1px thickness.

This is a lot better than it was with SumatraPDF 3.1.2, where most of the content was not rendered at all. Thank you for your hard work!

[Układ_pomiarowy-2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4682931/Uklad_pomiarowy-2.pdf)

**Comment by GitHubRulesOK** [comment]
In common with every one of dozens of CAD(D) products I have used there should be a means to set real weights/widths for PDF output. the absolute minimum recommended value in Europe is 0.13 mm

**Comment by bumcyk** [comment]
You're right. Sumatra PDF is not the one to blame. I'll file a bug report on KiCad issue tracker.

**Comment by GitHubRulesOK** [comment]
Note when rasterised if it translates to 1 pixel wide then SumatraPDF use of MuPDF antialias setting will cause some reytone effect so aiming for 2 pixels wide as a minimum is best
0.13 = 1/195" so say 1 pixel at 200 dpi using 400 dpi =2 pixels or say 600 dpi = 3 pixels

**Comment by GitHubRulesOK** [comment]
@bumcyk 
I had problems working with the example file due to fonts
so ignore those but to illustrate what the line weights would be if set to 0.0441 pts (a reasonable approximation of 0.125 mm) they should have presented as in the uper half of this 200% zoom
![image](https://user-images.githubusercontent.com/12754913/82933549-fc41f500-9f81-11ea-904b-221e9bbe6fde.png)

**Comment by GitHubRulesOK** [comment]
@bumcyk 
OK
There are some other unidentified issues in the file but running it through a fixing process it produces this reasonable output, so you can use this for comparison

[1591 fixed output.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4684414/1591.fixed.output.pdf)
