### ISSUE TITLE
Incorrect page rotation in DjVu file

### ISSUE THREAD

**Issue by Lis105** [sumatrapdfreader/sumatrapdf#1593]
In version 3.2 page is rotated incorrectly (Ctrl+ -; Ctrl++; Num *; Num/) in DjVu file. In PDF file all correct.
In version 3.1.2 page rotation in DjVu is correct.
Can you tell me how to fix this error?

**Comment by GitHubRulesOK** [comment]
@kjk 
I can confirm really odd DjVu refits x to y without rotate behavior in 3.2 and current builds

**Comment by simurq** [comment]
> @kjk
> I can confirm really odd DjVu refits x to y without rotate behavior in 3.2 and current builds
> was good in SumatraPDF-prerelease-11812
> was bad in SumatraPDF-prerelease-11938

Indeed, it rotates the page but keeps the image the same, only stretches it, which makes images odd-looking.

**Comment by w23rd** [comment]
59cc88b caused the problem

**Comment by kjk** [comment]
In `ddjvu_page_set_rotation`, `page->img->get_info()` returns false so it never does `page->img->set_rotate((int)rot);`

**Comment by GitHubRulesOK** [comment]
Just for reference This Fix was included in formal release 3.3.1
