### ISSUE TITLE
MuPdf Symbol Regression in 3.2

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1595]
From https://forum.sumatrapdfreader.org/t/the-diameter-symbol-is-not-displayed/3027
File
[forum 3027 Деталь.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4695471/forum.3027.pdf)

The Diameter symbol was showing in version 3.1.2 but does not appear in MuPdf 1.17 or recent SumatraPDF builds including 3.2

**Comment by SumatraPeter** [comment]
More example files from the [forum](https://forum.sumatrapdfreader.org/t/the-diameter-symbol-is-not-displayed/3027/3?u=sumatrapeter): [3616.110.00.00.017.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5550439/3616.110.00.00.017.pdf) and [3616.110.00.00.017 rasterized.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5550440/3616.110.00.00.017.rasterized.pdf).

**Comment by GitHubRulesOK** [comment]
bug report opened
https://bugs.ghostscript.com/show_bug.cgi?id=703273
