### ISSUE TITLE
'm' and 'n' letters cannot be selected/searched

### ISSUE THREAD

**Issue by tstone-1** [sumatrapdfreader/sumatrapdf#1596]
Using the 3.3.12654 pre-release and the latest stable release of Sumatra Reader with the following file:
[mwe.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4697912/mwe.pdf)

When the whole text is selected, 'm' and 'n' letters will be left out from the selection:

![Screenshot 2020-05-28 21 57 54](https://user-images.githubusercontent.com/48162401/83187416-6c8d7980-a12e-11ea-86d8-735bb1b2ce30.png)

Also, I'm not able to find 'amet' within the document. The file was compiled using an up-to-date MiKTeX distribution:

```
% arara: pdflatex
\documentclass[fontsize=12pt,paper=a4,bibliography=totoc,titlepage,twoside,open=right,headings=small]{scrreprt}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}

% Minion Pro / Universalis
\usepackage{MinionPro}
\usepackage{universalis}

\begin{document}
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
\end{document}
```

I've created MinionPro font files for LaTeX by using [FontPro by user sebschub](https://github.com/sebschub/FontPro). I'm also a user of Acrobat DC and created the LaTeX font files from MinionPro .otf files (version 2.113) included with my Acrobat installation; Strange thing is: 'm' and 'n' letters are recognized fine within Acrobat?

Thanks for your help!

**Comment by GitHubRulesOK** [comment]
Thanks for the MinimumWorkingExample
Unsure why its happening but first look shows the one font is embedded as four customised parts
![image](https://user-images.githubusercontent.com/12754913/83192869-0acd0f80-a12e-11ea-8c6b-bfa7747f7951.png)
And as usual If I replace those 4 with one of the approved conventional fonts e.g. Times Roman then there is no problem
![image](https://user-images.githubusercontent.com/12754913/83193476-035a3600-a12f-11ea-8f41-e227e65cc839.png)

**Comment by tstone-1** [comment]
Thanks for having a look at this!

Hmm, seems like Acrobat Pro DC recognizes only one font...

![Screenshot 2020-05-29 01 21 48](https://user-images.githubusercontent.com/48162401/83204010-06fbb600-a14b-11ea-937a-16e307e0011f.png)

**Comment by GitHubRulesOK** [comment]
I agree my Acrobat also accumulates the 4 seperate font blocks as only one Minion Pro family
If I replace the 4 blocks in an editor with one embeded font e.g. Minion Pro then the file is "regularised"
![image](https://user-images.githubusercontent.com/12754913/83204766-889c1580-a144-11ea-9e09-8ca2a64b7915.png)

I agree there is a problem in 3.2 with selection of non "standard" fonts built from within LaTeX systems and for now suggest using version 3.1.2 (portable should work) as the previewer if searching or copying

![image](https://user-images.githubusercontent.com/12754913/83204980-28f23a00-a145-11ea-9b5f-75154f5cc3dc.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
this is yet another example of some underlying problem in determining the placement of non system fonts generated in UTF8 encoding. I guess just one misbehaving character makes it no easier to track down the cause, however if this one can be resolved, it may lead to many similar issues being closed.
e.g. https://github.com/sumatrapdfreader/sumatrapdf/issues/1505
