### ISSUE TITLE
V3.2 causes Flickering Blocks with some LaTeX Files

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1598]
@kjk
Issue from forum https://forum.sumatrapdfreader.org/t/latest-sumatrapdf-3-2-flickers-on-various-latex-generated-files/3023
NOTE the request for developer pointers to code that could be having an effect

From Original Poster
"Recently updated to the latest Sumatra 3.2 x64 on Windows 10. Since updating, the program often flickers on various PDF files (tried mostly with Latex-generated files). The display flickers quickly between proper display to displaying white rectangles, as in the image below."

![image](https://user-images.githubusercontent.com/12754913/83327650-60600400-a275-11ea-8af8-7def7500eebb.png)

Forum Thread covered the fact that most OS/hardware combinations can not replicate misbehavior however the problem remains on the posters HP machine. and a description of hardware/windows settings is in the above thread

Minimal Working Example file
[A test file.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4705575/A.test.file.pdf)

**Comment by kjk** [comment]
Probably the same as https://github.com/sumatrapdfreader/sumatrapdf/issues/1711 (one of the comments talks about having many tabs open). If still happens, the bug can be re-opened.
