### ISSUE TITLE
Modern toolbar icons

### ISSUE THREAD

**Issue by alexandrunastase** [sumatrapdfreader/sumatrapdf#16]
I think that an updated set of icons would make sumatra look significantly better.
I have taken the liberty to play around with some icons and update the bmp file which can be found on my forked repo (https://github.com/alexng8/sumatrapdf).
They look best on the 3.0 version. The 3.1 version seems to have the icons streched.

I've also uploaded a side by side comparison : 
![sumatra_pdf_minimalist_icons_comparison](https://cloud.githubusercontent.com/assets/2458807/5330681/b698dec4-7e0d-11e4-8333-43ac0e5208b3.png)

I should mention that I am not a designer, and I got the icons from http://iconmonstr.com/. Here's their licencing policy : http://iconmonstr.com/license/

**Comment by gl-bars** [comment]
I've made [22x22 icon set](https://gist.github.com/gl-bars/7842c590e884dae8f17c#file-toolbar_11-bmp) based on KDE Oxygen theme (except "match case" icon taken from gmusicbrowser) for those who want larger icons.
A screenshot:
![oxygen-sample](https://cloud.githubusercontent.com/assets/3192565/6736056/cbf500c2-ce62-11e4-8d89-b6e8da1e5891.png)

First I was thinking to take "pmahomme" icon theme (quite similar to Sumatra icons), but I could only find its 16x16 images.
