### ISSUE TITLE
Enable monitor color correction

### ISSUE THREAD

**Issue by thomas001** [sumatrapdfreader/sumatrapdf#160]
This issue is *not* about interpreting color profiles in embedded images. 

Monitors, especially wide gamut monitors, do not match the standard sRGB color space. So colors (even sRGB colors) need to be corrected before they can displayed correctly. This would involve querying the monitor color profile from the system and apply a color transformation to everything which is displayed. Luckily, this seems to be pretty easy in Windows by just enabling ICM in the current DC, see [SetICMMode](https://msdn.microsoft.com/en-us/library/windows/desktop/dd372195%28v=vs.85%29.aspx).

**Comment by kjk** [comment]
I don't know much about this topic. Mostly, I don't know how I would go about verifying that color correction happens or doesn't happen, so I don't see making changes in this area.
