### ISSUE TITLE
annotation icons are printed

### ISSUE THREAD

**Issue by ousia** [sumatrapdfreader/sumatrapdf#1601]
This issue is related to (and comes from) #1600.

Just after switching to SumatraPDF-3.2 at work (I have neither Windows nor a printer at home), I realized that annotation icons are printed.

This minimal PDF document contains an attachment and an annotation icon:

> [PDF document with attachment annotation](https://github.com/sumatrapdfreader/sumatrapdf/files/4706141/a.pdf)

The object for the attachment annotation reads:

```
4 0 obj
<<
  /Type /Annot
  /C [ 0 .6 0 ]
  /CA 1
  /Contents <FEFF006100740074006100630068006D0065006E0074002D0031>
  /F 4
  /FS 2 0 R
  /NM (attachment:1)
  /Name /PushPin
  /Subtype /FileAttachment
  /T <FEFF006100740074006100630068006D0065006E0074>
  /Rect [ 94.111377 44.710634 100.08568 50.684934 ]
>>
endobj
```

Although the dictionary above uses `/F 4` ([print](https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf#nameddest=G11.2096191)), annotations may only be printed [if an appearance dictionary is provided for the annotation](https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf#nameddest=M11.9.34021.2Heading.733.Annotation.Appearances.PDF.663) (under the [`/AP` key](https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf#nameddest=G11.2108375) [which is missing in the code above]).

This is the same reason like not printing link annotation borders fixed in #257.

Would it be possible that this could be improved?

Many thanks for your help.

**Comment by kjk** [comment]
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=702543

**Comment by ousia** [comment]
Fixed by http://git.ghostscript.com/?p=mupdf.git;h=14711caa0f236f04412ef314e185e2daacb7b13b.

**Comment by GitHubRulesOK** [comment]
@ousia 
Pablo lets hope more fixes filter through soon, (I see MuPDF 1.18 RC1 is in progress but not for download) 
So in this case SumatraPDF pre-rel was updated about that same day, can you confirm if printing is as expected without icons ?

**Comment by SumatraPeter** [comment]
Unless I'm mistaken the fix has not made its way into Sumatra yet and this has been prematurely closed.

**Comment by kjk** [comment]
it's there https://github.com/sumatrapdfreader/sumatrapdf/commit/390f445551d30c4702e1a86905586eeca67d5bcc
