### ISSUE TITLE
Problem - .\utils\BaseUtil.h (125.10): fatal error C1083: Cannot open inclusion file: "span"

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1604]
.\SumatraPDF\source\src\utils\BaseUtil.h (125.10): fatal error C1083: Cannot open inclusion file: span: No such file or directory, (source file is compiled ..\src\utils\DbgHelpDyn. cpp).\SumatraPDF\source\vs2019\utils.vcxproj]

Whats is file "span"? I don't find it on my system....

**Comment by kjk** [comment]
You have to upgrade to the latest Visual Studio 16.6. <span> is a new C++ feature only available since 16.6

**Comment by VictorVG** [comment]
Thank! Ok! I don't know it.
