### ISSUE TITLE
Website AccessDenied image problems ?

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1605]
Experiencing problems with images in forum including slow down as they are not found see missing logo on left

![image](https://user-images.githubusercontent.com/12754913/83514410-81ba2d80-a4cb-11ea-8f5e-b26f1a5bf2b8.png)

**Comment by SumatraPeter** [comment]
Same here. I think the latest Discourse upgrade broke something.

**Comment by GitHubRulesOK** [comment]
Oddly I can see some images and add new images but dont know why others are blocked

**Comment by kjk** [comment]
Thanks for reporting.
No idea why the images became in-accessible. I've re-uploaded them and seems to be fixed.

**Comment by GitHubRulesOK** [comment]
I guess too late you beat me to it

**Comment by SumatraPeter** [comment]
@kjk: Many images still broken here - the 2 in [this post](https://forum.sumatrapdfreader.org/t/outlook-folders-previewer-change-set-zoom-width/2506/5) for example...

Cleared browser cache completely and also tested with a different browser.

**Comment by kjk** [comment]
Looks like Discourse messed up. I've asked https://meta.discourse.org/t/upgrade-broke-images/153614, we'll see if they suggest anything.

**Comment by SumatraPeter** [comment]
So people have reported that it's been randomly happening during upgrades for more than 4 years now, and the Discourse devs still haven't managed to fix such a massive bug? 🙄

**Comment by SumatraPeter** [comment]
So no replies from the Discourse devs... Most probably 'cos they have no clue how to fix this or else the bug wouldn't fester for so many years.

**Comment by kjk** [comment]
Interestingly, https://forum.sumatrapdfreader.org/t/outlook-folders-previewer-change-set-zoom-width/2506/5 seems no longer broken, however https://forum.sumatrapdfreader.org/t/the-diameter-symbol-is-not-displayed/3027 still is.

Either way, not much that I can do without some hint from Discourse, so closing the issue.

**Comment by SumatraPeter** [comment]
> Interestingly, https://forum.sumatrapdfreader.org/t/outlook-folders-previewer-change-set-zoom-width/2506/5 seems no longer broken

@kjk: If only it were that easy, but nope, all old image uploads are still broken. It's just that in this particular case GitHubRulesOK edited his post on June 4 and replaced the broken images with new ones.

Maybe you can bump your meta.discourse post and ping top-level [Discourse team members](https://meta.discourse.org/g/team) such as **@codinghorror** (Jeff Atwood - co-founder), **@sam** (Sam Saffron - co-founder) and **@eviltrout** (Robin Ward - co-founder) about this long-standing bug. You've got nothing to lose, and if _that_ doesn't spark a response and _some_ useful suggestions at least, then nothing will!
