### ISSUE TITLE
Error when install "Embedded lzsa archive is corrupted"

### ISSUE THREAD

**Issue by psimaster1** [sumatrapdfreader/sumatrapdf#1608]
Hello.
Error when install "Embedded lzsa archive is corrupted"
What to do?

file to install SumatraPDF-3.2-64-install.exe
size 9 380 520 bytes
OS: Windows 10 (64-bit)

**Comment by kjk** [comment]
The size is correct.
Drop the file in https://emn178.github.io/online-tools/sha1_checksum.html
It should generate `e1359ffbf4015bb446cbe537f889a889d329f72f` hash value.
If your value is different then the download is corrupted. Try to re-download, maybe using different browser.
If your value is the same then my only theory is that you have a process (maybe anti-virus software) that corrupts things on load.

**Comment by psimaster1** [comment]
Thanks for answer :)
Hash 2ea4225389dd0afcbab46d260503a9210dca318f
Not good :) Re-download...
And, now ok!
Thanks for help and very usefull program!
