### ISSUE TITLE
Sumatra won't render image on encrypted PDF

### ISSUE THREAD

**Issue by HMGovic** [sumatrapdfreader/sumatrapdf#161]
When you try to open an encrypted PDF which contains an image, the image won't render.

Password prompt:
![image](https://cloud.githubusercontent.com/assets/9989401/7037385/6b2153de-dd78-11e4-92ce-8f5c269c9e8f.png)

Opened PDF:
![image](https://cloud.githubusercontent.com/assets/9989401/7037392/860d03d2-dd78-11e4-82d3-d680dcc2af31.png)

Opened PDF (with Chrome):
![image](https://cloud.githubusercontent.com/assets/9989401/7037429/2464f15c-dd79-11e4-860a-10a0b641b2e1.png)

**Comment by gschenck** [comment]
I think, to get a solution you need to upload a file somewhere and post the link and the password here.

**Comment by kjk** [comment]
I doubt it's related to encryption but there's nothing we can do without having access to the file that shows the problem (see https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports)

**Comment by GitHubRulesOK** [comment]
@kjk dormant issue ?

**Comment by kjk** [comment]
Yeah, closing as lacking test file.
