### ISSUE TITLE
CTD on right-clicking in the bookmarks panel of DJVU/PDF files.

### ISSUE THREAD

**Issue by simurq** [sumatrapdfreader/sumatrapdf#1611]
Hope you'll find my gist report useful: https://gist.githubusercontent.com/simurq/c320a21b0032a2342017b471fa9d3bdb/raw/c276bd38760a2afbb01a6369d9b98dad579401ca/gistfile1.txt
Thanks!

PS: Sorry, if it's been asked/raised as issue before. If so, please move this post as necessary.

**Comment by kjk** [comment]
Hopefully this will fix it. You might try latest daily build https://www.sumatrapdfreader.org/dailybuilds.html (12685 or later) to see if it's fixed.

**Comment by simurq** [comment]
It did the trick indeed. Big thanks to you for ALL your efforts, Krzysztof!!!
