### ISSUE TITLE
CHM issue

### ISSUE THREAD

**Issue by kingkongace** [sumatrapdfreader/sumatrapdf#1612]
Question:

1。 When the CHM file is opened, it cannot automatically adapt to the page size, that is to say, some text is outside the boundary and cannot be seen.

2。 The e-book that has been opened cannot be displayed on the front page, and there is no record of using the file that has been opened on the front page

Suggestions:

1. Add note function to mark and color articles.

2. In reading, the function of "maximize" or "full screen reading" can be added.

**Comment by GitHubRulesOK** [comment]
1。Usually in chmUI mode it reflows to fit the window
![image](https://user-images.githubusercontent.com/12754913/84056541-44afd880-a9ae-11ea-87fe-44f98e015a22.png)
![image](https://user-images.githubusercontent.com/12754913/84056590-53968b00-a9ae-11ea-85f0-bf19a3aa815b.png)

**If using Fixed UI mode it should also wrap**
![image](https://user-images.githubusercontent.com/12754913/84057145-27c7d500-a9af-11ea-9d36-2a98c505eb5b.png)

2。 That only works if set on in options
![image](https://user-images.githubusercontent.com/12754913/84057765-0d422b80-a9b0-11ea-9cd9-157cca867540.png)


1. highlight in red is shown working in FixedPageUI in the 3rd chm picture above also works for ebooks text pdf etc in FixedUI
2. did you try <kbd>F</kbd> or F11 for fullscreen ?

**Comment by SumatraPeter** [comment]
@kjk: Issue title needs to be edited. In any case I don't see anything new (or valid) here to keep this open.

**Comment by kingkongace** [comment]
I come from China, I am a software user, using the win10 system.

I mean, when I use CHM files, there are problems:

1. When I have set the fit page function, however, the result is that the "fit page" cannot be effectively executed, which results in many words outside the screen interface during the reading of CHM files. In other words, when the font size of the text is enlarged, many words can not adapt to the page, and run out of the screen interface.

2. In the newly opened homepage, there is no list of books I have read.

3. Advanced option function cannot be clicked successfully.

**Comment by GitHubRulesOK** [comment]
Which version ? ensure you are using one from https://www.sumatrapdfreader.org nowhere else

1. sample file and settings

2. The window must be at least tall enough for the icons 410 pixels minimum
![image](https://user-images.githubusercontent.com/12754913/84067662-a3ca1900-a9bf-11ea-9497-d5a77b93b894.png)

3. show us why not
![image](https://user-images.githubusercontent.com/12754913/84067812-eee42c00-a9bf-11ea-8727-6d8791297091.png)

**Comment by kjk** [comment]
Please post a single thing per GitHub issue.

For things like the 2 issues you've reported, please provide more information, like sample files, screenshots of incorrect behavior etc.
