### ISSUE TITLE
gap bands in printout of this file

### ISSUE THREAD

**Issue by Digital-Monk** [sumatrapdfreader/sumatrapdf#1614]
[rexulti-card.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4753120/rexulti-card.pdf)

When I print that file there are horizontal gaps in the printout every inch or two.  Printed it OK with Chrome's built in PDF, so it's not a completely broken file (and my printer works).

(by the way, thank you so much for SumatraPDF!)

**Comment by GitHubRulesOK** [comment]
Frequent problem with many printers. It seems to be down to the drivers handling of the large image print files that SumatraPDF produces. Some users have found using a portable version 3.0 which allows to set print NOT as image works for them, whilst others have found deselecting optimization settings in the driver helps them. Usually it is not the file structure at fault  rather the type of contents that cause more bloated printer image outputs with then poor print driver handling.

**Comment by GitHubRulesOK** [comment]
What we find is the file has a large 10" x 6" insert
![image](https://user-images.githubusercontent.com/12754913/84408014-838a9c00-ac03-11ea-9724-99f04d306145.png) where the contents of the ID get overwritten like in a Form thus the file is composed of different scales and overlays generally not an issue for viewing but when printing it creates a 39 MB decompressed file that just starts to get bigger and bigger

As an alternative try the much simpler output from MSPrint and send that to the hardware printer
[MSPrint out.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4765906/MSPrint.out.pdf)

**Comment by Digital-Monk** [comment]
Thanks for looking into it.  I never cease to be amazed by some of the crazy stuff that gets jammed into PDF files.

**Comment by Digital-Monk** [comment]
[LoremIpsum.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4805818/LoremIpsum.pdf)

Not just giant images.  The attached file is just text and fonts.

Seems to be an issue introduced in 3.2.  The attached file prints properly in 3.1.2, but has bands in 3.2.

File was produced with LibreOffice Writer 6.4.4, "File/Export As/Export As PDF..."

It is possible that this is an issue with the Portable build.  I have 3.1.2 installed from before my company locked down admin access.  Unable to update it now, so I am running 3.2 via a portable build.  I suppose the 3.2 portable build could be pulling in a DLL from the 3.1.2 installed system, but that seems unlikely (and not very "portable"), so I'm leaning towards a fault introduced in 3.2.

Thanks again.  Awesome program regardless!

**Comment by GitHubRulesOK** [comment]
Checking with 3.1.2 and 3.2x I see very very minor differences in output to Virtual HP laserjet print files (They both get bloated to about 1MB) so not enough code difference to make an obvious difference to a printout. In both cases I was able to view the same output.PRN files without visual difference and expect that If I were to send the file to my HP inkjet printer that page would be unaffected.
Thus I have to suggest there is some print driver related problem. it may help to know which printer driver you are using so I can try to emulate your set-up but cant guarantee to be able to duplicate the issue.

**Comment by Digital-Monk** [comment]
Sharp MX-6240N PCL6

Network printer, PCL mode.  Fair sized office printer/copier.  Windows 10 64-bit driver.

**Comment by GitHubRulesOK** [comment]
Hpw many Sharp MX-6240N PCL6 drivers can there be? I found 4 different types in just one Sharp site and that does not include those that Microsoft may push.
can you determine the variant or a filename you downloaded ?

**Comment by Digital-Monk** [comment]
Sorry, took awhile to find the right place to dig to get more than just the model of the printer for an identifier...

Driver Version 03.00.03.14, Copyright (c) 2012

Which is ancient, but seems to work for everything else...  Also, that's a corporate printer, so I couldn't update the driver if I wanted to.  I could ask IT to do so, but they'd ask why, and since they also supply Acrobat Reader (which doesn't do this) for PDF viewing, I seriously doubt that they'd perform an update...

For now, I've just backed up to 3.1.2.

**Comment by GitHubRulesOK** [comment]
closing as older version resolved OP issue 
but also looks like many others a duplicate resource/timing problem with printing large volumes of pixels through windows drivers. soo covered in #919 & [#1312](https://github.com/sumatrapdfreader/sumatrapdf/issues/1312)
