### ISSUE TITLE
[Thumbnail function]Added the ability to display PDF thumbnails in Windows Explorer.

### ISSUE THREAD

**Issue by abc1044** [sumatrapdfreader/sumatrapdf#1616]
Hope to add: the ability to display PDF thumbnails in Windows Explorer.

After setting sumatraPDF to the default open mode of PDF, the PDF file in Windows Explorer was shown as an icon of SumatrapDF without the thumbnail display. Sometimes it is not convenient to quickly understand the CONTENT of PDF. Want to add thumbnail function. Please consider it, thank you!

**Comment by GitHubRulesOK** [comment]
Windows shows thumbnails, SumatraPDF can provide thumbnail and previews if that extra option is installed correctly.
![image](https://user-images.githubusercontent.com/12754913/84390258-3270ad00-abef-11ea-896e-ad511a545178.png)

**Comment by abc1044** [comment]
> Windows shows thumbnails, SumatraPDF can provide thumbnail and previews if that extra option is installed correctly.
> ![image](https://user-images.githubusercontent.com/12754913/84390258-3270ad00-abef-11ea-896e-ad511a545178.png)

**Thank you very much**, I have successfully used the "**-with-preview**" command. I'll mark the links and commands here so that others can view them.

https://www.sumatrapdfreader.org/docs/Installer-cmd-line-arguments.html
To get list of options run the installer with -help.
Available options:
-s : silent installation. Doesn't show any UI
-d <directory> : set directory where program is installed. The default is %LOCALAPPDATA%\SumatraPDF. For example Sumatra-installe.exe -d "c:\Sumatra PDF"
-x : don't actually install the program. Only extracts the files
-with-filter : install search filter
**-with-preview : install shell preview**
-log : since 3.2, writes installation log to %LOCALAPPDATA%\sumatra-install-log.txt
