### ISSUE TITLE
Maximised window doesn't obey Fitt's law

### ISSUE THREAD

**Issue by jaloopa** [sumatrapdfreader/sumatrapdf#1617]
Sumatra version 3.1.2 64 bit
Windows 10 1909

Reproduction steps:
* Open some PDFs and maximise the window
* Move the mouse to a different tab, right at the top of the screen
* click to select the tab

This will sometimes work as expected, selecting the new tab, but sometimes will bring any window behind into focus, or remove focus from the Sumartra window if there is no window behind.

If I move the mouse along the top edge of the screen, I can see that it is highlighting tabs in some positions but not others

Video of the bug in action
[ISO20022_MDRPart2_CAPE_catm_2016_2017_v1.pdf - SumatraPDF 2020-06-11 14-14-04.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4764953/ISO20022_MDRPart2_CAPE_catm_2016_2017_v1.pdf.-.SumatraPDF.2020-06-11.14-14-04.zip)

**Comment by GitHubRulesOK** [comment]
Its a bit academic since you are using some odd theme boundary with an old version 3.1.2 thus that can't be fixed.
Please check if behaviour is still the same with current Pre-Release, since that could possibly be changed to ignore the effects of the windows system boundaries.

**Comment by jaloopa** [comment]
>an old version 3.1.2

Well in that case, I need to report another bug
![image](https://user-images.githubusercontent.com/3093252/84393863-0a377d00-abf4-11ea-8752-9816c781cd85.png)

**Comment by GitHubRulesOK** [comment]
Not a bug 3.1.2 was / is the best latest version

**Comment by jaloopa** [comment]
I also don't know what you mean by "odd theme boundary". To the best of my knowledge I haven't installed any themes for Windows or Sumatra, only changed the accent colour from within Windows Settings, and if that breaks Sumatra then it's something that needs to be looked at

**Comment by jaloopa** [comment]
This appears to be fixed in 3.2

**Comment by GitHubRulesOK** [comment]
I mean you have a windows controlled area outside SumatraPDF which I dont get when its Maximized
