### ISSUE TITLE
text of PDF comments does not appear on click or hover

### ISSUE THREAD

**Issue by jmfranck** [sumatrapdfreader/sumatrapdf#1618]
to provide a test [see this file](http://ctan.math.illinois.edu/macros/latex/contrib/pdfcomment/doc/example.pdf)

note that the comment text can be read by right clicking and selecting "copy comment" but it doesn't appear on hover (as I believe it did in earlier versions?)

v3.2: fc8535a

**Comment by stephenlevitt** [comment]
I can confirm that I can no longer view comments. 

Running v3.2, 64-bit on Windows 10.

**Comment by GitHubRulesOK** [comment]
Closing as known issue and fixed after 3.2 see https://www.sumatrapdfreader.org/docs/Version-3.2.1.html and https://github.com/sumatrapdfreader/sumatrapdf/issues/512
