### ISSUE TITLE
Feature request: do not default to 'facing' view if the PDF has only one page

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [sumatrapdfreader/sumatrapdf#1619]
I create many double-sided handouts. So, I set Sumatra to default to the 'facing' view'. However, that view looks odd - everything is smaller than it need be - for single page documents. Yet, Sumatra displays those in facing mode anyway (if that mode is the default).

My suggestion is that the reader override the facing view default for single page documents. I cannot see a reason not to (though possible a tool-tip explaining what is happening might be an idea).

**Comment by kjk** [comment]
Here's the problem:

The next person will set the default view to facing, open a single page file and Sumatra will open it in different view than he requested.

He will consider it a bug and come here complaining how Sumatra ignores settings.

You can switch easily to another view with e.g. `Ctrl-6` but we will not be ignoring the settings you chose.

**Comment by LinuxOnTheDesktop** [comment]
'The next person will set the default view to facing, open a single page file and Sumatra will open it in different view than he requested. // He will consider it a bug'. Not if he is sensible - for a single page cannot face another page, because there is no other page in that situation - and not if there is the tooltip I mentioned. Or so it seems to me.

**Comment by GitHubRulesOK** [comment]
Whilst I understand that 1 single page is offset by a default of either "facing" or "book" and don't forget it is reversed for RTL vis LTR so there are several locations the code would need to be bloated.

The undesired effect

> that view looks odd - everything is smaller than it need be - for single page documents. 

will be exactly the same if centred, thus can be very easily remedied by pressing fit width "continuous"

**Comment by LinuxOnTheDesktop** [comment]
I had some trouble understanding you there; but I think I understand.

I take it from your second paragraph that the following is the case. When I see a single page displayed as if it were part of a pair of pages, there's a particular icon that I should press. OK: I've located that icon. Pressing it does improve spacing in such a scenario, but it changes the scaling too, such that I cannot immediately see the whole page.

Here is why it matters that one be able _quickly_ to have the page look how one wants. One might be generating many a PDF, one shortly after the other, and opening each in Sumatra in order to check, quickly, that it looks alright (i.e. that it contains no gross mistakes).

On your first paragraph: I am unsure you really mean bloat. Bloat in code is code that takes up much space (or uses many resources) without doing anything very useful. Still, I suppose we're debating how useful the code in question would be.

**Comment by GitHubRulesOK** [comment]
If you need whole page use the other "single page" Icon to centre the offset page
you can also set a default zoom to any preference.

my point about bloat is that all "feature requests" usually result in slow down for analysis and KJK does frequently tighten it by consolidating features but inevitably feature crepe makes it slower.
