### ISSUE TITLE
x64 installer defaults to 32-bit folder (Program Files (x86))

### ISSUE THREAD

**Issue by GeneralKenobi1** [sumatrapdfreader/sumatrapdf#1626]
I'm on Windows 7, although this may apply to other versions of Windows too.

When using the x64 installer from the official website, the installer automatically picks the 32-bit folder "Program Files (x86)" to install Sumatra PDF to. It should install to "Program Files" instead (the 64-bit folder)

This wrong folder issue confuses my automatic file updater program PatchMyPC. It downloads the 32-bit update for it, then SumatraPDF halts all my silent updates to throw a "32-bit on 64-bit system" popup.

edit: Just uninstalled and reinstalled it, and now it is defaulting to AppData\Local\SumatraPDF. Another odd place for it. Aren't program files supposed to go in the program files folder, and AppData is for settings? Hmm.

**Comment by GitHubRulesOK** [comment]
Not the developer so I will simply comment that the installer will install to a previous installation directory, thus for me it is the existing 64bit \Program Files\ and ONLY If I run the 32bit installer then it would attempt to update my \Program Files (x86)\ copy.
In both cases if it is a fresh installation it will by default install all its files in one accessible user %localappdata%\sumatraPDF folder
Silent (Admin) users should be aware of default consequences in their managed systems and decide what is most appropriate for OTHER users.

**Comment by kjk** [comment]
When you upgrade, Sumatra installs to whatever the old installation path was.

A new install defaults to %LOCALAPPDATA% because unlike %PROGRAMFILES%, it can be written to without admin permissions.
