### ISSUE TITLE
Regression, "Please wait - rendering" nerver show after issue #1621 fix

### ISSUE THREAD

**Issue by Bambooin** [sumatrapdfreader/sumatrapdf#1630]
I used had a complex resume pdf file, every time I **first load it after os restart**, the "Please wait - rendering" will show in about 2 seconds. Now it nerver show it, after issue #1621 fixed.

**Comment by GitHubRulesOK** [comment]
@kjk 
I can confirm the warning about "rendering" whilst taking a long time to render does not appear when opening the slowest example e.g. "Please wait - rendering..." for infinite time #1030
