### ISSUE TITLE
MuPDF & Freetype

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1632]
Whilst looking through MuPDF issues I noted that a number of issues similar to those raised in SumatraPDF  (Type1 fonts created by pdflatex) were attributed to using more recent unmodified Freetype2.

This seems to coincide with poorer font related word searching after SumatraPDF changing in https://github.com/sumatrapdfreader/sumatrapdf/commit/08acb67ecc7899fdbdc2e347616c853703d4799f

Without the ability to look closer at the merits of the comments I will refer you to 
https://bugs.ghostscript.com/show_bug.cgi?id=701977

which suggests Freetype 2.10.2 should fix it
 https://savannah.nongnu.org/bugs/?57519

**Comment by GitHubRulesOK** [comment]
@kjk 
high on your list is = review #1596
https://github.com/sumatrapdfreader/sumatrapdf/blob/1606815c0cc2aebe2b96a29f6ec03dd6c7c36205/src/todo.txt#L3 

folowing is latest discusion by Willus (App developer/Tesseract User) and Tor (Artifex)
https://bugs.ghostscript.com/show_bug.cgi?id=702509

**Comment by kjk** [comment]
Thanks @GitHubRulesOK 
This was really useful information.

I wasn't compiling freetype with the exact same options as mupdf, which led to issues. Fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/59ee85e40bed1a94a16ef3cfa801fe4e0face3f1

If mupdf updates their freetype in the future, we'll update as well.

**Comment by GitHubRulesOK** [comment]
@kjk 
bump (I'm trawling bugzilla fixes)

several mupdf users have reported better copy /past /find / read aloud results using freetype v 2.10.2 as mentioned above e.g also see https://bugs.ghostscript.com/show_bug.cgi?id=701977

however SumatraPDF lib at https://github.com/sumatrapdfreader/sumatrapdf/tree/master/ext/freetype still reports as 2.10.0 ?

**Comment by kjk** [comment]
I'm using the same version of libraries that mupdf. For freetype it's 2.10.0 currently.

When they I upgrade, I'll upgrade.

They are aware of the issue (as the mupdf bug shows) so I assume they have a reason to use that version of freetype.
