### ISSUE TITLE
Handle DPI changes when moving between monitors

### ISSUE THREAD

**Issue by wang-ps** [sumatrapdfreader/sumatrapdf#1636]
I have two displays on my PC, the resolutions are `3840 x 2160` (denoted as A)  and `1920 x 1200` (denoted as B) respectively. 
The version of Sumatrapdf I used is v3.3.12858 64-bit.

On display A, the window looks as follows, and it is OK.
![image](https://user-images.githubusercontent.com/7525130/85518116-825d6400-b632-11ea-8605-04fc9e65d4b7.png)

but on display B, the window looks as follows, _the font size on the **Toolbar** and **Bookmarks**  becomes much larger_:
![image](https://user-images.githubusercontent.com/7525130/85518401-c5b7d280-b632-11ea-9c4d-e63658300f88.png)

**Comment by GitHubRulesOK** [comment]
I am not sure all the issues with different screen resolutions could be addressable
There are actually 3 different inter related problems

1) The number of pixels used by the two different screens will naturally make the working areas different
That could be controlled by **windows scale settings** increasing screen A @ 200% and keeping screen B @ 100% , but that would defeate using a hi-res screen

2) The scale of the Toolbar and Bookmarks text can also be controled by altering **windows settings** to make all applications on screen A twice as big however I am not sure if windows will do that on a per application basis.

3) The scale of the Toolbar Icons follows the above windows dpi settings so the toolbar layout ratios would be affected as the two others changing.

Most of this is related to **Windows display settings** see "Add setting for changing sidebar (and toolbar) font size #899"

SumatraPDF now has a new optional setting for Bookmark text which can help see https://github.com/sumatrapdfreader/sumatrapdf/issues/710

**Comment by wang-ps** [comment]
Thank you so much for your support! SumatraPdf is an excellent software and my default Pdf viewer.

I could not fully understand your explanations. Here I provide more details.
The display A (resolution 3840 x 2160) is scaled by 175%, and the display B (resolution 1920 x 1200) is scaled by 100%.  I took another two snapshots with the vscode as a reference. 

On display A, the screenshot is as follows, and both the **_Toolbars_** of SumatraPdf and vscode look OK.

![1](https://user-images.githubusercontent.com/7525130/85935974-edf04b80-b928-11ea-864b-f25b0ffb378c.png)


But on display B, the **_Toolbar_** of vscode looks ok, the **_Toolbar_** of SumatraPdf is much larger. It seems that SumatraPdf did not rescale the **_Toolbar_**  on display B. 

![2](https://user-images.githubusercontent.com/7525130/85936021-5d663b00-b929-11ea-8fcd-ebbd25f40c8f.png)

Look forward to your replay!

**Comment by kjk** [comment]
Yes, we don't handle DPI changing as a result of moving between monitors with different DPIs.
It's non-trivial to get working.

**Comment by wang-ps** [comment]
OK, I see. Thank you!
