### ISSUE TITLE
[feature request] Hotkey for "Open in folder" command

### ISSUE THREAD

**Issue by helperman** [sumatrapdfreader/sumatrapdf#1637]
There is no hotkey for this command.

**Comment by GitHubRulesOK** [comment]
**S**how in Folder in english menu is defaulting on S
<kbd>ALT</kbd><kbd>F</kbd><kbd>S</kbd>

**Comment by helperman** [comment]
OK. Found.
But on my version it is on F.
Alt + F + F.
S is for "Save"
