### ISSUE TITLE
[feature request] Close and delete currently opened document

### ISSUE THREAD

**Issue by helperman** [sumatrapdfreader/sumatrapdf#1638]
Since you've read a document and no longer need it, you can delete it easily just in one click (or hotkey).
Or please provide any way to retrieve full path to currently opened document so that folks could use their own ways to do it (or any other tasks).
For ex, some viewers have feature "Copy document's fullpath to clipboard".

**Comment by GitHubRulesOK** [comment]
<kbd>ALT</kbd><kbd>F</kbd><kbd>S</kbd><kbd>DEL</kbd><kbd>ENTER</kbd>

**Comment by helperman** [comment]
My documents are opened upon this hotkey.
But my opened document is located in another folder.

**Comment by helperman** [comment]
Ok. Looks like you meant Alt + F +F + Del + Enter.
This works. Thanks.

**Comment by GitHubRulesOK** [comment]
@helperman 
You may on occasion find there is a system limitation.
Normally Windows will stop you deleting the file you have open and are reading.
SumatraPDF does not lock smaller PDF files (e.g. you should not be able to delete a PDF that is over 32 MB if it is Locked OPEN)
