### ISSUE TITLE
Open containing folder

### ISSUE THREAD

**Issue by jantari** [sumatrapdfreader/sumatrapdf#1639]
Hi,

I frequently open PDFs directly from Outlook (eMail attachments), and Outlook saves them to a temporary directory that's rather annoying to navigate to manually should I then decide I need to keep the PDF or save it somewhere etc.

A menu item or right-click option (on the document surface or tab) to open the document in file explorer, with it already highlighted/selected, would be fantastic for me.

I found an option "Open documents folder", it's the 4th item inside the "File" menu,
but - and I'm not sure whether this is intended - it doesn't open the current documents' folder, but rather literally just the Windows "Documents" library ( What you get from PowerShell/.NET `[Environment]::GetFolderPath('MyDocuments')`)
![image](https://user-images.githubusercontent.com/25607767/85670845-91d7be00-b6c1-11ea-8b57-7ca3571dbdd0.png)
( I use a german localized SumatraInstall, sorry)

What I really want is to open this folder quickly, that can be seen in File -> Document Properties (or sth, similar, it's localized for me)
![image](https://user-images.githubusercontent.com/25607767/85670957-b16ee680-b6c1-11ea-86fc-04b14d8d8f95.png)

If you use Visual Studio Code, it has the feature I'm looking for in Sumatra - including the part where it pre-selects the file:
![image](https://user-images.githubusercontent.com/25607767/85671457-2cd09800-b6c2-11ea-9da8-890ecaf176ec.png)

**Comment by kjk** [comment]
I can't reproduce this - for me it shows the right folder / file.

All sumatra does is to launch `explorer.exe /select,"$filePath"`.

**Comment by jantari** [comment]
Ok I did some more testing and you are right - I can now say this is not a bug in Sumatra.

When opening a PDF attachment from Outlook 2019 in SumatraPDF 3.3.12844-x64 I can open the containing folder just fine through that menu item - for as long as I still have the mail the attachment came from selected/open in the preview pane in Outlook Outlook deletes the local temporary PDF when I click on another E-Mail in my inbox. Thus, the PDF stays open in Sumatra (cached?) but it's already gone from the filesystem and that's what causes the "Open containing folder" menu item to just open up "This PC" ( I misspoke earlier when I said it would open the Documents library, my bad).

Now, it makes all the sense in the world that Outlook cleans up temporary files in this manner - my bad.

Also, I have found another way to resolve my user-story:

Even once the original file has been deleted, Sumatra is thankfully able to "Save As" the cached document somewhere - so my scenario where I open a PDF directly from a Mail and THEN decide whether I want to keep it (as opposed to blindly saving directly from Outlook) can be achieved through that.

Thanks!

**Comment by GitHubRulesOK** [comment]
@jantari 
If you want to keep a temporary file use the "Rename" function <kbd>F2</kbd> (just one key)
it picks up the current filename and allows you, at the same time, to navigate like "save as" 
with an added bonus that the file name changes in the tab to the new location
You can also change to more meaningful filename or **remove** any odd name endings like ....[1].pdf
