### ISSUE TITLE
Zoom hot keys not working

### ISSUE THREAD

**Issue by ksrik** [sumatrapdfreader/sumatrapdf#164]
I am using these:
`SumatraPDF 3.0`
`Windows XP, SP3`
Zooming hotkeys don't work, i.e `Ctrl+1,Ctrl+2, Ctrl+3` and `Ctrl+Y`. But `Ctrl+0` works fine.

Is there a patch for this?

Regards,
srik

**Comment by kjk** [comment]
In general, it works.

Do the corresponding menu items (Zoom/*) work?

Does it happen with all PDF files or just one?

If it just one, the please share the file as described in https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports

**Comment by ksrik** [comment]
Menu items (Zoom To width) works fine.

The hotkeys don't work for *any PDF file*.

---ksrik

**Comment by kjk** [comment]
My only explanation is that either when you're pressing Ctrl-1 etc., the window doesn't have focus or you've reconfigured the keyboard.

This works as expected in my testing.
