### ISSUE TITLE
Add system level install

### ISSUE THREAD

**Issue by jmacasd** [sumatrapdfreader/sumatrapdf#1643]
Current installer only installs for current user (desktop icon), and if you choose another path like C:\Program Files\SumatraPDF does not create all user's desktop shortcut nor integrates as a PDF reader for all users.

**Comment by jmacasd** [comment]
Related post on forum: https://forum.sumatrapdfreader.org/t/sumatrapdf-v3-2-system-wide-installer-all-users/2809

**Comment by GitHubRulesOK** [comment]
@kjk I think the recent installer addresses this request ? and possibly linked https://github.com/sumatrapdfreader/sumatrapdf/issues/1794

**Comment by kjk** [comment]
Yes, but I haven't tested it yet so I'm not sure if it addresses all the issues so let's say it's a work in progress.

**Comment by kjk** [comment]
See https://github.com/sumatrapdfreader/sumatrapdf/issues/1794#issuecomment-1114052198
