### ISSUE TITLE
Why is the default zoom fit to page?

### ISSUE THREAD

**Issue by DoTheEvo** [sumatrapdfreader/sumatrapdf#1650]
Any practical reason for it? Or is it just personal preference?

Why not just go for 100%?

I mean I would understand if there would be expected standard behavior in PDF readers world, but sumatra is actually an outlier here.

Not that the others are doing better
* adobe reader DC goes for fit width
* foxit goes for fit width
* all browsers go for 100%

I still prefer fit page better than eyes burning  out fit width, but not everyone has 27" screen and it still requires adjustment.

100% should be the default.

Just a bit of bikeshedding thought.

**Comment by GitHubRulesOK** [comment]
You can set your own preference in "options" mine is "Fit Page"
![image](https://user-images.githubusercontent.com/12754913/86070692-2f8e0d00-ba75-11ea-9a25-3adebd5fe08d.png)
But if I quit the file when using fit width then "remember these settings per document" then it will be fit width the next time I open it If I switch that off it will naturally go back to fit page

**Comment by DoTheEvo** [comment]
Oh I do know that I can change.

I am just installing various software with powershell scripts quite often, and then if easy I make adjustment I find would benefit a regular-barely-able-to-click-something users...   so that it is more user friendly out of the box.

And since recent version changed location of the config file and it is populated on the first run I had to adjust that...
I realized I could maybe just ask...  and skip all that in the future.

**Comment by GitHubRulesOK** [comment]
If you are spoonfeeding a mass install with your own settings.txt
many options (perhaps not all) can be injected at the top of the file and will percolate down to replace the default

```
# For documentation, see https://www.sumatrapdfreader.org/settings/settings3.3.html
DefaultZoom = 100
MainWindowBackground = #80fff200
```

**Comment by GitHubRulesOK** [comment]
In answer to the question 
There is naturally a default first setting on installation
which historically matched Adobe Acrobat topmost entries of the time
i.e. Automatic, Fit Page.
If SumatraPDF were to vary from using its historic topmost values then the future question would be
Why is the default zoom on installation "not fit to page"

**Comment by DoTheEvo** [comment]
Yeah, that answer tends to send me in to angry mood immediately, especially if one heard it often enough.

- "Why do we do this this way?"
- "cuz we have been doing it that way"
- ".... yes... I am...  aware"

Dont really affect me here with rage ;)
But i must point out how disgusting excuse that is, that allows to completely give up on any thought given.

But people who make sumatra obviously use it, and if they never felt like constant ever present zooming in is an issue then its fine. Its just be better if it was conscious choice, rather than... copying someones setting and inertia.

**Comment by GitHubRulesOK** [comment]
I do not know if it was a concious copy of Acrobat behavior, SumatraPDF has used various engines such as xPdf and Popplar before the current MuPDF whose own viewer generally defaults to fit window to page like some graphics apps.
@kjk any comment ? since I was not around when the following pecking order was first initalised ? 

Fit Page
[Actual Size] on zoom menu but not when starting
Fit Width
Fit Content
Zoom factors
