### ISSUE TITLE
Installer of SumatraPDF

### ISSUE THREAD

**Issue by b-deng** [sumatrapdfreader/sumatrapdf#1652]
How can I installer of SumatraPDF from resouce.

**Comment by GitHubRulesOK** [comment]
Your question is too short and unclear

The GitHub source code needs to be compiled with VS2019 etc. to build an installer.
Last 3.2 source release is at https://github.com/sumatrapdfreader/sumatrapdf/releases/tag/3.2

Precompiled binaries are available from
https://www.sumatrapdfreader.org/download-free-pdf-viewer.html
https://www.sumatrapdfreader.org/prerelease.html
https://www.sumatrapdfreader.org/dailybuilds.html

**Comment by b-deng** [comment]
I want to know how can I build SumatraPDF installer packet.Thanks.
https://www.sumatrapdfreader.org/dailybuilds.html
https://www.sumatrapdfreader.org/prerelease.html

**Comment by GitHubRulesOK** [comment]
The binaries are either already installers (or portable.exe)
Still not clear what you are expecting to "build" that is different

**Comment by b-deng** [comment]
I have found the answer.Thank you very much for your reply.
