### ISSUE TITLE
可以加一个功能吗？

### ISSUE THREAD

**Issue by StephenWu5** [sumatrapdfreader/sumatrapdf#1658]
请问可以加上这样一个功能吗？
写文字注释和区域高亮。简单点就行。
就好像福昕编辑器那样。

if you can't see my word, you can use google translate.

**Comment by GitHubRulesOK** [comment]
_Can such a function be added?
Write text notes and area highlights. Just keep it simple._

Already has been (已经) see https://www.sumatrapdfreader.org/prerelease.html

**Comment by StephenWu5** [comment]
ok
