### ISSUE TITLE
Hide temporary internet files from frequently used.

### ISSUE THREAD

**Issue by ifazk** [sumatrapdfreader/sumatrapdf#166]
I view a lot of pdfs on the internet, and most of the time, I do not need to save them. Hence I have a lot of pdfs from the Temporary Internet Files Folder polluting my frequently used list.

I would like the hiding the files whose paths are similar to the following. This is for Internet Explorer, but other browsers might be similar.
C:\Users[a-zA-Z]+\AppData\Local\Microsoft\Windows\INetCache\IE.*

**Comment by kjk** [comment]
Other people might consider such behavior a bug.

It's easy to remove from the list (right-click for context menu and use `Remove From History`)
