### ISSUE TITLE
Crash in template_affine_N_near_fb0 during zoom

### ISSUE THREAD

**Issue by LoGaIta99** [sumatrapdfreader/sumatrapdf#1660]
I was zooming quite fast and Sumatra crashed. The document was an export from TeXmacs.

https://gist.github.com/LoGaIta99/45a8b9570d58763c7424e85e4fa17408

**Comment by SumatraPeter** [comment]
@kjk Looks to be a dupe of #1514 (which seems to have been ignored by the MuPDF devs). #1642 is also zoom-related but seems to be a different cause.

**Comment by kjk** [comment]
Most likely a duplicate of #1514
