### ISSUE TITLE
Display wrong text in figure

### ISSUE THREAD

**Issue by ikjoon-son** [sumatrapdfreader/sumatrapdf#1661]
Hi All,

In certain documents, I found that the text in the figure was broken.

test document: [atc19-zhang-lu.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4876913/atc19-zhang-lu.pdf)

![20200706_143042](https://user-images.githubusercontent.com/61674613/86558803-52e51a80-bf95-11ea-9e89-03702d382375.png)
Left is Microsoft Edge built-in PDF viewer, and Adobe Reader DC is also fine.
Right is Latest SumatraPDF daily build, built on 2020-07-06, commit 0134249f7c1e7ce916e8c3d2228631b21fb47e58.

Thanks.

**Comment by kjk** [comment]
Opened mupdf bug https://bugs.ghostscript.com/show_bug.cgi?id=702542
