### ISSUE TITLE
Currently highlights are in Limbo 

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1662]
re: latest "remove support for saving annotations in .smx files "

Appears to result in (going forward) there would be no way to view older smx highlights other than use portable copy of full release 3.2.0

Also there is curently no highlight function in daily !

**Comment by GitHubRulesOK** [comment]
@kjk 
I stand corrected there is a highlight it just has no meaningful rect
the enclosed pdf has the **same two highlights**
yellow from mupdf-gl and red from latest sumatraPDF
[Hospital Medical Report-no comment  - mupdf.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4887876/Hospital.Medical.Report-no.comment.-.mupdf.pdf)

**Comment by kjk** [comment]
Restored highlights.

Yes, .smx are no longer supported.

**Comment by GitHubRulesOK** [comment]
@kjk 
They show whilst editing but disappear after save and refresh, I cant find a way to make them stick in this file
[Hospital Medical Report-no comments  - Commented.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4890283/Hospital.Medical.Report-no.comments.-.Commented.pdf)

**Comment by nod5** [comment]
@kjk regarding "Yes, .smx are no longer supported." and https://github.com/sumatrapdfreader/sumatrapdf/commit/85fc453c6f67e23c9bb408c78e9f493a36f41c60

Please clarify, are you now
(1) dropping the feature of saving annotations to external file altogether
(2) removing the specific .smx implementation to prepare for later replacing it with some other external file annotation implementation?

**Comment by GitHubRulesOK** [comment]
@nod5 
kjk will need to give you a definitive answer, however between the lines, .smx was a very good experiment for simple highlights across all FixedPageUI formats, and I am sorry to see it retired.
As described expanding smx to include all annotations would involve reinventing all the cogs and gears that are available within MuPDF annotation which is "almost" working internally but only designed for appending to a PDF.

**Comment by kjk** [comment]
@nod5 Going forward I plan to implement full support for annotations in PDF files. Support for other file types (i.e. .smx files) is dropped.

**Comment by kjk** [comment]
@GitHubRulesOK I've made some tweaks and can't reproduce the annotations issues in `Hospital Medical....pdf` file i.e. I can create highlight annotations and save them and they are present in saved file.

If it still happens for you, please provide more detailed steps to reproduce.

**Comment by GitHubRulesOK** [comment]
@kjk 
confirm that with the example file 13040 is working.
either (strong possibility) I was not running/watching latest version or it was a different file (perhaps with a password) am testing both possibilities but agree this thread is closed

**Comment by GitHubRulesOK** [comment]
@kjk 
as far as I can tell non working was daily version of SumatraPDF-prerel-13034-64.exe ( same as current pre-rel)

**Comment by nod5** [comment]
@kjk Ok, very sorry to hear that .smx will be dropped _and_ no new way to save annotations to external files will be added.

Prerelease versions has had .smx support for quite a few years now. They were also for a long time the only versions that got updates. Anyone who during that time used the .smx feature may want some way to access their already created annotations going forward. I sure will.

Two possibilities:
1. A legacy release of the most recent prerelease version that had working .smx support.
2. Some tool to convert old .smx annotations to whatever new format you adopt for PDF file internal annotations.

Will you do either? If not then those who want to access their already created .smx annotation data will have to either compile from older prerelease sources or use older prerelease binary versions. The latter option presupposes distributing those older binary releases.

**Comment by GitHubRulesOK** [comment]
@kjk 
as you know legacy formal releases will all since smx was introduced support viewing smx annotation.
the problem is that Nod5 apps depend on the pre-release, however they eventually get purged on a cycle from the downloads. What would be useful is one permanant 32 and 64 bit portable to be retained. 
An alternative is to permit Nod5 to mirror those last two working copies

**Comment by kjk** [comment]
@nod5 You could convert .smx to PDF using an older pre-release version that had .smx support.

But going forward only PDF will be supported (PDF format already supports annotations, I'm not inventing anything new).

@GitHubRulesOK anyone can compile an older version of Sumatra (before the checkin which removed .smx support) using source code from GitHub. There's no permission needed to distribute older or modified Sumatra builds.

**Comment by GitHubRulesOK** [comment]
@kjk 
not sure your statement could not be misconstrued (as it often is) to allow rebranding

@nod5 
In light of the current situation several of your open issues may need edit or closure ?

**Comment by nod5** [comment]
@kjk Ok. I will make a script to automate those manual conversion steps, in case users, like me, have a lot of .smx files. 

It would be useful if the official site permanently stored a frozen/legacy binary of a prerelease with .smx support working, as GitHubRulesOK mentions. For anyone who at a later time wishes to make that conversion.

> There's no permission needed to distribute older or modified Sumatra builds.

Legally no, but you make the request "please do not redistribute" at https://www.sumatrapdfreader.org/prerelease.html

> going forward only PDF will be supported

This means that already created .smx annotations for other filetypes like EPUB will not be usable other than through older prerelease binaries.

**Comment by GitHubRulesOK** [comment]
@nod5 
the epub.smx can be seen in 3.2 binary it is only edits that need pre-release
