### ISSUE TITLE
Copy selection is not functioning in latest version

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1668]
Using current 13044 selecting an area using ctrl & left click 

Allows to either create highlight or zoom / print selection
However it does not allow copy selection as it did previously

**Comment by kjk** [comment]
Could you provide more information?

I used ctrl mouse to select a region and then both context menu and Ctrl-C to copy a text selection, and it worked for me.

**Comment by GitHubRulesOK** [comment]
Not text selection, area should store both image and text, always have been able to paste into paint

13000 was working still trying to find the break point

**Comment by GitHubRulesOK** [comment]
Just a random guess and potential red herring since there was no comiler output for me to pin to one commit but at end of https://github.com/sumatrapdfreader/sumatrapdf/commit/305bf3a88ef740c6c45c10651ae10ef1ede35f84 there is a `DeleteOldSelectionInfo(win, true);`
