### ISSUE TITLE
PDF internal annotations requests: restore original PDF, annotations editor, restricted file visual cue

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#1670]
PDF internal annotations feature requests

1. ability to after annotations have been saved restore the PDF (i.e. remove all annotations) to the bit identical original file (as verified via SHA256 or similar), including restoring the original file created and file modified timestamp file properties. Currently there is no way to restore the exact original PDF file after saving annotations into the PDF. This would be the functional equivalent of deleting the .smx file for the old external annotations feature.

2. Annotations editor of some kind. Overview of all annotations in the document and ways to delete individual annotation items, even when overlapping colors. Useful for cases with overlapping highlight annotation. For example if a whole section has yellow highlight and two words within it also has green highlight there should be an easy way to pick what to remove. Also useful if the user wants to batch edit some feature of the annotations, for example change the color of all light green highlights to dark green. The functional equivalent of some plaintext search/replace actions on the old .smx files.

3. visual cue if the active open PDF file is restricted against annotation. (Background assumption: for PDF files with editing restriction SumatraPDF will not allow saving annotations into the PDF.) Users will when prompted by the cue know that in order to annotate they will have to first have to use other tools to disable the editing restriction and reopen a restriction free copy of that PDF file.

4. Annotation exporter/importer. Ability to export a subset of annotations from one PDF file into another (copy) of the original PDF file. For example with the old .smx we could for the file novel.pdf have one .smx file with annotations on the topic "character developments" and another .smx with annotations on "plot details". Since these were plaintext we could easily collate them into one big .smx and use that to view all annotations at the same time. We could also copy subsets from one to the other .smx files. I request something functionally equivalent for the internal PDF annotations feature.

**Comment by kjk** [comment]
1. too much work

2. right-click for context menu, pick 'Edit Annotations'

3. I don't think there is such thing like editing restrictions

4. too much work

**Comment by nod5** [comment]
> 2. right-click for context menu, pick 'Edit Annotations'

That can currently delete individual highlight items and edit individual highlight but not batch edit.

> 3. I don't think there is such thing like editing restrictions

Acrobat Pro has Document Security feature that allows restricting editing of the document. That can be set such that when later viewing that PDF in Acrobat Pro annotations are disallowed, unless the user removes that setting in Acrobat Pro after providing the correct password. But it seems `SumatraPDF-prerel-13044-64.exe` ignores any such property of the PDF file and saves annotations anyway. Can I from your reply assume that SumatraPDF will continue to ignore that PDF security settings?

General comment: it would be useful if you somewhere specify in detail what features related to PDF internal annotations that you plan to support in SumatraPDF and what will not supported and/or deviated from. For example, will you support all of these: text markup (i.e. highlighting, strikethrough, etcetera), drawing annotations, stamp annotations, text annotations, multimedia annotations, widget annotations?  See https://pspdfkit.com/blog/2018/what-are-annotations/

**Comment by GitHubRulesOK** [comment]
@nod5 

just comments on my part
1 standard work practice, to backup a file and edit a copy
2 Work in progress, but similar to MuPDF external CLI apps needed for batch process
3 Password required to open, (and may be neded to save) but print/commenting restrictions no longer apply
4 Annotations are embeded thus file specific they may not always be in the tail end. the selection set includes files but for example media or xls sheets with macros should be saved not run.

**Comment by nod5** [comment]
@GitHubRulesOK 

> 3 Password required to open, (and may be neded to save) but print/commenting restrictions no longer apply

Do you mean that the latest PDF specification no longer supports restrictions on editing/annotating? (That may well be the case because I have only tested the restriction I described in an older version of Acrobat Pro). Do you have a reference for that?

> 4 Annotations are embeded thus file specific they may not always be in the tail end. the selection set includes files but for example media or xls sheets with macros should be saved not run.

Yes, but given that SumatraPDF can already read, display and save annotations regardless of where in the particular PDF file they are stored it would be possible to also import/export. Once the annotation features in SumatraPDF reaches a more stable state I will examine if I can add something like that to an alternative version. But no use attempting while the official annotation feature development is in flux and without a public roadmap.

**Comment by GitHubRulesOK** [comment]
3) The thing that now calls itself a standard has not changed, it still asked that drm and other obsccura be allowed for the snake oil sellers benefit.
4) there are some open issues around annotations and extraction, and SumatraPDF cannot yet handle all those from MuPDF. nor would I expect it to modify other 3rd party ones, but inevitably (just like I do) others will likely mix and match. It may be easy to batch delete all annotations but keeping those from one set whilst removing another set could be more difficult than of benefit unless they are tied to one type.

I expect users that rely on temporary highlights may need temporary visual bookmarks and that becomes more difficult if they are saving permanent ones at the same time. 

Which comes back to my point of a need for a coloured visual bookmarking app that works in the full release.
Select a word (store it for listing)
color a mark in top right corner
show me a list of say 9 locations
take me there and back again
