### ISSUE TITLE
Crash (Access Violation) in to v3.3.13051 Git-7a8375022 x86 and x86_x64 then try use URL in to eBook page body

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1672]
Crash (Access Violation) in to v3.3.13051 Git-7a8375022 x86 and x86_x64 then try use URL in to eBook page body:

![crash](https://user-images.githubusercontent.com/906886/87168277-e50f5a80-c2d6-11ea-94ae-5eede822185e.png)

Crash reports and dumps, and test file - my build [**v13051_crash.zip**](https://github.com/sumatrapdfreader/sumatrapdf/files/4903836/v13051_crash.zip) , official SumatraPDF pre-release builds are for testing [**SumatraPDF-prerel-13051.zip**](https://github.com/sumatrapdfreader/sumatrapdf/files/4903942/SumatraPDF-prerel-13051.zip) / [**SumatraPDF-prerel-13051-64_crash.zip**](https://github.com/sumatrapdfreader/sumatrapdf/files/4903943/SumatraPDF-prerel-13051-64_crash.zip)

In to v3.3.13044 Git-52cd8c65d this phenomena not exist.

Also if use STDU Viewer 1.6.375.0. hi can't open this file - freeze, then crash.

**Comment by GitHubRulesOK** [comment]
@kjk 
I can confirm odd behaviour, selecting that self reference, no problem in say MuPDF
SumatraPDF instantly dies, no time to write a crash !

**Comment by kjk** [comment]
I hope this fixes the issue.

**Comment by GitHubRulesOK** [comment]
That seems quick I was still binary choping the versions

**Comment by VictorVG** [comment]
@kjk 

Big thanks!
