### ISSUE TITLE
Annotation Defaults

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1675]
[Updated to reflect current 3.3 status]

Currently old settings are ignored

AnnotationDefaults [
	HighlightColor = #ff0000
<strike>	SaveIntoDocument = false</strike>
]

The default color for highlights is currently yellow ~= `HighlightColor = #ffff00`
 or is that `#ffffff00` for full opacity ?

<strike>SaveIntoDocument is perhaps redundant unless true is needed for runtime autosave, However some users like to just add temporary highlights (that can be discarded on closure). The final save warning, is desirable in such cases, but advanced users may also want to optionally switch off that reminder?</strike>

**Comment by GitHubRulesOK** [comment]
@kjk 
I was about to close this but hit a minor wrinkle

Annotation [
HighlightColor = #ff0000
]

Works nicely for highlighting either a line or area and on a previous occasion had found a difference in color when selecting an object such as an image. however I will open a fresh issue for the crash result

**Comment by astroHaoPeng** [comment]
> Any way to set a default `opacity` now?

I found it here [how the color code is parsed](https://github.com/sumatrapdfreader/sumatrapdf/blob/51f7f5029f83d2deaf217d333067212037f155fb/src/utils/ColorUtil.cpp#L90).
Color hex is parsed as `#(alpha)(R)(G)(B)`. 
So, for example, I use `#1e00ff00` for a 30%-opacity green color.

**Comment by GitHubRulesOK** [comment]
@astroHaoPeng
whilst that method may work you get the same effect with #B4FFB4 (try them side by side)

**Comment by astroHaoPeng** [comment]
> @astroHaoPeng whilst that method may work you get the same effect with #B4FFB4 (try them side by side)

Ha, just saw your reply. Yeah, I tried that too, pick a similar color without the alpha channel. 
I still prefer to use opacity because it makes easier to overlap highlights with other colors.
