### ISSUE TITLE
There is a problem about memory leak

### ISSUE THREAD

**Issue by Deteriorator** [sumatrapdfreader/sumatrapdf#1684]
hi, i find a problem about suspected memory leak when i read caspp pdf.
When i turn next page, the memory usage increases. Screenshot are as follows:
now:
![image](https://user-images.githubusercontent.com/31269745/87292035-c9a08b80-c532-11ea-893d-d828d4e6eca5.png)

turn next page:
![image](https://user-images.githubusercontent.com/31269745/87292086-dde48880-c532-11ea-949e-d9cc702ef5e5.png)

I think it's a bug of memory leak, please check it,  thanks.

**Comment by Deteriorator** [comment]
and the memory usage don't recover

**Comment by GitHubRulesOK** [comment]
Can not progress test without file and both SumatraPDF version and OS info

It is natural with graphics intensive rendering for current memory to fluctuate upto 300 MB or more 
and not always drop back to ## until the file is closed.

![image](https://user-images.githubusercontent.com/12754913/87296477-b7a4f580-c4fe-11ea-87c7-0fc43f692e95.png)
![image](https://user-images.githubusercontent.com/12754913/87296688-10748e00-c4ff-11ea-9f36-d4fef88de0d7.png)

**Comment by kjk** [comment]
This is not an evidence of memory leak.

**Comment by Deteriorator** [comment]
> This is not an evidence of memory leak.

![image](https://user-images.githubusercontent.com/31269745/87495429-fe702800-c683-11ea-906b-849df795fc50.png)

Can this picture be taken as evidence?

**Comment by Deteriorator** [comment]
> Can not progress test without file and both SumatraPDF version and OS info
> 
> It is natural with graphics intensive rendering for current memory to fluctuate upto 300 MB or more
> and not always drop back to ## until the file is closed.
> 
> ![image](https://user-images.githubusercontent.com/12754913/87296477-b7a4f580-c4fe-11ea-87c7-0fc43f692e95.png)
> ![image](https://user-images.githubusercontent.com/12754913/87296688-10748e00-c4ff-11ea-9f36-d4fef88de0d7.png)

em, now the memory usage is 1.8GB on computer, i get the screenshot, and the day i submit the issue, the memory usage is up to more than 5GB, But I forgot to take the screenshots. 
the picture is today's screenshot
![image](https://user-images.githubusercontent.com/31269745/87495878-04b2d400-c685-11ea-97c0-0e04cd54985a.png)

**Comment by Deteriorator** [comment]
SumatraPDF version:
![image](https://user-images.githubusercontent.com/31269745/87496063-683d0180-c685-11ea-912c-962a07a3bb7d.png)

OS info
![image](https://user-images.githubusercontent.com/31269745/87496077-70953c80-c685-11ea-8734-10c4252a4ce8.png)

**Comment by GitHubRulesOK** [comment]
Thanks for confirming version as 3.2, there have be a large number of issues raised and fixed since that release. Some of those may  resolve your observation. 
It always helps to test current pre-release situation using a recent daily version if possible. When you see such a high memory usage it also helps to provide details of actions such as zooming or searching and the actual file for testing if that behavior is to be expected or not. Note a test file needs to be under 10 Mb to be included  in a comment, otherwise a valid link would be needed.

**Comment by Deteriorator** [comment]
> Thanks for confirming version as 3.2, there have be a large number of issues raised and fixed since that release. Some of those may resolve your observation.
> It always helps to test the current [pre-release](https://www.sumatrapdfreader.org/prerelease.html) situation using a recent [daily](https://www.sumatrapdfreader.org/dailybuilds.html) version if possible. When you see such a high memory usage it also helps to provide details of actions such as zooming or searching and the actual file for testing here, as to whether that behavior is to be expected or not. Note a test file needs to be under 10 Mb to be included in a comment, otherwise a valid link would be needed.

the pdf document i test:
file link：https://c-t.work/s/3694e5e2406947 or  cowtransfer.com，input passcode in index page：dhgc7u（24 hours effective）

**Comment by GitHubRulesOK** [comment]
@kjk 
Thats a very heavy file by western standards, but not dissimilar to many others. Graphics seem to have caused **excessive memory usage in 3.2 release**, not a leak ? **There appears to be little problem using that file in current builds.**

![image](https://user-images.githubusercontent.com/12754913/87650556-bd424b80-c749-11ea-8173-8e051a0df06f.png)
