### ISSUE TITLE
Zip files prevent opening next/previous document in directory

### ISSUE THREAD

**Issue by lcfarini** [sumatrapdfreader/sumatrapdf#1686]
Sumatra 3.1.2 showed a gray page with an "error loading" message if next document (ctrl+shift+right) reached a zip file which did not contain images. Pressing ctrl+shift+right again moved to the next file, thus the zip file could be skipped.
Sumatra 3.2 instead shows a tooltip-like "error loading" message but the current document continues to be displayed. It is not possible to "skip" the zip file and move to the next displayable document.

**Comment by GitHubRulesOK** [comment]
I think this a duplicate of a previous issue but will take some searching

**Comment by kjk** [comment]
Yes, this should work as well. Thanks for pointing it out.
