### ISSUE TITLE
[feature] The window's close button should close the current tab

### ISSUE THREAD

**Issue by DerpMcDerp** [sumatrapdfreader/sumatrapdf#169]
1. remove the close button on all the tabs
2. make the window's close button close the current tab instead of the current window ("File | Exit" and "Window | Close" should continue to close the current window)
3. There should be a "File | Close Tab Ctrl+W" just above "File | Exit"
4. Closing a tab when there is 1 tab left should exit SumatraPDF rather than showing the about page
5. Closing a tab when the about page is displayed should exit SumatraPDF

This also has the benefit of giving you some protection against accidentally closing multiple tabs (i.e. firefox warns you if you close the window with more than 1 tab in it).

**Comment by kjk** [comment]
Our behavior follows other popular apps that use tabs (chrome, firefox). We won't be changing that.
