### ISSUE TITLE
Misaligned layers in PDF

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#1690]
[This PDF](https://github.com/sumatrapdfreader/sumatrapdf/files/4922453/Asterix.Magazine.08.French.4pg.Excerpt.pdf) (which is a 4 page excerpt from [the original](https://www.asterix.com/wp-content/uploads/2020/05/Magazine_Asterix_Mai_08.pdf)) looks horrible in Sumatra (tested with **3.2** and **prerel-13073** x64). The black 'text'/inking layer (which is actually an image since the text isn't selectable) and underlying flat comic layer aren't being aligned properly for some reason:

![Bug_1](https://user-images.githubusercontent.com/15380332/87495654-88fa5c80-c66f-11ea-9638-e97f3ce4cfe9.png)

Same PDF looks fine in **Sumatra 3.1.2** (so it's a clear regression), Firefox (pdf.js) and ChrEdge x64:

![Bug_2](https://user-images.githubusercontent.com/15380332/87495666-9283c480-c66f-11ea-954c-62e6d1e9d080.png)

**Comment by GitHubRulesOK** [comment]
Inititially looks like the overlay is incorrectly scaled at 80% by MuPDF in the horizontal direction, the image looks like it was 200 x 200 dpi so no obvious reason for that ratio !

**Comment by GitHubRulesOK** [comment]
@kjk 
I guess SumatraPDF can not distinguish if CCITTFaxDecode filter is working correctly or not, so this issue may need to be raised as MuPDF Bug ?

**Comment by kjk** [comment]
Reported as https://bugs.ghostscript.com/show_bug.cgi?id=702565

**Comment by GitHubRulesOK** [comment]
"Curiouser and curiouser!" Cried Alice (she was so much surprised, that for the moment she quite forgot how to speak good English)." 
When we zoom in !
![image](https://user-images.githubusercontent.com/12754913/87602192-75420b00-c6ee-11ea-9c82-4d73c141f2c6.png)

**Comment by SumatraPeter** [comment]
> When we zoom in ! And for me thats 209+% !!!

Same here; How weird!

**Comment by SumatraPeter** [comment]
Fixed? Great! Waiting for latest daily to test...

**Comment by kjk** [comment]
It's already there. 

"daily" is a bit misleading. Every change gets build and uploaded as the latest "daily" build.

It typically takes ~30 min from the time of change to show up as a new daily build (unless there is a compilation error or GitHub has issues).

I've recently added a link to the change on daily build page so that you can see on which checkin exactly is the daily build based.

**Comment by SumatraPeter** [comment]
I think I got confused by the date since the page said "built on 2020-07-16" and it was the 17th here. :)
