### ISSUE TITLE
Download button does not work on new version notification

### ISSUE THREAD

**Issue by andelepeter** [sumatrapdfreader/sumatrapdf#1691]
There is a notofication dialog when a new version of sumatra is available. At least for me, although correctly notified, the download button does not work (nothing happens when pressed) for the preview builds.

**Comment by GitHubRulesOK** [comment]
It usually opens internet explorer on the relevant pre-view download page so you can choose where and how to download and save, it should work with any any default browser such as Edge or others.

**Comment by kjk** [comment]
Yeah, it works for me and all we do is launch web browser so I'm guessing your system association for http:// handlers 

See what happens if you type `start https://google.com` in `cmd.exe` or powershell cmd-line window. Should open a browser with this url. Sumatra does equivalent of that.

**Comment by GitHubRulesOK** [comment]
@kjk several legacy 3.1.2 blockers even if **http://** launches

JavaScript controls will not show (nor action downloads)

Legacy IE users will be left hanging on a blank .html (they need to remove extension manually)
