### ISSUE TITLE
Cannot open ".pdf" and ".epub" files from jumplist

### ISSUE THREAD

**Issue by umeshktangnu** [sumatrapdfreader/sumatrapdf#1695]
Hi! Great app!

Version: 3.2 64-bits on Windows 10 v1909  

Steps:
    Open either a ".pdf" or ".epub" file in Sumatra.
    Check if the opened file appears in jumplist.
    Close the application.
    Try to open aforementioned file from the jumplist
    The file does not open, with "Item you selected is not avaiable" error.

"djvu" files open just fine 
Thanks!

**Comment by GitHubRulesOK** [comment]
I am tempted to close as not an issue within SumatraPDF, Jumplists are a Windows feature.
I don't normally use jump lists, but here I added an epub to SumatraPDF on the taskbar and it opens the file as expected.
The main thing to note is that the jumplist is not the same as what other windows shortcuts expect to use so here is what my test shows, i.e. the file is opened by selected prerelease version (the newer logo on the task bar) but it shows an older logo for my default SumatraPDF e-pub file opener i.e the one shown in "Opens with". Thats a mystery of jump lists they do not behave exactly the same as the default setting.
![image](https://user-images.githubusercontent.com/12754913/87660219-9f2f1800-c756-11ea-8cf0-cd7642f288b7.png)
