### ISSUE TITLE
Text selection is not available for epubs and mobi

### ISSUE THREAD

**Issue by fitdev** [sumatrapdfreader/sumatrapdf#1698]
Using SumatraPDF 3.2 64-bit on Windows 10.

I can only select text (to copy) in `pdf`s. If a file is an `epub` or `mobi`, it is not possible to select any text, yet this feature is hugely useful.

**Comment by GitHubRulesOK** [comment]
Not a problem, in 3.2 just use the  Debug > Toggle Ebook UI
If you are reading an ebook, press R to refresh UI
![image](https://user-images.githubusercontent.com/12754913/87851867-ad1a9f80-c8f4-11ea-9688-230db1416cf1.png)

**Comment by fitdev** [comment]
Oh, thanks a lot, @GitHubRulesOK I was not aware of this functionality as it is well hidden.
