### ISSUE TITLE
feature request: See the filename for images in an archive

### ISSUE THREAD

**Issue by Jolar** [sumatrapdfreader/sumatrapdf#170]
When looking through a collection of images stored in an archive, sometimes it would be very useful to be able to see the filename for the image. Either on the toolbar or an overlay on the image, or maybe a right-click.

**Comment by SumatraPeter** [comment]
An on-demand tooltip comes to mind, like the venerable CDisplay shows on pressing 'i' (though I wish it showed the filename too).

![cdisplay_tooltip](https://cloud.githubusercontent.com/assets/15380332/11038990/a8975a8a-872b-11e5-8c53-c1e0a064a47e.png)

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
The OP request is addressed by recent updates tat meet your other long standing request :-) thus in theory this one could be closed ? However you may need to raise a new issue  to cover "image properties" then this one becomes "old duplicate"

**Comment by SumatraPeter** [comment]
Yup, the major requirement has been addressed with #543 so @kjk this can be closed IMO. A separate issue can be opened regarding improvements to be made specifically to the 'i' info tooltip (for example displaying size of page/image, zoom level, info. for both pages in case of Facing/Book View modes etc.)
