### ISSUE TITLE
Feature request: add an option in the UI to set gDisableDocumentRestrictions to true

### ISSUE THREAD

**Issue by Lucas-C** [sumatrapdfreader/sumatrapdf#1700]
Currently, in Sumatra PDF source code, a [`DISABLE_DOCUMENT_RESTRICTIONS` C macro constant](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/SumatraConfig.cpp#L81) allows to ignore a PDF protection to copy content, which displays [this message](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/Selection.cpp#L306):

> Copying text was denied (copying as image only)

This permission mechanism has existed for a long time in Sumatra, but this macro constant was introduced only [2 weeks ago](https://github.com/sumatrapdfreader/sumatrapdf/commit/82ceb5cf38bbf3e95288c17393ec9fbda1f83c99#diff-b4609ccff8aa00369e804599fe51dda3R81).

Technically, while removing this protection was beforehand a matter of patching the C source code and recompiling the software, it is now even simpler: one only needs to define `DISABLE_DOCUMENT_RESTRICTIONS` and recompile Sumatra PDF Reader.

Would it be conceivable to go one step further and add a control in the UI, or just an entry in `SumatraPDF-settings.txt` configuration file, in order to override this `gDisableDocumentRestrictions` global variable at run time ?

**Comment by Lucas-C** [comment]
As workaround, in the meantime, I went with [modifying the PDF file itself](https://superuser.com/questions/179064/how-to-remove-security-from-a-pdf-file).

**Comment by GitHubRulesOK** [comment]
@Lucas-C 
Previously it was necessary at compile time to flag up an equivalent setting so as to DISABLE_DOCUMENT_RESTRICTIONS
Recent pre-release builds do that using this run time flag by default as it is essential to allow annotations.

Opening passwords are still respected and also needed to save annotations in those files, but its easy for user to select remember this password when opening those files.

**Comment by kjk** [comment]
It's a default since https://github.com/sumatrapdfreader/sumatrapdf/commit/8d7f51407f5b20e830ec8593f17926bc59bae006 so this issue seems to be addressed.
