### ISSUE TITLE
Annotation misplaced in continuous or book modes

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1705]
Common problem as highlighted by NOD5 with old smx annotation, persists in new.

When two pages are on screen and the division between them is showing (aka continuous mode)
When the boundary is below half height the page number is correctly showing the upper page.
Placing a highlight in the lower part will incorrectly assign it to upper page number !
Thus it will be placed on wrong page.

P.S. Also can happen when two pages are side by side i.e. facing or book modes.
![image](https://user-images.githubusercontent.com/12754913/88122278-108c2200-cbc0-11ea-8e9c-a9e23fbfc710.png)

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/fc0b656b20796e4bad60ff43ec85aa6be0367060
