### ISSUE TITLE
Need Search Feature for ebooks(epub, mobi) in non-fixed-page ui mode

### ISSUE THREAD

**Issue by Rajeshtims** [sumatrapdfreader/sumatrapdf#1707]
String search works in fixed-page-ui mode for ebooks(epub, mobi), but there is no file search option in non-fixed page ui mode.

**Comment by GitHubRulesOK** [comment]
Closing as Duplicate of numerous other requests to search the non fixed target.
Cross Ref to #199 #225 #239 #268 #414 #639 #779 #1439 #1653 #1698 all consolidated into #284
