### ISSUE TITLE
SumatraPDF as an alternative to the WinForms control in relation to the Acrobat Reader

### ISSUE THREAD

**Issue by ch0mik** [sumatrapdfreader/sumatrapdf#171]
I did a mini App for PDF generation from XML / XSLT based on the FOP for .net. PDF generated in the  Acrobat Reader Control in WinForms and it was ok (had a print preview, etc). Unfortunately, the new version of Acrobat Reader, DC does not support this (can not load a PDF and print) - I would like to become independent of what is installed on the computer (eg. Whether it is or is not Acrobat Reader) - Is SumatraPDF is available for deposition WinForms as PdfViewer?

**Comment by kjk** [comment]
No, we don't support that.

**Comment by marcoscmonteiro** [comment]
> I did a mini App for PDF generation from XML / XSLT based on the FOP for .net. PDF generated in the Acrobat Reader Control in WinForms and it was ok (had a print preview, etc). Unfortunately, the new version of Acrobat Reader, DC does not support this (can not load a PDF and print) - I would like to become independent of what is installed on the computer (eg. Whether it is or is not Acrobat Reader) - Is SumatraPDF is available for deposition WinForms as PdfViewer?

Now you can do this with a modified version of sumatrapdf: https://www.nuget.org/packages/SumatraPDFControl/
