### ISSUE TITLE
Regression in 3.2 saving folder or zip folder containing .webp as PDF

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1710]
I think it may have been mentiond as a side issue, but cant find an open issue.

In version 3.1.2 either a Comic Book archive (even one named as comic.zip)
OR a folder of images could be saved as PDF.

In Version 3.2 and current Pre-release simple Comic Books will save as PDF,
but some **comic.zip OR folders with images** will not.

![image](https://user-images.githubusercontent.com/12754913/88393817-40047f80-cdb6-11ea-97d1-30ceca4ea4a5.png)

**Comment by SumatraPeter** [comment]
Didn't test the latest pre-release, but 3.2 works fine here with RAR, CBR, CBZ, ZIP and folder of images to PDF.

**Comment by SumatraPeter** [comment]
Both 3.2-x64 and prerel-13085-x64 are perfectly able to convert .RAR (RAR4 and RAR5), .CBR  (RAR4 and RAR5), .ZIP, .CBZ and folder of images to PDF. Check both versions again and if problem persists but your HDD is fine, has sufficient free space etc. then attach comic.zip and I'll take a look.

P.S. Interesting thing I noted while testing - .RAR (RAR4 and RAR5), .CBR  (RAR4 and RAR5), .ZIP and .CBZ resulted in 6 bit-identical PDFs, but PDF from folder with same images was not a match (slightly bigger too). However all 7 when extracted resulted in JPGs that were bit-identical to the originals, so at least the embedded images aren't affected. Not sure why (@kjk?), but guess the PDF structure is slightly different for folder > PDF and archive > PDF.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
I was confused that 3.1.2 worked but 3.2+ did not
(any existing readable archive is no problem in 3.2)
It is only a fresh zip or folder that caused problems
Thanks at your insistance I retested, but ensured all files were valid in 3.2, and there seems to be the problem!

There was a rogue file in one folder of images that is now a problem for 3.1.2 (odd since I thought that folder had saved, but have no older test files to check contents, my bad)
Removing the bad file, that folder now saves as PDF in both 3.1.2 and 3.2

In the second folder tested there were related xml metadata files that 3.1.2 simply ignored. 
It is similar with the zip file there is comic book metadata that 3.1.2 ignored for the save as PDF

I now see that CBZ with metadata does not save as PDF

This file saves as PDF in 3.1.2 but not 3.2
[Illustrated_Book_of_Bad_Arguments.cbz.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4975455/Illustrated_Book_of_Bad_Arguments.cbz.zip)


So the issue is now:- **3.2 does not ignore extraneous files in a folder or CBX when saving as PDF** but 3.1.2 ignored them

Which now reminds me it is potentially related to some other folder issue where extra files are a problem

**Comment by SumatraPeter** [comment]
I tested only with folders and archives containing valid/supported JPGs (and ComicInfo.XMLs which were ignored), and Sumatra had no problems with these. Can confirm that Illustrated_Book_of_Bad_Arguments.cbz.zip does indeed fail to Save as PDF in 3.2.

> Which now reminds me it is potentially related to some other folder issue where extra files are a problem

I guess you're referring to #1449 and #1686 where too 3.2 seems worse than 3.1.2?

**Comment by GitHubRulesOK** [comment]
closing as function has been "depreciated" in 3.5 release
