### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#1717]
https://gist.github.com/775405984/96cdca7967d8e8013700a8d55f6754c9

**Comment by kjk** [comment]
Unfortunately the symbols failed to download so the callstack doesn't provide any useful information.

```
HttpGet: url: 'https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/daily/SumatraPDF-prerel-13104-64.pdb.lzsa'
HttpGet: InternetReadFile fail
```

There's no way to make progress here.
