### ISSUE TITLE
Sumatra no longer shows thumbnail for CBZ files

### ISSUE THREAD

**Issue by flaviojcojr** [sumatrapdfreader/sumatrapdf#1718]
Until recently when associating the CBZ format to Sumatra PDF, thumbnails appeared automatically in Windows 10 1909. Now only PDF shows thumbnails.

**Comment by GitHubRulesOK** [comment]
Need more info as SumatraPDF "normally" does not show Thumbnails for CBZ, its a common complaint it needs  a dedicated build by the user.
So either you had an "special" build before and now are usind a standard one OR another 3rd party previewer was producing those thumbnails for you ?

**Comment by flaviojcojr** [comment]
I got it, thanks.
