### ISSUE TITLE
How to disable all shortcuts?

### ISSUE THREAD

**Issue by yuankk8** [sumatrapdfreader/sumatrapdf#1719]
Is it possible that add a option to disable shortcuts?

**Comment by kjk** [comment]
What shortcuts are you referring to?

**Comment by yuankk8** [comment]
Thank u for your reply. Keyboard shortcuts,I worry about pressing some wrong keys.

**Comment by kjk** [comment]
That's not possible unless you make changes to the code.

**Comment by GitHubRulesOK** [comment]
@yuankk8 
for posible solutions see here where another user had problems always brushing <kbd>F8</kbd>
you can edit the registry (not recommended) or use MS Powertoys or AHK
https://forum.sumatrapdfreader.org/t/how-to-prevent-the-toolbar-and-menu-from-being-hidden/2473
