### ISSUE TITLE
[MuPDF] Error loading nearly 3GB file

### ISSUE THREAD

**Issue by zzzzz** [sumatrapdfreader/sumatrapdf#172]
Problematic file:
The Walking Dead Compendium One.pdf
Size: 2,85 GB (bytes: 3 069 208 283)
Pages: 1091
PDF version 1.6, no DRM.
Error: "Error loading" and path to file

Doesn't work in SumatraPDF 3, MuPDF 1.7
Works in PDFXChange Viewer 2.5

For obvious reasons can't upload problematic file.

**Comment by Horridge** [comment]
Experiencing the same issue on a PDF with following file size; 2.93 GB (3,147,159,886 bytes)

Opens as expected within Adobe Reader, but 'Error loading' within Sumatra PDF v3.1.2 x64

**Comment by GitHubRulesOK** [comment]
@kjk historic potentially superseeded by those issues where files **have** been supplied

**Comment by kjk** [comment]
Can't investigate without a test file. Confidential files can be sent to kkowalczyk@gmail.com
