### ISSUE TITLE
Show scrollbars option aren't saving the preference

### ISSUE THREAD

**Issue by Shideravan** [sumatrapdfreader/sumatrapdf#1720]
**Version**
66517e5 (2020-07-28)

**Issue**
I loved that now we can remove the scrollbars when zoon-in, but unfortunatelly the feature seems incomplete and aren't saving the preferences. Is bad to have to re-uncheck "Show scrollbars" everytime.

**Comment by godey4me** [comment]
Can we have a fix for this? I have  `HideScrollbars = true` in the Advanced Options but I have to use the menu to hide the scroll bars whenever I start a new instance. It appears the option doesn't stick.
Thanks
