### ISSUE TITLE
Loading Rotated Documents without Rotation

### ISSUE THREAD

**Issue by samuel-greenberg** [sumatrapdfreader/sumatrapdf#1722]
When a document is rotated and then saved (save-as), re-opening the document will revert to the original un-rotated version of the document.

Case 1:

I received a scan upside-down so I used rotate to make the document right side up. When using save-as and re-opening the document under its new filename the document reverts to the original upside down state.

Case 2:

Saving a document (either save or save-as) after a rotation and then loading it in another pdf viewer (chrome pdf viewer) yields the original (un-rotated) document.

**Comment by GitHubRulesOK** [comment]
That is correct behaviour (same as save as in Acrobat reader), only an editor can alter page rotation when saving. SumatraPDF only rotates all pages not seperate ones.
SumatraPDF when told to" remember per document view settings" can open the same whole file rotated as it was when closed. However, that will not affect any other viewer.
For simple permanent rotations, I call the first page using ExternalViewer commands make changes there and can see the rotation results instantly within SumatraPDF, before sending it on to other users.

**Comment by GitHubRulesOK** [comment]
I have described an "addins" script using QPDF that can permanently rotate a page or optionally pages with some limitations as described in forum https://forum.sumatrapdfreader.org/t/please-add-tool-for-rotating-pages-permanently/411/5

**Comment by kjk** [comment]
Sumatra doesn't persist rotation file back into the file.
