### ISSUE TITLE
Show error when saving annotations fail; properly set incremental saving flag

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1723]
You may have seen a crash referencing this file when testing behaviour in a less stable pre release.
The reason was double checking the files odd behaviour. Just in case it helps I think this was related report [sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/5024702/sumatrapdfcrash.zip)

So in latest pre-releases this file when simply opened and closed says it needs to save changes, however in SumatraPDF there is no valid annotation visible? not saving annotations it repeats on next closing ! Possibly corrupted file by not saving something deleted but the message is nevertheless unexpected.
[BlankA4x2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5024599/BlankA4x2.pdf)

OK looking closer in other viewer/editors reports corrupt xref info
It appears MuPDF is unable to save after atempting fixing and seeing the false date properties that file is not a good example to be using, It will work in Adobe reader and can be saved by other editors such that the save annotation message is not triggered when re-used by SumatraPDF

If you consider the corruption was not introduced by Mu(Sumatra)PDF then close as a bad file for now ?

**Comment by GitHubRulesOK** [comment]
@kjk 
behaviour tested against recent build is different

I download and open above potentially not correct PDF,
 I add a carat
 I close the tab and correctly am told the file needs saving 
I give the filename as existing but add " with carat"
The tab closes as expected but the file is nowhere to be found

**Comment by kjk** [comment]
Fails saving with `Pdf save of 'C:\Users\kjk\Downloads\bug1723-BlankA4x2-with-caret.pdf' failed with 'Can't do incremental writes on a repaired file'`

Need to:
* notify the user when saving fails
* disable incremental saving option for repaired files (needs to detect that or just re-try saving if fails)

The code is in `EnginePdfSaveUpdated`.
