### ISSUE TITLE
Undocumented shortcut

### ISSUE THREAD

**Issue by aaronshenhao** [sumatrapdfreader/sumatrapdf#1726]
I'm using Sumatra on Windows 10. I discovered by accident that `Ctrl + L` brings you into presentation mode, which is pretty handy. In the menu, the corresponding shortcut listed as `F5`, but `Ctrl + L` is not listed. I wonder how many other shortcuts there are.

**Comment by GitHubRulesOK** [comment]
it is [documented](https://www.sumatrapdfreader.org/manual.html) as 

< Ctrl > + L or F5 | toggle presentation mode (minimal full screen mode)
-- | --

So am closing this issue, 
However there certainly are others so try hitting just <kbd>F</kbd> = <kbd>F11</kbd>
or  (powerpoint shortcut) <kbd>B</kbd> whilst in presentation mode = <kbd>.</kbd>
