### ISSUE TITLE
Crash report for v3.3.13104 64 bit pre-release

### ISSUE THREAD

**Issue by JohnyZlo** [sumatrapdfreader/sumatrapdf#1729]
link to the [gist in the bug report](https://gist.github.com/JohnyZlo/d3d1a0cba588d593480219be8a8e5195)

**Comment by kjk** [comment]
This is a crash due to mismatched gAllowAllocaFailure which should already be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/cac39520a8811d7cac3e9b2bccecdccc1b9b6804

**Comment by GitHubRulesOK** [comment]
@kjk 
**gist says**
BuiltOn: 2020-07-29 Type: dll Ver: 3.3.13104 pre-release 64-bit

cac3952 says
fix mismatched gAllowAllocFailure accounting (fixes #1693) 
committed on 15 Jul 

to me suggests build / fix did not stop this event

**Comment by kjk** [comment]
Good point. I think it's HttpGet() done in background that messed up the gAllowAllocFailure refcount. This should fix it.

**Comment by GitHubRulesOK** [comment]
@kjk 
I note the indication that additional lines were rejected on loading, which suggests the settings file may not have be a standard Master branch one ?

**Comment by GitHubRulesOK** [comment]
@kjk 
even more puzzling that is an old invalid settings file rather than a valid one ??
