### ISSUE TITLE
Bookmarks in index of pdf invisible

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [sumatrapdfreader/sumatrapdf#173]
The pdf in question: http://ge.tt/7wtYQsE2/v/0?c

The index of the document contains a number of entries which are bookmarked to jump to that specific section of the book. None of the index entries show up. 

Screenshot of the problem: http://ge.tt/7wtYQsE2/v/2?c
Screenshot of what it's supposed to look like: http://ge.tt/7wtYQsE2/v/3?c

They show up in Adobe Acrobat XI Pro and Reader for Windows 8.

I encountered the problem on SumatraPDF v3.0 full installation and on the SumatraPDF prerelease built on 2015-03-23 (portable version) on Windows 8 64-bit.

If anyone needs additional details, feel free to mail me at abhijeet.krishnan@gmail.com

**Comment by kjk** [comment]
Confirmed it happens. The bounding box of the link is there but link text is not displayed (either a problem with font color or missing font).

**Comment by GitHubRulesOK** [comment]
@kjk another where a commit appears to have previously been made

**Comment by kjk** [comment]
Test file is no longer available. Please re-test with latest build https://www.sumatrapdfreader.org/dailybuilds.html. If still happens, please provide a test file.
