### ISSUE TITLE
Unable to select/copy text in epub files

### ISSUE THREAD

**Issue by taseikyo** [sumatrapdfreader/sumatrapdf#1731]
Windows 10, SumatraPDF 3.2 64-bit

The shortcut `<Ctrl> + Left Mouse` doesn't work in epub files :(
![select](https://user-images.githubusercontent.com/23132915/90367926-e08b4e00-e09b-11ea-9b0d-290534494aff.png)

**Comment by SumatraPeter** [comment]
Wish people would search a bit before opening issues...

Duplicate of #284 via #1456.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter  agreed duplicate of many similar
