### ISSUE TITLE
Single Item in Favorites Does Not Allow Navigation

### ISSUE THREAD

**Issue by ss-reposit** [sumatrapdfreader/sumatrapdf#1733]
1: Add page to favorites
2: Scroll down to next page
3: Go to favorites bar and click on said page - will not navigate you to that page

Seems to only be a problem when a single item is in the favorites bar, adding 2 pages works as intended

**Comment by SumatraPeter** [comment]
@kjk; Looks like this may need a similar fix to the one you implemented for #1716 (https://github.com/sumatrapdfreader/sumatrapdf/commit/9f2b9d7d30dd18f8d19849e8627c47682086e4fa).
