### ISSUE TITLE
Set annotation color defaults

### ISSUE THREAD

**Issue by bertgoz** [sumatrapdfreader/sumatrapdf#1734]
Hi, I am using the pre-release 3.3. version with supports the new annotations feature. It would be great if there was a way to set the default color for each annotation type instead of having to manually change it each time.

**Comment by kjk** [comment]
We have default color for Text annotation. Need to add more, I guess.

**Comment by GitHubRulesOK** [comment]
Closing as recent enhancements have covered the OP basic requirements, so this issue would otherwise be open never ended 
For any new specific requests I suggest they be raised on a case by case basis.
```
Annotations [
	HighlightColor = #ffff00
	UnderlineColor = #00ff00
	SquigglyColor = #ff00ff
	StrikeOutColor = #000000
	FreeTextColor = blue
	FreeTextSize = 12
	FreeTextBorderWidth = 0
	TextIconColor = #ffff00
	TextIconType = comment
	DefaultAuthor = none
]
```
