### ISSUE TITLE
Sumatra doesn't to open signed document

### ISSUE THREAD

**Issue by tih2010** [sumatrapdfreader/sumatrapdf#1735]
Not much to explain here. Just try to open the attached document with SumatraPdf 3.2 and you will see.

[go-digital_Autorisierungsantrag.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5094397/go-digital_Autorisierungsantrag.pdf)

**Comment by GitHubRulesOK** [comment]
Well 
Edge says the file is a borked PDF
Acrobat PDF previewer shows exactly the same as SumatraPDF e.g. its not a PDF it is an XFA pretending to be a PDF

**Comment by kjk** [comment]
Sumatra doesn't support XFA documents and won't unless mupdf adds support for it.
Same as #27
