### ISSUE TITLE
Crash report from forum user Aliaksandr 

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1737]
Description was modifying bookmarks

"  crash is shown when I removed items of bookmark
![image](https://user-images.githubusercontent.com/12754913/90824814-e26d3f80-e32f-11ea-942f-e7a6faa61ea5.png)

 if I click on button two times in a row then program is crash. "
![image](https://user-images.githubusercontent.com/12754913/90824913-0b8dd000-e330-11ea-91a8-12e262db138d.png)

[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/5099219/sumatrapdfcrash.zip)

**Comment by SumatraPeter** [comment]
Here's a [YT video](https://www.youtube.com/watch?v=R9M8DL8S91Y) submitted by the same user.

**Comment by kjk** [comment]
The crash seems to be debug crash detecting there is no treectrl selection, but visually it shows in the screenshot:
```
void TocEditorWindow::RemoveItem() {
    TreeItem* sel = treeCtrl->GetSelection();
    CrashIf(!sel);   <---- crash
    TocItem* ti = (TocItem*)sel;
    RemoveTocItem(ti, true);
}
```

**Comment by GitHubRulesOK** [comment]
@kjk 
there is no means to follow this issue up with unregistered user, so can  you consider if keep as an edge case or potentially addressed by treectrl changes

**Comment by kjk** [comment]
This functionality will not ship so it's a bit moot.
