### ISSUE TITLE
Apparent difference in 3.1+ behaviour with Esc compared to 3.0 or 2.xx

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1741]
Odd it has not been raised before but testing for forum issue 
https://forum.sumatrapdfreader.org/t/esc-button-in-presentation-mode-esc/3307
it seems from my experience that 3.1+ (including current) behaves differently in some cases when using escape

In 3.0 it required both an ESC to exit presentation mode then an additional ESC to Exit SumatraPDF
in 3.1+ if Esc to Exit is active then using esc ONCE from presentation mode will also exit sumatrapdf

**Comment by GitHubRulesOK** [comment]
@kjk 
Testing this difference across versions and calling methods I am tempted to suggest closure as

a) Historic
b) When esc to exit is set true it seems to work in recent versions correctly. 
I.e. on pressing escape the session is closed **with the proviso that when using a new window each one needs to be escaped independantly**

There is still the OP suggestion that it is not working for them as expected, but I cannot replicate with Total Commander and supect there is more than one setting file involved.

**Comment by GitHubRulesOK** [comment]
@kjk 
This issue seems to be more related to the manual definition


ESC | exit full screen or presentation mode
-- | --


and that appears to have changed around version 3.1 to now be overriden by EscToExit?

**Comment by kjk** [comment]
Not sure what to do. It seems that people complain about both behaviors.

**Comment by GitHubRulesOK** [comment]
@kjk 
I suggested that the -esc-to-exit or settings.txt value=true should take precedence over the secondary usage to exit fullscreen etc.

thus its Either / OR NOT AND 
the residual issue is thus the manual should be clearer
```
ESC = exit full screen or presentation mode **(OR esc to exit when set true)**
```

**Comment by kjk** [comment]
After some thought, customizing `EscToExit` is a niche thing. Both behavior are acceptable.

I'm not going to complicate docs with detailed explanation on how `EscToExit` changes standard behavior.

https://www.sumatrapdfreader.org/settings/settings3-3 says "if true, Esc key closes SumatraPDF" and that's exactly what we do
