### ISSUE TITLE
Saving .vbkm does not include forms data

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1743]
Again raised by a forum request
The OP wanted a means to freeze form field entries such as to be non changable, which can be achieved by print to pdf as printing is image only.
Saving a vbkm to pdf preserves much vector info but currently discards bookmarks, so the vbkm is still needed for those outputs.

Testing a populated sample entry when saving to pdf the non field data is preserved as searchable and the file is much smaller but the field data appears to be lost rather than flattened.
[sumatra vbkm save.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/5144446/sumatra.vbkm.save.zip)

**Comment by kjk** [comment]
vbkm is no longer supported
