### ISSUE TITLE
Lost tabs when Windows restarts

### ISSUE THREAD

**Issue by jotaf98** [sumatrapdfreader/sumatrapdf#1745]
This has been a problem for a long time, but as Windows 10 forces more updates, it starts to result in frequent loss of data.

Steps to reproduce:
1. Ensure RestoreSession=true and RememberOpenedFiles=true.
2. Open about 3 files into tabs.
3. Restart Windows.
4. Open SumatraPDF. Tabs are gone.

Any way to solve this? Suggestion: periodically save the list of open tabs (e.g. schedule a timer to save a few seconds after a new file is open, in case many are open at once).

**Comment by GitHubRulesOK** [comment]
You need to be using pre-release (not 3.2) so as to get latest saving of settings file during tab changes so less prone to total loss, but no basic application can guard against lost memory unless hardned by continuous dual back-ups.
Thus if I make lots of changes or edits in any application I save frequently and make copies, but that can still be frustrated if I forget or the computer shuts down unexpectedly.

**Comment by jotaf98** [comment]
Thanks for the quick solution! I'll try the pre-release.

So if I understand correctly, it saves on tab changes (such as opening a file)? That should take care of it, even on unexpected shutdowns.

Outside of tab changes, the only unsaved data should be the view position, but that changes extremely frequently so would require many write operations, and also (in my opinion) it's not as important as remembering which files are open (which is a problem for people who have many PDFs on disk).

**Comment by jotaf98** [comment]
Just tested the pre-release by going through the steps above. Works like a charm! Thank you!

**Comment by GitHubRulesOK** [comment]
I need to revisit my personal batch file for hardening saving settings as it basically backs-up the settings on closure then checked for a legitimate file ending on next startup, then using a fall back from penultimate session if not happy, However that test needs to be updated/bettered to check for valid session history rather than simply a basic file ending.

**Comment by jotaf98** [comment]
Yes I guess there may be 2 sources of corruption: 1) unfinished write due to crash or badly-timed shutdown, 2) silent yet bad write that doesn't crash the application.

Case 1 may happen due to a number of things: internally-inconsistent state or even the OS / forced shutdown. But since in all cases the write is not finished, an atomic replace strategy after writing (like what I described above) would guard against all failure modes.

I think that Case 2 is a lot less likely, it would take a subtle bug in the serialization code, which should be pretty much bug-free at this point.
