### ISSUE TITLE
Is there some info on running golang files withe the (official) build in Visual Studio ?

### ISSUE THREAD

**Issue by zb-z** [sumatrapdfreader/sumatrapdf#1746]
I was just wondering since I see that gen_settingsstructs.py has been removed and rewritten for golang which is not "native" in VS while Python is (VS happily mixes cpp and py projects and knows all paths) => meaning that a build from VS definitely can't run .go without additional setup.

The reason I noticed is that I kept a link to gen_settingsstructs.py (the sole "documentation" for SumatraPDF-settings.txt) and now I see that it's gone.

**Comment by kjk** [comment]
You must have go installed. Then run `doit.bat -gen-structs` from `cmd.exe` or `powershell`.
I don't run it from Visual Studio.
