### ISSUE TITLE
[Feature request] Separate Highlights and keep them in SumatraPDF-settings.txt, like Favorites []

### ISSUE THREAD

**Issue by zb-z** [sumatrapdfreader/sumatrapdf#1749]
They are very different by nature and will probably get 99% usage which also means being in need of a separate KBD shortcut. That will also allow them to be feature complete and included in a release much sooner.

Freestanding annotations for example will need many additional params and ways to set them (size, text inside font/size for text, dragging to adjust etc. etc. => very long development process).

The data needed for a highlight definition is smaller then for a "favorite" and can be made very compact (to reduce the pressure on -settings.txt) like page/line/char start,end (161/19:31, 161/12:63) <-- regex parsable, plus color and opacity which is two numbers (or a short name and a number) and possibly a flag for inverted text (say a Navy is pointless unless you can have a white text).

The set of (reasonably usable) colors for highlights is also very different than for frames for example (rectangle, "circle" (oval in reality), callout (rect/oval with "stem" pointing at text or pic, "line" needs pointing and horiz part) etc. etc.).

Default colors+opacity for highlights should also be in -settings.txt and it would be best to make them flexible, say 4 with hard-coded names (Yellow, Aqua, Lime, Fuchsia) + up to 12 with names directly copied from config to UI (nothing fancy, no Unicode, plain text) with reasonable defaults provided for say 6.

If you are linking PCRE (or any regex lib even std::regex) that can be made very compact as well ( say  (\w{1,16})\s+=\s+#([0-9a-fA-F]{6}),(\d{2}) <-- groups 1,2,3 ex.  Aqua = #00FFFF,62)

**Comment by GitHubRulesOK** [comment]
In the past highlights were separate and stored in two different but mutually useful ways.
They were temporarily stored in a text file for easy editing and worked with multiple formats such as epub and chm then could be flushed to ta pdf as and when wanted
That system although limited had highlights compatible with other PDF annotators.

So in the current round those highlights are still supported for reading but no longer for writing.

The current method is to for PDF only write highlights temporarily in memory (similar to before) but with an editor to adjust contents to 16 named colours or opacity and save to the PDF (much as before). This is comparable to the way its done in many PDF editors thus there is no longer a  need to add them to any text file. Any problems that bloating or crashing settings could wipe out all the highlights in one go is avoided.

**Comment by kjk** [comment]
no plans to implement that
