### ISSUE TITLE
CHM file with Chinese paths not opening

### ISSUE THREAD

**Issue by tomwenseleers** [sumatrapdfreader/sumatrapdf#175]
I would like to open the .CHM file available at
http://www.dahuasecurity.com/download/General_PlaySDK_Eng_Windows64_IS_V3.35.1.R.140719.zip
In subdirectory /Manual (PLAYSDK.htm), which apparently has Chinese subdirectory names.
It doesn't open though in sumatrapdf and just says "Error loading...". With CHMViewer I was able to extract the file to .html OK though, but the issue I think is related to the presence of Chinese subdirectory names. Any thoughts?

**Comment by GitHubRulesOK** [comment]
@kjk there are still issues with chm internal security blocking by windows, however in this case a commit was generated , no feedback to suggest it did not work, further historic improvements in UTF-8 paths should have also helped. The file requires registration to download from this page https://www.dahuasecurity.com/support/downloadCenter/softwares?child=3&page=2 so have not tested it personally.

**Comment by kjk** [comment]
Test file no longer available. Let's consider this fixed.
