### ISSUE TITLE
Line and line-like Annotations can't be edited/created

### ISSUE THREAD

**Issue by DhruvaSambrani** [sumatrapdfreader/sumatrapdf#1754]
# Env
OS: Windows 10 2004
Sumatra Version: prerelease - build 13112

# Expected behavior:
1. Line annotation should be editable to change the location and orientation of the annotated line.
2. Polygon/polyline should work, allowing user to create the required polygon/polyline.

# Actual behavior
1. Line is generated beginning at cursor and ending SE of start
2. Nothing happens.

# Other notes
I searched for other issues like this, but couldn't find any. I may also be missing some steps to create/edit the annotations.
Both these annotations seem like they need multiple points to be defined before they can be drawn. Is this an issue?

**Comment by GitHubRulesOK** [comment]
Not an issue they will be removed in next pre-release e.g. I cant see them in 3.3.13135
they are temporarily removed as too raw for current use and people like me complain they are not usable 🙂
