### ISSUE TITLE
[Feature Request] Search online option

### ISSUE THREAD

**Issue by DhruvaSambrani** [sumatrapdfreader/sumatrapdf#1756]
I work a lot with academic papers which have certain phrases which I need to search online. It isn't much of a hassle to simply copy and paste, but I'd really love it if I could select text and do `f9` or something like that to search the selected text online. I suppose this should be straightforward to implement. In settings, have a `SearchUrl` and `BrowserPath` which allows the user to customize the browser and the url, with the query parameter being replaced with the url-encoded selected text.

An example of `SearchUrl` would be `https://www.google.com/search?q=%s`, where %s is replaced with the query.

**Comment by DhruvaSambrani** [comment]
I just realized #1280 is this.
Closing in favor of that

**Comment by GitHubRulesOK** [comment]
You could easily cut and paste the vbs solution you posibly followed from https://forum.sumatrapdfreader.org/t/advanced-tips-pass-selection-to-another-app-e-g-web-search/2700

And there are also more powerfull 3rd party options Search for "QTranslate" not Open Source but free from QuestSoft (unclear if the are the Banking software house, and no idea if they are aggregating any searches etc)
