### ISSUE TITLE
[Feature Request] Use cmd Line to print a page based on the page label

### ISSUE THREAD

**Issue by Shragel** [sumatrapdfreader/sumatrapdf#176]
Have an option when printing from the cmd line to allow for page labels Printing.

http://forums.fofou.org/sumatrapdf/topic?id=3184670

**Comment by Shragel** [comment]
Didn't receive any answer on this. Is this something we might see added?

**Comment by kjk** [comment]
No one is working on this feature.

**Comment by Shragel** [comment]
Any hope you will do it?

 

Sincerely,

Joel Lebovits

Joel Lebovits Computers, Inc.

President

 

T. 718-305-6762

F. 718-305-6763

E. Joel@JLComputersInc.com

**Comment by kjk** [comment]
Hope springs eternal but we never make promises.

**Comment by kjk** [comment]
We don't have plans to work on that.
