### ISSUE TITLE
Can you just use the print function? Is independent DLL file, and then I call, can this be implemented? How to achieve it? Can you help me? Thank you very much!!

### ISSUE THREAD

**Issue by wangpai1998** [sumatrapdfreader/sumatrapdf#1760]
Can you just use the print function? Is independent DLL file, and then I call, can this be implemented? How to achieve it? Can you help me? Thank you very much!!

**Comment by wangpai1998** [comment]
Can it be separated? I really need this. Thank you very much if you can

**Comment by GitHubRulesOK** [comment]
SumatraPDF is a viewer, not print utility, however it will accept CLI to print. see https://www.sumatrapdfreader.org/docs/Command-line-arguments.html

Each new version may add more options, so there are newer options in 3.2 (not available in 3.0) but for spoolsize we have covered that issue as a seperate item.

**Comment by wangpai1998** [comment]
Can you add an option to print low-quality documents, and then those parameters are available? Some of the parameters before 3.0 don't work, and those of 3.2 work. I mean, can you add an option to print small files? When entering the printer, the file size is very small

**Comment by GitHubRulesOK** [comment]
I am not the developer but after 3.0 the developers decided that there were too many problems supporting different print methods so fixed on just one which is affected by the viewing library output.
There are many dedicated PDF printer applications that will produce much better results and are easier to configure to print. The code in SumatraPDF is written by the team that write GhostScript which has hundreds of variables for printing.

**Comment by kjk** [comment]
Sorry, but if you want to use Sumatra code for your own needs, you have to figure things out yourself.
