### ISSUE TITLE
Issues compiling revision 12,138 on visual studio community 16.6.5

### ISSUE THREAD

**Issue by ianamk** [sumatrapdfreader/sumatrapdf#1761]
I'm trying to do a vanilla compile of current sumatrapdf code with Visual Studio Community 16.6.5 and am getting a 500+ compile errors. Most of them with the information that 'atomic' is not a member of std:: and an unknown type

>Severity	Code	Description	Project	File	Line	Suppression State
Error	C2039	'atomic': is not a member of 'std' (compiling source file ..\src\EbookDoc.cpp)	engines	..\sumatrapdf-master\src\utils\BaseUtil.h	600	
>Severity	Code	Description	Project	File	Line	Suppression State
Error	C2062	type 'unknown-type' unexpected (compiling source file ..\src\utils\Archive.cpp)	utils	..\sumatrapdf-master\src\utils\BaseUtil.h	600	

What am I doing wrong do I have to update visual studio or am I missing an include directory?

**Comment by kjk** [comment]
Upgrade VS to latest 16.7.3
