### ISSUE TITLE
New format support: DAISY

### ISSUE THREAD

**Issue by jmroyb** [sumatrapdfreader/sumatrapdf#1763]
Hi folks,

Can I suggest DAISY format for Sumatra?

DAISY is the format for visual impairment people, as me. It consist in xml indexes and mp3 player

For testing I have access to copyright protected downloads (in my mother tongue, catalan) of my local Visual Impairment Organization (In Spain is once.es) but not sure if I can share, but can ask if you are interested on.

Format specification:
https://daisy.org/activities/standards/daisy/

Cheers

**Comment by GitHubRulesOK** [comment]
@kjk 
As far as I understand it Daisy is a sub or super set, thus variant of e-pub three,
Currently SumatraPDF is very roughly equivalent to e-pub one, and even if the core were switched to MuPDF would still at this stage be less than e-pub two for accesibility purposes.
There are also, the challenges related to audio readers, such as NVDA that would require additional boosting of MuPDF abilities.
Whilst in principle, a Daisy reader looks like a market that SumatraPDF could address, I suspect it would be a significant undertaking for one individual, without support from Artifex.

**Comment by jmroyb** [comment]
Ok. Thanks!

**Comment by GitHubRulesOK** [comment]
@jmroyb 
I have not closed this issue but think is is raised in outher threads, I just observed that whilst not impossible for the the developer, the task would be significant thus unlikely without wider support.

**Comment by jmroyb** [comment]
Ok. 
I reopen it again. Let's wait for some time...

Thanks folks!

**Comment by GitHubRulesOK** [comment]
There are many seperate attempts at readers for the blind, and I do not know their individual merits compared to SumatraPDF. Ones that spring to mind may only suport epub or pdf, and may not be currently in development  or are often dedicated small one or two man teams, thus may not maintain them frequently.
Many support  NVDA features such as,

Q-Read (low cost at "about $35 US or somewhere in that range") from https://q-continuum.net/ 

possibly V I P reader from the swiss association for the blind, but I think that stagnated, and was possibly only PDF

It is best to raise the topic on related sites and several visually impaired users discuss alternatives and rate QRead as good in this discussion https://nvda.groups.io/g/nvda/message/37351

**Comment by kjk** [comment]
there is no plan to support that
