### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1767]
Historically it was possible to see the homepages in other languages e.g.
https://web.archive.org/web/20161207131816if_/http://www.sumatrapdfreader.org/manual-de.html

But more importantly
The translator links were dedicated and examples in the site documentation offer as an example
http://www.apptranslator.org/rss?app=SumatraPDF&lang=de

That does not work for me in either firefox or edge I get a similar
"This XML file does not appear to have any style information associated with it. The document tree is shown below."

Back to the reason I was looking for language support is that many web links connect to as an example
http://blog.kowalczyk.info/software/sumatrapdf/free-pdf-reader-de.html
However that also seems to be broken / redirected to english

Also trying to navigate the site in another language is almost impossible possibly due to the banner code so google, bing or yandex also appears not to work as each page needs to be manually copied

Again noticably most pages wont work with yandex translate

**Comment by kjk** [comment]
I abandoned translation of the website because it's too much effort to maintain.

http://www.apptranslator.org/rss?app=SumatraPDF&lang=de is a working link for an RSS feed.
