### ISSUE TITLE
Copy-paste Host to VM

### ISSUE THREAD

**Issue by dachod** [sumatrapdfreader/sumatrapdf#1771]
I want to perform multiple copy-pastes of several textual items from a single PDF document to another application.  The source is Sumatra 3.2 64-bit running on a Windows 7 host.  The paste destination is on an Ubuntu Linux running in a VirtualBox VM.  I created the VM with a bi-directional shared clipboard.

The first such copy-paste usually works.  But on subsequent copies the following paste in the VM just pastes the text I copied the first time.  That is, only the text copied first makes it into the VM.  This was true of previous 3.x Sumatra 64-bit releases as well.

**Comment by GitHubRulesOK** [comment]
Since I have not generally encountered cut n paste issues between windows apps this seems to be an external issue between host and guest so DuckDuckGo searching "vm copy paste windows ubuntu" seenms to throw up many similar queries, unless @kjk has any more insight? perhaps related to user elevation then I have to suggest this is an issue outside of SumatraPDF's control.

**Comment by SumatraPeter** [comment]
Ensure you're running the latest VBox version and also have the latest Guest Additions version installed (6.1.14 for both at present).

If that doesn't help, test with the latest Sumatra daily build (you can use the portable version for testing), and also confirm that the bug affects _only_ copy-paste from Sumatra and no other host Windows app.

**Comment by dachod** [comment]
Thank you to those who responded.

Good call about the Guest Additions.  I often forget to update them after updating VBox until VBox finallly dings me.  VBox is already at the latest.  However, installing the latest GA ran into an open VBox issue regarding the Guest display going black after login.  Rather than trying to work past this issue, I ran some tests using the old GA, since I'm sure I've seen the issue before when VBox and GA were in alignment.

I performed Copy in SumatraPDF, Acrobat Reader DC, Thunderbird, and Notepad++ on the Host Windows 7 side.  All the Pastes were into Mousepad in the Ubuntu Guest.  I found the results very interesting.  All of the non-PDF apps worked without problem.  **_Both_** PDF apps exhibited the same problem I originally reported.  Do they share any code?  I didn't think Acrobat was open source.

Also, after Copy-Pasting from one of the non-PDF apps, a Copy from either PDF reader didn't take.  That is, the subsequent Paste just inserted the last Copied text from the non-PDF app.

I'm new around here so I don't know who has authority over issue status.  But if someone wants to close this without further action, I certainly won't complain.  Who knows where the problem really is?

**Comment by GitHubRulesOK** [comment]
There should be no common code with Acrobat but there is the fact they are both copy/pasing pdf contents (which itself can be code/encoded or dual text&image, not just plain text) so it would be interesting to observe if other PDF viewers clipboard contents behave likewise (however Browser PDF viewers could be different?)

**Comment by kjk** [comment]
If it only happens between Windows and Linux inside a VM, then there's nothing I can do about it.

Sumatra doesn't share code with Acrobat.

**Comment by GitHubRulesOK** [comment]
@kjk 
whilst SumatraPdf does not use Adobe code Artifex (Mupdf authors) do have an arrangement with Adobe to provide code. :-)  and common cross platform behaviours should often be desired by users even if its not what the user desires :-).
