### ISSUE TITLE
Closing after annotation edit

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1773]
Unsure if it is a issue, but perhaps needs review?

When opening a file with annotation and moving it accidentally whilst selecting it, Then understandably on file closure using the menu or closing the tab, there is a warning there were changes to be saved, in that case it is simple enough to say No.

Conversely when intentionally moving or adding annotation, then if using the aplication top right red cross or menu eXit or quitting with CTRL Q or ESC there is no warning and changes are lost.

So generally there is more likely a loss of hard work rather than an annoying reminder.

There is desirably a need to have some means of escape that does not enforce asking the question, However it may be useful to include the warning in more of the natural cases of hitting a close option?

**Comment by kjk** [comment]
I think we're asking for confirmation on unsaved annotations in every scenario.
