### ISSUE TITLE
[Feature Request] Show single page docs in Single Page view when default is BookView

### ISSUE THREAD

**Issue by evergreenjasong** [sumatrapdfreader/sumatrapdf#1774]
I generally default to the book view so I can view two pages at a time on my big monitor.  It would be nice if single page documents opened in single page view.

Love the speed at which Sumatra opens.  Thank for keeping Sumatra alive.

**Comment by GitHubRulesOK** [comment]
Hmmm as expected eventually we get the converse of Do not default to 'facing' view if the PDF has only one page #1619 and I guess the answer should be the same "just tap the single page icon"
![image](https://user-images.githubusercontent.com/12754913/95511467-6dbd9580-09af-11eb-9ea2-f3ce71175549.png)

**Comment by evergreenjasong** [comment]
Fair enough.  Thanks for responding.
