### ISSUE TITLE
i think that this a virus of collections.

### ISSUE THREAD

**Issue by jak3456** [sumatrapdfreader/sumatrapdf#1780]
i found 2 ip and 2 domain in this software . can you tell me . why you are using ip and domain in offline software. first i scanned with virustotal then i got no virus . But when scan every part of sumatrapdf one by one .i got virus of collections in this software. 
1st. https://www.virustotal.com/gui/file/28bb160970082ba078bdf2ec7f1723c7fa25d41fb4497844cf4b1c05b2e35535/detection
2nd.  https://www.virustotal.com/gui/file/ebc8249fa2717f3ecd6c4fce1584686e7a01fbbaa8dc52b76bf6b60367a96572/detection
3rd. https://www.virustotal.com/gui/file/ebc8249fa2717f3ecd6c4fce1584686e7a01fbbaa8dc52b76bf6b60367a96572/detection

**Comment by kjk** [comment]
I don't know what files you submitted to VirusTotal so I can't verify any of it.

That being said, there's no virus in Sumatra executables I publish.

Consider possibility that your computer is infected by a virus and executables you're submitting to VirusTotal were infected on your computer.

**Comment by SumatraPeter** [comment]
Unsigned infected executables obtained from who knows where and submitted as some sort of 'evidence' of malware by an 'ethical hacker'? Hilarous. 🤣 How old are you, kid?
