### ISSUE TITLE
Ebook Visual controls

### ISSUE THREAD

**Issue by shockergit** [sumatrapdfreader/sumatrapdf#1788]
1.) Please add options for changing font and font size like in normal ebook readers in menu
2.) Give option to choose background images for ebooks
3.) Give an option for Custom margin numbers and Paragraph alignment like justify and centre
4.) Give an animation for page turning

**Comment by GitHubRulesOK** [comment]
The idea of seperate issues is to make it possible to address each one,
 if they are mixed or variations on those already raised they are less likely to be closed out.

1) Menu requests are usually resisted when there are already Advanced Settings for default choice as in this case.
Writing code for a dedicated drop down or similar for highly variable user preferences adds to slowing the application down. Choosing a default point size between 0.1pt and 99.9pt is easily set via Notepad, equally it would require code and time to detect all the fonts in the system to offer the users just the one they prefer. All that may change if (or when) e-book interface is overhauled.

2) Skinning is not a feature often seen  in document readers. It is up to the author to set the document background. When such document bloat e.g. canvas effects is applied badly, it often does not work and consumes much time to decode all those artifacts, so usually grinds down a page reader. SumatraPDF does not modify background tiling (nor should a reader app do so, in my humble opinion).

3) Covered by Allow changing text alignment #358  

4) Animation requires considerable programming and resources. I suggest if you want to be distracted from reading the page contents, you can use a much slower application. There are many that charge for the privileged. Animation of media content is a different matter, thus a higher priority, and covered in other issues.

**Comment by shockergit** [comment]
ok

**Comment by GitHubRulesOK** [comment]
@kjk 
I had left this open as there is some merit in the primary request for changing text size and font on the fly.
The ebook flag is for when interface is reviewed/updated 

MuPDF has the ability via the hotkeys <> to scale up/down the font size in steps ? and e-book font styles variations are potentially governed by user customised CSS
