### ISSUE TITLE
Bookmark errors for only pdf format 

### ISSUE THREAD

**Issue by delta-ij** [sumatrapdfreader/sumatrapdf#1789]
i am having Bookmark errors for pdf format; always one page increment. i tested with other pdfs and also checked with other reader. 
djvu is working fine though.
for every pdf file i am having this issue. 
I am using v3.2 64bit

**Comment by GitHubRulesOK** [comment]
Most likely a known Issue with the way sumatraPDF interprets full page bookmarks, please re-test them with a current https://www.sumatrapdfreader.org/prerelease.html then provide a small sample file that is clearly handled incorrectly

@kjk 
I think there may still be an open issue here but have not determined if it is clouded by some differences between editor apps

**Comment by delta-ij** [comment]
i guess this issue solved in v 3.3.112 64bit :) 
just checked
