### ISSUE TITLE
[REQUEST] Release Universal App verision of SumatraPDF

### ISSUE THREAD

**Issue by Loreno10** [sumatrapdfreader/sumatrapdf#179]
It would be just great to see SumatraPDF as a Modern App available for all W10 devices (phones included). SumatraPDF is the fastest PDF reader out there and I personally think that Modern Apps are the future - I think that Sumatra would gain many new users if it was available as a Modern App and still was so fast. Currently it's hard to find a good pdf reader in the Windows Store (especially for Windows Phone - they are all laggy).

**Comment by kjk** [comment]
It would be a lot of work so we don't have plans for that.
