### ISSUE TITLE
Request for new Sumatra URL Protocol

### ISSUE THREAD

**Issue by MichaelRiechel** [sumatrapdfreader/sumatrapdf#1792]
I would like to use the Command Line features within a Browser.

Therefore the following URL Protocol for Sumatra shall be inserted in the registry:
`[HKEY_CLASSES_ROOT\sumatra]
"URL Protocol"=""
@="URL: sumatra Protocol"

[HKEY_CLASSES_ROOT\sumatra\shell]

[HKEY_CLASSES_ROOT\sumatra\shell\open]

[HKEY_CLASSES_ROOT\sumatra\shell\open\command]
@="\"C:\\Program Files\\SumatraPDF\\SumatraPDF.exe\" \"%1\""`

If the passed parameter %1 contains the characters :// all characters left and the characters itself must be removed respectively replaced by ‘’.

**Comment by kjk** [comment]
Not sure what scenario this would address. 

Even if you execute Sumatra from a link in the browser, the PDF file won't be on user's computer and Sumatra doesn't download files from internet.

**Comment by MichaelRiechel** [comment]
Oh, that ist very sad. 
Another try - the last one - to convince you: 

We are working with a Browser-based App **On-Prem**. All related PDF-documents resides on a server. The users have at least reading rights on these UNC-paths. The idea is to integrate URL-calls of the Sumatra Command Line within this App, so the users can easily view and/or print some PDF ;-)
