### ISSUE TITLE
Documentation update required

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#1793]
https://www.sumatrapdfreader.org/settings/settings.html is linked to from various locations such as the Manual page, Documentation\How we store settings page and so on.

Even though the header clearly states that the page is about "Customizing SumatraPDF **3.2**", the location for the SumatraPDF-settings.txt is incorrectly mentioned as the old `%AppData%\SumatraPDF` directory and not the new `%LocalAppData%\SumatraPDF` one.

A fixed page already exists at https://www.sumatrapdfreader.org/settings/settings3.2.html, so either that should be the page linked to everywhere, or settings.html should be updated.

**Comment by GitHubRulesOK** [comment]
@kjk 
I think you jumped through that hoop twice but there must have been a regression in "Notion"
