### ISSUE TITLE
PDF file with large toc is slow to load

### ISSUE THREAD

**Issue by kyle-goodwin** [sumatrapdfreader/sumatrapdf#1795]
I literally just downloaded, installed, and opened 110MB file with Adobe Reader all before Sumatra opened the file.

Both Adobe and mupdf open the file pretty much immediately.

What gives? Very frustrating.

**Comment by SumatraPeter** [comment]
Depends on the file, so I suggest you provide a sample link to such a file that can be tested or else this issue is likely to get closed quite soon. Also, do test the same file with the latest [daily version](https://www.sumatrapdfreader.org/dailybuilds.html) once and report back.

**Comment by kyle-goodwin** [comment]
It will be tricky to provide as it is not mine but a client's file. Doesn't really contain anything too sensitive but it's not my property to be distributing. I can say it is 5473 pages long with a lot of bookmarks and links. It's an electrical schematic so there are a lot of lines that are connected to other lines with links.

I will try and daily version.

Thanks.

**Comment by SumatraPeter** [comment]
As you can see from the Actions tab above there are regular MuPDF updates being incorporated into Sumatra. I'm not sure which version of MuPDF is being used right now, but it should be the latest i.e. 1.18.0. After a reboot (to rule out any prior caching), how quickly does MuPDF 1.18.0 manage to load the PDF completely?

Unfortunately, without a file to actually test with, it might be impossible for the dev to progress given only such a vague description. If possible, perhaps you can mail it to the dev directly (see [here](https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports.html) for instructions) and he can look into the issue while maintaining confidentiality.

**Comment by kyle-goodwin** [comment]
MuPDF 1.8.0 for Windows opens the file in about 3 seconds after a reboot.

I've emailed the dev in the link you provided. Thanks.

**Comment by kjk** [comment]
I've looked at the profile for the file.

It's a file with over 5k pages and large table of contents. The code takes most of the time in `PopulateTreeItem`:

```
Function Name       Total CPU [unit, %]	Self CPU [unit, %]	Module	Category
PopulateTreeItem    44591 (94.24%)	3 (0.01%)	SumatraPDF.exe	UI | IO | Kernel
  insertItem        23674 (50.04%)	1 (0.00%)	SumatraPDF.exe	UI | IO | Kernel
  TocItem::ChildAt  20474 (43.27%)	20469 (43.26%)	SumatraPDF.exe	Kernel
  PopulateTreeItem  435   (0.92%)	0 (0.00%)	SumatraPDF.exe	UI | IO | Kernel
```

To make a significant improvement, would probably have to move to "virtual" Tree i.e. avoid inserting all tree items, just insert those that are currently visible and then insert the rest on demand.

**Comment by GitHubRulesOK** [comment]
@kjk 
could this tree behaviour be related to https://github.com/sumatrapdfreader/sumatrapdf/issues/1786 ?

**Comment by kjk** [comment]
It's a different issue.

**Comment by kjk** [comment]
Optimized `TocItem::ChildAt()`. In this specific document there are toc items with lots of children and `ChildAt()` would also start from first child to get n-th child. It reduced time taken by `TocItem::ChildAt()` from 43.27% to 0.02%:

```
Function Name	Total CPU [unit, %]	Self CPU [unit, %]	Module	Category
|||||||||||| + TreeCtrl::SetTreeModel	16123 (79.83%)	0 (0.00%)	SumatraPDF.exe	UI | IO | Kernel
||||||||||||| + PopulateTreeItem	16122 (79.83%)	4 (0.02%)	SumatraPDF.exe	UI | IO | Kernel
|||||||||||||| + insertItem	15936 (78.91%)	1 (0.00%)	SumatraPDF.exe	UI | IO | Kernel
||||||||||||||| + [External Call] SendMessageW	15935 (78.90%)	64 (0.32%)	Multiple modules	UI | IO | Kernel
|||||||||||||||| + wndProcSubclassed	15871 (78.58%)	1 (0.00%)	SumatraPDF.exe	UI | IO | Kernel
||||||||||||||||| - [External Call] DefSubclassProc	15862 (78.54%)	15862 (78.54%)	Multiple modules	UI | IO | Kernel
||||||||||||||||| - HandleRegisteredMessages	8 (0.04%)	8 (0.04%)	SumatraPDF.exe	
|||||||||||||| - PopulateTreeItem	172 (0.85%)	0 (0.00%)	SumatraPDF.exe	UI | Kernel
|||||||||||||| - TocItem::ChildAt	5 (0.02%)	5 (0.02%)	SumatraPDF.exe	
|||||||||||||| - TocItem::ChildCount	3 (0.01%)	3 (0.01%)	SumatraPDF.exe	
|||||||||||||| - Vec<WStrList::Item>::MakeSpaceAt	2 (0.01%)	1 (0.00%)	SumatraPDF.exe	Kernel
||||||||||||| - insertItem	1 (0.00%)	0 (0.00%)	SumatraPDF.exe	Kernel
```

It's probably ~40% faster but still slow.

**Comment by kjk** [comment]
Preserving some code:
```c++
// complicated because it inserts items backwards, as described in
// https://devblogs.microsoft.com/oldnewthing/20111125-00/?p=9033
void PopulateTreeItem2(TreeCtrl* tree, TreeItem* parent, HTREEITEM hParent) {
    TreeItem* tmp[256];
    HTREEITEM hTmp[256];
    TreeItem** a = &tmp[0];
    HTREEITEM* ah = &hTmp[0];
    int n = parent->ChildCount();
    if (n > dimof(tmp)) {
        size_t nBytes = (size_t)n * sizeof(TreeItem*);
        a = (TreeItem**)malloc(nBytes);
        nBytes = (size_t)n * sizeof(HTREEITEM);
        ah = (HTREEITEM*)malloc(nBytes);
        if (a == nullptr || ah == nullptr) {
            free(a);
            a = &tmp[0];
            free(ah);
            ah = &hTmp[0];
            n = (int)dimof(tmp);
        }
    }
    // ChildAt() is optimized for sequential access and we need to
    // insert backwards, so gather the items in v first
    for (int i = 0; i < n; i++) {
        auto ti = parent->ChildAt(i);
        CrashIf(ti == nullptr);
        a[n - 1 - i] = ti;
    }

    for (int i = 0; i < n; i++) {
        auto ti = a[i];
        HTREEITEM h = insertItemFront(tree, hParent, ti);
        ah[i] = h;
        auto el = std::make_tuple(ti, h);
        tree->insertedItems.Append(el);
    }

    for (int i = 0; i < n; i++) {
        auto ti = a[i];
        auto h = ah[i];
        // avoid recursing if not needed because we use a lot of stack space
        if (ti->ChildCount() > 0) {
            PopulateTreeItem(tree, ti, h);
        }
    }

    if (a != &tmp[0]) {
        free(a);
    }
    if (ah != &hTmp[0]) {
        free(ah);
    }
}
```
