### ISSUE TITLE
Basic PDF Editing

### ISSUE THREAD

**Issue by shockergit** [sumatrapdfreader/sumatrapdf#1796]
Can you guys add options for basic pdf files editing like 
1) Changing the order of page in a PDF file
2) Cropping PDF and saving it as a separate PDF file
3) Merging multiple PDF files
4) Creating PDF from Images
5) Deleting pages from a PDF file
6) Rotate pages in a PDF file
7) PDF Reflow Mode

**Comment by GitHubRulesOK** [comment]
I am not the developer so will let kjk give his own take on the likelihood of such "editor" functions.

Whilst potentially all those functions might be possible using MuTools commands (Although I have never tried to use them in that fashion) it is not easy to add a GUI interface that could compete well with other applications.
There have been such attempts built around the lightweight PDF toolkit (still a worthwhile portable app) and the most current Open Source (Semi commercial) model is Sejda/PDFsam as built by a team of programmers but that requires a similar slow footprint to Adobe Acrobat without half the features.

**Comment by kjk** [comment]
Those features are unlikely to be added.

**Comment by TCB13** [comment]
I guess except for the feature 7 those would be great additions to this program. I usually use pdfill free that but having them in Sumatra would be very nice. Thank you.

**Comment by GitHubRulesOK** [comment]
@TCB13 none of those features are in MuPDF-GL which is the primary part of SumatraPDF
Adding annotation as an appendix is as far as the GUI version goes,
 all other functions such as tear apart and rebuild are in MuTool which is command line only.
