### ISSUE TITLE
Display filename of document being viewed

### ISSUE THREAD

**Issue by fencepost-error** [sumatrapdfreader/sumatrapdf#1798]
It would be nice if Sumatra PDF could display the filename of the document currently being viewed.  If you're viewing multiple documents, you have no idea which one you're currently viewing.  You can Ctrl-Tab between documents, but there's no indication which document you're currently viewing.

**Comment by GitHubRulesOK** [comment]
The easiest shortcut is possiblty CTRL D and then ESC to dismiss you can CTRL C all those details if you want to save them to clipboard but cant select juxt the first line, (which has been raised elsewhere)

Another posibility is use F2 just to see/capture only the filename without path and if using pre-release there are ways to save current tab filepath\name or all tabs as described using `ExternalCierwers" in https://forum.sumatrapdfreader.org/t/open-files-from-multiple-tabs-in-acrobat-or-other-app/3431

**Comment by fencepost-error** [comment]
Ah, thanks, I didn't know about Ctrl-D.  

Still, it would be nice to have the filename in the title bar (which is currently empty, i.e. available for use) or similar for when you're viewing a lot of docs.  My use cases is data sheets where I might have a dozen open at once, and hitting ^D on each one to see which is the one I want would get old fast.

**Comment by GitHubRulesOK** [comment]
Requested many times as **show filename when hovering over tab** etc etc so I will be closing this when I find the correct references that raise similar issues.

**Comment by fencepost-error** [comment]
Ah, OK.  OTOH since it doesn't have tabs I wouldn't know what to hover over :-).

**Comment by GitHubRulesOK** [comment]
I seem to be missing a point here since the filename is usually shown in the heading when viewing either in tab or non tab mode 
![image](https://user-images.githubusercontent.com/12754913/98237231-7a0c2280-1f5c-11eb-8c59-ed460d11b689.png)
![image](https://user-images.githubusercontent.com/12754913/98237338-aa53c100-1f5c-11eb-924e-f685ac06e132.png)
The problem with tabs is that when there are many the space for each filename reduces
![image](https://user-images.githubusercontent.com/12754913/98237485-df601380-1f5c-11eb-990e-97a9ada94054.png)

**Comment by fencepost-error** [comment]
Ah, sorry, user error.  I'm using Stardock's Window Blinds to undo some of the braindamage in Windows 10, and the skinning from that is causing portions of the UI to disappear.  For anyone else who's run into this, you need to select custom settings for the application, then check "Enable this to prevent applications using glass".  This still gives you most of the non-Win10 UI while allowing the full UI to be visible.

**Comment by fencepost-error** [comment]
Filed a bug for Window Blinds with Stardock, apologies for the false alarm.
