### ISSUE TITLE
Lack of functionality compared to Microsoft Edge

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#1799]
Microsoft Edge allows users to draw on, highlight, and erase drawings/highlights on PDFs. It would be great if you could add these features. You could also create a text box feature to allow users to type over PDFs, like in Adobe.

**Comment by GitHubRulesOK** [comment]
Much of those are possible with pre-release versions (highlighting only has been possible for years)

Drawing (Inking) is on the cards (not yet available) but you can call Edge with a page to add the inking in the background and instantly see the effect in SumatraPDF. Where you can change colour, add comments and drag it around ( but beware it is still a little rough around the Edges (pun)
![image](https://user-images.githubusercontent.com/12754913/98281080-333a1f00-1f94-11eb-8152-53e8df6ca228.png)

The free text is also a tad limited in its experimental form especially as a fixed size box but you can change font size and make the border invisible so as to add several overlaping etc.

**Comment by Daniel-Lebedinsky** [comment]
Thank you for the drawing tips. Why isn't highlighting possible in all versions though? I'm using the Windows v3.2 version (most recent one apparently) and I don't see it. Also, any plans to release Sumatra on Mac or mobile?

**Comment by GitHubRulesOK** [comment]
3.2 has the stable features but has not yet replaced 3.1.2 (long time stable version with less bugs e.g. font display or cut and paste of such fonts)

Pre-release includes many frequent improvements and the less robust features in development, so will unprotect files to allow editing and has many other updated benefits but on any day that release could go ape on exactly the one feature your depending on, hence there is a pre-release and a "daily". However dont delete yor previous working pre-release they are not available once replaced.

Mac and mobile are unlikely, whilst the core library is cross platform the wrapping that SumatraPDF provides is based on Windows Only, There have been some atempts at running on ARM processors. and It should work reasonably well in Linux Wine or ReactOS, unsure about Mac Parallels.

**Comment by kjk** [comment]
We now have basic annotations editing. See https://www.notion.so/Editing-annotations-15b0e4667f4f4825a4afe1bb10918914
Will be in upcoming 3.3, you can test in daily builds from https://www.sumatrapdfreader.org/dailybuilds
