### ISSUE TITLE
Tab mode: allow multiple windows, moving tabs between windows

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#18]
This only applies to tabs ui mode.

We need to implement drag&drop of tabs, with the following behavior:
- dragging within tab bar works like today: re-arranges the tab order
- dragging a tab to another sumatra window moves the tab to that window. By default as the last tab. As a bonus, if dropped on tab area, puts at the position where it was dropped
- dragging a tab outside a window and dropping creates a new window with this tab as the first tab

As a bonus, when drag&drop is initated, the drag image is a thumbnail of the document.

When dragging out the last tab of the window, we close the window.

**Comment by cheesecracker** [comment]
Please add the following behaviour:
* Right-click on a tab.  Context menu suggests "Move to new window"
  NB: This is implemented in Firefox and I find it very cool to use.

**Comment by theFork** [comment]
+1
Support for multiple windows would be nice, regardless how to un-dock tabs.

**Comment by Balls0fSteel** [comment]
Subscribed, this would be awesome.

**Comment by AndyDurden** [comment]
Very interested in this

**Comment by p0te** [comment]
How would one contribute to this issue? I plan on looking at how this behavior is accomplished in chromium and Firefox, but I'm not nearly skilled enough to try to replicate that code. I guess I'll see what I can gather from the source and post my findings here. or is there a better mechanism for that in GitHub? (i.e. If I have an idea of how to implement the solution, but not the skills to implement it myself, how do I share that idea  )

**Comment by kjk** [comment]
Really the only thing that would help is a working implementation. It's just a lot of work.

**Comment by Sasstraliss** [comment]
Would really like this feature

**Comment by spok7** [comment]
Workaround for multiple tabs:
1. Run SumatraPDF
2. Create and go to a new virtual desktop (Task View Button or Win+Tab, New desktop)
3. Run SumatraPDF in new desktop (this should run a new instance in the new desktop)
4. Drag window from one virtual desktop to the other in task view
5. Close unused virtual desktop
6. Profit

**Comment by spok7** [comment]
Sadly that solution only works for Windows 10 systems. Shout outs to all of the awesome devs that are working on these features!

**Comment by strandloper** [comment]
I tried the suggestion from @spok7 but it didn't work for me. When I tried to launch the new instance of SumatraPDF on the second desktop, it just switched to the first desktop and focused the already running SumatraPDF instance. This on Windows 10 Fall Creator's Edition.

**Comment by strandloper** [comment]
I have just found an easier way to launch a second SumatraODF instance. No need for virtual desktops; just make a second copy of  SumatraPDF.exe, I just copied and pasted so I have "SumatraPDF - Copy.exe". Execute both executables and you end up with two instances of SumatraPDF.

**Comment by ThrosturX** [comment]
How has this PDF viewer survived 4 years since this issue opened?? Do people really only read 1 PDF at a time, like ever?

**Comment by RazinShaikh** [comment]
Workaround suggested by @ThrosturX  can also be used to open multiple windows with multiple tabs.
 
1. Open the tabs you want in one window
2. Options > Use tabs (uncheck)
3. Open another window
4. Options > Use tabs (check)
5. Open files in the new window as tabs
6. Repeat as needed

**Comment by GitHubRulesOK** [comment]
There are several ways to run two windows together like this (explained elswhere but repeated here for relevance to this thread)
![image](https://user-images.githubusercontent.com/12754913/70156198-77011600-16ab-11ea-9ebf-b9dcc1c96f73.png)

The option I am showing is to add a section in external viewers which uses the suggestion above to use a copy of the main exe.
So find the folder with your current SumatraPDF.exe (In my case it is c:\users\username\AppData\local\SumatraPDF) and add a new folder. I simply called it **` 2 `** for brevity also copy the **SumatraPDF.exe** by default it is called **SumatraPDF - Copy.exe**
![image](https://user-images.githubusercontent.com/12754913/70157470-8d0fd600-16ad-11ea-8eb8-a03c770e9a37.png)

In the **SumatraPDF-settings.txt** file you need to modify my entry to suit your own locations adding the following few lines in the ExternalViewers section

```
ExternalViewers [
	[
		CommandLine = "C:\Users\Username\AppData\Local\SumatraPDF\SumatraPDF - copy.exe" -appdata "C:\Users\Username\AppData\Local\SumatraPDF\2" "%1" -page %p
		Name = Second Window
	]
]
```

**Comment by kjk** [comment]
Some progress, available in latest pre-release (https://www.sumatrapdfreader.org/prerelease.html).

I've implemented Ctrl-Shift-N which opens a new window showing a currently shown document (i.e. "duplicate in current window).

There's also Ctrl-N to open a new, empty window (like Chrome's Ctrl-N) and "File / New window" menu item.

**Comment by aneutron** [comment]
@kjk Thank you very much for this much needed feature

**Comment by horychen** [comment]
I am surprised when reading this thread...
Before Sumatra 3, it has the multiple window feature.
Just go to [its official site](https://www.sumatrapdfreader.org/download-prev.html) and download the 2.5.2 version.

**Comment by SumatraPeter** [comment]
@horychen: What's there to be so surprised about? Before 3.0 Sumatra did not support multiple tabs inside a single window. You can still turn off tabs if you want to go back to previous behavior, instead of reverting to such an old version.

**Comment by horychen** [comment]
> @horychen: What's there to be so surprised about? Before 3.0 Sumatra did not support multiple tabs inside a single window. You can still turn off tabs if you want to go back to previous behavior, instead of reverting to such an old version.

It seems I misunderstood the issue. People want tabs feature and multiple window feature at the same time, while I was looking for multiple window feature with SumatraPDF 3. After reading your comment I managed to use multiple window with SumatraPDF 3 by check "settings-options-advanced-Use tabs". This is exactly what I was looking for. Thanks!

**Comment by SumatraPeter** [comment]
@horychen: As the dev has mentioned above, the latest versions support Ctrl+N and Ctrl+Shift+N to open multiple windows _with_ tabs still enabled, if that is what you're indeed looking for.

**Comment by GitHubRulesOK** [comment]
@kjk much of the desires **except drag from one group to the other** (which oddly/naturally opens a  third window :-)
 are now realised in 3.5.x Pre-release

Perhaps time to close this long thread in favour of one to cover residual desire(s) in 3.5+

**Comment by kjk** [comment]
Well, well, well. Only 9 years but it's done now: https://github.com/sumatrapdfreader/sumatrapdf/commits/master

**Comment by LinuxOnTheDesktop** [comment]
In Sumatra v. 3.6, I failed to find in any menu the option to get a new window showing the same document as the existing tab. I was about to file a feature request but then I found this very webpage - giving the keyboard shortcut of ctrl-alt-n. I welcome the functionality but should the feature not be available from a menu too? Otherwise, as my case shows, there is a discoverability problem!

**Comment by GitHubRulesOK** [comment]
@LinuxOnTheDesktop 
That question has been raised before just cant remembered where
 but without checking, the generic answer was there would be too many to list and show all
 occasionally over time some get added for one reason or another so probably less now "not shown" than in the past

**Comment by LinuxOnTheDesktop** [comment]
@GitHubRulesOK : right. Thanks for the information. Some sort of 'More . .' menu option might be in order. I note also that there are a couple of requests (#3990 and #1467) that there be a way of showing all the keyboards shortcuts.

('[S]o probably less now "not shown" than in the past': for the avoidance of confusion you might want to change 'less' to 'fewer'.)

**Comment by GitHubRulesOK** [comment]
@LinuxOnTheDesktop 
the functionality was improved by adding the CTRL K options but that does not show "shortcuts"
 and even one very very old one such as `F` for fullscreen only recently added to docs :-) as many are generic to windows apps.

**Comment by LinuxOnTheDesktop** [comment]
@GitHubRulesOK 

I'm sorry, but you are going to have to spell things out a bit here. '[T]hat functionality was improved by adding the CTRL K options but that does not show "shortcuts"' - what functionality? What 'CTRL K' options? When I press CTRL-K a menu today with 'multimedia trust options' appears . .

**Comment by GitHubRulesOK** [comment]
@LinuxOnTheDesktop  I meant the list of options for commands are shown using CTRL+K but the key press will not be shown so for >new or >fu
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c7871257-1d35-4c98-b4f7-84195e663720)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/fcce314a-12a8-413d-8e82-3149333040f7)
