### ISSUE TITLE
Request: Separate "Frequently Read" and "Restore Session"

### ISSUE THREAD

**Issue by cheesecracker** [sumatrapdfreader/sumatrapdf#180]
I'm currently using 3.1.10135.
From an issue I reported to the forum (http://forums.fofou.org/sumatrapdf/topic?id=3184748), I've learned that "Frequently Read" page when we run SumatraPDF without any PDF is sorted of linked to "Restore Session" if we unable or disable "Remember opened files" in Options.
Please separate these two functionalities.  There are situation where one wants "Frequently Read" but not "Restore Session", or vice versa.  So "Remember opened files" option should only trigger "Frequently Read" page on/off.
Personally I don't need "Restore Session", but it would still be nice if "Restore Session" could be moved from Advanced Options to Options for those who need it.

**Comment by kjk** [comment]
They are additive. We can't restore session if we didn't remember what files were opened and their state, which is what "Remembered opened files" is.
