### ISSUE TITLE
Memory cache option.

### ISSUE THREAD

**Issue by Achaean** [sumatrapdfreader/sumatrapdf#1802]
It would be nice I think, if the user had the option to change it.
Apparently, I couldn't find, such an option.

Bye!  A.

**Comment by SumatraPeter** [comment]
Duplicate of #327.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
Thanks I had not spotted that one

@kjk 
Many recent cache changes may have altered historic view but I suspect allowing user to mess it up then complain their bug is better than anyone elses is not on the cards.
