### ISSUE TITLE
[bug ]Sometimes the number page menu disappears

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#1805]
[bug ]Sometimes the number page menu disappears
![image](https://user-images.githubusercontent.com/11432724/98672088-4d924500-2366-11eb-9c0f-299790fcc174.png)

**Comment by GitHubRulesOK** [comment]
Duplicate but dont have time to check which one at the moment
Caused by setting text to inverted e.g. near white on a near white bacground, so related to theming issues.

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: A dupe of #1553 only if the user has modified TextColor, but for most users who don't bother with the advanced settings it's way more likely to be a dupe of #1329 instead.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
Thanks again I initially left open as otherwise occupied and closed on asumption that @Aliaksandr3by  may have been trying inversion.

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Regardless of which of the two bugs he encountered, they've certainly been around long enough and need to be fixed. In the case of #1553 especially it shouldn't be all that difficult to make the menu labels independent of the TextColor setting.
