### ISSUE TITLE
Option: 'close button to system tray'

### ISSUE THREAD

**Issue by billox** [sumatrapdfreader/sumatrapdf#181]
I'd like an option that when I click on "X" red icon on window (close button), SumatraPDF go on tray system area, instead of close the application, because very often, after I close the window I realize that I need that document again.

Thanks.

**Comment by stufkan** [comment]
See gschenck's comment on #129

**Comment by billox** [comment]
Sorry for the long delay. Hmmmm, my request is a bit different. I am more comfortable with minimize on the task bar (or notification area), because I often close Sumatra without noticing it, and soon after I open another document. In this case, if I understand well how this option works, the previous session is already gone away. But perhaps the development of my request option would be too exacting. Thanks anyway for your answer, stufkan, and I hope that in the future my request will be accepted.

**Comment by kjk** [comment]
No plans to add this.
