### ISSUE TITLE
Can support PaperSize Configuration

### ISSUE THREAD

**Issue by ckrgithub** [sumatrapdfreader/sumatrapdf#1812]
like java
![image](https://user-images.githubusercontent.com/18225851/99329879-1bc73400-28ba-11eb-97e2-2e141e90c694.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
related to this request I note a recent fork has been looking at the issue of limited paper sizes
ref: https://github.com/JensBejer/sumatrapdf

@JensBejer
 <ping ?>
I do not know how useful that may be for this issue

**Comment by ckrgithub** [comment]
@GitHubRulesOK @JensBejer
How to compile  this project(https://github.com/JensBejer/sumatrapdf) with Visual Studio 2019

**Comment by ckrgithub** [comment]
compile failure
![image](https://user-images.githubusercontent.com/18225851/99389602-404efa80-2912-11eb-9b62-083d2d574f0e.png)

**Comment by JensBejer** [comment]
@GitHubRulesOK 
I have made a fork to experiment with a couple of ways to use paper size specification from the command line.

I have added a function that directly uses a PAPERKIND specification on the command line and I have made an extension to the original code for PAPERSIZE to handle custom sizes and to use PAPERKIND as a numeric alternative.

Both of these are used as ways to be able to control the correct paper size when printing a PDF using a SumatraPDF command line.

I have used this solution with a number of different printer drivers and paper formats and sizes.

@ckrgithub 
My fork should compile directly, I try to keep up with the upstream SumatraPDF, and whenever I update I just do a fetch all and then rebase my changes on the upstream code.

I then usually build by opening the solution in VS2019, select the Debug configuration, and then build the SumatraPDF project in the solution. I then run a few tests and if's they are OK i switch to the Release configuration and rebuild the SumatraPDF project and then do the tests again.

I have not yet had any problems with this procedure

I have only used the SumatraPDF project, for building a single stand-alone exe, and have not tested the build of the DLL project

**Comment by ckrgithub** [comment]
I refer to the README, but the compilation failed
![image](https://user-images.githubusercontent.com/18225851/99473199-0f5bdd80-2985-11eb-95bc-08bff8b809ee.png)

@JensBejer 
Can you give a compilation tutorial？

**Comment by JensBejer** [comment]
@ckrgithub 

My process is:
  Clone my repository from github to my local machine
  Open Visual Studio 2019 Community Edition (I use version 16.8.1 currently)
  Open the SumatraPDF solution "sumatrapdf\vs2019\SumatraPDF.sln"
  Select "Debug" for the Solution Configuration and "x64" for the Solution Platform
  Select the "SumatraPDF" project in the Solution Explorer
  Right-click the "SumatraPDF" project in the Solution Explorer and choose Rebuild
  When the build is done the resulting SumatraPDF.exe should be in the solution folder "out\dbg64\"

I then test this build and then change the Solution Configuration to "Release" and do a new Rebuild and test that build.

This process works for me

**Comment by ckrgithub** [comment]
@JensBejer 
Thanks！But it still fails to compile

**Comment by JensBejer** [comment]
@ckrgithub 
I have tried to make a build of the full solution.

I select the Solution, right-clicks and choose clean solution and then rigt-click and choose rebuild.

The build works, no errors, one warning, 41 succeeded, = failed, 0 skipped

**Comment by GitHubRulesOK** [comment]
@JensBejer 
Thanks for responses, I cant compile due to hardware limits ( may need to try harder ) Is there any way you can post a  binary with your changes, for me to try out ?

**Comment by JensBejer** [comment]
@GitHubRulesOK 
I'm not yet fully set up to use github for distribution of binaries, so I have made a set of builds and put the results on my DropBox.

PrinterInformation.exe (Debug/AnyCPU)
https://www.dropbox.com/s/hs9lyll3t5peg2g/PrinterInformation.exe?dl=0

SumatraPDF.exe (Debug/x64)
https://www.dropbox.com/s/xfq7pfy6mjakncp/SumatraPDF.exe?dl=0

SumatraPDF.exe (Release/x64)
https://www.dropbox.com/s/2fc07sibc6gs4xo/SumatraPDF.exe?dl=0

SumatraPDF.exe (Debug/x86)
https://www.dropbox.com/s/dqhqcdjh1uknka2/SumatraPDF.exe?dl=0

SumatraPDF.exe (Release/x86)
https://www.dropbox.com/s/o1c06k8alrzpaz6/SumatraPDF.exe?dl=0

The PrinterInformation is a very simple printer information tool to get printer names, paper names and kind numbers and paper input bin names and numbers.

The additions I have made to SumatraPDF is to add a settings for paperkind=<number> to the -print-settings <settings-list> argument, where the <number> is a valid paper kind number for the selected printer.

I have also extended the paper=<page size> to accept any valid paper size for the printer, but so far i have only made some testing with a few paper sizes for the printers i have access to, and I'm not sure if the current argument parser if capable of handling any paper size name that a printer driver may define.

**Comment by GitHubRulesOK** [comment]
Well I am impressed at the variety of paper sizes listed simply for a virtual fax and was about to say it can not detect my printer but when looking in connected devices, my printers driver is not loaded, so your app was in effect confirming I am a forgetful Idiot 🙂  

I will try and test out some of the SumatraPDF related calls to see how useful that range of paper sizes may be for say zebra or other label printers or larger scale plotting (those outside native A6-A2 range)

**Comment by kjk** [comment]
In https://github.com/sumatrapdfreader/sumatrapdf/commit/b4db2f104f4c6790b87da03cfc7ac803e41f137d I merged the changes from https://github.com/JensBejer/sumatrapdf

Does that resolve this issue?

**Comment by JensBejer** [comment]
@kjk 
Thanks for accepting my little addition to SumatraPDF, I have merged this to my fork, so it reflects the current SumatraPDF master.

**Comment by kjk** [comment]
@JensBejer Thanks for writing the code. If you want to add even more functionality, feel free to submit pull request

**Comment by GitHubRulesOK** [comment]
@JensBejer 
My testing suggests we can use say for "MicroSoft print to pdf" to add the following new page sizes

"paper=b4 jis" Page Size: 25.7 x 36.4 cm (verified)
"paper=B5 Jis" Page Size: 18.2 x 25.7 cm (verified)
"paper=eXecutive" Page Size: 18.42 x 26.67 cm (verified)

NOTE case does not seem to matter but B# **needs to have the space** followed by (JIS)

That is a distinct improvement that could allow to set larger or smaller printer acceptable sizes so should help with label printers

**Comment by ckrgithub** [comment]
@JensBejer @kjk 
Can you give the latest usage document

**Comment by GitHubRulesOK** [comment]
@ckrgithub 
not a lot to document other than more `paper=` sizes should be available but it depends totally on the printer driver authors.
As shown above there are 3 more for "Microsoft Print to PDF" again I do not have a HP driver loaded at present (using a green system where there is low carbon footprint ❤️ 🌲 )

The command line should also accept the longer word `paperkind=A4`

If I want PDF output at A2 I have to use "Microsoft XPS Document Writer" paperkind=66 or A2 then use SumatraPDF to add to clipboard then use MSpaint to save as image then after that use SumatraPDF to save as PDF 
Much easier to use a virtual printer that accepts paperkind=A2 and use that with the SumatraPDF command line.

Custom user sizes are normally paperkind=256 but SumatraPDF has no control over those as its a print driver setting. So the default for "Microsoft XPS Document Writer" 256=A4 and I would likely need to go into the registry to alter that. It needs a good print driver (commercial ?) to allow for changing sizes in its own settings.

**Comment by GitHubRulesOK** [comment]
@JensBejer 
Is there a way to set a custom size using SumatraPDF via command line or do you have a means to adjust say the one used by "Microsoft XPS Document Writer" before it is called by SumatraPDF ?

**Comment by JensBejer** [comment]
@GitHubRulesOK 

I don't know any generic way to add custom paper sizes to a printer.

Some printer drivers allows to add new page setups, but not all printers do this.

As far as I can see the "Microsoft XPS Document Writer" has a fixed set of paper sizes.

I use a commercial PDF printer driver, "eDocPrinter PDF Pro" from ITEKSOFT, and this printer has a button in the advanced settings to add custom paper sizes.

So it seems to depend on the printer driver.

@ckrgithub @GitHubRulesOK 
The paperkind= settings must be given a number for example the "eDocPrinter PDF Pro" mentioned has a paper size for A0 and for that paper size the paperkind number is 296, so for this printer driver I can use paperkind=296 to get A0 paper size output.

These paperkind numbers for non-windows API page sizes are all higher than 255 and depends on the printer driver.

**Comment by GitHubRulesOK** [comment]
@JensBejer 
Brilliant result
Since MS print to XPS driver has a custom setting I did a bit of research on that one
I added a custom size (1inch x 1 inch) so as to save <strike>trees</strike> 🙂 time to run
here I added it in windows 10 (was easier in XP/Win 7) and then use your nifty tool to see it listed as 119

![image](https://user-images.githubusercontent.com/12754913/99994551-0f0e7880-2db1-11eb-9945-d53aaebbf18c.png)

And here is the perfect result of "SumatraPDFx32with printers.exe" -print-to "Microsoft XPS Document Writer" -print-settings "paperkind=119" tiger.pdf

![image](https://user-images.githubusercontent.com/12754913/99994376-d40c4500-2db0-11eb-9202-efae9c97df2b.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
I have been able to use these new features repeatedly to print many ways to custom / non standard page sizes. So although the paper dimensions need to be set-up / named using Windows Print Server features SumatraPDF can easily use them either via command line or print dialog (if they are accepted by the print driver)

 NOTE it can depend on the print driver so Microsoft print to PDF does not always accept/show them via the GUI dialog but may use them without problems from CLI using -print-settings "paperkind=###"
Here in SumatraPDF print dialog it has accepted my  A4 RH and LH variations and they work as expected either via dialog or CLI.
![image](https://user-images.githubusercontent.com/12754913/101971526-cfa5b000-3c29-11eb-9662-80cf0a75b4d5.png)
