### ISSUE TITLE
Rendering issue with latest daily build: somes pages are not stretched

### ISSUE THREAD

**Issue by Lucas-C** [sumatrapdfreader/sumatrapdf#1813]
Tested with the latest 2 version of Undying Dusk PDF that can be found here:
https://github.com/Lucas-C/undying-dusk/releases

On Windows 10 64-bit, with Sumatra 3.3.13200 64-bit Pre-Release.

When opening this huge PDF (which is fast!) I see this:
![2020-11-18 09_27_11-Window](https://user-images.githubusercontent.com/925560/99504815-57c4cc80-2980-11eb-9f94-faf33d13e035.png)
![2020-11-18 09_27_28-Window](https://user-images.githubusercontent.com/925560/99504828-5abfbd00-2980-11eb-946c-ebd2c29f17f8.png)

Then the 3rd page gets rendered right, stretched:
![2020-11-18 09_27_41-](https://user-images.githubusercontent.com/925560/99504876-68754280-2980-11eb-8a60-38936ba73f87.png)

This also happens with small PDFs, like this eleven-page example: https://chezsoi.org/lucas/undying-dusk/minimal-foxit-bug-repro.pdf

Depending on the PDF, the placement of "correctly rendered" pages & "non-stretched" pages is different,
but overall it looks like half the pages.

**Comment by Lucas-C** [comment]
👍 
Thank you for fixing this!

**Comment by Lucas-C** [comment]
I tested the fix with the the [daily build](https://www.sumatrapdfreader.org/dailybuilds.html) (2020-11-20, commit b4db2f1, SumatraPDF-prerel-13204-64-install.exe) and there is still an issue... 😔

Now **not one** page of a PDF gets "stretched" correctly on the full Undying Dusk PDF...
However this issue only appears with big PDFs. It does not appear with [minimal-foxit-bug-repro.pdf](https://chezsoi.org/lucas/undying-dusk/minimal-foxit-bug-repro.pdf), nor with "truncated" Undying Dusk PDF of 6788 pages.

This issue does not appear with the latest [prerelease build](https://www.sumatrapdfreader.org/prerelease.html) (2020-08-16, commit e29de52, SumatraPDF-prerel-13112-64.exe).

Would you mind re-opening this @kjk?

**Comment by GitHubRulesOK** [comment]
Hi Lucas
I am not seeing a problem using commit b4db2f1, SumatraPDF-prerel-13204-64 **portable** (have not tried the installed version to compare if that is different) 13200 with problem on left 13204 on right

![image](https://user-images.githubusercontent.com/12754913/99812588-8d171900-2b3e-11eb-991c-55dbe64c393c.png)

Which modes of zoom are you using if I use 300% then i get a very reasonable even  render of all pages with fewest artefacts

**Comment by Lucas-C** [comment]
You are right, my mistake.

I was expecting Sumatra to auto-zoom to "full height" mode, but Sumatra does not do that I think.
It simply remembers the "prefered zoom level" from the last time a given PDF file was open.

After zooming manually, all is fine.
This can be closed, thank you @GitHubRulesOK !
