### ISSUE TITLE
I want to change the printing direction by silently printing from the command line, how can I change it?

### ISSUE THREAD

**Issue by wangpai1998** [sumatrapdfreader/sumatrapdf#1816]
portrait or landscape : can provide 90 degree rotation of contents (NOT the rotation of paper which must be pre-set by the choice of printer defaults)

What does it mean? How can I change direction using the command line? I can’t change the direction after adding parameters. How can I change the direction?

**Comment by GitHubRulesOK** [comment]
The printer direction of print is **only one way up**
As decided by the printer default setting and paper tray handlers either the paper is to be printed in landscape or it is to be printed rotated in portrait so if you send any image to it it can come out two ways as decided by the PRINTER SETTINGS

Thus it is easiest to have TWO print queues (one of each setting.)
the landscape / portrait command line value allows you to work with / override those defaults

here is the result as expected when using paper="paper=b5 (jIS),portrait" and "paper=b5 (jIS),landscape" to just the portrait device both are correct but perhaps not what you may have expected. the desired result may be provided by the **landscape device**.

![image](https://user-images.githubusercontent.com/12754913/99879501-4fc98e80-2c05-11eb-874d-d21cb93f00f3.png)

![image](https://user-images.githubusercontent.com/12754913/99879620-fe6dcf00-2c05-11eb-9e27-029ebfe2451d.png)

**Comment by wangpai1998** [comment]
I do not know what you mean. . I set "paper=b5 (jIS),portrait" and "paper=b5 (jIS),landscape" according to your settings. Does it still work? ? Do I need to change the printer's preferences through c#? Or what? ? I don't know much, please trouble you

**Comment by wangpai1998** [comment]
The file I printed out is still in the same direction as the default setting, it can’t be changed

**Comment by wangpai1998** [comment]
-print-to "HP DeskJet 2130 series" -print-settings "1-1,2x,landscape" -silent 1.pdf

-print-to "HP DeskJet 2130 series" -print-settings "1-1,2x,portrait" -silent 1.pdf

The effects of these two are both vertical, without changing the direction

**Comment by GitHubRulesOK** [comment]
So as to have most control over direction. Historically I use two copies of print driver for either a virtual or a physical paper one.
I cant show you the example paper two as the HP drivers are not yet on this machine but here you can see two virtual PDF ones ignore that the paper sizes are different **if I send A4 page to either one it will be rotated 90 degrees compared to the other.**

This was needed for SumatraPDF before the choice of rotation was added more recently, so the first question has to be which version of SumatraPDF are you using ?


![image](https://user-images.githubusercontent.com/12754913/99880307-98377b00-2c0a-11eb-9ce5-d8650992fae5.png)

With the command line you can do a 90 degree rotation that should

**Comment by wangpai1998** [comment]
I used Sumatra pdf-3.2

**Comment by wangpai1998** [comment]
I know what you mean. You mean there are two printers, one is vertical and the other is horizontal. But the effect I want to achieve is to switch parameters on one printer

**Comment by GitHubRulesOK** [comment]
perhaps try latest daily https://www.sumatrapdfreader.org/dailybuilds.html 
without -silent it works for the examples above
newest daily this week also has the new paper=sizes

**Comment by GitHubRulesOK** [comment]
Io am loading HP drivers to confirm if portrait/landscape differ here on a physical device but do expect that it will work with latest builds

**Comment by wangpai1998** [comment]
I mean, change direction is not available, that is, you can't change the direction on a printer, not the paper parameter. I want to know how I can change direction on a printer. For example, the first time I print is vertical and the second time I want to print horizontally, what should I do?? I pass in the parameter settings. No matter what, the answer I went to search for is that you need to change the printer's preferences??

**Comment by wangpai1998** [comment]
What can I do to change the direction if I print it with your parameters or vertically, which is the default preference of the printer, and it is not changed to horizontal?

**Comment by wangpai1998** [comment]
Thank you very much.

！！

**Comment by wangpai1998** [comment]
Thank you very much.

！！
