### ISSUE TITLE
F5 presentation mode can only display single pages

### ISSUE THREAD

**Issue by foceno** [sumatrapdfreader/sumatrapdf#1817]
F5 presentation mode hides the mouse cursor but can only display single pages.
F11 fullscreen mode can display 2 pages ("facing" or "book view") but does not hide the mouse cursor.

Seems like F5 presentation should also be able to display 2 pages (and/or F11 should be able to hide the mouse cursor as an option). Ideally, the delay time before the mouse is hidden would be adjustable in advanced options.

**Comment by SumatraPeter** [comment]
Try pressing F5 and then Ctrl+7/Ctrl+8. 😉

**Comment by GitHubRulesOK** [comment]
@foceno 
Since you have your acceptable method to hide mouse in F11 mode and @SumatraPeter has corrected my error re using F5 
are you happy to close this issue ?

@kjk 
any reason why hiding mouse on a timer in F11 ( and F5) mode would be a challenge for provide a user setting ?

**Comment by foceno** [comment]
There's no more issue for me since I'm using a separate program to hide the mouse and AutoHotKey opens/closes it without issue. The timer in F5 presentation mode is longer than I want anyway. 

Though it doesn't make sense that F5 presentation mode automatically switches to single page even if you were on "book view" or "facing".

**Comment by GitHubRulesOK** [comment]
Closing issue as the headlined reason was based on my mistake (corrected by SumatraPeter) in not spotting that invoking F5 (Presentation) needs a secondary command to switch on facing or book mode and thus here is a non issue, although consistent behaviour could be enhanced by maintaining previous page mode the same as the more useful F11 (Full screen).
