### ISSUE TITLE
SumatraPDF portable won't run from "C:\Program Files (Portable)" path

### ISSUE THREAD

**Issue by rdelia** [sumatrapdfreader/sumatrapdf#1818]
Hi, I'd like to launch SumatraPDF portable from path "C:\Program Files (Portable)" on my Windows PC, but the following error is presented:
![image](https://user-images.githubusercontent.com/19497121/100467019-1fd12e00-30d2-11eb-9d95-cb0ff1761579.png)

**Comment by GitHubRulesOK** [comment]
Its not a problem simply either download from the original source or raise an issue with Portable apps, the version you are using is not the standard portable version.
