### ISSUE TITLE
RIGHT CLICK / PRINT MISSING

### ISSUE THREAD

**Issue by LLAURRA01** [sumatrapdfreader/sumatrapdf#182]
WHERE DID IT GO?  RIGHT CLICK / PRINT IS NO LONGER AN OPTION.  I USE THIS DAILY ...  HOW DO I PUT IT BACK?

**Comment by LLAURRA01** [comment]
UMMMMM  CLOSED WITH NO EXPLANATION?   RUDE

**Comment by kjk** [comment]
First, DONT SCREAM.

Second, the question doesn't have enough information. I don't understand what you're asking.

Third, this is for reporting bugs.

**Comment by LLAURRA01** [comment]
First… it wasn’t a scream.. c’mon now, who even thinks or says that anymore.  Cap lock was on…   smh.
2nd…  it’s a simple request.. right click (on mouse, obviously) doesn’t show an option as PRINT like it did last week.  Actually there are only 2 options and none are of any use to me.
3rd.. it is a bug.  Whatever update was done removed all the right click functions…

Here’s what I see when I right click
[cid:image001.png@01D081B9.D669DFA0]
No options available.     This was my point of the posting.  Now if you aren’t the correct party, maybe directing me to the appropriate person would have been a better option than zeroing in on a “scream”.

**Comment by kjk** [comment]
The screenshot is missing so I still don't understand the scenario.
