### ISSUE TITLE
file displays differently in acrobat and sumatra

### ISSUE THREAD

**Issue by skylas173** [sumatrapdfreader/sumatrapdf#1820]
a file displays differently in sumatra and acrobat:

![1](https://user-images.githubusercontent.com/34537362/100614362-b3973a00-331e-11eb-8c78-e290e0ab98d2.png)

(acrobat is the correct view)
file is attached
[ToDo.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5616087/ToDo.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk 
Not analysed in depth however certainly seems to be a regression from 3.1.2
Not sure if "The total price" text is only meant to be shown by using JavaScript However 3.1.2 hid/coloured it exactly same as Acrobat does

**Comment by GitHubRulesOK** [comment]
Forgot to say raised as bugreport at
https://bugs.ghostscript.com/show_bug.cgi?id=703274

**Comment by GitHubRulesOK** [comment]
Feedback from Artifex analysis classes this as "Bad File"  and since the invalid characters are present they are displayed by MuPDF rather than discarded by other renderers.

For the above reason this issue should be classed as Working as expected (with a bad file) thus "Can't Fix" bad file.
