### ISSUE TITLE
Sumatra PDF v3.3.13112 64-bit Pre-release = crashed

### ISSUE THREAD

**Issue by givemeatip** [sumatrapdfreader/sumatrapdf#1823]
Link to the gist: https://gist.github.com/givemeatip/1ee4d0ada01281b0a874e871fe23dab1

**Comment by GitHubRulesOK** [comment]
@kjk 
old report unknown if addressed

**Comment by kjk** [comment]
Thanks for pointing this. From callstack it does look like one of the things I've fixed.
