### ISSUE TITLE
File registration in CMD does not work

### ISSUE THREAD

**Issue by andrecool-68** [sumatrapdfreader/sumatrapdf#1824]
File registration does not work when installing the program from the command line.
`SumatraPDF-3.2-64-install.exe /s /register`
`SumatraPDF-3.2-install.exe /s /register`

**Comment by GitHubRulesOK** [comment]
/register (as default pdf handler) was an option in 3.1.2 across windows versions
![image](https://user-images.githubusercontent.com/12754913/101846861-c34a2600-3b49-11eb-8b0b-5d584a8cbcb1.png)

AFAIK even as administrator it did/does NOT work on Windows 10 (blame MS Edge is the default)
I just tried 3.1.2 without silent and nothing changes also in 1020H2 Edge no longer even bothers to warn me it blocked an attempted change.

Unsure if its (still working via 3.2 in say windows 7) but certainly no longer shown on 10 installs
![image](https://user-images.githubusercontent.com/12754913/101846921-e8d72f80-3b49-11eb-81b5-c819ec41ca4a.png)

So I guess trying it silently will fail silently

@kjk 
Am closing as no longer a viable command option / no longer documented as such

**Comment by andrecool-68** [comment]
@GitHubRulesOK This means that we will no longer see the `/register` flag?

**Comment by GitHubRulesOK** [comment]
I cant say it would not return in a future version that's down to @kjk or others  but since the goal posts were moved by Microsoft windows 10 to require a much more complex requirement including UAC hashes I suspect 3.1.2 was the last version to use that simpler method which is not allowed by windows 10

**Comment by andrecool-68** [comment]
@GitHubRulesOK  Ok!
