### ISSUE TITLE
Pre-release v 3.3.13112 bug

### ISSUE THREAD

**Issue by rzzzvikashkumar** [sumatrapdfreader/sumatrapdf#1825]
https://gist.github.com/rzzzvikashkumar/ceeabc426a6bc24e87f2b911b33c8c77

![mfzCcq4azD](https://user-images.githubusercontent.com/75368279/101788433-190cd700-3b26-11eb-90e2-2f4f9656a2d4.png)

![VZqxnQ29dY](https://user-images.githubusercontent.com/75368279/101785933-57ed5d80-3b23-11eb-8113-c406ed58676f.gif)

**Comment by GitHubRulesOK** [comment]
@kjk confirmed as present with / without history in current pre-release
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/5675913/sumatrapdfcrash.zip)
