### ISSUE TITLE
Discussion: port to Linux/Mac: native external libs + winelib-linked sumatra

### ISSUE THREAD

**Issue by yatli** [sumatrapdfreader/sumatrapdf#1829]
Yeah this again... See #17 #109 #260 #314 #792 #856, and then #1077.
And also quoting @kjk :
> We don't have plans for that: https://www.notion.so/Why-only-Windows-78e2d376690e4034997908c0788f038b

(So please don't downvote if he reiterate on this!)

We want sumatrapdf because it's a very good implementation built upon win32, taking advantages of all the "good side" of the platform. I don't think porting the UI to GTK/Qt/Cocoa/you-name-it will make any sense.
Sumatra also runs just fine with wine, so why bother?

The benefit of a native build is to bring the dependency of wine down to minimum -- performance and stability-wise, the program will benefit from this. All the external libraries can be natively compiled.
But we still want the core sumatra experience don't we :) That's where `winelib` kicks in -- link the win32 layer ahead of time, so parts of wine is baked directly into the binary and you don't need to install wine to use it.

I'm not familiar with `premake5`, but nevertheless I don't think it'll be that hard to populate `premake5.unix.lua` and native-compile the ext libs, and involve winelib.

Thoughts?

**Comment by GitHubRulesOK** [comment]
In many similar cases its down to knowledgeable "porters", By that I mean those that know how to address any kernel related oddities that occur.
So take SmartPDF which was probably the _leanest_ [fewest differences] past port of SumatraPDF It worked well enough for a number of iterations but then running out of steam fell behind and was abandoned. I have attempted to tery out current builds to determine comparative status but have not yet succeeded to find compatible hardware!

The logic goes

> "I think that it's more appropriate to make ROS run it [SumatraPDF] , **not hack it to make it run on** ROS [ /Wine / Parallels].
> You are absolutely right, it was just a kind of "inside" shortcut, that shouldn`t be used.
> 
> To make something work under ROS [/ Wine / Parallels]  = to fix ROS [/ Wine / Parallels], so the aforementioned app would work.

My HO is that if there is a Linux / Mac  shell for Windows then their apps should work well in those VMs

 I am happy to run several similar Nix apps (Ocular Evince Kchm) that have been ported via GW etc I just expect them using emulation to crawl compared to their native version.

**Comment by yatli** [comment]
Fiddled around and it's not really that hard to "port" -- given that I'm just switching on/off a few flags while the "kernel related oddities" are handled by the library authors.

For example, to build unarrlib, make the following changes:

```lua
project "unarrlib-opt"
    kind "StaticLib"
    language "C"
    optconf()

    -- TODO: for bzip2, need BZ_NO_STDIO and BZ_DEBUG=0
    -- TODO: for lzma, need _7ZIP_PPMD_SUPPPORT
    defines { "HAVE_ZLIB", "HAVE_BZIP2", "HAVE_7Z", "BZ_NO_STDIO", "_7ZIP_PPMD_SUPPPORT", 
    -- >>>>>>>> HERE <<<<<<<<<<
              "_FILE_OFFSET_BITS=64" ,"_UNIX" }
    -- TODO: most of these warnings are due to bzip2 and lzma
    disablewarnings { "unused-but-set-variable", "int-conversion", "unused-parameter", "sign-compare", "type-limits" }
    includedirs { "ext/zlib", "ext/bzip2", "ext/lzma/C" }
    files {
      "ext/unarr/common/*",
      "ext/unarr/rar/*",
      "ext/unarr/zip/*",
      "ext/unarr/tar/*",
      "ext/unarr/_7z/*",

      "ext/bzip2/bzip_all.c",
    }
    unarrr_lzmasdk_files()
    -- >>>>>>>> HERE <<<<<<<<<<
    -- doesn't work
    -- unarr_lzma_files()
```

**Comment by kjk** [comment]
I'm not opposed to it but I'm not going to do any work on that.

**Comment by GitHubRulesOK** [comment]
I defer to others knowledge of system variations, and agree most of the core libs, such as MuPDF etc, do have multi platform variations. However, as SumatraPDF is heavily tailored to WinOS screen rendering and related file handling things, like path handling (which can significantly different cross systems) those  would consume much more resources especially time for debugging, such that I suspect it would need a  second devout C++ programmer.

**Comment by GitHubRulesOK** [comment]
@kjk 
I am tempted to close this as historically a non-issue 
SumatraPDF may be ported to other platforms but is not currently targeted for non-windows OS

**Comment by kjk** [comment]
makes sense

**Comment by yatli** [comment]
My WIP branch is here: https://github.com/yatli/sumatrapdf/commit/04883f018d6e82ec05b72004d0577b9b768953d5
For anyone interested in maintaining an out-of-tree cross platform build (maybe living in AUR or other package sources)
