### ISSUE TITLE
SumatraPDF scales to paper size of default printer when different printer is selected

### ISSUE THREAD

**Issue by jgferrell** [sumatrapdfreader/sumatrapdf#183]
I have several Windows 7 computers that require a small label printer to be set as the default printer; these labels are about 3.1cm × 2.5cm. The computers can also print to a HP laser printer loaded with 8.5" × 11" paper. When printing from SumatraPDF, I change the selected printer from the default label printer to the HP laser printer. The PDF prints but it's scaled to the size of the label. PDFs will print correctly if I close SumatraPDF, change the default printer to the HP, and then open the PDF and print. If I change the default printer while SumatraPDF is open and fail to restart SumatraPDF, then the print will still be scaled incorrectly.

![sumatrapdf-prints](https://cloud.githubusercontent.com/assets/8268290/7417620/4554885a-ef35-11e4-922c-b7d712fc3227.jpg)
From left to right, the same page: printed to a label, exhibiting the issue at hand, printed when the default printer is set to the HP *before* opening SumatraPDF.

**Comment by kjk** [comment]
I don't really understand the issue. Don't you select a printer in printer dialog when you print?

**Comment by GitHubRulesOK** [comment]
in effect duplicate of #97 SumatraPDF will be offered the current System Default setting in this case it will be small label size until the SYSTEM default is reset BEFORE re-opening SumatraPDF
