### ISSUE TITLE
New sugar in forward research

### ISSUE THREAD

**Issue by qiancy98** [sumatrapdfreader/sumatrapdf#1833]
I find that SumatraPDF reads /mnt/d/path-to-file as c:/mnt/d/path-to-file, resulting it impossible to reach the desired file.

I wonder if you can turn /mnt/d/path-to-file into d:/path-to-file before searching the file? Thanks.

> > After replacing /mnt/c by c: in the .synctex.gz file forward search works fine.
>
> Hello. I wonder How can I do this replacement?
> Thank you very much.
> 
> _Originally posted by @qiancy98 in https://github.com/sumatrapdfreader/sumatrapdf/issues/1026#issuecomment-747462518_

**Comment by GitHubRulesOK** [comment]
SumatraPDF does not write the file it reads it and uses it to re-call the editor which maybe a linux one
but SumaraPDF should be calling a windows editor.

So Sumatra should not need to make any change the call to an editor is normally
 C:\path\editor.exe c:\folder\file.tex

I am unsure why your files include unix mnt unless they are sharing syntex files which is not recommended 
the the primary use is for the author to compile on one OR other platform at a time.

**Comment by qiancy98** [comment]
(Sorry I was busy rushing my homework.)
I am using WSL and all my operations are done in windows.
I always use a single file but somehow it stores the full path.
Now I create a command in `command line` that does this transform.
What I mean is that, maybe we can view the path starting with `/mnt/c/` as `c:/`, or at least provide such an operation?
Thanks.
(If you still think that it is meaningless, then I will close this comment. Thanks.)

**Comment by GitHubRulesOK** [comment]
@qiancy98 
The synctex handler ( the part that reads and actions the two way handling) between SumatraPDF and LaTeX was added a long time ago. It currently works well the way it WAS built, so further changes are on hold as it "Works well, so don't fix it".  Ideally if adjusted it should be updated to more recent version, That update could include any additional changes such as this request to check paths for valid run time entries.

However it is not as far as I know on any ones radar although the synctex Author did raise an update suggestion  https://github.com/sumatrapdfreader/sumatrapdf/issues/841
Testing the validity of the target files falls into that abyss between the synctex library handlers and SumatraPDF internally calling external paths, and here it seems to be aggravated by working "cross-platform" (WSL).

Untested as I don't have LaTeX running, but I am guessing any other Windows based synctex preview readers could hit the same problem.

I am not sure of the correct solution, however I think someone would need to look closer at the way LaTeX compilers build the synctex file in the first place. It is much easier in LaTeX compilation chain of commands to add an extra step to post process the synctex file to make the desired "nix 2 win" text related changes, for example by using sed.

You say "Now I create a command in command line that does this transform.", so does that mean you already have a means to make the correction of the synctex file ?

An alternative SumatraPDF workaround may possibly be to simply use text substitution during the inverse call but without knowing your editors entry in your settings file am unsure how practical that might be as it is not very easy in windows Batch or CoMmanD language to do string manipulation, especially with escape characters involved "/\".

**Comment by qiancy98** [comment]
I am closing this issue as it is already dumped with #841.
In case my transforming code helps anyone, I will share it here:

- the one works in bash is `find -maxdepth 1 -name "*.synctex.gz" -execdir bash -c 'cp "{}" "{}.tmp" && cat "{}.tmp" | gunzip | sed --expression="s@/mnt/\(.\)/@\1:/@g" | gzip > "{}" && rm "{}.tmp"' \;`
- the one works in powershell is `bash -xc 'find -maxdepth 1 -name \"*.synctex.gz\" -execdir bash -xc ''cp \"{}\" \"{}.tmp\" && cat \"{}.tmp\" | gunzip | sed --expression=\"s@/mnt/\(.\)/@\1:/@g\" | gzip > \"{}\" && rm \"{}.tmp\";'' \;'`
- the one works in cmd is `powershell -encodedcommand YgBhAHMAaAAgAC0AeABjACAAJwBmAGkAbgBkACAALQBtAGEAeABkAGUAcAB0AGgAIAAxACAALQBuAGEAbQBlACAAXAAiACoALgBzAHkAbgBjAHQAZQB4AC4AZwB6AFwAIgAgAC0AZQB4AGUAYwBkAGkAcgAgAGIAYQBzAGgAIAAtAHgAYwAgACcAJwBjAHAAIABcACIAewB9AFwAIgAgAFwAIgB7AH0ALgB0AG0AcABcACIAIAAmACYAIABjAGEAdAAgAFwAIgB7AH0ALgB0AG0AcABcACIAIAB8ACAAZwB1AG4AegBpAHAAIAB8ACAAcwBlAGQAIAAtAC0AZQB4AHAAcgBlAHMAcwBpAG8AbgA9AFwAIgBzAEAALwBtAG4AdAAvAFwAKAAuAFwAKQAvAEAAXAAxADoALwBAAGcAXAAiACAAfAAgAGcAegBpAHAAIAA+ACAAXAAiAHsAfQBcACIAIAAmACYAIAByAG0AIABcACIAewB9AC4AdABtAHAAXAAiADsAJwAnACAAXAA7ACcA`

Basic idea is to run powershell in cmd and then run bash in powershell.
A detailed explanation can be found in [Zhihu](https://zhuanlan.zhihu.com/p/337459645) which is totally written in Chinese.

**Comment by yashpalgoyal1304** [comment]
oh, you meant forward search? i got confused for a solid minute
