### ISSUE TITLE
print pdf with cmd command line and paper not A4 format

### ISSUE THREAD

**Issue by mopyfish88** [sumatrapdfreader/sumatrapdf#1834]
If i try to print a pdf with the command line and with a paper size different to A4 the print is stopped at A4 height size.

**Comment by GitHubRulesOK** [comment]
You don't say what paper size you are targeting, but see some of the other command line print issues including those closed, however if the SYSTEM default paper is set to A4 that is what THE SYSTEM will use as print paper size.

There have been many changes such that I suggest you either use 

Latest https://www.sumatrapdfreader.org/dailybuilds.html , which includes the ability to use custom sizes which was discussed at length in https://github.com/sumatrapdfreader/sumatrapdf/issues/1812
There you will find a utility to check paperkind, but note sizes are a windows feature thus SumatraPDF is tied to some extent. Again  -print-settings "noscale,paper=A3" should be the first option to try then swap noscale to both fit and shrink to see the differences -print-settings "fit,paper=A3" should work best

OR if large print file sizes are an issue version 3.0 DO NOT print as image (can be more difficult to control without some newer settings) but it should respect older "paper=A4" (or A5 or A3)

**Comment by GitHubRulesOK** [comment]
Closing as Currently works when setting "paper=anything valid"
