### ISSUE TITLE
add button to go back to "most viewed" page

### ISSUE THREAD

**Issue by JoostScheffer** [sumatrapdfreader/sumatrapdf#1835]
I would like to have the option of viewing the `earlier shown`-page without needing to restart SumatraPDF.
Preferably this would take shape in the form of opening a new tab on which the `earlier shown`-page would show up.

Please note that I use the Dutch version of SumatraPDF, I do not actually know if this is called `earlier shown`. In Dutch it is `Eerder Weergegeven`

**Comment by GitHubRulesOK** [comment]
In general I translate your request as "previously displayed"

so if **within a document** if you jump to page 6 then link to 10 then to 8
 using  (Terug) = Alt + Left Arrow
1 time = page 10
1 more time = page 6
1 more time = entry page
I do not know how big the page number stack can be but  most times I would only go back a forward a few jumps. Each Tab can have its own history until the file is closed or opened in another tab.

If you know you will want to return later to special pages then you can save using "favorieten"
If you open the same file in another tab then the favourites can be applied to the second tab.

Unfortunately for Dutch users there are 2 options for Alt+B so you need to either request that is changed in the translation or use an extra right arrow ➝
For documents it is not so simple (Bestand) Alt+B+ ➝ 2 will swap back to the previous file
Alt+B+ ➝ 3 goes back to the file before either of the two last files.

Can  you explain how your requirement is not met by one of those or similar actions

**Comment by kjk** [comment]
don't quite understand the request
