### ISSUE TITLE
Open multiple instances of a file

### ISSUE THREAD

**Issue by zkosk** [sumatrapdfreader/sumatrapdf#1837]
Possible feature: open multiple instances of a single file. The existing program will open each file only once.

The reading positions and settings for each instances of the same file are all remembered too.

Possible UI: ctrl+o for single instance open, ctrl+u for multiple instance open. Open file outside the program will open single instance as usual.

**Comment by GitHubRulesOK** [comment]
CTRL +Shift +New opens copy of existing file = second window = multiple windows in one instance
File open or drop file in same instance same file = multiple tabs = multiple copies in one instance
Switch tabs off , File open or drop file in one instance same file = second window = multiple instances

![image](https://user-images.githubusercontent.com/12754913/102946240-f8deff80-44b7-11eb-8be6-affc7a8116b5.png)
One file = One history thus as session is closed all status is stored. Poor exit or crash = no (or older) history.
So if one file is open in two windows the LAST one closed is the one LAST remembered.

If you need two separate session histories then run 2 separate exe windows
That need can best be controlled via cmd files to open the two instances with any one file. But ensure the settings file is not the same one. Settings can be started in multiple sub folders using -appdata foldername

**Comment by zkosk** [comment]
Indeed if one file is opened in multiple tabs, the status of each tab can be remembered as hoped.
What is Ctrl+Shift+New?

**Comment by zkosk** [comment]
As I remembered it didn't work like this but it indeed work like this. Another bug about the overflow button covering the closing button of the tab on the right disappears too, is the program upgrading it self?

**Comment by koppor** [comment]
>What is Ctrl+Shift+New?

It is <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd>.

Accessible in the context menu of the tab

<img width="587" height="310" alt="Image" src="https://github.com/user-attachments/assets/3f043c50-c8d5-49ca-9e3f-b5f5ccccc641" />

This command opens the same document in a new window.
