### ISSUE TITLE
Cannot open containing folder?

### ISSUE THREAD

**Issue by zkosk** [sumatrapdfreader/sumatrapdf#1839]
Why isn't there menu item "open containing folder" for version 3.1.1?

**Comment by GitHubRulesOK** [comment]
Most versions don't have "Show in folder" until introduced more recently after 3.1.2
I have seen "Open folder" added  at one time but that was removed soon after, so I am guessing that did not work well with windows file handling.
It is not normal to back track so version 3.1.1 from 2015 is unlikely to be revised, The quickest way to show the file in a folder in older versions, was always to use F2
