### ISSUE TITLE
System pop up dialog in open file dialog prevents main program from receiving shortcuts

### ISSUE THREAD

**Issue by zkosk** [sumatrapdfreader/sumatrapdf#1842]
1. ctrl+o to bring up the open file dialog
2. In the open file dialog, delete a file that is already opened, which will bring up the the message box that says the file is currently in use.
3. Click any where except for the message box in the program, which bring the message box to background
4. Cancel the open file dialog
5. Now shortcuts don't work. They will only work after the messagebox is closed

**Comment by GitHubRulesOK** [comment]
Note it IS often possible to delete some files open in SumatraPDF (depending on file type and size)
In such cases windows will NOT open a message box.

Accepting that in other cases Windows itself will raise the warning, SumatraPDF should not auto close that message box that Windows produced. Unfortunatly there are Many such cases where windows does not keep such warnings "On Top" and shifting focus will often stop normal application progress.

@kjk I would suggest that as this is a common Windows behaviour that SumatraPDF has little means to regain control until a  system warning is addressed ?

**Comment by zkosk** [comment]
@GitHubRulesOK  I was talking about the "open file dialog" but you seem not.

**Comment by GitHubRulesOK** [comment]
I used CTRL+O
but there is no point in testing older versions as they cant be updated, so issues can only be relevant to latest (pre-release) version. result was as expected NO warning for PDF under 32MB
![image](https://user-images.githubusercontent.com/12754913/103898813-6a8c8f80-50ed-11eb-838a-ae796e005c54.png)
Its different for the tiny epub that WILL throw a warning as described (**and become hidden by default windows behaviour**)
![image](https://user-images.githubusercontent.com/12754913/103899210-facad480-50ed-11eb-8bc5-708efafed195.png)
We can see from the taskbar the hidden window and can close it with the red X
![image](https://user-images.githubusercontent.com/12754913/103899657-9e1be980-50ee-11eb-953b-d149c6bea418.png)
![image](https://user-images.githubusercontent.com/12754913/103899866-f05d0a80-50ee-11eb-87ee-3cfd88ed72b5.png)

**Comment by zkosk** [comment]
The strange thing is now it won't warn the delete as you mentioned (open it in Chrome and Edge also doesn't lock the file), as a result I can't do this experiment easily anymore.

**Comment by GitHubRulesOK** [comment]
your older version would be subject to 10MB PDF file locking but latest version moved the boundary to only locking PDF of 32 MB or more

**Comment by zkosk** [comment]
quote "In my testing I WAS able to continue in SumatraPDF, so the question arises what version of SumatraPDF, what type of file (and file size) and exactly which shortcuts then did not work?"

Every shortcuts then did not work including ctrl+o. The problem is the system dialog, not the file. V3.1 but it should also exist in V3.2.

**Comment by GitHubRulesOK** [comment]
I only check current version behaviour for "regressions" That is  **does current pre-release behave worse than previous,** my rough experience was that in current pre-release (with the message hidden) I could continue to apply shortcuts. such as open another file etc.
Certainly not ideal as the Message should be acknowledged or cleared first.

**Comment by kjk** [comment]
No plans to investigate such edge cases.
