### ISSUE TITLE
Unusual behavior of SumatraPDF ver. 3.3.205 - 3.3.218 with specific corrupted pdf-file

### ISSUE THREAD

**Issue by jourmager** [sumatrapdfreader/sumatrapdf#1844]
https://gist.github.com/jourmager/5f32e61870af6f7e035b771150d12378
Title: Unusual behavior of SumatraPDF ver 3.3.205 - 3.3.218 with specific corrupted pdf-file
1) Platform:
Windows 10 Pro 64-bit, Version 20H2, Build 19042.685
Security: only built-in Windows 10 Security turn on by default: Virus & threat protection, Account Protection, Firewall & network protection, etc.
2) Steps to reproduce:
a) Run the application - SumatraPDF 64-bit portable (or install-version) ver. 3.3.205 - 3.3.218
b) open test pdf-file via:
- click on "Open a document" link on "Frequently Read" area of application, or
- Menu -> File -> Open, or
- shortcut Ctrl+O
3) Expected result:
a) specific test pdf-file has 52 pages and has corrupted file format (header, trailer, objects, xref, streams)
b) test pdf-file should be opened without problem
c) the application should display first 50 pages of the test pdf-file correctly
d) page 51 - the application should display the first quarter of page correctly, and the other three quarters - as a blue background
e) page 52:
- application display nothing, or
- application display blank page, or
- application display warning, that this page couldn't be displayed
4) Actual result:
a) We try to open test pdf-file
b) We see warning "Please wait - rendering"
c) Then, application crashed with notification: "We're sorry, SumatraPDF crashed. Press 'Cancel' to see crash report. OK/Cancel"
d) After pressing "Cancel" button, we have:
- folder "crashinfo" in application folder with files: sumatrapdfcrash.dmp, libmupdf.pdb, SumatraPDF.pdb, SumatraPDF-dll.pdb, sumatrapdfcrash.txt
- file sumatrapdfcrash.txt opened in Notepad
- page https://www.sumatrapdfreader.org/docs/Submit-crash-report.html opened in default internet browser
5) SumatraPDF ver. 3.3.205 - 3.3.218 has unusual behaivoir with such corrupted files, because this file was opened without problem and first 50 pages and one quarter of 51th page were displayed in release SumatraPDF 3.2, pre-release SumatraPDF 3.3.13112, daily SumatraPDF 3.3.13123-3.3.13180, MuPDF 1.18.0, Adobe Acrobat Reader DC 2019, Foxit Reader 10, Nitro Reader 5.5.9.2, PDF XChange Viewer 2.5 Free, STDU Viewer 1.6.375, Microsoft Edge 87, Opera 72.
6) Attachment: specific test pdf-file in zip-archive http://file.karelia.ru/ggt3kk/
P.S. this is my first bug report, and sorry for my poor english

**Comment by GitHubRulesOK** [comment]
@kjk 
I agree this file is severely corrupted, you will no doubt have noticed my attempts to clean it several ways failed.
MuPDF standalone does not crash but attempts to clean and save the result.
I also tried other automatic repair tools but without success in creating a version acceptable to SumatraPDF

The only way to stabilise appears to be deleting corrupted page 51 and so removing reference to non existent page 52, I get a 50 page file that loads instantly since its not trying to handle any corruptions.

**Comment by jourmager** [comment]
Sorry if I described my attempts poorly.
Sorry if I misunderstood you.
I, personally, have no problem opening this file. All my pdf viewers and editors (Adobe, Foxit, Nitro, Callas, etc.) render this file correctly, including SumatraPDF up to version 3.3.13180 - 50 pages and a quarter of 51.
I have problem with SumatraPDF ver 3.3.13205-13218 only.
I may be wrong, but in my opinion, changes were made in version 3.3.13205 (for example, update mupdf, change EnginePdf) that lead to the crash of the program and the inability to display this file.
I need release SumatraPDF 3.3 to work exactly like the rest of the pdf viewers and editors.

**Comment by GitHubRulesOK** [comment]
@jourmager 
please try again with daily build 3.3.12220 when it finishes hopefully in about one hour

**Comment by kjk** [comment]
@jourmager yes, this crash is a regression caused by recent changes to speed up loading of very large PDF documents. Thanks for reporting the bug

**Comment by GitHubRulesOK** [comment]
I can confirm all my corrupted test variants of that file do work in 3.3.13219
