### ISSUE TITLE
Right Clicking on .epub files does nothing

### ISSUE THREAD

**Issue by Trinidweller** [sumatrapdfreader/sumatrapdf#1845]
- Opening a .epub file then right clicking on any page in the document does not show a context menu
- Opening a .pdf or .cbr file then right clicking and the context menu shows.
- The reason for wanting the context menu on .epub files is because I need to add a page to the favorites section.
- Going into the "advanced options" then adding the .epub document page to favorites manually works like a charm.

**Comment by GitHubRulesOK** [comment]
In ebook mode pages are not static, thus favourite pages (and many other functions such as printing) become meaningless here is page 334
![image](https://user-images.githubusercontent.com/12754913/103158783-b79d6700-47b9-11eb-8ac7-8c193f2bb3b1.png)
or should it be 165 ?
![image](https://user-images.githubusercontent.com/12754913/103158788-ce43be00-47b9-11eb-8c5c-5f58cfff8db6.png)
However if we fix it as page 39 then its available as a favorite
![image](https://user-images.githubusercontent.com/12754913/103158799-0a771e80-47ba-11eb-953b-2f01b4cf89dc.png)
