### ISSUE TITLE
Chinese characters have obvious jagged

### ISSUE THREAD

**Issue by PaulHerrero** [sumatrapdfreader/sumatrapdf#1847]
![image](https://user-images.githubusercontent.com/56058332/103253658-036c2e00-49bd-11eb-9e52-b0a8cd56381e.png)

This is the effect of sumatrapdf

![image](https://user-images.githubusercontent.com/56058332/103253700-30204580-49bd-11eb-8f5f-0e053d9e1b50.png)

This is the effect of another reader

**Comment by GitHubRulesOK** [comment]
I am closing as can not progress without a sample file, so as  to see what can be having an effect.
SumatraPDF will linebreak when refowing as best it can, but in a case such as this it will vary from line to line, depending on font and height.
