### ISSUE TITLE
Three links 404

### ISSUE THREAD

**Issue by jaywhen** [sumatrapdfreader/sumatrapdf#1848]
```
version: v3.2 64-bit
```
**When click: menu->help->about**
In the **about** window，the following links are all 404：
- programming  ---> https://github.com/sumatrapdfreader/sumatrapdf/blob/3.2rel/AUTHORS
- translations     --->  https://github.com/sumatrapdfreader/sumatrapdf/blob/3.2rel/TRANSLATORS
- licences           ---> https://github.com/sumatrapdfreader/sumatrapdf/blob/3.2rel/AUTHORS

I think they might be like this:

- programming  ---> https://github.com/sumatrapdfreader/sumatrapdf/blob/master/AUTHORS
- translations     --->  https://github.com/sumatrapdfreader/sumatrapdf/blob/master/TRANSLATORS
- licences           ---> https://github.com/sumatrapdfreader/sumatrapdf/blob/master/AUTHORS

**Comment by GitHubRulesOK** [comment]
@kjk 
confirmed as occurred in 3.2 release, I think this was possibly raised previously and then corrected in pre-releases ?
perhaps worth adding those pages back retrospectively ?

**Comment by kjk** [comment]
Thanks, I mis-tagged in git. Fixed.
