### ISSUE TITLE
Add highlighting capability

### ISSUE THREAD

**Issue by airstrike** [sumatrapdfreader/sumatrapdf#185]
I know Sumatra PDF is proud of its very slim profile (which I love!), and everyone hates applications that take up system resources unnecessarily, so thank you for making such a great reader, and I ask you to consider my suggestion from an unbiased perspective.

Personally, one key functionality for dealing with PDFs is the ability to highlight and/or underline text. At work and in class, I often need to go through 20+-page documents and annotate them for later discussions. Unfortunately I am forced to resort to other applications when I'm in "edit mode", as opposed to just reading a file -- I often use Drawboard PDF or the native Reader app in Windows 8/10 in these cases. In Drawboard I use a yellow highlighter and a yellow "underliner", and I often annotate with the Surface Pro 3 stylus.

Has this issue been considered in the past, and, if so, what were the presented objections to it? Thank you again for an amazingly stable and fast piece of software. It's quite a relief to use it after years of being stuck with horribly slow PDF readers.

**Comment by Babbzzz** [comment]
That would be a great addition.

**Comment by drweb86** [comment]
I've attached mockups as i see that feature.
![selectionmockup](https://cloud.githubusercontent.com/assets/4712173/11095225/fdab92c8-88a4-11e5-85ec-94d8c1092e3d.png)
I propose to add 2 selection tools into application: text selection tool (1) and document part selection tool (2) with ability to select at least 2 colors: yellow and red. Text selection tool will be used most of the time so select important parts of the document, so it will be easier to read it as it is. Image selection is for scanned documents.
I also vote for saving that data inside PDF document in separate special part to support that scenario: several users has Sumatra installed, one mails entire PDF document to other user and other user sees it. Or a better variant: to make such things visible by all pdf readers.

Please consider adding ability to add review comments (as it is done in word) to selection documents in the same manner.

**Comment by airstrike** [comment]
If we're debating the actual looks of highlighted documents, I propose that the highlight effect be "behind" the text, so as not to color the actual text, but only the background.

When I need highlighting, I use Drawboard PDF. Here's what it looks like:

![c5zu36k](https://cloud.githubusercontent.com/assets/152812/11731815/e8e9384c-9f63-11e5-9ea5-ddd617b9b36f.png)

As you can see, it allows for underlining and highlighting as drweb86 proposed, with customizable colors, but only the background gets highlighted. It also allows for annotation, but that's a separate topic.

**Comment by kjmobile** [comment]
Finally, highlighting for Sumatra PDF is here !!
This works very well  [https://github.com/sumatrapdfreader/sumatrapdf/issues/747](url)

**Comment by Babbzzz** [comment]
Thank you very much.

**Comment by nod5** [comment]
Years ago I made sumatra_highlight_helper. It is a AutoHotkey helper script to add, remove and jump between different color highlights in Sumatra PDF reader.

I've now also put the code on GitHub https://github.com/nod5/sumatra_highlight_helper

Sumatra Highlight Helper is really "feature request ware". I hope someone likes the features and implements them into Sumatra PDF.

See also #103 and #746 for more on this topic

**Comment by GitHubRulesOK** [comment]
@kjk consolidate with #747 ?

**Comment by kjk** [comment]
Consolidate as #747

**Comment by Rik44444** [comment]
hi all, is there any chance of development of a function whereby we can doubleclick the highlighted sections and add a note for those sections? That would make Sumatra the ultimate pdf reader for me!

**Comment by GitHubRulesOK** [comment]
> hi all, is there any chance of development of a function whereby we can doubleclick the highlighted sections and add a note for those sections? That would make Sumatra the ultimate pdf reader for me!

**That has been for a long time the default for synctex users** you double click somewhere on the PDF page and it fires up the designated editor with the TeX file opened at that location so you can add more  notes etc. 
So it would take some significant modification to alter that historic function just to suit your average user.

A dummy synctex file can of course fire up notepad by default but if its not a valid one you will simply get the dreaded
 ```
No synchronization at this position
```
There are other ways to add any other shortcut to open a "My.pdf.notes" file in notepad,  WordPad or or better yet a programmable editor that could accept page number tags. Examples can be found in the forum try "wordpad" as a search term.
