### ISSUE TITLE
Overlapped buttions

### ISSUE THREAD

**Issue by Foooool** [sumatrapdfreader/sumatrapdf#1850]
When open several files, the close button of the last file will be overlapped by "Left/Right" button.
![image](https://user-images.githubusercontent.com/32285651/103337452-65f52500-4ab6-11eb-9be1-ec7fe4db8abd.png)

**Comment by GitHubRulesOK** [comment]
This issue is another duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/586/ consolidated as #447
