### ISSUE TITLE
it is export not found books to file.txt

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#1853]
it is export not found books to file.txt

![2021-01-06](https://user-images.githubusercontent.com/11432724/103707747-48492380-4fc0-11eb-85e4-1490b248a825.png)

**Comment by GitHubRulesOK** [comment]
Generally not a good idea to use punctuation in folder and filenames
However ###. ###, ###\###_.epub should not cause a not found message 
unless that file is no longer there, or the file system is confused
 so  is E: drive a NTFS File system?

**Comment by Aliaksandr3by** [comment]
I am working on Windows 10, there is no problem with size or special characters.
But if I rename file, or remove one, I forgot that it exist.
I would like to have a file that stored a list of not found files.
Or maybe, in "FileStates [	[ ]]", might be a mark that file has not found.
Ot other TAG: MISSING_FILES [ [] ];

Sorry for my English

**Comment by GitHubRulesOK** [comment]
The problem arises before SummatraPDF starts thus it is best to first use an external cmd file to read SumatraPDF-settings.txt and test for any invalid "FilePath = " from the forum example for saving tabs could be adapted to test all entries.

you probably have better tools but the windos way would be something like

 FIND "FilePath ="  "..\..\SumatraPDF-settings.txt" >%temp%\SaveFileList.txt
FOR /F ["options"] %variable IN (SaveFileList.txt) DO command [command-parameters]
start sumatrapdf.exe %*

**Comment by Aliaksandr3by** [comment]
I can use Python for it
But I think that if It is found statement IF in c++ that tests being exist files, you might add the missing file error in file, is not it?



code for test files in 'SumatraPDF-settings.txt'

```
import time
import os
import re
import ctypes  # An included library with Python install.

__FILE__ = 'SumatraPDF-settings.txt'
__ENCODING__ = 'utf-8-sig'

with open(__FILE__, 'r', encoding=__ENCODING__) as fileHandleRead:

    _lineIsReaded = True

    while _lineIsReaded:

        _lineIsReaded = fileHandleRead.readline()

        filePath = re.findall(r'^\t{4}FilePath\s\=\s(.*)$', _lineIsReaded)

        if len(filePath) > 0:

            if os.path.isfile(filePath[0]):
                print(filePath[0])
            else:
                ctypes.windll.user32.MessageBoxW(0, filePath[0], 'Missing', 0)

time.sleep(3)

```

**Comment by Aliaksandr3by** [comment]
Maybe here?

![image](https://user-images.githubusercontent.com/11432724/103716343-d67ad500-4fd3-11eb-9e41-97f1cae6b13c.png)

**Comment by GitHubRulesOK** [comment]
OK your Python code looks good\t(4) reported session data had no errors
 but \t(2)  for all files reported one I know I had previously deleted, so good catch
![image](https://user-images.githubusercontent.com/12754913/103718804-872aa980-4fbf-11eb-90f9-450a961fdf76.png)

You may note that just before the section you highlighted that SumatraPDF will try to "fix" some missing files when it starts, I have not tested that heavily I would hope if folder moves between drives e.g.. C: changes to D: that would work for session  but it did not do so for me ! so best to use an app such as your python code to also perhaps fix missing links if its important.

**Comment by Aliaksandr3by** [comment]
My code is only examining the"SessionData [", where there are the 4*tab symbol.
The "FileStates" text my code in not examine.

Oh, I understand. 
I think this issue could get closed.
Thx.

```
import time
import os
import re
import ctypes  # An included library with Python install.

__FILE__ = './SumatraPDF-settings.txt'
__ENCODING__ = 'utf-8-sig'
TITLE = ''
count = 0
count_missing = 0

with open(__FILE__, 'r', encoding=__ENCODING__) as fileHandleRead:

    _lineIsReaded = True

    while _lineIsReaded:

        _lineIsReaded = fileHandleRead.readline()

        if len(re.findall(r'^FileStates.*$', _lineIsReaded)) > 0:  TITLE = 'FileStates'
        if len(re.findall(r'^SessionData.*$', _lineIsReaded)) > 0:  TITLE = 'SessionData'

        filePath_FileStates = re.findall(
            r'^\t{2}FilePath\s\=\s(.*)$', _lineIsReaded)
        filePath_SessionData = re.findall(
            r'^\t{4}FilePath\s\=\s(.*)$', _lineIsReaded)

        if len(filePath_FileStates or filePath_SessionData) > 0:

            filePath = filePath_FileStates if len(
                filePath_FileStates) > 0 else filePath_SessionData

            if os.path.isfile(filePath[0]):
                count += 1
                print(f'{count} {filePath[0]}')
            else:
                count_missing += 1
                print(f'{count_missing} {filePath[0]}')
                ctypes.windll.user32.MessageBoxW(
                    0, filePath[0], f'{count_missing} Missing {TITLE}', 0)

time.sleep(5)

```

**Comment by Aliaksandr3by** [comment]
the script for finding a missing books in many folders;

```
import os
import re
import sys
import logging


def file_executer(__file_folder__):

    filePathCollector = []

    with open(f'{__file_folder__}/SumatraPDF-settings.txt', 'r', encoding='utf-8-sig') as fileHandleRead:

        title = ''
        count = 0
        count_missing = 0
        _lineIsReaded = True

        while _lineIsReaded:

            _lineIsReaded = fileHandleRead.readline()

            if len(re.findall(r'^FileStates.*$', _lineIsReaded)) > 0:
                title = 'FileStates'

            if len(re.findall(r'^SessionData.*$', _lineIsReaded)) > 0:
                title = 'SessionData'

            filePath_FileStates = re.findall(r'^\t{2}FilePath\s\=\s(.*)$', _lineIsReaded)
            filePath_SessionData = re.findall(r'^\t{4}FilePath\s\=\s(.*)$', _lineIsReaded)

            if len(filePath_FileStates) > 0 or len(filePath_SessionData) > 0:

                filePath = filePath_FileStates if len(filePath_FileStates) > 0 else filePath_SessionData

                if os.path.isfile(filePath[0]):
                    count += 1
                    #print(f'{title} {count}:\t{filePath[0]}')
                else:
                    count_missing += 1
                    #print(f'MISSSING {title}:\t{count_missing} {filePath[0]}')
                    if len(filePath_SessionData) > 0:
                        filePathCollector.append(filePath[0])
                        print(f'MISSSING {title}: {filePath[0]}')

    return filePathCollector


def main(*argv):
    try:
        print("The script has the name %s" % (sys.argv[0]))

        if len(sys.argv) == 2:
            __file_folder__ = "./" + sys.argv[1]
            print("argv %s" % (sys.argv[1]))
            with open('./MISSSING.txt', 'w', encoding='utf-8-sig') as f1:
                for item in file_executer(__file_folder__):
                    f1.write(item+'\r\n')

        if len(sys.argv) == 1:
            for items in os.listdir('./'):
                if items.find('.') < 0:
                    if os.path.isdir(items):
                        print(f'{items}')
                        with open('./MISSSING.txt', 'a', encoding='utf-8-sig', newline='\r\n') as f2:
                            for item in file_executer(items):
                                f2.writelines(item + '\r\n' )

        input("Press Enter to continue...")

    except IndexError:
        logging.error(IndexError)
        sys.exit(2)
        input("Press Enter to continue...")


main(sys.argv)


```

**Comment by kjk** [comment]
doesn't look like a sumatra issue

**Comment by GitHubRulesOK** [comment]
@kjk the issue is created by SumatraPDF having a history feature with few user means to manage apart from delete. There are related bugs raised against .MuPDF.history

One recent reason not to autodelete missing files is say for example someone waits ages for a remote file. at that point SumatraPDF may be told the file is available an attempt to open, Then some aggressive Anti-virus may temporarily make the file unavailable. but then the missing entry miraculously becomes available again.

It is more common that all the dead entries are just that i.e. now DEAD, but deletion should be optionally determined by the user
