### ISSUE TITLE
Compilation of V3.2 VS2019 project failed for code page issues

### ISSUE THREAD

**Issue by zkosk** [sumatrapdfreader/sumatrapdf#1854]
V3.1 compiles fine but V3.2 failed with code page issues (warning C4819 then error C2220) when the local code page is not the code page for the English version of Windows 10.

The reason is that alghouth some program like notepad.exe can not only detect utf-8 by the 2 byte prefix in the file, but also by a scan of the full file, but Visual Studio can only detect utf-8 by the 2 byte prefix. [https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-160](url)

Many file in the V3.2 source is utf-8 but without the 2 byte prefix.

Solution:

1. Not verified: Add prefix to the sources.
or
2. Verified: Add /utf-8 to compilation options (how to add this flag to all the projects easily?)

List of projects that need /utf-8:

Freetype-opt
Harfbuzz-opt
Mupdf-opt
Harfbuzz
Mujs
Sumatrapdf-dll

**Comment by GitHubRulesOK** [comment]
Since I do not compile, I am likely not giving the true answer.
SumatraPDF uses many 3rd party files, some with BOM, some without thus Code page warnings are ignored in pre-make
Certainly 4819 was blocked in both current version and in previous stable 3.1.2 but I don't see it clearly listed against 3.2 so it may be you simply need to add it into your list, as others have done
see https://github.com/sumatrapdfreader/sumatrapdf/search?q=4819&type=commits for the two I found and follow this link to see  more recent commits/fix
https://github.com/sumatrapdfreader/sumatrapdf/search?q=4819&type=issues 

For 2220 you will need to wait for the programmer @kjk to reply

**Comment by zkosk** [comment]
As I tried, disable warning doesn't work, other stringe compilation error will follow.

**Comment by GitHubRulesOK** [comment]
The "foreign" regular compiler who encounters similar issues including C2220 is victorvg who uses his own methods to compile so worth checking out his experiences see https://github.com/sumatrapdfreader/sumatrapdf/search?q=victorvg&type=issues and look at his git hub build chain which is linked somewhere in those comments

**Comment by GitHubRulesOK** [comment]
I found link to latest of victors build kit at https://github.com/VictorVG/Source/releases/tag/SPDFTK-1.7.4

**Comment by zkosk** [comment]
After adding /utf-8 to serveral error projects and success in the build project sequence, finally utils/engines/test_util/makelzsa all failed with such messages:

sumatrapdf-3.2\src\utils\Vec.h(745,25): error C3861: 'gWindows': identifier not found

 /utf-8 won't fix them. Not sure whether these are code page related.

**Comment by GitHubRulesOK** [comment]
I have in the past compiled the test util but its not needed for main program so it looks like you are compiling ALL sub projects rather than just the core one

**Comment by zkosk** [comment]
I'm only compiling the core one - one by one based on the build sequence list.

**Comment by zkosk** [comment]
Is 3.2 rel the same as 3.2?

**Comment by GitHubRulesOK** [comment]
3.2.rel should be the final stable / public release of all 3.2 versions
currently we are in 3.3 pre-release versions but the  next release **was** slated as 3.2.1

**Comment by zkosk** [comment]
I thought I was using 3.2 instead of 3.2rel only based on the file date 2020.3.15 in the zip file and 3.2rel is release on April. Can I identify between 3.2 and 3.2rel from the content of the source zip file?

**Comment by zkosk** [comment]
Based on the error message mentioned, I checked Vec.h:

`// remove el from a vector
template <typename T>
void vectorRemove(std::vector<T>& v, const T el) {
    auto b = std::begin(gWindows);
    auto e = std::end(gWindows);
    // TODO: does it work if element doesn't exist in vector?
    v.erase(std::remove(b, e, el), e);
}`

Why is there "gWindows" in such a place? Replace gWindows with v remove that error (but there is still a lot of other errors).

**Comment by GitHubRulesOK** [comment]
reference your comment on versions, I dont know which ones you are accessing I guess its those from
https://github.com/sumatrapdfreader/sumatrapdf/releases but agree the latest date seems wrong.
The **master** branch is normally the current daily 
But some historic release versions are stored at other locations so the 3.2 branch as at 3rd April may be the one at https://github.com/sumatrapdfreader/sumatrapdf/tree/rel3.2working
The recommended way to build is outlined at https://www.sumatrapdfreader.org/docs/Our-build-system.html

**Comment by zkosk** [comment]
Although vectorRemove is not there anymore, but for curiocity, how can the above v->gWindows "bug" happen?

**Comment by kjk** [comment]
The recommended approach is to disable the warning on relevant projects.

But for old versions of the code you're on your own.

I'm only really interested in issues in master branch.

**Comment by zkosk** [comment]
@kjk Guess they also exist on master, I'll try master later.

**Comment by zkosk** [comment]
@GitHubRulesOK @kjk Are there other ways to download the source like torrents or mirrors? I'v been failling to download master  or 3.2rel since last night, either zip or git clone, all failed after several MB at a speed of 10KB/s.

**Comment by GitHubRulesOK** [comment]
I just tried master and it took less than 10 seconds for the 72Mb
https://github.com/sumatrapdfreader/sumatrapdf/archive/master.zip

**Comment by zkosk** [comment]
The problem is the speed is not the same from differenct location in the world. At the same time I'm downloading 2020-12 version of wiki zim with peak of 166M.

**Comment by GitHubRulesOK** [comment]
I am the otherside of the world from USA so there must be some mirroring as the distance does not affect me it should have been a few seconds as many times over 7MB/s but most of my download time may have been anti-virus checking

**Comment by GitHubRulesOK** [comment]
You can check each country flag at https://downdetector.com/status/github/
and there was some recent pland maintenance as shown at https://www.githubstatus.com/history

**Comment by zkosk** [comment]
Its just failure in the middle of the download. Suprised to know that git doesn't support to continue the last download.
