### ISSUE TITLE
C++ language version

### ISSUE THREAD

**Issue by zkosk** [sumatrapdfreader/sumatrapdf#1855]
In V3.2, for some projects the C++ language is 
Preview - Features from the Latest C++ Working Draft (/std:c++latest)
which produce a lot of strange build error.
Change the version to 
ISO C++17 Standard (/std:c++17)
solves the problems.

Project list:
Utils
Pdffilter
Pdfpreview
Enginies
Test_util
Makelzsa
Sumatrapdf-dll
Sumatrapdf

**Comment by kjk** [comment]
Those kinds of issues are only relevant for latest code in github master.
