### ISSUE TITLE
Add 'CloseAfterLaunch' line to ExternalViewers mechanism

### ISSUE THREAD

**Issue by Marmotian** [sumatrapdfreader/sumatrapdf#1857]
The current method for opening a file in an external viewer uses this data structure:
`
ExternalViewers [
	[

		CommandLine = <path>\MyProgramOrScript "%1"
		Name = MyWhizbangThing
		Filter = *.pdf;...
	]
]
`

I propose adding another line, and the necessary code to perform the function:
`
ExternalViewers [
	[

		CommandLine = <path>\MyProgramOrScript "%1"
		Name = MyWhizbangThing
		Filter = *.pdf;...
		CloseAfterLaunch = (no|tab_only|window_if_last_tab|window)
	]
]
`

The problem I encounter is that if the current file is _really_ big, the external program will get an error if it tries to write to it, move it, or delete it. I have dealt with this issue so far by always using a script to launch my "viewer" and including a delay of several seconds to give me time to close the Sumatra window.

I have also found previously with Windows that closing the file may not be sufficient to unlock access to it. I'm not a Windows programmer so I don't know why this is, but closing the window is the only way I've found to bypass this issue. This is why I have included 4 options instead of just (yes|no).

I apologize if there is a separate method for making feature requests as I couldn't find it.

**Comment by GitHubRulesOK** [comment]
The variation in behaviour is that one app that locks a file should "block" another until released, BUT for pdf compilers that use SumatraPDF whilst editing there needs to be common access, so in the past 0-10MB pdfs are not locked and in recent versions the range is 0-32MB.
Primarily file locking is a windows controlled behaviour.
Normally when using an "ExternalViewer" it is only for viewing thus the conflict should not arise. Using it to call scripts for more than simple viewing is beyond its intended scope (but I do use it heavily for other functions)

One dirty possibility ( if you just need to exit SumatraPDF) is to use a TaskKill command, but you need to understand the consequential implications in your workflow for the next start-up step.
The cleaner approach I usually use in some such cases is to use the active filename to make a copy of file , act upon that, then read back the copy, however that does not free up the first active file.

SumatraPDF does not have a way to programmatically close currently viewed file but using an autohotkey.ahk to simply close the tab should work
It helps to know how you are abusing the current feature, to give any better workaround.

**Comment by Marmotian** [comment]
What my script currently does is either delete or recycle the file I'm viewing, using 2 different "viewer" menu entries. I'm going to modify it to also extract the document name stored in "Properties" (if present) and offer to rename the file to that as well as setting the datestamp to the "Modified" date, and then move it to one of several directories. Most/all of these operations require the file to be unlocked for them to succeed. 

I do this because I download a lot of datasheets from manufacturers while looking for the right part to use in a design. The manufacturers usually give them totally cryptic filenames and I need to have a usable name if I decide the part warrants further investigation. Many times, a quick look at the file tells me that it isn't what I need so I want to get rid of it quickly and easily -- hence the "Delete" option. Occasionally, I won't be completely sure it isn't useful so those I recycle.

Now that I know the file won't be locked if it's less than 32 MB, I can check the file size and then issue a warning to close the file before proceeding.

**Comment by GitHubRulesOK** [comment]
You cant drag a file to a subfolder but Sumatra F2 allows to "rename" open files
which could possibly include adding an action prefix to delete-me-later with a shorter mnemonic **del-**...rubbish.epub or pdf etc.

**Comment by kjk** [comment]
Sorry but this seems like extremely niche functionality. Too much effort to implement.

**Comment by GitHubRulesOK** [comment]
@kjk 
agreed the request here is niche BUT one of the reasons SumatraPDF is favoured over Acrobat or Foxit by the PDFLaTeX community is the relaxation of file locking, Acrobat and previously Foxit were notorious for blocking PDF previews whilst compiling. If I recall correctly there were multiple 3rd party solutions built to work around Acrobat not having e.g. a DDE close file command. (Also I think the semi-related issues of holding file open after print)
As users build larger and more complex PDF outputs, the pressure, in the wider community to find solutions that don't lock larger files is noticeable. I think Foxit may now have no size limit, thus is often proposed as a good solution in many cases

**Comment by Marmotian** [comment]
I'm just going to point out that the only reason I "misuse" this functionality is that a feature request from 5 years ago requesting that "Delete" functionality be added (#633) was never commented or acted on by anyone other than me.

**Comment by GitHubRulesOK** [comment]
@Marmotian
I agree such a function would be very useful, and having now seeing your other post, I will make an appropriate suggestion there.
