### ISSUE TITLE
Selection color also changes text color

### ISSUE THREAD

**Issue by ASHIT-AXAR** [sumatrapdfreader/sumatrapdf#1858]
selection color also changes text color. is this ok?

![sumatra1](https://user-images.githubusercontent.com/24279964/104363477-7f708500-552a-11eb-86fd-cf62a5934f72.jpg)

![sumatra](https://user-images.githubusercontent.com/24279964/104363500-826b7580-552a-11eb-99f9-b90593cf29cd.jpg)

im not sure if fixing this is as simple as just changing something like "Paint Event Order"
( background > textcolor > selectioncolor) -> (background > selectioncolor > textcolor) or requires more workaround.
also selected text has a border color which makes it harder for eyes to read.

**Comment by kjk** [comment]
No plans to change that.
