### ISSUE TITLE
color mixture when using sumatra to display tikzfigures drawed by TikZ (LaTeX)

### ISSUE THREAD

**Issue by Luobin-Lin** [sumatrapdfreader/sumatrapdf#1859]
I prefer using the background color #c7edcc than the default one #ffffff for PDF reading. However, when displaying tikzfigures drawed by TikZ(LaTeX), the background color #c7edcc of Sumatra would affect the original color of the tikzfigures.

How can I fix this? Or it is a bug remaining to be solved?

**Comment by GitHubRulesOK** [comment]
foreground/background are not exactly as written on the tin, they are range upper colour and range lower colour so once they shift from max /min rgb all colours are automatically affected.

**Comment by GitHubRulesOK** [comment]
Without sample to deny I am going to assume this is the common issue of modified colours
![image](https://user-images.githubusercontent.com/12754913/124855328-b5099e80-dfa0-11eb-813e-cf34ec66cacf.png)
