### ISSUE TITLE
Could not obtain Printer properties

### ISSUE THREAD

**Issue by jtaylorme** [sumatrapdfreader/sumatrapdf#1864]
What would cause the message "Could not obtain Printer properties"?  I have it popping up on a couple of machines.   Rebooting fixed it temporarily but it is back and being persistent.   I am using the latest version.

Thanks.

**Comment by GitHubRulesOK** [comment]
"Latest Version" is too Woolly 
is it 3.2 or 3.3,pre-release (if so which version)

**Comment by jtaylorme** [comment]
Sorry.   3.2

**Comment by jtaylorme** [comment]
3.2 was the first version I have used.

**Comment by GitHubRulesOK** [comment]
There was a significant recent change in pre-release so needed to check that was not the reason.
Perhaps worth trying a portable copy of 64bit https://www.sumatrapdfreader.org/dailybuilds.html which includes those changes However I suspect it is not SumatraPDF but Windows spooler that is causing such issues

**Comment by GitHubRulesOK** [comment]
Windows has an option to "let windows control my printer" which may be having an effect so worth testing for a while with it both on and off

**Comment by jtaylorme** [comment]
Will give those two things a try.   Just couldn't find anyone reporting this issue anywhere.

Thanks.

**Comment by GitHubRulesOK** [comment]
Constant blocking of getting properties would indicate a user authorisation issue for one or more printers, which would then be "intermittent" if the default was being changed i.e. by "Allow windows..."
Intermittent across multiple users and or multiple printers makes it harder to pinpoint if that could be a cause.

If it is down to one printer driver then either an update / downgrade / uninstall/reinstall driver could possibly help.

My default printer is always set to MS print to PDF although I have a Physical HP printer and as Admin I thus have no restriction on getting its properties (or any the other of several print drivers installed when called.)

**Comment by jtaylorme** [comment]
Thanks again.   If I find anything definitive I will post back.

**Comment by kjk** [comment]
We show this message when `DocumentProperties()` Windows function fails. I don't know why it would fail but that's coming from Windows so there's nothing I can do about it.
