### ISSUE TITLE
Support for custom text and background color

### ISSUE THREAD

**Issue by zkosk** [sumatrapdfreader/sumatrapdf#1866]
At least a support for white-black exchange, useful for books that doesn't have color? For eye protection? 

For example a gray scale reverse (R,G,B)->(255-R,255-G,255-B), but does colored subpixel rendering still looks good after this transformation?

**Comment by GitHubRulesOK** [comment]
Those requests were covered by Deprecated options see https://www.sumatrapdfreader.org/docs/Command-line-arguments.html
white-black exchange = `-invert-colors` command which is toggle to `-set-color-range #ffffff #000000`
both are replaced by using advanced settings. and subpixel colour range should thus correctly be affected (reversed)

**Comment by GitHubRulesOK** [comment]
Closing as inversion requests and its "negative" effects are covered by numerous other issues.
