### ISSUE TITLE
Is there any place where I can download the previous pre-release version of SumatraPDF installers?

### ISSUE THREAD

**Issue by WangYihang** [sumatrapdfreader/sumatrapdf#1867]
Hi, 
I am a deep user of your excellent pdf viewing software SumatraPDF, I really appreciate that you guys have developed such a small, quick, and elegant software. Especially, the annotation feature is the most functionality I have used. But when I update SumatraPDF to the latest version, I found that I cannot save highlighted area into the separated `.smx` file, instead, all highlights will be saved into the original PDF file.

I spent almost the whole night figuring out how to revert my SumatraPDF version, but I forgot the version I previously used (the only thing that I remember is that it is a prerelease version I downloaded approximately in 2019 Dec).

After reading the official website, I found there is a web page(https://www.sumatrapdfreader.org/download-prev.html) where users can download the previous version, but these versions are too old I guess, cause when I installed version `3.1.2`, nothing happens after I select a sentence and press `a`.

Also, I tried to download all daily builds from OSS services like DigitalOcean and AmazonAWS, I can only download the versions after 
 `SumatraPDF-prerel-13182-64-install.exe` which released on 2020-11-06 at most, the earlier version seems to have been deleted...

The filenames I downloaded from DigitalOcean stored in Ubuntu Pastebin (https://paste.ubuntu.com/p/q7gBjwW2Bx/)

Besides, I found @GitHubRulesOK mentioned in [highlighting-removal-after-saving](https://forum.sumatrapdfreader.org/t/highlighting-removal-after-saving/433/10): 

> [LATER EDIT] This thread is now locked as the experimental Sumatrapdf Meta eXtension a.k.a. SMX feature has been retired. It is replaced in the latest Pre-Releases by newer, more extensive PDF annotations features.

This feature is great and it's so important to me, but I cannot find any other alternatives, so please help me. 

My questions are:

* Is there any place I can download previous daily builds or prerelease installers
* Could you guys please tell me after which version/git commit the SMX feature has been removed (so I can check out the version and build manually)

**Comment by GitHubRulesOK** [comment]
The official line is likely to be there is no source of old pre-release binaries (you would need to retro recompile an older development version) There are of course a few lurking in the WorldWideWeb but beware if easily found they are very likely to be offered with unwelcome payloads. You have followed some of my forum comments and therein is a hint of one previous clean pre-release but for obvious reasons I cant give a direct link.

There is a direct link within these issues to an older developer (zeniko) copy But it **is very old so uses H for adding** to .smx

I have come to accept that I need to keep two copies of a pdf (one archived without highlights and one with permanent highlights/additions that can be easily deleted) But I still use smx for highlighting non pdf files.

@kjk the continued creating of smx entries is clearly to be discouraged, and providing any historic pre-release with known bugs could create unwanted problems but an official copy of last one around 3.3.12458-13011 with proviso "bugs may/will be present" could help such edge case users. Just unsure how to avoid bulk downloaders
![image](https://user-images.githubusercontent.com/12754913/105384267-e7e5f300-5c09-11eb-863a-2974e2d11aaf.png)

**Comment by kjk** [comment]
There's no support for downloading older pre-release versions.

You can probably look through checkins to see when .smx support was removed.
