### ISSUE TITLE
UAC control

### ISSUE THREAD

**Issue by debjan** [sumatrapdfreader/sumatrapdf#187]
Well hi again,

if I open document 1 as Admin and try to open another document 2 as a user Sumpatrapdf doesn't load document 2.
If I load document 1 as a user and then open another document 2 as Admin it is fine.

Hope this is not as expected.

Thanks

**Comment by kjk** [comment]
Can you provide more details about the first scenario? How exactly are you running Sumatra, how are you opening the files (File/Open menu? drag&drop?), what are the error messages you're getting etc.

**Comment by debjan** [comment]
I open "Document 1" with double-click, from totalcmd run as Admin. Then I open "Document 2" as User (i.e. double-click in Explorer). Result is that "Document 2" does not open, and there are no error messages.

**Comment by kjk** [comment]
This is how Windows works. We use a single process by default. The first time you run Sumatra as admin it runs as privileged process. When you do it again as a user, a non-privileged process tries to communicate with privileged process and that's not allowed.
