### ISSUE TITLE
Wrong page for highlighting (annotation) when focus between page

### ISSUE THREAD

**Issue by taooceros** [sumatrapdfreader/sumatrapdf#1871]
The annotation system gets the wrong page when the focus is between two page.
![image](https://user-images.githubusercontent.com/45326534/106169524-5237ef80-6144-11eb-883c-306b98d0cb79.png)
For example, when I click `a` to highlight the text I select, it will highlight the text in the next page on the same place.

**Comment by GitHubRulesOK** [comment]
That will only occur when two pages are active. Highlight should be saved to the one that is shown in the page indicator.
Has been a problem identified in the past with third-party highlighting, thus it could be a page before or after or to the left or right depending, the position of two or more pages.

The only way currently to ensure it is placed on the correct page is to be in single age mode. (easy to toggle on and off using the one page icon)

**Comment by GitHubRulesOK** [comment]
@kjk 
unsure how east this should be  since x y dy & dy appear correctly collected and applied it is just the page reference that is "wrong"

Closing as duplicated by https://github.com/sumatrapdfreader/sumatrapdf/issues/1806 and #1705
