### ISSUE TITLE
Main web site visual problems

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1873]
@kjk something has changed recently in serving images especially in discourse ?
Occasionally home page looks blank only showing top text then large white space so looks like there is nothing to link to as banner is limited

That is mainly in explorer both on windows 7 and 10 so guess its all explorer users

![image](https://user-images.githubusercontent.com/12754913/106363104-6afbfd00-631e-11eb-850a-9f14fc27ead3.png)

Equally forum looks less than modern but at least there navigation links are functional
 However note that user icons are now missing and that seems to affect Firefox and Chromedge as well

![image](https://user-images.githubusercontent.com/12754913/106363172-e6f64500-631e-11eb-9474-179b4e484f1b.png)

**Comment by GitHubRulesOK** [comment]
For the Discourse user images there is a time warp based on those that registered about 8 or more months ago

The few exceptions seem like me to have logged in within the last few days and thus in all probability replaced their missing avatars like I have done.

**Comment by kjk** [comment]
There were no changes to the website recently. The blank images in the website seem to be ie 11 issue but I have no idea what it is. ie 11 is not supported.

As to discourse, I do update it with latest code every couple of weeks but then I have no control over the changes.

**Comment by GitHubRulesOK** [comment]
What is an oddity using explorer is that the forum page supports navigation bar under the top banner which on main site only has donate active since there is no navigation bar to switch pages
