### ISSUE TITLE
crashes in DisplayModel::RotateBy while reading a Bengali e-book on windows 10

### ISSUE THREAD

**Issue by msayadurr** [sumatrapdfreader/sumatrapdf#1876]
Here is the gist link

https://gist.github.com/msayadurr/7edbac9e351d4c0a648e7ad8ab2be753

**Comment by kjk** [comment]
This is 3.2. 

Please see if it also crashes in latest daily build https://www.sumatrapdfreader.org/dailybuilds.html

If yes, please provide the file that crashes (if can't share publicly, you can e-mail it to kkowalczyk@gmail.com)

**Comment by kjk** [comment]
```
00007FF734F632AB 01:00000000000D22AB sumatrapdf.exe!DisplayModel::RotateBy+0x6b C:\Users\kjk\src\sumatrapdf\src\DisplayModel.cpp+1431
00007FF734FA5B2A 01:0000000000114B2A sumatrapdf.exe!WndProcFrame+0x54a C:\Users\kjk\src\sumatrapdf\src\SumatraPDF.cpp+4738
```

**Comment by kjk** [comment]
Can't do much without being able to reproduce the crash locally.
