### ISSUE TITLE
get back to previous viewed page

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#1877]
if I on mistakes click on link, I gone from the reading page and want get back to previous viewed page;
I forgotten the number page which was reading.
I would like to have a feature, like the FoxitReader has
![image](https://user-images.githubusercontent.com/11432724/106552701-d7e2e300-6528-11eb-9bbe-40e61c7e12c9.png)

**Comment by GitHubRulesOK** [comment]
Previous view should be exactly the same as you show in acrobat please check those keys on your keyboard are working.
From Manual
<kbd> Alt </kbd> + Left | go back (=Previous view)
-- | --
<kbd> Alt </kbd> + Right | go forward

There are no icons (have been requested multiple times)
