### ISSUE TITLE
CBZ/CBR/CB7 Thumbnail Cover?

### ISSUE THREAD

**Issue by DReaper** [sumatrapdfreader/sumatrapdf#1879]
During installation, there's an option to show thumbnail covers for .pdf files. Is it possible to have other formats supported too, like CBZ/CBR/CB7, which are comic book based? Thank you.

**Comment by GitHubRulesOK** [comment]
The feature has been there for some time, but is disabled in Formal or Pre-Release (you would need to compile your own copy with the correct flags enabled / not disabled). There have on intermittent occasions, been issues for one example see https://github.com/sumatrapdfreader/sumatrapdf/issues/1718 that in part may still be there for the odd format e.g. some CBR variants seem to cause problems. Whilst fairly stable at present, it has always been held back for several reasons some related to association such as icons, but that is not the most pressing problem.

I am closing this request as it is in effect part of open issue https://github.com/sumatrapdfreader/sumatrapdf/issues/1248#
