### ISSUE TITLE
Add support for .7z & .cb7 compressed files with images

### ISSUE THREAD

**Issue by Guibuu** [sumatrapdfreader/sumatrapdf#188]
SumatraPDF currently supports .zip, .rar, and comic book .cbz and .cbr compressed files with images. It would be nice if it also add support to **.7z** and **.cb7** files.

This has been [requested](http://forums.fofou.org/sumatrapdf/topic?id=2108323) [in the](http://forums.fofou.org/sumatrapdf/topic?id=3183782) [past](http://forums.fofou.org/sumatrapdf/topic?id=2690325) by other users.

[LZMA SDK](http://www.7-zip.org/sdk.html) is placed in the public domain.

Thanks.

**Comment by SumatraPeter** [comment]
I suppose the program can also add support for these file types via the optional addition of 7z.dll / 7za.dll / 7zxa.dll, just as it now supports the optional addition of unrar.dll / unrar64.dll.

**Comment by GitHubRulesOK** [comment]
@kjk not sure when this format was suported but is working in current pre-release 

simply extract images.cb7 from inside this .zip
[images.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3947939/images.zip)

**Comment by kjk** [comment]
Like @GitHubRulesOK said, *.cb7 format is supported in 3.1.2 and above.
