### ISSUE TITLE
Feature request: Add CTRL + SHIFT + T - Reopen last tab

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [sumatrapdfreader/sumatrapdf#1881]
Multi tab applications (google chrome / firefox) use these shortcuts:
CTRL + W -> Close current tab (sumatra OK);
CTRL + W -> Close application (Sumatra not OK, but it has CTRL +Q / Alt + F4, so this is OK);
CTRL + T -> Open new blank tab (Sumatra does nothing, but that is ok);
__CTRL + SHIFT + T -> Reopen recently closed tab (document) <- I miss this shortcut.__

Reopen last used tab could also be tied to CTRL + Shift + W, because CTRL + W closes it, but such shortcut would be different from firefox / chrome, so it is advisable to stick with __CTRL + SHIFT + T = Reopen recent document / tab__.

**Comment by GitHubRulesOK** [comment]
Closing as duplicate (cross link will consolidate) with wider discussion in https://github.com/sumatrapdfreader/sumatrapdf/issues/788
