### ISSUE TITLE
Feature request: Implement "Drag tab to open in new window"

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [sumatrapdfreader/sumatrapdf#1882]
Popular apps (chrome / firefox) supports opening active tab in new window when tab is grabbed and dragged out from tab bar. This would be a neat feature for sumatra: Grab pdf tab, move to 2nd display -> Have two instances of reader.

**Comment by GitHubRulesOK** [comment]
Second New instance with or without current document is possible via control [shift] <kbd>N</kbd>
Larger task long term task of tearing off tabs has been attempted but "frozen" and is covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/18
