### ISSUE TITLE
[Feature request] Add tooltip with full filename when hovering over tabs

### ISSUE THREAD

**Issue by vlakoff** [sumatrapdfreader/sumatrapdf#1884]
Title says it all :)

Long filenames don't fit in the tabs, so they are cropped with trailing dots ("...").
As many softwares do, we could display a tooltip with the full filename when hovering over the tab.

**Comment by GitHubRulesOK** [comment]
Long time request from when tabs were first added, earliest duplicated request https://github.com/sumatrapdfreader/sumatrapdf/issues/336 so closing as duplicate of currently open https://github.com/sumatrapdfreader/sumatrapdf/issues/1188
