### ISSUE TITLE
Crash report related to vbkm

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1886]
Using New  bookmarks to attempt some known problems with a known suspected file [mackay_information_theory.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5973607/mackay_information_theory.pdf)
[known bookmark problem file.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/5973613/known.bookmark.problem.file.zip)

I hit a crash, so not unexpected but in the hope there is some value in avoiding repeated crashing here is crash report

[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/5973598/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
New bookmarks and .vbkm was experimental and will probably be removed. Too much work and there's lots of other things to do.
