### ISSUE TITLE
Wrong epub thumbnails displayed in windows explorer

### ISSUE THREAD

**Issue by Marvinoo** [sumatrapdfreader/sumatrapdf#1888]
I'm sorry if this was asked before or not but I searched and found nothing related. 
Could you please make the eBook files (.epub, etc..) shows correct thumbnails instead of the generic Pdf icon? will be awesome if it would generate epub thumbnails from the book covers. Thank you. 
![Screenshot 2021-02-16 161624](https://user-images.githubusercontent.com/45720537/108282030-92a9ec80-7189-11eb-8887-7deb5a782cdb.png)

**Comment by GitHubRulesOK** [comment]
I agree that searching for thumbnails returns 10 unrelated  open issues
https://github.com/sumatrapdfreader/sumatrapdf/search?q=thumbnails&state=open&type=issues

I am closing as this will almost certainly be duplicating a request in one of the 9 related to the previewer
https://github.com/sumatrapdfreader/sumatrapdf/search?q=previewer&state=open&type=issues

**Comment by Korb** [comment]
Workaround: use [DarkThumbs](https://github.com/fire-eggs/DarkThumbs). It supports displaying thumbnails for the following formats:

1. CBR Image Archives
2. CBZ Image Archives
3. EPUB ebooks
4. FB2 ebooks
5. Kindle ebooks (MOBL AZW, AZ'.'/3)
6. RAR Archives
7. ZIP Archives
8. 7z Archives
9. DJVU

**Comment by GitHubRulesOK** [comment]
@Korb 
The last 32 bit release was Jan 26, 2023 and has many key functions  / issues fixed since then so makes that version less useful 
![image](https://github.com/user-attachments/assets/279a047f-5178-4b90-8844-eec27a52bb01)

SumatraPDF still supports 32bit thus the one I have to stick with and cannot test DarkThumbs 2.0
