### ISSUE TITLE
Maybe missing font?

### ISSUE THREAD

**Issue by ErinaceusLinnaeus** [sumatrapdfreader/sumatrapdf#1889]
I have an issue with the two following books:
How to invent everything
Hitchhiker's guide to the galaxy.

Every page looks like in the screenshot.
All other books I have work perfectly fine.

![sumatra](https://user-images.githubusercontent.com/24620406/108403943-2c6bab00-7217-11eb-84a5-458016808b17.png)

**Comment by GitHubRulesOK** [comment]
Every copy can appear different so I do not know which version, language or source your file has
especially as cover pages appear to have been removed, for example this pirate copy with flaws in the bookmarks visually looks reasonable in Western English using default font Georgia.
![image](https://user-images.githubusercontent.com/12754913/108407859-380da080-721c-11eb-9465-94bb8c3942a5.png)
![image](https://user-images.githubusercontent.com/12754913/108407211-5757fe00-721b-11eb-9a1d-df6c0a0ac782.png)

For some embedded languages it can help to change to a more compatible font so depending on the language of the source file I might try an Eastern font

**Comment by GitHubRulesOK** [comment]
Closing since without a sample it appears to be either DRM encrypted or other non acceptable source file
