### ISSUE TITLE
SumatraPDF crash, pre-release v3.3.13112 64-bit win10 20H2 19042.804

### ISSUE THREAD

**Issue by zengdabo** [sumatrapdfreader/sumatrapdf#1890]
https://gist.github.com/zengdabo/464110c4dfe39e7641dc30288ea4fb1a

**Comment by kjk** [comment]
```
00007FF7FA583971 01:0000000000122971 sumatrapdf.exe
00007FF7FA669816 01:0000000000208816 sumatrapdf.exe
00007FFED9897034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FFEDB1DD241 01:000000000004C241 ntdll.dll!RtlUserThreadStart+0x21
```

Unfortunately, as you can see from the crash, there are no symbols because they failed to download
```
HttpGet: url: 'https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/prerel/SumatraPDF-prerel-13112-64.pdb.lzsa'
HttpGet: InternetReadFile failed
```

As a result, there's not enough information to investigate further.

**Comment by GitHubRulesOK** [comment]
@zengdabo 
to provide a valid debugger output the correct version.pdb files need to be accessed either when crashing or before
In 3.3.13112 pre-release 64-bit you can pre-down load for the next time you get a crash
![image](https://user-images.githubusercontent.com/12754913/108731944-000ca300-7525-11eb-93e0-e7ba16fe7031.png)
