### ISSUE TITLE
Zoom in value jumps between two values when max zoom is reached

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [sumatrapdfreader/sumatrapdf#1891]
Steps to reproduce:
1. Open PDF;
2. CTRL + Mouse wheel up, or click zoom in icon many times;
3. Zooming level begins to jump between "max" to "max -1" after maximum zoom level is reached;

![image](https://user-images.githubusercontent.com/46539653/108498280-51166000-72b5-11eb-83e3-09e8ede4bbfc.png)

https://user-images.githubusercontent.com/46539653/108498330-63909980-72b5-11eb-8cc4-a305b02bc8d6.mp4

**Comment by GitHubRulesOK** [comment]
@kjk 
This odd behaviour of alternating from max value (6400) to drop back to max custom/default lower (4800) has been there for some time so is most noticeable in default settings.
As a **workaround** if wishing to reduce visual effect it can be significantly reduced by adding 6399 as a custom value to fall-back to, but then seems to be affected by "pixel creep" (down and right) of some values,

**Comment by kjk** [comment]
I can't reproduce this: I've tested 3 PDF files and I just reach 6400 and stay there.

I'm reluctant to add fixes if I can't verify the fix.

Does it happen to you with every PDF file in every view?

Could you provide a sample PDF and more repro info (like: view used etc.).

**Comment by kjk** [comment]
I was only testing on max zoom, which didn't reproduce, but it did reproduce on min zoom.

**Comment by GitHubRulesOK** [comment]
Fixes my **Max** zoom problem (i had not noticed on Min, but had not been looking there closely :-)

**Comment by WhiteChairFromIkea** [comment]
Hi, neither MAX (happened on all pdfs in my setup) nor MIN (never experiences) jumping does not occur anymore in:
![image](https://user-images.githubusercontent.com/46539653/108667548-23fac500-74e2-11eb-814b-5c1cc54ba4d6.png)

Tested twice
