### ISSUE TITLE
Expanding the new external viewer auto-detections

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1897]
I note that Alt + F + F was suggested as a fast show in File Folder shortcut to access Del Key to delete the current file. (a useful feature)

With the exception of the mutual use of Alt + F +M for both xps=xpsview or chm=hh then there are normally no CLASHING shortcuts except for using Alt + F + F when any Foxit product is detected
I have removed Foxit so cant prove, but highly suspect, that would require in some users cases a different pair of key combinations
Alt + F + F + Enter + Del
or
Alt + F + F + F + Enter for Foxit

Whilst we are at it, Foxit historically had the ability like Edge to open ePub and print to Vector PDF but is now like Acrobat only good as external handler for PDF (or PDF.AI) so in general the same file filter on *.pdf makes sense

**However** Tracker eXchange has a range of file formats support (excepting eBooks/chm) to equal or better SumatraPDF so can allow say open MS office XPS and save to Vector PDF (one common web recommendation) thus if there was a `Not Chm | Not eBook` filter then almost any other file types could be enabled. (worst case Xchange could reject those it cant handle)
 
![image](https://user-images.githubusercontent.com/12754913/109726672-02b56b00-7bab-11eb-8754-a0b46b2d2446.png)

If SumatraPDF included say .MD as a .TXT extension then it would be easy to pass those (on occasion) to Xchange editor for Save as PDF when truer rendering is important
![image](https://user-images.githubusercontent.com/12754913/109727973-3f826180-7bad-11eb-8e68-2591a76b5459.png)

**Suggestion**
I hate to mention that a switch of hotkeys may be preferred, so keeping disruption minimal 
&Tracker PDF-XChange Viewer / Editor
Show in &Folder
Fox&It Reader / Phantom editor

**Comment by kjk** [comment]
I've made improvements to this. Has this been addressed?

**Comment by GitHubRulesOK** [comment]
I forgot to check recent combinations but note you seem to have currently
F= &folder (as requested/suggested) but I have no &Foxit installed to re-compare OP conflict
i =&in PDF exchange (unchanged)
T = free ? so could be used for Anno&tations (but I often try to use that myself 🙂 )

**Comment by GitHubRulesOK** [comment]
Closing as seems to be working well enough as is.
