### ISSUE TITLE
Sumatrapdf sets epubs set all text to bold

### ISSUE THREAD

**Issue by komawoyo** [sumatrapdfreader/sumatrapdf#1898]
This doesn't happen to all epubs I have but most of them. I'm using Literata font which shows all the text correctly in other epubs.
Left: Sumatrapdf 
Right: Google ebook reader
![109443858-9262ea00-79f0-11eb-9cb0-1f998d097443](https://user-images.githubusercontent.com/18315233/110247776-be1b2e00-7f22-11eb-9d35-ff966f2bf011.png)

[test.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6097538/test.zip)

**Comment by kjk** [comment]
This epub contains its own font files and complicated CSS that we currently don't support.
Probably won't get better until we switch epub to mupdf (currently we use our own mini-css and html renderer that isn't very capable).

**Comment by GitHubRulesOK** [comment]
@kjk I suggest closing as SumatraPDF with MuPDF is in this case is now comparable
![image](https://user-images.githubusercontent.com/12754913/129496025-ef6fe54f-8d16-4988-b00d-92160c5bab69.png)

**Comment by kjk** [comment]
@GitHubRulesOK thanks for verifying, closing as fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease
