### ISSUE TITLE
Redesign menu in tab mode

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#19]
The new menu in tab mode is a regression over regular menu in that it now takes more clicks to achieve actions.

The goal of redesign is to have the same functionality but with less clicks needed to achieve it.

Implementation-wise, it'll no longer be a menu, because it's too restrictive. It'll be a custom window that will behave like a pop-up.

Design-wise, a few ideas on how to achieve the goal:
- use good ideas from Chrome:
  - use the main design of how it looks like
  - put multiple items (like zoom controls, view controls) in a more compact form, on one line
- don't be afraid to use multiple columns. When users are looking at the menu, they are not looking at anything else, so we can use the whole space of the window to show the menu. See e.g. how amazon.com implements 2-level menus that don't require clicks to navigate
- see if can remove some menu items by making the functionality available in a different way e.g. toolbar

TBD: the exact layout of the menu.

**Comment by jjurkus** [comment]
I rather like the old menu, but this is incompatible with the tabbed mode. Is it possible these two can be used together?

**Comment by kjk** [comment]
Tabling it for now.
