### ISSUE TITLE
Page printed blank with flag -silent

### ISSUE THREAD

**Issue by iozuniga** [sumatrapdfreader/sumatrapdf#1902]
Hello, 

The third page is printed completely blank when using the -silent flag. For example:

sumatrapdf.exe -silent -exit-when-done-print-dialog %file%

It only happens on the 32 bits version of sumatrapdf.exe  version 3.2 dated on 03/15/2020 0:34

TIA. 

Regards,

**Comment by GitHubRulesOK** [comment]
Unshure why you need to be using silent as that only blocks you seeing any error message 

I get exactly the same seven pages with or without -silent

`SumatraPDF-3.2-32.exe -silent -exit-when-done -print-dialog "1-7.pdf"`
same result as
`SumatraPDF-3.2-32.exe -exit-when-done -print-dialog "1-7.pdf"`

**Comment by iozuniga** [comment]
> Unsure why you need to be using silent as that only blocks you seeing any error message
Because sumatraPdf.exe is launched from an application just for printing purposes. There is no need see the PDF file. 

> I get exactly the same seven pages with or without -silent
Digging a little bit more I see that the problem only arises when using Microsoft Print to PDF virtual printer version. 10.0.19041.1  (Windows 10). I tried with another PDF virtual printer (Wondershare) and it worked perfectly. Sorry to bother you with this.  My fault. BTW, is curious it only happens with the 32 bits version. 

Regards,

**Comment by GitHubRulesOK** [comment]
Try dialog without -silent you should only see the dialog  box ?
-silent stops you seeing the error dialogs (not a good idea)
I have not seen problems on win10x64 19042.867 or noticed any in the past using SumatraPDFx32bit when using MS print to PDF that's what I used to test

**Comment by iozuniga** [comment]
Ok. Thank you very much for your comments. BTW, congratulations for the great work!
Regards.

**Comment by GitHubRulesOK** [comment]
@iozuniga @kjk

Note there are now increasing reports that others are also now having similar problems, using copies that previously worked, last week, Sounds like MS monthly update nightmare, so you may wish to look at https://forum.sumatrapdfreader.org/t/printing-low-resolution-last-few-days/3764

**Comment by GitHubRulesOK** [comment]
Just an update that if others arrive here because of recent (March 2021) printing problems such as blank pages poor quality prints or even Blue Screen of Death please read the thread in the above link for the Windows updates needed to **Fix the MS March Updates ! **
