### ISSUE TITLE
Files do not print properly from with sumatra but will print with adobe-dc

### ISSUE THREAD

**Issue by bowcoastie** [sumatrapdfreader/sumatrapdf#1903]
Many times when I print a file that has any graphical content there are blank lines across the picture but the same file printed with Adobe Acrobat DC prints them properly. Thank you so much for the great PDF reader! I have attached a typical file that shows this behavior and a scanned copy of the print out by each viewer.

**Comment by bowcoastie** [comment]
[Sienna Door 1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6175786/Sienna.Door.1.pdf)
[Printed pages from adobe and sumatra.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6175793/Printed.pages.from.adobe.and.sumatra.pdf)

**Comment by GitHubRulesOK** [comment]
which version of SumatraPDF, how are you printing GUI or CLI
it is most likely I will not see that failure as I will not be using your printer driver, search for your maker such as HP and see if there are similar user problems

**Comment by bowcoastie** [comment]
Thank you for the suggestion. I tried it on a different printer and it worked as it should from Sumatra. I am printing from the GUI.

**Comment by GitHubRulesOK** [comment]
Some printer drivers cant handle the high memory requirements needed for the more basic graphics intensive method sumatraPDF uses since version 3.0 also there may be a current problem with Windows update this month ! 
In both cases it may help to use the older [32bit old portable version **3.0 zip**](https://www.sumatrapdfreader.org/download-prev.html) (try with and without the print as image setting)

**Comment by bowcoastie** [comment]
Thank you, I will try the 32 bit version a few hours from now.

**Comment by GitHubRulesOK** [comment]
The chances are your issue **is more likely with the driver for that printer**, so could see if there are alternative settings such as drop resolution or "optimisation" etc. or check for driver updates.
The issue with the March 2021 windows update is being hopefully resolved by yet more Microsoft updates so should eventually disappear.

**Comment by benryanau** [comment]
I'm seeing similar issues here. W10_21H1, Epson XP970, SumatraPDF Prerelease x64 v3.4.14221
Will try with some different page options and try and report back.

**Comment by GitHubRulesOK** [comment]
Closing as duplicate
like many others seems to be duplicate resource/timing problem with printing large volumes of pixels through windows drivers. So covered in https://github.com/sumatrapdfreader/sumatrapdf/issues/919 & https://github.com/sumatrapdfreader/sumatrapdf/issues/1312
