### ISSUE TITLE
Crash whilst testing vbkm and attempting to show context menu

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1905]
In testing #1904 
I naturally encountered some problems but got unexpected crashing.

You should note I was using a modified .vbkm enclosed whilst colors were inverted but that does not seem to be the cause as repeating in normal default colors also caused crash

The condition that seemed to trigger the crash was whilst viewing vbkm a right click to call up the context menu causes the crash

[sumatrapdfcrash (2).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6177637/sumatrapdfcrash.2.zip)

**Comment by kjk** [comment]
vbkm support is removed
