### ISSUE TITLE
Have to override arguments when install from winget

### ISSUE THREAD

**Issue by YsHaNgM** [sumatrapdfreader/sumatrapdf#1906]
`winget install -i SumatraPDF.SumatraPDF` jumps error: Either install it with -install option or use portable version. While successful install needs `winget install -i SumatraPDF.SumatraPDF --override -install`.

`winget` version: v0.2.10191 Preview

**Comment by GitHubRulesOK** [comment]
You will need to speak to Microsoft (the repository owners who write the download yaml 
Unfortunatly they did not RTFM (Read The File-commands Manual)

The only command needed is just -s for silent
Using /install /S will bork the expected intent of running installer hence I guess your need to override.

**Comment by YsHaNgM** [comment]
But run `winget install -s` will not be able to change install directory etc. I see what you mean. Although `winget install -i --override -install` seems to be trivial.

**Comment by kjk** [comment]
Nothing we can do in Sumatra
