### ISSUE TITLE
Crash whilst using plugin

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1907]
I don't wish to ask for anything that detracts from keeping the current -plugin functions as they are still heavily used by many other useful applications.

However I seemed to trigger a crash in latest version by what could either be desirable or possibly blocked as inappropriate usage.

What I was doing was using daily pre-release SumatraPDF as a plugin within a file manager to show it can add annotations via context. That seemed to work well as action is confined within the preview window. 

What failed was I tried to add the page as a favorite using context option (a potential security breach as it could later bypass confining the actions to the currently viewed file.) At that point it crashed.

[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6178459/sumatrapdfcrash.zip)

**Comment by GitHubRulesOK** [comment]
@kjk 
Red herrings ? I tried with a restrictions file to block related actions
However I seem to think that in plugin mode some restrictions are hard coded during compile thus the ini may be ignored ?

**Comment by kjk** [comment]
```
Crashed thread:
00007FF622C9C7E5
00007FF622C9DEC6
00007FF622C9E053
00007FF622CABA87
00007FF622C81AFC
00007FF622C826B6
00007FF825AEE858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FF825AEE299 01:000000000000D299 user32.dll!DispatchMessageW+0x259
```

no crash callstack, no way to make progress
