### ISSUE TITLE
Weird coloring in pdf generated with latex+tikz (countour filled), but only when visualized with sumatrapdf

### ISSUE THREAD

**Issue by NicolaDallaPozza** [sumatrapdfreader/sumatrapdf#1912]
I use TeXnicCenter (on a Windows machine) to produce pdf from latex sources, also employing the tikz/pgfplots package to create plots. After compiling the tex source with latex ( or with pdflatex) I usually visualize the pdf with SumatraPDF. 

In the following minimum working example (taken from https://tex.stackexchange.com/questions/310252/filled-contour-from-axis-symmetric-data  ) I get the filled-contour plot (on the left) with a weird colormap filling when visualized with SumatraPDF, but it is fine when visualized with other pdf viewers. Note that the other plot (only contour lines) is fine in SumatraPDF, as it always happened to me for other types of plots. 

\documentclass{standalone}
\usepackage{pgfplots}
\usepgfplotslibrary{colorbrewer}
\pgfplotsset{compat=1.14}
\begin{document}
    \begin{tikzpicture}
        \begin{axis}[colorbar, colormap/Spectral, view={0}{90}]
            \addplot3[domain=0:360, domain y=0:360, data cs=polar, contour filled={number=15}] (x,y,{sin(y)});
        \end{axis}
    \end{tikzpicture}
    \begin{tikzpicture}
        \begin{axis}[colorbar, colormap/Spectral, view={0}{90}]
            \addplot3[domain=0:360, domain y=0:360, data cs=polar, contour gnuplot={number=15}] (x,y,{sin(y)});
        \end{axis}
    \end{tikzpicture}
\end{document}

I am not an expert, but it seems that in some regions of the plot, the color is slightly changing (interpolating between values?), but the first part of the number associated to the color is truncated. When such number is mapped to the colormap, it generated those weird coloring.

I attach the .tex code and the .pdf generated, plus screenshots of what is visualized with SumatraPDF and with another pdf viewer (foxit reader). 
[weird_colormap_in_tikz.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6199164/weird_colormap_in_tikz.pdf)
![weird coloring foxit](https://user-images.githubusercontent.com/25989278/112352423-0aa88c80-8ccb-11eb-92ae-eb5c39f75ed2.png)
![wierd coloring sumatrapdf](https://user-images.githubusercontent.com/25989278/112352447-0e3c1380-8ccb-11eb-85d2-f7ac7e784632.png)

**Comment by GitHubRulesOK** [comment]
Was a really really long time known problem in MuPDF (now fixed)
Looks the same in my DAILY version compared with Xchange
![image](https://user-images.githubusercontent.com/12754913/112360194-f57f2e00-8cc9-11eb-89e9-e9254c308705.png)
