### ISSUE TITLE
In "Restricted" mode, re-enabling actions are not honored.

### ISSUE THREAD

**Issue by Ashokkumar-RV** [sumatrapdfreader/sumatrapdf#1913]
sumatrapdfrestrict.ini was put in the same directory where SumatraPDF.exe is, with the following setting.

```
[Policies]
DiskAccess = 1
PrinterAccess = 1
CopySelection = 1
```

But it does not honor the setting. Print action is not re-enabled for example.
Only the default "Restricted" mode is in effect.

The issue is with current version i.e. v-3.2.
But it was working on v-3.1.2 as expected.

**Comment by GitHubRulesOK** [comment]
ODD as a quick test with a copy of 3.2 x 64 (probably an installed copy but that's unverified)
I just set a file to InternetAccess = 0 and FullscreenAccess = 0
both were blocked

I left
DiskAccess = 1
PrinterAccess = 1
CopySelection = 1

and kept so I can edit changes
SavePreferences = 1 

All seem functional, so looked for a portable copy to test, found a copy and certainly it works in that portableX32 folder
same INI stops me going full screen or phoning home.

Thus either ini file is wrong format, or wrong location (duplicate exe ?)

**Comment by GitHubRulesOK** [comment]
@Ashokkumar-RV 
Ok I see what can make a difference

I have problems if the ini file is 16bit instead of a normal 8 bit 
since the characters are then not plain text

check you are saving as ansi or plain text e.g UTF-8 (=NOT16bit)
