### ISSUE TITLE
Print qualitiy degenerates from first to last page

### ISSUE THREAD

**Issue by carculator** [sumatrapdfreader/sumatrapdf#1916]
We are using SumatrPDF v3.2/64 on Windows 10 for printing:
_sumatrapdf.exe -silent -exit-when-done -print-to "KONICA MINOLTA C360SeriesPCL"_ 
From page to page the qualitity degenerates:
![Unbenannt1](https://user-images.githubusercontent.com/45626080/112961183-6b115100-9145-11eb-93f6-f5c3131430a6.png)
![Unbenannt2](https://user-images.githubusercontent.com/45626080/112961195-6fd60500-9145-11eb-9586-100e6375e4e6.png)

Any hints ?

**Comment by carculator** [comment]
Stepping back to version 3.0 solved the problem ... 
seems that the rasterization process introduced the issue.

**Comment by GitHubRulesOK** [comment]
Please check your windows updates since this month Microsoft did their usual fix to a fix to a fix ! 
All versions should in theory be working without degradation.
for more details see https://forum.sumatrapdfreader.org/t/blank-printing-or-low-resolution-since-9th-march-2021/3764

**Comment by carculator** [comment]
Removing the Windows Update solved the problem! Great support, thx. !

**Comment by GitHubRulesOK** [comment]
The alternatives IF removing the update(s) is 
EITHER add all 2 or 3 patches and cross finger's it goes well (but I had variable issues with patching more than 1 pc)
OR wait for next months update (Note that will be on the 13th !, so, hope your not superstitious)

**Comment by GitHubRulesOK** [comment]
@kjk 
This issue is Microsoft fail during March Updates so It can perhaps be closed ? although the June Updates may have impacted Acrobat plugin it seems SumatraPDF is immune without a plugin !
