### ISSUE TITLE
ePUB text color changed by sumatrapdf 

### ISSUE THREAD

**Issue by komawoyo** [sumatrapdfreader/sumatrapdf#1917]
Many epub books have predefined text colors for headers and body within the epub but sumatrapdf selects only 1 color by default for all the text in the book.

**Comment by komawoyo** [comment]
Here is an [example ebook ](http://epubtest.org/books/Fundamental-Accessibility-Tests-Visual-Adjustments-v1.0.0.epub) that how color adjustment. The header should be blue 
source: http://epubtest.org/test-books

**Comment by GitHubRulesOK** [comment]
eBook formats were designed to be used on monochrome devices, such as those leading up to Kindle.
Most software emulators started with the same premise that highest contrast is black and white.
![image](https://user-images.githubusercontent.com/12754913/113172296-3504c780-9240-11eb-8a07-0722280f0c4f.png)


It is only those more recent updates to ePub 3.0 / Kindle Fire that insist on enforcing upgraded extensions onto a user such as colours etc.

You can of course set the one colour to whatever contrast or single font you wish but at present SumatraPDF is only compatible with those broad ranging earlier ebook formats. 

![image](https://user-images.githubusercontent.com/12754913/113172173-17376280-9240-11eb-8ddd-a3cb6be008fd.png)

The intention is to update in the future to a more modern concept of ebook engine, but even if switched to using MuPDF you may note in the bottom right corner of upper screenshot that MuPDF still considers the text as Mono.

**Comment by komawoyo** [comment]
Yeah. I noticed that nearly all my ebook, 90% of them, published after 2012 has colors. They shown correctly  with [calibre ](https://calibre-ebook.com/) or when its uploaded to[ google ebook reader](https://play.google.com/books/uploads)

**Comment by GitHubRulesOK** [comment]
Closing as switch To MuPDF resolves OP colour Issue (and passes most other tests)
