### ISSUE TITLE
Callback messages to host application when in plugin mode 

### ISSUE THREAD

**Issue by marcoscmonteiro** [sumatrapdfreader/sumatrapdf#1919]
I embedding the sumatrapdf in my Windows Forms application using command line -plugin parameter. I did it successful so I can control SumatraPDF sending basic DDE commands from host application. 

But now I need to increase functionalities of my host application through sending callback messages from SumatraPDF when things like page change, zoom change or menu context occurs. I did not found any means of do that even in pre-releases versions. 

So, I know some of C and a little of C++ and trying to program this to submit in a future pull request. 

For now I program an generic Callback plugin function and calling it from some points of SumatraPDF code:

```
/* Auxiliary function to callback Plugin Host Window with a generic message */
LRESULT PluginHostCallback(WCHAR* msg, ...) {
    if (gPluginMode) {
        CrashIf(gWindows.IsEmpty());
        if (gWindows.IsEmpty())
            return 0;
        HWND plugin = gWindows.at(0)->hwndFrame;
        HWND Parent = GetAncestor(plugin, GA_PARENT);
        if (!Parent)
            return 0;

        // Format msg string with argment list
        va_list args;

        va_start(args, msg);
        ScopedMem<WCHAR> MsgStr0(str::FmtV(msg, args));
        va_end(args);

        // Converts msg to UTF8
        strconv::StackWstrToUtf8 MsgStr = MsgStr0.Get();

        // Prepare struct and send message to plugin Host Window
        COPYDATASTRUCT cds = {0x1 /* Message from SumatraPDF plugin */, (DWORD)str::Len(MsgStr), MsgStr.Get()};
        return SendMessage(Parent, WM_COPYDATA, (WPARAM)plugin, (LPARAM)&cds);
    }

    return 0;
}
```
And, for example, calling from:
```

void OnWindowContextMenu(WindowInfo* win, int x, int y) {
    DisplayModel* dm = win->AsFixed();
    CrashIf(!dm);
    if (!dm) {
        return;
    }

	/* Sends a message to plugin host window telling Context Menu is opening and cancel if host app desire */
    if (PluginHostCallback(L"OPEN_CONTEXTMENU(%d, %d)", x, y)==1) return;
...
```

Would the SumatraPDF most experienced programmers recommend another best approach for this?

**Comment by kjk** [comment]
Plugin mode is not supported anymore. You're on your own.

**Comment by marcoscmonteiro** [comment]
Ok. But, Do you pretend to remove plugin mode in future versions? I'm question this because I forked sumatrapdf in github to developing these plugin improvements. So I will merge your code in future... If you remove the code I will be in serious problems...

**Comment by kjk** [comment]
No plans to remove
