### ISSUE TITLE
remove non existent documents for start up screen

### ISSUE THREAD

**Issue by Kame7C0** [sumatrapdfreader/sumatrapdf#192]
Hi.
I have small suggestion:

Could be that start up screen (this one that looks like web browser new tab) could check if documents exists and remove those that do not exist (or are moved), or maybe just add simple "clear recent" menu entry.

**Comment by SumatraPeter** [comment]
Non-existent documents shouldn't be automatically removed from the list by default. Think about docs opened from external disks or over the network that are temporarily unavailable for example. If these were removed without asking the user then it would be quite annoying. On demand cleaning would definitely be preferable.

**Comment by kopias** [comment]
Your totally right. Automatic removal would be very bad. I did not consider this scenario.
If I remember correctly I was opening a lot of documents and than moving them to a different location. I was left with list full of not working documents. Solution for me was to clean all history via disabling it and enabling in preferences. 

Some clear History menu entry would`t harm though and maybe just gray out (or any kind of visual feedback) "unavailable" documents.

**Comment by Pfiffikus** [comment]
What about a simple clean up of recent files by mouse selection?
Frame selection, Strg/Shift+click should introduce a new function on recent files page.
Currently removal is possible only file by file or in the config file :(

**Comment by kjk** [comment]
I've added `Clear History` command you can trigger from command palette (`Ctrl + K`)

We won't remove non-existent because they could be only temporarily missing (on network drive or usb drive).

Maybe could remove those that are on fixed drives (not network, not removable)
