### ISSUE TITLE
AGPL GhostScript 9.54.0 not recognised then changes API

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#1923]
AGPL GhostScript 9.54.0 not recognised then changes API. Also [**some problem have XnViewMP v0.98.2**](https://newsgroup.xnview.com/viewtopic.php?f=101&t=41756). Source - some changes GhostScrip 9.54.0 API:

> Version 9.54.0 (2021-03-30)
> The 9.54.0 release is a maintenance release, and also adds new functionality.
> 
> Highlights in this release include:
> 
> Overprint simulation is now available to all output devices, allowing quality previewing/proofing of PostScript and PDF jobs that rely on overprint. See the -dOverprint option documentation in: Overprint
> 
> The "docxwrite" device adds the ability to output to Microsoft Word "docx" format. See: docxwrite
> 
> The pdfwrite device is now capable of using the Tesseract OCR engine when it is built into Ghostscript to improve searchability and copy and paste functionality when the input lacks the metadata for that purpose. See: UseOCR
> 
> Ghostscript/GhostPDL now includes a "map text to black" function, where text drawn by an input job (except when drawn using a Type 3 font) can be forced to draw in solid black. See: BlackText
> 
> Ghostscript/GhostPDL now supports simple N-up imposition "internally". See: NupControl
> 
> Our efforts in code hygiene and maintainability continue.
> 
> The usual round of bug fixes, compatibility changes, and incremental improvements.
> 
> (9.53.0) We have added the capability to build with the Tesseract OCR engine. In such a build, new devices are available (pdfocr8/pdfocr24/pdfocr32) which render the output file to an image, OCR that image, and output the image "wrapped" up as a PDF file, with the OCR generated text information included as "invisible" text (in PDF terms, text rendering mode 3).
> 
> Mainly due to time constraints, we only support including Tesseract from source included in our release packages, and not linking to Tesseract/Leptonica shared libraries. Whether we add this capability will be largely dependent on community demand for the feature.
> 
> See Enabling OCR for more details.
> 
> For a list of open issues, or to report problems, please visit bugs.ghostscript.com.
> 
> Incompatible changes
> Included below are incompatible changes from recent releases (the specific release in question listed in parentheses). We include these, for now, as we are aware that not everyone upgrades with every release.
> (9.53.0) As of 9.53.0, we have (re-)introduced the patch level to the version number, this helps facilitate a revised policy on handling security related issues.
> 
> Note for GSView Users:The patch level addition breaks GSView 5 (it is hardcoded to check for versions 704-999. It is possible, but not guaranteed that a GSView update might be forthcoming to resolve this.
> 
> (9.52) As of 9.52, the Windows binaries released by the Ghostscript development team are built with Microsoft Visual Studio 2019. As a result, Microsoft Windows XP and earlier are no longer supported by these binaries. This does not imply we are, or will start relying upon features only available in VS2019, so the nmake Makefiles will continue to allow older Visual Studio versions (back to VS2005) to build Ghostscript.
> 
> (9.52) -dALLOWPSTRANSPARENCY: The transparency compositor (and related features), whilst we are improving it, remains sensitive to being driven correctly, and incorrect use can have unexpected/undefined results. Hence, as part of improving security we limited access to these operators, originally using the -dSAFER feature. As we made "SAFER" the default mode, that became unacceptable, hence the new option -dALLOWPSTRANSPARENCY which enables access to the operators.
> 
> (9.50) There are a couple of subtle incompatibilities between the old and new SAFER implementations. Firstly, as mentioned in the 9.50 release notes, SAFER now leaves standard Postcript functionality unchanged (except for the file access limitations). Secondly, the interaction with save/restore operations, see SAFER.
> 
> Important Note for Windows Users:
> The file/path pattern matching is case sensitive, even on Windows. This is a change in behaviour compared to the old code which, on Windows, was case insensitive. This is in recognition of changes in Windows behaviour, in that it now supports (although does not enforce) case sensitivity.
> 
> (9.27) The process of "tidying" the PostScript name space should have removed only non-standard and undocumented operators. Nevertheless, it is possible that any integrations or utilities that rely on those non-standard and undocumented operators may stop working or may change behaviour.
> 
> If you encounter such a case, please contact us (either the #ghostscript IRC channel, or the gs-devel mailing list would be best), and we'll work with you to either find an alternative solution or return the previous functionality, if there is genuinely no other option.

**Comment by GitHubRulesOK** [comment]
Hi Victor
I do not think SumatraPDF gswin calling should be affected unless the .reg name location is affected ?

**versions.SortNatural();**
    // return the path to the **newest installation**
![image](https://user-images.githubusercontent.com/12754913/114380695-3f995800-9b82-11eb-8fef-901a24a68f08.png)


@kjk 
My understanding from looking at code is that SumatraPDF uses highest number **from registry** before searching path ? So if reg entry has priority over path ! 
**Will 9.54x32c installed here (below) be used in preference to 9.53.3x64c on path (above) ?**
GS as cross platform relies more heavily on setting env variables 
![image](https://user-images.githubusercontent.com/12754913/114387355-3e6c2900-9b8a-11eb-846a-ff2f6a341288.png)
![image](https://user-images.githubusercontent.com/12754913/114387637-97d45800-9b8a-11eb-8bc1-985b419587e8.png)

Many portable apps **expect to set** path variable (usually prefixed) to over-ride multiple installed versions

**Comment by GitHubRulesOK** [comment]
@VictorVG @kjk 
Just to confirm If I remove the 9.54.0 registry entry it falls back to working with 9.53.3 but unsure if it is from registry or my over-ride path setting?

File only says
Invocation: path/gswin64c.exe -dDisplayFormat=198788 -dDisplayResolution=96 -q -dSAFER -dNOPAUSE -dBATCH -dEPSCrop -sOutputFile=? -sDEVICE=pdfwrite ? ? -f ?

**Comment by VictorVG** [comment]
Idea! Free myself - I'll try (I make changes to my project and clean up the garbage in the code - it has accumulated :) therefore I need to walk over it with a broom :)).

**Comment by VictorVG** [comment]
SumatraPDF v3.3.13315 Git-32419390f x64, AGPL GhostScript 9.54.0 x64, try open SESB_122502203_2016_12.eps - `Error loading SESB_122502203_2016_12.eps`ю If use AGP

![1](https://user-images.githubusercontent.com/906886/114400981-2c4eb280-9bab-11eb-888a-093e9ae196b1.png)

XnViewMP also can't use this version AGPL GhostScript, but I wait fix in to version 0.98.3 - bug confirmed by XnViewMP author.

**Comment by GitHubRulesOK** [comment]
@kjk @VictorVG 
from running GS9.52 on command line
**** WARNING: The .setpdfwrite operator has been deprecated and will be removed entirely
              in the next release of Ghostscript. The functionality of this operator has
              been reduced to increasing the size of the VM threshold. If you believe you
              have a real need for this then you should replace your call to .setpdfwrite
              with:

                  3000000 setvmthreshold

**Comment by VictorVG** [comment]
I see only:

![1](https://user-images.githubusercontent.com/906886/114940293-49ed7780-9e4a-11eb-8c40-863d64b398d2.png)

and in to gswin64c.exe window after start:

> GPL Ghostscript 9.53.3 (2020-10-01)
> Copyright (C) 2020 Artifex Software, Inc.  All rights reserved.
> This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
> see the file COPYING for details.
> GS>

But find this information:
> 2019-08-13 16:05:37 +0100 Ken Sharp http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=15d95340389f0f46bd214803ec19685c0a738a0e
>  
> Deprecate .setpdfwrite
>  
> The .setpdfwrite operator nowadays does nothing more than increase the VM threshold, which is relatively pointless so we're going to remove it.
> 
> In this commit; add a warning message to the .setpdfwrite operator so that anyone using it will be warned. Remove usage from the various shell scripts we provide.
>     
> Resource/Init/gs_pdfwr.ps
> lib/dvipdf
> lib/ps2pdfwr
> lib/ps2pdfxx.bat
>

**Comment by GitHubRulesOK** [comment]
Just to confirm dirty **over patching** works for pre-release thus should also work for legacy
d�f�w�r�i�t�e� �-�c� �"� � � � � � � � � � � � �%�s�"� �-�f� �"�%�s�"�����������
64 00 66 00 77 00 72 00 69 00 74 00 65 00 20 00 2D 00 63 00 20 00 22 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 25 00 73 00 22 00 20 00 2D 00 66 00 20 00 22 00 25 00 73 00 22 00 00 00 00 00 00 00 00 00 00 00  
![image](https://user-images.githubusercontent.com/12754913/114948017-21fc1500-9e46-11eb-86f2-540ddf3a053d.png)
pdf header is
%PDF-1.7
%Çì¢
%%Invocation: path/gswin64c.exe -dDisplayFormat=198788 -dDisplayResolution=96 -q -dSAFER -dNOPAUSE -dBATCH -dEPSCrop -sOutputFile=? -sDEVICE=pdfwrite ? ? -f ?

Thus appears that **for now at least** -c "            " is ignored by 9.54.0

**Comment by VictorVG** [comment]
Key word - this file is just renamed PDF file Adobe PDF Specification v1.7 - see signature `PDF-` and full signature `%PDF-1.7` included specification version. 

For real PS-files signature like `%!PS-Adobe-3.0` and for EPS-files `%!PS-Adobe-3.0 EPSF-3.0` .

Please try Your test use real [**.PF/.EPS files**](https://github.com/VictorVG/test/releases/tag/PS-EPS) produced by GIMP 2.10.24.

**Comment by GitHubRulesOK** [comment]
@VictorVG 
I modified (hex patched) SumatraPDF.exe to not fail on returned error 
It should work or fail on any file **same as before**
please UPLOAD OR LINK me a sample to test

**Comment by VictorVG** [comment]
I commited test files in to GitHub:

> Please try Your test use real .PF/.EPS files produced by GIMP 2.10.24.
also URL http://ns.adobe.com/pdf/1.3/ is not found then ns.<domain>.<zone> is typically link for DNS servers :)

**Comment by GitHubRulesOK** [comment]
![image](https://user-images.githubusercontent.com/12754913/114953831-309bf980-9e51-11eb-9f44-e5c7fff124b4.png)

I can open PS and save as PDF using 9.54 from inside PATCHED SumatraPDF
![image](https://user-images.githubusercontent.com/12754913/114953895-56290300-9e51-11eb-8584-2ffbac3d581a.png)

**Comment by VictorVG** [comment]
**WARNING! METHOD'S ERROR!** 

Your try read PDF document specification v1.7, both have any name. But for open PDF SumatraPDF don't use GhostScript, but GhostScript called for open PS, EPS, LaTeX files - Your test method's is wrong.

**Comment by GitHubRulesOK** [comment]
I open your PS with sumatrapdf and GS 9.54.0
I use sumatraPDF to save as PDF to test it is working
in sumatraPDF.exe find 
00 2E 00 73 00 65 00 74 00 70 00 64 00 66 00 77 00 72 00 69 00 74 00 65
change to
00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20 00 20

**Comment by VictorVG** [comment]
You reopen the PDF documents renamed to `*.ps / *.eps`, generated by an external program and passed to the SumatraPDF command line. Above, I have already pointed out to you this methodical error, which naturally leads you to wrong results. The operation you call is equivalent to "_Create a copy of the document in PDF, overwrite the original document, and then open the generated PDF file_."

**Comment by GitHubRulesOK** [comment]
SumatraPDF (e)PS engine = 
1) store (e)ps filename
2) look for newest GS in registry
3) pass filename to Ghostscript to build PS2PDF %temp%\PsE###.tmp (is now a PDF)
4) GS5.53.3 =success OR  GS9.54.0=fail
5 SumatraPDF "cheats" displays %temp%\PsE**PDF**.tmp success **with PS filename**

**Comment by VictorVG** [comment]
Search and logging did not show any handle or events that would meet the described model. Also, neither of the RAM, nor on the disks did not at all detected files according to the data coinciding with running .eps / .ps, but having the .pdf structure while both .eps and .ps files were opened in Sumatrapdf.

**Comment by GitHubRulesOK** [comment]
To add **basic** render ps eps prn plt etc use GS

https://github.com/sumatrapdfreader/sumatrapdf/commit/a0b1dac7397e76003e074c8e6c9c8fcb51757e63
*add support for **displaying** Postscript documents (requires a recent Ghostscript installation)
PsEngine::CreateFromFileName(fileName);
// find all installed Ghostscript versions
// return the path to the newest installation
// TODO: read from gswin32c's stdout instead of using a TEMP file
ScopedMem<TCHAR> args(str::Format(_T("-q -dSAFER -dNOPAUSE -dBATCH -sOutputFile=\"%s\" -sDEVICE=pdfwrite -c .setpdfwrite -f \"%s\""), tmpFile, fileName));

so has always used  -c .setpdfwrite

search Ghostscript in the PATH as well
 [AFAIK is fallback NOT over-ride]
https://github.com/sumatrapdfreader/sumatrapdf/commit/2e3093c6debb066ff6dfedf7f0db00530925dd42

later
allow to save PS documents in PDF format (as **already converted by Ghostscript**
https://github.com/sumatrapdfreader/sumatrapdf/commit/825e2beb5f3223c4866892f3c6ba1c7c11e6ef3c

look for 32-bit and 64-bit Ghostscript under 64-bit Windows 
[AFAIK 64bit gets priority]
https://github.com/sumatrapdfreader/sumatrapdf/commit/2dc9626e11117c3ba242f5ed4940b95cdfddd70e

**Comment by GitHubRulesOK** [comment]
@kjk 
I am not able to compile a code change but I consider this a significant future regression and thus potential blocker to 3.2.1 release

in https://github.com/sumatrapdfreader/sumatrapdf/blob/9b95bcdf1dffeecf0416969b5b15c4f1667cac51/src/EnginePs.cpp#L152



   const WCHAR* psSetupStr = psSetup ? psSetup.Get() : L"";
    AutoFreeWstr cmdLine = str::Format(
        L"\"%s\" -q -dSAFER -dNOPAUSE -dBATCH -dEPSCrop -sOutputFile=\"%s\" -sDEVICE=pdfwrite -c " 
       L"\".setpdfwrite%s\" -f \"%s\"",        gswin32c.Get(), tmpFile.Get(), psSetupStr, shortPath.Get());
<br class="Apple-interchange-newline">


what appears to be needed is to remove `-c` from third line
and remove `\".setpdfwrite%s\"` from fourth line

However I am uncertain how that is affected by the %s

**Comment by VictorVG** [comment]
Big thanks!
