### ISSUE TITLE
How does v3.1.2 print file get smaller? How to change it? This version supports XP system. But the file is too big

### ISSUE THREAD

**Issue by wangpai1998** [sumatrapdfreader/sumatrapdf#1925]
PDF Print file is sent to the printer. Starting from v3.1.2, it becomes a page of 33MB. Can it become the original file size? 33MB is too large. How can I change the version 3.1.2, which supports XP system. This means that in this version, there is a CMD to print the parameters, and then the file size is not too large, how to modify it? Which parameters should be modified? Because XP system needs to use, but the print file is too large. What should I do? Sorry to bother you.

**Comment by GitHubRulesOK** [comment]
use [Version: 3.0](https://www.sumatrapdfreader.org/download-prev.html)
NOT all parameters are available e.g. paper=system defaults for limited sizes, no rotation etc.
Those are the limitations with version 3.0 that have been improved in newer (non-XP) 64 bit
most important **DO NOT use print as image** keep `PrintAsImage = false`
```
PrinterDefaults [
	PrintScale = shrink
	PrintAsImage = false
]
```

**Comment by wangpai1998** [comment]
Why is the file so large when this parameter is used? Is v3.1.2 not available?

**Comment by GitHubRulesOK** [comment]
3.1.0 and later like 3.1.2 ONLY use print as image (that is why some users prefer that more reliable method !)
acrobat reader command line printing probably still uses both methods but many users find that a problem
Tracker Xchange (viewer and editor) are often used as a reliable substiture 
Many thousands still use the older 32bit portable viewer version in a CLI wrapper see http://www.columbia.edu/~em36/pdftoprinter.html
