### ISSUE TITLE
Pre-release builds are very old

### ISSUE THREAD

**Issue by mikhaelkh** [sumatrapdfreader/sumatrapdf#1926]
The latest [pre-release builds](https://www.sumatrapdfreader.org/prerelease.html) were built on [2020-08-16](https://github.com/sumatrapdfreader/sumatrapdf/commit/e29de529247449e40836ef75d0deeffe5993b092), more than 8 months ago. It is a lot for testing builds. Is this release channel abandoned? Or is SumatraPDF not stable enough anymore for this channel?

**Comment by GitHubRulesOK** [comment]
The pre-release dailys agreed are not "every" day but there have been more than 200 in roughly as many days.

Much has improved in the 64 bit versus that older 32 bit pre-release but IMHO the best version for some tasks is still stable 3.1.2 which is now 5 years older

**Comment by kjk** [comment]
For now use daily builds. I wanted pre-release builds to be signed but I currently don't have signing certificate.

**Comment by GitHubRulesOK** [comment]
@kjk 
I saw  the horrendous price for MS enforced EV level code signing which seems significantly biased towards 3 years at a time, I wonder if a **specific** cloud sourced funding would collect enough over a 3 years interval to cover the first and hopefully something towards the next (and dare I say past) certificates.
