### ISSUE TITLE
Temporary Website outage

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1934]
@kjk 
Cloudflare was reporting issues with Download pages I got 522 others get 523
**Hours Later** Seems to have been a temporary outage
see https://forum.sumatrapdfreader.org/t/fixed-website-errors-523-or-522-due-to-temporary-outage/3855
but has reappeared !!

Online.SumatraPDF?  and seperate host for forum appear to be OK
[**correction**]<strike> Problem has now spread to all hosted pages e.g. Home, Manual, Documentation and Sponsor
1st affected
https://www.sumatrapdfreader.org/download-free-pdf-viewer.html
I pulled the page from github and all seems to be OK it works correctly without a problem, it is only the routing between local Cloudflare in London and hosted Server that threw the error
![image](https://user-images.githubusercontent.com/12754913/116538446-72ac4d00-a8df-11eb-8db7-ed2ee27db6c7.png)

 and AFAIK although unchanged i.e. still are working off to online 
attempting to use Website Hosted I can only get same on
https://www.sumatrapdfreader.org/prerelease.html
https://www.sumatrapdfreader.org/dailybuilds.html

Checked in IExplore, Edge and Firefox on two devices (could be local but odd it is after web commits)

Error 522 Ray ID: ### • 2021-04-29 09:32:46 UTC Connection timed out
 An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522)
</strike>

**Comment by GitHubRulesOK** [comment]
Problem appears to be with Cloudflare as it comes and goes

**Comment by kjk** [comment]
Thanks. I moved the site from netlify to cloudflare pages and mis-configured things. Should  be working now.
