### ISSUE TITLE
How to disable automatic expansion of bookmarks?

### ISSUE THREAD

**Issue by midvok** [sumatrapdfreader/sumatrapdf#1937]
I just installed and tried Sumatra v3.2 64-bit. It looks very nice and lightweight, but this bookmark behavior is very annoying. While I scroll pages, the bookmarks tree is expanding and getting longer and longer, which makes it really hard to use the bookmark tree for navigation (especially when a book has several nested levels).

I looked to Options and Advanced options, but I can't find any option to either automatically collapse bookmarks after leaving the branch, or to disable the auto-expanding feature completely? Is there such option?

**Comment by kjk** [comment]
In 3.3 the behavior will go back to how it worked in 3.1.2 and is available in daily build https://www.sumatrapdfreader.org/dailybuilds
