### ISSUE TITLE
Broken links to previous versions ZIPs

### ISSUE THREAD

**Issue by Lucas-C** [sumatrapdfreader/sumatrapdf#1938]
All the links on https://www.sumatrapdfreader.org/download-prev
are currently broken, they all redirect to https://www.sumatrapdfreader.org/free-pdf-reader

**Comment by GitHubRulesOK** [comment]
Thanks  Lucas
Your report on Forum was blocked as a suspicious link :-)
 so with your permission I will delete that one and we will run with this open issue.

**Comment by GitHubRulesOK** [comment]
@Lucas-C 
Searching around there are some very dubious mirrored sources however the best I can suggest is
https://www.fosshub.com/Sumatra-PDF-old.html
You need to compare with virustotal that they match the source dates and sha etc.

**Comment by Lucas-C** [comment]
Ok, thanks for the suggested workaround.

Any idea on what can be causing the issue?

**Comment by GitHubRulesOK** [comment]
@kjk 
the redirect is certainly picking up dl for current and prerelease
 but I cant see it working for  the OP old version 3.1.2

**Comment by Lucas-C** [comment]
Thank you!

**Comment by cscode2000** [comment]
Still the same or again? All links to older versions on
https://www.sumatrapdfreader.org/docs/Version-history
https://www.sumatrapdfreader.org/download-free-pdf-viewer
go to
https://www.sumatrapdfreader.org/download-prev
There is only one link to https://www.sumatrapdfreader.org/free-pdf-reader

**Comment by GitHubRulesOK** [comment]
@cscode2000 
Any links in  https://www.sumatrapdfreader.org/docs/Version-history appear to be working here as expected  on 32bit Windows MS Edge can you be more specific which one and what browser?

any links to previous version such as 3.1.2 should by design go to https://www.sumatrapdfreader.org/download-prev

**Comment by cscode2000** [comment]
I use Torbrowser and see only one link on https://www.sumatrapdfreader.org/download-prev
-> https://www.sumatrapdfreader.org/free-pdf-reader

**Comment by GitHubRulesOK** [comment]
@cscode2000 
that is deliberate there are NO LIVE LINKS for leachers

**Comment by kjk** [comment]
@cscode2000 More likely you've disabled JavaScript. Too much work to manually maintain the list so it's generated via JavaScript

**Comment by GitHubRulesOK** [comment]
@kjk its not java its your need to not provide links on that page.

**Comment by GitHubRulesOK** [comment]
@kjk perhaps add a byline if you dont see the scripted links ....blah blah

**Comment by kjk** [comment]
@GitHubRulesOK done, will go live next I deploy the website
