### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by lunbudao** [sumatrapdfreader/sumatrapdf#1939]
Often I just want to **highlight** content instead of add **comment**, **but** the annotation function provided by pre-release edition always add comment, is there a way to solve this.

**Comment by GitHubRulesOK** [comment]
The default behaviour in MuPDF-GL when highlighting text is to add it into the comments box.
there is no identical feature to  SumatraPDF for selecting an area with text (it uses multiple lines) but both will highlight and place the area selection into the comments.

If the highlighted area does not contain text then comments will be blank

This is a common behaviour amongst many such highlighting apps, but not in Edge where it is not automatic so there any comment has to be added by copy and paste etc.

It is easy to delete the comment if not wanted but does require using the mouse.

**Comment by lunbudao** [comment]
Thanks for answering my question, though I still think that it's better to not have the highlighted text added to comments box. Anyway, sumatrapdf is really a good pdf viewer.

**Comment by GitHubRulesOK** [comment]
@kjk 
I "guess" the request is to add an option in highlight settings along the lines of 
HighlightAutoComment = false

**Comment by lunbudao** [comment]
Yes, I think this behavior is preferable.

**Comment by kjk** [comment]
Not sure I understand.

When you select text and press 'a' (or use context menu `Create Annotation / Highlight`), Sumatra does create a highlight annotation. It also opens the annotations window where you can provide more details for annotation.

 Not sure what do you mean by "comment". There's no such thing in PDF, there are just different kinds of annotations.

To put it different:
* what exactly are you doing ("annotation function provided by pre-release" is too vague)
* what happens
* what do you expect to happen

**Comment by GitHubRulesOK** [comment]
@kjk 
When you press A the highlights contents: (often referred to as the "comment") 
property is AUTO populated by the selected text.

In some apps it is not AUTO added and the "comments" may need to be manually alternately worded (like say favorites) or attached / positioned separately compared to the highlighted area.

The desire is that those alternative conflicting features be set by the user.

**Comment by kjk** [comment]
Maybe default behavior should be to not add selected text as a comment? Maybe add text with ctrl-a or alt-a?

**Comment by GitHubRulesOK** [comment]
if a/A are undefined the logical two key choice is a || shift A 
However there will be two camps as to preference
So backed up with a true / false setting for those that preferer opposing choice when only hitting one key?

**Comment by GitHubRulesOK** [comment]
@lunbudao
Pre-release behaviour has now changed please try a recent version and try out A
NOTE that  IF you DO want the comments to show the selection then use SHIFT + A to highlight (opens the editor) and CTRL + V to Paste selection into Contents Box.
