### ISSUE TITLE
Website legacy support

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1941]
Yes I know XP is dead and with it Internet explorer, however 2/3 of my global usage is on Windows 7 with IE as default, and yes Edge is the secondary browser.

Whilst using SumatraPDF I often refer to the manual or call up the website, which by default starts up in IE.
If I land on the HOME page it is usually easy to navigate to other pages via the banner and internal links. 

However more recently with some of the fixes that is no-longer working from home **page banner** (which is visible) for others I simply get blank pages
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML><HEAD>
<META http-equiv="Content-Type" 
content="text/html; charset=windows-1252"></HEAD>
<BODY></BODY></HTML>
```
By comparison selecting forum from masthead banner does relocate with no html page specified to forum default page with the warning that they think IE is pants

**As far as i can tell it is related to with/without .html extension since if I REMOVE the .html at end of IE address then the page appears** (simply deleting anything less will take me to default home page) and when using the banner **in Edge the .html appears** then is automatically split and removed by js to display the page?!

**Comment by kjk** [comment]
Sorry, don't have spare bandwidth to test the website on ie11. Will accept PR with fixes but that's as far as I can go.
