### ISSUE TITLE
Open pdf from URL using command line arguments

### ISSUE THREAD

**Issue by jakubmaguza** [sumatrapdfreader/sumatrapdf#1949]
Hello!

I can open pdf from url using front-end Open function but i can't find a way to open url using command line arguments. It always prepends directory to url.

What I'm trying to achive is to print pdf from url directly f.e.:

`.\sumatra.exe -print-to-default "https://www.testpdf.com/pdf.pdf"`

**Comment by GitHubRulesOK** [comment]
I am not sure how practical that approach may be as the URL call is transferred via the browsers cache
and your hypothetical example for testpdf.com would require a curl command such as 
https://pdf.testpdf.com/pdf.pdf?down=1 to bring the file outside the browser cache

**Comment by jakubmaguza** [comment]
I'm not sure why you need browser there.
This is somehow working when you are pasting url to pdf in `OpenFileDialog` in `sumatra.exe`

**Comment by GitHubRulesOK** [comment]
Type in a url and look at the first line description with Ctrl D and follow the path so for the example above
![image](https://user-images.githubusercontent.com/12754913/118698485-5cbbe900-b808-11eb-858a-a6fc79809917.png)

**Comment by GitHubRulesOK** [comment]
Y=I like to use outside my browser to print a browsable PDF
X = why not print from the browser

**Comment by jakubmaguza** [comment]
I don't wont to use browser at all.
As i wrote in my first message, I would like to call f.e.:
`.\sumatra.exe -print-to-default "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"`

This is not working. I'm sure it's problem with reading http protocol. You can verify it by runing:
`.\sumatra.exe "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf"`

The result is:
![image](https://user-images.githubusercontent.com/24191650/118701177-b970d100-b813-11eb-9cb1-88987067374a.png)

It's prepending directory to url.

**Comment by GitHubRulesOK** [comment]
The http(s): protocol is "handled" on windows by IE components, so SumatraPDF internally passes the request and the URL is converted (including DNS) to a cache address that can be constantly changing but is on success return a localised cached file address of something like \ _variable_ \dummy[1].pdf and internally SumatraPDF will then render that localised file.
Externally you can call SumatraPDF "\\server\folder\file.pdf" and it should work
so if you have \\ip.ad.re.ss\storage location\ and don't use http:// then it may be possible to call remotely

**Comment by jakubmaguza** [comment]
I know that I can download file first as a workaround. I'm doing that know.
Front end application can load PDF directly from URL, so maybe there is a way to make this happen in console version.

**Comment by kjk** [comment]
Downloading files from the internet is outside of the scope of sumatra. You can code a work-around quite easily (i.e. use some other method to download the file and then launch sumatra)
