### ISSUE TITLE
more/customizable toolbar buttons

### ISSUE THREAD

**Issue by avih** [sumatrapdfreader/sumatrapdf#1956]
It would be nice if more "actions" from the menu could be placed at the toolbar.

For instance, personally I often toggle between book-view (without "show pages continuously" and with "fit-page") and single-continuous-fit-width.

I've also never used the print button, or open button, or rotate buttons.

I'm sure other users have different workflows than mine, and perhaps they have other preferences about which buttons should appear at the toolbar.

Therefore I think it would be nice if:
- Add more items from the menus to the toolbar (mostly view and zoom/fit?)
- Maybe allow to choose which items appear at the toolbar?
- Maybe place some/all of the menus at the toolbar? e.g. to allow faster and bigger click-area for view->whatever directly from the toolbar without having to go through the hamburger menu.

But even if customizable is off the table, the toolbar is still quite empty in normal desktop/laptop usage (I'd imagine it'd be less empty with portrait display with a tablet, for instance), so it could be nicer to make use of the space - which is otherwise just empty.

**Comment by Diogo-Rossi** [comment]
I agree. The toolbar is very empty in landscape mode and is something empty in portrait mode.
I always have to use shortcuts to change the view mode (but I often forgot them and have to go to the menu).

### Landscape 
![image](https://user-images.githubusercontent.com/57204023/154326980-34b679ef-1c08-40d5-8ab1-d95ee689eb20.png)

### Portrait 
![image](https://user-images.githubusercontent.com/57204023/154327162-1658be4b-faa4-4c49-95f7-c7c0b8724670.png)

**Comment by GitHubRulesOK** [comment]
@Diogo-Rossi 

Th main issue is that sumatraPDF is designed for windows and windows come in many factors so currently this is how it looks on my notebook and yes it could be my tablet is a tad wider. the ethos has been minimum use of ribbon space for all users not add thousands of icons for those with 4k screens.

![image](https://user-images.githubusercontent.com/12754913/154328848-281a9260-1028-43f7-b271-f1cda3bd5a3d.png)

**Comment by avih** [comment]
>  the ethos has been minimum use of ribbon space for all users not add thousands of icons for those with 4k screens.

The ethos should be usefulness.

If people have to resort to the hamburger menu for things they do frequently then for them it's less useful than it could be.

Similarly, if the toolbar contains items they never use, then for them it would be more useful if there were other items instead of those.

Of course, different people have different needs and different workflows, so I can't pretend to know which toolbar buttons would be best for any other user.

Other than fully customized toolbar (even if only via a config file), there could be other approaches, like choosing between several predefined layout, or other ways.

**Comment by Diogo-Rossi** [comment]
@GitHubRulesOK , I understand, thanks for clarify.

If I may: do you think that would be reasonable to add some more buttons (like some view options) to improve usability in large screens, while they are kept hide in smaller screens?

Off course the experience would be different by the users, but it may help bigger screens users, while maintain the current experience in the small ones.

**Comment by GitHubRulesOK** [comment]
@Diogo-Rossi 
I am not a developer simply user/suport however the need to shift some functions out the hamberger has been a long time request/slow moving target, the addition of rotate to the ribbon took years to establish as a priority and some users make their own mods to some paired icons either via AutoHotKey or by compiling their minor changes in a forked version. the developer would seem to favour various improvements in UserInterface but none of those are trivial to impliment, e.g. annotation is still very much work in progress.

**Comment by dominiosc** [comment]
It is not about filling the bar, allow us just two or three icons of our choice, no more.
In my case: Save as and Delete (option that is not currently on the menu)

In the meantime, I'll try to add shortcuts that they don't have now. For example, Show in folder.
https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts

**Comment by GitHubRulesOK** [comment]
@dominiosc 

Windows SaveAs is via CTRL+S

Delete is not advisable as in theory (with one exception) all files open should be locked against changes e.g. to allow user to add annotation etc. The exception is PDF files need to be kept accessible for previewing by PDF compilers, such as PDFLaTeX editors. Elsewhere I explained how to store filenames for delete after SumatraPDF is closed

**Comment by dominiosc** [comment]
You are right with save as, ctrl+s, but sometimes you also have to think with users who only use the mouse or do not have computer skills, my mother. Click here is acceptable for these people, ctrl+s not.

I understand what you mean by the problem of deleting the file in use, see irfanview or notepad++ for example.

The function could be implemented and when requesting to delete the file, ask for confirmation, close the tab and delete the file, for making it easy...

The rename function is working good.

**Comment by kjk** [comment]
Toolbar is now customizable. See https://www.sumatrapdfreader.org/docs/Customize-toolbar

**Comment by avih** [comment]
I can indeed add toolbar items with latest prerelease (16645). Thanks!

I noticed with the specific example at the docs of prev/next tab, the buttons can move away from the mouse cursor, as far as I can tell depending on the number of pages the document at the tab holds. I'd think if space is reserved for, say, 4 digits at the total pages count (similar-ish to how it's reserved for the current page number), then the rest of the toolbar is likely to not move.

Is there a way to remove items from the toolbar?

Maybe the shortcuts array shoule/could be populated automatically with the default toolbar items (which could be compound, e.g. maybe PageNav could be the whole `Page [  X] / Y` thing, and maybe "Find" is the whole block with next/prev etc), so that it's easier to remove, or rearrange items, while also serving as examples to get going quickly?

Thanks again for the work you do.

**Comment by kjk** [comment]
No way to remove items.

No way to combine commands. Would need to be convinced there are useful use-cases.

**Comment by avih** [comment]
> Would need to be convinced there are useful use-cases.

Wouldn't the fact that you chose exactly such combined command to be included by default at the toolbar be good enough argument?

**Comment by kjk** [comment]
No because it was a special case. 

I can't think of any other uses for such functionality.

**Comment by GitHubRulesOK** [comment]
Just a Note that toolbar icons now allow for svg  and thus coloured icons 

<img width="638" height="144" alt="Image" src="https://github.com/user-attachments/assets/4de21fce-c201-4305-a45b-3124dadf7dd7" />
