### ISSUE TITLE
Feature request: Open current tab in new window

### ISSUE THREAD

**Issue by lennertcl** [sumatrapdfreader/sumatrapdf#1957]
Detach a tab from the current window and open a new window with this tab.
Or even better: drag and drop tabs from one window to another (like Google Chrome).

**Comment by GitHubRulesOK** [comment]
duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/18
Currently nearest equivalence is <kbd>CTRL</kbd><kbd>SHIFT</kbd><kbd>N</kbd> and middle click the old tab
