### ISSUE TITLE
All Open Documents Lister\ Switcher

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#1960]
A way to list all documents [switch to them] would be very useful as I have tons of tabs open [with Session Resume]; & cannot read their names. Or maybe the 10 or so documents listed in the File Menu be changed to unlimited, so every document opened is viewable. This is a feature request.

**Comment by GitHubRulesOK** [comment]
This is generally a duplicate request, but wont be closed until this comment is replace by issue number(s)
