### ISSUE TITLE
Dark Color Scheme For Documents

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#1961]
Dark Mode would be handy since the whitepage colors are too bright for the eyes, kinda like with Foxit Reader, being able to switch black themes … This is a feature request.
P.S: As a workaround, I use Windows 10 Night Light mode plus Color Filters [Accessibility Feature] set to Inverted Grayscale —it works for now.

**Comment by GitHubRulesOK** [comment]
I too use Win 10 NightLight that's what its there for, This is a duplicate request so will be closed once the reference is found.
