### ISSUE TITLE
Ask to save unsaved annotations when closing a window with Alt-F4

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1962]
1) Whilst testing adding annotation I observed that I could use top right X to close without any warning of unsaved annotations, which is not the case when closing a single tab or using menu to close open single file.

2) unsure how that applies to escape to exit.

3) when using the menu option save annotations, then attempting to close current file I get the odd situation that they appear to have been saved and save button is grey, but am warned that's not the case.
Two be sure, Two be sure, I saved anyway and on comparison I had moved one object slightly, but the visual feedback from looking at the save button would have been welcome.
![image](https://user-images.githubusercontent.com/12754913/119917597-c9e52200-bf5e-11eb-893f-ad7c545b7664.png)

**Comment by kjk** [comment]
We should always ask to save unsaved annotations.

Relevant code:
* we ask in `CloseTab`
* we don't ask in `CloseWindow`
* should also ask in `BrowseFolder` ?
* there's also a TODO in `TabsOnCloseDoc`
