### ISSUE TITLE
Loading wdp image (jpegxr) result blank page using xps

### ISSUE THREAD

**Issue by xinsheng** [sumatrapdfreader/sumatrapdf#1963]
Hi,
the latest version removed wincodec.h for load-jxr.c, replaced as <jpegxr.h> lib.
could i know the reason of this modification? and if i want build the jpegxr lib in it on Windows by myself, which version jpegxr should i use and where can i find it?

I've tried https://jpeg.org/jpegxr/software.html   (Source Code v1.41) but not work because of some function missing.

Thanks~

**Comment by kjk** [comment]
Could you share a test file that has jpeg-xr images in it? If yes, please attach to this bug report (possibly inside .zip file) 

If you can't share publicly, please e-mail to me at kkowalczyk@gmail.com

I would like to add support for jpeg-xr but hard to verify it works without test files.

**Comment by xinsheng** [comment]
Dear kjk,
I have send you the attachment by email, please check. :) @kjk

**Comment by kjk** [comment]
@xinsheng I got the test file, thanks!

**Comment by kjk** [comment]
Daily build now opens test .xps file with jpeg-xr image in it.
