### ISSUE TITLE
MSBuild: error MSB4057: The target does not exist in the project

### ISSUE THREAD

**Issue by skipik** [sumatrapdfreader/sumatrapdf#1965]
I have such problems with the latest VS 2019 v16.10

![Снимок экрана (2)](https://user-images.githubusercontent.com/24621645/120071596-c950a680-c098-11eb-9ac9-842767e1dc7d.png)

I'm using MSBUILD

```
msbuild.exe "vs2019\SumatraPDF.sln" "/t:SumatraPDF;SumatraPDF-dll;PdfFilter;PdfPreview;test_util" "/p:Configuration=Release;Platform=Win32" /m "/p:VcpkgEnabled=false"
msbuild.exe "vs2019\SumatraPDF.sln" "/t:SumatraPDF;SumatraPDF-dll;PdfFilter;PdfPreview;test_util" "/p:Configuration=Release;Platform=x64" /m "/p:VcpkgEnabled=false"
```

Those red lines on the screen says 'The target does not exist in the project' and everything was fine some time ago.
Am I only one with this problem and what actually causes it - the new VS version or may be something else?
Thanks!

**Comment by kjk** [comment]
See https://github.com/sumatrapdfreader/sumatrapdf/commit/348d27f942a71534e769536d1849c9ca6f58dcf3

**Comment by skipik** [comment]
Thank you so much! It worked.
