### ISSUE TITLE
an unknown item appeared and does not appear on my other pdf readers

### ISSUE THREAD

**Issue by DragonMS92** [sumatrapdfreader/sumatrapdf#1968]
i use sumatra frequently  and when i got it reinstalled on my comp this was never on this page. how do i fix it?
![alert](https://user-images.githubusercontent.com/85376299/120874436-4afa7580-c56c-11eb-9722-ddbda8463269.png)

**Comment by kjk** [comment]
This might already be fixed in latest code. Please check with a daily build: https://www.sumatrapdfreader.org/dailybuilds

If it's not fixed in daily build, please provide a test file. See https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

**Comment by DragonMS92** [comment]
[Warhammer 40.000 - Rogue Trader - The Expander Origin Path - Complete.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6602998/Warhammer.40.000.-.Rogue.Trader.-.The.Expander.Origin.Path.-.Complete.pdf)
![Screenshot 2021-06-05 131247](https://user-images.githubusercontent.com/85376299/120901334-c5280a00-c5ff-11eb-907a-47dfdf8d8d22.png)

here is the file i have as a test. it did not work though instead more of the markings appeared

**Comment by kjk** [comment]
Confirmed still exists in latest build e.g. on page 10.

Command to trace page 10: `C:\Users\kjk\mupdf\mutool.exe draw -F trace ..\..\Downloads\bug1968-Warhammer.40.000.-.Rogue.Trader.-.The.Expander.Origin.Path.-.Complete.pdf 10`

**Comment by kjk** [comment]
A simplified repro file with just page 10 extracted from the original file:

[bug1968-simplified.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6603033/bug1968-simplified.pdf)

**Comment by kjk** [comment]
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=703915

**Comment by GitHubRulesOK** [comment]
@kjk 
Whilst MuPDF appears to be going against the grain in showing those objects my editor shows there is a difference in those "black" watermark masks compared to the translucent softmasks on other pages. However we will have to see if MuPDF declare the PDF-tools modified file is at fault

**Comment by GitHubRulesOK** [comment]
@kjk still unconfirmed by MuPDF tracker however their test case seems to have been fixed ?
![image](https://user-images.githubusercontent.com/12754913/174463564-182fbc18-67c6-498b-ad82-93a767736e8c.png)

**Comment by kjk** [comment]
Yes, looks fixed, thanks!

**Comment by PreachingPython** [comment]
Daily build fixed this for me, thanks guys!
