### ISSUE TITLE
sumatra pdf 3.0.0.0 hangs on W7

### ISSUE THREAD

**Issue by fredinvdg** [sumatrapdfreader/sumatrapdf#197]
Hi, 
On Windows 7 up to date, sumatra pdf 3.0.0.0 crashes ( more precisely freezes ).
I run it, then it freezes whenever :
- I try to open any document (which where once opened without trouble)
- or I select another app (change focus) I tries to get sumatra_pdf focus back.

When it gets frozen, I can see by looking at the process "SumatraPDF.exe *32", that the memory used keeps growing slowly.
This version comes from https://kjkpub.s3.amazonaws.com/sumatrapdf/rel/SumatraPDF-3.0-install.exe
Btw: the COMODO certificate is outdated. 2015.04.14 (‎00 c5 47 16 b6 73 13 b3 03 5e 03 d1 e7 8d 30 88 63 )
I cannot use sumatra anymore, snif :-(
How can I help to debug ?
Fred

**Comment by mr-E** [comment]
No creo que sea lo adecuado, pero con esto salí del apuro:
```python
    try:
        default_carpeta_destino = os.path.join(os.environ.get('HOME'), 'cfdi-descarga')
    except:
        default_carpeta_destino = os.path.join(os.environ.get('HOMEPATH'), 'cfdi-descarga')
```

**Comment by mr-E** [comment]
I'm using SumatraPDF.exe version 3.0.0.0.0 on Windows 8.1 32-bit and it works the certificate is outdated but works.

Maybe your pc protections, like antivirus or MSproducts running are the cause.
Or the pdf file is the cause, is stored locally? Maybe trying with other pdf file stored locally.

P.S. I have disabled the windows malware protection because It puts a lot of time to load files and list the content directory, and without antivirus installed.

**Comment by kjk** [comment]
If it worked before and doesn't work now, most likely it's some other software that was installed in-between and is invasive and causes the problem. Most likely a shell extension or some file-system plugin or an anti-virus program since it seems to happen when you open the file.

It would be helpful to get the info described in "Debugging a hang" in https://github.com/sumatrapdfreader/sumatrapdf/wiki/Debugging-Sumatra

You can also try pre-release version to see if it happens there http://www.sumatrapdfreader.org/prerelease.html

Regarding certificate: does it cause some warnings/issues? I've renewed the certificate and am signing new versions with updated certificate but the binaries that have been signed with the old certificate should still work just the same.

**Comment by fredinvdg** [comment]
Hi,

The hang does NOT occur when I disable antivirus McAfee. 
(btw:The obsolete certificate does not cause any issue.)
To confirm the antivirus hang, I installed the windbg and followed your instructions, see the capture below. 

Nonetheless, I don't fell comfortable disabling the antivirus for good for any executable reading pdf's.
Let me know if I can do more tests.

Fred

--
Microsoft (R) Windows Debugger Version 6.3.9600.17336 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach
Symbol search path is: *** Invalid ***
****************************************************************************
* Symbol loading may be unreliable without a symbol search path.           *
* Use .symfix to have the debugger choose a symbol path.                   *
* After setting your symbol path, use .reload to refresh symbol locations. *
****************************************************************************
Executable search path is: 
ModLoad: 00000000`00a80000 00000000`00bee000   C:\Program Files (x86)\SumatraPDF\SumatraPDF.exe
ModLoad: 00000000`77ba0000 00000000`77d49000   C:\Windows\SYSTEM32\ntdll.dll
ModLoad: 00000000`77d80000 00000000`77f00000   ntdll.dll
ModLoad: 00000000`752e0000 00000000`7531f000   C:\Windows\SYSTEM32\wow64.dll
ModLoad: 00000000`75280000 00000000`752dc000   C:\Windows\SYSTEM32\wow64win.dll
ModLoad: 00000000`75270000 00000000`75278000   C:\Windows\SYSTEM32\wow64cpu.dll
ModLoad: 00000000`75de0000 00000000`75ef0000   KERNEL32.dll
ModLoad: 00000000`76370000 00000000`763b7000   KERNELBASE.dll
ModLoad: 00000000`6cb80000 00000000`6d087000   libmupdf.dll
ModLoad: 00000000`73830000 00000000`739c0000   gdiplus.dll
ModLoad: 00000000`756d0000 00000000`7577c000   msvcrt.dll
ModLoad: 00000000`77380000 00000000`77480000   USER32.dll
ModLoad: 00000000`75a50000 00000000`75ae0000   GDI32.dll
ModLoad: 00000000`75b80000 00000000`75b8a000   LPK.dll 
ModLoad: 00000000`75480000 00000000`7551d000   USP10.dll
ModLoad: 00000000`772d0000 00000000`77371000   ADVAPI32.dll
ModLoad: 00000000`763c0000 00000000`763d9000   SECHOST.dll
ModLoad: 00000000`76150000 00000000`76240000   RPCRT4.dll
ModLoad: 00000000`75420000 00000000`75480000   SspiCli.dll
ModLoad: 00000000`75410000 00000000`7541c000   CRYPTBASE.dll
ModLoad: 00000000`75ff0000 00000000`7614c000   ole32.dll
ModLoad: 00000000`75520000 00000000`7559b000   COMDLG32.dll
ModLoad: 00000000`759f0000 00000000`75a47000   SHLWAPI.dll
ModLoad: 00000000`6e490000 00000000`6e62e000   COMCTL32.dll
ModLoad: 00000000`765f0000 00000000`7723b000   SHELL32.dll
ModLoad: 00000000`6ed10000 00000000`6ed15000   MSIMG32.dll
ModLoad: 00000000`75200000 00000000`75251000   WINSPOOL.DRV
ModLoad: 00000000`76250000 00000000`7636b000   WININET.dll
ModLoad: 00000000`76240000 00000000`76243000   Normaliz.dll
ModLoad: 00000000`75be0000 00000000`75d9b000   iertutil.dll
ModLoad: 00000000`764d0000 00000000`765e9000   urlmon.dll
ModLoad: 00000000`77240000 00000000`772cf000   OLEAUT32.dll
ModLoad: 00000000`75260000 00000000`75269000   VERSION.dll
ModLoad: 00000000`76470000 00000000`764d0000   IMM32.dll
ModLoad: 00000000`75f20000 00000000`75fec000   MSCTF.dll
ModLoad: 00000000`6ed20000 00000000`6eda0000   UxTheme.dll
ModLoad: 00000000`6caf0000 00000000`6cb7c000   UIAutomationCore.DLL
ModLoad: 00000000`75b10000 00000000`75b15000   PSAPI.DLL
ModLoad: 00000000`74260000 00000000`7429c000   OLEACC.dll
ModLoad: 00000000`74220000 00000000`7422b000   profapi.dll
ModLoad: 00000000`73050000 00000000`73181000   WindowsCodecs.dll
ModLoad: 00000000`71fe0000 00000000`7202c000   apphelp.dll
ModLoad: 00000000`763e0000 00000000`76463000   CLBCatQ.DLL
ModLoad: 00000000`66f10000 00000000`66f22000   TORTOISEOVERLAYS.dll
ModLoad: 00000000`66f30000 00000000`66f44000   TortoiseStub32.dll
ModLoad: 00000000`66ea0000 00000000`66f0f000   TortoiseSVN32.dll
ModLoad: 00000000`66b40000 00000000`66e9d000   libsvn_tsvn32.dll
ModLoad: 00000000`66b10000 00000000`66b35000   libapr_tsvn32.dll
ModLoad: 00000000`75da0000 00000000`75dd5000   WS2_32.dll
ModLoad: 00000000`77d50000 00000000`77d56000   NSI.dll 
ModLoad: 00000000`741e0000 00000000`7421c000   MSWSOCK.dll
ModLoad: 00000000`66a30000 00000000`66b06000   MSVCR110.dll
ModLoad: 00000000`669f0000 00000000`66a28000   libaprutil_tsvn32.dll
ModLoad: 00000000`75b90000 00000000`75bd5000   WLDAP32.dll
ModLoad: 00000000`6e250000 00000000`6e25d000   intl3_tsvn32.dll
ModLoad: 00000000`669d0000 00000000`669e3000   libsasl32.dll
ModLoad: 00000000`71eb0000 00000000`71eb8000   Secur32.dll
ModLoad: 00000000`755a0000 00000000`756c1000   CRYPT32.dll
ModLoad: 00000000`759e0000 00000000`759ec000   MSASN1.dll
ModLoad: 00000000`66940000 00000000`669c5000   MSVCP110.dll
ModLoad: 00000000`668c0000 00000000`668f1000   EhStorAPI.DLL
ModLoad: 00000000`75780000 00000000`7591d000   SETUPAPI.dll
ModLoad: 00000000`75ae0000 00000000`75b07000   CFGMGR32.dll
ModLoad: 00000000`77480000 00000000`77492000   DEVOBJ.dll
ModLoad: 00000000`6eb40000 00000000`6ec35000   PROPSYS.dll
ModLoad: 00000000`667e0000 00000000`66850000   ntshrui.dll
ModLoad: 00000000`74100000 00000000`74119000   srvcli.dll
ModLoad: 00000000`6e8d0000 00000000`6e8db000   CSCAPI.dll
ModLoad: 00000000`66930000 00000000`6693a000   slc.dll 
ModLoad: 00000000`6dd00000 00000000`6dd13000   dwmapi.dll
ModLoad: 00000000`75170000 00000000`75183000   SendMail.dll
ModLoad: 00000000`741c0000 00000000`741d2000   MPR.dll 
ModLoad: 00000000`6ca00000 00000000`6cae2000   NCNETPROVIDER.dll
ModLoad: 00000000`73030000 00000000`73049000   NCLangID.dll
ModLoad: 00000000`72480000 00000000`724a8000   MAPBASE.dll
ModLoad: 00000000`50d20000 00000000`50d54000   CALWIN32.DLL
ModLoad: 00000000`50d00000 00000000`50d1a000   CLNWIN32.DLL
ModLoad: 00000000`50df0000 00000000`50e15000   LOCWIN32.dll
ModLoad: 00000000`50db0000 00000000`50de5000   NCPWIN32.DLL
ModLoad: 00000000`50da0000 00000000`50db0000   CLXWIN32.DLL
ModLoad: 00000000`03400000 00000000`03435000   NETWIN32.DLL
ModLoad: 00000000`73db0000 00000000`73db7000   WSOCK32.dll
ModLoad: 00000000`6c940000 00000000`6c9ff000   MSVCR100.dll
ModLoad: 00000000`716a0000 00000000`716db000   NWSHLXNT.dll
ModLoad: 00000000`74130000 00000000`74141000   NETAPI32.dll
ModLoad: 00000000`74120000 00000000`74129000   netutils.dll
ModLoad: 00000000`740f0000 00000000`740ff000   wkscli.dll
ModLoad: 00000000`740e0000 00000000`740ef000   samcli.dll
ModLoad: 00000000`74230000 00000000`7423d000   browcli.dll
ModLoad: 00000000`71ec0000 00000000`71ecd000   WTSAPI32.dll
ModLoad: 00000000`735e0000 00000000`735e5000   image00000000`735e0000
ModLoad: 00000000`71680000 00000000`71697000   image00000000`71680000
ModLoad: 00000000`71630000 00000000`7164a000   image00000000`71630000
ModLoad: 00000000`6c8c0000 00000000`6c93c000   image00000000`6c8c0000
ModLoad: 00000000`73020000 00000000`73028000   drprov.dll
ModLoad: 00000000`70c70000 00000000`70c99000   WINSTA.dll
ModLoad: 00000000`71530000 00000000`71544000   NTLANMAN.dll
ModLoad: 00000000`71510000 00000000`71527000   davclnt.dll
ModLoad: 00000000`72fc0000 00000000`72fc8000   DAVHLPR.dll
ModLoad: 00000000`72eb0000 00000000`72eb9000   ktmw32.dll
ModLoad: 00000000`751d0000 00000000`751f1000   NTMARTA.dll
(5a0.1728): Break instruction exception - code 80000003 (first chance)
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Windows\SYSTEM32\ntdll.dll - 
ntdll!DbgBreakPoint:
00000000`77bece30 cc              int     3
0:008> .sympath+ SRV*c:\symbols*http://msdl.microsoft.com/download/symbols
Symbol search path is: SRV*c:\symbols*http://msdl.microsoft.com/download/symbols
Expanded Symbol search path is: srv*c:\symbols*http://msdl.microsoft.com/download/symbols

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       SRV*c:\symbols*http://msdl.microsoft.com/download/symbols
0:008> ~*kb

   0  Id: 5a0.4b0 Suspend: 1 Teb: 00000000`7efdb000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`752fc1ff : 00000000`0036f388 00000000`0036f3a0 00000000`0036f37c 00000000`7efdb000 : ntdll!ZwCreateFile+0xa
00000000`752ed18f : 00000000`0036f388 00000000`00000000 00000000`00000000 00000000`00000060 : wow64!whNtCreateFile+0x10f
00000000`75272776 : 00000000`773978d7 00000000`752e0023 00000000`00200246 00000000`0036f530 : wow64!Wow64SystemServiceEx+0xd7
00000000`752ed286 : 00000000`00000000 00000000`75271920 ffffffff`fc710000 00000000`77bce111 : wow64cpu!ServiceNoTurbo+0x2d
00000000`752ec69e : 00000000`00000000 00000000`00000000 00000000`752e4b10 00000000`7ffe0030 : wow64!RunCpuSimulation+0xa
00000000`77be16f6 : 00000000`00153370 00000000`00000000 00000000`77cce670 00000000`77ca1920 : wow64!Wow64LdrpInitialize+0x42a
00000000`77c3cdb0 : 00000000`00000000 00000000`77be0e01 00000000`0022f210 00000000`00000000 : ntdll!RtlUniform+0x6e6
00000000`77bcb78e : 00000000`0022f210 00000000`00000000 00000000`7efdf000 00000000`00000000 : ntdll!EtwEventSetInformation+0x15158
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

   1  Id: 5a0.1af4 Suspend: 1 Teb: 00000000`7efd8000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`75272bf1 : 00000000`75a6ad9e 00000000`00000023 00000000`00000246 00000000`0233f6d4 : wow64cpu!CpupSyscallStub+0x9
00000000`752ed286 : 00000000`00000000 00000000`75271920 00000000`00000000 00000000`00000000 : wow64cpu!Thunk0ArgReloadState+0x23
00000000`752ec69e : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wow64!RunCpuSimulation+0xa
00000000`77c14ff4 : 00000000`00000000 00000000`7efdf000 00000000`7efd8000 00000000`00000000 : wow64!Wow64LdrpInitialize+0x42a
00000000`77bcb78e : 00000000`0014f2a0 00000000`00000000 00000000`7efdf000 00000000`00000000 : ntdll!RtlIsDosDeviceName_U+0x1f5c4
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

   2  Id: 5a0.548 Suspend: 1 Teb: 00000000`7efd5000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`75272bf1 : 00000000`77d901e4 00000000`00000023 00000000`00000202 00000000`0286fecc : wow64cpu!CpupSyscallStub+0x9
00000000`752ed286 : 00000000`00000000 00000000`75271920 00000000`00000000 00000000`00000000 : wow64cpu!Thunk0ArgReloadState+0x23
00000000`752ec69e : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wow64!RunCpuSimulation+0xa
00000000`77c14ff4 : 00000000`00000000 00000000`7efdf000 00000000`7efd5000 00000000`00000000 : wow64!Wow64LdrpInitialize+0x42a
00000000`77bcb78e : 00000000`0212f5d0 00000000`00000000 00000000`7efdf000 00000000`00000000 : ntdll!RtlIsDosDeviceName_U+0x1f5c4
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

   3  Id: 5a0.1524 Suspend: 1 Teb: 00000000`7efad000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`7530a4fb : 00000000`00000000 00000000`00000000 00000000`75272450 00000000`7530a968 : ntdll!NtWaitForWorkViaWorkerFactory+0xa
00000000`752ed18f : 00000000`0328f65c ffffffff`00000000 00000000`00000000 00000000`00000060 : wow64!whNtWaitForWorkViaWorkerFactory+0x23
00000000`75272776 : 00000000`77d901e4 00000000`00000023 00000000`00000246 00000000`0328fb98 : wow64!Wow64SystemServiceEx+0xd7
00000000`752ed286 : 00000000`00000000 00000000`75271920 00000000`00000000 00000000`00000000 : wow64cpu!ServiceNoTurbo+0x2d
00000000`752ec69e : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wow64!RunCpuSimulation+0xa
00000000`77c14ff4 : 00000000`00000000 00000000`7efdf000 00000000`7efad000 00000000`00000000 : wow64!Wow64LdrpInitialize+0x42a
00000000`77bcb78e : 00000000`00a7f490 00000000`00000000 00000000`7efdf000 00000000`00000000 : ntdll!RtlIsDosDeviceName_U+0x1f5c4
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

   4  Id: 5a0.18a8 Suspend: 1 Teb: 00000000`7efaa000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`7527283e : 00000000`77d901e4 00000000`00000023 00000000`00000246 00000000`033fffe4 : wow64cpu!CpupSyscallStub+0x9
00000000`752ed286 : 00000000`00000000 00000000`75271920 00000000`00000000 00000000`00000000 : wow64cpu!WaitForMultipleObjects32+0x3b
00000000`752ec69e : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wow64!RunCpuSimulation+0xa
00000000`77c14ff4 : 00000000`00000000 00000000`7efdf000 00000000`7efaa000 00000000`00000000 : wow64!Wow64LdrpInitialize+0x42a
00000000`77bcb78e : 00000000`0221f670 00000000`00000000 00000000`7efdf000 00000000`00000000 : ntdll!RtlIsDosDeviceName_U+0x1f5c4
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

   5  Id: 5a0.d34 Suspend: 1 Teb: 00000000`7efa4000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`7527283e : 00000000`77da01a9 00000000`00000023 00000000`00000246 00000000`047bfa68 : wow64cpu!CpupSyscallStub+0x9
00000000`752ed286 : 00000000`00000000 00000000`75271920 00000000`00000000 00000000`00000000 : wow64cpu!WaitForMultipleObjects32+0x3b
00000000`752ec69e : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wow64!RunCpuSimulation+0xa
00000000`77c14ff4 : 00000000`00000000 00000000`7efdf000 00000000`7efa4000 00000000`00000000 : wow64!Wow64LdrpInitialize+0x42a
00000000`77bcb78e : 00000000`0349f600 00000000`00000000 00000000`7efdf000 00000000`00000000 : ntdll!RtlIsDosDeviceName_U+0x1f5c4
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

   6  Id: 5a0.fe4 Suspend: 1 Teb: 00000000`7efa7000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`7530a4fb : 00000000`00000001 00000000`00000001 00000000`00000004 00000000`7530a968 : ntdll!NtWaitForWorkViaWorkerFactory+0xa
00000000`752ed18f : 00000000`04edf68c 00000000`04edf640 00000000`039ee9e0 00000000`00204020 : wow64!whNtWaitForWorkViaWorkerFactory+0x23
00000000`75272776 : 00000000`77d901e4 00000000`00000023 00000000`00000246 00000000`04edfd60 : wow64!Wow64SystemServiceEx+0xd7
00000000`752ed286 : 00000000`00000000 00000000`75271920 00000000`00000000 00000000`00000000 : wow64cpu!ServiceNoTurbo+0x2d
00000000`752ec69e : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wow64!RunCpuSimulation+0xa
00000000`77c14ff4 : 00000000`00000000 00000000`7efdf000 00000000`7efa7000 00000000`00000000 : wow64!Wow64LdrpInitialize+0x42a
00000000`77bcb78e : 00000000`039ef160 00000000`00000000 00000000`7efdf000 00000000`00000000 : ntdll!RtlIsDosDeviceName_U+0x1f5c4
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

   7  Id: 5a0.10b8 Suspend: 1 Teb: 00000000`7efa1000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`7530a4fb : 00000000`00000000 00000000`00000000 00000000`75272450 00000000`7530a968 : ntdll!NtWaitForWorkViaWorkerFactory+0xa
00000000`752ed18f : 00000000`0579f6c0 ffffffff`00000000 00000000`00000000 00000000`00000060 : wow64!whNtWaitForWorkViaWorkerFactory+0x23
00000000`75272776 : 00000000`77d901e4 00000000`00000023 00000000`00000246 00000000`0579fbfc : wow64!Wow64SystemServiceEx+0xd7
00000000`752ed286 : 00000000`00000000 00000000`75271920 00000000`00000000 00000000`00000000 : wow64cpu!ServiceNoTurbo+0x2d
00000000`752ec69e : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : wow64!RunCpuSimulation+0xa
00000000`77c14ff4 : 00000000`00000000 00000000`7efdf000 00000000`7efa1000 00000000`00000000 : wow64!Wow64LdrpInitialize+0x42a
00000000`77bcb78e : 00000000`0449f360 00000000`00000000 00000000`7efdf000 00000000`00000000 : ntdll!RtlIsDosDeviceName_U+0x1f5c4
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

#  8  Id: 5a0.1728 Suspend: 1 Teb: 00000000`7ef9e000 Unfrozen
RetAddr           : Args to Child                                                           : Call Site
00000000`77c93d18 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!DbgBreakPoint
00000000`77c03ef2 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!DbgUiRemoteBreakin+0x38
00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlIsDosDeviceName_U+0xe4c2
0:008> lmf
start             end                 module name
00000000`00a80000 00000000`00bee000   SumatraPDF C:\Program Files (x86)\SumatraPDF\SumatraPDF.exe
00000000`03400000 00000000`03435000   NETWIN32 NETWIN32.DLL
00000000`50d00000 00000000`50d1a000   CLNWIN32 CLNWIN32.DLL
00000000`50d20000 00000000`50d54000   CALWIN32 CALWIN32.DLL
00000000`50da0000 00000000`50db0000   CLXWIN32 CLXWIN32.DLL
00000000`50db0000 00000000`50de5000   NCPWIN32 NCPWIN32.DLL
00000000`50df0000 00000000`50e15000   LOCWIN32 LOCWIN32.dll
00000000`667e0000 00000000`66850000   ntshrui  ntshrui.dll 
00000000`668c0000 00000000`668f1000   EhStorAPI EhStorAPI.DLL
00000000`66930000 00000000`6693a000   slc      slc.dll     
00000000`66940000 00000000`669c5000   MSVCP110 MSVCP110.dll
00000000`669d0000 00000000`669e3000   libsasl32 libsasl32.dll
00000000`669f0000 00000000`66a28000   libaprutil_tsvn32 libaprutil_tsvn32.dll
00000000`66a30000 00000000`66b06000   MSVCR110 MSVCR110.dll
00000000`66b10000 00000000`66b35000   libapr_tsvn32 libapr_tsvn32.dll
00000000`66b40000 00000000`66e9d000   libsvn_tsvn32 libsvn_tsvn32.dll
00000000`66ea0000 00000000`66f0f000   TortoiseSVN32 TortoiseSVN32.dll
00000000`66f10000 00000000`66f22000   TORTOISEOVERLAYS TORTOISEOVERLAYS.dll
00000000`66f30000 00000000`66f44000   TortoiseStub32 TortoiseStub32.dll
00000000`6c8c0000 00000000`6c93c000   image00000000_6c8c0000 image00000000`6c8c0000
00000000`6c940000 00000000`6c9ff000   MSVCR100 MSVCR100.dll
00000000`6ca00000 00000000`6cae2000   NCNETPROVIDER NCNETPROVIDER.dll
00000000`6caf0000 00000000`6cb7c000   UIAutomationCore UIAutomationCore.DLL
00000000`6cb80000 00000000`6d087000   libmupdf libmupdf.dll
00000000`6dd00000 00000000`6dd13000   dwmapi   dwmapi.dll  
00000000`6e250000 00000000`6e25d000   intl3_tsvn32 intl3_tsvn32.dll
00000000`6e490000 00000000`6e62e000   COMCTL32 COMCTL32.dll
00000000`6e8d0000 00000000`6e8db000   CSCAPI   CSCAPI.dll  
00000000`6eb40000 00000000`6ec35000   PROPSYS  PROPSYS.dll 
00000000`6ed10000 00000000`6ed15000   MSIMG32  MSIMG32.dll 
00000000`6ed20000 00000000`6eda0000   UxTheme  UxTheme.dll 
00000000`70c70000 00000000`70c99000   WINSTA   WINSTA.dll  
00000000`71510000 00000000`71527000   davclnt  davclnt.dll 
00000000`71530000 00000000`71544000   NTLANMAN NTLANMAN.dll
00000000`71630000 00000000`7164a000   image00000000_71630000 image00000000`71630000
00000000`71680000 00000000`71697000   image00000000_71680000 image00000000`71680000
00000000`716a0000 00000000`716db000   NWSHLXNT NWSHLXNT.dll
00000000`71eb0000 00000000`71eb8000   Secur32  Secur32.dll 
00000000`71ec0000 00000000`71ecd000   WTSAPI32 WTSAPI32.dll
00000000`71fe0000 00000000`7202c000   apphelp  apphelp.dll 
00000000`72480000 00000000`724a8000   MAPBASE  MAPBASE.dll 
00000000`72eb0000 00000000`72eb9000   ktmw32   ktmw32.dll  
00000000`72fc0000 00000000`72fc8000   DAVHLPR  DAVHLPR.dll 
00000000`73020000 00000000`73028000   drprov   drprov.dll  
00000000`73030000 00000000`73049000   NCLangID NCLangID.dll
00000000`73050000 00000000`73181000   WindowsCodecs WindowsCodecs.dll
00000000`735e0000 00000000`735e5000   image00000000_735e0000 image00000000`735e0000
00000000`73830000 00000000`739c0000   gdiplus  gdiplus.dll 
00000000`73db0000 00000000`73db7000   WSOCK32  WSOCK32.dll 
00000000`740e0000 00000000`740ef000   samcli   samcli.dll  
00000000`740f0000 00000000`740ff000   wkscli   wkscli.dll  
00000000`74100000 00000000`74119000   srvcli   srvcli.dll  
00000000`74120000 00000000`74129000   netutils netutils.dll
00000000`74130000 00000000`74141000   NETAPI32 NETAPI32.dll
00000000`741c0000 00000000`741d2000   MPR      MPR.dll     
00000000`741e0000 00000000`7421c000   MSWSOCK  MSWSOCK.dll 
00000000`74220000 00000000`7422b000   profapi  profapi.dll 
00000000`74230000 00000000`7423d000   browcli  browcli.dll 
00000000`74260000 00000000`7429c000   OLEACC   OLEACC.dll  
00000000`75170000 00000000`75183000   SendMail SendMail.dll
00000000`751d0000 00000000`751f1000   NTMARTA  NTMARTA.dll 
00000000`75200000 00000000`75251000   WINSPOOL WINSPOOL.DRV
00000000`75260000 00000000`75269000   VERSION  VERSION.dll 
00000000`75270000 00000000`75278000   wow64cpu C:\Windows\SYSTEM32\wow64cpu.dll
00000000`75280000 00000000`752dc000   wow64win C:\Windows\SYSTEM32\wow64win.dll
00000000`752e0000 00000000`7531f000   wow64    C:\Windows\SYSTEM32\wow64.dll
00000000`75410000 00000000`7541c000   CRYPTBASE CRYPTBASE.dll
00000000`75420000 00000000`75480000   SspiCli  SspiCli.dll 
00000000`75480000 00000000`7551d000   USP10    USP10.dll   
00000000`75520000 00000000`7559b000   COMDLG32 COMDLG32.dll
00000000`755a0000 00000000`756c1000   CRYPT32  CRYPT32.dll 
00000000`756d0000 00000000`7577c000   msvcrt   msvcrt.dll  
00000000`75780000 00000000`7591d000   SETUPAPI SETUPAPI.dll
00000000`759e0000 00000000`759ec000   MSASN1   MSASN1.dll  
00000000`759f0000 00000000`75a47000   SHLWAPI  SHLWAPI.dll 
00000000`75a50000 00000000`75ae0000   GDI32    GDI32.dll   
00000000`75ae0000 00000000`75b07000   CFGMGR32 CFGMGR32.dll
00000000`75b10000 00000000`75b15000   PSAPI    PSAPI.DLL   
00000000`75b80000 00000000`75b8a000   LPK      LPK.dll     
00000000`75b90000 00000000`75bd5000   WLDAP32  WLDAP32.dll 
00000000`75be0000 00000000`75d9b000   iertutil iertutil.dll
00000000`75da0000 00000000`75dd5000   WS2_32   WS2_32.dll  
00000000`75de0000 00000000`75ef0000   KERNEL32 KERNEL32.dll
00000000`75f20000 00000000`75fec000   MSCTF    MSCTF.dll   
00000000`75ff0000 00000000`7614c000   ole32    ole32.dll   
00000000`76150000 00000000`76240000   RPCRT4   RPCRT4.dll  
00000000`76240000 00000000`76243000   Normaliz Normaliz.dll
00000000`76250000 00000000`7636b000   WININET  WININET.dll 
00000000`76370000 00000000`763b7000   KERNELBASE KERNELBASE.dll
00000000`763c0000 00000000`763d9000   SECHOST  SECHOST.dll 
00000000`763e0000 00000000`76463000   CLBCatQ  CLBCatQ.DLL 
00000000`76470000 00000000`764d0000   IMM32    IMM32.dll   
00000000`764d0000 00000000`765e9000   urlmon   urlmon.dll  
00000000`765f0000 00000000`7723b000   SHELL32  SHELL32.dll 
00000000`77240000 00000000`772cf000   OLEAUT32 OLEAUT32.dll
00000000`772d0000 00000000`77371000   ADVAPI32 ADVAPI32.dll
00000000`77380000 00000000`77480000   USER32   USER32.dll  
00000000`77480000 00000000`77492000   DEVOBJ   DEVOBJ.dll  
00000000`77ba0000 00000000`77d49000   ntdll    C:\Windows\SYSTEM32\ntdll.dll
00000000`77d50000 00000000`77d56000   NSI      NSI.dll     
00000000`77d80000 00000000`77f00000   ntdll_77d80000 ntdll.dll   

--

**Comment by fredinvdg** [comment]
Sorry, I didn't mean to close the issue.

**Comment by kjk** [comment]
Unfortunately I have no idea what is going on. Based on the callstacks, it looks like Sumatra code is not running at all, there are only system threads, all blocked.

**Comment by adenbley** [comment]
FWIW i'm also having this problem, but don't have the luxury of being able to disable mcafee. I have tried on past, current, and future version of sumatra; and with normal, and portable installations.

some versions:
McAfee Host Intrusion Prevention 8.0
McAfee Agent 4.8.0.1500
McAfee VirusScan Enterprise + AntiSpyware Enterprise 8.8.0 (8.8.0.1247)
