### ISSUE TITLE
SumatraPDF 3.3.13382 crash after pressing Q key

### ISSUE THREAD

**Issue by pulbitz** [sumatrapdfreader/sumatrapdf#1970]
SumatraPDF 3.3.13382 crash after pressing Q key.

[crashinfo.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6602453/crashinfo.zip)

**Comment by GitHubRulesOK** [comment]
@kjk 
On a sidenote the menu says CTRL+Q to quit a tab but has always accepted Q without CTRL and of consequence Q on a single tab exits application which may not expected, especially when using the nearby A key for annotation.

**Comment by kjk** [comment]
@GitHubRulesOK Good point about 'q' being close to 'a', will have to think about it.

But `Ctrl-q` is 'Exit app` while `q` is like 'Ctrl-w' i.e. close tab + exit if last tab.

**Comment by GitHubRulesOK** [comment]
@kjk
Manual is a tad unclear as Q alone is not on manual page and related are shown as
 

&lt;Ctrl&gt;&nbsp;+&nbsp;W | close current document
-- | --
&lt;Ctrl&gt;&nbsp;+&nbsp;F4 | also close current document
&lt;Ctrl&gt;&nbsp;+&nbsp;Q&nbsp;or&nbsp;q | quit program


Perhaps need to add a Q entry or drop its action as undefined
F4 closes ALL e.g. should be similar description to CTRL+Q
