### ISSUE TITLE
Annotation odd color behaviour in 3.3.13397

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1974]
Added Free  Text comment
Changed colour from default to RED to make it stand out but it now shows as white?
[OoPdfFormExample-annotated.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6609712/OoPdfFormExample-annotated.pdf)

**Comment by GitHubRulesOK** [comment]
On review the infill colors work but core "free TEXT" appear to become greyscale i.e. ranging from grey to white

**Comment by GitHubRulesOK** [comment]
@kjk 
Revisiting with latest version the previous wrong annotation background can be changed but Core Text color still cannot be corrected !

However on trying to add another similar problem text (with the latest build) I am not getting same bad behaviour, thus suggest that unless you can see from object analysis why there could be a difference, I suggest this issue be closed for now ?

**Comment by kjk** [comment]
Compared to mupdf, we detect `Text Color` incorrectly (should be white).

`Color` is "background color" and mupdf also seems to detect incorrectly. It's None/transparent (?) but detected as Black (probably because they only differ in alpha (0xff000000 for black and 0x00000000 for transparent)
