### ISSUE TITLE
Annotations and Save As

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1976]
Separate ? to Other Save As Issues

Opening a File that has either non SumatraPDF annotations OR ones previously saved by SumatraPDF.

If I make alterations such as amend come free text entry. I can use ALT+F+S to "Save As" the file

The "Save AS" function works as expected (and in latest version on saving OVER existing file, the RED reminder clears on the refreshed view)
However the changes to annotations are not in the file when reopened and the next click on the thought as changed item will revert it and then trigger a fresh You have unsaved changes :-)

**Comment by kjk** [comment]
Code: `OnMenuSaveAs`

Currently `Save As` only copies the bytes of the file. There is infra for `include annotations` option (from the old annotation code) but it's now unused.

Not sure what should we do? Always save annotations?

**Comment by GitHubRulesOK** [comment]
Unsure if "Save AS" can look-up and IF needed loop back to a "save with/without annotations dialog" ?

**Comment by GitHubRulesOK** [comment]
Closing this as stale issue covered by other more recent changes.
