### ISSUE TITLE
Crash whilst highlighting an area with image

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1978]
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6619345/sumatrapdfcrash.zip)

Source with no annotation

[OoPdfFormExample.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6619348/OoPdfFormExample.pdf)

What was attempted but does not appear to crash (not repeated so far)
[OoPdfFormExamplePlus.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6619370/OoPdfFormExamplePlus.pdf)

crash was initially triggered when double clicking upper image area after highlights were placed

I see from crash report other files are mentioned, some of which are temporary and not listed nor exist in settings.txt?

**Comment by GitHubRulesOK** [comment]
@kjk 
I have not personally repeated this issue with recent refactoring/changes so perhaps close for now unless you have similar reports, or I need to reopen ?

**Comment by kjk** [comment]
```
Crashed thread:
00007FF617DEBF33 01:000000000015AF33 sumatrapdf.exe!Annotation::SetColor+0x23 D:\a\sumatrapdf\sumatrapdf\src\Annotation.cpp+325
00007FF617DB5DC5 01:0000000000124DC5 sumatrapdf.exe!FrameOnChar+0xa25 D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+4051
00007FF617DB856D 01:000000000012756D sumatrapdf.exe!WndProcFrame+0x57d D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+4764
```

Most likely fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/78148a44546099b16a0dddf4a52e96a8b1bd62bb
