### ISSUE TITLE
Plugin mode does not work with negative HWND command line

### ISSUE THREAD

**Issue by vsemken** [sumatrapdfreader/sumatrapdf#1980]
I'm using Total Commander with the slister plugin, which loads SumatraPDF in plugin mode. This usually works fine, but sometimes it fails. If I open a file with the lister, I'd say in 20 to 30 per cent of the time it fails. In this case the Sumatra window is basically empty, as if no file is loaded and the calling programm hangs.

I traced this down to an issue with the plugin mode. The slister plugin is open source and it creates the comand line simelar to the example file for the plugin mode (plugin-test.cpp). Using ProcMon I found the following command line being used. 
"C:\Program Files (x86)\Total Commander\Viewer\SumatraPDF\SumatraPDF.exe" -plugin -27520030 "d:\Download\perfection_v500_office.pdf"
As the value is negative, the sign is passed to the function str::IsDigit in StrUtils.cpp and that one checks the first char only. The sign does cause the test to fail and plugin mode is not activated. 

I tried to send this parameter unsigned, which works for opening the file, but the slister plugin and the plugin-test.cpp use the function FindWindowEx to get a reference to the child window. That one seems to fail.

Any suggestion or possibility to fix this in the next version? I tried various version of SumatraPDF including the latest pre-release. This also happens with the 32 bit and 64 bit version of the slister plugin.

**Comment by kjk** [comment]
Plugin mode is no longer supported.

**Comment by vsemken** [comment]
That's a pity. Not supported as in "won't get fixed" or "not in 3.3"?
