### ISSUE TITLE
Active tab color is the same as inactive tabs

### ISSUE THREAD

**Issue by Dreamer8** [sumatrapdfreader/sumatrapdf#1985]
It's a minor issue, active tab is the same as inactive tabs, everything is the same, so it's impossible to see which tab is active.

Color of active tab should be different.

SumatraPDF v3.2 64-bit, Windows 10 20H2 64-bit..

**Comment by GitHubRulesOK** [comment]
@kjk although this is a duplicate (so will close once I find references later)

The problem appears "worser" in more recent win 10 so perhaps bump standard and hover contrasts to doubled?

![image](https://user-images.githubusercontent.com/12754913/121918408-eab6c100-cd2d-11eb-92d3-d3c87baadde4.png)
