### ISSUE TITLE
sumatrapdfcrash

### ISSUE THREAD

**Issue by iarithik** [sumatrapdfreader/sumatrapdf#1986]
https://gist.github.com/iarithik/5cbf87a834fe0cc2acf358b2678ea0ac

**Comment by GitHubRulesOK** [comment]
@kjk will need to confirm 
but that  problem from 2020-03-14 version should already have been fixed so please try a recent pre-release or better yet the current daily https://www.sumatrapdfreader.org/dailybuilds

**Comment by kjk** [comment]
Yes, based on a callstack that's a frequent 3.2 crash that I'm not seeing in latest daily builds anymore.
