### ISSUE TITLE
Is there a way to let it auto change view based on layout (portrait/landscape)?

### ISSUE THREAD

**Issue by lxvs** [sumatrapdfreader/sumatrapdf#1988]
Is there a way to let it auto change view based on layout (portrait/landscape)? E.g. book view when the pdf is in protrait layout, single page when landscape?

**Comment by kjk** [comment]
Sumatra doesn't have such capability.

**Comment by GitHubRulesOK** [comment]
@lxvs 
settings "options" default on opening to Book View and Fit Width will give you that for most of the time but **if A3 page** needs to be "Landscape" just quickly Toggle **on/off** "Fit Width" as required, should work in most cases
![image](https://user-images.githubusercontent.com/12754913/122493311-62f7dd80-cfdf-11eb-84f9-8ab719741c5e.png)

**Comment by lxvs** [comment]
> @lxvs
> settings "options" default on opening to Book View and Fit Width will give you that for most of the time but **if A3 page** needs to be "Landscape" just quickly Toggle **on/off** "Fit Width" as required, should work in most cases
> ![image](https://user-images.githubusercontent.com/12754913/122493311-62f7dd80-cfdf-11eb-84f9-8ab719741c5e.png)

Thanks for your advice, but IMHO, this is far from convenience, since I always disable continuous paging.

**Comment by GitHubRulesOK** [comment]
@lxvs 
If you want full portrait/Landscape pages without <kbd>C</kbd>ontinuous on then set **Default to Book View and Fit Page** then use the other icon **to the right* it will switch **single/double** page **on/off**
![image](https://user-images.githubusercontent.com/12754913/122640340-fa9c1f80-d0f6-11eb-8cc6-1c2acbca3172.png)

**Comment by lxvs** [comment]
> @lxvs
> If you want full portrait/Landscape pages without Continuous on then set **Default to Book View and Fit Page** then use the other icon _to the right_ it will switch **single/double** page **on/off** (most of the time)
> ![image](https://user-images.githubusercontent.com/12754913/122640340-fa9c1f80-d0f6-11eb-8cc6-1c2acbca3172.png)

This is sweet! Thanks for your help!

**Comment by GitHubRulesOK** [comment]
@lxvs Consider FACING Pages rather than "BOOK" view as on opening there will be either two portrait (or two landscape to toggle)
