### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by JW01** [sumatrapdfreader/sumatrapdf#199]
Unless I am missing something, it is not possible to search the contents of a file using SumatraPDF while other readers do have this capability.
I have a number of collected works, Jane Austen, Charles Dickens etc, and each collection is contained in a single mobi or epub file, so it would be very useful to be able to search them.

**Comment by kjk** [comment]
Search is available in PDF files. It still needs to be implemented for epub/mobi/etc. files.

**Comment by kjk** [comment]
dup of #268
