### ISSUE TITLE
Pdf is not displayed as expected

### ISSUE THREAD

**Issue by jagrin** [sumatrapdfreader/sumatrapdf#1990]
Hi,
I have a pdf file i cannot display properly in SumatraPdf. 
Or, at least, the display i get is different from what i get in firefox or edge.

The pdf can be found here : [https://cdn.1j1ju.com/medias/5c/3b/25-a-fistful-of-meeples-rulebook.pdf](url)

Attached are the result displayed in Firefox and in SumatraPDF (the SumatraPDF version is unreadable...)
I have no idea about the cause of this problem, this is the only pdf file with which i saw that kind of problem.

![SumatraPDF](https://user-images.githubusercontent.com/10414709/122582683-b5c1ab80-d058-11eb-9bf7-9ca3406a5245.JPG)
![Firefox](https://user-images.githubusercontent.com/10414709/122582684-b65a4200-d058-11eb-8813-802a9354b79a.JPG)

**Comment by GitHubRulesOK** [comment]
Very Interesting, 
I am trying to work out if they were exceptionally clever (copy obscuration) or stupid (poor PDF construction)
Clearly printing to PDF negates the clever and fixes the stupid
![image](https://user-images.githubusercontent.com/12754913/122590553-a131e300-d059-11eb-955d-c1180763410f.png)

**Comment by GitHubRulesOK** [comment]
Based on Stupidity I tried online conversion to Archival Quality PDF/A (which cannot fix the non readable/searchable font issues but sets the bad text positions enough so you can at least highlight the words graphically)

[25-a-fistful-of-meeples-rulebook-pdfa.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6678333/25-a-fistful-of-meeples-rulebook-pdfa.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk 
As the problem is with a PDF structure (not rendered well in some areas by MuPDF) I suspect they will declare as an invalid PDF but add a [link here](https://cdn.1j1ju.com/medias/5c/3b/25-a-fistful-of-meeples-rulebook.pdf) if you wish to consider worthy of a bug report

**Comment by GitHubRulesOK** [comment]
3.4.6 and pre-release are working with this file (unsure which version fixed it looks good in 3.4.0 not 3.3.3)

![image](https://user-images.githubusercontent.com/12754913/174463086-fd7970ce-0e87-426f-9146-f560a0449b69.png)
