### ISSUE TITLE
Annotation Warning on exit

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#1991]
Related to the other issues when closing a document with unsaved annotation

An editor user normally expects to be offered 3 options depending on context yes-no-cancel (/continue)

I understand you have allowed for this indirectly within the 2 options = Save them Yes or No

![image](https://user-images.githubusercontent.com/12754913/122619971-a60e8b00-d089-11eb-9a9a-e5d82b6f05bd.png)

My USER **perceived** choice is to Yes=Corrupt a Master PDF document No=Abandon all annotation that were not saved thus I might not know if I select Yes I can choose between **Yes** "Overwrite OR As New filename."

Without that extra info I may naturally pick NO and then be annoyed at closure without any choice to cancel and continue with a different Save As occasion/method. (Which is a different issue)

**Comment by kjk** [comment]
I agree it's not great but probably after 3.3.

This is a standard message box which are trivial to show but limit what you can put on the buttons.

It should be a custom dialog that says something like:
```
You have unsaved annotations in `foo.pdf`.

[Save to a new PDF] [Save to 'foo.pdf`] [Discard]
```

**Comment by GitHubRulesOK** [comment]
from vba experience its a "small" bit change to show 3 buttons the ["matter of programming" (SMOP)](https://en.wikipedia.org/wiki/Small_matter_of_programming) is how to abort saving ?

**Comment by kjk** [comment]
Not sure I understand the proposal. Those are the options for message box: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messagebox (see `uType` and `MB_*` constants).

What should the message say and which of the `MB_` constant should I use?

**Comment by GitHubRulesOK** [comment]
I have no clue about VS C++ and its options but VBA uses a flag /value to alter Message Box from Yes/No to Yes/No/Cancel 
The issue then, is how easy to catch the selected cancel return code and abort the imminent requested closure, without knowing what/where the call was initiated, thus I ASSume in some cases leading to a potential instability ?
