### ISSUE TITLE
Indicate currently edited annotation on the page

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#1996]
It's hard to tell which annotation is being edited. Indicate currently selected annotation in the editor on the page by e.g. drawing a focus ring around it.

**Comment by GitHubRulesOK** [comment]
@kjk 
Apart from the fact is a horrible thick black slap in the face, this seems to have been addressed ?

**Comment by kjk** [comment]
yep, thanks for spotting this
