### ISSUE TITLE
Planning 3.1 release

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#20]
To me, we could release 3.1 if #18 or #19 (or both) are implemented. Those are the 2 most requested improvements.

**Comment by zeniko** [comment]
I don't see any progress on either of the mentioned bugs. Given issues like #40 and other security and correctness fixes, I'd suggest aiming for an early March release with what we've got until then instead of holding on indefinitely.

**Comment by kjk** [comment]
The release criteria has always been: we have some new user-visible features.
 They don't have to be those 2 but currently we have none.

**Comment by zeniko** [comment]
We have multiple known bugs which repeatedly confuse our users. I'd consider no longer having these as user-visible enough. If you don't consider this enough for 3.1, let's just call it bug fix release 3.0.1 (and disable automatic session restoration so that there are no unexpected new features in it).

**Comment by kjk** [comment]
It's not about naming but limiting the number of times people have to upgrade.

If you prepare the code (i.e create a 3.0.1 branch and make the necessary changes) I can make 3.0.1 release, but without enabling auto-updates. New downloads will get 3.0.1 but we wouldn't notify about new version until 3.1.

**Comment by zeniko** [comment]
For me, this is the wrong trade-off - in particular, if there's also security fixes involved. Anyway, I'm not going to fight for a proper release but will rather take some time off (trying not to care).

**Comment by Shragel** [comment]
It's June already. So maybe lets just release.

**Comment by kjk** [comment]
Comment 3 describes release criteria. Nothing has changed in that regard.
