### ISSUE TITLE
collapse all bookmarks to level n

### ISSUE THREAD

**Issue by andy080** [sumatrapdfreader/sumatrapdf#200]
Hi all 

(I have looked but this functionality does not seem to be present)

I have many textbooks in PDF format. Some of them have a lot of chapters and a lot of nesting in the bookmarks (even within chapters).

I would like to be able to collapse the bookmark "tree" to a specific level e.g.
- collapse to level 2  -> result: I see only chapter titles
- collapse to level 3 -> result: I see only chapter titles and the chapter sections

Is this level of control possible?

Thank you in advance and well done for a great program!

Andy

**Comment by kjk** [comment]
We use standard windows tree control. If it doesn't support that, then neither do we.

**Comment by andy080** [comment]
OK. That's a shame. Thanks for the quick answer!
