### ISSUE TITLE
Save state before ctrl-shift-n

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2001]
This is so that the file opens in a new window at the same position.

Maybe add ctrl-alt-n for opening in a new tab.

Related to #46

**Comment by GitHubRulesOK** [comment]
I will close https://github.com/sumatrapdfreader/sumatrapdf/issues/1448# as a more muddled older duplicate of this description. For illustration, here is a recent screenshot where the file was last stored as closed/opened at page 15 but a new window on page 91 will thus open the second copy at page 15.
https://github.com/sumatrapdfreader/sumatrapdf/issues/1448#
