### ISSUE TITLE
Find Next key binding

### ISSUE THREAD

**Issue by github-account1111** [sumatrapdfreader/sumatrapdf#2005]
Why F3? That's the most random thing ever. I don't even use the F-row, and I imagine most people don't either, because it's so far away from the main row, so one has to move hand (and thus lose focus) and look down at the keyboard every time. Not to mention I've set my keyboard to use Fn keys (Play/Pause/Vol Up/ Down etc) by default, so I have to press the FN key + F3 every time I want to progress to the next search result.

Why didn't you just do what literally every other software (at least the ones I've used) does, i.e. assign it to Enter? That way you don't have to search for anything (since you've just pressed it to find the word). Actually, why not let people rebind the keys? Also why not highlight all the results? Who wants to go through them one-by-one?

**Comment by kjk** [comment]
Those are not bad suggestions but we already have issues for most of them and the tone is unacceptable.
