### ISSUE TITLE
Context menu loses multi-language support

### ISSUE THREAD

**Issue by Megre** [sumatrapdfreader/sumatrapdf#2007]
These context menus lose multi-language support:
+ Create Annotation From Selection.
+ Create Annotation Under Cursor.

**Comment by kjk** [comment]
Not sure what you mean but Sumatra relies on translations provided by people who know the language.

If there are translations missing in a language you know, please contribute at http://www.apptranslator.org/app/SumatraPDF

**Comment by Megre** [comment]
> Not sure what you mean but Sumatra relies on translations provided by people who know the language.
> 
> If there are translations missing in a language you know, please contribute at http://www.apptranslator.org/app/SumatraPDF

Thanks. You are right. I noticed some context menus are not translated. I will translate them at the site.
