### ISSUE TITLE
Debug crash CrashIf(zoom <= 0);

### ISSUE THREAD

**Issue by benyaminl** [sumatrapdfreader/sumatrapdf#2014]
See log 
https://gist.github.com/benyaminl/ecdb45ece1b2ed86ceeb864bd74f354d

It's new for me, I never encounter before, but yes this's pre-release, but is this normal? Or this shouldn't be bug? Thank you

**Comment by kjk** [comment]
Could you provide more information i.e. detailed steps for how to reproduce the crash?

**Comment by benyaminl** [comment]
> Could you provide more information i.e. detailed steps for how to reproduce the crash?

Just normal win+3 (jump number) from taskbar. I just minimize maximize minimize maximize. 

Is there anything else I could give to you to help? Seems it's very generic error and strange one, it wouldn't happen in normal case right? 

After rerun I have no problem with it.

**Comment by GitHubRulesOK** [comment]
@kjk 
two things catch my eye
TeX flag is true and there is a hint of compiling ?

Why is SumatraPDF scanning "everything" folder ?

**Comment by benyaminl** [comment]
What is that? Why TeX? I can't even run latext file with sumatra pdf why it
suddenly pop up?




Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by GitHubRulesOK** [comment]
@benyaminl 
To answer your question,

When SumatraPDF opens a PDF that has an attendant synctex file It automatically assumes you **may** want to use that file so sets the tex flag TRUE in preparation for an inverse call.

If you dont have an editor set then the double click will often invoke the default tex(t) editor (Notepad by default)

SO if I have Thesis.pdf AND Thesis.synctex.gz then a double click will _Open_ Thesis.tex at the required point within the default text editor but if none is set In my case it opens Notepad.exe.
However NotePad as a non TeX editor so has no idea which line to jump to.

**Comment by benyaminl** [comment]
> 
> 
> @benyaminl
> To answer your question,
> 
> When SumatraPDF _OPENS_ a PDF that has an **attendant** synctex[.gz] file (a TeX file at that point, may be anywhere so is not a condition of the trigger) It automatically assumes you **may** want to use that file so sets the tex flag TRUE in preparation for an inverse call. I am unsure if opening a pdf with a pdfsync file would also do the same, but guess it could.
> 
> If you dont have an editor set, then the double click will often invoke the default tex(t) editor (Notepad by default)
> 
> SO if I have Thesis.pdf AND Thesis.synctex[.gz] then a double click will _Open_ Thesis.tex at the required point within the default TeX editor but if none is set, as in my case, it opens the TeX in Notepad.exe.
> However NotePad as a non TeX editor has no idea which line to jump to.

I mean why it need to jump or such, Is that thing happen on my crash case?

**Comment by GitHubRulesOK** [comment]
@benyaminl
I dont analyse the CAUSE of crash that is for developer @kjk to look for any reason

I am an observer of common behaviours and can only say that it appears you have some problem files that appear to be commonly compiled using LaTeX even if you are not using it. Normally (but depending on user settings) a synctex file is deleted after a successful compile. However for Example Sets or convenience synctex files may be retained for a fast editor launch from SumatraPDF best done when all 3 files are in the same folder.

**Comment by kjk** [comment]
It's `CrashIf(zoom <= 0);`

I've seen this crash before but so far I've been unable to reproduce it.

Based on your information it might be related to minimizing/maximing the window but I've been unable to reproduce it so far.

It would help if you could provide a sequence of steps that reliably cause the crash.

I tried minimizing / maximizing using window min/max buttons, by clicking  on taskbar sumatra icon and with `Win- ${num}` keyboard shortcut. I had 2 PDF documents open. Couldn't reproduce so far.

**Comment by kjk** [comment]
```
00007FF7827650B5 01:00000000001740B5 sumatrapdf.exe!EnginePdf::Transform+0xa5 D:\a\sumatrapdf\sumatrapdf\src\EnginePdf.cpp+1275
00007FF7826CCB6A 01:00000000000DBB6A sumatrapdf.exe!DisplayModel::CvtToScreen+0xca D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+975
00007FF7826CF3A2 01:00000000000DE3A2 sumatrapdf.exe!DisplayModel::SetScrollState+0x92 D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+1763
00007FF7826CD279 01:00000000000DC279 sumatrapdf.exe!DisplayModel::SetViewPortSize+0xf9 D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+1135
00007FF78273515B 01:000000000014415B sumatrapdf.exe!WindowInfo::UpdateCanvasSize+0x20b D:\a\sumatrapdf\sumatrapdf\src\WindowInfo.cpp+164
00007FF7826C2C3E 01:00000000000D1C3E sumatrapdf.exe!WndProcCanvas+0x38e D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1616
00007FFCE896E858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FFCE896DE1B 01:000000000000CE1B user32.dll!SendMessageW+0x86b
00007FFCE896CBC3 01:000000000000BBC3 user32.dll!GetWindowTextW+0x8d3
00007FFCE896C2AF 01:000000000000B2AF user32.dll!IsIconic+0xbf
00007FFCE546B889 01:000000000000A889 uxtheme.dll!IsCompositionActive+0x2039
00007FFCE546B271 01:000000000000A271 uxtheme.dll!IsCompositionActive+0x1a21
00007FFCE896C7E3 01:000000000000B7E3 user32.dll!GetWindowTextW+0x4f3
00007FF7826C1953 01:00000000000D0953 sumatrapdf.exe!WndProcCanvasFixedPageUI+0x153 D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1375
00007FF7826C2956 01:00000000000D1956 sumatrapdf.exe!WndProcCanvas+0xa6 D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1650
00007FFCE896E858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FFCE896E3DC 01:000000000000D3DC user32.dll!DispatchMessageW+0x39c
00007FFCE8985BF0 01:0000000000024BF0 user32.dll!LookupIconIdFromDirectoryEx+0x2b0
00007FFCEA8D0C54 01:000000000009FC54 ntdll.dll!KiUserCallbackDispatcher+0x24
00007FFCE8261504 01:0000000000000504 win32u.dll!NtUserEndDeferWindowPosEx+0x14
00007FF782714C75 01:0000000000123C75 sumatrapdf.exe!RelayoutFrame+0x615 D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+3370
00007FF782719754 01:0000000000128754 sumatrapdf.exe!WndProcFrame+0x114 D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+4883
```

It seems to originate from `RelayoutFrame`

**Comment by benyaminl** [comment]
I remember now.. I use WinActivate and WinMinimize from. AHK.

Does that count?

But before I did use Win+5 then Win+S to bring to front




Regards,
Benyamin Limanto
sent from my Sony XPERIA XZ Premium

**Comment by kjk** [comment]
The bug could be triggered by AHK doing something differently, so it's a clue.

Either, this shouldn't happen in latest daily build.

**Comment by benyaminl** [comment]
> 
> 
> The bug could be triggered by AHK doing something differently, so it's a clue.
> 
> Either way, this shouldn't happen in latest daily build.

Confirmed not error anymore on AHK using WinMinimize and WinMaximize. Neat. Thanks
