### ISSUE TITLE
Sumatra PDF Crash when Select Annotation in Editor

### ISSUE THREAD

**Issue by benyaminl** [sumatrapdfreader/sumatrapdf#2016]
This is the log 
https://gist.github.com/benyaminl/56f98b07b00ff8ffce9e289c2c7f5c85

Seems I click wrong menu when annotate (This's pre build version that just been updated)

I think this related to what @GitHubRulesOK said in last comment on https://github.com/sumatrapdfreader/sumatrapdf/issues/2014#issuecomment-877145147

But I opening PDF and tried to use menu "select annotation in editor"

Seems because it select Notepad.exe? Or other thing that isn't implemented so lead to this problem? 

Sorry to opening 2nd issue. 🙏

**Comment by GitHubRulesOK** [comment]
@kjk 
until recently scroll pos would be low integer say -1,-1

current build is showing 
ScrollPos = -1082130432 -1082130432 ?

is that expected ?

**Comment by kjk** [comment]
@benyaminl Don't feel bad about opening issues. They help me improve Sumatra.

This was a recent regression, which should be fixed now.

@GitHubRulesOK I've opened a separate issue for the weird ScrollPos. Doesn't look right.
