### ISSUE TITLE
Look into ScrollPos = -1082130432 -1082130432 ?

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2017]
From https://github.com/sumatrapdfreader/sumatrapdf/issues/2016

Probably shouldn't be like this, need to look into it.

**Comment by benyaminl** [comment]
hello just want to add, now any epub that I tried to open cause sumatra pdf crash with same error, this is really strange

**Comment by kjk** [comment]
@benyaminl I've opened a separate issue for the epub crash at https://github.com/sumatrapdfreader/sumatrapdf/issues/2018

**Comment by kjk** [comment]
Regression from https://github.com/sumatrapdfreader/sumatrapdf/issues/1752
where I changed scroll position from int to float but didn't change
the serialization as int
