### ISSUE TITLE
Can't build the latest version

### ISSUE THREAD

**Issue by skipik** [sumatrapdfreader/sumatrapdf#2019]
![123](https://user-images.githubusercontent.com/24621645/125160069-a3342100-e183-11eb-8335-c35059c0285c.png)

Visual Studio 2019 v16.10.3

**Comment by kjk** [comment]
Should already be fixed.

**Comment by skipik** [comment]
Shame but it's not :(

![111](https://user-images.githubusercontent.com/24621645/125173966-dcdc4a80-e1ca-11eb-8801-7d2486100a24.png)

**Comment by kjk** [comment]
Fixed now. It only happens in 32 build which I rarely do.
