### ISSUE TITLE
[Feature request] Advanced presentation mode

### ISSUE THREAD

**Issue by faramir** [sumatrapdfreader/sumatrapdf#202]
Add possibility to use presentation mode with notes visible in different window and screen, while main window is fullscreen on one screen.

In the beamer, notes can be put in other PDF file and switching slides should also changes page in notes. Additionally, beamer allows to create wide (or tall) slides, where half of the slide is treated as real slides, and other side is left for notes.

Ideally, I would like to have something similar to http://pympress.org (
![screenshot-presenter](https://cloud.githubusercontent.com/assets/567976/7739723/60a99172-ff66-11e4-9663-171ab0eab411.png)
) - with clock, elapsed time, current and next slide or notes.

**Comment by kjk** [comment]
We don't have plans to work on that.

**Comment by faramir** [comment]
For people who wish to have similar feature, I have prepared standalone Java application to do something similar to "advanced presentation mode" described here: https://github.com/faramir/BeamerPresenter
