### ISSUE TITLE
pdf rendering become slower after zoom in/out in version 3.3(compared with 3.1.2)

### ISSUE THREAD

**Issue by ccabbey** [sumatrapdfreader/sumatrapdf#2020]
i've been using version 3.1.2 for years for viewing some large-scale pdf engineering drawings(vector graphics converted from catia file). 

before that, i use Acrobat to read the same pdf files, for some reason i need to repeatly zoom in-zoom out all the time when reading those pdf drawings, and every time after i zoomed in/out, the graphics will become fuzzy for less than a second, with a noticeable lag, and then become clear. it seems like the graphics is re-rendering itself everytime after when i zoom in/out. however i found that somehow the re-rendering process is incrediblely fast when using sumatra(10 times faster at least). for this reason i've been using sumatra since then. 

few days ago i found that sumatra has been updated so i switched from v3.1.2 to v3.3. then i found that the rendering process become just as slow as when i use Acrobat. at first i thought it was my computer, then i switch back to version 3.1.2, it is fast as usual, and then back to 3.3, it become slow again. i really can not bear the lagging so i have no chioce but to stay at version 3.1.2.

i'm not a professional programmer so it's way beyond my ability to solve this, but i really love this software, i hope i can do something to make it better. if you need any further information please feel free to ask. thanks again for making this wonderful software!

the fuzzy issue is just like this as below: and this happens every time when i zoom in/out
![2021-07-12_01-32-02](https://user-images.githubusercontent.com/47359140/125204698-18e9db00-e2b1-11eb-92ba-47c227c2a498.png)

**Comment by kjk** [comment]
You would have to provide the file for which that happens for me to investigate. See https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

**Comment by ccabbey** [comment]
thanks for reply, i have read the guide. the issued file is confidencial so i have sent it via email, thanks!

**Comment by kjk** [comment]
3.3 seems about 30% slower than 3.1.2 in rendering this doc. Not insignificant but not some giant change. Nothing stands out in profile as being slow and it's all in mupdf code.

As to zoom in / out I don't see much difference between 3.1.2 and 3.3 on my laptop. They both have visible fuzziness / log before becoming sharp but I wouldn't say one version is so much better than the other.

Maybe there is some trick to improve perceived speed of rendering like caching of rendered bitmaps at various zoom levels.

**Comment by ccabbey** [comment]
thanks for looking into this, regarding the zoom in fuzziness issue, i have tested again, in 3.1.2 the lagging does exists too but it is very short, so the reading experience is still fluent. but in 3.3 the lagging breaks your reading.
maybe there is something with my computer though, considering that you didn't find much difference between 3.1.2 and 3.3.
i'll do some some test and let you know.
