### ISSUE TITLE
DjVu not rotation in version 3.3

### ISSUE THREAD

**Issue by Lis105** [sumatrapdfreader/sumatrapdf#2021]
The new version 3.3 does not rotate DjVu files again!

**Comment by kjk** [comment]
Yes, unfortunately it was fixed after 3.3 release in https://github.com/sumatrapdfreader/sumatrapdf/commit/009c8ab35059d58077fb4388436bb9648e181894

It's fixed in pre-release version https://www.sumatrapdfreader.org/prerelease
