### ISSUE TITLE
Add advanced settings for default icon / color of Text annotation

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2025]
As per https://forum.sumatrapdfreader.org/t/shortcut-for-inserting-text-annotation-on-current-mouse-position/4180/8

**Comment by GitHubRulesOK** [comment]
C++ Syntax eludes me but is that the Alpha at the end RGBA(0xff, 0, 0, 0) thus default is Full RED but 0=? Opacity

**Comment by kjk** [comment]
Good catch, it was a debug value.
