### ISSUE TITLE
Characters in diagrams rendering as "▯"

### ISSUE THREAD

**Issue by talenelat-elin** [sumatrapdfreader/sumatrapdf#2028]
![image](https://user-images.githubusercontent.com/71895835/125766440-5f1feefb-0d77-4520-824d-5b648dc783e1.png)
The page in SumatraPDF.
<hr>

![image](https://user-images.githubusercontent.com/71895835/125766753-d82610c9-e2d3-41d7-8242-824f8536984d.png)

The same page in PDF.js in Firefox 89
<hr>

![image](https://user-images.githubusercontent.com/71895835/125767045-cedfb503-78e9-491c-8730-c604cf6f4632.png)

The same page in Foxit Reader

All diagrams in this particular pdf are having the same issue. I can't upload the file here for copyright reasons, but I'll email it if you want. 
<hr>
Windows 10
Latest SumatraPDF pre-release build, built on 2021-07-15 , commit ebb97bafd9ac87b3a22a3add2b46fe93bc135272
64 bit installer

**Comment by talenelat-elin** [comment]
Replicable in version 3.3.1, 64 bit, installer.

**Comment by GitHubRulesOK** [comment]
Most likely its a poor font recognition issue, the file needs to be sent privately (**not attached** to bug tracker) to MuPDF maintainers at https://bugs.ghostscript.com/ select MuPDF as the product with a bug and you could reference https://github.com/sumatrapdfreader/sumatrapdf/issues/2028# as showing effect. However as a non-customer there is no priority other than "normal"

**Comment by McGerbick** [comment]
@talenelat-elin: Have you already submitted a bug report for MuPDF? If so, I could try to vote up this bug.

I have encountered the similar font rendering problem with SumatraPDF 3.3.3 x64, here on tickets of the german railway (Deutsche Bahn), where special, German-specific characters (e.g. ü, ä, ö, ß) are not rendered and just shown as square. It may be a problem related to Type1 fonts.

In SumatraPDF version 3.2 this problem does not occur and those characters are rendered correctly.

**Comment by talenelat-elin** [comment]
@McGerbick
No, I didn't submit a report as I couldn't be bothered to make an account there. I just read that particular PDF in Firefox.

> in SumatraPDF version 3.2 this problem does not occur 
Thanks for this information! I'll try it.

**Comment by kjk** [comment]
@talenelat-elin Please e-mail me the file at kkowalczyk@gmail.com

**Comment by kjk** [comment]
@talenelat-elin Thanks, should be fixed in pre-release build https://www.sumatrapdfreader.org/prerelease in about an hour (if the build doesn't fail)

**Comment by kjk** [comment]
@McGerbick please open an issue and attach one of the files that mis-render (or e-mail me if file is private)

**Comment by McGerbick** [comment]
I've checked my affected PDF file with pre-release version 3.4.14025 64-bit and can confirm that all characters in that PDF are now displayed correctly again. Thanks for the fix.
