### ISSUE TITLE
in-file hyperlink works wrongly, pre-release v3.4.13750 64-bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2039]
version is pre-release v3.4.13750 64-bit

before, when i clicked the in-file hyperlink, e.g. contents, it would jump to the corresponding page. but in this version, it will jump to somewhere on the CURRENT page where i click the hyperlink.

**Comment by GitHubRulesOK** [comment]
@LqkUWp
A sample is required since there are many related changes in progress in pre-release. 
A note as to your last working version also helps.

**Comment by LqkUWp** [comment]
i remember that the version just before v3.4.13747 works fine, but cannot recall the whole version number.

there are 2 PDFs for test.

the 1st one is downloaded from https://arxiv.org/abs/2107.08369 and here is the behavior of Microsoft Edge and SumatraPDF

https://user-images.githubusercontent.com/28478572/126280280-1b07ae2e-49ae-4e7a-bff3-3ccaaff62740.mp4

https://user-images.githubusercontent.com/28478572/126280298-c486aadb-b03a-40c5-add7-b2e164cfe68b.mp4

the 2nd one is uploaded to [note.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6846348/note.pdf) and here is the behavior of Microsoft Edge and SumatraPDF. i notice that the contents in file page don't work while those in left-side bar <f12> work. 

https://user-images.githubusercontent.com/28478572/126280861-08c5d1ab-2576-4048-aeae-a02386b995d3.mp4

https://user-images.githubusercontent.com/28478572/126280873-767ab89b-f69d-4c8a-810e-0acf023aa13c.mp4
