### ISSUE TITLE
Sumatra hangs on Windows 8.1 64 bits

### ISSUE THREAD

**Issue by andreslb151** [sumatrapdfreader/sumatrapdf#204]
When viewing any file and scrolling down and up several times, it hangs.
I was viewing this file: https://www.dropbox.com/s/ko03objk0hyf5c9/Tarea%20Acad%C3%A9mica%201.pdf?dl=0
![console](https://cloud.githubusercontent.com/assets/3934748/7757861/fe721a96-ffca-11e4-9271-9c4717b86e09.png)

**Comment by kjk** [comment]
I couldn't reproduce this with 3.0 or latest pre-release (http://www.sumatrapdfreader.org/prerelease.html).

Which version of sumtra is this? Can you show a screenshot of Sumatra window when it's hanged?

It would be very helpful to also get information described in "Debugging a hang" in https://github.com/sumatrapdfreader/sumatrapdf/wiki/Debugging-Sumatra
