### ISSUE TITLE
version number showed wrongly, SumatraPDF-prerel-13767 64bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2040]
after installed SumatraPDF-prerel-13767 64bit from https://www.sumatrapdfreader.org/prerelease, when i open `help - about` from left-top bar, it shows `v3.4.13750` instead of `v3.4.13767`. if i click `help - check for updates`, it will pop to notify me that there is a newer version although i actually already installed the latest version.

**Comment by kjk** [comment]
Looks like I messed up the installer and it just runs the existing installer.

**Comment by kjk** [comment]
should be fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/f1d1803f52b9b4a7dd2bf1a931b5dc3214730026 (build 13775 or later)
