### ISSUE TITLE
Latest installer failed due to active handlers

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2041]
Sumatra update check downloaded and offered to update

![image](https://user-images.githubusercontent.com/12754913/126415591-d3aafa7c-3894-4818-b455-88fbab60bd25.png)

**Comment by kjk** [comment]
Before that did it also ask to terminate a process?

There installer tries to detect if `libmupdf.dll` is loaded by a process (which most likely indicates an active use of PdfFilter.dll or PdfPreview.dll) but it might not be perfect or it could be timing issue (libmupdf.dll is loaded after the check).

Not sure what to do here. Maybe just try to kill the processes holding libmupdf.dll loaded and retry?

**Comment by GitHubRulesOK** [comment]
I did not see the usual request and so manually uninstalled preview is not active and search filter seems to be not running but reinstall to program files is still blocked.
![image](https://user-images.githubusercontent.com/12754913/126417447-04ed7272-1d03-4137-a157-e142d2cbdf0a.png)![image](https://user-images.githubusercontent.com/12754913/126417481-daf5d8c0-df6c-4049-82be-e7c386f00b01.png)

**Comment by GitHubRulesOK** [comment]
I restarted after uninstall but program files still has last version so need to manually remove

I am a lowly user so need elevation to install and uninstall, would UAC during update have a bearing ?

**Comment by Rauvin** [comment]
I am having exactly the same problem, but have all privileges on my system. Just will not install and took several attempts to receive exactly the same error message as above (earlier fails were a generic windows dialogue)

I have the error file generated by the program if required, as well as the same error dialogue as shown above..

Existing instillation is now failing to start, but worked perfectly before the 3.3.3 update failed to install. (either directly or via launch icon)

**Comment by GitHubRulesOK** [comment]
@Rauvin
Which directory was previous install in (you say same as above e.g. Program Files ?) I.E you had to manually change from default for a single user ?
Ideally when the handlers are installed for Multiple Users they should by rights be uninstalled by the installer, it is my bad habit to let it update itself but recently I was used to portable.exe simply overwriting itself.

The main problem here is there is not the previous warning that explorer needs to be shutdown for insitu update.

That is generally needed to ensure deregistering the handlers works if active for preview or file indexing.
Normally I dont install search filter and avoid any pdf showing in preview, thus may on occasion get away without any termination message requirement.

**Comment by Rauvin** [comment]
The program is installed to D:\Program Files\SumatraPDF for all users on the PC, however only used on 1 account

**Comment by Rauvin** [comment]
OK... It has now installed without problem and is working again. Guess the switch it off & on again cleared the problem

**Comment by GitHubRulesOK** [comment]
@Rauvin 
Yes a reset will help but no need to switch off at the wall and wait 10 mins for capacitors to dissipate (old cathode tube habit :-)
All that should be needed is closing active explorer processes that have a hold of previews or searches that are using libmupdf.dll however it is possible that other process like AV scanning may have the dll in lockdown. USUALLY SumatraPDF uninstall should warn that it can't **deregister** one ore more dlls.

**Comment by GitHubRulesOK** [comment]
@kjk 
to test recent previewer I had to go though uninstall re-install cycle and it was obvious iUNinstaller reported it had removed SumatraPDF however yet again the files had not been deleted nor folder removed.
I could not delete files until manually closing most active explorer windows and it was not obvious which of those was caching preview host as I had tried to un-focus all previewed contents

**Comment by GitHubRulesOK** [comment]
Curently not getting the same problem since running on another system (32bit Win 7)
so closing this issue unless it need to be reopened under known circumstances (previously using windows 10)
