### ISSUE TITLE
Handling of MuPDF-related patchs

### ISSUE THREAD

**Issue by Lucas-C** [sumatrapdfreader/sumatrapdf#2043]
Hi!

Thank you for merging in some recent patches in MuPDF (commits 2b791ca & b1e505d) that fixed some small rendering glitches! _cf._ https://git.ghostscript.com/?p=mupdf.git;a=summary

<details>

Undying Dusk front 3rd page with MuPDF 1.18.0, with visual glitches highlighted in green :
![UndyingDusk-page3-mupdf-1 18 0](https://user-images.githubusercontent.com/925560/126452581-2cbb11ce-65f7-4431-b490-a1e14370e2f8.png)

Undying Dusk front 3rd page with latest version of MuPDF :
![UndyingDusk-page3-mupdf-latest](https://user-images.githubusercontent.com/925560/126452619-1ce67b25-85ba-4eae-b70c-a28bc7f75fd2.png)
</details>

Sadly this removed a patch I made a few days ago 😢:
https://github.com/sumatrapdfreader/sumatrapdf/commit/3aa18aaf89caef7dd28529682d9344ef89422100#diff-b74959757a33838b186b7587a7d3e643bc7600a516ed1d42370b8c9ad8ca76bf

How do you usually handle changes made in the `mupdf/` directory in Sumatra repo?

What is your strategy regarding such patches to Sumatra dependencies versioned in this repo?

**Comment by kjk** [comment]
I don't believe I over-wrote your change when merging.

My policy regarding mupdf is that I keep mupdf changes to minimum and am careful when merging mupdf to not undo  changes.

It would be best if you could convince mupdf to merge your change so that I don't have to maintain this change in sumatra.

**Comment by Lucas-C** [comment]
My mistake, sorry, I really thought the patch on `mupdf/source/pdf/pdf-link.c` had disappeared 🤦‍♂️

I'm currently discussing this patch with the MuPDF team over Discord
