### ISSUE TITLE
hyphenated words at end of line not handled properly

### ISSUE THREAD

**Issue by bobvance** [sumatrapdfreader/sumatrapdf#2045]
This is actually in response to issue #815
  https://github.com/sumatrapdfreader/sumatrapdf/issues/815
which was *closed* before I could respond.

I have attached 2 screen shots which show that Sumatra does not handle it correctly, while Adobe Reader 11 *does* (as does MSEdge's built in PDF viewer).

This is on Windows 10 x64, 3 different systems/builds
   2004
   20H2
   21H1
.
![From Sumatra](https://user-images.githubusercontent.com/29075259/126530066-b2201e5b-4bc3-40d2-8a5b-1c7faed1bb09.JPG)
![From Adobe](https://user-images.githubusercontent.com/29075259/126530154-79ed12d8-1406-4d30-8192-2ecbdf471ad1.jpg)

**Comment by GitHubRulesOK** [comment]
It cannot be fixed in 3.2 it currently is not an issue
![image](https://user-images.githubusercontent.com/12754913/126553388-e9f5f7ec-6977-4d2e-b088-0389a4d8007b.png)

**Comment by bobvance** [comment]
Excellent !
When I asked it to check for updates,
it said that I had the latest !?
I didn't think to check the Web site to be sure.
BTW, I couldn't find 3.4, but 3.3.3 fixes it, as well.
Thanks.
