### ISSUE TITLE
Support custom translators for text selection in advanced settings

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2046]
Like `ExternalViewers` but `SelectionHandlers`.

Allow defining additional e.g. translation providers (in addition to "Translate with Google` context menu).

For now just browser based (urls). If people ask might add supporting executables (programs).

**Comment by GitHubRulesOK** [comment]
How do I ensure translations are to my language
existing translations appear backwards my UI is EN but translatens are to DE

https://www.deepl.com/translator#zh/de/%E8%AE%A1%E7%AE%97%E6%95%B0%E5%80%BC%E7%A7%AF%E5%88%86

![image](https://user-images.githubusercontent.com/12754913/126582359-e3f1b44a-33e7-49ad-b880-57bed9e6fde9.png)

**Comment by GitHubRulesOK** [comment]
OK Io thing I need to hardcode en instead of ${userlang}
like this 
URL = https://www.deepl.com/translator#??/en/${selection}

**Comment by GitHubRulesOK** [comment]
I just realised my common context use was rightclick select all but thats now deeper in seletion and even more nocible at the end so needs swiching from mouse to keyboard for speed !

I digress the other bugbear is that I can not remove the two non working **for me** intermediate translators
![image](https://user-images.githubusercontent.com/12754913/126586194-c20b9fbb-f4fa-46f7-aae0-604756aea583.png)

**Comment by kjk** [comment]
Yes, `${currLang}` is meant for "language you're translating to`, for which "user's language" is a good guess. But if it's English, then I hard-code it to "de". This is needed for DeepL api which requires a destination language. Maybe I should leave it as "en".

But this is just a guess. I guess the right usage would be for user to provide both `from` and `to` language for translation as separate entries e.g. `Translate English -> Spanish", "Translate Spanish -> German` etc.

**Comment by GitHubRulesOK** [comment]
Most users (I guess) just want to know what the foreign words are in their own language ? unlesss learning German :-)

**Comment by GitHubRulesOK** [comment]
I cant find currlLng I only saw / find UserLang https://github.com/sumatrapdfreader/sumatrapdf/blob/94dddad9bacbd82552d667b4d88d6888465834bb/src/SumatraPDF.cpp#L4266

**Comment by kjk** [comment]
Sorry, I meant `${userlang}` as in docs
