### ISSUE TITLE
Crashes continued in 13866

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2055]
Opening afresh since other related issues were potentially addressed but using the CHM file is sill creating crash condition
I opened the file in default state (embeded chm viewer) and had no problems navigating up and down the file.

I switched Debug EbookUI toggle to fixed = no noticeable problem (navigation continued well)
 However display had not changed so pressed  R to refresh, then the result looked like plain text and shortly after trying to use left hand navigation, crashed .
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6872683/sumatrapdfcrash.zip)

I followed a similar set of actions with the mobi file
I opened by default in mobi mode and was able to navigate no problem (apart from some issues with the way 3rd level gotos were in some cases not actioned)
No problems with viewing so again switched to fixed mode and as usual the display does not change until Refreshed
The body changed appearance but as the TOC started to rebuild the app crashed
[sumatrapdfcrash (2).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6872714/sumatrapdfcrash.2.zip)

**Comment by kjk** [comment]
Thanks.

It was most likely a crash due to 'r' which should be fixed now.
