### ISSUE TITLE
Sumatra crash when opening PDF

### ISSUE THREAD

**Issue by DietrichXD** [sumatrapdfreader/sumatrapdf#2060]
Crash log here: https://gist.github.com/DietrichXD/0bb88453ee9af99cedb1d63f78bf9897

PDF that causes the crash: [Tekeningenbundel Museumbeveiliging.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6877267/Tekeningenbundel.Museumbeveiliging.pdf)

**Comment by kjk** [comment]
Works for me with latest code. This crash is in 13837 and the latest is 13878. Please update to latest pre-release https://www.sumatrapdfreader.org/prerelease and see if it still happens

**Comment by DietrichXD** [comment]
Yep, solved it! Should have tried to update first. Thanks!
