### ISSUE TITLE
Sumatra 3.4.0 branch: Open PDF via Total Commander plugin is broken

### ISSUE THREAD

**Issue by deus-e-x** [sumatrapdfreader/sumatrapdf#2061]
I'm using Total Commander v10.00 x64 along with the 64-bit lister plugin SLister, which allows opening PDF files with SumatraPDF via F3 (Lister) or Ctrl+Q (Quickview) in Total Commander. I regularly update to a pre-release version of SumatraPDF.

Today I noticed that since one of the recent updates in the SumatraPDF v3.4.0 branch, I cannot open PDF files via Total Commander/SLister with F3 or Ctrl-Q anymore. Executing SumatraPDF directly or via command-line argument (sumatrapdf.exe <path/pdf-file>) still does work.

I guess some internal argument handling in SumatraPDF was changed? The oldest 3.4.0 pre-release version I could check that fails in TC is built 13860. Could you please check what is causing the issue and perhaps revert the change/find another approach?

EDIT: I should add that the recent release of SumatraPDF v3.3.3 does work with TC and the SLister plugin.

Total Commander: https://www.ghisler.com/
SLister plugin: https://totalcmd.net/plugring/slister.html

**Comment by kjk** [comment]
Thanks for the report.

Should be fixed in 13879 or later from https://www.sumatrapdfreader.org/prerelease

**Comment by deus-e-x** [comment]
I just checked the build 13879-64, SumatraPDF works flawlessly again with Total Commander and the SLister plugin.

Thank you very much for the quick response and for providing a new build with a fix super short-termed.
