### ISSUE TITLE
crashed after ctrl+scroll wheel

### ISSUE THREAD

**Issue by ajbmirasol** [sumatrapdfreader/sumatrapdf#2063]
https://gist.github.com/ajbmirasol/013ec675cdd629d413c4fb5fb6c13a7f#file-sumatra-crash-report

**Comment by GitHubRulesOK** [comment]
Sorry but that is an older version 3.2 please update to either version 3.3.3 or version 3.4 pre-release

**Comment by kjk** [comment]
like @GitHubRulesOK this is 3.2 and latest is 3.3.3
