### ISSUE TITLE
HTML unstable

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2066]
You may have noticed I tried different types of html files
The common point of failure in all seems to be

CalcDestKind(): unknown uri: '#'1'

here is the simplest (nearest to a book) I tried to open

[MANUAL.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6889535/MANUAL.zip)

**Comment by kjk** [comment]
Yeah, links in html/epub files are not yet supported

**Comment by GitHubRulesOK** [comment]
@kjk 
I opened a few simple html also referencing to external SVG without a problem (no other links)

 but this file with no dependency, reports similar crash to above, however there should be no "link"

[Drop Shadow Heading.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6889745/Drop.Shadow.Heading.zip)

**Comment by kjk** [comment]
Those should work now. I'm sure I broke some rarer link types due to refactoring but epub / html should now work.
