### ISSUE TITLE
Latest Builds File properties not working

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2067]
Well transparency seems OK :-)

![image](https://user-images.githubusercontent.com/12754913/127248730-abb80b20-450c-4dec-ab6f-032e45022311.png)
![image](https://user-images.githubusercontent.com/12754913/127249016-63a2027b-81d7-451a-bf61-ebb27c3a75fb.png)

**Comment by pulbitz** [comment]
pdf document properties seems broken

![document_properites](https://user-images.githubusercontent.com/58905725/127307195-317a2c5b-b346-4ff4-a276-94c00328313a.png)

**Comment by GitHubRulesOK** [comment]
@pulbitz Thanks
Agreed 
I have changed title

**Comment by GitHubRulesOK** [comment]
Thanks, I see it was part of a much larger exercise that took hours for a "Small Problem Of Programming 😄 "
