### ISSUE TITLE
Preview cache is emptied on closure

### ISSUE THREAD

**Issue by andelepeter** [sumatrapdfreader/sumatrapdf#2068]
Using currently latest pre-release build 3.4.13823 it happens for me that the directory with the pdf preview images used on the recent documents page (files in sumatrapdfcache) is cleared when I close SumatraPDF. All previews are gone when I open SumatraPDF the next time.
So: SumatraPDF creates a new preview image every time when I open a PDF and deletes it again every time when I close SumatraPDF.

**Comment by kjk** [comment]
I can't reproduce this.

Can you upgrade to latest (13894) and see if it still happens?

**Comment by andelepeter** [comment]
You are right. Works also for me on the latest build. Thanks.
Strangely, I wasn't notified as usual that there exists a new build. This is why I was mistakenly thinking I had the latest build. I should have checked on the website. Sorry.

**Comment by kjk** [comment]
No worries. 

The update check in pre-release version only happens once a week because I don't want to annoy people with too many updates.

You can trigger the check via menu `Help / Check for updates` in which case it'll force the check.
