### ISSUE TITLE
IFilter sending font info to stderr

### ISSUE THREAD

**Issue by BillDimm** [sumatrapdfreader/sumatrapdf#207]
When using the IFilter (from version 3.1.10155 and earlier) on some PDF files it prints messages to stderr like these:

```
- pdf-fontfile.c:815: loading non-embedded font 'Verdana' from 'C:\Windows\Fonts\verdana.ttf'
- pdf-fontfile.c:815: loading non-embedded font 'TrebuchetMS-Bold' from 'C:\Windows\Fonts\trebucbd.ttf'
- pdf-fontfile.c:815: loading non-embedded font 'TrebuchetMS' from 'C:\Windows\Fonts\trebuc.ttf'
- pdf-font.c:590: freetype could not find any cmaps

! pdf-fontfile.c:813: couldn't find system font 'HelveticaNeueLTStd'
! pdf-fontfile.c:813: couldn't find system font 'HelveticaNeueLTStd,Italic'
! pdf-fontfile.c:813: couldn't find system font 'HelveticaNeueLTStd,Bold'
! pdf-fontfile.c:813: couldn't find system font 'HelveticaNeueLTStd,BoldItalic'
- pdf-fontfile.c:815: loading non-embedded font 'TimesNewRoman' from 'C:\Windows\Fonts\times.ttf'
! pdf-fontfile.c:813: couldn't find system font 'HelveticaNeueLTStd,Bold'
! pdf-fontfile.c:813: couldn't find system font 'HelveticaNeueLTStd'
- pdf-fontfile.c:815: loading non-embedded font 'Symbol' from 'C:\Windows\Fonts\symbol.ttf'
! pdf-fontfile.c:813: couldn't find system font 'HelveticaNeueLTStd,BoldItalic'
- pdf-fontfile.c:815: loading non-embedded font 'Arial' from 'C:\Windows\Fonts\arial.ttf'
- pdf-fontfile.c:815: loading non-embedded font 'Arial,Bold' from 'C:\Windows\Fonts\arialbd.ttf'
```

Is there a reason why an IFilter would be doing anything with fonts?  Is it considered acceptable for an IFilter to print stuff to stderr?  I have never noticed an IFilter printing to stderr before.  In my case, my GUI program is launching a separate program that invokes the IFilter to extract text that will be analyzed and that program is apparently getting stuck because nothing is reading the stuff accumulating on stderr since the GUI program is not expecting the program it launched to output anything to stderr (since the program itself doesn't).  I don't know if it is *wrong* for an IFilter to write to stderr, but it is (at least to me) surprising and annoying.

Sidenote: The PDF files causing this belong to one of my clients, so I cannot provide them without getting permission.  I'm guessing you won't need them since filenames and line numbers are included in the messages above.  If you do need a sample file, let me know and I'll see if I can get them to release one.

**Comment by kjk** [comment]
This is printed by mupdf. I don't understand how you capture the output of iFilter but it's not an issue for users.
