### ISSUE TITLE
Change directory before showing file selection dialog

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2073]
To prevent dll hijacking at startup we change the directory to Windows\System32.

This is bad when opening file selelection dialog. Windows\System32 is probably not the right place and it happens to be a large directory, which slows down opening the dialog.

Switch the directory to something saner, like Documents folder, the first time we show file selection dialog.

I think it remembers the last location so it only needs to be done once.

**Comment by GitHubRulesOK** [comment]
yes defaulting admin level CMDs to system32 is a bad problem as a badly scripted cmd file can wreak havoc in the hands of a novice admin user.
