### ISSUE TITLE
Request to enable one-time sponsor option.

### ISSUE THREAD

**Issue by ckunte** [sumatrapdfreader/sumatrapdf#2079]
Request the author to consider enabling one-time sponsor option too. This enable end-users like myself (that appreciate good utilities like SumatraPDF) to pay for it for the author's efforts.

**Comment by kjk** [comment]
I don't see such option in GitHub sponsors or Patreon.

You can make a one time donation via PayPal: https://www.paypal.com/paypalme/sumatrapdf

**Comment by ckunte** [comment]
But there is under GitHub sponsors -- please consider switching it on. Please see screenshot below. (PayPal does not help sponsor without an account, and I was not looking to.)

<img width="784" alt="Screen Shot 2021-07-30 at 18 31 16" src="https://user-images.githubusercontent.com/177423/127640520-3d33f963-9d6d-476f-9cd5-158b3e8ed04b.png">

**Comment by SySDevel7** [comment]
@kjk add GitHub has sponsor option for both user or organization.

**Comment by ilayn** [comment]
Hi @kjk, I know this is a bit of an old issue but I would also appreciate if there is a non-Paypal option for donations for folks who don't have/want a Paypal account due to many reasons.
