### ISSUE TITLE
why i failed to build sumatrapdf using vs 2013?

### ISSUE THREAD

**Issue by chapgaga** [sumatrapdfreader/sumatrapdf#208]
the command i use is `msbuild sumatrapdf-vc2013.sln`

![](http://img.itc.cn/photo/jRtR8R55Ztx)

http://img.itc.cn/photo/jRtR8R55Ztx.jpg

**Comment by kjk** [comment]
I never tried using msbuild. Try opening in Visual Studio IDE.

Also, I don't read chinese and you could make a minimal effort of trying to understand what the compiler tells you.

**Comment by chapgaga** [comment]
@kjk also failed with vs ide
![](http://img.itc.cn/photo/jRtyabbLRIM)
http://img.itc.cn/photo/jRtyabbLRIM.jpg
