### ISSUE TITLE
Show menu and tabs

### ISSUE THREAD

**Issue by erperion** [sumatrapdfreader/sumatrapdf#2081]
In settings I have:
UseTabs = true
ShowMenubar = true

But it has no effect, menu is hidden under burger icon. Is it possible to have tabs and menu visible at the same time?

**Comment by kjk** [comment]
currently it's not possible

**Comment by erperion** [comment]
Ok, thank you for fast reply. Could you say (more or less) when this feature will be fixed/implemented? Thanks.

**Comment by kjk** [comment]
I can't because I don't know

**Comment by GitHubRulesOK** [comment]
@erperion see duplicate https://github.com/sumatrapdfreader/sumatrapdf/issues/232 request and it is a fixed bug :-)
