### ISSUE TITLE
Tab management - right click on tab options.

### ISSUE THREAD

**Issue by erperion** [sumatrapdfreader/sumatrapdf#2082]
Many apps have options to manage tabs when you right click on tab. It would be useful if right clicking on tab had such options:
Move to start (Moves current tab to the first place on tab list)
Move to end (Moves current tab to the last place on tab list)
Close tabs on the right
Close tabs on the left
Close other tabs
Move tab to new window

Maybe some others. Any thoughts on this?

**Comment by GitHubRulesOK** [comment]
Basically two separate issues Alter current tabs behaviour and Drag to another window
partly covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/388
partly covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/18
duplicates requests in https://github.com/sumatrapdfreader/sumatrapdf/issues/656
 and others so now linked and closed
