### ISSUE TITLE
Cannot open DQ965GF_TechProdSpec.pdf

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2089]
https://www.intel.com/content/dam/support/us/en/documents/boardsandkits/desktop-boards/965/DQ965GF/DQ965GF_TechProdSpec.pdf

mupdf says:
```
error: expected object number
warning: repairing PDF document
error: cannot find page tree
```

**Comment by kjk** [comment]
Reported to mupdf https://bugs.ghostscript.com/show_bug.cgi?id=704162

**Comment by GitHubRulesOK** [comment]
Interesting Acrobat 9 says its bad, Even though built using Adobe Acrobat 6 (Intel ! custom Font)
![image](https://user-images.githubusercontent.com/12754913/127918649-a9caf0e4-2954-4be9-9d82-84bd57e299a1.png)
![image](https://user-images.githubusercontent.com/12754913/127918728-b0e81102-fe1d-4668-b042-b508632c454b.png)

**Comment by VictorVG** [comment]
Traker Software PDF-Xchange Editor says then it to this document have offset object and repair it, then save as new name or copy.

**Comment by VictorVG** [comment]
I try SumatraPDF v3.4.13978 Git-a12101b46 and DQ965GF_TechProdSpec.pdf:

original Intel PDF

![2](https://user-images.githubusercontent.com/906886/128160730-26621d07-f383-435b-bdae-9822386513d1.png)

recovered PDF:

![3](https://user-images.githubusercontent.com/906886/128160735-3c5ab034-a243-44a4-86e3-09d3d48542f2.png)

**P.S.**

_By the way, in the documentation on the Intel website, such incorrectly created PDFs are found quite often and I accumulate them, and then restore them to PDF-Xchange PRO with a friend at the publisher - they use it for work, well, when the machine is free, they start up "Fix this scrap!": )._

**Comment by kjk** [comment]
mupdf fixed it and we inherited it

**Comment by VictorVG** [comment]
Excellent!
