### ISSUE TITLE
failed to build sumatrapdf using vs 2013 ide

### ISSUE THREAD

**Issue by chapgaga** [sumatrapdfreader/sumatrapdf#209]
detailed error message as follows:
http://pastie.org/10208013#11-14,30-32,79

warning treated as error, why it still appears, i have modified the configuration of efi project
![](http://img.itc.cn/photo/jRtzHB8Jm1v)
http://img.itc.cn/photo/jRtzHB8Jm1v.jpg

**Comment by kjk** [comment]
Please update to latest version. https://github.com/sumatrapdfreader/sumatrapdf/commit/3e3375e4ea5c7c62634698d4b358f46f98121128 should fix this issue.
