### ISSUE TITLE
SumatraPDF crash when open pdf file

### ISSUE THREAD

**Issue by lunbudao** [sumatrapdfreader/sumatrapdf#2092]
It works well until I opened one of my pdf files, then it crashed.
![image](https://user-images.githubusercontent.com/24380551/128105866-3ecfe589-69af-4c87-9c36-e5cf85ab06be.png)
The crash report is [here](https://gist.github.com/lunbudao/682197d7887ec4dafed52dcce167440b)

**Comment by lunbudao** [comment]
And it remains crashed when I opened previously normal pdf files.

**Comment by lunbudao** [comment]
The version is 3.4.13963 pre-release 64-bit (from the crashed report).
Sorry, I am not clear about what is the right way to report an issue. But I think all the detailed information should be in the crash report I provided above.

**Comment by kjk** [comment]
This is most likely fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/3150630982cb9ecf1caf795b50c2ada1056ca052 in latest pre-release https://www.sumatrapdfreader.org/prerelease (13976 or later).

Please re-open if that's not the case.
