### ISSUE TITLE
Bitmap annotations

### ISSUE THREAD

**Issue by LoZio** [sumatrapdfreader/sumatrapdf#2095]
Currently you can add various annotations/stamps with predefined messages. It would be useful to insert PNG/GIF bitmaps, with support for transparent background. This will allow to insert the "digital signature" :-( that most require when compiling PDF.
I understand annotations are borrowed from MuPDF, nonetheless they are a missing feature in SumatraPDF.

**Comment by GitHubRulesOK** [comment]
Not missing they are supported just adding slowly

- [ ] Highlight Text
- [ ] Highlight Text with Tooltip Comment
- [ ] Highlight Area with Comments
- [ ] Underline Text [with Comment]
- [ ] Strike Through Text
- [ ] Squiggle Under Text
- [ ] Standard Stamps with Text
- [ ] Caret [with comment]
- [ ] Text Comment with Icons of different types and colour
- [ ] Text in a Rectangle
- [ ] Rectangle
- [ ] Circloid
- [ ] 

- [ ] Custom Stamps with Images

**Comment by GitHubRulesOK** [comment]
Closing as duplicated by comments raised as https://github.com/sumatrapdfreader/sumatrapdf/issues/2085

**Comment by GitHubRulesOK** [comment]
With 3.7 images can be added via clipboard paste but that usually does not support transparency in PDF

<img width="1106" height="532" alt="Image" src="https://github.com/user-attachments/assets/b65a117b-c092-4001-841e-4cdbd0050c94" /> 

however you can use a scripting tool to convert a PNG into PDF signature objects such as images with asoft mask (alpha opacity)

<img width="1029" height="464" alt="Image" src="https://github.com/user-attachments/assets/3e682e81-06bd-4ae8-a495-01a601bb2abd" />

the same transparent image can be used with a digital pfx for eSigning

<img width="1116" height="432" alt="Image" src="https://github.com/user-attachments/assets/19400289-ce47-4d66-bd7d-7c62621931f5" />
