### ISSUE TITLE
Bookmarks point to wrong page for djvu files

### ISSUE THREAD

**Issue by pglpm** [sumatrapdfreader/sumatrapdf#2097]
Hi all, I just installed the prerelease version 13978, 64 bits. There seems to be a little bug with bookmarks for djvu files: If one clicks on a bookmark on the bookmarks tab (or navigates there with the up/down arrow keys), one lands on the page *preceding* the correct page of the bookmark. I tested this on several djvu files, on which SumatraPDF navigated correctly before.

This quirk doesn't seem to occur with pdf files.

**Comment by GitHubRulesOK** [comment]
If it is consistent behaviour with all of your bookmarked djvu's it helps to zip a **public available** sample for comparison by developer as any test files may not have same structure/behaviour.
