### ISSUE TITLE
Show page number when hovering over page progress bar

### ISSUE THREAD

**Issue by Peter-Sumatra** [sumatrapdfreader/sumatrapdf#21]
Currently with **EbookUI** active when you click on the page progress bar there's no way to know exactly which page you'll land up on.

If the page number is shown in a small tooltip or something over the hovering 'hand' pointer that would make it a lot easier to jump to precisely the one required.

**Comment by GitHubRulesOK** [comment]
@kjk consolidate :-) with https://github.com/sumatrapdfreader/sumatrapdf/issues/335
