### ISSUE TITLE
Annotation over two pages not working

### ISSUE THREAD

**Issue by mahfiaz** [sumatrapdfreader/sumatrapdf#2100]
1. Select some text in a PDF so that some of the selected text is on the next page.
2. Right-click -> Create annotation from selection -> Highlight
3. Nothing happens

Version v3.3 commit 9eda07b

**Comment by GitHubRulesOK** [comment]
Always use latest pre-release 

However note PDF is a **P**AGE **D**escription **F**ormat thus text (and other objects do not "span" between pages. Internally half is allocated to x y co-ordinates on one page and half is allocated to the other, thus highlight needs two separate selections and application. The same is often true when extracting, the clipboard may struggle with page selections across a page boundary.

**Comment by mahfiaz** [comment]
It's the same in pre-release v3.4.13984.

Having it turn out as two (or more) separate annotations wouldn't bother me.
The context menu item isn't grayed out, no error message pops up, it just does nothing. Looks like a bug to me.

**Comment by GitHubRulesOK** [comment]
Bug is relative term 
any release is E&OE

@kjk 
can this be "fixed" OR a warning be given that user expectation across page boundary may not be met.
