### ISSUE TITLE
Include offline docs within Sumatra

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2103]
Some people want the docs to be included in Sumatra (as opposed to going to the website).

Now that we have a decent epub renderer, I could write a script to generate .epub file with docs, include it in resources and then open as a document within Sumatra.

**Comment by GitHubRulesOK** [comment]
F1 ? I think I opened an issue but suggested vbkm long live ePub, Should be "easy" to keep zipping the pages :big grin: just unpack optionally download alongside portable.exe to override http://?

**Comment by GitHubRulesOK** [comment]
@kjk closure ?
