### ISSUE TITLE
Crash when closing open tabs

### ISSUE THREAD

**Issue by mahfiaz** [sumatrapdfreader/sumatrapdf#2104]
I was closing PDF files with Ctrl+W when the program crashed.
v3.4.1.13984 64-bit

The crash log is attached:
[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/6943753/sumatrapdfcrash.txt)

**Comment by kjk** [comment]
```
00007FF78D3433CF 01:00000000000B23CF sumatrapdf.exe
00007FF78D33CE0E 01:00000000000ABE0E sumatrapdf.exe
00007FF78D33CD0C 01:00000000000ABD0C sumatrapdf.exe
````
Unfortunately  the callstack doesn't have symbols so there's not enough information to investigate.
