### ISSUE TITLE
annotations = off

### ISSUE THREAD

**Issue by yashpalgoyal1304** [sumatrapdfreader/sumatrapdf#2107]
hi, i like the sumatra pdf and use it exclusively for viewing pdfs. i understand that annotations are a work in progress and i appreciate the work. But the annotations are not ripe for my use - so, i dont use sumatra 3.3. for annotations. Rather i do annotations in other software.

But the problem is that the new version 3.3 messes up with the annotations done by other softwares and reformats it in its own style. So, i was wondering if there is an option of smth like read-only mode in sumatra?? if not, then can it be provided - so that it make no changes to the annotations just like the old version 3.2

**Comment by kjk** [comment]
I believe this is fixed in pre-release version https://www.sumatrapdfreader.org/prerelease

If you have an example of PDF file that is Sumatra pre-release messes up, please provide such file.

**Comment by yashpalgoyal1304** [comment]
> If you have an example of PDF file that is Sumatra pre-release messes up

i havent used sumatra pre-release. so, cant say. and am bit busy for 2 months or so, will try thereafter.
