### ISSUE TITLE
Incorrect Render of a Specific PDF File (since version 3.3)

### ISSUE THREAD

**Issue by jwangac** [sumatrapdfreader/sumatrapdf#2108]
Hello, the latest version of SumatraPDF incorrectly renders [a PDF file](https://jmlr.csail.mit.edu/reviewing-papers/smith-advice.pdf).

There are strange symbols:
![page](https://user-images.githubusercontent.com/12931565/128634888-2be6c4f4-d631-40fe-bb70-16d496345c2e.png)

I'm not sure if it is an invalid PDF file. But before version 3.3, SumatraPDF correctly renders this PDF file. MuPDF (version 1.18.0) and GPL Ghostscript (version 9.53.3) also correctly render it.

Would you mind check this problem?

**Comment by kjk** [comment]
Probably caused by:
```
loading non-embedded font 'Times-Roman' from 'C:\Windows\Fonts\times.ttf'
loading non-embedded font 'Times-Bold' from 'C:\Windows\Fonts\timesbd.ttf'
loading non-embedded font 'Times-Italic' from 'C:\Windows\Fonts\timesi.ttf'
```

The file uses non-standard `Times-Roman` font and we use Window's font because it matches the name. mupdf must be using a different fallback font.
