### ISSUE TITLE
Open With... fail to open file

### ISSUE THREAD

**Issue by danielHalan** [sumatrapdfreader/sumatrapdf#211]
When using Open With.. it fails to Open the file, the error msg shows that it looks for the file in Windows System32 Folder. 

Also it seems that it tries to open few other files from same folder.

Tested OS: Windows 8.1 Update1

**Comment by kjk** [comment]
It works correctly for me.

Most likely this a corruption of registry entries that describe which program to invoke for a given file type.

Try re-installing sumatra.

**Comment by klvbdmh** [comment]
Re-installing SumatraPDF didn't fix the problem.

Windows 10, Sumatra 3.2.1 64-bit.
