### ISSUE TITLE
Please use different update url checker

### ISSUE THREAD

**Issue by DeerSpotter** [sumatrapdfreader/sumatrapdf#2111]
this website is not blocked at my workplace, and probably will never be blocked at other locations: https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/rel/SumatraPDF-3.3.3-64-install.exe

But to check updates on a already installed version I receive an error:

![image](https://user-images.githubusercontent.com/16710090/128701921-5b81bfdd-1baa-4e56-a552-cd08863a7a21.png)

**Comment by GitHubRulesOK** [comment]
I don't think moving the location would help (unless inside your system firewall)
I have no clue as to cause (the dev will need to try and guess that one)
but its a common update Office365 (and other apps) problem.

ERROR_MUI_FILE_NOT_LOADED
15105 (0x3B01)
The resource loader cache doesn't have loaded MUI entry.

**Comment by kjk** [comment]
@GitHubRulesOK FYI: I'll delete your comment as this is speculation that is likely incorrect. Blocking of digitaloceanspaces.com is real.

**Comment by GitHubRulesOK** [comment]
@kjk 
Potential duplicate related to site access ?

**Comment by kjk** [comment]
If this is on Win7 then it's probably fixed.

If it's just someone going wild blocking websites => I'm not going to do anything about it.
