### ISSUE TITLE
Using i in image mode affects UI

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2113]
When using <kbd>i</kbd> accidentally for "info" (bad habits and this old dog)

the behaviour is the same as in some other modes as the UI text changes from black to white

![image](https://user-images.githubusercontent.com/12754913/128718811-322aaec8-6fdd-4b8f-bbbc-5ae6f7e2cebb.png)

**Comment by kjk** [comment]
Hmm, can't reproduce it. `i` shouldn't affect this.
Does it happen with unchanged advanced settings? Does it goes back to good after pressing `i` again?

**Comment by GitHubRulesOK** [comment]
In PDF (FixedUI) mode It should be noticeable that on pressing i the colours invert after R for refresh
at that time the words Page: /total and Find: (in the toolbar are also inverted
I am unsure but seem to recollect it is also in some way related to UseSysColors = true (which was set that way at present)

UseSysColors = true it depends on windows settings
UseSysColors = false it depends on foreground colour
![image](https://user-images.githubusercontent.com/12754913/128860868-a6e3edf3-5a12-41fa-a291-fc40ac1ef877.png)

**Comment by GitHubRulesOK** [comment]
closing as this is no longer relevant to the i key and if present using shifted I it is more related to sys colours.
