### ISSUE TITLE
sumatrapdf printing pictures is too slow?

### ISSUE THREAD

**Issue by sujiewen** [sumatrapdfreader/sumatrapdf#2115]
time_t now = GetTickCount();
    logf(L"start '%ld', printer: '%s'\n", now, printerName);
    bool ok = PrintFile(engine, printerName, displayErrors, settings);
    logf(L"end '%ld', printer: '%s'\n", (GetTickCount() - now), printerName);

    It took 3 seconds to print a picture!!!!

   ///////////////////////////////////////////////////////////////// Output
    start '3700000', printer: '(null)'
    EngineImages::RenderPage() in 251.38 ms
    end '3078', printer: '(null)'
   

   Normal printing in 100 milliseconds

Image
![DINGTALK_IM_540527596](https://user-images.githubusercontent.com/1973318/128801098-35014cfa-84c8-4774-9878-5d31da1a56f1.JPG)

**Comment by GitHubRulesOK** [comment]
251.38 ms = 1/4 second (0,251) but it depends what "normal" printing is
SumatraPDF Printing is often high res image (big files to transmit) but basically it is upto the driver setting for the negotiations and yes its a fairly slow transfer method to render each page into the spool queue.
The first page can sometimes take longer than the next twenty pages, whilst another file may only print three in the same amount of time, even different colour images can have a different timing effect per page.

**Comment by sujiewen** [comment]
A magical phenomenon, a 1.4MB picture, 47.9MB displayed in the print queue

<img width="1133" alt="截屏2021-08-10 下午12 19 14" src="https://user-images.githubusercontent.com/1973318/128807759-ef0d3bb9-a203-48a5-922d-20f7209cabc1.png">

**Comment by kjk** [comment]
Yes, Sumatra prints as a bitmap and it's unlikely to change.
