### ISSUE TITLE
Unsaved annotations even without any PDF modification

### ISSUE THREAD

**Issue by RomanTatar** [sumatrapdfreader/sumatrapdf#2118]
**Steps to reproduce**
Have SumatraPDF 3.3.3
Open attached PDF
Do not modify anything
Close SumatraPDF

**Actual result**
There is "Unsaved annotations" dialog
Right click - Edit Annotations (empty)
File - Save Annotations (there is info about saving file, but it remain identical) -> Closing PDF shows dialog again
![image](https://user-images.githubusercontent.com/37003251/128934137-b186a9c3-9a48-4580-ba7a-d694addafc90.png)

**Expected result**
When no changes to PDF are done, there should be no "Unsaved annotations" dialog

[2021-10-01-Podminky_k_elektronickemu_podpisu_a_Bankovni_identite_KB.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/6964502/2021-10-01-Podminky_k_elektronickemu_podpisu_a_Bankovni_identite_KB.pdf)

**Comment by kjk** [comment]
Already fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by RomanTatar** [comment]
Verified that with SumatraPDF-prerel-14000-64-install.exe it works fine. Thanks.
