### ISSUE TITLE
"Formatting Book" loop

### ISSUE THREAD

**Issue by Verser** [sumatrapdfreader/sumatrapdf#212]
There is an issue where a handful of books (very large omnibus books) randomly started to do a "formatting book" loop. It is as if it is stuck initializing the file. 

If I let it go on for long enough, the program will crash and as me to hit cancel if I need help. Similarly, I get the dialog and a hang if I try to click the bar at the bottom to move pages while the formatting is going on.

I've tried:
* Deleting the settings
* Uninstalling/reinstalling
* Using a backup copy of those files

Sadly nothing so far has worked. 

**EDIT - Update**
After a quick test,  I wanted to note that this problem was only happening with the 3.0 version. If I pop this build (3.1) into VS and compile it myself, the problem is gone.

So this might not be an issue after the new build is pushed to the main site.

**Comment by kjk** [comment]
If it still happens in 3.1, please reopen and provide a file that shows the problem.
