### ISSUE TITLE
Add 'Open Embedded File' toc context menu

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2122]
Currently when PDF file has an attachment, we show it in the bookmarks tree view and have "Save Embedded File" context menu option.

For convenience we should also have "Open Embedded File".

Got test file in an e-mail from a user.

Or maybe those should be called "Save Attachment" and "Open Attachment" since technically I think they are called attachments in PDF lingo.

**Comment by GitHubRulesOK** [comment]
there is also the annotations NYI entry perhaps both need a combined Save/Open Imbedded content(s) but there are a few related variants such as the PDF collections (portfolio) issue.

**Comment by PizzaProgram** [comment]
Currently (in V3.2 and V3.3) it does not show any way if it contains an embedded file or not. _(Sent an example via email)_
Only, if you "know somehow" it has one > and right-click on the bookmark > and click "Open embedded PDF".

![kép](https://user-images.githubusercontent.com/26026089/129445376-6e0785ad-1f69-413d-a197-a0d4ef3e5062.png)

I think the best way would be to put a small list over the bookmark-list.
 _(Push the bookm. list a bit more down. It still has plenty of space left.)_

**WHY? :**
 - if one of that is a PDF, you could double click to open it on a new tab.
 - it's easier to handle normal bookmarks and embedded files differently if there are 2 separate lists.
 - you can hide it, if there are no embedded files, and show if it has any. That would make visually easily distinguishable.
 - maybe colour the list's background a bit differently, than the bookmark list. _(Consider dark mode later!)_

**Comment by PizzaProgram** [comment]
May I ask why did you close this topic?
**The embedded file show/open problem is not solved yet.**

It is **not** obvious for the user, if there is an embedded file attacked to the PDF at all, because there is no "visual button" that would signal that.
Most users do not even think to try right-clicking on anything. 
 ( _Why would they, if there is no indicator?_ )

**Comment by kjk** [comment]
Issues have scope. The scope of this issue was to add 'Open Embedded' context menu and that was done.

If you want a different change, open a new issue.

That being said what you propose in the comment is too much work.
