### ISSUE TITLE
Clear recently opened files

### ISSUE THREAD

**Issue by Wiredframe** [sumatrapdfreader/sumatrapdf#2126]
Didn't find an issue, so excuse me if this is a duplicate. I would like to suggest adding a "clear recently opened files" option in the files menu and / or on the start screen.

**Comment by GitHubRulesOK** [comment]
Discussed on forum so adding a link here
https://forum.sumatrapdfreader.org/t/clear-all-recent-file-with-1-click/4253
The current workflow requires 8 mouse clicks or 12 keys so one click on home screen or a shorter few keys would make much easier.this issue

**Comment by kjk** [comment]
A menu item is unlikely. Adding more and more stuff to menus doesn't scale.

But it could be a command available via command palette. That's scalable.

**Comment by shockergit** [comment]
> A menu item is unlikely. Adding more and more stuff to menus doesn't scale.
> 
> But it could be a command available via command palette. That's scalable.

Not menu item it would have been nice if their is a clickable link like thing in bottom center of the home screen (clear recent)

**Comment by Wiredframe** [comment]
Thanks! Well, a menu item is the common pattern for clearing a recents list. Screenshots show Affinity Designer and AdobeXD. 
![image](https://user-images.githubusercontent.com/13737875/129682999-4045533f-8c09-4c2e-afbc-03518831c0c7.png)
![image](https://user-images.githubusercontent.com/13737875/129683078-d0525e1f-c363-426a-96fb-6933532eedb4.png)

**Comment by kjk** [comment]
I've added `Clear History` command you can trigger from command palette (`Ctrl + K`)
