### ISSUE TITLE
Minor appearance bug

### ISSUE THREAD

**Issue by onmyouji** [sumatrapdfreader/sumatrapdf#2127]
SumatraPDF version 3.3.3 64-bit
Windows 10 Home 64-bit 20H2 19042.1151

When viewing folder with multiple images, the first file in the bookmark list is not highlighted.

Steps to reproduce:

1. Open a folder which has multiple images.

2. Change the View to Single Page, Show Pages Continuously.

3. Scroll down to the 2nd image file. The file will be highlighted in the bookmark list.

![2021-08-16 22_52_01](https://user-images.githubusercontent.com/8424198/129592337-d0dea573-a229-46cd-8ddf-3afed24105a9.png)

4. Same thing if you continue to scroll to the next following images (3rd, 4th, so on), the file will be highlighted in the bookmark. 

5. But if you scroll up to the 1st image file, this file is not highlighted.

![2021-08-16 22_55_06](https://user-images.githubusercontent.com/8424198/129592735-9952b0bf-3b5e-4763-b337-97154a4c5532.png)

**Comment by GitHubRulesOK** [comment]
Confirmed as an issue in 3.3.3 However
Testing current behaviour seems to not be an issue
![image](https://user-images.githubusercontent.com/12754913/129598299-5776b42e-0cee-4461-be05-42661af59b7d.png)
