### ISSUE TITLE
display content of Simplified Chinese epub files in other language mode

### ISSUE THREAD

**Issue by maximumzhou** [sumatrapdfreader/sumatrapdf#213]
I'm using win 7 ultimate service pack 1, region and language was set to Japanese,the epub text in Chinese shows the character by □.if i want to read it ,i must switch to Chinese language and restart the system,very inconvenience !
hope it be fixed!

**Comment by KrasnayaPloshchad** [comment]
I think you should provide the document in question as described in https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports

**Comment by GitHubRulesOK** [comment]
Without an example to test
I have to suggest that the font needs changing in the settings file for each locality thus this is effect related to #121
On that basis am closing as duplicate requirement of 121
