### ISSUE TITLE
Always show home page

### ISSUE THREAD

**Issue by ss005** [sumatrapdfreader/sumatrapdf#2134]
Once I open a pdf, how can I go to start/home page to open more documents from "frequently read"?
Currently I've to close all open pdf to see the start/home page.

version 3.3.3

**Comment by kjk** [comment]
Currently that's not possible. It's something I would like to improve.

Today to access recently open files you can use File menu.

You can use `Alt-F` shortcut and then press `1` to `9` to open a file. Or you can use a mouse.

**Comment by GitHubRulesOK** [comment]
An alternative is to open new window and use the secondary window.
Related to many other suggestions collated in https://github.com/sumatrapdfreader/sumatrapdf/issues/406

**Comment by kjk** [comment]
This is now available in pre-release build: https://www.sumatrapdfreader.org/prerelease
