### ISSUE TITLE
bug report: sumatrapdf crashes when a link is dragged in the app

### ISSUE THREAD

**Issue by hrishikesh-deshpande** [sumatrapdfreader/sumatrapdf#2135]
**bug :-**
sumatrapdf crashes when a hyperlink is dragged and released inside the app (on the document)

**how to reproduce :-**
1. open a document which has any hyperlink (url linked to any text or photo).
2. hover over the link till you see clickable cursor.
3. drag the link and drop over the same document.
4. sumatrapdf will stop responding or crash.

version:- v3.4.14013 64 bit pre rel

**Comment by GitHubRulesOK** [comment]
@kjk 
I can confirm SumatraPDF current release 14045 will shutdown without warning in some cases of attempting to drag an external hyperlink
