### ISSUE TITLE
Remove e-book UI

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2143]
Now that epub switched to mupdf rendering and fixed ui, will move .mobi and others to fixed ui as well.
Will remove a bunch of code, make the app smaller.

**Comment by GitHubRulesOK** [comment]
@Dharmainiciativ 
The different in font scaling between the two UIs was there before
so understandable the new default size for some formats will seem odd until you alter to preference.
Note for Mobi I have changed to a sans serif and similar size
![image](https://user-images.githubusercontent.com/12754913/131197259-44a7e30e-8108-4140-b907-6281797df536.png)

**Comment by Dharmainiciativ** [comment]
"The different in font scaling between the two UIs was there before" It was not there, before switching to mupdf rendering, and the dpi setting probably does not work correctly. The setting for changing the font and its size does not work for me. Maybe it's in the operating system, I have Windows 7. It is not entirely clear for what types of files it works for you. In Russia, the fb2 and epub formats are the most popular, the rest are very rare.

**Comment by kjk** [comment]
At the moment the EbookFontName and EbookFontSize only works for mobi because epub / fb2 are rendered using different engine.

I'll see if it can be done for epub / fb2 as well.

**Comment by Dharmainiciativ** [comment]
> At the moment the EbookFontName and EbookFontSize only works for mobi because epub / fb2 are rendered using different engine.
> 
> I'll see if it can be done for epub / fb2 as well.

Please open fb2 from zip archives. Sumatra used to open them calmly. They are very often distributed in this form, now Sumatra throws an error when trying to open them. Thank you in advance.

**Comment by GitHubRulesOK** [comment]
I saw it there as such, because there were complaints about the differences, when the scale was supposed to be the same font
![image](https://user-images.githubusercontent.com/12754913/131198411-58206d30-3a9c-4cb9-9705-5c2d17eeee0c.png)

**The main difference is FB2 fonts sizes will be affected by reflow and a nominal size**

![image](https://user-images.githubusercontent.com/12754913/131199026-060f79b2-d9dc-4a6c-b081-02ff0a05fd63.png)
