### ISSUE TITLE
Bookmark is not useable

### ISSUE THREAD

**Issue by zycsss** [sumatrapdfreader/sumatrapdf#2148]
When a title on the bookmark sidebar is clicked, there's no response.

**Comment by GitHubRulesOK** [comment]
https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports
current pre-release version of SumatraPDF ?
WITH sample of type of file

**Comment by zycsss** [comment]
https://user-images.githubusercontent.com/50743387/131251826-2d22167c-c8df-43be-af6b-a02e5c4f3fd6.mp4
after upgraded to the latest pre-release version, after a few tests, I found out that it only involves the specific PDF file.

however I don't know how to upload a PDF file

**Comment by GitHubRulesOK** [comment]
That file at 56 is possibly too big to upload so depends which pirate copy you have this one works well
![image](https://user-images.githubusercontent.com/12754913/131252354-045941c8-042d-4a11-8b60-ac33e6a7ffd7.png)

**Comment by kjk** [comment]
You can try using https://transfer.sh/ or e-mail me the file.
