### ISSUE TITLE
Is it possible to get the old icon set back?

### ISSUE THREAD

**Issue by Jonson26** [sumatrapdfreader/sumatrapdf#2152]
Hello, I just updated to 3.3.3 and I must say that I dno't particularly like the new "modern" look of the toolbar icon set. I found it much easier to use the reader when the icons had colour instead of being monochromatic. Is there a way I could use the old icons in the new version?

I don't mean to be rude by the way. I'm sure you put a lot of work into that new toolbar, it's just that I find the new vector icons harder to see. The new look seems somewhat blurry on my main monitor at least, wheras the old icons were sharp as ever.

**Comment by kjk** [comment]
There are no plans to support old icons.
