### ISSUE TITLE
Underline Hotkey Shortcut to "u"

### ISSUE THREAD

**Issue by benyaminl** [sumatrapdfreader/sumatrapdf#2157]
/kind suggestion
This feature suggestion is related to https://github.com/sumatrapdfreader/sumatrapdf/issues/2002 and https://forum.sumatrapdfreader.org/t/underline-annotation-shortcut/4304/2

Now in beta we have `a` as hightlight in text on sumatrapdf, I think there also need to add `u` shortcut key for underlining text if possible near future, because not everyone always use mouse to right click and underline something, and shortcut key will be convenient for people who choose to  use shortcut. 

Thanks

**Comment by Leoijeon** [comment]
Really want this feature
