### ISSUE TITLE
[feature request] Make Sumatra per monitor dpi-aware [Windows]

### ISSUE THREAD

**Issue by FSund** [sumatrapdfreader/sumatrapdf#216]
Sumatra handles high dpi-displays beautifully, but when I move an open Sumatra window from a high-dpi display to a regular/low-dpi screen the UI scaling stays the same. 

See the following image for an illustration using a 4K 15.6 display with UI scaling set to high in W8.1, and a "regular" 1080p monitor with no Windows UI scaling.
![2015-06-03 09_02_59-clipboard](https://cloud.githubusercontent.com/assets/3352483/7954427/c45b7eb0-09cf-11e5-963a-764e327ad6b3.jpg)
You can see that the window with the open folder scales well, but the UI in Sumatra is too large.

Since it seems like you already have some dpi-scaling, I hope adding scaling when moving between displays with different dpi-settings can be easily implemented.

Some info on this: https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx
(note the section "Categories of Applications")

**Comment by FSund** [comment]
I just tested prerelease v3.2.10448 (64bit), and it seems like DPI scaling is working very well there.

Thank you for fixing this! But I guess the issue should stay open until this feature is released.

As can be seen in the following image, UI and even zoom level scales perfectly.
![sumatra pdf dpi scaling fixed](https://cloud.githubusercontent.com/assets/3352483/10630011/fd57b978-77d3-11e5-9a39-42d37746d726.png)

**Comment by kjk** [comment]
Thanks for testing. We close the issues when the fix is checked in.

**Comment by FSund** [comment]
I think this also fixes these three issues from the forum:
http://forums.fofou.org/sumatrapdf/topic?id=3184879
http://forums.fofou.org/sumatrapdf/topic?id=3184193
http://forums.fofou.org/sumatrapdf/topic?id=3184701

**Comment by jan-glx** [comment]
I just installed SumatraPDF-prerelease-10569-64 for this feature, but it does not work:
![capture2](https://cloud.githubusercontent.com/assets/1266815/21267686/b3b2236a-c3ab-11e6-851e-4475d9e7d268.PNG)

I am running Microsoft Windows 10.0.14393.
