### ISSUE TITLE
Ability to set default author name for annotations

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2160]
https://forum.sumatrapdfreader.org/t/how-to-change-author-name-in-annotations/3601

Add advanced setting to set default author name for annotation. "(none)" to disable (empty string doesn't work because it means "use the Windows user name".

Currently we use windows user name.

**Comment by GitHubRulesOK** [comment]
I think for blanking/none if a single space is replaced by my windows username it becomes K (as if I need reminding) but a simple - (minus/hyphen) would do
