### ISSUE TITLE
wrong path has been contained in the substitute "1%"

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#2163]
https://www.sumatrapdfreader.org/docs/Customize-external-viewers

if  I will use the 1%, It don't work properly.

I get path :
![image](https://user-images.githubusercontent.com/11432724/133196106-bcb25acb-f38c-4a9f-931c-328ffda05c7e.png)

although I have to get path:
E:\Books\English\Greenbaum Sidney, Nelson Gerald C. An Introduction to English Grammar, 4th, 2016.pdf

```
ExternalViewers [
	[
		CommandLine = "C:\Users\God\AppData\Local\SumatraPDF\SumatraPDF.exe" "%1" "-page" %p
		Name = SumatraPDF
		Filter = *.pdf
	]
	[
		CommandLine = "C:\Program Files (x86)\Foxit Software\Foxit PhantomPDF\FoxitPhantomPDF.exe" "%1"  "/A" "page="%p
		Name = Fo&xit PhantomPDF
		Filter = *.pdf
	]
	[
		CommandLine = "C:\Program Files (x86)\Pdf & Djvu Bookmarker\PdfDjvuBookmarker.exe" "%1"
		Name = Pdf&Djvu Bookmarker
		Filter = *.*
	]
]
```

**Comment by kjk** [comment]
Which sumatra version?

**Comment by Aliaksandr3by** [comment]
![image](https://user-images.githubusercontent.com/11432724/133199973-14e7aa6d-531e-4129-aa74-ff662dd1ff26.png)

**Comment by Aliaksandr3by** [comment]
or get this:
![image](https://user-images.githubusercontent.com/11432724/133200074-3d72b806-f2e9-4a4f-8b8e-552df217bbb1.png)
instead that:
E:\BooksOther\Электрика\Жабцев В.М. - Главная книга электрика (Мастер Золотые руки) - 2014.pdf

might path bad work with spaces, points or dash?

**Comment by GitHubRulesOK** [comment]
just a side comment that in your SumatraPDF call you do NOT need the extra quotes around `"-page"` but it should not normally cause an issue

Command Line calls are often a problem with filenames containing spaces which require the `"` thus most of the time you need `"%1"` (but that is not always the case)

Unicode and odd CodePage characters will very frequently be an issue on some command lines.
International usage means usernames can have characters, now accepted by windows explorer but still not acceptable to basic Command Lines. So my native name has many times caused a problem (not just CMD but email etc) if I do not abbreviate it to simply K. When trying to support a user elsewhere I eventually had to suggest they used a different user account for LaTeX !! which has many different apps that could not respect their foreign identity.

Simple semi-poisonous characters such as . (dot) or differing da-sh¬es , (commas) `(quotes) and a'postrophes can sometimes cause issues thus are not recommended for filenames or paths. there are others that are not allowed in a filename such as : / & ^ ><etc.

**Comment by Aliaksandr3by** [comment]
can I use the powershell instead CMD?

this is work:
`PS C:\Users\god> &'C:\Program Files (x86)\Pdf & Djvu Bookmarker\PdfDjvuBookmarker.exe' 'E:\BooksOther\Кулинария\Голиенко А. Домашние сырники, творожники, запеканки, ватрушки, чизкейки и другие блюда из творога.pdf'`

**Comment by GitHubRulesOK** [comment]
@kjk
it looks like there is a regression it is not the filename  but removal of double quoting "

![image](https://user-images.githubusercontent.com/12754913/133264460-1fe07c67-7f2d-4936-8f29-797c263ba838.png)

![image](https://user-images.githubusercontent.com/12754913/133264949-fa552b05-9309-4ced-accd-5ffa9875dc20.png)
