### ISSUE TITLE
copy from arabic pdf does not respect RTL setting

### ISSUE THREAD

**Issue by pbienst** [sumatrapdfreader/sumatrapdf#2170]
When copying and pasting from an arabic text pdf, the letters are in the wrong order.

E.g, Adobe copies بعد just fine, but sumatrapdf turns this into دعب

**Comment by 9a3eedi** [comment]
I can confirm this issue as well on v3.2. I've tried this on mulitple Arabic PDFs from difference sources and it happens on all of them.

**Comment by GitHubRulesOK** [comment]
Same known regression in MuPDF support as per https://github.com/sumatrapdfreader/sumatrapdf/issues/1870 since version 3.1.2

![image](https://user-images.githubusercontent.com/12754913/136673268-2e7625ca-06e6-4ff0-b124-9e3aea382bed.png)
