### ISSUE TITLE
pre-release download links

### ISSUE THREAD

**Issue by m000** [sumatrapdfreader/sumatrapdf#2172]
This is not software related, so I'm not sure if this is the right place to report it.

Currently, the download links for pre-releases appear to be broken. The issue seems to be a double `/` character in the URL, which is not handled correctly somewhere along the way.

E.g.
* Broken: https://kjkpubsf.sfo2.digitaloceanspaces.com//software/sumatrapdf/prerel/14145/SumatraPDF-prerel-64-install.exe
* Should be changed to: https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/prerel/14145/SumatraPDF-prerel-64-install.exe

**Comment by kjk** [comment]
Thanks, fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/a16d6b423c8cf9e0260ff21f9abc850d86ef3fee
