### ISSUE TITLE
Crash and pdf corrupt when saving annotations

### ISSUE THREAD

**Issue by dlopez831** [sumatrapdfreader/sumatrapdf#2173]
Version: 3.4.14152 64-bit Pre-release (Windows 10)
Steps done:
1) Created highlight annotations by selecting text and pressing "a".
2) Context menu > Save annotations: This has a first issue since a message appear saying "annotations saved to file..." but message in red on toolbar keeps saying "You have unsaved annotations".
3)  Context menu > Show annotations:
4) Press button "Save changes to existing PDF": Results in app crash and the pdf document can no longer be opened ("error loading file").

**Comment by kjk** [comment]
Does it happen with every file or just one specific file?

If only specific file, could you share it with me (kkowalczyk@gmail.com) ?
