### ISSUE TITLE
Feature request: copy selection as an image

### ISSUE THREAD

**Issue by ikanakova** [sumatrapdfreader/sumatrapdf#2176]
I would like it to be possible to copy part of the text as an image - this is especially useful for mathematics formulas (in PDF files created using LaTeX) that behave strangely after pasting into a text editor.

**Comment by kjk** [comment]
It's already possible:
* hold Ctrl when selecting area with mouse
* press Ctrl-C
* copy as image with Ctrl-V (to e.g. ms paint)
