### ISSUE TITLE
Feature Request: Change starting page for book view

### ISSUE THREAD

**Issue by BurkSchu** [sumatrapdfreader/sumatrapdf#2179]
When i'm reading a magazine, I want to change the pages that are displayed together. Sumatra shows Page 1+2, 3+4, but I want to see page 2+3, 4+5, and so on. Is that already possible? If not, it would be great to have an option to change the start page!

**Comment by Miademora** [comment]
If you go to View - Book view (or ctrl+8) you get 2+3 and 4+5 etc.
