### ISSUE TITLE
bumpy text rows

### ISSUE THREAD

**Issue by libor-m** [sumatrapdfreader/sumatrapdf#218]
The pdf at http://aidblab.cse.iitm.ac.in/cs625/vptree.pdf seems not to be rendered correctly (sumatra pdf version 3.0):
![sumatra](https://cloud.githubusercontent.com/assets/1497769/8055931/b71316f4-0ea3-11e5-92f3-6427b29cd5fb.png)

This is Acrobat 7.0 rendering:
![acrobat](https://cloud.githubusercontent.com/assets/1497769/8055932/b7198624-0ea3-11e5-9dcf-b8cec9afdf38.png)

**Comment by kjk** [comment]
Dup of #210

**Comment by libor-m** [comment]
Sorry for the dupe, didn't know how to describe the problem in the search box;)
