### ISSUE TITLE
cannot open my pdf with version 3.3.3 but 3.0 does

### ISSUE THREAD

**Issue by icefairy** [sumatrapdfreader/sumatrapdf#2181]
I have a pdf file,that open and view it normal in ver3.0 but ver 3.3.3 tell me open failed,there is the file:https://drive.google.com/file/d/1mWCze9i21YKOqaFv6xIVJU6AmrQ0XHy-/view?usp=sharing
thank you

**Comment by GitHubRulesOK** [comment]
@icefairy 

I have no idea how well the repairs are on this repaired file, which is repaired by one of many older pdf repair tools.
[fixed.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7315545/fixed.pdf)

**Comment by icefairy** [comment]
thanks
