### ISSUE TITLE
Odd scanned PDF from forum post

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2190]
From https://forum.sumatrapdfreader.org/t/scanned-doc-show-black-background-with-faintly-visible-bold-text-3-0-and-above/4400/2

Looks like the file uses an odd JP2 compression or colour space for that format which recent MuPDF considers as black

[black-3.0-above[1].pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7345079/black-3.0-above.1.pdf)

**Comment by GitHubRulesOK** [comment]
Hmm ? 

last time I tested **on Win 10** this file still had some problems even after the MuPDF correction commit,

 however current build 3.4.14234 in Win 7 with aero the bug does not appear ?
![image](https://user-images.githubusercontent.com/12754913/145698301-c677772c-96c3-4a07-944f-60421e040913.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
not sure this is 100% closed (muPDF say fixed)
and I can get good results in both 32bit Win7 and 32/64bit Win10 
thus appears to be resolved?
have you any other platform for testing ?

**Comment by DevBeatDad** [comment]
No unctuously untoward utterances here.

**Comment by GitHubRulesOK** [comment]
@tactilis 
Martin can you confirm latest build works for you with these files ?

**Comment by tactilis** [comment]
Yes, the file is displayed correctly in pre-release build version 14234

**Comment by GitHubRulesOK** [comment]
@kjk Closing as seems to have been resolved in MuPDF as a result of your bug report
