### ISSUE TITLE
Crash when printing

### ISSUE THREAD

**Issue by rickannoy** [sumatrapdfreader/sumatrapdf#2191]
While printing a pdf file from sumatrapdf to PDF24 printer (virtual printer pipeline) I stopped printing midway and that caused a crash. 
Link to gist: https://gist.github.com/rickannoy/eec711d7eac44bd5b5bff78124c3dc25#file-sumatrapdfcrash-txt

**Comment by kjk** [comment]
Can you share the file as describned in https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports ?

There's really nothing I can do if I can't reproduce the crash myself.

**Comment by kjk** [comment]
Can't investigate without a file
