### ISSUE TITLE
Compiling/linking issues with EngineDump

### ISSUE THREAD

**Issue by TallBoySmall** [sumatrapdfreader/sumatrapdf#2192]
Hi!

First of all, I have some programming experience, but with C/C++ I am still a beginner. Now,  I just wanted to compile SumatraPDF myself. I successfully did that a few times before, but this time it won't work.
I simply downloaded the source code by using the "Code" button. I did not check out the repository.
The compilation process stopped with an error:

_Description: "Cannot open include file: 'EngineDjVu.h': No such file or directory
Project: enginedump
File: EngineDump.cpp
Line: 18_

So, I added that file. I even tried to reconstruct the code as it looked like several months ago with some adjustments.
That worked, but then I got the next issue:

_Description: 'CreateEngine': function does not take 2 arguments
Project: enginedump
File: EngineDump.cpp
Line: 550_

Well, I added _false_ as the 3rd argument and the compilation completed, but then it failed while linking. The error looks like this:

_Description: unresolved external symbol "class Gdiplus::Bitmap *_ ___cdecl BitmapFromData(struct ByteSlice)" (?BitmapFromData@@YAPEAVBitmap@Gdiplus@@UByteSlice@@@Z)
Project: enginedump
File: engines.lib(EngineImages.obj)
Line: 1_

I have no idea how to fix this properly. I commented out all calls of that function what makes compilation and linking to work, but then the program would be nearly unuseful :-)

It would be nice, if that could be solved, since I wanted to experiment a bit and eventually contribute some code when the time comes.

Thanks.

**Comment by GitHubRulesOK** [comment]
@TallBoySmall you may wish to note https://github.com/sumatrapdfreader/sumatrapdf/commit/e3ea0a6a21fa2c3a3017cbead3512d043fb1c6d2

**Comment by TallBoySmall** [comment]
@GitHubRulesOK, @kjk
Great! Thanks!
