### ISSUE TITLE
support heic / heif files

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2196]
https://forum.sumatrapdfreader.org/t/sumatrapdf-isnt-opening-heic-or-heif-files/4403/2

**Comment by GitHubRulesOK** [comment]
@kjk 
My windows 10 does not support heic/heif files so sumatraPDF does not open either of these supposed stock samples
can you confirm both are valid as test cases?

[sample1.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/7357397/sample1.zip)

**Comment by kjk** [comment]
Could you link to that codec?

Somehow one of my Windows 11 instances has the codec but the other doesn't.
