### ISSUE TITLE
Pinning the tabs, multi-row tab management and session management

### ISSUE THREAD

**Issue by dataskin** [sumatrapdfreader/sumatrapdf#220]
Hi,

I'd like to request a new features and functionality that would allow me to:
-pin the tabs (just like in Chrome/Firefox web browser) for future use
-optional multi-rows for better multi-tab management
-saving and restoring the tabs in bulk as "sessions" (with a clear list of sessions, an option to name/re-name them/delete them or even - search through them)

These are the features that I miss the most in SumatraPDF, so far.

Thanks for an amazing app.

**Comment by Sasstraliss** [comment]
Seconded

**Comment by kjk** [comment]
let's not create issues with multiple things in them.
