### ISSUE TITLE
Navigating via bookmark requires two Back commands to undo

### ISSUE THREAD

**Issue by SpecLad** [sumatrapdfreader/sumatrapdf#2202]
1. Open any PDF file with bookmarks ([example](https://webassembly.github.io/spec/core/_download/WebAssembly.pdf)).
2. Click on a bookmark.
3. Press Alt+⬅. Nothing will happen.
4. Press it again. SumatraPDF will navigate back to the beginning of the document.

Expected behavior: SumatraPDF should navigate back in step 3. It shouldn't be necessary to press the shortcut twice.

I can reproduce this with both the current release (3.3.3) and the development branch (commit 68c5a9912ccfc52be1234158391129db06c52e83).

**Comment by GitHubRulesOK** [comment]
that commad is a bit of an oddball in MS trees its a go back to previous thus can jump forwards to previous mark just as much as back to start.

To see that in action pick a few bookmarks in reverse order, the same in windows explorer, the last resting place is the one first opened and in a PDF opened by SumatraPDF that is usually counted as the first page.

**Comment by SpecLad** [comment]
@GitHubRulesOK That's totally fine. The problem is that it doesn't jump _anywhere_ at first.

Anyway, I did a bisect and found out that this is a regression that was introduced in 9f2b9d7d.

**Comment by SpecLad** [comment]
I did some more digging and found the cause of the problem. When you click the bookmark, both `TocTreeClick` and `TocTreeSelectionChanged` run and both of them navigate to the new location. Therefore, two locations get added to the location history instead of one.

`TocTreeClick` should probably only do its thing if the item being clicked is already selected.

**Comment by humidifier-dev** [comment]
@SpecLad Hey! I also investigated this situation and made a pull request. 
I also think that clicking on selected bookmark should only works if this bookmark is already selected. So I've made a pull request
https://github.com/sumatrapdfreader/sumatrapdf/pull/5157

**Comment by GitHubRulesOK** [comment]
@DerDunkelheit 
Current version works as per issue thus was closed how does your addition make that different ?
Use the above sample click on introduction it goes there instantly

<img width="700" height="249" alt="Image" src="https://github.com/user-attachments/assets/619d2126-a134-44cd-a16f-f0214b392951" />

click on back and it goes back to first page. which is correct "Alt + Left Go back"

<img width="700" height="295" alt="Image" src="https://github.com/user-attachments/assets/49ac3829-4dff-44c6-8a4f-202928ac31c2" />

**Comment by humidifier-dev** [comment]
@GitHubRulesOK My PR is not directly related to this issue.
It makes navigation to the currently selected bookmark possible.

To reproduce this, you can do either of the following:
1. Click on any bookmark you have, then scroll away from that page. Click on the same bookmark again — nothing will happen
2. Add only one bookmark to the list and try to navigate to it several times

When the onClick callback was introduced, this issue appeared, so the old code was commented out to restore working navigation.
I reworked this code a bit in my PR so that we can now select a single bookmark again, without breaking the existing functionality related to this issue.

**Comment by GitHubRulesOK** [comment]
@DerDunkelheit  agreed the select function is as you describe (non functioning)
 but appears here in this thread as if a solution directly to this issue
 but it is more related to others.
