### ISSUE TITLE
Multiple crashes

### ISSUE THREAD

**Issue by SFerrel** [sumatrapdfreader/sumatrapdf#2203]
https://gist.github.com/SFerrel/25445637e9e23646ce2f073ddee13f68
Edited the crash report for privacy.

**Comment by GitHubRulesOK** [comment]
`cannot find ExtGState` is usually an indicator that the the file is not built correctly and possibly as a warning ignored but another object then crashes the file see https://stackoverflow.com/questions/33741465/how-to-fix-cannot-find-extgstate-dictionary-in-mupdf

Perhaps if you can send or email a copy to kjk for checking if the problem can be worked around, but f the file is truly bad there's no guarantee You can e-mail the file to kkowalczyk@gmail.com

**Comment by kjk** [comment]
Unfortunately the crash report has no symbols so there's nothing I can do.

**Comment by kjk** [comment]
No repro file, nothing to investigate.
