### ISSUE TITLE
Annotation saving very slow on large pdf

### ISSUE THREAD

**Issue by sleepyspider1** [sumatrapdfreader/sumatrapdf#2205]
When adding and then saving an annotation (highlight), clicking "save" to save the annotations is very slow.
Like on the order of minutes. App is unresponsive during this time.
I was annotating the large pdfs at [](https://www.motionmountain.net/)

**Comment by kjk** [comment]
How big is big?

I tried with a 1 MB PDF and it took ~120 ms, which is fast.

That being said, I can see how a bigger, more complex file could take more time.

If you send me the file I can profile saving process to see if there's something obviously slow there.

Without a concrete repro it's not actionable.
