### ISSUE TITLE
Open .fb2.zip files in mupdf engine

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2209]
`EngineMupdf` doesn't support `.fb2.zip` files (fb2 inside .zip). For expediency, I use `FbDoc` to render them.

They render differently so for consistency we should support `fb2.zip` in mupdf.

Maybe also support e.g. .pdf inside .zip.

**Comment by GitHubRulesOK** [comment]
@kjk perhaps close this as duplicated by description in https://github.com/sumatrapdfreader/sumatrapdf/issues/2305

**Comment by kjk** [comment]
Closing as dup of #2305
