### ISSUE TITLE
Add text reflow option

### ISSUE THREAD

**Issue by Saya47** [sumatrapdfreader/sumatrapdf#2211]
Text reflow option is a "zoom option" it basically zooms as much as there are no left and right white margins visible.

This is very useful because PDF's have large left/right margins and the text appears small, and I have to manually zoom in and find the perfect zoom percentage for each PDF file.

This feature is almost like the Ctrl + 3 (Fit Content) but the issue is that Fit Content zooms vertically and horizontally. I just want an option so that it fully zooms horizontally.

Thanks very much for reading! I hope you consider this, it's a brilliant app regardless, my favorite and only PDF reader.

**Comment by GitHubRulesOK** [comment]
Closing as duplicate of requested function "fit to width" https://github.com/sumatrapdfreader/sumatrapdf/issues/767
