### ISSUE TITLE
left and right narrow

### ISSUE THREAD

**Issue by yanlongbinluck** [sumatrapdfreader/sumatrapdf#2214]
Hi，SumatraPDF is my favorite pdf reader. But there may be a bug in 4k screen?
As shown in follow figure, when I want to close the rightmost pdf file, there is a "left and right narrow". It prevents me from closing the pdf file.
But there is no problem using 2k resolution.

![111](https://user-images.githubusercontent.com/35165028/138622352-b0d7adcd-ffac-4aa7-ab50-bd020e7035b5.png)

**Comment by yanlongbinluck** [comment]
any solution？

**Comment by yanlongbinluck** [comment]
@GitHubRulesOK
Thanks.

**Comment by GitHubRulesOK** [comment]
I am closing as duplicate of a longtime issue that the rescaling usually when using high resolution monitors upsets tab bar scaled widths

Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/447
