### ISSUE TITLE
printing PowerPoint 2010 pdf documents with formulas results in Korean symbols

### ISSUE THREAD

**Issue by axelh** [sumatrapdfreader/sumatrapdf#222]
When printing math formulas created in PowerPoint2010 and save it as pdf, open in Sumatra, it displays everything correctly, but prints out Korean symbols instead of some math symbols. Adobe Acrobat 8.0 prints fine, though.

**Comment by kjk** [comment]
Should be fixed in the latest pre-release version (http://www.sumatrapdfreader.org/prerelease.html)
