### ISSUE TITLE
When installed by admin user, non-admin users cannot use

### ISSUE THREAD

**Issue by GuiLearner** [sumatrapdfreader/sumatrapdf#2222]
Trying to install to a _non-Administrator_ account on Windows 10.
Using the 64 bit instal.

The process requires giving the PIN of the administrator account.
It then runs through, installing the program, and putting an icon onto the Administor (not the non-Administrator) account.

Attempting to use Sumatra from the non-Administrator account fails with authorisation error.
But it seems to work perfectly from the Administrator account.

Best regards

**Comment by masteralarm** [comment]
This would also be a welcome improvement for the usage in packacge managers, like [winget](https://github.com/microsoft/winget-pkgs).
Currently this fails to work reliably for the same reasons. The installer also seems to always demand elevated permissions, which also breaks this.

**Comment by maehne** [comment]
I agree with @masteralarm that it would be very nice if this issue would be resolved to facilitate installation via package managers.

**Comment by kjk** [comment]
In pre-release now by default we only install for current user.
There's `-all-users` flag for installing for all users (local machine)
