### ISSUE TITLE
Some menu bar entries sometimes not rendered

### ISSUE THREAD

**Issue by edo9300** [sumatrapdfreader/sumatrapdf#2223]
When switching tabs or sometimes even scrolling the pages, sometimes sumatra no longer renders some elements in the menu bar
![image](https://user-images.githubusercontent.com/18705342/139440738-973980f7-3259-43d7-b7be-eb061b099c2a.png)
(here it's not drawing the `page` text and the `find` text + edit box.
![image](https://user-images.githubusercontent.com/18705342/139440886-452cc1a9-c72c-498f-8b49-f44a7906a5dd.png)
Here it renders them properly.
I'm currently using v3.4.14110 64 bit but this issue happened on earlier versions as well.

**Comment by kjk** [comment]
Can't reproduce this in latest builds

**Comment by edo9300** [comment]
Recently i too didn't get this error (or at least didn't notice) but apparently it's still there 
![image](https://user-images.githubusercontent.com/18705342/173194283-d7f4d9e2-1079-48db-94ed-5381efd3f01a.png)
Also to be sure i downloaded the latest portable prerelease (to get a clean setup) and i'm still getting it

https://user-images.githubusercontent.com/18705342/173194719-8cc3c8a1-58c1-418c-8377-82a882c24d87.mp4

.

**Comment by kjk** [comment]
Can't reproduce in latest builds.
