### ISSUE TITLE
Crash with SumatraPDF Prerelease

### ISSUE THREAD

**Issue by karthikgopalakrishnan** [sumatrapdfreader/sumatrapdf#2225]
I have SumatraPDF set as the default handler for PDF files. So normally, I can open PDF files from the command line by simply typing the name of the file.

> D:\Reading Material> "Intel SDM\Intel 64 and IA-32 Architectures Software Developers Manual.pdf"

This works with version 3.3.3. But when I attempt the same with 3.4.14210 (c7ff295), it crashes.

The crash log is available [HERE](https://gist.github.com/karthikgopalakrishnan/f9b43b4e4a21494599b2b6a33d25bf30).

The PDF in question is available [HERE](https://www.intel.com/content/www/us/en/develop/download/intel-64-and-ia-32-architectures-sdm-combined-volumes-1-2a-2b-2c-2d-3a-3b-3c-3d-and-4.html).

I observe this crash with a few other PDFs as well, so it is not specific to just this one.

When I launch SumatraPDF.exe first & then open the same file from within the application, it does not crash.

**Comment by GitHubRulesOK** [comment]
@kjk just for comparison 
whilst MuPDF is not triggered to signal rebuilding, PDF-Xchange requires that files xref table be rebuilt

**Comment by karthikgopalakrishnan** [comment]
If you have the PDB for this build handy, can you please share it with me.

**Comment by GitHubRulesOK** [comment]
@kjk see comment in my crashreport #2228

**Comment by karthikgopalakrishnan** [comment]
Issue appears to be resolved with 3.4.14221 [(c3ae148)](https://github.com/sumatrapdfreader/sumatrapdf/commit/c3ae1487538092e4f7e29b7d5ca2bad82ef6aea7). Thank you.
