### ISSUE TITLE
Continuous scrolling / ebook mode accessibility

### ISSUE THREAD

**Issue by eliacc** [sumatrapdfreader/sumatrapdf#2226]
If you open an epub file, you must set `UseFixedPageUI=true` in advanced settings to get continuous scrolling. I think this is currently overly difficult to discover.

If you open an epub file, there's no mention of continuous/smooth scrolling anywhere except in Settings, under Default Layout. You can see a list of modes under the View menu, but it's not clear why continous/smooth isn't among them. If you google around and hit the right keywords, you might eventually hit #564 and realize you need to go into advanced settings and set a flag. Or you might assume it's broken / not a feature and uninstall and move to the next ebook reader (if you're a user like me searching for a program to view epub files nicely)

It seems like some options could be
* annotate the requirement under Default Layout
* show all modes under View, but have continuous mode greyed out / switch to pdf mode if you select it

Of course it could always be that less people want continuous mode than I believe, but it seems like something that should be easy out of the box and could especially turn less technical users away so I figured I'd make the suggestion. Having found smooth mode, I love sumatrapdf.

**Comment by GitHubRulesOK** [comment]
There is now only UseFixedPageUI=true as default in pre-release 3.4 (thus most likely kept in next release)

Continuous mode is a Fixed Page toolbar button (along with zoom and search) and optionally could and can be set as as you note to default in options.

Closing as a historic requirement.

**Comment by tayflo** [comment]
It's a little too bad that this new behaviour removes the possibility to customise font face/name and size for epub files, even if I don't see that as such a big deal.
