### ISSUE TITLE
Crash and pdf corrupt when saving annotations

### ISSUE THREAD

**Issue by dlopez831** [sumatrapdfreader/sumatrapdf#2227]
This issue is to reopen #2173 that is not fixed in pre 3.4.14210

Now I add the info sent to kkowalczyk@gmail.com on october 1st:

**The problem seems to happen with any pdf file that is in my Google Drive folder. I mean, a local folder that is synchronized with Google Drive client for Windows in real time**.
Sumatra seems to effectively save the annotations but doesn't realize itself.
For example, the following capture is after "Save annotations" via context menu.

![image](https://user-images.githubusercontent.com/38507751/139723040-0db6e52c-08f5-4594-bf24-634d85e41970.png)
If after that, I exit Sumatra, it asks again whether to save the changes. If I choose "Discard changes" and reopen the file, I see that the annotations were saved.
If I choose "Save to new file", then Sumatra can't open the new file.
If I choose "Save to existing file", then Sumatra can't open the original file.
If I go to Edit annotations and the press button "Save changes to existing pdf" then Sumatra says it saved the file, gives an error reloading the file and crashes.
See 2nd capture:
![image2](https://user-images.githubusercontent.com/38507751/139723091-e789b5b3-a780-4a24-96bd-07507685ae38.png)

**Comment by fepz** [comment]
I have the same problem (v3.4.6 64-bit -- git commit 7a19622). It seems to happen only with files in the Google Drive drive (tested it with OneDrive and Dropbox and it works fine).

**Comment by fepz** [comment]
I think that that shouldn't be an issue. Anyway, the synchronised drive is personal, and I am the only one editing the file.

**Comment by GitHubRulesOK** [comment]
@dlopez831 
Can you please test current pre-release 3.5.17## for same problems as there were many changes since this 3.4.14210 version

**Comment by dlopez831** [comment]
> @dlopez831 Can you please test current pre-release 3.5.157## for same problems as there were many changes since this 3.4.14210 version

Sorry. Where do I find that version?

**Comment by kjk** [comment]
You can test with latest release 3.5.2 from https://www.sumatrapdfreader.org/download-free-pdf-viewer

**Comment by dlopez831** [comment]
@kjk  Now it seems to work fine. 
Thank you for the great job!
