### ISSUE TITLE
Crashreport did not download symbols

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2228]
Failed to download symbols seems to be a fresh issue
This file cause me a crash without symbols downloading even if requested from debug for a second test after

[primefaces_user_guide_5_0.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7456360/primefaces_user_guide_5_0.pdf)
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/7456367/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
I can't get this file to crash with 14298.

Downloading of symbols seems fixed.
