### ISSUE TITLE
Bookmark tree not navigating

### ISSUE THREAD

**Issue by ajs138** [sumatrapdfreader/sumatrapdf#223]
When you click on a bookmark in the tree, it should navigate to that section. It's not happening. I checked the latest pre-release, still not working. This is kind of a deal-breaker.

**Comment by kjk** [comment]
It does work in general. Most likely it's a malformed PDF file. Please verify with another reader (like Adobe Reader) and if it works in Adobe, then please make the PDF available for investigation.

**Comment by ajs138** [comment]
You're right, it was the pdf. It doesn't work in Adobe Reader either, and when I got the updated version from the vendor, it works fine in both. Thanks for the prompt response.

**Comment by kjk** [comment]
Thanks for the confirmation.
