### ISSUE TITLE
Cursor doesn't hide in fullscreen mode

### ISSUE THREAD

**Issue by Zuj3brusu** [sumatrapdfreader/sumatrapdf#2231]
Cursor doesn't hide automatically while using fullscreen mode.

**Comment by GitHubRulesOK** [comment]
I dont think it should its just fullscreen rather than windowed

If you need cursor to timeout that's needed and available for presentation (F5 mode)

**Comment by kjk** [comment]
It does look like a regression in 3.3 re: not hiding the cursor on timeout after first time.

@Zuj3brusu can you name those other applications?
