### ISSUE TITLE
Show zoom level when zooming in / out

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2237]
When zooming in / out with keyboard shortcuts / toolbar, "flash" temporarily the current zoom level.

Similar to info shown with 'i'. Maybe also add zoom info to 'i'. 

Make it nicer, visually than current Notifications.

https://forum.sumatrapdfreader.org/t/zoom-percentage-info/4458

**Comment by drkhn1234** [comment]
Yes, please. I sometimes have a hard time which zoom level I am on and thus incorrectly judge by which zoom level I want to set to using one of the CmdZoom[zoomlevel] shortcuts.

**Comment by GitHubRulesOK** [comment]
@drkhn1234 
see related #2502 but "For a fast check you can use the CTRL Y shortcut" to a degree !

**Comment by drkhn1234** [comment]
> @drkhn1234 see related #2502 but "For a fast check you can use the CTRL Y shortcut" to a degree !

Thanks for the heads up :)

**Comment by kjk** [comment]
Fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/709549f8ac6eb0a3f71fe086c18099fdb1254f61
