### ISSUE TITLE
Make the file background itself and properties background colors independent

### ISSUE THREAD

**Issue by Shideravan** [sumatrapdfreader/sumatrapdf#2241]
I really prefer that the file background be dark (#fff200) rather than bright yellow (#fff200) distracting my reading
![image](https://user-images.githubusercontent.com/12163923/140610955-e0dcd64b-42a6-49f1-aace-cea577cdcfee.png)

The problem is, with that configuration, the information in the document properties is not visible:
![image](https://user-images.githubusercontent.com/12163923/140610926-2cfccf72-d7d4-4404-8e39-6221047aa38a.png)

Could you make these color selections (for the properties window and the file itself) independent?

**Comment by GitHubRulesOK** [comment]
They are separate, however there are overlapping effects with different colour setting that would not be there if we still had the original two colours of a paper/valve display still common when PDF was invented.

![image](https://user-images.githubusercontent.com/12754913/140611797-68a071a5-07cb-4e37-8cb4-7e73c71a2254.png)

Closing as the theming/Main colour issues  are covered in multiple other open requests but issue of Main Yellow Backgroud was changed to user choice of a background colour and black is not a good choice for placing behind the Black UI artwork

**Comment by Shideravan** [comment]
Black is awesome to display areas not used. That's why it's used in many contexts as the default color of background of different proportion image, as eg. movies using movie players.
Also, black isn't a bright color and don't makes the eyes tired at the contrary of the yellow background. That said, in the same logic, yellow isn't a good color for.
Everything said, I didn't understood why not give the user the option for him to choose the colors. Most of PDF readers uses black as background color

**Comment by GitHubRulesOK** [comment]
Personally I find using black themes a nightmare you can let the system do whatever you like but its highly confusing using any other graphics app
![image](https://user-images.githubusercontent.com/12754913/140622373-8b78c34f-6932-45c8-9f2f-eecfd26618f1.png)
![image](https://user-images.githubusercontent.com/12754913/140622438-453441aa-48d9-4cf4-9927-71c1c1e7d883.png)
