### ISSUE TITLE
Open English book fast while open Chinese slow and even crash down sometimes 

### ISSUE THREAD

**Issue by HackYardo** [sumatrapdfreader/sumatrapdf#2243]
Could it repair?

**Comment by GitHubRulesOK** [comment]
Use latest pre-release 3.4.14221
Sadly non Latin fonts are often more problematic if not embedded correctly into PDF or epub in a standard fashion.

Provide a public sample file that crashes regularly with pre-release, (paste into question)

No promise of a fix, IF that file is way outside standards.

**Comment by HackYardo** [comment]
- Sorry, I'm a computer-blind. I don't know where is 3.4.14221, I can find 3.3.3.
- When open a bad file and get stuck, only first page and content could see, so I don't know whether or not that the file be in standard.
- When it get stuck, the SumatraPDF could open another good file and run fluently. But if I choose a chapter from the content of a bad file, SumatraPDF can not run and Windows11 ask me choose to close or wait.
- It seems that SumatraPDF doesn't use Unicode to parse characters of a file, why? I hear **utf-8** support any languages in the world and often used by programmers, so why support Latin rather than utf-8 for tier-1?

**Comment by GitHubRulesOK** [comment]
Apologies I should have shown a link to https://www.sumatrapdfreader.org/prerelease

A portable copy will do for testing files crashing

The PDF format was initially designed to support 14 stock printer font styles 12 anglo-american, one limited CJK font and one limited symbol font thus may not work with many European characters even if UTF-8 supported.

For non stock fonts they must be bloating the PDF by inclusion (embedding full font or a limited sub set) and must be included in a well defined method table or they cause corruption in viewing / read aloud / extraction of text.

**Comment by HackYardo** [comment]
- I use pre-release-3.4.14221 to open a bad file, it run **as fast as lightning**!
- I also open different Chinese files by release-3.3.3, its cases depends on **file-itself**. Some Chinese files open slower than English files, while some just get stuck. 
  - get stuck at the Page 2
  - get suck around ~1000 pages
    - [2_1000.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/7502235/2_1000.zip)

- Will SumatraPDF support **.azw3** in the future?

**Comment by kjk** [comment]
`2.epub` works fine for me in pre-release.

`1000.mobi` doesn't work. I can't tell if there's infinite loop or is measuring chinese text so slow that it just goes on forever.

**Comment by HackYardo** [comment]
@kjk I could open 1000.mobi completely after waiting several seconds by pre-rel-3.4.
The pre-rel-3.4 has solve my question, so I close this issue.

**Comment by GitHubRulesOK** [comment]
@HackYardo if you have a reasonable pre-release that suits your needs keep a back-up just in case any newer update exposes other file failings. The pre-releases are replaced frequently and not possible to re download if there are breaking changes consider as a beta version.

**Comment by HackYardo** [comment]
@GitHubRulesOK Got it, thanks a lot.
