### ISSUE TITLE
Email option needed

### ISSUE THREAD

**Issue by gorza47** [sumatrapdfreader/sumatrapdf#2244]
An (advanced) option to copy email address from the email adress ONLY would be nice, without "mailto:" text.
Now, I must delete "mailto:" each time manually (when used from context menu, Copy link address).

The (left) click on an email address starts now the default email program, this is not what I want.

An (advanced) option would be nice, to choose what will happen, like:
a) start email program (default)
b) copy email address (without "mailto:")
c) copy email address (with "mailto:")
d) do nothing ...

Thanks.

**Comment by kjk** [comment]
We'll just always strip "mailto:" when using Copy Link Target menu item.
