### ISSUE TITLE
pre-release tabs tooltips bug

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2247]
from user0 @
https://forum.sumatrapdfreader.org/t/3-4-0-0-prerelease-tooltips-bug/4493
I confirm there is odd behaviour after closing a tab the tooltips are out of sync

**Comment by kjk** [comment]
Most likely a regression from https://github.com/sumatrapdfreader/sumatrapdf/commit/fa479aa95f85bfbc49f8fc7aac029003f49c8d38

**Comment by kjk** [comment]
Management of tooltips in TabsCtrl2 is broken. We add in `TabsCtrl2::SetTooltip` when new tab is created, but we don't update  this info when tab is removed.
