### ISSUE TITLE
trouble in deleting highlight

### ISSUE THREAD

**Issue by lunbudao** [sumatrapdfreader/sumatrapdf#2248]
I'm very happy with the feature that we can highlight text with keyboard "a", but I think it is better to have a convenient way to delete the highlight. My current workflow of deleting highlight is:
1. right click on the highlight
2. press *E* to open the *annotation editor*
3. then click *delete annotation*

Though I can do this quickly, but this is somewhat distracting.
I think it would be better to add a shortcut (e.g. D) to automatically complete the workflow above.

**Comment by kjk** [comment]
Added context menu 'Delete Annotation' (if cursor is over annotation) and Del / Backspace keyboard shortcut (again, cursor must be over annotation).

**Comment by lunbudao** [comment]
Thanks very much, it is now more convenient now.

**Comment by harleyxu-xhl** [comment]
sorry, but I didn't find the 'delete annotation' in context menu.

**Comment by GitHubRulesOK** [comment]
@harleyxu-xhl ensure your using latest pre-release and over the annotation as mentioned above
![image](https://user-images.githubusercontent.com/12754913/160224526-343adca7-aa4a-441a-94c4-db01991e77b8.png)

**Comment by harleyxu-xhl** [comment]
thanks for replying! I already downloaded the pre-release version and it worked. This version is more user-friendly.
