### ISSUE TITLE
Bugs in continuously  deleting annotations without reopening Annotation Editor

### ISSUE THREAD

**Issue by lunbudao** [sumatrapdfreader/sumatrapdf#2249]
Here is what I do to delete annotations

1. Right click on the annotation I want to delete
2. Press shortcut *E* to open the *annotation editor*
3. Click *delete annotation*

This works fine if I only  delete one or two annotations, it fails when I continuously delete annotations (exactly follow the workflow above) while leaving *annotation editor* opened (since it could be inconvenient to close the *annotation editor* repeatedly)

**Comment by kjk** [comment]
Hopefully fixed but please re-open if you still encounter problems with deleting annotations.

**Comment by GitHubRulesOK** [comment]
@lunbudao 
Be aware the nature of annotations per Adobe (dont blame SumatraPDF for using MuPDF methods)
is to append them at the end of file (they are not inserted into the core PDF, they "float" over the underlying page).

The consequence is that they accumulate and a deletion is not removed from the file, simply removed from the page order.
Thus if you add and delete many annotations they may be saved in the file (not flushed) which can lead to unexpected (embarrassing) recovery later, and if repeatedly done in large numbers can make the file much bigger and in very extreme cases slower.

**Comment by lunbudao** [comment]
@kjk Thanks a lot, I think it is fixed now, I do not find problems using *del* shortcut.

**Comment by lunbudao** [comment]
@GitHubRulesOK Sorry, I do not really understand. If I delete an annotation, is it deleted from the final saved file?

**Comment by GitHubRulesOK** [comment]
@lunbudao 

Not always that is why there are news headlines when someone releases a "Redacted" file because the removed info is not always removed see https://forum.sumatrapdfreader.org/t/undo-highlights/4356/2?u=githubrulesok where the deleted comment is not visible but still in the file. That is not a bug in SumatraPDF or MuPDF it is a fail in the way a PDF annotation was designed by Adobe to be quick and easy.

**Comment by lunbudao** [comment]
Thanks, got it.
