### ISSUE TITLE
Printed barcode is with noise

### ISSUE THREAD

**Issue by apetrichkovich** [sumatrapdfreader/sumatrapdf#2250]
Hello.
We make PDF with barcode by **JasperReports** and it looks **OK**.
But when we print it using **SumatraPDF** we can see **noise** like on image.
Can you help to solve this issue?

![barcodeIssue](https://user-images.githubusercontent.com/531015/141967936-2de8e490-2b77-4283-91c4-4ef87fc901d6.png)

**Comment by GitHubRulesOK** [comment]
SumatraPDF printing is via windows basic image printing (much like jPeg with artefacts, is reasonably good with inkjets) so not ideally suited for laser or thermal printing, if you use SumatraPDF to push grey coloured pdfs (not the best format for thermal labels, ZPL or PNG in monochrome are much better) through a windows driver then a driver by seagull/bartender may improve / reduce those greyscale castellation's

**Comment by apetrichkovich** [comment]
Will try.
Thank you :)

**Comment by GitHubRulesOK** [comment]
Closing as duplicate mono thermal castellation of greytone see https://github.com/sumatrapdfreader/sumatrapdf/issues/203 and related https://github.com/sumatrapdfreader/sumatrapdf/issues/2140
