### ISSUE TITLE
read pdf and find keyword

### ISSUE THREAD

**Issue by husiluanxiang** [sumatrapdfreader/sumatrapdf#2251]
I want to open a pdf file and find keyword location in my project ,how can I use sumatrapdf lib.

**Comment by GitHubRulesOK** [comment]
Did you use current 3,4 pre-release and -search


`Sumatrapdf -search "sumatra" latest.txt`

![image](https://user-images.githubusercontent.com/12754913/142128597-a9ea2ce3-2382-4b56-a2b6-41d6586ce2ef.png)

**Comment by husiluanxiang** [comment]
> Did you use current 3,4 pre-release and -search
> 
> `Sumatrapdf -search "sumatra" latest.txt`
> 
> ![image](https://user-images.githubusercontent.com/12754913/142128597-a9ea2ce3-2382-4b56-a2b6-41d6586ce2ef.png)




> Did you use current 3,4 pre-release and -search
> 
> `Sumatrapdf -search "sumatra" latest.txt`
> 
> ![image](https://user-images.githubusercontent.com/12754913/142128597-a9ea2ce3-2382-4b56-a2b6-41d6586ce2ef.png)



> Did you use current 3,4 pre-release and -search
> 
> `Sumatrapdf -search "sumatra" latest.txt`
> 
> ![image](https://user-images.githubusercontent.com/12754913/142128597-a9ea2ce3-2382-4b56-a2b6-41d6586ce2ef.png)

thanks; but I want to use api find Keyword in my vs project not use  Sumatrapdf.exe file.how to solve it ,in code I am not find .rc file like Sumatrapdf GUI

**Comment by husiluanxiang** [comment]
thanks; but I want to use api find Keyword in my vs project not use  Sumatrapdf.exe file.how to solve it ,in code I am not find .rc file like Sumatrapdf GUI

**Comment by GitHubRulesOK** [comment]
SumatraPDF des not provide a Licensable API for the AGPL code
you would need to buy MuPDF from Artifex

**Comment by husiluanxiang** [comment]
ok  thanks
