### ISSUE TITLE
[Feature request]Customize the font size of EPUB e-books

### ISSUE THREAD

**Issue by Leroy-X** [sumatrapdfreader/sumatrapdf#2253]
First of all, I must thank the new version(3.4) of epub reading function is really great, speed performance, reading experience are very amazing. I bet this is the best epub reader on PC. I can't wait to tell my friend the news. You know I'm so excited.

Now I have a problem. The fonts of some epub books are very large, resulting in very little content on one page. I want to know how to modify or customize the font. This will be very useful for some epub books.

By the way, I found that the new version adds the function of invert color, coupled with advanced settings, which is really great. But I really hope to add some theme presets, such as a night theme that does not invert the color of the picture.

If you add the tts voice reading function, it will be more perfect, such as using edge's tts. Thank you very much for everything the development has done. Cheers

**Comment by GitHubRulesOK** [comment]
epub css fonts is an already open issue, the MuPDF engine allows for one user over-ride but in SumatraPDF  is potential work in progress

invert colour for negatives/blueprints etc. has never been a means to theming but is all too often abused as such. there are many open issues around both together.

Read Aloud and other accessibility limitations are also covered in other open issues, however the easiest method is to use SumatraPDF to call onboard Edge with the pdf page opened for that function, then its down to edge if the page is readable or not :-)

Closing as all items are covered by other open issues

**Comment by Leroy-X** [comment]
Thank you very much, you are awesome.

**Comment by Leroy-X** [comment]
Hi, MuPDF's Tinted Color Mode looks great, and it can be used with Inverted Color Mode to get very good results. Looking forward to adding this feature. big thanks again.

**Comment by GitHubRulesOK** [comment]
sumatraPDF has generally since switching to MuPDF used thos settings hence the problem that they are misused
```
-I
Start in inverted color mode.
-B hex-color
Set black tint color (default 303030)
-C hex-color
Set white tint color (default FFFFF0)
```

**Comment by Leroy-X** [comment]
Hi, my English is not good and I am not very clear. I downloaded the latest SumatraPDF（３．４．１４２２１）, press the shortcut keys B, C or Shift+B, Shift+C, I didn’t find tint　ｃolor, thank you very much for your reply

**Comment by GitHubRulesOK** [comment]
Those are the MuPDF viewer commands shown here inverted I was trying to say those are exactly what SumatraPDF uses for foreground and background either via colors on command line or internally in settings there is just the different names and command syntax
![image](https://user-images.githubusercontent.com/12754913/142338474-b0833e47-baa4-4e62-b085-684c3b5a0095.png)

**Comment by Leroy-X** [comment]
I got it, thank you very much. . . although I would prefer to have a shortcut, hahahaha

**Comment by GitHubRulesOK** [comment]
you can add it to a desktop startup shortcut (look at the command line options) for colour range and IF you really must have two, please call one normal and the other inverted (not night mode)

**Comment by Leroy-X** [comment]
wow,thanks. it's useful for me, cheers
