### ISSUE TITLE
Install per machine (for all-users)

### ISSUE THREAD

**Issue by xmha97** [sumatrapdfreader/sumatrapdf#2257]
Hi,
I want to install the SumatraPDF per machine (for all-users)
![image](https://user-images.githubusercontent.com/23485114/143325133-be40b3a0-dfbf-4920-8bda-1d0c21cb7af9.png)

**Comment by GitHubRulesOK** [comment]
duplicate of many isseues will search later 
Admins Install into whiver Program Files are is relevant to your language and users

for 64 bit English install to c:\Program Files
move the desktop icon from admin desktop to Public Desktop
each user will have a local file app data history / settings without corrupting others
 (so no need for admin to do anything else)
