### ISSUE TITLE
Pre-rel Menu missing on 32bit win 7

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2264]
Currently limited to netbook (32 bit win 7) so don't know if affects other platform(s) but the last few updates look like this (no web manual/update section) with a clean settings file

![image](https://user-images.githubusercontent.com/12754913/145308255-5d038aae-98be-43d4-9399-ebb9f671839d.png)

current downloads `not deleting 14229` only let me go back that far on this unit and the problem was manifest in that version

digging in archive 14228 was OK

**Comment by kjk** [comment]
It works for me.

Those menus are removed if internet access is disabled with `sumatrapdfrestrict.ini` (or `-restrict`)

**Comment by GitHubRulesOK** [comment]
ok am using different unfamiliar directories so it makes some sense

**Comment by GitHubRulesOK** [comment]
Spot On there was an ini lurking
