### ISSUE TITLE
14236 doesn't show bookmarks in this PDF

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#2268]
[2021年04月中国2型糖尿病防治.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7728365/2021.04.2.pdf)

But 3.3.3 does.

**Comment by kjk** [comment]
Looks like mupdf regression in loading an outline (bookmarks).

Reported as https://bugs.ghostscript.com/show_bug.cgi?id=704786
