### ISSUE TITLE
Feature Request: Close all open tabs with Ctrl + Shift + W

### ISSUE THREAD

**Issue by auyx** [sumatrapdfreader/sumatrapdf#2269]
I often use Ctrl + W to close multiple documents and would love to modify this function so holding shift too would close all the currently open tabs.

Anyone have any reason why this wouldn’t be a good addition?

Thanks for the hard work on this awesome application.

**Comment by GitHubRulesOK** [comment]
Closing as in effect duplicated by New feature: Close all other tabs / close right tabs
#388

Shortest workaround is to open one desired file in new window (CTRL SHIFT N) 
**or in this case none (CTRL N)** then close the one with multiple tabs open
