### ISSUE TITLE
German umlaut "ö" rendered on screen, but not printed

### ISSUE THREAD

**Issue by mweber55** [sumatrapdfreader/sumatrapdf#227]
We create PDFs automatically with Java API of Crystal Reports. Resulting documents can be printed correctly with Adobe Reader, but when printed with Sumatra it does not print the German special character / umlaut "ö". 
Other umlauts ("ä", "ü") are printed correctly, also screen rendering of the document is ok.
When creating PDFs with Windows Version of Crystal Reports API this problem does not occur. I thought of font problems, but have not idea where to look into or what to try.
Example document: https://www.dropbox.com/s/0rnicbwrql2c9kc/Penka_Klima_LF_307768_Packstueckliste_Ex_2.pdf?dl=0

**Comment by kjk** [comment]
Please try the latest pre-release (http://www.sumatrapdfreader.org/prerelease.html), it should print exactly as it renders on screen.

**Comment by mweber55** [comment]
It worked, wonderful. Thanks for your quick reply and for developing this handy tool. My customer wanted to donate some money to the project, but I read on the forums that you don't accept any donations?

**Comment by kjk** [comment]
Thanks for verifying the fix.

Yes, we don't accept donations.
