### ISSUE TITLE
Add custom value (or more fine-grained) for zoom

### ISSUE THREAD

**Issue by tawmoto** [sumatrapdfreader/sumatrapdf#2270]
Hi,

Is there any chance that the zoom can be more fine-grained or add a custom value there?
For example in Adobe I mostly use 175% which is missing in SumatraPdf, I have only 150% and 200%.

Thank you

**Comment by GitHubRulesOK** [comment]
Just insert the value you want in settings as I have done Here

ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150  **175**  200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

You could also try the zoom increment however it is not steps but percent so if set to 10% and you are currently 210% and zoom in it will then be 231% so less useful for precis steps

**Comment by GitHubRulesOK** [comment]
I forgot to add you could add a custom view in settings so that a hotkey of say ALT F Z could zoom current page to 175

ExternalViewers [
	[
		CommandLine = "C:\SumatraPDF\3.1.2\SumatraPDF.exe" -zoom 175 -page %p  "%1"
		Name=&Zoom 175
	]
]

**Comment by tawmoto** [comment]
> Just insert the custom value you want in settings as I have done Here
> 
> ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 **175** 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400 ZoomIncrement = 0
> 
> You could also try the fine grain ZoomIncrement set to a low value however it is not steps but percent so if set to 10 and you are currently 210% and zoom in it will then be 231% so less useful for precis steps

Hi, thanks for the answer.
I added 175% in the settings but they it does not show in the Options
![image](https://user-images.githubusercontent.com/35702340/147256969-3f161bda-d010-4d84-8178-3172aed257b1.png)

**Comment by GitHubRulesOK** [comment]
I think that list is hard coded to the default values but the custom zoom step should be honored when zooming in out past that point. For a fast check you can use the CTRL Y shortcut but it too will not offer custom values in its drop down you can manually enter 175, but that is slow hence the suggestion to **add** the ALT F Z for speed and consistency.

@kjk  I am guessing that modifying the drop downs to include poor user custom values might cause instability or need some slower refactoring of both dialogs?

**Comment by tawmoto** [comment]
> I think that list is hard coded to the default values but the custom zoom step should be honored when zooming in out past that point. For a fast check you can use the CTRL Y shortcut but it too will not offer custom values in its drop downs. You can manually enter 175, but that is slow hence the suggestion to **add** the ALT F Z for speed and consistency.
> 
> @kjk I am guessing that modifying the drop downs to include poor user custom values might cause instability or need some slower refactoring of both dialogs?

Thank you, I will use CTRL-Y for now, I think it's enough, thank you.

May I ask another question pls: can I somehow increase the size of the toolbar buttons? I have a very big screen, but those button are very small, I barely can see them. Also the "Match case" button looks very pixelated. Thank you.

![image](https://user-images.githubusercontent.com/35702340/147265860-5117dffa-afe1-4a6b-b9c1-270d5c8cfa93.png)

**Comment by GitHubRulesOK** [comment]
You can add the custom 175 value with a space each side 
my query to the developer KJK was if a bad value was included in drop down would it upset using custom settings values since in some other cases where users have applied incorrect settings values it has caused other problems.

For your other question there is another discussion https://github.com/sumatrapdfreader/sumatrapdf/issues/1519 , but note the icons were customisable bitmaps that got complaints but now are SVG vectors and it is the translation to screen pixel resolution that affects size and appearance.

**Comment by GitHubRulesOK** [comment]
@tawmoto 

> May I ask another question pls: can I somehow increase the size of the toolbar buttons? I have a very big screen, but those
> button are very small, I barely can see them. Also the "Match case" button looks very pixelated. Thank you.

Now possible in pre-release 3.4.14458
ToolbarSize = 36
