### ISSUE TITLE
If outline was repaired we show "unsaved annotations"

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2271]
Repro file in #2268 
https://github.com/sumatrapdfreader/sumatrapdf/files/7728365/2021.04.2.pdf

After outline is repaired, we show the file as having unsaved annotations.

**Comment by GitHubRulesOK** [comment]
@kjk This reminds me that some other annotation change of appearance, perhaps form field widgets or similar, picked up by mupdf may also trigger the "unsaved" condition so is there a way to flag the difference of those found by MuPDF "fixes" in the file before user adds annotations, I presume that would still need a query to save first? but no way to divide and conquer the problem.

**Comment by kjk** [comment]
Yes I hope there is a way to tell the difference but I have to look into mupdf code to figure it out

**Comment by GitHubRulesOK** [comment]
@kjk there is a fresh example linked in forum at https://forum.sumatrapdfreader.org/t/you-have-unsaved-annotations/4634
