### ISSUE TITLE
Some "text" objects not displayed in current version

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2273]
From Forum

[960468_FI_070.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/7788921/960468_FI_070.pdf)

Overprinted near White (252,252,252) text (and possibly some other objects, see top registration target)  can be seen/printed in acrobat

![image](https://user-images.githubusercontent.com/12754913/147664257-2913a787-a45d-45f5-ae29-bb97f0ed9be6.png)

However they are not showing in SumatraPDF

![image](https://user-images.githubusercontent.com/12754913/147664548-8749d4dc-90f7-4e76-98a0-a5bc39b4911c.png)

**Comment by entaxei** [comment]
I think I have the same issue. Old Sumatra Version is OK, last version is worng.
Unfortunately I cannot attach the entire original file as it contains personal data (tax return).
![errore sumatrapdf v3 3 3](https://user-images.githubusercontent.com/98883967/152143387-96fe18c0-0d34-4a89-a02a-31baafbde26f.JPG)

**Comment by GitHubRulesOK** [comment]
@entaxei 
No thats a different problem the letters are not invisible they are just not the right ones. try latest 3.4 [pre-release](https://www.sumatrapdfreader.org/prerelease) which fixes ***some*** of similar wrong font problems

**Comment by entaxei** [comment]
Thank you.
The pre-release does not have the same problem, the document reads correctly.
Thank you.
Regards.

**Comment by GitHubRulesOK** [comment]
@kjk the original problem still stands in 12460
![image](https://user-images.githubusercontent.com/12754913/152454403-79728ac8-f1dd-4f20-bebe-572a7809636c.png)

**Comment by GitHubRulesOK** [comment]
The text object (13) has off white embedded font contents but in SumatraPDF the white is not showing, over the pink
![image](https://user-images.githubusercontent.com/12754913/152454970-958c2f10-facb-4ddd-887d-a501baac8d47.png)

**Comment by kjk** [comment]
Reported to mupdf as https://bugs.ghostscript.com/show_bug.cgi?id=704874
