### ISSUE TITLE
Delete key not working in text boxes

### ISSUE THREAD

**Issue by edo9300** [sumatrapdfreader/sumatrapdf#2274]
I can properly use the backspace key in the page/find text box, but the delete key has no effect instead.

**Comment by GitHubRulesOK** [comment]
closing as duplicate of ['Delete' is not working in search field](https://github.com/sumatrapdfreader/sumatrapdf/issues/2321#)
#2321
@kjk closed this in https://github.com/sumatrapdfreader/sumatrapdf/commit/2f9f1ef3017d516afd50579bdefb9f6b6ef1ca47
