### ISSUE TITLE
Supporting Word Format

### ISSUE THREAD

**Issue by lghita** [sumatrapdfreader/sumatrapdf#228]
Hello,

Maybe a new feature in the coming versions would be to support also the opening of word format documents.

**Comment by vgturtle127** [comment]
Why not use LibreOffice or OpenOffice for that?

**Comment by SumatraPeter** [comment]
You mean the old proprietary closed DOC format (still only partially described), or the newer DOCX ([Office Open XML](https://en.wikipedia.org/wiki/Office_Open_XML)) format? In either case frankly I don't see this being implemented, but of course I'm not the program developer.

**Comment by vgturtle127** [comment]
I don't know, why not use LibreOffice or OpenOffice?

**Comment by GitHubRulesOK** [comment]
@kjk 
I think given the very large number of multiple variant formats of .doc .docx .dot .dotx .odf .odt .rtf .wps etc. which would require yet another engine or two.
This "feature request" most likely falls into a "won't fix" category

**Comment by SumatraPeter** [comment]
The main modern standards to be implemented are ISO/IEC 26300 (Open Document Format) and ISO/IEC 29500 (Office Open XML), but as Sumatra is a PDF viewer first and foremost (with secondary limited support for viewing certain ebook formats), we know realistically this is never going to happen unless MuPDF itself one day decides to support ODF and OOXML.

**Comment by kjk** [comment]
Yeah, no plans to add this.
