### ISSUE TITLE
error in bookmarks; 

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#2280]
wrong a page position when I choose bookmark that need to me.

![image](https://user-images.githubusercontent.com/11432724/148461392-5c5ec3fb-cc06-4705-984c-91147dfad898.png)
![image](https://user-images.githubusercontent.com/11432724/148461567-5b616763-36a6-4877-be1c-72cbfa7f2a16.png)

**Comment by GitHubRulesOK** [comment]
common issue that retro fitted bookmarks may be seen as bottom of a full page, thus in continuous mode you will correctly see the page after, but in single page mode they will show that page.
NO SAMPLE, no can tell if that's the cause or if its a badly bookmarked pirate copy.

**Comment by Aliaksandr3by** [comment]
this is the Michael Swan_&_Catherine Walter-Oxford_English_Grammar_Course_Basic_2016(2021OCR) from the internet link after.

https://mega.nz/folder/01EiCRhI#cLOHWr3ydgsV3AOQF3uENQ

**Comment by GitHubRulesOK** [comment]
I tried download twice that beast of 200+ MB once as pdf once as zip both reached 100 % but crashed out MS Edge
I noted the name has OCR suggesting it is not an original file, thus suspect but have no idea if that was my problem.

I suggest you find a smaller sample from a reputable source, that behaves the same way, it will likely be an OCR page by page output that was not built with standard inpage bookmarks

**Comment by Aliaksandr3by** [comment]
Maybe PDF is broken 
I tested 20-30 another PDF and they is good working.
