### ISSUE TITLE
File used to open sumatra (via double click on explorer) not focused if it was already loaded previously

### ISSUE THREAD

**Issue by edo9300** [sumatrapdfreader/sumatrapdf#2284]
Have sumatra open with various PDF files opened, including the one we're gonna open later, but have another PDF be the currently focused one. Also have enables in the settings reopening previously open files on restart. Close sumatra by having it open the previous PDF. Sumatra opens, reloads the previously open documents, but doesn't focus the file it was opened with (behaviour that is to be expected), instead the focused document will be the one that was focused before closing sumatra.

**Comment by GitHubRulesOK** [comment]
There have been different behaviors over time with different settings
 so please confirm what version , and note it should be the **current pre-release** so as to be changed 

With what settings for reuseinstance = are active at time of opening.

**Comment by edo9300** [comment]
> There have been different behaviors over time with different settings so please confirm what version , and note it should be the **current pre-release** so as to be changed
> 
> With what settings for reuseinstance = are active at time of opening.

Sorry for missing the version, i'm on the latest pre release version, 3.4.14242 64 bit
The ``ReuseInstance`` option is set to false

**Comment by GitHubRulesOK** [comment]
@edo9300 Thanks
Agreed there is no difference whichever way Reuseinstance is set in current version
Previously the reason for that setting was to not open a second copy on recall
and in 3.1.2 focus does shift to the recalled file as required by LaTeX users

@kjk there does seem to be a shift in recent 3.4 pre-rel behavior from that desired for setting focus to a recalled file in reopening current session. I suspect when some refactoring of session history was improved.

**Comment by kjk** [comment]
broken by https://github.com/sumatrapdfreader/sumatrapdf/commit/79ee16baac2cde162b9c68e042b8b91b1ca50e9a#diff-59283385fe3a037ff054b0ac330423244227acf1060bfdaaf8f3ca943dfbfbabR952

**Comment by kjk** [comment]
For future reference, a repro:
* open multiple files, including `foo.pdf`
* ensure a tab different than `foo.pdf` is selected`
* close sumatra
* run `SumatraPDF.exe foo.pdf`

This is a case of restoring a session, we should select the tab `foo.pdf`
