### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by pakistanofficial** [sumatrapdfreader/sumatrapdf#2285]
Hi
i'm using this amazing software few last months and i found it lite and amazing.
but i faced some problem in (right click context):
create Annotation under cursor > free text
here "free text" give a box.
in this box , if  i put few lines text. text goes beyond fixed borders. due to this issue i can not see vanished text.
so, please provide control to make custom size box.
Thanks in advance.

**Comment by GitHubRulesOK** [comment]
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1694
