### ISSUE TITLE
Add a feature for more closing method

### ISSUE THREAD

**Issue by sharego** [sumatrapdfreader/sumatrapdf#2288]
Add a right menu for a opening file, to provide more closing choices, like:  closing other files,  closing the right files, close all opening files. Just like the chrome tabs.

This menu is very good for more files are opened, as `sumatrapdf` can do, but now can only close one by one.

**Comment by Nailuj1** [comment]
Closing with mouse-wheel click is kind of annoying cause you first have to click on the specific tab, then you are able with another click to close it. So if you wanna close some pdfs you have to click a lot ;)

I think a solution would be really simple cause the under-mouse-tab is already highlighted.
#2471

**Comment by kjk** [comment]
In pre-release builds there's now context menu on tabs with "Close Other" and "Close All But Tjhis"
