### ISSUE TITLE
Launching sumatra re-opens files

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2289]
Reported via e-mail, not verified:

1- open SumatraPDF
2- from the list open a PDF file
3- hit CTRL+SHIFT+N to open another instance of the current file
4- now from the start menu, open the SumatraPDF again

Now instead of opening the main program to choose which PDF file you want to read, the same PDF file that was opened in stage 2 appears again not for once, but for twice. Now you have 4 instances of the same PDF. If you open SumatraPDF again, you'll get another 2, another 2 etc. Unless you close some of them, then opening SumatraPDF from the start menu works as it should (you'll see a list of pinned files etc.).

**Comment by GitHubRulesOK** [comment]
I think this is related to https://github.com/sumatrapdfreader/sumatrapdf/issues/2284 ?

**Comment by kjk** [comment]
Tried to repro but couldn't. Maybe fixed by recent fixes or maybe I don't understand repro steps.
