### ISSUE TITLE
Suggestion about Printing

### ISSUE THREAD

**Issue by xinsheng** [sumatrapdfreader/sumatrapdf#229]
For now, Sumatrapdf printing use one whole BMP paint to printer hdc by 'StretchBlt' API.
Here have problem, because the 'StretchBlt' API may return failed, so we have continue shrink until the API return successful. But when shrink too much, the result of printing may so bad(a1.jpg).

So i want fix this problem by Split the bmp image to blocks(maybe 1000x1000),and paint one by one block.
The sketch like this:sketch.jpg

The code a2.jpg is copy one block from the whole bmp.
The code a3.jpg is Printing main function.

I compile the code on my machine, and the printing result is good, printing speed is not bad, slower 1 sec per page.

Then i have several questions:
1,Does the method good?
2,My testing is the 1500x1500 is faster than 1000x1000.So the split of blocks more less, the printing more fast.
How can i find the max block size of the 'StretchBlt' API support? Can i get the size by GetDeviceCaps function?

Attaches:http://pan.baidu.com/s/1i3CfBVZ

**Comment by kjk** [comment]
That link is no longer valid.
