### ISSUE TITLE
Cover page  / 1st page in epubs not accessible when 'View' set to 'Facing'

### ISSUE THREAD

**Issue by danielmmmm** [sumatrapdfreader/sumatrapdf#2298]
**How to reproduce:**
**1)** Load an epub (e.g. Pride & Prejudice from Project Gutenberg [https://www.gutenberg.org/ebooks/1342](https://www.gutenberg.org/ebooks/1342) ).
**2)** Switch View to Facing (Ctrl+7)
**3)** Click on the first Bookmark 'Pride and Prejudice' (the page indicator says page 2 of ...)
**4)** Try to reach the cover page (left arrow, mouse wheel, left key)

**What I expect to happen:**
SumatraPDF should navigate to the cover page and show pages 1 & 2 next to each other.

**What actually happens**
SumatraPDF will not show the cover page and remain on page 2 of ...

The only way to reach the first page is to switch to single page view.

**Comment by GitHubRulesOK** [comment]
Its not possible to show that old mode in Current release for ePub
So moving Forwards this is the current support for Facing similar tos before with the Standard Zoom/Search interface

![image](https://user-images.githubusercontent.com/12754913/151668630-699f4942-4a3f-4cf9-abaa-7da65000dccc.png)
