### ISSUE TITLE
Color key masking broken (DeviceGray + BitsPerComponent 1 + Mask)

### ISSUE THREAD

**Issue by labdev42** [sumatrapdfreader/sumatrapdf#2299]
From the PDF specification, section 8.9.6.4, "Colour Key Masking":

> In PDF 1.3, the `Mask` entry in an image dictionary may be an array specifying a range of colours to be masked out. Samples in the image that fall within this range shall not be painted, allowing the existing background to show through.

This is currently not working in SumatraPDF 3.3.3 64-bit on Windows, at least for bitonal images using the `DeviceGray` color space.

The attached [sample file](https://github.com/sumatrapdfreader/sumatrapdf/files/7964423/devicegray-1bpc-mask.pdf) contains an image with the text "XYZ", and a line which runs under the image. The line should be visible under the image and under the letters, since the color white has been masked, but instead the line stops at the edges of the image.

Relevant image object from the sample file:

```
6 0 obj
<<
/Length 1920
/Type /XObject
/Subtype /Image
/Filter /ASCIIHexDecode
/BitsPerComponent 1
/Width 90
/Height 80
/ColorSpace /DeviceGray
/Mask [1 1]
>>
stream
FFFFFFFFFF<snip>FFFFFFFFFFFC0
endstream
endobj
```

**Comment by kjk** [comment]
Reported to mupdf as https://bugs.ghostscript.com/show_bug.cgi?id=704869

**Comment by DLTech21** [comment]
The attached [sample file](https://github.com/DLTech21/mupdf/blob/23/111.pdf) contains an image with the 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/2238211/2ebd9ffa-bae5-4f6b-a12e-6ddcfb77036c)

**Comment by GitHubRulesOK** [comment]
@DLTech21 
Reader says the signatures are broken and another editor agrees they need removal and replace.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/57ad44eb-21e9-4e1a-a1ea-d7d5401b78c6)
