### ISSUE TITLE
Could not compile with VS 2015 RC

### ISSUE THREAD

**Issue by wmjordan** [sumatrapdfreader/sumatrapdf#231]
VS 2015 threw the following error.
How to fix it?
Did I miss something on my computer?
Previously the project could be compiled with VS 2008. But recently it was impossible either.

1>  Trans_sumatra_txt.cpp
1>c:\program files (x86)\windows kits\8.1\include\um\GdiplusRegion.h(506): error C2220: warning as error - object file not generated
1>c:\program files (x86)\windows kits\8.1\include\um\GdiplusRegion.h(506): warning C4458: the declaration of "nativeRegion" had hidden class member
1>  c:\program files (x86)\windows kits\8.1\include\um\GdiplusRegion.h(506): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings

**Comment by kjk** [comment]
At this moment the only supported compiler is VS 2013. I don't have the time at the moment to look into 2015 compilation.
This is also a dup of #201
