### ISSUE TITLE
"Remember Opened Files" option no longer works

### ISSUE THREAD

**Issue by JustinWebDev** [sumatrapdfreader/sumatrapdf#2311]
"Remember Opened Files" option no longer works
v3.3.3 x64, Win 10 v21H2

Launch SumatraPDF, open some PDFs
Close SumatraPDF
Launch SumatraPDF, no files are open

**Comment by kjk** [comment]
It does work.

There must be something specific to your setup but there's not enough information to even make a guess.

**Comment by JustinWebDev** [comment]
What information could I provide to help diagnose?

**Comment by GitHubRulesOK** [comment]
@JustinWebDev 
first it could be a bad settings file or entry so in advanced settings  backup your current file once (control + S and using "save as" also some easy to remember name.txt  then save difference 
in sumatra just in case its then cleared check **BOTH** remember settings are on in options (bottom of the two text groups) 

![image](https://user-images.githubusercontent.com/12754913/152614668-b487e7af-5f1f-4eb3-b8f3-4dad8746a09c.png)

open two files in tabs and without closing either tab use the red X top right then open sumatraPDF two tabs should be visible .

**Comment by JustinWebDev** [comment]
It is working.  Thank you.
Why a minimum of two files have to be open for this feature to work?

Is there a way to get to the pinned/frequently read w/o closing all the open files?  I can't find a way after a file is open.

**Comment by GitHubRulesOK** [comment]
There have been some recent canges that mean that you can have two windows ( one tab each)
 and they will be restored if closed with CTRL+Q (File Exit) but may not when using the fast exit for each window :-)

HOWEVER if closed one by one the last one closed has only one tab active thus does not count as a ***session*** so you need to open that file alone ! or select from front page etc.

**Comment by JustinWebDev** [comment]
Thanks.
