### ISSUE TITLE
Incorrect display of bullet points, random square appearing in document title

### ISSUE THREAD

**Issue by dlebedinsky** [sumatrapdfreader/sumatrapdf#2312]
I compiled this PDF using groff. It displays correctly in my web browser, but in Sumatra, part of the title is obscured by a square-like character, and the bullet points are replaced by the square character.
[groff.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8000813/groff.pdf)

**Comment by GitHubRulesOK** [comment]
Looks good to me in 3.3, 3.3.3 and 3.4 pre-release

![image](https://user-images.githubusercontent.com/12754913/152530224-2db485fe-0063-42d5-be81-a2f08fc35606.png)

However the fonts are Type1 so I suspect its an `ff` ligature problem as some users have with other 3.3.# Please try https://www.sumatrapdfreader.org/prerelease and if thats good for you, then please close this as a duplicate now fixed.

**Comment by kjk** [comment]
Works for me on win11 and pre-releaes
