### ISSUE TITLE
Feature Request: change Save As and create Save shortcuts

### ISSUE THREAD

**Issue by mrrezaie** [sumatrapdfreader/sumatrapdf#2317]
Hi,

Thanks for developing SumatraPDF. It is extremely lightweight and what I was looking for.

It would be great if you set `Ctrl+S` to `Save Annotations to Existing PDF`,
and set `Ctrl+Shift+S` to `Save As...`.

By these changes, it is more convenient and user-friendly to work with annotations (Ctrl+A (or a), Ctrl+S).

All the best,
MrR

**Comment by kjk** [comment]
Changing the meaning of existing shortcuts is a non-starter. People are already used to current shortcuts and will be confused.

**Comment by mrrezaie** [comment]
And what about creating a shortcut for Save Annotations to Existing PDF?

**Comment by GitHubRulesOK** [comment]
@mrrezaie 
traditionally experimental shortcuts like annotation were not documented or translated or added to menu until release, ok there are always hiccups :-) but has been the "norm"

**Comment by GitHubRulesOK** [comment]
@mrrezaie 
The current :-) "Shortcut" is context key + up arrow key + enter

**Comment by mrrezaie** [comment]
For the sake of ease, I suggest adding `s` shortcut for that.

**Comment by GitHubRulesOK** [comment]
Sadly <kbd>≣ CONTEXT </kbd>+<kbd>S</kbd> is already set as (toggle) Show Scrollbars as an in page context.

However personally recommend DO NOT keep saving annotation as it bloats the file by adding a fresh index each save just do it once an hour or simply file close and save annotation with one set of extra overheads and no embaracing deletes..

**Comment by mrrezaie** [comment]
Ok, thank for your reply.

**Comment by kucukaslan** [comment]
> Hi,
> 
> Thanks for developing SumatraPDF. It is extremely lightweight and what I was looking for.
> 
> It would be great if you set `Ctrl+S` to `Save Annotations to Existing PDF`, and set `Ctrl+Shift+S` to `Save As...`.
> 
> By these changes, it is more convenient and user-friendly to work with annotations (Ctrl+A (or a), Ctrl+S).
> 
> All the best, MrR

I aggree that this behaviour is different from the usual editors. As a solution I customized the shortcut by adding following to the settings file:
```python
Shortcuts [
	[
		Cmd = CmdSaveAnnotations
		Key = Ctrl + S
	]
]
```
