### ISSUE TITLE
Add Toolbar Buttons to improve tablet/touch-screen user experience

### ISSUE THREAD

**Issue by karthikgopalakrishnan** [sumatrapdfreader/sumatrapdf#2318]
The following features that are easily available on systems with keyboard/mouse are missing on tablet/touch-screen.

- Show/Hide Bookmarks Bar via F12.

- Go Forward/Backward in history via ALT+RIGHT/ALT+LEFT.

These can be easily resolved by adding new buttons to the Toolbar.

**Comment by kjk** [comment]
No plans to add more toolbar buttons.
