### ISSUE TITLE
Tab and Menubar (at the same time)

### ISSUE THREAD

**Issue by Gugus99** [sumatrapdfreader/sumatrapdf#232]
Dear developers

I would like to request a feature that allows for tabs while still displaying the traditional menu bar.

Call me an antiquated, stubborn old person, yet I find it cumbersome to always click on the hamburger (three bars) icon, when I need to access a menu item.

Best regards & thanks for your great product which I appreciate very much on my old computer.
Max

**Comment by kjk** [comment]
We don't have plans to do that.

**Comment by mklhmnn** [comment]
+1 for a classic menu bar
