### ISSUE TITLE
highlighter feature.....

### ISSUE THREAD

**Issue by 4evermaat** [sumatrapdfreader/sumatrapdf#2329]
I would like ability to highlight parts of a pdf.  This could be only for the current session or saved across sessions per pdf.   

And I can customize the color/opacity of the highlighter....and of course you would have a couple of default colors pre-loaded.

**Comment by GitHubRulesOK** [comment]
@4evermaat 
Read 3.3 notes https://www.sumatrapdfreader.org/docs/Editing-annotations
Please use the 3.4 pre-release as better updates to those features https://www.sumatrapdfreader.org/prerelease
Please read the forum discussions or closed issues for any questions about latest additions to advanced settings.txt

**Comment by 4evermaat** [comment]
the customize color of the highlighter could be a bit more user-friendly as a tiny popup palette near where the highlighter will be used.  Having to go to advanced options to change colors is a bit unintuitive.

I assume multiple colors can be used in the same document?

In fact, there could be an annotator floating window that would contain different options.  This is more intuitive to a user that is trying to do several annotations and wishes to avoid context menu.

also, do you prefer this in discussion or issues section of github?

**Comment by GitHubRulesOK** [comment]
A small 7 or so colour popup is useful I built an AHK one for the older all formats [highlightjumper](https://github.com/nod5/HighlightJump/issues/8#issuecomment-594047229) but have not tried adapting for new pdf only as easy enough for my personal using editors for one colour choice or a modify at a time per file.

Not the dev so cant say yet whats prefered as discussions are new
and I cant change naming etc once migrated which I could do as moderator on discourse.
