### ISSUE TITLE
unkonventionell solution for nightmode/lightmode/...etc.

### ISSUE THREAD

**Issue by daaviiiiiid** [sumatrapdfreader/sumatrapdf#2330]
Based on the post from GitHubRulesOK (https://forum.sumatrapdfreader.org/t/how-to-customise-colors-for-light-dark-theme-day-night-mode/258/44) you can run a batch-file witch ExternalViewers.

The idea is to use fart.exe (http://fart-it.sourceforge.net) in a batch file to change the color values. After the change, SumatraPDF-settings-dark.txt must be opened and saved. Autohotkey (https://www.autohotkey.com) can be used for this purpose. 

For darkmode you must safe following code in dark.bat:
----------------------------------
@echo off
"C:\Users\USERNAME\Documents\Sumatra_mode\fart.exe" -i "C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt" #80fff200 #1E1E1E
"C:\Users\USERNAME\Documents\Sumatra_mode\fart.exe" -i "C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt" #000000 #E5E5D5
"C:\Users\USERNAME\Documents\Sumatra_mode\fart.exe" -i "C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt" #ffffff #2D2D30

Start ""  "C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt"
timeout /t 0 /nobreak >nul

"C:\Users\USERNAME\Documents\Sumatra_mode\safe.ahk"

exit
-------------------------------

Same for the lightmode in light.bat:
-------------------------------
@echo off
"C:\Users\USERNAME\Documents\Sumatra_mode\fart.exe" -i "C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt" #1E1E1E #80fff200
"C:\Users\USERNAME\Documents\Sumatra_mode\fart.exe" -i "C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt" #E5E5D5 #000000
"C:\Users\USERNAME\Documents\Sumatra_mode\fart.exe" -i "C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt" #2D2D30 #ffffff

Start ""  "C:\Users\USERNAME\AppData\Local\SumatraPDF\SumatraPDF-settings.txt"
timeout /t 0 /nobreak >nul

"C:\Users\USERNAME\Documents\Sumatra_mode\safe.ahk"

exit
-------------------------------

The safe.ahk file:
-------------------------------
sleep 100
send ^s
send !{F4}
ExitApp 
-------------------------------

Finally the SumatraPDF-settings.txt file has to be modified:
-------------------------------
ExternalViewers [
	[
		CommandLine = "C:\Users\USERNAME\Documents\Sumatra_mode\light.bat"
		Name = Lightmode
	]
	[
		CommandLine = "C:\Users\USERNAME\Documents\Sumatra_mode\dark.bat"
		Name = Darkmode
	]
]
-------------------------------
![1](https://user-images.githubusercontent.com/86719741/152952208-52628342-e725-4ef0-ba26-1dbd4ed5369d.png)
![2](https://user-images.githubusercontent.com/86719741/152952253-bb2cea4d-2df3-4628-93e2-fcde839932dd.png)

**Comment by GitHubRulesOK** [comment]
This is not an issue it was an old workaround 
which in effect is replaced in current by SIMPLY pressing <kbd>SHIFT</kbd><kbd>I</kbd>
