### ISSUE TITLE
Changing the UI collors without affecting images inside the book

### ISSUE THREAD

**Issue by Pandaa-P** [sumatrapdfreader/sumatrapdf#2337]
Sumatra v3.4.14255 64bit pre-release (as well the stable version)

I tinkered with the setting and searched online for a solution without success.
I hope this feature to be implemented in future versions, while it supposed to only affecting text and the background of it, sumatrapdf as of now can't change the UI colors without affecting everything.

**Comment by GitHubRulesOK** [comment]
That setting is for reversing colours such as blue&white prints can be made white&black or image transparencies inverted or change colours between any two end points, I consider that whilst plain text can be inverted, it is a bug  that plain images can not be inverted.

It is not for setting a "Mode" or for theming it is the body colour range, sometimes the colours were not affected in earlier versions interface but the correct way to swap background and foreground colours range is using <kbd>shift</kbd><kbd>I</kbd> so best if those values now be ignored.

Closing as related to [Seperate theming from image inverting](https://github.com/sumatrapdfreader/sumatrapdf/issues/1275) and in efect duplicated by https://github.com/sumatrapdfreader/sumatrapdf/issues/743
