### ISSUE TITLE
Website outdated

### ISSUE THREAD

**Issue by Wolf68k** [sumatrapdfreader/sumatrapdf#2338]
When I try to go to your website I get this:

Your connection is not secure

An error occurred during a connection to www.sumatrapdfreader.org.

www.sumatrapdfreader.org uses security technology that is outdated and vulnerable to attack. An attacker could easily reveal information which you thought to be safe. The website administrator will need to fix the server first before you can visit the site.

Error code: NS_ERROR_NET_INADEQUATE_SECURITY

**Comment by GitHubRulesOK** [comment]
Perhaps check it is not a firefox variant report. https://support.mozilla.org/en-US/questions/1242628

**Comment by kjk** [comment]
Can't reproduce this with latest version of Chrome or Firefox on Windows 11.

Speaking more broadly, the website is hosted on Cloudflare, which also hosts millions of other websites. It's unlikely Cloudflare is broken.

Also, if it was happening to many people we would be getting lots of reports like this. Yours is second so far.

It's more likely it's your browser or your network (browsers can be configured to connect through a proxy and that proxy might be the issue).
