### ISSUE TITLE
Don’t silently discard unknown paths

### ISSUE THREAD

**Issue by bradrn** [sumatrapdfreader/sumatrapdf#2339]
At the moment, if SumatraPDF encounters an unknown `FilePath` in its `SessionData` (in `SumatraPDF-settings.txt`), it silently discards the relevant tab. This behaviour is understandable but extremely annoying for some workflows. For instance, I have numerous PDFs open in SumatraPDF currently, many of which are stored on a local NAS; if I take my laptop anywhere else, I have to be extremely careful to avoid using SumatraPDF, lest all these tabs be forgotten.

It would therefore be useful to change SumatraPDF’s behaviour when such a tab is encountered. I suggest that, instead of the tab being discarded, it should remain in place with its state being maintained as in `SumatraPDF-settings.txt`; if the user attempts to open the tab, its content is replaced by an error message. That way, when the PDF becomes available again, the user can simply keep reading from where they left off.

**Comment by bradrn** [comment]
> Using the -appdata switch pointing to a sub folder for "AWAY" usage, would avoid the deletion of "HOME" setttings and if at first the "Home" set is copied to the folder would allow for shared history. with the bonus of "Away" files not clogging the last "Home" set, in return.

Clever! Alas, this still has two problems:

- SumatraPDF is on my taskbar; I often press it accidentally — especially when away, where I’m often using the touchscreen — at which point all my tabs get deleted
- I usually *do* want to have access to ‘away’ files at home

Still, I’ll set this up if this issue doesn’t have any quick fix.

> The request is basically to revert to prior behaviour where missing files were errror messaged but many users want a simple means to dismiss/cull historic entries

Oh, I wasn’t aware of this. Why not add a setting to toggle between the two behaviours then? After all, SumatraPDF has settings for so many other things…

**Comment by GitHubRulesOK** [comment]
Sorry am on win7x32, but in principle should not matter which version up to Windos 12x128 with luck and a fair wind.
![image](https://user-images.githubusercontent.com/12754913/153714333-7ba7ac33-004f-4cc4-881f-a9102b1b4000.png)
![image](https://user-images.githubusercontent.com/12754913/153714486-366d2ab9-b470-4d04-8440-42624c118db9.png)


In the properties of the command icon you should be able to add switches. so my MSEdge starts incognito or SumatraPDF can at the end include a choice of command line settings, or even a batch.cmd to do several tasks before start SumatraPDF

**Comment by bradrn** [comment]
> In the properties of the command icon you should be able to add switches. so my MSEdge starts incognito or SumatraPDF can at the end include a choice of command line settings, or even a batch.cmd to do several tasks before start SumatraPDF

Ah yes, I am indeed aware of this, and am even currently using this technique myself. The problem is that, as I mentioned, even if I add a new shortcut for ‘away’ SumatraPDF, I still will often need to access ‘home’ SumatraPDF, so this doesn’t fully solve this issue for me.

**Comment by GitHubRulesOK** [comment]
I started with the words workaround as each case is different and your, not alone with this long term problem of temporary drive allocations. But as to when it changed is still a mystery since rereading this report https://github.com/sumatrapdfreader/sumatrapdf/issues/2219# the OP said 3.3.3 was less of an issue for removable drives, so perhaps its a combination of two changes in behaviours with network drives.

Personally I try to use set mapped drive names rather than \\server\share (easier said than done) so T:\ is \\Toshiba\AtHome whilst S:\ may be \\atClient\Share still does not stop ?:\ but often reduced past issues by remapping between them when required.

**Comment by kjk** [comment]
This won't be implemented for 2 reasons.

1. Way too much effort
2. Such behavior would be annoying for a more common case of a file being deleted

**Comment by bradrn** [comment]
> Way too much effort

But I thought @GitHubRulesOK said this would be a reversion?

> Such behavior would be annoying for a more common case of a file being deleted

And the existing behaviour is annoying for my case of a file not being deleted. Actually, it goes well past annoying: in case I wasn’t clear earlier, this is literally **preventing me from using SumatraPDF** for a good portion of each day.

**Comment by GitHubRulesOK** [comment]
@bradrn I thought the problem was recent, but you said that reverting did not work.
So did not suggest it was possible to reverse since sumatraPDF moves forwards and missing drives are historically not easy to allow for. Similar problems can occur with syncronised files thus I would not recommend using with say OneDrive or similar.

If you use other portable apps they usually have one history per location. SumatraPDF is fairly unique in trying to remember all current open pages on transportation. Other apps need to do that by using more complex methods.

**Comment by bradrn** [comment]
> I thought the problem was recent, but you said that reverting did not work.

I never tried reverting anything. You said that ‘The auto-culling is, as far as I know, only in 3.4 pre-release’; all I said was that auto-culling is present in at least v3.3.3, which I have been using.

> Similar problems can occur with syncronised files thus I would not recommend using with say OneDrive or similar.

How is this not an argument for fixing this bug? Numerous people use OneDrive etc. to manage their documents — it feels counterproductive to declare that they just can’t use SumatraPDF.

> If you use other portable apps they usually have one history per location.

I don’t understand what you mean by this. For comparison, I also use Firefox, which remembers my tabs on close. When a website becomes unavailable, or the Internet is down, Firefox does not silently delete any inaccessible tabs; it simply keeps them as is with an error message.

**Comment by bradrn** [comment]
The issue is getting worse. For various reasons I am currently unable to access my NAS even at home; this means I am completely unable to use SumatraPDF at all, because even opening the application would delete nearly all my open tabs. For the moment I am compensating by using Acrobat Reader instead, although it really is unsatisfactory compared to SumatraPDF. (Besides, sooner or later muscle memory *will* take over, and I’ll accidentally open SumatraPDF and get all my tabs deleted anyway. Ah well, at least I have backups.)

**Comment by bradrn** [comment]
OK, so I’ve been looking through the code, and I think I see why this issue is so difficult to fix. It seems pretty easy to just *not discard open paths* — but it’s much more difficult to prevent SumatraPDF from crashing when it tries to open a nonexistent file. (i.e. https://github.com/sumatrapdfreader/sumatrapdf/issues/1674; in fact, it looks like this issue was introduced as a quick fix for that one.) Fundamentally, this is difficult because rendering is split over ~10 different rendering engines, each of which reads from the file in numerous places.

I can think of one possible solution: add a new engine type for nonexistent files, and create an instance of that engine whenever we run into a case of this. Alternately, we might be able to do something similar to what SumatraPDF does when it loses access to a file it hasn’t fully read yet, though I suspect that might be more difficult.

**Comment by bradrn** [comment]
> when using a full install then removable drive causes the drive assignment removal to become ?: in the settings file list until the stored data can be reapplied to the new drive assignment e.g. unplug g: and plug back it may become f: thus no problem in reapply in main file list.
> 
> The prime problem is on close session the missing file cannot be a valid tab so the session data for g:drive is discarded but the file preferences are preserved for reuse with a new f:drive tab

Isn’t this handled by a different part of the code? Namely:

https://github.com/sumatrapdfreader/sumatrapdf/blob/e226491c63d9dff7b3fc17f27f0a15eae920aa21/src/SumatraPDF.cpp#L1566-L1577

Whereas my problem involves the lines following that section:

https://github.com/sumatrapdfreader/sumatrapdf/blob/e226491c63d9dff7b3fc17f27f0a15eae920aa21/src/SumatraPDF.cpp#L1579-L1598

> if a tab is not accessible it cannot be kept as a tab 

I disagree. For one thing, SumatraPDF already keeps inaccessible tabs in some cases: in particular, if a large file on a remote drive becomes inaccessible before SumatraPDF can render the whole thing, the tab is not autoclosed, but rather kept open with an error message (‘Couldn't render the page’). I am proposing something similar.

> thus exporting tabs for reuse at each location may be an answer

Come to think about it, this is actually a really interesting idea. I’m thinking there’s no reason to stop there — we could even go further: perhaps SumatraPDF could eventually maintain whole sets of tabs, and allow the user to switch between them at will. (So e.g. I could have one tabset for my physics units, one for my chemistry units, one for home use holding remote files, and so on.) As far as I’m aware no other PDF reader allows anything like this, and I suspect it wouldn’t be overly difficult to implement. This wouldn’t actually resolve the issue, mind you, but it would be a mostly acceptable workaround from a UX perspective.

> somewhere i showed on old forum how to backup tabs. perhaps in https://forum.sumatrapdfreader.org/t/reopen-closed-tab/1756

I am already backing up my tabs (due to precisely this issue), but the process is painful enough that I’d rather avoid using the backups as much as possible. Besides, users shouldn’t be required to manually maintain backups just to avoid their tabs being deleted automatically.

(I note that one of the posts in your link mentions using git for backups. I suspect this might provide an temporary duct-tape fix in the short term, until this issue is resolved.)

**Comment by GitHubRulesOK** [comment]
I don't disagree with your observations mine are limited to my mileage, and now don't get out much.
The idea of my workaround was it is a menu / hot keys temporary user based workaround that's quick, and yes dirty.

**Comment by bradrn** [comment]
>  don't disagree with your observations, mine are limited to my mileage, and now don't get out much.

Sorry, I’m not quite sure what you’re saying here. Could you elaborate?

(Also, if we’re discussing this issue again, could I get it re-opened please?)

**Comment by GitHubRulesOK** [comment]
> Sorry, I’m not quite sure what you’re saying here. Could you elaborate?
I agree your observations are reasonable, but that does not change the outcome, there is one part time developer (not me) who does not have an assistant programmer to experiment with peripheral issues, I normally reported / raise user issues often based on my heavy usage at differing clients, but since Covid hit there is/was zero other sites in order to compare.

**Comment by bradrn** [comment]
> there is one part time developer (not me) who does not have an assistant programmer to experiment with peripheral issues

In that case I am happy to try fix this myself — I think I now have a pretty good idea of how I would go about implementing this.

**Comment by jddcef** [comment]
> In that case I am happy to try fix this myself — I think I now have a pretty good idea of how I would go about implementing this.
@bradrn  how did you manage?
I got burnt by my trust in the tabs being open, then I didn't have my external drive plugged in and Sumatra opened and I lost all the documents I had open which took a long time to find out of a large set.

I agree with you, Sumatra must not close tabs of "missing files", rather just have them display some error state with two big buttons in the middle: ["Reload/refresh"] ["close tab"] and maybe also ["open containing path.."].

Let the user decide when to close a tab that he has opened at some time in the past. 
Please reopen this issue.

**Comment by bradrn** [comment]
> how did you manage?

Alas, I never did get around to trying this… and now I’ve switched to Linux, so for me it’s a moot point in any case.

**Comment by jddcef** [comment]
@GitHubRulesOK - could the session file at least mark the files that were recently "opened but missing"? So that I don't have to keep a back of the session file just for this common case?

**Comment by GitHubRulesOK** [comment]
@jddcef 
I am not a developer simply an advanced user, so have no control over any code changes.
My experience is SessionData [ can only hold what's currently found not what fails to load

However there seems to be a shortage in whats stored when a file goes missing

@kjk 
When a file was in a previous session and is not found on re-open its not found in the file history section where I would expect it to be but showing
```
	[
		FilePath = C:\Users\user\Documents\MissingFile.PDF
		Favorites [
		]
		IsPinned = false
		IsMissing = true
		OpenCount = 3
		UseDefaultState = true
	]
```
