### ISSUE TITLE
blow zoom up

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#2354]
when I am using a zoom (ctrl+scroll up/down) in program, page size is "jumps".

f.e.: 50% ... "fit page" .. 70%
but the "fit page" is bigger then 70%.

![image](https://user-images.githubusercontent.com/11432724/154614008-4adcadac-736e-4eed-890c-b2abebbfe6e1.png)

**Comment by kjk** [comment]
The value of `fit page` depends on the size of window. 
It's not practical to re-calculate it after each change of window size just for this zoom functionaliy.

**Comment by kjk** [comment]
You can set `ZoomIncrement` setting to non-zero fixed percent increment (e.g. 10 is 10%) for zoom in / zoom out instead of default behavior

See https://www.sumatrapdfreader.org/settings/settings
