### ISSUE TITLE
Scroll Size And Smooth Scrolling

### ISSUE THREAD

**Issue by muser0** [sumatrapdfreader/sumatrapdf#2358]
**- Add smooth scrolling and scroll size feature in options menu.**

**Comment by kjk** [comment]
In pre-release (https://www.sumatrapdfreader.org/prerelease) you can enable smooth scrolling experiment as described in https://www.sumatrapdfreader.org/settings/settings by setting SmoothScrolling = true.

I'm not sure if that's an improvement so please test and comment.

**Comment by alen098** [comment]
It works fine sometimes and at times its bumpy. There is still room for improvement.

I used [cdisplayex ](https://www.cdisplayex.com/) for reference and the smooth scrolling feature in pre-release of sumatrapdf lacks in comparison.

(Values used in [cdisplayex](https://www.cdisplayex.com/): Scroll Size: 50 and Smooth Scrolling: On).
