### ISSUE TITLE
New Feature Support for SumatraPDF: AZW Formats

### ISSUE THREAD

**Issue by Freddo98** [sumatrapdfreader/sumatrapdf#236]
It would be great if Sumatra PDF Reader would support AZW formats.  
The formats are very similar to MOBI file. In fact if I change the suffix from azw or azw3 to mobi Sumatra reads the files just fine.
Is this format going to be supported in future updates?

**Comment by DavorV** [comment]
I'm reading both azw and azw3 files in Sumatra by simply renaming the suffix to .mobi
Azw files without DRM are equal to .mobi and you can read them as such. With DRM you can't read them anyway, so this feature may be implemented right away - just treat all azw files as mobi, and if you can't open them, they are either broken or DRM-ed.
