### ISSUE TITLE
Rendering issues in sumatra

### ISSUE THREAD

**Issue by Yuven91** [sumatrapdfreader/sumatrapdf#2365]
There is an issue where some colors are not shown correctly in certain pdfs. this creates issues with readability.

Sumatra
![unknown](https://user-images.githubusercontent.com/22319152/154945773-fc52fee7-2db8-49b2-8d8d-69d95cf8cb18.png) 
Adobe
![unknown](https://user-images.githubusercontent.com/22319152/154945780-10cc5d2d-7321-4e56-8a94-cd03e3b44ced.png)

**Comment by GitHubRulesOK** [comment]
Please check if it is present in current [pre-release](https://www.sumatrapdfreader.org/prerelease) portable will do, and if still a problem the developer cant do anything without a sample.

**Comment by Yuven91** [comment]
it is not present in the current pre-release! thank you. now i can ditch adobe once again! <3
