### ISSUE TITLE
Request - Associate .mobi file to SumatraPDF upon installation

### ISSUE THREAD

**Issue by petrasteri** [sumatrapdfreader/sumatrapdf#237]
I've recently learned that SumatraPDF can actually open MOBI files.  But .mobi file extension is not associated to SumatraPDF (no install option to make it the default application).  Please consider adding the association during installation (ie the option to associate it).

**Comment by petrasteri** [comment]
And .epub as well, please.

Some nice free icons can be found at https://www.iconfinder.com/basrach

**Comment by GitHubRulesOK** [comment]
@kjk key issue is superceded by https://github.com/sumatrapdfreader/sumatrapdf/issues/1248

**Comment by kjk** [comment]
Consolidating as #1248
