### ISSUE TITLE
Feature request: Annotations window embedded in main window

### ISSUE THREAD

**Issue by hudcap** [sumatrapdfreader/sumatrapdf#2379]
First, thank you for this awesome pdf reader, with an extra thank you for supporting annotations!!

I would very much like the annotations window to be part of the main window, similar to the bookmarks.
As I go through a pdf, I am constantly commenting and highlighting, and having the annotations in a separate window is just an inconvenience. I end up grouping the windows together with the new Windows 11 group feature, trying to treat them as one.

I searched both open and closed issues and was surprised not to find anyone requesting this. Either I'm using the wrong terms, or I'm the only nut who wants this... Am I missing the boat here?

Thanks!

**Comment by GitHubRulesOK** [comment]
Most users complaints have asked for the annotation control to be hidden !!
Personally I have no problem unless it is too big and asked a few times for dialogues to be reduced during development for my smaller screen the floating arrangement helps to push it to one side or behind when covering the page.

**Comment by hudcap** [comment]
I guess I'm the odd one out...
Am I crazy that I'd want a little comment box to pop up when highlighting? I'm generally highlighting something to add a comment to it.

**Comment by GitHubRulesOK** [comment]
Cant please all of the people all of the...

If you use SHIFT A the box will "pop-up" like it used to until there were many requests to keep it hidden !! 
you can then paste the highlighted text into comments manually (previously it was automatic !!)
