### ISSUE TITLE
SumaptraPDF inserts extra spacing between spans in epub ebooks when UseFixedPageUI = true is used

### ISSUE THREAD

**Issue by lvmm** [sumatrapdfreader/sumatrapdf#2382]
Suppose styles style1 and style2 are defined. The following two string should look the same but actually, there will be an extra spacing between t and ext in the second one.

```
<p class="style1"><span class="style2">text</span></p>
<p class="style1"><span class="style2">t</span><span class="style2">ext</span></p>

```
And yes, the second span in the second string is redundant but such things are surprisingly frequent in real-world ebooks.

![2022-03-01 11_25_27-The Thirteen Problems epub -  The Thirteen Problems  - SumatraPDF](https://user-images.githubusercontent.com/11752339/156132401-00a21852-b69b-4d06-bc6c-17ee4e2d845c.png)

**Comment by GitHubRulesOK** [comment]
Undefined there is no problem with rendering different spans, I took your 2 lines an injected two different ways between the heading and body as shown here both ***spans*** behave correctly but then I do not have your styles.
![image](https://user-images.githubusercontent.com/12754913/156164081-12d1b2b4-0bb0-401e-a07b-13524a59fda7.png)

**Comment by lvmm** [comment]
Ok, so my attempt to create a clean simple testcase failed. I am attaching the file [13p.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8161575/13p.zip) which has this issue with clean (apart from setting UseFixedPageUI = true) profile. Search for "'Ah!' said Joyce Lemprié re encouragingly." I just noticed that I even have to insert a space after é, otherwise the string won't be found, and yet in the html it looks like 

`<p class="description"><span class="none2">'Ah!' said Joyce Lempri</span><span class="none2">é</span><span class="none2">re encouragingly.</span></p>`

without spaces. And yet this is how it looks:

![2022-03-01 15_27_35-The Thirteen Problems epub -  The Thirteen Problems  - SumatraPDF](https://user-images.githubusercontent.com/11752339/156169116-646cdba6-2318-4a49-b306-a6502c81b5c7.png)

**Comment by GitHubRulesOK** [comment]
SumatraPDF bases ePub support on MuPDF so here is how it renders there
![image](https://user-images.githubusercontent.com/12754913/156172824-d6cb440b-0a32-4e94-943e-c1c38c35457f.png)

using Joyce Lempriére in sumatraPDF it also works the same way

![image](https://user-images.githubusercontent.com/12754913/156173231-b8302dc7-0211-490c-b916-ce560914eb34.png)

**Comment by lvmm** [comment]
Yes, this pre-release doesn't have this issue.
