### ISSUE TITLE
Text search functionality for .mobi and .epub

### ISSUE THREAD

**Issue by garegin16** [sumatrapdfreader/sumatrapdf#239]
Currently you can't search the text for matching string for neither mobi or epub files. It could be others to, I didn't check.
Any chance is can be implemented?

Thanks

**Comment by GitHubRulesOK** [comment]
The easiest way to solve this is
1) Use a second window to show the same file runing in FixedUI mode (the one that includes search) so for second window see that issue, but you will complain the pages are not reflowing to the same number negating the value of search etc etc.
2) Simply switch between modes as required . This is a LOT easier with the current pre-release and the switch to Toggle ebookUI (ON=OFF:-)
