### ISSUE TITLE
Prerelease downlad link broken

### ISSUE THREAD

**Issue by pulbitz** [sumatrapdfreader/sumatrapdf#2390]
https://www.sumatrapdfreader.org/prerelease download link broken.

When I click 64-bit portable version,

https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/prerel/14281/software/sumatrapdf/prerel/14281/SumatraPDF-prerel-64.exe

{
  "code": "not_found",
  "message": "File with such name does not exist.",
  "status": 404
}

**Comment by GitHubRulesOK** [comment]
Thanks already reported in https://github.com/sumatrapdfreader/sumatrapdf/discussions/2375
its still a problem for new users via that page **but pre-release updates are still working**

Ping @kjk looks like it happens after dl area was reassigned

**Comment by kjk** [comment]
Fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/9228277f23c5223c703d2460b57509b10cbf8eb1
