### ISSUE TITLE
[RFE] Allow user to set number of recent files in File menu

### ISSUE THREAD

**Issue by africola** [sumatrapdfreader/sumatrapdf#2392]
Apologies if this has been suggested before; searching for a related issue (open or closed) yielded nothing.

I would like to suggest a small feature. SumatraPDF displays recent files in the File menu, between "Properties" and "Exit". The number of entries in that list is currently hardcoded to 10 ([see here](https://github.com/sumatrapdfreader/sumatrapdf/blob/3a9568c05cd9029c227722da52eeca73082acc44/src/FileHistory.h#L7)); it would be great if this were user-configurable in the settings file instead.

I would personally find this very helpful, since I regularly have more than ten files (papers, slides, books etc.) open, and this causes other files to disappear from the Recent Files list --- which in turn causes regular moments of "now where was that file again, I know I had it open yesterday, if only it were still in the list".

There's also been a [forum question](https://forum.sumatrapdfreader.org/t/question-settings-display-more-than-10-books-in-menu/1401) to the same effect, so there's at least one other person out there who'd appreciate this.

Thank you very much!

**Comment by kjk** [comment]
No plans for such level of customizability
