### ISSUE TITLE
CTRL+SHIFT+RIGHT/LEFT opens only one extension files

### ISSUE THREAD

**Issue by yatoya** [sumatrapdfreader/sumatrapdf#2395]
I have mixed files in my folder. Some have an EPS and some AI extension.
The problem is Sumatra opens only EPS files using CTRL+SHIFT+RIGHT/LEFT shortcut.
It completely skips AI files even though it can display them perfectly.

**Comment by kjk** [comment]
As explained in https://github.com/sumatrapdfreader/sumatrapdf/discussions/2394 .ai is not a supported file format
