### ISSUE TITLE
Crash when closing tabs

### ISSUE THREAD

**Issue by nkmathew** [sumatrapdfreader/sumatrapdf#240]
I'm on v3.0

Trying to close any other tabs other than the current one causes the hang/crash
![First Crash](https://cloud.githubusercontent.com/assets/5522822/8685385/eb27929a-2a86-11e5-9473-1739a0b827a3.gif)

[Second case](http://i.imgur.com/21zVYL6.gif)
An attempt to close the last remaining tab causes another hang
![Second Crash](https://cloud.githubusercontent.com/assets/5522822/8685399/fff1deec-2a86-11e5-8bea-d7e1f9581020.gif)

**Comment by kjk** [comment]
What is ip address of the machine that crashes (as shown by e.g. https://www.whatismyip.com/)?

Knowing that might enable me to find the corresponding crash report.

**Comment by nkmathew** [comment]
It's not static. Looks something like this _154.122.\*.\*_

Also it doesn't crash like that when I open the three pdf files from Everything Search

**Comment by kjk** [comment]
For future reference, seems to be crash 117329
```
Ver: 3.0
Browser plugin: no
OS: Windows 8.1 build 9600 Wow64
Number Of Processors: 4
Processor: AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G 
Physical Memory: 3.45 GB
Commit Charge Limit: 6.95 GB
Memory Used: 68%
Machine: 103C_5336AN G=N L=BUS B=HP S=PRO A3008DD10B03
Lang: en GB
Graphics driver 0
  DriverDesc:         A
  DriverVersion:      13.352.1004.1009
  UserModeDriverName: aticfx64.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00BCCEA2 01:0003BEA2 sumatrapdf.exe!onUnexpected+0x2 c:\users\kkowalczyk\src\sumatrapdf30\src\crashhandler.cpp+656
Fault writing address 00000000

Registers:
EAX:00000000  EBX:02F6A930  ECX:02F5C618
EDX:00BCCEA0  ESI:02F5C850  EDI:02F5DCA0
CS:EIP:0023:00BCCEA2
SS:ESP:002B:00E4F7C4  EBP:00E4F7F8
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010246

Crashed thread:
00BCCEA2 01:0003BEA2 sumatrapdf.exe!onUnexpected+0x2 c:\users\kkowalczyk\src\sumatrapdf30\src\crashhandler.cpp+656
00B9597A 01:0000497A sumatrapdf.exe!LoadModelIntoTab+0x3a c:\users\kkowalczyk\src\sumatrapdf30\src\sumatrapdf.cpp+1605
00BC3EAD 01:00032EAD sumatrapdf.exe!TabsOnNotify+0x6d c:\users\kkowalczyk\src\sumatrapdf30\src\tabs.cpp+874
00BC2968 01:00031968 sumatrapdf.exe!TabNotification::Execute+0xd8 c:\users\kkowalczyk\src\sumatrapdf30\src\tabs.cpp+390
00BE6F49 01:00055F49 sumatrapdf.exe!uitask::WndProcTaskDispatch+0x19 c:\users\kkowalczyk\src\sumatrapdf30\src\utils\uitask.cpp+40
779A7834 01:00006834 user32.dll!CallNextHookEx+0x97
779A7A9A 01:00006A9A user32.dll!CallNextHookEx+0x2fd
779A988E 01:0000888E user32.dll!GetMessageW+0x330
779A98F1 01:000088F1 user32.dll!DispatchMessageW+0x10
00B9D13B 01:0000C13B sumatrapdf.exe!RunMessageLoop+0xeb c:\users\kkowalczyk\src\sumatrapdf30\src\sumatrapdf.cpp+4456
00BA22B9 01:000112B9 sumatrapdf.exe!WinMain+0x5f9 c:\users\kkowalczyk\src\sumatrapdf30\src\sumatrastartup.cpp+578
00C3909C 01:000A809C sumatrapdf.exe!__tmainCRTStartup+0x11a f:\dd\vctools\crt_bld\self_x86\crt\src\crt0.c+275
7778919F 01:0000919F kernel32.dll!BaseThreadInitThunk+0xe
77E4B90F 01:0005A90F ntdll.dll!RtlInitializeExceptionChain+0x8f
77E4B8DA 01:0005A8DA ntdll.dll!RtlInitializeExceptionChain+0x5a
```

**Comment by GitHubRulesOK** [comment]
@kjk 
looking at the gifs I notice in both cases given that the files tabs when opened are NOT as selected/expected
I.E. in the first case there are 2x Spanish-page tabs and in the second case 2x Japanese-page tabs
this suggests there was an OS problem calling SumatraPDF with the selected filenames
I cannot emulate that odd behaviour and suspect that since others have not raised the same issue with version 3.0 or since that it was a machine specific error at that time rather than a bug within SumatraPDF
unless you have other related crash reports I would suggest this be closed as a random "one off" event

**Comment by GitHubRulesOK** [comment]
@kjk I am guessing this issue was platform/version specific to 3.0 and has been addressed by more recent builds?
