### ISSUE TITLE
Error loading epub file

### ISSUE THREAD

**Issue by elchipsvico** [sumatrapdfreader/sumatrapdf#2419]
Hi,
I downloaded ibooks I purchased from my iphone to my PC via iTunes but can't seem to be able to open them in sumatrapdf. I was wondering if it were a fixable issue or not. I would share the file with you but the file type is not supported apparently.
Thanks in advance.

**Comment by GitHubRulesOK** [comment]
always check if the current prerelease https://www.sumatrapdfreader.org/prerelease is able to support a particular file However iPhone uses a number of protection measures that may mean those files will not work in other readers see https://apple.stackexchange.com/questions/1824/is-it-better-to-use-epub-or-mobi-files-in-ibooks

**Comment by GitHubRulesOK** [comment]
you can usually upload a file if renamed to .zip since ibooks are supposedly "application/x-ibooks+zip"

**Comment by kjk** [comment]
Those are most likely files protected with DRM.

Either way, nothing can be done without access to a sample file.
