### ISSUE TITLE
Window can no longer be resized below some minimum width anymore

### ISSUE THREAD

**Issue by sturgman** [sumatrapdfreader/sumatrapdf#2425]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/2424

<div type='discussions-op-text'>

<sup>Originally posted by **sturgman** March 17, 2022</sup>
Not sure which update changed this behavior, but I can no longer resize the SumatraPDF window below some (seemingly arbitrary) minimum width. I relied on being able to change the width of the SumatraPDF window to any width needed for a particular application. Was this change purposeful? Can it be toggled? Thanks in advance.</div>

**Comment by GitHubRulesOK** [comment]
The difference should only be about 20 pixels
![image](https://user-images.githubusercontent.com/12754913/158873942-ee5b83cd-d8b7-46d4-83ca-a65bf0939981.png)

**Comment by sturgman** [comment]
Alright. Just reinstalled 3.3.3 and everything is back to normal. Don't know what happened.
