### ISSUE TITLE
Is there any way to make the found text highlight more obvious?

### ISSUE THREAD

**Issue by LorenAmelang** [sumatrapdfreader/sumatrapdf#2426]
I have vision issues, and have Sumatra configured to full white text on black background for maximum contrast. Works great, except for search results. I can change the SelectionColor, but the background for the found text changes with it, and is always much darker than the text itself. And in complex scientific papers, the found item is typically tiny. 

Is there a way to control the found text background color separately? If it was obviously different from the rest of the background, it would stand out more. If it could be much lighter than the SelectionColor in my situation, that would be wonderful! 

Or is there a way to expand the size of the background area? If the found text was surrounded by maybe five line heights of even the dim background, it would be obvious. 

Or could I somehow trigger the left margin marker for the line with the found text? 

Otherwise, Sumatra solved my PDF vision problems!

**Comment by GitHubRulesOK** [comment]
Hmm I understand the need to alter contrast but raw image inversion is not always the best method, however I don't have your advantage of knowing what you find best for you within SumatraPDFs more limited mods than those more DDA dedicated in say Okular or Adobe Acrobat.

Inversion feature was primarily for brief usage within a document that has inverted contents, and not expected to be used with translucent selection thus flipping between the two may make the location more obvious.

When a word is selected then using zoom steps "in" will generally be focused on the selection , however to step back you need previous views rather than zoom out, so not ideal. 
![image](https://user-images.githubusercontent.com/12754913/158999010-ca543308-e128-407b-b330-32abb99c31a7.png)

**Comment by LorenAmelang** [comment]
@GitHubRulesOK 

"Inversion feature was primarily for brief usage within a document that has inverted contents, and not expected to be used with translucent selection thus flipping between the two may make the location more obvious."

Are you talking about: 
https://github.com/sumatrapdfreader/sumatrapdf/commit/5332297c5518eb32ba429dbe47ac67f50d0a02ff

It says "3.3 (2021-07-06)", but I have SumatraPDF-3.3.3-64-install.exe and both I and Shift+I show/hide the "Page # of #" message. (The About box is pretty much invisible, gets my black background but very dark blue text that can't be selected or copied.) 

https://www.sumatrapdfreader.org/docs/Keyboard-shortcuts still shows only "i - show page information in full screen/presentation mode". (But it works in a normal window too...) 

"When a word is selected then using zoom steps "in" will generally be focused on the selection , however to step back you need previous views rather than zoom out, so not ideal."

Aha! "Ctrl + scroll wheel - zoom in/out" moves the found word to the center of the screen, as large as necessary! And you can just zoom back out, or stay zoomed in while searching through the whole document. I think that works for me! 

Thanks for sending me there!

**Comment by LorenAmelang** [comment]
Ooops...  If you're in Show Pages Continuously mode, and if the found text is near the left-right center of the page, and if your cursor is near the center of the document window when you zoom, the found item will zoom right toward the cursor. If not, it may slide well off the screen. 

But once you're zoomed in, new search items _will_ appear in the center of your view. Find previous, find next, to locate the result that didn't show immediately.

**Comment by GitHubRulesOK** [comment]
The shifted colour eye (pun) was temporarily set to the normal <kbd>I</kbd>nfo key for a while but had been added into [3.4 pre-release](https://www.sumatrapdfreader.org/prerelease) so not yet documented

**Comment by kjk** [comment]
No plans to do more that what is already possible with settings
