### ISSUE TITLE
Option to pin page in the center.

### ISSUE THREAD

**Issue by legenw848dary** [sumatrapdfreader/sumatrapdf#2427]
When you open a document with wide and relatively thin pages, the document opens with a horizontal scroller. It would be convenient to have an option to pin a page in the center instead of opening it aligned to the left side and then scaling relative to the pointer. With this option you open a document, scale it and the page always stays in the center unless you change its position. Today if you open a document and scale it (and with this scale you still have big pages not fully fitting in window, so scroller is still there), you need to place the page in the center of the window by hand, whereas it's better to have it done automatically and precisely.
![Screenshot 2022-03-18 190529](https://user-images.githubusercontent.com/80561975/159018177-288c9e09-01c5-45a1-bda7-3582df140330.jpg)
.

**Comment by GitHubRulesOK** [comment]
You can set the default to width then there is no need for horizontal scrollbar until you change view.
![image](https://user-images.githubusercontent.com/12754913/159041076-d39ed08e-5048-4183-8979-80edf9f7b7b0.png)

**Comment by legenw848dary** [comment]
You need to change a scale, so text size in the book is comfortable to read. So this option would be really helpful in reading - you don't need to mind page position, page always stays in center. You can check how it works in WinDjVu.

**Comment by kjk** [comment]
I'm guessing it has to do with PDF documents that have pages of different sizes but I don't really understand the ask.
