### ISSUE TITLE
[Feature Request] Remember More than One Window of Same Doc

### ISSUE THREAD

**Issue by lmstearn** [sumatrapdfreader/sumatrapdf#243]
Working with a large tutorial where it's extremely convenient to operate multiple windows of the same document in a session. Now that MS insists on rebooting frequently, there's a time factor in opening the page positions back again manually
 There has to be more than one FilePath entry for the same FilePath. Sumatra opens different documents beautifully, but it's a little awkward making several filecopies of the same tutorial for it to work.as advertised. Thanks :)

**Comment by drweb86** [comment]
As i understand you're talking about bookmarks

**Comment by kjk** [comment]
I don't really understand the request.

**Comment by lmstearn** [comment]
Hi kjk, it's about opening more than one instance of the same document. It's convenient to have doc opened at the index section, and another window at the chapter section, and another window at the answers section. Large document. :)
 Windows boots, Sumatra remembers one window instance, but all the page locations of the other parts of the document have to be manually found again to match the windows instances loaded before the boot.
