### ISSUE TITLE
v3.4.14301 64-bit Pre-release crashed

### ISSUE THREAD

**Issue by augor** [sumatrapdfreader/sumatrapdf#2432]
v3.4.14301 64-bit Pre-release crashed when the left margin setting is less then zero.

Crash file: C:\Users\Administrator\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.txt
Exe: C:\Users\Administrator\AppData\Local\SumatraPDF\SumatraPDF.exe 6.74 MB (7,067,672 Bytes)
Dll: C:\Users\Administrator\AppData\Local\SumatraPDF\libmupdf.dll 10.91 MB (11,438,080 Bytes)
BuiltOn: 2022-03-20
Type: dll
Ver: 3.4.14301 pre-release 64-bit
Git: a1c2f834eda522a06ba2c7494a15ea724e880d0c (https://github.com/sumatrapdfreader/sumatrapdf/commit/a1c2f834eda522a06ba2c7494a15ea724e880d0c)
OS: Windows 7 SP1 build 7601 64-bit
Number Of Processors: 4
Processor: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
Physical Memory: 3.95 GB
Commit Charge Limit: 11.95 GB
Memory Used: 62%
Machine: To be filled by O.E.M. System Version
Lang: zh CN
Graphics driver 0
  DriverDesc:         NVIDIA GeForce GT 730
  DriverVersion:      23.21.13.9135
  UserModeDriverName: nvd3dumx.dll
Graphics driver 1
  DriverDesc:         NVIDIA GeForce GT 730
  DriverVersion:      23.21.13.8792
  UserModeDriverName: nvd3dumx.dll
Graphics driver 2
  DriverDesc:         Intel(R) HD Graphics 610
  DriverVersion:      21.20.16.4528
  UserModeDriverName: igdumdim64.dll
Graphics driver 3
  DriverDesc:         Intel(R) HD Graphics 610
  DriverVersion:      21.20.16.4528
  UserModeDriverName: igdumdim64.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 000000013F298E54 01:0000000000017E54 sumatrapdf.exe!DisplayModel::Relayout+0x608 D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+818
Fault writing address 0000000000000000

Registers:
RAX:0000000000000000  RBX:0000000001FD89D0  RCX:000007FFFFFD8000
RDX:0000000000000001  RSI:0000000000000000  RDI:0000000000000000
R8: 0000000000000000
R9: 00000000002AEF20
R10:000000013F3390FC
R11:00000000002AF000
R12:0000000000000001
R13:0000000000000001
R14:0000000000000001
R15:0000000000000000
CS:RIP:0033:000000013F298E54
SS:RSP:002B:00000000002AF020  RBP:002AF0A9
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010246

Crashed thread:
000000013F298E54 01:0000000000017E54 sumatrapdf.exe!DisplayModel::Relayout+0x608 D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+818
000000013F2C5E42 01:0000000000044E42 sumatrapdf.exe!LoadDocIntoCurrentTab+0x58a D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+1134
000000013F2C7371 01:0000000000046371 sumatrapdf.exe!LoadDocument+0x4a9 D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+1692
000000013F2D1D5A 01:0000000000050D5A sumatrapdf.exe!LoadOnStartup+0x8a D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+264
000000013F2D41B5 01:00000000000531B5 sumatrapdf.exe!WinMain+0xec1 D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+1240
000000013F356F4E 01:00000000000D5F4E sumatrapdf.exe!__scrt_common_main_seh+0x106 d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl+288
0000000077A9556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
0000000077BF385D 01:000000000005285D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 128c
0000000077C098CA 01:00000000000688CA ntdll.dll!ZwWaitForSingleObject+0xa
000007FEFD7C10DC 01:00000000000000DC kernelbase.dll!WaitForSingleObjectEx+0x9c
000000013F2968C3 01:00000000000158C3 sumatrapdf.exe!DumpExceptionHandler+0xaf D:\a\sumatrapdf\sumatrapdf\src\CrashHandler.cpp+432
0000000077B1B9B0 01:000000000009A9B0 kernel32.dll!UnhandledExceptionFilter+0x160
0000000077C19015 01:0000000000078015 ntdll.dll!longjmp+0xc2f5
0000000077BF7388 01:0000000000056388 ntdll.dll!_C_specific_handler+0x8c
0000000077C0BF7D 01:000000000006AF7D ntdll.dll!_chkstk+0x9d
0000000077BE043A 01:000000000003F43A ntdll.dll!RtlInitializeResource+0x53a
0000000077C0B61E 01:000000000006A61E ntdll.dll!KiUserExceptionDispatcher+0x2e
000000013F298E54 01:0000000000017E54 sumatrapdf.exe!DisplayModel::Relayout+0x608 D:\a\sumatrapdf\sumatrapdf\src\DisplayModel.cpp+818
000000013F2C5E42 01:0000000000044E42 sumatrapdf.exe!LoadDocIntoCurrentTab+0x58a D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+1134
000000013F2C7371 01:0000000000046371 sumatrapdf.exe!LoadDocument+0x4a9 D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+1692
000000013F2D1D5A 01:0000000000050D5A sumatrapdf.exe!LoadOnStartup+0x8a D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+264
000000013F2D41B5 01:00000000000531B5 sumatrapdf.exe!WinMain+0xec1 D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+1240
000000013F356F4E 01:00000000000D5F4E sumatrapdf.exe!__scrt_common_main_seh+0x106 d:\a01\_work\43\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl+288
0000000077A9556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
0000000077BF385D 01:000000000005285D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 20c4
0000000077C098CA 01:00000000000688CA ntdll.dll!ZwWaitForSingleObject+0xa
000007FEFD7C10DC 01:00000000000000DC kernelbase.dll!WaitForSingleObjectEx+0x9c
000000013F2B6A57 01:0000000000035A57 sumatrapdf.exe!RenderCache::RenderCacheThread+0xb7 D:\a\sumatrapdf\sumatrapdf\src\RenderCache.cpp+641
0000000077A9556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
0000000077BF385D 01:000000000005285D ntdll.dll!RtlUserThreadStart+0x1d

Module: 000000013F280000 6C8000 SumatraPDF.exe   C:\Users\Administrator\AppData\Local\SumatraPDF\SumatraPDF.exe
Module: 0000000077BA0000 19F000 ntdll.dll        C:\Windows\SYSTEM32\ntdll.dll
Module: 0000000077A80000 11F000 kernel32.dll     C:\Windows\system32\kernel32.dll
Module: 000007FEFD7C0000 067000 KERNELBASE.dll   C:\Windows\system32\KERNELBASE.dll
Module: 000007FEFC1B0000 1F5000 COMCTL32.dll     C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.24483_none_e372d88f30fbb845\COMCTL32.dll
Module: 000007FEFFC10000 09F000 msvcrt.dll       C:\Windows\system32\msvcrt.dll
Module: 000007FEFF470000 067000 GDI32.dll        C:\Windows\system32\GDI32.dll
Module: 0000000077980000 0FA000 USER32.dll       C:\Windows\system32\USER32.dll
Module: 000007FEFDE00000 00E000 LPK.dll          C:\Windows\system32\LPK.dll
Module: 000007FEFEE60000 0CB000 USP10.dll        C:\Windows\system32\USP10.dll
Module: 000007FEFF3E0000 071000 SHLWAPI.dll      C:\Windows\system32\SHLWAPI.dll
Module: 000007FEF9F10000 071000 WINSPOOL.DRV     C:\Windows\system32\WINSPOOL.DRV
Module: 000007FEFFAF0000 097000 COMDLG32.dll     C:\Windows\system32\COMDLG32.dll
Module: 000007FEFE0D0000 D8B000 SHELL32.dll      C:\Windows\system32\SHELL32.dll
Module: 000007FEFDFF0000 0DB000 ADVAPI32.dll     C:\Windows\system32\ADVAPI32.dll
Module: 000007FEFDD80000 01F000 sechost.dll      C:\Windows\SYSTEM32\sechost.dll
Module: 000007FEFF8E0000 12C000 RPCRT4.dll       C:\Windows\system32\RPCRT4.dll
Module: 000007FEFF4E0000 1FF000 ole32.dll        C:\Windows\system32\ole32.dll
Module: 000007FEFFA10000 0DB000 OLEAUT32.dll     C:\Windows\system32\OLEAUT32.dll
Module: 000007FEFF890000 02E000 IMM32.DLL        C:\Windows\system32\IMM32.DLL
Module: 000007FEFF780000 109000 MSCTF.dll        C:\Windows\system32\MSCTF.dll
Module: 000007FEFB4B0000 003000 api-ms-win-core-synch-l1-2-0.DLL C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL
Module: 000007FEFCF80000 056000 uxtheme.dll      C:\Windows\system32\uxtheme.dll
Module: 000007FEFCDF0000 018000 dwmapi.dll       C:\Windows\system32\dwmapi.dll
Module: 0000000077D50000 003000 normaliz.dll     C:\Windows\system32\normaliz.dll
Module: 000007FEFB2C0000 125000 dbghelp.dll      C:\Windows\system32\dbghelp.dll
Module: 000007FEFBC90000 219000 gdiplus.dll      C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.24494_none_145eb4f68b8d650b\gdiplus.dll
Module: 000007FEFB190000 007000 msimg32.dll      C:\Windows\system32\msimg32.dll
Module: 000007FEFFCB0000 188000 urlmon.dll       C:\Windows\system32\urlmon.dll
Module: 000007FEFDA70000 004000 api-ms-win-downlevel-ole32-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-ole32-l1-1-0.dll
Module: 000007FEFDA80000 004000 api-ms-win-downlevel-shlwapi-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll
Module: 000007FEFD840000 005000 api-ms-win-downlevel-advapi32-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll
Module: 000007FEFD870000 004000 api-ms-win-downlevel-user32-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll
Module: 000007FEFD710000 004000 api-ms-win-downlevel-version-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-version-l1-1-0.dll
Module: 000007FEFD200000 00C000 version.DLL      C:\Windows\system32\version.DLL
Module: 000007FEFD830000 003000 api-ms-win-downlevel-normaliz-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll
Module: 000007FEFDAB0000 2CA000 iertutil.dll     C:\Windows\system32\iertutil.dll
Module: 000007FEFEF30000 4AC000 WININET.dll      C:\Windows\system32\WININET.dll
Module: 000007FEFDA90000 01F000 USERENV.dll      C:\Windows\system32\USERENV.dll
Module: 000007FEFD6F0000 00F000 profapi.dll      C:\Windows\system32\profapi.dll
Module: 000007FEFB6F0000 161000 windowscodecs.dll C:\Windows\system32\windowscodecs.dll

Modules loaded later:
Module: 000007FEFD590000 00F000 CRYPTBASE.dll    C:\Windows\system32\CRYPTBASE.dll
Module: 000007FECCDA0000 AFB000 libmupdf.dll     C:\Users\Administrator\AppData\Local\SumatraPDF\libmupdf.dll

-------- Log -----------------

InstallCrashHandler crashDumpPath: 'C:\Users\Administrator\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.dmp', crashFilePath: 'C:\Users\Administrator\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.txt', symDir: 'C:\Users\Administrator\AppData\Local\SumatraPDF\crashinfo'
Starting SumatraPDF
prefs::Load() took 0.20 ms
ParseTranslationsTxt: 20105 lines, nStrings: 358
LoadDocument: 'D:\11.pdf' tid=4748
CreateControllerForFile: 'D:\11.pdf', 10 pages
LoadDocument: !forceReuse, created win->currentTab at 0x0000000000483C60
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.00 ms

----- Settings file ----------

﻿# For documentation, see https://www.sumatrapdfreader.org/settings/settings3-4.html

MainWindowBackground = #666666
SmoothScroll = false
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true
TabWidth = 300

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #F6FFF6
	SelectionColor = #15C191
	WindowMargin = 2 0 2 -2
	PageSpacing = 2 2
	HideScrollbars = false
	EbookFontName = default
	EbookFontSize = 10
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]
SelectionHandlers [
]
ExternalViewers [
]
ShowMenubar = true
ReloadModifiedDocuments = true
FullPathInTitle = false
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #15C191
	HighlightPermanent = true
]
Annotations [
	HighlightColor = #ffff00
	UnderlineColor = #00ff00
	TextIconColor = #ffff00
	TextIconType = 
	DefaultAuthor = 
]
CustomScreenDPI = 0

RememberStatePerDocument = false
UiLanguage = cn
ShowToolbar = true
ShowFavorites = false
AssociateSilently = false
CheckForUpdates = false
RememberOpenedFiles = false
EnableTeXEnhancements = false
DefaultDisplayMode = continuous facing
DefaultZoom = fit width
WindowState = 2
WindowPos = 960 0 960 1032
ShowToc = false
SidebarDx = 480
TocDy = 0
TreeFontSize = 0
ShowStartPage = true
UseTabs = false

FileStates [
]
SessionData [
]
TimeOfLastUpdateCheck = 0 0
OpenCountWeek = 585

# Settings after this line have not been recognized by the current version

**Comment by kjk** [comment]
This is a debug crash only present in pre-release builds.

The fix is to probably change negative margin values to 0. The layout code wasn't written to handle negative margin values.

**Comment by GitHubRulesOK** [comment]
@kjk 
hmm we also saw worse abuse in https://github.com/sumatrapdfreader/sumatrapdf/issues/1899#
would it be trivial to ignore negative abusage ?

**Comment by kjk** [comment]
Yes, it's relatively simple to sanitize margin values after loading settings.
