### ISSUE TITLE
Inline images in epub not shown

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [sumatrapdfreader/sumatrapdf#2444]
Hi,

I looked for an open-source epub reader for simple opening and checking out epub files instead of having Calibre do all its slow things and adding stuff to its library and whatnot.

I was recommended Sumatra PDF, so I tried that. Immediately I noticed the text "image" where the cover image of the first epub I opened was supposed to be. This image is an inline HTML image (`<img src="data:image/jpeg;base64,/9j/4AAQS ...`), so I'm assuming that's the issue? Works fin in Calibre, on my Kindle, on macOS' native reader...

Is this something that'll be supported, or is it just a known shortcoming?

Thanks :)

**Comment by GitHubRulesOK** [comment]
The eBook engine came in two types the "legacy" all flowing formats in one interface or the Fixed Interface that's based on PDF features such as find text in page, etc. 
The current interface is now default to the Fixed format with a few types still using legacy when required.

So ePub now is rendered by MuPDF graphically which can have some limitations (most notable is weak table support) Inline images should be better supported as long as the structure is conventional html.
 
Note that pdf/jpeg/png;base64 are NOT what they seem they are not "inline" they are "encoded data uri" thus need insecure java scripting to be decoded.

**Comment by kjk** [comment]
Can't say anything about a sample file.

Also check in https://www.sumatrapdfreader.org/prerelease because it has a new epub engine.

**Comment by GitHubRulesOK** [comment]
@kjk 
Without a non working sample I injected a data:uri Icon into XHTML and replaced into ePub.
Current pre-release version handles both "inline" as expected. Thus suggest this issue be closed

![image](https://user-images.githubusercontent.com/12754913/174503504-e429c111-f139-46a5-8a7e-a455ad39a21f.png)

**Comment by DanielSmedegaardBuus** [comment]
I am SO sorry for disappearing like that right after asking a question. Life happened.

However, I can confirm that the pre-release version renders the epub document with my "inline" (@GitHubRulesOK - is there another way to inline images in HTML? Because I'm generating these epubs myself, and I did it this way because it's super easy for me) images as I'd expected :)

Thank you guys, and again, apologies for my absence.

**Comment by GitHubRulesOK** [comment]
@DanielSmedegaardBuus
Unsure how you are handling the files I simply ran tar to extract xml then used notepad to paste the base64 (could be done with custom cmd script)  then tar -a to resave as epub but its simpler to use any GUI epub editor that may add embedment's, and unclear if there is a natural  base64 string limit around 1.5 MB so never tried to see if this would work https://github.com/GitHubRulesOK/MyNotes/raw/master/Hanoi.htm
