### ISSUE TITLE
[BUG] KEY_F6 is suppressed to propagate to other applications

### ISSUE THREAD

**Issue by redstoneleo** [sumatrapdfreader/sumatrapdf#2446]
If you press KEY_F6 while the main window is active and the bookmarks are visible, it seems the KEY_F6 event is suppressed to propagate to other applications.

The same issue also happens to the wheel-clicked action of the mouse.

I do think these events should be allowed to propagate to other applications.

Tested with v3.3.3， 64bit, win11.

**Comment by kjk** [comment]
That's not how Windows works. No keys are ever propagated to other apps.

**Comment by redstoneleo** [comment]
I hooked KEY_F6 and the wheel-clicked action of the mouse in a global-wide, but didn't receive this event when sumatrapdf is active, so I guess sumatrapdf suppressed these event, while it works with other applications as the active window.
