### ISSUE TITLE
Is it possible to go to the next file in a folder?

### ISSUE THREAD

**Issue by Darkmaster006** [sumatrapdfreader/sumatrapdf#2448]
So I was just wondering if there was any way to, with a hotkey, like 'Ctrl+Alt+N' or something, open the next file that's available in the same folder in which the files you're reading is. Thanks.

**Comment by kjk** [comment]
`Ctrl + Shift + Right`
See https://www.sumatrapdfreader.org/manual

**Comment by Darkmaster006** [comment]
> `Ctrl + Shift + Right` See https://www.sumatrapdfreader.org/manual

Should have looked at the manual first, you're right. Thank you.
