### ISSUE TITLE
Undocumented feature

### ISSUE THREAD

**Issue by nata1993** [sumatrapdfreader/sumatrapdf#2449]
Stumbled upon feature which is as far as I checked manual and keyboard shortcuts, is not documented.
Hitting / or * on numerical keyboard in page viewing state rotates page left or right respectively. Same can be done according to manual by hitting Ctrl Shift - or Ctrl Shift + respectively. 
Keyboard shortcuts could be updated to include / and * numerical symbols for rotating pages which is easier and faster than Ctrl Shift + or Ctrl Shift -.
The undocumented part is on the page only https://www.sumatrapdfreader.org/manual

**Comment by GitHubRulesOK** [comment]
documented as [`/ on numeric keypad - rotate left` & * on numeric keypad - rotate left`](https://www.sumatrapdfreader.org/docs/Keyboard-shortcuts#ade4498d-520d-48bd-b710-acae93d19f4c) so closing issue
