### ISSUE TITLE
sumatrapdf suppressed KEY_F6, Ctrl and the wheel-clicked action of the mouse in a global-wide

### ISSUE THREAD

**Issue by redstoneleo** [sumatrapdfreader/sumatrapdf#2450]
I hooked KEY_F6, Ctrl and the wheel-clicked action of the mouse in a global-wide, but didn't receive this event when sumatrapdf is active, so I guess sumatrapdf suppressed these event, which made my application do not work, while it works with other applications as the active window. I hope  sumatrapdf doesn't suppress these event

Tested with v3.3.3， 64bit, win11.

**Comment by kjk** [comment]
Or your code has bugs.

Unless you can point to a bug (and fix) in Sumatra, my assumption is that the bug is in your code.

**Comment by GitHubRulesOK** [comment]
On windows 11 I confirm with SumatraPDF 3.4 pre-release  active AND in focus it correctly responds to F6
and correctly when not in focus it does NOT hook F6 as F6 can then affect whatever current window is in focus.

I downloaded official 3.3.3 64bit and the result is exactly the same.

thus whilst a file is open and I am using explorer then F6 will tab in explorer from place to place **thus is not blocked by SumatraPdf activity/usage**. equally whichever window is active will respond to ctrl wheel so zoom in will work in either SumatraPdf OR this edge browser depending which one I am hovering over thus ***Edge is not hooking the control from SumatraPdf or the other way round***
BOTH function the same independently.
