### ISSUE TITLE
Vertical Tabs

### ISSUE THREAD

**Issue by devindang** [sumatrapdfreader/sumatrapdf#2451]
When I have too many files open, the filenames may be shown incompletely. It's hoped that Sumatra Pdf supports vertical tabs like EDGE

**Comment by GitHubRulesOK** [comment]
@kjk requests like these for a massive change in interface ? 
yes, I know you are working on a related customization change
are best moved to discussion rather than issue/bug
my question here is can I move this to discussion only?

**Comment by devindang** [comment]
> 

yes
