### ISSUE TITLE
Add feature: save pdf as images

### ISSUE THREAD

**Issue by helperman** [sumatrapdfreader/sumatrapdf#2469]
Please add this feature.

**Comment by GitHubRulesOK** [comment]
Most of those are already possible but there are so many ways to export images it would not be practical to add as many options, most native windows methods involve cut and paste then you chose save as the target format such as TIFF is probably the best all round as allows for multile pages as mono/grey/colour at high resolution, for Mono save as.bmp or 256 colour GIF then Ideally the next best all rounder is RGBA optimized PNG and worst of all Non-Alpha JPEG (unless the source was a lossy.jpg.
