### ISSUE TITLE
Opening Various Files

### ISSUE THREAD

**Issue by famfop** [sumatrapdfreader/sumatrapdf#247]
Hi,
when opening various files (doesn't matter if .djvu or .pdf or mixed [haven't tried with others]) the order in which it is opened is changed. Let me explain:
I have 3 .pdf's (a, b, c) in a folder and want them to open in the order as shown in the folder (lets say the order is: a, b, c): I select them and press enter (using windows explorer). The order of the tabs in Sumatra doesn't match, sometimes it will be (b,a,c), (a,c,b) or something else.
Not sure if it's a bug or a feature but I don't like it, especially when opening 20+ files!

**Comment by kjk** [comment]
We don't guarantee any specific order of opening in that scenario.
