### ISSUE TITLE
Sumatra does not follow stylesheet for epub files

### ISSUE THREAD

**Issue by 3N4N** [sumatrapdfreader/sumatrapdf#2478]
In Sumatra, the epub file (checked with both epub v2 and v3) is not rendered according to the stylesheet. For comparison, see the rendering in Calibre Ebook Viewer on the right.

![image](https://user-images.githubusercontent.com/32037751/162921601-1f24daf1-3c2b-4c4b-8daf-e2bc93bbc2a8.png)

**Comment by GitHubRulesOK** [comment]
The problem with rogue books is having the same copy so compare what I think was the Authors intent in this PDF where there are no indents as you show https://files.libcom.org/files/Le%20Guin%20-%20The%20Dispossessed.pdf

**Comment by 3N4N** [comment]
@kjk You're right. I was using an older version. In the current pre-release, the indentation is correct. Thanks for the response and feel free to close this issue.
