### ISSUE TITLE
60 FPS smooth scrolling

### ISSUE THREAD

**Issue by gblazex** [sumatrapdfreader/sumatrapdf#248]
I first thought this might require a lot of work, but just discovered that moving the document with the hand tool seems to be _perfectly_ smooth.

However, high-precision mouse wheel scroll (or touchpad) seems to be jerky.

Also auto-scroll (click and hold middle mouse button with movement) is jerky too.

**Comment by vgturtle127** [comment]
I'm not sure the problem you describe is an issue with SumatraPDF. What graphics card are you using?

**Comment by Canule** [comment]
Problem still exist 2017-v3.1.2 x64 , especially with an scroll flywheel the delay makes it hard to stop on the right page.

**Comment by Poopooracoocoo** [comment]
i really hope someone implements this. i wish i knew how it all worked

**Comment by GitHubRulesOK** [comment]
@kjk 
I find this issue a difficult one to call since you can't please 7 billion people all of the time.
My experiments suggest  file scrolling behaviour in SumatraPDF is generally similar to behaviour in Adobe Acrobat.
Each file will be different, Each PC hardware will be different. Each user step choices will be different

Since there is nothing much that the application can do to correct user hardware settings, behaviours and perceptions IMHO it is working as well as can be expected. The only way to achieve 60fps behaviour is to convert files that contain stepped lines of text into video streams.

**Comment by gblazex** [comment]
That is where you are gravely mistaken my friend 

Having written a universal smooth scrolling mouse driver for windows (and Mac) I can assure you that 60-120-240 FPS PDF scrolling is possible.

Check out the listed apps from the Windows store 
https://www.smoothscroll.net/win/getting-started/pdf/


Mobile devices have had these for a long time now but you can see it working on your desktop as well (which should come as no surprise as the hw is actually beefier)


Blaze

**Comment by GitHubRulesOK** [comment]
Hi Blaze
Ok I am possibly biased so installed the first one linked "PDF reader" I could not find any settings to make a comparison, It was slower to load a 434 page file It took longer to jump to page 343 and there is no autoscrolling option It only offers to scroll around the page which I can do in SumatraPDF no problem.

**Comment by gblazex** [comment]
Try it with a 
- touchpad, 
- a precision mouse (MX Master, Anywhere), 
- or with a classical wheel mouse (needs a my driver from SmoothScroll.net to get 60 FPS)

You’ll see the difference 


Blaze

**Comment by GitHubRulesOK** [comment]
Seems that "Give it a spin 😉" would have been your better catch line, however I do appreciate you have not tried to advertise your wares, so up for a challenge will test it out.

**Comment by GitHubRulesOK** [comment]
I spent a little time playing about with different settings and the most useful was setting step sizes, so I could (for different zoom levels) wheel step exactly one text line distance at a time, but overall it did not seem to better the auto scroll response.

[scrolling driver feature enhancement]
when I need to change wheel step size per zoom it is unwieldy to trial and error the settings
unsure how to suggest it be called by "hot key" or mouse action
but it would be nice to click bottom of two sequential lines to set the stepping distance on-the-fly

**Comment by Poopooracoocoo** [comment]
Personally, I don't want perfect 60 FPS scrolling but I just want smooth scrolling with a Precision Touchpad just like with a touchscreen to match other apps' (such as UWP apps and browsers like Chrome) behaviour. Scrolling is heaps smoother in Sumatra PDF compared to Adobe Acrobat Reader/Pro in terms of lag, but they both scroll line by line

**Comment by GitHubRulesOK** [comment]
@kjk 
Can you confirm if rendering line by line of **text by its very nature** results in the common jerky line feed  action seen in most  PDF readers such as **Acrobat, Chromium Edge** _and SumatraPDF_ unfortunately I can't find a similar mode in MuPDF to compare

**Comment by gblazex** [comment]
Pixel scrolling, that is the same thing 


Blaze

**Comment by GitHubRulesOK** [comment]
Hi Blase
I agree that when a single page is rendered to pixels then smooth scrolling is not a problem.

The Issue here is that when megabytes of lines of text need to be rendered as a continuous scrolled object there is inevitably frequent pauses for buffering, that can happen at variable intervals which gives the appearance of jerking unless you can slow it down to appear as imperceptible movements.

**Comment by gblazex** [comment]
You can easily show blank pages as scrolling and fill them up as they get rendered in a non-main-thread-blocking way. 

The faster the hardware the less it is noticeable.
And it only really matters if you are flying through the pages insanely fast.

UI stays responsive and can react to events on a pixel level accuracy 

That is how mobile devices (and those windows store apps) do it

Blaze

**Comment by GitHubRulesOK** [comment]
Consolidating as duplicated by more recent #606 which has more definitive responses as to the underlying issue

**Comment by gblazex** [comment]
Whatever dude, I just tell my users to use other PDF readers until it’s fixed 

It’s unacceptable UX for me in 2020

Blaze

**Comment by GitHubRulesOK** [comment]
Blaze if your driver can hook the legacy behaviour of drag'n'grab or emulate autoscroll speeds on a touchpad you open up a much wider market.

**Comment by gblazex** [comment]
It sends standard wheel events like laptop trackpads do. (Delta less than 120)

This is the Microsoft Recommendation for high precision mouse input! (like MX Anywhere)


(Not touch events like touchscreen that is not possible)


Many many apps can handle it corrctly
The ball is not on my court

Browsers can handle it correctly.
Chrome’s PDF reader can handle it correctly!
UWP apps can too. (uwp pdf readers too)
Text editors etc

Blaze

**Comment by djdelarosa25** [comment]
2022 and still no smooth scrolling for the top recommended PDF viewer app

For those interested, Xodo from the Microsoft Store has smooth scrolling
