### ISSUE TITLE
Keyboard key 'a' in searching starts annotation

### ISSUE THREAD

**Issue by lRadha** [sumatrapdfreader/sumatrapdf#2481]
Searching in SumatraPDF with any text containing key 'a' didn't type 'a' in the search bar but it starts annotations in the latest version.

SumatraPDF v3.4.14338 64bit
OS: Windows 10

**Comment by kjk** [comment]
Has been fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/2b4b633221131aaaf81b6aaea5d256beb124931b so should be fixed by updating to latest 14434
