### ISSUE TITLE
Horizontal two-finger scrolling crashes Sumatrapdf 

### ISSUE THREAD

**Issue by letusbegintheadventure** [sumatrapdfreader/sumatrapdf#2483]
Every time I accidentally use horizontal two-finger scrolling - left or right - Sumatra will crash. 

Can I do something in order to be able to use horizontal two-finger scrolling again? 

All the best from Stan

**Comment by kjk** [comment]
Which version of Sumatra?

Does it happen in pre-release version https://www.sumatrapdfreader.org/prerelease ?

If yes, please post crash report https://www.sumatrapdfreader.org/docs/Submit-crash-report

**Comment by letusbegintheadventure** [comment]
Hi kjk

Thanks for getting back :-) 

Yes, it also happens in the prerelease (I verified that I use the prerelease version in the "about" menu) 

I'm not able to find the crash report - where to look?

According to the link, notepad should open upon crashes but it doesn't happen on my machine. 

Thanks.

**Comment by kjk** [comment]
You should see this message box after the crash:

![image](https://user-images.githubusercontent.com/7935/163249389-7fbe2a3d-da91-4f79-8eec-85e39789925f.png)

Crash info is also saved in `crashinfo/sumatrapdfcrash.txt` file in Sumatra's settings directory.

For installed it's `%APPLOCALDATE%/SumatraPDF`. For portable it's where `SumatraPDF.exe` is.

But if you don't get message box about crash, it's possible the handling didn't work so there won't be crash file either.

You should definitely intercept the crash if you run SumatraPDF.exe under a debugger like `WinDBG`, but that's a bit advanced.

That being said: if Sumatra was crashing with two-finger scroll, more people would report it.

Most likely you have bad / outdated drivers or some invasive software injects itself into SumatraPDF process and causes the crash.

**Comment by kjk** [comment]
For what it's worth, I just tested two finger scrolling on my Thinkpad X1 and it didn't crash.

**Comment by GitHubRulesOK** [comment]
the prerelease version in the "about" menu will show a number currently 3.4.14443 :-)
if you run debug download symbols it should show (slowly)
```
---------------------------
Downloading symbols
---------------------------
Downloaded symbols! to C:\Users\YourAccount\AppData\Local\SumatraPDF\crashinfo
---------------------------
OK   
---------------------------
```

**Comment by GitHubRulesOK** [comment]
> Crash info is also saved in `crashinfo/sumatrapdfcrash.txt` file in Sumatra's settings directory.
> 
> For installed it's ***`%APPLOCALDATE%/SumatraPDF`.*** For portable it's where `SumatraPDF.exe` is.
> 
@ KJK
that should be  For installed it's **`%LOCALAPPDATA%\SumatraPDF`**
