### ISSUE TITLE
Crash upon setting custom-shortcuts

### ISSUE THREAD

**Issue by CRTejaswi** [sumatrapdfreader/sumatrapdf#2488]
https://gist.github.com/CRTejaswi/88a6f94cb8c033a4e2ec66d1b73dafc1

**Comment by kjk** [comment]
What was the custom shortcut you were adding that caused the crash?

**Comment by kjk** [comment]
Should be fixed but if not, please provide the shortcut causing the trouble.

**Comment by CRTejaswi** [comment]
I've tried this a few times, and am noticing it's remapping keys like n/N, p/P. As a Vim user, I prefer n/N for CmdFindNext/CmdFindPrev. Remapping these to f/F doesn't cause a crash.

**Comment by kjk** [comment]
I've made another fix
