### ISSUE TITLE
Sumatra Portable 3.0 Missing Images

### ISSUE THREAD

**Issue by JoJo415** [sumatrapdfreader/sumatrapdf#249]
I have been using Sumatra Portable 3.0.0 and every once and a while I will print pages and there will be missing images.

**Comment by kjk** [comment]
Does it happen with 3.1 pre-relase (http://www.sumatrapdfreader.org/prerelease.html) ?

If yes, please provide a document that shows the problem.

**Comment by JoJo415** [comment]
I haven't tried it with the 3.1 pre-release. My only fear with the pre-release is of new bugs that have not been crushed. Do you have an ETA of the of final 3.1 release?
Here is what I am getting. 

[URL=http://img4.imagetitan.com/img.php?image=11_image683.jpg][IMG]http://img4.imagetitan.com/img4/small/11/11_image683.jpg[/IMG][/URL]

**Comment by JoJo415** [comment]
http://img4.imagetitan.com/img.php?image=11_image937.jpg

http://img4.imagetitan.com/img.php?image=11_image683.jpg

**Comment by kjk** [comment]
Please try with 3.1 and reopen if still happens.
