### ISSUE TITLE
Window minimization button not visible/accessible on v3.1.2 64bit

### ISSUE THREAD

**Issue by uhclDelta** [sumatrapdfreader/sumatrapdf#2495]
Thanks for all the hard work - love SumataraPDF.

Window minimization button not visible/accessible on v3.1.2 64bit
If more that a few file tabs are open, the tab-name for the rightmost file covers the window minimization button. The minimization  button seems to be there, just not reachable as the tab-name of the rightmost file is covering it. This is not a problem with only a few files tabs.

**Comment by kjk** [comment]
This is a very old version.

Please check with latest pre-release https://www.sumatrapdfreader.org/prerelease

If still exists, please post screenshot.
