### ISSUE TITLE
fontsize in tool bar is too large, prerel v3.4.14469 64bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2496]
font size is much larger than that of the previous version, as shown in this screenshot.
maybe a bug? if that's new feature, is it possible to be modifiable by user?
BTW, i installed this version 'for all users'. 

![image](https://user-images.githubusercontent.com/28478572/164022832-e14f3226-32ab-4870-a230-2ee48192b33b.png)

**Comment by GitHubRulesOK** [comment]
see https://github.com/sumatrapdfreader/sumatrapdf/issues/2319#issuecomment-1100777026
ToolbarSize = 36
![image](https://user-images.githubusercontent.com/12754913/164044932-4964f17e-3052-4661-b38e-87c17fa1da43.png)

ToolbarSize = 12
![image](https://user-images.githubusercontent.com/12754913/164044867-b5e4fabf-73e0-4940-b938-2858daa330a6.png)

**Comment by kjk** [comment]
It is a bit too big with display scaling (to e.g. 150%).

When I added `ToolbarSize` setting I had to adjust the font size as well but it seems it's not quite right when display scaling is enabled.
