### ISSUE TITLE
Sumatra displays some scanned documents as blank pages

### ISSUE THREAD

**Issue by YANG-WQ** [sumatrapdfreader/sumatrapdf#2498]
PDF file download address http://www.moe.gov.cn/publicfiles/business/htmlfiles/moe/cmsmedia/other/2013/7/other98742.zip
In Sumatra, the file displays as blank pages. In Adobe Reader, the file displays correctly.

Sumatra
![图片](https://user-images.githubusercontent.com/12840990/164646293-84538611-9cd9-4ecc-8dc1-250e7c0e5469.png)

Adobe Reader
![图片](https://user-images.githubusercontent.com/12840990/164646408-b6f1b825-4863-4256-8e92-918f6acb8f93.png)

**Comment by kjk** [comment]
Confirmed it renders in pdfium.

Opened https://bugs.ghostscript.com/show_bug.cgi?id=705248

**Comment by kjk** [comment]
Removing RLE bomb check makes this PDF render

**Comment by eladkarako** [comment]
try linearize the pdf with qPDF first, if it works after, something in the layers of the pdf is glitching sumatrapdf (can help to create a nice fix and test case later)
