### ISSUE TITLE
Please support the two-bytes format, ex: Chinese or Japanese, Thanks.

### ISSUE THREAD

**Issue by jrlintw** [sumatrapdfreader/sumatrapdf#250]
The flow is a little bit mass, cause words are not separated by space. 
![Image of two bytes](http://i.imgur.com/LU2p3lI.jpg)

**Comment by kjk** [comment]
1. I don't read chinese. Please highlight on the screenshot the part that is not correct (on the first page, so that I can find the text)

2. Please provide the document in question as described in https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports

**Comment by jrlintw** [comment]
Thanks for your reply, attached files for your reference.
Adobe Digital Editions has a better Chinese text flow.
     寄件者： Krzysztof Kowalczyk <notifications@github.com>
 收件者： sumatrapdfreader/sumatrapdf <sumatrapdf@noreply.github.com> 
副本： jrlintw <jr_lin@yahoo.com> 
 寄件日期： 2015/8/4 (週二) 9:07 AM
 主旨： Re: [sumatrapdf] Please support the two-bytes format, ex: Chinese or Japanese, Thanks. (#250)
   
   
   - I don't read chinese. Please highlight on the screenshot the part that is not correct (on the first page, so that I can find the text)
   - Please provide the document in question as described in https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports
—
Reply to this email directly or view it on GitHub.   

  
﻿第一卷　陰神篇 

第一卷　陰神篇 001回 陰陽一席坐，佛道兩騖人
(更新時間：2006-6-13 19:06:00  本章字數：6182)

（題記：你嚮往天賦秉異的人生嗎？普通人幾乎無不希望能夠擁有超人般的能力。很多玄幻小說中的主人公一出場往往就有令人羨慕的奇遇發生，擁有了種種神奇的異能，然後一步步實現普通人在白日夢中曾擁有的願望。然而在現實中，如果這種事情真的發生在你身上，你也許會發現情況並非是想像中的那麼美好。因為大自然的法則是公平的，不會特別青睞於某個人。）

我叫石野，從小住在蕪城市東北四十里外，昭亭山下石柱村。村裡的小夥伴都說我是從石頭縫裡揀來的野孩子，對我總有些疏遠。我問過父母這個問題，他們都笑著告訴我當然不是。別的孩子不願意接近我，只有我妹妹除外。但是我當時並不覺得我有什麼與眾不同的特別之處，直到懂事之後回想起來，才發現自己小時候確實很特別。

小時候第一個特別的地方，就是經常能夠看到別人看不見的東西。現在有一種說法，說人幼年時心靈純淨眼睛也特別亮，能看見很多成人看不見的東西，但是等到人們成年後都不會保留這種記憶。而我不同，這種記憶一直很清晰。

記得我七歲那年，有一天傍晚在村口玩耍，看見村東頭的三大爺拄著枴杖走過來。三大爺經過我身邊時，我很有禮貌的跟他打了個招呼。可是三大爺卻沒有答話，只是很奇怪的看了我一眼，還輕輕歎了一口氣，然後獨自一人走向村外的昭亭山。我當時也覺得很奇怪，因為三大爺的腿腳不好，很少出門，怎麼會一個人上山呢？回家的時候我碰見了三大爺的孫子石小三，對他說他爺爺一個人上山了，天快黑了恐怕會有危險。可是石小三說他爺爺病了，這幾天一直躺在家裡怎麼可能起床呢！我和石小三一起回到村中的時候，遠遠就聽見他家傳來哭聲，問了大人才知道三大爺今天傍晚的時候走了。「走了」在蕪城的方言就是去世的意思，而在當地的方言中，去世還有一種委婉的說法就是「上山」。這件事情我沒有告訴別人，只有我和石小三知道。

我小時候第二個特別的地方，就是經常能夠預感到將要發生的事情。記得在我五歲那年，有一天一個人在村長家的院牆外玩泥巴，玩著玩著突然覺得身後不對勁，總覺得要發生什麼事，只有離開才安全。我站起來快步跑開了，就在我剛剛跑開沒多遠，一尺厚、一人多高的土牆無聲無息的坍塌了，正好砸在我剛才蹲的位置。

說到這裡有些人可能會羨慕我這種特別的天賦，因為在人們看來這是一件非常幸運的好事，比如說我可以去炒股，利用神奇的預感去賺很多錢。只可惜實際情況並非是大家想像的那樣簡單，我雖然經常有預感猜到將要發生的事情。但是我不能決定自己會預感到什麼事情發生，也不能預感到所發生事情前後過程的全部，因此對我幾乎沒有什麼實際用處。

再舉一個例子。我六歲那年夏天，蕪城市發大水，村前的青漪江水位幾乎快漲到村外的小樹林邊。前一天晚上我做了個夢，夢到很多條大魚從江裡跳出來落在岸邊。我知道這又是一次清晰的預感，於是第二天帶著魚簍去樹林邊等著抓魚。確實有魚從江裡跳到了樹林中，我抓了好幾條大魚放進了魚簍。正在高興的時候，卻不小心碰到一棵樹，驚動了樹上的一群馬蜂。結果我很不走運，被馬蜂叮了滿腦門的包，不僅魚沒抓到，連魚簍都失手丟了。我能預感到有魚上岸，卻不能預感到樹上會有馬蜂出現，所以這種預感是好是壞很難說。但是這次事情也並非全然不幸，我回家之後不久，發現我的久治無效的關節炎自己好了，不知道與馬蜂叮咬有沒有關係。

說到關節炎，我小的時候一直體弱多病，身體就沒怎麼好過，能活下來就是個奇跡。這還多虧了村裡的金爺爺，經常來給我看病。我們石柱村幾乎全村的男人都姓石，只有金爺爺這麼一個外姓人家。這種情況在當地，這個人往往會很受排斥，但金爺爺是個例外，他受到全村人的敬重，因為他是方圓十里最好的醫生。金爺爺沒有開醫館，而是無償的給上門求醫的人看病，主要是用針灸和自己上山采的草藥。我的童年奇異經歷的轉折和金爺爺有很大關係。

……

那是我八歲那年夏天，有一天村裡的小孩一起去池塘裡洗澡，所謂洗澡就是游泳玩水。村口池塘的水不深，人又多，從來沒聽說過會發生什麼危險。一起去的時候我看見了村長的兒子石東，東東的樣子嚇了我一跳：只見他面目浮腫蒼白，鼻子下面還掛著淤泥和血跡。我嚇的驚叫出來，周圍的人被我的驚叫聲也嚇了一跳，問我怎麼了。我揉了揉眼睛再看東東，剛才的樣子消失了，站在面前的仍然是個活蹦亂跳的少年。

我在那一剎那間明白了這是怎麼回事。當時年紀小說話不知道掩飾，我指著東東大聲說道：「東東，你不能下水，否則你會淹死的！」周圍的人都哄笑，沒有人理會我的話。大大小小的孩子都下水了，只有我忐忑不安的坐在池塘邊。他們在水裡玩的很開心，然而過了不久，就聽見東東大聲喊救命，人不由自主的向水下滑去，怎麼也起不來。當時就有幾個水性好的大孩子想過去拉他，卻在水下摸不到，等到村裡的大人趕來將東東撈上來的時候，人已經不行了。

我清晰的記得東東躺在池塘邊的樣子——面目浮腫蒼白，鼻子下面還掛著淤泥和血跡，一切就像我曾經看見過的那樣。後來東東的爸爸也就是村長也來了，我總覺得他看我的眼光那麼讓人不舒服，而周圍的其它人看我的眼神也是怪怪的。

回家之後我告訴父母白天發生的事情，然後當天晚上我就病了。我病的很重，一連幾天高燒不退，不斷的說著胡話。送到鄉衛生所吊了兩天鹽水也毫無起色，父母又只好把我抱回家，請來了金爺爺。金爺爺給我把完了脈，皺著眉頭問我父母我生病前發生了什麼事情，父母將那天的事情都告訴了他。

金爺爺聽完之後仍然眉頭緊鎖，若有所思的說：「這孩子天資奇異，將來禍福難料，但是現在這樣下去，很難安全長大。」我媽在一邊哭聲的問：「金大伯，難道就沒有辦法嗎？求你救救這個孩子。」金爺爺答道：「辦法倒是有一個，可以試一試。可是這樣只能起暫時的作用。」我爸也說：「別的先不管了，只要他能安安穩穩的長大就行。」金爺爺歎了一口氣：「天意如此，不知道人力能不能強求。這孩子要盡量遠離寺廟和道觀一類的地方，你們要記住了。」

金爺爺說完之後將我抱到椅子上，打開了隨身帶的一個小盒子，從盒子裡拿出一個黃色的皮卷，展開之後是一排金針。不知道大家對針灸有沒有認識，現在的醫院裡針灸用的都是一次性不銹鋼針，而過去講究一點的中醫用的是銀針，但是金爺爺當時用的是金針。金針細如毛髮，而且金本身質地很軟，用來做針灸需要醫生有相當的功力，否則根本就捻不進穴位。

我模模糊糊的記得，金爺爺在我的太陽穴、眉心、耳根、頭頂、後腦下了很多根金針，我覺得金針刺入後還在慢慢的旋轉，不知道是幻覺還是真實。後來我睡著了，醒來之後人已經躺在床上，金爺爺也離去了，我的病也好了。從此之後，我就像變了一個人，再也沒有以前那種特異的經歷，不再看見別人看不見的東西，也失去了異乎尋常的預感。

……

**Comment by kjk** [comment]
Unfortunately you can add files to Github via e-mail. As described in https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports, you have to use some extern file hosting service and provide a link to a file.

**Comment by jrlintw** [comment]
I had sent files to your gmail.     寄件者： Krzysztof Kowalczyk <notifications@github.com>
 收件者： sumatrapdfreader/sumatrapdf <sumatrapdf@noreply.github.com> 
副本： jrlintw <jr_lin@yahoo.com> 
 寄件日期： 2015/8/4 (週二) 10:14 AM
 主旨： Re: [sumatrapdf] Please support the two-bytes format, ex: Chinese or Japanese, Thanks. (#250)
   
Unfortunately you can add files to Github via e-mail. As described in https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports, you have to use some extern file hosting service and provide a link to a file.—

**Comment by kjk** [comment]
Got them, thanks.

**Comment by renyouguo** [comment]
That is the biggest bug for me.

**Comment by jrlintw** [comment]
Thanks a lot.
      寄件者： renyouguo <notifications@github.com>
 收件者： sumatrapdfreader/sumatrapdf <sumatrapdf@noreply.github.com> 
副本： jrlintw <jr_lin@yahoo.com> 
 寄件日期： 2015/9/10 (週四) 3:32 PM
 主旨： Re: [sumatrapdf] Please support the two-bytes format, ex: Chinese or Japanese, Thanks. (#250)
   
That is the biggest bug for me.—

**Comment by renyouguo** [comment]
There is this bug in .pdf and .epub files too.

**Comment by kjk** [comment]
Please provide a file with the problem and a detailed description of the problem. There's nothing we can do about vague reports. See https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports

**Comment by jrlintw** [comment]
寄件者： Krzysztof Kowalczyk <notifications@github.com>
 收件者： sumatrapdfreader/sumatrapdf <sumatrapdf@noreply.github.com> 
副本： jrlintw <jr_lin@yahoo.com> 
 寄件日期： 2015/9/10 (週四) 3:49 PM
 主旨： Re: [sumatrapdf] Please support the two-bytes format, ex: Chinese or Japanese, Thanks. (#250)
   
Please provide a file with the problem and a detailed description of the problem. There's nothing we can do about vague reports. See https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports—

**Comment by renyouguo** [comment]
2015-09-10 15:57 GMT+08:00 jrlintw <notifications@github.com>:

**Comment by jrlintw** [comment]
寄件者： renyouguo <notifications@github.com>
 收件者： sumatrapdfreader/sumatrapdf <sumatrapdf@noreply.github.com> 
副本： jrlintw <jr_lin@yahoo.com> 
 寄件日期： 2015/9/10 (週四) 4:23 PM
 主旨： Re: [sumatrapdf] Please support the two-bytes format, ex: Chinese or Japanese, Thanks. (#250)
   
2015-09-10 15:57 GMT+08:00 jrlintw <notifications@github.com>:

**Comment by cheesecracker** [comment]
Let me put in the marks where things are wrong inside the image as kjk requested.  Hope this help.

![chinese-in-sumatrapdf](https://cloud.githubusercontent.com/assets/5957892/9789105/4253cdee-57ce-11e5-9878-94a33dae2202.png)

**Comment by renyouguo** [comment]
@kjk Would you fix it?

**Comment by kjk** [comment]
This is hopefully fixed. Please try latest pre-release to see if it fixed the issue for you: https://www.sumatrapdfreader.org/prerelease.html

**Comment by jrlintw** [comment]
Thank you, it works fine.

--------------------------------------------
18/8/18 (週六)，Krzysztof Kowalczyk <notifications@github.com> 寫道：

 主旨: Re: [sumatrapdfreader/sumatrapdf] Please support the two-bytes format, ex: Chinese or Japanese, Thanks. (#250)
 收件者: "sumatrapdfreader/sumatrapdf" <sumatrapdf@noreply.github.com>
 副本: "jrlintw" <jr_lin@yahoo.com>, "Author" <author@noreply.github.com>
 日期: 2018年8月18日,六,上午9:37
 
 This is hopefully fixed. Please
 try latest pre-release to see if it fixed the issue for you:
 https://www.sumatrapdfreader.org/prerelease.html
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
