### ISSUE TITLE
ZoomLevels not honored in zoom menu

### ISSUE THREAD

**Issue by jesuslop** [sumatrapdfreader/sumatrapdf#2502]
I added 300 to the ZoomLevels setting of the file that opens in advanced options, but even after retarting there is no 300 entry in the zoom menu. Sumatra 3.1.2.

**Comment by GitHubRulesOK** [comment]
it works just not listed duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/2270#issuecomment-1000382101

@kjk previous was closed and there is your open issue https://github.com/sumatrapdfreader/sumatrapdf/issues/2237 to which this could perhaps be added ?

**Comment by kjk** [comment]
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/4432
