### ISSUE TITLE
Windows sandbox scale of installer

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2506]
Running installer inside windows sandbox has noticeably different appearance, but other dialogs seem to be scaled equally inside and outside sandbox?

![image](https://user-images.githubusercontent.com/12754913/165005842-6d54579a-bceb-4bf6-8548-798bfaf7ffb4.png)
![image](https://user-images.githubusercontent.com/12754913/165006039-91fabfb9-ac97-4d49-addc-62e717a7aa21.png)

**Comment by kjk** [comment]
Not familiar with sandbox, how do I run installer inside the sandbox?

**Comment by GitHubRulesOK** [comment]
Sandbox is win 10 / 11 extra feature where there is some limitations to provide a "web safe" virtual machine, on this new kit its faster than main OS because no bloat yet as I can start with new registry each time I run however this is about 11 days old and still blindingly fast.

**Comment by kjk** [comment]
Thanks, that seems very useful for testing the installer.

**Comment by GitHubRulesOK** [comment]
My wsb includes desktop folders
```
<Configuration>
<vGPU>Enable</vGPU>
<Networking>Default</Networking>
<MappedFolders>
   <MappedFolder>
     <HostFolder>C:\Users\K\Desktop\SandBox</HostFolder>
     <ReadOnly>false</ReadOnly>
   </MappedFolder>
</MappedFolders>
<LogonCommand>
   <Command>C:\users\WDAGUtilityAccount\Desktop\SandBox\SB_Ini_2.bat</Command>
</LogonCommand>
</Configuration>
```
and the bat includes a silent install then custom settings and the firefox plugin 🙂 for latest 32bit palemoon or 64bit waterfox classic

```
C:\Users\WDAGUtilityAccount\Desktop\SandBox\SumatraPDF\latest\SumatraPDF-prerel-64-install.exe -s -d "c:\program files\SumatraPDF" -with-filter -with-preview -log
md C:\Users\WDAGUtilityAccount\AppData\Local\SumatraPDF
copy /y C:\Users\WDAGUtilityAccount\Desktop\SandBox\SumatraPDF\SumatraPDF-default.txt C:\Users\WDAGUtilityAccount\AppData\Local\SumatraPDF\SumatraPDF-settings.txt >>C:\Users\WDAGUtilityAccount\Desktop\temp.log
cd C:\Users\WDAGUtilityAccount\Desktop\SandBox\SumatraPDF\browser_plugin Install_x32.bat
dir C:\Users\WDAGUtilityAccount\AppData\Local\SumatraPDF >>C:\Users\WDAGUtilityAccount\Desktop\temp.log
```

**Comment by kjk** [comment]
It happens outside of sandbox as well and is related to DPI scaling.

With DPI scaling of 100%, the installer window is fine.

With DPI scaling of 125% (or more, I'm guessing) , the installer window is too small to fit the text.

Most likely I just need to DPI scale the installer window.

**Comment by GitHubRulesOK** [comment]
@kjk Thanks

Side comments, FYI on other different sandbox behavior, some of which can be expected to raise related comment/issues

- MuPDF-GL does not seem to work but SumatraPDF does
<strike>- There is no MSPaint support thus Heic plugins don't appear to function as dependent on that feature</strike> HEIC works because MSPaint was restored in more recent versions
- There are no native printers (only FAX!) thus no MS Print to PDF but browser PDF printing works fine in headless Edge
