### ISSUE TITLE
Close Sumatra PDF when last tab is closed?

### ISSUE THREAD

**Issue by GithubUser99999999** [sumatrapdfreader/sumatrapdf#2510]
Is there any advanced options command with which it is possible to set Sumatra PDF to close once the last tab is closed? It is *so* annoying that it always remains open and must be closed manually...

**Comment by GitHubRulesOK** [comment]
depends how you may have set other choices like remember files but if there is only one tab then close window (top right X or Alt F4 or CTRL+Q i.e. not the tab) will not (should not, by legacy design) reopen that tab next time its started unless you open that file again.

**Comment by GitHubRulesOK** [comment]
@kjk since the idea of closing last tab is to go back to start screen

 can I delete this comment first and consider this a non issue and move to discussion ?

**Comment by GithubUser99999999** [comment]
I have indeed posted this in the wrong tab since this is not a bug, I am sorry!

Regarding the topic: I am really desperately looking for a way to close the entire programm once I hit this particular X button. It drives me nuts that it doesn't close the application. It's possible to do that in FoxitReader and I am trying to switch to SumatraPDF. 

![Untitled](https://user-images.githubusercontent.com/101017273/165879889-c67a7d5b-9c56-41bb-8c0a-3243c12e188c.png)

Isn't there any advanced option like "exit_on_last_tab_closed 1" or something?

**Comment by kjk** [comment]
`q` already does that and in pre-release you can bind `CmdCloseCurrentDocument` to any other keyboard shortcut https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts

No plans beyond that.

**Comment by GithubUser99999999** [comment]
I work with people who have certain motor impairments and they (slowly) use a mouse cursor through different HID devices and cannot simply use hotkeys. I myself would also like to use a mouse-based solution since not everyone is a hotkey aficionado and I often don't have access to an attached keyboard.

I mean, giving such an option surely wouldn't be hard to implement. Can you at least explain why it's apparently not wanted? Did I miss something supposedly obvious here?
