### ISSUE TITLE
crashed on opening second instance, Windows 10

### ISSUE THREAD

**Issue by kahldune** [sumatrapdfreader/sumatrapdf#2514]
https://gist.github.com/kahldune/c7b519b507015b5c12d06cfece491ceb

The file it was attempting to open was PDF, Python Crash Course 2nd edition

Good luck, and thank you for your work on this project.  Sumatra PDF is the best!

**Comment by kjk** [comment]
I believe I've already fixed this crash in latest pre-release.

Please re-open if it happens again. Preferably please also provide step-by-step instructions on how to reproduce the crash.
