### ISSUE TITLE
Cannot Change FontName In PreRelease & Stable

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#2520]
I'm trying to change the font on my PDF to "RussellSquare" but it's not working ! Only the Bookmarks (TOC) panel is in the "RussellSquare" font. I've done this before on the Stable build & pretty sure it can be done. Any fixes\ thoughts\ suggestions ? The PDF in question is "Windows Internals, Part 2 (Developer Reference) by Andrea Allievi, Alex Ionescu, Mark Russinovich, David A. Solomon.pdf"

**Comment by GitHubRulesOK** [comment]
No way to change a PDF font in a pdf reader, without using a PDF editor. potentially a PDF reader may on occasions substitute for fonts when bad or missing (not included) but not otherwise.

The Author must include the font (or subset) inside the PDF for it to be used, where defined.
