### ISSUE TITLE
Bad admin user install

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2521]
I and possibly many users run in super-user mode, that is single admin user, but expect to elevate as required.

So using script or double click installation it starts in elevated user mode but not started as Administrator)
The installer shows for a previous installation this state where I select optional feature.

![Screenshot 2022-05-02 233022](https://user-images.githubusercontent.com/12754913/166337713-fa84bb92-3cbf-47a7-a705-760fcb004420.png)

On running without having previously selected run as admin nor selecting all users (I am the only one) I get (probably correctly) this

![Screenshot 2022-05-02 233106](https://user-images.githubusercontent.com/12754913/166337870-afe68ac1-010a-4aed-aa1a-e6840c1d02c1.png)

obviously if I remember to select all users the install require higher elevation and am reminded by the shield

![Screenshot 2022-05-02 234026](https://user-images.githubusercontent.com/12754913/166338231-36bae13d-ee0f-4ce0-94bd-9abe53e55573.png)

Related (was ? previous mention when updating) the second run installation screen on completion is **hidden** by other desktop windows as not "on top" adding to confusion

**Comment by kjk** [comment]
I don't understand the exact scenario and what the issue is.

Installing to `%PROGRAMFILES%` will fail unless `all users` because it requires elevation. That's expected.

There is an issue if previous install was to `%PROGRAMFILES%`. Technically pre-3.4 is `all users` install so maybe I should default `all users` installation or uninstall previous version.

**Comment by GitHubRulesOK** [comment]
You are correct there is technically no "issue", administrative users should know better, but we are lazy and just click the minimum thus shoot selves in foot when given a half cocked gun. It is not just "pre-3.4", it any previous install where program files was the prior location.

**Comment by kjk** [comment]
Better expressed in #2525
