### ISSUE TITLE
error message "couldn't get printer name" pops-up when canceling print, through the print-dialog

### ISSUE THREAD

**Issue by eladkarako** [sumatrapdfreader/sumatrapdf#2522]
<img src="https://user-images.githubusercontent.com/415238/166406929-1f374a10-b091-4eb4-9907-25d5b6692185.png">

clicking cancel brings up an error message.

<hr/>

0. was pointing to a (another) pdf printer it that matters (should not be since it is the system's print-dialog).
1. Windows `10.0.19044.1469`.
2. tried all, `v3.3.3` / prerel `14508`, built on `2022-05-02` / `x86` and `x64`. portable and normal installation.
3. it is not related to printing isolation (I've disabled it <sub>(removed the certificate and overridden the <a href="https://github.com/eladkarako/manifest">manifest</a>)</sub> and it still happens).

**Comment by GitHubRulesOK** [comment]
Hmm not sure what conditions can lead to the warning, the message means that the default printer was not a valid fallback
With other apps its perhaps clearer as 
![image](https://user-images.githubusercontent.com/12754913/166471426-15afecce-0f08-4ea1-9fef-3f08cb0bc268.png)
![image](https://user-images.githubusercontent.com/12754913/166472118-7f9884b3-b7be-40e1-ae0d-2985954034cb.png)

**Comment by eladkarako** [comment]
might be a leak of uncatched exception through the next nearest catch, so it does not have to make sense either.. ;)

**Comment by GitHubRulesOK** [comment]
I get that message on windows 7 32 bit - 11 64 bit when cancel 
SumatraPDF uses a very simplistic print method of asking default printer for its paper size etc. If it does not respond then the message is correct the printer did not identify anything via its name.

@kjk this only seems to be in recent 3.4 pre-releases 
I could not emulate that behavior on 3.3.3
