### ISSUE TITLE
[feature request] making it easier to use (optionally larger toolbars, and larger gap between continues pages)

### ISSUE THREAD

**Issue by eladkarako** [sumatrapdfreader/sumatrapdf#2523]
for the sake of elderly/visually impaired users,  
it will be a lot easier if the gap space between continues pages may be adjusted,  
and something like a box-shadow could be applied to a page's outter-layer,  
so it will be more-clear visually that a page has changed,  
gap being few pixels of gray separator-line is hard to notice through speedy scrolling,  
even if for standard users (it looks like a part of the page's style, especially if the pdf has been exported from a monochrome website, which is the default pdf-printer definition for Microsoft edge and Google chrome/chromium).

<img width="808" alt="2022-05-03_082415" src="https://user-images.githubusercontent.com/415238/166407894-64988dc9-458e-49c8-b50a-ab367b39dcc6.png">  

<img width="923" alt="2022-05-03_082516" src="https://user-images.githubusercontent.com/415238/166407896-86c33903-8411-448a-a06a-c02365788dbf.png">

edit: 
I've changed `PageSpacing` from `4 4` to `40 40` (`FixedPageUI` + `ComicBookUI`),  
so it looks like this now:  
<img width="503" alt="2022-05-03_084052" src="https://user-images.githubusercontent.com/415238/166409009-f41bd4ce-783c-4790-85cc-419679561cb5.png">

a 3d-shadow around the pages still would be helpful too though.

<hr/>

on large DPI screens the toolbar is so tiny it is really hard to distinguish what are the buttons do,  
is there an option to make it larger?

setting the DPI of the operation system to about 150%-300% (text and application) does not seems to matter to the application.

setting `CustomScreenDPI = 200` does not matter either

edit1: I've changed `ToolbarSize = 18` to `ToolbarSize = 40`
edit2: I've changed `UseTabs = true` to `UseTabs = false`
edit3: I've kept the custom screen dpi on 200 even though it does not seems to do anything.

now from this:  
<img width="479" alt="2022-05-03_083821" src="https://user-images.githubusercontent.com/415238/166409309-33697c0e-6fa4-4f77-a871-95a970585a67.png">

it look like this:  
<img width="644" alt="2022-05-03_084433" src="https://user-images.githubusercontent.com/415238/166409339-9ff59415-f795-4cc8-9e22-7787f8f0309f.png">

<hr/>

note1: I've used the "advanced settings" (portable version saves it into `SumatraPDF-settings.txt` in the same folder).

note2: even though I've managed to solve it (in the middle of opening this issue), I'll keep it here, for the sake of others looking for the same thing,  
since those are not available through the UI in a straightforward way.

**Comment by GitHubRulesOK** [comment]
For changing the surround 3D 4 color alpha gradient shadow per page would require slowing down display significantly as each needs calculation and controlling a much  wider area however there is very simple "graduated color" for whole PDF document background
```
GraduatedColors = #ff0000 #0000ff
```

however beware there can only be 1,  2, or 3. and it is from start first to end last page thus for example you have 2 pages the gap between page 1 and page 2 would not be well defined thus using a single colour (without graduation) is often best.

![image](https://user-images.githubusercontent.com/12754913/166454155-a36158fa-ea7c-4e6f-9b74-803e1f406242.png)

**Comment by eladkarako** [comment]
that's not very useful. But you've meant well and that's what matter.

**Comment by GitHubRulesOK** [comment]
@eladkarako 
Very sorry my bad not checking the manual that should have been Gradient Colors (one word)
```
GradientColors = #ff0000 #0000ff
```
