### ISSUE TITLE
Pre-release versions don't recognize any formating like Italic and such in certain epub books

### ISSUE THREAD

**Issue by Pocokk** [sumatrapdfreader/sumatrapdf#2527]
Dear kjk,

[Here is the example file ](https://we.tl/t-3XALWo6qXx) ([backup here](https://fichub.net/cache/epub/rxtkvfgi/Silent_Measures_by_Eirian_Erisdar-rxtkvfgi.epub?h=b953e9912169e19eeb59278cbc4d1c4d)) currently using the build version 14509, built on 2022-05-03 and every text is just plain simple[ compared to the PDF version](https://we.tl/t-jX9IXKjXMg) ([backup here](https://fichub.net/cache/pdf/rxtkvfgi?cv=26&eh=b953e9912169e19eeb59278cbc4d1c4d)) where I can see bold/italic and other text modification.

You mentioned a new engine being used/developed in these builds, can you somehow modify them to recognize the epub format properly, regarding the book's options/config or not? For example using an ebook reader on my phone called "ReadEra" shows the formatting properly.

Here are two pictures that show what I see on [epub](https://i.imgur.com/6L6XcJS.png) vs [pdf](https://i.imgur.com/y1E1aV0.png) versions.

**Comment by GitHubRulesOK** [comment]
@kjk 
is there some way a user can still use legacy layout as optional alternative to MuPDF?
![image](https://user-images.githubusercontent.com/12754913/166713377-f0c98f63-60a3-46a9-a833-0d96965c8b7e.png)

**Comment by kjk** [comment]
Confirmed italic / bold don't show up with mupdf.

Asking people to choose between 2 engines is too much. Need to look into why mupdf doesn't display it well.

**Comment by kjk** [comment]
I think the file is correctly parsed but we're missing `Charis SIL` font and instead we use a font that doesn't look bold / italic even though it is.

**Comment by kjk** [comment]
Adding `Charis SIL` font doesn't help. mupdf 1.9.1 also doesn't render it as bold / italic so there's something there.

**Comment by kjk** [comment]
Using `mutool trace .epub` I get:
```
    <span font="Nimbus Sans Regular" wmode="0" bidi="0" trm="11 0 0 -11">
        <g unicode="C" glyph="C" x="41" y="97.79" adv=".722"/>
        <g unicode="u" glyph="u" x="48.942" y="97.79" adv=".556"/>
        <g unicode="l" glyph="l" x="55.058" y="97.79" adv=".222"/>
        <g unicode="i" glyph="i" x="57.5" y="97.79" adv=".222"/>
        <g unicode="n" glyph="n" x="59.942" y="97.79" adv=".556"/>
        <g unicode="a" glyph="a" x="66.058" y="97.79" adv=".556"/>
        <g unicode="r" glyph="r" x="72.173999" y="97.79" adv=".333"/>
        <g unicode="y" glyph="y" x="75.837" y="97.79" adv=".5"/>
    </span>

    <span font="Nimbus Sans Regular" wmode="0" bidi="0" trm="11 0 0 -11">
        <g unicode="W" glyph="W" x="11" y="57.090005" adv=".944"/>
        <g unicode="e" glyph="e" x="21.383999" y="57.090005" adv=".556"/>
        <g unicode="l" glyph="l" x="27.5" y="57.090005" adv=".222"/>
        <g unicode="c" glyph="c" x="29.942" y="57.090005" adv=".5"/>
        <g unicode="o" glyph="o" x="35.442" y="57.090005" adv=".556"/>
        <g unicode="m" glyph="m" x="41.558" y="57.090005" adv=".833"/>
        <g unicode="e" glyph="e" x="50.721" y="57.090005" adv=".556"/>
    </span>
```

This is for:
```
<h2>Culinary Instinct</h2><p/><div><p><strong> Welcome to </strong> <em> <strong> Silent Measures</strong>
```
Both `h2` and `strong` should be bold per `html_default_css` in `html-parse.c`.

There is custom css in `main.css` but it doesn't over-write `strong` style and has `h2` as bold.

**Comment by kjk** [comment]
I think the issue is: custom css has font as:
```css
body {
    font-family: Verdana, Helvetica, Arial, sans-serif;
}
```
`fz_lookup_builtin_font` called from `fz_load_html_font` doesn't recognize `Verdana` so we get `Helvetica` which is `NimbusSans`.

Except instead of using bold version of the string, we get `Nimbus Sans Regular`, as per the trace.

**Comment by kjk** [comment]
Ok, the issue is that `fz_load_html_font` would return approximate font `Nimbux Sans Regular` for `Nimbus Sans Bold`  even though an exact match exists and would be loaded by `fz_lookup_builtin_font`.

**Comment by kjk** [comment]
[bug2527-KfdkHJO92a.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8628829/bug2527-KfdkHJO92a.zip)

**Comment by kjk** [comment]
Also opened mupf https://bugs.ghostscript.com/show_bug.cgi?id=705281 in case they will have better fix

**Comment by Pocokk** [comment]
I can confirm that it is showing the formatting without any problem, thank you!
