### ISSUE TITLE
Could you mind adding a function which can create a link in the pdf file?

### ISSUE THREAD

**Issue by sl0000** [sumatrapdfreader/sumatrapdf#253]
Could you mind adding a function which can create a link in the pdf file?

**Comment by kjk** [comment]
I don't understand the request.

**Comment by sl0000** [comment]
SumatraPDF can show the links which defined by the Foxit reader or the Acrobat reader. It will be very nice if I could create links in the SumatraPDF. 

For example, after choosing a rectangle using Ctrl + left mouse then popup a menu item which name is "Add link...". A dialog box will provide user a user interface to input target URL or target pdf file name.

**Comment by kjk** [comment]
Sumatra is a PDF reader, not an editor, so we don't have plans to add such editing functionality.

**Comment by GitHubRulesOK** [comment]
Duplicated by https://github.com/sumatrapdfreader/sumatrapdf/issues/1706 since similar annotations are under development and this is a basic bookmark requirement to jump to referenced or named destinations (internal and external)
