### ISSUE TITLE
Latest Pre-release build 14531 install is stuck and using resources (CPU,RAM) in an ever increasing way

### ISSUE THREAD

**Issue by Pocokk** [sumatrapdfreader/sumatrapdf#2530]
After the latest epub fix, I did the regular "check for update" and started the install, when I encountered a bug that never happened before: the setup process is stuck/halted at 80-85% (can't say exactly as there are no numbers on the install bar) and the RAM usage started to ramp up, from a couple dozen megabytes to couple hundreds, and now in the gigabytes. Same with CPU, it barely used 5-10%, now its above 15-17%. (using Windows 10 64 bit, Admin account, CPU intel i7 6700k). 

The "Install for all users" option wasn't selected.

[Here is the task manager picture about it](https://i.imgur.com/xdY2VQG.png) after 5 mins or so waiting.

**Comment by GitHubRulesOK** [comment]
Thanks for feedback, In theory new installer should have built log of any fail, but if you had to abort that may not have completed.

If written it would help to post in a gist or zip it should be in explorer address **%userprofile%/appdata/local** as sumatra-install-log.txt so copy before overwritten ?
The dev may also need some more info about prior settings such as system bitwise previewer active user level etc.

**Comment by Pocokk** [comment]
As it is not an outright "fail" (there is no error message, just a hanging process) there is no sumatra-install-log.txt created.

**Comment by Pocokk** [comment]
Now I opened the program and It seems the installer was successful at the end despite the fact that I closed it (alt f4), it managed to finish the setup.[ (picture)](https://i.imgur.com/OoR5I9I.png)

**Comment by GitHubRulesOK** [comment]
@kjk am reopening as I am currently getting this hung at 50% CPU behaviour on each windows 7 update

**Comment by GitHubRulesOK** [comment]
@kljk 
currently 14452 and now 14453 available is there any thing you want me to check on this run?

**Comment by kjk** [comment]
Could you check if this is due to excessive logging i.e. start installer with `-log` command and see if the log file grows quickly.

If yes, post portion of the log (just enough to see what is excessively logged).

**Comment by kjk** [comment]
Also, at which point in the installation process does it hang? 
On start? After clicking "Install"? Which options are selected?

**Comment by GitHubRulesOK** [comment]
@kjk looking at why an installer might have problems on that unit
1) I do not have access to all users I only have access to own directory's such as local appdata and installer started elevating
2) I have a different temp directory to normal so there is no higher level of directory other than root
3) installer attempt are in that temp directory and have zero byte tmp file plus next the matching.tmp.exe
4) but not for the latest run there is a newer sum29B.tmp (oddly 3 random different to others with 4 random chars)
5) as OP above I aborted and the time of the seemingly correct install in program files is the same time as the last paired files in temp before the odd file which may have the time of aborting 10 mins later ??

**Comment by GitHubRulesOK** [comment]
sorry comms cross over in time
 so just to be shur it is auto-update fails thus to log will need to download and run installer
progress bar runs about 75%
Lazy selection chose preview (needs elevation) but naturally there are no "all users"  to need tick boxing

**Comment by GitHubRulesOK** [comment]
@kjk This time run from cmd line and seemingly hung per image above SumatraPDF with logging was not a heavy user but stuck along with cmd constantly running and the log escalating with continuous lines of

```
LoggedDeleteRegValue(HKEY_LOCAL_MACHINE, Software\Classes\.tif\OpenWithProgids, SumatraPDF) => 2
LoggedDeleteRegKey(HKEY_LOCAL_MACHINE, Software\Classes\.tif\OpenWithList\SumatraPDF.exe, 0) => 2
LoggedDeleteRegValue(HKEY_LOCAL_MACHINE, Software\Classes\.tif\OpenWithProgids, SumatraPDF) => 2
LoggedDeleteRegKey(HKEY_LOCAL_MACHINE, Software\Classes\.tif\OpenWithList\SumatraPDF.exe, 0) => 2
LoggedDeleteRegValue(HKEY_LOCAL_MACHINE, Software\Classes\.tif\OpenWithProgids, SumatraPDF) => 2
LoggedDeleteRegKey(HKEY_LOCAL_MACHINE, Software\Classes\.tif\OpenWithList\SumatraPDF.exe, 0) => 2
```

**Comment by kjk** [comment]
Thanks, should be fixed in the next build (in about an hour).
