### ISSUE TITLE
Request to "cool down" the red color while showing the message to save annotations "You have unsaved annotations"

### ISSUE THREAD

**Issue by subashmu** [sumatrapdfreader/sumatrapdf#2532]
**The whole UI of sumatra is super cool. But the red color message reminding to save annotations is actually a distraction due to the color stands out from rest of the UI.**

**_I would recommend grey color as it blend well with background well._**

<img width="959" alt="red_annotation" src="https://user-images.githubusercontent.com/86005956/166935423-834b943b-ad6e-4bcd-adc8-fb3d254b04ba.png">

**Comment by GitHubRulesOK** [comment]
Personally agree the comment may be better written as Flashing ***WARNING don't save edits until ALL are done*** but that's my one and a half cents

**Comment by tactilis** [comment]
Flashing?

Surely it should be a scrolling marquee.  Because everyone _loves_ a marquee ;-)

But I agree with **"until ALL are done"**

**Comment by GitHubRulesOK** [comment]
I think the message is useful when opening a fill that is detected as needing save later due to changed appearance
MuPDf uses a simplistic `*` in the headline to signal `changed on open` or due to `fixed` or due to `annotation`
