### ISSUE TITLE
SumatraPDF pre-release sending and receiving data to IP 216.24.57.1

### ISSUE THREAD

**Issue by OAStubby** [sumatrapdfreader/sumatrapdf#2540]
The problem occurs with all epubs.
[Sigil User Guide 2022.02.01.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8642913/Sigil.User.Guide.2022.02.01.zip)
![SumatraPDF](https://user-images.githubusercontent.com/37912680/167196303-20c7080c-61a9-4fa4-8e5b-d1f19c25b1ea.jpg)

**Comment by kjk** [comment]
I can't reproduce this using LiveTcpUdpWatch and 14547. I opened the epub file, did a bunch of scrolling, changing views, clicking links and never triggered sending the report.

Can you provide more information:
* when exactly does that happen? After you open a file, after some specific action?
* what are your view settings? can you post Sumatra screenshot right after the send happens
* did you do any customization in advanced settings? If yes, what kind? Can you send your modified settings file

**Comment by kjk** [comment]
Related discussion: https://github.com/sumatrapdfreader/sumatrapdf/discussions/2539

**Comment by OAStubby** [comment]
After open a file.
![SumatraPDF](https://user-images.githubusercontent.com/37912680/167203181-78088664-1e40-45b7-84b1-f949e175f5ed.jpg)
[SumatraPDF-settings.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8643145/SumatraPDF-settings.zip)
[crashinfo.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8643150/crashinfo.zip)

**Comment by kjk** [comment]
The difference from my setup is not using tabs. That being said, still can't reproduce.

**Comment by kjk** [comment]
It would be helpful to know what data was sent.
I can't see how to do it with LiveTcpUdpWatch (it has option to capture the data but no option to view it?)
If you could capture the content (using this or some other tool) and attach, it would help.

**Comment by OAStubby** [comment]
TCP/IP Streams
[SumatraPDF.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8643276/SumatraPDF.zip)

**Comment by kjk** [comment]
Unfortunately this is compressed/encrypted version so not usable. Is there an option to get unencrypted/uncompressed data?

**Comment by GitHubRulesOK** [comment]
@kjk although not usable as such those packets in zip do seem to include on occasion `updatecheck.io` and authorization snippets

perhaps no help but using 64 in Win11 sandbox if asking for update I  get these entries but at no other time, nor the quoted address (different dchp?)
```
Process ID	Process Name	Protocol	Local Port	Local Address	Remote Port	Remote Port Name	Remote Address	Received Bytes	Sent Bytes	Received Packets	Sent Packets	Receive Speed	Send Speed	Connect Time	Disconnect Time	Accept Time	Connections Count	Disconnect Count	Process Path	Remote IP Country	
8468	SumatraPDF.exe	TCP IPv4	52488	192.168.43.248	443	https	104.26.8.244	5,227	526	5	3			5/6/2022 10:03:13 PM.496	5/6/2022 10:05:03 PM.479		1	1	C:\Program Files\SumatraPDF\SumatraPDF.exe		
8468	SumatraPDF.exe	TCP IPv4	52489	192.168.43.248	80	http	93.184.220.29	798	236	2	1			5/6/2022 10:03:13 PM.551	5/6/2022 10:05:03 PM.554		1	1	C:\Program Files\SumatraPDF\SumatraPDF.exe		
```

**Comment by kjk** [comment]
I've added an easy way to get this information:
* upgrade to at least 14549
* start SumatraPDF with `-log` flag
* load epub file
* quit SumatraPDF

Upon exit, a log file will be opened in Notepad. It should contain the callstack for this (should include `_uploadDebugReportIfFunc`).

Could you provide this log?

**Comment by kjk** [comment]
I've fixed 2 causes of sending reports. Please upgrade to 14555 or later.

If this still happens, please create a new issue and attach log.

Easiest way to get the log:
* use command palette (`Ctrl + K`)
* select "show log"
* this should open the log file in notepad

This log should contain a callstack that will help me to figure out the issue.
