### ISSUE TITLE
Pre-Release Installer Version Stalls at 75% !! Needs Fixing

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#2542]
The latest Pre-Release Installer version doesn't fully install, stalls midway through. Please fix ASAP !

**Comment by kjk** [comment]
Which version? 

This should be fixed in latest pre-release 14550 or later.

See https://github.com/sumatrapdfreader/sumatrapdf/issues/2530

**Comment by alienfxfiend** [comment]
O.K. it installed, I ran it as Admin from another folder.
