### ISSUE TITLE
The current version does not open fb2.zip files.

### ISSUE THREAD

**Issue by Dharmainiciativ** [sumatrapdfreader/sumatrapdf#2547]
The current version does not open fb2.zip files, giving an error when opening.
Latest SumatraPDF pre-release build version 14559, built on 2022-05-08 , commit [1349c4b82551a2ca57a55b35dbb41865f8bf8d07](https://github.com/sumatrapdfreader/sumatrapdf/commit/1349c4b82551a2ca57a55b35dbb41865f8bf8d07) :

**Comment by GitHubRulesOK** [comment]
generally its the .zip extension that throws the sniffer off so try rename to .fb2z
[Around the World in 28 Languages.fb2.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8647803/Around.the.World.in.28.Languages.fb2.zip)

@kjk 
perhaps allow for the other common naming by re-oder detection ?

**Comment by Dharmainiciativ** [comment]
Sorry, but why should I change the extension of a huge number of files to *.fbz, if everything worked in previous versions?
You probably just don't understand how common the *.fb2.zip extension is.

**Comment by GitHubRulesOK** [comment]
@Dharmainiciativ 
I agree it should not matter my suggestion was short term work around

**Comment by kjk** [comment]
fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/383bf8747f71d677230628e7624c9e5dfe521a99
