### ISSUE TITLE
Add next and previous documents buttons in toolbar

### ISSUE THREAD

**Issue by lRadha** [sumatrapdfreader/sumatrapdf#2548]
As per now, CTRL + SHIFT + RIGHT and CTRL + SHIFT + LEFT hotkeys are assigned for next and previous documents respectively. But, my concern is to add buttons for these hotkeys in toolbar or in menus so that one using only mouse can surf from one document to another easily.

**Comment by kjk** [comment]
No plans to add more buttons to toolbar.

In pre-release you can also use command palette https://www.sumatrapdfreader.org/docs/Command-Palette

**Comment by lRadha** [comment]
At least update the menus for this, if possible.
