### ISSUE TITLE
Sumatrapdf freezes repeatedly while reading different pdf and djvu's after upgrading to windows 10 home.

### ISSUE THREAD

**Issue by ericv911** [sumatrapdfreader/sumatrapdf#255]
I have been using SumatraPDF since a year now.  I started using it on a single core 32-bit Vista PC, where it worked perfectly. 
I then acquired a new laptop with windows 8.1 which caused some minor issues in the functioning of Sumatra. Sudden crashes mainly, but nothing serious and all in all maybe three times in 4 months . But now after upgrading to WIndows 10, I have encountered the following problem repeatedly maybe twice or thrice a day, with different kinds of documents. : 

One of the processors, where SumatraPDF is apparently running on, starts to use 100 % capacity and Sumatra just freezes.. All the other applications still work perfectly ok,  Then maybe after 5 minutes or so. i just quit the program using task manager. 

My laptop is an asus r556 L, i7. with an Nvidia 820 M graphics card and 6 GB of memory. Nothing fancy, but an ok laptop. The only other applications running at the time were Chrome and Visual Studio Express Community.

**Comment by kjk** [comment]
There's not much to go on.

Which version of Sumatra is this?

Does it happen with latest pre-release version (http://www.sumatrapdfreader.org/prerelease.html)?

Since you mentioned running Visual Studio, can you attach a debugger when the freeze happens and attach a callstack (see https://github.com/sumatrapdfreader/sumatrapdf/wiki/Debugging-Sumatra for more info).

**Comment by ericv911** [comment]
currently using Sumatra v3.0 If it freezes again i'll send you what windbg has to say. Although in the meantime I think found the program responsible for the freeze.  After disabling  MsMpEng.Exe, microsofts antimalware program, Sumatra hasn't frozen again.  With all together better performance of the system.  Sumatra was however the only program freezing.u I'll test a bit with MsMpEng.Exe enabled and if the problem happens again. i'll send you the windbg call stack data.



Date: Fri, 7 Aug 2015 12:00:50 -0700

**Comment by ericv911** [comment]
Another crash. This time I had one .MOBI e-book open.   I had this particular.mobi and other epub, mobi and pdf-files ,open for the last  2 weeks. No problems. Just this one.
I get the following message :  
Unhandled exception at 0x778DA4E5 (ntdll.dll) in SumatraPDF.exe: 0xC0000005: Access violation writing location 0x007B0ED8.
The picture is all i got from the callstack and part of the disassembly.  Sumatra symbols are installed in the Sumatrapdf folder next to the .Exe.  I hope it helps you. Do you also need the pdf I was reading? 
Best regards 
Eric Vosselmans



Date: Fri, 7 Aug 2015 12:00:50 -0700

**Comment by kjk** [comment]
There is no picture with callstack?

**Comment by ericv911** [comment]
that was all there was.    I'll try and get more the next time it happens.  I normally debug with x64-dbg. But ended up doing it with windbg in visual studio, so probably i did something incorrect.  
Anyway. i love the program. Probably just some glitches with windows 10 which will get ironed out in due time.



Date: Fri, 28 Aug 2015 09:47:04 -0700

**Comment by kjk** [comment]
Not enough information for progress.
