### ISSUE TITLE
Potential problem with DjVu preview

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2550]
On windows 7 x32 (and possibly others)
There seems to be problems when previewer is parsing thumbnails/previews  in areas containing DjVu files, am struggling to find exact culprits as previewer kicks out on all files so need to better isolate.

![image](https://user-images.githubusercontent.com/12754913/167514506-45c46163-bdb4-4e00-a337-8b74a6d8e667.png)

Preview handler
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	prevhost.exe
  Application Version:	6.1.7601.17514
  Application Timestamp:	4ce796ac
  Fault Module Name:	libmupdf.dll
  Fault Module Version:	3.4.0.0
  Fault Module Timestamp:	6276db14
  Exception Code:	c0000005
  Exception Offset:	000f8e5e
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

```

Com Surrogate
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	DllHost.exe
  Application Version:	6.1.7600.16385
  Application Timestamp:	4a5bc6b7
  Fault Module Name:	libmupdf.dll
  Fault Module Version:	3.4.0.0
  Fault Module Timestamp:	6276db14
  Exception Code:	c0000005
  Exception Offset:	000f8e5e
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

```
files
[00DD18981126_2700000300000058000001.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8655966/00DD18981126_2700000300000058000001.zip)

**Comment by kjk** [comment]
Hmm, can't reproduce it on my win 10 64-bit.

**Comment by GitHubRulesOK** [comment]
On 11 the files behave inside sandbox only showing icons
 but outside sandbox most thumbnails work except one !
seen similar before so wonder if that is a herring or cause 
Any way you see if its different
![image](https://user-images.githubusercontent.com/12754913/167537101-e61c9a6f-9208-482f-9a73-c2db8b37370b.png)

**Comment by GitHubRulesOK** [comment]
ok closing as not reproducible on mainstream supported (7 is eol) Windows 10x64  is OK
