### ISSUE TITLE
Current Keyboard setting for invert

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2553]
@kjk 
It looks like Shifted I for invert has dropped back to unshifted i

Also the manual shows historic entry
```
i - show page information in full screen/presentation mode
```
but generally works showing numbers in other modes too ?

**Comment by kjk** [comment]
> It looks like Shifted I for invert has dropped back to unshifted i
Yes. I figured it's used more often so should be easier to access

re: manual: you're right, thanks, I've dropped "full screen/presentation mode" part
