### ISSUE TITLE
Command palette improvements

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2554]
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2476#discussioncomment-2723025

Some ideas to improve command palette:
* [x] for opened files, only show file name (not full path)
* [x] don't remove duplicate file names (files opened in multiple tabs / windows). Maybe add something to distinguish them (tab number? window number if not using tabs?)
* [x] file name is most important but might be cut off in long file paths. Show file name first and then maybe directory e.g. `foo.pdf (c:\Users\kjk\Documents)`. Or maybe show directory in smaller font and gray color
* [x] if typed filter starts with `>`, only show commands (lots of files might obscure commands) `Ctrl + Shift + K` would enter this. Similar to Visual Studio Code.
* [x] add `Toggle Table Of Content` as synonym of `Toggle Bookmarks`.
* [x] make command palette window wider and longer

**Comment by nutnutwin** [comment]
Hi, Thank you for the great work
before this update I never thought of Command Pallete with 
- Go to File...
- Show All Commands
(like VSCode) Combined together
and I like this feature

> if typed filter starts with >, only show commands (lots of files might obscure commands) Ctrl + Shift + K would enter this. Similar to Visual Studio Code.
Yes, specifying "commands only" would be strongly appreciated too. 

Thank you so much

**Comment by GitHubRulesOK** [comment]
@nutnutwin 
most of above are already active including **`>`** but not numbered windows/tabs

![image](https://user-images.githubusercontent.com/12754913/171965912-55c13c00-aa41-423e-8ee6-2102371d3166.png)

**Comment by nutnutwin** [comment]
@GitHubRulesOK 
Hi, thank you for the info
as for ｢>｣ I tried on 3.4.4 and does not seem to work? 
(I took severl screenshots, wonder if I did it wrong
<img width="382" alt="20220604_Sat -082755" src="https://user-images.githubusercontent.com/34512273/171966575-ffd10449-b74c-4dad-bce4-c985b2b05d67.png">
<img width="328" alt="20220604_Sat -082801" src="https://user-images.githubusercontent.com/34512273/171966578-852ce82c-0bf1-48a7-8b82-08034b34d01b.png">
<img width="352" alt="20220604_Sat -082815" src="https://user-images.githubusercontent.com/34512273/171966579-95654e53-90af-4a7a-80ee-9eca807635d5.png">

**Comment by kjk** [comment]
Yes, for latest features you need to use pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by nutnutwin** [comment]
@kjk hi, thank you for the reply.
Will try it later.

**Comment by nutnutwin** [comment]
@kjk Tried and it works
Thank you so much
