### ISSUE TITLE
[Feature Request] Booklet printing

### ISSUE THREAD

**Issue by Wnderer** [sumatrapdfreader/sumatrapdf#256]
I would like to print so that I have four pages on a single piece of paper, so that when I fold the paper in half the order of the pages is page 1 on the front, page 2 and 3 inside and page 4 on the back. Then I would like this to continue with rest of the pages so I can stack these folded papers, clip them with a binder clip and create a booklet. I would like to do this with my printer that only prints on one side at a time. The order of the printing would be {4,1},{8,5},{12,9},{16,13}, ..., stop flip stack print {2,3},{6,7},{10,11},{14,15},...

Thanks

**Comment by kjk** [comment]
We don't have plans to implement that.

**Comment by Sciaopersone** [comment]
Still no plans for it?

**Comment by GitHubRulesOK** [comment]
Booklet production is not a usual feature of a PDF reader but is seen in an editing PDF reader like Adobe Acrobat or Tracker Exchange etc.

There are several free command line tools to reorder pages by rotate and shuffle into a format suitable for Sumatra to feed to the spool Queue but far easier to combine those with say their own GhostScripting  outputs.

I have shown in the past such combinations are very specific to a users desires. so there was a simple option in my old https://github.com/GitHubRulesOK/MyNotes/blob/master/AppNotes/SumatraPDF/Addins/N-Up-PDF/N-Up-PDF.cmd

**Comment by cmasterdelphi** [comment]
I love Sumatra PDF but that's a feature I always have go back to Acrobat Reader. I wouldn't call it an 'editing' function. Even if you can re-arrange the pages yourself or with a script, it's nothing like the convenience of the simple selection in the printing GUI.

**Comment by GitHubRulesOK** [comment]
@cmasterdelphi 
SumatraPDF print production is not like scriptable GhostScript or heavyweight  Acrobat restricted Editor (Reader DC) with inclusive print Drivers

SumatraPDF simply asks Windows to provide the Print Dialogs supplied by the Windows Print system thus the Quality of Print Driver Decides the probabilities and Widows offers those via its Print Dialogs which now in Windows 11 are seriously impacted by Windows changes

This means the options for booklet printing must be in the Printers own settings and many do not have such advanced abilities to reorder the printing.

![Image](https://github.com/user-attachments/assets/d3ffba02-dddd-4533-bbc8-445a1b09e088)
