### ISSUE TITLE
Add arm64 build

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2566]
There is arm64 version of windows. Create a build variant for arm64.

**Comment by GitHubRulesOK** [comment]
Many lightweight credit card computer developers use basic text/PDF or PDFm image formats and use the resourceless base14 fonts of Helvetica, Times, Courier, that significantly helps with fast display, and print to serial IO. SumatraPDF is designed for windows but windows w(h)ines very slowly in a pi.

**Comment by kjk** [comment]
@Biswa96 

> * The fonts as resource addition need to be done without assembly.

I believe `nasm` supports arm64 so it should be possible to use the same trick as for x86/amd64 ?

**Comment by Biswa96** [comment]
Nope, nasm is only for x86.

**Comment by kjk** [comment]
You're right. Yasm then? (https://yasm.tortall.net/)

The build system (premake) is flexible enough to add custom compilers (that's how `nasm` is integrated).

Either yasm could replace nasm (if it's fully compatible) or be an addition just to compile the font.asm code for amd64

**Comment by wbsdty331** [comment]
Hello,
Maybe we can try it? (update libjpeg-turbo and use `yasm` instead of `nasm`)

**Comment by kjk** [comment]
Started on arm 64 support.

Todo:
* [ ] unrar, maybe upgrade to latest will fix it
* [ ] crash handler 
* [ ] memory hooking

**Comment by GitHubRulesOK** [comment]
> This issue has been linked to a Canny post: [Add arm64 build](https://sumatrapdf.canny.io/admin/board/feature-requests/p/add-arm64-build) 🎉

In Progress or Complete :-)

**Comment by kjk** [comment]
It compiles, no idea if it works.

**Comment by GitHubRulesOK** [comment]
Hmm, thats interesting what might run it Raspberry ?

**Comment by qwinsi** [comment]
I have a Windows11 ARM machine. I built it on my machine at commit https://github.com/sumatrapdfreader/sumatrapdf/commit/5d9fc739584aaae8f6318f8e4ddec283ba76691f successfully. (configuration = Release ARM64)
Here's the VS2022 output: 

> ========== Build: 24 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
> ========== Elapsed 06:33.117 ==========

The ARM64 binary executable works fine.

**Comment by kjk** [comment]
Thanks for the info @qwinsi 
Now I need to make the builds available on the website.

**Comment by kjk** [comment]
ARM 64 builds are now available via https://www.sumatrapdfreader.org/prerelease

The downside is that pre-release builds will now be updated once a day, not on every checkin.

**Comment by Biswa96** [comment]
Thank you for working on this.

Just wondering. Is the TODO in DbgHelpDyn.cpp required for normal usage? I have the diff from my previous attempt (https://github.com/sumatrapdfreader/sumatrapdf/issues/2566#issuecomment-1157818183). I can try to add those.

**Comment by kjk** [comment]
@Biswa96 any improvement (in form of PR) is appreciated

GetExceptionInfo() is not required but it does help in case of a crash.

Also, libjpeg-turbo and dav1d are compiled without arm assembly, making them slower on arm.

Not sure how to compile arm assembly with msvc toolchain - this would require reverse engineering of how dav1d is building for windows. It's ok to add a .exe of a tool, like I do for nasm.exe in bin\ directory for compiling x86 assembly.

libjpeg-turbo could use an upgrade to latest released version, which has arm assembly, I believe.

I don't have an arm device for testing which limits my ability to work on such issues.

**Comment by kjk** [comment]
run with `-crash-on-open` cmd-line arg. this will trigger a crash when opening a file.

I will also add a command to Command Palette (`Ctrl + K`) to trigger a crash and a memory corruption, for testing 

To see logs as they happen: `go run .\tools\logview\`

This is a helper program that shows all the `logf()` and `logfa()` Sumatra logs as they happen. Helpful for monitoring what happens when not running under a debugger.

Note: testing crash handler is better outside of the debugger as the debugger gets the first dibs at handling exceptions. I'm not sure I figured out how to tell Visual Studio debugger to keep going so that my exception handler (crash handling code) is executed.

**Comment by kjk** [comment]
I fixed `logview` logging from crash reporting as well

**Comment by ReptiIe** [comment]
So em.. Sumatra works on Raspberries or not? Got bit confused here 😄 
I can try to run some tests just need to know where to start.

**Comment by GitHubRulesOK** [comment]
@ReptiIe you need somebody who runs Raspberry to test (mine are not active)
If running a Windows IoT core it would be worth knowing what works
but Linux based devices have Wine for running standard SumatraPDF variants
