### ISSUE TITLE
PDF annotation borders are printed

### ISSUE THREAD

**Issue by ousia** [sumatrapdfreader/sumatrapdf#257]
Both stable release and the development version print annotation borders in PDF files.

A PDF file with annotation borders can be found at http://bugs.ghostscript.com/attachment.cgi?id=11606.

At least, annotation borders shouldn’t be printed by default.

**Comment by kjk** [comment]
Fixed in pre-release http://www.sumatrapdfreader.org/prerelease.html

**Comment by ousia** [comment]
@kjk and @zeniko, many thanks for the fix.
