### ISSUE TITLE
SumatraPDF pre-release build version 14590 Crash On Launch

### ISSUE THREAD

**Issue by OAStubby** [sumatrapdfreader/sumatrapdf#2572]
Changing even one parameter in the configuration SumatraPDF does not start.
The problem was not present in the previous build.
[SumatraPDF-settings (Not working).txt](https://github.com/sumatrapdfreader/sumatrapdf/files/8693184/SumatraPDF-settings.Not.working.txt)
[SumatraPDF-settings (Working).txt](https://github.com/sumatrapdfreader/sumatrapdf/files/8693185/SumatraPDF-settings.Working.txt)

**Comment by GitHubRulesOK** [comment]
@kjk 
unsure if relate but on last update to 14590 I got failure to launch after using all users install
 and sumatraPDF only launched after delete settings in personal localappdata.

**Comment by OAStubby** [comment]
The problem seems the same, installation for all users and SumatraPDF-settings.txt in personal localappdata.

**Comment by kjk** [comment]
Can you provide crash report?

**Comment by OAStubby** [comment]
How can I do this?
The -log flag does not work.

**Comment by kjk** [comment]
Never mind, I figured out and in this particular case there was no crash report generated. Next 14591 should be fixed.

Should be fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/a7de5c6ba80d5d5fcb5db185c3f9b942c870141d
