### ISSUE TITLE
Add configuration option for tooltips: FullPathInTooltips

### ISSUE THREAD

**Issue by terax6669** [sumatrapdfreader/sumatrapdf#2574]
Similarily to `FullPathInTitle = false` can we have `FullPathInTooltip = false` for when we hover over a tab?

**Comment by kjk** [comment]
Latest pre-release already does that https://www.sumatrapdfreader.org/prerelease

**Comment by terax6669** [comment]
@kjk 

![image](https://user-images.githubusercontent.com/19204073/168465350-523323a2-62c4-4ad0-8c9c-171da5fb8c2b.png)

- https://www.sumatrapdfreader.org/docs/Version-history no mention of this in version history for `next`.
- I am on `v3.4.14597 64-bit` and I don't see this option in `SumatraPDF-settings.txt`.
- After adding the `FullPathInTooltip = false` nothing changed.
- After re-opening `SumatraPDF-settings.txt` I can see that `FullPathInTooltip` was moved down into a section labeled `# Settings below are not recognized by the current version`.
