### ISSUE TITLE
Images in *.fb2 files are not displayed

### ISSUE THREAD

**Issue by Dharmainiciativ** [sumatrapdfreader/sumatrapdf#2575]
The current assembly does not display images in *.fb2 files.
An example file is attached
[Gippenreyter_Obshchatsya-s-rebenkom-Kak-.jn6v6A.263993.fb2.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8693972/Gippenreyter_Obshchatsya-s-rebenkom-Kak-.jn6v6A.263993.fb2.zip)

**Comment by kjk** [comment]
Also submitted https://bugs.ghostscript.com/show_bug.cgi?id=705302
