### ISSUE TITLE
this pdf book open is crashed

### ISSUE THREAD

**Issue by quicklwl** [sumatrapdfreader/sumatrapdf#2579]
crashed
https://cn1lib.vip/book/21030059/788f82
《现代C++(中文版) 白皮书 在拥挤和变化的世界中茁壮成长：C++ 2006–2020》
this book ；

Reproduction method:
Copy multiple copies and open them all at once；

Expect better and better

**Comment by GitHubRulesOK** [comment]
![image](https://user-images.githubusercontent.com/12754913/168704663-a5f47212-d085-4664-a9b9-83b65e3a43a7.png)
[现代C++(中文版) 白皮书 在拥挤和变化的世界中茁壮成长：C++ 2006–2020 ((美)Bjarne Stroustrup 著  吴咏炜、杨文波、张云潮 等 译) (z-lib.org).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8704243/C%2B%2B.C%2B%2B.2006.2020.Bjarne.Stroustrup.z-lib.org.pdf)

**Comment by quicklwl** [comment]
Crash file: C:\PortableTools\SumatraPDF-3.3.3-641\SumatraPDF-3.3.3-64\crashinfo\sumatrapdfcrash.txt
Exe: C:\PortableTools\SumatraPDF-3.3.3-641\SumatraPDF-3.3.3-64\SumatraPDF-3.3.3-64.exe
BuiltOn: 2021-07-20
Type: static
Ver: 3.3.3 64-bit
Git: 21678b88191b57ef0d8a4eded97532731ef57f43 (https://github.com/sumatrapdfreader/sumatrapdf/commit/21678b88191b57ef0d8a4eded97532731ef57f43)
OS: Windows 10 build 19044 64-bit
Number Of Processors: 8
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Physical Memory: 31.89 GB
Commit Charge Limit: 63.89 GB
Memory Used: 17%
Machine: MateBook D M1G
Lang: zh CN
Graphics driver 0
  DriverDesc:         Microsoft Hyper-V Video
  DriverVersion:      10.0.19041.1
Graphics driver 1
  DriverDesc:         Intel(R) UHD Graphics 620
  DriverVersion:      23.20.16.4958
  UserModeDriverName: C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_48e7e903a369eae2\igdumdim64.dll
Graphics driver 2
  DriverDesc:         NVIDIA GeForce MX150
  DriverVersion:      27.21.14.5671
  UserModeDriverName: C:\WINDOWS\System32\DriverStore\FileRepository\nvhwi.inf_amd64_13d711196fad43f3\nvldumdx.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FF63C265FCB 01:00000000000B4FCB sumatrapdf-3.3.3-64.exe
Fault writing address 0000023FED488288

Registers:
RAX:00000000E3DA6AD1  RBX:000002B4E3D6F260  RCX:0000023FED488120
RDX:FFFFFFFFE3DA6AD0  RSI:000002B4E7A97E80  RDI:00000000000000CB
R8: 000000F70B0FE0B0
R9: 0000000000000000
R10:000000F70B0FDF38
R11:0000000000000001
R12:0000000000000202
R13:000002B4E3D89B40
R14:0000000000000000
R15:00007FF63C428D15
CS:RIP:0033:00007FF63C265FCB
SS:RSP:002B:000000000B0FDF70  RBP:0B0FE070
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010203

Crashed thread:
00007FF63C265FCB 01:00000000000B4FCB sumatrapdf-3.3.3-64.exe
00007FF63C264E37 01:00000000000B3E37 sumatrapdf-3.3.3-64.exe
00007FF63C2534BA 01:00000000000A24BA sumatrapdf-3.3.3-64.exe
00007FF63C253965 01:00000000000A2965 sumatrapdf-3.3.3-64.exe
00007FF63C21656B 01:000000000006556B sumatrapdf-3.3.3-64.exe
00007FF63C218F03 01:0000000000067F03 sumatrapdf-3.3.3-64.exe
00007FF63C1D014D 01:000000000001F14D sumatrapdf-3.3.3-64.exe
00007FF63C1D03AE 01:000000000001F3AE sumatrapdf-3.3.3-64.exe
00007FF63C1CF8A1 01:000000000001E8A1 sumatrapdf-3.3.3-64.exe
00007FF825B0E858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FF825B0E4EE 01:000000000000D4EE user32.dll!CallWindowProcW+0x8e
00007FF814779ABA 01:0000000000088ABA comctl32.dll!DefSubclassProc+0x14a
00007FF814779799 01:0000000000088799 comctl32.dll!DSA_Create+0x1809
00007FF814779ABA 01:0000000000088ABA comctl32.dll!DefSubclassProc+0x14a
00007FF8147798B7 01:00000000000888B7 comctl32.dll!DSA_Create+0x1927
00007FF825B0E858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FF825B0E299 01:000000000000D299 user32.dll!DispatchMessageW+0x259
00007FF63C22A8FA 01:00000000000798FA sumatrapdf-3.3.3-64.exe
00007FF63C5A1D26 01:00000000003F0D26 sumatrapdf-3.3.3-64.exe
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 1d64
00007FF825E0CDC4 01:000000000009BDC4 ntdll.dll!NtWaitForSingleObject+0x14
00007FF823731ACE 01:0000000000020ACE kernelbase.dll!WaitForSingleObjectEx+0x8e
00007FF63C1D5D73 01:0000000000024D73 sumatrapdf-3.3.3-64.exe
00007FF82381FF27 01:000000000010EF27 kernelbase.dll!UnhandledExceptionFilter+0x1e7
00007FF825E151B0 01:00000000000A41B0 ntdll.dll!memset+0x13b0
00007FF825DFC766 01:000000000008B766 ntdll.dll!_C_specific_handler+0x96
00007FF825E1209F 01:00000000000A109F ntdll.dll!_chkstk+0x11f
00007FF825DC1454 01:0000000000050454 ntdll.dll!RtlRaiseException+0x434
00007FF825E10BCE 01:000000000009FBCE ntdll.dll!KiUserExceptionDispatcher+0x2e
00007FF63C265FCB 01:00000000000B4FCB sumatrapdf-3.3.3-64.exe
00007FF63C264E37 01:00000000000B3E37 sumatrapdf-3.3.3-64.exe
00007FF63C2534BA 01:00000000000A24BA sumatrapdf-3.3.3-64.exe
00007FF63C253965 01:00000000000A2965 sumatrapdf-3.3.3-64.exe
00007FF63C21656B 01:000000000006556B sumatrapdf-3.3.3-64.exe
00007FF63C218F03 01:0000000000067F03 sumatrapdf-3.3.3-64.exe
00007FF63C1D014D 01:000000000001F14D sumatrapdf-3.3.3-64.exe
00007FF63C1D03AE 01:000000000001F3AE sumatrapdf-3.3.3-64.exe
00007FF63C1CF8A1 01:000000000001E8A1 sumatrapdf-3.3.3-64.exe
00007FF825B0E858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FF825B0E4EE 01:000000000000D4EE user32.dll!CallWindowProcW+0x8e
00007FF814779ABA 01:0000000000088ABA comctl32.dll!DefSubclassProc+0x14a
00007FF814779799 01:0000000000088799 comctl32.dll!DSA_Create+0x1809
00007FF814779ABA 01:0000000000088ABA comctl32.dll!DefSubclassProc+0x14a
00007FF8147798B7 01:00000000000888B7 comctl32.dll!DSA_Create+0x1927
00007FF825B0E858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FF825B0E299 01:000000000000D299 user32.dll!DispatchMessageW+0x259
00007FF63C22A8FA 01:00000000000798FA sumatrapdf-3.3.3-64.exe
00007FF63C5A1D26 01:00000000003F0D26 sumatrapdf-3.3.3-64.exe
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 760
00007FF825E10794 01:000000000009F794 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FF825DC2DC7 01:0000000000051DC7 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 4398
00007FF825E10794 01:000000000009F794 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FF825DC2DC7 01:0000000000051DC7 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 770
00007FF825E10794 01:000000000009F794 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FF825DC2DC7 01:0000000000051DC7 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2998
00007FF825E0CDC4 01:000000000009BDC4 ntdll.dll!NtWaitForSingleObject+0x14
00007FF823731ACE 01:0000000000020ACE kernelbase.dll!WaitForSingleObjectEx+0x8e
00007FF63C203C6C 01:0000000000052C6C sumatrapdf-3.3.3-64.exe
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 1fb0
00007FF825E0D894 01:000000000009C894 ntdll.dll!ZwWaitForMultipleObjects+0x14
00007FF82375CBC0 01:000000000004BBC0 kernelbase.dll!WaitForMultipleObjectsEx+0xf0
00007FF63C42CDE2 01:000000000027BDE2 sumatrapdf-3.3.3-64.exe
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 3a38
00007FF825E10794 01:000000000009F794 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FF825DC2DC7 01:0000000000051DC7 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 41e0
00007FF825E10794 01:000000000009F794 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FF825DC2DC7 01:0000000000051DC7 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2754
00007FF825E10794 01:000000000009F794 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FF825DC2DC7 01:0000000000051DC7 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 33a0
00007FF825E10794 01:000000000009F794 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FF825DC2DC7 01:0000000000051DC7 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FF825747034 01:0000000000016034 kernel32.dll!BaseThreadInitThunk+0x14
00007FF825DC2651 01:0000000000051651 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2b18
00007FF825E0D894 01:000000000009C894 ntdll.dll!ZwWaitForMultipleObjects+0x14
00007FF82375CBC0 01:000000000004BBC0 kernelbase.dll!WaitForMultipleObjectsEx+0xf0
00007FF8239FBEE7 01:000000000001AEE7 crypt32.dll

Module: 00007FF63C1B0000 CE7000 SumatraPDF-3.3.3-64.exe C:\PortableTools\SumatraPDF-3.3.3-641\SumatraPDF-3.3.3-64\SumatraPDF-3.3.3-64.exe
Module: 00007FF825D70000 1F5000 ntdll.dll        C:\WINDOWS\SYSTEM32\ntdll.dll
Module: 00007FF825730000 0BD000 KERNEL32.DLL     C:\WINDOWS\System32\KERNEL32.DLL
Module: 00007FF823710000 2CD000 KERNELBASE.dll   C:\WINDOWS\System32\KERNELBASE.dll
Module: 00007FF825B00000 1A0000 USER32.dll       C:\WINDOWS\System32\USER32.dll
Module: 00007FF823550000 022000 win32u.dll       C:\WINDOWS\System32\win32u.dll
Module: 00007FF8257F0000 02A000 GDI32.dll        C:\WINDOWS\System32\GDI32.dll
Module: 00007FF823C40000 10B000 gdi32full.dll    C:\WINDOWS\System32\gdi32full.dll
Module: 00007FF8234B0000 09D000 msvcp_win.dll    C:\WINDOWS\System32\msvcp_win.dll
Module: 00007FF823610000 100000 ucrtbase.dll     C:\WINDOWS\System32\ucrtbase.dll
Module: 00007FF8146F0000 29A000 COMCTL32.dll     C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\COMCTL32.dll
Module: 00007FF825A20000 0DB000 COMDLG32.dll     C:\WINDOWS\System32\COMDLG32.dll
Module: 00007FF824B10000 09E000 msvcrt.dll       C:\WINDOWS\System32\msvcrt.dll
Module: 00007FF825330000 354000 combase.dll      C:\WINDOWS\System32\combase.dll
Module: 00007FF824700000 125000 RPCRT4.dll       C:\WINDOWS\System32\RPCRT4.dll
Module: 00007FF825830000 0AD000 shcore.dll       C:\WINDOWS\System32\shcore.dll
Module: 00007FF824640000 055000 SHLWAPI.dll      C:\WINDOWS\System32\SHLWAPI.dll
Module: 00007FF823DC0000 744000 SHELL32.dll      C:\WINDOWS\System32\SHELL32.dll
Module: 00007FF824A60000 0AE000 ADVAPI32.dll     C:\WINDOWS\System32\ADVAPI32.dll
Module: 00007FF814990000 094000 WINSPOOL.DRV     C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
Module: 00007FF825690000 09C000 sechost.dll      C:\WINDOWS\System32\sechost.dll
Module: 00007FF824510000 12A000 ole32.dll        C:\WINDOWS\System32\ole32.dll
Module: 00007FF8250D0000 0CD000 OLEAUT32.dll     C:\WINDOWS\System32\OLEAUT32.dll
Module: 00007FF825D00000 030000 IMM32.DLL        C:\WINDOWS\System32\IMM32.DLL
Module: 00007FF820A80000 09E000 uxtheme.dll      C:\WINDOWS\system32\uxtheme.dll
Module: 00007FF820E50000 02F000 dwmapi.dll       C:\WINDOWS\system32\dwmapi.dll
Module: 00007FF8250C0000 008000 normaliz.dll     C:\WINDOWS\System32\normaliz.dll
Module: 00007FF821200000 1E4000 dbghelp.dll      C:\WINDOWS\system32\dbghelp.dll
Module: 00007FFFF9E00000 02C000 dbgcore.DLL      C:\WINDOWS\SYSTEM32\dbgcore.DLL
Module: 00007FF814430000 1A5000 gdiplus.dll      C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.1706_none_919e8e54cc8d4ca1\gdiplus.dll
Module: 00007FF81CB60000 007000 msimg32.dll      C:\WINDOWS\system32\msimg32.dll
Module: 00007FF811D70000 1EC000 urlmon.dll       C:\WINDOWS\system32\urlmon.dll
Module: 00007FF812930000 2B1000 iertutil.dll     C:\WINDOWS\SYSTEM32\iertutil.dll
Module: 00007FF822900000 00C000 netutils.dll     C:\WINDOWS\SYSTEM32\netutils.dll
Module: 00007FF811D00000 028000 srvcli.dll       C:\WINDOWS\SYSTEM32\srvcli.dll
Module: 00007FF822F40000 00A000 version.dll      C:\WINDOWS\system32\version.dll
Module: 00007FF81B650000 1B4000 windowscodecs.dll C:\WINDOWS\system32\windowscodecs.dll
Module: 00007FF823480000 027000 bcrypt.dll       C:\WINDOWS\System32\bcrypt.dll
Module: 00007FF80DAF0000 4D6000 wininet.dll      C:\WINDOWS\system32\wininet.dll
Module: 00007FF821410000 794000 windows.storage.dll C:\WINDOWS\SYSTEM32\windows.storage.dll
Module: 00007FF822DA0000 02C000 Wldp.dll         C:\WINDOWS\SYSTEM32\Wldp.dll


-------- Log -----------------

Starting SumatraPDF
CmdLine: "C:\PortableTools\SumatraPDF-3.3.3-641\SumatraPDF-3.3.3-64\SumatraPDF-3.3.3-64.exe" 
StartMonitoringDirForChangesAPC() C:\PortableTools\SumatraPDF-3.3.3-641\SumatraPDF-3.3.3-64
LoadDocument: 'D:\01娱乐\现代C++ 白皮书 在拥挤和变化的世界中茁壮成长：C++ 2006–2020.pdf', tid=7524
CreateControllerForFile: 'D:\01娱乐\现代C++ 白皮书 在拥挤和变化的世界中茁壮成长：C++ 2006–2020.pdf'
HttpGet: url: 'https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/rel/SumatraPDF-3.3.3-64.pdb.lzsa'

**Comment by kjk** [comment]
Confirmed it crashes with 3.3.3 but it doesn't crash in latest pre-release (https://www.sumatrapdfreader.org/prerelease) so likely already fixed.

**Comment by quicklwl** [comment]
good

**Comment by GitHubRulesOK** [comment]
@quicklwl 
note the screenshots above, it does not crash in 3.4 but as with many many pirate samples we see from z-lib.org it is a bad file with a poor index.
