### ISSUE TITLE
(SumatraPDF 3.0 windows) text in the TOC is not displayed - see attached PDF

### ISSUE THREAD

**Issue by wizzard0** [sumatrapdfreader/sumatrapdf#258]
How to reproduce:

1. Download http://krzysztofpasek.staff.tcs.uj.edu.pl/From_AI_to_Zombies.pdf
2. Open with SumatraPDF
3. In comparison, open with built-in Windows 8.1 PDF Reader

**Comment by kjk** [comment]
This has already been fixed in latest pre-release http://www.sumatrapdfreader.org/prerelease.html
