### ISSUE TITLE
Sumatrapdf Double Open

### ISSUE THREAD

**Issue by Tunann** [sumatrapdfreader/sumatrapdf#2581]
Many software, like Chrome, Adobe Acrobat DC, Word, etc. can be double-opened **by dragging** the windows as the picture below:
![image](https://user-images.githubusercontent.com/72566949/168820248-2eb95ad4-2901-466e-b578-db53e809f6ea.png)
I flipped through Sumatrapdf's documentation, but I didn't seem to find this function. I think it would be great if this function could be implemented.

**Comment by GitHubRulesOK** [comment]
Many different related requests but press CTRL + SHIFT +N in current 3.4 pre-release opens same file twice or without shift you can pick one you pinned or a favorite or drag and drop or or

**Comment by eladkarako** [comment]
that could be nice  
(although tab-re-dock calculation is somewhat is a pain to program).  

you can use SumatraPDF as a single instance, 

- `ReuseInstance = false`
- `UseTabs = false`

it might provide a simpler way of switching between tasks,  
which might be useful if you mostly use your keyboard to switch between tasks (<kbd>Alt</kbd>+<kbd>Tab</kbd>, <kbd>Alt</kbd>+<kbd>F4</kbd>).

(you can also just keep `UseTabs = true` and open a new session with another file).  

<details><summary>for example (portable, <code>SumatraPDF-settings.txt</code>)</summary>

```conf
# For documentation, see https://www.sumatrapdfreader.org/settings/settings3-4.html

MainWindowBackground = #80fff200
SmoothScroll = false
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true
ToolbarSize = 40
TabWidth = 300

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 40 40
	HideScrollbars = false
	EbookFontName = default
	EbookFontSize = 10
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 40 40
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]
SelectionHandlers [
]
ExternalViewers [
]
ShowMenubar = true
ReloadModifiedDocuments = true
FullPathInTitle = true
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
Annotations [
	HighlightColor = #ffff00
	UnderlineColor = #00ff00
	TextIconColor = #ffff00
	TextIconType = 
	DefaultAuthor = 
]
CustomScreenDPI = 200

RememberStatePerDocument = true
UiLanguage = en
ShowToolbar = true
ShowFavorites = false
CheckForUpdates = false
RememberOpenedFiles = true
EnableTeXEnhancements = false
DefaultDisplayMode = continuous
DefaultZoom = fit content
WindowState = 2
WindowPos = 590 0 740 958
ShowToc = true
SidebarDx = 0
TocDy = 0
TreeFontSize = 0
ShowStartPage = true
UseTabs = false
Shortcuts [
]

FileStates [
	[
		FilePath = C:\Users\Elad\Desktop\How to ditch Microsoft Edge as your default PDF reader on Windows 10 _ Windows Central.pdf
		Favorites [
		]
		IsPinned = false
		IsMissing = false
		OpenCount = 7
		UseDefaultState = false
		DisplayMode = continuous
		ScrollPos = -1 -1
		PageNo = 5
		Zoom = fit page
		Rotation = 0
		WindowState = 2
		WindowPos = 590 0 740 958
		ShowToc = false
		SidebarDx = 0
		DisplayR2L = false
		ReparseIdx = 0
	]
]
SessionData [
]
TimeOfLastUpdateCheck = 0 0
OpenCountWeek = 591

# Settings after this line have not been recognized by the current version

```

</details>

**Comment by GitHubRulesOK** [comment]
closing as now dragging tabs as and to other windows is available in https://www.sumatrapdfreader.org/prerelease
