### ISSUE TITLE
How to disable select function (left mouse button)

### ISSUE THREAD

**Issue by NicXmec** [sumatrapdfreader/sumatrapdf#2582]
Hi all, 

Does anybody know how to disable left mouse button to select text?
Is it even possible to do something like that in SumatraPDF?

My wishes is to keep only posibility for moving PDF document...
But, at the same time, to disable possibility for/to select text!?

So, in other words...
I would like "left" and "right" mouse buttons have the same behavior.

Best regards. 
NicXmec

**Comment by kjk** [comment]
That is not possible.

**Comment by GitHubRulesOK** [comment]
@NicXmec 
most users would use a simple mouse reassignment app (native windows only allows global swap R&L) 
so that should be possible in HiRez X-Mouse https://www.highrez.co.uk/downloads/XMouseButtonControl.htm (23rd May 2020) where you assign buttons per app.
Alternative is a few lines in AutoHotKey which can also be used to macro change other behaviors per app

**Comment by NicXmec** [comment]
Thanks for answer... 

I asked this question mostly because I saw that in the next ver. of SumatraPDF (3.4) it will be possible to adjust the settings on the keyboard; so I was wondering if such "customization" already exists _(**or will exist)**_ to specific what-each key do on the mouse.

**Those features are for upcoming 3.4** [SumatraPDF-KEYBOARD]
Version history
- customizable keyboard shortcuts


**EXAMPLE: This would be for the mouse function**

![MOUSE](https://user-images.githubusercontent.com/105751015/168935321-b93057ed-4e3a-4701-b6d9-7e92b31225e2.jpg)


Best regards, 
NicXmec.

**Comment by GitHubRulesOK** [comment]
@NicXmec 
Nice Artwork I have no idea how the mouse, could be redefined for the multiple functions it has (some relate to other apps), however if there is no text (white space) it works as drag.

**Comment by NicXmec** [comment]
Hi all, 
Once again thank you for all your answers and sorry for the late reply!

**@kjk**

OK maybe then for the some **next versions** if the **mouse can be customize** also. I would love to so much! 😊
I do not mean to discover something new but what already exists and which has proven to be as so useful solution.

In the following video, I will show you what I am facing and what is my actual problem.
As you can see (**EXAMPLE1**) - if I 'accidentally' pull to the side then the text is selected without dragging.
_It can be very irritating, when it is constantly happening.... again, again etc._

Solution, for that, already exists "PDF-XChange" (**EXAMPLE2**)
Dragging the pages, without selecting text, it gives a completely different feel! - I hope it can be agreed with me about that.
Also, It would be very nice, if exist perhaps effect as "Inertial Scroll" or similar like that. 
One more example: YOUTUBE: https://www.youtube.com/watch?v=q9jMS-bQmTU

What I previously mentioned (**EXAMPLE3**) it could be different types of scrolling for mouse middle button: 
Short middle-wheel mouse click button - Full (Complete) Automated scrolling
Long middle-wheel mouse click button - Semi (Manual) Automated scrolling



VIDEO: **EXAMPLE1**

https://user-images.githubusercontent.com/105751015/169365085-e0eaf034-dd15-41bf-bb3e-0659eb3a4872.mp4

VIDEO: **EXAMPLE2**

https://user-images.githubusercontent.com/105751015/169365521-e7d7f605-d41a-4752-918e-0ee59cc8c529.mp4

VIDEO: **EXAMPLE3**

https://user-images.githubusercontent.com/105751015/169365569-c531115c-7ef0-4cf5-8dda-106ff2fd5541.mp4


Best regards, 
NicXmec

**Comment by kjk** [comment]
There are already 2 ways to just drag with mouse, without selecting text:
* right mouse button
* press SHIFT while using left mouse button

Given that those already exist, there's less justification for making left mouse behavior customizable

**Comment by NicXmec** [comment]
@kjk

I didn't know about that combination SHIFT+LEFT.  Okay, I tried, it works...
Yes, I knew about RIGHT, but it's kind (at least, for me) "un-natural" solution (I can't get used to it...)
Because of that, I don’t use it that often - so then I reach out of LEFT BUTTON 😒

Best regards, 
NicXmec.

**Comment by NicXmec** [comment]
@kjk

That's the thing. The "customization" means everyone can do what suits for themself at the best way. 
I tried the BETA version Sumatra PDF (3.4) - with the keyboard shortcuts.... works just great, I'm delighted.

Best regards,
NicXmec.

**Comment by NicXmec** [comment]
**@kjk**

I’m not an IT expert but it seems to me that it wouldn’t be hard to perform for a MOUSE as well.
Make the same as customizable as keyboard based on pre-defined commands.

Best regards,
NicXmec.

**Comment by tactilis** [comment]
@NicXmec
> I’m not an IT expert but it seems to me that it wouldn’t be hard...

Ha! You should get that printed on a t-shirt.

I may be missing something here, but why can't you simply use the scroll wheel to scroll up and down?  It's much faster and requires less hand movement than dragging with the mouse. And there's no danger of accidentally selecting text.

**Comment by NicXmec** [comment]
**"Ha! You should get that printed on a t-shirt"**

Thanks for the advice, maybe I will do so! 👍  😊
You obviously missed the part when I said "un-natural".
I will repeat what I say before: I don’t use it often ("Right mouse") - also "Wheel" etc - so then I reach instead of that to LEFT BUTTON - I do not why, I can only guesses... it makes me better feeling, when I scroll pages like that - it's much easier, as I move, as much, as I want to be moved when I have to read something.
 
That why I say it is all about "customization"
Everyone can then adjust to how they respond/like etc.

The keyboard can be also used for scrolling instead of a mouse - right? 
Well someone may ask why use a mouse at all, when you can use only keyboard!?
I would never/ever judge anyone who use keyboard over mouse!!!

It's free choice who love what and how who likes to set for themself.

Let me just go back to the beginning....
In the BETA version Sumatra PDF 3.4 there is one thing (which I also liked) it's called "SMOOTH SCROLL" which is better option for scrolling when using the mouse wheel.
I tried before few days and works as well as keyboard shortcuts. 

Sumatra PDF 3.4- BETA
Those features are for upcoming 3.4
 - add experimental smooth scrolling

I don't want to be wrong misunderstood what I mantioned about the mouse.
It is only my suggestion that can be 'customize' mouse settings like keyboard.
Maybe, for same future version - if anybody will be interested about it!
Potentially, maybe there people, who is weird, and love 'strange-things' like me!!! 😂

**_How's that statement go:_** 
Either we are alone in space, or there are billions like us, both facts are equally terrifying! 😎

Best regards, 
NicXmec.

**Comment by GitHubRulesOK** [comment]
@NicXmec not wishing to labor the point that the left mouse button is tied to potentially a dozen functions thus "customizing" all behaviors would be context sensitive. 
I do understand your desire that when in a text area your desire is it behaves same as right button.

At a simple level swapping mouse buttons could suffice and rather than use windows to effect that change across all apps it would be simplest to swap mouse buttons just while viewing some documents then toggle back for others. Hoever that is best done via a dedicated hot key handler such as AutoIT or AutoHotKey.

There was a very similar discussion 6 years ago with similar solution see https://github.com/sumatrapdfreader/sumatrapdf/issues/299#issuecomment-865261918

**Comment by NicXmec** [comment]
**@GitHubRulesOK**

Okay, thanks for the suggestion - I'll study a bit; so far I haven't been very familiar with these programs, such like AutoIT or AutoHotKey. As far as I can see, you suggested it a few days ago also.

PS. I'm not really a supporter of using 'additional programs' to do something in the primary - just because of what you mentioned "context sensitive stuff". That's where is the door opens for a lot potentialy security problems, that can arise because of doing that...

I thought there might be some "simpler solution" like typing some code into "SumatraPDF settings" and that would then be the solution for my - or also for similar cases (like mine)


Best regards,
NicXmec.

**Comment by tactilis** [comment]
> I thought there might be some "simpler solution" like...

...just learning to use the scroll wheel.

You do seem to be making a big issue out of something that is pretty simple to do.

**Comment by NicXmec** [comment]
Okay, I don't want to argue, about that any-more. I think I've explained enough in the previous posts. Now I have a feeling that I'm going to have to repeat myself every time from the beginning....

If anyone is interested, or whom it is not yet clear what I was saying - please return a couple of posts to the beginning, and read more carefully what I have been said about that/those topics.  For me, it's solved! 👌

Thank everyone for their advice/suggestions-participation. 

Greetings! 😊
