### ISSUE TITLE
When does it support reading videos in PDF

### ISSUE THREAD

**Issue by bzmework** [sumatrapdfreader/sumatrapdf#2592]
Hi，This project is very good，When does it support reading videos in PDF。

**Comment by GitHubRulesOK** [comment]
currently it should not since those are often SWF and thus no longer supported on web or PDF readers,
If the link is to a local media file like an mp4 file internal or external then it would be simpler to click the mp4 file direct

**Comment by kjk** [comment]
No plans to support video inside PDF files
