### ISSUE TITLE
Regression: "MainWindowBackground" does not work anymore

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [sumatrapdfreader/sumatrapdf#2593]
# Description
1. Settings -> Advanced Options...;
2. Change `MainWindowBackground = #80fff200` to some value;
3. Backgdround color is always "default" in todays (2022-May-24) nightly.
4. It was set to custom (dark) in previous nightlies (see screenshot from https://github.com/sumatrapdfreader/sumatrapdf/issues/898#issuecomment-922859723)

![0957J](https://user-images.githubusercontent.com/46539653/170031559-45530731-4dbb-4327-a7ee-278cacb7c4c1.png)

![1354N](https://user-images.githubusercontent.com/46539653/170031996-8419b325-c9ae-4fdb-9547-a5b98a93a087.png)

**Comment by WhiteChairFromIkea** [comment]
Forget it, `MainWindowBackground` is working as it should on my other PC. I will inspect further on problematic PC, it may be my mistake (just noticed today, that I do not have dark background color, as always had). I will reopen if some problem arise, sorry for the disturbance.
And here is a video this issue was created about (it demonstrates, that there is no issue at all :)):

https://user-images.githubusercontent.com/46539653/170133733-9c09561a-eeae-42bb-9666-ca5447e4caf4.mp4

**Comment by WhiteChairFromIkea** [comment]
The video above is done with cleared settings ini file, and it works. `MainWindowBackground`  does not do anything in my real installation after update (daily used ini file). It seems, that setting this: `TimeOfLastUpdateCheck = 30961510 1515458354` to `TimeOfLastUpdateCheck = 0 0` (default setting) fixed the problem. Please reopen think something needs to be done here.

**Comment by WhiteChairFromIkea** [comment]
FIY, about this strange issue (not sumatra's fault, but sumatra does not detect settings change, made by [notepad3.exe](https://www.rizonesoft.com/downloads/notepad3/)

https://user-images.githubusercontent.com/46539653/170138467-f0e4e8e7-23f7-426d-9db9-6394537223a1.mp4

**Comment by GitHubRulesOK** [comment]
Non ntfs local drives will often cause problems for several reasons. So synchronized drives can interfere with some editors including SumatraPDF annotation or other saving functions, its not just SumatraPDF I have lost hours of work when a "smart"  folder decided to go AWOL.
