### ISSUE TITLE
SmoothScrolling not recognized in 3.41

### ISSUE THREAD

**Issue by lollita** [sumatrapdfreader/sumatrapdf#2597]
SmoothScrolling setting not recognized in 3.41 but present in history change.

**Comment by lollita** [comment]
SmoothScrolling setting not recognized in 3.41 but present in history change.

**Comment by kjk** [comment]
It is recognized and there's definite difference in scrolling.

It might not work as you expect it to, but it's a different matter.

**Comment by lollita** [comment]
But sumatrapdf move this setting in section
# Settings below are not recognized by the current version
SmoothScrolling = true

**Comment by kjk** [comment]
The option is `SmoothScroll`

**Comment by lollita** [comment]
So it works even if "not work as you expect it to".
Ty.

**Comment by lollita** [comment]
the history 3.4 (2022-05-24) report:
`add experimental smooth scrolling (enabled with SmoothScrolling advanced setting) `
and not SmoothScroll.
Do it is wrong?

**Comment by kjk** [comment]
Was a mistake in release notes, I've fixed it.
