### ISSUE TITLE
${userlang} replace every "de"

### ISSUE THREAD

**Issue by lollita** [sumatrapdfreader/sumatrapdf#2598]
${userlang} not work if current UI is english.

**Comment by lollita** [comment]
> The translation is presumed from english text to your language. If language is also english, then translation is from english => english, which doesn't make sense.

This is a limited presunction; I can have a german page to translate to english.
I can to use:
URL = https://translate.google.com/?sl=auto&tl=$${userlang}&text=$${selection}

**Comment by GitHubRulesOK** [comment]
@kjk 
it is more natural a user want translation from unknown TO users lang (for better understanding)

Bonjour le monde! > user lang >Hi World!
  darn google translate!
![image](https://user-images.githubusercontent.com/12754913/170347643-042ba320-110e-4e49-9d3f-38af6099c5dd.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
where en=user lang
https://translate.google.com/?sl=auto&tl=en&text=Bonjour%20le%20monde!&op=translate
https://www.deepl.com/translator#-/en/Bonjour%20le%20monde!
![image](https://user-images.githubusercontent.com/12754913/170350436-85f53618-192c-476a-8d60-1eed31f669dc.png)

**Comment by kjk** [comment]
Thanks @GitHubRulesOK , I didn't know about the `#-` syntax for DeepL to auto-detect the source language.

I've used it and removed the over-ride of target en language to de.

**Comment by GitHubRulesOK** [comment]
@kjk i see change will be "next" (in progress) but not in 3.4.# working??

**Comment by kjk** [comment]
yes, point releases are to fix serious bugs (think crashes etc.). 

Everything else will have to wait for 3.5
