### ISSUE TITLE
Find Function, Version 3.0

### ISSUE THREAD

**Issue by noeggi** [sumatrapdfreader/sumatrapdf#26]
In a datasheet  "PIC16F1788"  I searched for "tcy" (The same with "Tcy"). I found about five entries, the first entry on page 411. With another PDF Reader I found 42 entries, the first on page 95.

**Comment by GitHubRulesOK** [comment]
@kjk the original file referenced above appears to be updated however the replacement exhibits some similar behaviour On testing between versions older pre release did not find tcy until page 412 (skipping lots of other entries) and in total only a handful of occurrences. similar to the original issue

"about five entries, the first entry on page 411. With another PDF Reader I found 42 entries, the first on page 95."

The newer builds will find tcy at  page 95 (as expected) and there are over 40 hits thus latest behaviour suggest this issue can now be closed
