### ISSUE TITLE
Sumatra for Linux

### ISSUE THREAD

**Issue by carlvn** [sumatrapdfreader/sumatrapdf#260]
Hi, 
I really hope my request is not too stupid (I'm quite new to programming), but would it be possible to build Sumatra for Linux, since there is the source code and everything?
Sumatra is actually one of the very few things that is still tying me to Windows.
I really love that reader, keep it up!
Carl

**Comment by kjk** [comment]
People reported success using Wine on Linux. But it's not possible to compile for Linux see https://github.com/sumatrapdfreader/sumatrapdf/wiki/Why-only-Windows%3F

**Comment by ousia** [comment]
@carlvn, [mupdf](http://mupdf.com) is also available for Linux.

**Comment by azispratama92** [comment]
Yeah me too, i was able to run sumatra pdf in Linux Ubuntu by using wine, (older version of Sumatra PDF is recommended 2.xx), @carlvn i was wondering too if its possible to port this software into crossplatform desktop apps by using QT. 

The most excellent feature that i like is `Mouse Zoom`, i really loved it !!
