### ISSUE TITLE
Slow loading of 11 MB epub

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#2607]
[(Addison-Wesley Microsoft Technology Series) Mark Michaelis-Essential C# 7.0-Addison-Wesley Professional (2018).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/8790352/Addison-Wesley.Microsoft.Technology.Series.Mark.Michaelis-Essential.C.7.0-Addison-Wesley.Professional.2018.zip)

I've been updating to the latest Pre-Release but just recently, my 11-MB "Essential C#" EPUB e-Book brings SumatraPDF to a grinding halt when clicking on it, I have 2 Portable versions & 1 Installed version (for more e-Book tab capacity —Some tabs when clicking on them, crash SumatraPDF (my second app (also Portable).) Anyway the third app (Portable) has no tab capability only Home screen + few pinned documents which I'm reading at the moment, & when I launch said EPUB it takes around 4 minutes to load (very slow !) & even to close the tab takes ages ! I'm attaching the EPUB in zip file in the hopes SumatraPDF can be fixed ASAP, & bring the Pre-Release to a working state.

**Comment by kjk** [comment]
one thing per issue please.

For crashes, please create a separate issue, provide a file that reproduces a crash and steps to reproduce the crash.

This is a very large file, so there's only so much we can do.

**Comment by alienfxfiend** [comment]
Yes before recent updates, there was no lag in open & closing this 11 MB EPUB, maybe a few seconds if I'm not mistaken. Also I pinpointed the Crash, it occurs when you open a CHM file within SumatraPDF's latest Pre-Release Version.

**Comment by alienfxfiend** [comment]
Maybe the code or engine is partially incomplete ? Also, if it help, I'm on Windows 10.

**Comment by alienfxfiend** [comment]
O.K. so I further tested older builds & SumatraPDF 3.2 displays the 11 MB EPUB instantly, so it has to be a bug in the latest version !!! & that's not all, even EPUBReader Edge addon opens this instantly. I remember you mentioning Lazy Loading is disabled so maybe that's why. At least now I can read the EPUBs & launch them instantly till you can sort out this mess. Here is the link I used: [SumatraPDF 3.2](https://www.sumatrapdfreader.org//dl/rel/SumatraPDF-3.2-64.zip)

**Comment by kjk** [comment]
It's not a bug, just slowness.

I changed epub rendering engine from a simple one that we wrote for Sumatra to mupdf.

The new engine is much more capable and understands much more formatting of epub files.

But it's not as fast.

There might be opportunity to optimize things further.

**Comment by alienfxfiend** [comment]
Oh I see, well that explains it. Hope so too.

**Comment by alienfxfiend** [comment]
That also explains why I was able to change the fontfamily of my EPUB documents.

**Comment by kjk** [comment]
Ok, so there actually was a bug I introduced to fix another issue.

With this change, this file now loads in 2 secs vs 20 secs before.

Probably still not as fast as the old engine, but 10x faster than before the fix.

**Comment by alienfxfiend** [comment]
Awesomesauce !
