### ISSUE TITLE
Latest Sumatra Releases Not on GitHub

### ISSUE THREAD

**Issue by Gitoffthelawn** [sumatrapdfreader/sumatrapdf#2612]
Thank you for SumatraPDF and for updating it.

I noticed that the releases (and tags) on GitHub currently are behind the releases on https://sumatrapdfreader.org

Is this intentional or an oversight?

If it's intentional, what is the reasoning and what are the future plans?

Thanks again.

**Comment by GitHubRulesOK** [comment]
Its always been common as described in docs to hold back formal release until proven
 thus currently although testing a pre-release (current 3.5.pr) may take a 3.5 years as was 3.1.2-3.2 or just a 1 day(s) 3.3.2-3.3.3?
 the 3.4.# release will not be triggered until considered stable.

**Comment by pitsi** [comment]
I am also interested in that and I was about to ask the same thing. I use github's rss feature to inform me for new releases (or commits) on the projects I like, e.g. for sumatra's releases the url is
`https://github.com/sumatrapdfreader/sumatrapdf/releases.atom`

And with v3.4.1 I noticed that my installation was still on v3.3.3, so I checked github first and it was still on 3.3.3.

**Comment by Gitoffthelawn** [comment]
@pitsi I didn't know that GitHub had an RSS feature.  Thanks for pointing that out.  It might be even faster than my current automated method of checking for updates, which involves scraping the release page of every repo that interests me.

**Comment by kjk** [comment]
Done: https://github.com/sumatrapdfreader/sumatrapdf/releases/tag/3.4.3

**Comment by pitsi** [comment]
Thank you :) I am off to update to 3.4.3.

@Gitoffthelawn
Glad I hepled :)

**Comment by Gitoffthelawn** [comment]
@kjk Thanks! Do you also want to put the pre-compiled executables on GitHub in case your server is down or otherwise inaccessible?

**Comment by GitHubRulesOK** [comment]
If you need to check there are enough unofficial mirrors so safest is probaly Sumo or https://www.filehorse.com/download-sumatra-pdf-64/

**Comment by Korb** [comment]
Judging by the latest releases, Krzysztof Kowalczyk, Simon Bünzli and others have basically given up on publishing compiled binaries of SumatraPDF on Github. This is sad.

**Comment by H5820121** [comment]
Could you please explain more what you mean?
And by the way, do you know why for a long time a new release of
Pre-Release 3.6 has not been released?

What I'm really missing is that I don't get an email notification from
GitHub when a new version of pre-release 3.6 is released (even though I
signed up for it). This is very convenient in other programs on GitHub.

‫בתאריך יום א׳, 6 באוק׳ 2024 ב-11:09 מאת ‪Korb‬‏ ***@***.***
‬‏>:‬

**Comment by GitHubRulesOK** [comment]
@H5820121 
There are no releases via GitHub (GH and clients, tend to discourage the way many sites used commercial release services like AppVeyor)

There is over time a heavy cost for serving each downloaded copy. Clearly a regular system like every second Tuesday suits Microsoft or others on say a monthly payments cycle.

SumatraPDF never has had a regular release although during bursts of development "Daily" systems have sometimes been used.

Releases currently triggered per device stream should be Internal Formal Update  to 3.1.2, 3.5.2 and 3.6.16779

**Comment by H5820121** [comment]
@GitHubRulesOK
Thanks!, is there a way to receive an email when a new version of
Pre-Release 3.6 is released (and as is common with many other programs)?

‫בתאריך יום א׳, 6 באוק׳ 2024 ב-12:02 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by GitHubRulesOK** [comment]
@H5820121 
There is no free GH service unless you subscribe to one, (so wonder why others are "free" do they pay you for your email address?)

SumatraPDF costs a lot to maintain but has no commercial returns (at a guess personally cost me thousands of lost revenue opportunities, but I dont count a Hobby as a loss)

**Comment by H5820121** [comment]
@GitHubRulesOK I'm getting an email from GH when a new release of AHK,
AHK++ ext, CopyQ, is released . And of Everything, TeraCopy free vr (not
GH) and more, and I subscribe to it at no cost.

‫בתאריך יום א׳, 6 באוק׳ 2024 ב-12:24 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by Korb** [comment]
> There is no free GH service unless you subscribe to one

What do you mean? I am this

![Subscribe to events for sumatrapdfreadersumatrapdf](https://github.com/user-attachments/assets/d5a07186-0ef5-426c-8152-b5b5496f0011)

**Comment by GitHubRulesOK** [comment]
@Korb yes the formal release cycle is available `https://github.com/sumatrapdfreader/sumatrapdf/releases/tag/3.5.2rel` but not the one for every commit and the point here is that the off site releases are not the ones on GH.
