### ISSUE TITLE
double clicking pdf file cannot open it in ver. pre-3.5.14947 64bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2613]
dragging pdf file into the graphic window of sumatrapdf can open the file. but double clicking pdf file does not work, e.g. it reports error 'File C:\Users\Axx xxx\Downloads\C:\Users\A not found' in the left top corner of graphic window with yellow background when I double click a pdf file 'C:\Users\Axx xxx\Downloads\yyy.pdf'

**Comment by kjk** [comment]
Hopefully fixed in 14950

**Comment by LqkUWp** [comment]
sadly, it still not work

**Comment by kjk** [comment]
Narrowing down scenario: happens when Sumatra is already running, we double click and use `OpenUsingDDE` to send to existing instance.
