### ISSUE TITLE
Some hidden chinese files

### ISSUE THREAD

**Issue by skipik** [sumatrapdfreader/sumatrapdf#2620]
![123](https://user-images.githubusercontent.com/24621645/170841436-df8dbcf8-a857-4900-bc72-aa1c58e2d221.png)

Everytime I open any PDF document I see that in my start menu in Windows 11. The file doesn't exist actually, but it shows in the start menu / recent files. Wtf?
v3.5.14959 Git-253222301 | master branch
P.S. Path is /all users/my_profile/Desktop

**Comment by kjk** [comment]
There was a problem present in a few 3.5 pre-releases, should be fixed now.

However, those entries created by those builds will remain. It just shouldn't create new ones.

**Comment by kjk** [comment]
Actually, I just fixed it now, so the fix will be in 14961+

**Comment by GitHubRulesOK** [comment]
@kjk it is a windows issue
the Windows favorites/recents history (same as SumatraPDF internal 🙁 ) is not culled for all renames/removals
![image](https://user-images.githubusercontent.com/12754913/170844244-c08164d1-c760-4093-8aaa-d7a053f7708f.png)
