### ISSUE TITLE
EPUB Text & Diagrams Overlapping In New Commit

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#2622]
There is a bug in the latest commit 2b3c6ed. If you go to pg. 418 of the "Essential C#" EPUB the images overlap the text —they're all over the place, & this is /w all the diff modes I tried out: "Single Page Continuous + Fit Width", as well as "Book View." The link to the EPUB is in here: [Slow Loading of 11 MB EPUB](https://github.com/sumatrapdfreader/sumatrapdf/issues/2607) This needs to be fixed ASAP ! Till it's worked out I will read the e-Books in SumatraPDF 3.2. Also 2 seconds loadtime ? I have a 2015-era Dual-Core Dell laptop & it takes something like 20-25 seconds to load the e-Book —quite unacceptable, but as you say in the future the engine will be improved; I have confidence that it will. P.S: Luckily there's no issue /w PDF's ! P.P.S: Before it was around 4 minutes to load the document for me (without tabs.)

**Comment by GitHubRulesOK** [comment]
MeToo ! using Dell but it takes 2 seconds
 because the other one I use is older than yours and even updated pre-rel just crashed after ages :-)

**Comment by alienfxfiend** [comment]
It's not right, it shouldn't have to lag. The biggest EPUB I have is "The Math Book (Big Ideas Simply Explained) by DK Publishing (z-lib.org).epub" which is 315 MB, & I bet you it opens just fine in SumatraPDF 3.2. I've tested out these files, even in tabbed mode, /w like 30 of these size files open (no hitch.) I don't know why it crashed on your Win 7 box, but I opened a "Pro .NET Memory Management -For B [Konrad_Kokosa] (z-lib.org).epub" 35 MB EPUB just fine on both 3.2 & the Pre-Release (though it was very very slow on the latest commit,) I have a Dell Inspiron 3543, I use it extensively for retro-gaming & never had any issues /w Sumatra on it before.

**Comment by GitHubRulesOK** [comment]
Lag is inherent in zip compressed formats Like PDF and ePub or DocX etcwritten pixel by pixel on a screen.
One reason a smaller file can take longer is using things like wavelet or efficient high density compression.
For a PDF reader the full length of the file after slow heavy decompression has to be parsed to find the page catalog (TOC outline etc) then and only then can it be shown slow as paint drying on a screen, small files less pages less compression less colors will exponentially help.

With 32bit fix that steam driven 1GB netbook is working as fast as yours under 20 seconds to do all those manipulations onto 800x600 screen but that's irrelevant there were billions of computations in an atom CPU per 20 seconds.

Local AppData was suggested for settings around 7 years ago? see https://github.com/sumatrapdfreader/sumatrapdf/issues/115 just not implemented as common until needed by changes for more draconian win 10/11 use of security 2 years ago. Basically there are many directory/folders used and for user access Local is the best place for settings with cache per user. If you are having a different problem please open one issue at a time.

**Comment by alienfxfiend** [comment]
Lag is a side issue, I'm talking about the rendering which is all wrong\ broken due to the fixing of the EPUB loadtimes. The images are in front of the text (not just in pg 418 but every image on every page) ! This needs to be addressed.

**Comment by kjk** [comment]
The issue of images overlapping text is fixed in latest pre-release 14994 or later

**Comment by alienfxfiend** [comment]
Thanks ! ♥
