### ISSUE TITLE
Can't use backspace key to delete text in find 

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#2623]
![image](https://user-images.githubusercontent.com/7196377/170849479-aba21e7e-8f01-47da-b9cb-4fde2aa831e3.png)

Windows 10 x64 LTSC 21H2
SumatraPDF 3.4.2

**Comment by kjk** [comment]
It's fixed in pre-release (https://www.sumatrapdfreader.org/prerelease) and will be fixed in 3.4.3
