### ISSUE TITLE
Pre--Rel crash Win 7x32

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2624]
using that big sample from https://github.com/sumatrapdfreader/sumatrapdf/issues/2607
getting a crash, preloaded symbols but no crash loging only seeing windows close program

Problem signature:
  Problem Event Name:	BEX
  Application Name:	SumatraPDF.exe
  Application Version:	3.5.0.0
  Application Timestamp:	6292d7f3
  Fault Module Name:	USER32.dll
  Fault Module Version:	6.1.7601.24545
  Fault Module Timestamp:	5e0eb75b
  Exception Offset:	0006675c
  Exception Code:	c0000409
  Exception Data:	00000000
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	2057
  Additional Information 1:	a8cb
  Additional Information 2:	a8cb5b468d47cb5a1cf8370416bc4c78
  Additional Information 3:	9346
  Additional Information 4:	9346ee78ddb97f551da354e996ea778d

**Comment by kjk** [comment]
32-bit builds crash on exit. I'm looking into it.
