### ISSUE TITLE
Problem in rendering fonts

### ISSUE THREAD

**Issue by vladcykka** [sumatrapdfreader/sumatrapdf#2625]
Several fonts that I have installed seem to have a problem in rendering (using the Ebook UI for epub files). The fonts as seen in the reader have jagged edges. How do you fix this?

Fonts in question include Karla, Helvetica, Helvetica Neue, among others.

**Comment by GitHubRulesOK** [comment]
Older versions used only one generic font for ebooks, newer try to use the internal definitions, with mixed success, depending on author!
Each version may have different abilities, you have not specified version. 

However in general only current pre-release (3.5.#) can itself be "fixed" for any fixable inbuilt problem, given a problem sample.

**Comment by vladcykka** [comment]
I think I lost you there. Can you explain what you mean by version? Are you referring to the Sumatra PDF version? 

I also seem to have another problem - mostly with spacing and sizing of particular fonts. I really like this particular font called Amiri, but when I use it for epubs I get this https://imgur.com/a/MuIvokG. Not particularly off-putting at first sight, but in relation to other fonts, the text size is unusually small, spacing b/w sentences and words are very large. How does one fix this (since there seems to be no way to set this in the settings notepad file)? 

P.S. It doesn't look like an issue with the font itself - I've tried the same in another EPUB reader (Calibre) and I've tried the font out in Notepad and Word.

**Comment by kjk** [comment]
This screenshot doesn't show a problem to me. I don't see jagged edges there.

There's nothing I can do without a sample file showing the problem and even then the rendering engine comes from mupdf so it's unlikely that I'll make major changes like changing the rendering.

**Comment by vladcykka** [comment]
My bad I shared a different screenshot. I'll link the screenshot with the jagged edges here. https://imgur.com/a/OJyQ4p3 (The fonts shown in order are: Helvetica, HelveticaNeue, Karla, and Austera Text) JPG compression might make the edges seem a lot harder to notice but it's pretty evident in the PDF viewer.  
I'm afraid I can't share an epub file using GitHub. But the problem seems to persist in any given epub file. 

As a side note, is it possible to make changes to the font display itself as I suggested? Increase the native size, reduce spacing between words and lines? Because a few fonts are really tiny and have a lot of padding and this seems to be only in sumatra.

**Comment by GitHubRulesOK** [comment]
It is not currently possible to change fonts, the rendering was changed from ebook pixel type fonts to default font rendering however for comparison here are Old render, New render and Edge
![image](https://user-images.githubusercontent.com/12754913/171000860-f4f36dd5-3c31-4692-b9ad-238e88d11f02.png)

**Comment by vladcykka** [comment]
Ahhhh right right. Two things: how does one resolve the issue of aliasing in the version that I have?

And will the option to change fonts be added later on, into the newer versions?

**Comment by GitHubRulesOK** [comment]
Aliasing was a side effect of pixelating fonts. Unsure if some widows/sizes were better , cant say I ever noticed much of a problem on any screen, but then in past not using modern hires/dpi scaling. 200 x XY% =4 pixels per pixel.

Fonts is tough because some ebooks have them built in like PDF and others do not thus a default font would need to cover all styles and languages. It should be possible but I am not developer and he has many priorities.

**Comment by vladcykka** [comment]
Right, so should I change any scaling settings or how do I go about fixing it?

Sumatra is one program that I really liked because of the crazy good customization for ePUB files. Still, I really appreciate the program. @kjk I'm assuming you're the developer, so thanks a lot for making an amazing product! I'd like to know how feasible it is to keep the fonts settings for epub files.

**Comment by GitHubRulesOK** [comment]
windows has many ways to modify app compatibilities but pixel edges are often difficult to tune hence many ways. you could see if compatibility setting help but font scale in small steps `FontSize = 12.55` may be just as good 
![image](https://user-images.githubusercontent.com/12754913/171025868-8e20ce27-9812-411f-b15e-449eca4fc933.png)
