### ISSUE TITLE
3.5 installer won't change destination folder

### ISSUE THREAD

**Issue by bobvance** [sumatrapdfreader/sumatrapdf#2626]
I (almost) always install my add-on programs, such as Sumatra, under a non-default destination location:
  C:\Program Files\_MY_Progs\
or
  C:\Program Files (x86)\_MY_Progs_x86
.e.g.
   C:\Program Files\_MY_Progs\SumatraPDF
.
Also, the account that I run under is an admin account.
Up thru 3.4, the installers allowed me to change the destination with no problem.
3.5 pre-release,
when I select all users, and make the destination change,
the installer igores my change
and always puts it in
   C:\Program Files\SumatraPDF
.
Earlier releases did not do this.

bv

**Comment by GitHubRulesOK** [comment]
security in windows 10/11 needs all user exe in "Program Files" [{x86)] was always default and still should be for "all users" then the shared preview and search options dlls should work for all users.

If you change an installed version to elsewhere you need to beware the consequences to windows security.

If all users are not using either search or preview simply use portable in any folder you like or let them install as single users.

**Comment by bobvance** [comment]
Please read my edited/updated post above.

I install in a sub folder of C:\Program Files
_MY_Progs
e.g.
C:\Program Files\_MY_Progs\SumatraPDF

The installer let me try to change it,
but ignored it and used
C:\Program Files\SumatraPDF
anyway

**Comment by bobvance** [comment]
Note: this occurs when I select "All Users"

**Comment by GitHubRulesOK** [comment]
Bob I see your update and bid more 🙂 3.4.3 or 3.5 pre-rel but check previous is not there (uninstall is not always my habit 🙂 )
My update was add it after select all users (I personally work back/upwards through options)

**Comment by bobvance** [comment]
@GitHubRulesOK

You did not read the post carefully:
"Up thru 3.4, the installers allowed me to change the destination with no problem"

It is 3.5 which has the problem.

**Comment by GitHubRulesOK** [comment]
Bob
![image](https://user-images.githubusercontent.com/12754913/171015579-0a3a2d87-dd20-45a0-9aba-cf499e653c96.png)
![image](https://user-images.githubusercontent.com/12754913/171015664-bbd24933-f279-439f-a208-ebab54ad527e.png)

**Comment by bobvance** [comment]
@GitHubRulesOK
Yeah.
kjk  said, above, that he fixed it (thanks!),
but I did not immediately understand his quiet little post ~8-/
(sorry!)
I just downloaded v3.5.14987
and it installed properly and, importantly,
I am  happy ;-)

bv

**Comment by bobvance** [comment]
I updated my forum post.

I install in a *sub* folder of C:\Program Files
_MY_Progs
e.g.
C:\Program Files\_MY_Progs\SumatraPDF

The installer let me *try* to change it,
but ignored it and used
C:\Program Files\SumatraPDF

tks
bv
Tks,
bv
---
"The lyf so short, the craft so long to lerne."
 - Chaucer
-----------------------------------------------------------------
