### ISSUE TITLE
Close Directory Tab Crashes

### ISSUE THREAD

**Issue by dominiosc** [sumatrapdfreader/sumatrapdf#2627]
In 3.5.14978 x64
Open dir function work, but when try to close with mouse, from tab it crash and need to delete from advanced settings to be able to reopen Sumatra:

			[
				FilePath = C:\Users\dc\PC\Documents\pdf
				DisplayMode = continuous
				PageNo = 33
				Zoom = 75
				Rotation = 0
				ScrollPos = -1 175.001
				ShowToc = false
			]

If you use ctrl+w to close tab, Sumatra it closes unexpectedly, but reopen showing alert can't reopen the directory

**Comment by kjk** [comment]
Hopefully fixed but let me know if it still happens.

**Comment by dominiosc** [comment]
In 14980 it's fixed, close and open correctly, but the bookmars show correct all documents at directory, but only work the first, when I try to open another document with click or double click, not open, continues in the same.

**Comment by kjk** [comment]
I've created https://github.com/sumatrapdfreader/sumatrapdf/issues/2628 to track this
