### ISSUE TITLE
[Feature Request] Remembering open tabs after restart

### ISSUE THREAD

**Issue by protik77** [sumatrapdfreader/sumatrapdf#263]
As I am a graduate student, I keep open a lot of tabs. Sometimes I need to restart the pc to install a new software or to install new updates. So when I do that & start sumatrapdf again, it forgets all the tabs I kept open. Though they are in the recent files are in the file menu, it would be really nice if sumatrapdf could remember the tabs I kept open before closing & automatically open them for me when I run the program after restart.

**Comment by kjk** [comment]
This is fixed in 3.1

**Comment by protik77** [comment]
Thanks!
