### ISSUE TITLE
"Couldn't initialize printer" doesn't trigger error 

### ISSUE THREAD

**Issue by e-gaulue** [sumatrapdfreader/sumatrapdf#2630]
Hi community,

I'm migrating from a Windows 2008 R2 Server to a 2022. I used to get this script working for pdf files:
```
	(
	REM Apply a stamp
	"qpdf-9.1.0\bin\qpdf.exe" --overlay mask.pdf --from= --repeat=1 -- %1 %TEMP%\%Name%.pdf
	) && ( 
	REM Print to a specific printer 
	"C:\Program Files\SumatraPDF\SumatraPDF.exe" -print-to "Sharp 1" -silent %TEMP%\%Name%.pdf
	) && (
	REM del %1
	) && (
	REM Logging
	echo.%Name% traité sans erreur par %USERNAME%.>> log.log
	)
```

It takes a pdf file, applies a stamp, prints it and if all right deletes it and logs.

Recently, when I applied this on a list of files, it did just print the two or three first ones, but it deletes and logs them all.

If I remove ```-silent``` in my SumatraPDF.exe call, I get "Couldn't initialize printer" windows for all those not printed. As far as I understand, this is due to the Windows stack, and I still don't understand if I can do anything to resolve this.

But, despite this Windows trouble, SumatraPDF.exe returned code shouldn't be ```ok```. If Sumatra didn't manage to print, I should get an error code and so don't go on. I suppose it is due to https://github.com/sumatrapdfreader/sumatrapdf/blob/3b51854d9ac293c35c42c3e9ad7bc4ca9c45777b/src/Print.cpp#L1209-L1212 that should ```return false```.

Could anyone confirm and apply a patch? Could anyone tell more about this windows driver stack trouble or leads to good lecture about it?

Regards,

**Comment by GitHubRulesOK** [comment]
- SumatraPDF is a GUI PDF GDI reading application/pdf (With steroids.)
- Adobe Reader / Edge / Chrome --headless are not intended for use on servers thus unsupported for silent printing
- SumatraPDF has a go / no go, minimalist approach to printing thus since 3.0 printing is 100% down to GDI drivers and their fails (last year about every 3 months MS caused Print Nightmares on Tuesdays, then changed their "fixes")
- If the file is invalid or the drivers bork it should not be an error condition for feedback (printed / did not print)
- 
Handower Error ***Errorlevel 3***

![image](https://user-images.githubusercontent.com/12754913/170972286-605a9f56-9e35-47c5-85c4-7d6dac69e5b2.png)

Handover succeeded ***Errorlevel 0***

![image](https://user-images.githubusercontent.com/12754913/170972607-331e3357-305f-473d-8ef4-9dbba8cd2b47.png)
![image](https://user-images.githubusercontent.com/12754913/170974427-825878ff-d61e-4673-9d1b-cac41f23bf69.png)

**Comment by e-gaulue** [comment]
Hi @GitHubRulesOK,

To be sure I understand SumatraPDF request driver to print the doc but it's a top down request with no return messaging system, so SumatraPDF can't know if the doc is printed or not. 

That's it?

**Comment by GitHubRulesOK** [comment]
In general that's it watch the visible command line 
the errorlevel is returned instantly at handover
the error is generated then by the printing system
like "you ran out of ink" etc.
SumatraPDF spools the next command before previous has errored
much the same as chrome headless can error many times whilst spooling multiple renders,
however since chrome is printing its own PDF render you get "it failed several requests ago" messages.
SumatraPDF cannot as it is not itself doing print spooling.

**Comment by kjk** [comment]
1. We already return exit code 1 or more if there's printing failure. The code you point out will return false in this scenario. I don't see checking for exit code in your .bat script (errorlevel) so I don't know what is the basis of the claim that sumatra doesn't return non-zero exit code on printing failure.

2. This error message is pretty generic - a bunch of different things could have gone wrong.

3. Also, there was a bug in `PrintToDevice` where sometimes it would return false even when there was no issue.

I've fixed that and I've added a bunch of logging to print code to pin-point the problem.

So please download the latest pre-release (https://www.sumatrapdfreader.org/prerelease) 14994 or later.

Run printing with `-log`. This should log detailed printing info to a file and open that file when the process exists. Then you can post the log here and there will be more information to analyze.

**Comment by kjk** [comment]
So I just found out: you can't test for exit code for GUI apps from batch scripts / powershell etc. It's just how windows works.

SumatraPDF is a gui app so it doesn't matter what exit code we return, it won't be visible to your .bat script.

You can use the `-log` option in latest pre-release builds to figure out what goes wrong when printing, but you can't know in batch script if printing failed or not.

**Comment by GitHubRulesOK** [comment]
Hmm I am no authority on how the code or windows works but I suspect start wait will not indicate any print errors just make them more verbose in their delay

start wait application response is not relevant other than to visibly show shell errors so it waits in this case for

>start "" /wait SumatraPDF.exe -print-to-default pipo.pdf
Fail in invoke exe
![image](https://user-images.githubusercontent.com/12754913/171155345-85dfbed9-6dd9-4660-8faf-21c5760f6ddb.png)
The system cannot find the file SumatraPDF.exe.

or worse I don't have a default print system so valid SumatraPDF crashed and burned (NOT its fault) so waited with
![image](https://user-images.githubusercontent.com/12754913/171156104-18657903-1dc6-4455-81fc-0d4c8f79de21.png)

**Comment by GitHubRulesOK** [comment]
Can't say its always been the same but 3.2 / 3.3 / 3.4 / 3.5 all behave similar

was SumatraPDF started with valid arguments yes=0 or no=something else?
 else don't wait and get on with the next invocation of show next page or whatever

**Comment by e-gaulue** [comment]
Ok, so I did process monitor Sumatra.

I used this command:
> (start "" /wait SumatraPDF.exe -log -print-to "Sharp FACTURES" pdf-exemple.pdf) & echo %errorlevel% > tempo

I wrote the ```errorlevel``` in the tempo file just to be able to log it in process monitor. I can assure that the %errorlevel% we get is the one send by Sumatra. In process monitor, we can see it few lines before in the "Process Exit" event.

But Sumatra is right, those no link, no ink, no paper are not printed but they have been accept by the printer spooler. As long as the spooler is alive, if link/ink/paper is back the file should be printed. So an exit code of 0 is rather good.

The trouble looks to be with situation triggering "Couldn't initialize printer", but instead of keeping it in the spooler for trying later, Windows looks to trash it. It's a shame!

So, for my specific usage, I decided to disable the spooler for this printer. It looks quite slower, even if to be true it takes the same time. Only difference is the user don't get the prompt back as fast.

**Comment by GitHubRulesOK** [comment]
"Couldn't initialize printer" means there is no defined object to render too so there would ergo be no file to send to driver thus no file for driver to send to spooler thus no port input or output 

Its like a relay sprint with hurdles. if there is no second man the first will simply lay down in tears, and blindly get on with prepping for next race.
