### ISSUE TITLE
Respect page argument in links to files

### ISSUE THREAD

**Issue by Clstei** [sumatrapdfreader/sumatrapdf#2635]
PDF links from one local PDF file to another PDF do not go to the right page of the target file. Sumatra successfully opens the target PDF, but it does not go to the right page. Instead it always goes to page 1. I would rather expect that it would jump to the right page in the target PDF.

### Background:
We are creating our PDFs using Latex and are intensively using external cross-references. These are hyperlinks from one PDF to another one, created with the XR-Hyper Latex package.

### Versions:
We like Sumatra very much. It is our standard PDF viewer. Until Version 3.1.2 our external PDF links worked very well. But all newer versions (up to most recent 3.4.3) exhibit the issue. 

Please also note that other PDF viewers (such as Acrobat) do not have problems.

### Reproduce:
The issue is easily reproduce with both attached PDF files. 
[source.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8798656/source.pdf)
[target.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8798657/target.pdf)
Open the source.pdf and click the link. It will open target.pdf. 
But it always starts at page 1, instead of the right target page 2.

**Comment by meisterallerklassen** [comment]
Yeah would be pretty nice if that would work.

**Comment by GitHubRulesOK** [comment]
Interesting method annotation link does not work in Edge
![image](https://user-images.githubusercontent.com/12754913/199576104-3c9cfb0c-75ed-4a81-b550-833c056d987c.png)

However on first run of
```
/Subtype/Link/A<</F(./target.pdf)/S/GoToR/D(chapter.1)
```
returns me this for no rhyme or reason (not the first ./*.pdf)
![image](https://user-images.githubusercontent.com/12754913/199576774-55c0fb93-d8be-4077-801d-5a199f27ad47.png)

But must agree on further runs in pre-release opens target one page before destination

**Comment by Clstei** [comment]
Hello Krzysztof

May thanks for creating SumatraPDF.

This is just to confirm that the current release version 3.4.6 (2022-06-08) as well as latest pre-release build version (15376, built on 2023-03-25) still suffer from this issue. All versions after 3.1.2 do not jump to the target link when opening a PDF. I depend on this feature, which is why I cannot update to a new version.

I very much like Sumatra as my favourite PDF viewer. Especially I do appreciate its integration with LaTeX. By the way it is LaTeX which I use to create those PDF hyperlinks.

Do you see any chance to get this issues fixed? 

Thank you very much
Clemens

**Comment by GitHubRulesOK** [comment]
@kjk @Clstei 

This appears to be fixed more recently both without and with tabs
![image](https://user-images.githubusercontent.com/12754913/227798718-a75e05e0-24e6-4a0a-9e87-c83c8fbce35c.png)
![image](https://user-images.githubusercontent.com/12754913/227798945-fc676e8b-d59a-47bf-aa4e-f26398b7012a.png)

**Comment by Clstei** [comment]
> @kjk @Clstei
> This appears to be fixed more recently both without and with tabs 

@Clstei  @kjk 
Sorry, but I cannot confirm. Please note that in my example the `target.pdf` is expected to be opened at the target mark "Target Chapter" which is on page 2. But Sumatra opens  `target.pdf` on page 1.

**Comment by avorobey** [comment]
@Clstei, I may have a fix for that, but I'd like to test it on a link that leads to a specific page number, and not only (as in your example PDFs) to a named destination in the target file. Do you perhaps have/can produce equally simple test files where source.pdf links to page 2 (say) of target.pdf rather than to the named destination "Target Chapter"?

**Comment by GitHubRulesOK** [comment]
[source.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11073223/source.pdf)
@avorobey modified left half second line should goto page2 rihjght half should goto named-dest

**Comment by avorobey** [comment]
Thanks! Seems like both kinds of links are working, as I'd hoped.

**Comment by GitHubRulesOK** [comment]
darn quick as usual !

**Comment by Clstei** [comment]
Happily I can confirm that the last pre-release build version 15377  built on 2023-03-26 (containing the bug fix) works well. 
GREAT! Thanks.
