### ISSUE TITLE
Feat. req: Preserve tab order on CTRL + SHIFT + T 

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [sumatrapdfreader/sumatrapdf#2636]
Thank you for CTRL + SHIFT + T :)

It could be improved by preserving tab order on reopening, like web browsers do:
1) Open 10 tabs in chrome (firefox..);
2) Close 2nd 3rd and 9th tab;
3) CTRL + SHIFT + T 3 times ->
4)Tab order is the same as was in step 1.
5) Repeat steps 1 .. 3 in SumatraPDF ->
6) Reopened tabs are not in the same order as set in step 1 (reopened tabs appears at the end of a tab row.

See feature requested at 00:12:

https://user-images.githubusercontent.com/46539653/171012302-c44e8972-2bdd-4798-b8ea-d3eb325a16cf.mp4

![2545u](https://user-images.githubusercontent.com/46539653/171012389-547eed2d-0828-4b35-b86a-7b24d0068dd2.png)

**Comment by kjk** [comment]
Too much work for too little benefit.
