### ISSUE TITLE
Issues with rendering fonts in fb2 files.

### ISSUE THREAD

**Issue by Dharmainiciativ** [sumatrapdfreader/sumatrapdf#2637]
Issues with rendering fonts in fb2 files.
The screenshot shows the differences between the current prerelease version and versions 3.4.3
https://imgur.com/a/PPg43u8
The problem concerns only the fb2 format, on epub files the font is normal.

**Comment by GitHubRulesOK** [comment]
@jkj
 not always noticeable but I guess something in newer MuPDF is altering font handling (anti-aliasing changed?)

 here on FB2 from https://github.com/sumatrapdfreader/sumatrapdf/issues/2619 the pixilation is just noticeable in pre-rel
this was also mentioned in another comparison re fonts see https://github.com/sumatrapdfreader/sumatrapdf/issues/2625#

![image](https://user-images.githubusercontent.com/12754913/171062898-08efc7c0-057f-482f-b3d3-c9bc7ce88fa1.png)

**Comment by kjk** [comment]
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=705375
