### ISSUE TITLE
In `Book View` mode, Horizonal image (double page) should be single

### ISSUE THREAD

**Issue by GihanSoft** [sumatrapdfreader/sumatrapdf#2639]
When reading comics and mangas in `Book View` mode, there are some horizonal image that represent 2 combined page for better experience. This kind of pages should be viewed alone because they are actually two page and when a second img is a side of them, it is not look good and make them smaller.

**Comment by GitHubRulesOK** [comment]
Duplicate of something, let me seek which one,

**Comment by GitHubRulesOK** [comment]
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/872 
Related discussion https://github.com/sumatrapdfreader/sumatrapdf/issues/1324
