### ISSUE TITLE
Tabs Styles, Frequently Read Style, General Style 

### ISSUE THREAD

**Issue by Bit-Dust** [sumatrapdfreader/sumatrapdf#264]
Hi! I love **sumatra**, fast and lightweight, **excellent!** I'd like to know if there is some way to configure the tab's roundness (I prefer squeare tabs). Also, my request is about a **Modern UI** Style for Sumatra. The frequently read could looks like the Kindle home page showing the entire PDF Cover [Like this](http://cdn2.ubergizmo.com/wp-content/uploads/2014/05/kindle-paperwhite-review-cover-view.jpg) or a default PDF file image. The icons can have a flat design style. So, I'm talking about a general style changes. I'd like to help and contribute with that on the Sumatra project or a Sumatra fork but I need some documentation about all the designs definitions and the used libraries. I don't have experience working with **Gdi+** but I will learn.

Regards!

P/S: I'm Argentinean developer, sorry for the english!

**Comment by kjk** [comment]
Go for it but don't expect any documentation. You have to figure things out by reading the code.

There are few high-level things to know:
- we use win32 APIs directly so all you need to know is how that works. They are documented on msdn e.g. https://msdn.microsoft.com/en-us/library/windows/desktop/ms632680(v=vs.85).aspx
- we use C++ but don't go overboard the way e.g. boost does
- we don't use STL
- we don't use exception

We would love more people contribute code, we do ask people to follow the style of existing code when adding new code.

If you need win32 refresher:
- http://zetcode.com/gui/winapi/
- http://www.winprog.org/tutorial/
- http://www.relisoft.com/win32/

**Comment by kjk** [comment]
For people new to code: https://github.com/sumatrapdfreader/sumatrapdf/wiki/Contribute-code, https://github.com/sumatrapdfreader/sumatrapdf/wiki/Some-notes-for-developers-new-to-Sumatra
