### ISSUE TITLE
Sumatra-PreRelease Rendering Glitches in EPUB mupdf Engine Not in 3.2!

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#2643]
The text is truncated in latest Pre-release but in 3.2 it's wrapped around properly. The link to the EPUB is here: [Slow Loading of 11 MB EPUB](https://github.com/sumatrapdfreader/sumatrapdf/issues/2607) Wonder if something can be done to fix it; as shown in these two screenshots ( 1. Sumatra-3.2-ProperTxtRender versus 2. Sumatra-Pre-OutOfBoundsTxt ):

File in Sumatra Pre-Release (text is cut at the edge):
![Sumatra-Pre-OutOfBoundsTxt](https://user-images.githubusercontent.com/32994445/171270614-2c0fb48f-0477-471d-b3b4-c23821593481.png)

File in Sumatra 3.2 (displayed correctly):
![Sumatra-32-ProperTxtRender](https://user-images.githubusercontent.com/32994445/171270701-fee977fe-f31e-418a-a335-c2998e8890fc.png)

I think it has to do with the way the embedded text in a different font & in the box is rendered. The main text has no issues, just the code boxes which are lengthy. SumatraPDF 3.2 had its own problems like when you go back & forth between Bookview pages, they would sometimes get re-shuffled. P.S: I apologize for the constant barrage of reports ♥

**Comment by GitHubRulesOK** [comment]
@kjk there does seem to be a scaling issue (css ?)
here in the same file the html is rendered one way but as ePub rendered differently
![image](https://user-images.githubusercontent.com/12754913/171433404-34d73301-ed59-4133-93bd-a44f22012aba.png)

**Comment by alienfxfiend** [comment]
Oops sorry, I opened the attached PDF in PDFX-Change Viewer 2.0 Portable & found the same problem (it's inherent in the PDF itself), so it's not a problem /w SumatraPDF's mupdf Engine —I found a better version (w/o corruption) of the e-Book & that is rendering fine on every reader ! Sorry for troubling you ! ♥ [Essential C 7.0 (Mark Michaelis Eric Lippert (editor)) (z-lib.org).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8819138/Essential.C.7.0.Mark.Michaelis.Eric.Lippert.editor.z-lib.org.pdf)
