### ISSUE TITLE
Add keyboard shortcut for favorites

### ISSUE THREAD

**Issue by wogong** [sumatrapdfreader/sumatrapdf#265]
Wish there is a shortcut for favorite, like `Ctrl+B`. 

Many documents are opened in Sumatrapdf. Reopening them after closed the application is really painful. Related issues are #43 #263 

Please take into consideration.  Many thanks!

Best regards

**Comment by quaerenz** [comment]
Why is this feature not yet attended? Add shortcut for favorites is very important.

**Comment by Arklytte** [comment]
I would like to add my voice to this request.  I make/utilize a significant number of PDF's daily that dont have Bookmarks.  Being able to quick add favorites would be a HUGE timesaver.

FYI, I'm a HUGE fan of your software, and have been using it for a couple of years.  I use it exclusively at work and at home and find it to be (mostly) far more user friendly than it's competition.  However, the lack of user customization for keyboard shortcuts is very frustrating.

**Comment by kjk** [comment]
"Alt - a" followed by Enter works as a shortcut.
