### ISSUE TITLE
Word -> PDF -> Printer: fails on equations

### ISSUE THREAD

**Issue by simon815** [sumatrapdfreader/sumatrapdf#266]
Hi there, 

i have problems with word-generated pdf's, that contain equations. Sumatra displays the pdf correctly, but the printed result is kind of buggy. Some characters are printed out nice, some are not. 

For better replicability i uploaded 3 files: http://ge.tt/9xpxUOM2
- word 
- from word generated pdf
- printed and scanned result as pdf

Greetings
Simon

**Comment by kjk** [comment]
Please try latest pre-release (http://www.sumatrapdfreader.org/prerelease.html). This should already be fixed.

**Comment by simon815** [comment]
sorry for not testing this with the pre-release before and thank you. issue resolved :)
