### ISSUE TITLE
What happened to right-left scrolling?

### ISSUE THREAD

**Issue by vie2004** [sumatrapdfreader/sumatrapdf#2661]
just updated to [portable] version 3.4.4 64-bit and can't figure out where to adjust to the old settings.
When comparing the "SumatraPDF-settings.txt" file with the one from my backup everything seems to match, but the 'View' is clearly not matching the old style.  Only up-down scrolling, no old background, huge page-filling book cover, font different, etc. and no matter what I change in the settings has no effect whatsoever.
Downloaded the App several times, ran it as 32-bit and install version as well with no change in behavior. 
Does anyone have any clue what happened here?
Any help is highly appreciated.

Thanks in advance and stay safe!

**Comment by kjk** [comment]
I assume you're talking about eBook UI (epub, mobi).

We changed the rendering engine. New engine renders ebooks better, we get search and text selection / copy but we lost the old ebook UI (at least for now) and some customizability options.

**Comment by vie2004** [comment]
Thanks for the info/feedback.
Guess I'll stick with the previous version until you get a handle on the eBook UI and customization.
Keep up the good work and stay safe.
vie
