### ISSUE TITLE
Bug with clipboard in Windows 10 (a problem with text encoding)

### ISSUE THREAD

**Issue by zagursky** [sumatrapdfreader/sumatrapdf#267]
Hello,
there is a problem with text encoding in Windows 10.
When you copy text from a file to the clipboard, then paste, then instead of the text are inserted question marks. For example, the copied text is 12345, then insert ????? 

Thanks for the program!

**Comment by kjk** [comment]
Which version of Sumatra is it?

Does it work in other PDF readers like Adobe?

Does it fail in latest pre-release (http://www.sumatrapdfreader.org/prerelease.html) as well?

Does it happen with every PDF or just one?

If only with one, please provide the PDF that shows the problem.

**Comment by campbeb** [comment]
I can reproduce this with current master branch.
An example PDF file is here: http://campbeb.github.io/Math%20f.pdf

Steps I used to recreate:
 - In PowerPoint 2013, insert equation and choose just simple math f
 - Save as PDF
 - Open PDF with Sumatra
 - Select f and copy. Past into another document (such as Word)
 - Character pasted isn't same as the one copied.

Note: This is same as #222

**Comment by kjk** [comment]
Does it work correctly in other PDF readers like Adobe?

Sometimes malformed PDF documents don't include enough information to map a glyph to a character code. It's only a bug in Sumatra if other programs can handle it correctly.

**Comment by campbeb** [comment]
Yes, it works correctly in Adobe with the same file.

It seems odd that it displays correctly, but not copied or printed correctly. It looks like copy comes from DisplayModel->textCache, which seems to get the incorrect value when loaded.
