### ISSUE TITLE
the change of length of title blocks in tab bar is laggy when switching between "maximize" and "restore down" in ver. pre-3.5.15123 64bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2670]
Each file tab in tab bar is shorter when sumatrapdf window is in "restore down" state than in "maximize" state. The length of tabs should change when switching window size between those two state. That change is instant in older prerel version but so laggy in the current ver. pre-3.5.15123 64bit.

**Comment by GitHubRulesOK** [comment]
hmm
@kjk only tried one test but with 4 tabs active dropping from max to restored only showed only the 3 I was not viewing until widow was adjusted when 4th current one reappeared
