### ISSUE TITLE
Add searching in epub

### ISSUE THREAD

**Issue by gblazex** [sumatrapdfreader/sumatrapdf#268]
seems to be missing.

**Comment by SumatraPeter** [comment]
@kjk - Aren't there so many similar requests that can be marked as duplicates? For example:

https://github.com/sumatrapdfreader/sumatrapdf/issues/199
https://github.com/sumatrapdfreader/sumatrapdf/issues/225

**Comment by SumatraPeter** [comment]
Another similar one: #239

**Comment by monolied** [comment]
You have to set "UseFixedPageUI = true" in the EbookUI-section of the advanced options. The option is set to false there. After that (and a restart), you don't have the flowing text with epub anymore, but the navigation bar is back, and with it the search function. Which, in my opinion, is the greatest advantage of digital text over printed one, and therefore absolutely essential in a reader.

**Comment by faridcher** [comment]
@monolied what does it have to do with reflowable text that comes with epub, mobi or awz formats? we can have reflowable text and search in Kindle or desktop apps like Calibre!!?

**Comment by monolied** [comment]
I'm just describing the setting to get the search function back, which seems to be a side effect of switching off reflowable text. I do not know or claim to know why that is, or if there is a causal connection...

**Comment by kjk** [comment]
Closing as duplicate
