### ISSUE TITLE
I can't save an embedded file

### ISSUE THREAD

**Issue by vgyuri78** [sumatrapdfreader/sumatrapdf#2689]
Dear Kjk,

This bug appeared from 3.4, I attached a sample file, please check it.

https://github.com/sumatrapdfreader/sumatrapdf/discussions/2363

[ABCDEF.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8851913/ABCDEF.pdf)

Thank you:
Gyorgy Vaszko

**Comment by GitHubRulesOK** [comment]
@kjk last pre-rel update seems to handle this attachment case in the same reasonable fashion so options to open or save seem to be covered.

@vgyuri78 Please try the current pre-release (otherwise you may need older version 3.1.2 for such embedded files)
