### ISSUE TITLE
Crash after start from Windows 10 "Search" (without file)

### ISSUE THREAD

**Issue by magicprinc** [sumatrapdfreader/sumatrapdf#2691]
I simply have found SumatraPDF in Windows Search (magnifying glass close to "Windows" button) and started it
Boom!
https://gist.github.com/magicprinc/542e94634a66694228504e706339c5a9

**Comment by magicprinc** [comment]
The cause in these settings:

ExternalViewers [
  [
    CommandLine = "C:\Program Files\Google\Chrome\Application\chrome.exe" %1
  ]
  [
    CommandLine = "C:\Program Files\WindowsApps\KDEe.V.Okular_22.401.1031.0_x64__7vt06qxq7ptv8\bin\okular.exe" %1
  ]
]

**Comment by kjk** [comment]
Thanks, will be fixed in 3.5.6 https://github.com/sumatrapdfreader/sumatrapdf/commit/7a19622d5ad35702dad2694cca4873693e88bc4e
