### ISSUE TITLE
arrow buttons in tab bar is buggy in ver. pre-3.5.15162 64bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2696]
After opening multi tabs, clicking arrow button in tab bar seems like copy some tabs multi times and move copies to overlap with other tabs, and hence messes up the whole tab bar. Then, after moving mouse cursor to somewhere else, everything goes back to be fine. Btw arrow buttons in tab bar seems like has no other effects.

**Comment by GitHubRulesOK** [comment]
related to https://github.com/sumatrapdfreader/sumatrapdf/issues/2694

**Comment by GitHubRulesOK** [comment]
@kjk great a related issue was https://github.com/sumatrapdfreader/sumatrapdf/issues/447#
