### ISSUE TITLE
support xfa forms

### ISSUE THREAD

**Issue by raymondjtoth** [sumatrapdfreader/sumatrapdf#27]
name is ray toth piperpiper2@wowway.com i use this site https://myportal.supervalu.com its my job mio system to do thing like view paystub, when i go into it with user name and password job gave me and try to view my pay stub with Sumatra PDF tell me i dont have pdf reader from adobe version 7 or higher can you work on this i like to use sumatra pdf to view my pay stub with my jobs online thing thanks in firefox can you work on fixing this? so i can use it with that thanks so much ray toth pieprpiper2@wowway.com 
other use love it thanks

**Comment by GitHubRulesOK** [comment]
@kjk dup of https://github.com/sumatrapdfreader/sumatrapdf/issues/48#

**Comment by kjk** [comment]
Per https://bugs.ghostscript.com/show_bug.cgi?id=693446 mupdf won't support XFA because it's deprecated in PDF 2.0. For that reason we won't support XFA either.
Although some forms are using AcroForms which is supported by mupdf?
Can't really say much without test documents.

**Comment by GithubUser99999999** [comment]
More than 10 years later this feature is still missing and more and more modern documents use XFA forms which renders SumatraPDF useless.

**Comment by GitHubRulesOK** [comment]
@GithubUser99999999 
XFA are proprietary Adobe XML NOT open licensed PDF per ISO standard which Adobe license for free public permitted usage.

Those using XFA via Adobe license do so by a COVER PAGE as a PDF and the rest as licensed ADE that requires an XFA editor such as Adobe managed Reader DC. Hence there should be a page that ever so clearly says use Acrobat.

Most software houses cannot afford to license nor reverse Adobes own protected software dynamic scripted extensions, especially as in effect like SWF Adobe are the only stakeholders.
