### ISSUE TITLE
Change default parameters of the Free Text annotation

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#2700]
Is there a way to change the default parameters of the Free Text annotation? Every time I add a new one, I'd have to change the following parameters: 
- Text Size: 8
- Text Color: Blue
- Border: 0

It'd be nice to be able to set these as default somewhere in the Advanced Settings document.

_Originally posted by @msn969 in https://github.com/sumatrapdfreader/sumatrapdf/discussions/2695_

**Comment by thesomeexp** [comment]
I have the same need.

**Comment by vincio-collab** [comment]
I have the same need

**Comment by boulash** [comment]
I would love such an option as well.

**Comment by gowski** [comment]
This would be very helpful. Most documents have black text, so defaulting annotations to black text just causes them to blend into the document's text. I also prefer not to use a border because it is unnecessary if the text stands out by itself.

**Comment by rdragoni** [comment]
Same wish here too.

Let me think big... being able to set default values for text size and color, background color, border size and color, dx and dy would be GREAT.

Is it feasible to add (manage) these values with a few more lines in the advanced option txt?
Even better, have dx and dy values editable through the "edit annotations" interface and add a "save as default" or "remember last used values" checkbox.

Above all, my sincere compliments to the developers and contributors.
I've discovered Sumatra not long ago but it's already, and will probably long be, my favorite PDF reader.
Keep it up!

**Comment by totooqiao** [comment]
Now that this issue has been resolved, will there be a new release? I noticed that there hasn't been a new release, and this feature is still unavailable. My current version is v3.4.6.

**Comment by kjk** [comment]
You can get the latest code in pre-release version: https://www.sumatrapdfreader.org/prerelease

A release will happen eventually.
