### ISSUE TITLE
Please add drop-down Zoom menu to the toolbar

### ISSUE THREAD

**Issue by DanielYurystovskyi** [sumatrapdfreader/sumatrapdf#271]
I want something similar to this, with ability to enter your own zoom percents
![adobereaderscreen](https://cloud.githubusercontent.com/assets/12008774/9562620/7cd9169e-4e79-11e5-8296-d6184a064560.png)

**Comment by vlakoff** [comment]
See #332.

On a related note, great graphic skills. Are you available for hire?

**Comment by GitHubRulesOK** [comment]
@kjk 
potential duplicate of part of https://github.com/sumatrapdfreader/sumatrapdf/issues/1117 which requests these zoom box/buttons and in issue 1117 also for facing/book view controls

**Comment by GitHubRulesOK** [comment]
@vlakoff  **Thanks** the current aim is to reduce open issues by merging similarities, @kjk has requested that those with "best" description may be promoted over "older" issues which makes for a greater challenge.

**Comment by GitHubRulesOK** [comment]
@kjk suggest this is closed as this request is currently available via CTRL Y
![image](https://user-images.githubusercontent.com/12754913/70012330-08696e80-156c-11ea-9005-9048c34c2fde.png)

**Comment by SumatraPeter** [comment]
I wouldn't exactly say that Ctrl+Y is a perfect solution for all. Just think of tablet users for example...

However all such issues do fall under the same generic "user-customizable toolbar" request.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
whilst the title did say toolbar and the shot from acrobat is in the toolbar, we both know SumatraPDF policy on toolbar even if it is crippling me when I use my tablet to have to contort through a virtual keyboard. In the spirit that some users are often unaware that many invisible functions can be called up via the trad keyboard especially if the read the "manual" I deemed the request was met by current design :-)

**Comment by WinfredHuang** [comment]
> [@SumatraPeter](https://github.com/SumatraPeter) whilst the title did say toolbar and the shot from acrobat is in the toolbar, we both know SumatraPDF policy on toolbar even if it is crippling me when I use my tablet to have to contort through a virtual keyboard. In the spirit that some users are often unaware that many invisible functions can be called up via the trad keyboard especially if they read the "manual" I deemed the request was met by current design :-)

And that's the arrogance of RTFM.
