### ISSUE TITLE
unwanted debug spew on console when invoked from WSL

### ISSUE THREAD

**Issue by 0xabu** [sumatrapdfreader/sumatrapdf#2710]
I just updated to 3.4.6 (from 3.3.3, using the chocolatey package), and I've noticed SumatraPDF is now spewing debug output on my console. I don't think it ever did that before. Has it been compiled with debug enabled by accident, or is there any way to turn this off?

Example:
```
$ SumatraPDF.exe paper.pdf &
[2] 2142
$ Starting SumatraPDF, GetCommandLineW():
SumatraPDF.exe paper.pdf
OpenEmbeddedFilesArchive: opened archive
prefs::Load() took 0.52 ms
ParseTranslationsTxt: 19181 lines, nStrings: 357
LoadDocument: 6.77 ms, 19 pages for 'C:\Users\me\Documents\paper.pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.00 ms
StartMonitoringDirForChangesAPC() C:\Users\me\Documents
StartMonitoringDirForChangesAPC() C:\Users\me\AppData\Local\SumatraPDF
```

**Comment by 0xabu** [comment]
Hmm. On further investigation, I found that 
 * chocolatey's [sumatrapdf.install](https://community.chocolatey.org/packages/sumatrapdf.install) package ends up in AppData\Local\SumatraPDF by default (I don't think this matters?)
 * The log output appearing on the console only happens in WSL. It doesn't repro in CMD.

Still, it has definitely changed from earlier versions. I'm guessing something in my environment when I run from WSL. I'll dig deeper.

**Comment by GitHubRulesOK** [comment]
local is one user default install (program files is all users)

WSL is untested by me, can not say for developer

**Comment by kjk** [comment]
We do more logging because it's important for diagnosing problems that happen on other people's machines and it's always enabled, not just in debug build.

I'm guessing the difference between WSL and cmd / powershell is that WSL somehow connects the console to GUI process so our console output goes to, well, console.

Typically for GUI program to output to a console from which it was launched, you have to specifically ask to connect stdout to parent's console. Maybe WSL console works differently.

Or WSL shows the output of `OutputDebugString` calls, which are intended for debuggers.

**Comment by 0xabu** [comment]
More discoveries:
 * it only happens from when I launch from WSL and background the process on launch (i.e. `SumatraPDF.exe foo.pdf &`)
 * no repro on 3.3.3, confirmed repro on 3.4 onwards

So as much as this is a WSL gremlin, it also appears to be triggered by some kind of change in Sumatra introduced with 3.4.

**Comment by GitHubRulesOK** [comment]
& is usually concatenate (start) second process so what is it there for ?

**Comment by 0xabu** [comment]
In Bourne shell, `&` starts a command asynchronously.

Refer https://www.gnu.org/software/bash/manual/html_node/Lists.html#Lists:
> If a command is terminated by the control operator ‘&’, the shell executes the command asynchronously in a subshell. This is known as executing the command in the background, and these are referred to as asynchronous commands. The shell does not wait for the command to finish, and the return status is 0 (true).

**Comment by 0xabu** [comment]
Possible change that exposed this: a81ad544fa846a6087f43a93671bd9373e95f3fe (changing stderr log outupt to stdout, but more significantly enabling it by default from WinMain).

**Comment by GitHubRulesOK** [comment]
I dont follow the code but that seems to be logging install or stress test
 your log should from my usage only be built as `C:\Users\...\AppData\Local\sumatra-log.txt` when -log is used at runtime, but as said I dont know how it may differ in WSL shell

@kjk ? Do you have input as to odd output ?

**Comment by 0xabu** [comment]
I believe @kjk already said that it's intentional that if a console is attached, we see the log output. It wasn't obvious from his earlier comment whether that was part of 3.4, but it could be. When I have time I'll dig into the bug/weirdness on the WSL side, because the fact that interop process is background or foreground shouldn't change the presence of a console (IMO).

**Comment by 0xabu** [comment]
I've been told this is "by design" for WSL. In any case, it's clear this is not the fault of SumatraPDF, besides the fact that it relies on a rather unusual (but documented) aspect of the Win32 API.
