### ISSUE TITLE
Maximize Window, bad renders tab

### ISSUE THREAD

**Issue by dominiosc** [sumatrapdfreader/sumatrapdf#2716]
In 15184 persists, for a few versions.
When restore windows and maximize, the tabs render bad, you only need to put mouse on it, and it will be seen correctly again.

![imagen](https://user-images.githubusercontent.com/63964184/173206682-0cb012fe-4fb7-4b31-8853-9c1d5fc80e9f.png)

![imagen](https://user-images.githubusercontent.com/63964184/173206697-84692e69-ec85-4430-a4a6-d930fdbb11eb.png)

**Comment by kjk** [comment]
I believe this is fixed now.
