### ISSUE TITLE
scroll down/up by half page

### ISSUE THREAD

**Issue by amosbird** [sumatrapdfreader/sumatrapdf#272]
It will be more ergonomic to scroll down/up by half page just like Ctrl-d/Ctrl-u does in Vim.

**Comment by corneliusroemer** [comment]
I agree, this feature would be great! Why did you close this issue? I will reopen, it would be much better to have half-page than full-page scrolling.

**Comment by GitHubRulesOK** [comment]
If only half a page is showing in either fixed page or continuous mode then CTRL Down /Up arrow will start every second step at top of page (thus not exactly half but a roughly equivalent move)

**Comment by folofjc** [comment]
> If only half a page is showing in either fixed page or continuous mode then CTRL Down / Up arrow will start every second step at top of page (thus not exactly half but a roughly equivalent move)
> 
> If current page height is less than half page the numer of steps is clearly more so every 3 or 4 etc. will realign. that feature can be useful for hands free stepping by say a musician via a pedel or dedicated AutoHotKey script.

`CTRL+Up` does not do this. What `<C-d>` does in vim is jump have a _screen_ height, not half a page. So it should do half of whatever `<Space>` does. Agree that this is great and should be re-opened.
