### ISSUE TITLE
Tab Name Contains Gibberish? 

### ISSUE THREAD

**Issue by nutnutwin** [sumatrapdfreader/sumatrapdf#2722]
Hi, I run SumatraPDF on three PCs, all Windows 10/11 Pro
When I open ｢2022_Bonus.pdf｣ on these PCs, 
> 2022_Bonus.pdf - [iWFM Server] - SumatraPDF

Thank you. 

@kjk

**Comment by nutnutwin** [comment]
Some Follow-Up 
seems that this strings is part of the bookmarks? 
Wonder it is possible to hide them in Advanced Settings.
(Yes it is possible to parse the string, just wonder why such strings are shown
Thank you.

**Comment by kjk** [comment]
I would need a screenshot and a test file that shows the problem (see https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports)

Does it happen when you delete settings file (i.e. revert all settings to default)?

**Comment by kjk** [comment]
Also, please don't @tag me. I read all issues.

**Comment by nutnutwin** [comment]
![IMG_6591](https://user-images.githubusercontent.com/34512273/174467143-922f49d7-1314-47fb-85e3-4a5d0ac3d47f.jpg)
Hi, sorry for the late reply(won't tag)
I am using ｢Window Spy｣ included in Autohot key to see the Title of the window
(for the purpose of automation

The filename is ｢[202106]_Bonus.pdf｣, and while open it shows as 
> ｢[202106]_Bonus.pdf - [iWFM Server] - SumatraPDF｣

with some other files it does not show only
> ｢- SumatraPDF｣
or 
> ｢something from bookmarks - SumatraPDF｣

I can manage to parse the unwanted string, but wonder why they are there?

**Comment by nutnutwin** [comment]
some more info: 
I turn on 

> FullPathInTitle = true

to gain full path from title, so as to show the file in FileExplorer(or other apps)

Thank you.

**Comment by kjk** [comment]
Most likely some other program changes the title of the Window. Sumatra sets the name of the window to file name.

**Comment by nutnutwin** [comment]
Thank you for your help. really appreciate it
As is aforementioned, I can parse the title so there are no real problems at all. 

Thank you.

**Comment by GitHubRulesOK** [comment]
@nutnutwin 
For what its worth  "iWFM Server" is likely the Cannon PDF generator Title"/"Application" =  [iWFM Server] so possible it is detected as Title Application ?

File: blah blah.pdf
Title: iWFM Server
Created: 4/12/2019 4:31:27 PM
Modified: 4/12/2019 7:09:27 PM
Application: iWFM Server
PDF Producer: Canon FM PDF Writer II 1.20
PDF Version: 1.4
PDF Optimizations: Fast Web View

**Comment by nutnutwin** [comment]
@GitHubRulesOK Likely 
Will check if it is the case
Thank you for the tips
