### ISSUE TITLE
UI glitch when closing tabs

### ISSUE THREAD

**Issue by WhiteChairFromIkea** [sumatrapdfreader/sumatrapdf#2726]
Pressing CTRL + W (close tab) here, from 00:03. Not nicely looking tab gap appears between tabs. This started to occur after https://github.com/sumatrapdfreader/sumatrapdf/issues/2694 has been fixed.

https://user-images.githubusercontent.com/46539653/173561585-60c0c1f8-ce6a-4100-a2a7-e5fc9d645f2e.mp4

**Comment by kjk** [comment]
I believe this is fixed now.
