### ISSUE TITLE
Shortcuts in tooltips and menus

### ISSUE THREAD

**Issue by magicprinc** [sumatrapdfreader/sumatrapdf#2727]
Please display shortcuts in tooltips and menus!

I.e.
If one puts mouse over "Find Next" (>), he will see "Find Next (F3)"

The menu item  "Go to | Page..." will look like "Page... (g / Ctrl+G)

It would be a great idea to show shortcuts in Command palette menu too, like
...
Find (Ctrl + F)

**Comment by dominiosc** [comment]
Good improvement, there are many shortcuts and few icons, remember in tooltips is a good idea, I also thought so a long time ago.

**Comment by Podbrushkin** [comment]
Please, make shortcuts visible in command pallete. This is a very nice architecture pattern in app, and it can get even better and more useful. All apps I know show shortcuts in command pallete.

Check it out in Windows Terminal(Ctrl+Shift+P):
![Screenshot 2023-09-22 170536 sm](https://github.com/sumatrapdfreader/sumatrapdf/assets/110057725/362da5b3-32eb-42a5-af2b-31b2de3576d9)

In Microsoft Edge (CTRL+Q):
![Screenshot 2023-09-22 170814s](https://github.com/sumatrapdfreader/sumatrapdf/assets/110057725/ccdd72bd-d793-4c1f-8a71-2aa79cc8f438)

In VSCode (Ctrl+Shift+P):
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/110057725/fa81eb1f-6072-4757-a098-cd186878698a)

Also, speaking of shortcuts, it's preferable for them to be persistent across different apps. In Sumatra command pallete shortcut is currently Ctrl+K, which differs from shortcuts in other apps I have. I hope Ctrl+K isn't unique for Sumatra.

**Comment by GitHubRulesOK** [comment]
Closing as multi part request and 
1) original primary request was fulfilled ![image](https://github.com/user-attachments/assets/1576d70a-1465-49ce-8788-367402a168c7)
2) Secondary requests for Command Pallett entries are covered in a separate clean issue see #3990
3) @Podbrushkin  tertiary request for alter CTRL+ K should be possible via key mapping. in PRe-Release here mapped to `ALT + o`
![image](https://github.com/user-attachments/assets/d45f5d60-9f74-4934-be36-5d6c6a452ba0)
```
Shortcuts [
	[
		Cmd = CmdCommandPalette
		Key = Alt + o
	]
]
```
