### ISSUE TITLE
flickering of a pop -up hint

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#2728]
![image](https://user-images.githubusercontent.com/11432724/173623186-9edd948f-ac88-4b37-9f12-558356e77bb4.png)

![image](https://user-images.githubusercontent.com/11432724/173623337-8ad9c46d-855e-44c1-aa50-45facac15fca.png)

**Comment by GitHubRulesOK** [comment]
closing as effectively same /similar to #2873 which has a sample
