### ISSUE TITLE
Unable to open PDFs from a certain site, example attached

### ISSUE THREAD

**Issue by Robbbert** [sumatrapdfreader/sumatrapdf#2729]
[j6 [F].pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8906946/j6.F.pdf)

This file is one of a number found on a certain site. It can be opened by AcrobatDC (current version = 2022.001.20117) on Windows 10 only. It will not open on Windows 7 or on XP. Windows 7 displays a full-screen Adobe logo, while XP wants me to install Adobe 10 (when it already has Adobe 11). Sumatra PDF shows the same screen (on Win10/Win7) as XP does. What you should get is a one-page schematic diagram of an old transistor radio.

I tried the current version (3.4.6) and the pre-version of Sumatra PDF as suggested.

I cannot know if the PDF is damaged in some way, I will leave that to you to determine.

Please let me know if it's possible for Sumatra PDF to support this file in the future, or if you think I have a bug in my system (I tried multiple computers).

**Comment by tactilis** [comment]
FYI, the circuit diagram can be viewed in SumatraPDF on Windows 7 as follows:

1. Open the original PDF it in Firefox
2. Show Attachments and click on 'J6 (1).pdf'
3. Select SumatraPDF to open the attached '.pdf'
4. Tada!
 
  
![PDF](https://user-images.githubusercontent.com/4060092/173784101-e2a8edab-e34b-4733-8b71-af8aa70086fd.png)
 
  
Note that opening the original file and then Open Embedded PDF does not work in Sumatra (v3.4.6):
 
![image](https://user-images.githubusercontent.com/4060092/173784982-f5d902e3-0c79-40f0-bccb-a51766983286.png)

**Comment by tactilis** [comment]
>I tried your method, but at Step 2 I clicked on J6(1).pdf and it just went back to step 1 - no open dialog appeared. After trying that a few times I noticed something was downloading, so I found a file called pdf in the download folder (and several copies). Renaming this to 1.pdf and double-clicking let it open successfully.

Ah, yes. That will be because in Firefox | Settings, I have Firefox set to Always Ask when clicking on a link to a PDF, whereas yours will still be set to Save File.

I have Firefox ask me because sometimes I want to download and just save the PDF, but other times I want it to download and open automatically in SumatraPDF (or whatever other application I choose).

**Comment by GitHubRulesOK** [comment]
@tactilis I have fond memories of warm hot or cold valves :-)

**Comment by Robbbert** [comment]
@tactilis It's a hobby of mine to repair old valve radios, but somehow I picked up this transistor model. Last week I decided to try repairing it, which is how this PDF saga got started.

**Comment by kjk** [comment]
I've re-enabled opening and saving attachments, as present in this file.

You can right-click on the attachment in the Bookmarks tree view and either open it in Sumatra or save to a file.

![image](https://user-images.githubusercontent.com/7935/175793536-d0961893-af48-4ef4-8739-75cba53e237a.png)


However we won't support more than that in such files unless mupdf implements support.
