### ISSUE TITLE
Synchronization between pdf and tex

### ISSUE THREAD

**Issue by surmann** [sumatrapdfreader/sumatrapdf#273]
Hallo Sumatra-Team!

I use Sumatra in my document workflow with TeXstudio and TeXlive2015 with LuaLaTeX.
Typically, a doubleclick in the pdf sends me to the correct position in the tex file.
In the last chapter I get the message: "No synchronization info at this position". When I try to create a MWE, I figured out that comment out some `\includegraphics` in a `center` environment solves the problem. However, it was not possible for me to create a real MWE.
Do you have a hint how I can solve this problem?

Thanks in advance!

Best regards
Dirk

**Comment by kjk** [comment]
Bug tracker is for reporting bugs.

**Comment by surmann** [comment]
Please help me understand:
The link "eine neue Fehlermeldung" on the [german website](http://www.sumatrapdfreader.org/free-pdf-reader-de.html) links directly to the issues.
The link "bug report" on the [english website](http://www.sumatrapdfreader.org/free-pdf-reader.html) refers at the end to the issues, too.
Where do I find the bugtracker?

**Comment by kjk** [comment]
You seem to be asking a question about particulars of (la)tex integration, not reporting a bug.

For questions we refer people to the forums.

I pretty much don't know anything about tex integration so I won't be able to help.

**Comment by surmann** [comment]
That means, you think this is a TeX problem, right?
Ok, then I will ask in the forum or at StackExchange.
