### ISSUE TITLE
Sumatra PDF beta 3.5.15184 hangs after Print

### ISSUE THREAD

**Issue by steve4github** [sumatrapdfreader/sumatrapdf#2736]
64 bit.  Windows 10 system all updates installed.
Whenever I print a PDF to my HP 1020 printer, SumatraPDF beta 3.5.15184 and the previous beta hangs after the print is complete.  I am trying to print two-sided copies of a 2-page PDF on my old printer, so I print the current page, flip the page in my printer, then print the back of the page with the second PDF page.  First problem, Using "current page" print works and then SumatraPDF closes immediately.  Restarting SumatraPDF has the page loaded, but the current document is not the PDF file I was trying to print.  Second problem, If I print just page 1, or if I print page 2 specifying the page number, SumatraPDF hangs.  And printing all two pages in my PDF, SumatraPDF hangs.   "Hangs" means that SumatraPDF  is unresponsive after the print and no mouse click or keypress work. This has happened to several different PDFs.  Acrobat DC does not have these problems printing the same PDF files.
[GOBA_33_-_1_SUNDAY.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8933843/GOBA_33_-_1_SUNDAY.pdf)

**Comment by GitHubRulesOK** [comment]
Your workflow is not clear since you mention " Restarting SumatraPDF" 

However I have to agree more recent versions seem to go into a hung state
![image](https://user-images.githubusercontent.com/12754913/174446845-f466bf9a-0d20-4fc0-aac2-d866bb43e100.png)
