### ISSUE TITLE
update SumatraPDF-settings.txt

### ISSUE THREAD

**Issue by alialshishani** [sumatrapdfreader/sumatrapdf#274]
i think updating SumatraPDF-settings.txt when you change the page in any book is better than updating when the application closes. because sometimes the computer restarts and then your progress is lost.

**Comment by kjk** [comment]
We optimize the code for common case, not extremely unlikely case (and computer restarting is extremely unlikely) so we won't be changing how SumatraPDF-settings.txt is saved.

**Comment by alialshishani** [comment]
well, i posed this one because i read books on multiple machines, and i want the last page i read to be sharable between my machines, so I got the portable version of sumatra and stored it in my dropbox folder. i can share the last page, but i have to close sumatra on one machine to do that.

**Comment by ahxxm** [comment]
@kjk it happened to me recently due to some driver misconfiguration combined with windows update, seesion data was lost although individual books progress are kept... i found a [todo](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/CrashHandler.cpp#L706) about session data in CrashHandler, is this related?

**Comment by GitHubRulesOK** [comment]
@ahxxm
 this old thread was when session data was not updated per tab change which is generally now the case

The settings file is "volatile" but not as volatile as the state of files in memory. When windows updates it does not clean close apps by waiting, it forces closure, if it thinks there is no fast enough user action then ignores those anyway.

Previously this meant that the history in memory was not rewritten to settings.txt, currently sessions are frequently updated by tab changes, resulting in a much more robust experience.

However its not infallible to outside corruption hence if you thing start of session is mission criticle you need to store start-up setting. that will not protect against session loss but will guard against total loss of start-up.

Its the good old grandfather question did you back-up frequently and switch off at the wall ?

**Comment by ahxxm** [comment]
@GitHubRulesOK ah i see, as i opened another file or scroll down, the new progress is then reflected in SessionData section inside settings.txt... then i don't understand why the session is not restored after abnormal reboot

**Comment by GitHubRulesOK** [comment]
@ahxxm 
Abnormal reboot ***in the past*** (thus historic to earlier versions) often meant no session data saved, currently it should be better (hence issues closed) but there is no way to avoid file corrupting on abnormal exit while writing, if widows kills task while write is in progress the file will be incomplete/invalid. A problem with having all ones goodies in one basket.

**Comment by ahxxm** [comment]
@GitHubRulesOK sorry to be unclear! The reboot i mentioned previously occured after the machine went to sleep/hibernation state for a while(according to the event viewer, which is bedtime), i wasn't using the reader at that time
![image](https://user-images.githubusercontent.com/1286225/171184119-b78d28fe-e0cd-44eb-bc75-55f2eff0557c.png)

**Comment by GitHubRulesOK** [comment]
Unexpected shutdown can certainly cause problems for open files, best to close SumatraPDF and any other apps that have pending edits at bedtime, but after a long session its best to use settings save as (that can be automated by you using scripting but is not an inbuilt feature. one way would be to use "ExternalViewers with a hotkey compbination to save settings file with time date but then you need to manage culling older entries. Not difficult but custom to each user somewhere on old forum I suggested a way to save current tabs so this need could be slightly similar. toughest part is defining a method like date-time

Along the lines of
 name ALT F B &Backup Settings
command copy "/path to /sumatra-setting.txt" "/path to/220530-2300.sumatra-settings.txt"
