### ISSUE TITLE
Missing keyboard shortcuts from the interface.

### ISSUE THREAD

**Issue by medovy** [sumatrapdfreader/sumatrapdf#2742]
In the current version 3.4.6, if you open pdf files by double-clicking (or enter), the keyboard shortcuts are missing from SumatraPDF menu. 
If you open files from start menu of SumatraPDF (or ctrl+o), everything is fine.

I tested the old version (3.2), which I used until recently, there is no such the bug there.

![1](https://user-images.githubusercontent.com/107910762/174734771-9891ee9e-83fb-4e5a-95ac-a523d80b8662.png)

**Comment by kjk** [comment]
Can confirm. Somehow they are present in File menu.
Also, it fixes itself if you close the document or open another one.
