### ISSUE TITLE
zoom levels

### ISSUE THREAD

**Issue by RudiRed** [sumatrapdfreader/sumatrapdf#2743]
Hello, first of all thanks for the wonderful tool :)
Is there a setting to only switch between full page and zoom to page width without intermediate "fit content"?
Thanks from Germany
Rudolf

**Comment by GitHubRulesOK** [comment]
Commonly you would use the 2 icons

![image](https://user-images.githubusercontent.com/12754913/174787422-b454608b-6d3f-4055-9171-2b78a46c26ee.png)

**Comment by RudiRed** [comment]
Hi,

I am a keyboard junkie, a little bit older thus, and I don't wanna use 
the mice. Thanks in advance...

Thomas

Am 21.06.2022 um 13:20 schrieb GitHubRulesOK:
> Commonly you would use the 2 icons
> 
> ![image](https://user-images.githubusercontent.com/12754913/174787422-b454608b-6d3f-4055-9171-2b78a46c26ee.png)
> 
>

**Comment by kjk** [comment]
If I understand correctly, it's `Ctrl + 1` and `Ctrl + 0`

You can see all available shortcuts here: https://www.sumatrapdfreader.org/docs/Keyboard-shortcuts

All zoom levels are available via some shortcut and you can even assign your own shortcuts: https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts
