### ISSUE TITLE
Invert Colors (dark color) key or menu option

### ISSUE THREAD

**Issue by TheTaLlesT** [sumatrapdfreader/sumatrapdf#275]
I find I want the ability to invert the colors a lot and having to relaunch the app with the command line option is annoying.
A simple way I added this ability is to add the following to 'SumatraPDF.cpp' after line 3426.

<code>case 'i':</code>
<code>    gGlobalPrefs->fixedPageUI.invertColors ^= true;</code>
<code>    UpdateDocumentColors();</code>
<code>return;</code>

I don't know how to make suggestions without forking... or is that how your supposed to do it?

**Comment by kjk** [comment]
This is a good way to report this.

I'm not promising, however, that I'll make this change. I'm wary of adding too many keyboard shortcuts that can be hit accidentally and leave user perplexed as to what happened and how to go back. Maybe with some modifier (Shift-I or Ctrl-I).

**Comment by ousia** [comment]
Just in case it might help, Ctrl+I seems a more reasonable keyboard shortcut than simply I.

**Comment by TheTaLlesT** [comment]
I agree that just the 'I' key is probably not a good idea.
I changed the code to something a bit more acceptable I think.

In 'resorce.h' I added
<code>#define IDM_VIEW_INVERT_COLOR           700</code>
looked like a free id

In 'SumatraPDF.rc' under accelerators I added
<code>    "I",            IDM_VIEW_INVERT_COLOR,  VIRTKEY, CONTROL</code>

In 'Menu.cpp' under <code> { _TRN("Man&ga Mode"),                  IDM_VIEW_MANGA_MODE,        MF_CBX_ONLY },</code> I added
<code> { _TRN("Invert Color\tCtrl+I"),         IDM_VIEW_INVERT_COLOR,      0 },</code>


Also in 'Menu.cpp' in the 'MenuUpdateDisplayMode' function I added
<code>win::menu::SetChecked(win->menu, IDM_VIEW_INVERT_COLOR, gGlobalPrefs->fixedPageUI.invertColors);</code>

Under 'switch (wmId)' in 'SumatraPDF.cpp' I added
<code>        case IDM_VIEW_INVERT_COLOR:</code>
<code>              OnMenuInvertColors(win);</code>
<code>              break;</code>

And after the 'OnMenuViewMangaMode' function I added

<code>static void OnMenuInvertColors(WindowInfo *win)</code>
<code>{</code>
<code>    gGlobalPrefs->fixedPageUI.invertColors ^= true;</code>
<code>    UpdateDocumentColors();</code>
<code>    for (int tab = 0; tab < win->tabs.Count(); tab++)</code>
<code>        if (win->tabs[tab] != win->currentTab)</code>
<code>            win->tabs[tab]->reloadOnFocus = true; // need to fix flash effect...</code>
<code>}</code>

A problem I noticed with my old code was if you went to another tab that was loaded before inverting the colors, the pages in the view area of that tab did not get inverted, they would update if you scroll away and back.

The above code does not do that anymore but when you switch to a tab that was loaded before inverting the colors you see the original page for a split second and can create an flash effect. Any ideas on how I might fix that?

Also should this be a setting per document/tab or keep it global?

If I was to add much more this would start to become a really annoying way to share my changes. Is there a better way?

**Comment by kjk** [comment]
For bigger changes you can fork and make changes on a branch.

Regarding the changes, we have a very high bar for adding new menu items and 'invert colors' doesn't meet that bar.

**Comment by FSund** [comment]
Perhaps it could be added as an advanced option in addition to a hotkey? (pressing the hotkey would probably need to change the advanced settings file)

**Comment by fbobraga** [comment]
A button or shortcut key for inverting colors is a very welcome change for me (I love and frequently use the https://wiki.gnome.org/Apps/Evince Ctrl+I shortcut - but, for Windows (in my work), Evince is a bit bloated) :-)

**Comment by Jeff-Relf** [comment]
I'd like a RightClick Menu option to toggle To|WayFrom an unaltered bitmap,
so I can see human faces properly.  I do not want to alter 
the foreground/background colors of text.   Nor do I want anything "inverted".

**Comment by jkopczyn** [comment]
> we have a very high bar for adding new menu items and 'invert colors' doesn't meet that bar.

Any bar which allows 'favorites' but forbids 'invert colors' is a very silly bar. Night Mode is far more broadly useful than a favorites list.

**Comment by GitHubRulesOK** [comment]
@jkopczyn 
Historically -invert-colors is specified during startup, it was never considered as needing to be a toggle during a session. Whilst it is depreciated (as now replaced by user preferences) it is still active.

**Comment by GitHubRulesOK** [comment]
Consolidating as duplicated by discussions in Toggle background color #79

**Comment by ImportTaste** [comment]
> I find I want the ability to invert the colors a lot and having to relaunch the app with the command line option is annoying.
> A simple way I added this ability is to add the following to 'SumatraPDF.cpp' after line 3426.
> 
> `case 'i':`
> ` gGlobalPrefs->fixedPageUI.invertColors ^= true;`
> ` UpdateDocumentColors();`
> `return;`
> 
> I don't know how to make suggestions without forking... or is that how your supposed to do it?

6 years later and I'm still relying on these 4 lines of code. 😕
