### ISSUE TITLE
Menu text is invisible in high contrast mode

### ISSUE THREAD

**Issue by zoharl3** [sumatrapdfreader/sumatrapdf#2756]
The issue is since version 3.2.

Happens on win10 high contrast mode, where the default background is black. The menu and toolbar text is also black and thus invisible.

**Comment by GitHubRulesOK** [comment]
it happened variably before 3.2 hence even in XP may have needed adjustment. its a side effect of not having a consistent windows system to handle apps, so windows theme settings do not always see the contrast is already set black on white and place near black on black inversion. Perhaps if theming was possible it could work with windows contrast.

**Comment by zoharl3** [comment]
It's fine in version 3.1.2. So you could probably see what changed.

My suggestion: either use default system colors or the color settings in SumatraPDF-settings.txt:

FixedPageUI [
	TextColor = #ffffff
	BackgroundColor = #000000
	...
]

What bothers me the most is that I can't see the page number and the total number of pages.

**Comment by kjk** [comment]
I can reproduce the toolbar issue but not the menu issue.

I tried with "Aquatic" Contrast theme in latest Windows 11.

Can you post a screenshot of the menu and screenshot of the settings panel with the theme selection so that I know which theme setting you're talking about (you can use `<win key> + <shift> + S` to take a screenshot and `Ctrl + V` to paste it into an issue)

**Comment by zoharl3** [comment]
My bad:
- The menu is fine (once enabled; it's just not showing at all by default).
- It shows the page number.

But it doesn't show the total number of pages, which is the only thing that I'm missing.

![image](https://user-images.githubusercontent.com/4432831/175835834-e7a5544b-2240-47ae-8b30-2100ac65a654.png)

**Comment by GitHubRulesOK** [comment]
@zoharl3 for page 5 of ## press Shifted `I` but beware unshifted is now invert

**Comment by zoharl3** [comment]
I guess I could also press END (keypad) to jump to the end of the document. 

Thanks for the suggestion, I'll consider it, or may stay with the older version for a while. I'll close the ticket.
