### ISSUE TITLE
Wish: support "epub3"

### ISSUE THREAD

**Issue by Denisov21** [sumatrapdfreader/sumatrapdf#276]
You can see more informations here: http://idpf.org/epub/30

**Comment by kjk** [comment]
Did you actually try opening epub3 file with Sumatra?

Do you have sample epub3 files that do not open with Sumatra? If yes, please share them (see https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports)

**Comment by Denisov21** [comment]
Sorry I solved. I thought that this format is not supported .
