### ISSUE TITLE
SumatraPDF beta v3.5.15207 64-bit crash loading PDF 

### ISSUE THREAD

**Issue by steve4github** [sumatrapdfreader/sumatrapdf#2760]
[1011556_mirage-liberty_components-card_amer_eng.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/8994433/1011556_mirage-liberty_components-card_amer_eng.pdf)
SumatraPDF beta 64-bit crashes when loading PDF in Windows 10 (latest, all patches).  SumatraPDF has no previous PDF files and is not running.
Crashes when loaded from Chrome or from Windows Explorer.  Browsing with Chrome, downloaded link 
https://document.resmed.com/documents/products/mask/mirage-series/components-card/1011556_mirage-liberty_components-card_amer_eng.pdf
SumatraPDF beta is default PDF viewer.  PDF loads correctly in Acrobat DC.
Gist is here:
https://gist.github.com/steve4github/9d5ad67fde07cd92ecb83b9329ced4f0

**Comment by kjk** [comment]
This should already be fixed in latest pre-release 15210 or later, by https://github.com/sumatrapdfreader/sumatrapdf/commit/63bd630ec4c0c77fe109366a0802e056f36df8bd
