### ISSUE TITLE
advanced options is opened by winedt in ver. pre-3.5.15210 64bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2762]
Clicking 'settings - Advanced options' will open settings.txt file via winedt automatically in ver. pre-3.5.15210 64bit. But that settings.txt was opened via windows notepad automatically in previous version, e.g. ver. pre-3.5.15187. The default action on txt file is already set to opening via windows notepad on my computer. 

would it be possible to change that behavior back to opening via windows notepad?

**Comment by kjk** [comment]
I made this change because any editor is better than notepad. Is it about winedt specifically or would it apply to any non-notepad editor (VS Code, Sublime?)

**Comment by GitHubRulesOK** [comment]
I am perhaps unique in using many editors at different times but hourly notepad is the send to default, so if any other was redirecting It would be a problem to me.

I use portable thus it is not a problem to jump from one to another, however many Latex users have more than one installed/active and may rely on -inverse-search every call (though I totally discourage such use.)

**Comment by DDNH-Maps** [comment]
**SumatraPDF-3.5.15201-64-Prerelease crashed when [Settings] [Advanced Options...] is selected from the menu, 
software is running on a W7 PC, NO files are loaded, and is repeatable.**

Below is the "sumatrapdfcrash.txt" file.

\## Start of File ## 

Crash file: C:\Users\My PC\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.txt
Exe: C:\Program Files\SumatraPDF-PreRel\SumatraPDF.exe 7.69 MB (8,066,520 Bytes)
Dll: C:\Program Files\SumatraPDF-PreRel\libmupdf.dll 12.99 MB (13,622,784 Bytes)
BuiltOn: 2022-06-26
Type: dll
Ver: 3.5.15201 pre-release 64-bit
Git: 32f7d14ee9bfaefdf1cc65d34f8d25167bf0d4c3 (https://github.com/sumatrapdfreader/sumatrapdf/commit/32f7d14ee9bfaefdf1cc65d34f8d25167bf0d4c3)
OS: Windows 7 SP1 build 7601 64-bit
Number Of Processors: 2
Processor: Intel(R) Celeron(R) CPU        E3300  @ 2.50GHz
Physical Memory: 3.99 GB
Commit Charge Limit: 7.98 GB
Memory Used: 66%
Machine: To Be Filled By O.E.M. 1.0
Lang: en US
Graphics driver 0
  DriverDesc:         Intel(R) G33/G31 Express Chipset Family
  DriverVersion:      8.15.10.1930
  UserModeDriverName: igdumd64.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 000000013F65C2EC 01:00000000000EB2EC sumatrapdf.exe
Fault reading address 0000000000000000

Registers:
RAX:00000000FFFFFFFF  RBX:000000000027D070  RCX:0000000000000000
RDX:0000000000000025  RSI:0000000000000001  RDI:0000000000000000
R8: 0000000000000000
R9: 0000000000000000
R10:0000000000002525
R11:000000013F65C8DB
R12:00000000FFFFFFF0
R13:0000000000000000
R14:0000000000000001
R15:000000000027D070
CS:RIP:0033:000000013F65C2EC
SS:RSP:002B:00000000001AE808  RBP:001AE888
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010286

Crashed thread:
000000013F65C2EC 01:00000000000EB2EC sumatrapdf.exe
000000013F589061 01:0000000000018061 sumatrapdf.exe
000000013F589159 01:0000000000018159 sumatrapdf.exe
000000013F5CFBF4 01:000000000005EBF4 sumatrapdf.exe
000000013F5D07C1 01:000000000005F7C1 sumatrapdf.exe
00000000775C9861 01:0000000000018861 user32.dll!TranslateMessageEx+0x291
00000000775C9572 01:0000000000018572 user32.dll!TranslateMessage+0x1de
000000013F5D4A49 01:0000000000063A49 sumatrapdf.exe
000000013F5D642D 01:000000000006542D sumatrapdf.exe
000000013F65AF1A 01:00000000000E9F1A sumatrapdf.exe
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1d90
00000000777197EA 01:00000000000687EA ntdll.dll!ZwWaitForSingleObject+0xa
000007FEFD5510DC 01:00000000000000DC kernelbase.dll!WaitForSingleObjectEx+0x9c
000000013F5947F1 01:00000000000237F1 sumatrapdf.exe
000000007752B9B0 01:000000000009A9B0 kernel32.dll!UnhandledExceptionFilter+0x160
0000000077728F95 01:0000000000077F95 ntdll.dll!longjmp+0xc355
0000000077707258 01:0000000000056258 ntdll.dll!_C_specific_handler+0x8c
000000007771BE9D 01:000000000006AE9D ntdll.dll!_chkstk+0x9d
00000000776F040A 01:000000000003F40A ntdll.dll!RtlInitializeResource+0x53a
000000007771B53E 01:000000000006A53E ntdll.dll!KiUserExceptionDispatcher+0x2e
000000013F65C2EC 01:00000000000EB2EC sumatrapdf.exe
000000013F589061 01:0000000000018061 sumatrapdf.exe
000000013F589159 01:0000000000018159 sumatrapdf.exe
000000013F5CFBF4 01:000000000005EBF4 sumatrapdf.exe
000000013F5D07C1 01:000000000005F7C1 sumatrapdf.exe
00000000775C9861 01:0000000000018861 user32.dll!TranslateMessageEx+0x291
00000000775C9572 01:0000000000018572 user32.dll!TranslateMessage+0x1de
000000013F5D4A49 01:0000000000063A49 sumatrapdf.exe
000000013F5D642D 01:000000000006542D sumatrapdf.exe
000000013F65AF1A 01:00000000000E9F1A sumatrapdf.exe
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1600
00000000777197EA 01:00000000000687EA ntdll.dll!ZwWaitForSingleObject+0xa
000007FEFD5510DC 01:00000000000000DC kernelbase.dll!WaitForSingleObjectEx+0x9c
000000013F5B7CD8 01:0000000000046CD8 sumatrapdf.exe
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1570
0000000077719D5A 01:0000000000068D5A ntdll.dll!NtWaitForMultipleObjects+0xa
000007FEFD551420 01:0000000000000420 kernelbase.dll!GetCurrentProcess+0x40
00000000774B1273 01:0000000000020273 kernel32.dll!WaitForMultipleObjectsEx+0xb3
000000013F5F3550 01:0000000000082550 sumatrapdf.exe
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 162c
0000000077719D5A 01:0000000000068D5A ntdll.dll!NtWaitForMultipleObjects+0xa
00000000776C332D 01:000000000001232D ntdll.dll!RtlIsCriticalSectionLockedByThread+0xd4d
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: b34
000000007771B0AA 01:000000000006A0AA ntdll.dll!ZwWaitForWorkViaWorkerFactory+0xa
00000000777A97C4 01:00000000000F87C4 ntdll.dll!DbgUiRemoteBreakin+0x354
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1560
000000007771B0AA 01:000000000006A0AA ntdll.dll!ZwWaitForWorkViaWorkerFactory+0xa
00000000777A97C4 01:00000000000F87C4 ntdll.dll!DbgUiRemoteBreakin+0x354
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: ff8
000000007771B0AA 01:000000000006A0AA ntdll.dll!ZwWaitForWorkViaWorkerFactory+0xa
00000000777A97C4 01:00000000000F87C4 ntdll.dll!DbgUiRemoteBreakin+0x354
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1c08
000000007771B0AA 01:000000000006A0AA ntdll.dll!ZwWaitForWorkViaWorkerFactory+0xa
00000000777A97C4 01:00000000000F87C4 ntdll.dll!DbgUiRemoteBreakin+0x354
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1680
00000000777197EA 01:00000000000687EA ntdll.dll!ZwWaitForSingleObject+0xa
000007FEFD5510DC 01:00000000000000DC kernelbase.dll!WaitForSingleObjectEx+0x9c
000007FEFE16DEF8 01:000000000017CEF8 wininet.dll!InternetConfirmZoneCrossingA+0x15ab8
000007FEFE16C794 01:000000000017B794 wininet.dll!InternetConfirmZoneCrossingA+0x14354
000007FEFE16C394 01:000000000017B394 wininet.dll!InternetConfirmZoneCrossingA+0x13f54
000007FEFE1694A2 01:00000000001784A2 wininet.dll!InternetConfirmZoneCrossingA+0x11062
000007FEFE169702 01:0000000000178702 wininet.dll!InternetConfirmZoneCrossingA+0x112c2
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1d3c
000000007771B0AA 01:000000000006A0AA ntdll.dll!ZwWaitForWorkViaWorkerFactory+0xa
00000000777A97C4 01:00000000000F87C4 ntdll.dll!DbgUiRemoteBreakin+0x354
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 15bc
000000007771B0AA 01:000000000006A0AA ntdll.dll!ZwWaitForWorkViaWorkerFactory+0xa
00000000777A97C4 01:00000000000F87C4 ntdll.dll!DbgUiRemoteBreakin+0x354
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1b78
0000000077719AEA 01:0000000000068AEA ntdll.dll!ZwDelayExecution+0xa
000007FEFD551203 01:0000000000000203 kernelbase.dll!SleepEx+0xb3
000007FEFD74D828 01:000000000000C828 ole32.dll!ObjectStublessClient24+0x1958
000007FEFD7516EE 01:00000000000106EE ole32.dll!CoGetTreatAsClass+0xf16
000007FEFD74D7DA 01:000000000000C7DA ole32.dll!ObjectStublessClient24+0x190a
00000000774A556D 01:000000000001456D kernel32.dll!BaseThreadInitThunk+0xd
000000007770372D 01:000000000005272D ntdll.dll!RtlUserThreadStart+0x1d

Thread: 1e64
0000000077719D5A 01:0000000000068D5A ntdll.dll!NtWaitForMultipleObjects+0xa
000007FEFD551420 01:0000000000000420 kernelbase.dll!GetCurrentProcess+0x40
00000000774B1273 01:0000000000020273 kernel32.dll!WaitForMultipleObjectsEx+0xb3
000007FEFD2B20DE 01:00000000000010DE crypt32.dll

Module: 000000013F570000 7BB000 SumatraPDF.exe   C:\Program Files\SumatraPDF-PreRel\SumatraPDF.exe
Module: 00000000776B0000 19F000 ntdll.dll        C:\Windows\SYSTEM32\ntdll.dll
Module: 0000000077490000 11F000 kernel32.dll     C:\Windows\system32\kernel32.dll
Module: 000007FEFD550000 067000 KERNELBASE.dll   C:\Windows\system32\KERNELBASE.dll
Module: 000007FEFBB40000 1F5000 COMCTL32.dll     C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.24483_none_e372d88f30fbb845\COMCTL32.dll
Module: 000007FEFE4D0000 09F000 msvcrt.dll       C:\Windows\system32\msvcrt.dll
Module: 000007FEFE570000 067000 GDI32.dll        C:\Windows\system32\GDI32.dll
Module: 00000000775B0000 0FA000 USER32.dll       C:\Windows\system32\USER32.dll
Module: 000007FEFD730000 00E000 LPK.dll          C:\Windows\system32\LPK.dll
Module: 000007FEFD5C0000 0CB000 USP10.dll        C:\Windows\system32\USP10.dll
Module: 000007FEFE6F0000 071000 SHLWAPI.dll      C:\Windows\system32\SHLWAPI.dll
Module: 000007FEF9390000 071000 WINSPOOL.DRV     C:\Windows\system32\WINSPOOL.DRV
Module: 000007FEFD690000 097000 COMDLG32.dll     C:\Windows\system32\COMDLG32.dll
Module: 000007FEFE810000 D8B000 SHELL32.dll      C:\Windows\system32\SHELL32.dll
Module: 000007FEFD940000 0DB000 ADVAPI32.dll     C:\Windows\system32\ADVAPI32.dll
Module: 000007FEFF5F0000 01F000 sechost.dll      C:\Windows\SYSTEM32\sechost.dll
Module: 000007FEFF7F0000 12C000 RPCRT4.dll       C:\Windows\system32\RPCRT4.dll
Module: 000007FEFD740000 1FF000 ole32.dll        C:\Windows\system32\ole32.dll
Module: 000007FEFDA20000 0DB000 OLEAUT32.dll     C:\Windows\system32\OLEAUT32.dll
Module: 000007FEFE4A0000 02E000 IMM32.DLL        C:\Windows\system32\IMM32.DLL
Module: 000007FEFE5E0000 10B000 MSCTF.dll        C:\Windows\system32\MSCTF.dll
Module: 000007FEF1880000 003000 api-ms-win-core-synch-l1-2-0.DLL C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL
Module: 000007FEFB960000 056000 uxtheme.dll      C:\Windows\system32\uxtheme.dll
Module: 000007FEFB500000 018000 dwmapi.dll       C:\Windows\system32\dwmapi.dll
Module: 0000000077850000 003000 normaliz.dll     C:\Windows\system32\normaliz.dll
Module: 000007FEF80A0000 125000 dbghelp.dll      C:\Windows\system32\dbghelp.dll
Module: 000007FEFB740000 219000 gdiplus.dll      C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.24542_none_1459e0f08b91b367\gdiplus.dll
Module: 000007FEFA2A0000 007000 msimg32.dll      C:\Windows\system32\msimg32.dll
Module: 000007FEFDE50000 18A000 urlmon.dll       C:\Windows\system32\urlmon.dll
Module: 000007FEFD430000 004000 api-ms-win-downlevel-ole32-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-ole32-l1-1-0.dll
Module: 000007FEFD540000 004000 api-ms-win-downlevel-shlwapi-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-shlwapi-l1-1-0.dll
Module: 000007FEFD420000 005000 api-ms-win-downlevel-advapi32-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-advapi32-l1-1-0.dll
Module: 000007FEFD240000 004000 api-ms-win-downlevel-user32-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-user32-l1-1-0.dll
Module: 000007FEFD440000 004000 api-ms-win-downlevel-version-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-version-l1-1-0.dll
Module: 000007FEFC2E0000 00C000 version.DLL      C:\Windows\system32\version.DLL
Module: 000007FEFD530000 003000 api-ms-win-downlevel-normaliz-l1-1-0.dll C:\Windows\system32\api-ms-win-downlevel-normaliz-l1-1-0.dll
Module: 000007FEFDB80000 2CC000 iertutil.dll     C:\Windows\system32\iertutil.dll
Module: 000007FEFDFF0000 4AC000 WININET.dll      C:\Windows\system32\WININET.dll
Module: 000007FEFD250000 01F000 USERENV.dll      C:\Windows\system32\USERENV.dll
Module: 000007FEFD210000 00F000 profapi.dll      C:\Windows\system32\profapi.dll
Module: 000007FEFB350000 161000 windowscodecs.dll C:\Windows\system32\windowscodecs.dll

Modules loaded later:
Module: 000007FEFD060000 00F000 CRYPTBASE.dll    C:\Windows\system32\CRYPTBASE.dll
Module: 000007FEE0C00000 D55000 libmupdf.dll     C:\Program Files\SumatraPDF-PreRel\libmupdf.dll
Module: 000007FEFCE00000 00B000 Secur32.dll      C:\Windows\system32\Secur32.dll
Module: 000007FEFCFD0000 025000 SSPICLI.DLL      C:\Windows\system32\SSPICLI.DLL
Module: 000007FEF9CF0000 004000 api-ms-win-downlevel-advapi32-l2-1-0.dll C:\Windows\system32\api-ms-win-downlevel-advapi32-l2-1-0.dll
Module: 000007FEFF5A0000 04D000 WS2_32.dll       C:\Windows\system32\WS2_32.dll
Module: 000007FEFDFE0000 008000 NSI.dll          C:\Windows\system32\NSI.dll
Module: 000007FEFC940000 055000 mswsock.dll      C:\Windows\system32\mswsock.dll
Module: 000007FEFA740000 027000 IPHLPAPI.DLL     C:\Windows\system32\IPHLPAPI.DLL
Module: 000007FEFA670000 00B000 WINNSI.DLL       C:\Windows\system32\WINNSI.DLL
Module: 000007FEFC930000 007000 wship6.dll       C:\Windows\System32\wship6.dll
Module: 000007FEF77D0000 004000 api-ms-win-downlevel-shlwapi-l2-1-0.dll C:\Windows\system32\api-ms-win-downlevel-shlwapi-l2-1-0.dll
Module: 000007FEFC7C0000 05B000 DNSAPI.dll       C:\Windows\system32\DNSAPI.dll
Module: 000007FEFE770000 099000 CLBCatQ.DLL      C:\Windows\system32\CLBCatQ.DLL
Module: 000007FEFD2B0000 16D000 CRYPT32.dll      C:\Windows\system32\CRYPT32.dll
Module: 000007FEFD200000 00F000 MSASN1.dll       C:\Windows\system32\MSASN1.dll
Module: 000007FEFC3B0000 007000 wshtcpip.dll     C:\Windows\System32\wshtcpip.dll
Module: 000007FEFA4D0000 011000 dhcpcsvc6.DLL    C:\Windows\system32\dhcpcsvc6.DLL
Module: 000007FEF2360000 074000 netprofm.dll     C:\Windows\System32\netprofm.dll
Module: 000007FEFA9F0000 015000 nlaapi.dll       C:\Windows\System32\nlaapi.dll
Module: 0000000073B20000 026000 mdnsNSP.dll      C:\Program Files\Bonjour\mdnsNSP.dll
Module: 000007FEF9BE0000 008000 rasadhlp.dll     C:\Windows\system32\rasadhlp.dll
Module: 000007FEFA430000 018000 dhcpcsvc.DLL     C:\Windows\system32\dhcpcsvc.DLL
Module: 000007FEFA5B0000 053000 fwpuclnt.dll     C:\Windows\System32\fwpuclnt.dll
Module: 000007FEFC9A0000 018000 CRYPTSP.dll      C:\Windows\system32\CRYPTSP.dll
Module: 000007FEFC6A0000 047000 rsaenh.dll       C:\Windows\system32\rsaenh.dll
Module: 000007FEFD150000 014000 RpcRtRemote.dll  C:\Windows\system32\RpcRtRemote.dll
Module: 000007FEF1BC0000 00C000 npmproxy.dll     C:\Windows\System32\npmproxy.dll
Module: 000007FEFC5F0000 00A000 credssp.dll      C:\Windows\system32\credssp.dll
Module: 000007FEFC730000 058000 schannel.DLL     C:\Windows\system32\schannel.DLL
Module: 000007FEFCB70000 050000 ncrypt.dll       C:\Windows\system32\ncrypt.dll
Module: 000007FEFCB40000 022000 bcrypt.dll       C:\Windows\system32\bcrypt.dll
Module: 000007FEFCAB0000 04C000 bcryptprimitives.dll C:\Windows\system32\bcryptprimitives.dll
Module: 000007FEFD270000 03B000 WINTRUST.dll     C:\Windows\system32\WINTRUST.dll
Module: 000007FEFC4A0000 01B000 GPAPI.dll        C:\Windows\system32\GPAPI.dll
Module: 000007FEF79D0000 027000 cryptnet.dll     C:\Windows\system32\cryptnet.dll
Module: 000007FEFF920000 052000 WLDAP32.dll      C:\Windows\system32\WLDAP32.dll
Module: 000007FEF1EE0000 009000 SensApi.dll      C:\Windows\system32\SensApi.dll


-------- Log -----------------

ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => 'C:\Program Files\SumatraPDF-PreRel'
InstallCrashHandler crashDumpPath: 'C:\Users\My PC\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.dmp'
crashFilePath: 'C:\Users\My PC\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.txt'
symDir: 'C:\Users\My PC\AppData\Local\SumatraPDF\crashinfo'
Starting SumatraPDF 15201, GetCommandLineW():
"C:\Program Files\SumatraPDF-PreRel\SumatraPDF.exe" 
OpenEmbeddedFilesArchive: opened archive
LoadSettings() took 0.90 ms
ParseTranslationsTxt: 19274 lines, nStrings: 362
StartMonitoringDirForChangesAPC() C:\Users\My PC\AppData\Local\SumatraPDF
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\{771FD6B0-FA20-440A-A002-3B3BAC16DC50}_is1, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\App Paths\WinEdt.exe, (null)) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\App Paths\WinEdt.exe, (null)) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\WinEdt, Install Root) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\WinEdt, Install Root) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\App Paths\notepad++.exe, (null)) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\App Paths\notepad++.exe, (null)) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Notepad++, (null)) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Notepad++, (null)) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\Notepad++, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 3_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 3_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 3_is1, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 3_is1, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 2_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 2_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 2_is1, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text 2_is1, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text_is1, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\Sublime Text_is1, DisplayIcon) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\ToolsCenter\TeXnicCenterNT, AppPath) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\ToolsCenter\TeXnicCenterNT, AppPath) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\TeXnicCenter_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\TeXnicCenter_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\TeXnicCenter Alpha_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\TeXnicCenter Alpha_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\ToolsCenter\TeXnicCenter, AppPath) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\ToolsCenter\TeXnicCenter, AppPath) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\WinShell_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\WinShell_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Vim\Gvim, path) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Vim\Gvim, path) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\Texmaker, UninstallString) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\Texmaker, UninstallString) => '(null)'
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\{41DA4817-4D2A-4D83-AD02-6A2D95DC8DCB}_is1, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\{41DA4817-4D2A-4D83-AD02-6A2D95DC8DCB}_is1, InstallLocation) => '(null)'


----- Settings file ----------

﻿# For documentation, see https://www.sumatrapdfreader.org/settings/settings3-5.html
FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	HideScrollbars = false
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]

SelectionHandlers [
]
ExternalViewers [
]

ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
Annotations [
	HighlightColor = #ffff00
	UnderlineColor = #00ff00
	TextIconColor = #ffff00
	TextIconType = 
	DefaultAuthor = 
]

RememberOpenedFiles = false
RememberStatePerDocument = false
RestoreSession = true
UiLanguage = en
EnableTeXEnhancements = false
DefaultDisplayMode = continuous facing
DefaultZoom = 25
Shortcuts [
]
EscToExit = false
ReuseInstance = false
ReloadModifiedDocuments = true

MainWindowBackground = #80fff200
FullPathInTitle = false
ShowMenubar = true
ShowToolbar = true
ShowFavorites = false
ShowToc = true
NoHomeTab = false
TocDy = 0
SidebarDx = 327
ToolbarSize = 18
TabWidth = 300
TreeFontSize = 0
SmoothScroll = false
ShowStartPage = true
CheckForUpdates = true
WindowState = 1
WindowPos = 9 0 1456 900
UseTabs = true
UseSysColors = false
CustomScreenDPI = 0

FileStates [
]
SessionData [
]
TimeOfLastUpdateCheck = 0 0
OpenCountWeek = 599

\# Settings below are not recognized by the current version

\## end of "sumatrapdfcrash.txt" ##

**Comment by mperry2** [comment]
@kjk When will this change be reverted? It's been over a year since this issue was opened.
