### ISSUE TITLE
notification 'saved annotations to ...' doesn't fade out unless click its 'x' button in ver. pre-3.5.15210 64bit

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2763]
After saving annotation to existed pdf file via `ctrl` `shift` `s`, a notification 'saved annotations to ...' pops up, but it doesn't fade out automatically in ver. pre-3.5.15210 64bit unless click its 'x' button. It does fade out automatically in previous version, e.g. ver. pre-3.5.15187 64bit. maybe a new bug?

**Comment by GitHubRulesOK** [comment]
Closing as this certainly does fade in latest 3.5.15706 pre-release so regression appears to be "fixed" when save as was adjusted.
