### ISSUE TITLE
Couldn't open PDF with # as folder name

### ISSUE THREAD

**Issue by rocketaz** [sumatrapdfreader/sumatrapdf#2766]
This occurred on pre-release build version 3.5.15211 64-bit.
Folder name: #InvoicePDF 
Could not open all the PDF inside the folder. Sumatra stated 'Error loading'

P/S: Thank you for adding this into the latest build. (Next Tab / Prev Tab bind to Ctrl + PageUp / Ctrl + PageDown)

**Comment by GitHubRulesOK** [comment]
@kjk 
since the fragnent flag/seperater `#` should only appear when using with `.pdf#` then perhaps needs tighter detection, of course there are possibly users inking `name.ai#page=2` or other types of construct but those should be rarer than `folder for pdf#pages`
