### ISSUE TITLE
`q` and 'NoHomeTab=true' cause the last closed individual file stuck in the 1st place

### ISSUE THREAD

**Issue by LqkUWp** [sumatrapdfreader/sumatrapdf#2768]
reproducing procedure: 
1. open a single pdf file named xxx.pdf. what you'll see are Home and xxx.pdf tabs. 
2. change NoHomeTab to true via 'settings - advanced options'. 
3. close Home and xxx.pdf tabs orderly via key `q`. 
4. open any pdf file(s) and you'll see xxx.pdf tab at the 1st place in tab bar. 
5. close them all in any order via key `q`. say the last one you closed is yyy.pdf. 
6. open any pdf file(s) and you'll see yyy.pdf tab at the 1st place in tab bar. 

if i replace `q` with `ctrl` `w`, then the problem will be gone.

**Comment by GitHubRulesOK** [comment]
hmm I think this was a recent "improvement" traditionally remember one tab was not allowed since it should be home page alone  unless two or more tabs were saved but many users want reopen last page viewed and others want no home page, thus what you seem to have is remember last one tab session before Quit.

**Comment by kjk** [comment]
Could you clarify how you're opening the file (File / Open? drag & drop? double click).

Are you closing sumatra at any point in the repro steps?

**Comment by GitHubRulesOK** [comment]
@kjk 
I think you will find this is related to `RestoreSession = true` previously ignored one tab active on closure but now one tab is allowed to "stick" from prior session so opening a file adds it as second tab to the previous single tab remembered session.

**Comment by LqkUWp** [comment]
@kjk 
I open all files via double click them. 
I don't close sumatrapdf explicitly. But press `q` when only one file opened in sumatrapdf causes sumatrapdf closed.

**Comment by kjk** [comment]
Should be fixed in next pre-release.

When closing with `q`, would remember the session before closing the document, so on next launch it would think it has to restore session.

Fixed by saving session after closing the document / tab.
