### ISSUE TITLE
Number 10 in the list of recent files

### ISSUE THREAD

**Issue by username116** [sumatrapdfreader/sumatrapdf#2769]
In the list of recent files, the 10th has the number zero instead of ten.
It is indeed the 10th, just the 1 is missing. Or is it intentional?
I have tried other languages. I have tried several versions and all are affected.

![Capture d'écran 56](https://user-images.githubusercontent.com/108369600/176786553-3bc2ddb6-ea85-42ac-b12d-909c4e67ebfd.png)

**Comment by kjk** [comment]
It's intentional: you can use keyboard `1` to `0` to open those files when the menu is open.

You can use keyboard shortcut: `Alt - F`, `3` to open 3rd recently used file.

That wouldn't work with `10`, as that's 2 keystrokes.
