### ISSUE TITLE
Bit change in "View" Menu

### ISSUE THREAD

**Issue by jforozco** [sumatrapdfreader/sumatrapdf#277]
Hello

Feature Request:exclamation: In the __"Book View"__, the 1rst page force along, at this way the page 2 are opose to page 3, as paper impresion.

_Example_: see "http://issuu.com/columbia-magazine/docs/columbiasep15es" on pages 8 & 9 in ISSUU and then Sumatra PDF

/play deeper

**Comment by kjk** [comment]
I don't really understand the request. Either way, changing existing behavior would require a very good strong argument. People are used to how "Book View" works and we won't be changing it unless there is a really good reason for it.

**Comment by jforozco** [comment]
It does not require changing existing behavior, only the first page, that accommodates the following, why ?, only to better view facing pages, as in our example.

Seeing the __"Book View"__ on page 2 Sumatra is right and should be on the right, like all pairs. Odd are left and should be all right, really "like a book"

ISSUU understands this and so shows:

In __ISSUU__ the pag 8 - 9, PDF Book View:
![ISSUU](http://nicahosting.net/cap1.jpg)

In __SumatraPDF__ the same pages:
![SumatraPDF](http://nicahosting.net/cap2.jpg)

Do you understand me now? is not a problem, it is a detail of __Quality__.
