### ISSUE TITLE
SumatraPDF-3.4.6-64 hangs after installation on pdf with Bookmarks?

### ISSUE THREAD

**Issue by zeezhao** [sumatrapdfreader/sumatrapdf#2770]
Hi - Thanks for your work on this program. Much appreciated.

I upgraded from version 3.3.3-64 to the latest using  SumatraPDF-3.4.6-64-install.exe on a Windows 10 machine.

The installation went well. But when I run SumatraPDF it hangs trying to open previous tabs. it seems to be haning on one with a Bookmarks tab with table of contents.

I have had to revert to 3.3.3.

**Comment by kjk** [comment]
Nothing I can do without a file that reproduces the problem.

If you can isolate the file that causes the hang then please provide as described in https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

**Comment by zeezhao** [comment]
Hi. I just tried pre-release 3.5.15222 64-bit and that seems to work. Will observe and close if no more issues.
