### ISSUE TITLE
Using CommandLine : Last page isn't read/displayed

### ISSUE THREAD

**Issue by axel15rr** [sumatrapdfreader/sumatrapdf#2783]
Hello,
Maybe somebody can help me.

Following problem:
A PDF is read page by page in a **Lazarus project** using the integrated SumatraPDF.exe.

 with PDFProcess do
    begin
    CommandLine :=
            SumatraPfad+                      // file path of SumatraPDF.exe
            ' -plugin '+
            IntToStr(PanelPDF.Handle)+
            '-named-dest '+PDFFilename+' page 1'+
            ' -view "single page"'+
            ' -zoom '+IntToStr(SpinEditZoom.Value);
     Execute;
     end;
There are PDF files where the last page is not read/displayed in this way. Also
Turning ends on the penultimate page.

 with PDFProcess do
  begin
  CommandLine := SumatraPfad+
          ' -reuse-instance -plugin '+
          IntToStr(PanelPDF.Handle)+
          '-named-dest '+PDFFilename+
          ' -page '+intToStr(Seitennummer)+
          ' -view "single page"'+
          ' -zoom '+IntToStr(SpinEditZoom.Value);
   Execute;
   end; 

In the command line of SumatraPDF, only the penultimate page is displayed after importing but continuing there works.

What could be the reason for this different behavior?

I added the testprogram with the affected PDF fil
[PDF Last Page missing.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/9049436/PDF.Last.Page.missing.zip)
[LPMissing.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9049438/LPMissing.pdf)
[PDF_ok.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9049439/PDF_ok.pdf)

**Comment by GitHubRulesOK** [comment]
you are using an odd method of calling so for example

`sumatrapdf -page 3 -view "single page" -zoom 50 LPMissing.pdf`

will zoom to 50 on page 3 (there is NO -named-dest visible in the bookmarks list)
![image](https://user-images.githubusercontent.com/12754913/177411432-3ffddb0b-3ea5-4c47-8945-fd67f89f9896.png)

with newer versions I can do
`"c:\program files\sumatrapdf \sumatrapdf" -page 3 -view "single page" -zoom 500 -search "3b" LPMissing.pdf`

![image](https://user-images.githubusercontent.com/12754913/177412099-db95a9ed-db65-49c1-8125-86b9da8e09df.png)

**Comment by axel15rr** [comment]
Many thanks for the answer. But unfortunately that doesn't help me. Searching for a specific element on a PDF page isn't helpful, it doesn't help me because I want to read all the pages of the PDF file first before showing them.
**CommandLine :=
            SumatraPfad+                      _// 'C:\ProgramDownloads\Sumatra\SumatraPDF\SumatraPDF.exe'_
            ' -plugin '+
            IntToStr(PanelPDF.Handle)+
            '-named-dest '+PDFFilename+
	    ' page 1'+
            ' -view "single page"'+
            ' -zoom '+IntToStr(SpinEditZoom.Value);     _//  gives the PDF page a specific size_
     Execute;**
In most cases this works perfectly, in some cases unfortunately only up to the penultimate page. 
Why do the CommandLine instructions work correctly in one case and incorrectly in the other?

**Comment by GitHubRulesOK** [comment]
-named-dest '+PDFFilename+ does not make sense -named-dest is a named object **inside** a pdf file

**Comment by kjk** [comment]
It's unclear what you're trying to achieve. Looks like trying to control sumatra.

Maybe you can use DDE commands instead. See https://www.sumatrapdfreader.org/docs/DDE-Commands

In 3.5 pre-release you can send any command available in command palette like `CmdGoToNextPage`

**Comment by axel15rr** [comment]
I was not able to solve the problem with DDE commands. Does anyone have an idea how these should be included in the CommandLine in the example below?

**procedure TForm1.ButtonLadenClick(Sender: TObject);
begin
SeitenNummer:=1;     //pagenumber
PDFProcess:=TProcess.Create(nil);
if OpenDialog1.Execute
then
  begin
  PDFFileName:=UTF8Decode(OpenDialog1.filename);
  Anzahl:=SeitenAnzahl(PDFFileName);              // Number of pages of the PDF file will be 
  if Anzahl>0 then                                            // determined.
  with PDFProcess do
    begin
     CommandLine := SumatraPfad +
                     ' -plugin '+
                     IntToStr(PanelPDF.Handle)+
                     ' -named-dest '+PDFFilename+' page 1'+
                     ' -view "single page"'+
                     ' -zoom '+IntToStr(SpinEditZoom.Value);
     Execute;
     end
  end;
end;**

**Comment by GitHubRulesOK** [comment]
DDE is not easy via command line but exposes direct control, it is an internal dynamic call like a memory pipe thus used by machine code orientated languages like C +[+] # or similar. It may be possible via ddl support such as used by even AHK or a similar method as discussed in https://forum.lazarus.freepascal.org/index.php?topic=47029.0

However your issue seems to be `-named-dest '+PDFFilename` what is "PDFFilename" it is NOT a named destination unless you injected it into the PDF
