### ISSUE TITLE
Toolbar icons wrongly(?) rendered

### ISSUE THREAD

**Issue by edo9300** [sumatrapdfreader/sumatrapdf#2785]
I updated to the latest prerelease 15218 from a ~2 weeks old one and i immediately noticed that the toolbar icons now are rendered wrongly, i checked the commit history but i couldn't find anything related to them
![image](https://user-images.githubusercontent.com/18705342/177617773-efe6c5eb-d9c6-4d57-8db1-e14e0462afa4.png)
 this is before 
![image](https://user-images.githubusercontent.com/18705342/177617855-e7c1f006-03aa-4176-a1e5-e10900d304a3.png)
The pics might not show it very accurately as they don't really respect the proportions, but here the difference in the thikness of the lines is very noticeable.
Is this intended or something wrongly changed?

**Comment by GitHubRulesOK** [comment]
It will be down to some variation such as monitor dpi (CustomScreenDPI = 96) so using custom dpi you might need to rescale icons via say `ToolbarSize = 24`

**Comment by edo9300** [comment]
I haven't changed anything related to DPI tho, or is it a newly introduced behaviour? I had already tried changing the toolbar size setting, but changing the size of it isn't what I really want (the current size is fine). And also I checked and I have CustomScreenDPI at 0.

**Comment by edo9300** [comment]
![image](https://user-images.githubusercontent.com/18705342/177637150-b0905102-62d5-485f-b42e-502a9210c726.png)
Also in the home page, with the disabled icons, this change is even more noticeable
![image](https://user-images.githubusercontent.com/18705342/177637417-30d8a6d9-8418-495a-85ed-c7873cabd40e.png)

**Comment by GitHubRulesOK** [comment]
OK granted it seems to be recent ?
![image](https://user-images.githubusercontent.com/12754913/177662975-d750e9a8-cf82-44c3-85a4-84b85e947267.png)

**Comment by edo9300** [comment]
> kjk there were MuPDF updates related to SVG stroke width but surprised if there was effect on UI?

Indeed i tested earlier prerelease builds, the build for this commit https://github.com/sumatrapdfreader/sumatrapdf/commit/a069bdddb0e67ec5a8b86cfd6c264fc0478e7ea1 is still drawing them right, https://github.com/sumatrapdfreader/sumatrapdf/commit/4139c02d1a8f3365772855bd435a5bb92691e5c2 this made them render wrongly
