### ISSUE TITLE
Tab not rendered if sumatra is opened with the last closed file

### ISSUE THREAD

**Issue by edo9300** [sumatrapdfreader/sumatrapdf#2786]
On the latest prerelease (15218), when you have a single open file and close sumatra, when you reopen that file in a new instance, the tab for it will not be drawn until you hover over it with the mouse
![image](https://user-images.githubusercontent.com/18705342/177618594-3d0f7d82-75ba-43d4-b2d9-6489755a99bb.png)
After hovering
![image](https://user-images.githubusercontent.com/18705342/177618633-a5a413e6-031a-4e66-8b25-c0b14d38d7c6.png)
A possible conflicting setting could be the fact that i have the home tab disabled

**Comment by GitHubRulesOK** [comment]
@kjk I cannot replicate in recent version and currently don have a suitable 1521# to test but think this was likely refactored by other tab changes after that version?

**Comment by edo9300** [comment]
Hmm, can't seem to reproduce anymore

**Comment by kjk** [comment]
was fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/c6b4e9bfd143572993a0eff66978379a074d4c74
