### ISSUE TITLE
Post 3.1 refactors

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#279]
A few ideas:
- [x] clang-reformat all code
- [ ] str::Str => str::StrBase, typedef str::StrBase<char> str::Str, typedef str:StrBase<WCHAR> str::WStr
- [ ] assert() => AssertCrash()
- [ ] GetRValueSafe => ColGetR

**Comment by GitHubRulesOK** [comment]
ping @kjk
current status of these, I guess I have seen some done?

**Comment by kjk** [comment]
Yeah, mostly obsolete plans.
