### ISSUE TITLE
Sumatra 3.4.6 doesnt add support for the files it can read

### ISSUE THREAD

**Issue by Felipefpl** [sumatrapdfreader/sumatrapdf#2791]
When i try to open a pdf it says i have to go to control panel to add support for a certain file.

**Comment by GitHubRulesOK** [comment]
thats new windows since Microsoft introduced Edge as the default PDF file handler and at the same time blocked most other File Type Associations, by requiring a user select their preferences one by one.

**Comment by Felipefpl** [comment]
I'm not using edge, win7 here.

**Comment by GitHubRulesOK** [comment]
Hmm so used to win 11 sandbox usage (no defaults) I forgot to see how the #7 screen on the right is behaving for that aspect so have reset pdf default to Edge as I.E is now dead (but functioning) 
Installing SumatraPDf 3.4.6 does not as you say attempt to wrestle with Edge nor is there any old option to be rejected by currently supported Windows OS e.g 10+

You would need to perhaps install an older version to reset Associations but its simple to right click any pdf file and point at SumatraPDF.exe to relink as default when you open the first of each filetype. It took about 4 clicks to change all PDF icons from red to yellow or ePub to green or CBZ to blue or fb2 also to yellow

**Comment by kjk** [comment]
Yes, you have to make the associations manually e.g. in file explorer, right click, Open With.

I don't have win7 for testing and it's been discontinued by Microsoft in January 14, 2020
