### ISSUE TITLE
Question: Search selection with CTRL + F

### ISSUE THREAD

**Issue by Ursescu** [sumatrapdfreader/sumatrapdf#2795]
Hi,

Is it possible to bind CTRL + F to search for the text that's selected? I usually find myself selecting some text and pressing the search shortcut, I find it a bit tedious to copy text -> paste it in the search input.

**Comment by GitHubRulesOK** [comment]
The find box must be inactive (unpopulated from last search) so clear it first
Double click a word OR stripe more than one then CTRL+F OR simpler `/` will transfer it to find box then enter+(shift) to find next or (previous) 
Ideally use Del in the box to clear the find box for next/new selection

A much faster method is use Ctrl+[shift]+F3 as that selects & replaces box entry and finds next or previous
