### ISSUE TITLE
Remember opened tabs

### ISSUE THREAD

**Issue by pnsantos** [sumatrapdfreader/sumatrapdf#28]
Don't know if this has been requested before (tried searching for it but didn't find anything).

It would be very useful if when closing a window with multiple tabs, sumatrapdf recorded which files were opened and upon restarting the application, sumatrapdf re-opened the last instance opened tabs (much like firefox "Show my windows and tabs from last time").

**Comment by Peter-Sumatra** [comment]
For what it's worth I'd like <b>no</b> history to be retained by default, with session restore being a configurable option just like "Remember opened files".

**Comment by 9gix** [comment]
Thanks for the issues, I really need this feature. 
It is quite painful to open all of my document one by one after closing it.
(Chrome and Foxit Reader have such this features in their settings)

**Comment by Omaestre** [comment]
Any progress with this? 

I have not dug into the code of how Sumatra handles file paths and recent documents, put could that same procedure not be used for storing "recent documents" of each session upon exit? hen simply have a toolbar button to restore.

Then again that may cause issues for those who don't want their history to be remembered.

**Comment by ggutoski** [comment]
+1 for this feature.  Currently, each time I need to shut down sumatra (say for a system update) I manually compile a text file with a list of documents that need to be re-opened next time I launch sumatra.  It's painful.

**Comment by NicolBolas** [comment]
Well, SumatraPDF ought to be able to have a general "private" feature that allows the program to track nothing. No previously used file list, no tab restoration, nothing. It should be one option rather than having to hunt down every possible non-private option.

**Comment by lmstearn** [comment]
I don't know whether to raise a separate issue but as it comes under this feature let's put it here.
Working with a large tutorial where it's extremely convenient to operate multiple windows of the same document in a session. Now that MS insists on rebooting frequently, there's a time factor in opening the positions back again manually
There has to be more than one FilePath entry for the same FilePath. Sumatra opens different documents beautifully, but it's a little awkward making several filecopies of the same tutorial for it to work.as advertised.
Thanks for the fantastic program! :)

**Comment by kjk** [comment]
This has been implemented for a while.

**Comment by qywx** [comment]
And how to use the feature?

**Comment by NicolBolas** [comment]
@qywx: Presumably, they would have to make a new release of SumatraPDF. And it's been awhile since they've made a release.

Or you could download and compile it yourself.

**Comment by TPS** [comment]
@qywx, @NicolBolas: Or y'all could try prereleases from https://www.sumatrapdfreader.org/prerelease.html

**Comment by NicolBolas** [comment]
@TPS, @kjk, I downloaded the prerelease version and it still doesn't work. If I kill the process (to simulate restarting the PC), it fails to reload everything that was running at the time.

**Comment by kjk** [comment]
it only works for proper restarts, not killing the process. When windows is about to shutdown it sends a message to all programs before killing them and we use that message to save the state.

**Comment by NicolBolas** [comment]
@kjk The reason I tried killing the process is because previously (a few days ago) Windows *did* restart for me and the prerelease version still didn't restore the tabs. So I tested out a process kill as a way to figure out if I had done something wrong or not.

**Comment by jddcef** [comment]
@kjk - couldn't you just save the list of open tabs every time a new tab/document is opened or closed? Then it won't matter whether or not the process is killed nicely or if it dies suddenly.

**Comment by propagare** [comment]
Doesn't work for me as expected.
