### ISSUE TITLE
Debugging code appearing if started froma  shell

### ISSUE THREAD

**Issue by Harold-The-Wombat** [sumatrapdfreader/sumatrapdf#2805]
Good evening all,
    I have a portable development environment built upon Msys2. As a part of this, one piece of functionality I have is that Sumatra is loaded up from a shell script with an appropriate file after it scans a designated dir. With the current release of Sumatra, 3.4.6, I get a whole lot of start up debugging code when the script runs:

****************************
user@lappy ~ $ Starting SumatraPDF, GetCommandLineW():
C:\temp\barry\opt\bin\sumatrapdf.exe C:/temp/barry/doco/aaa.pdf
prefs::Load() took 0.63 ms
ParseTranslationsTxt: 19181 lines, nStrings: 357
LoadDocument: 20.32 ms, 189 pages for 'C:\temp\barry\doco\aaa.pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.01 ms
StartMonitoringDirForChangesAPC() C:\temp\barry\doco
StartMonitoringDirForChangesAPC() C:\temp\barry\opt\bin
~EngineMupdf: 0x0000026CE4AEC160
Calling PostQuitMessage() in CloseWindow() because closing lastWindow
****************************

If I drop back to 3.3.3, this release because I already had it on the machine, then nothing appears as I would expect. Has a debugging compilation switch been left on or do I need to pass something on the command line to turn this off?

    Any thoughts are greatly appreciated.

        Andrew

**Comment by Harold-The-Wombat** [comment]
Some additional info:
This system is based upon Msys2 and the console in question is ConEmu
The system has the path set so that the original Windows path is last

- If I start up the system and via Comenu run the script in question, the debugging info appears
- If I go into the dir that contains the *.exe and enter the name, _sumatrapdf_, of the current release manually and run it I get the debugging info. In fact doing this from anywhere, due to the pathing, gets the app starting along with the debugging.
- Doing the same as above but with V3.3.3, _sumatrapdf_3.3.3_, gets just the app, NO debugging info.
- Interestingly, if I in turn fire up a Windows cmd.exe shell and change into the apps dir and then run the app, either version, I get NO debugging info.
- Doing a double click from Explorer results in no debug stuff appearing anywhere for either release. 

As I'm typing this, I've just had the thought _I wonder if ConEmu pushes both strout and strerr both to the one screen?_

    Andrew

**Comment by GitHubRulesOK** [comment]
the option to render  verbose output was added more recently but should not be on console unless using wsl see https://github.com/sumatrapdfreader/sumatrapdf/issues/2710#issuecomment-1155754587

**Comment by Harold-The-Wombat** [comment]
I'm in the process of playing around with the development environment setup, in particular the way it fires up via Comenu - using the Msys2 provided cmd files or with task settings in Conemu. I have no idea what I've done but now, after I did the original post and fiddled some more with Conemu for other stuff, this problem has now disappeared.

The error was most likely my fault with some sort of weird config option in Conemu. I think this can be closed...

Andrew
