### ISSUE TITLE
PDF file with long annotations may cause program freeze

### ISSUE THREAD

**Issue by Leoongithub** [sumatrapdfreader/sumatrapdf#2814]
SumatraPDF version: `3.4.6-64 bit`

[Drawing1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9155567/Drawing1.pdf)
This file is generated by AutoCAD 2016 DWG To PDF printer. It will insert annotations when dwg file has text. If the annotation is too long, SumatraPDF will freeze. (I'm not sure about whether this problem relates to the length of annotations)

PS: I have tried previous versions of SumatraPDF. `3.2` will not freeze but `3.3` will.

**Comment by GitHubRulesOK** [comment]
wow only recently found how wasteful that cad workaround is and never seen this combination so its like a single OCR block whereas one would expect three columns as a slightly better method. It is what it is (not a good method) but needed by (shx vectors) custom old non ttf fonts. Amusing they say they wer written in 1969 style.
