### ISSUE TITLE
Suggestion: clear Frequently Read, aka Recently Open Files

### ISSUE THREAD

**Issue by cheesecracker** [sumatrapdfreader/sumatrapdf#282]
In case this has not been suggested (as I can't find any in this issue tracker):

Please implement a function to remove **all** frequently read files, alias recently open files, as a measure for privacy.  Please also remove them from Advanced Options file, because I can still find traces of these files in this "Advanced Options" file after I've removed Frequently Read files.

**Comment by kjk** [comment]
This already exists: Settings/Options/Remember opened files

**Comment by cheesecracker** [comment]
I see.  But in order to achieve "Clear Frequently Read", users have to go to Settings > Options, uncheck Remember opened files, and then go back to Settings > Options and **check** Remember opened files **again**.  Yes, this does give the expected result, but it's not convenient.

It's like on **every** calculator: we still have the x^2 key while it is essentially the same thing as doing the x * x operation, but this is NOT convenient.  You cannot ask users to press multiplication key instead of square key.

So, please implement the "Clear Frequently Read" function.

**Comment by qazo** [comment]
that wouldn't be a bad feature. if possible could this please be implemented?

**Comment by geminorum** [comment]
It's equivalent to “Clear History”, not “No History”.
