### ISSUE TITLE
No difference in enabling UseSysColors = true

### ISSUE THREAD

**Issue by Noexpert** [sumatrapdfreader/sumatrapdf#2823]
Using the portable v.3.4.6 64-bit and setting `UseSysColors = true` makes no difference.

**Comment by GitHubRulesOK** [comment]
using current windows will generally have little or no effect it was primarily an XP feature that worked fairly well until Metro messed with windows themes. I think but am not certain that it was related to *The color management scheme that's used starting with Windows 2000, Windows XP, and Windows Server 2003 is called Image Color Management (ICM) 2.0*

**Comment by GitHubRulesOK** [comment]
@kjk closing as still behaves as was historically designed. !

**Comment by Noexpert** [comment]
Thanks,

I (mistakenly) thought it would conform to Windows' system theme.

**Comment by thinkfan** [comment]
"UseSysColors = true" works when testing 3.4.6 on Windows 10, but doesn't take effect after 3.4.6. Hope change it back.
![2023-11-01_123631](https://github.com/sumatrapdfreader/sumatrapdf/assets/1967862/8b07d84c-720a-40bb-8a22-3babb54aeaeb)

**Comment by GitHubRulesOK** [comment]
@thinkfan  sys colours should be working in 3.5 / 3.6 for the titlebar (just not much use most of the time)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/5941e9eb-a280-4aeb-9b71-986b47104bb9)

**Comment by thinkfan** [comment]
@GitHubRulesOK Indeed titlebar color is almost no use. Is it possible to get the background color feature back in the future version?

**Comment by GitHubRulesOK** [comment]
@thinkfan 
I have shown it works exactly same as before there is nothing to fix except ask Microsoft to restore Windows 10 theming to Windows 7 compattible. So there are different colour settings for paper than sys colours so you can set paper to blue but that will affect all other colours between white and blue such as the red  green yellow cyan magenta and black.
