### ISSUE TITLE
C2039 compiler error

### ISSUE THREAD

**Issue by Avtroman** [sumatrapdfreader/sumatrapdf#2824]
![Снимок экрана (4)](https://user-images.githubusercontent.com/42459158/180694345-ac3418ca-bdfd-4367-9ddf-5fab9213df0f.png)
D:\0\sumatrapdf-master\src\CrashHandler.cpp(728,7): error C2039: "set_unexpected": не является членом "`global namespace'".
D:\0\sumatrapdf-master\src\CrashHandler.cpp(728,21): error C3861: set_unexpected: идентификатор не найден

**Comment by ClearSeve** [comment]
use c++ standard   ISO C++20
