### ISSUE TITLE
Cannot open embedded file

### ISSUE THREAD

**Issue by koppor** [sumatrapdfreader/sumatrapdf#2830]
In the PDF https://math.hamburg/s/xQWpANnd7gKT97r, there is a ".dtx" file embedded. The embedded file can be opened well in SumatraPDF 3.1.2. However, in SumatraPDF 3.4.6, it cannot be opened any more. Maybe, it is related to https://github.com/sumatrapdfreader/sumatrapdf/issues/1738? 

Note that Acrobat Reader and Adobe Acrobat XI [11.0.23.22](http://11.0.23.22/) can open it, too. - The PDF object model can somehow be read from https://github.com/zauguin/intopdf/blob/212e24d5073fc04f69c4f2c71b34013e16e692a7/intopdf.dtx#L121. - The PDF is from https://github.com/zauguin/intopdf/issues/3#issuecomment-1191846697.

**Comment by GitHubRulesOK** [comment]
Its not clear where here is in any reader so far tested
![image](https://user-images.githubusercontent.com/12754913/181361345-7fbd3360-e952-4df0-ad92-1b7ba6125ea9.png)

Took a while to spot whare the missing icon is

![image](https://user-images.githubusercontent.com/12754913/181361214-b1466dff-fbf1-4440-9480-ac3571770f35.png)

**Comment by koppor** [comment]
## Acrobat Reader

![grafik](https://user-images.githubusercontent.com/1366654/181361870-590b6f43-ce18-4a42-ab9e-2c1b5991a1cf.png)

Double click:

![grafik](https://user-images.githubusercontent.com/1366654/181361905-ad854fa4-5a25-4487-bdff-44d35bad10cb.png)


## SumatraPDF 3.1.2

![grafik](https://user-images.githubusercontent.com/1366654/181362316-4b9e677f-01f5-496f-8201-5821857d9fb6.png)

Single click:

![grafik](https://user-images.githubusercontent.com/1366654/181362416-75d136d6-3bc2-4749-9241-17093a1755e9.png)

**Comment by koppor** [comment]
Closing, because it is really a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1602.

| Version | Displays information on hover | Opens file |
| -- | -- | -- |
| 3.1.2 | yes | yes |
| 3.2 | no | no |
| 3.3 | yes | no |
| 3.3.1 | yes | no |
| 3.3.2 | yes | no |
| 3.3.3 | yes | no |
| 3.4.1 | no | no |

**Comment by GitHubRulesOK** [comment]
3.5 still is NYI  but hover is working :-) but like many others why should I hover ??

**Comment by koppor** [comment]
> 3.5 still is NYI but hover is working :-) but like many others why should I hover ??

For me, as a Desktop PC user and a curious person, I am using the mouse on a document ^^. -- For the concrete use case, a correct "hover" is an indication that file open / save could work.

**Comment by GitHubRulesOK** [comment]
Iagree my conjecture was that whilst the word here is clear to some it is not blue underline like we are used to in browsing apps and in my recent review image only Acrobat seem to show the comment marker but its non functional when download file until trusted. Agrred best visual is Tracker PDF editor shows it clearly when attachments window is open (same as SumatraPDF did does but still "not yet implemented" since major refactoring) agreed it "should" be simple to invoke save as but apparently not a small problem extracting that type?

**Comment by GitHubRulesOK** [comment]
just a comment that this again possible in 3.7 pre-release

<img width="789" height="461" alt="Image" src="https://github.com/user-attachments/assets/125d4d3f-f2e8-4487-b2dd-6a575a3f45cb" />
