### ISSUE TITLE
Title bar behaves weirdly in the latest nightly version

### ISSUE THREAD

**Issue by taooceros** [sumatrapdfreader/sumatrapdf#2833]
![image](https://user-images.githubusercontent.com/45326534/181385288-cb2c376b-a2f2-4054-bd10-349caeccf2bd.png)

**Comment by taooceros** [comment]
Seems like switching between monitor may get this partially fixed, and open enough documents that spans the title bar will partially address the issue.

**Comment by lenix3347** [comment]
Same problem #2806

**Comment by GitHubRulesOK** [comment]
@taooceros please re-check against 15235

**Comment by ikanakova** [comment]
@GitHubRulesOK  I have the same issue, in the version 3.5.15239 as well.

**Comment by kjk** [comment]
Is this still happening in the latest pre-release? There was a fix for tabs.

**Comment by taooceros** [comment]
I feel like it works, but I will give a more detailed check later.

**Comment by kjk** [comment]
I believe this is fixed now.
