### ISSUE TITLE
Cannot print CAD drawing PDFs on HP DesignJet 4000 since version 3.4+

### ISSUE THREAD

**Issue by mfvescovi** [sumatrapdfreader/sumatrapdf#2842]
_Preamble_: I've already tested pre-release build and the issue persists.

An annoying problem on printing CAD drawing PDFs (mainly on ISO A1 and ISO A0 formats) started occurring since the upgrade to v3.4+ (Windows 10 64 bit, testing both installer and portable).
Following, the dialog I got as output of SumatraPDF on starting printing:

![SumatraPDF_EniSYFiIBO](https://user-images.githubusercontent.com/1636078/182158245-c25df59f-d87b-4273-a164-0db3ad07a83c.png)

For the sake of testing, I've downgraded to v3.3.3 and the issue disappears on the same PDFs v3.4+ failed to print.
On any other application, the printer works as expected.

Thanks for your efforts in fixing this problem.

**Comment by kjk** [comment]
Can you provide a sample file that shows this problem? See https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

I've also added more logging for printing in pre-release which you can see with "Show Log" command in Command Palette (`Ctrl - K`). This should provide more information about what failed but realistically if I can't reproduce the issue myself, I'm unlikely to fix it.

**Comment by mfvescovi** [comment]
FYI, my HP DesignJet is EOL now and I've replaced it. So the issue isn't relevant anymore. Thus, closing.
