### ISSUE TITLE
Sumatra is not supporting epub with bangla font anymore

### ISSUE THREAD

**Issue by Rick0Sanch3z** [sumatrapdfreader/sumatrapdf#2849]
I checked the change log and it was saying **"better support for epub files using mupdf's epub engine"**. So, I updated and it's not even supporting epub with local language font anymore. Any possibly working method?
![SumatraPDF-3 4 6-64_94WJ2byouQ](https://user-images.githubusercontent.com/89753463/182849737-ebef6981-dd34-4766-a341-d0fab2fe0e8b.png)

**Comment by kjk** [comment]
Can't investigate with a sample file.
