### ISSUE TITLE
Link to local PDF-File with %20 doesn't work

### ISSUE THREAD

**Issue by RomanPils** [sumatrapdfreader/sumatrapdf#285]
It seems that a link to a PDF-File with url-escaped whitespace (%20) does not work in sumatra (Tested with Version 3.0 and Pree-Version 3.1)..

The same link works with Adobe PDF-Reader.

For example:
I have two files:
D:\file 1.pdf
D:\file 2.pdf

D:\file 1.pdf contains a link like "File%202.pdf
The link doesn't work in Sumatra.

Is this a known problem?

**Comment by kjk** [comment]
Well, this is not a valid link and I'm not sure we should try to work around this the way Adobe does.

File names are not urls, they don't need to (and shouldn't be) url-escaped. A file name link should use the exact name of the file.

**Comment by RomanPils** [comment]
Hello Krzysztof,

thank you for your answer. I agree with you.

My problem is word 2010:
I am writing a lot of documents with word 2010 and print them as PDF with the word built in function.
For crosslinks between the PDF-Documents I use word-Hyperlinks with relative filepaths.
Currently it seems that I cannot avoid that word change the spaces of the filepaths with %20 (url-escaping).
I will try some more word-settings for avoiding url-escaping.

I closed that issue.

Thanks again,

Roman

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/6bbd7a90510d7b3888eb5d33d4c00b4c2b452cdc

**Comment by RomanPils** [comment]
Hello Krzysztof,

this is good news!
Thank you for your fast reaction.

Best regards,
Roman
