### ISSUE TITLE
Proposal: use different files for global and local settings

### ISSUE THREAD

**Issue by matteocoder** [sumatrapdfreader/sumatrapdf#2850]
Thank you for your hard work, SumatraPDF is one of my favourite applications of all time.

I noticed that the application saves all its settings inside a single file in `$HOME\AppData\Local\SumatraPDF`.
It would be great if configuration options were stored in separate files,
for example `$HOME\AppData\Roaming\SumatraPDF\global-settings.txt` for global settings,
and `$HOME\AppData\Local\SumatraPDF\local-settings.txt` for local settings.
This would allow the user to cleanly sync their global settings
across machines without document-specific configuration, which might be relevant only on the local machine.

**Comment by GitHubRulesOK** [comment]
There were multiple locations more recently consolidated to the the one local folder for one local user or program + local for multiple users.

If you wish different roaming global profiles you can set using -appdata switch but really that is more useful for different file history settings, and not a good idea to use within shared drive or other managed folders. For portable usage it is sensible to keep all setting in the exe folder.

I have suggested in the past that the older smx or (v)bmk files  reduced the dependency on one settings file but it becomes increasingly difficult to maintain as a cohesive working set.

**Comment by matteocoder** [comment]
@GitHubRulesOK Thanks for the explanation. Personally I keep all my configuration files in a dotfiles repository versioned with git, and since the settings file also records the last window position and document-specific settings, it would constantly appear as a changed file. That is what led me to think that "static" global settings should be in `Roaming`, whereas "dynamic" settings such as the last window position should be considered a sort of cache and should stay in `Local`.
Thank you again for explaining me why the settings file works the way it does.

**Comment by GitHubRulesOK** [comment]
@matteocoder I am not developer so my observations are based on (ab)usage, the "settings" file is highly dynamic so entries flip true or false ow window size changes or historically user edits fonts/colours etc, thus very little could be kept separate. 

SumatraPDf as a lightweight one exe only had one "settings.ini" but over time that has had to adapt to larger variable content, but the ethos has primarily been to keep the settings together or comply with sufficient registry values when installed
