### ISSUE TITLE
when i change the free text`s color,  sumatrapdf crashed everytime!!!!!

### ISSUE THREAD

**Issue by WangYH195** [sumatrapdfreader/sumatrapdf#2856]
annotaion → free text →  text color, if I choose red, CRASHED!!! EVERYTIME!!!
now, I find that the border width is same!!!!!!!

**Comment by GitHubRulesOK** [comment]
There should be no problem with colour or border unless the annotations are added to a  faulty file

![image](https://user-images.githubusercontent.com/12754913/183259232-2cc41473-194e-4d0b-8fa7-f6fc8c550808.png)

**Comment by kjk** [comment]
Can't reproduce in latest pre-release.
