### ISSUE TITLE
Customize SumetraPDF

### ISSUE THREAD

**Issue by Canby** [sumatrapdfreader/sumatrapdf#286]
I work for an Engineer in a small practice who is looking for someone, for a fee, to  customize a version of SumetraPDF. 

Customization 1:
When I move around the map,  I get yellow boxs apparently used as part of the “find” command. Therefore I would want the Find command disabled and removed from the top ribbon.  Will this eliminate the yellow boxes?

Customization 2:

SumetraPDF is being run on a tablet, so the print and magnify icons are small. Make the icons larger 
If anyone is interested, please contact me to discuss a fee by Friday September 18th
Thanks

Ben Gulzow
Canby112414@aol.com

**Comment by kjk** [comment]
I assume it's past deadline.

**Comment by GitHubRulesOK** [comment]
Just for the record (in case any one else stumbles here) there was no real need for either of these requests

1) "yellow boxes" are a feature of mouse selection or search and will not appear unless a character is inserted in the find box, so short answer was don't put any thing in find or simply enter a single space character. Alternatively in advanced settings the "yellow" value can be set to transparent by changing SelectionColor = #ffffff 

2) Icons can be easily replaced/resized (by adding a bmp file in the settings directory).
