### ISSUE TITLE
Crashed while scrolling to the end of pdf of page 517

### ISSUE THREAD

**Issue by ujjwalgarg100204** [sumatrapdfreader/sumatrapdf#2861]
https://gist.github.com/ujjwalgarg100204/7356ab82c5e4053bde9a77b09a942e0f

**Comment by ujjwalgarg100204** [comment]
[A_First_Course_in_Complex_Analysis_with_Applications_(Dennis_G._Zill__Patrick_Shanahan)_(z-lib.org)_5.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9287000/A_First_Course_in_Complex_Analysis_with_Applications_.Dennis_G._Zill__Patrick_Shanahan._.z-lib.org._5.pdf)

I was this pdf

**Comment by GitHubRulesOK** [comment]
(z-lib.org) files usually indicates a poor quality rip off and often are substandard
MuDF finds a fail around page 84 in attempting to use the standalone MuPDF-GL

**Comment by kjk** [comment]
Can't reproduce the crash in latest pre-release and there were fixes for not crashing when mupdf failed so this is most likely fixed.

On the other hand, nothing past page 100 renders because the PDF is malformed.

**Comment by kjk** [comment]
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=706397

**Comment by kjk** [comment]
Should fully render now.
