### ISSUE TITLE
To describe the phenomenon, but I have not met him yet, and therefore decided to consult ...

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#287]
To describe the phenomenon, but I have not met him yet, and therefore decided to consult where to find it possible reasons:

http://forum.ru-board.com/topic.cgi?forum=5&topic=22740&start=1120#19

Author: ***maxud***, Submitted: 09/11/2015 21:27

***Victor_VG***

By the way, in all cases tried by me Sumatra 3x (on different machines and platforms) has a bug: I have often Sumatra open for a long time, after a certain running time (hours) becomes nothing can enter in the search box. It helps only restart Sumatra.

Author: Skif_off, Submitted: 09/11/2015 21:40

***maxud***

The Process Hacker (http://forum.ru-board.com/topic.cgi?forum=5&topic=29703&glp#lt), for example, did not see any chance, what happens? A nasty bug, it seems to me.

Author: ***maxud***, Submitted: 09/11/2015 21:54

***Skif_off***

>Nasty bug, it seems to me.

And unpredictable. And then when it happens exactly once examined. And Sumatra does not hang, a glitch is the inability to enter letters into the search box.

**Comment by kjk** [comment]
Extremely rare issue with no reliable steps to reproduce it. There's nothing we can do about it.

**Comment by VictorVG** [comment]
Author I have the same thing I said. Let's clarify it because now we can make dozens of hypotheses and make mistakes ...

**Comment by kjk** [comment]
A screencast showing the problem will help. "can't enter in search box" is too vague. Did you try ctrl-f? Did you try using a mouse? What exactly happens? Does it help if you close all the documents and open a new one?

**Comment by VictorVG** [comment]
I asked him exactly the same questions:

Nobody but you is not no conditions - OS, document type, CPU usage, the effect of anti-virus, load and the amount of RAM, the size of the document, what actions need to take to reproduce the problem? Do you want to help - give information needed to understand the picture.

Let's see what he has to answer for, and I do not imagine that he's going on there?
