### ISSUE TITLE
Bookmark option is greyed out

### ISSUE THREAD

**Issue by Lizardman101** [sumatrapdfreader/sumatrapdf#2874]
Pressing f12 or shift f12 doesn't do anything to activate bookmarks. It's a 166-page document, so I don't know if that would have anything to do with it. Any help would be greatly appreciated!

![image](https://user-images.githubusercontent.com/47120185/185030718-abab0c53-e0ea-4584-87c3-f2a4ff7a6f0f.png)

**Comment by Lizardman101** [comment]
Ooooh, I think I put it together. It can only view bookmarks not add them.

**Comment by GitHubRulesOK** [comment]
bookmarks are internal edits so pdf viewers cant add them, the likes of Edge browsers etc will use thumbnails to show all pages as miniatures.

SumatraPDF can add pointers for pages in any format in its settings called "favorites" which are similar but not stored in a pdf etc.
