### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by amboris** [sumatrapdfreader/sumatrapdf#2878]
https://gist.github.com/amboris/918ffd6366d7fddd10f4e2450297bd07
[CI_en.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9371977/CI_en.pdf)

**Comment by GitHubRulesOK** [comment]
looks like the highlights issue 

Highlight annotations have no Rect property

**Comment by GitHubRulesOK** [comment]
Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984
