### ISSUE TITLE
Cannot select text properly from pdf printed from chrome.

### ISSUE THREAD

**Issue by jiucenglou** [sumatrapdfreader/sumatrapdf#2891]
Can not select text properly from pdf printed from Chrome: the selection cursor does not show up when the mouse is on the text but appears when the mouse is under the text; selection appears as thin lines rather than blocks. The behavior can be similarly seen using Edge. Note that the pdf file is perfectly selectable using Chrome, Adobe or WPS. Many thanks !

[goodnotes_sample.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9411781/goodnotes_sample.pdf)

[sample video](https://user-images.githubusercontent.com/37147430/186302688-c2fac391-8118-4b1e-b8d9-2d66d4749784.mp4)

**Comment by GitHubRulesOK** [comment]
seen this a few times usually with poor OCR with a thin low baseline for the text blocks, but this looks different.
Unsure what would be a solution without editing the line as one common font height.

![image](https://user-images.githubusercontent.com/12754913/186325341-f76bf69e-86d1-470f-b25b-342713d7ec03.png)

**Comment by jiucenglou** [comment]
Many thanks ! Could you suggest what could be done ? Should one try to fix the pdf printed from Chrome (maybe by pdftk or ghostscript ?), or can one wait for handling by sumatra ?

**Comment by GitHubRulesOK** [comment]
Ideally
The source page should probably be reprinted by different means,  editing or reprint may not change the font behavior.
 I Edge Print/Save as PDF dozens of times a day similar without that issue so it is possibly post processing that caused it.

**Comment by jiucenglou** [comment]
> Ideally The source page should probably be reprinted by different means, editing or reprint may not change the font behavior. I Edge Print/Save as PDF dozens of times a day similar without that issue so it is possibly post processing that caused it.

The situation is exactly as you suspect. The text on the pdf printed from Chrome is perfectly selectable. However, the text on the pdf post-processed by ghostscript (for example, `gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=gs_output2.pdf gs_input.pdf`) cannot be properly selected. I could not figure out any clue about how to solve this... Could you by any chance suggest how to post-process using ghostscript so that the text can be selected properly ? Many thanks !

[gs_output2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9426387/gs_output2.pdf)

[gs_input.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9426385/gs_input.pdf)
!

**Comment by GitHubRulesOK** [comment]
I suspect there is a need to raise your issue with Artifex but their first question will be why is the file built using 9.55.0 combined with 2005 iText library and pdftk-java (3.0.9-1) unstable?
does it happen with current GS 9.56.1 and iText7 and that's without considering why the page size is not a default scale like Letter or A4

**Comment by jiucenglou** [comment]
> I suspect there is a need to raise your issue with Artifex but their first question will be why is the file built using 9.55.0 combined with 2005 iText library and pdftk-java (3.0.9-1) unstable? does it happen with current GS 9.56.1 and iText7 and that's without considering why the page size is not a default scale like Letter or A4

The text on the pdf becomes perfectly selectable and highlightable in Sumatra when current GS 9.56.1 is used ! Many thanks for your knowledgeable suggestions ! I am not sure about the page size: when I print from Chrome, the settings in the preview dialog does show the paper size is A4.
