### ISSUE TITLE
Print multiple pages per sheet

### ISSUE THREAD

**Issue by ikheeteric** [sumatrapdfreader/sumatrapdf#2894]
Over command line :)

**Comment by GitHubRulesOK** [comment]
Pages per sheet is a driver setting (Imposition) thus would generally need a driver that allows n-up and that easiest set as the printing driver default using a duplicated driver copy. 

Trying to specify scaling such as rotate at 1:0.71 is not easy between cli applications, unless it is a graphics app like IrfanView/Gimp/Magick all of which would be much better suited to the task.

For n-up before print I use https://github.com/GitHubRulesOK/MyNotes/tree/master/AppNotes/SumatraPDF/Addins/N-Up-PDF

**Comment by GitHubRulesOK** [comment]
@kjk n-up printing is not possible with many print drivers and I suspect adding such a command line ability would likely lead to multiple downstream problems so is it "out of scope" for SumatraPDF command line printing ?

**Comment by GitHubRulesOK** [comment]
closing as out of scope for SumatraPDF to alter forms layout as set by Windows print drivers, it is there or it is not.

There are many PDF command line editors to "N-UP" page layouts. and the function is more related to pdf media scale conversion not  basic viewing
