### ISSUE TITLE
Opening a PDF leads to a selection of already openend PDFs being opened again

### ISSUE THREAD

**Issue by ZPMU** [sumatrapdfreader/sumatrapdf#2901]
Since the last Windows-Update some days ago, SumatraPDF hast strange behaviour when opening new PDF file.
It **duplicates** some (not necessarly all) of **existing opened PDF windows.** This is accompanied by flashing the concerned windows rapidly before finally the volitional PDF appears. Presumably the flashing windows are the newly opened windows.

This leads to this behaviour: When some PDFs are already opened (say, five) and then I browse through some PDFs, open and close here and there some of them to peek, I soon got 20..30 or even more Sumatra-windows opened with some files opened two-, three- or more-fold. To keep the session manageable, **I have to clean up the set of open Sumatra windows frequently.**

Sadly I can't give a reliable way to demonstrate this behaviour. Usually not all open windows are concerned, occasionally even no window is concerned. But I'm quite sure that this behaviour wasn't introduced by V3.4.6 (Sumatra), but by last Windows-Update.
I already tried a reboot.

I'm using SumytraPDF usually in non-tabbed mode.
I'm using V3.4.6 64-bit and
Edition	Windows 10 Pro
Version	22H2
Installiert am	‎07.‎05.‎2021
Betriebssystembuild	19045.1889
Leistung	Windows Feature Experience Pack 120.2212.4180.0

**Comment by ZPMU** [comment]
I open a PDF by double clicking on it and then let the OS doing the rest.

**Comment by ZPMU** [comment]
The above issue stems from a long running installation.
But now, I recently installed current version (from <https://www.sumatrapdfreader.org/dl/rel/3.5.2/SumatraPDF-3.5.2-64-install.exe>) on an almost freshly installed Win-10. I installed as an ordinary user (without admin rights). The only thing I changed at Sumatra's options: I'd unchecked "open documents in tabs".

**Comment by GitHubRulesOK** [comment]
There were many changes over past 2 years some corrected this behaviour in pre-release then again others changed similar behaviour. 3.5.2 seems to be as it was at that time.

Only pre-release can be changed and currently should be "as expected" thus not "as in the past" !

There are 2 base "modus operandi" (with tabs and without tabs) so there will be some differences but basically should have similar abilities!

If restore session is active (true) then expect previous files (if found available) will be used and opened along with fresh files.

**Comment by kjk** [comment]
Most likely this is fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by ZPMU** [comment]
This version lets my explorer every four seconds stopping and then restarting. (I mean not the file manager, but the UI-manager of windows.) Other app. still running. But as this constantly proceeding killing steals input focus every time, rendering the computer unusable. If one manages in taskmanager to open "explorer"s context menu, choose "quit/exit/terminate task" (don't know, first entry, "Task beenden" in german UI), and nod through the security query fast enough, this sequence stops. But as soon as I restart "explorer" (lacking the UI, therefore by means of taskmanager's menu "file, execute new task", then typing "explorer", the four-second-loop starts again. Of course I killed all instances of sumatrapdf at first place.

**Comment by ZPMU** [comment]
This "feature" survived a reboot. I have to cut the loop by manually kill explorer by means of taskmanager, prior to do anything sensible with the computer. Albeit sensible is to be understood relatively -- as there is no UI except taskmanager's "file, execute" menu item.

**Comment by ZPMU** [comment]
appwiz.cpl is the command to start application-manager.
