### ISSUE TITLE
WinApi to toggle toolbar button

### ISSUE THREAD

**Issue by lollita** [sumatrapdfreader/sumatrapdf#2907]
I would send a message to toolbar button "fit width and show pagescontinuesly" to toggle it.
I use:

wnd = FindWindowEx(wnd, NULL, "ToolbarWindow32", NULL);
PostMessage(wnd, WM_LBUTTONDOWN, 1, MAKELONG(297, 20));
PostMessage(wnd, WM_LBUTTONUP, 0, MAKELONG(297, 20));

but it not work on all computer screen.
How to do?
How to find the button coordinates or send message direcly?

**Comment by GitHubRulesOK** [comment]
the easier hotkey to toggle continuous shuld be lowercase C (if not changed by user, should work in all ? languages)

**Comment by lollita** [comment]
This is a good advice. Ty.
