### ISSUE TITLE
SumatraPDF vs UDC vs Windows 10 crash on printer properties

### ISSUE THREAD

**Issue by v-python** [sumatrapdfreader/sumatrapdf#291]
I had UDC 5.1 installed on Windows 7, upgraded to Windows 10, then to UDC 6 trial. I discovered that UDC 6 trial wouldn't capture PDF files very well, so backed off the UDC 5.5. I discovered that printing non-ASCII characters from SumatraPDF to UDC 5.5 produced boxes instead of characters (they displayed fine in SumatraPDF, so the working theory is UDC 5.5 bug). So I backed back off to UDC 5.1, and attempting to access the Printer Properties for UDC 5.1 causes a crash.

Printing without changing the properties produces boxes instead of characters from Sumatra.

I installed Adobe Reader (it had been years since I even had it installed, after findnig Sumatra), and it allowed access to the printer properties, and printed the correct characters through UDF 5.1.

Working theory changes to bug in SumatraPDF. Possibly exacerbated by Windows 10, as I had been using SumtraPDF and UDC 5.1 together successfully before all the upgrades.  UDC 5.1 doesn't really claim Windows 10 support, but UDC 5.5 does, but doesn't work with SumatraPDF to produce non-ASCII characters.

Font in use: Times New Roman, embedded by Python/Reportlab.  Character: (Spanish) (upside-down question mark) ¿  (and others).

**Comment by kjk** [comment]
Please try with latest pre-release http://www.sumatrapdfreader.org/prerelease.html

**Comment by v-python** [comment]
Both problems cured in the prerelease 10360. Thanks.

**Comment by kjk** [comment]
What is UDC?

Please provide a test file that shows the problem and a detailed description (step-by-step) of how to reproduce it.

**Comment by v-python** [comment]
UDC is Universal Printer Driver from print-driver.com.  Handy tool... sort of like a print-to-PDF driver (and includes one of those, although that feature is rather buggy yet, like most of them), but also allows print-to-TIF, print-to-JPG, etc., print-to-graphics-image-file in general.

**Comment by kjk** [comment]
I still need a test file and detailed steps to reproduce the issue. 

I don't understand what you're trying to do, print a PDF to another PDF?

Is the PDF in question display correctly on screen but prints differently?

**Comment by v-python** [comment]
Do you? Comment 2, both problems were cured by the 10360 prerelease.

I was trying to print a PDF file to a TIFF file, by printing from SumatraPDF to UDC (which acts like a printer driver).

Yes, it displayed correctly on screen, but printed only the ASCII characters.  But with prerelease 10360 (or maybe just because of reinstalling after having upgraded to Windows 10, which might have internally not quite converted something correctly during the upgrade), everything is working again.

**Comment by kjk** [comment]
Sorry, I misunderstood your previous comment. I thought it still happens in pre-release. It looks like it's fixed then.
