### ISSUE TITLE
How to get statistics on files e.g. how many times file opened, number of pages read, last page read, etc.

### ISSUE THREAD

**Issue by zeezhao** [sumatrapdfreader/sumatrapdf#2912]
Hi. This is more of a feature request, unless it already exists. 
Please how can one get statistics on the various files e.g. how many times file opened, number of pages read, last page read, etc.
Since there are already Favourites/Bookmarks, I thought may be such information is kept. Please confirm. Thanks.

**Comment by tactilis** [comment]
> how can one get statistics on the various files e.g. how many times file opened, number of pages read, last page read, **etc**.

Out of interest, what are you wanting to do with this information? Why would it be helpful to you?

What other information are you seeking that is hinted at by your 'etc'?

**Comment by zeezhao** [comment]
Thanks for your reply. It is more to see which documents are opened and read the most, especially in an "-all-users" installation or just for personal usage by a researcher. 

I just added "etc" in case there may be other useful info.

**Comment by GitHubRulesOK** [comment]
the historic data does not store much more than last page or rough ranking
currently my one favorite shows `OpenCount = 0` because it has not yet been used
If I switch remember files on and use it then next time  settings.txt shows `OpenCount = 1`

**Comment by kjk** [comment]
The data is stored in sumatrapdf-settings.txt file but it's not guaranteed to work the same in the future.

In general, this is not possible and no plans to work on that.
