### ISSUE TITLE
colorful links

### ISSUE THREAD

**Issue by ikp123** [sumatrapdfreader/sumatrapdf#2921]
Sumatra is great, but it doesn't highlight links (within the document) like other pdf readers do. 
xodo:
![image](https://user-images.githubusercontent.com/54283421/188171497-ca219909-412b-43b2-89c6-b584e3bffd8e.png)
Sumatra:
![image](https://user-images.githubusercontent.com/54283421/188171669-c22cef40-1dc8-4704-859f-a11747e2874c.png)

Is it possible to give this as an option?

**Comment by GitHubRulesOK** [comment]
External links are highlighted in blue when switched on for that session

![image](https://user-images.githubusercontent.com/12754913/188178837-b7bba2c8-950f-4f41-bbcb-590e0e3cf9bf.png)

**Comment by ikp123** [comment]
How do you switch it on? Also, this is not an external link, it's an internal link (it leads to a point in the file).

**Comment by GitHubRulesOK** [comment]
internal links should look the same I set this one to page 2 but there is no tooltip to confirm where internals go to
![image](https://user-images.githubusercontent.com/12754913/188180239-0bbc088e-63b3-4d5e-ba14-af2267d8f578.png)
![image](https://user-images.githubusercontent.com/12754913/188180436-87da08f4-eccc-4ca7-9fce-9a12f8837c0c.png)

**Comment by ikp123** [comment]
OK, but I don't have this "Debug" in the main menu
![image](https://user-images.githubusercontent.com/54283421/188180867-53bcf84a-2d96-4950-97c2-7cb51cac1f3f.png)

**Comment by GitHubRulesOK** [comment]
AFAIK 3.2 had it shown in the official release (oversight ?) but not in 3.3/3.4 ?

**Comment by ikp123** [comment]
Yes, I think that's right. I have version 3.4.6, and I do remember that Sumatra used to have this feature by default.

**Comment by GitHubRulesOK** [comment]
its classed "experimental" not matured :-) so in the debug features but 3.2 included some

**Comment by ikp123** [comment]
And hence my request :)
Sumatra is great (it is the only pdf reader on Windows that I know of that updates the presentation when the file changes automatically; Adobe reader doesn't even allow to change the file if it's open), but this feature is really missing from the latest versions.

**Comment by GitHubRulesOK** [comment]
@kjk 
several PDF viewers allow 2 colour link outlines, one usually for internal gotos and one usually for externals URL
could HighlightLinks be a settings.txt option on /of 
or at least one colour used such as current ? #00ffff (default) or better yet be changeable for both types?

**Comment by kjk** [comment]
Yeah, we already have code to show links in debug mode. I'll expose it via command / setting.

**Comment by kjk** [comment]
added `ShowLinks` advanced setting and `Toggle Show Links` for command palette (`Ctrl + K`)

Will be in next [pre-release](https://www.sumatrapdfreader.org/prerelease) within next 24 hrs

**Comment by kjk** [comment]
There's no way to change the color (other than compiling the application from sources)
