### ISSUE TITLE
I use two modes and the software displays different pages

### ISSUE THREAD

**Issue by shiwangyan** [sumatrapdfreader/sumatrapdf#2922]
just like the pictures
![1](https://user-images.githubusercontent.com/60057517/188230518-a914b71b-0000-47ec-94f1-c3a94c834f8a.png)
![2](https://user-images.githubusercontent.com/60057517/188230534-f3f83760-f91d-404b-bc25-171a57809028.png)

**Comment by kjk** [comment]
Not enough information
