### ISSUE TITLE
Printing large epub results in crash

### ISSUE THREAD

**Issue by Tarek-Hasan** [sumatrapdfreader/sumatrapdf#2930]
Trying to print a large epub file hangs windows and ultimately results in crash. Tried with both pdf24 virtual printer and physical printer with same outcome. Okular can ready that file to print in few seconds. Maybe cause is enormous cache size 9gb and still counting, on okular that was around 450mb only.
Partially similar issue #2191
![IMG_20220904_195918](https://user-images.githubusercontent.com/27731012/188317854-975160e2-72c2-4876-ab86-302f4c7b3c5e.jpg)

**Comment by GitHubRulesOK** [comment]
OMG 843 decompressed pages as images only I am surprised windows did not blue screen, Printing in SumatraPDF is not designed to do any thing other than hand over to windows system printing as images, which is fine in small batches. perhaps split task down. I cannot send more than 20 pages per call to my printer as the hopper is not designed for 100s

**Comment by Tarek-Hasan** [comment]
I only tried physical printer cause I was curious if the problem is in pdf24, but same issue. Later I tried it with Okular and it only took 15 to 20 seconds.

**Comment by GitHubRulesOK** [comment]
Acrobat reader is good for PDF printing then next 2 best are Foxit/Chrome & Ghostscript, however for epub as Edge no longer works I would say your choice of Okular is good

**Comment by kjk** [comment]
Can't investigate without crash report file, a test file and steps to reproduce the crash.
