### ISSUE TITLE
some watermarks are displayed without transparency

### ISSUE THREAD

**Issue by mo-bai** [sumatrapdfreader/sumatrapdf#2934]
[1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9486479/1.pdf)
the watermark should be semi-translucent ,but the second page of the watermark display section transparent

**Comment by GitHubRulesOK** [comment]
that is not a normal print document method and adobe seems to also have issues, so problems are file specific per viewer so seems to be a mupdf problem
![image](https://user-images.githubusercontent.com/12754913/188457971-c16aa867-d9f6-4e88-ae18-d3e5cb3a0166.png)
Personally would classify as bad file
![image](https://user-images.githubusercontent.com/12754913/188458203-3bdee2cf-49a7-42be-a6c6-98d6d3bd932d.png)

**Comment by GitHubRulesOK** [comment]
Closing as appears to be fixed by more recent MuPDF updates

![image](https://user-images.githubusercontent.com/12754913/233781470-d6304927-30ad-4da7-925b-af430966d7f5.png)
