### ISSUE TITLE
Double Click Not Opening TeX Editor

### ISSUE THREAD

**Issue by zibdibbie** [sumatrapdfreader/sumatrapdf#2936]
Double clicking on a pdf in Sumatra no longer opens the Tex editor.

Sumatra is my default pdf viewer and the Tex editor hasn't changed either.  In each case, the Tex file is in the same folder as the pdf.  Below is the command for the set inverse search command line:
"D:\Program Files\WinEdt Team\WinEdt 10\WinEdt.exe" -C="WinEdt 10.3" "[Open(|%f|);SelPar(%l,8);]"

The issue is present in version 3.4.6 and the pre-release build.  I can't attach Tex files but below is a MWE in Tex and the pdf itself.

\documentclass{article}
\begin{document}
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
\end{document} 

[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9491195/test.pdf)

P.S. first time reporting an issue.  Sorry if I forgot to include anything important.

**Comment by GitHubRulesOK** [comment]
known issue with 3.4.6 installed (portable exe should work) also try current pre-release but the problem may still be using installed with compressed synctex ?

**Comment by zibdibbie** [comment]
Could not open Tex files using the portable exe either.

How would I change -synctex to 0 compression?

**Comment by GitHubRulesOK** [comment]
syctex command i cant remember but `synctex=-1` mentioned in previous discussion https://github.com/sumatrapdfreader/sumatrapdf/discussions/2640

I am surprised 32bit is not working since that was the common "works for me", thus wonder if something else has changed in your configuration

**Comment by zibdibbie** [comment]
Sorry for the confusion, looks like this was my own mistake and I'll mark this as solved.
If anyone else ever encounters this issue, synctex files can be disabled in WinEdt via the status bar on the bottom.  Re-enabling this fixed my problem. Screenshot below.
![src](https://user-images.githubusercontent.com/112892175/189500894-6616563e-c077-42b1-b7a2-0630e0994188.png)
