### ISSUE TITLE
Sumatra Hang over 5 minutes each time until delete SumatraPDF-settings files than clear start

### ISSUE THREAD

**Issue by spamkutu** [sumatrapdfreader/sumatrapdf#2939]
[SumatraPDF-settings.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/9496446/SumatraPDF-settings.txt)

i have to delete or clear each time settings files very abuse, if Sumatra can't find cached files or if that files on mapped drive etc
Sumatra hang hang hand each time until to stop it delete all settings files and clear start but thats very weird. Please add some fonction to not wait so much i guess its always try find files i not try on another computer but please try to open sumatra with this settings files hope you catch hanging regards,

[SumatraPDF-settings.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/9496492/SumatraPDF-settings.txt)

**Comment by GitHubRulesOK** [comment]
network access can be slow so calling
\\192.168.0.41 will be bound by network issues and additionally the remote archive needs constant decompressive zipped access (.cb7 & .epub)
likewise temp folders may be temporarily missing (Temp\7zO85A8075E) so need to see if available (IsMissing = false)

for network files I would first try keeping a mapped drive so my very slow netbook other side of room is s:\ ( S:\Desktop\AVIS-DE-SOUTENANCE-ACHACHI-HIND.pdf) but no problem using big files over there as the download to this fast machine is the only delay

**Comment by spamkutu** [comment]
Could you possible to add no wait action because i have to wait always 3-4 minutes with that start 
Maybe you could add this loading side on background process so no hang will occur and i could look newest opened pdf, will be so nice?
If you need any other detailed log included hanging and long start video ( mouse busy state not permit any action )

  
>Tuesday, September 6, 2022 4:26 PM +03:00 from GitHubRulesOK ***@***.***>:
> 
> 
>network access can be slow so calling
>\192.168.0.41 will be bound by network issues and additionally the remote archive needs constant decompressive zipped access (.cb7 & .epub)
>likewise temp folders may be temporarily missing (Temp\7zO85A8075E) so need to see if available (IsMissing = false)
>for network files I would first try keeping a mapped drive so my very slow netbook other side of room is s:\ ( S:\Desktop\AVIS-DE-SOUTENANCE-ACHACHI-HIND.pdf) but no problem using big files over there as the download to this fast machine is the only delay
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <sumatrapdfreader/sumatrapdf/issues/2939/1238149871 @ github . com> 
 
 
--
spam kutu
Sent from  Mail.ru

**Comment by spamkutu** [comment]
Everything is fine, normally there is no delay, but at startup such a file blocks all access.
Slowness and lags are not normally present, but assuming they are, it's not a problem.  At least when you click on the pdf and open it or at the first startup, these slow problematic and mapped files can continue to process in the background without blocking all the other parts, otherwise the whole program locks itself for one problematic file until the loading is finished very weird about 5min or shit the close open again and that's spam again until clear the option that hard and most of us no know that too. 

I guess this can be easily fixed by prioritizing opening files or loading them in the background, maybe it won't cause any problems for most users today, but in the future, when many users are constantly faced with this situation, when closing and opening doesn't help, they will become disenchanted with using this beautiful and rare program by constantly uninstalling and installing the program.

The simplest solution is to at least make the program ignore previous pdfs when opening a pdf directly and open only the one clicked on. Of course, it would be better to load all open pdfs in the background without interrupting the process without any freezing at the end of the process.

**Comment by kuro68k** [comment]
I have the same issue and would like to expand on it a bit.

It's not just opening files. Closing tabs also hangs for a few minutes too. In fact all sorts of operations do.

I use mapped drives. To be fair Windows isn't much better, it often takes 30 seconds to open a file requester.

Hopefully the fix will address all these issues.

**Comment by kjk** [comment]
Unfortunately there is no simple fix for slow drives. Sumatra hangs because it tries to read a file and the OS is taking long time to do it.

**Comment by GitHubRulesOK** [comment]
@kjk
one place where I think logging **"seemed"** to show large delays  (no current copy of those logs and current seems fast)

WAS when is opening epub where if I recall, MuPDF was repeatedly attempting a system font substitution?

**Comment by kjk** [comment]
Not enough information.

Main question: is it slow when restoring session (i.e. loading documents from network drive at startup) or even when not opening any files?

If when opening files at startup then most likely can't do anything do about it, especially if files are large. Network drives can have high latency and be slow to read.

If it blocks even when not opening files then that's bad but I can't repro this and to narrow this down I would need a CPU profile of the slow startup.

Please try latest pre-release.

Try `LazyLoading = true` advanced setting and see if it helps. It delays opening the file on startup until a tab is shown.
