### ISSUE TITLE
AESV3 encrypted pdf be viewed with blank page

### ISSUE THREAD

**Issue by wankang73** [sumatrapdfreader/sumatrapdf#294]
the pdf file can be viewed with text and image, but in SumatraPdf, it is a blank page with password 123

it can be viewed with another password 456

it is encrypted with AESV3 algorithm.

ge.tt/7FBciJO2/v/0

**Comment by kjk** [comment]
Confirmed that it's properly shown with password "456: and shows blank page with password "123".

`doc->crypt->r` is 5 and we go via `pdf_saslprep_from_utf8()`, which has a TODO about SALSprep.

**Comment by kjk** [comment]
It works in preview on Mac.

It looks like decryption `aes_crypt_cbc` in `pdf_crypt_obj_imp` returns garbage data (and we go through `fz_warn("aes padding out of range")`

**Comment by VictorVG** [comment]
Also confirmed. Interesting movie, interestingly, we see that there is - to each password added 0x03 byte, and that the idea should not happen. With password-456 the same file I opened in SumatraPDF v3.1 Git-15f19c9bd7 x64 under Win7 SP1 x64, then within us is distorted password. Or I'm wrong?

**Comment by VictorVG** [comment]
I build and test new revision Git-c83867bd98 - bug is fixed:

![sppdf](https://cloud.githubusercontent.com/assets/906886/10017489/5df8f4a8-6137-11e5-8200-c82c097f9717.png)

password 123 , Ok! Thanks ***zeniko***

**Comment by VictorVG** [comment]
oh, slip of the tongue - is subtracted rather than added.
