### ISSUE TITLE
Print in reverse order

### ISSUE THREAD

**Issue by vercinstex** [sumatrapdfreader/sumatrapdf#295]
Hello
I think it will be useful when you try to print leaflet to print odd or even pages but sometimes it is needed also to control the direction of the print. I mean the ability to print from 1 to XXX pages or from XXX pages to the first. This function is available in some other pdf reader.

Bye

**Comment by VictorVG** [comment]
Just use the print driver settings for your printer - in which it emerged in the 60 years of the last century, beginning with the IBM OS / 360. The application simply knocks incorporated in a kernel handler print job, and everything else including the adjustment to the size of the media (paper), the change in orientation and printing order of pages already doing it.

**Comment by kjk** [comment]
@vercinstex You can already do that. In printer dialog enter a reverse page range e.g. if document has 34 pages, a regular range is "1-34", a reverse range would be "34-1"

@VictorVG I appreciate your enthusiasm but please limit your comments only to essential information. This comment is not helpful. It doesn't actually provide enough information to solve the problem and has stuff not relevant to the issue (issue tracker is not a place for documenting history of printer drivers).

**Comment by VictorVG** [comment]
***kjk***

You're right. The head was busy fuss setting up a melted Xs. He answered mechanically.

**Comment by turnercat** [comment]
Thank you KJK for the most direct answer. I will use that method to print in reverse order, however, if you click Preferences from the main Print window, then click the Advanced tab, there is a Reverse Print check box that, when checked, does not work.

**Comment by hedges333** [comment]
It would be great to have a reverse option for CLI though, for a little powershell script ChatGPT just wrote for me to do manual duplex.

**Comment by GitHubRulesOK** [comment]
@hedges333  there is a commandline duplex flag but as with most Hardware options the printer needs to get that from windows.

The OPTION to send pages BACKWARDS is Windows Spooling via printer drivers so SumatraPDF does not need to send pages in reverse. If there is a Windows means to change the current defaut driver printer driver that is down to the PRINTUI command.

![Image](https://github.com/user-attachments/assets/253c80e8-1fdc-4a90-97b9-157267a16254)![Image](https://github.com/user-attachments/assets/f6632f8f-7e44-414f-ba0a-e3dec500c63a)
