### ISSUE TITLE
Enhance pdfmark

### ISSUE THREAD

**Issue by tim-chan** [sumatrapdfreader/sumatrapdf#296]
Limited pdfmark support already exists, for example, URL link.

Text (or note) support does not seem to work properly but is recognised as "something".

Complete pdfmark is complex and has security risks. A working subset is useful. For example, showing text when a mouse pointer is hovered, or opening a  text display notice. Going as far as Forms would I think be a lot of work, probably not worth the effort.

Here is one reference document.
http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdfmark_reference.pdf

**Comment by kjk** [comment]
It's too vague of a request.

If you have a PDF with a specific feature that works in another PDF reader but not sumatra, then open an issue for that specific thing (providing a test file) and we will take a look and decide if it's worth supporting.

We don't have the time to do lots of work to support extensions that I don't even know are commonly used in practice and have no test documents to verify that the feature works correctly.
