### ISSUE TITLE
Command line arguments not working

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#2965]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/2964

<div type='discussions-op-text'>

<sup>Originally posted by **exonie** September 18, 2022</sup>
Hello,
SumatraPDF does not respect any arguments I tried passing to it. It's the latest Sumatra ver. 3.4.6 64-bit on Windows 10 ver. 21H2.

Neither arguments in shortcuts to PDF files, nor from the command terminal as shown in the attached images:
![sumatra-arguments1](https://user-images.githubusercontent.com/7358387/190915916-4be036b4-163c-42e8-a42b-a3389c887447.png)
![sumatra-arguments3](https://user-images.githubusercontent.com/7358387/190916759-a654815d-39b2-4cb9-ac64-4abf5f704687.png)

It does not open the indicated page, nor does it start in fullscreen. It worked fine before. Other programs on my system, like the Chrome browser, work alright with arguments.

Does anyone else have this problem or is something wrong with my set-up?</div>

**Comment by GitHubRulesOK** [comment]
@exonie

OK I agree 3.4.6 does not work same as 3.4.5

@kjk 
I confirmed there is a difference in both 32 bit and 64 bit compared to any previous so moved to issues

**Comment by hme3** [comment]
I noticed in 3.4.6 the shell open command in registry (specific to my user) for SummatraPDF.pdf
"C:\Users\Henry\AppData\Local\SumatraPDF\SumatraPDF.exe" "%1"
changing it to:
"C:\Users\Henry\AppData\Local\SumatraPDF\SumatraPDF.exe" "%1" "%2" "%3"
allows the -page 10 to work

**Comment by GitHubRulesOK** [comment]
@kjk I am reminded by this issue that Something changed in the way sumatraPDF exe is called 
which may or may not have a bearing on other problems such as use by LaTeX

**Comment by kjk** [comment]
I can't reproduce this.
```
> ."C:\Users\kjk\AppData\Local\SumatraPDF\SumatraPDF.exe" "C:\Users\kjk\!sumatra\1.pdf"
> ."C:\Users\kjk\AppData\Local\SumatraPDF\SumatraPDF.exe" "C:\Users\kjk\!sumatra\1.pdf" -page 3
> ."C:\Users\kjk\AppData\Local\SumatraPDF\SumatraPDF.exe" "C:\Users\kjk\!sumatra\1.pdf" -fullscreen
```
all work as expected.

Also made a copy of the shortcut and added pdf path an `-page 3` arg and it worked.

One thing that doesn't work is naked `-fullscreen` but I don't know if that every worked or should work.

I would need a step-by-step repro that demonstrates the problem.

**Comment by GitHubRulesOK** [comment]
thanks I agree it is naked fullscreen seem the common non one mentioned and perhaps that is the core of this issue?

**Comment by GitHubRulesOK** [comment]
@kjk 
I wonder if manual needs adjusted mention

```
List of command line options
-presentation : start in presentation view
-fullscreen : start in full screen view
```

**List of command line options**
-presentation : start **with file** in presentation view
-fullscreen : start **with file** in full screen view

**Comment by kjk** [comment]
made `-fullscreen` work even without any file opened

**Comment by exonie** [comment]
This still does not work for me. It turns out a bit more complicated as it seems to be connected with this bug #3992 

1. In Settings: "Use tabs"-> uncheck
2. Open some file.
3. Try to open another file with the `-page` option - either through a shortcut or in the command line. It does not open at that page. The other bug also instantiates here as an additional copy of the first file is opened.

**Comment by GitHubRulesOK** [comment]
@exonie 
fixes are only generally applied to newest pre-release (or in a few cases to a new minor release) thus if a bug was in 3.5.2 it stays in 3.5.2

**Comment by exonie** [comment]
Alright, just checked it - it's fixed in the prerelease.
