### ISSUE TITLE
VS2022 Preview complains about wide char to char conversions in MakeLZSA

### ISSUE THREAD

**Issue by KaoDome** [sumatrapdfreader/sumatrapdf#2968]
Hi, I was looking into setting up a build environment for SumatraPDF to see how it all fits together, cloned the repo and fired up the current VS2022 Preview in a VM after regenerating the solution and projects using Premake (I used the binary their devs released a couple of days ago).

When trying to build the `MakeLZSA` project without any modification in x64 release mode I stumbled upon a function expecting a `char *` being handed a wide char version of it. Internally it (or some other functions that it uses) makes the conversion to wide chars using `ToWstrTemp()`. I noticed there's also a similar one to go backwards, `ToUtf8Temp()`, but I was wondering if things could be streamlined using wide chars throughout.

I looked into changing those functions, so they already accept a wide string as an input and dispense of the conversions, but I wonder if that would have ramifications through other areas since I'm not acquainted with the whole codebase. So I thought of letting you guys know, here's a screenshot of a failed build for context:

![WCHAR to char](https://user-images.githubusercontent.com/61412446/191197220-96e23778-5140-4498-b81c-32412f12f265.png)

The environment was a clean Windows 11 VM, Visual Studio 2022 17.4 Preview 2.0 and the Windows SDK in use is 10.0.22621.0, in case it's relevant. Language standards and the like are defaults, so it's Draft for C++ and the older, legacy one for C, not any of the current ones (C11 / C17).

**Comment by kjk** [comment]
I don't keep makelzsa up-to-date with refactorings because I don't need to build it and it's not used by SumatraPDF.sln solution. You don't need to build it to make sumatra.

The right fix here would be to convert from WCHAR* to char*
