### ISSUE TITLE
Bad rendering of narrow polygons

### ISSUE THREAD

**Issue by otsaw** [sumatrapdfreader/sumatrapdf#297]
Sumatra seems to render narrow polygons with inconsistent widths. I have a PDF of traffic flows created with R, ggplot2 and the [cairo_pdf](https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/cairo.html) device. The graphics consist of polygons scaled away from road centerlines according to direction-wise traffic volume. The polygons should consistently get narrower when going from a larger to a smaller road, especially in case of dead-end roads. See the PDF below and my screenshots from Sumatra and Adobe Reader. As the polygons get very narrow, Sumatra begins to render parts with a constant excessive width.

http://files.strafica.fi/osa/sumatra/test_polys.pdf
http://files.strafica.fi/osa/sumatra/test_polys-sumatra.png
http://files.strafica.fi/osa/sumatra/test_polys-adobe.png

**Comment by kjk** [comment]
Fixed in latest pre-release http://www.sumatrapdfreader.org/prerelease.html
