### ISSUE TITLE
Crash from PDF with embedded graphical signature

### ISSUE THREAD

**Issue by dd23** [sumatrapdfreader/sumatrapdf#2979]
I can reproducibly crash the latest pre-release 3.5.15241 and get the following error log:
https://gist.github.com/dd23/c105fed59b2cadeb3d12f7c48ac222a6
(I redacted some directories and file names in there).

The problems occurs on a page that has a hand-drawn figure of a signature. Other PDF viewers (XODO PDF, Firefox's internal PDF thingy) show it fine, but Sumatra currently crashes.

I will send the problematic PDF via email, as I cannot share it publicly.

**Comment by GitHubRulesOK** [comment]
@kjk 
I am going to Hazzard a guess this is the same annotation crash as all the others

>Ink annotations have no Rect property

**Comment by GitHubRulesOK** [comment]
Should be fixed in 3.5.15244+ (see note)
likely caused by annotation instability

Note:- current pre-release is 3.5.15249 and on first run MAY crash for a different reason see  https://github.com/sumatrapdfreader/sumatrapdf/issues/2984

**Comment by dd23** [comment]
Can confirm: v3.5.15249 fixes the issue mentioned here. Thanks!
