### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by taooceros** [sumatrapdfreader/sumatrapdf#2981]
https://gist.github.com/taooceros/ca1198a3816892f96e10e7b9e5a2c73d

Crash when opening the following file
[TheTextBook.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9637926/TheTextBook.pdf)

**Comment by GitHubRulesOK** [comment]
Should be fixed in 3.5.15244+ (see note)
likely caused by incomplete annotation on page 171 (181)

Note:- current pre-release is 3.5.15449 and on first run MAY crash for a different reason see https://github.com/sumatrapdfreader/sumatrapdf/issues/2984
