### ISSUE TITLE
Feature Request: Wanted to get meaning of a specific word just after selecting it

### ISSUE THREAD

**Issue by Akshay-1024** [sumatrapdfreader/sumatrapdf#2982]
Let us say we are reading some PDF or any other format and we suddenly got struck at a word that we don't know the meaning.

![image](https://user-images.githubusercontent.com/63490132/192082984-3f92d069-2b94-46e1-b173-095be904644c.png)

* lets see we don't know the word "Introduction" so to get the meaning of it we will use the internet and search and we waste a lot of 
  time if we do that through UI, but there is a free API call for the dictionary that we can integrate it with SumatraPDF

* Website: https://dictionaryapi.dev/ the api call is in the website with that when we select the word in SumatraPDF

![image](https://user-images.githubusercontent.com/63490132/192083143-ce26a281-c9f1-4872-8cb4-2b423989c28a.png)

Immediately the call should go from the api to get the meaning of the word and the meaning of the word should be stored in any text editor like notepad or any other thing or maybe displayed like a closeable pop up so that very less time will be wasted when going through any reading materials

![image](https://user-images.githubusercontent.com/63490132/192083266-681f6a15-10ae-4b61-9634-564fff3b03f5.png)

So if it will be like that in the end we can save the file and use it when ever we need 
This is the basic idea I wanted to implement. Any help would be appreciated, feedback and review comments are welcomed.
This will be my first push to open source.

**Comment by GitHubRulesOK** [comment]
SumatraPDF is a windows based web enhanced browser so in the past was used to show web pdf like acrobat or online xps or djvu files but that function was removed by IE and Chrome dominance  plus security concerns, However I can still read this web page as HTML and select your Introduction example, just as I can in a local PDF to look-up via any configured infernal setting
![image](https://user-images.githubusercontent.com/12754913/192107265-28d76917-048b-447a-8f68-60d8d386ee23.png)

**Comment by Akshay-1024** [comment]
Thank you @GitHubRulesOK , I can use the search with google as mentioned, that seems easy compared to using the API call. And also thanks for the very detailed explanation. I have a lot to learn from this Code.
