### ISSUE TITLE
Sumatra window omnipresent in all the virtual desktops

### ISSUE THREAD

**Issue by yashpalgoyal1304** [sumatrapdfreader/sumatrapdf#2983]
### Steps
* open sumatra - to keep simple, open only single window of it
* create new virtual desktop
(above steps can be done in any order)
3. change the virtual desktop
4. observe that sumatra's presence spans across all the virtual desktops

this is like a feature bug - i.e. sometimes it is wanted, most of the times not. So, having an option to toggle this behaviour would be nice.

aside: reading here: https://github.com/sumatrapdfreader/sumatrapdf/issues/18#issuecomment-358389944 ; it seems that earlier, sumatra stayed local to the virtual desktop, rather than becoming omnipresent

### Environment
* Windows 10 20H2
* Sumatra v3.4.6 64bit, v3.2 64bit

### Screenrecording

https://user-images.githubusercontent.com/19423063/192115813-7b9f23b2-62dc-42df-bb31-24717791be51.mp4

-----
duplicate searched with:
* [virtual desktop](https://github.com/sumatrapdfreader/sumatrapdf/issues?q=virtual+desktop+is%3Aclosed)
* [desktop](https://github.com/sumatrapdfreader/sumatrapdf/issues?q=desktop+is%3Aopen)
* [spans across all workspaces](https://github.com/sumatrapdfreader/sumatrapdf/issues?q=spans+across+all+desktops)

**Comment by GitHubRulesOK** [comment]
you will need to give more details
If SumatraPDF is on Desktop1 it is not carried over on 2 unless I start a second copy there
![image](https://user-images.githubusercontent.com/12754913/192110686-3f7454dc-856a-49ac-8218-2dd8a0c78857.png)
![image](https://user-images.githubusercontent.com/12754913/192110787-4c6feafd-6b9e-4617-9f8c-779234f8d2d2.png)

**Comment by yashpalgoyal1304** [comment]
> you will need to give more details

windows 10 20H2 Sumatra pdf v3.2 64 bit

**Comment by GitHubRulesOK** [comment]
I am using win 11 (most often in sandbox, but desktop does not function well there so using standard desktops) current test was using a recent (not latest, pre-release)

So with 3.2 if the session is on desktop1 and I call it again from desktop2 it will naturally resume desktop1 (where the current tabbed session window is). If on desktop1 I release (uncheck tabs) the seperate windows then on desktop2 a seconnd session will start. Thus I guess that's part of your problem. Tabs on one window, or no tabs on both. There are means to start SumatraPDF twice but unsure of your needs.

![image](https://user-images.githubusercontent.com/12754913/192114306-eea405fe-d609-4ee6-9326-d4b950c559b3.png)

**Comment by yashpalgoyal1304** [comment]
okay wait, lemme (try to) share a screen rec...

**Comment by yashpalgoyal1304** [comment]
https://user-images.githubusercontent.com/19423063/192115813-7b9f23b2-62dc-42df-bb31-24717791be51.mp4

**Comment by GitHubRulesOK** [comment]
I still cannot duplicate that behavior on Windows 11 using One SumatraPDF it can be dragged between multiple desktops without any second copy but you are running a latex file so I suspect notepad3 may be the issue in your case as it needs to call SumatraPDF as its latex previewer.

**Comment by yashpalgoyal1304** [comment]
> you are running a latex file so I suspect notepad3 may be the issue in your case as it needs to call SumatraPDF as its latex previewer.


* i had created one more recording with only sumatra just before this recording , but i didn't post that as i thought that since sumatra is present everywhere, the process of changing virtual desktops was not really noticable.
* that was just for sample - so that differences on changing virtual desktops and the fact that some things stay local on one desktop while sumatra doesn't could be easily spottable. 
* i faced this issue in every situation, long before i even knew what latex is. and even in this recording, only the pdf regarding latex was open. i had closed everything else. the notepad was started afresh - blank - not with source.

here's the recording i created before:

https://user-images.githubusercontent.com/19423063/192118610-a23ea70f-e227-45fb-96b2-66f203cb6ebc.mp4

**Comment by GitHubRulesOK** [comment]
Hmm the only way i am seeing any thing like that is in sumatrapdf start with new window but then there are two desktop copies that I can drag the second to second desktop, but that not what your displaying.

On windows 10 I am using current prerelease and that is exactly the same for me i.e. one sumatrapdf can only be dragged one desktop at a time when using tabs (even in fullscreen) or more copies can be more desktops.

So I am perplexed/confused why your 3.2 is behaving differently, perhaps try a portable copy of current release 3.4.6 or 3.5 prerelease and see if that behavior is still there since only 3.5 is likely to be fixable.

**Comment by yashpalgoyal1304** [comment]
so, 
* i opened "menu > settings > advanced options" to see maybe if some option exist there
* but found none
* meanwhile, there were many many old enteries which are no-longer of my use in the `FileStats[ [][] ... ]` - i deleted some of those
* and it fixed the issue.... 

so closing the issue

**Comment by yashpalgoyal1304** [comment]
And even though, the issue is closed, i would still like to know some thoughts on why it could have been and can this be made into an optional feature?

**Comment by yashpalgoyal1304** [comment]
i am 80-90% sure that this issue will pop up again, i will **try to** keep an eye out to notice it, and if some pattern could be observed off of it. so, please don't lock this issue - if some bot mechanism is used here for this repo's tracker

**Comment by yashpalgoyal1304** [comment]
and of course this reappeared soon - i thought i had reported back/updateed it here

**Comment by yashpalgoyal1304** [comment]
this is driving me nuts really - i really liked sumatra, but this particular issue is forcing me to look for alts...

**Comment by kjk** [comment]
I'm pretty sure you've enabled "Show window on all desktop" feature for Sumatra window.

Here's how to enable / disable it: https://superuser.com/questions/1674972/how-to-show-a-window-on-all-virtual-desktops

In short: Windows key + Tab, right click on Sumatra window and change the setting.

**Comment by yashpalgoyal1304** [comment]
> "Show window on all desktop" feature for Sumatra window.

aahow, now that you mentioned it, i have a suuuuper faint memory - maybe even illusionary or imaginary that yeah, maybe i might have did smth like that some years ago maybe....

so many windows updates, turn offs etc since then...

i just checked on right clicking sumatra in task view, it was unchecked - but i enabled and disabled it to do a kinda force refresh.

it has fixed it so far. thanks a lot for sharing :smiley:

**Comment by yashpalgoyal1304** [comment]
one more thing i did some days ago that may have helped "disabling" that option from windows rememberance is that i uninstalled sumatra, and extracted a portable sumatra instead
