### ISSUE TITLE
Crash Report - Crash ocurred right after updating Sumatra

### ISSUE THREAD

**Issue by ProgrammedPeinado** [sumatrapdfreader/sumatrapdf#2984]
[<script src="https://gist.github.com/ProgrammedPeinado/37d24648e66f6cac9cbe8511cf94b59b.js"></script>](https://gist.github.com/ProgrammedPeinado/37d24648e66f6cac9cbe8511cf94b59b)

**Comment by GitHubRulesOK** [comment]
@kjk I am seeing similar related crashes in last four builds annotation looks more stable but am seeing
CreateSumatraAcceleratorTable

**Comment by d0ggie** [comment]
A workaround is to add (an empty) Shortcut entry to SumatraPDF-settings.txt:

```
Shortcuts [
	[
	]
]
```

**Comment by GitHubRulesOK** [comment]
@d0ggie 
Well done so how did you work that out?

**Comment by d0ggie** [comment]
I was chasing a wrong lead, and that was just by an accident.  The issue here is that sizeof(ACCEL)==6 and since the allocation is done for both tables at once if the number of resulting accelators is odd the latter treeViewAccels is unaligned.

Really difficult to tell by looking at the code alone but CreateAcceleratorTableW returns a null pointer and sets up a corresponding error code unless the input table is aligned.

**Comment by davidbstanley** [comment]
Another confirmation that the workaround works.  Sumatra was crashing on opening with version 3.5.15249 64 bit on Win 10.

**Comment by GitHubRulesOK** [comment]
@davidbstanley there are two separate bugs from 3.5.15234 - 243 there was poor annotation detections due to MuPDF changes, rectified in 3.5.15244 however a fresh settings issue introduced straight after as seen in 3.5.15246 - 15249 hopefully to be addressed soon

**Comment by fblais** [comment]
Workaround worked for me too.

**Comment by meteorquake** [comment]
I've just updated and have found this crash. Unfortunately I didn't keep the previous prerel exe, though I have an older one.
As a general point -
1. Is there an archive of prereleases, even if not every single one? as that would also help people roll back to something that works that is more than just the stable release.
2. When updating from Sumatra is it possible it could retain the prior exe and settings as a rollback? this would make things much simpler!
d

**Comment by GitHubRulesOK** [comment]
@meteorquake 
There were older revs for some time but they get abused by leaching software update sites, so some did offer own copies, but if one day there are 20 updates they struggle, in this case the last retained 15244 , luckily works ok but the whole point of pre-release its cutting edge and if you want to keep any prior as backups you can.
