### ISSUE TITLE
Crash right after update

### ISSUE THREAD

**Issue by fblais** [sumatrapdfreader/sumatrapdf#2988]
https://gist.github.com/fblais/48d588b60d2fd81d5d67555e06fd96cd

[Sequence_de_test_Labview_C0061x_Rev1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9668673/Sequence_de_test_Labview_C0061x_Rev1.pdf)

The crash happened right after SumatraPDF update.
Now each time I start SumatraPDF it crashes.

**Comment by GitHubRulesOK** [comment]
please at least check a few open issues 3.5.15249 CreateSumatraAcceleratorTable has been reported by at least a handful of entries

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/01d3fa8709699157864dcee59d8346414322914b
