### ISSUE TITLE
Hand tool

### ISSUE THREAD

**Issue by Dogway** [sumatrapdfreader/sumatrapdf#299]
There are no tools currently (text, hand, arrow) only a single one context sensible.

I just go through the pages by clicking and dragging up, this is the most convenient/brainless way since I can click anywhere inside the document without going to the keyboard or the sidescroll bar. The problem is that depending on content it will click on any kind of objects, text (highlighting text), links, etc.

Could it be possible to add a content agnostic hand tool? or maybe a view mode that respects book's layout.

**Comment by GitHubRulesOK** [comment]
@Dogway 
Technically whilst left click an drag is "contextually aware" and only uses a fist in inactive areas, a right click and drag should show the fist "content agnostically" i.e. only allow for dragging, ignoring content, unless you click without drag which at worst only offers a small selection dialog.

**Comment by Dogway** [comment]
I tried with RMB+Drag but it feels strange and kind of tiring after a bit.
It's unnatural, just for the sake of how often we are going to copy an image/text chunk.

**Comment by GitHubRulesOK** [comment]
Fair point and simple solution inside SumatraPDF could be a swap mouse buttons setting
I guess the next best option would be a solution to togle usage just while you are running SumatraPDF which may involve a script such as those discussed at https://superuser.com/questions/205861/keyboard-shortcut-to-swap-mouse-buttons personally I would use an AutoHotKey answer from https://superuser.com/questions/1244084/how-do-i-swap-primary-and-secondary-mouse-buttons-from-the-command-line-or-by-us?noredirect=1&lq=1

**Comment by GitHubRulesOK** [comment]
For anyone  coming here and wanting a quickway to toggle the mouse

The easiest answer based on first answer above was to run main.cpl (you can enter `main.cpl` into cortana searchbox or simply make yourself a shortcut

Then its click to select the handedness you want (if you see  touchpad you may need to select mouse) for keyboard users its ALT L Enter for set mouse to Left Handed settings and ALT R Enter to set back to Right Handed Default

**Comment by kjk** [comment]
Lack of explicit "hand" tool is intentional.

Not sure if that helps but `right mouse` or `Shift + left mouse` will always move the page (instead of selecting text)

**Comment by Dogway** [comment]
I think it's basically a thing of how often you open a PDF to select text, versus scroll pages. Adding the burden of hold shift or hold middle finger down for a corner use case seems awkward. I will craft an AHK script, thank you.

**Comment by GitHubRulesOK** [comment]
@Dogway if you write a ToggleDragHandle.ahk for SumatraPDF class/exe it may help other users if you can post it here.

**Comment by Dogway** [comment]
```
#If WinActive("ahk_exe SumatraPDF.exe")
MouseGetPos, , , id, ControlHwnd,2
WinGetClass, winclass, ahk_id %id%
MyClass := "SUMATRA_PDF_FRAME"
IfInString, MyClass, %winclass%
{
LButton::Send, {RButton down}
LButton Up::Send,  {RButton up}
}
#If
Return
```
Draft code, needs some work. Will eventually upload to my AHK [repo](https://github.com/Dogway/AutoHotkey-Scripts)

**Comment by springjools** [comment]
> Lack of explicit "hand" tool is intentional.
> 
> Not sure if that helps but `right mouse` or `Shift + left mouse` will always move the page (instead of selecting text)

Then a hand symbol should appear when holding shift or jusing RMB
