### ISSUE TITLE
Crash on start without file

### ISSUE THREAD

**Issue by ratuka** [sumatrapdfreader/sumatrapdf#2996]
https://gist.github.com/ratuka/8dce79d1d42667c29d1caecac72b4c6d

what were you doing when the crash happened
just starting the application after install

when did the crash happen. When opening a file? changing view? etc.
at start

**Comment by GitHubRulesOK** [comment]
3.5.15249 please see any one of the other reports either rollback to 15244 or apply the workaround until resolved
retest and close this issue if you think workaround resolves your case..

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/01d3fa8709699157864dcee59d8346414322914b
