### ISSUE TITLE
[bug report] failed to open SumatraPDF

### ISSUE THREAD

**Issue by tylvn** [sumatrapdfreader/sumatrapdf#2997]
When I right-click a file and opened with SumatraPDF pre-release version in file manager, I received a upgrade from SumatraPDF. I cannot open SumatraPDF after pre-release version is updating. 

[crash report file](https://gist.github.com/tylvn/b86b7cde88e52952febbecdbd52bf99f)

the file that caused the crash: [免疫学实验一.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9692545/default.pdf)

**Comment by GitHubRulesOK** [comment]
3.5.15249 please see any one of the other reports either rollback to 15244 or apply the CreateSumatraAcceleratorTable workaround two lines [ & ] after settings shortcuts [ until resolved
retest and close this issue if you think workaround resolves your case..

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/01d3fa8709699157864dcee59d8346414322914b

**Comment by tylvn** [comment]
> Should be fixed by [01d3fa8](https://github.com/sumatrapdfreader/sumatrapdf/commit/01d3fa8709699157864dcee59d8346414322914b)

Thanks👌
