### ISSUE TITLE
Dotted line (created in InDesign) missing single dot

### ISSUE THREAD

**Issue by briester85** [sumatrapdfreader/sumatrapdf#30]
Hello, the Sumatra app is rendering dotted lines without a dot. Usually the second dot in the line. Zooming and scrolling show consistently that the same dot is always missing. The web renderer does not present the bug, and importing to Illustrator and Photoshop also do not present the bug. 

Screens attached.

Enjoy ^_^

![mainscreen](https://cloud.githubusercontent.com/assets/10161183/5405623/330389f4-815c-11e4-84bb-a328f2dfcfb2.png)

![pdf](https://cloud.githubusercontent.com/assets/10161183/5405624/33054028-815c-11e4-8208-2b6f205c1489.png)

**Comment by GitHubRulesOK** [comment]
@kjk without a sample to test and in light of the numerous rendering improvements I suggest this is closed as insufficient information until any other example is forthcoming.

**Comment by kjk** [comment]
agreed, closing as most likely fixed
