### ISSUE TITLE
Feature or Request - XPx64 / 2003x64 - is not a valid Win32 application

### ISSUE THREAD

**Issue by LancelotC** [sumatrapdfreader/sumatrapdf#300]
Hi,

I am not sure where to write, feature or request:

just tested SumatraPDF-prerelease-10375-64.exe on Xp-X64,
which gives error:

"..SumatraPDF-prerelease-10375-64.exe is not a valid Win32 application"

I hope it is easy to fix on compiler settings :)

Thanks for Sumatra :+1:

**Comment by VictorVG** [comment]
**LancelotC**

PE64 header on SumatraPDF-prerelease-10375-64.exe have record *required OS version 6.00* wrote that x64 edition required OS Windows Vista/Server 2008 or letter OS version.

**Comment by LancelotC** [comment]
Hi VictorVG,

I believe this header is a mistake about compiler default setting that compiles x64,
 I had seen that before ;)

I hope it will be fixed on final x64 release :)

**Comment by VictorVG** [comment]
Try to collect from the command line MS VC++ 2010 (not sure that your compiler will gather):

*nmake -f makefile.msvc CFG = rel PLATFORM = X64*

But where to get the source code I think you know.

**Comment by kjk** [comment]
Fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/6dd584d26eb2e070926287250cd7bc449501c91e

**Comment by LancelotC** [comment]
Thanks kjk,
Thanks VictorVG
:)

**Comment by VictorVG** [comment]
Ok! :)
