### ISSUE TITLE
Crash opening file (right after updating)

### ISSUE THREAD

**Issue by jiangliubang99** [sumatrapdfreader/sumatrapdf#3004]
https://gist.github.com/jiangliubang99/b27f95df99b98695a75c3e9c8070d8ba

[Light Rays, Singularities, and All That.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9712349/Light.Rays.Singularities.and.All.That.pdf)

On windows 11 machine, previously had this file opened.
Updated Sumatra, then tried to open this file from search bar (windows key search), crashed again.
Tried to open again, crashed again.

**Comment by Otherdeath** [comment]
Having the exact same issue. All files attempting to open in Sumatrapdf are crashing and it's not tied to a single one including the desktop shortcut for Sumatrapdf itself. I tried both pdf and epub files on hand.

[https://gist.github.com/Otherdeath/020e73b94aad73d59af2b05ef4440b52.js](url) Error from an epub novel.

**Comment by GitHubRulesOK** [comment]
@jiangliubang99 & @Otherdeath
 your using 3.5.15249 please read https://github.com/sumatrapdfreader/sumatrapdf/issues/3003#issuecomment-1267629292

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/01d3fa8709699157864dcee59d8346414322914b
