### ISSUE TITLE
Settings file contains extensive recent files history

### ISSUE THREAD

**Issue by tmryan2** [sumatrapdfreader/sumatrapdf#3005]
In the settings.txt file under Advanced Options, Sumatra keeps an extensive history of all the pdfs that have been opened and their FilePath as well, not just the 10 most recent files. This can be a privacy issue. There doesn't seem to be a way to limit the history that is tracked in this file to the last 10 files only?

**Comment by kjk** [comment]
There's no option to limit that and no plan to add it.
