### ISSUE TITLE
sumatrapdf crash

### ISSUE THREAD

**Issue by bluelayer** [sumatrapdfreader/sumatrapdf#3010]
hello!

for the first time ever, a crash! =)

https://gist.github.com/bluelayer/f3c2700bc25483ab1cd2b668b2a95b77

**Comment by GitHubRulesOK** [comment]
hmm yous is not the latest round of crash reports yours is likely annotation (15241) so see one of the earlier ones related to annotations but to shortcut that try this [comment 152**44**](https://github.com/sumatrapdfreader/sumatrapdf/issues/2984#issuecomment-1260708162) version should solve yours If so please close this one

**Comment by bluelayer** [comment]
15244 does not fix it, 15249 does not even open, applied fix to 15249, all ok now =)
