### ISSUE TITLE
DiskAcess

### ISSUE THREAD

**Issue by alexmonro** [sumatrapdfreader/sumatrapdf#302]
DiskAccess is allowed on version 3.0 and PinterAccess is not, would you please help me out changing the values of this variables, we use pc that are locked down by group policies and we do not allow the user to have access to the disk, on the other hando i need to give them access to be able to print 1 or more pages, this is because they work with manuals that can have 1 page or 600 pages, also what i noticed its that when you right click on the opened document the app crashes.

Thank you and i hope you can help me out.
Alex Leon 

 // enables Update checks, crash report submitting and hyperlinks
    Perm_InternetAccess     = 1 << 0,
    // enables opening and saving documents and launching external viewers
    Perm_DiskAccess         = 0 << 1,
    // enables persistence of preferences to disk (includes the Frequently Read page and Favorites)
    Perm_SavePreferences    = 1 << 2,
    // enables setting as default viewer
    Perm_RegistryAccess     = 1 << 3,
    // enables printing
    Perm_PrinterAccess      = 1 << 4,
    // enables image/text selections and selection copying (if permitted by the document)
    Perm_CopySelection      = 1 << 5,
    // enables fullscreen and presentation view modes
    Perm_FullscreenAccess   = 1 << 6,
    // enables all of the above
    Perm_All                = 0x0FFFFFF,
    // set through the command line (Policies might only apply when in restricted use mode)
    Perm_RestrictedUse      = 0x1000000,

**Comment by kjk** [comment]
This is a bug tracker, not a support forum. See http://forums.fofou.org/sumatrapdf
