### ISSUE TITLE
Error updating SumatraPDF-dev

### ISSUE THREAD

**Issue by GATOQSECOMIO** [sumatrapdfreader/sumatrapdf#3020]
When you try to update SumatraPDF-dev receive the following message: Can't connect to the Internet (error 0x2) (on SumatraPDF pre-release build version 15253, built on 2022-10-11).

**Comment by GATOQSECOMIO** [comment]
> Are you building your own ?

No, downloaded from [sumatrapdfreader.org/prerelease](https://www.sumatrapdfreader.org/prerelease)

I have the same issue on update 15253 to 15255. (Error 0x2)

S.O: Windows 10 LTSC 1809 2019

**Comment by GitHubRulesOK** [comment]
Hmm if i open a cmd on say local desktop or downloads and run to get older15253

`curl -O https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/prerel/15253/SumatraPDF-prerel-64.exe`

then launch SumatraPDF-prerel-64.exe and check update on click install it downloads and replaces as 15255
![image](https://user-images.githubusercontent.com/12754913/195835696-4b1fec91-b75f-4ea9-b128-2e73ed96ac49.png)

**Comment by sergeevabc** [comment]
Windows 7 x64, Sumatra [SumatraPDF-prerel-64.exe](https://www.sumatrapdfreader.org/dl/prerel/15261/SumatraPDF-prerel-64.exe) 15261.

![image](https://user-images.githubusercontent.com/373718/202937160-d9f2443f-85bf-40e9-83bb-caa07b66cf51.png)

**Comment by GitHubRulesOK** [comment]
@sergeevabc 
thats  odd just downloaded from your link runs ok
 ask for update and gives normal "you have the latest"

**Comment by sergeevabc** [comment]
@GitHubRulesOK, I get a Schannel error in Windows Events log after a failed Sumatra update attempt. It might be related to the handshake issue, e.g. protocol incompatibility when server refuses to accept TLS 1.2 connections. Wha URL is used in this case? I can try to connect via Internet Explorer directly.

**Comment by GitHubRulesOK** [comment]
I think it downloads the plain text from one of two txt
https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/sumpdf-prerelease-latest.txt
https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/sumpdf-prerelease-update.txt
those are in the upload sequence, but unsure which is used more likely the first

**Comment by sergeevabc** [comment]
Tried Sumatra's update check on an entirely different computer, however also located in Russia and managed by Windows 7 x64. The same 0x2 error there. 

As for direct opening update URLs via various browsers, cURL, and even Powershell's IRM method to fetch flies, sometimes the connection could be established, but more often meh.

With VPN turned on, URLs work fine, but Sumatra's check still produces that error.

**Comment by sergeevabc** [comment]
Trying out update checks in [different versions](https://sourceforge.net/projects/portableapps/files/Sumatra%20PDF%20Portable/) of Sumatra:
- 3.1.2 check works fine and offers 3.3.3 update
- 3.2 and later versions throw error 0x3afc
- 3.4.6 and later versions throw error 0x2

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by GitHubRulesOK** [comment]
Hi, still not a problem in Atlantic area still not uptated for last two, lets try 
![image](https://user-images.githubusercontent.com/12754913/204420182-5d17b01d-6f89-495a-b535-79bd3b696e33.png)
Instantly shows
![image](https://user-images.githubusercontent.com/12754913/204420296-58c09b11-627b-4c61-a754-2a0aaf8af561.png)
6 seconds later all done and working !

**Comment by sergeevabc** [comment]
Sumatra, according to [this piece of code](https://github.com/sumatrapdfreader/sumatrapdf/blob/c8afecac0a3d8c53cbb6e299ed0790ba3f6c7edd/src/UpdateCheck.cpp#L41), uses https://www.sumatrapdfreader.org/updatecheck-pre-release.txt for update check. That server is poorly configured, since only two cipher suites are enabled for TLS 1.2 (see below) It explains why Win10 machines are able to connect, whereas [Win7](https://learn.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-7) machines are rejected. Hence the issue.

```console
$ sslyze --tlsv1_2 www.sumatrapdfreader.org:443
 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             256       ECDH: prime256v1 (256 bits)
 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             128       ECDH: prime256v1 (256 bits)
```

**Comment by GitHubRulesOK** [comment]
ahh that may explain why my windows 7 devices never have a problem, They were updating afaik (or perhaps I used download page) but not updated daily since it went 64bit only as that older kit is 32 bit, and 7x64 is inactive at present.

**Comment by sergeevabc** [comment]
Right, since the problem with updates has been pinpointed, something should be done about it. Any of [these folks](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/AUTHORS) could alter the source files for sure, but only the one with an admin access to server is able to add missing ciphers. Who is it? Krzysztof Kowalczyk? Is he evne aware of this issue?

**Comment by LaurieWilliams5066** [comment]
I have been using Sumatra PDF reader for a few years.
Excellent light fast reader.
I have recommended it to many other people.
For many months every time I try to update Sumatra it shows the same 0x2 message that others have mentioned on this page.
It has never shown any error message as a result of its own automatic attempts at updating immediately after being started.
Late last year I tried uninstalling, then reinstalling from the latest file on the Sumatra PDF website.
The result was the same.
I'm in Adelaide, using Windows 7 x64, same as at least one other person here.
I hope this fault can be rectified soon.

**Comment by kjk** [comment]
@sergeevabc The website is proxied by Cloudflare. They claim to support more ciphers: https://developers.cloudflare.com/ssl/reference/cipher-suites/supported-cipher-suites/

I find it hard to believe Cloudflare would just break every win7 machine.

I see 2 possibilities:
* your network configuration injects some proxy which breaks things
* the code in Sumatra to do http requests (see HttpUtil.cpp, InternetOpenW etc.) doesn't work on win7 against cloudflare proxied websites.

Unfortunately I don't have win7 so it's hard to debug this.

Please attach the logs after this happens. Using latest pre-release, Ctrl-K (for command palette) and "show log". This should launch notepad with logs. I have logging in HttpUtil.cpp which should help point the exact code that failed.

**Comment by LaurieWilliams5066** [comment]
Same Sumatra update fault persists.
Other things in the same computer update with no trouble, including:
Opera
Thunderbird
VLC Media Player
Internet Download Manager
7+ Taskbar Tweaker

**Comment by kjk** [comment]
Still working on it, more info in https://github.com/sumatrapdfreader/sumatrapdf/issues/3306
