### ISSUE TITLE
Sumatra crash in Win11 22H2 clean install

### ISSUE THREAD

**Issue by mrebello** [sumatrapdfreader/sumatrapdf#3026]
[crashinfo.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/9802076/crashinfo.zip)
Windows 11 22H2 clean install, PT-BR, updated, with only sumatra installed.
In 22H2 updated from 22H1, its runs, but in a clean install of 22H22 it crash.

**Comment by kjk** [comment]
Can't do anything with a file that shows the problem.

Either way, I've replaced zlib-ng (present in your versoin) with zlib in latest pre-release, because it seems to crash less, so it's likely it's been fixed in latest pre-release: https://www.sumatrapdfreader.org/prerelease
