### ISSUE TITLE
Tabs do not display filenames properly due to font replacement

### ISSUE THREAD

**Issue by ryanlo713** [sumatrapdfreader/sumatrapdf#3029]
![image](https://user-images.githubusercontent.com/12672523/196667063-52661603-e664-4b12-9e7e-9d17c93489bf.png)

I’ve previously replaced the system UI fonts so that may have caused a text misalignment here. However, as shown in the figure, they show blank.

Possible solution: Provide the ability to adjust and customize the fonts used in the default user interface?

**Comment by kjk** [comment]
How did you replace system UI font and what did you change it to?
