### ISSUE TITLE
Regresion in rendering font in PDF between version 3.3.3 and 3.4.6

### ISSUE THREAD

**Issue by faramir** [sumatrapdfreader/sumatrapdf#3035]
There is a regression in rendering font in PDF files between version **3.3.3** and **3.4.6**. As far as I was able to investigate, the whole 3.4.x is causing problems.

In the newest version the letters are _jumping around_ as you can see in the screenshot. I'm attaching PDF file that is presented in screenshot ([contributor.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9827450/contributor.pdf)) as well as the source code from which the PDF file was generated ([mwe.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/9827451/mwe.zip)).

![Comparison](https://user-images.githubusercontent.com/567976/196887438-2f0f99fe-2324-4b76-87ac-ab9fb1d15787.png)

Current pre-release (build version 15260, built on 2022-10-19, commit cca40eea00bda7d230ede520f108133bfbaef453) also renders file like in version 3.4.6.

**Comment by GitHubRulesOK** [comment]
Common problem with that type of font the curves  get over compensated by pixel rendering
![image](https://user-images.githubusercontent.com/12754913/196933371-f8ad597f-a5c3-4553-9d4f-2103649e5a8e.png)


In an image viewer we can see especially all curved characters are deliberately lowered to average the visual pixel height

![image](https://user-images.githubusercontent.com/12754913/196933778-07b635f9-1982-4bb7-98a5-0ad8cdfc02c1.png)

**Comment by GitHubRulesOK** [comment]
Looks good in 3.5
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/72502d90-e5f9-4e40-9ed2-0107f37bd671)

screenshot at "actual size"
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/621b14c0-1a8f-4f7c-b479-338c19bcdd36)
