### ISSUE TITLE
Poor performance with specific PDF file (Rohm Semiconductor RVQ040N05 Datasheet)

### ISSUE THREAD

**Issue by multiplemonomials** [sumatrapdfreader/sumatrapdf#3037]
I frequently refer to this datasheet for a transistor: 
[rvq040n05tr-e.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9835863/rvq040n05tr-e.pdf)
However, SumatraPDF's performance with this document is extremely bad; it takes 5-10 seconds to render each page as I scroll through.  I practically have to keep Acrobat Reader around for this one file.  Not totally sure if this is a Sumatra issue, but figured I'd submit it in case you can find a fix.

**Comment by tactilis** [comment]
FYI, the datasheet opens perfectly and every page renders instantly for me in SumatraPDF v3.4.6 64bit.

**Comment by GitHubRulesOK** [comment]
There is a bit to be desired in that file since many vectors are seperate shards (possibly duplicates and overlaps) thus take longer to assemble
However opens in 0.00221 seconds then 0.00001 seconds to start display
```
rvq040n05tr-e.pdf', 14 pages
LoadDocument: 2.21 ms, 14 pages for 'C:\Users\K\Desktop\Issues\3037 rvq040n05tr-e.pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.01 ms
```

**Comment by multiplemonomials** [comment]
Huh, this is what I get when I open it
![sumatrapdf-rvq040n05](https://user-images.githubusercontent.com/2099358/197233679-29d360e7-771f-4d21-bb07-a392567bb3c6.gif)

**Comment by GitHubRulesOK** [comment]
hmm using your sample here in 3.4.6x64 it opens instantly there is no visible delay dragging scrollbar all 14 pages do not wait it is like viewing one continuous page 

I work with i7 device SSD drive so expect instant results, let me try 32 bit coal fired device but will take a few minutes to download :-)

**Comment by GitHubRulesOK** [comment]
see if this is better
[3037 rvq040n05tr-e_Optimized.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9840766/3037.rvq040n05tr-e_Optimized.pdf)

**Comment by multiplemonomials** [comment]
Wow, that one opens and scrolls instantly!  Thanks!
For reference I'm using an i7-7770k desktop with an SSD as well, so not sure why my performance is so much worse 🤷

**Comment by GitHubRulesOK** [comment]
I have no idea why as the source is nearly 600 objects in an encoded very random order and accepted the tracker optimization reduced objects to less than 500 but in a much better order for reading, unknown what it did so check fonts were not worsened, but I chose settings to minimize any damage
