### ISSUE TITLE
Crash when opening a pdf

### ISSUE THREAD

**Issue by mrjoaoarthur** [sumatrapdfreader/sumatrapdf#3041]
https://gist.github.com/mrjoaoarthur/33ae6dba7a923ef4df583eb443d8af49
[38906-227967-1-PB (2).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9841822/38906-227967-1-PB.2.pdf)

I had several files open and when I opened this one by double clicking it, the program crashed

**Comment by kjk** [comment]
I opened the file in latest pre-release (https://www.sumatrapdfreader.org/prerelease) and it didn't crash.

Please re-open if it crashes for you in latest pre-release
