### ISSUE TITLE
comment in SumatraPDF-settings.txt

### ISSUE THREAD

**Issue by yashpalgoyal1304** [sumatrapdfreader/sumatrapdf#3043]
hi, 
* i want to add some comments (i.e. lines which sumatra ignores) in that file, 
* how should i do those?
* i didn't find related any documentation at https://www.sumatrapdfreader.org/settings/settings3-2

**Comment by GitHubRulesOK** [comment]
Basically, anything not defined as a valid entry or as the head or tail comment lines gets swept top to bottom until held at the end so you can add comments = in the trailer but not in-line.
![image](https://user-images.githubusercontent.com/12754913/197346697-348743e9-deeb-4cfb-a46e-62f58262e86e.png)

**Comment by yashpalgoyal1304** [comment]
> ... or as the head or tail comment lines gets swept top to bottom until held at the end so you can add comments = in the trailer but not in-line ...

i can't understand this, can u rephrase?

**Comment by GitHubRulesOK** [comment]
you can add them for notes but SumatraPDF will delete or push down anything out of place as it rewrites the file from top to bottom

The only place you can keep comments is as per image (lower than # settings below)

**Comment by yashpalgoyal1304** [comment]
oh ohwkayh. so, this warrants a new issue then i guess 😅: https://github.com/sumatrapdfreader/sumatrapdf/issues/3046
