### ISSUE TITLE
Text with a superscript <sup>***</sup> tag appears as text with a subscript tag in epub format

### ISSUE THREAD

**Issue by alekssmitt** [sumatrapdfreader/sumatrapdf#3047]
`(the conceptual parent of</span> <em>e<sup>iπ</sup></em><span> + 1 = 0) is immensely useful for mathematically modeling phenomena`
(the conceptual parent of</span> <em>e<sup>iπ</sup></em><span> + 1 = 0) is immensely useful for mathematically modeling phenomena

![Untitled 1](https://user-images.githubusercontent.com/36442471/197384545-7d15405c-e066-4c60-90cd-c79cb5d2d91c.jpg)

**Comment by GitHubRulesOK** [comment]
need samples but styles are down to authorship
[Superscript.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/9846345/Superscript.zip)
![image](https://user-images.githubusercontent.com/12754913/197388357-2424653c-c70b-4a86-bb13-8e5174280fb1.png)

**Comment by alekssmitt** [comment]
here the excerpt of David Stipp's - A Most Elegant Equation.epub
[A Most Elegant Equation excerpt.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/9846921/A.Most.Elegant.Equation.excerpt.zip)

**Comment by alekssmitt** [comment]
Just found out the stylesheet is the culprit
`sup
{
  vertical-align: baseline;
  position: relative;
  top: -0.4em;
  font-size: 0.7em;
}`
Don't know much about it, just deleted it and that did the job just fine
