### ISSUE TITLE
How to make SumatraPDF not look terrible when dark?

### ISSUE THREAD

**Issue by Bestulo** [sumatrapdfreader/sumatrapdf#3048]
I've been trying for a while and it just doesn't seem possible? Is there some way to turn all of these whites into black or dark gray?

![image](https://user-images.githubusercontent.com/23301025/197393732-14f4cc49-2c1d-40c5-bbeb-028205a472f5.png)

**Comment by GitHubRulesOK** [comment]
use windowsblinds for the windows VisualC parts
for the internal paper canvas surround you can use custom rgb https://github.com/search?q=GradientColors&type=discussions
