### ISSUE TITLE
Error trying to print in 64-bit version 

### ISSUE THREAD

**Issue by dgdegiorgi** [sumatrapdfreader/sumatrapdf#305]
Trying to print a document (clicking to the printer icon) an error occurs.
The 32 bit vesion works without problem.
With 64-bit versions (I tried prerelease 10314 and 10375: both fail) it happens with all documents I tried.

Here some cut+Paste from Visual Studio debugger

Error shown in debug
Unhandled exception at 0x0000000001007356 (dlxcrjdm.dll) in SumatraPDF.exe: 0xC0000005: Access violation reading location 0x00000000A7737D50.

Repeated if "Continue" is selected
Exception thrown at 0x0000000001007356 (dlxcrjdm.dll) in SumatraPDF.exe: 0xC0000005: Access violation reading location 0x00000000A7737D50.

short disassembly

0000000001007342  jmp         000000000100736C
0000000001007344  cmp         dx,bp
0000000001007347  jne         0000000001007374
0000000001007349  cmp         r11d,r8d
000000000100734C  jg          0000000001007369
000000000100734E  mov         edi,dword ptr [rsi]
0000000001007350  xor         eax,eax
0000000001007352  lea         rcx,[rax-1]
0000000001007356  repne scas  word ptr [rdi]
0000000001007359  not         rcx
000000000100735C  lea         eax,[rcx+rcx]
000000000100735F  cmp         eax,r8d
0000000001007362  jg          0000000001007369
0000000001007364  cmp         eax,r11d
0000000001007367  jle         0000000001007374
0000000001007369  mov         di,bx

Call stack

>	dlxcrjdm.dll!0000000001007356()	Unknown
 	dlxcrziu.dll!000000006a92753c()	Unknown
 	dlxcrziu.dll!000000006a9305d4()	Unknown
 	dlxcrziu.dll!000000006a92bb1b()	Unknown
 	dlxcrziu.dll!000000006a947b92()	Unknown
 	dlxcrziu.dll!000000006a948598()	Unknown
 	winspool.drv!00007ffedb3cb94d()	Unknown
 	winspool.drv!00007ffedb3cb577()	Unknown
 	winspool.drv!00007ffedb3cb3e5()	Unknown
 	[External Code]	
 	SumatraPDF.exe!00007ff791ccd88e()	Unknown
 	SumatraPDF.exe!00007ff791d01be5()	Unknown
 	[External Code]	
 	dlxcrjdm.dll!0000000001007356()	Unknown
 	dlxcrziu.dll!000000006a92753c()	Unknown
 	dlxcrziu.dll!000000006a9305d4()	Unknown
 	dlxcrziu.dll!000000006a92bb1b()	Unknown
 	dlxcrziu.dll!000000006a947b92()	Unknown
 	dlxcrziu.dll!000000006a948598()	Unknown
 	winspool.drv!00007ffedb3cb94d()	Unknown
 	winspool.drv!00007ffedb3cb577()	Unknown
 	winspool.drv!00007ffedb3cb3e5()	Unknown
 	[External Code]	
 	SumatraPDF.exe!00007ff791cf4ad4()	Unknown
 	SumatraPDF.exe!00007ff791cccd68()	Unknown
 	SumatraPDF.exe!00007ff791ccd373()	Unknown
 	[External Code]	
 	SumatraPDF.exe!00007ff791cdc3c1()	Unknown
 	[External Code]	
 	SumatraPDF.exe!00007ff791cd08cb()	Unknown
 	SumatraPDF.exe!00007ff791cd1160()	Unknown
 	SumatraPDF.exe!00007ff791db3396()	Unknown
 	[External Code]

**Comment by kjk** [comment]
Unfortunately, the crash is in Dell printer driver (dlxcrjdm.dll), not Sumatra. There's nothing we can do about it.
