### ISSUE TITLE
Wish: `-DDE` command-line option

### ISSUE THREAD

**Issue by ilyaza** [sumatrapdfreader/sumatrapdf#3051]
Now that `DDE` is fully functional — can the `-DDE` option be supported (to send its argument[s] as `DDE` command[s] to the running copy of `SumatraPDF`?

**Comment by kjk** [comment]
I forgot to document it but `-dde` was added in 3.5 (I think). It's certainly available in latest pre-release (https://www.sumatrapdfreader.org/prerelease)

I've documented it at https://www.sumatrapdfreader.org/docs/DDE-Commands
