### ISSUE TITLE
Expanded bookmarks subtrees re-expand even after collapsing them

### ISSUE THREAD

**Issue by HamzaHajeir** [sumatrapdfreader/sumatrapdf#3055]
Hi There

Once I expand a sub-tree from the bookmarks, it can be collapsed, but it re-expands automatically after getting back to the tab (pdf file).
Scenario of:
1. collapse 
2. Close Sumatra 
3. Launch Sumatra
Didn't came up with this behavior.

![Sumatra bug](https://user-images.githubusercontent.com/32960423/197832831-b4b8e20c-9479-416d-b765-0f79989d479e.gif)

Seems to me it saves the state of expanding on tabs switch, but doesn't update it with collapses afterwards, (only expands).

**Comment by GitHubRulesOK** [comment]
SumatraPDF without store history should use document initial setting, however if user remember history is active it should on tab closure remember last state, BUT I think there is an open issue that flipping between tabs it does not store the closing state, probably reverting to last opened state !!

**Comment by HamzaHajeir** [comment]
Yes, I've found this one: 
https://github.com/sumatrapdfreader/sumatrapdf/issues/1721

**Comment by kjk** [comment]
this has been fixed
