### ISSUE TITLE
Background colors of application and pdf document are inverted

### ISSUE THREAD

**Issue by markus-hsk** [sumatrapdfreader/sumatrapdf#3059]
Since a few weeks now my Sumatra app shows a weird behaviour. The applications background is white while the documents are being colored in a grayish tone. It looks like the colors are being inverted though i dont intended this.

I already deinstalled and reinstalled Sumatra but without any effect (maybe because configs werent removed on deinstallation).

I use Sumatra 3.4.6 x64 under Windows 10 x64. Do you need some more specs?

This is how it looks like:
![Screenshot 2022-10-27 163008](https://user-images.githubusercontent.com/13730463/198315239-d7077044-b1d2-4d00-ad11-1be879392ec8.png)

This is the actual pdf file:
[sumatraissue.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/9880342/sumatraissue.pdf)

And this is my Sumatra configuration file:
[SumatraPDF-settings.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/9880354/SumatraPDF-settings.txt)

What am i doing wrong or how can i repair my installation?

Thanks in advance

**Comment by GitHubRulesOK** [comment]
currently your pdf/ebook background is grey `BackgroundColor = #cccccc` default white would be `#ffffff`
background is paper colour

For the whiter surround (canvas background) you can use GradientColors=#abc123 [#second] [#third]

**Comment by markus-hsk** [comment]
Oh... i found the real reason. Not exactly what you suggested, because GradientColors was removed a second after saving. BUT your hint about different backgrounds triggered me to search for more background configs (should have done that earlier). I found this one: 

MainWindowBackground = #80fff200

8 characters RGB code is wrong. after removing the last two chars its now finally back at how it should be. Why that value got saved wrong, i have really no idea though.

The backgroundColor was set to #cccccc by myself thinking it should be the color of the application and not the pdf document. Now everything makes sense.

Thank you for your quick reply.

**Comment by GitHubRulesOK** [comment]
GradientColors = #0000FF works for that blue but must be in same section of file as paper and ink

```
	PageSpacing = 4 4
	GradientColors = #0000FF
	HideScrollbars = false
```

MainWindowBackground = #80fff200 is normal but behaves oddly when disturbed

MainWindowBackground = #80fff201 will be bright yellow :-)

MainWindowBackground = #80cccccc will be dull grey

**Comment by markus-hsk** [comment]
Uhm i dont get it. How is that 8 digit RGB-Colorcode in MainWindowBackground suppossed to work? What does the first two digits (80) do? An why #fff200? #fff200 would be yellow just like fff201. #80fff2 on the other hand would be cyan. 

Yesterday i changed the value to #cccccc and it was all fine. #80cccccc is also as you say "dull gray", though i dont understand how. #80fff201 is exactly like you say a bright yellow without me understanding it. BUT #80fff200 is clear white and thats the most weird.

**Comment by GitHubRulesOK** [comment]
historically the background was alpha bright yellow, so many complaints the argb setting was neutralised to pale grey one bit more or less it becomes active.

**Comment by markus-hsk** [comment]
Okay i see. But what might be the reason, why #80fff200 switched from a grayish or so background to clear white a few weeks ago? Some change in operating system or display configuration? There must be a reason because i didnt change that color code first hand and it was grayish back then but suddenly changed to clear white.

**Comment by GitHubRulesOK** [comment]
If I set my colours to your settings file it will in latest versions look like
![image](https://user-images.githubusercontent.com/12754913/198619938-ce37a0f9-0157-454c-bba5-f355d6694827.png)

So very old versions that light canvas would have been yellow but different versions use different defaults
here is 3.1.2
![image](https://user-images.githubusercontent.com/12754913/198621990-7e064b03-7b97-4839-8657-c29f152cb9a6.png)

**Comment by markus-hsk** [comment]
Can't remeber to having updated Sumatra at that time. And if i do update something i check it out afterwards. So i really dont think that its the case. I remember the day i scanned some incoming bills and wondered "why is the sheet so big" (Everything white: Paper and Canvas)? I went to configs, saw that BackgroundColor code #000000 and thought "thats clearly the problem". Thats then i edited to #cccccc with the above effekt. Me thinking that there must be some error resulting in my issue here. 

I suspect we wont find out what exactly happened. There is no automatic update and without a log its hard to tell.

**Comment by GitHubRulesOK** [comment]
Am closing as it was a temporary miss configuration that can be cleared by resetting all settings to defaults
