### ISSUE TITLE
View Notes Added in Other PDF Programs

### ISSUE THREAD

**Issue by gnuarm** [sumatrapdfreader/sumatrapdf#3065]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3063

<div type='discussions-op-text'>

<sup>Originally posted by **gnuarm** October 29, 2022</sup>
I use Foxit Reader to add Notes to PDF files.  I can fully view these notes in Foxit.  In Sumatra, only the Note marker icon is visible and I can't find a way to read the note.  This icon looks like a tiny text balloon in yellow, like a tiny sticky note.  

In Foxit Reader you can hover over it to read the text, or it can be double clicked to open it for reading and editing.  Is the ability to view these notes not part of Sumatra?   

v3.4.14267 64 bit Pre-release </div>

**Comment by GitHubRulesOK** [comment]
no way to know without  exact sample but perdiscussion MuPDF is not Foxit based

**Comment by GitHubRulesOK** [comment]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/300a7a5b-f1d1-4516-8bec-88ecd026c063)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c6d75780-60f8-422a-9ee9-2424afc7627e)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e280e2ae-a755-4217-a466-262df19220f8)
