### ISSUE TITLE
Can't drag tabs to reorder them

### ISSUE THREAD

**Issue by dedmu5** [sumatrapdfreader/sumatrapdf#3067]
When I try to drag a tab between other tabs nothing happens
here is a gif of me doing it: [https://i.imgur.com/0EXB7B8.gif](url)

# my cfg file is:

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	HideScrollbars = false
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]

SelectionHandlers [
]
ExternalViewers [
]

ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
Annotations [
	HighlightColor = #ffff00
	UnderlineColor = #00ff00
	TextIconColor = #ffff00
	TextIconType = 
	DefaultAuthor = 
]

RememberOpenedFiles = true
RememberStatePerDocument = true
RestoreSession = true
UiLanguage = es
EnableTeXEnhancements = false
DefaultDisplayMode = continuous
DefaultZoom = fit width
Shortcuts [
	[
		Cmd = CmdDuplicateInNewWindow
		Key = W
	]
	[
		Cmd = CmdPrevTab
		Key = J
	]
	[
		Cmd = CmdNextTab
		Key = K
	]
	[
		Cmd = CmdScrollDownHalfPage
		Key = d
	]
	[
		Cmd = CmdScrollUpHalfPage
		Key = u
	]
	[
		Cmd = CmdCommandPalette
		Key = :
	]
	[
		Cmd = CmdFindNext
		Key = n
	]
	[
		Cmd = CmdFindPrev
		Key = N
	]
	[
		Cmd = CmdZoomIn
		Key = K
	]
	[
		Cmd = CmdZoomOut
		Key = J
	]
	[
		Cmd = CmdGoToNextPage
		Key = L
	]
	[
		Cmd = CmdGoToPrevPage
		Key = H
	]
	[
		Cmd = CmdToggleBookmarks
		Key = b
	]
	[
		Cmd = CmdClose
		Key = x
	]
	[
		Cmd = CmdReopenLastClosedFile
		Key = X
	]
]
EscToExit = false
ReuseInstance = false
ReloadModifiedDocuments = true

MainWindowBackground = #80fff200
FullPathInTitle = false
ShowMenubar = true
ShowToolbar = false
ShowFavorites = false
ShowToc = false
NoHomeTab = true
TocDy = 0
SidebarDx = 150
ToolbarSize = 18
TabWidth = 300
TreeFontSize = 0
SmoothScroll = false
ShowStartPage = true
CheckForUpdates = true
WindowState = 1
WindowPos = -1 26 646 742
UseTabs = true
UseSysColors = true
CustomScreenDPI = 0

FileStates [
	]

# my specs are:

         Operating System: Windows 11 Pro 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)
                 Language: Spanish (Regional Setting: Spanish)
      System Manufacturer: HP
             System Model: HP ProBook 440 G6
                Processor: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 CPUs), ~2.0GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16254MB RAM
          DirectX Version: DirectX 12
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.4.3
           DxDiag Version: 10.00.22621.0001 64bit Unicode

**Comment by GitHubRulesOK** [comment]
Hmm a problem since recent fixes to tab layout

@kjk seems that fixing tab issues recently has regressed ability to drag them

**Comment by kjk** [comment]
Yes, dragging tabs has been (temporarily) lost
