### ISSUE TITLE
Password bank for PDF.

### ISSUE THREAD

**Issue by rogacz1988** [sumatrapdfreader/sumatrapdf#307]
Hello
Sometimes i have many pdf from one source and one unchanged password.
Is a option to remember password and use for different pdf names?

**Comment by kjk** [comment]
No, we don't have such option.

**Comment by zeniko** [comment]
There's the advanced setting [DefaultPasswords](http://www.sumatrapdfreader.org/settings.html#DefaultPasswords) which should help in such a case: Through Settings -> Advanced Options... add a line starting with

    DefaultPasswords =

and add the password(s) SumatraPDF should try before showing the password prompt.

**Comment by rogacz1988** [comment]
Thanks, that is what i need :)
