### ISSUE TITLE
Hide cursor on fullscreen

### ISSUE THREAD

**Issue by priyavrat-misra** [sumatrapdfreader/sumatrapdf#3076]
Will it be possible to automatically hide the cursor if it is inactive for few seconds, like in media players?
I'd say this would make a good feature for fullscreen, since there will be one less distraction to worry about.

Thanks.

**Comment by priyavrat-misra** [comment]
Yes I'd love to see something like <kbd>F5</kbd> in <kbd>F11</kbd>.

@GitHubRulesOK It works for me in `v3.4.6`'s presentation mode, no flickerings.

**Comment by GitHubRulesOK** [comment]
Current pre-release 3.5.15732 this F5 issue seems to have been fixed at some time
