### ISSUE TITLE
move across multiple monitors with different DPIs

### ISSUE THREAD

**Issue by enihcam** [sumatrapdfreader/sumatrapdf#3078]
![image](https://user-images.githubusercontent.com/7010097/199908747-c85caa85-7a6c-4d2c-aebd-e75592970c0f.png)

as you can see, when sumatrapdf (3.4.6) is moved across multiple monitors with different DPIs, only menu bar adapts the new DPI setting of target monitor, whereas nav icon bar and bookmarks do not. 

a similar issue (https://github.com/sumatrapdfreader/sumatrapdf/issues/1832) has been filed previously, but that issue happens on 3.2 + bitmap and svg is being used today.

**Comment by kjk** [comment]
It is the same issue as #1832 We just don't have code to re-layout everything when DPI changes
