### ISSUE TITLE
Make 3.1 release

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#308]
The plan is to make a release sometime before Oct 12 (at the latest).

Need to at least re-run stress test after recent changes to rel3.1working branch.

**Comment by VictorVG** [comment]
Thanks! I realized that in the 3.1 branch remains only the last restore luster and announce write upon the appearance branch 3.2. :)

**Comment by VictorVG** [comment]
Another review (from the beginner just translated from Russian):

**Kaber**
http://forum.ru-board.com/topic.cgi?forum=5&topic=22740&start=1180#3

>I tried a program, I can say that the super. But explain to me how Krzysztof Kowalczyk has created a program much faster than the department programmers Adobe ?? He's a genius, or are they not?

**Comment by vgturtle127** [comment]
Is the plan still to release on the 12th? Because I see some issues and stuff that haven't been closed that have the 3.1 milestone/tag on them...

**Comment by VictorVG** [comment]
**@vgturtle127**

"*before Oct 12 (at the latest).*" not equ 12th :)

**Comment by vgturtle127** [comment]
@VictorVG  I suppose more specifically will the release be on schedule? :smiley:

**Comment by VictorVG** [comment]
Roughly it does not mean that it was in that day. You need - cheap or go? :)

**Comment by kjk** [comment]
@VictorVG  Please don't use bug tracker as a chat and don't comment unless it adds relevant information. There are people following the project that get e-mail after each comment.

@vgturtle127  I don't know what you're referring to. There are no bugs  with 3.1 milestone.

**Comment by vgturtle127** [comment]
#279, #56, #51, #18, #19, #20, #9, #5, #4, etc, etc.

I meant issues you created with the intention of hitting the 3.1 milestone. Sorry for the confusion.

**Comment by kjk** [comment]
Released: http://www.sumatrapdfreader.org/news.html#3.1

**Comment by VictorVG** [comment]
Thank you! The guys at ru-bord all day today asked: 

>*- This is a release?* 

Dream upgraded. Here he and a reason to rejoice. :-)
