### ISSUE TITLE
Bug: noscale + portrait print landscaped document

### ISSUE THREAD

**Issue by touhidurrr** [sumatrapdfreader/sumatrapdf#3081]
Same as title.

**Comment by GitHubRulesOK** [comment]
same as design

**Comment by touhidurrr** [comment]
so how to fix this? and how is this according to design?

**Comment by GitHubRulesOK** [comment]
I have no idea what your fixing "works for me"
what sumatrapdf are you using what install or portable which version what file sample 
how does dialog look like for printing what buttons selected for noscale
![image](https://user-images.githubusercontent.com/12754913/200125215-8e02ada5-11f6-407c-8db7-64bc99a50787.png)

**Comment by touhidurrr** [comment]
I am trying to print a PDF with my printer using SumatraPDF from command line with the following settings, Scale: noscale & orientation: portrait.

But it prints the document landscaped.

**Comment by GitHubRulesOK** [comment]
for command line `noscale`
edit settings to agree
```
PrinterDefaults [
	PrintScale = none
]
```
SumatraPDF uses default printer system but you can adapt some via command line as needed
here I changed **just the printer** and with default no scale expect the default of portrait no need to add any over-rides
`default paper is A4 portrait` default scale setting is now `none` default autorotate is not over-ridden  

![image](https://user-images.githubusercontent.com/12754913/200167347-0ca98555-7385-48ea-8360-9719e41aab32.png)
