### ISSUE TITLE
Opens files from recent files when opening new file 

### ISSUE THREAD

**Issue by rafehq** [sumatrapdfreader/sumatrapdf#3084]
When I click on a new file, sumatrapdf opens the previous 2-4 files from the "recent files" list as well. This goes away after restarting, but keeps happening. This does not happen with any other programs I use.

**Comment by GitHubRulesOK** [comment]
hmm unsure it is just the normal behaviour that open with remember open files `switched on` will reopen tabs as expected or if its different like https://github.com/sumatrapdfreader/sumatrapdf/discussions/3030

```
It is possible to over-ride sessions to false and keep page history for opening single files
by setting in current pre-release this combination

```
RememberOpenedFiles = true
RememberStatePerDocument = true
RestoreSession = false
```

**Comment by rafehq** [comment]
Thank you! It's definitely not keeping sessions open as sumatrapdf is still open when I open the new files, and it reopens existing files, and it also does not open tabs but instead new windows. I had not been able to find session #3030 before, but that seems to be the exact same problem. I will try the fixes there. Thanks for letting me know!

**Comment by dallinghamdpi** [comment]
I see this behaviour when double-clicking on a file to open it.  Right-clicking and choosing "Open" is okay, as is opening a file from the "File" menu in Sumatra.

**Comment by GitHubRulesOK** [comment]
@dallinghamdpi 
check-out todays latest pre-release
portable should perhaps be enough for testing (3.5.15545 should be up soon but I see 15510! at https://www.[sumatrapdfreader.org/prerelease](https://www.sumatrapdfreader.org/prerelease))
there were some recent changes and only pre-release can be "fixed"

**Comment by kjk** [comment]
Use Task Manager (Ctrl + Alt + Del) and see if there are 2 SumatraPDF executables running and one of them runs in admin mode or if they come from 2 different paths on the disk.

If yes, that's the problem. There should only be one executable running.

**Comment by kjk** [comment]
Most likely fixed in [pre-release](https://www.sumatrapdfreader.org/prerelease).
