### ISSUE TITLE
In the footsteps of issues #294 - unexpected effects.

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#309]
The Git commit de6f689037e earlier (noted on Git commit 7fa2a701bf) swam funny moment - on the same test file and https://github.com/sumatrapdfreader/sumatrapdf/issues/294 that we can use both versions of the password - and 123 and 456. :) In principle, not a hindrance, but in terms of security compromise a encryption algorithm, but as a reserve for the forgetful can benefit. :)

**Comment by kjk** [comment]
I don't understand what you're asking for.

**Comment by VictorVG** [comment]
This is just an observation, and I happened to notice this fact. The idea is the ability to use two versions of the password - 123 and 456 to decrypt the same crypto-container indicator of mistakes, but I do not think our country, but the algorithm itself. Perhaps we should be aware that this phenomenon may sometimes manifesting itself - suddenly favor will serve?

**Comment by zeniko** [comment]
@VictorVG: 123 and 456 are two *different* passwords. PDF documents can be protected with one or two passwords: ["user password"](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/mupdf/source/pdf/pdf-crypt.c#L617) for reading and updating the document and ["owner password"](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/mupdf/source/pdf/pdf-crypt.c#L636) for also changing document permissions. Password handling should now work as expected.

**Comment by VictorVG** [comment]
Got a question rented. I did not know about the fact that for the PDF permissible use of two passwords and was surprised by what he saw.
