### ISSUE TITLE
Page turning in blocks (as opposed to full pages)

### ISSUE THREAD

**Issue by jonathan-sung** [sumatrapdfreader/sumatrapdf#3090]
Say you have a PDF open with _Fit to Width_ enabled so only the top half of the page is visible. When you scroll, it incrementally scrolls the page up and down. When you use the left and right arrow keys, the full page is turned (thus you miss the bottom half of the page). My proposal is that a feature should be added so that instead of fully turning a page or incrementally scrolling a page, we strike a balance between the two. When you scroll with this feature enabled, the page does not turn fully to the next page but to the bottom half of the page. And a horizontal guideline appears which indicates the position of the bottom line from where you last read. I think this feature would be useful because I like to use a wireless presentation remote which invokes the left and right arrow keys. It's good for PowerPoint presentations because the slides are already in the shape of the screen, but A4 sheets of paper are more vertical thus if you fit the full page onto the screen, the text is tiny. Zooming in with _Fit to Width_ makes the text legible. However, the page turning feature turns full pages so you're missing the bottom half of the page. Thanks.

**Comment by GitHubRulesOK** [comment]
Hmmm
there are several ways to step though full page using say CTRL+DOWN but each widow can be altered shape/zoom not easy to get one size fits all like say full screen height.

You can for a known case reallocate key strokes or scrollto to step a given amount based on constants but those constants need determination per hardware.

somewhere there was a "brutal scroll" kludge for similar*, but how to invoke in presentation is difficult unless pointer keys can be re-mapped

* https://github.com/sumatrapdfreader/sumatrapdf/issues/1500

**Comment by jonathan-sung** [comment]
Thank you! CTRL+DOWN works perfectly and it's already assigned to my wireless remote! Logitech must have some smart drivers which change the key depending on its application (in this case Sumatra reads CTRL+DOWN, but on Microsoft Word is reads it as LEFT and RIGHT ARROW KEYS) .
