### ISSUE TITLE
Sumatra hangs on opening an EPUB file

### ISSUE THREAD

**Issue by ormax3** [sumatrapdfreader/sumatrapdf#3099]
I tried to open the python documentation EPUB file, but Sumatra program hangs and stops responding with high cpu usage, and I have to kill the process to end it.

The file (6.22 MB) can be found here: https://docs.python.org/3.11/archives/python-3.11.0-docs.epub

Tested on latest stable version `SumatraPDF-3.4.6-64.zip`, Windows 10 21H2.

**Comment by ormax3** [comment]
I understand what epub files are underneath, but how is the case different from chm files..

Sumatra can open and handle similarly packed CHM files just fine (with hundreds/thousands of web pages inside)

For example:

- https://www.python.org/ftp/python/3.10.8/python3108.chm
- https://docs.python.org/3.10/archives/python-3.10.8-docs.epub

Both files represent the entire documentation of python 3.10.8 as a single file, one being CHM and the other EPUB. The chm file opens just fine in Sumatra. This leads me to believe that Sumatra's epub implementation is at fault here. After all, ZIP is a [non-solid](https://en.wikipedia.org/wiki/Solid_compression) archive which allows random access to the individual files without unpacking the whole thing..

(PS: the reason I noticed this issue is because the latest python version 3.11.0 stopped shipping their docs as chm, offering only a zip file of individual HTML files or an epub file, and I prefer a single self-contained file)

**Comment by GitHubRulesOK** [comment]
the  chm is in pre rel 474 fixed pages (3.1.2 was 3521 pages) with fixed hyperlinks (but not all bookmark entries working in 3.1.2)

as xhtml files the epub has 530 top level Files and 10 seconds later those are slowly converted to 9096 pages with new hyperlinks
in 3.12 its less as 7999 pages (pages use a different layout) and works well in both loading and linking terms but not all bookmarks shown and crashed when playing with flowing pages (oh dear, needed to force settings to avoid that)

**The Python Tutorial** (chm page 24 is now epub chapter 24/530 and starts 1/6 mupdf pages) is SumatraPDF physical page 2162 (2133/7999) in epub layout thats the way page breaks need to be recalculated to keep pages in their reading order


Overall, I would say the Chm is the better format. and for the epub then output as PDF would be better, however don't try to convert from SumatraPDF to PDF (takes ages and many links tables etc. would be lost in such processing.

Online conversion to 8596 pages (several sites zamar fails) is reasonable but file gets severely inflated manifold variously about 61 to 62 MB and normal optimisation does not reduce that and compression is not much better (never recommended but extreme is 48.54 MB) so can't upload to show it is fast and effective.

**Comment by ormax3** [comment]
> Overall, I would say the Chm is the better format

agree

---

I ended up [building](https://devguide.python.org/documentation/start-documenting/index.html#building-the-documentation) the latest docs as CHM from source myself. Steps if anyone is interested:

```bat
curl -O -L https://github.com/python/cpython/archive/refs/tags/v3.11.0.zip
7x.exe x cpython-3.11.0.zip
cd cpython-3.11.0\Doc
set "PATH=%PATH%;C:\Program Files (x86)\HTML Help Workshop"
make.bat htmlhelp
start build\htmlhelp\python3110.chm
```

you'll need the [Microsoft HTML Help Workshop](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/microsoft-html-help-downloads), download link seems dead but you can find a [backup](http://web.archive.org/web/20200720082839/https://go.microsoft.com/fwlink/p/?linkid=14188) copy.

**Comment by kjk** [comment]
It opens for me in the latest pre-release. I've added loading in the background so it no longer blocks the main thread.

That being said, that is a large file (8935) so it takes long time to load and layout. That is expected.
