### ISSUE TITLE
Font size x Screen resolution

### ISSUE THREAD

**Issue by luizrobertomeier** [sumatrapdfreader/sumatrapdf#31]
Hello,

First, Thank you for this fast and small software. I'm using Sumatra mainly for ePub files.

I would like to suggest some kind of way to increase the font size. Maybe a window or simple control+ , control- and control 0 to change the size of the font. I am using a big screen with a resolution of 1920x1080 and for me, the font is small. 

Thank you for your attention,
Meier

**Comment by GitHubRulesOK** [comment]
@kjk this historic issue has no further information other than "font" which if it is the content the answer was addressed by zenico, If it is the interface then that is determined by windows.

Either way without further information I suggest this is issue closed as insufficient information forthcoming.

**Comment by kjk** [comment]
agreed, closing
