### ISSUE TITLE
Erroneous display the contents of the last open CHM to PDF tab.

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#310]
Mode MDI, version 3.2, Git commit d3ac2df345 , de6f689037 , [**pre-release 10408**](http://www.sumatrapdfreader.org/prerelease.html) when opening the PDF and CHM documents in multiple tabs when switching between tabs is updated contents only CHM tabs instead of PDF content tab displays the contents of the last CHM or sometimes (it was after minimization the window) instead of the PDF content can be displayed a black screen.

The phenomenon discovered **iNNOKENTIY21** [**original post**](http://forum.ru-board.com/topic.cgi?forum=5&topic=22740&start=1180#7) and [**continue**](http://forum.ru-board.com/topic.cgi?forum=5&topic=22740&start=1180#9)

OS Win7 SP1 x64. The phenomenon demonstrates screenshots taken during the inspection posts **iNNOKENTIY21** (pleas, see document name on tab title):

![1](https://cloud.githubusercontent.com/assets/906886/10327556/5090ed40-6cb1-11e5-85e3-57b47eeaf775.png)

![2](https://cloud.githubusercontent.com/assets/906886/10327558/536f3904-6cb1-11e5-8470-023e44e9d342.png)

![3](https://cloud.githubusercontent.com/assets/906886/10327560/5aa3f980-6cb1-11e5-9997-1d21f52f8e01.png)

![4](https://cloud.githubusercontent.com/assets/906886/10327568/636a0e56-6cb1-11e5-9da8-8eb80ca2fced.png)

![5](https://cloud.githubusercontent.com/assets/906886/10327570/67af0b2e-6cb1-11e5-9ed4-9f2e2e891f2b.png)

**Comment by VictorVG** [comment]
@**zeniko** and @**kjk** 

Big thanks! This issues fixed in to Git ba94c6f6be

I close issues #310

**Comment by VictorVG** [comment]
Sooner we were happy :( - chance I could find a condition when such error is eliminated resurfaced. :( For it was enough to open a pair of double-PDF, and a couple of CHM files. For example chart1.pdf - manual_en.chm - manual_ru.chm - chart1.pdf cause a number of interesting effects:

1) in the tab where you want to output PDF file is rendered CHM manual_en.chm:

![chart1](https://cloud.githubusercontent.com/assets/906886/10355084/1e94c734-6d70-11e5-99fb-b9098319b650.png)

![chm_overlay_pdf](https://cloud.githubusercontent.com/assets/906886/10355089/350247da-6d70-11e5-9ef9-7bae40f3ab47.png)

2) manual_en.chm - manual_ru.chm displayed correctly:

![manual_en](https://cloud.githubusercontent.com/assets/906886/10355104/73ae8d36-6d70-11e5-80cb-7dd4a8c311fd.png)

![manual_ru](https://cloud.githubusercontent.com/assets/906886/10355106/7b0bb856-6d70-11e5-9916-6e14a3ec509a.png)

3) instead of the fourth tab in chart1.pdf see manual_ru.chm:

![chart1_manual_ru](https://cloud.githubusercontent.com/assets/906886/10355112/905fd426-6d70-11e5-8cb6-3659e89fb3c2.png)

4) When will close all previously open tabs in the background see manual_ru.chm:

![manual_en_on_close_all](https://cloud.githubusercontent.com/assets/906886/10355114/983f56da-6d70-11e5-9cda-1d8725a7c631.png)

I suppose that there is an error in the management of buffer rendering of pages that leads him to memorize the image of the last page and CHM overlay the image they overlap the current PDF pages or the main window.

And what's interesting - when I turned on the test set, and DjVu files FB2, the error does not play, but I got Acces Violation (AV) because 222-page DjVu file has not had time to read, and I accidentally tried to use the scroll window:

![av](https://cloud.githubusercontent.com/assets/906886/10355117/9f98d780-6d70-11e5-89f8-35248b33b079.png)

**Comment by VictorVG** [comment]
[**Additional user repoted information:**](http://forum.ru-board.com/topic.cgi?forum=5&topic=22740&start=1180#17)

*Original (Russian)*:

**iNNOKENTIY21**

>а если удалить кэш и SumatraPDF-settings.txt то PDF-CHM-CHM-PDF у меня не проявляется.

>а при наличии кеша и SumatraPDF-settings.txt - глючит. и похоже, и по старой схеме тоже, если закрыть с вкладками. запомнит и при следующем запуске их откроет. то глюк
 
 
>**Добавлено:**
>портабельную 64 мучаю.
 
>стабл 3.0 при этом в установленных.
 
>**Добавлено:**
>да и по старой схеме pdf+chm+chm чет теперь глючит и с удаленным кэшем и файлом настройки.
 
>сам ехе кэшируется, мусор остается...  ?

Translated (English):

**iNNOKENTIY21**

>and if you remove the cache and SumatraPDF-settings.txt the PDF-CHM-CHM-PDF I have not seen.
 
>and in the presence of cache and SumatraPDF-settings.txt - buggy. and it seems, and under the old scheme, too, if you close the tabs. remember for the next time they open. glitch 
 
>**Added:**
>Portability 64 torment.
 
>stabl 3.0 with a set.
 
>**Added:**
>Even under the old scheme pdf + chm + chm Thu buggy and is now with the remote cache and configuration file.
 
>exe itself is cached, the garbage is ...?

**Comment by VictorVG** [comment]
**Addition:**

After commit 6347bfe812 phenomenon I have not played. I wonder what caused it?

**Comment by zeniko** [comment]
@VictorVG: Please test the latest [3.1 prerelease build](http://www.zeniko.ch/#SumatraPDF) compiled from the [rel3.1working branch](https://github.com/sumatrapdfreader/sumatrapdf/tree/rel3.1working) and not the 3.2 prerelease builds from master/trunk. Currently, only the former contain a fix for this issue.

**Comment by VictorVG** [comment]
**@zeniko**: 

Checked on SumatraPDF-dev v3.1.0.10398z her appearance does not play. Settings in use:

```
MainWindowBackground = #80fff200
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
EbookUI [
	FontName = Georgia
	FontSize = 12.5
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = true
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = true
]
ExternalViewers [
]
ShowMenubar = true
ReloadModifiedDocuments = true
FullPathInTitle = false
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
CustomScreenDPI = 0

RememberStatePerDocument = true
UiLanguage = ru
ShowToolbar = true
ShowFavorites = false
AssociateSilently = false
CheckForUpdates = true
RememberOpenedFiles = true
EnableTeXEnhancements = false
DefaultDisplayMode = automatic
DefaultZoom = fit page
WindowState = 2
WindowPos = 558 0 803 1040
ShowToc = true
SidebarDx = 0
TocDy = 0
ShowStartPage = true
UseTabs = true
```
. Just could not reproduce this phenomenon in the assembly rel3.1working Git commit 7292c98dc9 regardless of the preset - I tested a set of default settings, as well that the use that I:
```
MainWindowBackground = #80fff200
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = false

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
EbookUI [
	FontName = Georgia
	FontSize = 12.5
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = false
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]
ExternalViewers [
]
ShowMenubar = true
ReloadModifiedDocuments = true
FullPathInTitle = false
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
	PrintAsImage = false
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
CustomScreenDPI = 0

RememberStatePerDocument = true
UiLanguage = ru
ShowToolbar = true
ShowFavorites = false
AssociateSilently = false
CheckForUpdates = true
RememberOpenedFiles = true
EnableTeXEnhancements = false
DefaultDisplayMode = automatic
DefaultZoom = fit page
WindowState = 2
WindowPos = 558 0 803 1040
ShowToc = true
SidebarDx = 196
TocDy = 0
ShowStartPage = true
UseTabs = true
```
To test the configuration of a specially assembled both x86 and AMD64 - here the phenomenon under investigation.

**Comment by VictorVG** [comment]
Who decided to double-check the hypothesis of an error and your settings as an experiment changed settings:

ReuseInstance = false -> true
RestoreSession = false -> true

As a result, version 3.2 Git-6347bfe812 got Access Violation, although at different times - for the x64 version of AV in ntdll.dll arose in the time of recovery of the session:
```
SessionData [
	[
		TabStates [
			[
				FilePath = chart1.pdf
				DisplayMode = continuous
				PageNo = 1
				Zoom = fit page
				Rotation = 0
				ScrollPos = -1 -1
				ShowToc = false
			]
			[
				FilePath = manual_en.chm
				DisplayMode = single page
				PageNo = 1
				Zoom = 100
				Rotation = 0
				ScrollPos = 0 0
				ShowToc = false
			]
			[
				FilePath = manual_ru.chm
				DisplayMode = single page
				PageNo = 1
				Zoom = 100
				Rotation = 0
				ScrollPos = 0 0
				ShowToc = false
			]
			[
				FilePath = test.pdf
				DisplayMode = continuous
				PageNo = 1
				Zoom = fit page
				Rotation = 0
				ScrollPos = -1 -1
				ShowToc = false
			]
			[
				FilePath = chart1.pdf
				DisplayMode = continuous
				PageNo = 1
				Zoom = fit page
				Rotation = 0
				ScrollPos = -1 -1
				ShowToc = false
			]
			[
				FilePath = manual_en.chm
				DisplayMode = single page
				PageNo = 1
				Zoom = 100
				Rotation = 0
				ScrollPos = 0 0
				ShowToc = false
			]
			[
				FilePath = manual_ru.chm
				DisplayMode = single page
				PageNo = 1
				Zoom = 100
				Rotation = 0
				ScrollPos = 0 0
				ShowToc = false
			]
			[
				FilePath = test.pdf
				DisplayMode = continuous
				PageNo = 1
				Zoom = fit page
				Rotation = 0
				ScrollPos = -1 -1
				ShowToc = false
			]
		]
		TabIndex = 8
		WindowState = 2
		WindowPos = 558 0 803 1040
		SidebarDx = 196
	]
]

```

![x64_av](https://cloud.githubusercontent.com/assets/906886/10408075/95b2438a-6efd-11e5-892b-53e99f70c86c.png)

```
SumatraPDF v3.2 x64 Git-6347bfe812 - AV then reopen last session

Exception on address  0x00000000777C4FD0 (ntdll.dll) in to SumatraPDF-3.2-x64.exe: 0xC0000005
Access Violation on write in to address 0x0000000000060F6A.

DLL name         :	ntdll.dll
DLL version      :	6.1.7601.18933
Exception code  :	c0000005
Exception offset:	0000000000054fd0
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
Additional info 1:	bab8
Additional info 2:	bab86e36b300dc69d20a09f7205b4ea7
Additional info 3:	a782
Additional info 4:	a7820bd09e38dc0b16ba7753694df725
```
x86 does not render a final PDF tab (actually hatched white background) and after a while when you try to close it came to the AV GdiPlus.dll:

![x86_av](https://cloud.githubusercontent.com/assets/906886/10408078/a071456e-6efd-11e5-9250-a078903d7ec9.png)

![stak](https://cloud.githubusercontent.com/assets/906886/10408079/a8f71c68-6efd-11e5-980f-2bef01001683.png)

![perfomance](https://cloud.githubusercontent.com/assets/906886/10408112/25900834-6efe-11e5-9853-cc1544d1538a.png)

```
SumatraPDF v3.2 x86 Git-6347bfe812 - AV then close in to gdiplus.dll v6.1.7601.18946

Exception on address 0x6DDD1FFF (GdiPlus.dll) in to SumatraPDF-3.2.exe: 0xC0000005:
Access Violation on write in to address 0x009C0FB8.

Exception code  : c0000005
Exception offset: 000a1fff
OS version:	6.1.7601.2.1.0.256.1
Language:	1049
Additional info 1:	cc41
Additional info 2:	cc4107a1fe3e5b4b94ffaad134c2d381
Additional info 3:	cc41
Additional info 4:	cc4107a1fe3e5b4b94ffaad134c2d381

Stak dumped use Process Hacker v2.37 (r6242), kernel-mode driver KProcessHacker.sys is running:

TID 6468:

0, ntoskrnl.exe!PoStartNextPowerIrp+0x17e7
1, ntoskrnl.exe!KeWaitForMultipleObjects+0xf5d
2, ntoskrnl.exe!KeWaitForMutexObject+0x19f
3, ntoskrnl.exe!ExAcquireSharedStarveExclusive+0x30f
4, ntoskrnl.exe!NtQuerySystemInformation+0x5a8a
5, ntoskrnl.exe!NtQuerySystemInformation+0x50d9
6, ntoskrnl.exe!NtQuerySystemInformation+0x2ecf
7, ntoskrnl.exe!KeSynchronizeExecution+0x3a23
8, ntoskrnl.exe!ZwUnlockFile+0x150
9, ntoskrnl.exe!IoCreateController+0x386
10, ntoskrnl.exe!IoRegisterFsRegistrationChangeMountAwareEx+0x255b1
11, ntoskrnl.exe!EtwSetInformation+0x2d78a
12, ntoskrnl.exe!KeSynchronizeExecution+0x3e12
13, ntoskrnl.exe!KeSynchronizeExecution+0x298a
14, GdiPlus.dll!GdipCreateSolidFill+0x5afc5
15, GdiPlus.dll!GdipCreateSolidFill+0x5afc5 (No unwind info)
16, GdiPlus.dll!GdipCreateSolidFill+0x5b385 (No unwind info)
17, GdiPlus.dll!GdipCreateSolidFill+0x5b73a (No unwind info)
18, GdiPlus.dll!GdipCreateSolidFill+0x7020e (No unwind info)
19, GdiPlus.dll!GdipCreateSolidFill+0xfc77 (No unwind info)
20, GdiPlus.dll!GdipCreateSolidFill+0xfd8b (No unwind info)
21, GdiPlus.dll!GdipCreateSolidFill+0x10e21 (No unwind info)
22, GdiPlus.dll!GdipFillPath+0x112 (No unwind info)
23, SumatraPDF-3.2.exe+0x16a942 (No unwind info)
24, SumatraPDF-3.2.exe+0x16b105 (No unwind info)
25, user32.dll!gapfnScSendMessage+0x332 (No unwind info)
26, user32.dll!GetDC+0x52 (No unwind info)
27, user32.dll!GetThreadDesktop+0x185 (No unwind info)
28, user32.dll!GetThreadDesktop+0x1e1 (No unwind info)
29, ntdll.dll!KiUserCallbackDispatcher+0x2e (No unwind info)
30, SumatraPDF-3.2.exe+0x1b1af (No unwind info)
31, user32.dll!gapfnScSendMessage+0x332 (No unwind info)
32, user32.dll!GetThreadDesktop+0xd7 (No unwind info)
33, user32.dll!GetThreadDesktop+0x185 (No unwind info)
34, user32.dll!GetThreadDesktop+0x1e1 (No unwind info)
35, ntdll.dll!KiUserCallbackDispatcher+0x2e (No unwind info)
36, user32.dll!gapfnScSendMessage+0x332 (No unwind info)
37, user32.dll!GetCursor+0x2ff (No unwind info)
38, user32.dll!GetCursor+0xa4 (No unwind info)
39, user32.dll!GetCursor+0x1a9 (No unwind info)
40, user32.dll!gapfnScSendMessage+0x332 (No unwind info)
41, user32.dll!GetThreadDesktop+0xd7 (No unwind info)
42, user32.dll!GetWindow+0x3f0 (No unwind info)
43, user32.dll!SetKeyboardState+0xbbd (No unwind info)
44, user32.dll!DialogBoxIndirectParamAorW+0xf7 (No unwind info)
45, user32.dll!SoftModalMessageBox+0x757 (No unwind info)
46, user32.dll!SoftModalMessageBox+0xa33 (No unwind info)
47, user32.dll!MessageBoxTimeoutW+0x52 (No unwind info)
48, user32.dll!MessageBoxExW+0x1b (No unwind info)
49, user32.dll!MessageBoxW+0x18 (No unwind info)
50, SumatraPDF-3.2.exe+0x1b8af (No unwind info)
51, RockallDLL.dll!ZONE_HEAP::`default constructor closure'+0xb554 (No unwind info)
52, ntdll.dll!RtlKnownExceptionFilter+0xb7 (No unwind info)
53, ntdll.dll!RtlInitializeExceptionChain+0x36 (No unwind info)
```

**Comment by VictorVG** [comment]
v3.2 Git-6fefd20607 x64 - another AV on same test.

**Comment by VictorVG** [comment]
Now I gather a look. And then my system (C2D E8500 / 8 Gb DDR3-1333) does not have time for you. :)

**Comment by VictorVG** [comment]
**@kjk**

Big thanks! My test is success, bug is fixed in to Git commit d0f221b8f3.

**Comment by kjk** [comment]
@VictorVG Thanks for verifying the fix.

**Comment by VictorVG** [comment]
It's my pleasure. :) This is a thank you and a low bow to you for your work. This error does not have enough blood to drink.
