### ISSUE TITLE
Page in PDF doesn't render

### ISSUE THREAD

**Issue by majkaz** [sumatrapdfreader/sumatrapdf#3101]
In recent files from the same organisation, the first page doesn't render for some reason. Other applications do show it (Acrobat DC, js viewer). Something changed recently, in the past the files worked just fine in Sumatra PDF Reader.  

From the original info:
Producent PDF: Microsoft® Word 2021
PDF Version: 1.7

Old files without this problem show:
Producent PDF: Microsoft: Print To PDF
PDF version: 1.7

The attached file is just the first page alone (split out using coherent pdf) and for this reason, shows invalid digital signature.

[err.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/10012331/err.pdf)

Original file (4MB) can be downloaded from [this link](https://nen.nipez.cz/file?id=1470695745)

**Comment by GitHubRulesOK** [comment]
Hmm

<rant> I despair where pdf developments are going they are no longer readable by humans (simply designed for androids consumption.) </end rant>

so its a PDF/2A "standardised" <</Linearized "signed" pdf 

not just a simple printer or human passable document like say a book or report , clearly placing a signature in that fashion is confusing to mupdf engine it reports the image on page 1 is invalid so cannot display page but clearly other apps don't see that problem !

**Comment by kjk** [comment]
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=706402

**Comment by GitHubRulesOK** [comment]
related but not identical issue as both are adulterated signed files with JPX designated signed fields
![image](https://user-images.githubusercontent.com/12754913/219957106-1211a24e-65cc-4603-b21a-c7bffa2d6ab8.png)

**Comment by kjk** [comment]
fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/60eb60f436ca6d3a05f78144f2110ba6bddbafbd
