### ISSUE TITLE
Bookmark behavior

### ISSUE THREAD

**Issue by AlMacd17** [sumatrapdfreader/sumatrapdf#3102]
I am writing a book with chapters and sections. Bookmarks are displayed. If I am reading in a section and click on that section in the bookmarks, nothing happens. I would often like to go to the top of the section. Nothing would be lost by adding that facility.

**Comment by GitHubRulesOK** [comment]
outline bookmarks are embedded inside the pdf code (encoded several ways) some work better than others
 thus need a binary editor like acrobat pro or a command line tool like pdftk or cpdf etc.
Some will work others may not if not built correctly (there is one type that may be misread to top/bottom edge of page)

SumatraPDF keeps favourite pages in settings file for page level viewer navigation across all formats that does not edit the source files.

**Comment by kjk** [comment]
Can say anything without access to the file that shows the problem.
