### ISSUE TITLE
opening previous session (thank you)

### ISSUE THREAD

**Issue by scobiem** [sumatrapdfreader/sumatrapdf#311]
Thank you for the pre-released feature that lets you open the files of your previous session and go to the previous page/file locations. That is fantastic.

The only thing I could add as a feature request would be to be able to save a "project" or "session" that specifies this set of files and page locations. So I might have a set of files open dealing with some subject, then leave that and open a different set of files on a different subject. I could change/resume work/reading on a set of files, depending on the subject. It's a real scenario for me.

Thanks.
S. Smith

**Comment by kjk** [comment]
We don't have plans to implement such feature. Too much work, not enough people would use it.
