### ISSUE TITLE
Problem with Command-line-arguments V 3.4.6

### ISSUE THREAD

**Issue by AlexSTHfg** [sumatrapdfreader/sumatrapdf#3129]
Hi,
i have a problem with command-line-arguments or maybe i use it incorrect.
Following situation:

Situation 1:
PDF-1 is opened
PDF-2 is opened
PDF-3 is opened
Now i have 3 tabs
PDF-2 i scroll to page 5 (only a example).
I don't close anything.
I enter the command line to open PDF-2 at page 2.
What happens: 
Opened PDF-2 jump from page 5 to page 2
Everything fine.

Situation 2:
PDF-1 is opened
PDF-2 is opened
PDF-3 is opened
Now i have 3 tabs
PDF-2 i scroll to page 5 (only a example).
I close sumatra with main close icon (not with small cross at each pdf).
I enter the command line to open PDF-2 at page 2.
What happens: 
Sumatra opens again with all 3 PDFs and tab with PDF-2 is selected but page don't jump to 2, it is already page 5.
Something is not correct because i want to open page 2, not 5 (5 was opened before i close sumatra)

Situation 3:
PDF-1 is opened
PDF-2 is opened
PDF-3 is opened
Now i have 3 tabs
PDF-2 i scroll to page 5 (only a example).
I select PDF-3, which page is not important.
I close sumatra with main close icon (not with small cross at each pdf).
I enter the command line to open PDF-2 at page 2.
What happens: 
Sumatra opens again with all 3 PDFs and select tab with PDF-2 (before closing tab 3 was selected) but page don't jump to 2, it is already page 5.
Something is not correct because i want to open page 2, not 5 (5 was opened before i close sumatra).

Did you know, what i can do to solve this or it is a bug?
I try to use "-reuse-instance" or without it, but nothing changed for me.

A second question is, is there a way to add a command, like this:
Open a PDF but when PDF is already open (for example at page 5), open the same PDF once again but for example at page 10?
So i want to decide by command line, use a already opened PDF and jump to page x or open the PDF once again and jump to a different page.
I hope you understand my situation and i hope you can help me

**Comment by GitHubRulesOK** [comment]
much depends on several items so for example I close SumatraPDF session and ask

`sumatrapdf -reuse-instance -page 5 C:\Apps\PDF\poppler\#33.pdf` it only opens the one target correctly at page 5 but that's because I have a setting from a previous question/answer to `RestoreSession = false` and `ReuseInstance = false` thus ignores the previous session.

so resetting to `RestoreSession = true` and `ReuseInstance = true` I find if I change to page 10 and close on page 10 then it without -page (`sumatrapdf -reuse-instance C:\Apps\PDF\poppler\#33.pdf`) it goes to page 10 of that one of 3 files but if I again ask as above `sumatrapdf -reuse-instance -page 5 C:\Apps\PDF\poppler\#33.pdf` then it also opens at page 10 because thats the over-ride thus have now its active a second call `sumatrapdf -reuse-instance -page 5 C:\Apps\PDF\poppler\#33.pdf` and it **on second call** changes from 10 to 5 

Its very similar to DDE 1st call is to invoke the session settings and a second singular call will then action the reuse, basically SumatraPDF session needs to be active to respond. One way round that could be

`"C:\Program Files\SumatraPDF\SumatraPDF.exe" & "C:\Program Files\SumatraPDF\SumatraPDF.exe" -reuse-instance -page 5 C:\Apps\PDF\poppler\#33.pdf`

**Comment by AlexSTHfg** [comment]
For me the best way would be, when i can open a PDF with page and add a command, that this PDF file should open once again, when it is already opened. That means, the PDF-1 is at page 2 and PDF-1 again (second tab in sumatra) is at page 5.
Is there a way to add this as command line, that means "open PDF again, no matter if it is already opened"?

**Comment by GitHubRulesOK** [comment]
@AlexSTHfg 
that's not normal behaviour for tabbed interface, open as separate view windows needs old behaviour (before tabs) so as many separate pages as needed then -reuse-instance will  (should) work on the last opened of viewer windows.  

For new tabbed behaviour it is possible to emulate same by open a new separated tab in a -new-window, and keep changing the new window tab.  

What you need can probably be done via DDE which is the way SummatraPDF is internally comand controlled, so open file, open copy of file, alter last loaded filename.

From Command line tabs are not addressable, they can be dragged around in user order, it is generally the last filename that is addressed. So closest command line method per desire is have two tabs already set to be opened by remember the session, then address the later of the two.

**Comment by AlexSTHfg** [comment]
But for my understanding, Sumatra can work with same PDF files in different tabs.
Because when i open a pdf (by double click) and after this i press the button for open file dialog in sumatra and i select the same opened file again, it creates a second tab with this pdf.
And this is, what i want to do with command line argument...

![2022 11 25-12_10_19-001](https://user-images.githubusercontent.com/91115065/203974365-7c9d5609-ed7c-4e49-a42e-3c2360339150.png)
![2022 11 25-12_10_47-001](https://user-images.githubusercontent.com/91115065/203974371-58f5ae55-d7ef-4611-9875-c219afcfe83d.png)

**Comment by GitHubRulesOK** [comment]
Hmmm
unsure if that was possibly closed as a previous bug ! that when calling the command line filename it would add an unwanted second copy. So perhaps older version(s) may have different behaviour. Not got DDE active to see if that behaves different to CLI but based on the fact that GUI can open 2 then suspect DDE can also open 2

**Comment by AlexSTHfg** [comment]
Ok, i never used DDE. 
Did you have a description, how to use this?
Normally i use Sumatra from my own developed application to open pdf files.
I use ShellExecute command to open the sumatra exe file and attach the command line arguments for filename and page...
I don't know if this works with DDE and how it works...

**Comment by GitHubRulesOK** [comment]
Hmm a while since done similar but you can use DDE from command line via an exe (its fiddly until you understand it also requires SumatraPDF to be active thus both serving and listening) search DDE in above issues **both open and closed**

**Comment by kjk** [comment]
Probably a corner case of interaction between restoring a session and opening the same file from cmd-line.

Since you're a programmer and SumatraPDF is open-source, you can track down the issue and submit a fix.

I don't have the bandwidth to investigate this.
