### ISSUE TITLE
Suggestion: Coloring text elements differently.

### ISSUE THREAD

**Issue by 200901002** [sumatrapdfreader/sumatrapdf#3132]
# Currently 

changing the background and foreground color changes whole document. Would it be possible to color different elements like **Title**, **subtitle** differently?

# Changing FG and BG
![image](https://user-images.githubusercontent.com/112180722/203904204-c8e071ae-0f3b-405a-a5ed-17f5c673ba6d.png)

![image](https://user-images.githubusercontent.com/112180722/203904223-dd85262e-17a3-424f-aaa6-93fcae6ac484.png)

# Suggested change
![image](https://user-images.githubusercontent.com/112180722/203905500-88f46af3-85eb-4d7c-ac6a-f4f5c73766e8.png)

Now the Heading is colored with purple and numbers in orange, plain text in white.

Is this is feature feasible?

**Comment by GitHubRulesOK** [comment]
such changes are not easy in Acrobat PRO or other full document editors as it means locating every single letter or block of characters of that font and in many cases that font may appear on many pages so it would be totally impracticle especially for fonts that are encrypted most are compressed and encoded too.

So SumatraPDF Viewer uses the existing colours **without any alterations,** the reversing of ALL screen colours is easy the reversal or change of one or more items is not easy, for that you need a word processing editor.
