### ISSUE TITLE
[Feature Request] Discuss Linux port

### ISSUE THREAD

**Issue by vgturtle127** [sumatrapdfreader/sumatrapdf#314]
I saw Mac is in the works, it should be somewhat trivial (assuming everything goes well) to port to Linux. If anybody has any reason why we couldn't port it or something, we can note it here and add it to the portability issues.

I am not expecting this in one day or anything, just would like to see my favorite, most secure PDF reader get a great Linux port. :smile:

**Comment by kjk** [comment]
We don't have plans for Linux. See https://github.com/sumatrapdfreader/sumatrapdf/wiki/Why-only-Windows%3F.

**Comment by vgturtle127** [comment]
Is the Mac branch able to compile on a Mac, and does it work?

**Comment by kjk** [comment]
No, there's almost nothing there.

**Comment by vgturtle127** [comment]
Oh, alright. So what parts are Win32-specific?
