### ISSUE TITLE
Sumatra looses session/open tabs on system crash

### ISSUE THREAD

**Issue by rouilj** [sumatrapdfreader/sumatrapdf#3150]
Hello:

I am using sumatra 3.2 64 bit on windows 10. I have "RestoreSession = true" in the config file.

If I exit and restart sumatra via menu or hotkey the session is restored on restart.

If sumatra was running when the system crashed (or the battery dies unexpectedly), no pdf's
are restored.

Looking at the config file:

  SessionData [
  ]

is empty, but the FileStates array is full with many more entries than I had open documents.
The FileStates array does include all the files I had open at the time of the crash.

What do I need to do to get the session state preserved when sumatra is abruptly
shutdown. All my browsers and other programs are able to handle this unfortunate
series of events.

Thanks for your help.

**Comment by GitHubRulesOK** [comment]
I think that was introduced after 3.2 during development 2020-07-05 Sun was just before 3.3  so should not happen in more recent versions
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2398#:~:text=Sumatra%20crashes%20or%20get%20killed%20by%20Windows
old earlier suggestion was making dated backup https://github.com/sumatrapdfreader/sumatrapdf/discussions/3045

**Comment by rouilj** [comment]
Thanks. I have updated (didn't realize my version was that old). I'll close this out.
