### ISSUE TITLE
Bookmark issue

### ISSUE THREAD

**Issue by hongy19** [sumatrapdfreader/sumatrapdf#3156]
For this [pdf file](https://file.io/tmDIqNwaX55l),  3.3.3-64 could display bookmark but 3.4.6-64 couldn't. The bookmark could  also be displayed in Acrobat reader and chrome.

**Comment by GitHubRulesOK** [comment]
[LaTeX入门-刘海洋-2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/10145610/LaTeX.-.-2.pdf)

Works fine in current version so nothing to change
![image](https://user-images.githubusercontent.com/12754913/205422645-50266cda-d197-40ad-bbf8-3e2a721b5c91.png)

**Comment by GitHubRulesOK** [comment]
@hongy19 If there are ANY attachments in the file like XML in a Facture Invoice they are classified as part of the Outline thus included at the end of the attached bookmarks listing. It would be similar to a degree when two pdfs are wrapped in one the overall contents index is shown but not those content locations that are classed as "Named Destinations"

![image](https://user-images.githubusercontent.com/12754913/209365809-04288529-cbe3-41c5-b796-4d2a139ec69f.png)
![image](https://user-images.githubusercontent.com/12754913/209366021-97f07a92-8f7e-49eb-a36a-4d86e13c8e79.png)

**Comment by hongy19** [comment]
> 

Thanks. It is clear that this pdf file has some issues since bookmarks is displayed correctly after I repair it with ghostscript.

But do we know why 3.3.3 version could display bookmarks even pdf file is broken?

**Comment by GitHubRulesOK** [comment]
@hongy19 
SumatraPDF is wrapped around MuPDF which can work around some broken file issues but itself changes as to what is tolerated (currently trying to work out why SumatraPDF does show objects that other pdf viewers will NOT ! 🙂 its a temporary bonus ?)

**Comment by hongy19** [comment]
@GitHubRulesOK  thanks so much! By the way SumatraPDF is really great PDF tool and thanks for your excellent work
