### ISSUE TITLE
Why Sumatra open same file in another new page tab?

### ISSUE THREAD

**Issue by balmydrizzle** [sumatrapdfreader/sumatrapdf#3162]
The scenario: I open Sumatra. There's a opened file, e.g. 'playbook_aid.pdf', which is my last- opened file and continuing reading it. Later, when I doulbe click 'playbook_aid.pdf' in windows explorer (Just to be back to Sumatra quicker to continue my reading). Sumtra creates another page tab with this same again. Doesn't Sumatra remeber what files it has opened?

**Comment by kjk** [comment]
As a general rule, if you have a file foo.pdf opened in sumatra and you open it again, sumatra will go to the already opened tab.

There are cases where that logic doesn't work e.g. mixing admin and non-admin sumatra processes.

Most likely you're starting non-admin Sumatra process and then launching an admin version (by double-clicking from admin process like explorer)
