### ISSUE TITLE
.djvu files do not open or do not render

### ISSUE THREAD

**Issue by wstaelens** [sumatrapdfreader/sumatrapdf#3163]
These [djvu](https://wiki.genealogy.net/Geschichte_des_Reserve-Infanterie-Regiments_Nr._203) files do not open or do not render.

I'm using Sumatra v3.4.6 64bit on Windows 10. It also failed in version v3.3.3 64bit.

**Comment by GitHubRulesOK** [comment]
thy are chimeras same as google docs pdf they are a web deceipt of smoke and mirrors its not a djvu file its an encrypted single page in a viewer or jpeg reproductions 
![image](https://user-images.githubusercontent.com/12754913/205920968-96fb21dd-1b80-4031-a1a2-c43f8432be5f.png)

**Comment by GitHubRulesOK** [comment]
it downloads as a djvu sheet but here it is in the developers own viewer, 
![image](https://user-images.githubusercontent.com/12754913/205923430-64bf9332-0058-4b31-9ea2-58f67becca06.png)

**Comment by wstaelens** [comment]
ok, so even with internet connection for viewing it not in browser but in sumatra it will never work? Sumatra is unable to download these files because it doesn't have a full link, only relative link to file which sits on the webserver?

**Comment by GitHubRulesOK** [comment]
you could try download each sheet and then attempt rebundling but it would be easier to scrape all the jpegs as more universal if less compact then try reconvert the files to djvu or in a zip use like a CBZ in sumatraPDF

**Comment by kjk** [comment]
Those are not .djvu files
