### ISSUE TITLE
Numerical addition in page number box.

### ISSUE THREAD

**Issue by 200901002** [sumatrapdfreader/sumatrapdf#3167]
# Feature suggestion

Let's say in the document there is offset in "Book page number" and "Pdf page number", If we want to add that offset, We need to perform numerical addition in **page number box**.  So kindly try to add this feature.

![image](https://user-images.githubusercontent.com/112180722/206639935-4a6d3fa7-2b33-4926-9aca-f2587011e74b.png)

**Comment by GitHubRulesOK** [comment]
Hmm those numbers can be letters so it would be complex to add v to ii to go to vii much about PDF is Latin-American in the case above good old school maths suggests type 223 to jump forward 20 or 219 for +16 you can actually write your cmd to ask how many to add or subtract by export current page and the redirect that many plus or minus, its fiddly but doable using windows cmd set /p and set /a on old forum there was an example how to jump a set number tha could be addapted but simpler to write a custom one based on current behaviours.

extrernalvierwers call batchfile with current page number then ask user how many the add or subtract then recall pdf with tha new page number so about half  a dozen lines may possibly condensed into just a few. however am late for my funeral so no time to write one today.

**Comment by kjk** [comment]
Don't quite understand the request. You want to be able to enter "20+13" and Sumatra do the addition and go to 33? Not sure how useful that would be for most people.

**Comment by GitHubRulesOK** [comment]
@200901002 

Ok here it is , just for you (took 45 mins to test !!)

Jump.cmd
--

```
@echo off&Title=PageJumper&color 9F&mode con cols=56 lines=8
setlocal ENABLEDELAYEDEXPANSION
set "num=" &set "jump="&set "result="
rem echo %1 "%~2"
if .%2==. goto help
set /a "num=%1"
if %num%==0 goto help
echo/ &echo  Current page is %num%
echo  Enter +## for jump forward pages and -## for jumpback
echo  For example current is %num% so + 10 is forward by 10
echo  out of possible range can NOT work so +10000 says put
echo/
set /p "jump=? Remember include + or - ? "
set /a "result=%num% %jump%"
"C:\Program Files\SumatraPDF\SumatraPDF.exe" -reuse-instance -page %result% "%~2"
exit /b

:help
echo need a number and filename
pause
:eof
```

to use it add
```
ExternalViewers [
	[
		CommandLine = "C:\path to wherever\jump.cmd" %p "%1"
		Name = send Pages to &Jump
	]
]
```
Shortcut in English will be <kbd> Alt </kbd><kbd> F </kbd><kbd> J </kbd>
![image](https://user-images.githubusercontent.com/12754913/217434324-cf81813a-23ea-40a1-a3a8-b72edb3547f9.png)

***So 21 Jumps to 41*** if you use +20

![image](https://user-images.githubusercontent.com/12754913/217434372-fc5a0571-4a30-4fc7-9156-45e3ac726945.png)
