### ISSUE TITLE
Failed to build: "panic: exit status 128" (main.runExeMust)

### ISSUE THREAD

**Issue by vsr3y** [sumatrapdfreader/sumatrapdf#3171]
I tried to build Sumatra following [this guide](https://www.sumatrapdfreader.org/docs/Build-system) by issuing just `doit.bat` as well as with `-build-docs`, `-build-pre-rel`, and `-build-release` but they all return the same error below. Am I doing something wrong?

```
C:\sumatrapdf>doit.bat

C:\sumatrapdf\do>go run .
Current directory: C:\sumatrapdf
> C:\Program Files\Git\cmd\git.exe log --oneline
Finished in 47.8109ms
panic: exit status 128

goroutine 1 [running]:
github.com/kjk/common/u.Must({0x8a7100?, 0xc0000a3420?})
        C:/Users/USERNAME/go/pkg/mod/github.com/kjk/common@v0.0.0-20220127201717-eb74a6a7c4ae/u/base.go:11 +0x3a
main.runExeMust({0x7e0ba4?, 0x2?}, {0xc00019fc90?, 0x34dea7?, 0x40?})
        C:/sumatrapdf/do/util.go:57 +0xa3
main.getGitLinearVersionMust()
        C:/sumatrapdf/do/git.go:9 +0x6c
main.detectVersions()
        C:/sumatrapdf/do/build.go:114 +0x1d
main.main()
        C:/sumatrapdf/do/main.go:240 +0x90a
exit status 2
```

**Comment by kjk** [comment]
You don't have git installed (in PATH).

But that's not really what you want to use. To compile Sumatra follow https://www.sumatrapdfreader.org/docs/Contribute-to-SumatraPDF i.e.: open vs2022/SumatraPDF.sln in Visual Studio, compile and run.
