### ISSUE TITLE
increase and decrease line height

### ISSUE THREAD

**Issue by bung87** [sumatrapdfreader/sumatrapdf#3177]
not sure it's supported in other pdf reader or not.

**Comment by GitHubRulesOK** [comment]
Not really possible in any PDF the text is generated hundreds of different ways per page, say for example we have a Line With the Authors name, it could look like this, so If you rewrite the 15 for this line as I have to taller 30 it will run over the line above. Hou would need to calculate every single letter to check if it may impact any ink aroun it. That massive set of calculations per page would generate a very very slow response on screen.

`BT +0.50 Tc -1.4 Tw 999 TL /F2 1 Tf 15 001 10. 30 200.000 440.000 Tm [(Jane A)600(usten)] TJ ET`

**Comment by bung87** [comment]
Thanks for response, I understand now, I am reading some pdfs , text are too dense for me.

**Comment by GitHubRulesOK** [comment]
Hmm 
best I can suggest is consider if plain text extraction (with or without images) is of value for use in Word Processor for restyling but can be variable results as each line is separate, thus no paragraphs without edits of the line endings.

OR use a visual Editor like Tracker Xchange or Foxit, they should alter text as blocks but you need space on each page as text cannot flow from page to page.

**Comment by bung87** [comment]
Thanks for the solution!

**Comment by kjk** [comment]
As @GitHubRulesOK said, in PDF format it's not possible to change line height.
