### ISSUE TITLE
PDF Comments are misplaced/disappear

### ISSUE THREAD

**Issue by craffael** [sumatrapdfreader/sumatrapdf#318]
Open the [PDF File](https://www.dropbox.com/s/jw29l8fn1n49b9g/pdf_sumatra_error.pdf?dl=0) once with Adobe Reader and once with Summatra PDf.

In Adobe Reader you should see two comments: "co-linear" and "97, 116 (Raymond A.) (Yosida)"

In Summatra 3.0 the "co-linear" comment has completly disappeared whereas the "97, 116 (Raymond A.) (Yosida)" has been moved quite a bit from it's original location.

**Comment by kjk** [comment]
Should be fixed in latest pre-release version: http://www.sumatrapdfreader.org/prerelease.html
