### ISSUE TITLE
Distinction of active and inactive tabs

### ISSUE THREAD

**Issue by davesssn** [sumatrapdfreader/sumatrapdf#3182]
Version: 3.4.6 x64
OS: Windows 11 22H2 x64

When multiple pdf files are opened in Tabs, it is impossible for me to distinguish which tab is active and which are not.
I already tried different Windows Styles, including the High Contrast options, but I was not able to change the colours.
In the attached picture can be seen, that the active tab has almost the same colour as the inactive ones.
![Sumatra_Tab_issue](https://user-images.githubusercontent.com/30881452/208466284-c6078202-b39e-409a-87af-81888e173b17.png)

**Comment by GitHubRulesOK** [comment]
related to https://github.com/sumatrapdfreader/sumatrapdf/issues/559

**Comment by kjk** [comment]
Fixed by: https://github.com/sumatrapdfreader/sumatrapdf/commit/4749faf60c6234ff1823b5b50d43c3dce370eca4
