### ISSUE TITLE
Ctrl-Shift-S Save notification persists until closed

### ISSUE THREAD

**Issue by meteorquake** [sumatrapdfreader/sumatrapdf#3184]
If I do Ctrl-Shift-Save it saves the annotations and puts a largish banner at the top saying it has done so ("Saved Annotations to <filename>").
But it stays there over the top part of the document until you manually go up and click the x to remove it, unless it goes eventually.
In my view it should remove itself after about 1.5 secs. If wished it could be given some colour to make its short appearance stand out.
Cheers, David

**Comment by GitHubRulesOK** [comment]
Please check latest pre-release as such changes were recently added to reduce the "persistence" see for example https://github.com/sumatrapdfreader/sumatrapdf/issues/3448

however some instability in annots is addressed today so your test should be say tomorrow using a version AFTER 15545 [https://www.sumatrapdfreader.org/prerelease](https://www.sumatrapdfreader.org/prerelease)

**Comment by kjk** [comment]
Those will now go away after 5 secs https://github.com/sumatrapdfreader/sumatrapdf/commit/7d4a5961f1ae75d91084c7ffac4f3a7cdbd22682
