### ISSUE TITLE
No tables in ePub

### ISSUE THREAD

**Issue by tico-tico** [sumatrapdfreader/sumatrapdf#319]
Hi, everybody.

For me it's a pretty obvious issue, but I couldn't find anything related on the bug list. In short – SumatraPDF instead of showing tables shows lines of text.
You can see it with the test ePub I just made. Firefox ePub plugin shows the table just fine.

https://app.box.com/s/elz0izncy2t8i2572t7a7634q6wfu81i

**Comment by pcdinh** [comment]
This bug occurs in the latest version v 3.1.2 64-bit as well

**Comment by petrasteri** [comment]
Your test ePub file is not available.
You can try to attach it in this GitHub system
