### ISSUE TITLE
Images was not displayed in some .fb2 files, [image] instead

### ISSUE THREAD

**Issue by AndNovAtor** [sumatrapdfreader/sumatrapdf#3196]
Looks like some sort of "regression" or duplicate, anyway.

On "current", for 25.12.2022, release, 3.4.6 [btw, with any 3.4.* <= 3.4.6], I had some strange bug - images in a some .fb2 file was not displayed (in .epub variant of the same "book" images was displayed). Instead, I saw `[image]`
![image](https://user-images.githubusercontent.com/3628514/209481498-44c133a3-9cc1-433c-a8f8-c515b75f5642.png)

I tried "current" prerelease, 15262, and images worked! as usual.

Is it duplicate of #2575 (about base64)? Or something new (still from certain engine version, with few files)?

Again, it's NOT presented in 15262 build
(as 15262 worked, I didn't attached file example, yet...)

**Comment by kjk** [comment]
Nothing I can say without a repro file.

**Comment by AndNovAtor** [comment]
Can I post here TEMP link to a file, that after confirmation I can delete?

**Comment by GitHubRulesOK** [comment]
@AndNovAtor files placed here even for short time get trawled
I suggest email to KJK direct is possibly better

**Comment by AndNovAtor** [comment]
> kkowalczyk
Can I send file directly from my gmail to gmail?

**Comment by AndNovAtor** [comment]
@kjk, Can I send file directly from my gmail to this gmail?
(it's 6.4mb)

**Comment by AndNovAtor** [comment]
btw, if somebody interested in torrent links to files, it has hash _08ff7976dbf0438b898ba3553b4c60948bd4f60f_, there are fb2 files...

**Comment by kjk** [comment]
@AndNovAtor Yes, you can send me the file to kkowalczyk@gmail.com

**Comment by AndNovAtor** [comment]
> @AndNovAtor Yes, you can send me the file

Ok, thank you. I have sent you an email with a sample file

**Comment by kjk** [comment]
I got the file and images are showing in latest pre-release.

That means that the bug is fixed, 3.4.6 has already been released so it's not going to get  this bug fixed.

**Comment by AndNovAtor** [comment]
> That means that the bug is fixed

Still after 3 months 3.4.6 is release version, many people don't know about prerelease version, so why I created this issue - for notice.
~(And if somebody wanted to look for engine difference)~
