### ISSUE TITLE
Bad rendering with older PDF

### ISSUE THREAD

**Issue by atomicthumbs** [sumatrapdfreader/sumatrapdf#3204]
https://accessories.volvocars.com/LegacyCatalog/Pdf/X70_total_FR_GB_NL_DE.pdf

In 3.4.6, opening this PDF results in a majority of the text being invisible. Renders okay in a Chromium-based browser.

Edit: Incorrect link. Here is the version of the PDF that renders incorrectly: https://drive.google.com/file/d/0B1hcMnD6HEm5NEI1OWtFaVpzb0U/view?usp=share_link&resourcekey=0-AO1EG-NyPPUUrFISKBCYtA

**Comment by sergsako** [comment]
Strange to me, I see this PDF correctly in stable SumatraPDF 3.4.6 portable x64 on Win10x64 21H2, as well as in the latest pre-release and two other PDF viewers.
@atomicthumbs  May it be that you use x86 (32-bit) version?

**Comment by GitHubRulesOK** [comment]
I have to agree with @sergsako I used both 3.4.6 portables and current installed pre-release without seeing problems. 
Perhaps you have a faulty download try opening that address in file open but there will be a delay while it trickles through windows trident.
![image](https://user-images.githubusercontent.com/12754913/210437179-21aeb6c3-285f-4c9f-a31d-30ca27f0c443.png)

**Comment by atomicthumbs** [comment]
My mistake, I looked for an online version of the file I'm having trouble with, and found that one, but what I linked is the wrong version. Here is the incorrectly rendering PDF: https://drive.google.com/file/d/0B1hcMnD6HEm5NEI1OWtFaVpzb0U/view?usp=share_link&resourcekey=0-AO1EG-NyPPUUrFISKBCYtA

(Also helpful to have discovered that there is a version that *does* render correctly. I'll update the issue for clarity.)

**Comment by sergsako** [comment]
@atomicthumbs @GitHubRulesOK   Now I see that the (new) PDF is incorrectly rendered by SumatraPDF. The PDF document has some internal errors, please look at the picture about what PDF-XChange Viewer says when opens this PDF
![problems](https://user-images.githubusercontent.com/106967914/210532420-c5cd7eab-1383-4c97-b049-4c00157cd92f.jpg)
However, the recommended re-saving of the document with PDF-XChange Viewer makes the rendering in SumatraPDF even worse.

**Comment by GitHubRulesOK** [comment]
The file has faults and Xchange attempts repair but they are not good enough to fix all the problems, Since there is a perfectly good version from the author site I suggest it is simplest replaced by the good one.

**Comment by sergsako** [comment]
However, I found one more example
[manual.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/10368120/manual.pdf)
The latest SumatraPDF pre-release **cannot render it**. SumatraPDF 3.1.2 and 3.4.6 show everything fine but the interactive elements of the document do not work. MS Edge, PDF-XChange and Master PDF show everything and the interactive buttons work.

**Comment by GitHubRulesOK** [comment]
SumatraPDF does not generally support form structures and those buttons appear to be built as one button on page one then multiple duplicate fields as one per page.

So button 1 works on page 1 but the rest will not

**Comment by sergsako** [comment]
@GitHubRulesOK  May it be a kind of regression in the latest pre-release build version 15264? At least I can look through the whole manual.pdf in the stable SumatraPDF 3.1.2 and 3.4.6, but I can see only the 1st page  with 3.5.15264

**Comment by GitHubRulesOK** [comment]
@kjk certainly seems to be a regression

![image](https://user-images.githubusercontent.com/12754913/211305829-6ded780b-c611-47cf-a9e4-c01434988a61.png)
![image](https://user-images.githubusercontent.com/12754913/211306213-7ac1dc40-caf6-463f-ab22-012dcd2a97af.png)

**Comment by kjk** [comment]
This is a minimized reproduction, only page 2 extracted:

[page2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/10680625/page2.pdf)

**Comment by kjk** [comment]
interesting thing that unicode is correct but glyph is not:
```
    <span font="MAFOFD+HelveticaLinotype" wmode="0" bidi="0" trm="9 0 0 9">
        <g unicode="V" glyph="0" x="296.06" y="742" adv=".953"/>
        <g unicode="o" glyph="0" x="301.9721" y="742" adv=".953"/>
        <g unicode="l" glyph="0" x="307.0112" y="742" adv=".953"/>
        <g unicode="v" glyph="0" x="308.9993" y="742" adv=".953"/>
        <g unicode="o" glyph="0" x="313.4714" y="742" adv=".953"/>
        <g unicode="ΓÇÖ" glyph="0" x="318.5105" y="742" adv=".953"/>
```

**Comment by kjk** [comment]
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=706396

**Comment by GitHubRulesOK** [comment]
@sergsako 
your problem is not there in recent versions 

but OP issue is still there as unconfirmed by MuPDF

**Comment by kjk** [comment]
Seems fixed, I closed mupdf issue as well.
