### ISSUE TITLE
Error reported in Win7: SumatraPDF crashed.

### ISSUE THREAD

**Issue by iTanken** [sumatrapdfreader/sumatrapdf#3212]
![image](https://user-images.githubusercontent.com/23544702/211254371-6617d35a-24f4-486d-b2ba-f7d45cc2dac8.png)

BuiltOn: 2022-06-08
Type: static
Ver: 3.4.6 64-bit
Git: 7a19622d5ad35702dad2694cca4873693e88bc4e (https://github.com/sumatrapdfreader/sumatrapdf/commit/7a19622d5ad35702dad2694cca4873693e88bc4e)
OS: Windows 7 build 7600 64-bit
Number Of Processors: 4
Processor: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Physical Memory: 3.91 GB
Commit Charge Limit: 7.83 GB
Memory Used: 56%

### crashinfo

[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/10370968/sumatrapdfcrash.txt)
[sumatrapdfcrash.dmp.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/10370972/sumatrapdfcrash.dmp.zip)

**Comment by GitHubRulesOK** [comment]
try **without -silent** it should not be needed and **watch for an error message**
 but ensure your settings are "quoted" `-print-settings "1-3,5,10-8,odd,fit,bin=2"`

**Comment by iTanken** [comment]
> try **without -silent** it should not be needed and **watch for an error message** but ensure your settings are "quoted" `-print-settings "1-3,5,10-8,odd,fit,bin=2"` but worst of all sumatraPDF is not designed to be used in that fashion use a local user copy for remote printing. Your best "served" by using Acrobat reader for that task.

Thank you for reply, I will try it

**Comment by iTanken** [comment]
![image](https://user-images.githubusercontent.com/23544702/218693249-67dec8d6-a576-4ad3-a8fa-967e223a9936.png)

It's normal on `Windows 7 build 7601`, need to install `Windows 7 SP1` upgrade `7600` to `7601`.
