### ISSUE TITLE
Save PDF/document position using MD5 checksums

### ISSUE THREAD

**Issue by neinWur5** [sumatrapdfreader/sumatrapdf#322]
A document position is saved using it's full path, I believe.

What if one moves or renames the document?

A possible better solution would be using a fast checksum and use checksums to track the document's properties.

To consider: this would collide with in-file PDF annotations; one would use the checksums only if the path was not recognized.
One would have:
Table 1: file properties table (with unique ID)
Table 2: path name table (with pointer to table 1)
Table 3: checksum table (with pointer to table 1)

Process of opening document:
check table 2,
if found, open properties
else check table 3, if found, open properties
else open default properties

**Comment by kjk** [comment]
That doesn't happen often enough to warrant so much work to support it.

**Comment by neinWur5** [comment]
Ok, understood.
If I did the work and submitted a pull request, would it probably be rejected, then?
Thanks for your time and for your work :)

**Comment by kjk** [comment]
After more thought, I don't see how storing md5 would help.

Imagine you open c:\foo.pdf, remember md5, rename to c:\bar.pdf. You reopen sumatra. How will you know that bar.pdf corresponds to remembered md5? (without calculating md5 for all files on all drives at every start, which is too expensive).

**Comment by neinWur5** [comment]
I don't understand.
We'd save the MD5 of every file open.
We'd just need to calculate the MD5 of the one file we opened and match with the list we already have.

Alternatively, if we really don't want MD5 and want file preferences to survive rename, we could use [ADS](http://www.flexhex.com/docs/articles/alternate-streams.phtml). ADS are copied transparently with the file, so it would work better than the MD5 method.

**Comment by kjk** [comment]
I misunderstood, please disregard my previous comment.

This scheme also has issues. Currently we don't always load the whole file. We would have to add a pretty expensive step (loading the file and calculating a hash) to a common operation. It would make every file open slower. It would be especially bad for large PDF files on slow file system (network drives).

I don't want to use ADS. Modifying files we touch just to account for a rare use case is not good and ADS has significant restrictions (only work on NTFS i.e. no flash drives or network drives).

My opinion is still that the benefit of preserving viewing state after rename doesn't warrant additional complexity of implementation.

**Comment by neinWur5** [comment]
I thought adding a ADS would not touch the file atime, ctime or mtime.
I was wrong.

As such I agree with your reasoning. Thanks again for your time :)
