### ISSUE TITLE
Annotation Improvements

### ISSUE THREAD

**Issue by berkdemir** [sumatrapdfreader/sumatrapdf#3229]
Hi!
Here is two annotation improvements that I believe is very important.
1) Annotation window should be in the Sumatra PDF, not a floating window. It can be on the right by default, just like a bookmark window. Floating annotation window does not make sense at all in terms of user experience.
2) As mentioned in #1734, setting default annotation style is not possible. Example: I use yellow (same as default), but I use more transparent highlighting. In every highlight, I need to change the opacity manually. The usual way: The PDF reader remembers the last annotation style and uses that until further changes.
![image](https://user-images.githubusercontent.com/40423004/212853153-05406968-e9a1-43f5-8251-a9e1799475b0.png)

**Comment by GitHubRulesOK** [comment]
1) As illustrated if your annotation panel was internal to SumatraPDF window it would exceed my small format screen (I needed to keep ask for panel to be smaller during development) and where MuPDF does as you suggest, (keep it rightside "in-frame") I often even on larger screen cannot action the lower controls there leaving me having to find a different device!.
Floating allows me to move panel to see more of the actions.
![image](https://user-images.githubusercontent.com/12754913/212900680-de1711e9-6f8a-40b0-8b25-6613eff8668c.png)

For colour you set the defaults in advanced options as required so yes inconvenient to swap red blue and green values ad hoc but you can pre-set a preference for each that way.

Annotations [
	HighlightColor = #ffff00
	UnderlineColor = #00ff00
	TextIconColor = #ffff00
	TextIconType = 
	DefaultAuthor = 
]

**Comment by berkdemir** [comment]
Thanks @GitHubRulesOK.
For the floating annotation, we can allow undocking to the user by dragging, right? It's the usual methods, we are not reinventing the wheel. If user has space, s/he can dock it. If not, undock it and try to use on top of the PDF.

For the second part, how about remembering the last choice?

**Comment by GitHubRulesOK** [comment]
1) the first hurdle would be that currently you cannot "undock" tabs let alone other parts,
 so priority would be tabs first, and that's just as simple as find a programmer or two to do that job.
took long enough to get floating windows done well enough :-).

2) save settings remembers one from settings for dialog not other way round, possibly doable but see answer 1)

**Comment by berkdemir** [comment]
OK, anyway, I don't agree with anything related to floating windows, but it is your decision. Thanks for the answers.

**Comment by GitHubRulesOK** [comment]
Not my decision, I am not the Developer, just supporter and my personal observations over a time

**Comment by hudcap** [comment]
Apparently, we are not alone: #3490
