### ISSUE TITLE
Add ability to 1) mark areas with color 2) add comments to certain text parts of document

### ISSUE THREAD

**Issue by drweb86** [sumatrapdfreader/sumatrapdf#323]
Hello
Could you please add ability to mark areas with yellow and red color so i can mark important things in books and errors in articles.
Could you please add ability to store comments about pdf document so i can share them along with pdf to some other guys.
Thanks.

**Comment by SumatraPeter** [comment]
Highlighting has been available in the pre-release builds for a long time, but I don't know when it'll make it to the stable release.

http://forums.fofou.org/sumatrapdf/topic?id=3184963

**Comment by gabo77** [comment]
While highlighting works as expected, is there any way to undo or remove the highlighting?

**Comment by zklhp** [comment]
Hi all,

I added some lines to make the remove of highlighting possible. I have made a pull request https://github.com/sumatrapdfreader/sumatrapdf/pull/741, and you can find the .exe with this feature at 

https://ci.appveyor.com/project/zklhp/sumatrapdf/build/artifacts

The use of this feature is simple. With the highlighting selected, press h/H, the highlighting disappears.

**Comment by GitHubRulesOK** [comment]
All the above points except comments were available in numerous pre-release versions so am closing on the basis the one remaining issue (requesting comments) is covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/453
