### ISSUE TITLE
change on print page after migrating on Windows 11 (Print from Win32)

### ISSUE THREAD

**Issue by David83470** [sumatrapdfreader/sumatrapdf#3231]
Hi.
My Windows 10 decided yesterday by it's own to migrate to Windows 11.

No comment about that, but:
Sumatra (last version V3.4.6 64bits already installed) changed its print page. 
Instead of the usual print settings window, I now have a different and much less practical window

On the top of its windows, I can read
![Capture](https://user-images.githubusercontent.com/122969753/213127581-43fad31e-b492-418f-8b2d-db79714bfd6f.png)
 'impression à partir de l'application Win32' ('print from Win32 application')
See attached print screen.
Could anybody help me to fix that ?
Thanks
Dave

**Comment by tactilis** [comment]
Welcome to Windows 11!

Please see this issue [https://github.com/sumatrapdfreader/sumatrapdf/issues/3216](https://github.com/sumatrapdfreader/sumatrapdf/issues/3216)

**Comment by kjk** [comment]
Unfortunately that's a Windows thing. Sumatra uses standard print dialog and Microsoft changed it.

**Comment by David-CMZ** [comment]
It's worse. 
In vb6-made apps, the 'Print' button does not enable, so It's useless.

![image](https://user-images.githubusercontent.com/100340007/221171096-81059c31-2b18-49fe-b535-b0a2d99bfb4f.png)
