### ISSUE TITLE
Problem displaying symbol ■ (square symbol)

### ISSUE THREAD

**Issue by metafo** [sumatrapdfreader/sumatrapdf#3236]
![image](https://user-images.githubusercontent.com/111051267/213899327-bba32519-3789-4d88-a5bc-0b436e2cbff4.png)
![image](https://user-images.githubusercontent.com/111051267/213899338-91c5c901-97e6-4f05-88e2-f81c952fd96b.png)

**Comment by GitHubRulesOK** [comment]
Not a problem unless badly included
![image](https://user-images.githubusercontent.com/12754913/213901717-d4ac74db-11fa-4178-8342-4f2ee090b2c2.png)

**Comment by metafo** [comment]
> Not a problem unless badly included ![image](https://user-images.githubusercontent.com/12754913/213901717-d4ac74db-11fa-4178-8342-4f2ee090b2c2.png)

It's still there on both my Windows 11 and Windows 10.

**Comment by GitHubRulesOK** [comment]
Sybols are not part of everyday native fonts in PDF (or other documents) For PDF they should be fallback to ZapfDingbats but not everyone uses that font nowadays, thus whatever font was used needs to be included inside a PDF to be shown out same as in. Most PDF writers but not all may do that correctly (especially foreign characters/punctuation/symbols , even simple European letters)

**Comment by kjk** [comment]
I can't investigate without access to the file showing the problem. Looks like font matching problem which could be an issue with mupdf or it could be a difference in installed fonts on your machine.

**Comment by GitHubRulesOK** [comment]
@kjk without a test sample I suggest this be closed.
