### ISSUE TITLE
Store only the changed settings in the advanced settings.txt

### ISSUE THREAD

**Issue by yashpalgoyal1304** [sumatrapdfreader/sumatrapdf#3237]
_This idea was on my mind for quite a long time; was a bit unsure earlier, but I got confirmed that it is correct when i saw an actual implementation of it in the config file of helix editor._

So, currently, sumatra stores all the settings in the `SumatraPDF-settings.txt` - and rewrites them everywhere a setting is changed from UI and at various other triggers/events I suppose. 

The suggestion is to internally store a default configuration, and append (i.e. write at end) the `SumatraPDF-settings.txt` with only those settings which are changed. This approach is used by various TUI based applications, and is really helpful.

It will also allow #3043 and will ease the process for running with default config for diagnosing bugs.
This will require https://github.com/sumatrapdfreader/sumatrapdf/issues/1174

**Comment by yashpalgoyal1304** [comment]
While searching for content for https://github.com/helix-editor/helix/issues/396#issuecomment-1365283396 , just found out that Python does this too:

> Non-default user settings are saved in a .idlerc directory in the user’s home directory. Problems caused by bad user configuration files are solved by editing or deleting one or more of the files in .idlerc.
/- Python: [3 IDLE](https://docs.python.org/3/library/idle.html?highlight=idlerc#setting-preferences)
/- Python: [2.7 IDLE](https://docs.python.org/2.7/library/idle.html?highlight=idlerc#options-menu-shell-and-editor)

**Comment by GitHubRulesOK** [comment]
MuPDF itself hides (nix like) the history settings in user root thus not very useful as a portable app, SumatraPDF Portable keeps portable settings file in exe folder like most Traditional PortApps did/do (there can be problems with other moder PortableApp Clones that use multiple ini regs and dat's.

The historic settings were not exposed as a txt type file but a dat file for only application but over time extra user acessible features have been added so as to keep sessions against failure in that same one control set the set could be made inaccessible like MuPDF to avoid interference, but as it stands almost one file fits all. (exception is the thumbnails error or runtime or crash logs, etc.)

**Comment by kjk** [comment]
Too much work for the benefit.

Also, having all the settings listed in the file educates people about what the settings are.
