### ISSUE TITLE
Form values in IRS tax documents are not displayed

### ISSUE THREAD

**Issue by dandv** [sumatrapdfreader/sumatrapdf#324]
The form values in this filled-in [IRS form 1099](https://www.irs.gov/pub/irs-pdf/f1099msc.pdf) are not shown (filled-in form sent privately). There's no indication that there was data in the form, which almost made me delete the file, thinking it was the unfilled copy of form.

**Comment by kjk** [comment]
Confirmed values show in preview but not in sumatra.

**Comment by dandv** [comment]
Chrome's PDF viewer displays them correctly as well.

**Comment by VictorVG** [comment]
Sorry, but latest version the PDF-Xchange Viewer, KPDF, Okular, XPDF (UNIX) damage reported XREF table and the presence of unsupported elements. So I think this paper is specially made so that it could work with only Adobe Acrobat?

**Comment by dandv** [comment]
The open source PDF viewer in Chromium does display the values correctly.

**Comment by VictorVG** [comment]
Chrome PDF viewer is (it Gecko analogue [**pdf.js**](https://github.com/mozilla/pdf.js/)) scripting program converts PDF markup in the browser's HTML5 media and from my point of view, the prototype can not be due to the fact that using other mechanisms for its operation.

**Comment by kjk** [comment]
This is now tracked in #1249
