### ISSUE TITLE
[SHIFT+TAB] change to previous tab

### ISSUE THREAD

**Issue by mrx23dot** [sumatrapdfreader/sumatrapdf#3242]
CTRL+TAB correctly moves to next tab
but SHIFT+TAB doesn't move back one tab. 
It would be intuitive as in other apps.

**Comment by GitHubRulesOK** [comment]
Ctrl + Tab - go to next tab
Ctrl + Shift + Tab - go to previous tab

you can change those in most recent versions, however beware tab and shift tab are a global windows navigation control hence for tabbed windows both need CTRL
