### ISSUE TITLE
bam!

### ISSUE THREAD

**Issue by medukia** [sumatrapdfreader/sumatrapdf#3247]
bam!

**Comment by GitHubRulesOK** [comment]
Hmmm the problem with no fonts is its then often impossible to show characters outside the stock 128 ansi Latin range so either boxes or at best without an international characters, I am unsure what Mupdf may use as fail-back for a given case perhaps post a sample we can see what it uses in different machines.

**Comment by medukia** [comment]
@GitHubRulesOK thank you for the input. I don't have problem about broken glyphs at the moment although in rare case some are displayed with square boxes. most of my books are written in korean.

in the former build, Sumatra could offer an option to edit the .ini settings file in a way user can specify the font that must be used. now that option is gone.

**Comment by quyleanh** [comment]
+1 for option to changing font for epub file. Hope this option will be back soon.
