### ISSUE TITLE
3.4.6 Small Images in .epub files

### ISSUE THREAD

**Issue by BirdyQ** [sumatrapdfreader/sumatrapdf#3248]
Been using 3.1.2 for awhile now. Decided to check out the update. All looks great but images in my .epub files are tiny. This was not present in 3.1.2 so I can't update until it's fixed. Attached is the photo of what they look like side by side. All settings in "options" and "advanced options" are as identical as they can be. 

![sumatra pdf images](https://user-images.githubusercontent.com/124018839/215659982-4b61044d-7815-435e-a00d-eb4c53178f2b.PNG)

**Comment by GJoe2** [comment]
Is your issue related on how your document looks in specific SumatraPDF version? Is your issue solved if you zoom in your epub on 3.4.6 version? 
What if you select this option?
![image](https://user-images.githubusercontent.com/71229258/222813301-b63d999c-1b4b-4f5f-adc6-3a2470021764.png)

I tried SumatraPDF 3.4.6 version with a random epub with some images and I did not have that issue

Random epub:
https://www.gutenberg.org/ebooks/70194.epub3.images

**Comment by AndNovAtor** [comment]
Sorry for offtopic idea, still. @BirdyQ , can you try [prerelease](https://www.sumatrapdfreader.org/prerelease) version (for example, download portable SumatraPDF-prerel-64.exe and try the SAME file with it?
Simply, I had some image issue with some file, that also a novel, but fb2. Also with 3.4.6 version, but SUDDENLY it's not presented in prerelease version

**Comment by kjk** [comment]
I can't reproduce this with the files I have. Would need a sample file that shows the problem.
