### ISSUE TITLE
The problem in the assembly install.exe

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#325]
The problem in the assembly install.exe I occurs regardless of the configuration and manifest error in the final assembly of the log. The cause of the error can be seen in installer.log:
```
".. \ rel \ MakeLZSA.exe" is not an internal or external command, operable program or batch file.
C: \ Program Files (x86) \ MSBuild \ Microsoft.Cpp \ v4.0 \ V140 \ Microsoft.CppCommon.targets (123,5): error MSB3073: exit the command "cd ../rel & .. \ rel \ MakeLZSA.exe InstallerData.dat SumatraPDF-no-MUPDF.exe: SumatraPDF.exe libmupdf.dll: libmupdf.dll PdfFilter.dll: PdfFilter.dll PdfPreview.dll: PdfPreview.dll Uninstaller.exe: uninstall.exe .. \ mupdf \ resources \ fonts \ droid \ DroidSansFallback.ttf: DroidSansFallback.ttf
C: \ Program Files (x86) \ MSBuild \ Microsoft.Cpp \ v4.0 \ V140 \ Microsoft.CppCommon.targets (123,5): error MSB3073:: VCEnd "with code 9009.
```
ьakeLZSA.exe for reasons not clear to me is not going (???) to start assembling installer.exe and it crashes. If you remove the current working copy and get it with Git again, then on again - the other will suffice. The previous audit Git-7adbe9a40c successfully if everything was going to collect the first x86 configuration if you start with x64 mistake was similar.

Judging by the fact that I was in the toolbox of the project shows the VS 2015 it gathers the elements in alphabetical order, and if so, you may rename the project in such makeLZSA arcLZSA to VS it is always going up to build the installer?

*I ask the board how to eliminate this phenomenon?*

**Comment by kjk** [comment]
When you do 64-bit build you first have to build release 32-bit build so that rel\MakeLZSA.exe is created.

**Comment by VictorVG** [comment]
Here it is interesting that at that time gathered in this order - first 32 it after the 64-bit and that the first step was a mistake. After obtaining her hand, I gathered makeLZSA and only going installer.exe. Here it surprised me. Frankly I do not understand what causes this phenomenon? At one time the car was clink 0.44 - 0.45 and after its removal were failures drivers NVIDIA. It got to the inability to start the daemons. I suspect the problem router TP-Link R460 which accounts for restart after receiving files over Skype, or you try to download an ISO image of BSD UNIX by the torrent, but there is no certainty if I think in the wrong direction. As an engineer I can easily decide this problem, but not sure of the correctness of the hypothesis, and therefore need a tip in the direction of whether I think.

**Comment by VictorVG** [comment]
Asked [**"thank you"**](http://forum.ru-board.com/topic.cgi?forum=5&topic=22740&start=1220#14) to transfer (quoting as is): 

>**lemor** 
>Sumatra PDF 
>He began to use - like scary. Developers thank you !!!!!!
