### ISSUE TITLE
Will activate bug-fixing/development resume in 2023?

### ISSUE THREAD

**Issue by Pocokk** [sumatrapdfreader/sumatrapdf#3252]
First of all I appreciate all the work that has been done!

However as there are still hundreds of opened tickets (ranging from small minor problems to various feature requests etc) that is mounting up on a daily basis and with reduced newer versions updates in the last 4 months and no new major release in the last 8 months or so, I'm a bit worried about the Project and its future.

Am I over exaggerating or the situation is not that "bad"? Can we get some reassuring replies about the upcoming plans? Thank you!

**Comment by tactilis** [comment]
> Will activate bug-fixing/development resume in 2023?

It depends on whether people divert the developer's attention by posting issues saying that they are "_a bit worried about the Project and its future_" and asking for "_reassuring replies about the upcoming plans_".

Such diversion is even more of a problem when the OP generates 5 versions of their issue with minor wording changes:

![image](https://user-images.githubusercontent.com/4060092/216658811-359d4adf-ff9d-4c54-b1fc-66b308a737eb.png)
 
> Am I over exaggerating

Yes.

**Comment by GitHubRulesOK** [comment]
I dont think 9 or 10 hours is that long since last update

[update go to 1.19](https://github.com/sumatrapdfreader/sumatrapdf/commit/9beddaeedd15d8db96852ca54cf155be54a6defb)

@[kjk](https://github.com/sumatrapdfreader/sumatrapdf/commits?author=kjk)
kjk committed 10 hours ago
