### ISSUE TITLE
crash in eval_sample_func

### ISSUE THREAD

**Issue by planetkalpesh** [sumatrapdfreader/sumatrapdf#3253]
Crash file: C:\Users\John\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.txt
Exe: C:\Program Files\SumatraPDF\SumatraPDF.exe 7.75 MB (8,129,496 Bytes)
Dll: C:\Program Files\SumatraPDF\libmupdf.dll 13.08 MB (13,710,336 Bytes)
BuiltOn: 2023-02-03
Type: dll
Ver: 3.5.15265 pre-release 64-bit
Git: 9beddaeedd15d8db96852ca54cf155be54a6defb (https://github.com/sumatrapdfreader/sumatrapdf/commit/9beddaeedd15d8db96852ca54cf155be54a6defb)
OS: Windows 10.22621 build 22621 64-bit
Number Of Processors: 4
Processor: Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
Physical Memory: 7.86 GB
Commit Charge Limit: 8.36 GB
Memory Used: 32%
Machine: 103C_53311M HP Desktop 
Lang: en US
Graphics driver 0
  DriverDesc:         Intel(R) UHD Graphics 630
  DriverVersion:      30.0.101.1404
  UserModeDriverName: C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_a934a9379f55edc8\igdumdim64.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FFFEFAD8DA5 01:00000000001B7DA5 libmupdf.dll!pdf_load_cmap+0x26ed
Fault reading address 000001D98A110A70

Registers:
RAX:FFFFFFFF80000000  RBX:0000000080000000  RCX:FFFFFFFF80000000
RDX:000001DB8A110A70  RSI:000001DB8A2C1040  RDI:000000A6C6DFC224
R8: 0000000000000001
R9: 000000A6C6DFBFB0
R10:000001DB8A2C13F0
R11:0000000080000000
R12:000000A6C6DFBFB0
R13:00000134C34C4E20
R14:0000000000000000
R15:000001DB8A2C106C
CS:RIP:0033:00007FFFEFAD8DA5
SS:RSP:002B:00000000C6DFBB40  RBP:C6DFBC40
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010286

Crashed thread:
00007FFFEFAD8DA5 01:00000000001B7DA5 libmupdf.dll!pdf_load_cmap+0x26ed
00007FFFEFAD99E2 01:00000000001B89E2 libmupdf.dll!pdf_load_cmap+0x332a
00007FFFEFA5553B 01:000000000013453B libmupdf.dll!fz_new_indexed_colorspace+0x1153
00007FFFEFA51F08 01:0000000000130F08 libmupdf.dll!fz_clone_pixmap_area_with_different_seps+0xd64
00007FFFEFA51288 01:0000000000130288 libmupdf.dll!fz_clone_pixmap_area_with_different_seps+0xe4
00007FFFEFAA6A77 01:0000000000185A77 libmupdf.dll!fz_paint_shade+0x643
00007FFFEFA6739D 01:000000000014639D libmupdf.dll!fz_drop_stext_page+0x16f9
00007FFFEFA6750D 01:000000000014650D libmupdf.dll!fz_drop_stext_page+0x1869
00007FFFEFA46F29 01:0000000000125F29 libmupdf.dll!fz_fill_shade+0x89
00007FFFEFB2E616 01:000000000020D616 libmupdf.dll!xps_resolve_url+0x33386
00007FFFEFB2C8EC 01:000000000020B8EC libmupdf.dll!xps_resolve_url+0x3165c
00007FFFEFB2CD99 01:000000000020BD99 libmupdf.dll!xps_resolve_url+0x31b09
00007FFFEFB2D50A 01:000000000020C50A libmupdf.dll!xps_resolve_url+0x3227a
00007FFFEFB2D655 01:000000000020C655 libmupdf.dll!xps_resolve_url+0x323c5
00007FFFEFAE5793 01:00000000001C4793 libmupdf.dll!pdf_repair_obj_stms+0xac3
00007FFFEFAE592C 01:00000000001C492C libmupdf.dll!pdf_repair_obj_stms+0xc5c
00007FFFEFAE59D0 01:00000000001C49D0 libmupdf.dll!pdf_run_page_contents+0x30
00007FFFEFA45B20 01:0000000000124B20 libmupdf.dll!fz_run_page_contents+0x8c
00007FFFEFA8C443 01:000000000016B443 libmupdf.dll!fz_new_stext_page_from_page+0xc7
00007FF719BA72DB 01:00000000000A62DB sumatrapdf.exe
00007FF719BA79B2 01:00000000000A69B2 sumatrapdf.exe
00007FF719B48111 01:0000000000047111 sumatrapdf.exe

**Comment by kjk** [comment]
Please provide the file that caused the crash, as described in https://www.sumatrapdfreader.org/docs/Submit-crash-report

**Comment by planetkalpesh** [comment]
> Please provide the file that caused the crash, as described in https://www.sumatrapdfreader.org/docs/Submit-crash-report

I have emailed you the file that caused crash at your gmail address. Please check it.

**Comment by kjk** [comment]
Thanks, I got it.

The crash is:
```
Exception thrown: read access violation.
func->u.sa.**samples** was 0x11102D2A88DA8A2.

mupdf.exe!eval_sample_func(fz_context * ctx, pdf_function * func, const float * in, float * out) Line 1092
	at C:\Users\kjk\src\mupdf\source\pdf\pdf-function.c(1092)
mupdf.exe!pdf_eval_function_imp(fz_context * ctx, pdf_function * func, const float * in, float * out) Line 1383
	at C:\Users\kjk\src\mupdf\source\pdf\pdf-function.c(1383)
mupdf.exe!pdf_eval_function(fz_context * ctx, pdf_function * func, const float * in, int inlen, float * out, int outlen) Line 1415
	at C:\Users\kjk\src\mupdf\source\pdf\pdf-function.c(1415)
mupdf.exe!devicen_eval(fz_context * ctx, void * tint, const float * sv, int sn, float * dv, int dn) Line 107
	at C:\Users\kjk\src\mupdf\source\pdf\pdf-colorspace.c(107)
mupdf.exe!separation_via_base(fz_context * ctx, fz_color_converter * cc, const float * src, float * dst) Line 903
	at C:\Users\kjk\src\mupdf\source\fitz\colorspace.c(903)
mupdf.exe!fz_copy_pixmap_area_converting_seps(fz_context * ctx, fz_pixmap * src, fz_pixmap * dst, fz_colorspace * prf, fz_color_params color_params, fz_default_colorspaces * default_cs) Line 722
	at C:\Users\kjk\src\mupdf\source\fitz\separation.c(722)
mupdf.exe!fz_clone_pixmap_area_with_different_seps(fz_context * ctx, fz_pixmap * src, const fz_irect * bbox, fz_colorspace * dcs, fz_separations * dseps, fz_color_params color_params, fz_default_colorspaces * default_cs) Line 305
	at C:\Users\kjk\src\mupdf\source\fitz\separation.c(305)
```

**Comment by kjk** [comment]
Fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/d24e4a46191bb7203fa9fe2f806b940b4cf66287
