### ISSUE TITLE
separate colorpref for ebooks (epub) and fixedpages (pdf, djvu)

### ISSUE THREAD

**Issue by expikr** [sumatrapdfreader/sumatrapdf#3255]
I would like to use a dark theme for flowing-text files like epub, and normal (un-inverted picture color) light theme for pdfs/djvus. Currently they are all lumped together into the fixedpage preference, which makes no sense.

**Comment by GitHubRulesOK** [comment]
There is no theming so closing as covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/743 and https://github.com/sumatrapdfreader/sumatrapdf/issues/898

**Comment by GitHubRulesOK** [comment]
There is nno colour scheme either its nt being pedantic its reducing duplicate feature requests to a manageable level of one per "issue" the reason there is a means to control canvas colour is mainly inversion

**Comment by GitHubRulesOK** [comment]
Its legacy entries the Manga Mode is now a common feature so in effect the ComicBookUI could be removed

@kjk is there a need for different sections ? however I guess combining them will raise objections ?
