### ISSUE TITLE
Portable Version losing Drive Letter

### ISSUE THREAD

**Issue by ancient-gopher** [sumatrapdfreader/sumatrapdf#3258]
I am using the portable version 3.4.6..
When opening a file, the Path is written into the SumatraPDF-settings.txt.

But when reopening Sumatra, the filepath is changed. The Drive letter is lost and replaced by a "?".

![grafik](https://user-images.githubusercontent.com/124663309/217182216-2bab4e8c-5e14-484e-b3c8-d3d68489a8e5.png)

**Comment by GitHubRulesOK** [comment]
AFAIK that is by design as the portable drive has a variable ? (non static) device letter
