### ISSUE TITLE
Prevent accidental changes by moving annotations

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#3261]
Example file: https://github.com/sumatrapdfreader/sumatrapdf/files/4909953/pmi_sample3.pdf

As discussed https://github.com/sumatrapdfreader/sumatrapdf/discussions/2331, it's too easy to accidentally move an annotation with a mouse.

Most likely will require pressing additional key e.g. Shift or Ctrl to move an annotation.

**Comment by GitHubRulesOK** [comment]
related https://github.com/sumatrapdfreader/sumatrapdf/issues/1999 and https://github.com/sumatrapdfreader/sumatrapdf/issues/1681
