### ISSUE TITLE
greek letters not showing in epub

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#3265]
_Originally posted by @Andley in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3263_

Repro file: https://www.gutenberg.org/ebooks/39536.epub.noimages

It shows properly in mupdf so must be some font change I've made.

**Comment by GitHubRulesOK** [comment]
@kjk
The legacy issue was more capitals than accents, however that issue was kept open on the transfer to MuPDF, 
thus untested but first looks suggest older https://github.com/sumatrapdfreader/sumatrapdf/issues/442#issuecomment-899118555 may be related

**Comment by kjk** [comment]
the problem is that we pick up fonts:
```
0x000000dcbdcfd760 "Charis SIL Regular"
0x000000dcbdcfca70 "Charis SIL Bold"
0x000000dcbdcfcf00 "Nimbus Mono PS Regular"
0x00007ff79f64a530 "Symbol"
```

while mupdf picks up:
```
0x000000045896d268 "Charis SIL Regular"
0x000000045896c698 "Charis SIL Bold"
0x000000045896de38 "Noto Serif Regular"
0x000000045896cab8 "Nimbus Mono PS Regular"
```

We pick "symbol" instead of Noto Serif Regular" because it matches from windows installed fonts, which mupdf doesn't check.

**Comment by kjk** [comment]
The issue is that we don't ship with Noto fonts.

**Comment by Andley** [comment]
@kjk, thanks ! It works 😀
