### ISSUE TITLE
searching in pdf by arabic language

### ISSUE THREAD

**Issue by Raed1411** [sumatrapdfreader/sumatrapdf#3270]
there is no result when I search in arabic pdf 
I think the search box reverse the letters for example :
the word "الفرد"  the right word   >>>  "درفلا" the wrong word  

that means zero rsult for all words

**Comment by GitHubRulesOK** [comment]
am going to close this as common problem( Duplicate) between Persian area RTL languages
 such as Arabic Farsi Hebrew and others of that region https://github.com/sumatrapdfreader/sumatrapdf/issues/2631
 https://github.com/sumatrapdfreader/sumatrapdf/issues/2170 
currently covered by [#1870](https://github.com/sumatrapdfreader/sumatrapdf/issues/1870)

Also related to https://github.com/sumatrapdfreader/sumatrapdf/issues/2344 and https://github.com/sumatrapdfreader/sumatrapdf/issues/3244
