### ISSUE TITLE
reloads old pdfs again when launched by double-clicking on pdf in explorer

### ISSUE THREAD

**Issue by asbloomf** [sumatrapdfreader/sumatrapdf#328]
I have tabs turned off.  If I load multiple documents using File -> Open and then File -> Exit, all documents close.  When I launch Sumatra, they all open as expected.  But then if I double-click on a PDF in explorer, it launches Sumatra and reloads all the documents again.  If I do File -> Exit, only those windows get closed.  The windows from before I launched the file from explorer remain.  I hope that is clear.

**Comment by kjk** [comment]
Should be fixed in pre-release http://www.sumatrapdfreader.org/prerelease.html
