### ISSUE TITLE
Can save annotation on restricted mode v3.5.15312.

### ISSUE THREAD

**Issue by alxstxra** [sumatrapdfreader/sumatrapdf#3290]
Hi guys,

When i use the annotation's shortcuts on a select word, i create an annotation that can be save.

I put in sumatrapdfrestrict.ini, DiskAccess = 0.

**Comment by GitHubRulesOK** [comment]
Hmm this was mentioned before https://github.com/sumatrapdfreader/sumatrapdf/issues/2846
@kjk has thee been some regression ?

**Comment by hoffst** [comment]
Maybe DiskAccess is too general. It should be possible to add annotations even with DiskAccess=0, and save them in a renamed file with "Save As". A new option for the viewed PDF-file could allow this, e.g. "PdfReadOnly=1".

**Comment by Monarch46a** [comment]
Hello, we also discovered this issue today. In our use case it should not be possible to edit annotations in restricted mode. 
What we discovered is, that in restricted mode it is even possible to create new annotations using the keyboard shortcut.

Perhaps a new option could also be called "Annotations = false" or something like that.

**Comment by kjk** [comment]
I hopefully fixed it in [pre-release](https://www.sumatrapdfreader.org/prerelease) 16430 or later.

Let me know if I missed a case.
