### ISSUE TITLE
Can't customize shortcuts v3.5.15312

### ISSUE THREAD

**Issue by alxstxra** [sumatrapdfreader/sumatrapdf#3291]
Hi guys,

I use the portable version
I customized the shorcuts "a" and "u", but they keep the old setup.
I want to change the shortcut cmd to CmdNone.

Shortcuts [
	[
		Cmd = CmdNone
		Key = A
	]
	[	
		Cmd = CmdNone
		Key = a
	]	
	[
		Cmd = CmdNone
		Key = U
	]	
	[
		Cmd = CmdNone
		Key = u
	]	
]

**Comment by kjk** [comment]
It works for me in15312 with:
```
Shortcuts [
	[
		Cmd = CmdNone
		Key = a
	]
	[
		Cmd = CmdNone
		Key = u
	]
]
```

Double-check you're modifying the right settings file (Use `Ctrl - K` and `advanced options`)
