### ISSUE TITLE
Navigate Back

### ISSUE THREAD

**Issue by mrrezaie** [sumatrapdfreader/sumatrapdf#3303]
Hello,

It would be great if you add this option to navigate to the previous page quickly. In articles, when I click on a hyperlinked reference, it switches to the references page and it's hard to get back to the initial page. WPS has such functionality:

https://user-images.githubusercontent.com/38867713/221369161-18e1a316-169e-4f98-9305-3776f8cfe44e.mp4

I'm looking forward to seeing this option in SumatraPDF.

**Comment by kjk** [comment]
It's already there: Backspace / Shift+Backspace, Alt + Left, Alt + Right
Menu: Go To / Back | Forward
Command menu (Ctrl + K) "back", "forward"

See https://www.sumatrapdfreader.org/docs/Keyboard-shortcuts

**Comment by mrrezaie** [comment]
Thank you so much.

Is it possible to add these shortcuts to toolbar?

Also, when I click on a hyperlinked reference, it jumps incorrectly, i.e. the reference is at the bottom of the page, but it jumps to the top of that page ("Fit Width and Show Pages Continuously" is selected).

Thanks again.

**Comment by GitHubRulesOK** [comment]
@mrrezaie 
currently add to toolbar = No (in general) the toolbar has always been kept small and essentials only, for small  screen, and there are still some of us using netbooks with ebooks for reading, any more icons / custom entries eats critical canvas area.

hyperlinked refs are defined many many ways so zoom in and see if the target moves to **anywhere** in viewer area if not then there is a potential problem but if your viewing page its normal to not zoom in unless the ref was correctly set to zoom.
