### ISSUE TITLE
Special Characters do not copy paste properly

### ISSUE THREAD

**Issue by MrVauxs** [sumatrapdfreader/sumatrapdf#3307]
Paizo's Pathfinder 2e booklets use a special font, which when copied in say, Chrome, returns a string such as `[free-action]`, `[reaction]`, `[one-action]`, etc.
Unfortunately with Sumatra, these characters are instead copied as `�`, `�`, and `�` in that order.
The fonts are embedded in the PDF document.

```
PDF Producer: iLovePDF
PDF Version: 1.7
   
Fonts: Gin-Regular (Type1; Ansi; embedded)
Gin-Regular-SC700 (Type1; Ansi; embedded)
GoodOT (Type1; embedded)
GoodOT-Bold (Type1; Ansi; embedded)
GoodOT-Bold (Type1; embedded)
GoodOT-BoldItalic (Type1; Ansi; embedded)
GoodOT-BoldItalic (Type1; embedded)
GoodOT-CondBold (Type1; Ansi; embedded)
GoodOT-CondBold (Type1; embedded)
GoodOT-Italic (Type1; 
GoodOT-Italic (Type1; Ansi; embedded)
GoodOT-News (Type1; embedded)
Helvetica (TrueType; Ansi; embedded)
Pathfinder-Icons (TrueType (CID); Identity-H; embedded)
SabonLTStd-Italic (Type1; Ansi; embedded)
SabonLTStd-Italic (Type1; embedded)
SabonLTStd-Roman (Type1; Ansi; embedded)
SabonLTStd-Roman (Type1; embedded)
Taroca (TrueType; Ansi; embedded)
TestamentII-Bold (Type1; embedded)
TimesNewRomanPS-BoldItalicMT (TrueType (CID); Identity-H; embedded)
TimesNewRomanPS-BoldItalicMT (TrueType; Ansi; embedded)
TimesNewRomanPS-BoldMT (TrueType (CID); Identity-H; embedded)
TimesNewRomanPS-BoldMT (TrueType; Ansi; embedded)
```

**Comment by GitHubRulesOK** [comment]
Embedding means very little the MAP needs to work so 10000001 = 65 = � if not mapped to a character such as say an arabic character in one font or with an accent in a baltic font. PDF is painting by numbers but if the colour range is wrong you get muddy brown outs.

See how the case of a good CID mapping from MS works here using /TTF2  (Calibri on a Mac device) 
  https://github.com/sumatrapdfreader/sumatrapdf/issues/3305#issuecomment-1445353471

**Comment by MrVauxs** [comment]
I am not sure what you are talking about. I was just wondering why Chrome lets me copy the highlighted character as `[free-action]` while Sumatra returns a `�`.

![image](https://user-images.githubusercontent.com/32039708/221454443-4e3265ce-def8-4ea4-8d69-113149171ca7.png)
![image](https://user-images.githubusercontent.com/32039708/221454711-e1206218-9231-4fda-9a99-5ca69a9c07ef.png)

**Comment by GitHubRulesOK** [comment]
It depends what your capturing and viewing so here without your sample WordPad can only substitute © for the picture, With he file it would be simpler to see if there is some underlying [free-action] #tag since thats what chrome is showing as Tab [file-name]
![image](https://user-images.githubusercontent.com/12754913/221462737-b7c51b16-a517-450d-b575-602b94346775.png)

**Comment by MrVauxs** [comment]
Here is a single-page excerpt from the PDF
[Treasure Vault-pages-13.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/10836155/Treasure.Vault-pages-13.pdf)

**Comment by GitHubRulesOK** [comment]
OK thanks for a sample
this is a MuPDF limitation, perhaps best raised there 
@kjk can SumatraPDF do better in such cases ?

Pathfinder-Icons (TrueType (CID); Identity-H; embedded)

Chrome extract
---
```
ADVANCING RUNE 9+
 MAGICALNECROMANCY
 Usage etched onto heavy armor
 This rune charges up as you defeat your foes, driving you 
forward across the battlefield with every victory.
 Activate [free-action] command; Requirements Your last action or 
...
```

MuPDF extract
---
```
ADVANCING
RUNE 9+
MAGICAL
NECROMANCY
Usage etched onto heavy armor
This rune charges up as you defeat your foes, driving you
forward across the battlefield with every victory.
Activate � command; Requirements Your last action or
...
```

So these are custom named characters

- [three-actions]
- [two-actions]
- [one-action]
- [free-action]
- [reaction]

from
---
```
76 0 obj
<<
  /Length 626
>>
stream
/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CIDSystemInfo
<< /Registry (Adobe)
/Ordering (UCS) /Supplement 0 >> def
/CMapName /Adobe-Identity-UCS def
/CMapType 2 def
1 begincodespacerange
<0000> <FFFF>
endcodespacerange
5 beginbfchar
<0013> <005B00740068007200650065002D0061006300740069006F006E0073005D>
<0014> <005B00740077006F002D0061006300740069006F006E0073005D>
<0015> <005B006F006E0065002D0061006300740069006F006E005D>
<0016> <005B0066007200650065002D0061006300740069006F006E005D>
<0017> <005B007200650061006300740069006F006E005D>
endbfchar
endcmap CMapName currentdict /CMap defineresource pop end end

endstream
```

**Comment by MrVauxs** [comment]
First time using BugZilla, but there you go: https://bugs.ghostscript.com/show_bug.cgi?id=706498

**Comment by kjk** [comment]
Good news, mupdf fixed this.
