### ISSUE TITLE
3.1 x64 installed to x86 programfiles

### ISSUE THREAD

**Issue by renyouguo** [sumatrapdfreader/sumatrapdf#331]
C:\Program Files (x86)\SumatraPDF

**Comment by kjk** [comment]
If you had previous 32-bit version of Sumatra installed, this is expected behavior.

By default we preserve installation location from previous install. You can change it using "Options" in the installer.

If this is fresh installation, we default to c:\Program Files for 64-bit exe.

**Comment by SumatraPeter** [comment]
Somehow this sort of behavior seems very unclean to me. Isn't it possible in such cases to invoke the uninstaller first (as some other apps do), then install to the proper location? The prefs will of course stay untouched in %AppData%\SumatraPDF.
