### ISSUE TITLE
Off-by-one page when using bookmarks or ToC

### ISSUE THREAD

**Issue by mowny** [sumatrapdfreader/sumatrapdf#3310]
Version: v3.4.6 64bit
Any links that target a page are off by one and open the following page instead.
Links to an anchor are fine. Unfortunately InDesign lets bookmarks and ToC point to the page, not to the text anchor like Word does.

Works in Acrobat, PDFXChange, Firefox, Chrome, and I'm pretty sure it also worked in earlier versions of SumatraPDF.
Example: https://download.sourcetronic.com/ST500BDA_v1.27.pdf

**Comment by kjk** [comment]
Fixed in latest pre-release builds https://www.sumatrapdfreader.org/prerelease
