### ISSUE TITLE
How does WindowMargin paramater work?

### ISSUE THREAD

**Issue by Astro-Aionia** [sumatrapdfreader/sumatrapdf#3315]
The paramater WindowMargin was set as `2 4 2 4` defaultly, I tried to change it as `0 0 0 0` and a very large number respectively, but I found that the margin length between pdf page and window edge did change. So did I misunderstand this parameter? What does it really control?

**Comment by kjk** [comment]
Set it to e.g. 	WindowMargin = 64 32 46 32
and make sure to use Fit Single Page (Ctrl + 0) mode.
You should see large margin between page and window. It doesn't apply in all layout modes.
