### ISSUE TITLE
Sumtrapdf ignores specified page when printing single page from multipage pdf and prints current page shown on screen

### ISSUE THREAD

**Issue by hellomrsax** [sumatrapdfreader/sumatrapdf#3319]
Sumtrapdf ignores specified page when printing single page from multipage pdf and prints current page shown on screen

IE, on an 11 page pdf, if you select to only print page 4, but have page 2 on the screen, it will print page 2.
It does not occur when more than one page is specified.

Tried this on 3.4.6 and latest pre release (3/2/23). Same behavior

Considered the possibility it is a print driver issue, but verified this did not happen with other applications that can view/print PDF's.

Windows 11 22H2.

No judgement here, printers can #*#$ off.

**Comment by GitHubRulesOK** [comment]
not reproducible with current 3.5 plus MS print to PDF ??
here viewing page 3 ask print page 2 that's what I instantly see in the second window.

![image](https://user-images.githubusercontent.com/12754913/222717896-169d8aa2-0ddb-4229-9de6-e61123b74edd.png)

**Comment by kjk** [comment]
Yeah, would need more information i.e. the exact print settings (screenshots of the dialog), is it happening with every PDF or just one etc.
