### ISSUE TITLE
Add tool bar buttons "facing pages" and "save as".

### ISSUE THREAD

**Issue by HiTechHiTouch** [sumatrapdfreader/sumatrapdf#332]
These are the two menu functions I most often use.  A very distant 3rd is custom zoom.

I read a lot of data sheets downloaded from manufactures, and switch between "fit width" and "facing pages", depending on how dense the information is.

When I find a part for which I want to keep the data sheet, then I use "save as".

Perhaps there are people with similar usage patterns to justify adding to the tool bar?

Thanks!

**Comment by kjk** [comment]
We don't have plans to add more features to toolbar. See https://github.com/sumatrapdfreader/sumatrapdf/wiki/Toolbar-design

**Comment by vlakoff** [comment]
Personally what I miss the most is a zoom dropdown. I also miss a way to switch between single/facing/book views.

Some thoughts:
* There are already some buttons in the toolbar for view mode and zoom (and maybe not the most useful ones).
* Despite what is stated in [Toolbar design](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Toolbar-design), apparently Sumatra doesn't offer a context menu solution.
* If you want to remove clutter from the toolbar, you may want to go for the Print button. As a bonus, it might save some paper.
* Adding/removing toolbar items using the advanced options sounds really fine, IMHO.

**Comment by GitHubRulesOK** [comment]
@kjk note two open duplicates showing above #271 & #1117may require similar review for closure
