### ISSUE TITLE
framework 

### ISSUE THREAD

**Issue by mishav78** [sumatrapdfreader/sumatrapdf#3327]
what dot net framework does this project use? 
can you use the code for Android and ios with the visual Studio mobile?

**Comment by GitHubRulesOK** [comment]
In this version it uses raw assembly code , for mobiles see core Artifex MuPDF Libraries

**Comment by mishav78** [comment]
does it use assembly just to render the pdf or for the whole project? Are you saying just replace assembly with the proper functions from the above libraries? can you direct me to the part that needs to be replaced?

**Comment by GitHubRulesOK** [comment]
I have no knowledge of how each part works, basically its hard to port, due to its very broad codebase of many parts. It works as a Wine exe in Linux and possibly under other Windows core emulations but is as you can see from the open source highly dependent on Artifex licensed MuPDF code.
