### ISSUE TITLE
epub格式的有些文本产生了截断

### ISSUE THREAD

**Issue by quicklwl** [sumatrapdfreader/sumatrapdf#3332]
上传不了截图，epub格式的书籍，有些行显示被截断了。

**Comment by kjk** [comment]
Nothing I can do without a sample file that shows the problem.

**Comment by quicklwl** [comment]
Go语言精进之路：从新手到...明) (Z-Library).epub
https://www.aliyundrive.com/s/Rtmo4iDK6K9

看你能下载不？？

**Comment by kjk** [comment]
I can't access the file. Please use something like https://transfer.sh/

Also, provide a screenshot pointing out what's wrong. I don't understand Chinese so it won't be obvious to me what's wrong.
