### ISSUE TITLE
a bug with settings

### ISSUE THREAD

**Issue by AHK0** [sumatrapdfreader/sumatrapdf#3335]
**am 100% sure** about this issue: have tested this with my two computers, one PC and one laptop, OS system win10prox64 and win11prox64 (Administrator privilege)
sumatrapdf, 64bit 3.46 stable **portable version (100% sure)**.

if putting the exe and setting files in a folder under the "C:\Program Files", then the settings document does not work at all, and the software directly generates a new settings in the Appdata\Local, regardless of the settings in the exe folder. 

the setting document works only when the 'exe and settings' are put into any other places in the computer (not the "C:\Program Files").

**Comment by GitHubRulesOK** [comment]
not a bug that's standard windows security behaviours to protect Program Files from data hijacking/contamination.

**Comment by kjk** [comment]
It's as designed: when .exe is inside `Program File` then we don't consider it portable.

The .exe for portable and non-portable is the same so we use heuristics like "was it installed?", "is it outside of Program Files?" to decide portable vs. non-portable use.
