### ISSUE TITLE
Problem opening RAR5 CBRs with SumatraPDF 3.1 64-bit

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#334]
RAR5 CBRs (solid and non-solid both) fail to open with SumatraPDF 3.1 64-bit.

1) Copied unrar.dll 5.30.6.1763 to program directory - File open failed.

2) Copied unrar64.dll 5.30.6.1763 to program directory - Still failed.

3) Copied unrar64.dll 5.30.6.1763 renamed as unrar.dll to program directory - Still failed.

Tried all the above with the portable 64-bit version (SumatraPDF-prerelease-10448-64.exe) but still failed.

SumatraPDF 3.1 32-bit version with 32-bit unrar.dll 5.30.6.1763 still works, just as it did with SumatraPDF 3.0 32-bit, so looks like support for unrar64.dll wasn't added to the new 64-bit version.

[[Link back to forum topic](http://forums.fofou.org/sumatrapdf/topic?id=3184946).]

**Comment by VictorVG** [comment]
@**SumatraPeter** 

Please, read my [**answer in date 29.10.2015 in topic**](http://forums.fofou.org/sumatrapdf/topic?id=3184946). This is no problem, just first need to read the documentation (which many users do not :()

**Comment by SumatraPeter** [comment]
@VictorVG: Please do not accuse people of not reading the documentation without backing up your assertion. All your forum post tells me is how to download and extract unrar64.dll to the SumatraPDF directory. If you had read my original issue text above carefully, I have done all that and more and it didn't work, so it **is** a problem. Test yourself with the 64-bit version whether your 'solution' works.

In any case @zeniko seems to have fixed this with a recent commit (although I haven't tested and confirmed it yet with the latest pre-release version).

**Comment by VictorVG** [comment]
I know, but correction does not negate the need to read the documentation. :)

**Comment by SumatraPeter** [comment]
Which, I repeat, I did (and always do), and hence the irritation when you suggested otherwise.

@zeniko: Thanks, I can confirm that the problem is fixed (tested with SumatraPDF-prerelease-10488-64.exe and unrar64.dll).
