### ISSUE TITLE
Show page number when hovering over page progress bar in EbookUI mode

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#335]
Currently in EbookUI mode when you click on the page progress bar there's no way to know exactly which page you'll land up on. If the page number is shown in a small tooltip or something over the hovering 'hand' pointer, that would make it a lot easier to jump to precisely the one required.

[[Link back to forum topic.](http://forums.fofou.org/sumatrapdf/topic?id=3184585)]

**Comment by GitHubRulesOK** [comment]
Closing as no longer relevant to pre-release change in ebook UI
