### ISSUE TITLE
Ask a printing question

### ISSUE THREAD

**Issue by nine-city** [sumatrapdfreader/sumatrapdf#3371]
I have a 3 page PDF file, but now I only need to print the first page and need to type 5 copies. I print it through the command line, but it doesn't seem to work. Please help me see why. It's normal if I type 1-2 pages

D:\pdf\SumatraPDF-3.4.6-64.exe -print-to-default -print-settings "5x,1-1,fit,color,bin=267,paper=A4" -print-to-default -print-to "Canon G5080" "D:/print_file/names.pdf"

**Comment by GitHubRulesOK** [comment]
use only **one** `-print-to` you have  three !!

`D:\pdf\SumatraPDF-3.4.6-64.exe -print-settings "1,5x,fit,bin=267,paper=A4" -print-to "Canon G5080" "D:/print_file/names.pdf"`
