### ISSUE TITLE
Closing Home tab

### ISSUE THREAD

**Issue by sergsako** [sumatrapdfreader/sumatrapdf#3373]
Latest SumatraPDF pre-release build version 15357, built on 2023-03-21. Two kinds of strange behavior of Home tab.
First: I have two tabs: one is Home, the other one is Doc1. I close Home (click to [X] button) => this closes Doc1 tab, Home page remains --- without tab.
Second: I have three tabs: Home, Doc1, and Doc2. I close Home => this closes Home, and tabs of Doc1 and Doc2 remain. Then I close any of the two, either Doc1 or Doc2, => this closes BOTH tabs simultaneously, Doc1 AND Doc2, but the Home page appears --- without tab.
Probably I'm crazy today.

**Comment by kjk** [comment]
Home tab is not supposed to be closed ever so it's a bug that this happens. Will fix.

**Comment by kjk** [comment]
Hopefully prevented closing home page tab in all cases but please re-open if you find another way to close home tab or any other weirdness with tabs.

**Comment by kjk** [comment]
You can use `NoHomeTab` advanced settings if you don't want it.

**Comment by GitHubRulesOK** [comment]
Hmm
@kjk 
Home tab closes when click where the X would be 🙂 I like it but may  confuse others ?
![image](https://user-images.githubusercontent.com/12754913/227052488-23993768-4753-4b65-8894-474ce0f7f9b7.png)

**Comment by GitHubRulesOK** [comment]
@Ronald-G-Andrade 
to compare visually with any 2 tabs is usually use ALT not CTRL so 
 for example here toggling rapidly between Alt+2 & Alt+3
![image](https://user-images.githubusercontent.com/12754913/227356222-21391a4c-7ada-4598-9d3a-2a31cbbef74b.png)
