### ISSUE TITLE
Tweak caption colors

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#3376]
Now that I figured out how to change caption background color, change it to grayish.

Must also change the tabCtrl background to match and maybe use the same color as mainwindowcolor as progress toward theming.

**Comment by GitHubRulesOK** [comment]
If I recollect for tabs (ecluding their background) there were simply 3 names which I used to "poke" for setting to custom colours, perhaps if expossed in settings-txt those would pacify some users custom needs, the biggest bar to theming is literally that menu bar where inverting colour light to dark is highest request.
