### ISSUE TITLE
Progress bar disappear

### ISSUE THREAD

**Issue by Tuinpad** [sumatrapdfreader/sumatrapdf#338]
I just install the new Sumatra PDF 3.1 64bit.
But now the progress bar (with the slider) in the right on the screen is gone.
Is there a solution to this "bug"?
My OS is Windows 10 64bit

**Comment by kjk** [comment]
Please provide a screenshot. I don't know which progress bar you're referring to.

**Comment by Tuinpad** [comment]
![knipsel](https://cloud.githubusercontent.com/assets/15441116/10868711/1efbf23a-8097-11e5-9dc6-2c5c4ef16582.JPG)

**Comment by Tuinpad** [comment]
You can see there is no slider to scroll in the right of the windows.

Sorry for my bad English

**Comment by kjk** [comment]
Most likely that's because you've selected non-continuous mode, in which case that's expected behavior.

Switch to continuous mode (view/show pages continuously) for scrollbars.
