### ISSUE TITLE
Support Middle Mouse Click and Shift + Click in Taskbar when using tabs

### ISSUE THREAD

**Issue by chris400** [sumatrapdfreader/sumatrapdf#3386]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3384

<div type='discussions-op-text'>

<sup>Originally posted by **chris400** March 26, 2023</sup>
Most applications nowadays support Middle Mouse Click (aka Wheel Click) or Shift + Click on Taskbar to open up a new window. SumatraPDF supports this functionality only, when tabs are disabled. I would like to suggest to support this behavior when using tabs also.</div>

**Comment by kjk** [comment]
I'm guessing what happens is that this starts new SumatraPDF instance and since it has no cmd-line args, it just quits.

We could send a DDE command over to existing instance to open a new window.

**Comment by GitHubRulesOK** [comment]
Click stacked icons on taskbar is different to middle click thumbnails, on bar opens another app instance !!

Calc/Notepad select a window on taskbar seems to be like SumatraPDF middle click closes window,

**Comment by chris400** [comment]
> I'm guessing what happens is that this starts new SumatraPDF instance and since it has no cmd-line args, it just quits.
> 
> We could send a DDE command over to existing instance to open a new window.

I don't want to insist on adding this, would you mind clarifying what "We could..." actually means @kjk ? Is it a development task or a user task, which is already there? 😇

**Comment by GitHubRulesOK** [comment]
@kjk 
I cant test if this is fixed as 2 daily runs have failed

**Comment by kjk** [comment]
fixed in pre-release

**Comment by GitHubRulesOK** [comment]
Hmm may be worth mentioning the dependency on being installed i.e. not a portable facility.
