### ISSUE TITLE
Cannot open XPS files from Autodesk named *.dwfx - only with rename to *.xps

### ISSUE THREAD

**Issue by michaelnum** [sumatrapdfreader/sumatrapdf#3393]
Hello,
Autodesk uses/save XPS-files with the file extension *.dwfx
With the Version 3.3.3 you open this *.dwfx-files.

With the version 3.4.6 and the prerelease 3.5.1x it does not work, only if you rename the file to *.xps.

Does there is a way to get it working or can you change anything?

Thanks

Michael

**Comment by GitHubRulesOK** [comment]
I am closing and adding to #1678
