### ISSUE TITLE
"This file can not be previewed because there is no previewer installed for it" error in outlook

### ISSUE THREAD

**Issue by vineethams** [sumatrapdfreader/sumatrapdf#3400]
We installed SumatraPDF-3.4.6-64-install.exe in C:\Users\username\AppData\Local . Our outlook is 64 bit. 
![Screenshot 2023-03-29 090422](https://user-images.githubusercontent.com/61493966/228400111-e555e5dc-adcf-4ed6-b0d1-c32b73fca714.png)

**Comment by GitHubRulesOK** [comment]
SumatraPDF Previewer is designed for Windows Explorer,  so first check that its working as designed

Outlook is Microsoft Application and thus the PreView function is in their control, ensure About screen confirms outlook is full fat 64bit not 365 or a 32bit OL in 64bit Office  

Also note this is signature of Microsoft Edge previewer.
![image](https://user-images.githubusercontent.com/12754913/228410395-4db4654a-7802-4a4d-b5e1-9b415577cdbe.png)

SumatraPDF should be something like
![image](https://user-images.githubusercontent.com/12754913/228411618-d2802305-e893-4724-b73c-f894065c5bc0.png)


The best suggestions are possibly at https://woshub.com/outlook-attachment-preview-error/

Note that outlook has several on/off functions and Powertoys will also mess about PDF settings. 

Another possibility is that Bluebeam or other PDF handler has hooked that function
