### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Generalize** [sumatrapdfreader/sumatrapdf#3407]
1: Support adjust page width in epub to display more characters in line.
2: Click the bookmark to change the reading progress and then click the backward and Forward buttons to go backward/Forward to the previous/next reading progress instead of turning the page.
3: User customize font family and font size in epub.

**Comment by GitHubRulesOK** [comment]
Issues is primarily for single problems

1) is a "suggestion" that is not common in readers its usually editors adjust page size or content.

2) previous next toolbar icon is for pages,  there are other keys for last location with 
Alt + Left Arrow = Back
Alt + Right Arrow = Forward

3) is  old constantly changing issue see https://github.com/sumatrapdfreader/sumatrapdf/issues?q=is%3Aissue+is%3Aopen+label%3Aebook

**Comment by kjk** [comment]
Don't put multiple things into a single issue. Those were already requested.
