### ISSUE TITLE
The reader blocks when i try to read an epub file

### ISSUE THREAD

**Issue by FrancescoKa** [sumatrapdfreader/sumatrapdf#342]
The reader blocks itself when i try to open an epub file

The message shown in the footer is (in Italian) "Formattazione del libro...0 pagine"

The SO is windows  7 Enterprise SP1 64 bit

Having the 3.0 release i've installed the last one (3.1 64 bit ) but the problem remains the same.

Reproduced with varies different files, the last time with 
E49322-11.epub 
downloaded from 
https://docs.oracle.com/database/121/NEWFT/chapter12102.htm#NEWFT003

I have succesfully opened the epub files with FBReader

Sumatra PDF is continuing working well with PDF files

**Comment by ousia** [comment]
@FrancescoKa, I have just downloaded https://docs.oracle.com/database/121/NEWFT/E49322-11.epub and SumatraPDF-3.1 (32bit) works fine with Wine in Linux.

Could you try the 32bit version?

**Comment by kjk** [comment]
Do you have anti-virus software installed? This is most likely caused by software like anti-virus intercepting file reading calls and causing problems like that.

**Comment by FrancescoKa** [comment]
Hello to all.
i've just installed the 32 bit version and it works
So it's an issue of the 64bit version only.

**Comment by gschenck** [comment]
There is no issue with this epub-file at my computer. I am using the 64-bit version 3.2.10488.

**Comment by ousia** [comment]
@FrancescoKa,

I have checked both latest stable (3.1.1) and unstable (3.2.10488) 64bit versions with the ePub file mentioned above and both worked fine.

Since @gschenck has also tested it succesfully, could you check the ePub file with [stable](http://www.sumatrapdfreader.org/download-free-pdf-viewer.html) and [unstable](http://www.sumatrapdfreader.org/prerelease.html) SumatraPDF 64bit?

**Comment by FrancescoKa** [comment]
Hello.
I've downloaded, installed (via the installer) and tested with some files all the last versions,
stable and unstable, 32 and 64 bit and the problem doesn't repeat anymore
