### ISSUE TITLE
current builds not always accessible

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#3424]
I understand WIP builds are not all uploaded at present, however several report not latest and currently 
The last uploaded 64bit install seems to be inaccessible from the web pre-rel page link

https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/prerel/15463/SumatraPDF-prerel-64-install.exe

{
  "code": "not_found",
  "message": "File with such name does not exist.",
  "status": 404
}

I also noted there was a 32bit upload intentional or not but as its a year since last update it triggers  go to download page. so I was able to update, but others would not know

![image](https://user-images.githubusercontent.com/12754913/230461933-2f7a2fe1-21a4-4421-ba71-02460c3caf86.png)

**Comment by VictorVG** [comment]
Yes, in the morning it was noticed - cURL downloaded the plug.

**Comment by kjk** [comment]
Thanks for letting me know. The current setup is flaky - it just happens. I'm working on changing how this works.

I did restore building and uploading 32-bit builds. I'm not listing them because, well, 32bit windows is long gone and no-one seems to be complaining.

**Comment by GitHubRulesOK** [comment]
well complain or not its darn useful for my really slow 32 bit netbook one of  possibly the typical user that needs new features 
the tear off tabs work well even if a small factor needs the second screen, and looking forward to trying the theming soon ?

**Comment by VictorVG** [comment]
v3.5.15471 Git-604af7ace - all files exists. Big thanks!

**Comment by kjk** [comment]
I've made a change to how things are stores and downloaded. We'll see if it's more robust.

**Comment by VictorVG** [comment]
Ok!

**Comment by VictorVG** [comment]
v3.5.15473 - OK! My simple test scrip download all files
```
@echo off
setlocal enableextensions
if "%1"=="-h" (echo. & echo parameter #1 build number [ , parameter #2 version] & echo Usage: spdfpreld 15301 3.5 or spdfpreld 15301 & echo. & pause & exit)
if "%1"=="--help" (echo. & echo parameter #1 build number [ , parameter #2 version] & echo Usage: spdfpreld 15301 3.5 or spdfpreld 15301 & echo. & pause & exit)
if "%1"=="" (echo. & echo Version required! & echo. & pause & exit)
if "%2"=="" (set vr=3.5) else (set vr=%2)
curl -C - -LRZ --create-dirs --output "SumatraPDF\SumatraPDF-%vr%-x64-install.exe" https://www.sumatrapdfreader.org/dl/prerel/%1/SumatraPDF-prerel-64-install.exe
curl -C - -LRZ --create-dirs --output "SumatraPDF\SumatraPDF-%vr%-x64.exe" https://www.sumatrapdfreader.org/dl/prerel/%1/SumatraPDF-prerel-64.exe
curl -C - -LRZ --create-dirs --output "SumatraPDF\SumatraPDF-%vr%-arm64-install.exe" https://www.sumatrapdfreader.org/dl/prerel/%1/SumatraPDF-prerel-arm64-install.exe
curl -C - -LRZ --create-dirs --output "SumatraPDF\SumatraPDF-%vr%-arm64.exe" https://www.sumatrapdfreader.org/dl/prerel/%1/SumatraPDF-prerel-arm64.exe
echo v%vr%.%1 > SumatraPDF\version.txt
exit
```
