### ISSUE TITLE
tab appearance

### ISSUE THREAD

**Issue by 7ko** [sumatrapdfreader/sumatrapdf#343]
When two tabs are opened it is a bit hard to tell which one is active:

![pdf-clipboard02](https://cloud.githubusercontent.com/assets/15608740/10879026/2277f2f6-815a-11e5-8ac9-59e362e94b19.jpg)

Please consider how it is easy to tell it in the other program:

![pdf-clipboard03](https://cloud.githubusercontent.com/assets/15608740/10879027/227fdad4-815a-11e5-9b6c-bf2ac9afe3ed.jpg)

**Comment by patricktokeeffe** [comment]
SumatraPDF makes the active tab *darker* than inactive tabs, which is backwards w.r.t to every other tabbed program ~~in existence~~ I've used. I disable the tabs feature because this issue is so distracting and counter-intuitive (and I'm here today because I had to re-disable them). 

The solution: make inactive tabs shaded (darker) to indicate they are in the background. Consider this screenshot... which Firefox tab is active? which SumatraPDF tab is active? Which of those questions required less thought?

![sumatrapdf tab problem screenshot](https://cloud.githubusercontent.com/assets/1348834/10896071/782ad5da-816c-11e5-942a-ce67f78b78f5.png)

**Comment by SumatraPeter** [comment]
> SumatraPDF makes the active tab *darker* than inactive tabs

@patricktokeeffe: No it doesn't, not for me at least (tested with 32-bit 3.1 and 3.1.1 after updating just now on Windows 7).

![tabs](https://cloud.githubusercontent.com/assets/15380332/11034737/dc5c3614-8713-11e5-87a7-1512b7ef68c6.png)

**Comment by patricktokeeffe** [comment]
That's interesting @SumatraPeter. Here's a screenshot of SumatraPDF 3.1.1-x64-portable running on Windows 7 Enterprise SP1 x64:

![sumatra-3 1 1-win7x64-screenshot](https://cloud.githubusercontent.com/assets/1348834/11135924/a96f046e-895e-11e5-8507-0b2f53f93b77.png)

Active tab is darker. So... maybe it's x86 vs x64? @7ko what is your environment?

**Comment by 7ko** [comment]
I did a clean install and nothing changed - see the first post, active tab is lighter and after I saw your samples I see the outlines are missing on mine. Is this windows theme-dependent?
PS I have Win 10 x86

**Comment by 7ko** [comment]
I think what makes other programs like Firefox, Edge, etc seem more intuitive is that the tab look like a vertical extension of the underlying UI element (i.e. of a toolbar) . On the other hand, in Sumatra tabs seem to float on top, it doesn't help regardless of which is darker of lighter. I like the visual solution they employed in Firefox, the tabs not only have rounded top corner, but also on the lower part they "blend" into a toolbar with a kind of "skirts".

**Comment by SumatraPeter** [comment]
> So... maybe it's x86 vs x64?

Doesn't seem to be the case.

> Is this windows theme-dependent?

I think you nailed it.

**Windows 7 Ultimate x64** with ***Aero*** theme: Active tab is **lighter**

![win7_aero](https://cloud.githubusercontent.com/assets/15380332/11318111/1fad85e8-906b-11e5-80f7-af6646c879f6.png)

**Windows 7 Ultimate x64** with ***Aero Basic*** theme: Active tab is **lighter**

![win7_basic](https://cloud.githubusercontent.com/assets/15380332/11318128/636dcc02-906b-11e5-98f4-b13c9f673c89.png)

**Windows 7 Ultimate x64** with ***Aero Classic*** theme: Active tab is **darker**

![win7_classic](https://cloud.githubusercontent.com/assets/15380332/11318130/710d52ba-906b-11e5-9695-b473cf0fa1d3.png)

In my previous screenshot on Windows 7 x86 I was using Aero Basic, and @patricktokeeffe seems to be using Aero Classic on Windows 7 x64. The theme being used by @7ko in Windows 10 x86 is not known, so active tab highlighting under the Windows Classic theme needs to be fixed (colors reversed), and perhaps in Windows 10 as well.

**Comment by ofaurax** [comment]
Hello! I'm currently working on this, please have a look at #559

**Comment by GitHubRulesOK** [comment]
Both this thread and its duplicate Selected tab needs more contrast when SumatraPDF window has the focus #559 raise valid observations however closing this one as "superseded" by #559

**Comment by LinuxOnTheDesktop** [comment]
On Sumatra 3.6 x64, and using Windows 10 dark mode without any special theming, [this comment](https://github.com/sumatrapdfreader/sumatrapdf/issues/343#issuecomment-153176151) remains true

> SumatraPDF makes the active tab darker than inactive tabs, which is backwards.

Or, if it is not backwards, it does at least take some getting used to, and is debatable for that latter reason.
