### ISSUE TITLE
[Feature Request] Dark borders when colours are inverted

### ISSUE THREAD

**Issue by alpozcan** [sumatrapdfreader/sumatrapdf#3433]
Hi,
Firstly, thank you for this neat piece of software. It is my favourite PDF viewer by far.

The colour-inversion feature is great (via the `i` key) - I use it all the time when reading documents. However one issue I have is that the borders that fill the space around the pages are white, at least in the 'Fit Content' zoom mode:
![image](https://user-images.githubusercontent.com/9840837/230765003-14621a18-62ae-430d-a866-43ed530b7b46.png)

My eyes would be much happier if those borders also turned black when the colours are inverted.

**Comment by alpozcan** [comment]
perhaps would be implemented as part of https://github.com/sumatrapdfreader/sumatrapdf/issues/3429 but black borders could be an interim solution

**Comment by GitHubRulesOK** [comment]
that background both  historically and currently is controlled by a mix of settngs so was background with GradientColors override for Fixed UI
![image](https://user-images.githubusercontent.com/12754913/230769949-e8acfbdb-6f56-4237-aebf-3e3e838b2d26.png)

closing as not an old or new issue

**Comment by alpozcan** [comment]
Thank you GitHubRulesOK , I found my perfect settings as below.
I didn't find a setting to change the Home page background so that one is still pure white, but it's OK since it doesn't get used much.

```
FixedPageUI [
	TextColor = #ffffc0
	BackgroundColor = #000000
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	GradientColors = #101010 #101010 #101010
	HideScrollbars = true
]
...
```

**Comment by GitHubRulesOK** [comment]
@alpozcan 
for single colour you dont need three or two just `GradientColors = #000000`
