### ISSUE TITLE
EPUB. Font issue with first paragraph

### ISSUE THREAD

**Issue by brian5-1** [sumatrapdfreader/sumatrapdf#3438]
Not sure if this can be catered for, but a particular EPUB file has the issue that I've screenshotted.  The first page of every section has this overridden text.
Let me know if I should send the EPUB file.

Thanks
<img width="568" alt="2023-04-10_09-40-48" src="https://user-images.githubusercontent.com/104744128/230913058-b1cf1796-46fe-4508-8539-faa147354258.png">

<img width="225" alt="2023-04-10_09-45-41" src="https://user-images.githubusercontent.com/104744128/230913530-5daed5bf-9a25-4cc6-843b-2b02b24b345f.png">

**Comment by kjk** [comment]
Please first check with latest pre-release and if it still happens, send me the file as described at https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

**Comment by brian5-1** [comment]
kyk, Thanks for response. Yes, I'm using latest pre-release v3.5.15480 64-bit.  I've attached the EPUB file (which I had to ZIP).
[PardonMyFrench-RachaelMoganMcIntosh.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/11193262/PardonMyFrench-RachaelMoganMcIntosh.zip)

**Comment by kjk** [comment]
mupdf issue which I reported at https://bugs.ghostscript.com/show_bug.cgi?id=706564

**Comment by brian5-1** [comment]
Thanks!

**Comment by planetkalpesh** [comment]
This issue might be same as https://github.com/sumatrapdfreader/sumatrapdf/issues/3341

**Comment by GitHubRulesOK** [comment]
@kjk was not a problem with older Mupdf so unsure how it looks in recent as I am stuck on 1.20
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2c7bb42d-69be-40ad-b450-22161da6cb49)

**Comment by kjk** [comment]
fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/8024e4fe01c980332656b8880808520e671a5bc2
