### ISSUE TITLE
Upgrade MuPDF to latest version

### ISSUE THREAD

**Issue by vgturtle127** [sumatrapdfreader/sumatrapdf#344]
SumatraPDF is two versions behind the latest stable MuPDF.

There are many fixes, improvements, and some new features that could easily be added to SumatraPDF just by upgrading.

New versions are here:

http://mupdf.com/

You can also get the latest source here:

http://git.ghostscript.com/?p=mupdf.git

This would also be a good opportunity to upgrade FreeType or Ghostscript if you use it.

**Comment by KrasnayaPloshchad** [comment]
MuPDF have released v1.8 in 11 November.

**Comment by vgturtle127** [comment]
All the changes seem like they would benefit SumatraPDF! :+1:

**Comment by kjk** [comment]
The issue, as usually, is that it's non-trivial amount of work. Sumatra has a fairly large amount of changes  to mupdf, mupdf changed a lot, upgrading requires lots of work that isn't priority (at least not to me).

**Comment by vgturtle127** [comment]
So what kind of changes are we talking? Are we talking hard-coded Win32 hacks? That seems to be the theme of projects I have worked on as of late. :laughing:

**Comment by kjk** [comment]
https://github.com/sumatrapdfreader/sumatrapdf/blob/master/mupdf/SumatraMuPDF.patch

**Comment by vgturtle127** [comment]
Oh, so you basically customized MuPDF to fit your needs, and as such upgrading is much more difficult. Is there a chance that updating to the latest version is possible in the future? I have been working on a local fork that I have been trying to port to Linux, and so far it is very basic and has many bugs, but it somewhat works and some of the features don't work. Maybe that might help in some way? I had to change the build system and some of the makefiles and stuff...

**Comment by kjk** [comment]
Those are bug fixes and additional features that I don't want to regress.

As a rule I don't promise that something will ever be done.

**Comment by vgturtle127** [comment]
Alright, fair enough.

But you would consider helping with the work if you felt porting it to Linux or upgrading MuPDF would be worthwhile/fun?

**Comment by kjk** [comment]
If I din't close the issue, it remains a possibility.

**Comment by vgturtle127** [comment]
OK. That's all I really wanted to know. :smile:

**Comment by KrasnayaPloshchad** [comment]
@vgturtle127 MuPDF has Git mirrors here:

https://github.com/ccxvii/mupdf 
https://github.com/ArtifexSoftware/mupdf

**Comment by vgturtle127** [comment]
@KrasnayaPloshchad I can just use the official Git and use GitHub to create a fork. Thanks for the mirrors, though. I will copy the links and keep them for future reference.

**Comment by GitHubRulesOK** [comment]
@kjk in progress :-)

**Comment by kjk** [comment]
The port is done, so closing this.

There are regression but we'll need separate issues for them.

**Comment by vgturtle127** [comment]
@kjk Thanks so much! Sorry I didn't see this for so long because I took a break. I hope you're doing well! 😀
