### ISSUE TITLE
Can not display this pdf file.

### ISSUE THREAD

**Issue by WangPingGang** [sumatrapdfreader/sumatrapdf#3442]
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11245965/test.pdf)
![AyqCZdGfjw](https://user-images.githubusercontent.com/29242789/232371929-a2b04806-75db-47d7-8f0f-7b7f17ede59d.png)
Please see attachment, in Adobe Reader, everything is ok.
![bOCZOIuwed](https://user-images.githubusercontent.com/29242789/232372212-2e519300-b0b7-443a-8fd4-587821a7a701.png)

**Comment by GitHubRulesOK** [comment]
The file is not up to standard since file should be bigger with the font included
 However other viewers will look at the font name and use system font

**Comment by kjk** [comment]
If you're the one generating the PDF: yes, this PDF has problems with incorrectly embedded fonts.

SumatraPDF could be improved to handle such mistakes but this is really mupdf issue as we use mupdf for that part.
