### ISSUE TITLE
Feature request: close duplicates / close all left

### ISSUE THREAD

**Issue by pmallot** [sumatrapdfreader/sumatrapdf#3444]
I often open a pdf file to find Sumatra PDF loading 20 other files that I did not close after reading them.
Options to 
- ~~close all~~
- ~~close all but current~~
- ~~close all right~~
- close all left
- close duplicates

would be nice.
Browsers like Firefox and Opera have this feature, in both it is accessed by right-clicking the tab in question.

edit: Some of this has already been implemented in the current dev version. Changed text and title.

**Comment by GitHubRulesOK** [comment]
most of those are "context" available in curent pre-release 
![image](https://user-images.githubusercontent.com/12754913/232549384-8d422570-4139-439c-bd77-db0bd32acec5.png)

**Comment by pmallot** [comment]
@GitHubRulesOK sry, should have checked there first. That's great news. Close all left and close duplicates would be nice, but close all and close others are the really useful ones!

**Comment by kjk** [comment]
I've implemented `CmdCloseAllTabs` and `CmdCloseTabsToTheLeft`.

No plans for `close duplicates`.
