### ISSUE TITLE
Using the old toolbar icons

### ISSUE THREAD

**Issue by exuvo** [sumatrapdfreader/sumatrapdf#3447]
I have troubles quickly identifying the new toolbar buttons which are made of only thin lines.
Each new install i do i try the latest version but i keep going back to 3.2.
Would the new theming support allow me to change the toolbar icons back to the old colored and filled icons?

**Comment by GitHubRulesOK** [comment]
Not likely, bitmap icons were dropped after 3.2 in favour of DPI almost compatible SVG icons, it may be possible to revert your own forked version to use them but as time goes by the reversion would be harder and harder to maintain.

**Comment by GitHubRulesOK** [comment]
@kjk with the switch to DPI aware SVG icons I presume there will not be a revert to bmp icons?

**Comment by kjk** [comment]
yeah, there's no going back
