### ISSUE TITLE
Tabbed view multiple documents simultaneously

### ISSUE THREAD

**Issue by Rok13** [sumatrapdfreader/sumatrapdf#345]
I like the tabbed view, but I would occasionally like to view two documents simultaneously. Could you make something like "Move to other view" in Notepad Plus Plus? And maybe synchronized scrolling?

**Comment by SumatraPeter** [comment]
[Tab mode: allow multiple windows](https://github.com/sumatrapdfreader/sumatrapdf/issues/18) might be implemented some day...

The split window feature request was [rejected](https://code.google.com/p/sumatrapdf/issues/detail?id=1462) by @kjk 4 years ago almost to the day, but perhaps his mind has changed now and either he or @zeniko will be willing to at least consider this for future implementation.

BTW someone did get frustrated with the refusal and [forked](https://code.google.com/p/sumatrapdf-new/wiki/Screenshots) the project to add the split window feature, but development of that version was abandoned a long time ago.

**Comment by balintbabics** [comment]
There is any hope to add this feature to Sumatra? Only this what I miss.

**Comment by kjk** [comment]
Closed as duplicate of #18

**Comment by GitHubRulesOK** [comment]
@kjk close button failure :-) ?
