### ISSUE TITLE
On mouse hover tab a tooltip with title of the book.

### ISSUE THREAD

**Issue by chan18** [sumatrapdfreader/sumatrapdf#3455]
Hi, I’ve been using Sumatra PDF for years and often have 20 to 30 books (PDFs) open at once for research or learning purposes. Since all the book titles have the same first word, it can be difficult to find the specific book I need. A tooltip displaying the title of the book when I hover my mouse over a tab would be incredibly helpful.

**Comment by kjk** [comment]
It's already implemented in pre-release build: https://www.sumatrapdfreader.org/prerelease
