### ISSUE TITLE
How do I create bookmarks (not Favorites)

### ISSUE THREAD

**Issue by Clownsw** [sumatrapdfreader/sumatrapdf#3459]
How do I create bookmarks (not Favorites)

**Comment by GitHubRulesOK** [comment]
use a pdf writer/editor since the PDF need total rewriting or fully appending with existing page catalogue replaced. One simple line tool is pdftk another that may be useful is coherent cpdf (personally I use GUI tracker or my paid up SoftMaker FreePDF editors)
