### ISSUE TITLE
Older portable SumatraPDF's update checker doesn't see the newer versions.

### ISSUE THREAD

**Issue by antdude** [sumatrapdfreader/sumatrapdf#346]
On my Windows XP Pro SP3 machine. I had to manually download the (new/lat)est version from the web site. :(

**Comment by kjk** [comment]
Which version?

If 3.0, then it's expected for now as we delay auto-updates. See https://github.com/sumatrapdfreader/sumatrapdf/wiki/Update-check-doesn't-work%3F

**Comment by antdude** [comment]
Yeah, v3.0. Thanks. :)

**Comment by kjk** [comment]
It will work in a week or so.
