### ISSUE TITLE
Opening a relative Link to an DOCX doesn't work

### ISSUE THREAD

**Issue by hilavoku** [sumatrapdfreader/sumatrapdf#3461]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3457

<div type='discussions-op-text'>

<sup>Originally posted by **hilavoku** April 22, 2023</sup>
Hello.

I searched the forum to see if anyone else had the same problem, but I didn't find anything similar.

I have a PDF file that contains a relative link to a Word DOCX file.
When I open the PDF file and click on the link in SumatraPDF, I get the error message "Error loading C:\Applications\SumatraPDF\Test-PDF.docx".
If I change the UseTabs = true setting in SumatraPDF-settings.txt to UseTabs = false and then click on the link, the behavior is now different. SumatraPDF opens another instance of SumatraPDF, which displays the same error message, but immediately opens the DOCX document with Microsoft Word. 

Very strange behavior. I have tried all the different SafeFileTypes settings in sumatrapdfrestrict.ini, but no change.

Has anyone else had the same observations?

When I open the PDF with FoxitReader and click on the link, after a confirmation prompt, the Word document opens immediately.

Thanks in advance for any tips.</div>
[Simple.docx](https://github.com/sumatrapdfreader/sumatrapdf/files/11311948/Simple.docx)
[Simple.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11311949/Simple.pdf)

**Comment by kjk** [comment]
In pre-release we now open .docx documents because mupdf supports them.

So it kinda solves this issue.
