### ISSUE TITLE
Text partially clipped in SumatraPDF

### ISSUE THREAD

**Issue by tactilis** [sumatrapdfreader/sumatrapdf#3463]
Using the latest SumatraPDF pre-release, the text "HM Land Registry" is clipped:

![image](https://user-images.githubusercontent.com/4060092/234073044-ed1ce5f7-7257-4888-9d57-61ac9624bc0d.png)

<br>

In Acrobat, Firefox, Chrome, etc the text is rendered correctly:

![image](https://user-images.githubusercontent.com/4060092/234072129-ec0a19ac-35bf-459b-a13c-26d2ec5f035a.png)

<br>

Here's page 1 of the document:

[TR1 v1 TEST.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11313094/TR1.v1.TEST.pdf)

**Comment by GitHubRulesOK** [comment]
Interesting the two texts are images so the second ones transparency as a mask is "masking" the first one as overlapped

![image](https://user-images.githubusercontent.com/12754913/234088261-1bd32427-e2df-4677-be1d-2dfa91022738.png)

Unknown if thats MuPDF strugling with a poor PDF definition of image as is well below good use of the area
![image](https://user-images.githubusercontent.com/12754913/234089188-feab7ac7-fb46-4b91-aa86-ebe17fb175ef.png)

**Comment by tactilis** [comment]
The original government document from the UK Land Registry is here: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/548684/TR1.pdf

It contains an amateurish paste of a single image as you can see from the JPEG artefacts surrounding the letters:

![image](https://user-images.githubusercontent.com/4060092/234097055-96767520-3131-4061-9935-e25f9da0e081.png)

It appears that somewhere along the line, someone has split the image into two (with an overlap) and changed them to pure black and white.

The fact remains that MuPDF renders the images badly, whereas all the other apps I've tried cope with the transparent overlap OK.

**Comment by GitHubRulesOK** [comment]
@tactilis agreed MuPDF should behave similar to other viewers, such as acrobat etc. but my fixed version above is how I would have suggested in QA the issue be handled by the author if not rejected for other reasons.

**Comment by GitHubRulesOK** [comment]
closing as fixed before / by 3.5 release
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d22b3a77-433c-4f37-95d1-89ee11fd960d)
