### ISSUE TITLE
Brand new- How to use as KIOSK fullscreen?

### ISSUE THREAD

**Issue by gtlighthouse** [sumatrapdfreader/sumatrapdf#3465]
Hi guys, I'm an historian, not a coder/programmer etc. I thought SumatraPDF could be what I need- trying to load an interactive, local, offline PDF on a Windows 10 pc as a fullscreen kiosk mode upon startup... I've placed the sumatrapdfrestrict.ini file in the same directory, I've modified and saved the Advanced text file for Sumatra, I've made a shortcut and changed target in Properties, but all of this and the PDF doesn't open on startup. When I open the PDF manually with Sumatra as default, it opens in the default screen, meaning not fullscreen and the scrollbar and taskbar are there even though I've asked settings not to load them. What am I doing wrong? What do you need from me? I need help in general with this and don't know where to turn after multiple, multiple google searches. thanks.

**Comment by GitHubRulesOK** [comment]
For MS edge it would be (restricted no toolbar ?
```
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --kiosk --no-first-run --edge-kiosk-type=fullscreen "file:///C:/Index.pdf#toolbar=0"
```
 or similar

**Comment by gtlighthouse** [comment]
Thanks so much for answering! I have struggled and struggled with the Microsoft Edge option but there's no way it works for me, because my PDF is local and offline and I have no access to the internet.

I don't necessarily know HOW to even write CMD fullscreen directives- is this through the PowerShell (msconfig)? Because when I tried that, all that did was open SumatraPDF again with its defaults.

Every time I tried to open the pdf in Edge single-app kiosk mode, it opened with the taskbar visible and not in fullscreen. I don't know why! It also gave me a "restrictions access" error just before opening the PDF.

I'm not even sure which subreddit to ask this question in, to access more help. maybe some kind of discord server?

**Comment by GitHubRulesOK** [comment]
Sumatrapdf will remember last screen position so if I `start "" SumatraPDF` a fresh copy it looks like 
![image](https://user-images.githubusercontent.com/12754913/234639138-325fa1ff-f5b9-4fab-a2ae-8bbf5d698a78.png)

**Comment by gtlighthouse** [comment]
Is there no way to remove the taskbar above? I tried targeting "-presentation" and nothing changed. Is there a way to make Sumatra listen to my commands rather than "remembering" the last-time-it-was-opened settings and applying them upon launch? thanks

**Comment by GitHubRulesOK** [comment]
use -fullscreen on command line

**Comment by kjk** [comment]
It's a question, not a bug report. It belongs in Discussion

**Comment by GitHubRulesOK** [comment]
You can not add switches to end of a default shortcut.lnk it needs to include the "blah blah.exe" so take a SumatraPDF shortcut and add the command switch and filename to that.  
![image](https://user-images.githubusercontent.com/12754913/234652350-3f56b108-7b72-4a39-bac5-02fea9d03158.png)
![image](https://user-images.githubusercontent.com/12754913/234652646-98ebe517-6086-4c24-9236-a80e2eb5e599.png)
