### ISSUE TITLE
Microsoft Edge has fullscreen -kiosk mode However Sumatra needs to be started with CMD fullscreen directives.

### ISSUE THREAD

**Issue by gtlighthouse** [sumatrapdfreader/sumatrapdf#3466]
Microsoft Edge has fullscreen -kiosk mode However Sumatra needs to be started with CMD fullscreen directives.

So do you want edge viewer or SumatraPDF as Windows Start-UP viewer with only one file ?

_Originally posted by @GitHubRulesOK in https://github.com/sumatrapdfreader/sumatrapdf/issues/3465#issuecomment-1523688326_
 
Thanks so much for answering! I have struggled and struggled with the Microsoft Edge option but there's no way it works for me, because my PDF is local and offline and I have no access to the internet. 

I don't necessarily know HOW to even write CMD fullscreen directives- is this through the PowerShell (msconfig)? Because when I tried that, all that did was open SumatraPDF again with its defaults.

Every time I tried to open the pdf in Edge single-app kiosk mode, it opened with the taskbar visible and not in fullscreen. I don't know why! It also gave me a "restrictions access" error just before opening the PDF.

I'm not even sure which subreddit to ask this question in, to access more help. maybe some kind of discord server?

**Comment by GitHubRulesOK** [comment]
"C:\Program Files\SumatraPDF\SumatraPDF.exe" -fullscreen "C:\Apps\test 2.pdf" should look like (ignore my personal toolbar)

![image](https://user-images.githubusercontent.com/12754913/234648417-fb4b1fcd-cdb0-4e5a-b6c5-80ec023881be.png)
