### ISSUE TITLE
new feature: clean up list of recent open file

### ISSUE THREAD

**Issue by r9nunes** [sumatrapdfreader/sumatrapdf#3471]
I suggest add a new feature: clean up list of recent open file. Currently, to do this, the user go to "advanced options" is manually remove the list

**Comment by GitHubRulesOK** [comment]
Two shortcuts 
- Old one was in standard options switch off then on remember it clears all history EXCEPT favorite ones
- New one use history command from Ctrl K 
![image](https://user-images.githubusercontent.com/12754913/235210455-22b55309-263d-4806-a112-4c358ac31875.png)
