### ISSUE TITLE
3.5 pre-alpha does not maintain text highlight when changing documents

### ISSUE THREAD

**Issue by githwithit** [sumatrapdfreader/sumatrapdf#3473]
Using Win10, Sumatra 3.4.6, viewing epubs, highlighting text is maintained when changing tabs from doc1 to doc2.

But Sumatra 3.4.6 does not correctly display one of my epubs so I tried the pre-alpha.

I tried pre-release build version 15481 built on 2023-04-18 which displayed the epub correctly but text highlighting is not maintain when change from doc1 to doc2.

I tried setting "HighlightPermanent = true" thinking it might help but it did not.

I am reverting to 3.4.6 and will use Calibre from the one epub that does not work with Sumatra 3.4.6.

I hope Sumatra 3.5 will have the text highlighting fixed since I like it better than Calibre.

**Comment by GitHubRulesOK** [comment]
I see no difference in my test highlighted pdf in both tabs then go back and forth the highlight is still visible.

Please describe your steps in detail with possibly supply any test files that itself causes such issue.

**Comment by githwithit** [comment]
both docs are epubs
epub1 = https://www.gutenberg.org/ebooks/70681.epub3.images
Slavery: Letters and Speeches by Horace Mann - EPUB3 (E-readers incl. Send-to-Kindle) 661 kB
epub2 = https://www.gutenberg.org/ebooks/70683.epub3.images
The doom trail by Arthur D. Howden Smith - EPUB3 (E-readers incl. Send-to-Kindle) 423 kB

**win10 sumatra 3.4.6**
1 window
2 document tabs

click tab1 to view epub1
tab1: control-f on "_desire of some form of happiness_" and the text is found and highlighted in epub1
click on tab2 to view epub2
tab2: control-f on "_where our women sowed and reaped and our_" and the text is found and highlighted in epub2

click tab1 to view epub1
"_desire of some form of happiness_" is highlighted << 3.4.6 works
click on tab2 to view epub2
"_where our women sowed and reaped and our_" is highlighted << 3.4.6 works

**win10 sumatra 3.5.15481 pre-release**
1 window
2 document tabs
both docs are epubs

click tab1 to view epub1
tab1: control-f on "_desire of some form of happiness_" and the text is found and highlighted in epub1
click on tab2 to view epub2
tab2: control-f on "_where our women sowed and reaped and our_" and the text is found and highlighted in epub2

click tab1 to view epub1
NOTHING is highlighted << 3.5.15481 does not work
click on tab2 to view epub2
NOTHING is highlighted << 3.5.15481 does not work

**Comment by GitHubRulesOK** [comment]
Find and highlight are now more tied as if one, So it works for one file per window, thus drag that tab off and you can have two selections
The ability in 3.4.6 was agreeably more independent, so selection was not as tightly bound
@kjk do you want to class as a regression ?

![image](https://user-images.githubusercontent.com/12754913/235461291-198d55d7-8067-45e4-b66a-2df67fe164de.png)

**Comment by kjk** [comment]
Simple repro:
* select text in one tab
* switch to another tab
* switch back

Selection is lost because when switching tabs we call `CloseDocumentInCurrentTab()` which calls `DeleteOldSelectionInfo()`.

Have to look why it didn't happen in 3.4.6 (we did re-do loading process and tab handling a fair bit).

Selection is per-tab thing but we treat it as a per-Window thing hence the desire to clear Window state when switching tabs.

Not sure what happens if we just not call  `DeleteOldSelectionInfo()`.

Also: MainWindow::showSelection: instead of maintaining in manually, it could be:
````
bool MainWindow::IsShowingSelection() const {
    // TODO: include MouseAction::SelectingText ???
    if (mouseAction == MouseAction::Selecting || mouseAction == MouseAction::SelectingText) {
        return true;
    }
    WindowTab* tab = CurrentTab();
    if (tab) {
        return tab->selectionOnPage != nullptr;
    }
    return false;
}
```

**Comment by kjk** [comment]
Did a non-working `MainWindow::ShowingSelection` on https://github.com/sumatrapdfreader/sumatrapdf/tree/selection

Broken because not showing selection during mouse selection.

Also, must be clean build or else is showing the weirdest crashes.
