### ISSUE TITLE
Older versions not downloadable

### ISSUE THREAD

**Issue by ErikNikolajsen** [sumatrapdfreader/sumatrapdf#3474]
One receives a 404 error when trying to download Sumatra version 3.1.2 or older via the webpage: "https://www.sumatrapdfreader.org/download-prev".

**Comment by GitHubRulesOK** [comment]
Agreed
for 3.1.2 should be clean download from
https://www.filehorse.com/download-sumatra-pdf-64/27202/
https://www.filehorse.com/download-sumatra-pdf-32/27203/

**Comment by miloush** [comment]
URLs on https://web.archive.org/web/20211127165802/https://www.sumatrapdfreader.org/download-prev seem to mostly work.

**Comment by kjk** [comment]
Sorry it took so long. It should work now.
