### ISSUE TITLE
Files that have been confirmed not to exist are not deleted from "Recently Opened" after an open failure.

### ISSUE THREAD

**Issue by KargathEx** [sumatrapdfreader/sumatrapdf#3484]
![111](https://user-images.githubusercontent.com/40135358/236658935-deae8d82-dfa4-40ba-b6e4-e6e58c6d499d.gif)

As shown in the figure.

**Comment by kjk** [comment]
It's not obvious that they should be.

Some files live in drives that can be inaccessible for a while: unplugged usb drive, dropbox when you have no internet connection.

In those cases removing the files is not necesarily the right thing to do.

**Comment by KargathEx** [comment]
Perhaps we could add an option to pop up a dialog box when the text does not exist, asking if we want to remove this entry from the recently opened list
