### ISSUE TITLE
[bug] white text on black block is mis-rendered and invisible

### ISSUE THREAD

**Issue by jeremyhetzler** [sumatrapdfreader/sumatrapdf#3488]
PDF invoices from Verizon Wireless render incorrectly in SumatraPDF v3.4.6 64-bit.

In SumatraPDF, the text of the account number is unreadable.

The same file renders correctly in Acrobat and Chrome.

Acrobat:
![ex-acrobat](https://github.com/sumatrapdfreader/sumatrapdf/assets/4957082/b20aefea-7c39-42b7-82d0-e50252216003)

Chrome:
![ex-chrome](https://github.com/sumatrapdfreader/sumatrapdf/assets/4957082/ec41f252-9aec-438a-bf03-d30d8f586e09)

SumatraPDF:

![ex-sumatra](https://github.com/sumatrapdfreader/sumatrapdf/assets/4957082/2f84da59-347b-4026-9288-70e68c8d69ef)

**Comment by GitHubRulesOK** [comment]
hmm 1st check it out in pre-release portable will do https://www.sumatrapdfreader.org/prerelease

if still a problem the file would need to mailed to developer kkowalczyk@gmail.com

**Comment by kjk** [comment]
can't investigate without a sample file
