### ISSUE TITLE
[Feature request] Text "Bionification"

### ISSUE THREAD

**Issue by sdasda7777** [sumatrapdfreader/sumatrapdf#3491]
Hi, would it be possible to include some options for text "bionification"? [bionify](https://github.com/Cveinnt/bionify) seems to be open source implementation of the algorithm, so there shouldn't be any issues from Bionic Reading®.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/17746796/e470f180-7cba-4d66-940a-a6b9e58957d3)

**Comment by GitHubRulesOK** [comment]
Whilst thats possible with some file formats like Word processors, it would not be possible to do that in native pdf contents,

PDF contents are not what you see they are binary numbers that can be in random orders and a named set of characters are applied to those numbers (his is called CMAPing in some few cases its as simple as binary %20 or \x20 or decimal 032 will be screened as a White space in Times -Roman but that same number can be allocated to BoLD ***G*** in Comic Sans in another file.

Thus to substitute appearance you would need every font on the planet included inside the PDF

**Comment by sdasda7777** [comment]
I see, and what about other formats, such as epub?

**Comment by kjk** [comment]
not possible with our pdf / epub engine.

**Comment by sdasda7777** [comment]
Yes, if it was possible to do, this issue wouldn't exist in the first place. I don't see why this issue was closed, much less why it was closed as completed.

**Comment by tactilis** [comment]
> I don't see why this issue was closed

Did you read and understand what @GitHubRulesOK and @kjk wrote?

<br>

> much less why it was closed as completed.

'Completed' doesn't necessarily mean that a feature is implemented.

The issue discussion is Closed as Completed. There is nothing more to say as it is not possible to implement what you asked for.

**Comment by GitHubRulesOK** [comment]
ok the choice could be the different tag as "Not planned" (i.e. Can't fix) but the default close with comment is set by GitHub as "Completed" whatever the reason lets see what happens when I try that button

**Comment by sdasda7777** [comment]
Nice, thanks
