### ISSUE TITLE
PDF text is misrendered, practically unreadable

### ISSUE THREAD

**Issue by Darkmaster006** [sumatrapdfreader/sumatrapdf#3500]
On Sumatra:
![imagen](https://github.com/sumatrapdfreader/sumatrapdf/assets/21136515/4dcf4c87-492d-4990-879f-52ab278c7a3c)
On Firefox:
![imagen](https://github.com/sumatrapdfreader/sumatrapdf/assets/21136515/74c8b010-1c90-4261-b14d-573948a1540b)
On Opera:
![imagen](https://github.com/sumatrapdfreader/sumatrapdf/assets/21136515/da849542-c658-4195-aaa5-7e03bcd41d42)
On Edge:
![imagen](https://github.com/sumatrapdfreader/sumatrapdf/assets/21136515/eae75ce1-62b2-4923-99bd-01694ea1815a)

As you can see, the text is practically unreadable and weirdly blurry in Sumatra, seems like it can't process it correctly. This happens with some files.

**Comment by kjk** [comment]
can't investigate without a sample file.

**Comment by Darkmaster006** [comment]
> can't investigate without a sample file.

[GANSHOF, François-Louis - Frankish Institutions under Charlemagne (1968).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12615174/GANSHOF.Francois-Louis.-.Frankish.Institutions.under.Charlemagne.1968.pdf)
This is the file I used. Hope it can be investigated. Thank you!

**Comment by GitHubRulesOK** [comment]
@Darkmaster006 
There is practically little can be done with that file other than Either rescan or reprint.

To explain why see this first 6 pages reversal at a "lower" resolution 
[Frankish.Institutions1-6.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12618626/Frankish.Institutions1-6.pdf)

The problems seen are the pages have been scanned with poor decisions, so the format is black and white but with a tonal mask of white pixels (grey tone/greyscale/halftone) which reduces quality by 50% if done at high resolution the readability is possible but the lower the resolution the worse the readability. It is like good old fashioned Facsimile printing

**Comment by kjk** [comment]
Reported to mupdf: https://bugs.ghostscript.com/show_bug.cgi?id=707136

**Comment by GitHubRulesOK** [comment]
hmm 
@kjk 
mupdf say fixed 
op file is fine 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/3af0deef-3b62-4489-b831-cbf9809e6db2)


HOWEVER SumatraPDF 3.6 crashed on test file
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/13110197/sumatrapdfcrash.zip)
[3500 badimage.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13110199/3500.badimage.pdf)

**Comment by kjk** [comment]
Crash should be fixed as well as rendering.

**Comment by Darkmaster006** [comment]
> Crash should be fixed as well as rendering.

How can I fix it? Still looking the same for me. Thank you.

**Comment by GitHubRulesOK** [comment]
@Darkmaster006 
The file is poor halftone but the Bigger white gaps issue has been reduced to "fixed" quality as per specs in Most recent updates
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/ff99ffa2-1304-4360-946d-3cba3a932393)

**Acrobat top left cannot see the page contents ! SumatraPDF top right is NOW no worse than Edge or Exchange**  
   
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/abe0502e-5235-4610-9941-c0db1cc03a73)

**Comment by Darkmaster006** [comment]
> @Darkmaster006 The file is poor halftone but the Bigger white gaps issue has been reduced to "fixed" quality as per specs in Most recent updates ![image](https://user-images.githubusercontent.com/12754913/278196255-ff99ffa2-1304-4360-946d-3cba3a932393.png)
> 
> **Acrobat top left cannot see the page contents ! SumatraPDF top right is NOW no worse than Edge or Exchange**
> 
> ![image](https://user-images.githubusercontent.com/12754913/278198184-abe0502e-5235-4610-9941-c0db1cc03a73.png)

Looks good! Great fix. I will try with the latest update, though, thought I had it. Thanks!
