### ISSUE TITLE
Implement Ctrl + Backspace (Delete the word to the left of the caret) in Edit control

### ISSUE THREAD

**Issue by raynerdacruz** [sumatrapdfreader/sumatrapdf#3502]
**Keyboard shortcut:** 
Ctrl + Backspace. 

**The action associated with the keyboard shortcut:** 
Delete the word to the left of the caret.

**Expected behaviour:** 
The word to the left of the caret is deleted.

**Actual behaviour:** 
Inserts a rectangle i.e. the non-renderable character symbol.

Fyi, deleting the word to the right of the caret with ( Ctrl + Delete ) works as expected - i.e. the word to the right of the caret is deleted.

Can you please fix the bug?

Thank you.

**Comment by GitHubRulesOK** [comment]
Its working for me Ctrl +Backspace end of line or mid line removes word to left Can only be tested in Pre-Release for any future changes.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/13e0601e-77f4-477e-912a-166b49f22685)
then Ctrl + BS
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/8d32510a-5678-4822-9515-8a13e677586c)

**Comment by raynerdacruz** [comment]
Hmmm interesting, it seems to work in the Find text field as you've shown, but not in the Content text field within the Annotations window.
![SumatraPDF_GhW0onz61D](https://github.com/sumatrapdfreader/sumatrapdf/assets/10243952/cae624aa-f516-4e21-b8a0-7e9a2d6888c7)

**Comment by raynerdacruz** [comment]
Btw, I'm running the latest stable release v3.4.6. If you're running the pre-release can you check if this is fixed?

**Comment by GitHubRulesOK** [comment]
I doubt its fixed in "official" pre-release as its not recently altered much there HOWEVER see users modification at https://github.com/sumatrapdfreader/sumatrapdf/discussions/3489#discussioncomment-5909905

**Comment by raynerdacruz** [comment]
Could it be that the event handler of SumatraPDF for handling keyboard shortcuts is not handling the Ctrl + Backspace key combination properly? Because when I open the PDF file in Adobe Acrobat and try to edit the annotations, i.e. delete words to the left of the caret, I don't face the same problem that I described in my opening post. Have a look.

![Acrobat_S7IziD7EDX](https://github.com/sumatrapdfreader/sumatrapdf/assets/10243952/d63ae2da-f8d8-411f-88a5-05b7e62a5a8a)

**Comment by raynerdacruz** [comment]
Btw, the annotation in this GIF was **created in SumatraPDF** but edited in Adobe Acrobat.

**Comment by GitHubRulesOK** [comment]
@raynerdacruz 
The core of SumatraPDF annotations is MuPDF source so unknown by me if its a SumatraPDF dialog or Mupdf text box cause, hence not yet tagged as MuPDF until developer can review.

I suspect its more likely MS VS constraint

**Comment by raynerdacruz** [comment]
Thanks, I appreciate your input on this issue. I hope it gets fixed sooner rather than later. For now, I guess I could just use the Ctrl + Delete as a workaround by moving the caret to the left of every word that I want to delete. Or just try to keep the typos to a minimum 😏.

**Comment by kjk** [comment]
That's because we have custom code to implement Ctrl + Backspace for search edit control (`ExtendedEditWndProc()`, `UWM_DELAYED_CTRL_BACK`) and not for other edit controls. Would have to implement similar logick in `Edit` control in `WinGui.cpp`
