### ISSUE TITLE
zoom support for epub

### ISSUE THREAD

**Issue by RedDragonWebDesign** [sumatrapdfreader/sumatrapdf#3507]
Can't currently get epub formatted files to zoom in/zoom out/change font size. This is a feature request to have epubs act more like PDFs, with zoom features. Please let me know if you need more info for this ticket, such as a screenshot, my versions, or an example file. Thank you for your consideration.

**Comment by GitHubRulesOK** [comment]
Zoom has always been there
but not so obvious as in more recent Releases as it previously needed a false true setting for Fixed UI
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/0c175fab-01c1-46c0-ae71-4839d0f6bab4)

Here is Current Pre-relase where there is no choice, its with zoom or with zoom only, and no longer a possibility to alter font scale.

**Comment by alexnguyennz** [comment]
Was trying to find this out - just had to update my version of SumatraPDF. Was still running 3.1.2 from about 5 years ago (where epubs had that different limited yellow view with no zoom so likely OP just is using a very old version).

**Comment by RedDragonWebDesign** [comment]
Thanks for pointing that out. Confirmed working in current version. Closing.
