### ISSUE TITLE
Add the ability to open a folder full of images

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#351]
SumatraPDF can save a CBZ or CBR as a PDF. However if I want to save a bunch of sequentially numbered images as PDF I need to archive them first and then save as PDF using Sumatra. Instead it would be great if this process could be simplified by enabling Sumatra to open a folder full of images, which can then be saved as a single PDF. Of course this would also help when one just wants to view a folder full of images that are not/cannot be archived for some reason.

**Comment by kjk** [comment]
You can already open a folder with images by drag&droping the folder for explorer onto Sumatra.

As to converting images to a PDF - sumatra is a mostly viewer, not an editor and we don't plan to add that specific functionality.

**Comment by SumatraPeter** [comment]
Thanks; all I wanted was the ability to open a folder full of images as a *single* document so that I could use Sumatra's existing Save As PDF feature to save them all as one PDF. Turns out that by dragging & dropping folders I can do just that, so no new functionality is required. Love Sumatra!

**Comment by GitHubRulesOK** [comment]
Just to confirm once a folder is open relative navigation is possible
<Ctrl> + <Shift> + Right   open next document in the directory 
<Ctrl> + <Shift> + Left   open previous document in the directory

**Comment by GitHubRulesOK** [comment]
`<Ctrl> + <Shift> + Right   open next document in the directory `
`<Ctrl> + <Shift> + Left   open previous document in the directory`

**Comment by GitHubRulesOK** [comment]
Just to confirm once a folder is open **relative navigation is possible**

`<Ctrl> + <Shift> + Right open next document in the directory` 
`<Ctrl> + <Shift> + Left open previous document in the directory`
