### ISSUE TITLE
Type 3 font rendering regession from 3.3.3 to 3.4.x

### ISSUE THREAD

**Issue by ThomasKrenn** [sumatrapdfreader/sumatrapdf#3513]
Hello,

Sumatra 3.3.3

![sumsi_333](https://github.com/sumatrapdfreader/sumatrapdf/assets/24775002/576034d3-8495-401b-8053-561fd5876485)

versus Sumatra 3.4.x

![sumsi_340](https://github.com/sumatrapdfreader/sumatrapdf/assets/24775002/fb7efa16-c076-45e6-92c2-727fd0ee3472)

Type 3 font rendering was a strength of Sumatra, no other viewer (including Foxit) had such a precise rendering when displayed with 100% resolution.

The PDF document can be found here:

[tt_test_psg_change300.pdf](https://www.yellowsubroutine.com/content/privatemk/tt_test_psg_change300.afp.pdf)

This is not the same issue as in:
https://github.com/sumatrapdfreader/sumatrapdf/issues/3232
because it is a verified PDF/A document with correct font embedding.

Best regards
Thomas

**Comment by GitHubRulesOK** [comment]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/988b1702-b736-4446-b793-f661e64eafc1)

OH dear its one that passes the rules but the font is POOR as displaced its 0.1 thick stretched to 0.1 high but replace with an 8pt font and all the letters are defined upside down and inside out
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/de5530e7-1c58-4a9a-97b4-eee3dc270dc2)

**Comment by ThomasKrenn** [comment]
Thanks for your fast response.

The Pre-release version (build version 15481, built on 2023-04-18) has better rendering quality. Thanks for the hint.

Yes, it is a font with poor (bitmap) quality. Unfortunately this kind of fonts are still in use.

Best regards
Thomas

**Comment by ThomasKrenn** [comment]
Solved with: build version 15481, built on 2023-04-18
