### ISSUE TITLE
Please support background image

### ISSUE THREAD

**Issue by kelilife** [sumatrapdfreader/sumatrapdf#3519]
I want to use it to read plain text e-books, and I want to set a beautiful and romantic light-colored background outline (in order not to affect the text display) to fill the whole background plane (including the blank area on both sides).

Of course, the so-called content page area can be adjusted by adjusting the transparency of the way to decide whether to see through the underlying background image, so it should be able to solve the trouble caused when displaying pdf and other formats.

These are some of my personal views, I hope you can consider, thank you.

Reference:
https://github.com/sumatrapdfreader/sumatrapdf/issues/3520

**Comment by GitHubRulesOK** [comment]
you set the side colour as one 2 or three via GradientColors but you cant set canvas that needs to be white as we don't have see through hololens monitors yet like in the star wars movies. Generally the backdrop needs to be a solid contrasting black colour for showing white pages or solid scanned images on.

**Comment by kelilife** [comment]
Perhaps a lot of things need to be changed, and I'm just asking for it from a user perspective. Maybe a series of issues will be involved, it doesn't matter if none of them are supported, it's just an idea I have.

**Comment by GitHubRulesOK** [comment]
try gradient colour settings in advanced but they will be "flat" single colours from side to side, the gradient shift is only vertical.

**Comment by kelilife** [comment]
[Demo.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11600187/Demo.pdf)

https://github.com/sumatrapdfreader/sumatrapdf/assets/115648681/ff987b20-c773-4854-983c-eb48ee523bc4

**Comment by GitHubRulesOK** [comment]
you mean something like set paper color but it can only be one device colour your pdf has different coloured pages.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/aca02e6c-0458-4aed-939d-fb668ece87a4)

**Comment by kelilife** [comment]
The background I have is a picture, not a solid color. In fact expect to achieve a converter that can set the background image, I this pdf file with Acrobat editor processed.

**Comment by GitHubRulesOK** [comment]
SumatraPDF is not an Editor and the work in progress to stamp images would hide any text as it would become an annotation top layer  not what you want which is an underlay so needs to be written first as the page canvas. you can do all this in HTML and print to PDF its just not what a viewer/reader application is designed for Acrobat is how many files spread throughout the system and how many staff did I pay for when I purchased their editor?

**Comment by kelilife** [comment]
However, it still seems that the implantation of the pdf is not quite right. The main problem is that each page has a background, and the size needs to just fit the size of the more troublesome, and if there is a lot of content, will cause the file size is too large.

**Comment by GitHubRulesOK** [comment]
size of images is gigantic so PDF is always going to be big if included every single dot of ink tates up 24 bits of clear background space PDF is a hog when scanned or carrying backgrounds hence most PDFs will not have a background.

**Comment by kelilife** [comment]
If I had the energy maybe I should write a minimalist reader.
