### ISSUE TITLE
Add option for all supported image formats to the File Open dialog

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#352]
The wiki states the various [image formats supported by the program](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Supported-formats) (although I'm not sure whether it's an exhaustive list).

The formats aren't included in the File Open dialog though (see screenshot below), so the only way to see them is to select **All files** which naturally displays all other unsupported file types as well.

Instead it would be nice to have a new filter option added to the dialog similar to **All supported documents** called **All supported image formats** or **All supported image formats (.tga, .gif, .jpg, .j2k, .png, .webp, .tiff)**, which would display only the formats supported by the program.

![open_dialog](https://cloud.githubusercontent.com/assets/15380332/11036916/15f082a6-8721-11e5-93bb-2333ec5ec70a.png)

**Comment by kjk** [comment]
We support images but it's not a big selling point so I don't see a reason to advertise it more.

**Comment by SumatraPeter** [comment]
Honestly, adding a filter to the File Open dialog is trivial and I see no downside at all to 'advertising' image support a bit more, but you're the final judge of course.

**Comment by isidroco** [comment]
kjk, I totally disagree about not being a good selling point, this would be a great light image viewer. In fact I couldn't find yet a light viewer of .CB7 and .JPGs folders I'm happy with, and Sumatra could have been that program, but it doesn't allow to navigate through JPGs, or directly open them. It's a pity to criple that feature on purpose as it's trivial to implement it.

**Comment by kjk** [comment]
Fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/a64779ce9ff72a84f06b5ff7fe548e4af681236c

**Comment by SumatraPeter** [comment]
@kjk: Well this certainly is a pleasant surprise four and a half years after closure! 👍😄

Left a [comment](https://github.com/sumatrapdfreader/sumatrapdf/commit/a64779ce9ff72a84f06b5ff7fe548e4af681236c#r39885974) for you re. the commit...
