### ISSUE TITLE
Please support line space, font size and etc. for txt

### ISSUE THREAD

**Issue by kelilife** [sumatrapdfreader/sumatrapdf#3520]
I want to read e-book

**Comment by kelilife** [comment]
I want to read e-book

**Comment by GitHubRulesOK** [comment]
Line spacing in a reader is set by the authors choice of font, so re-auther in any editor as generally a viewer of static pages could not do that. The older sumatraPDF allowed as much re-use of one flowing font as was possible but most fonts will have a fixed "leading"

**Comment by kelilife** [comment]
I just wish I could set more parameters, everyone has some different ideas and needs.
