### ISSUE TITLE
SumatraPDF crashes when opening a pdf doc.

### ISSUE THREAD

**Issue by Scat27** [sumatrapdfreader/sumatrapdf#3522]
SumatraPDF crashes whenever a pdf doc is opened. This is a new incident, first noticed less than a week ago. Been using the tool for years with no issues at all. 

Crash report contained in the attached file.

[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/11629474/sumatrapdfcrash.txt)

Action:
1. Open Pdf file - either by doubleclick or right click.

Result:
Crash happens - see attached error message. 
Also attached sample pdf doc used for testing.
[Three Network 5G Home Broadband – Terms & Conditions (Post_29_October_2020).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11629590/Three.Network.5G.Home.Broadband.Terms.Conditions.Post_29_October_2020.pdf)
![Crash screenshot](https://github.com/sumatrapdfreader/sumatrapdf/assets/135268870/4c2bac5f-b2bd-4f20-b39f-21f50da18c97)

**Comment by GitHubRulesOK** [comment]
hmm your crash report seemed to see several problem files and looks like it fell over on "2021.11.15 - Medical Records - [redacted### ###] Hosp No [#######]5.pdf'"

Unknown if that is still a cause for crash your sample file does not cause me a problem in current Pre-Release
However I have to suggest that the only way forward is you re-test your files using current Pre-Release (https://www.sumatrapdfreader.org/prerelease) as only that can be "fixed"

**Comment by Scat27** [comment]
I suspect something about the older version may have triggered my issues. I have reinstalled SumatraPDF version 3.4.6 and it works like a dream. The crashes no longer occur. Thanks for the support. It's much appreciated.
