### ISSUE TITLE
Incorrect page numbering

### ISSUE THREAD

**Issue by kaba2** [sumatrapdfreader/sumatrapdf#353]
In this PDF:

http://tempsend.com/B02B4B4675

SumatraPDF 3.1.1 shows the logical page numbers as 1 (1/3), 1.1 (2/3), 2 (3/3). Acrobat Reader and Foxit Reader show 1,1,2, which is correct in this case. The bug is present in the latest portable version.

More information:

http://tex.stackexchange.com/questions/276925/strange-page-numbering-with-onesided-book-and-hyperref-package

**Comment by ousia** [comment]
@Kaba2, I can confirm the bug: logical page 2 is numbered as having label `1.1` with latest unstable version. Evince displays this page label as `1`.

The issue persists also in the latest pre-released version (sorry if you meant that with the latest portable binary).

**Comment by kjk** [comment]
[bug.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/31252/bug.pdf)

**Comment by ousia** [comment]
@kjk,

I attach an already uncompressed PDF ([wrong-pagelabels.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1180505/wrong-pagelabels.pdf)).

Its dictionary reads:

```
  /PageLabels <<
    /Nums [ 0 <<
          /S /D
          /St 1
        >> 1 <<
          /S /D
          /St 1
        >> 2 <<
          /S /D
          /St 1
        >> 3 <<
          /S /D
          /St 1
        >> 4 <<
          /S /D
          /St 1
        >> 5 <<
          /S /D
          /St 1
        >> ]
  >>
```

Pages in that document are to be labeled: 1 to 6 with `1` and 7 to 10 with `2` to `5`.

_SumatraPDF_ seems to read non-existing information in the [`/PageLabels` dictionary](https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=383).

Extra-labels may be specified by the `/P` key, such as in the modified dictionary:

```
  /PageLabels <<
    /Nums [ 0 <<
          /S /D
          /St 1
        >> 1 <<
          /S /D
          /St 1
        >> 2 <<
          /S /D
          /St 1
        >> 3 <<
          /S /D
          /P (1.)
          /St 1
        >> 4 <<
          /S /D
          /P (1.)
          /St 1
        >> 5 <<
          /S /D
          /St 1
        >> ]
  >>
```

The uncompressed output ([real-pagelabels.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1180530/real-pagelabels.pdf)) has the following page label sequence:

```
1
1
1
1.1
1.1
1
2
3
4
5
```

_SumatraPDF_ reads the previously modified dictionary as:

```
1
1.2
1.3
1.1
1.1.1
1.4
2
3
4
5
```

Could you fix this issue?

Many thanks for your help.

**Comment by kjk** [comment]
For future reference: relevant code is BuildPageLabelVec
