### ISSUE TITLE
Find stuck at "Searching 7881 of 7900"

### ISSUE THREAD

**Issue by pmor13** [sumatrapdfreader/sumatrapdf#3532]
Document: Arm Architecture Reference Manual Armv8, for Armv8-A architecture profile, version (issue) [E.a](https://developer.arm.com/documentation/ddi0487/ea/?lang=en).

Find input `Default NaN use for NaN propagation`.

Find stuck at "Searching 7881 of 7900":
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/4587883/8a1bd13f-90a5-4c9d-bd8b-6ffec2acfd86)

Tool version: v3.4.6 64-bit (last change: https://github.com/sumatrapdfreader/sumatrapdf/commit/7a19622d5ad35702dad2694cca4873693e88bc4e).

OS: Windows 10

HW: Intel

**Comment by kjk** [comment]
Can't reproduce in latest pre-release https://www.sumatrapdfreader.org/prerelease
