### ISSUE TITLE
Move to next/previous tab at end/start of current file

### ISSUE THREAD

**Issue by seidler2547** [sumatrapdfreader/sumatrapdf#354]
I use SumatraPDF for displaying music scores and I have Bluetooth footswitch with left+rights "keys". It would be nice to have an option to move to the next tab when I press right/down/pgdn in a document which is at its last page (and similarly for first page → previous tab). That way one could cycle through all open documents using just two keys.

I could take a stance at it myself, but my Win32 & C++ skills are a bit rusty, it might be an easy feat for someone who knows the codebase well?

**Comment by kjk** [comment]
Such feature would be too specialized.
