### ISSUE TITLE
fix CI build

### ISSUE THREAD

**Issue by deep-soft** [sumatrapdfreader/sumatrapdf#3541]
Visual Studio last update broke compilation (run: .\doit.bat -ci)

# Temporary fix - option 1:
replace in vs2022/*.vcxproj
`      <LanguageStandard>stdcpplatest</LanguageStandard>`
with
`      <LanguageStandard>stdcpp20</LanguageStandard>`

credits:
https://github.com/FarGroup/FarManager/commit/f2e1caa3806c72a18f6d800c704e7a6654fa82ae#diff-b6315975488298bf7935f899f36a6808777e3b7dd02786577a727c5621905084

# or
# Temporary fix - option 2:
//# apply in build.yml, before line 23 (- name: Build)
```

# fix in CI - begin
      - name: Try fix build
        shell: bash
        run: |
          echo "Dir1:"
          ls -l ${{ env.WORK_DIR }}/vs2022
          sed -ibak 's!<LanguageStandard>stdcpplatest</LanguageStandard>!<LanguageStandard>stdcpp20</LanguageStandard>!' ${{ env.WORK_DIR }}/vs2022/*.vcxproj
          echo "Dir2:"
          ls -l ${{ env.WORK_DIR }}/vs2022
# fix in CI - end
```

# first try to fix: rename modules.json from Visual Studio folder
```
      - name: Try fix build
        shell: cmd
        run: |
          echo "Dir1:"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\"
          move "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\modules\modules.json" "modules.js!n"
          echo "Dir2:"
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\"

```

**Comment by kjk** [comment]
It works for me.
