### ISSUE TITLE
Menu bar color

### ISSUE THREAD

**Issue by newinnov** [sumatrapdfreader/sumatrapdf#3550]
Please allow to change background color for menu bar  or allow to select a dark menu layout.
As though sumatra allows to configure colors for reading area, but late night readings becomes hard due to glowing white menu bar. 
Please consider this request. 
Regards,

**Comment by GitHubRulesOK** [comment]
Menu bar does change as a result of theming, however title bar and scrollbars are outside of that influence as was controlled via legacy system.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2c8ea502-6a9d-49f3-a1f2-172807503d5c)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/20d051eb-b2ec-46f1-a138-4df459b19622)
![Untitled](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/0c4fb999-617b-47b5-a9d1-058747f901d8)
