### ISSUE TITLE
CTRL + F should replace current search box entry with selection

### ISSUE THREAD

**Issue by tbertels** [sumatrapdfreader/sumatrapdf#3559]
Currently, pressing CTRL + F uses the current selection as the search text only if the search box is empty.

While Ctrl + F3 does replace current search box entry with selection, CTRL + F seems wider spread and is easier to press.

**Comment by miloush** [comment]
Just selecting all in the textbox seems fine. What if I just want to edit the search query regardless of what I copy and paste in other applications?

**Comment by tbertels** [comment]
I'm not sure I understand what you mean.

Here's how it works in most software:
CTRL + F uses the current selection as the search text and gives the focus to the search box with the new text selected.
If we then paste something (CTRL + V), the current search text is replaced by the pasted text.

**Comment by miloush** [comment]
Oh ok my misunderstanding, sorry, you said "pastes" and I got misled thinking it is using the clipboard content. Your requests sounds reasonable to me now.

**Comment by GitHubRulesOK** [comment]
Hmm 
I agree its been like that a long time, as search is one of the more quirky features,
So to replace the current "Find" selection with new it needs Ctrl+C + Ctrl+F3 or simplest "double click" a word then Ctrl+F3

Currently no way to combine HotKeys / Commands so it does seem unwieldy
