### ISSUE TITLE
Outline styles were ignored

### ISSUE THREAD

**Issue by wmjordan** [sumatrapdfreader/sumatrapdf#3560]
The following sample document has two outline entries. The first one is red, bold. The second one is blue.
[temp.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11901118/temp.pdf)

They are displayed correctly in SumatraPDF 3.2.
<img width="299" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/12182730/aac969be-f1b4-471a-a51f-3ad40ea59584">

However, from version 3.3 on, the outline styles were ignored.

**Comment by GitHubRulesOK** [comment]
Hmm last time I checked (clearly some time ago) they looked OK However have to agree its not working in current pre-release

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/fcccd6be-3951-491b-8e63-acaf30fba6d3)

**Comment by kjk** [comment]
We had to modify mupdf code to get outline color but then mupdf significantly changed outline code and we lost those changes.

**Comment by wmjordan** [comment]
I understood that. `fz_outline` does not support styles. Their changes in related code files got you frustrated.

Since the structure of PDF outline is not very likely to be changed, is it possible to copy the outline extraction logic into the source code of SumatraPDF and use a custom `pdf_outline`-like structure to hold the outline information with styles?

**Comment by kjk** [comment]
No plans to modify or fork mupdf code that much. Too much on-going work to keep up with mupdf changes.

**Comment by wmjordan** [comment]
The recent version of MuPDF supports colors and styles of outlines. Please consider reimplementing outline styles.

**Comment by wmjordan** [comment]
I checked out their source code, and see the `pdf_outline_iterator_item` function is reading colors and styles from PDF outlines.
See:
https://github.com/ArtifexSoftware/mupdf/blob/f84bb9fbe8abea011d500d28d90e3c31c576a209/source/pdf/pdf-outline.c#L484-L522

**Comment by wmjordan** [comment]
Any news for this issue?

**Comment by kjk** [comment]
issue still opened so no

**Comment by wmjordan** [comment]
Thank you very much for having this issue fixed.
Now I am using the latest prerelease version and the new version is great!
