### ISSUE TITLE
Highlighted section in Bookmarks and Favorites panels does not respect colour customisation

### ISSUE THREAD

**Issue by AiredDev** [sumatrapdfreader/sumatrapdf#3564]
This issue occurs across the Fixed Page, ebook and chm UIs. I noticed it first in the Fixed Page UI.

I've customised the background colour and text colour of the UI via the advanced settings:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/84405912/29f4d793-2f71-4978-bc65-66da302bd045)
Note that specifically customising the colours is not the same as issuing the "invert colors" command to the reader (not sure if the problem occurs in that scenario).

The customisation gives the UI a grey background colour with white text:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/84405912/494c4ef0-b4e5-46df-9e96-ad6ad020ebc9)

However, as you can see, the highlighted text in the Bookmarks panel on the left is still black (as opposed to white), which makes it difficult to read:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/84405912/d548001e-1565-4174-9191-179aa0276fe3)

The same thing occurs in the Favorites panel:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/84405912/f8d6a43a-05c0-42f3-bd58-68fb4b6c2cb1)

Notably, the issue only happens when the panels are _unfocused_ (i.e. if I click on a different panel or window after selecting a section). If I just click on a section in the panel and do nothing else, the customisation is still respected:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/84405912/efb67ebf-8e86-4728-a6d8-28a220d05e1d)

**Comment by GitHubRulesOK** [comment]
well it will be different for each of the 3 themes and inversion but generally only affects hover as once selected its usually ok
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/3fa25926-6737-4754-9b1a-9bb5b6ac3399)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/df54dd37-4d8c-49bb-abc4-00af2f940682)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d9185077-6be4-4eae-922f-495e9cb29723)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/a58db84d-ddee-4fc1-bbeb-de73b8e76307)

**Comment by GitHubRulesOK** [comment]
Issue is covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/3429
