### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by aryamozart01** [sumatrapdfreader/sumatrapdf#3565]
https://gist.github.com/aryamozart01/45694f5bfb01fb5bd2959eec383f1f2f

**Comment by GitHubRulesOK** [comment]
`3.4.6 64-bit`
has had some similar crashes in libmupdf.dll
however keeping open as not seen specific one with !generate_boxes

Normally the current pre-release with its update resulve such rogue situations so try with https://www.[sumatrapdfreader.org/prerelease](https://www.sumatrapdfreader.org/prerelease)

**Comment by kjk** [comment]
Can't reproduce in latest build.
