### ISSUE TITLE
pdf crashed in window 7

### ISSUE THREAD

**Issue by tru02** [sumatrapdfreader/sumatrapdf#3568]
https://gist.github.com/tru02/5628e3e19e87d9c53dc917e4a89d695e
[Adjustment.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/11951158/Adjustment.pdf)

**Comment by kjk** [comment]
didn't crash for me in latest pre-release https://www.sumatrapdfreader.org/prerelease
