### ISSUE TITLE
underlining text

### ISSUE THREAD

**Issue by rrrafalsz** [sumatrapdfreader/sumatrapdf#357]
i like that you've finally implemented highlighting in the prerelease.
what i would to see, though, is the ability to underline text aside from highlighting. my kindle renders any highlighted text unreadable, so i must resort to underlining anything i want to highlight. 
is that something i could hope to see in the coming releases?

**Comment by GitHubRulesOK** [comment]
Underline in prerelease versions is possible by editing the .smx file prior to saving into pdf.

Work was(is) still in hand to improve annotation support so am closing this issue as covered by other open issues such as underlines shown in https://github.com/sumatrapdfreader/sumatrapdf/issues/1560#
and related to #453 #561 #747 #1479 #1499
