### ISSUE TITLE
Random crash out of nowhere with the latest pre-release version

### ISSUE THREAD

**Issue by Pocokk** [sumatrapdfreader/sumatrapdf#3570]
Crash file: E:\Programs\SumatraPDF\crashinfo\sumatrapdfcrash.txt
Exe: E:\Programs\SumatraPDF\SumatraPDF.exe 7.94 MB (8,329,176 Bytes)
Dll: E:\Programs\SumatraPDF\libmupdf.dll 13.39 MB (14,039,040 Bytes)
BuiltOn: 2023-04-18
Type: dll
Ver: 3.5.15481 pre-release 64-bit
Git: 9a2183db3c3db5cbf242ac9d8f8576750f581096 (https://github.com/sumatrapdfreader/sumatrapdf/commit/9a2183db3c3db5cbf242ac9d8f8576750f581096)
OS: Windows 10.19045 build 19045 64-bit
Number Of Processors: 8
Processor: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
Physical Memory: 15.94 GB
Commit Charge Limit: 27.94 GB
Memory Used: 43%
Machine: To be filled by O.E.M. System Version
Lang: en US
Graphics driver 0
  DriverDesc:         NVIDIA GeForce GTX 1070
  DriverVersion:      31.0.15.3598
  UserModeDriverName: C:\WINDOWS\System32\DriverStore\FileRepository\nvgbdig.inf_amd64_82eb686a406694a3\nvldumdx.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FF68CC2A80E 01:000000000001980E sumatrapdf.exe!OnMouseLeftButtonUp+0xa2 D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+502
Fault writing address 0000000000000000

Registers:
RAX:0000000000000000  RBX:000001D4DBC1C6E0  RCX:000001D4E038A250
RDX:000000000000027C  RSI:000001D4E038A250  RDI:0000000000000003
R8: 0000000000000009
R9: 0000000000000000
R10:00007FFDC79D15F0
R11:0000000000000246
R12:000000000000027C
R13:0000000000000000
R14:0000000000000000
R15:0000000000000009
CS:RIP:0033:00007FF68CC2A80E
SS:RSP:002B:000000006D4FF0B0  RBP:6D4FF0F0
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010246

Crashed thread:
00007FF68CC2A80E 01:000000000001980E sumatrapdf.exe!OnMouseLeftButtonUp+0xa2 D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+502
00007FF68CC2C832 01:000000000001B832 sumatrapdf.exe!WndProcCanvasFixedPageUI+0x2fe D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1474
00007FF68CC2CF23 01:000000000001BF23 sumatrapdf.exe!WndProcCanvas+0xa7 D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1721
00007FFDC792E858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FFDC792E299 01:000000000000D299 user32.dll!DispatchMessageW+0x259
00007FF68CC744CC 01:00000000000634CC sumatrapdf.exe!RunMessageLoop+0x15c D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+555
00007FF68CC75EF0 01:0000000000064EF0 sumatrapdf.exe!WinMain+0x1124 D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+1378
00007FF68CCFD94A 01:00000000000EC94A sumatrapdf.exe!__scrt_common_main_seh+0x106 D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl+288
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2848
00007FFDC864D064 01:000000000009C064 ntdll.dll!ZwWaitForSingleObject+0x14
00007FFDC61030CE 01:00000000000220CE kernelbase.dll!WaitForSingleObjectEx+0x8e
00007FF68CC3497A 01:000000000002397A sumatrapdf.exe!CrashDumpExceptionHandler+0x86 D:\a\sumatrapdf\sumatrapdf\src\CrashHandler.cpp+472
00007FFDC620DDA7 01:000000000012CDA7 kernelbase.dll!UnhandledExceptionFilter+0x1e7
00007FFDC86554B0 01:00000000000A44B0 ntdll.dll!memset+0x13b0
00007FFDC863C886 01:000000000008B886 ntdll.dll!_C_specific_handler+0x96
00007FFDC86523AF 01:00000000000A13AF ntdll.dll!_chkstk+0x11f
00007FFDC86014B4 01:00000000000504B4 ntdll.dll!RtlRaiseException+0x484
00007FFDC8650EBE 01:000000000009FEBE ntdll.dll!KiUserExceptionDispatcher+0x2e
00007FF68CC2A80E 01:000000000001980E sumatrapdf.exe!OnMouseLeftButtonUp+0xa2 D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+502
00007FF68CC2C832 01:000000000001B832 sumatrapdf.exe!WndProcCanvasFixedPageUI+0x2fe D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1474
00007FF68CC2CF23 01:000000000001BF23 sumatrapdf.exe!WndProcCanvas+0xa7 D:\a\sumatrapdf\sumatrapdf\src\Canvas.cpp+1721
00007FFDC792E858 01:000000000000D858 user32.dll!CallWindowProcW+0x3f8
00007FFDC792E299 01:000000000000D299 user32.dll!DispatchMessageW+0x259
00007FF68CC744CC 01:00000000000634CC sumatrapdf.exe!RunMessageLoop+0x15c D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+555
00007FF68CC75EF0 01:0000000000064EF0 sumatrapdf.exe!WinMain+0x1124 D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+1378
00007FF68CCFD94A 01:00000000000EC94A sumatrapdf.exe!__scrt_common_main_seh+0x106 D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl+288
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 3fb0
00007FFDC8650A74 01:000000000009FA74 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFDC8602E27 01:0000000000051E27 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 9bc
00007FFDC8650A74 01:000000000009FA74 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFDC8602E27 01:0000000000051E27 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 3354
00007FFDC8650A74 01:000000000009FA74 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFDC8602E27 01:0000000000051E27 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 28f4
00007FFDC864D064 01:000000000009C064 ntdll.dll!ZwWaitForSingleObject+0x14
00007FFDC61030CE 01:00000000000220CE kernelbase.dll!WaitForSingleObjectEx+0x8e
00007FF68CC57644 01:0000000000046644 sumatrapdf.exe!RenderCache::RenderCacheThread+0xb0 D:\a\sumatrapdf\sumatrapdf\src\RenderCache.cpp+645
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 1bd8
00007FFDC864DB34 01:000000000009CB34 ntdll.dll!NtWaitForMultipleObjects+0x14
00007FFDC6131B40 01:0000000000050B40 kernelbase.dll!WaitForMultipleObjectsEx+0xf0
00007FF68CC93A04 01:0000000000082A04 sumatrapdf.exe!FileWatcherThread+0x74 D:\a\sumatrapdf\sumatrapdf\src\utils\FileWatcher.cpp+325
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Thread: d38
00007FFDC8650A74 01:000000000009FA74 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFDC8602E27 01:0000000000051E27 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 2e84
00007FFDC8650A74 01:000000000009FA74 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFDC8602E27 01:0000000000051E27 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFDC8417614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFDC86026B1 01:00000000000516B1 ntdll.dll!RtlUserThreadStart+0x21

Module: 00007FF68CC10000 7FB000 SumatraPDF.exe   E:\Programs\SumatraPDF\SumatraPDF.exe
Module: 00007FFDC85B0000 1F8000 ntdll.dll        C:\WINDOWS\SYSTEM32\ntdll.dll
Module: 00007FFDC8400000 0BF000 KERNEL32.DLL     C:\WINDOWS\System32\KERNEL32.DLL
Module: 00007FFDC60E0000 2F6000 KERNELBASE.dll   C:\WINDOWS\System32\KERNELBASE.dll
Module: 00007FFDC7920000 19D000 USER32.dll       C:\WINDOWS\System32\USER32.dll
Module: 00007FFDC63E0000 022000 win32u.dll       C:\WINDOWS\System32\win32u.dll
Module: 00007FFDC6BA0000 02C000 GDI32.dll        C:\WINDOWS\System32\GDI32.dll
Module: 00007FFDC64A0000 115000 gdi32full.dll    C:\WINDOWS\System32\gdi32full.dll
Module: 00007FFDB0310000 29A000 COMCTL32.dll     C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\COMCTL32.dll
Module: 00007FFDC5FD0000 09D000 msvcp_win.dll    C:\WINDOWS\System32\msvcp_win.dll
Module: 00007FFDC5C90000 100000 ucrtbase.dll     C:\WINDOWS\System32\ucrtbase.dll
Module: 00007FFDC8360000 09E000 msvcrt.dll       C:\WINDOWS\System32\msvcrt.dll
Module: 00007FFDC7D40000 0DA000 COMDLG32.dll     C:\WINDOWS\System32\COMDLG32.dll
Module: 00007FFDC7E90000 354000 combase.dll      C:\WINDOWS\System32\combase.dll
Module: 00007FFDC6DB0000 126000 RPCRT4.dll       C:\WINDOWS\System32\RPCRT4.dll
Module: 00007FFDC81F0000 0AD000 shcore.dll       C:\WINDOWS\System32\shcore.dll
Module: 00007FFDC7BB0000 055000 SHLWAPI.dll      C:\WINDOWS\System32\SHLWAPI.dll
Module: 00007FFDC7130000 744000 SHELL32.dll      C:\WINDOWS\System32\SHELL32.dll
Module: 00007FFDB0270000 09D000 WINSPOOL.DRV     C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
Module: 00007FFDC84C0000 0AF000 ADVAPI32.dll     C:\WINDOWS\System32\ADVAPI32.dll
Module: 00007FFDC7880000 09C000 sechost.dll      C:\WINDOWS\System32\sechost.dll
Module: 00007FFDC7C10000 12A000 ole32.dll        C:\WINDOWS\System32\ole32.dll
Module: 00007FFDC7060000 0CD000 OLEAUT32.dll     C:\WINDOWS\System32\OLEAUT32.dll
Module: 00007FFDC6BD0000 030000 IMM32.DLL        C:\WINDOWS\System32\IMM32.DLL
Module: 00007FFDC3660000 09E000 uxtheme.dll      C:\WINDOWS\system32\uxtheme.dll
Module: 00007FFDC3860000 02F000 dwmapi.dll       C:\WINDOWS\system32\dwmapi.dll
Module: 00007FFDC7E20000 008000 normaliz.dll     C:\WINDOWS\System32\normaliz.dll
Module: 00007FFDB1CC0000 1E4000 dbghelp.dll      C:\WINDOWS\system32\dbghelp.dll
Module: 00007FFDA7A90000 034000 dbgcore.DLL      C:\WINDOWS\SYSTEM32\dbgcore.DLL
Module: 00007FFDB05B0000 1A5000 gdiplus.dll      C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.2251_none_91a40448cc8846c1\gdiplus.dll
Module: 00007FFDB07E0000 007000 msimg32.dll      C:\WINDOWS\system32\msimg32.dll
Module: 00007FFDBBF50000 1EC000 urlmon.dll       C:\WINDOWS\system32\urlmon.dll
Module: 00007FFDBBEC0000 029000 srvcli.dll       C:\WINDOWS\SYSTEM32\srvcli.dll
Module: 00007FFDBC680000 2B1000 iertutil.dll     C:\WINDOWS\SYSTEM32\iertutil.dll
Module: 00007FFDC5100000 00C000 netutils.dll     C:\WINDOWS\SYSTEM32\netutils.dll
Module: 00007FFDC00B0000 00A000 version.dll      C:\WINDOWS\system32\version.dll
Module: 00007FFDC0510000 1B4000 windowscodecs.dll C:\WINDOWS\system32\windowscodecs.dll
Module: 00007FFDC5FA0000 027000 bcrypt.dll       C:\WINDOWS\System32\bcrypt.dll
Module: 00007FFDACF50000 4D6000 wininet.dll      C:\WINDOWS\system32\wininet.dll
Module: 00007FFDC3D50000 794000 windows.storage.dll C:\WINDOWS\SYSTEM32\windows.storage.dll
Module: 00007FFDC56C0000 02E000 Wldp.dll         C:\WINDOWS\SYSTEM32\Wldp.dll

Modules loaded later:
Module: 00007FFDC3B50000 012000 kernel.appcore.dll C:\WINDOWS\SYSTEM32\kernel.appcore.dll
Module: 00007FFDC6410000 082000 bcryptPrimitives.dll C:\WINDOWS\System32\bcryptPrimitives.dll
Module: 00007FFDC6A80000 114000 MSCTF.dll        C:\WINDOWS\System32\MSCTF.dll
Module: 00007FFDB4070000 0AC000 TextShaping.dll  C:\WINDOWS\SYSTEM32\TextShaping.dll
Module: 00007FFDBE0C0000 0F9000 textinputframework.dll C:\WINDOWS\SYSTEM32\textinputframework.dll
Module: 00007FFDC2A90000 35E000 CoreUIComponents.dll C:\WINDOWS\System32\CoreUIComponents.dll
Module: 00007FFDC3170000 0F2000 CoreMessaging.dll C:\WINDOWS\System32\CoreMessaging.dll
Module: 00007FFDC7B40000 06B000 WS2_32.dll       C:\WINDOWS\System32\WS2_32.dll
Module: 00007FFDC4DF0000 033000 ntmarta.dll      C:\WINDOWS\SYSTEM32\ntmarta.dll
Module: 00007FFDC1AB0000 154000 wintypes.dll     C:\WINDOWS\SYSTEM32\wintypes.dll
Module: 00007FFD5F9E0000 DC9000 libmupdf.dll     E:\Programs\SumatraPDF\libmupdf.dll
Module: 00007FFDC82A0000 0A9000 clbcatq.dll      C:\WINDOWS\System32\clbcatq.dll
Module: 00007FFD97A10000 02B000 sendmail.dll     C:\WINDOWS\System32\sendmail.dll
Module: 00007FFDC17E0000 0F6000 PROPSYS.dll      C:\WINDOWS\System32\PROPSYS.dll
Module: 00007FFDB5990000 27F000 DWrite.dll       C:\WINDOWS\SYSTEM32\DWrite.dll
Module: 00007FFDC0280000 0A1000 policymanager.dll C:\WINDOWS\SYSTEM32\policymanager.dll
Module: 00007FFDC4D60000 08A000 msvcp110_win.dll C:\WINDOWS\SYSTEM32\msvcp110_win.dll
Module: 00007FFDC65C0000 04E000 CFGMGR32.dll     C:\WINDOWS\System32\CFGMGR32.dll
Module: 00007FFDC5BC0000 025000 profapi.dll      C:\WINDOWS\SYSTEM32\profapi.dll

-------- Log -----------------

ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => 'E:\Programs\SumatraPDF'
InstallCrashHandler crashDumpPath: 'E:\Programs\SumatraPDF\crashinfo\sumatrapdfcrash.dmp'
crashFilePath: 'E:\Programs\SumatraPDF\crashinfo\sumatrapdfcrash.txt'
symDir: 'E:\Programs\SumatraPDF\crashinfo'
Starting SumatraPDF 15481, GetCommandLineW():
"E:\Programs\SumatraPDF\SumatraPDF.exe" "F:\Comics\Warhammer\Books\Necromunda (Kal Jerico)\RP\Gang War Magazine 01.pdf"
OpenEmbeddedFilesArchive: opened archive
LoadSettings() took 0.34 ms
ParseTranslationsTxt: 20474 lines, nStrings: 365
retrieved doc colors in WinMain: 0x0 0xffffff
retrieved doc colors in tree control: 0x0 0xffffff
retrieved doc colors in tree control: 0x0 0xffffff
CreateControllerForEngine: 'F:\Comics\Warhammer\Books\Necromunda (Kal Jerico)\RP\Gang War Magazine 01.pdf', 50 pages
LoadDocument: 410.81 ms, 50 pages for 'F:\Comics\Warhammer\Books\Necromunda (Kal Jerico)\RP\Gang War Magazine 01.pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.04 ms
retrieved doc colors in tree control: 0x0 0xffffff
StartMonitoringDirForChangesAPC() F:\Comics\Warhammer\Books\Necromunda (Kal Jerico)\RP
StartMonitoringDirForChangesAPC() E:\Programs\SumatraPDF
HandleDdeCmds: '[Open("F:\Comics\Warhammer\Books\Necromunda (Kal Jerico)\RP\Gang War 01.pdf", 0, 1, 0)]'
CreateControllerForEngine: 'F:\Comics\Warhammer\Books\Necromunda (Kal Jerico)\RP\Gang War 01.pdf', 52 pages
LoadDocument: 76.77 ms, 52 pages for 'F:\Comics\Warhammer\Books\Necromunda (Kal Jerico)\RP\Gang War 01.pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.00 ms
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: -1, isDragging: 0
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
retrieved doc colors in tree control: 0x0 0xffffff
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 1
tv: NM_CLICK
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: -1, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 2
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: -1, isDragging: 0
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 2
tv: NM_CLICK
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: -1, isDragging: 0
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 1
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: -1, isDragging: 0
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 1
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: -1, isDragging: 0
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: 2, tabHighlited: 2
tv: NM_CLICK
tv: TVN_SELCHANGED
tv: NM_CLICK
tv: TVN_SELCHANGED
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 0
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 0
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 2
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: -1, isDragging: 0
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 0
tv: TVN_SELCHANGED
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 2
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: -1, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: 2, tabHighlited: 2
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 2, isDragging: 0
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 1, tabHighlited: 1, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 1, tabHighlited: 1, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 1
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: -1, isDragging: 0
tv: TVN_SELCHANGED
retrieved doc colors in tree control: 0x0 0xffffff
tv: TVN_SELCHANGED
TabsCtrl::WndProc: WM_LBUTTONDOWN, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 1
TabsCtrl::WndProc: WM_LBUTTONUP, tabUnderMouse: 2, tabHighlited: 2, tabBeingClosed: -1, overClose: 0
TabsCtrl::WndProc: WM_MOUSEMOVE: tabUnderMouse: 2, tabHighlited: 2, isDragging: 0
TabsCtrl::WndProc: WM_MOUSELEAVE, tabUnderMouse: -1, tabHighlited: 2

----- Settings file ----------

﻿# For documentation, see https://www.sumatrapdfreader.org/settings/settings3-5.html
FixedPageUI [
	TextColor = #00000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
	GradientColors = #000000 #888888 #ffffff
	HideScrollbars = false
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]

SelectionHandlers [
]
ExternalViewers [
]

ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
Annotations [
	HighlightColor = #ffff00
	UnderlineColor = #00ff00
	SquigglyColor = #ff00ff
	StrikeOutColor = #ff0000
	TextIconColor = #ffff00
	TextIconType = 
	DefaultAuthor = 
]

RememberOpenedFiles = false
RememberStatePerDocument = true
RestoreSession = true
UiLanguage = en
EnableTeXEnhancements = false
DefaultDisplayMode = automatic
DefaultZoom = fit page
Shortcuts [
]
EscToExit = false
ReuseInstance = false
ReloadModifiedDocuments = true

MainWindowBackground = #80fff200
FullPathInTitle = false
ShowMenubar = true
ShowToolbar = true
ShowFavorites = false
ShowToc = true
NoHomeTab = false
TocDy = 0
SidebarDx = 393
ToolbarSize = 18
TabWidth = 300
TreeFontSize = 0
TreeFontWeightOffset = 0
TreeFontName = automatic
SmoothScroll = false
ShowStartPage = true
CheckForUpdates = true
VersionToSkip = 15262
WindowState = 2
WindowPos = 690 43 805 1042
UseTabs = true
UseSysColors = false
CustomScreenDPI = 0

FileStates [
]
SessionData [
]
TimeOfLastUpdateCheck = 31044010 1137992883
OpenCountWeek = 653

# Settings below are not recognized by the current version

**Comment by kjk** [comment]
Need more information i.e. steps to reproduce the crash.
