### ISSUE TITLE
Image Colors Should Not Be Inverted

### ISSUE THREAD

**Issue by Genje5** [sumatrapdfreader/sumatrapdf#3571]
In the past few versions of SumatraPDF, at least those where EBookUI is gone from the settings, image colors are inverted when background color is changed to a dark color, and text to a light color. This makes it extremely hard to enjoy any ebook with any images embedded. See example below.

![inverted](https://github.com/sumatrapdfreader/sumatrapdf/assets/73438781/504a2fc9-bf16-4311-a8a9-ade74f251638)

**Comment by GitHubRulesOK** [comment]
That has always been the case for the MuPDF engine , so will close as not a new issue, once I find the earliest one still open.
Invert is inverted 100% within the range set by the users end points for back and fore grounds.
