### ISSUE TITLE
sumatra pdf does not display characters from a local language(hindi) ebook file

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#3576]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3575

<div type='discussions-op-text'>

<sup>Originally posted by **kinkblot** July 12, 2023</sup>
the entire eBook is blank. the eBook is attached. i have tried other softwares like moon reader pro, and Read aloud. file works in both.

after some searching, it looks like a problem with fonts structuring. but I do not know how to do that. 
![Sumatra Render](https://github.com/sumatrapdfreader/sumatrapdf/assets/50849787/f3313003-fdac-48da-a96d-a78cd4db3d3d)
[Awara Bheed Ke Khatare (Hindi Edition).zip](https://github.com/sumatrapdfreader/sumatrapdf/files/12024109/Awara.Bheed.Ke.Khatare.Hindi.Edition.zip)
</div>

**Comment by kjk** [comment]
Looks like we're not including the needed font:
```
DEFNOTO(NotoSerifDevanagari_Regular_otf,		"Noto Serif Devanagari",		UCDN_SCRIPT_DEVANAGARI)

UCDN_SCRIPT_DEVANAGARI = 9
```

`search_by_script_lang_strict` also fails to return font for script 168, 165, 164, 166, 167 but per `ucdn_db.h` the last script value is `UCDN_SCRIPT_NAG_MUNDARI 163`.
