### ISSUE TITLE
Automatically save last position of a viewed page based on CRC32 of a file instead of a path of a file

### ISSUE THREAD

**Issue by helperman** [sumatrapdfreader/sumatrapdf#3583]
When I open a pdf-file after moving it to another folder, it opens from first page, i.e. last position is lost.
To overcome it, it would be better to use CRC32 or any other hash of a file to store last position so that it doesn't lost after moving file to another folder or renaming file/folder.

**Comment by GitHubRulesOK** [comment]
Hmm Firefox I think from past tests tracks the file fingerprints. However they often change too, when appearances change .
SumatraPDF wll in some cases make a very simple attempt to work with basic rename, but storing the hash would be a significant slowdown in many cases when files are fluidly instantly regenerating which is a major usage of SumatraPDF in PDF compiling.

**Comment by kjk** [comment]
But then we would have to calculate crc32 for the whole file which will slow down the opening of files.

**Comment by helperman** [comment]
You can calculate crc32 in background. 
Or by small portion of file contents if it is huge.
