### ISSUE TITLE
Search and Test selection doesn't work in PDF with hyperlink

### ISSUE THREAD

**Issue by bernefr** [sumatrapdfreader/sumatrapdf#3586]
Hello
using v3.4.6 64bit  with Windows 10 20H2

when opening some file with hyperlike, the search function does not work, it 's impossible to find any test.
In the same time, it's imossible to select text too.

if i open the same file with an other program (acrobat or chromium edge) i can select text and use search function.

if it can help there is files properties for working and not working files

- Properties of file where search function is working : 

Created: 19/07/2023 15:00:35
Modified: 19/07/2023 15:03:05
Application: PScript5.dll Version 5.2.2
PDF Producer: Acrobat Distiller 10.1.16 (Windows)
PDF Version: 1.6
File Size: 121,98 KB (124 905 Bytes)
Number of Pages: 7
Page Size: 29,7 x 21,0 cm (A4)
   
Fonts: Arial (TrueType (CID); Identity-H; embedded)
Arial,Bold (TrueType (CID); Identity-H; embedded)
Helvetica (Type1)
POLICE0 (Type1; embedded)
POLICE1 (Type1; embedded)

- Properties of file where search function is NOT working : 

Created: 19/07/2023 15:05:36
Modified: 19/07/2023 15:05:36
Application: SEE Electrical Expert
PDF Producer: wPDF4 by WPCubed GmbH
PDF Version: 1.4
File Size: 19,76 MB (20 723 608 Bytes)
Number of Pages: 575
Page Size: 27,09 x 20,32 cm
   
Fonts: Arial (Type3; embedded)
Courier New (Type3; embedded)
POLICE0 (Type3; embedded)
POLICE1 (Type3; embedded)

**Comment by kjk** [comment]
Can't investigate without a sample file
