### ISSUE TITLE
Threat Detected

### ISSUE THREAD

**Issue by kjohn740** [sumatrapdfreader/sumatrapdf#3587]
I have downloaded the project source code and my antivirus has detected a threat.
Detection: W32.Auto:0870f3.in03.Talos
File: bin2coff.exe

**Comment by GitHubRulesOK** [comment]
HMM 
thanks for a heads up

@kjk Virustotal certainly does not value that version as usable. That version does have an exceptionally high score even the Artifex oversized one still counts as 1 beware.

You could try use the 2011 version with a clean slate from https://sourceforge.net/projects/libwdi/files/utilities/ however I have no idea if it would perform the same functionality.

**Comment by kjk** [comment]
False report, nothing I can do about it.
