### ISSUE TITLE
How to customize the command

### ISSUE THREAD

**Issue by 5rKB5bPlusD** [sumatrapdfreader/sumatrapdf#3588]
How to use custom commands and set them as custom shortcut keys.
Or is there a command to replace the configuration file that allows me to switch between two different reading interface configurations.
Thanks!

**Comment by GitHubRulesOK** [comment]
Hmm 3 questions in one none is an issue

1) https://www.sumatrapdfreader.org/docs/DDE-Commands and https://www.sumatrapdfreader.org/docs/Commands
2) https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts
3) I agree is not documented clearly as a topic see https://www.sumatrapdfreader.org/docs/Command-line-arguments `-appdata <directory> : set custom directory where we’ll store SumatraPDF-settings.txt file and thumbnail cache`
