### ISSUE TITLE
How to get the path to the currently open active document

### ISSUE THREAD

**Issue by jadetexy** [sumatrapdfreader/sumatrapdf#3589]
I need to get the path to the current document to be called by another program。
Which partner knows how to do it

**Comment by GitHubRulesOK** [comment]
discussed many times 
For Visual copy & paste use Ctrl+D once or twice or clipboard
alternatively use F2 and copy from addressbar
for internal command output use "externalviewers" with the appropriate syntax for the external app  (including re-entry)
for external apps its usually seen via the windows tasklist so can be used from command line or external commands
etc.

**Comment by jadetexy** [comment]
thanks 。In addition, I can't  use ( CmdOpenWithPdfXchange) to wake up The PdfXchange application opens has confirmed that the  my Notebook is installed PdfXchange software, test with CmdOpenWithAcrobat cmd line can open the current sumtra pdf normally with Acrobat pdf， What's going on?

**Comment by jadetexy** [comment]
Or can you specify the path to PdfXchange in the "SumatraPDF-settings.txt "to ensure that the sumatra pdf is called correctly and opens the document?、？

**Comment by GitHubRulesOK** [comment]
The external Viewers as shortcuts are very dependent on registry so can bounce off target
Hence I usually write my own (it does mean an extra key as its `Alt F A` (I personally find that unintentionally humorous) for Acrobat

For PDFXEDIT
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d526c88a-2937-4337-a8d8-c4b1b7be6710)

This would be Alt + F + T
```
ExternalViewers [
	[
		CommandLine = "C:\Users\user\Downloads\Apps\PDF\PDFXEdit10\PDFXEdit.exe" /A page=%p "%1"
		Name = &Tracker Xedit inc 3D view or Review Text
		Filter = *.pdf
	]
]
```

**Comment by jadetexy** [comment]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/115758418/b1e1eab6-9d10-43aa-b2b6-9588fb799c6e)
As shown in the figure, the test definition hotkey does not work. Do you test the definition hotkey work?

**Comment by jadetexy** [comment]
Thank you very much @GitHubRulesOK

**Comment by kjk** [comment]
In latest pre-release you can use command palette and `Copy File Path` command which copies path of the active file to clipboard.

You can also create a custom keyboard binding and bind `CmdCopyFilePath` command to a keyboard shortcut.
