### ISSUE TITLE
Allow WM_Command for page changes for external control?

### ISSUE THREAD

**Issue by Stretto** [sumatrapdfreader/sumatrapdf#359]
I use sumatra pdf and have an app I wrote to control it. The problem is that, while I can control most of summatra, I can't easily set pages.

The problem comes from using full screen/presentation mode. When set, and I use my page changing mechanisms(sendmessage), I get the page change dialog box that pops up in full screen mode because, I guess, the toolbar is hidden.

Could you guys add way to tell sumatra to change pages through the message loop?

e.g., normally I use
SendMessage(WindowHandle, WM.COMMAND, IDM_GOTO_PAGE, 0);

then send the keys using SendMessage and WM_CHAR one at a time,

But it would be nice if

I could do

SendMessage(WindowHandle, WM.COMMAND, IDM_GOTO_PAGE, pagenum);

or

SendMessage(WindowHandle, WM.COMMAND, IDM_GOTO_PAGENUM, pagenum);

where we use the lparam to send the page rather than having to send it through keyboard emulation.

Thanks!

**Comment by GitHubRulesOK** [comment]
SumatraPDF uses DDE for GotoPage and many systems use that via "control"

SumatraPDF also responds to system cmd external commands
so simply send for an open file via system -reuse-instance  -page # filename.pdf (that's what eternal editors do for PDF preview)
works for me from many other applications without any fuss

Also keyboard emulation is fast using AutoHotKey or SendKeys, so is good as a fallback third option.

@kjk suggest this is historic request duplicated by similar related 
long discussion in above linked https://github.com/sumatrapdfreader/sumatrapdf/issues/1398
but open topic is https://github.com/sumatrapdfreader/sumatrapdf/issues/964
