### ISSUE TITLE
Shortcut for "Select Annotation in Editor" doesn't work

### ISSUE THREAD

**Issue by wskaa** [sumatrapdfreader/sumatrapdf#3593]
I added it as:
[
Cmd = CmdSelectAnnotation
Key = t, T 
]

When right-clicking on an annotation, the dropdown menu shows "t" next to the command, and that's as far as the shortcut goes. The command works when selected from the menu, but doesn't when clicking "t". It's not a general issue with shortcuts, they work for all other commands in the same dropdown menu (e.g. delete, annotate). Changing the key did nothing.

**Comment by GitHubRulesOK** [comment]
see the entry directly before yours (admittedly it was a discussion not issue)
https://github.com/sumatrapdfreader/sumatrapdf/discussions/3592

HOWEVER I agree **THIS** does appear to be an issue as I cannot use a `"t"` key for that command
```
Shortcuts [
	[
		Cmd = CmdSelectAnnotation
		Key = t
	]
]
```
