### ISSUE TITLE
In the portable version how can we set default width and height?

### ISSUE THREAD

**Issue by funnyfox** [sumatrapdfreader/sumatrapdf#360]
Hi,
I am using portal version for the pdf previews in my project. If a user clicks the pdf file, Sumatra opens same as my winform's width and height size. But I don't know how must do this?
Kind regards,
Mehmet.

**Comment by okungnyo** [comment]
Why did you close the issue?

**Comment by kjk** [comment]
Sumatra is an application not an SDK for displaying PDFs. This is unsupported use case, you're on your own.
