### ISSUE TITLE
Please add a shortcut (global key) to switching between tabs

### ISSUE THREAD

**Issue by igogo2** [sumatrapdfreader/sumatrapdf#3601]
In case of several documents is opened simultaneously it is convenient to switch between Next or Previous Tab by pressing Ctrl+Page down or Ctrl+Page up. Like in Notepad++.

**Comment by GitHubRulesOK** [comment]
write your own and there are many examples through these page from long ago to present `Cmd =` `Key =` often in discussions

https://github.com/search?q=repo%3Asumatrapdfreader%2Fsumatrapdf+Ctrl%2BPage+tabs&type=discussions
or 
https://github.com/search?q=repo%3Asumatrapdfreader%2Fsumatrapdf+Ctrl%2BPage+tabs&type=issues

**Comment by tactilis** [comment]
> switch between Next or Previous Tab by pressing Ctrl+Page down or Ctrl+Page up

Those keys do that already.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/4060092/83e76c3a-4d57-490d-835f-507de90eeeef)

Which version are you using?

**Comment by GitHubRulesOK** [comment]
@tactilis 
You are right to point out its in 3.5, and I should have asked in case its a version prior to recent adding `Cmd =` (3.4.6 ? I should have checked befor out of hand dismissal, My Bad)
I would guess its mainstream 3.4  if the question was raised

**Comment by igogo2** [comment]
I'm a little confused. My version is 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/6361239/b7495c0f-e5b1-4d6e-a93b-0d25bd237440)
and application tell me 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/6361239/db83e634-ac5f-4a28-b14e-a8417312ee31)

**Comment by tactilis** [comment]
Correct. You have the latest stable released version.

If you want potentially unstable pre-release versions, you have to install them yourself.

**Comment by GitHubRulesOK** [comment]
@igogo2 
many commands (not all) in 3.4 were made accessible / changeable https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts
and some others have been altered or added  in pre-release for 3.5 (I cannot be certain when tabs were affected most but 3.4 "should" be possible to emulate browser tabs by setting your own shortcuts

**Comment by igogo2** [comment]
@GitHubRulesOK 
Thanks. [Unfortunately 3.4.6 doesn't have shortcuts for tabs yet.](https://www.sumatrapdfreader.org/docs/Commands)

**Comment by GitHubRulesOK** [comment]
@igogo2 I use two 3.5 portable official pre-release everyday for different usages (32 bit and 32bit+) https://www.[sumatrapdfreader.org/prerelease](https://www.sumatrapdfreader.org/prerelease) but both have been the most stable in a long time so suggest the only complaint is that some rogue files will trigger  the instant suggestion of unsaved changes when fixed for viewing, simply ignore and discard changes if you want to keep old input file.
