### ISSUE TITLE
[Feature request] Ability to customize or disable default keyboard shortcuts 

### ISSUE THREAD

**Issue by ami-null** [sumatrapdfreader/sumatrapdf#3602]
I use F8 as discord push to talk button. But F8 is set as the shortcut for show/hide toolbar in Sumatra. I want to be able to enable/disable such shortcuts. I have googled the issue and to the best of my knowledge, it is not implemented yet. Being able to edit the shortcut keys would be a life saver. Thanks.

**Comment by ami-null** [comment]
> See `customize a keyboard shortcut` on this page of the SumatraPDF documentation:
> 
> https://www.sumatrapdfreader.org/docs/Commands


I have added the following in the configuration file:

```
Shortcuts [
    [
        Cmd = CmdToggleToolbar
        Key = Ctrl + n
    ]
]
```

Now, `Ctrl+n` does toggle the toolbar, but `F8` is still triggering this shortcut. Is there any way to stop `F8` from toggling the toolbar?

**Comment by GitHubRulesOK** [comment]
it is there too look at https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts for adding Cmd = CmdNone as the Key = F8

**Comment by ami-null** [comment]
Oh, thanks. I was not thorough enough.
