### ISSUE TITLE
Highlight: only one possible color currently

### ISSUE THREAD

**Issue by A-Infor** [sumatrapdfreader/sumatrapdf#3607]
As [discussed since a year ago](https://github.com/sumatrapdfreader/sumatrapdf/discussions/2594), it would be nice to be able to have more than one `HighlightColor` under `Annotations` on [SumatraPDF-settings.txt](https://www.sumatrapdfreader.org/settings/settings3-5).

Why? Because, then, it would be possible to [customize keyboard shortcuts](https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts) in order for different keys to correspond to different highlighter pen colors.

I am sure that I am not the only one that have more than one highlighter pen on my case, being each of a different color, for highlighting on paper.

In my workplace, yellow, red, and green are specially useful. People understand better what the document is about with yellow, and see easily what is correct with green, and what is wrong with red.

Why not have the same choice on SumatraPDF settings file?
The other option is to print the PDFs in order to do the highligting, but this is not desirable. Otherwise, why use a PDF reader?

**Comment by kjk** [comment]
The right solution here would be to have commands that can take (optional) arguments.

Then you could create a key binding e.g.:
```

**Comment by Yasura47** [comment]
I tried it. It works except the color part. It uses the same color that in Annotation part not the one in the shortcut. What am i missing?

 [
	Cmd = CmdCreateAnnotHighlight 
	Key = d
	Color = #eda55c
        OpenEdit = false
 ]

Thank You!

**Comment by kjk** [comment]
Well, it's not implemented yet, just an idea.

**Comment by Yasura47** [comment]
Oh, Thank You!

**Comment by kjk** [comment]
In pre-release 16374 or later (https://www.sumatrapdfreader.org/prerelease) you can do:

```
Shortcuts [
	[
		Cmd = CmdCreateAnnotHighlight #00ff00   
		Key = b
	]
]
```
This creates shortcut `b` for creating green highlight
See https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts

**Comment by tomasrei** [comment]
> In pre-release 16374 or later (https://www.sumatrapdfreader.org/prerelease) you can do:
> 
> ```
> Shortcuts [
> 	[
> 		Cmd = CmdCreateAnnotHighlight #00ff00 openedit
> 		Key = b
> 	]
> ]
> ```
> 
> This creates shortcut `b` for creating green highlight See https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts

I find that this doesnt work. I have in my settings:

```
Shortcuts [
	[
		Cmd = CmdCreateAnnotHighlight #00ff00 openedit
		Key = b
	]
]
```

The log:

```
CreateSumatraAcceleratorTable: unknown cmd name 'CmdCreateAnnotHighlight #00ff00 openedit'
```

I'm using v 3.5.2 (portable edition)

**Comment by GitHubRulesOK** [comment]
@tomasrei it will not work in 3.5.2 only in 3.6.x

**Comment by tomasrei** [comment]
> @tomasrei it will not work in 3.5.2 only in 3.6.16374 + currently https://www.sumatrapdfreader.org/prerelease

Thanks! It works now :)
