### ISSUE TITLE
Scrollbar should represent the length of document instead of current page

### ISSUE THREAD

**Issue by skylee91** [sumatrapdfreader/sumatrapdf#361]
Hi, could we have a setting to choose the scrollbar represent the length of document or current page?

**Comment by kjk** [comment]
Different view modes do that and we don't have plans to go beyond that.

**Comment by skylee91** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5526164/11404716/5a4aa75a-93de-11e5-8464-02ce6b3bd16c.png)

Thanks, @kjk, finally found this solution as you mentioned.
