### ISSUE TITLE
Something wrong with epub files

### ISSUE THREAD

**Issue by Fan-Apple** [sumatrapdfreader/sumatrapdf#3616]
I always use sumatrapdf to open epub files. I used v3.1 in the past and there's nothing wrong. 
However, after I upgrade to v3.4, many BLANK pages appear.(shown in the screenshot) 

![图片](https://github.com/sumatrapdfreader/sumatrapdf/assets/60562348/754e1a52-148d-4476-8838-907594f9594b)

**Comment by kjk** [comment]
Can't investigate without a repro file.
