### ISSUE TITLE
'http://www.sumatrapdfreader.org/  ' sometimes not open in China

### ISSUE THREAD

**Issue by z007** [sumatrapdfreader/sumatrapdf#362]
__Recommend Installer, Portable version and md5, sha1 on a github.com.__

**Comment by kjk** [comment]
I don't have control over that. We're not planning to change where downloads are.

**Comment by SumatraPeter** [comment]
@kjk: Can you add the SHA1 hashes for the EXE and ZIP on the download page though (and for the portable version as well)? That is a good suggestion IMO.
