### ISSUE TITLE
Ability to adjust brightness

### ISSUE THREAD

**Issue by yeezylife** [sumatrapdfreader/sumatrapdf#3622]
![photo_2017-03-15_17-22-05](https://github.com/sumatrapdfreader/sumatrapdf/assets/30175425/a65e5b1e-0195-47f7-aafc-11e7244b530a)
Sometimes when I read, I would find that the image/background is to bright.
Something like this, some sort of Image enhancement filter will be nice.

**Comment by kosi2801** [comment]
Hi @yeezylife,
this looks like an iPad screenshot, is this correct? Furthermore the format is stated as CBR file.
Is this really SumatraPDF that you are using to read your comic or a different tool?
