### ISSUE TITLE
Restoring state

### ISSUE THREAD

**Issue by su-space** [sumatrapdfreader/sumatrapdf#3629]
I'm not completely sure if this started with updating windows or not.

I'm on Windows 10 21H2 OS build 19044.3324

I can open multiple copies of the same PDF in the same instance. The copies would be in distinct tabs. I would browse to different pages on the different copies.

Example:
progit.pdf pages 63
progit.pdf pages 102
progit.pdf pages 3

I have settings set to restore state.
When I close sumatrapdf and then open it, the copies of progit.pdf would open in three different tabs. They would be at the pages listed above. Zoom left and everything would be intact.

Now, when I close and reopen it, the settings in the SessionData do not seem to matter. I get three copies in three different tabs, but the page is from the FileStates. All three copies open at the same page.

Not sure if this is new or not, but it seems like the files aren't loaded until I actually click on the tabs.

**Comment by kjk** [comment]
Yeah, latest version has lazy loading of files i.e. the file is only loaded when you switch to a tab.

As a side effect this happens.

Lazy loading is to  speed up startup when restoring session with large number of files as loading blocks the main thread so opening them all can take a long time.

Not sure if there's an easy fix. Maybe somehow preserve initial state for each tab and use that.

**Comment by su-space** [comment]
Session restore is one of the key features that sets sumatrapdf apart. Lazy loading might speedup start up, but cost is breaking the session restore feature. Personally, I don't think it is worth it. Its better to wait for everything to load and fully restored, then to have to try and remember what state each tabs were on myself.
I'm sure most people that uses the restore session feature would feel the same way. 



    On Monday, September 11, 2023 at 08:23:05 PM EDT, Krzysztof Kowalczyk ***@***.***> wrote:  
 
 


Yeah, latest version has lazy loading of files i.e. the file is only loaded when you switch to a tab.

As a side effect this happens.

Lazy loading is to speed up startup when restoring session with large number of files as loading blocks the main thread so opening them all can take a long time.

Not sure if there's an easy fix. Maybe somehow preserve initial state for each tab and use that.

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/e717d53aed85702332d5c64a1236bcc041c6706d
