### ISSUE TITLE
can sumatra pdf support eml？

### ISSUE THREAD

**Issue by abshuhuhuhu** [sumatrapdfreader/sumatrapdf#363]
now  it's not usual to receive a eml file  anyway.
but if you occationally got one.
it may be hard to find a software to open and read it even allover the internet.
later, I find the way that  changing the file extention name from .eml to .mht and ie shows the text content well.but attachment would be missed. 
so I hope sumatra pdf can read it all well. 
there's so many requests on the internet looking for eml reader and google shows no good answer anyway.
With this small feature, I hope sumatra will be found and used more popular.
Hope you guys can add it in.
best wishes!

**Comment by kjk** [comment]
We don't have plans for eml support.
