### ISSUE TITLE
Crash on opening file

### ISSUE THREAD

**Issue by sshankar-rks** [sumatrapdfreader/sumatrapdf#3634]
Crash file: E:\Users\shank\AppData\Local\SumatraPDF\crashinfo\sumatrapdfcrash.txt
Exe: E:\Program Files\SumatraPDF\SumatraPDF.exe
BuiltOn: 2020-03-14
Type: dll
Ver: 3.2 64-bit
Git: fc8f35a2d0581735ea361990dc65c674b3cd2dcb (https://github.com/sumatrapdfreader/sumatrapdf/commit/fc8f35a2d0581735ea361990dc65c674b3cd2dcb)
OS: Windows 10 build 19045 64-bit
Number Of Processors: 24
Processor: AMD Ryzen 9 3900X 12-Core Processor            
Physical Memory: 63.92 GB
Commit Charge Limit: 73.42 GB
Memory Used: 32%
Machine: To be filled by O.E.M. System Version
Lang: en US
Graphics driver 0
  DriverDesc:         NVIDIA GeForce RTX 2060
  DriverVersion:      31.0.15.1694
  UserModeDriverName: C:\WINDOWS\System32\DriverStore\FileRepository\nv_dispig.inf_amd64_ee20464bb4ac57f4\nvldumdx.dll

Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FFCB6EED9F7 01:000000000004C9F7 libmupdf.dll!template_affine_N_near_fb0+0x127 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+703
Fault writing address 000001D4552BBEDC

Registers:
RAX:0000000000000008  RBX:000001D4552BBEDC  RCX:0000000000000000
RDX:0000000000000003  RSI:0000000000000000  RDI:FFFFFE2BAAD44124
R8: 0000000000000000
R9: 0000000000000003
R10:0000000000000004
R11:0000000000000000
R12:0000000000000003
R13:0000000000000003
R14:0000000000000000
R15:00007FF7E802F094
CS:RIP:0033:00007FFCB6EED9F7
SS:RSP:002B:00000000605FEC50  RBP:000000FF
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00010297

Crashed thread:
00007FFCB6EED9F7 01:000000000004C9F7 libmupdf.dll!template_affine_N_near_fb0+0x127 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+703
00007FFCB6EF79B1 01:00000000000569B1 libmupdf.dll!fz_paint_image_imp+0x1011 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+4081
00007FFCB6F099DF 01:00000000000689DF libmupdf.dll!fz_draw_fill_image+0xa8f C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-device.c+1803
00007FFCB6EC4B37 01:0000000000023B37 libmupdf.dll!fz_fill_image+0x97 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\device.c+337
00007FFCB6EE3B5E 01:0000000000042B5E libmupdf.dll!fz_run_display_list+0xdee C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\list-device.c+1800
00007FF7E80E8149 01:0000000000187149 sumatrapdf.exe!EnginePdf::RenderPage+0x439 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1191
00007FF7E8055ABC 01:00000000000F4ABC sumatrapdf.exe!RenderCache::RenderCacheThread+0x28c C:\Users\kjk\src\sumatrapdf\src\RenderCache.cpp+634
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 4c3c
00007FFD96F41104 01:0000000000000104 win32u.dll!NtUserGetMessage+0x14
00007FFD990A1BAE 01:0000000000020BAE user32.dll!GetMessageW+0x2e
00007FF7E807D2EE 01:000000000011C2EE sumatrapdf.exe!WinMain+0x201e C:\Users\kjk\src\sumatrapdf\src\SumatraStartup.cpp+1149
00007FF7E812FD66 01:00000000001CED66 sumatrapdf.exe!__scrt_common_main_seh+0x106 d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl+288
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Thread: f4
00007FFD993AD134 01:000000000009C134 ntdll.dll!ZwWaitForSingleObject+0x14
00007FFD96A130CE 01:00000000000220CE kernelbase.dll!WaitForSingleObjectEx+0x8e
00007FF7E802DD83 01:00000000000CCD83 sumatrapdf.exe!DumpExceptionHandler+0xa3 C:\Users\kjk\src\sumatrapdf\src\CrashHandler.cpp+341
00007FFD96B1DDA7 01:000000000012CDA7 kernelbase.dll!UnhandledExceptionFilter+0x1e7
00007FFD993B5570 01:00000000000A4570 ntdll.dll!memset+0x13b0
00007FFD9939C8C6 01:000000000008B8C6 ntdll.dll!_C_specific_handler+0x96
00007FFD993B247F 01:00000000000A147F ntdll.dll!_chkstk+0x11f
00007FFD993614F4 01:00000000000504F4 ntdll.dll!RtlRaiseException+0x484
00007FFD993B0F8E 01:000000000009FF8E ntdll.dll!KiUserExceptionDispatcher+0x2e
00007FFCB6EED9F7 01:000000000004C9F7 libmupdf.dll!template_affine_N_near_fb0+0x127 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+703
00007FFCB6EF79B1 01:00000000000569B1 libmupdf.dll!fz_paint_image_imp+0x1011 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-affine.c+4081
00007FFCB6F099DF 01:00000000000689DF libmupdf.dll!fz_draw_fill_image+0xa8f C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\draw-device.c+1803
00007FFCB6EC4B37 01:0000000000023B37 libmupdf.dll!fz_fill_image+0x97 C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\device.c+337
00007FFCB6EE3B5E 01:0000000000042B5E libmupdf.dll!fz_run_display_list+0xdee C:\Users\kjk\src\sumatrapdf\mupdf\source\fitz\list-device.c+1800
00007FF7E80E8149 01:0000000000187149 sumatrapdf.exe!EnginePdf::RenderPage+0x439 C:\Users\kjk\src\sumatrapdf\src\EnginePdf.cpp+1191
00007FF7E8055ABC 01:00000000000F4ABC sumatrapdf.exe!RenderCache::RenderCacheThread+0x28c C:\Users\kjk\src\sumatrapdf\src\RenderCache.cpp+634
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 5244
00007FFD993ADC04 01:000000000009CC04 ntdll.dll!NtWaitForMultipleObjects+0x14
00007FFD96A41B40 01:0000000000050B40 kernelbase.dll!WaitForMultipleObjectsEx+0xf0
00007FF7E80A6F84 01:0000000000145F84 sumatrapdf.exe!FileWatcherThread+0x84 C:\Users\kjk\src\sumatrapdf\src\utils\FileWatcher.cpp+283
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 5fdc
00007FFD993B0B44 01:000000000009FB44 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFD99362E67 01:0000000000051E67 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 5614
00007FFD993B0B44 01:000000000009FB44 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFD99362E67 01:0000000000051E67 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 5e90
00007FFD993B0B44 01:000000000009FB44 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFD99362E67 01:0000000000051E67 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 5cd4
00007FFD993B0B44 01:000000000009FB44 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFD99362E67 01:0000000000051E67 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Thread: 5730
00007FFD993B0B44 01:000000000009FB44 ntdll.dll!ZwWaitForWorkViaWorkerFactory+0x14
00007FFD99362E67 01:0000000000051E67 ntdll.dll!TpReleaseCleanupGroupMembers+0x747
00007FFD973E7614 01:0000000000016614 kernel32.dll!BaseThreadInitThunk+0x14
00007FFD993626F1 01:00000000000516F1 ntdll.dll!RtlUserThreadStart+0x21

Module: 00007FF7E7F60000 948000 SumatraPDF.exe   E:\Program Files\SumatraPDF\SumatraPDF.exe
Module: 00007FFD99310000 1F8000 ntdll.dll        C:\WINDOWS\SYSTEM32\ntdll.dll
Module: 00007FFD973D0000 0BF000 KERNEL32.DLL     C:\WINDOWS\System32\KERNEL32.DLL
Module: 00007FFD969F0000 2F6000 KERNELBASE.dll   C:\WINDOWS\System32\KERNELBASE.dll
Module: 00007FFD99080000 19D000 USER32.dll       C:\WINDOWS\System32\USER32.dll
Module: 00007FFD96F40000 022000 win32u.dll       C:\WINDOWS\System32\win32u.dll
Module: 00007FFD80680000 29A000 COMCTL32.dll     C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\COMCTL32.dll
Module: 00007FFD97580000 02C000 GDI32.dll        C:\WINDOWS\System32\GDI32.dll
Module: 00007FFD92D60000 5C0000 d2d1.dll         C:\WINDOWS\SYSTEM32\d2d1.dll
Module: 00007FFD98F30000 09E000 msvcrt.dll       C:\WINDOWS\System32\msvcrt.dll
Module: 00007FFD96E20000 115000 gdi32full.dll    C:\WINDOWS\System32\gdi32full.dll
Module: 00007FFD971D0000 09D000 msvcp_win.dll    C:\WINDOWS\System32\msvcp_win.dll
Module: 00007FFD96F70000 100000 ucrtbase.dll     C:\WINDOWS\System32\ucrtbase.dll
Module: 00007FFD98AA0000 0DA000 COMDLG32.dll     C:\WINDOWS\System32\COMDLG32.dll
Module: 00007FFD98610000 354000 combase.dll      C:\WINDOWS\System32\combase.dll
Module: 00007FFD80C50000 09D000 WINSPOOL.DRV     C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
Module: 00007FFD98970000 126000 RPCRT4.dll       C:\WINDOWS\System32\RPCRT4.dll
Module: 00007FFD98FD0000 0AD000 shcore.dll       C:\WINDOWS\System32\shcore.dll
Module: 00007FFD98ED0000 055000 SHLWAPI.dll      C:\WINDOWS\System32\SHLWAPI.dll
Module: 00007FFD97630000 744000 SHELL32.dll      C:\WINDOWS\System32\SHELL32.dll
Module: 00007FFD98DF0000 0AF000 ADVAPI32.dll     C:\WINDOWS\System32\ADVAPI32.dll
Module: 00007FFD98C20000 09C000 sechost.dll      C:\WINDOWS\System32\sechost.dll
Module: 00007FFD984E0000 12A000 ole32.dll        C:\WINDOWS\System32\ole32.dll
Module: 00007FFD98CC0000 0CD000 OLEAUT32.dll     C:\WINDOWS\System32\OLEAUT32.dll
Module: 00007FFD98EA0000 030000 IMM32.DLL        C:\WINDOWS\System32\IMM32.DLL
Module: 00007FFD93F20000 09E000 uxtheme.dll      C:\WINDOWS\system32\uxtheme.dll
Module: 00007FFD943D0000 02F000 dwmapi.dll       C:\WINDOWS\system32\dwmapi.dll
Module: 00007FFD97EA0000 008000 normaliz.dll     C:\WINDOWS\System32\normaliz.dll
Module: 00007FFD6FCA0000 2F5000 uiautomationcore.dll C:\WINDOWS\system32\uiautomationcore.dll
Module: 00007FFD91F50000 0F6000 PROPSYS.dll      C:\WINDOWS\SYSTEM32\PROPSYS.dll
Module: 00007FFD95000000 1E4000 dbghelp.dll      C:\WINDOWS\system32\dbghelp.dll
Module: 00007FFD83920000 034000 dbgcore.DLL      C:\WINDOWS\SYSTEM32\dbgcore.DLL
Module: 00007FFD80920000 1A5000 gdiplus.dll      C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.2251_none_91a40448cc8846c1\gdiplus.dll
Module: 00007FFD837D0000 007000 msimg32.dll      C:\WINDOWS\system32\msimg32.dll
Module: 00007FFD85AD0000 1EC000 urlmon.dll       C:\WINDOWS\system32\urlmon.dll
Module: 00007FFD88B70000 2B1000 iertutil.dll     C:\WINDOWS\SYSTEM32\iertutil.dll
Module: 00007FFD95F10000 00C000 netutils.dll     C:\WINDOWS\SYSTEM32\netutils.dll
Module: 00007FFD8E6E0000 028000 srvcli.dll       C:\WINDOWS\SYSTEM32\srvcli.dll
Module: 00007FFD90900000 00A000 version.dll      C:\WINDOWS\system32\version.dll
Module: 00007FFD8E500000 1B4000 windowscodecs.dll C:\WINDOWS\system32\windowscodecs.dll
Module: 00007FFD96CF0000 027000 bcrypt.dll       C:\WINDOWS\System32\bcrypt.dll
Module: 00007FFD7E2F0000 4D6000 wininet.dll      C:\WINDOWS\system32\wininet.dll
Module: 00007FFD94790000 793000 windows.storage.dll C:\WINDOWS\SYSTEM32\windows.storage.dll
Module: 00007FFD96360000 02E000 Wldp.dll         C:\WINDOWS\SYSTEM32\Wldp.dll
Module: 00007FFD96930000 01F000 profapi.dll      C:\WINDOWS\SYSTEM32\profapi.dll

-------- Log -----------------

Starting SumatraPDF
CmdLine: "E:\Program Files\SumatraPDF\SumatraPDF.exe" "9781955744096-Case_20230901.pdf" 
LoadDocument: '9781955744096-Case_20230901.pdf', tid=19516
CreateControllerForFile: '9781955744096-Case_20230901.pdf'
LoadDocument: !forceReuse, created win->currentTab at 0x000001D3547BFF00
RenderCache::Paint() pageNo: 1, bounds={4,2,1895,1107} in 0.01
RenderCache::Paint() pageNo: 1, bounds={4,0,1895,1109} in 0.00
LoadDocument: after LoadDocIntoCurrentTab win->currentTab is 0x000001D3547BFF00, path: '9781955744096-Case_20230901.pdf'
StartMonitoringDirForChangesAPC() 
StartMonitoringDirForChangesAPC() E:\Users\shank\AppData\Local\SumatraPDF
RenderCache::Paint() pageNo: 1, bounds={4,0,1895,1109} in 0.00
premature end of data in flate filter
RenderCache::Paint() pageNo: 1, bounds={4,0,1895,1109} in 0.00
RenderCache::Paint() pageNo: 1, bounds={4,0,1895,1109} in 0.61
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 2.66
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 2.14
... repeated 4 times...
items left on stack in draw device: 1
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 2.07
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 1.87
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 1.97
premature end of data in flate filter
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 1.86
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 2.80
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 3.76
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 3.86
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 3.67
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 3.77
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 3.94
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 4.07
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 4.38
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 4.55
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 6.76
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 12.25
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 13.32
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 12.60
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 10.61
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 17.26
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 16.36
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 4.48
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 1.67
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 6.44
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 0.75
RenderCache::Paint() pageNo: 1, bounds={4,0,1895,1109} in 5.94
RenderCache::Paint() pageNo: 1, bounds={87,0,1728,1109} in 6.07
... repeated 19 times...
items left on stack in draw device: 1
RenderCache::Paint() pageNo: 1, bounds={87,0,1728,1109} in 0.57
RenderCache::Paint() pageNo: 1, bounds={164,2,1591,1105} in 4.73
RenderCache::Paint() pageNo: 1, bounds={164,2,1591,1105} in 0.53
StartMonitoringDirForChangesAPC() E:\Users\shank\AppData\Local\SumatraPDF
StartMonitoringDirForChangesAPC() E:\Users\shank\AppData\Local\SumatraPDF
LoadDocument: '9781955744096-Case_20230901.pdf', tid=19516
CreateControllerForFile: '9781955744096-Case_20230901.pdf'
LoadDocument: !forceReuse, created win->currentTab at 0x000001D3548DE6B0
RenderCache::Paint() pageNo: 1, bounds={164,2,1591,1105} in 0.00
LoadDocument: after LoadDocIntoCurrentTab win->currentTab is 0x000001D3548DE6B0, path: '9781955744096-Case_20230901.pdf'
StartMonitoringDirForChangesAPC() 
StartMonitoringDirForChangesAPC() E:\Users\shank\AppData\Local\SumatraPDF
StartMonitoringDirForChangesAPC() E:\Users\shank\AppData\Local\SumatraPDF
RenderCache::Paint() pageNo: 1, bounds={164,2,1591,1105} in 0.00
premature end of data in flate filter
RenderCache::Paint() pageNo: 1, bounds={164,2,1591,1105} in 0.56
RenderCache::Paint() pageNo: 1, bounds={164,2,1591,1105} in 0.51
RenderCache::Paint() pageNo: 1, bounds={164,2,1591,1105} in 0.76
... repeated 4 times...
LoadDocument: '9781955744089-Case_20230901.pdf', tid=19516
CreateControllerForFile: '9781955744089-Case_20230901.pdf'
LoadDocument: !forceReuse, created win->currentTab at 0x000001D354A5F270
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 0.02
LoadDocument: after LoadDocIntoCurrentTab win->currentTab is 0x000001D354A5F270, path: '9781955744089-Case_20230901.pdf'
StartMonitoringDirForChangesAPC() 
StartMonitoringDirForChangesAPC() E:\Users\shank\AppData\Local\SumatraPDF
StartMonitoringDirForChangesAPC() E:\Users\shank\AppData\Local\SumatraPDF
premature end of data in flate filter
RenderCache::Paint() pageNo: 1, bounds={0,0,1903,1092} in 0.01

----- Settings file ----------

﻿# For documentation, see https://www.sumatrapdfreader.org/settings/settings3.2.html

MainWindowBackground = #80fff200
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true
TabWidth = 300

FixedPageUI [
	TextColor = #000000
	BackgroundColor = #ffffff
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
EbookUI [
	FontName = Georgia
	FontSize = 12.5
	TextColor = #5f4b32
	BackgroundColor = #fbf0d9
	UseFixedPageUI = false
]
ComicBookUI [
	WindowMargin = 0 0 0 0
	PageSpacing = 4 4
	CbxMangaMode = false
]
ChmUI [
	UseFixedPageUI = false
]
ExternalViewers [
]
ShowMenubar = true
ReloadModifiedDocuments = true
FullPathInTitle = false
ZoomLevels = 8.33 12.5 18 25 33.33 50 66.67 75 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400
ZoomIncrement = 0

PrinterDefaults [
	PrintScale = shrink
]
ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6581ff
	HighlightPermanent = false
]
CustomScreenDPI = 0

RememberStatePerDocument = true
UiLanguage = en
ShowToolbar = true
ShowFavorites = false
AssociateSilently = false
CheckForUpdates = true
RememberOpenedFiles = true
EnableTeXEnhancements = false
DefaultDisplayMode = automatic
DefaultZoom = fit page
WindowState = 2
WindowPos = 206 18 974 735
ShowToc = true
SidebarDx = 377
TocDy = 0
ShowStartPage = true
UseTabs = true

SessionData [
]
TimeOfLastUpdateCheck = 0 0
OpenCountWeek = 661

# Settings after this line have not been recognized by the current version

**Comment by GitHubRulesOK** [comment]
usually in that version it is down to a MuPDF crash triggered by zooming see https://github.com/sumatrapdfreader/sumatrapdf/issues/1514
fixed in 2021 releases  (3.3+)

**Comment by kjk** [comment]
3.2 is a very old version, please use the latest version.
