### ISSUE TITLE
Disable Save As

### ISSUE THREAD

**Issue by billdenver** [sumatrapdfreader/sumatrapdf#3637]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3636

<div type='discussions-op-text'>

<sup>Originally posted by **billdenver** September  7, 2023</sup>
The problem we face when using SumatraPDF is that users can “Save As” creating a new file.  This causes multiple files and this gets worse as one user will annotate and save a copy and another user will annotate and save a different copy so we now have the original plus 2+++n different files with different notes, etc.  

Is it possible to open the current file with prior user’s notes if any, add notes and save the file, etc. but NOT have the ability to save to a different name or location.</div>

**Comment by kjk** [comment]
That's a very specific customization that we don't plan to implement.
