### ISSUE TITLE
Comments are truncated

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3638]
As per issue #3086, "long" comments are truncated, which makes reading them very difficult (and reading comments is ever so useful!)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/e3581469-fa05-4d75-8581-41bf938bceef)

I discovered this after trying the pre-release build, because 3.4.6 had the flickering long comment bug. Truncating the text may stop the flickering, but it's not really a solution :-)

**Comment by kerryland** [comment]
Here is a [sample pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12553034/sample.pdf)

**Comment by kjk** [comment]
How does it look in other PDF readers?

We truncate comments because they are shown using a tooltip control and it doesn't do well with large text: it flickers, it's very slow and if we don't truncate at all, it might create a very large tooltip.

**Comment by GitHubRulesOK** [comment]
@kjk 
I know we had problems with larger tooltips and Edge seem to also "truncate" tooltips to a manageable area, however Acrobat tends to use scroll boxes in line (in screen modal pop-up) and comments sidebars
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9b55d380-bf20-4d17-868e-2c396f51a926)

**Comment by kjk** [comment]
I get the need for it but doing what Acrobat does would be a significant change.

**Comment by GitHubRulesOK** [comment]
I wonder the proposed free text enhancement allows such as this !! for better or worse 
Would it be posible to make that modal as popup ?
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9b24381d-1ee2-4df9-b8d0-e669ebe86f6c)

**Comment by kerryland** [comment]
> How does it look in other PDF readers?
> 
> We truncate comments because they are shown using a tooltip control and it doesn't do well with large text: it flickers, it's very slow and if we don't truncate at all, it might create a very large tooltip.

What was wrong with the implementation in Sumatra 3.3? It seemed to work OK with very large comments, and did not flicker.

That said, I have just discovered the "Annotation Editor", and I think this issue could be nicely solved with minor improvements in the integration between the Annotation Editor and the PDF viewer. Something like this:

- Double-clicking on a comment in the viewer should be the same as "Select Annotation in Editor". This would make it very easy to work through comments made on my document. Hurrah!
- Within the Annotation Editor, clicking on an annotation already adjusts the PDF view to show the location of the comment, but it needs a visual indicator to highlight the specific text that the comment applies to. Something like this red box:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/94009552-1ebd-4320-a217-51809b3a7938)

- Also, in the context menu, rename "Copy Comment" to "Copy Annotation" (or replace "Annotation" with "Comment" everywhere). Don't mix terminology.

We are *so close*! This is a much nicer workflow than hovering over bits of yellow text!

**Comment by kerryland** [comment]
> What was wrong with the implementation in Sumatra 3.3? It seemed to work OK with very large comments, and did not flicker.

I can answer that myself now: Bug #2814
