### ISSUE TITLE
[Feature request] Can sumatraPDF support export and import XDFD (XML-based Forms Data Format file) ?

### ISSUE THREAD

**Issue by xh542428798** [sumatrapdfreader/sumatrapdf#3639]
Can sumatraPDF support export and import XDFD (XML-based Forms Data Format file) ?  So I can import annotations from other pdf reader.

**Comment by GitHubRulesOK** [comment]
SumatraPDF in common with many PDF readers cannot handle
Adobe AI or Adobe XML or Adobe PSD  or Adobe DE (all adobe licensed proprietary formats)
Adobe is withdrawing support for XFA similar to SWF formats are EOL as not part of Open Sourced License
XML are not part of PDF ISO version 1.x or version 2.0 
so advice is to rebuild XMP/XML/XFA as conventional licensed AcroForm compatible PDFs

Currently SumatraPDF does not support AcroForm handling **but can read/show fields** whilst MuPDF can write/redact fields too, but not offer extraction and loading like PDFtk can.

**Comment by xh542428798** [comment]
> SumatraPDF in common with many PDF readers cannot handleSumatraPDF 与许多 PDF 阅读器一样无法处理 *1 Adobe AI or Adobe XML (adobe licensed proprietary formats)*1 Adob​​e AI 或 Adob​​e XML（Adobe 许可的专有格式） *2 or Adobe PSD or Adobe DE (adobe licensed proprietary formats) *2 或 Adob​​e PSD 或 Adob​​e DE（adobe 许可的专有格式） Adobe is withdrawing support for XFA similar to SWF formats are EOL as not part of Open Sourced LicenseAdobe 正在取消对 XFA 的支持，类似于 SWF 格式，这些格式已停产，不属于开源许可证的一部分 XML are not part of PDF ISO version 1.x or version 2.0 XML 不是 PDF ISO 版本 1.x 或版本 2.0 的一部分 so advice is to rebuild XMP/XML/XFA as conventional licensed AcroForm compatible PDFs 因此建议将 XMP/XML/XFA 重建为传统许可的 AcroForm 兼容 PDF
> 
> Currently SumatraPDF does not support AcroForm handling **but can read/show fields** (online can extract annotations) whilst MuPDF can write/redact fields too, but not offer extraction and loading like PDFtk can.目前，SumatraPDF 不支持 AcroForm 处理，但可以读取/显示字段（可以在线提取注释），而 MuPDF 也可以写入/编辑字段，但不提供像 PDFtk 那样的提取和加载功能。
> 
> For command line import/export of PDF data Fields those that can be export import by venerable PDFtk or its many many clones would be the yardstick to aim for, but a visual reader does not need to import and export, like say an editor such as PDFxedit.对于 PDF 数据的命令行导入/导出，那些可以通过古老的 PDFtk 或其许多克隆导出导入的字段将是目标标准，但视觉阅读器不需要导入和导出，就像编辑器一样PDFx编辑。
> 
> *1 may be able to handle parts of in some cases. (e.g. AI files saved as PDF are viewable)*1 在某些情况下可能能够处理部分。 （例如保存为 PDF 的 AI 文件可以查看） *2 PS & EPS can be loaded via GhostScript conversion. *2 PS & EPS 可以通过 GhostScript 转换加载。

I get it, thanks a lot
