### ISSUE TITLE
The '-invert-colors' command line option doesn't work on CHM files

### ISSUE THREAD

**Issue by darkred** [sumatrapdfreader/sumatrapdf#364]
I use v3.1.1 (have tried both x86 and x64 versions) in win10 x64
and I run it with the `-invert-colors` command line option.

The program starts and if I open a CHM file (I've tried various CHM files),
it displays it in normal colors, instead. 
_(but PDF files are in inverted colors though, as expected)_

What only is displayed in inverted colors is the `Frequently Read` thumbnails
on next program startup.

<br>
Thank you

**Comment by kjk** [comment]
It's a known issue but impossible to fix.
