### ISSUE TITLE
Make for android !

### ISSUE THREAD

**Issue by Avtroman** [sumatrapdfreader/sumatrapdf#3640]
Please, make program for android !

**Comment by GitHubRulesOK** [comment]
MuPDF (SumatraPDF core viewer) is released for Android in different ways, so suggest you consider that version

**Comment by KrasnayaPloshchad** [comment]
Maybe you can try [Librera](https://github.com/foobnix/LibreraReader) on Android.

**Comment by kjk** [comment]
No plans for Android, see https://www.sumatrapdfreader.org/docs/Why-only-Windows
