### ISSUE TITLE
Invert colors shortcut "i" doesn't invert background color in CHM files.

### ISSUE THREAD

**Issue by zsdex** [sumatrapdfreader/sumatrapdf#3644]
It works for PDF files but not for CHM.

**Comment by GitHubRulesOK** [comment]
It could and does only work for SumatraPDF viewer not for the imbedded MS CHM view

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4425db1a-bf5a-4fca-8261-ebe00e636e4e)

**Comment by zsdex** [comment]
Wow I didn't know about UseFixedPageUI setting, looking nice.

I'm closing this issue.
