### ISSUE TITLE
Remember opened files with only 1 opened file bug

### ISSUE THREAD

**Issue by ghdq** [sumatrapdfreader/sumatrapdf#365]
Hi,
When there is only 1 opened file, Sumatra doesn't remember the opened file. It works with 2 or more opened files.

Please fix bug.

Sumatra 3.1.1 x64

**Comment by kjk** [comment]
We remember the file. We only re-open on startup if there were 2 or more files open at the time of closing as a heuristic. This is behaving as designed.
