### ISSUE TITLE
Hello from a goverment user 

### ISSUE THREAD

**Issue by orithecapper** [sumatrapdfreader/sumatrapdf#3656]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/131520229/f3559383-bd31-41a9-be3e-e6a89502bfac)

Hello when in my days... we used a lot Sumantra P D F .

please advice this site to use it 
https://www.va.gov/oig/get-readers.asp

**Comment by GitHubRulesOK** [comment]
There is no issue
If they wish to link to SumatraPDF in addition to Adobe sites that is their prerogative

**Comment by orithecapper** [comment]
> There is no issue If they wish to link to SumatraPDF in addition to Adobe sites that is their prerogative

Lets get them do it... what should I search on linked in ? SumatraPDF is really the best tools out there... 

big youtubers should sponser it, as part of being mission driven and not profit driven

**Comment by tactilis** [comment]
> Lets get them do it... what should I search on linked in ? SumatraPDF is really the best tools out there...

Your desire to get the Department of Veterans Affairs, Office of Inspector General to promote the use of SumatraPDF in addition to Adobe Reader is _not_ a SumatraPDF issue.

So, why don't _you_ go to the va/oig website, click About Us | Organization | Office of Management and Administration and send them a well written argument as to why they should mention that in addition to Adobe Reader, other PDF viewers are available, for example SumatraPDF at https://www.sumatrapdfreader.org

**Comment by orithecapper** [comment]
> > Lets get them do it... what should I search on linked in ? SumatraPDF is really the best tools out there...
> 
> Your desire to get the Department of Veterans Affairs, Office of Inspector General to promote the use of SumatraPDF in addition to Adobe Reader is _not_ a SumatraPDF issue.
> 
> So, why don't _you_ go to the va/oig website, click About Us | Organization | Office of Management and Administration and send them a well written argument as to why they should mention that in addition to Adobe Reader, other PDF viewers are available, for example SumatraPDF at https://www.sumatrapdfreader.org

I just dont know man... most people will just ignore emails. Like we all do

**Comment by orithecapper** [comment]
> > Lets get them do it... what should I search on linked in ? SumatraPDF is really the best tools out there...
> 
> Your desire to get the Department of Veterans Affairs, Office of Inspector General to promote the use of SumatraPDF in addition to Adobe Reader is _not_ a SumatraPDF issue.
> 
> So, why don't _you_ go to the va/oig website, click About Us | Organization | Office of Management and Administration and send them a well written argument as to why they should mention that in addition to Adobe Reader, other PDF viewers are available, for example SumatraPDF at https://www.sumatrapdfreader.org

When you have the software Sumanta on your pc is great.... 
but many dont know which binrary to use as retard wage slave goverment workers

**Comment by tactilis** [comment]
> I just dont know man... most people will just ignore emails. Like we all do

Your discussion is pointless.

You are asking other people to lobby the organisation to use Sumatra PDF but you won't do anything yourself.

Bye.

**Comment by orithecapper** [comment]
> > I just dont know man... most people will just ignore emails. Like we all do
> 
> Your discussion is pointless.
> 
> You are asking other people to lobby the organisation to use Sumatra PDF but you won't do anything yourself.
> 
> Bye.

Lick yourself
