### ISSUE TITLE
[proposal] separate SumatraPDF-settings.txt on FileStates, Session_NameSession and  Settings

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#3658]
separate SumatraPDF-settings.txt on FileStates, Session_NameSession and  Settings.txt
use command line for it: SumatraPDF-prerel-64.exe -st Settings.txt -ss Session_NameSession.txt -fs FileStates.txt

**Comment by kjk** [comment]
No plans to do that.
