### ISSUE TITLE
Broken printing preferences menu

### ISSUE THREAD

**Issue by Edward-H** [sumatrapdfreader/sumatrapdf#366]
Since upgrading to v3.1 from v2.5, I have been unable to use the printer preferences menu. ![See screenshot.](https://cloud.githubusercontent.com/assets/5278522/11452340/60fc6dae-95dc-11e5-979c-f888339e2913.png) Flipping through the menu tabs and trying to use any of the fields causes SumatraPDF to crash. The crash occurs in a HP DLL (hpfuiw73.dll) and is caused by an unhandled exception: "0xC000041D: An unhandled exception was encountered during a user callback."

The printer is a HP Deskjet D2660 and the preferences menu is only broken in SumatraPDF.

**Comment by kjk** [comment]
The bug is most likely in the printer driver. Unfortunately without access to the printer there's nothing I can do to try to find a work-around.

**Comment by Edward-H** [comment]
Yeah, sorry, this is definitely a driver bug. HP have dropped support for the D2660 in Windows 10.
