### ISSUE TITLE
icons are changed without human involvement

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3664]
If you open [this file](https://github.com/sumatrapdfreader/sumatrapdf/files/5004024/BlankA4x2.ex.VS.eXpert.pdf) and drag this red triangle icon:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/76c20125-c20e-46ca-a47a-76488f3fb3ff)

it magically turns into this:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/550c0e07-45c0-4003-878a-28c65903d032)

To reproduce:

1. Open attached file
2. Drag the "Triangle" icon

OR

1. Open attached file
2. Open annotation editor (right-click, "Edit Annotations")
4. Click the first annotation, notice the icon drop-down says "Help". Notice also that the visual icon in the PDF is a triangle.
5. Change the "Go to page 2" text to something else

THEN

Notice the visual icon in the PDF has changed to a question-mark (the icon for "Help"). Oops.

The icon drop-down in step 3 should've displayed "Insert".

**Comment by GitHubRulesOK** [comment]
Not an issue it clearly shows it is a help iccon but apperance has not been updated yet.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9ee5c35b-0019-4daf-8016-caac502aab04)

**Comment by kjk** [comment]
Yeah, this happens for some annotations. I haven't looked deeply into it but apparently some annotations have appearance which dictates how it's being drawn. And appearance is not standardized so different editors can pick different graphics. And moving annotations causes mupdf to change the appearance.

Not sure if this is mupdf messes up the logic and if fixing that would require patching mupdf or could be done by us by ensuring the right appearance after the move.

**Comment by GitHubRulesOK** [comment]
@kjk 
My take on this sample is that it was at fault by using one apperance for another lable (same happens with Form fields the old data is stuck in the box until the apperances are changed to new contents , perhaps a flaw in PDF standard, but there should be enforced update when opening HOWEVER that then triggers This file needs saving which is a different related issue! (cant win them all)

**Comment by kerryland** [comment]
Let's not worry about it then. Closing tickets is good.
