### ISSUE TITLE
Remove ctrl-dblclick on annotations

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3666]
I know that [I suggested it](https://github.com/sumatrapdfreader/sumatrapdf/issues/3638#issuecomment-1714924035), and I know that it has been [successfully implemented](https://github.com/sumatrapdfreader/sumatrapdf/commit/5c63c533403e140ca8dc1051ef629a8166ad8ad2), but I now realise that the ["shortcut" functionality](https://github.com/sumatrapdfreader/sumatrapdf/pull/3665/commits/612df4d870f011122ba58bc0ecafe8010a71cd0e) is all that is needed to make navigation to an annotation easy.

**CTRL-double-click** is no more efficient than **double-click, e**.

This second method is also much more natural when you consider that an annotation can be added with **double-click, a**.

Either revert [this commit](https://github.com/sumatrapdfreader/sumatrapdf/commit/5c63c533403e140ca8dc1051ef629a8166ad8ad2) or delete these lines from `Canvas.cpp`. Removing code is always good :-)
```
    // ctrl + double click over annotation: start editing the annotation
    // check before IsOverText()
    if (pageEl && IsCtrlPressed() && pageEl->Is(kindPageElementComment)) {
        Annotation* annot = dm->GetAnnotationAtPos(mousePos, nullptr);
        if (annot) {
            StartEditAnnotations(win->CurrentTab(), annot);
            RepaintAsync(win, 0);
            return;
        }
    }
```

Do you agree?

**Comment by kjk** [comment]
sure
