### ISSUE TITLE
Induced a hang condition whilst playing with recent Free Text annots

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#3667]
As usual was pushing recent changes to see what breaks when "messin" about like a "virgin" user.

Several Minutes ago and still now it looks like a hang (no crash report)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/bc14b140-5403-4796-8bb9-d1e4ee667a72)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/88b0bd1f-4804-40df-842d-d26d592170c2)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/68b1e1ca-2e0e-4509-9164-7659a9899f35)

I took the "fixed" sample from previous issue, and opened in Edge to see what it does with Free Text in the box and as you can see I was altering font size to see its limits (8-36 in SumatraPDF)  I had made as small as possible in Edge where it defaults on save to 12 !! even if set smaller.
So the filename reflects it was saved in Edge then opened in SumatraPDF where I again tested size slider from 8 to 36 and was moving back down as box was not changing ! you can see it got to 33 then just sits there, as long as my slow fingers do not reach for the kill switch.

Clearly If I post the file it will only reflect the save before hang but here it is
[BlankA4x2.ex.VS.eXpert.Edge.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12641908/BlankA4x2.ex.VS.eXpert.Edge.pdf)

If I open again and slide the size up and down it seems OK but just remembered since the box was black I had also changed background to transparent too. ?? However I do not seem to make it hang again !!

**Comment by GitHubRulesOK** [comment]
tempted to close as not repeatable however it gives me the opertunity to say the box not resizing with text is somthing previously resolved by another user PLEASE SEE RELATED https://github.com/sumatrapdfreader/sumatrapdf/discussions/3489

**Comment by kerryland** [comment]
On a related note, I too was playing with that file and noticed that you can't move the "Ink" object, also, if you drag the "Free Text" object onto the "Ink" object it gets stuck and can no longer be moved. Here it is, trapped:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/8bee0c21-9c32-447f-a1af-4ecc44bed81c)

**Comment by GitHubRulesOK** [comment]
@kerryland 
Interesting but did you look at how https://github.com/youmjb has dealt with some issues I raised, it would be great if you helped them raise a PR (they seem not to be able to do that) the stamps feature is fantastic and seem to move around no problem (or had few problems at that time)

**Comment by kjk** [comment]
Yeah, would be good to look at and import all the good ideas from https://github.com/youmjb

**Comment by GitHubRulesOK** [comment]
I cant reproduce this hang over past 2 days so closing as nothing to work on=nothing to fix and chalk it down to bad operator actions until can be proven again
