### ISSUE TITLE
Disallow creating of duplicate annotations

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3668]
Once you start using keyboard shortcuts for working with annotations you learn that it's fairly easy to create duplicate annotations.

To reproduce:
- Open a PDF with no annotations
- Double-click a word, press 'a' to add an annotation. 
- Double-click the same word, press 'a' to add an annotation. 
- Right click, "Edit Annotations"
- Notice that you have two annotations for the same word.

Is this a good idea, or should we try and stop this?

**Comment by GitHubRulesOK** [comment]
Hmm not my call,
however I would say it is down to user control of their preference / ability
I have seen often a need to allow some overlaps of annots, (including highlight) but "unwise" for there to be two identical inline text

**Comment by kjk** [comment]
If it's easy to implement, then sure. If not => I wouldn't worry about that.
