### ISSUE TITLE
Bad toolbar icons when document is not open.

### ISSUE THREAD

**Issue by Konstantin749** [sumatrapdfreader/sumatrapdf#3669]
How it looks without opened document (its ugly...)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/58389262/2765af59-fa97-4164-8519-95462d38cb16)
And when a document is open icons become normal looking.
This should be default everywhere and will make Sumatra more popular since it wouldn't scare people with these 90s looking icons.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/58389262/d41d4f3b-664d-46ca-bc5c-353e18ea20df)

**Comment by GitHubRulesOK** [comment]
sadly it is a feature/side effect of modern SVG icons (the older 90s bitmaps were better for holding their blocky appearances)

**Comment by kjk** [comment]
That's windows' toolbar control that does that, not much I can do about it.

**Comment by Konstantin749** [comment]
So Windows makes icons look pixelated when they are greyed out?

**Comment by kjk** [comment]
yes

**Comment by Konstantin749** [comment]
Lol, another reason to switch to Linux

**Comment by kjk** [comment]
@expikr  I didn't do anything special, as far as can I remember.

Maybe the trick is that I'm (i.e. my GitHub account)  is creator and admin of sumatrapdfreader organization?
