### ISSUE TITLE
Impossible to move fully obscured annotation

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#3670]
As described in https://github.com/sumatrapdfreader/sumatrapdf/issues/3667, sometimes annotation A fully covers annotations B, making it impossible to move annotation B.

Two possible solutions:

1. When finding an annotation and seeing there is more than one that matches and one fully covers the other, select the smaller one.

Alternatively, or in addition: slightly change how we move annotations. Currently it's with Ctrl + drag.

Change to a model where we have a notion of currently selected annotation (which we already do for the purpose of highlighting).

Then this annotation is moved when dragging. Since annotations can also be selected in anontation editor window in the list, we could move any annotation by selecting it there.

**Comment by GitHubRulesOK** [comment]
bonus would be to be able to shift by alter XY dx dy (a long term beef of mine :-)

**Comment by kjk** [comment]
A smarter selection of annotation under cursor has been implemented in https://github.com/sumatrapdfreader/sumatrapdf/commit/aa97671def9ccae9243c604f739df815111660ba
