### ISSUE TITLE
A problem when I use annotation

### ISSUE THREAD

**Issue by 9Htang** [sumatrapdfreader/sumatrapdf#3680]
https://github.com/sumatrapdfreader/sumatrapdf/assets/111450903/c34f32b6-cdd3-473d-9563-c12bb20a5c1d

Can someone tell me how to solve this problem?

**Comment by kjk** [comment]
Does it happen with latest pre-release? https://www.sumatrapdfreader.org/prerelease
If yes, please provide a test file. You could extract that one page into a separate pdf file for a small test case.

**Comment by 9Htang** [comment]
> Does it happen with latest pre-release? https://www.sumatrapdfreader.org/prerelease If yes, please provide a test file. You could extract that one page into a separate pdf file for a small test case.

I download the latest pre-release and the problem disappeared. 
Thanks for your answer! 😄
