### ISSUE TITLE
Cursor Keys don't work in Annotation "Contents" field

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3685]
I've just noticed that cursor keys don't work in 3.5 pre-release when editing comments. It has existed since at least 3.5.15527 (a version I happened to have lying around)

 ![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/e0694ec9-b1a2-4a4c-bea5-b197d3b3bd98)

**Comment by GitHubRulesOK** [comment]
hmm I think there was a minor refactor to allow for backspace? or something similar 

and have I previously mentioned youmjb had resolved a lot of such issues EXCEPT not RTL and fonts :-0

**Comment by kerryland** [comment]
> and have I previously mentioned youmjb had resolved a lot of such issues

Feel free to close any issues I raise if they have been dealt with elsewhere.

**Comment by GitHubRulesOK** [comment]
@kerryland 
You are doing Stirling work , it was not meant to poke at your brilliant progress at closing issues, my C programming skull is less than a percent of yours. My jibe was more towards KJK and irrelevant in this case as porting in those changes is scheduled for post 3.5 and in this case make no difference.
