### ISSUE TITLE
Return to start page after you have finished searching

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3688]
After I have finished searching for text I would like to be able to easily return to the page I was on when I initiated the search.

To reproduce:
- Imagine you are a famous author
- Open the new novel you are writing (eg: https://github.com/sumatrapdfreader/sumatrapdf/files/12641281/bug3551-Emma.-.Jane.Austen.pdf)
- Go to page 10
- Wonder "what was it I said about the umbrella"
- Search for "Umbrella"
- Read the fascinating words
- Press **ESC** in the search box.
- Be surprised, because nothing happened.

I expected to return to where-ever I was when I decided to read about umbrellas, instead I have try and remember where that was, and navigate back manually.

I'm aware I could do a rather more cumbersome version of this with "Favorites", but this behaviour would be handy.

**Comment by kjk** [comment]
You can use `Alt - Left` to go back to page 10. We add navigation points and allow navigating back and forward like in a browser.

**Comment by kerryland** [comment]
> You can use `Alt - Left` to go back to page 10.

Ah. This is cool! It just needs a minor tweak though, because currently `Alt - Left` is not captured when you are in the 'Find' input field, which is where you are when you are searching for stuff :-)

**Comment by tactilis** [comment]
@kerryland   FYI  https://www.sumatrapdfreader.org/docs/Keyboard-shortcuts


> It just needs a minor tweak though, because currently Alt - Left is not captured when you are in the 'Find' input field, which is where you are when you are searching for stuff 

Agreed. Browsers allow ALT Left/Right navigation regardless of where the focus is.
