### ISSUE TITLE
Crashes after changing theme (or just settings?) multiple times

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3691]
Try this:
- Open `Settings | Advanced Options`
- Change the theme to  "Dark"
- Save the file
- Tab back to Sumatra
- See theme is indeed "Dark"
- Open `Settings | Advanced Options`
- Change the theme to  "Light"
- Save the file
- Tab back to Sumatra
- See theme is indeed "Light"
- **BUT** take a look at the menu...
 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/50fbf58a-cfde-4771-a542-5244553d2265)

Then things start [crashing](https://gist.github.com/kerryland/62db7535d38f58e2367e699aa31a8072). I actually initially suspected it was because I wasn't exiting the editor after saving changes to the configuration file, but I'm not sure.

**Comment by kjk** [comment]
This is a memory corruption.

If you were also playing with bookmarks, the crash could be https://github.com/sumatrapdfreader/sumatrapdf/commit/3102aa1c1774de3bd4f54ff76d918f1fc51e3571

I can repro the menu but not the crash so far.

**Comment by kjk** [comment]
Also we need more aggressive repaint after changing the theme.

And in custom menu painting we need to paint radio buttons - they are invisible in dark theme.

**Comment by kjk** [comment]
If you can repro the crash, please open a new issue.
