### ISSUE TITLE
Ability to edit and automatically open annotation editor

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3698]
Sumatra has trained me to look the right of my screen when I press `e`, so I can view and edit my highlighted annotation, but sometimes when I press `e` nothing happens, and I am confused. Ah, I remember, I need to open the annotation editor manually. But why? Couldn't `e` open it for me?

@kjk has an answer (from another conversation):

> I don't want an easy to press by accident key (i.e. e) to invoke a potentially confusing annotations window hence Ctrl + E which is still easy to press but not accidentally

Fair enough. I'm not sure it's *that* confusing, but I offer some ideas on how to solve this...

# Implementation Options

## Implement via a new command
Given we have the ability to define custom keys, and given we have `a` and `A`:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/96b1a29a-1be8-4c94-a36b-51c904c9d0ff)

How about we add the missing `E` to partner `e`, then I could rebind `E` to `e` and everybody's happy. So we would add a `CmdEditAndOpenAnnotations` command.

Note that this is *not* currently possible with `a` and `A` because they share the same command, so it's not actually possible to rebind `A` to any other key.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/c308da97-8816-485f-adb0-3976d1628f99)

## Add parameters to shortcuts
Here's a more radical idea, which *could* also be a way to provide shortcuts for favourite highlight colours. (https://github.com/sumatrapdfreader/sumatrapdf/issues/3607)
```
Shortcuts [
	[
		Cmd = CmdEditAnnotations
		Key = e
                OpenEdit = true
	]
	[
		Cmd = CmdCreateAnnotHighlight
		Key = L
                Color = Lime
                OpenEdit = true
	]

]
```
## Add a new configuration setting
The new setting would automatically open the editor whether the user presses `a`, or `e`, or uses any of the other `CmdCreateAnnot...` variations:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/14b15868-62dc-4081-808a-1065cc8895ad)

PS: This is obviously not critical, it's just something dumb that I keep getting momentarily confused by: "Why isn't `e` doing anything!?"

**Comment by kjk** [comment]
Yes, we need a notion of commands that can take arguments. The syntax would be more like:
```
[
    Cmd = CmdEditAnnotations true
    Key = e
]
```
or:
```
[
    Cmd = CmdEditAnnotations open=true
    Key = e
]
```
The reason for this syntax is technical limitation of our settings serialization code.

**Comment by kjk** [comment]
I've removed `e` and `Ctrl + E` shortcuts and instead use `Ctrl + click` and `Ctrl + double click`.

I believe you can get desired behavior with:
```
[
    Cmd = CmdEditAnnotations
    Key = e
]
```

as `CmdEditAnnotations` opens the editor.

**Comment by GitHubRulesOK** [comment]
@kjk loking forwards to see what has happened there 

so  CTRL+Click-drag has always been select area for copy, zoom, print & annotate a selected area

Double click is many actions so I guess  CTRL+ click + click will NOT cross over when drag ??

**Comment by kjk** [comment]
In my testing all existing functionality has been preserved but maybe I missed things.
