### ISSUE TITLE
Diffrent print speed

### ISSUE THREAD

**Issue by sumsu** [sumatrapdfreader/sumatrapdf#37]
Hi,
I've found out that sumatra 3.0 sends to printer nearly 2 times more data than sumatra 1.8 when printing the same document on the same printer, and what's more important, the old sumatra prints faster.
I've HP LaserJet 5100 printer which can shoot 15ppm. It's connected via 100Mbps ethernet so it is not a matter of connection. 
When printing with Sumatra 3.0, printer stops after every page and wait for data. When printing with oldest software, there is nearly constant stream of printed pages, one-by-one.
It happens whenever I've to print 10 pages or 200 pages.

Best Regards,
sumsu

**Comment by kjk** [comment]
It's unlikely we'll be able to improve on that.
