### ISSUE TITLE
Cant open DJVU book

### ISSUE THREAD

**Issue by AtuinWOW** [sumatrapdfreader/sumatrapdf#370]
Hi!
First of all, thank You for Your great program!
Unfortunately, i cant open 1 djvu book --> http://ge.tt/5EL6WnS2/v/0?c
Its strange, because i can open it with WinDjView reader.
Thx You!

**Comment by GitHubRulesOK** [comment]
@kjk 
closing as sample file is no longer accessable to me, thus I cant verify there is still an open issue.
