### ISSUE TITLE
Annotation Editor -- better context

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3702]
This is one for the wishlist.

Instead of this:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/3cadbc99-88a2-46a0-8d3a-a14db3bbb6e6)

Have something like this:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/0ba2102d-27d1-48b7-ba17-4d5a8e9ba712)

**Comment by GitHubRulesOK** [comment]
That's novel the editor window is big enough HOWEVER many people will highlight a whole block of text so pdf is usually highlights may not flow from line to line "visually" even if under the surface they are flowing a hundred single characters in lines.

**Comment by kjk** [comment]
Probably too difficult to implement.

Ultimately the UI for editing should not be edit window but a compact UI shown near the annotation. Which would obviate the need for this.

The current UI was just easy to implement.
