### ISSUE TITLE
Crashes if "Delete Annotation" when no Annotation Selected

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3703]
453086de08320c38b3178c7930cc910e6013e2a7 crashes:

- Open PDF
- Add an annotation
- Open annotation editor
- Press "Delete Annotation" to delete the annotation 
- Notice that no annotation is selected in the list box (this is good)
- Press "Delete Annotation" to watch application crash

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/cf94bd91e34d41fd0a79e7f1fc3c9de6d6a3fba4
