### ISSUE TITLE
Moving annotations is broken?

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3706]
In commit 453086de08320c38b3178c7930cc910e6013e2a7 I don't understand how moving an annotation is supposed to work. I remember reading somewhere (but can't find where) that it requires `ctrl-click`, but I can't figure it out.

Maybe it's a bug, or maybe I am dumb.

- Open a PDF
- Add a "Stamp Annotation under cursor"
- Do *something* to select the annotation, but I don't know what
- I can then, perhaps, move it around with *just* the mouse clicked (no `ctrl`), but it's unreliable, and I'm only allowed to move it once

**Comment by kjk** [comment]
* select moveable annotation (e.g. Ctrl + click, `Select annotation` under cursor via command palette, right-click and `Open Annotations`)
* drag & drop to move selected annotation

**Comment by GitHubRulesOK** [comment]
@kerryland in theory every annotation is "floating" Even text highlights should not be "fixed" however convention says
 strike out
 squiggly
 underline
 and text highlight
 should be tied to the text position that was used as their anchor.

So edge cases are common when working with different styles, This one was a Courier "Typewriter" comment with colour highlight by background, and font changed to sans serif in PDFxedit.

Move it in SumatraPDF and it changes appearance.

[sumpdf-prerelease-latest.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12706513/sumpdf-prerelease-latest.pdf)

**Comment by kerryland** [comment]
@kjk I'm not sure why this was closed. The bug is that it doesn't seem to work when the stamp is placed over text. It works fine on a plain background.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/5b54f1ff-a898-482c-b94c-00d25e1d4dd5)

**Comment by kjk** [comment]
I see, text selection takes precedence over dragging the annotation.
