### ISSUE TITLE
In the annotations editing window, program crash when modifying the contents

### ISSUE THREAD

**Issue by s92671** [sumatrapdfreader/sumatrapdf#3711]
In the annotations editing window, if no annotation is selected, modifying the contents will cause the program to crash.
![24](https://github.com/sumatrapdfreader/sumatrapdf/assets/40166/2dde08ff-d562-471c-8e7c-cb1ad5214247)
![23](https://github.com/sumatrapdfreader/sumatrapdf/assets/40166/6430e6a7-ef2e-46f4-9c75-2028084a022a)

**Comment by kjk** [comment]
The issue here is more broad in that after we delete an annotation and un-select the annotation, we don't update the annotation edit window state so we have widgets that try to operate on the delete annotation.
