### ISSUE TITLE
[proposal] add working with xpdf-tools-win for extracting to png

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#3712]
to add extract pdf to png with xpdf-tools-win
it can add external library e.g. to '.\xpdf-tools-win\bin64\pdftopng.exe'

**Comment by GitHubRulesOK** [comment]
you can send current file or page via externalviewers to any app such as poppler `pdftopbm -png` or inferior jpg not just xpdf
but there are so many options out there the most compatible would bee `mutool convert` or mutool draw etc.

**Comment by Aliaksandr3by** [comment]
I can use the terminal with the command line. 
but I think it will be cool if I might use a single app for all reasons.

**Comment by GitHubRulesOK** [comment]
it would be best to pass the current file name to a cmd file first for say make choices about output e.g. naming and reopen i n SumatraPDF, but just to show a command can be run direct here is a mutool call (can be pdftopng if you craft it well, but "calling direct" there are as you see oddities)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/ba815600-ad57-4cbd-b91e-63f6c43bc2c1)
```
ExternalViewers [
CommandLine = C:\Users\lez\Downloads\Apps\PDF\mupdf\1.20.0\mutool.exe convert -F png -o """%d\Page-.png""" "%1" %p
Name = Convert Page &To PNG
Filter = *.pdf
]
```
