### ISSUE TITLE
Moving Anots seems very fragile

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#3713]
a couple of crashes that seem to be easily triggered when trying out moving from other sources?
[sumatrapdfcrash1.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/12706527/sumatrapdfcrash1.zip)
[sumatrapdfcrash2.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/12706528/sumatrapdfcrash2.zip)

**Comment by kjk** [comment]
Thanks, should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/688c2a197a98173c1f38ecf13dbb5a50445d3725
