### ISSUE TITLE
Submitting crash report 

### ISSUE THREAD

**Issue by useribs** [sumatrapdfreader/sumatrapdf#3716]
https://pastebin.com/CzZLBE8z

The only file that was open during the crash is attached to this ticket
[ITC_Officina_Serif.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/12706692/ITC_Officina_Serif.pdf)

I think i just switched from the open PDF to the "Home" tab

**Comment by useribs** [comment]
I think i've nailed it: with the only this file open press Ctrl-W to close sumatra and it crashes consistently

**Comment by kjk** [comment]
Thanks, should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/688c2a197a98173c1f38ecf13dbb5a50445d3725 and available in next pre-release build
