### ISSUE TITLE
Enhancement: Start Page as tab

### ISSUE THREAD

**Issue by grimes2** [sumatrapdfreader/sumatrapdf#372]
For faster access of documents, the Start Page should be a tab. Example is the Speed Dial in the browser Opera.

**Comment by GitHubRulesOK** [comment]
The favorites sidebar rather than favourites page is IMHO potentially easier to use as a "speed dial"
not limited to 10 quick to call / edit and delete anyway as an enhanced option to add to
# 406 which also requests that it be constantly accessible I am calling this as duplicate and closing
