### ISSUE TITLE
Crash testing synctex

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#3722]
Probably shot myself in the foot

I said 32bit portable with synctex previously did not crash for me , well I need to find some relish before I eat my hat.

This is a demo set that was behaving perfectly well to show forward and reverse search functions
until I added a Forward Search.CMD trying all the 3 test files at once !!!

Note I removed the debug files to keep the zip size down but was pleased to see I had not needed to prompt their download.

[FORWARD SEARCH.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/12709718/FORWARD.SEARCH.zip)

**Comment by kjk** [comment]
The crash:
```
0058BF03 01:0008AF03 sumatrapdf-15670-32.exe!CrashIfFunc+0x16 D:\a\sumatrapdf\sumatrapdf\src\utils\BaseUtil.h+235
005BC13C 01:000BB13C sumatrapdf-15670-32.exe!LoadDocumentFinish+0x19e D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+1783
005BC67E 01:000BB67E sumatrapdf-15670-32.exe!LoadDocument+0x113 D:\a\sumatrapdf\sumatrapdf\src\SumatraPDF.cpp+1983
005C4AD1 01:000C3AD1 sumatrapdf-15670-32.exe!LoadOnStartup+0x5e D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+267
005C635A 01:000C535A sumatrapdf-15670-32.exe!WinMain+0xa57 D:\a\sumatrapdf\sumatrapdf\src\SumatraStartup.cpp+1331
008F8805 01:003F7805 sumatrapdf-15670-32.exe!__scrt_common_main_seh+0xf8 D:\a\_work\1\s\src\vctools\crt\vcstartup\s
```

It wasn't related to synctex handling, just a condition I wanted to track.
