### ISSUE TITLE
"Save As" doesn't include changed annotations

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3725]
To reproduce:
- Open a file
- Add an annotation
- File | Save As

I would expect the file to contain the annotation.

**Comment by GitHubRulesOK** [comment]
I thought @kjk had done that one in https://github.com/sumatrapdfreader/sumatrapdf/commit/95ebef7f936b65cb0f82a6e455bf4043890ca84e

**Comment by GitHubRulesOK** [comment]
@kerryland 

my initial rough test of 32bit 3.5.15686 shows file>save as>new file stores annots and reloads with new name
so any difference will need an example

**Comment by kerryland** [comment]
Its possible I made a mistake. I will double check later

**Comment by kerryland** [comment]
Ah, my build was two hours too old.
