### ISSUE TITLE
After saving the Annotation Editor Window should not move

### ISSUE THREAD

**Issue by kerryland** [sumatrapdfreader/sumatrapdf#3726]
To appreciate the problem fully:
- Open multiple documents in independent windows (not tabs)
- Open associated annotation editors
- Rearrange all the windows nicely:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/398113/704d5e02-ba0d-4b4c-a927-14a5d7b576ec)
- Save some annotations
- See that the annotation editor has closed itself, and reopened in an entirely different location.

**Comment by kerryland** [comment]
I notice that Sumatra remembers the size and location of the main "pdf" windows when it reopens -- it would be nice if it remembered the size and location of the annotation editor windows too, which would presumably also make this bug report go away

**Comment by kjk** [comment]
There's only one position for all annotations window though, so won't work great if multiple edit annotations window at the same time.

**Comment by kjk** [comment]
ok, made it per tab, but there are tradeoffs (a window for a new tab will start at default position).

**Comment by kerryland** [comment]
@kjk you missed the followup comment that reads:

> I notice that Sumatra remembers the size and location of the main "pdf" windows when it reopens -- it would be nice if it remembered the size, location, current active annotation/first annotation in the window, and "openness" of the annotation editor windows too

ie: If you `File | Quit` and re-open, the "PDF" windows remember where they were, but the annotation windows don't. It would be nice.

**Comment by kjk** [comment]
it's too much for 3.5
