### ISSUE TITLE
Deleted annotations are still visible

### ISSUE THREAD

**Issue by actimem** [sumatrapdfreader/sumatrapdf#3727]
When I create an annotation (highlight or underline), and then I delete it, the annotation "often" remains visible.  I am using the word "often" becouse sometimes the annotation is no longer visible, but more often than not it remains visible.

Then, if I scroll to another page and then come back, the annotation is "often" no longer visible.  

If I close the file and then reopen, the annotation is not visible as expected, thus pointing out that the annotation is removed but the page is not refreshed.

I am using **v3.5.1.15601 64-bit pre-release** version.

**Comment by kjk** [comment]
**15601** is a relatively old build. Please update to the latest and re-check.

If still happens, please provide a screenshot of of the visible annotation or video recording of how you trigger it.

**Comment by GitHubRulesOK** [comment]
common problem with data fields the change of apperance data fill or hidden  (not removed) when deleted and require a "flush"

**Comment by actimem** [comment]
I cannot reproduce the issue in 15697, so closing this ticket.
