### ISSUE TITLE
Founded where error

### ISSUE THREAD

**Issue by Avtroman** [sumatrapdfreader/sumatrapdf#3728]
Error in code while set compiler option /Ob1
Worked - default, /Ob0, /Ob2

If set /Ob1 - program crash ACCESS_VIO;ATION, in code:
mov [0], Rx
![Снимок экрана (18)](https://github.com/sumatrapdfreader/sumatrapdf/assets/42459158/d579ea01-8232-4cc5-82ce-3f49387371dc)

**Comment by kjk** [comment]
I'm not going to investigate non-standard builds
