### ISSUE TITLE
[bug] don't work RememberStatePerDocument

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#3729]
does not remember the state of the book (number of page)

the SessionData [] always is clean

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/f5327d89-80d5-4a00-b53c-f91f683c05ec)

RememberOpenedFiles = false
RememberStatePerDocument = true
RestoreSession = true

[SumatraPDF-settings.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/12713892/SumatraPDF-settings.txt)

**Comment by kjk** [comment]
`RememberOpenedFiles = false` should be true

**Comment by Aliaksandr3by** [comment]
the information that save in FileStates segment

**Comment by kjk** [comment]
no, one depends on the other

**Comment by GitHubRulesOK** [comment]
@Aliaksandr3by 
to persist a favourite page there is favorites
 but then not easy to reassign as a reading order which is why remember opened files was added
 then secondly remember progress in remembered files.

**Comment by Aliaksandr3by** [comment]
but If I delete the TabStatesfrom from the SessionData manually and I will open any book (that I did open) the session of book (page number .. other) is restored.
don't it exist the feature to disable reading SessionData ?
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/df20ae0b-e922-4548-918c-ca037a1784b6)

**Comment by GitHubRulesOK** [comment]
@kjk there does appear to be some current bug when testing states

while test a larger set of frequently read attempting to switch OFF remember per document induces a crash
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e16d774e-464a-4256-a12c-fa5c625ff048)
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/12714451/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
@GitHubRulesOK Could you open a separate issue for this and provide repro steps?

I tried several times to repro by toggling that setting but couldn't trigger the crash.

**Comment by GitHubRulesOK** [comment]
> @GitHubRulesOK Could you open a separate issue for this and provide repro steps?
> 
> I tried several times to repro by toggling that setting but couldn't trigger the crash.

ok will try to get replication

**Comment by kjk** [comment]
@GitHubRulesOK Actually, I think I fixed it with https://github.com/sumatrapdfreader/sumatrapdf/commit/85e5d24e1d0527ca5c3c2073a0792101c1f852c1

**Comment by Aliaksandr3by** [comment]
can you add feature for "close all opened files  after close main window" ?

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/a2d0a7cb-04e5-4640-a6ee-468f0547d280)

**Comment by gaoqiangks** [comment]
I don't understand why "remember state of per doc" should depend on "remember opened files".  For my own case, the former is one of the most frequently used, while the latter is seldom needed.  Can you add an option to remove this dependency? @kjk

**Comment by kjk** [comment]
Arguably there should be only one setting, like "Remeber State".

I don't remember why we have `remember state of per doc` (it should always be true).

But I'm not sure what you're complaining about exactly.

Obviously I cannot remember the state of the file without also remembering the file. So at least at a level of the implementation, 'remember state of the file' requires remembering the file names.

Disabling `Remember Opened Files` is for people who don't want that history to be preserved so for them it would be surprising if 'remember state' also turned 'rember opened files`

So maybe you're complaining about UI i.e. showing thumbnails on home page. You can turn that off with `Hide frequently read` link at the bottom of the home page.

Or maybe you don't like file history showing in `File` menu or command palette. Which is fine as a personal quirk but I don't see why that should be a problem for most people.

**Comment by gaoqiangks** [comment]
I think "remember state of per doc" and "remember opened files" are totally different things. For "remember state of per doc", I mean remember the view of this doc I last opened it. For example, I opened a doc named "a.pdf" yesterday, and lookded up something on Page 100, and then I closed sumatrapdf hours later. Today, I continue my work. Again, I open "a.pdf", and I want sumatrapdf to remember "it's on Page 100 yesterday".  Why I don't want to restore all opened files? Because there might be too many tabs, which makes it hard to locate a certain tab. Maybe I'm I am a minority. But it's a pleasure if there's such an option.




> Arguably there should be only one setting, like "Remeber State".
> 
> I don't remember why we have `remember state of per doc` (it should always be true).
> 
> But I'm not sure what you're complaining about exactly.
> 
> Obviously I cannot remember the state of the file without also remembering the file. So at least at a level of the implementation, 'remember state of the file' requires remembering the file names.
> 
> Disabling `Remember Opened Files` is for people who don't want that history to be preserved so for them it would be surprising if 'remember state' also turned 'rember opened files`
> 
> So maybe you're complaining about UI i.e. showing thumbnails on home page. You can turn that off with `Hide frequently read` link at the bottom of the home page.
> 
> Or maybe you don't like file history showing in `File` menu or command palette. Which is fine as a personal quirk but I don't see why that should be a problem for most people.

**Comment by kjk** [comment]
You can disable restoring the session with `RestoreSession = false` advanced setting

**Comment by gaoqiangks** [comment]
Thank you! I didn't notice this option.
