### ISSUE TITLE
Black box around all new annotations

### ISSUE THREAD

**Issue by actimem** [sumatrapdfreader/sumatrapdf#3732]
Hi

I am trying the latest pre-release candidate 15697, so not sure if this is something you are playing with or a bug.

When I add an annotation, a black box surrounding the annotation appears, which is very distracting.

I do like the new functionality that Ctrl + left clicking on an annotation "selects" the annotation with the black box, so you can edit and delete it.    

However, I do not think we should auto select with the black box every time we add a new annotation.  When the user is reading a book and adds a new annotation, they expect to see their newly added annotation, not a big ugly black box.  This is distracting, counter-intuitive and breaks the reading flow.

![2023-09-26_06-20-44](https://github.com/sumatrapdfreader/sumatrapdf/assets/10696965/2455f951-a0b5-4321-8f54-554a554e5822)

**Comment by PrinceOC912** [comment]
I was just about to open an issue for that as well. I would much prefer that it shows up if the user selects the annotation with the new Ctrl + left click feature but disappears on left click or only when the annotation editor window is open.

**Comment by kerryland** [comment]
What if it was a bit more subtle, rather than "a big ugly black box"? Would that make the distraction go away?

If that's still too much, is changing it so that only displays when the annotation editor is open acceptable?

**Comment by PrinceOC912** [comment]
I think making it so that it displays only when the editor is open is good because, as far as I understand, it serves as a 'navigator' or 'selector' of annotations, making it easier to determine which one the user is about to modify. But I don't think it is necessary for it to be present all the time.

**Comment by actimem** [comment]
I agree with Prince, it is acceptable to highlight the annotation while the annotation editor is open to easily identify what you have selected.  This is even desirable as otherwise it is hard to identify the selected annotation in a page with many annotations.

I would however make it a bit more subtle; the current thick black box is simply tacky and too distracting. You want to give a hint as to the annotation selected, not overpower the document with the selection.  If you can make the color and thickness configurable, all the better.  Another option would be to add a tick box in the editor to highlight the selected annotation on demand.

Having said this, I 100% would not add a marker box when the editor is not open.  Most users simply use SumatraPDF for work and won't need to edit annotations.  They want to read and annotate, and when they add an annotation they expect to see only that annotation.  Anything else is simply a distraction to your flow.
