### ISSUE TITLE
Update MuPDF

### ISSUE THREAD

**Issue by planetkalpesh** [sumatrapdfreader/sumatrapdf#3733]
There are many improvements in the version of MuPDF starting 1.23.0.  If possible update MuPDF.

**Comment by kjk** [comment]
Yes. I'm focusing on 3.5 release and will update mupdf right after that.

**Comment by GitHubRulesOK** [comment]
@kjk I think you just updated to this level ?

**Comment by quyleanh** [comment]
The latest is [1.23.4](https://github.com/ArtifexSoftware/mupdf/releases/tag/1.23.4)
There is still problem with rendering Unicode character such as Vietnamese character in latest SumatraPDF 3.5. I hope it can be fixed soon.

**Comment by GitHubRulesOK** [comment]
@quyleanh if you review https://github.com/sumatrapdfreader/sumatrapdf/commit/f51352f1c647906a314e3f700e144ab71ef083e0#diff-f341bcef7de599f7eed3b9416bb6179307f9a599dee97715cf54b4d2531e21b3 you should see that 2 week old commit was included today, not that it is necessarily used.

**Comment by quyleanh** [comment]
@GitHubRulesOK Thank you for pointing it out.

About rendering problem, I mean the epub reader not PDF itself. However, as I check issue in this repo, there are also problem with PDF. May I ask if it can be fixed or not?

**Comment by kjk** [comment]
did update
