### ISSUE TITLE
The arrangement of tabs obscures the close button

### ISSUE THREAD

**Issue by AstroCIEL** [sumatrapdfreader/sumatrapdf#3745]
the tabs are of the same height with the close button so if i have opened more than 5 files, the close button will be blocked. also, the sixth tabs is out of range to click. note that im using 3.4.6 version and windows11.

the first pic is when i open 4 files and i works well, 
![1696584255346](https://github.com/sumatrapdfreader/sumatrapdf/assets/53786489/21041c0b-b5b9-4716-93cf-7cafbcedbf7a)

but if i open 5files, the close button is obscured
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/53786489/b0a25b32-fc37-4ff0-b97e-b0dc06897636)

**Comment by GitHubRulesOK** [comment]
old issue so closing as tabs are significantly different in imminent 3.5
