### ISSUE TITLE
The issue with ff characters

### ISSUE THREAD

**Issue by dmitrystas** [sumatrapdfreader/sumatrapdf#3746]
Sumatra PDF Reader does not work correctly with 'ff' characters (some fonts).

Steps to reproduce:

1. Download and open https://www.dropbox.com/scl/fi/3usz415jfo7738mzssqw6/testffcharacters.pdf?rlkey=dtka3rboo7dknhfrh4fe20lls&dl=0
2. Double click to select on 'anyLongWordWith2ffCharacters'. Note that only 'anyLongWordWith2' or 'Characters' (depends on the place you click on) will be selected, but 'ff' - not
3. Select all characters in the 'normal' way (hold down the left mouse button, and then drag the pointer over the text that you want to select)
4. Copy selected text and paste it in any text editor (Notepad+ for example)
6. Note that it will be 'anyLongWordWith2?Characters' (ff -> ?)

P.S. You can create pdf yourself, for example using google docs:

1. Create new doc or use this one https://docs.google.com/document/d/1-YzCdp3MjVUFWexfjghmpPXw3rSFBNh1UBfgsrABL_8/edit
2. Select 'Chivo' font
3. Type 'anyLongWordWith2ffCharacters' or any other word with 'ff'
4. File -> Download -> PDF 

P.P.S. I've also seen this issue with "ff" characters in some other pdf libraries, for example https://github.com/pkp/pkp-lib/issues/4749 , maybe it will be helpful

**Comment by GitHubRulesOK** [comment]
That will be the way a PDF uses fonts with ligatures those are not counted as normal letters so Acrobat text exporter does not think they are worth announcing.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d56355b5-fbc7-41b8-8774-9ced755d65e8)

BT is begin some text and ET is End of text so a PDF does not store as conventional text but many ways but even letters are just binary numbers. so the text string is 0184 0108 017B 0184 etc. and thus you see t e s t (184=t = same letter at start and end of a human word) however FF clearly is not handle the same it is an auxiliary definition like a symbol may be  it has its own coding as just one letter <01BF>.
```
BT
/F4 14.666667 Tf
1 0 0 -1 0 0 Tm
0 -13.7866669 Td <0184> Tj
5.4228363 0 Td <0108> Tj
8.3687439 0 Td <017B> Tj
7.9437103 0 Td <0184> Tj
5.4228363 0 Td <0184> Tj
5.4228363 0 Td <0108> Tj
8.3687439 0 Td <0184> Tj
5.4228363 0 Td <017B> Tj
/Span<</ActualText (ff) >> BDC
7.9437103 0 Td <01BF> Tj
EMC
10.2154388 0 Td <0184> Tj
5.4228363 0 Td <0108> Tj
8.3687439 0 Td <017B> Tj
7.9437103 0 Td <0184> Tj
5.4228363 0 Td <0184> Tj
5.4228363 0 Td <0108> Tj
8.3687439 0 Td <0184> Tj
5.4228363 0 Td <017B> Tj
/Span<</ActualText (ff) >> BDC
7.9437103 0 Td <01BF> Tj
EMC
10.2154388 0 Td <0184> Tj
5.4228363 0 Td <0108> Tj
8.3687439 0 Td <017B> Tj
7.9437103 0 Td <0184> Tj
ET
```

**Comment by GitHubRulesOK** [comment]
Closing as any pdf with imbedded ligatures is correctly read as plain text with ligatures
but that character does not exist in plain text.

**Simplest means to extract that text is use a ligature reader & writer like MS Edge** so it can use its wide repertoire of fonts to reverse the contents back to F F

**Comment by dmitrystas** [comment]
> That will be the way a PDF uses fonts with ligatures those are not counted as normal letters so Acrobat text exporter does not think they are worth announcing.

Tbh I don't know what Acrobat text exporter is, but Adobe Acrobat Reader shows this example pdf correctly

**Comment by GitHubRulesOK** [comment]
If you ask Acrobat to save what it sees as "Accessible" text you will see the raw page characters that are "plain"text
which is what MuPDF uses for copy and paste.

Here is that text exported from Adobe Acrobat Reader, which can be different to what IT may use for editing or searching.
In order for ligatures to be seen as seperated characters they need editing by some extractor and Mupdf does not do such character splitting.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4ef36495-03bc-4346-9b1e-5c54ea32ae57)

**Comment by dmitrystas** [comment]
Unfortunately I can say almost nothing from technical point of view, but from user side Adobe Acrobat Reader looks pretty good -  I can copy and paste ff characters without any problem (for example I inserted the following text 'anyLongWordWith2ffCharacters' from it)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/17676541/11686fe5-f861-411e-bfd0-33931b783c2c)

**Comment by GitHubRulesOK** [comment]
Acrobat file handling has many heuristics for text handling (like ignore accents etc.) as its a programmable PDF editor (big and slow) but much is restricted to viewing. There are many ways it can change the PDF contents to suit its functions.
