### ISSUE TITLE
'sumatra pdf crashed'

### ISSUE THREAD

**Issue by lb2601** [sumatrapdfreader/sumatrapdf#3751]
[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/12839996/sumatrapdfcrash.txt)

the app opens fine but whenever i try to open a pdf it crashes

**Comment by kjk** [comment]
Does it crash on every PDF? 

If only with specific file, please include the file that caused the crash as described in https://www.sumatrapdfreader.org/docs/Submit-crash-report

It might also be already fixed in pre-release version https://www.sumatrapdfreader.org/prerelease

```
Ver: 3.4.6
61D42F03 01:000F1F03 libmupdf.dll!inflateEnd+0x5968
61D41F7B 01:000F0F7B libmupdf.dll!inflateEnd+0x49e0
61D3CE3A 01:000EBE3A libmupdf.dll!inflate+0xd93
61CB8EA5 01:00067EA5 libmupdf.dll!fz_open_faxd+0x1cd
61C714B4 01:000204B4 libmupdf.dll!fz_blendmode_name+0x264a
61CE00B7 01:0008F0B7 libmupdf.dll!pdf_lex+0x15
61D236AB 01:000D26AB libmupdf.dll!xps_resolve_url+0x26178
61D23D97 01:000D2D97 libmupdf.dll!xps_resolve_url+0x26864
61CECB5C 01:0009BB5C libmupdf.dll!pdf_repair_obj_stms+0x788
61CECC43 01:0009BC43 libmupdf.dll!pdf_repair_obj_stms+0x86f
61CECC9C 01:0009BC9C libmupdf.dll!pdf_run_page_contents+0x23
61C6D67F 01:0001C67F libmupdf.dll!fz_run_page_contents+0x53
61CA5A7D 01:00054A7D libmupdf.dll!fz_new_stext_page_from_page+0x8d
012AFFF2 01:0007EFF2 sumatrapdf.exe
01280CA8 01:0004FCA8 sumatrapdf.exe
012665F5 01:000355F5 sumatrapdf.exe
```

**Comment by lb2601** [comment]
It crashes on every pdf yes
and i have a 32 bit windows so i cannot download the prerelease

**Comment by GitHubRulesOK** [comment]
@lb2601  I download 32 bit every daily here is yesterdays, HOWEVER
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/43938329-d863-4f94-a485-4f71383d811c)
It is not shown on screen and for many like me it does not autodownload so open the https://www.sumatrapdfreader.org/prerelease page in another window
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/acb04d29-bc5d-4294-911d-61710eadc5aa)
 and rightclick the 64bit file you want as 32bit and COPY LINK
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/7aadacaf-0b1d-433c-b156-ccd7a590f2eb)
paste that in the addressbar and change 64 to 32
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/ef0b33c1-7a0d-45c8-9016-9f9cd695a804)
it should confirm a download is available
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e9c4585a-1f89-441f-8776-333ab6cff4dc)

**Comment by lb2601** [comment]
sorry for not replyng sooner but seriously THANK YOU VERY MUCH it worked
