### ISSUE TITLE
Annotation Takes too much time

### ISSUE THREAD

**Issue by imadkat** [sumatrapdfreader/sumatrapdf#3762]
Whenever we make an annotation and then we save the annotation then it takes too much time to save the annotation.

**Comment by GitHubRulesOK** [comment]
to save a file takes longer than opening as the whole file needs seekand write then append the related replacements and additions this applies to most annotations or application, what has a significant difference is how well written the source file is as a complex compressed file can take longer than a well decompressed one.

**Comment by kjk** [comment]
Please provide concrete numbers:
* how big is the file?
* how much time does it take to save annotations?
* is the file on a networked drive or remote storage like Dropbox or One Drive?

Does it happen with every file or just some files?

**Comment by imadkat** [comment]
The average file size is 400-700 pages
it takes about 2 minutes to save the annotation till that time you've to wait
the file is on a local system (hard drive).

**Comment by GitHubRulesOK** [comment]
4096 pages comment page 1 say about 15 seconds to save in Acrobat after select folder/name
same file same task same folder similar naming 3 seconds in SumatraPDF and it has saved and switched to reopen new name (Acrobat does not seem to do that)

**Comment by kjk** [comment]
That's not typical I just tried with 2.5 MB, 260 pages and it took 35 milliseconds.

There must be something unusual about your file but nothing I can do without a sample file.
