### ISSUE TITLE
Cannot open 'edit annotations' window through Ctrl+K -> Edit Annotations

### ISSUE THREAD

**Issue by mqxt** [sumatrapdfreader/sumatrapdf#3771]
Cannot open 'edit annotations' window through Ctrl+K -> Edit Annotations

**Comment by GitHubRulesOK** [comment]
ensure you are reporting against current pre-release 3.5.15722
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/b2ce7e46-c5ee-480f-aef9-76fd69001be5)
