### ISSUE TITLE
Epub content not viewable/missing in recent versions

### ISSUE THREAD

**Issue by RickDasterdly** [sumatrapdfreader/sumatrapdf#3778]
I have a number of epub files which worked in older versions of Sumatrapdf, but do not in the current version. All of them work in Calibre and some other reader I tried at random. From reading here I guess this is since the change to mupdf. The files in question are completely unusable in Sumatra now.

They all show similar behaviour: Very short page count, large quantities of content is not displayed at all when scrolling through the pages or jumping from the index/bookmarks, pages that do show seem in poor order. Also font/size issues. Here is one example showing first a file opened in Sumatra 3.0 (in a VM), then the same file opened in Sumatra 3.4.6. I have tried various view settings and options; nothing helps.

**File opened in v3.0, displayed as it should be:**

![Su02](https://github.com/sumatrapdfreader/sumatrapdf/assets/148659504/886384c8-59ce-45a5-a14e-2a2ead8cfe99)

**File opened in v3.4.6 - missing lots of content after a few correct-ish pages. Only a fraction of the pages seem to be viewable:**

![Su01](https://github.com/sumatrapdfreader/sumatrapdf/assets/148659504/bd1172c5-8450-430d-a7ea-aa213eda6ce4)

**Comment by GitHubRulesOK** [comment]
It may be you have a faulty copy as this one looks OKish

251 pages but these would be much better viewed in MS Edge where its only spread over 147 pages or so.?
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6c97945d-a0b0-4eda-9418-ccc0c359b249)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f16e287b-9e94-456d-8889-5583b42074e9)

**Comment by RickDasterdly** [comment]
That is possible. I tried the file in Edge and it still displayed incorrectly, so clearly your file is different.

I've just found and tried three different versions of my file though (all around 4.9MB but slightly different) and all of them fail in Sumatra and Edge, but the other readers I've tried all display them properly (Calibre, AlfaReader, Icecream, and of course SumatraPDF up to version 3.3.3).

I have other files that behave the same. The one in the other tab in my pictures, "The Arabian Cookbook - Traditional Arab Cuisine" does exactly the same... if I click on "Main Courses" from the bookmarks, then scroll down the pages, it jumps immediately to the next bookmark, then a couple of pages and jumps again, missing huge numbers of pages out. Again, that file works perfectly in the other readers.

Would it help to send you a copy of my file?

**Comment by GitHubRulesOK** [comment]
perhaps ensure your using latest pre-releae version of SumatraPDF so mine was yesterdays but there should be a new one now, my file is also about 4.90 MB so cant see any difference there

 HOWEVER the other one has a very odd wide bilingual format and not likely to work well with MuPDF engine.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2054f1ef-634d-4f95-a01e-e43b32a2bcb5)

**Comment by RickDasterdly** [comment]
Ahh... yes, the latest pre-release does display the files properly. I had only tried up to the release version 3.4.6.

You are right, that last file is a little problematic in itself. It works better in AlfaReader or Icecream if I stretch the window out quite wide (see below). Anyway, my problem is solved with the pre-relase. Thank you for helping me.

![Su03](https://github.com/sumatrapdfreader/sumatrapdf/assets/148659504/7b840f5f-1733-413b-aaf8-13aeb6a9a5f7)

**Comment by kjk** [comment]
Closing as apparently mostly fixed. Either way, without a test file there's nothing I can do.
