### ISSUE TITLE
Incorrect bookmark font name

### ISSUE THREAD

**Issue by Shan-Zhou** [sumatrapdfreader/sumatrapdf#3779]
The current implementation use
https://github.com/sumatrapdfreader/sumatrapdf/blob/f26f857dcd16592657c133bdf70cde17ec734f24/src/utils/WinUtil.cpp#L1396
to compute the font name, but before that
https://github.com/sumatrapdfreader/sumatrapdf/blob/f26f857dcd16592657c133bdf70cde17ec734f24/src/utils/WinUtil.cpp#L1390
would set the font name to the system default font, so using `StrCatBuffW` will end up with an incorrect font name like `Segoe UIMicrosoft Sans Serif`. It should be replaced with `StringCchCopyW(dest, cchDestBufSize, fontNameW);` (and add `#include<strsafe.h>` somewhere. I am not sure where it should be added so please check whether the current location is good).

Here is my fix:
https://github.com/Shan-Zhou/sumatrapdf/tree/bookmark-font-fix

**Comment by kjk** [comment]
Thanks, fixed in https://github.com/sumatrapdfreader/sumatrapdf/commits/next
