### ISSUE TITLE
Reader is unable to show cyrillic text in pdf file

### ISSUE THREAD

**Issue by turbanoff** [sumatrapdfreader/sumatrapdf#378]
Version 3.1.1
See attached PDF - [42.195men-2008.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/51282/42.195men-2008.pdf)
Sumatra show file like this:
![sumatra_screen](https://cloud.githubusercontent.com/assets/741251/11572875/699b31fc-9a14-11e5-9dbc-b8d60ec111f0.png)

Properly should be shown like this:
![firefox_screen](https://cloud.githubusercontent.com/assets/741251/11572893/8637a534-9a14-11e5-85ae-337b610e4055.png)

**Comment by GitHubRulesOK** [comment]
@kjk may be related to #1437 since very old 2008 lightweight 6mb MuPDF Viewer was able to render those characters but current bloated MuPDF can't !
![image](https://user-images.githubusercontent.com/12754913/73355736-b190c480-4290-11ea-8ce2-33600c887542.png)

**Comment by kjk** [comment]
Looks like a corrupt files. Has font that FreeType can't handle / render.

No plans to work on that. As with other cases, if other viewers can handle it maybe mupdf could add more recovery code but it's up to them.

**Comment by GitHubRulesOK** [comment]
Just a confirmation that this file had bad font definition as detected by Acrobat Reader
![image](https://user-images.githubusercontent.com/12754913/82328156-68978400-99d7-11ea-8003-adab8b7ed7f4.png)

very simple to correct by rebuilding pdf using globally available TimesNewRoman
[378 42.195men-2008-fixed.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4650500/378.42.195men-2008-fixed.pdf)
