### ISSUE TITLE
mpdf (php library) generated pdf with bookmarks are not seen in Sumatra but are in Adobe Reader

### ISSUE THREAD

**Issue by AntonioCS** [sumatrapdfreader/sumatrapdf#3780]
Hey,

I've been testing some pdf generating libs in PHP and found [mpdf](https://mpdf.github.io/).
This library easily generates pdfs from html and can also generate some bookmarks.
I have attached a file which was generated using mpdf and unfortunately on Sumatra I don't see any bookmarks.
[output.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13069920/output.pdf)

Here is is on Sumatra:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/1086401/d871c51d-e6f6-41ae-a88d-102f8f25287e)
And here it is on Adobe Acrobat:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/1086401/3344b876-5de0-43e2-81a3-c3fc0a9700ce)

Is there special care that needs to be taken when generating bookmarks for Sumatra?
Here is some more information on the features I'm using from mpdf to generate the bookmarks: https://mpdf.github.io/reference/html-control-tags/bookmark.html

**Comment by kjk** [comment]
I can see bookmarks in this file. Make sure to show bookmarks tree view (F12, View / Show Bookmarks, or `Ctrl-K` and `Toggle bookmarks` command).

**Comment by AntonioCS** [comment]
Ok... this is very strange then. 
In other pdfs I never have to press anything to view the bookmarks. Is this because it only has one page?
But you are right, I can see it when I press F12. Thanks

**Comment by AntonioCS** [comment]
@GitHubRulesOK That is what I have in my options. As mentioned, I see other PDFs bookmarks automatically, that was I was surpriesed I had to press F12 on my little test PDF to get it showing.
Possibly the issue here is that this test PDF only has one page and that might be affecting something.

**Comment by GitHubRulesOK** [comment]
@AntonioCS 
I used latest pre-release , since only there can  there be any "fix" it is possible either a bad settings file or an older version may have issues with the way the bookmarks are flagged?

**Comment by AntonioCS** [comment]
Possibly but again, never had any issue with other PDFs.
Thanks for the suggestion

**Comment by kjk** [comment]
This setting is also remember for each file. You must have hidden bookmarks for that file in the past.

**Comment by kjk** [comment]
we remember the full path but we also match by file name for cases of moved files
