### ISSUE TITLE
Inconsistent menu sizing between light and dark mode

### ISSUE THREAD

**Issue by expikr** [sumatrapdfreader/sumatrapdf#3787]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/77922942/84bfb38d-be80-4355-ac9f-048e35399f4e)

**Comment by BennyBeat** [comment]
I agree with that issue in v3.5 64Bit.
I recorded a video about this error and, no matter the language you configured Sumatra; trouble persist...

https://github.com/sumatrapdfreader/sumatrapdf/assets/1072581/2d584d09-2ce9-4dbe-8d2f-c0829490e6dc

**Comment by BennyBeat** [comment]
> I agree with that issue in v3.5 64Bit. I recorded a video about this error and, no matter the language you configured Sumatra; trouble persist...
> SumatraPDF_yR2GIn692W.mp4

Same error on v3.6.15785 x64:

https://github.com/sumatrapdfreader/sumatrapdf/assets/1072581/5911ac75-9c64-4c3a-833a-f844419b29a3


Fortunately just a cosmetic issue...

**Comment by kjk** [comment]
I increased custom draw menu padding from x=2, y=2 to x=8, y=4. Please check in about a day when it lands in pre-release https://www.sumatrapdfreader.org/prerelease

Not sure if those match exactly. Is there a system setting for that?

**Comment by BennyBeat** [comment]
> I increased custom draw menu padding from x=2, y=2 to x=8, y=4. Please check in about a day when it lands in pre-release https://www.sumatrapdfreader.org/prerelease
> 
> Not sure if those match exactly. Is there a system setting for that?

Hi,
The size now is more consistent than 2 days ago:

https://github.com/sumatrapdfreader/sumatrapdf/assets/1072581/c6820ee4-0032-4061-aa57-a75e0eea3101




Anyway, I found the Light theme is not lighter than the original ones, and I think the menus are smaller, too...
I do not know if there is a system setting for that but, if you can tell us where you made the changes ("SumatraPDF-settings.txt" file or something like that), I can try to bring you the optimal values; I have Win10 and W11 to test if needed...
THANK YOU! ;)

**Comment by kjk** [comment]
the light theme is the same as default in previous versions.

Those settings are in the source code, not in configurable in settings.
