### ISSUE TITLE
3.5.0 and 3.6 pre-relase couldn't show the tab title

### ISSUE THREAD

**Issue by Leoijeon** [sumatrapdfreader/sumatrapdf#3789]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/30471002/718bd0bc-44ac-4b5b-a780-f3582841187e)
using windows 11 
this didn't happen in 3.4.6 version

**Comment by GitHubRulesOK** [comment]
@kjk for what its worth there is no visible problem with 32bit win 10 !

**Comment by kjk** [comment]
I can't reproduce this.

Did you customize colors in settings? Does it still happen if you revert to defaults (i.e. delete colors)?

If it's related to color customization please share the settings file.

**Comment by th3v4n** [comment]
I did in fact customize my colours, so maybe that's it! Can test and get back to you in a bit :-)

**Comment by kjk** [comment]
most likely a dup of #3799

**Comment by GitHubRulesOK** [comment]
For others landing here 
most likely was closed in 3.5.2 update :-)
