### ISSUE TITLE
Change the tab shape to have a square edge.

### ISSUE THREAD

**Issue by noersetiawan** [sumatrapdfreader/sumatrapdf#379]
Can you change the tab shape to square? Since rounded tab looks very out-of-place compared to everything else. Even the sumatrapdf website has square navigation tab.

**Comment by okungnyo** [comment]
+1, would be nice.

**Comment by GitHubRulesOK** [comment]
@kjk I think this is current behaviour

**Comment by kjk** [comment]
Yes, they are square now in https://www.sumatrapdfreader.org/dailybuilds.html
