### ISSUE TITLE
background color of files couldn't change by "Backgroudcolor" tag in setting file

### ISSUE THREAD

**Issue by Leoijeon** [sumatrapdfreader/sumatrapdf#3790]
When I change the theme to dark or darker, the background color of files couldn't change by "Backgroudcolor" tag in setting file in 3.5 version.
Besides, in the light mode, the background color of the bookmark box also cannot change by "MainWindowBackground" tag

**Comment by kjk** [comment]
Yes, for backwards compatibility, `MainWindowBackground` etc. only works for the original, light theme.

Maybe I'll add a way to define your own themes.

**Comment by kjk** [comment]
Ok, I've made `MainWindowBackground` setting as a mini-theme. It'll now be also used to paint controls background, which is effectively theming.

It's a change in behavior, we'll see what other people will think about it.

You'll have to use pre-release for that, though https://www.sumatrapdfreader.org/prerelease

**Comment by FLWang-FUDAN** [comment]
I think maybe a good idea if remove `if (currentThemeIndex == 0)` in file `Theme.cpp`, since users can customize all colors both in LightTheme and DarkTheme, and the overall colors of sumatrapdf  in user interface look very consistent and beautiful.

**Comment by george9816** [comment]
> Yes, for backwards compatibility, `MainWindowBackground` etc. only works for the original, light theme.
> 
> Maybe I'll add a way to define your own themes.

Please add a way to define custom themes / colors. I specifically wish a black theme. I've tried to modify Theme.cpp myself, but I have no idea how to compile the program..

**Comment by FLongWang** [comment]
Refer to [https://github.com/FLongWang/sumatraPDF-modified.git](https://github.com/FLongWang/sumatraPDF-modified.git).  I have just uploaded the exe file.

**Comment by george9816** [comment]
> Refer to https://github.com/FLongWang/sumatraPDF-modified.git. I have just uploaded the exe file.

Thank you! :)

**Comment by GitHubRulesOK** [comment]
@george9816 
you dont need any exe other that the official one where you invert the page colours, Windows is responsible for Theming Windows so system colors controls title bat scroll bar and screen inversion, SumatraPDF can only influence the are inside the canvas and tabs
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d7dfe7fa-0e47-4721-bfd7-4c42962e5b28)

**Comment by FLongWang** [comment]
Just see this.
<img width="1080" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/55866242/1a7ed284-e874-4ae8-8ac0-5cfa26241702">

**Comment by george9816** [comment]
Thank you for your answer, @GitHubRulesOK. I understand now. Using windows high contrast mode is not reliable though.. Can't SumatraPDF have its "own" scroll bar?
