### ISSUE TITLE
Toolbar should use XOR bitmap-mask

### ISSUE THREAD

**Issue by expikr** [sumatrapdfreader/sumatrapdf#3793]
https://github.com/sumatrapdfreader/sumatrapdf/blob/ad67e643440a64b28c3521be4a136a07d640432d/src/Toolbar.cpp#L787

This should use `ImageList_Add` instead, and construct the following bitmaps:

Main bitmap -- `0x00RRGGBB` for colored pixels, `0x00000000` for transparent pixels.  
Mask bitmap -- `0x00000000` for colored pixels, `0x00FFFFFF` for transparent pixels.

This will create bitmap images that flips the underlying color.

Alternatively, if you require antialiased images that uses alpha compositing, then use `ImageList_Add` with the mask set to null and the main bitmap using the color format 0xAARRGGBB. You could also use `ImageList_AddIcon` for pre-generated icons.

This addresses the problem in #3669

---

Explanation:

There are two compositing modes that are automatically determined: alpha-blend mode and color filter mode.

When any pixel in the main bitmap has a nonzero alpha, alpha-blend mode is activated.
When all pixels in the main bitmap have zero alpha, color filter mode is activated.  

In alpha blend mode, the mask bitmap is ignored and the color is applied as you'd expect in typical alpha compositing.

In color filter mode, the mask bitmap sets the pixels to either SET BIT (if mask pixel is 0x00FFFFFF) or FLIP BIT (if mask pixel is anything other than 0x00FFFFFF) based on the bitflags set in the main bitmap.

So for example, if the mask pixel is FLIP BIT and the main pixel is 0x00FF00FF, this will result in the Red and Blue channels of the background being inverted while leaving the Green channel untouched.  
Or if the mask pixel is FLIP BIT and the main pixel is 0x00808080, this results in the most significant bit of the Red, Green, and Blue channels of background becoming flipped -- i.e. effectively swapping the 50% intensity region but keeping the relative color contours the same.

(https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-drawiconex)

**Comment by kjk** [comment]
Thanks for the explanation. I did struggle writing this code.

Would you mind writing a patch? I'll eventually get to trying that but right now I'm focusing on monitoring and fixing major 3.5 bugs and regressions .

**Comment by GitHubRulesOK** [comment]
@kjk the icons you are using have a generic common currentColor (black by default) as far as I know you are not setting a value  but if they were addressable here I set to "red" then that might resolve the theming aspect
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/1e9bc5cb-bea3-4be0-9612-5c4649508b5f)
```
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-folder" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <path d="M5 4h4l3 3h7a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-11a2 2 0 0 1 2 -2" />
</svg>
```

**Comment by kjk** [comment]
Tried creating a a mask bitmap but it didn't fix how disabled version is shown and made non-disabled look worse (thicker lines).

**Comment by kjk** [comment]
I think I've implemented 0xAARRGGBB suggestion which fixes default theme but still not great for non-default themes (but better than before due to earlier change).

**Comment by kjk** [comment]
I tried the version with 2 rgb bitmaps (with mask bitmap) but it's the same as a single rgba bitmap (without mask)

**Comment by GitHubRulesOK** [comment]
one alternative suggestion https://github.com/sumatrapdfreader/sumatrapdf/issues/3794 was use a "white/light" or other colour in the SVG as its the aliasing of vector to pixel causes the issue so a white font on blackground should "work"

**Comment by kjk** [comment]
I believe I fixed all the issues, even in dark themes.

**Comment by ArmanHayots** [comment]
Even in the latest prerelease 16189. W11 23H2, dark mode on.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/25264017/a3256cac-1fed-4fc8-bce5-8579ed7b267c)

**Comment by GitHubRulesOK** [comment]
@ArmanHayots 
That is odd so Win 10 without any 3rd party enhancements uses Windows colours
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2551e1ed-37a1-4068-a91e-89acb6c10d50)
