### ISSUE TITLE
Convert icon svg into TrueType Fonts, then have the toolbar buttons use the corresponding letter with that font

### ISSUE THREAD

**Issue by expikr** [sumatrapdfreader/sumatrapdf#3794]
See https://en.wikipedia.org/wiki/Marlett and https://devblogs.microsoft.com/oldnewthing/?p=8543

This is another way of solving the problem of toolbar icons looking like crap in darkmode.

**Comment by kjk** [comment]
Thanks for the pointer. Interesting idea and could open up a way for people to customize the toolbar icons with arbitrary SVG icons.

However, don't know how to easily convert a bunch of .svg icons into a true type font. Any pointers?

**Comment by kjk** [comment]
I believe I fixed all the issues, even in dark themes by generating a single argb bitmap for toolbar icons as outlined in #3793
