### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#3796]
https://gist.github.com/hme3/7a0279088d04cf85375dcd1319323b07
[MXZ-5C42NA2_MXZ-2C20-3C24-3C30NAHZ2_Install_BH79A240H02_06-16.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13121927/MXZ-5C42NA2_MXZ-2C20-3C24-3C30NAHZ2_Install_BH79A240H02_06-16.pdf)

**Comment by kjk** [comment]
Fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/426ff4d5948d726f4d9196175f3c5399f23421ee and will be available in next pre-release
