### ISSUE TITLE
Tab bar colors are off with 3.5

### ISSUE THREAD

**Issue by ImSpecial** [sumatrapdfreader/sumatrapdf#3797]
In version 3.4.6, freshly opened it looks like this;
https://i.imgur.com/MPpGlhc.png

 with something open a tab like so;
https://i.imgur.com/XvuSrFG.png

Now with v3.5.1, they look like this respectively.
https://i.imgur.com/6zUxyKn.png

https://i.imgur.com/HUuOKbP.png

**Comment by yoSachinkr** [comment]
Yes, the 3.5.1 look really bad.

**Comment by kjk** [comment]
Did you change `MainWindowBackground` or do the colors come from a Windows theme?

if `MainWindowBackground` then in next pre-release (https://www.sumatrapdfreader.org/prerelease) `MainWindowBackground` is also used to theme background of controls and tabs which might be more expected behavior.

**Comment by ImSpecial** [comment]
[I do, this is my settings file...
](https://bin.0xfc.de/?68ceaec666ef0a76#CeB7M3nzEFgDdhiZVK1bABHHFp8yzErrw7qDMMRZDC1d)

**Comment by kjk** [comment]
In pre-release it'll look like:
![3fU00CFLZ1](https://github.com/sumatrapdfreader/sumatrapdf/assets/7935/7b520d44-f601-4c25-aba7-f2042d9db04b)

Don't know if you consider this better or worse.

Either way we just changed tabs slightly to look better with standard colors. It's impossible to make it look best with any possible color.

Maybe the solution is to add a way to define custom themes that allow to define more colors.

**Comment by ImSpecial** [comment]
I'm not sure what the best solution would be, maybe others have an idea here. I just really like and prefer how 3.4.x and all previous releases had handled things...

> Don't know if you consider this better or worse.

Definitely not! lol

**Comment by yoSachinkr** [comment]
Basically, Windows theme color doesn't show in the empty space of the title/tab bar, instead a white colored strip appears which was not the case in the earlier versions.

**Comment by GitHubRulesOK** [comment]
@yoSachinkr Widows split themes apart so SumatraPDF relies on Windows  general colours from system
Windows 7 with 3.4.6 (should be "fairly similar" in 3.5 not tested yet but worked in pre-release)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4d7997e8-26ce-4412-bb38-08e469b9399e)

Windows 7
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/b90984bf-22f1-4899-b6d1-e4f37ec921e8)

Windows 10
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/bc897f0f-dbd0-449b-936b-8a6b74db9607)

**Comment by yoSachinkr** [comment]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/50204208/6807797f-7eb6-4186-b288-17bd60d7c687)
This extra white space is the concern here @GitHubRulesOK
