### ISSUE TITLE
Release page provides nothing executable, nor even a link to executables

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [sumatrapdfreader/sumatrapdf#3804]
Seemingly one is to get executables from [here](https://www.sumatrapdfreader.org/download-free-pdf-viewer). It would help to know that when one goes looking for executables [here](https://github.com/sumatrapdfreader/sumatrapdf/releases).

**Comment by GitHubRulesOK** [comment]
Binary Releases page is driven by remote Javascripts to  edit entries
 so should look like this with Javascript enabled
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6bf4bdc3-94a5-419d-b6d3-f29a85662301)

Github sources have a different method, so in common with other sources, releases looks like this 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/04751551-5a07-4ebb-8910-ebfdf2150de7)

@kjk 
Am unsure if there is a means on that page to say go to another site ?

**Comment by LinuxOnTheDesktop** [comment]
@GitHubRulesOK: thank you for your comment, but I wonder whether you misunderstand me. My point was that the GitHub Releases page makes downloadable only the source code, not any executables.

**Comment by GitHubRulesOK** [comment]
not misunderstood that is often the common way on github
binaries do not have to be included in assets if there are other locations for binaries
so look at MuPDF releases they do not even show the source downloads
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2da5edd2-d9e4-4a2b-9509-efa5ec41d108)
whilst others with CDN for binaries simply show the sources
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6af1ddf2-24f1-4815-b92f-354158e77fa6)

**Comment by kjk** [comment]
Yes, we don't distribute executables via GitHub releases but via the website.
Releases are just to tag the source code.

**Comment by LinuxOnTheDesktop** [comment]
@kjk 

> we don't distribute executables via GitHub releases but via the website.

That is why I wrote the following.

> Seemingly one is to get executables from [here](https://www.sumatrapdfreader.org/download-free-pdf-viewer). It would help to know that when one goes looking for executables [here](https://github.com/sumatrapdfreader/sumatrapdf/releases).

That is: why not help users out by putting a line on the releases Github page - presuming that one can do that - that links to the page where one can get the executables.

**Comment by kjk** [comment]
Good point, done
