### ISSUE TITLE
[propousal] get searching word in the textBox "find"

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#3806]
If I use the DnGrep with args like -search "%match", the textbox of sumantra will not get parameter of "%match" 

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/e13628c2-bd1c-49af-b9ee-4ec1eba34499)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/8c5d3441-190a-4798-81c4-bfd3d00532c9)

**Comment by GitHubRulesOK** [comment]
%match is not an acrobat or SumatraPDF definition it is a keyword in dnGrep
and thus In that app probably should be unquoted (it is not a SumatraPDF command line issue)
you would need a command shim to pass multiple words quoted in an MS CMD line to be converted to -search "Hello World!" 

Also note that as often stated SumatraPDF is the raw internal character search, so there are limitations like RTL languages may need serching letters in backwards order or some "w o r d s" may need OCR spaces !!

**Comment by Aliaksandr3by** [comment]
I tested on powershell

SumatraPDF.exe -page 16 -search perfect "E:\BooksOther\Cooking\Danielle Rye - Live Well Bake Cookies 75 Classic Cookie Recipes for Every Occasion 2021.pdf"

the text have searched, but in the TextBox it is not appeared

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/a1a73253-ff4e-4f24-966c-46217e828ee7)


![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/b56e2565-0b97-4461-b735-c826e9770a36)

**Comment by GitHubRulesOK** [comment]
Ahh I see thanks for the clarification
I am not sure if it should be there as that is for internal find

@Aliaksandr3by  I presume its because you may wish to search next which needs the box filled

@kjk is that easily rectified ??

**Comment by Aliaksandr3by** [comment]
> Ahh I see thanks for the clarification I am not sure if it should be there as that is for internal find
> 
> @Aliaksandr3by I presume its because you may wish to search next which needs the box filled
> 
> @kjk is that easily rectified ??

sorry, my English is bad
It is problem for me (only for me, my opinion): I want click on F3 and go to a next entry.
If I want to do next key word to finding out other result, I will do it manually. 
at this moment, I click CTRL+F3, and the highlighted text before  magical appearance  in TextBox.

**Comment by kjk** [comment]
fixed in next pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by Aliaksandr3by** [comment]
> fixed in next pre-release https://www.sumatrapdfreader.org/prerelease

hot is it work? I don't look difference
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/02641540-9a9d-4a82-8722-32180a574671)

**Comment by GitHubRulesOK** [comment]
@Aliaksandr3by 
NEXT pre-release will be about 12 hors from now
