### ISSUE TITLE
bug(dark-mode): current section in TOC while in dark mode keeps the colors from standard mode, ending as dark bg on dark font

### ISSUE THREAD

**Issue by quesada** [sumatrapdfreader/sumatrapdf#3809]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/182207/be822294-8df9-41d2-bad9-83f8fe07969f)

**Comment by GitHubRulesOK** [comment]
closing as duplicate of  many times problem and several should still be open
most noticeably Issue is covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/3429 and https://github.com/sumatrapdfreader/sumatrapdf/issues/2224
