### ISSUE TITLE
Backgroud and Text color does not change when darker and dark theme is applied.

### ISSUE THREAD

**Issue by chadify** [sumatrapdfreader/sumatrapdf#3826]
Gradient Colors works but the above dosen't. Issue is present in 3.6 as well as 3.5.

**Comment by GitHubRulesOK** [comment]
that is correct there realy is no such thing as canvas theming it always was and most likely untill a fully blown editor that MuPDF can only invert page colours so all colours are changed to opposite.

and because that's what everybody wants the dark and darker are smoke and mirrors inversion.

**Comment by kjk** [comment]
Not sure which aspect you're talking about.

1. Using colors from settings in dark theme. That's intentional - only the light (original) theme can have colors over-ridden by settings, for backwards compatibility. Other themes just use the theme colors.
2. Text and background color of rendered PDF / ebook pages doesn't match the theme. That's also intentional. Not everyone wants that. You can use `i` (invert colors) to change that and it'll be persisted in settings for the future.

**Comment by chadify** [comment]
> Not sure which aspect you're talking about.
> 
> 1. Using colors from settings in dark theme. That's intentional - only the light (original) theme can have colors over-ridden by settings, for backwards compatibility. Other themes just use the theme colors.
> 2. Text and background color of rendered PDF / ebook pages doesn't match the theme. That's also intentional. Not everyone wants that. You can use `i` (invert colors) to change that and it'll be persisted in settings for the future.

What I want is to darken the pdf page to dark background, while the darker theme is active, without inverting the colors.

**Comment by GitHubRulesOK** [comment]
@chadify 
the only way to lter paper colour is use an editor to add a black background and set all the text to white without alter any other contents.
Tthat is just not always possible unless you are Adobe Reader which is little restricted brother of PRO editor. Most readers cannot achieve what you desire, try reversing PDF in Edge with Acrobat light.

**Comment by chadify** [comment]
> @chadify the only way to alter paper colour is use an editor to add a black background and set all the text to white, without alter any other contents. That is just not always possible unless you are Adobe Reader (which is little restricted brother of PRO editor). Most readers cannot achieve what you desire, try reversing PDF in Edge with Acrobat light, same problem the black and white reversal alters every other colour to negative. ePub in Edge may be slightly different (it was in older SumatraPDF) however the same issues persist there too.

understood. Invert colors it is, then.

**Comment by GitHubRulesOK** [comment]
@chadify 
see latest update
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/83a0e654-c358-4011-adf7-68d63e5f3de7)
