### ISSUE TITLE
Open Files are reopened

### ISSUE THREAD

**Issue by michele74c** [sumatrapdfreader/sumatrapdf#3827]
If "Use tabs" is disabled in SumatraPDF options / Advanced, documents already open are opened again when opening another pdf.
Version 3.5.2

**Comment by GitHubRulesOK** [comment]
possibly resolved by setting ReuseInstance = true see https://github.com/sumatrapdfreader/sumatrapdf/issues/3800#issuecomment-1780928973

**Comment by michele74c** [comment]
Thank you, It works. Sorry if this issue had been answered somewhere here. I haven't found it.

**Comment by michele74c** [comment]
Thank you, It works. Sorry if this issue had been answered somewhere here. I haven't found it.
