### ISSUE TITLE
Usage of -named-dest does no longer work in pre-release 3.6?

### ISSUE THREAD

**Issue by honekamp** [sumatrapdfreader/sumatrapdf#3836]
I tried to search for a named destination in the 3.6 pre-release and it seems that the feature does no longer work. Using 3.5, everything works just fine.

**Comment by kjk** [comment]
please provide test document and the exact way you're using -named-dest

**Comment by GitHubRulesOK** [comment]
There does seem to be some problem so here is simplest sample each name from 100 to 600 is the page thus
```
SumatraPDF-15850-32.exe -named-dest 200 NamedDest100-600.pdf 
```
should open page 2 of this test file
[NamedDest100-600.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13244008/NamedDest100-600.pdf)

This does not always work when the file is first opened but may once DDE is active.  (Command line should over-ride remember last opened page but does not seem to matter if remember is on or off)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/7f78e112-397a-4704-9a18-0f87aa55edd4)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/37ac5ece-ff68-4ecd-b3ac-da9bd604c2dc)

**Comment by kjk** [comment]
Thanks for the example, bad interaction of -named-dest with restoring a session.

**Comment by honekamp** [comment]
My usage of Sumatra for reproducing the described issue:

SumatraPDF.exe -reuse-instance -named-dest constr_1006 AUTOSAR_TPS_SoftwareComponentTemplate.pdf

The file can be downloaded using this [link](https://www.autosar.org/fileadmin/standards/R22-11/CP/AUTOSAR_TPS_SoftwareComponentTemplate.pdf)

I used SumataPDF 3.5.3 (works) and 3.6.15861 (doesn't work) for testing.

**Comment by honekamp** [comment]
@kjk, the issue still persists in the latest pre-release build (from today). Here's what I do:

SumatraPDF-prerel-64.exe -named-dest MetaClassTarget:PortPrototype AUTOSAR_TPS_SoftwareComponentTemplate.pdf

This command line launches version 3.6.15875 and will not work, but 

sumatrapdf -reuse-instance -named-dest MetaClassTarget:PortPrototype AUTOSAR_TPS_SoftwareComponentTemplate.pdf

(which launches version 3.5.2) will work. The (admittedly rather big) PDF document can be downloaded from [here](https://www.autosar.org/fileadmin/standards/R22-11/CP/AUTOSAR_TPS_SoftwareComponentTemplate.pdf)

Could you please have a look at the problem again?

**Comment by GitHubRulesOK** [comment]
Does not work in Edge Powered by Acrobat but that's not too surprising its flaky at the best of times
https://www.autosar.org/fileadmin/standards/R22-11/CP/AUTOSAR_TPS_SoftwareComponentTemplate.pdf#nameddest=MetaClassTarget:PortPrototype

works for Acrobat = a Page 73 destination
"C:\Program Files\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe" /A nameddest=MetaClassTarget:PortPrototype C:\Users\lez\Downloads\AUTOSAR_TPS_SoftwareComponentTemplate.pdf

Earlier version 15712 works going to page 73 top of table @ Class              PortPrototype (abstract)
"C:\Users\lez\Downloads\Apps\PDF\SumatraPDF\15712\SumatraPDF.exe" -named-dest "MetaClassTarget:PortPrototype" C:\Users\lez\Downloads\AUTOSAR_TPS_SoftwareComponentTemplate.pdf

recent SumatraPDF does not respect same syntax nor
"C:\Users\lez\Downloads\Apps\PDF\SumatraPDF\15875\SumatraPDF.exe" /A "#nameddest=MetaClassTarget:PortPrototype" C:\Users\lez\Downloads\AUTOSAR_TPS_SoftwareComponentTemplate.pdf

only a destination of "PortPrototype" in current will go to Previous page text on Page 72

**Comment by honekamp** [comment]
Thanks for fixing, @kjk. I have taken the latest pre-release build for a test. It behaves as expected. Thanks, again!
