### ISSUE TITLE
Can't jump to bookmarked position in 3.5.2、prerel

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#3843]
[2022年07月产前和产时电子胎心监护临床实践专家共识.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13251448/2022.07.pdf)
This file has bookmarks contain specific positions, in 3.4.6, it worked fine.

But in recent versions, click on bookmarks only jump to page of contents, not the specific position.

**Comment by kjk** [comment]
The link is `#page=9&view=FitH,719.17807` and in `HandleLinkMupdf` fz_resolve_link() doesn't handle this, it returns `x` as `NaN`.

Not sure if that's mupdf regression or I'm not using the right functions.

**Comment by kjk** [comment]
Need to use fz_resolve_link_dest() and handle fz_link_dest_type of FZ_LINK_DEST_FIT_H etc.
