### ISSUE TITLE
formatting problems when copy text from some pdfs 

### ISSUE THREAD

**Issue by jacobkasper** [sumatrapdfreader/sumatrapdf#3844]
When copying text from the attached pdf spaces become '!' when pasted into another program. This does not happen when the text is copied from the document viewed in Adobe. When the text is bold the spaces become '?'.

[example.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13251735/example.pdf)

**Comment by GitHubRulesOK** [comment]
hmm looks like bad generation of text without spaces ??
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6fd24622-4b89-426c-98f5-96a102807bf0)

**Comment by jacobkasper** [comment]
what did you do to fix the pdf?

**Comment by GitHubRulesOK** [comment]
@jacobkasper 
In an editor I asked what each character is mapped to so can see the binary code os a TAB ! HeX=09 but the visual is a space and the core description is exclaim what a mix ! so simply said ALL three are 32=20 in HeX=space character.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/dedf3aa8-b58f-420e-8e11-dc669390c8b5)

**Comment by GitHubRulesOK** [comment]
@kjk 
unsure if this should be closed as bad file or MuPDF could ignore the poor definition of spaces as others appear to do ?
not an uncommon problem that CID is incorrect but I have not seen this odd mix before ?

**Comment by kjk** [comment]
If non-mupdf readers can handle it correctly, then it can be fixed in mupdf and should be reported to mupdf.

**Comment by GitHubRulesOK** [comment]
That is my point this file is unusual to each application
so Acrobat textport shows the rogue spaces ignored. (tab would be an invalid character)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c7b8cdba-0e17-42c4-a0d9-63496502a3b3)

**Comment by GitHubRulesOK** [comment]
Closing as Apparently some corrections in MuPDF updates
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/72b65707-bef9-44ef-ab85-23c028156389)
