### ISSUE TITLE
No full row selection of bookmarks in recent versions

### ISSUE THREAD

**Issue by 775405984** [sumatrapdfreader/sumatrapdf#3845]
![截图_2023-11-04_01-32-27](https://github.com/sumatrapdfreader/sumatrapdf/assets/7196377/0102266b-11e5-49e9-b57d-3c1c04ad1ac9)

This is 3.4.6, it can select bookmarks in full row, even in blank space.

But not in recent versions.

**Comment by Croqueta0** [comment]
This is definitely a downgrade. I hope they can restore it back.
