### ISSUE TITLE
3.5.2 installer asks for admin privileges when installing in %appdata%

### ISSUE THREAD

**Issue by skjaeve** [sumatrapdfreader/sumatrapdf#3847]
The installer asks for admin privileges when installing only for me. If I reject admin privileges, the installer exits without installing.
OS: Windows 10

**Comment by kjk** [comment]
We elevate if:
* you picked 'all users` option via cmd-line or in UI
* we detected existing installation that requires admin to uninstall

You can run the installer with `-log` option and that will log to `sumatra-install-log.txt` in temp directory and would show why.
