### ISSUE TITLE
unnable to open advanced option and unable to change text color for dark(er) theme

### ISSUE THREAD

**Issue by geethubccc** [sumatrapdfreader/sumatrapdf#3848]
_version:_ SumatraPDF-3.5.2-64 while SumatraPDF-3.4.6-64 is fine
_system:_ win10

_issue description:_
    In 3.5.2, I can't open SumatraPDF-settings.txt file by clicking  'advanced options'.
Besides, when I choose dark(er) theme, all my settings like 'TextColor', 'BackgroundColor', 'SelectionColor', etc, are all invalid, ofcause recover when choose light theme.

<img width="496" alt="0" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/71663910/9c921fe8-8504-409d-aa76-fded314b8abc">

<img width="462" alt="1" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/71663910/40d2953a-7996-4ab0-9c70-60c010039dcb">

_So, what I want are:_ 
    Able to open SumatraPDF-settings.txt file by clicking 'advanced options' like SumatraPDF-3.4.6-64.
    Able to edit settings like 'TextColor', 'BackgroundColor', 'SelectionColor', etc, in dark(er) theme.

**Comment by GitHubRulesOK** [comment]
Hmm Newer SumatraPDf does not automatically use Notepad for Settings but whatever FTA association may be detected !

the setting file should be accessible via `CTRL+K >a`  then either advanced settings or advanced options ?
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/a73f9450-c75b-4361-9175-eb87932828a2)

or via explorer `%localappdata%\SumatraPDF`
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c98f2ff4-0470-4da1-9196-93f35c9bcd30)

**Comment by username116** [comment]
May I suggest you try the [latest pre-release](https://www.sumatrapdfreader.org/prerelease)? `TextColor` and `BackgroundColor` customization has been working with the dark theme for two days, thanks to 5ceb24aadd2021a6ee2e4e14a3589fa65202790b. It works for me. I haven't tried to modify `SelectionColor`.

With this pre-release 3.6.15869, I can also open SumatraPDF-settings.txt from the menu (my editor is Notepad++), so I don't know about that.

**Comment by GitHubRulesOK** [comment]
@username116 beat me too it I was about to add latest pre-release allows setting colours in Dark/er
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6c740fe2-5141-46da-a420-54c52b41eddf)

**Comment by geethubccc** [comment]
@username116 Thank you for your advice. 
Using SumatraPDF-prerel-64 did fix my problems, though now the white frame looks a bit strange.
![20231105_190854](https://github.com/sumatrapdfreader/sumatrapdf/assets/71663910/fc41d4fc-2805-4efc-bc08-0e92c68852f6)
![20231105_191126](https://github.com/sumatrapdfreader/sumatrapdf/assets/71663910/b3cb885a-364e-45da-886f-22dc8c36f159)

**Comment by geethubccc** [comment]
@username116 It seems that the MainWindowBackground is linked to the tab color and toolbar color now.
![20231105_192703](https://github.com/sumatrapdfreader/sumatrapdf/assets/71663910/16e93351-3929-4d37-9bbf-2b56a490b1b4)
