### ISSUE TITLE
[bug] autoset ShowToc = false

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#3851]
If I close the Sumantra in SumatraPDF-settings.txt the ShowToc set to 'false'.
I don't know why.
I delete SumatraPDF-settings.txt, but problem is return 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/33c086a0-2188-49d8-888e-ec06967bfef4)

**Comment by kjk** [comment]
The only thing I can think of is: that SumatraPDF executable is also used in plugin mode, which resets `ShowToc` to false. Plugin mode is. e.g. when sumatra is used in Total Commander to preview PDF documents.

**Comment by Aliaksandr3by** [comment]
I use the free doublecmd.
but it is true, if I will use Explorer and there open SumatraPDF-prerel-64.exe, problem is gone... 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/f241d576-a0ea-47f4-b6f7-6a03b0e2f60b)

**Comment by kjk** [comment]
You can use Sumatra, just pass `Additional parameters` `-appdata <some_directory>` (see https://www.sumatrapdfreader.org/docs/Command-line-arguments).

This will save settings in that directory and they will not interfere with plugin usage.

**Comment by Aliaksandr3by** [comment]
> appdata

no, it use SumatraPDF-settings.txt from the path that contain SumatraPDF-prerel-64.exe.
after exit programm it switch ShowToc = false

**Comment by GitHubRulesOK** [comment]
@kjk
can you please double check parameter handling as this suggests -appdata is either getting or gathering some currentdir as unspecified prefix

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2a89ce99-1b29-4ffc-b282-195f55192c13)

**Comment by Aliaksandr3by** [comment]
I don't use 'appdata ', only exe an txt
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/6f49df3b-659c-4b78-8b32-a9a2576c388c)

**Comment by GitHubRulesOK** [comment]
My example above is portable SumatraPDF with portable commander so portable SumatraPDF is in one folder system and commander in another folder system but FOR COMMANDER View it calls with the settings in commander folder while other apps can have different default setting in portable folder or use the commander one If I want them to.

In theory you should not be having any problem with the settings file EXCEPT if the Windows Useage control is seeing a difference so a 64bit app should call a 64bit app and a 32bit app call up 32bit app BOTH mine commander & SumatraPDF are 32bit. local on C:\drive (although drives should not normally be a problem either unless managed by another app)

**Comment by Aliaksandr3by** [comment]
I don't know, I don't understand.
back to SumatraPDF-3.5.2-64.exe is good working for me

**Comment by GitHubRulesOK** [comment]
@Aliaksandr3by 
OHH thats a file by file setting not the master one, that one is set false usually by closing bookmarks
```
If I close bookmarks then the setting goes to false from true **for remember next time**
```
FilePath = C:\Users\lez\Downloads\pdf-lib_add_attachments.pdf
		Favorites [
		]
		IsPinned = false
		IsMissing = false
		OpenCount = 10
		UseDefaultState = false
		DisplayMode = continuous
		ScrollPos = -1 -1
		PageNo = 1
		Zoom = fit page
		Rotation = 0
		WindowState = 1
		WindowPos = 812 218 959 732
		ShowToc = false
```

**Comment by Aliaksandr3by** [comment]
If I use SumatraPDF-3.5.2-64.exe, I will get good using.
If I copy content from SumatraPDF-settings.txt, and then to run SumatraPDF-prerel-64.exe and then to close it.
SumatraPDF-prerel-64.exe have changed in the SumatraPDF-settings.txt.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/b05ba06c-7288-4bdd-99bb-4183ea34c759)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/a0c5b720-3f38-42a4-995d-301951b6d2cb)

**Comment by Aliaksandr3by** [comment]
))) problem is gone , thx

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/4619353c-31c9-4172-b46b-92eba9e50f3a)

**Comment by Aliaksandr3by** [comment]
no, it is don't work I hurried with conclusions

**Comment by Aliaksandr3by** [comment]
I understand:
If I open 10 books, all they have the 'ShowToc = true', the books, which I was reading (it were active), are saved the 'ShowToc = true' (e.g. 3 books) another 7 books will have been changed 'ShowToc = false' after to close Sumantra.

open Sumatra --> read SumatraPDF-settings.txt --> close Sumatra --> write  SumatraPDF-settings.txt

**Comment by Aliaksandr3by** [comment]
this bug will be not solve?
