### ISSUE TITLE
DarkThemes Not Applied To Custom Txt\ Bg Colors /w Recent Commit! (PreRelease Build)

### ISSUE THREAD

**Issue by alienfxfiend** [sumatrapdfreader/sumatrapdf#3854]
DarkThemes are not working [with custom colors] with this latest commit prerelease build 87a52849f17f6fa50b0d04df27ac38bef42e2ffd ! A few days back it worked brilliantly ! For instance when you set-up custom colors, try it /w TextColor = #A3DE34 BackgroundColor = #000000 SelectionColor = #f5fc0c. Also, I'am using a WindowBlinds skin but I have UseSysColors = false. Please fix this bug ! Only the UI is skinned /w DarkMode colors & the Menu is extra-padded, but the PDF etc. document colors remain the Custom-Chosen ones.

**Comment by alienfxfiend** [comment]
> There were problems with no custom control in last months versions so the old system for light was reinstated for dark so you can set custom colours in dark theme too
> 
> October (FORCED colours) on Left November (Custom colours) on right ![image](https://user-images.githubusercontent.com/12754913/280667599-fd7d9fbc-44b1-4d09-8204-0a2bac90b16c.png) ![image](https://user-images.githubusercontent.com/12754913/280669709-b92e1894-7b55-405a-8177-3702415e822f.png)
> 
> To restore inversed colours to October settings use
> 
> ```
> FixedPageUI [
> 	TextColor = #c0c0c0
> 	BackgroundColor = #303030
> 	SelectionColor = #f5fc0c
> ```

I see that these are the color settings for 'Darker' theme —but may I have the color settings for the Solarized Dark 'Dark' theme instead please ?

**Comment by alienfxfiend** [comment]
Nevermind, I'd still like it fixed to override custom-colors with DarkTheme colors. Thanks !

**Comment by GitHubRulesOK** [comment]
It should be something like this but thats based on comparison since I dont know which code it was
```
FixedPageUI [
	TextColor = #c0cccc
	BackgroundColor = #2c3a42
	SelectionColor = #f5fc0c
```
