### ISSUE TITLE
can not select/copy text  version 3.5.2 64-bit

### ISSUE THREAD

**Issue by WacoJohn** [sumatrapdfreader/sumatrapdf#3858]
Was using Foxit on 3 different Windows 10 machines.  Worked fine for years.  Could double click on a word and copy/paste it elsewhere.  No longer.  Tried everything I could find to make it work but it refused.  Trying Sumatra now .... same problem.  The file is a pdf printed from LastPass of all my passwords.  It is the same file I have selected, copied and pasted to/from for years.

Sumatra simply says double click on the word .... just like Foxit ... but neither work.  Sumatra opens the file with a mouse/trackpad 'arrow'.  Foxit with a 'hand'.  Tried enabling 'selection' on both, and Sumatra will only allow me to select the entire document.

Any help is appreciated in advance.

**Comment by GitHubRulesOK** [comment]
Not a SumatraPDF issue if its also a problem in Foxit
It sounds like it has been converted from text to image 
If so it would need OCR to try to convert back into selectable text, and SumatraPDF is not an editor with OCR

**Comment by kjk** [comment]
We need a sample document but as @GitHubRulesOK said: most likely that's a PDF with images that look like text so there's nothing to extract.

**Comment by WacoJohn** [comment]
> Not a SumatraPDF issue if its also a problem in Foxit It sounds like it has been converted from text to image If so it would need OCR editing to try to convert back into selectable text, and SumatraPDF is not an editor with OCR

I must totally agree with you.  I created a txt file with with Notepad, printed it as pdf, and it works (on all my PDF reader products).  What I don't understand is when/how the LastPass pdf file became an image file.  Guess next stop is LastPass forum.

Thanks to all who have been so helpful.
