### ISSUE TITLE
Cannot Access Advanced Options 

### ISSUE THREAD

**Issue by focusright** [sumatrapdfreader/sumatrapdf#3859]
Advanced Options opens in Visual Studio Code but a blank file shows up. Along with that, another vscode tab with my name in the title shows up as well, it's also empty.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/47800380/bd372dc8-de4f-4665-9211-ca8ce8cc454a)

**Comment by kjk** [comment]
Which version of Sumatra?
Installed or portable?

Please:
- trigger this
- use `Show Log` with `Ctrl + K` (command palette)

There should be a log line like:

````
BuildOpenFileCmd: path: 'C:\Users\kjk\!sumatra\!exe\SumatraPDF-settings.txt', pattern: '"C:\Users\kjk\AppData\Local\Programs\Microsoft VS Code\Code.exe" --goto %f:%l'
OpenFileWithTextEditor: '"C:\Users\kjk\AppData\Local\Programs\Microsoft VS Code\Code.exe" --goto C:\Users\kjk\!sumatra\!exe\SumatraPDF-settings.txt:1'
```

Please post what it says on your machine.

This works on my machine so it looks like a configuration issue (maybe admin / non-admin permissions).

**Comment by focusright** [comment]
BuildOpenFileCmd: path: 'C:\Users\Mike Lee\AppData\Local\SumatraPDF\SumatraPDF-settings.txt', pattern: '"C:\Users\Mike Lee\AppData\Local\Programs\Microsoft VS Code\Code.exe" --goto %f:%l'
OpenFileWithTextEditor: '"C:\Users\Mike Lee\AppData\Local\Programs\Microsoft VS Code\Code.exe" --goto C:\Users\Mike Lee\AppData\Local\SumatraPDF\SumatraPDF-settings.txt:1'

**Comment by kjk** [comment]
ah, it could be I'm not quoting the path to settings file and it breaks when there's a space in the path

**Comment by kjk** [comment]
thanks for the log, will be fixed in the next [pre-release](https://www.sumatrapdfreader.org/prerelease)
