### ISSUE TITLE
Specify paper bin by number?

### ISSUE THREAD

**Issue by floralsystems** [sumatrapdfreader/sumatrapdf#386]
Hello and thank you for this excellent software.

I'm attempting to use the "bin=" command line setting with the paper tray number (obtained from dmDefaultSource in another application), but printing instead occurs on the default tray no matter which paper tray is specified. If I switch to using bin names, printing occurs correctly on the specified tray. I've looked at the relevant source code at:
// alternatively allow indicating the paper bin directly by number
https://github.com/sumatrapdfreader/sumatrapdf/blob/9ef5067c38544b4f46554aa95334edd502983515/src/Print.cpp#L687

It seems fairly straightforward. Are there any "gotchas" to using this method?

**Comment by kjk** [comment]
Nothing that I can think of. If you're feeling brave, you can step through the code in the debugger to see if `name` variable is a valid number, if str::Parse() parses it correctly and if the named bin names resolve to the same values you're providing as numbers.

**Comment by floralsystems** [comment]
Thanks kjk. Brave I am, but experienced in c++ or win32 I am not.  I was barely able to cobble together a solution to capture the user's selected print settings... so I only have the dmDefaultSource. Selecting tray 1 and 2 for my current printer returns bin numbers 1 and 2 respectively.

If I manually run sumatra with "C:\Users\User\Desktop\sumatra.exe" "C:\printables\print-me.pdf" -print-to "Brother HL-5470DWT series" -print-settings "bin=**#**" (replacing # with both 1 and 2) it always prints from the first (default) tray.

**Comment by floralsystems** [comment]
A bit more information... I verified that my bin numbers were accurate with another app (http://www.unixwiz.net/tools/winprinfo.html). I believe this confirms that providing bin numbers is not supported via command line.

Thanks for listening.

**Comment by floralsystems** [comment]
It's not much, but I posted a bounty for this:
https://www.bountysource.com/issues/28966431-specify-paper-bin-by-number

**Comment by floralsystems** [comment]
Scratch that, I may have been passing the wrong bin numbers all along... more investigation is needed. Sorry for wasting your time.
