### ISSUE TITLE
HALFPAGEUP acts like DOWN in Single-Page View

### ISSUE THREAD

**Issue by ykqlg** [sumatrapdfreader/sumatrapdf#3862]
HalfPageUp acts like Down in Single-Page View. It causes a little trouble when i bind the 'd' to HalfPageUp and cannot act as expected when i am in single-page view.

**Comment by kjk** [comment]
There is no such thing as showing half page in single page view so what should it do instead?

**Comment by ykqlg** [comment]
> There is no such thing as showing half page in single page view so what should it do instead?

Please forgive me and let me restart my issue. There is a key named "HalfPageUp" (Command ID) which is used for roll down page halfly. The key behaves normally in other views except singel-page view. When I use it(HalfPageUp) in single-page view, it will have the effect of going to the next page instead of the previous page.

I have no idea what causes this key behave differently in different views. I will appreciate you guys to figure this out. If cannot, actually I can use other way to replace this need. Thanks!

**Comment by GitHubRulesOK** [comment]
@kjk the behaviour replicates the shifted up/down arrow so historically jumped page previous or next
this was shift one page up in 3.2 and previous
unsure without local 3.3 at present 
but seems to have regressed in  3.4/5/6 to be same as shift down
