### ISSUE TITLE
ExternalViewers Notepad Command Line Issue

### ISSUE THREAD

**Issue by tinygrox** [sumatrapdfreader/sumatrapdf#3868]
## Report Description:
I have encountered an issue while using SumatraPDF version 3.5. 
I set up an ExternalViewer configuration in the advanced options to open a separate Notepad file with the same name as the PDF file I was reading. The configuration was as follows:
```
:From: https://forum.sumatrapdfreader.org/t/advanced-tips-add-your-own-notes/2688
ExternalViewers [
  	[
		CommandLine = C:\windows\system32\Notepad.exe "%1.Page%p.txt"
		Name = Notepad the Notes for &This page
		Filter = *.*
	]
  ]
```
However, after upgrading to version 3.5, I noticed that when I use this feature, Notepad opens the PDF file itself instead of creating a separate `.txt` file with the same name. This issue was not present in version 2.3 as far as I know, and it also not working in 3.4.

## Steps to Reproduce:

1. Install SumatraPDF version 3.5.2.
2. Set up the ExternalViewer configuration in the advanced options as described above.
3. Open a PDF file then `File > Open in Notepad the Notes for &This page for This file`

## Expected Behavior:

Notepad should open a `.txt` file with the same name as the PDF file as the reading notes. Or ask if you want to create the file on the first run.

## Actual Behavior:

Notepad opens the PDF file itself instead of creating a separate .txt file.

## Additional Information:
- Operating System: [Windows 10]
- SumatraPDF Version: 3.5.2

**Comment by GitHubRulesOK** [comment]
@kjk I have had problems with the inclusion of unexpected quotes befor the user should be able to add their own so in thi case it disturbs the natural means to send filenale without quotes

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6289ca43-f221-41f4-a665-71c72580f85c)

**Comment by GitHubRulesOK** [comment]
@kjk unknown how it may have affected other issues such as https://github.com/sumatrapdfreader/sumatrapdf/issues/1140 however the root of the added quotes was to fix 
https://github.com/sumatrapdfreader/sumatrapdf/issues/2163
however that was an odd usage and perhaps as a result of my comment https://github.com/sumatrapdfreader/sumatrapdf/issues/2163#issuecomment-919144975

in 3.4.6 there was an error that double quotes were stripped from parameters (when the filename correctly already had them added manually)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6104d647-7a10-471c-891d-63a2df17af36)
they had been working well in 3.3.3
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/bba4fbc1-b4d1-4fcc-a183-8026c9e49373)
Currently this means commands and their arguments cannot be quoted
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f12cff83-c992-4236-9c43-edc2e9b538c7)

**Comment by GitHubRulesOK** [comment]
@tinygrox 

still not the way it used to be but this should work with current pre-release 3.6.15888 !

```
ExternalViewers [
	[
		CommandLine = "c:\windows\System32\notepad.exe" """%1-page%p.txt"""
		Name = Notepad Scrip&t
		Filter = *.*
	]
]
```1

**Comment by tinygrox** [comment]
In pre-release 3.6.15888, it works. Thanks! @GitHubRulesOK

**Comment by kjk** [comment]
The triple-quotes should not be necessary.
```
CommandLine = "c:\windows\System32\notepad.exe" %1-page%p.txt
and
CommandLine = "c:\windows\System32\notepad.exe" "%1-page%p.txt"
```
should work.
