### ISSUE TITLE
Keyboard shortcut for rotate left not working

### ISSUE THREAD

**Issue by bouzidabdelfattah** [sumatrapdfreader/sumatrapdf#387]
Hi
the keyboard shortcut  Ctrl Shift -     for  rotate left is not working
I'm in Acer Aspire One,Windows 7,keyboard AZERTY.

NB:
+, -     zoom in/out is working

**Comment by GitHubRulesOK** [comment]
@bouzidabdelfattah 
I have not noticed problems on acer QWERTY hardware, can you confirm if this issue is still affecting acer or AZERTY on new builds from https://www.sumatrapdfreader.org/dailybuilds.html

**Comment by kjk** [comment]
Without access to that hardware can't make progress.
