### ISSUE TITLE
Del should not delete an annotation if editing

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#3878]
When testing Sumatra version 3.5.2, I noticed that in the annotation editor, if the del key is pressed while the note is written, the note is completely deleted.

_Originally posted by @xmfbraga in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3872_

**Comment by romankarlstetter** [comment]
Any plans when this fix will be part of an official release?

**Comment by kjk** [comment]
Sorry, I don't know when the next release will be, hence pre-release builds.
