### ISSUE TITLE
Directory of file renaming should be the one of the PDF file

### ISSUE THREAD

**Issue by koppor** [sumatrapdfreader/sumatrapdf#3884]
I opened a PDF in SumatraPDF. Two hours later, I closed it and opened multiple other documents. Then I want to rename a document. I press <kbd>F2</kbd>. Following dialog opens:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/1366654/b86a010e-0657-4975-a50a-eb638fb4a1cb)

The directory shown is the one of the first document I opened with SumatraPDF, not the directory of the currently opened PDF.

Would it be possible to initialize the directory of that dialog to the directory of the PDF where the functionality was triggered?

---

After manually choosing the directory of the PDF, it works. Also with new PDFs in different folders. Then, the folder of the new PDFs is shown.

**Comment by GitHubRulesOK** [comment]
I think you will find that is a problem with most windows applications so when I download a file as a new name I will be spirited by windows to the last folder used for that task (thus default action is outside SumatraPDF control)

What helps is to use show in folder, then if allowed by the system rename the file.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9306e74a-1a06-4956-b4be-4f8b0ea0c13e)

**Comment by kjk** [comment]
Which version of Sumatra?

As far as I can tell in latest release we set the directory of rename dialog to the directory of the file being renamed.

**Comment by koppor** [comment]
v3.5.2 64-bit. Currently, it works. Maybe, it's a "random" behavior.

Current situation: When renaming, the directory is OK, but <kbd>Ctrl</kbd>+<kbd>O</kbd> opens the last opened directory and not the directory of the current PDF. (Not sure whether this is an intended behavior)

**Comment by koppor** [comment]
The issue appears if SumatraPDF is started from scratch and opens an existing PDF file. When pressing <kbd>Ctrl</kbd>+<kbd>O</kbd>, it does NOT use the file of the currently opened PDF file.

But for <kbd>F2</kbd> it is the right directory upon start.
