### ISSUE TITLE
Turn off the function of double click with left mouse button which exit full screen mode.

### ISSUE THREAD

**Issue by luckybencosmos** [sumatrapdfreader/sumatrapdf#3886]
When I try to select a word in full-screen mode by double-clicking the left mouse button, it exits the full-screen mode.

I suggest giving the user an option to turn off the function of double-clicking with the left mouse button in full-screen mode.

**Comment by GitHubRulesOK** [comment]
Hmm interesting that nobody mentioned it before 

@kjk seems to be present in all of 3.5 and 3.6 variants ?

**Comment by kjk** [comment]
Well, I can't please everyone. I've added this because people wanted a way to exit full screen without using keyboard (i.e. `Esc`) when using touchscreen in tablet mode.

**Comment by GitHubRulesOK** [comment]
@kjk 
I agree you cant please all but touchscreen hold shows context 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6dcaabb9-dabe-484f-896e-bf6a5e3c6b3c)

**Comment by kjk** [comment]
I've improved it so that if double click happens over text, it'll select a word even in fullscreen.

Still possible to do it by accident so maybe exit fullscreen exiting should be limited to e.g. only to an area in upper-right corner.

**Comment by yashamon** [comment]
Why not just make it an option? Clicking on a word makes no difference, the viewer still exists FS. Also why not allow setting a shortcut for inverse search?

**Comment by kjk** [comment]
If you're on a word and double-click, the word will get selected and viewer will not exit fullscreen.

Options have serious problems:
- few people even know about them
- the more options there are, the harder it is to find the option you want
- they are not free to implement and maintain

So I much prefer find a better design than just add options whenever someone does like some particular behavior.

**Comment by yashamon** [comment]
How about making it an advanced option then (which we already configure by
JSON type configuration)? Surely this doesn't affect regular user.

Another simple solution would be to make inverse search shortcut
configurable, again an advanced configuration not affecting regular user.

That said, Sumatra users are already often advanced users. Your
average user uses acrobat Adobe Acrobat DC - Market Share, Competitor
Insights in PDF Readers And Editors (6sense.com)
<https://6sense.com/tech/pdf-readers-and-editors/adobe-acrobat-dc-market-share>

Selecting a word creates new problems. After going back to viewer, the word
presumably stays selected, which may mess up some workflows. And also is
just ugly.

**Comment by kjk** [comment]
fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/2641ec280b7bbd88a2c3871c592c8216d2e9f053
