### ISSUE TITLE
Can all annotation operations be moved to the top level of the right-click menu to provide more convenience for simple annotations?

### ISSUE THREAD

**Issue by xh542428798** [sumatrapdfreader/sumatrapdf#3892]
Could you please move all the annotation operations to the top level of the right-click menu, instead of using submenus? Since the right-click menu doesn't have many functions to begin with, placing them at the top level won't affect anything. However, for those who need simple annotations, it would be much more convenient to access them with just one right-click.

**Comment by kjk** [comment]
Most people do not use annotations so most likely I wont do it.

Highlight and underline annotations have keyboard shortcuts (`a` and `u`) and you can create custom keyboard shortcuts for all other annotations commands (https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts, https://www.sumatrapdfreader.org/docs/Commands for commands, (filter command IDs by `annot`).

**Comment by xh542428798** [comment]
Thank you, I understand now.

> Most people do not use annotations so most likely I wont do it.
> 
> Highlight and underline annotations have keyboard shortcuts (`a` and `u`) and you can create custom keyboard shortcuts for all other annotations commands (https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts, https://www.sumatrapdfreader.org/docs/Commands for commands, (filter command IDs by `annot`).
