### ISSUE TITLE
Want to use custom colors with `TextColor` and `BackgroundColor` even in dark theme that does not invert colors

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [sumatrapdfreader/sumatrapdf#3897]
When the theme is `Dark` or `Darker`, custom colors using `TextColor` and `BackgroundColor` of `FixedPageUI` are restricted and cannot be used.

This issue has already been answered as follows, but I disagree with this opinion.

> Using colors from settings in dark theme. That's intentional - only the light (original) theme can have colors over-ridden by settings, for backwards compatibility. Other themes just use the theme colors.
>
> - https://github.com/sumatrapdfreader/sumatrapdf/issues/3826#issuecomment-1785214685

## Motivation of raising the issue

The reason why I raised a new issue even though there is a similar issue #3826 is because the motivations of me and the issuer are different.

I wanted a dark theme for the entire application's UI, but I'm confused by the fact that I can only choose background color for PDFs between pure white or a predefined theme.

When I was using v3.4.6, the PDF was bright with a pure white background color, a little hard to see when the color were completely inverted, I adjusted the background color of PDF to a light cream color. For me, this was the easiest coloring to look at.

So being able to specify custom colors was an important feature for me. Nevertheless latest versions restrict such configurations under dark theme...

## To reproduce

Configure <samp>SumatraPDF-settings.txt</samp> as follows.

```SumatraPDF-settings.txt
Theme = Dark
FixedPageUI [
	TextColor = #0d0116
	BackgroundColor = #fcf6e6
	InvertColors = false
```

Configurations of `TextColor` and `BackgroundColor` are not reflected in the actually displayed PDF.

## What is required

Even if the application UI is in dark mode, if the PDF is not color inverted, I would like it to follow the `TextColor` and `BackgroundColor` of `FixedPageUI`.

I would like to avoid PDFs with a pure white background color under a dark theme. (I'm not particularly interested in whether the background _inverted_ color of PDFs under the dark theme follows the custom color.)

## Version

- Version: 3.5.2 64-bit
- git commit: https://github.com/sumatrapdfreader/sumatrapdf/commit/646d1feddcc80b3b51072c5b27a1446487904175

**Comment by GitHubRulesOK** [comment]
3.5.2 cannot be changed  only current pre-release can be altered so curently your wish is honoured
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/a3a35178-87c1-430d-96ba-53e442d389f4)
