### ISSUE TITLE
Problem with command line "-page" argument

### ISSUE THREAD

**Issue by umbertoB67** [sumatrapdfreader/sumatrapdf#3902]
When I open a PDF file (eg. [C:\Temp\PDF\FileName.pdf), SumatraPDF creates one file called "SumatraPDF-settings.txt".

If, for example, I move to page 8, this information (PageNo = 8) is saved in this file when I close the program.

Now, if I open the same PDF using this command line [C:\Temp\PDF\SumatraPDF.exe C:\Temp\PDF\FileName.pdf -page 20 -view "single page" -new-window] the program doesn't open to page 20 but page 8.

**Comment by GitHubRulesOK** [comment]
Currently in pre-release there seem to be a number of command line issues but it is "good practice" to "quote" filenames with their paths. So ideally the target at least quoted "C:\temp\File Name.pdf" (in addition to -view"blah blah" 

Your commands certainly worked as expected in 3.3.3 and 3.4.6 **but not 3.5.2**
However they work again the same way in pre-release 3.6.15898

**Comment by kjk** [comment]
Which version of Sumatra?

**Comment by kjk** [comment]
It seems to work in pre-release

**Comment by kjk** [comment]
Will be fixed in 3.5.3, already fixed in pre-release.
