### ISSUE TITLE
Request for adding Santali language

### ISSUE THREAD

**Issue by Prasanta-Hembram** [sumatrapdfreader/sumatrapdf#3909]
I would like to request the addition of the Santali language to https://www.apptranslator.org/app/SumatraPDF. I am eager to begin translating Sumatra PDF into Santali.

Thanks

**Comment by Prasanta-Hembram** [comment]
Santali language uses ISO 639-2, 639-3 which uses the alpha-3 code which is **sat**, a three letter code. If the project will be started I will call more number of user maintainers for this language.

Thanks
Ref: 
1. https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?code_ID=388
2. https://iso639-3.sil.org/code/sat

**Comment by kjk** [comment]
I've added Santali support.

You can add translations at: https://www.apptranslator.org/app/SumatraPDF/sat

Once the number of translations cross a certain threshold, we'll include the translations in the next pre-release build https://www.sumatrapdfreader.org/prerelease

If you use RSS reader, please subscribe to https://www.apptranslator.org/rss?app=SumatraPDF&lang=sat
This will notify you if there are new strings that need to be translated.

**Comment by Prasanta-Hembram** [comment]
Thank you @kjk for adding Santali language.

**Comment by GitHubRulesOK** [comment]
@Prasanta-Hembram 

I see you have been busy however you have not included the English `&` Marker for menu HOT KEY entries 
This is a tricky part of adding translations as some are needed and others are not PLUS they should be unique, for example

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e6ffc48b-5c95-4d48-b070-a09298ec5b1b)

```
Facing [Add a translation...](https://www.apptranslator.org/app/SumatraPDF/sat#)
&Facing [Add a translation...](https://www.apptranslator.org/app/SumatraPDF/sat#)
```
the lower one need the `&` included for **V**iew **F**acing  
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/607499a3-a2c8-4ae8-b9eb-d7d13e0cc512)

**Comment by Prasanta-Hembram** [comment]
Thanks for the remarks. Considering adding "&" after 40% translation, but maintaining consistent terminology across translators is challenging (multiple people are working).  I'll update the "&" marker once terminology is uniform. I have almost figured out where to insert.👍👍
