### ISSUE TITLE
Saving Free text annotations to existing pdf removes all previous annotations

### ISSUE THREAD

**Issue by protaniv** [sumatrapdfreader/sumatrapdf#3911]
Same as the title. Windows 10

Having trouble seeing if my settings are incorrect. It does seem like a weird bug. I just have some annotations and when I want to save, it opens a new dialog box with all the annotations but it removes all of the previous annotations. Feels like it saves the current "updated" state over the old state and just overwrites the data instead of appending it for example. The feature works nice but the saving part is messing with me. Really annoying.

Anybody had similar experiences and did you fix them?

_Originally posted by @protaniv in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3910_

**Comment by GitHubRulesOK** [comment]
Always test the most current pre-release as only changes can be applied to that and yes some versions may have had related behaviour.

To be altered you need to provide a known clean source file, and a full account of what steps **repeatedly** fail to function in current [pre-release.](https://www.sumatrapdfreader.org/prerelease)

**Comment by A-Infor** [comment]
Related to 3954

**Comment by kjk** [comment]
Does it still happen in pre-release? (https://www.sumatrapdfreader.org/prerelease)

We fixed at least one bug related to saving annotations: https://github.com/sumatrapdfreader/sumatrapdf/issues/3981

**Comment by cr4zyfish** [comment]
I also have this problem in version 3.5.2

**Comment by kjk** [comment]
If you can reproduce this in pre-release, then please re-open with reproducible steps and a test documents that shows that.

**Comment by cr4zyfish** [comment]
I downloaded pre-release version 3.6.16105 from https://www.sumatrapdfreader.org/prerelease and it is fixed.
