### ISSUE TITLE
Add a button in the toolbar to show/hide the Table of Contents

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#3912]
Currently, showing/hiding the Table of Contents requires going to the Menu → View → Show Bookmarks.

However, this is such a frequent action that having a button in the toolbar would be better. I know that it can also be shown/hidden by the keyboard shortcut F12, but I think that it would still be better to have a button.

Just to give an example, the PDF viewer in Microsoft Edge shows it this way:
<img width="247" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/2b548421-8c43-4593-898d-828382b0bfc8">

**Comment by GitHubRulesOK** [comment]
if every key had a button it would be as big as OSK (on screen keyboard) and that on some devices can be more than half the 
screen

Core MuPDF has no icons at all so SumatraPDF has one basic improvement a very minimalist set about 10 icons to fill the screen one to open files and only most recently 2 to rotate the page (when needed by PDF as other formats did not need that enhancement).

**Comment by GitHubRulesOK** [comment]
Really this is not an issue as there are many controls that do not fit the requirement for an additional icon being essential above all others, and the F12 can be set to any shortcut you want except programmable icons.

**Comment by user1823** [comment]
I get it that not all controls can be added to the toolbar. However, all of the PDF viewers I use have a prominent shortcut for showing/hiding the Table of Contents. So, I think that it is important enough to be included in the toolbar. 

Microsoft Edge:
<img width="247" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/2b548421-8c43-4593-898d-828382b0bfc8">

Firefox:
<img width="209" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/38fc8159-de9e-4127-a70f-0029378c0da8">

Adobe Acrobat DC:
<img width="332" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/a8d2eb58-00c6-4082-b074-6ab7a07881c7">

**Comment by GitHubRulesOK** [comment]
It is easy to add custom keyboard shortcuts.

However
Configuring toolbar is tracked by https://github.com/sumatrapdfreader/sumatrapdf/issues/19561

**Comment by kjk** [comment]
Toolbar is not customizable https://www.sumatrapdfreader.org/docs/Customize-toolbar

**Comment by GitHubRulesOK** [comment]
> Toolbar is not customizable https://www.sumatrapdfreader.org/docs/Customize-toolbar

 :-) Toolbar is NOW customizable https://www.sumatrapdfreader.org/docs/Customize-toolbar
