### ISSUE TITLE
Allow output file in `-printer-settings` from command line

### ISSUE THREAD

**Issue by wqweto** [sumatrapdfreader/sumatrapdf#3917]
I was reading `-print-settings <settings-list>` in the [docs](https://www.sumatrapdfreader.org/docs/Command-line-arguments) and was wondering if it is feasable to add `output=<filename>` in the advanced options.

I looked at the sources and a PR would be 10-20 lines of code for this feature if you would allow such addition.

The most obvious use-case is to use `Microsoft Print To PDF` printer with an output file to convert some PDFs to other PDFs for one reason or another.

**Comment by kjk** [comment]
The change looks good, @wqweto make a PR and I'll merge it
