### ISSUE TITLE
Still Crashing After Update Today!

### ISSUE THREAD

**Issue by alibadrelsayed** [sumatrapdfreader/sumatrapdf#3918]
**Yesterday kjk closed the issue, after updating today the issue still exist.**

https://gist.github.com/alibadrelsayed/2dbc3e6bfa536117b47649a158177b99#file-gistfile1-txt

[sumatrapdfcrash.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/13483673/sumatrapdfcrash.txt)

**Comment by kjk** [comment]
Could you describe, step-by-step, in detail, what do you do from starting sumatra to getting the crash?

**Comment by alibadrelsayed** [comment]
> Could you describe, step-by-step, in detail, what do you do from starting Sumatra to getting the crash?
**1. I start Sumatra Normally from Start Menu.
2. In the main window there is 10 "Frequently Read" documents.
3. I opened one of them Normally.
4. When I tried to open another "Frequently Read" documents from the Main Tab the Crash happened.**

**Comment by GitHubRulesOK** [comment]
Hmmm
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/804b3a93-b0d5-4655-8469-1a4adc541d4c)

**Comment by alibadrelsayed** [comment]
> Hmmm [sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/13495320/sumatrapdfcrash.zip)
> 
> ![image](https://private-user-images.githubusercontent.com/12754913/286452244-804b3a93-b0d5-4655-8469-1a4adc541d4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMzEyMDAsIm5iZiI6MTcwMTIzMDkwMCwicGF0aCI6Ii8xMjc1NDkxMy8yODY0NTIyNDQtODA0YjNhOTMtYjBkNS00NjU1LTg0NjktMWE0YWRjNTQxZDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA0MDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2OGQzMDhlMzQxZDJiOTIwMjc1NDExNzc3NWRjOGE1NzU4MjQ0OGNhMzY3MWQwYjQyMmYyN2NjYjNjZjk3MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xSm-rPfAXprQiaCq69XqnLBXtz1cLqWIP2tA68ZU6FA)

Exactly the same Issue.

**Comment by alibadrelsayed** [comment]
Exactly The Same Crash
![Screenshot 2023-11-29 061314](https://github.com/sumatrapdfreader/sumatrapdf/assets/58970281/df6a326a-77de-456a-aa7a-dc5cec7f96c9)

**Comment by kjk** [comment]
Thanks, I was able to reproduce the problem.

**Comment by alibadrelsayed** [comment]
> reproduce

Thanks a lot, what you mean by reproduce?

**Comment by GitHubRulesOK** [comment]
all three of us
could use your description of actions to trigger (re - produce) a crashed state
thanks

**Comment by alibadrelsayed** [comment]
> all three of us could use your description of actions to trigger (re - produce) a crashed state thanks update should be in daily pre-release about 2 am UCT

Thanks a lot, appreciated.

**Comment by GitHubRulesOK** [comment]
@alibadrelsayed 
caution the daily download may not be easy to download
 there was a hiccup in daily build and web may download the day before 3.6.15914 (should be 15915, for me I see error 404)

**Comment by GitHubRulesOK** [comment]
@alibadrelsayed can you please remove that download link from your comments as later it will become redundant
