### ISSUE TITLE
Error Stream or Error Codes

### ISSUE THREAD

**Issue by Yannici** [sumatrapdfreader/sumatrapdf#392]
Hello,

we're using SumatraPDF to print pdf documents. We are happy with this tool, but one thing would be nice. We're siliencing the messages sumatra sends, because we don't want to show that error dialogs. We have customized error dialogs, therefore we don't want to display these dialogs. 

It would be nice when SumatraPDF.exe will return any error streams or console output if any error was thrown. A error code would be nice, too. So we can handle these errors individual.

Thanks!

**Comment by jdgvt81** [comment]
I just ran into this exact same issue today, so I'd like to second this request!  Sumatra is a fantastic tool, but there seems to be no (obvious?) way of diagnosing errors when using the -silent command line option.  Would be great if errors could be sent to the console.

**Comment by kjk** [comment]
It's unlikely I'll work on that. You can always give it a try and submit a fix https://github.com/sumatrapdfreader/sumatrapdf/wiki/Contribute-code

**Comment by jdgvt81** [comment]
That's too bad (I only know Python; am not familiar with C++), but I appreciate the response and thanks again for your work on the program!

**Comment by Yannici** [comment]
I'm not familiar with C++, too. :( But maybe I'll give it a try soon.

**Comment by Jolwarden** [comment]
I've found a solution using start /wait and looking at the errorlevel environment variable.
When using sumatraPDF in command line, use it with "start /wait" 
example : "start /wait sumatrapdf.exe -silent -print-to TESTPRINTER toto.pdf".
The program will set the environment variable errorlevel with the code returned.

(use echo %errorlevel% to see the code. If it set to 0 there is no error).

**Comment by GitHubRulesOK** [comment]
Most recent comment from development team of 1 :-) 
is that there is one code available and it is either 1 or not
https://forum.sumatrapdfreader.org/t/printing-from-command-line/886/4

When printing fails, the return code is 1. If it doesn’t, it’s 0.
