### ISSUE TITLE
Already opened files are re-opened when tabs are disabled

### ISSUE THREAD

**Issue by miloush** [sumatrapdfreader/sumatrapdf#3923]
This is duplicate of #3379.

Steps to reproduce:

0. disable tabs
1. open a file (from the win explorer or search bar)
2. open a different file (from the win explorer or search bar)

Now say I have `fileA` open.
There is one process. The command line is `"path-to-sumatra\SumatraPDF.exe"` `"path-to-file\fileA.pdf"`.
Then if I open `fileB` the previous process stays as it was, plus I get a new one, whose command line is `"path-to-sumatra\SumatraPDF.exe" "path-to-file\fileB.pdf"`. But `fileA` gets reopened in new window. So now I have two processes and three windows.
Open `fileC`, you get 3 processes and 7 windows, `fileD`, 4 processes and 15 windows.
Throughout this the image path name is always the same for all processes.

v3.5.2 x64

Setting `ReuseInstance = true` avoids the bug.

**Comment by GitHubRulesOK** [comment]
looks like duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3827 ? but that requirement was addressed

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/96eebbe3-9ff3-4461-9ad4-ea2a8495670b)

1. Open File A
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2cb93454-fdbb-4038-89e6-d657a1842f96)

2. Open another file but Reuse Instance is FALSE so use another instance
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/0fe96a54-2573-4a9d-b516-80541cc18172)

**Comment by miloush** [comment]
I was asked to open a new issue, pointing out https://github.com/sumatrapdfreader/sumatrapdf/commit/26cbe5c1376310391dc169028e363c1636820f6f instead would have helped. Thank you, looking forward to a new release.
