### ISSUE TITLE
Inverse search shortcut is not documented. Apparently cannot be changed. Conflicts with fullscreen.

### ISSUE THREAD

**Issue by yashamon** [sumatrapdfreader/sumatrapdf#3927]
Currently the inverse search shortcut is undocumented. Double left click works, but this seems to conflict with Full-screen. If I am in full-screen, double left click will take me out of full-screen.

An instant hack would be to remap the shortcut to right click. But we can't ...

This seems to be a new problem, with newer builds.

**Comment by kjk** [comment]
in https://github.com/sumatrapdfreader/sumatrapdf/commit/2641ec280b7bbd88a2c3871c592c8216d2e9f053 I removed double click to exit fullscreen (well, it works but only in upper right corner)
