### ISSUE TITLE
dailybuild failed yesterday 

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#3928]
there was a hiccup after compiling 3.6.15915 so web site pages are not updated ?

either I have a cache problem or the [https://www.sumatrapdfreader.org/prerelease](https://www.sumatrapdfreader.org/prerelease) page is stuck on 15914

build of type 'prerel' for ver '15915' already exists because 'https://kjk-files.s3.us-west-001.backblazeb2.com/software/sumatrapdf/prerel/15915/SumatraPDF-prerel-manifest.txt' exists
uploadToStorage: skipping upload because already uploadedFinished in 753.2114ms

**Comment by kjk** [comment]
Yeah, when upload fails this can happen. Should get cleared after new checkins.
