### ISSUE TITLE
Outlook 2016 32PDF Previewer stopped working with v3.1.1

### ISSUE THREAD

**Issue by wigster** [sumatrapdfreader/sumatrapdf#393]
Hi,

I am running the 32-bit MS Outlook 2016 on 64-bit Windows 10.

When I installed the 64-bit Sumatra, I get the option to use it as the system PDF previewer. The previewer works on the desktop, but it doesn't work with Outlook. It used to work with the 32-bit version previously. I am guessing it's because there isn't a 32-bit version of the handler. The previewer is recognised as installed but it doesn't open.

Installing the 32-bit version doesn't help, since the installer does not give the option to use that as the previewer for the system.

**Comment by craigalan** [comment]
Ditto here.  Although I am running **32-bit Outlook 2010 on 64-bit Windows 7.**  

The Outlook Preview is not working with the latest version.  If I uninstall and re-install 3.0, it works just fine.

With 3.0 the handler is listed in Outlook in Trust Center>Attachment Handlers....upon updated or installing 3.1, the handler is removed and obviously doesn't work.

For now sticking with v3.0 32-bit

**Comment by kjk** [comment]
Due to how things work, all apps and OS have to be of the same bit-ness (either all 32bit or all 64bit).

**Comment by craigalan** [comment]
But it does work with version 3.0 on W7 64bit with Office 32bit.

**Comment by irvinm** [comment]
I can confirm this bug as well.  Using Outlook 2016 (32-bit), neither 3.1.2 (x64 or x32) or 3.1.1 (x64 or x32) handle PDF previews.  Using 3.1 (x32) works fine.

**Comment by irvinm** [comment]
Also, I'm sorry kjk, but I disagree with your assessment.  Obviously Windows 10 (64-bit), running Outlook 2016 (32-bit), using SumatraPDF 3.0 (32-bit) works fine for many people.  I believe this issue should be open, not closed.  IMHO.

**Comment by craigalan** [comment]
Agreed that the issue should remain open.  SumatraPDF 3.0 32 bit obviously works with Windows 7 64 Bit, on Outlook 2010 32Bit...as the preview has been working fine this way for me.  The last update still has the same issue.

**Comment by lephyrus** [comment]
New user of SumatraPDF (64bit) here - I expected this to work and found this issue. If I'm not mistaken, Office defaults to a 32bit installation even on 64bit Windows, so that should be very common. Since it looks like Outlook preview has worked with this combination before, it certainly would be nice if it did again in the future. I like this lightweight viewer (thanks!), and the Outlook integration would make it that much more useful.

**Comment by tiz777** [comment]
Another new user here, any news about this issue?
I confirm that Sumatra v3.0 does correctly work on Win7/64 + Office2013/32.
Tried 3.1.2 both 32+64bit but won't do the job.

Thanks in advance for checking this again!

**Comment by craigalan** [comment]
FYI - I posted on this not working in the past with W7 and Office 2013, but I recently upgraded to Windows 10 and have been using the latest version of Sumatra with Office 2016...this does in fact work with my current set up  :)  I missed having it work in the past

**Comment by willowmaster66** [comment]
I first installed the 32 bit version. Copied the installed files to a backup location. Then deinstalled the 32 version. Then installed the 64 bit version. Copied back the 32bit version to the "program files (X86)" folder. Started a command prompt. Then I typed: regsvr32 C:\Program Files (x86)\SumatraPDF\pdfpreview.dll
Now it seems to work in both Windows explorer(64bit) and in Outlook 2013 (32 bit)

**Comment by servicesenthydro** [comment]
I was searching google for a solution to this problem, so for anyone else who comes here with this problem, I had originally set the portable version of sumatrapdf as my default pdf viewer and Outlook previews weren't showing. I had to do the full 64bit installer version and change that to my default viewer to get previews to work in Outlook. (To make sure you change the default viewer to the correct sumatrapdf exe in windows 10, right click on a pdf file, click "Open With" > "Choose Another App", enable the checkbox for "Always use this app to open .pdf files", scroll down and click "More Apps", scroll down again and click "Look for another app on this PC",  go to C:\Program Files\SumatraPDF and double click on the SumatraPDF.exe file in that folder. You may need to close and reopen Outlook.)

**Comment by Meth0d007** [comment]
I dont know why this Issue is closed, the issue still exists in the current Sumatra version 3.3.3.

With a 32Bit Outlook 2016 the Sumatra Preview Handler does not work.
For me, not even installing the 32Bit Version of Sumatra and regsvr32 the previewhandler.dll will give me Outlook 32Bit previews.
So from what i have tested Sumatra Preview Handler does not work With 32Bit Office 2016, period.

If you switch to Office 2016 64Bit the current 3.3.3 Sumatra 64Bit works, that might not be an option for multiple reasons, so this is a bug that should be adressed.
