### ISSUE TITLE
auto-reload of the document iain't working in sumatra v3.5.2

### ISSUE THREAD

**Issue by goyalyashpal** [sumatrapdfreader/sumatrapdf#3932]
auto-reload of the document iain't working in sumatra v3.5.2

despite this setting: `ReloadModifiedDocuments = true`

last change: https://github.com/sumatrapdfreader/sumatrapdf/commit/646d1feddcc80b3b51072c5b27a1446487904175

os: win 10 22h2

it was working on v3.4

i am trying with outpu of `latexmk` as well as texstudio

**Comment by goyalyashpal** [comment]
https://github.com/sumatrapdfreader/sumatrapdf/discussions/2903#discussioncomment-3489372

the file size is only 265k

**Comment by GitHubRulesOK** [comment]
Works here
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/07206ef1-6c38-4e6e-9650-ff935fa347b5)

**Comment by kjk** [comment]
it is working in general. it might not work or work less reliably on network drives, One Drive, Google Drive, Dropbox etc. but without additional detail can't say anything more.

We log auto-refresh attempts so ou can use `Ctrl + K`, `Show logs` command to see if they were triggered.
