### ISSUE TITLE
[Bug] Crash when opening

### ISSUE THREAD

**Issue by GlopGlop31** [sumatrapdfreader/sumatrapdf#3936]
Good evening,

Here is the link to the crash report
Thanks for this great software
Sincerely

https://gist.github.com/GlopGlop31/fa67c9da4bdc69aa12f806ac20155c4b#file-gistfile1-txt

**Comment by kjk** [comment]
should be fixed in https://github.com/sumatrapdfreader/sumatrapdf/actions/runs/7029580105
