### ISSUE TITLE
When I change the document’s background color to black, the menus become black and unreadable

### ISSUE THREAD

**Issue by Shideravan** [sumatrapdfreader/sumatrapdf#3939]
I would like to use pure black color (#ffffff) for that part that the document does not occupy when I display it in full screen. Note that I wanted to use pure black, not that grayish black from the dark theme.
But unfortunately, if I change it this way, it will not only change the background of the document area, but all the items in the window as well:
```
MainWindowBackground = #80000000
```

Is there any way to configure it so that the window items are normal, but the background of the document area is black? Or is this really a bug?
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12163923/91aafd61-a907-4283-8387-430cda4e89ba)

Note that this happens with other colors too:

```
MainWindowBackground = #80f00000
```

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12163923/7c87c3dc-495d-4ab3-95f5-a58daa335afd)

**Comment by username116** [comment]
Maybe this setting? I'm not sure it's what you're looking for.
`GradientColors = #000000`

**Comment by GitHubRulesOK** [comment]
@username116 
reasonable suggestion so it looks like Acrobat use that colour in their darkest hour.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/bcbcc453-be72-4ab1-af4b-0ca46d4b8402)

**Comment by Shideravan** [comment]
> Maybe this setting? I'm not sure it's what you're looking for. `GradientColors = #000000`

_GradientColors = #000000_

Inside _FixedPageUI_ fixes that for me.
Thanks!
