### ISSUE TITLE
Recent file path trimming 

### ISSUE THREAD

**Issue by miloush** [sumatrapdfreader/sumatrapdf#3943]
The recent file paths list in File menu might need to be a bit more careful when inserting ellipsis to not split multi-byte characters:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/10546952/94e3ba17-9f43-4dcc-9f47-863985dfa6dc)

(this is only UI issue, v3.5.2)

**Comment by GitHubRulesOK** [comment]
Hmm without clear logic is it 2 3 or 4 chars per global character ? its a moving fete a compete

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/36103a50-4775-4fae-a01e-62cf0faa3d88)

**Comment by miloush** [comment]
Presumably this is UTF-8... then if the two MSB are 10, don't put anything before it.

**Comment by GitHubRulesOK** [comment]
unsure if its just Windows 8 as there will be 16 24 and 32 in LFNs

**Comment by miloush** [comment]
Are you suggesting it's Windows API shortening the path? (There is no UTF-24.)

**Comment by GitHubRulesOK** [comment]
one problem I have is try to capture the name and its ALL nulls

 File: C:\Users\lez\Downloads\�������������������������������������������.txt

**Comment by kjk** [comment]
Can you post at least one such path so that I can test it?

**Comment by GitHubRulesOK** [comment]
my sample's just a random file with a name made from emoji string as it is commonly found on occasion but any mixed Unicode file name such as a few oriental should throw at least one oddity
[🤣😊😂❤😍😒👌😘💕😁👍🙌🤦‍♀️🤦‍♂️🤷‍♀️🤷‍♂️.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13647540/default.pdf)

**Comment by kjk** [comment]
@GitHubRulesOK Thanks for the example path.

Need to improve `ShortenString` to handle unicode chars (encoded in utf8).

**Comment by miloush** [comment]
@kjk where is that in the code? The code search on GitHub does not show any results.

**Comment by kjk** [comment]
See https://github.com/sumatrapdfreader/sumatrapdf/commit/679fad75e4dd8d69e364311f87594586bc0186ae

Just added so github probably didn't index it yet

**Comment by GitHubRulesOK** [comment]
Looks similar here ?
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/42695450-fa97-4d22-b4ac-5e7fce25a651)
