### ISSUE TITLE
SumatraPDF 3.5.2 takes 8 seconds to open any PDF file

### ISSUE THREAD

**Issue by d0vgan** [sumatrapdfreader/sumatrapdf#3947]
Tried SumatraPDF 3.5.2 portable, 32-bit and 64-bit.
The OS is Windows 10 Pro 22H2 19045.3693, 64-bit.

Steps to reproduce:
1. Download a portable version of SumatraPDF 3.5.2, either 32-bit or 64-bit.
2. Unpack the downloaded archive into a newly created folder
3. Run the SumatraPDF-3.5.2 exe
4. Click "Open a document" and open any .pdf file
5. SumatraPDF seems to hang for 8 seconds while opening any .pdf file

For example, any .txt or .jpg file is opened immediately in 3.5.2.
SumatraPDF 3.1.2 opens any .pdf file almost immediately.
I should say that SumatraPDF 3.1.2 seems to be the most stable version even today. Whenever I tried any newer version, I experienced either crashes or hangs.

**Comment by d0vgan** [comment]
The pre-release build SumatraPDF-prerel-64.exe version 15920, built on 2023-12-09, also hangs for 8 seconds while opening any .pdf file.

**Comment by GitHubRulesOK** [comment]
Clearly there is aOS overhead to opening any application while loaded into memory and SumatraPDF could not know how long that took bust from a basic start on this very slow 32 bit machine the internal start is less than 1/10 a second
```
SumatraPDF-3.5.2-32.exe" 
LoadSettings() took 14.13 ms
ParseTranslationsTxt: 17632 lines, nStrings: 372
```
A large single image does take more than 1 second both external and internal (about 2 seconds total)
```
CreateEngineImageFromFile(C:\Users\lez\Downloads\4500.bmp)
EngineImage::CreateFromFile(C:\Users\lez\Downloads\4500.bmp)
CreateControllerForEngineOrFile: 'C:\Users\lez\Downloads\4500.bmp', 1 pages
LoadDocument: 712.15 ms, 1 pages for 'C:\Users\lez\Downloads\4500.bmp'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.00 ms
StartMonitoringDirForChangesAPC() C:\Users\lez\Downloads
EngineImages::RenderPage() in 300.85 ms
Slow rendering: 300.94 ms, page: 1 in 'C:\Users\lez\Downloads\4500.bmp'
```
Ok very large PDF is about 10 seconds but not all of those are internal only a few
```
CreateControllerForEngineOrFile: 'C:\Users\lez\Downloads\bigtest (1980 pages).pdf', 1980 pages
LoadDocument: 2470.29 ms, 1980 pages for 'C:\Users\lez\Downloads\bigtest (1980 pages).pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.12 ms
```
OK so file is now in memory lets see how long SumatraPDF takes to open another copy in under 1 second
```
CreateControllerForEngineOrFile: 'C:\Users\lez\Downloads\bigtest (1980 pages).pdf', 1980 pages
LoadDocument: 91.39 ms, 1980 pages for 'C:\Users\lez\Downloads\bigtest (1980 pages).pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.17 ms
```
So about 1/10th of a second for 1800 pages (not bad) but not down to the external system either.

**Comment by d0vgan** [comment]
This behavior is 100% reproducible on my PC and my laptop (both Windows 10, 64-bit).
I've recorded a real-time demonstration using ScreenToGif:
![SumatraPDF-352-open-pdf](https://github.com/sumatrapdfreader/sumatrapdf/assets/2848457/764389cb-b343-4d60-831c-52e971bee700)

How do you make profiling of SumatraPDF? Can I enable some logging?

**Comment by GitHubRulesOK** [comment]
certainly something wrong with your machine Just incase it has a significant effect I ensured I started with Russian as language
one page file with a slight hiccup to check its counted 
And there is no delay like you show even with a slight hesitation it takes under a second

To see the rudimentary log use CTRL + K > show log
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/b7d383d5-229a-42c7-beb6-bd10a2ae3abe)

**Comment by d0vgan** [comment]
Yes, according to the log, the document loading is actually very fast.
It would be interesting to have time stamps in the log. In addition to time stamps, it would be useful to have more events in the log - for example, events related to rendering of the content.
```
ReadRegStrTemp(HKEY_LOCAL_MACHINE, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
ReadRegStrTemp(HKEY_CURRENT_USER, Software\Microsoft\Windows\CurrentVersion\Uninstall\SumatraPDF, InstallLocation) => '(null)'
InstallCrashHandler crashDumpPath: 'C:\Progs\Progs\SumatraPDF-352\crashinfo\sumatrapdfcrash.dmp'
crashFilePath: 'C:\Progs\Progs\SumatraPDF-352\crashinfo\sumatrapdfcrash.txt'
symDir: 'C:\Progs\Progs\SumatraPDF-352\crashinfo'
Starting SumatraPDF 3.5.2, GetCommandLineW():
"C:\Progs\Progs\SumatraPDF-352\SumatraPDF-3.5.2-64.exe" 
LoadSettings() took 1.78 ms
ParseTranslationsTxt: 17632 lines, nStrings: 372
Untranslated strings: 5 for lang 'ru:'
Didn't find translation for '&Keyboard Shortcuts'
StartMonitoringDirForChangesAPC() C:\Progs\Progs\SumatraPDF-352
CreateControllerForEngineOrFile: 'C:\Users\Vitalii\Documents\Лист клієнтам.pdf', 1 pages
LoadDocument: 12.61 ms, 1 pages for 'C:\Users\Vitalii\Documents\Лист клієнтам.pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.60 ms
CanViewWithKnownExternalViewer cmd: 294, !ev || ev->exeFullPath == nullptr
CanViewWithKnownExternalViewer cmd: 295, !ev || ev->exeFullPath == nullptr
CanViewWithKnownExternalViewer cmd: 296, !ev || ev->exeFullPath == nullptr
CanViewWithKnownExternalViewer cmd: 297, !ev || ev->exeFullPath == nullptr
CanViewWithKnownExternalViewer cmd: 298, !ev || ev->exeFullPath == nullptr
CanViewWithKnownExternalViewer cmd: 299, !ev || ev->exeFullPath == nullptr
CanViewWithKnownExternalViewer cmd: 300, !ev || ev->exeFullPath == nullptr
CanViewWithKnownExternalViewer cmd: 301, !pos
CanViewWithKnownExternalViewer cmd: 302, !pos
CanViewWithKnownExternalViewer cmd: 303, !ev || ev->exeFullPath == nullptr
Didn't find translation for '&Keyboard Shortcuts'
StartMonitoringDirForChangesAPC() C:\Users\Vitalii\Documents
ReadDirectoryChangesNotification: FILE_ACTION_MODIFIED 'SumatraPDF-settings.txt'
NotifyAboutFile(): i=0 'C:\Progs\Progs\SumatraPDF-352\SumatraPDF-settings.txt' 'SumatraPDF-settings.txt'
ReadDirectoryChangesNotification: FILE_ACTION_MODIFIED 'SumatraPDF-settings.txt'
NotifyAboutFile(): i=0 'C:\Progs\Progs\SumatraPDF-352\SumatraPDF-settings.txt' 'SumatraPDF-settings.txt'
ReadDirectoryChangesNotification: FILE_ACTION_MODIFIED 'sumatrapdfcache'
```

**Comment by GitHubRulesOK** [comment]
I cant use 64 bit at present as this is a 32 bit OS, so I wonder if you try 32 bit does it differ in timings (though 64 bit should just be faster!)

What is odd is you say 2 machines are slow ( PC & laptop) so what app may be on both that has an affect ?
If your using some AntiVirus can you disconnect one from internet and temporarily switch off any file checking, here I only us MS as that's more than enough of a slowdown on its own (its the biggest user of memory, apart from Edge) without another in contention. Likewise I dont have any cloud based interference so OneDrive is never active (another system hog)

**Comment by d0vgan** [comment]
After more experiments, I was able to reproduce this strange behavior under Notepad++ and under Sublime Text.
Here is what I was doing:
1. Press Ctrl+O to show the "Open file" dialog
2. Go to a folder with any .pdf document, quickly select a .pdf document (with a single click of left mouse button) and then quickly press the "Open" button
3. As the result, the "Open file" dialog immediately disappears and the editor seems to hang for 8 seconds before opening a file.

Observations:
- SumatraPDF, Notepad++ and Sublime Text show the "Open file" dialog _with a file preview pane_
- When I quickly select a .pdf document and quickly press the "Open" button, it looks like the _preview pane_ does not have enough time to preview the PDF content
- If I select a .pdf document and wait for several seconds, the _preview pane_ still does not show anything, but at some point it seem to change its background color from pure white to a little bit grayed white or something like that
- If I press the "Open" button after a .pdf document was selected for several seconds, I don't have the delay of 8 seconds after the "Open file" dialog is closed - instead, the document is opened instantly.

My conclusions:
- it looks like something is wrong with _PDF preview_ in my system.
- when I give _PDF preview_ enough time in the "Open file" dialog, there is no hang after the "Open file" dialog is closed; otherwise there is the hang.
- looks like when _PDF preview_ does not have enough time in the "Open file" dialog, it causes hanging by doing something in background when the "Open file" dialog has been closed.
- in any case, whether I give _PDF preview_ enough time in the "Open file" dialog or not, I never see any preview of the .pdf document content in the preview pane of the "Open file" dialog.

Even if it is the exact root cause, I still have no idea what can make _PDF preview_ to misbehave and what are the ways to fix that.
Could you suggest something?

**Comment by GitHubRulesOK** [comment]
My previewer plays up on occasion but thats because I oddly use the Acrobat one on this machime in preference to the Microsoft one and thus dont install the SumatraPDF one so installing SumatraPDF rather than use its previewer actually triggers off the conflicts between Acrobat and Microsoft, but it does not affect sumatraPDF loading and since Acrobat is so slow to load files now wonder if that a cause.

**Comment by kjk** [comment]
Not a SumatraPDF issue.

It could also be anti-virus program hogging the file.

There are programs that show which programs are accessing the file (e.g. https://learn.microsoft.com/en-us/sysinternals/downloads/procmon although not sure if it works on latest windows).

You can use such program to narrow down the processes that are accessing the file. Those are likely causing the problem.
