### ISSUE TITLE
Register for restart

### ISSUE THREAD

**Issue by miloush** [sumatrapdfreader/sumatrapdf#395]
It's not the first time I lost all my opened PDFs due to forced Windows Update restart. (I am not using tabs and the files were opened from internet.)

Could the reader perhaps register for application restart in these cases and restore the opened windows/tabs?

Related and probably prerequisite to #28, though without any concerns about the sessions management.

**Comment by smprather** [comment]
What is the status here? I always have a long list of pdf's open (manuals to different tools I support). And I too am hit by forced windows restarts when IT updates stuff. I need to re-open Sumatra and have it come up in its previous state. I just got hit by this again and went searching for a solution and wound up at #28 and then here. I see nothing in the options. I have the latest version. Thanks.

**Comment by smprather** [comment]
I have RestoreSession=true and RememberOpenedFiles=true.
