### ISSUE TITLE
Undesired opening of the last document viewed

### ISSUE THREAD

**Issue by Peter-202122** [sumatrapdfreader/sumatrapdf#3953]
Hello,

I recently updated from version 3.4.6 to 3.5.2 (64-bit). The described problem occurs only in the new version.  So it seems to me that it is an issue.

Here an example:
1. I open a document in Sumatra, called for example A.pdf (by clicking on A.pdf).
2. After reading it I close Sumatra by clicking the "X" in the right corner of the window. (**Not** the document itself!)
3. I open another document, e.g. B.pdf. Before is appears, for a short time (1 second or so) appears document A.pdf in the window of Sumatra (that means the last file I had used before closing Sumatra). Also I can see in the (Windows) taskbar **both** files. And indeed when clicking on "A.pdf" in the taskbar, it appears in Sumatra.

In order to avoid this, I could close every document separately before closing Sumatra itself. But this is cumbersome and was not necessary with the former version of Sumatra. 

The behaviour only occurs when in Settings -> Options I have checked the box "Remember opened Files". But unchecking this option is no (convincing) solution because in this case I also loose the list of "Frequently Read" documents and I would like to keep this list.

It would be fine if the behaviour could be re-established in the way it was in version 3.4.6. Thanks.

**Comment by GitHubRulesOK** [comment]
sounds like recently addressed issue https://github.com/sumatrapdfreader/sumatrapdf/issues/3923 so test out [pre-release](https://www.sumatrapdfreader.org/prerelease)

**Comment by Peter-202122** [comment]
@GitHubRulesOK
Thanks for pointing out the other thread and the pre-release (version 15920). 
I just tried it out. The issue remained (-> the last document reopens in the next session of Sumatra if I did not close the file manually).

**Comment by GitHubRulesOK** [comment]
Ahh that describes the newer "feature" historically close with one file then session started with no files the design was 2 or more HOWEVER there were many complaits so the newer SumatraPDF will reopen with the last file open when a new session starts and session remember is on.

**Comment by Peter-202122** [comment]
So it seems that what I regard as an issue is in reality a feature. ;-) But I think you showed me now the solution for my personal preferences.

If I understand you correctly, the behaviour is/was the following:
- In the past (e.g. version 3.4.6) **no** (open) file reopened in the next session of Sumatra.
- Currently (version 3.5.2) **two** such files reopen in the next session.
- In future versions **one** such file will reopen in the next session.

But the good news (for users like me) is that you wrote that such a re-opening will occur only when _"session remember is on"_. 

Obviously you refer to the entry "**RestoreSession = true**" in the settings-file (SumatraPDF-settings.txt).

So in order to achieve the same behaviour as it was in the past (= no file will reopen in the next session) I have to change this value to "**RestoreSession = false**". 

At least this is what I tried just a few moments ago and it seems to work. :-)

**Comment by tmssngr** [comment]
What about reopening the last documents only if SumatraPDF was started without file path?
