### ISSUE TITLE
From discussion "Lost all annotations"

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#3954]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/3935

<div type='discussions-op-text'>

<sup>Originally posted by **ledg555** December  5, 2023</sup>
Hi. I just wanted to ask: is there some shortcut to restore an original document or to suddenly delete all annotations? I was trying to save an annotation to the current document with the usual Ctrl+Shift+s but instead of s accidentally hit other key (I think w or e) and all my hundreds of annotations in a 700 pages book suddenly were gone.</div>

**Comment by GitHubRulesOK** [comment]
Whilst testing current pre -release I notice an oddity in the way SumatraPDF is writing trailers 
which would potentially produce lost annotations
here is same sample with SumatraPDF and MuPDF annotations not perfectly identical but close enough.

Whilst practically all readers will gloss over the transgression of inncorect start ref in simple case it will cause downstream losses as more and more startxref's are added 
[colours_decoded-mupdf (incremental).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13649610/colours_decoded-mupdf.incremental.pdf)

[colours_decodedSumatraPDF.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13649607/colours_decodedSumatraPDF.pdf)

**Comment by A-Infor** [comment]
There is really something happening on Sumatra v3.5.2 that makes it lose all annotations.
It happened to me and makes me very insecure to keep using the program.
My annotations are essential to the work I'm doing. I can't risk losing them.

**Comment by A-Infor** [comment]
Related to #3911

**Comment by kjk** [comment]
Does it still happen in pre-release? (https://www.sumatrapdfreader.org/prerelease)

We fixed at least one bug related to saving annotations: https://github.com/sumatrapdfreader/sumatrapdf/issues/3981

**Comment by A-Infor** [comment]
@kjk Hi. It is really good to know that the bug might already been fixed.
I'm testing the pre-release and I will comment later if it happens again.

**Comment by cascodoATX** [comment]
Still happening. Tried version 3.5.2 and version 3.5. Both have the same problem in Windows 10. I also tried saving with ctrl-shift-s and get same problem. And it also happens when I save in a different file.

**Comment by GitHubRulesOK** [comment]
@cascodoATX it camnnot be fixed in 3.5.# it was fixed as per above in 3.6. pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by kjk** [comment]
Closing as it was fixed in pre-release

**Comment by A-Infor** [comment]
@kjk Lost some annotations on v3.6.16022 64-bit after using CTRL+W to close another PDF file.

**Comment by GitHubRulesOK** [comment]
@A-Infor 
we are now at 3.6.16336/7
I dont have an old 16022 to test but  both a version before and after approx + - ###70 tested in 32 bit
closing one tab will even if double bounce the W, trigger a "do you wish to save annotations"

**Comment by kjk** [comment]
@A-Infor I need step-by-step instructions on how to reproduce the issue. This just isn't enough information.

**Comment by A-Infor** [comment]
@GitHubRulesOK I didn't mention double bouncing the CTRL+W.
I closed one tab and the previous one was shown.
The previous one then lost at least the not-yet-saved annotations.
