### ISSUE TITLE
Sumatra PDF v.3.0 reports itself as the latest version

### ISSUE THREAD

**Issue by mindstormer12** [sumatrapdfreader/sumatrapdf#396]
Sumatra PDF v.3.0 reports itself as the latest version (via Help > Check for updates) and there is no notification that an update is available elsewhere. The portable version of Sumatra PDF v.3.0 also has the same problem. Also, does Sumatra PDF notify its users of an available update automatically? 

I only found this issue because I was searching whether Sumatra PDF has the option to remember sessions.

**Comment by kjk** [comment]
Fixed, thanks.
