### ISSUE TITLE
64-bit version sets default install path to Program Files (x86)

### ISSUE THREAD

**Issue by tengwar** [sumatrapdfreader/sumatrapdf#397]
What happened:
I had a 32-bit 3.0 version installed and wanted to update to 64-bit 3.1.1. After downloading and launching the 64-bit installer the default install path was C:\Program Files (x86)\SumatraPDF. This would probably overwrite the old version, but it would also mean that 64-bit app would reside in a folder meant for 32-bit apps. Of course I can change the install path manually, but not all users look into the install options.

What I expected:
I expected the installer to either:
- remove old 32-bit version and have C:\Program Files\SumatraPDF as the default install path, or
- leave the old version alone and have C:\Program Files\SumatraPDF as the default install path.

**Comment by kjk** [comment]
Only if you upgrade from 32-bit version because we preserve the previous installation path (which could be a custom path chosen by the user). We don't have plans to change that. A fresh install would use the expected path.
