### ISSUE TITLE
How to make the scroll bar region adapt the dark theme ?

### ISSUE THREAD

**Issue by amatya-aditya** [sumatrapdfreader/sumatrapdf#3978]
I'm using 3.6.15927 pre-release version.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/63241408/c1b08b6b-94cf-4c8b-aecf-c70eb23a7258)

**Comment by GitHubRulesOK** [comment]
The Windows System interface manages Title bar and windows boundaries thus you can use system colours to allow the system to alter those. there are many examples shown from Windws XP or 7 screen views. but the most effective is use a 3rd party app as Microsoft Windows does not provide a simple means.

Here is a nice example from 2 days ago (https://github.com/sumatrapdfreader/sumatrapdf/issues/3973?notification_referrer_id=NT_kwDOAMKf4bM4ODQxMDAzMDY3OjEyNzU0OTEz#event-11330261198)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/28f875c6-0fac-492d-83a3-f364192125cf)

 wider discussion https://github.com/sumatrapdfreader/sumatrapdf/discussions/3839

Closing as System Colours is covered by open issue https://github.com/sumatrapdfreader/sumatrapdf/issues/3803
