### ISSUE TITLE
Improve rendering of very thin lines

### ISSUE THREAD

**Issue by jarnojarno** [sumatrapdfreader/sumatrapdf#398]
From saving Word 2010 .docx to PDF, my tables consisting out of 1 cell shows a thin 1px border:
[Bug.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/69578/Bug.pdf)

This is not being seen in other pdf-readers and sometimes disappears with zooming-actions. 
This is on Windows 10 with 3.1.1 64bit sumatra. Not shown earlier on my other laptop (win7 ultimate, maybey earlier sumatra version I think)

**Comment by jarnojarno** [comment]
I further investigated on this issue. It seems that with version 0.2-0.3 there's **no** thin line. Also with version 0.8 there's a thin line, but with MuPDF rendering switched off **no** thin line.

Also thin line in Firefox 44.02 (32-bit)
**no** thin line in Chrome 48.0.2564.116 m (64-bit).
[https://github.com/sumatrapdfreader/sumatrapdf/files/69578/Bug.pdf](url)
![bug thin line](https://cloud.githubusercontent.com/assets/5173930/13461815/1dfecd6a-e084-11e5-8c89-178dcf252832.png)

This is all on Win10 64-bit. On Win7 there's no issue.

**Comment by kjk** [comment]
Also see https://forum.sumatrapdfreader.org/t/it-is-very-hard-to-read-the-picture-with-this-software/83

**Comment by kjk** [comment]
Also seen in https://forum.sumatrapdfreader.org/t/almost-invisible-lines/192/1

**Comment by GitHubRulesOK** [comment]
@kjk this is a hard one to call it does NOT appear to be the issue that thin lines are too thin which has been improved 

Rather this is the opposite where a thin white boundary line is present that in some viewers is masked by thickening of adjoining fields.

As such I would say that SumatraPDF is behaving correctly in this case

**Comment by kjk** [comment]
Yeah, it seems to render the same in Chrome as in Sumatra.
