### ISSUE TITLE
Bug: annotations disappearing upon saving

### ISSUE THREAD

**Issue by hotwords123** [sumatrapdfreader/sumatrapdf#3981]
Sample PDF: [123.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13780141/123.pdf)

Steps to reproduce:

1. Open the file with SumatraPDF.
2. Add a text annotation anywhere, input anything, and click save.
3. Re-edit the annotation or create a new annotation, then click save.
4. At least one annotation disappears after saving.

The bug seems to appear only in versions 3.5 and later, but not in 3.4.6.

**Comment by hotwords123** [comment]
P.S. If I keep just the content up to the first `%%EOF`, there will be no errors.

**Comment by GitHubRulesOK** [comment]
The sample file is "dirty" it has many deleted and only partially purged entries.

SumatraMDF will not cleanup that combination (even if MuPDF could) as it works as a viewable PDF after a fashion.

Here is a clener copy which should behave correctly
[123 (cleaner).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13780282/123.cleaner.pdf)

**Comment by kjk** [comment]
mupdf 1.23 has the same problem.

It only happens for incremental saving. I'm tempted to not use incremental saving but then it'll take longer.

**Comment by kjk** [comment]
Reported to mupd: https://bugs.ghostscript.com/show_bug.cgi?id=707559
