### ISSUE TITLE
Ability to zoom in to any size using the touchpad/ touchscreen

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#3983]
Currently, the documents can be zoomed in only to some specific sizes, i.e. the zoom jumps from one size to another. Other PDF readers allow any amount of zoom (by using the pinch gesture on the touchpad).

This is especially useful when I want to take a screenshot for which I want to fit the desired portion on the screen and also ensure that it is large enough to produce a screenshot with good resolution.

So, please add the ability to zoom in and out to any size.

**Comment by misaz** [comment]
Try Menu > Zoom > Custom Zoom

![obrazek](https://github.com/sumatrapdfreader/sumatrapdf/assets/2937706/7ed59e0d-c15b-45c2-8d15-3d9a763a291a)

**Comment by kjk** [comment]
It already works this way when using touchscreen.

**Comment by user1823** [comment]
> It already works this way when using touchscreen.

Ok, but I don't have the hardware to test that.

It doesn't work that way using the touchpad and I thought that it would behave the same on a touchscreen because both use the pinch gesture.

**Comment by kjk** [comment]
Zoom by touch should be continuous in [pre-release](https://www.sumatrapdfreader.org/prerelease) 16073 or later.
