### ISSUE TITLE
Ability to change font, font-size in EPUB files

### ISSUE THREAD

**Issue by planetkalpesh** [sumatrapdfreader/sumatrapdf#3989]
MuPDF has option to change font, font-size in EPUB files by adding custom CSS files. Then can you add the feature in SumatraPDF to change font, font-size in EPUB files

**Comment by GitHubRulesOK** [comment]
related to https://github.com/sumatrapdfreader/sumatrapdf/issues?page=2&q=is%3Aopen+is%3Aissue+label%3Aebook in particular [#121](https://github.com/sumatrapdfreader/sumatrapdf/issues/121) https://github.com/sumatrapdfreader/sumatrapdf/issues/358 https://github.com/sumatrapdfreader/sumatrapdf/issues/944
 duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3138 etc.
