### ISSUE TITLE
Latex multiple integrals rendering issue

### ISSUE THREAD

**Issue by JsonLinesCode** [sumatrapdfreader/sumatrapdf#3991]
I noticed multiple latex integrals, cyclic or not are not rendered by sumatrapdf (`\iint`, `\iiint` and `\oint`).
I've linked some examples with Adobe comparison.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/45465075/ae1c2803-fa6e-42fb-93da-9858e9afdab2)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/45465075/7fb97e25-b9a8-4fe3-a402-2afed0361b0b)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/45465075/c9192a52-a033-4304-bfae-b3bf29fff85e)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/45465075/4b031bfc-888f-436e-8686-01b55d7217ee)

**Comment by kjk** [comment]
can't do anything without example PDF.

Most likely incorrect PDF generation (like not embedding fonts).

See logs (`Ctrl + K` for command palette, `Show log` command) to see if we complain about the PDF).
