### ISSUE TITLE
Problem opening PDF with use tabs option deselected

### ISSUE THREAD

**Issue by leonardomanero56** [sumatrapdfreader/sumatrapdf#3992]
SumatraPDF-3.5.1-64.exe portable
 sumatra options : use tabs unchecked
              - always opens another PDF in addition to the selected one

**Comment by GitHubRulesOK** [comment]
that is newer behaviour with restore sessions (remember opened files) true as now remembers last file when closed  (previously 2 files had to be active to be restored on opening.)

however current behaviours are determined by pre-release version so you should be using that for current issues, likely it is somewhat similar.

**Comment by kjk** [comment]
most likely fixe din pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by leonardomanero56** [comment]
tried prerelease but when I open a file it always opens 2 files.
The 3.4.6.64-bit version was fine

**Comment by kjk** [comment]
It's probably a result of a change to restore a session with 1 file.

In the past we used not to.

Then someone complained so we changed it to restore one-file sessions.

So if you close sumatra while it shows a file (as opposed to closing a file and the closing empty sumatra) then it will restore that single file (i.e. re-open the file).

If you double-click on a file we still restore the session i.e. re-open the file.

If you set `RestoreSession =false` advanced setting then this should match your expectations (but then it won't be remembering any sessions).

Maybe I can tweak it (again) for single-file restore in non-tab mode.

**Comment by exonie** [comment]
"Use tabs" unchecked, RestoreSession = true - does not behave well. (SumatraPDF 3.5.2 64bit on Windows 10)

Scenario 1 (bug):
If I have 2 open files and open a third - it opens again the 2 files and then opens the new file so I end up with 5 files open (two duplicates). Also, choosing File->Exit closed the last 3 files with two remaining.

Scenario 2:
If I close **all** program instances and then open a new file - I get two files opened, the requested one and the last closed one. This is the supposed behaviour as I understand but it's still very counter intuitive.

Maybe with these settings Exit should close all program instances and perhaps be renamed to End Session (or Exit All) and only then the session should be saved and subsequently restored? Thus all open files will be considered one session and End Session will close that session.

**Comment by exonie** [comment]
Alright, just checked it - it's fixed in the prerelease.
