### ISSUE TITLE
scrollbar behaves incorrectly, indicates PDF has only 1 page, but it has 15 pages

### ISSUE THREAD

**Issue by EugenNY** [sumatrapdfreader/sumatrapdf#3993]
the attached sample PDF has 15 standard pages. but when you view the file, the scrollbar indicates there is only 1 page. And using the scrollbar (not the mouse-wheel), you can only scroll within that 1 page and not scroll to the next/previous page. with PgUp/PgDn and the mouse wheel you can easily scroll to any page as usual. this appears to be a bug.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/7329265/62fea257-3ef2-4451-b636-96e7211a20df)

[231218_Leitfaden über Vormerkung, Platzvergabe und Aufnahme..pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/13805696/231218_Leitfaden.uber.Vormerkung.Platzvergabe.und.Aufnahme.pdf)

**Comment by GitHubRulesOK** [comment]
SumatraPDF uses scrollbars different to Acrobat as its not an Acrobat clone.

Single page fully in page has NO SCROLLBARS
Single Page within a page has scrollbars as required either horizontal or vertical or both
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2b028dcc-d03d-4a02-9a91-9e1e9f12029e)
For whole file in continuous mode the scroll bars will show the whole file
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/054fa661-f999-4f64-9f57-fde16d31bff2)

Closing as has always been that way. (press C to switch between modes or use the icons.)

**Comment by EugenNY** [comment]
apologies for this misunderstanding on my side. and thanks for taking the time to explain it! 👍
