### ISSUE TITLE
Options are not saved

### ISSUE THREAD

**Issue by lbltls** [sumatrapdfreader/sumatrapdf#3999]
**SumatraPDF version**

Version 3.5.2 64-bit on Windows 10

**Describe the bug**

Options are not saved on my PC in the current version of SumatraPDF (3.5.2 64-bit).

**To Reproduce**

1. Select "Settings → Options" in the menu.
2. Select e.g. next to "Standard magnification" the option "Fit to window width" and confirm with "OK".
3. Close SumatraPDF.

**Expected behavior**

The next time I launch SumatraPDF, the previously changed option should be applied. However, when I select "Settings → Options", the first option "Fit to page" is displayed next to "Standard magnification".

**Comment by GitHubRulesOK** [comment]
the entry should be `Default Zoom:`
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f2d6d065-e07f-495e-b578-3cb4aa6cc725)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c01e6d7b-5c37-4f03-8d99-4f855e77222e)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e1205ab4-040c-4481-bd0e-c8a68179bf6a)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/95bd59f5-c8d2-4602-8de1-22a0239ea2aa)

**Comment by lbltls** [comment]
Yes, you're right, it's actually "Default Zoom" (not "Standard magnification"). The language of my SumatraPDF is German and it was probably a translation error of DeepL.com ;-)

Anyway, I uninstalled SumatraPDF completely and reinstalled it, and fortunately the error no longer occurred. :-)
