### ISSUE TITLE
Add /analyze support in appveyor

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#4]
Involves:
- [ ] add another build step that runs with /analyze and outputs results to a file
- [ ] run a python script to post-process the output file into a more human-readable form and save to a file (text? html?). This code is already in buildbot.py, just needs to be extracted
- [ ] add the generated file as artifact so that it gets archived

**Comment by GitHubRulesOK** [comment]
@kjk 
above may need revision in light of more recent changes ?

**Comment by kjk** [comment]
Yeah, abandoning for now.
