### ISSUE TITLE
Please, let's create a possibiluty of saving "session" or "working space" for multiworking using of the SumatraPDF. In other words, please add multi-desktop framework in Sumatra.

### ISSUE THREAD

**Issue by nucleognom** [sumatrapdfreader/sumatrapdf#400]
Thanks for useful program!
I'm very pleasured by using Sumatra PDF and I want to ask you for add very important feature for me.
Please, let's create a possibility of saving "session" or "working space" for multi working using of the Sumatra PDF. In other words, please, add a multi-desktop frameworks in Sumatra, with possibility of saving them (in its formation, such as "sumatra session XML file"). Not as folder or archive, but as linking file.
Thanks for useful program!

**Comment by Remiol** [comment]
I would like to see the same thing.

**Comment by kjk** [comment]
no plans to add this
