### ISSUE TITLE
HighlightColor doesn't work

### ISSUE THREAD

**Issue by Aliaksandr3by** [sumatrapdfreader/sumatrapdf#4005]
maybe I don't know how it is working.
but to change this do nothing.

ForwardSearch [
	HighlightOffset = 0
	HighlightWidth = 15
	HighlightColor = #6D1FB0
	HighlightPermanent = true
]

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/2f9a6ca9-66ee-461e-b947-db7f90cebf06)

https://www.sumatrapdfreader.org/settings/settings3-6.html
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/11432724/fcaffef9-944b-4f6a-8f74-8bec4e46296c)

**Comment by GitHubRulesOK** [comment]
it needs a synctex file

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/a6e190a5-d40b-4d90-9538-628decf9bb51)

**Comment by Aliaksandr3by** [comment]
Sorry, I don't understand what exactly needed

**Comment by Aliaksandr3by** [comment]
is  it not have a simple solution ?

**Comment by GitHubRulesOK** [comment]
You can emulate your own system it is well documented last century but fairly cryptic here is the vbs I used to highlight the text file but thats tip of an iceburg

in setting.txt  
`InverseSearchCmdLine = cscript C:\Users\ path to \notepad.vbs "%f" %l`   
notepad.vbs    
```
' Usage:- in a Latex PDF viewer add this Reverse command or equivalent
' cscript C:\Path to\notepad.vbs "%f" %l
' where %f will be the file.tex and %l is the line number
' invokes 'WScript.ScriptFullName WScript.Arguments(0) WScript.Arguments(1)

Dim inShell
Dim Arguments()
SET inShell = WScript.CreateObject("WScript.Shell")

inShell.Run ("%windir%\notepad.exe " & WScript.Arguments(0))

' add a delay for file opening
WScript.Sleep(1000)

' % is alt key and + is shift following REQUIRES NOTEPAD IS CURRENTLY Format "Word Wrap" OFF (can be set in registry)
inShell.SendKeys ("%EG" & WScript.Arguments(1) & "{enter}+{end}")
```
the synctex is the key between the 2 as it acts like a pdf index   
start of file sync.synctex  
```
SyncTeX Version:1
Input:1:./sync.tex
Input:2:/usr/local/texlive/2017/texmf-dist/tex/latex/base/article.cls
Input:3:/usr/local/texlive/2017/texmf-dist/tex/latex/base/size10.clo
Output:pdf
Magnification:1000
Unit:1
X Offset:0
Y Offset:0
Content:
!305
{1
[1,25:4736286,46220574:26673152,41484288,0
[1,25:8799518,46220574:22609920,40435712,0
...
...
!4406
}1
Input:4:/Volumes/Users/Documents/synctex/synctex test files/texworks/./sync.aux
!89
Postamble:
Count:126
!25
Post scriptum:
```
About 200 lines to simply link to a handfull !! thats why they are normally compressed.gz
