### ISSUE TITLE
Cancel the influence of theme on background color

### ISSUE THREAD

**Issue by luyuduan** [sumatrapdfreader/sumatrapdf#4006]
I want to have this background color under the dark/darker theme, but currently it can only work under the bright theme
I tried changing the configuration file and flipping the color, but it didn't work
Does this association need to be closed or customizable?

The background color configuration is as follows, only changing the theme
`	BackgroundColor = #d2e3c7`

Light theme
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/37297576/206bbc2c-9863-4ccd-affa-533a2961713a)

Dark theme
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/37297576/cf82c01d-7261-44a2-a75f-e695ead302e6)

Darker theme
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/37297576/022a5468-297e-4272-92c8-0acf5e271da5)

SumatraPDF v3.5.2 64-bit Windows

**Comment by luyuduan** [comment]
In other words, background color configuration does not take effect under dark themes

**Comment by GitHubRulesOK** [comment]
BackgroundColor = #d2e3c7 should be working in a current pre-release
except the current release does not invert images when opened on their own, which was the whole reason for inversion !!
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/ea0ec73b-34bd-4234-abb3-5581722cf768)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/56ee169a-8fb6-47b6-a905-e9b1711ea8fe)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/ee46b0df-b403-4f23-9f1d-4801e01295b9)

**Comment by luyuduan** [comment]
The pre-release has been installed, and switching themes does not affect the background color, which is done well
