### ISSUE TITLE
Commit problems

### ISSUE THREAD

**Issue by Neustradamus** [sumatrapdfreader/sumatrapdf#4007]
Dear @sumatrapdfreader team, @kjk,

In first, I wish you a Happy New Year 2024!

Several commits are not from @kjk but "Krzysztof Kowalczyk":
- https://github.com/sumatrapdfreader/sumatrapdf/commits/master/

I think that you have a setting problem.

Can you look to solve it?

Thanks in advance.

**Comment by kjk** [comment]
Thanks for letting me know, should be fixed now.
