### ISSUE TITLE
About the Frequently Read preview view

### ISSUE THREAD

**Issue by LinJinkang** [sumatrapdfreader/sumatrapdf#4017]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/54579927/9596d0fd-d61d-42eb-8d79-230bad38de05)

**Comment by GitHubRulesOK** [comment]
BOTH are wrong but this is not an issue it hhas always been that the preview images will be scaled to 212px wide without any other change in pixel ratio and as high as is possible to a MAX of 150 pixels so as to form a landscape screen overview starting with top of page 0 (cover) or equivalent.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/711abf3d-9272-42c3-829d-f59ab2f22e44)

**Comment by GitHubRulesOK** [comment]
@kjk 
closed issue as not a fault if you think there is mileage in re-open as an "Enhancement" (note we dont have that tag for separating out feature requests) please feel free
