### ISSUE TITLE
needed: command line args to open the doc at a given page or with given string to search in

### ISSUE THREAD

**Issue by KorzunYuri** [sumatrapdfreader/sumatrapdf#402]
Hi!
Is it already possible, or will it be possible in the future to launch sumatraPDF with some command line args such as "open doc at page N" and "open doc, start searching for <string>"? It would be extremely helpful, not only for me I guess. 
For example, Adobe Acrobat Reader has these features, but there are problem when you need to search cyrillic text. If Sumatra can handle it I will forget about any other readers :)
Anyway, thank you guys for your job.
Best Regards, 
Yuri

**Comment by kjk** [comment]
You can already open at a given page. We don't have plans to automatically start a search. See http://www.sumatrapdfreader.org/manual.html and https://github.com/sumatrapdfreader/sumatrapdf/wiki/Command-line-arguments for all command-line arguments.

**Comment by GitHubRulesOK** [comment]
https://github.com/sumatrapdfreader/sumatrapdf/issues/1182#issuecomment-786980030
