### ISSUE TITLE
[Request] Change SumatraPDF-settings.txt to JSON format.

### ISSUE THREAD

**Issue by milnak** [sumatrapdfreader/sumatrapdf#4028]
Maybe I'm the only one who cares, but it would be nice, instead of a custom format if SumatraPDF-settings.txt used JSON, e.g.

```JSON
"settings": {
  "Theme": "Light",
  "FixedPageUI": {
	"TextColor": "#000000",
	"BackgroundColor": "#ffffff"
  }
}
```

Would make it easier to view/edit in an external editor.

**Comment by meteorquake** [comment]
I've not noticed an issue I suppose because the settings are only a few, but Visual Basic and CSS both seem to colourise it quite well (on Notepad2), I'm sure there are others, though the choice needs to be manually chosen.

**Comment by Andy2No** [comment]
Personally, I prefer having them in plain text, in a .txt file.

**Comment by milnak** [comment]
Json *is* plain text, it's just structured in a standard format.

**Comment by kjk** [comment]
Current format is much easier for humans to edit. Also not going to rewrite working code.
