### ISSUE TITLE
[Request] File state settings/cache should be in separate file, outside of SumatraPDF-settings.txt

### ISSUE THREAD

**Issue by milnak** [sumatrapdfreader/sumatrapdf#4029]
I'm probably the only one who cares about this, but it would be nice to have sumatra global settings in SumatraPDF-settings.txt and the file state settings/cache in a separate file, e.g. SumatraPDF-file-settings.txt.  Doing this would allow the settings file to be shared/copied without the "bloat" of the per-file cache.

**Comment by kjk** [comment]
It's a reasonable request but the benefit doesn't outweigh the cost of making the change.
