### ISSUE TITLE
Navigation link integrated in file

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#403]
Some educational e-book that really helpful by providing a features that allow user to navigate through pages using the navigation link text. This text usually appear for diagrams, index, Chapter content and Questions . This allow some students like me to move from one page to another by clicking only.
however this features is not available in sumatrapdfreader. I'm really seek for this function. Adobe reader and microsoft integrated windows 8 reader have this feature.
Please, I want to stick sumatra reader and have this feature.

**Comment by kjk** [comment]
Please provide a sample file that shows this problem. Can't do anything without it.

**Comment by masterdevirus** [comment]
Here is one example. 
https://drive.google.com/file/d/0B_pXJ6k3WuovcElnaTNFcEUycUE/view?usp=sharing

**Comment by GitHubRulesOK** [comment]
@kjk 
The sample is no longer available, unless you have a copy off-line that shows problems, then I suggest the current version appears to work with contents + internal and external links satisfactorily, so this issue can be closed ?
