### ISSUE TITLE
Add favorites button to the toolbar

### ISSUE THREAD

**Issue by 1Renus** [sumatrapdfreader/sumatrapdf#4037]
I have disabled the "remember opened files" and "remember these settings for each document" options because I don't want to save settings for every document I open. Instead, I always use the "add page to favorites" in the favorites menu. However, this is a bit longer. It would be better if you could add a short method: add a button to the toolbar. When you click the button, it saves the current page number and its settings. Then, when you go to another page and click the button again, it overrides the saved page number. Also, please pin a sticker on the saved page.

**Comment by GitHubRulesOK** [comment]
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/e1a3deae-b001-4d35-b7a6-de7255de54a3)

unsure if that is changeable to you own choice of key press shortcuts? but if so it then would be one key. 

The command is additive not overwrite but it is easy to delete via right click the entry.

Unclear what you mean about sticker as that would be annotation with its own go to dialog
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/875953be-58af-4445-a30d-d05cadef0395)

**Comment by 1Renus** [comment]
Thank you for taking your time to answer my question. I don't want to change the original PDF by adding annotations; I only want to save the page number and settings when I click on "add page to favorites." When I click again on "add page to favorites," it should override the previous number. I mean something like a sticker, as shown in this screenshot.
![imgonline-com-ua-dexifEvWqr6OLWVdI](https://github.com/sumatrapdfreader/sumatrapdf/assets/96239231/c706d2f0-4928-4f11-9fa5-40a1c958e6d0)

**Comment by GitHubRulesOK** [comment]
There was a third party AHK application that did that some time ago but only worked in pre-release at the time. Possibly similar may be achievable now in any release (or any app including notepad) but it was dependent on features that no longer exist and also have been replaced with better. So that app would need a fresh recent releases approach.

**Comment by kjk** [comment]
Not adding more stuff to the toolbar.

It has `Ctrl + b` shortcut and you can customize it (https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts) for `CmdFavoriteAdd`
