### ISSUE TITLE
Single document usage

### ISSUE THREAD

**Issue by anatoliy-savchak** [sumatrapdfreader/sumatrapdf#4038]
**Is your feature request related to a problem? Please describe.**
I need following:

1. Ability to open SumatraPDF always empty if not via Explorer.
2. Along with that: I want to pick file from Frequently read.
3. No tabs for me.

**Describe the solution you'd like**
Option "Remember opened files" prior to 4.5.* allowed above behavior.

But now it either:
1. Opens last opened file.
2. Opens empty app but no history in Files menu or awesome Frequently read section.

I think there should be two options:
1. Remember opened files - to open last files when app starts.
2. Remember history - whether to display history in Files or Frequently read section.

**Comment by GitHubRulesOK** [comment]
try this combination to only remember filenames not active files
```
RememberOpenedFiles = true
RememberStatePerDocument = false
RestoreSession = false
```

**Comment by anatoliy-savchak** [comment]
It works, thanks @GitHubRulesOK !! :)
