### ISSUE TITLE
Incorrect display of text, gray shading around characters.

### ISSUE THREAD

**Issue by OlieOlin** [sumatrapdfreader/sumatrapdf#404]
At the bottom of this pdf, the text has gray shadowing around the characters.  It displays the same on the portable version also.  It displays fine on other readers.
[GreyShadedText.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/72897/GreyShadedText.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk this example of a poorly scanned file is rendered in a similar fashion in either acrobat or recent builds of SumatraPDF

![untitled](https://user-images.githubusercontent.com/12754913/69364893-1fb27d00-0c8b-11ea-83cd-6287e1a65607.png)

**Comment by kjk** [comment]
Agreed. We render about the same way as Chrome.
