### ISSUE TITLE
[Feature request] "Traditional East Asian Book/Japanese Manga View" feature designed for right-to-left reading

### ISSUE THREAD

**Issue by ryanlo713** [sumatrapdfreader/sumatrapdf#4047]
### Is your feature request related to a problem? Please describe.
I, as user of the software, face difficulty in reading traditional East Asian books or Japanese manga, as the current "Book View" feature only allows reading from left to right, which is inconvenient for books that are traditionally read from right to left.

### Describe the solution you'd like
I would like to request the addition of a "Traditional East Asian Book View" feature that allows users to read books from right to left, accommodating the reading style of traditional East Asian books and Japanese manga.

### Additional context
For example, traditional East Asian books and Japanese manga are typically read from right to left, and this reading style is the norm for these publications. The current "Book View" feature, which is designed for left-to-right reading, creates a significant inconvenience for users who want to read these types of books.

This is an example of Japanese manga reading steps

![An example of Japanese manga reading steps](https://github.com/sumatrapdfreader/sumatrapdf/assets/12672523/4475de9f-31cd-4c81-bb4e-7a79a23b4a9e)

This reading style is used because East Asian traditionally uses vertical writing mode. For more details, see [Horizontal and vertical writing in East Asian scripts - Wikipedia](https://en.wikipedia.org/wiki/Horizontal_and_vertical_writing_in_East_Asian_scripts)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12672523/885080fb-8f1e-420c-b3f7-6509c1b077ca)

Here is an illustration. The orange line indicates the reading direction of vertical text. The read line indicates the reading direction of pages.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12672523/aa9b3236-52ac-4a10-ad5e-90960fa44696)

Note that "Facing" View has similar problems.

**Comment by GitHubRulesOK** [comment]
Modes can be set 4 ways Facing or Book (Default) & Manga ON or OFF (default)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4ee2e51d-5503-4a44-8941-65ed68027b3d)
