### ISSUE TITLE
A "clear frequently read" button

### ISSUE THREAD

**Issue by colejohnson66** [sumatrapdfreader/sumatrapdf#4048]
**Is your feature request related to a problem? Please describe.**
Commonly, I'll use the "frequently read" view to open up... frequently read documents. However, just like my browser history, I want to clear out the list from time to time.

**Describe the solution you'd like**
A button, possibly next to "hide frequently read" that would just clear the list.

**Describe alternatives you've considered**
Currently, there are two options: (1) delete the history one-by-one (right click &gt; remove from history), or (2) opening the "advanced settings" and blanking the `FileStates` array.

**Additional context**
N/A

**Comment by GitHubRulesOK** [comment]
in standard options simply toggle remember files it will surprisingly wipe almost all history you want to keep !!
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d7eead18-1851-4530-bfdf-e47e7fab34b5)

**Comment by colejohnson66** [comment]
Yes, that option exists, but I don't want to turn off history. I just want to clear it.

**Comment by GitHubRulesOK** [comment]
Toggle means set it of and on again it is surprising how many people accidentally wipe history by playing and not realising it is instant (or it was ?)

**Comment by kjk** [comment]
In latest version you can use Command Palette (`Ctrl + K`) and `Clear History` command. See https://www.sumatrapdfreader.org/docs/Commands

We will not add buttons for infrequently used functionality, only command palette commands.
