### ISSUE TITLE
installing 64 bit ver. on installed 32 bit ver.

### ISSUE THREAD

**Issue by jmb-kz** [sumatrapdfreader/sumatrapdf#405]
i have 32 version of sumatra installed. i try install 64 bit version on my pc, so path default is "C:\Program Files (x86)\SumatraPDF" like it is installing 32 bit. so u need add check about installing different 32 and 64 version. my windows is 7 pro 64bit and windows 7 corp 64 bit. all with last updates.
u could send advice message about u have other bit installed and uninstall other one before installing new. or could begin uninstall previous other bit version before installing other bit version, which i prefer.

![1](https://cloud.githubusercontent.com/assets/4984048/12013810/520f8054-ad49-11e5-8a02-0a24497a8f76.png)
![2](https://cloud.githubusercontent.com/assets/4984048/12013811/52587890-ad49-11e5-8c50-6f16516d5dab.png)

**Comment by jmb-kz** [comment]
or send advice message about u have other bit installed. or could begin uninstall previous other bit version before installing other bit version, which i prefer.

**Comment by kjk** [comment]
Not worth fixing.
