### ISSUE TITLE
"X" in close dialog "unsaved annotations" cancels the close process instead of closing and loosing all annotations

### ISSUE THREAD

**Issue by gentlepumpkin** [sumatrapdfreader/sumatrapdf#4058]
Situation
I made many annotations in a document. Accidently click "X" (Close Button). SumatraPDF asks "you have unsaved annotations". Intuitively, I click "X" to cancel the closing process. Instead SumatraPDF closes and my annotations are gone.

**Describe the solution you'd like**
Clicking on "X" in the "Unsaved annotations" windows returns to the document instead of closing it.

**Describe alternatives you've considered**
Add a 4th button saying "Cancel". Or press "ESC" to return to the document.

**Additional context**
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/55233349/e8e5acd3-ce48-4169-8929-74411581d96b)

PS: SumatraPDF is amazing, thank everyone who contributed!

**Comment by kjk** [comment]
It already works this way in latest pre-release https://www.sumatrapdfreader.org/prerelease
