### ISSUE TITLE
Sumarta can't read the file it previously could

### ISSUE THREAD

**Issue by PixelArt77** [sumatrapdfreader/sumatrapdf#4059]
SumatraPDF 
- Version 3.5.2, 64-bit

The text is written with Calibri. Sumatra used to open it before but now it just shows blank page or just the numbers. For some reason it doesn't recognize the letters anymore. The text is written in Georgian and maybe that is a problem, but until today it worked just fine 

![Screenshot](https://github.com/sumatrapdfreader/sumatrapdf/assets/158767898/94a2d43c-97db-490c-ba88-eaa09e6f2de5)

**Comment by GitHubRulesOK** [comment]
without a fill it is hard to guess but on the basis you have not changed SumatraPDF from before, then possibly MuPDF engine was using a substitute font which is no longer accessible, but you would need to remember what may have impacted windows\fonts accessibility

**Comment by kjk** [comment]
Can't do anything without access to test file as per https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports

**Comment by PixelArt77** [comment]
Hi, thank you for your answers. Every version of Sumatra before 3.5 can open the file just fine. 3.5 and others that were released after just don't work

**Comment by kjk** [comment]
Can't do anything without test file.

**Comment by PixelArt77** [comment]
I sent it to you via email. Thank you

**Comment by kjk** [comment]
I didn't receive anything.

**Comment by PixelArt77** [comment]
Sent it from my outlook mail

**Comment by kjk** [comment]
Got it, thanks. It is indeed misrendered.

**Comment by kjk** [comment]
mupdf-1.23 shows it so most likely a missing font issue. Can't tell what language is that.

**Comment by kjk** [comment]
Most likely we're missing font for script `UCDN_SCRIPT_GEORGIAN`, which is `Noto Serif Georgian`.

**Comment by PixelArt77** [comment]
Hi, 

I still have this problem. Should I do something with the properties or settings?

**Comment by kjk** [comment]
The fix should be available in latest pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by PixelArt77** [comment]
It works, thank youu
