### ISSUE TITLE
Add ability to display 'Home' screen with frequently read/pinned files

### ISSUE THREAD

**Issue by gmaresca** [sumatrapdfreader/sumatrapdf#406]
Ability to visualize the initial screen with thumbnails of pinned/recently opened documents when multiple documents are already opened.

**Comment by anzi** [comment]
add more items to 3 types of lists (
"Pinned to read" ; "Last read" ; "Frequently read" (with count / date)
) - now stores 10, wish it occupy all free space and be customisable (
choosable 
history form: lis / thumbnails
and to store or not thumbnails and how many
)

**Comment by weitzhandler** [comment]
Related #993.

**Comment by GitHubRulesOK** [comment]
#372 suggested it be simply accessible as a tab like any other

**Comment by xiao1201** [comment]
Hello is this fr available now? it is a quite common habit that ppl open frequent files from start page and when the file is opened as a new tab, the start page remains unclosed. I do see a lot of related fr about this but the content are all "related to this, relatedt to that, etc" and I dont see how to solve this. Thanks.

**Comment by GitHubRulesOK** [comment]
@xiao1201  I have seen many modifications to the front page by others (usually Chinese copies) where the _programmers_ want the front page for their own use, however I dont think any have changed in it the way that its requested here.

**Comment by kjk** [comment]
Same as #2134
