### ISSUE TITLE
Odd situation of unable to remove dead entry from home screen

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4066]
**SumatraPDF version**
- Version  pre-release

**Describe the bug**
Unknown how but managed at some time to loose a filename in settings, the effect is a dead preview in Home screen 

**Expected behavior**
As such a right click does not, per expectation, allow me to remove the dead entry. 

**File that reproduces the problem**
N/A is a null

**Screenshots**
see third entry
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d758c93c-6bb7-4176-8878-2783687be96b)

**Additional context**
clearly I could simply delete the entry but simpler expectation was to clear it from home screen.

**Comment by kjk** [comment]
Lots of things will break if settings file is manually corrupted in some way. There's no way to prevent all of them so I won't try to prevent any of them.
