### ISSUE TITLE
Advanced Options opens txt in notepad instead of default txt reader

### ISSUE THREAD

**Issue by NooneAtAll3** [sumatrapdfreader/sumatrapdf#4069]
**SumatraPDF version**
- Version 3.5.1 (at least beginning of settings.txt directs to settings3-5-1.html, although Check_for_Update returns "last version")

**Describe the bug**
"Advanced Options" button 

**To Reproduce**
1. Change windows' "default open with" program for txt files away from notepad (in file explorer right click on txt -> "open with" -> "choose different app" -> select something and tick off "use as default")
2. In Sumatra open Settings->Advanced Options

**Expected behavior**
settings.txt being opened with default txt program of the system, as defined by the system.

**Additional context**
I recently updated from 3.4.(smth) that opened settings.txt with gedit I installed on windows and set as default. So this change was immediately noticeable.
Notepad even managed to cache said file on reopen, causing me almost to report "a setting changes when you edit something else"

**Comment by GitHubRulesOK** [comment]
HMM I have always advocated ONLY use notepad as the Windows inbuilt  plain text editor not Write or Wordpad or MSWord VSCode etc, 
However recent versions look for "supported" installed editor so some will be used for advanced options in preference to the Notepad editor. which is last on the list that starts here [static TextEditor editorRules[] = {](https://github.com/sumatrapdfreader/sumatrapdf/blob/7d2e69da4c1a661eef5126981c803072f7ac8f15/src/AppTools.cpp#L148)

**Comment by kjk** [comment]
This is fixed in pre-release https://www.sumatrapdfreader.org/prerelease
