### ISSUE TITLE
Launching Sumatra from a service

### ISSUE THREAD

**Issue by colinmollenhour** [sumatrapdfreader/sumatrapdf#407]
Printing from the command line works great, but unfortunately I am not able to get it to print from a service. The service is written in node.js and I have created a simplified version of it for testing.

Note, I have been able to print using a node-based service before with GhostScript and GSPrint, but as you know SumatraPDF is much better and it supports selecting the printer tray so I really need to use it instead.

test.js:
```javascript
var sumatrapdf_path = 'SumatraPDF.exe';
var args = ['-print-to', 'EPSON NX410 Series', '-silent', 'test.pdf']

var server = require('http').createServer(requestHandler).listen(8000);

function requestHandler(req, res) {
  require('child_process').execFile(sumatrapdf_path, args, {cwd: process.cwd()}, function(err, stdout, stderr){
    if (err) {
      res.end('ERROR: '+err.message);
    } else {
      res.end('success');
    }
  });
}
```

Install node.js (any version should work).
Download nssm.exe (http://nssm.cc/download), SumatraPDF.exe, the above test.js and a test.pdf into a directory.
Create a service using nssm:

    > nssm.exe install SumatraTest "C:\Program Files\nodejs\node.exe" "<PATH_TO_TEST_DIRECTORY>\test.js"

Change the service to run as an admin user (this was required for Ghostscript too, have never found a way around it but have tried for hours)

    > sc config SumatraTest obj= ".\<USERNAME>" password= "<PASSWORD>"

Start the service:

    > net start SumatraTest

(you can cleanup the service using "sc delete SumatraTest")

Now assuming it started without error and node.exe is running, visit http://localhost:8000/ to trigger the print job to occur. On my system the SumatraPDF.exe just hangs indefinitely when run by the service, but prints instantly when run directly on the command line.

If you can spare some time to investigate I would really appreciate it. SumatraPDF is by far the lightest and most elegant PDF reader with good command line options I have found and I have searched a lot and this is the last issue blocking me from using it. Thanks in advance!!

**Comment by kjk** [comment]
I'm not surprised it doesn't work. Services have a number of restrictions. Unfortunately I don't have time to investigate this.

**Comment by colinmollenhour** [comment]
Ok, thanks Krzysztof.

**Comment by theinventor** [comment]
@colinmollenhour did you end up solving this? We have the same need..

**Comment by colinmollenhour** [comment]
I guess you could say I did.. My test printer was an Epson and I think Epson's bloated drivers with the pop up GUI was the main issue. I actually got it to work using other printer drivers. I don't think there were any other special steps necessary to get it to work, just stay away from Epson.
