### ISSUE TITLE
SumatraPDF crashed loading this specific file

### ISSUE THREAD

**Issue by McAnndra** [sumatrapdfreader/sumatrapdf#4071]
**SumatraPDF version**
- Version 3.5.2 64Bit

**Describe the bug**
SumatraPDF crashes while trying to load this specific file. It works properly with all other epub files I used up til now.

**To Reproduce**
1. double click the file
2. read the crash message
3. click "aboard"
4. read crash report file

**Expected behavior**
I expected to read the ebook.

**File that reproduces the problem**
is attached already

**Screenshots**
I don't think this is necessary

**Additional context**
at first I had a slightly older Version of sumatraPDF (1 or 2 versions behind), so I updated the program an tried the same file anew - with same result.
On an older pc i have a much older version of sumatraPDF (sinde I don't use this machine often and it is not being used for to read books, so there is no need to be up-to-date) Version v3.1.1 64Bit - and I'm very confused since with this version the file can be read properly (not very properly, since there are lots of characters not being displayed correctly - see in "Fehler.jpg" where the square should be a "-" as I saw in the xhtml file. But this version was able to display the epub file without crashing.

https://gist.github.com/McAnndra/7fc8021bc845c4b052cf059e3679cecc
[Maschinenmenschen.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/14223131/Maschinenmenschen.zip)
![Fehler](https://github.com/sumatrapdfreader/sumatrapdf/assets/159554600/32940fe6-8171-4829-a48c-03e731cb9bfa)

**Comment by kjk** [comment]
The attached crash report is from 3.4.6 and I confirmed it crashes there.

It doesn't crash in 3.5.2 or pre-release so has been fixed.

**Comment by McAnndra** [comment]
thank you - this seems to be fixed
