### ISSUE TITLE
Splitter leaves "ghost" versions behind when dragging

### ISSUE THREAD

**Issue by dcarpenter31** [sumatrapdfreader/sumatrapdf#4075]
**SumatraPDF version**
3.6.15960 (pre-release) and 3.5.2 (latest)

**Describe the bug**
When dragging the splitter between the main content pane and the sidebar pane, "ghost" versions of the splitter appear in locations the splitter was dragged through for a fraction of a second, but long enough to be visible. This same behavior occurs with the splitter between the bookmarks section of the sidebar pane and the favorites section of the sidebar pane, if the favorites section is visible.

This is observable when dragging the vertical splitter between the main content pane and the side bar pane when dragging it both left and right. This is observable when dragging the horizontal splitter between the favorites section and the bookmarks section only when dragging the splitter down, not up.

**To Reproduce**
1. Open any PDF file.
2. Click on the splitter between the bookmarks pane and the main content pane.
3. Drag the splitter to the right or left. Observe the "ghosting".
4. Favorite any page in the open PDF file.
5. Click on the menu drop-down at the top left.
6. Click Favorites > Show Favorites.
7. Click on the splitter between the Bookmarks section and the Favorites section.
8. Drag the splitter down. Observe the "ghosting".

**Expected behavior**
When dragging the splitter, the location where the splitter was should be filled with the background color as soon as the splitter has been moved.

**Screenshots**

https://github.com/sumatrapdfreader/sumatrapdf/assets/21251320/fe739dae-d8ac-4c96-bb10-d7f58e2ab5b8

https://github.com/sumatrapdfreader/sumatrapdf/assets/21251320/481feb16-414f-4b5b-9d99-bfa59642e615

![splitter_ghosting_horiz_light_theme](https://github.com/sumatrapdfreader/sumatrapdf/assets/21251320/6c5bdc89-1562-4a0b-9c53-184c688e7b2d)
![splitter_ghosting_vert_light_theme](https://github.com/sumatrapdfreader/sumatrapdf/assets/21251320/75e11e49-b888-4424-b8f9-ad3679bf28f8)

**Additional context**
This is much easier to see when a dark theme is enabled. It also is present when a light theme is enabled, but it is harder to see.

This was tested on 165 Hz and 60 Hz refresh rates and the "ghosting" was present for both refresh rates.

This may be an intentional choice to efficiently handle repaints that I am unaware of as a newcomer. Please feel free to close this issue if this is the case.

**Comment by kjk** [comment]
This is not intentional. If you figure out a way to fix it, I'll accept a PR but I don't have the bandwidth to spend on a minor cosmetic issue.

I'm closing the bug to indicate I'm not going to be looking into it further but if you figure a better way, I'm happy to merge a fix.
