### ISSUE TITLE
Send DDE command to SumatraPDF by VBA

### ISSUE THREAD

**Issue by valuex** [sumatrapdfreader/sumatrapdf#4078]
**SumatraPDF version**
3.5.2 64-bit

**Describe the bug**
I am using VBA to send DDE command to SumatraPDF.  
The code is shared by KJ, which works well.
https://stackoverflow.com/questions/77971634/how-to-send-dde-dynamic-data-exchange-information-using-vba-64-bit
The only one in-convinience point is that there are always two channels found when the code is running.
Actually I only opened one instance of SumatraPDF, but everytime I run the code, there is pop-up list with two items to be selected. The items are `SUMATRA|control` and `SUMATRA|`. The pop-up window snapshot is shown below. 

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/3627812/d070c8a3-169e-4c1b-841a-00ab56585329)

``` vba
Sub Sumatrapdf()
Dim channelNumber As Long
channelNumber = Application.DDEInitiate( _
 app:="SUMATRA", _
 topic:="control")
Application.DDEExecute channelNumber, "[Open(" & """Your_pdf_file_path.pdf""" & ", 1, 1, 0)]"
Application.DDETerminate channelNumber
End Sub
```

**To Reproduce**
1.  copy the code into VBE
2.  modify **Your_pdf_file_path.pdf**
3.  make sure that both Excel and SumatraPDF are of 64-bit, or 32-bit. They get to be the same in terms of bit number.
4. run the VBE code

**Expected behavior**
Only one channel for one instance would be better

**File that reproduces the problem**
NA

**Screenshots**
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/3627812/d070c8a3-169e-4c1b-841a-00ab56585329)

**Additional context**

**Comment by GitHubRulesOK** [comment]
Hmm I am the offending KJ from StackOverflow (Note NOT "The KJK" developer)

So in my tests I did not get a challenge it simply ran the example
and changing the file name in the snippet makes no difference here in MS Word "when run for me" (I am an Admin user) there is no dialog raised.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/bdcc509f-db19-41c9-b683-3355b90426fb)

I am on 32 bit so it is running in 32 bit mode and SumatraPDF  is an installed pre-release, however none of that "should" make any difference, unless 64 or the version you are testing has different characterisics down to User level.

**Comment by GitHubRulesOK** [comment]
there can be oddities in how DDE works that may be not as expected, so here are some discussions about those behaviours but note there is ONLY one DDE actively showing which is the topic `control`?

https://github.com/sumatrapdfreader/sumatrapdf/discussions/2993

An example of open file 2 and close file 1 to attempt avoid white screen time waiting for render https://github.com/sumatrapdfreader/sumatrapdf/issues/1080#issuecomment-1828796913

**Comment by kjk** [comment]
I'm afraid I'm not an expert on DDE. If you can point out what we do wrong in `SearchAndDDE.cpp` then I can I change it.

But the problem might just as well be in your VB code.

**Comment by valuex** [comment]
I just re-boot my computer, and it works right now. No addtional pop-up window for data source selection.   
So I think it could be caused by some un-sucessful `DDETerminate`.  But I also checked the Task Manager, there is no `SumatraPDF.exe` process.    
Anyway, re-boot always one of the solution. :-D
