### ISSUE TITLE
-page 11 not working from windows shortcut

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#4082]
**SumatraPDF version**
- Version 3.6.15961

**Describe the bug**
-page 11 not working in windows shortcut
"D:\hvac\Energy Kinetics\installer-manual-ek1-ek2-oil_2021.pdf" -page 11

I modified the registry shell open to "C:\Users\Henry\AppData\Local\SumatraPDF\SumatraPDF.exe" "%1" "%2" "%3"
which seems to work correctly

**Comment by GitHubRulesOK** [comment]
shortcuts generally will not work that wat the commands need ideally to be after the ex in a shortcut and before the document

shortcut to exe or bat can have the options shortcut to document usually is depending on the FTA so noting after the .PDF

**Comment by kjk** [comment]
Should be fixed in 15997 or later (you'll have to install so that new registry entries are written)
