### ISSUE TITLE
Button(s) and shortcut(s) for clossing all tabs, closing all tabs but one, closing all tabs but not the selected ones

### ISSUE THREAD

**Issue by pangolin14** [sumatrapdfreader/sumatrapdf#4083]
Hi, 

I would much appreciate following features : 
Button(s) and keyboard shortcut(s) for: 
 - closing all tabs, 
 - closing all tabs but one, 
 - closing all tabs but not the selected ones

With time many opened PDF are systematically re opened in Sumatra PDF.

BR,

**Comment by GitHubRulesOK** [comment]
just **Right click** the buttons at the top of the pages
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/21192d9b-9ee3-45e3-9bfd-7d5812a96d50)

**Comment by kjk** [comment]
What's the difference between "closing all tabs but one" and "closing all tabs but not the selected ones"?

**Comment by pangolin14** [comment]
> just **Right click** the buttons at the top of the pages ![image](https://private-user-images.githubusercontent.com/12754913/304413345-21192d9b-9ee3-45e3-9bfd-7d5812a96d50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODM2NjQsIm5iZiI6MTcwNzk4MzM2NCwicGF0aCI6Ii8xMjc1NDkxMy8zMDQ0MTMzNDUtMjExOTJkOWItOWVlMy00NWUzLTliZmQtN2Q1ODEyYTk2ZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA3NDkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZjQzYzU3MDM2MWFkNmIyMDc2Y2QzN2Y2Yjg0Njg0YTYwZTc1OGEwYmEzYWIwN2Y2YjM3MDIzNGVhOGZjN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o80Mgydh9rgzLEHCAaGBxCPlKzwDOq8J_aCvdJCZkCI)
> 
> @kjk It would be nice if the HOME tab had the context to close all other tabs so none were active on restart Also there are no CMDcloseTABs is logical to provide some ?

Thank you! 
By upgrading to 3.5.2 I got the tab-closing features, thanks! Great work :)

**Comment by pangolin14** [comment]
> What's the difference between "closing all tabs but one" and "closing all tabs but not the selected ones"?

None. My mistake.

**Comment by kjk** [comment]
I've added `CloseAllTabs` and `CloseTabsToTheLeft` commands which complete this.

You can invoke them via context-menu on the tab, `Ctrl + K` Command Palette or assign a custom shortcut https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts
