### ISSUE TITLE
Feature Request: Rotate left 90, rotate right 90 as icons on toolbar.

### ISSUE THREAD

**Issue by sunk818** [sumatrapdfreader/sumatrapdf#409]
http://www.sumatrapdfreader.org/manual.html

I see you can rotate via keyboard. I wouldn't mind seeing it on the toolbar though... a curved left arrow for rotate 90 left. and curved right arrow for rotate 90 right.

![image](https://cloud.githubusercontent.com/assets/6989799/12158104/bc5924a8-b48b-11e5-8958-0b95ced59d05.png)

**Comment by GitHubRulesOK** [comment]
Closing as now duplicated by #723

**Comment by GitHubRulesOK** [comment]
just a comment to say this request has now been included on toolbar
