### ISSUE TITLE
PDF text is not readable in german : unknown signs

### ISSUE THREAD

**Issue by MaximGraf** [sumatrapdfreader/sumatrapdf#4096]
**SumatraPDF version**
- Version [3.5.2, 64-bit]

**Describe the bug**
PDF text is not readable in german : unknown signs.
In Adobe-pdf it is all correct.

**To Reproduce**
View

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

[2023 LPB Online-Sparkonto X.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/14322295/2023.LPB.Online-Sparkonto.X.pdf)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/160397509/4a4834da-ebc9-498b-9360-a78b7e9f81f0)

**Comment by GitHubRulesOK** [comment]
The Font appears to be faulty CID (character numbers) but newer SumatraPDF will do its best to display the graphic glyphs (inked translation of those poor numbers)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4439e024-fd23-420c-a42d-fc4e539f96c4)
