### ISSUE TITLE
Feature to open pdfs from weblinks directly.

### ISSUE THREAD

**Issue by pranjal32** [sumatrapdfreader/sumatrapdf#4099]
**Describe the solution you'd like**
It would be great if we had an option to directly open pdfs hosted on the internet by their URL.
Maybe a dialog box could be added where we enter the URL and the pdf is downloaded in cache or somewhere and shown in a new tab.

**Describe alternatives you've considered**
Right now, one needs to download the pdf and then open it up. It just creates extra friction and instead of doing this, one just ends up opening the pdf in browser.

**Comment by tactilis** [comment]
> Maybe a dialog box could be added where we enter the URL and the pdf is downloaded in cache or somewhere and shown in a new tab.

You already have this. It's a standard feature of Windows.

In SumatraPDF:

1. Click File | Open   (or press Ctrl+O)
2. Paste the URL in the File name field
3. Click OK or press Enter

Try it with  https://pdfobject.com/pdf/sample.pdf

**Comment by tactilis** [comment]
> Right now, one needs to download the pdf and then open it up. It just creates extra friction and instead of doing this, one just ends up opening the pdf in browser.

Or set SumatraPDF to be the default PDF viewer in your browser

**Comment by pranjal32** [comment]
> > Maybe a dialog box could be added where we enter the URL and the pdf is downloaded in cache or somewhere and shown in a new tab.
> 
> You already have this. It's a standard feature of Windows.
> 
> In SumatraPDF:
> 
> 1. Click File | Open   (or press Ctrl+O)
> 2. Paste the URL in the File name field
> 3. Click OK or press Enter
> 
> Try it with https://pdfobject.com/pdf/sample.pdf

Alright, got it.
