### ISSUE TITLE
please add the function of finding content with "whole word only" option

### ISSUE THREAD

**Issue by rayoo** [sumatrapdfreader/sumatrapdf#410]
please add the function of finding content with "whole word only" option, thanks!

**Comment by pdgessler** [comment]
This already exists: You can add a space before and after the search query. For example, searching for " concept " will return matches for "concept" but not "concepts" or "conceptually". This technique works even when there is punctuation immediately before or after the word.

Krzysztof obviously has the final say about adding an option for this though. My comment is just for informational purposes. :smiley:

**Comment by rayoo** [comment]
All right.
