### ISSUE TITLE
The translations arent included in the pre-release builds

### ISSUE THREAD

**Issue by Felipefpl** [sumatrapdfreader/sumatrapdf#4104]
**SumatraPDF version**

Version 3.6.15966

**Describe the bug**

I updated the translation to brazilian portuguese and the program still uses the old translations.

**Comment by GitHubRulesOK** [comment]
duplicate of some other issues currently no time to find @kjk current progress ?

**Comment by kjk** [comment]
Should be available in next pre-release after 15966 (should be available within next 24 hrs)
