### ISSUE TITLE
32-bit version crashes on startup due to vs 2022 code generation bug

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4111]
**SumatraPDF version**
- Version [e.g. 3.5.2, pre-release]
 pre-release 15966
**Describe the bug**
initially crashed on opening with 2 tabs active  retested with no settings and it just crashes !
**To Reproduce**

**Expected behavior**
no crash the files have oddities but should not trigger a crash
**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

one file is sample used to describe issue with underline thickness the other is much larger and should not present a problem here but was edited twice at source so has incremental xrefs
[underline scale 4.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/14427026/underline.scale.4.pdf)
seems to be the offender

However without that file others also fail so probably the URLS
[sample-file (with videolink).pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/14427759/sample-file.with.videolink.pdf)

**Screenshots**

**Additional context**

**Comment by kjk** [comment]
Can't reproduce

**Comment by GitHubRulesOK** [comment]
sorry should have said 32bit installed as still cant test 64bit yet I have no problems with installed 15963 (so reverted ) but 966 throws me out as soon as open a file ??

**Comment by kjk** [comment]
can you attach crash report (make sure symbols are correct)

**Comment by GitHubRulesOK** [comment]
Ahh are you saying the symbols had not updated ?

**Comment by GitHubRulesOK** [comment]
Sybols unpacked before fress install 
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/14440877/sumatrapdfcrash.zip)

thought I had deleted settings.txt though I got something wrong a home screen was populated  hmmm
any way it crashed on opening

**Comment by kjk** [comment]
it seems 32-bit build just crashes

**Comment by GitHubRulesOK** [comment]
As said I have not rebooted and dotted about in this poor exampleof a Modern PC strugling with Enterprise 10 updates MuPDF got frozen at 1.20 (now we are at 1.24 ish so I managed to cobble VS into building 1.23.1 as 32bit thus that may be "lurking" about.

**Comment by kjk** [comment]
Looks like mis-compilation. The version built by GitHub bot (VS 2022) crashes but I can't reproduce building locally using VS 2022 Preview doesn't.

The one that crashes:
```
010DFDD3  push        ebp  
010DFDD4  mov         ebp,esp  
010DFDD6  push        ecx  
010DFDD7  push        ecx  
010DFDD8  push        edi  
010DFDD9  mov         byte ptr ds:[0],0  
010DFDE0  mov         edi,offset g_threadCritSec (01B664ACh)  
010DFDE5  call        ResetTempAllocator (010DE9D7h)  
```
The one that doesn't crash:
```
static DWORD WINAPI FileWatcherThread(void*) {
00C02D55  push        ebp  
00C02D56  mov         ebp,esp  
00C02D58  push        ecx  
00C02D59  push        ecx  
00C02D5A  push        edi  
00C02D5B  mov         edi,offset g_threadCritSec (0CB8590h)  
```

The one that crashes has:
```
010DFDD9  mov         byte ptr ds:[0],0  
```

`ds` is 0 so it tries to store at address 0 which is a crash.

Version of VS on github:
```
MSBuild version 17.9.5+33de0b227 for .NET Framework
```
 
Strange version because latest is 17.9.2 (https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes)

**Comment by GitHubRulesOK** [comment]
Ensured nothing visible in memory that could interfere except defender !
deleted program files exe and dll (not the folder) and deleted appdata local settings.txt
did full "admin for all users install" with search and preview (as per usual) it wrote all 3 files to program files directory (as expected) and started without settings then as fast as before simply crashed.
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/14441146/sumatrapdfcrash.zip)

**Comment by kjk** [comment]
Per https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md installed VS version is `17.9.34616.47`. 

Will have to wait until they change it and then re-check if it still mis-compiles.

**Comment by kjk** [comment]
Could try to use `windows-2019` image which has Visual Studio `16.11.34601.136` (https://github.com/actions/runner-images/blob/main/images/windows/Windows2019-Readme.md)

**Comment by kjk** [comment]
still crashing in latest pre-release even though vs version is updated to `17.9.34714.143`

**Comment by GitHubRulesOK** [comment]
thought so thus not updated yet
so missing all those good enhancements since 15963 :-0

I cant get all of MuPDF Mutool to compile as 1.24 it builds BUT some commands work and others (like newer trim) dont

**Comment by kjk** [comment]
I've downgraded GitHub daily builder to earlier vs version. Hopefully it'll fix the next daily build.

**Comment by GitHubRulesOK** [comment]
Will let you know or will close if it works.

(My issue with MuPDF code is that the std viewer works but my preferred GL variant fails most often over 95% (oddly not always other than seems good without graphic objects and no simple reason) to display with this 32bit graphics system but there is no newer driver to try!

P.S forgot to say the interface before crashing looks way better,
 so should address a lot of old issues (except bookmarks :-)

**Comment by kjk** [comment]
I forgot that building with vs 2019 is no longer supported so have to wait for Microsoft to fix the vs 2022 code generation bug and update the GitHub runners.

**Comment by GitHubRulesOK** [comment]
@kjk I persevered with 32 bit  in VS2019
 now as you know I have no idea what I am doing in that IDE so rely on the warnings thus I set all options preferences to use v142 not v143 (which is not available for 2019)
and got some success EXCEPT for one problem that took me a while to track down. 
so by blocking the two sections of one commit https://github.com/sumatrapdfreader/sumatrapdf/commit/04c50aefd09d21b76fb8d0ba012d78c96feba310 I have what seems to be a Windows 10 x32 working copy without crash on first UI render?

There are still warnings about heic so perhaps that may need me checking/not using them but as there is no heic enabler on this device (paint cant open them) thats currently not my issue.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c0677559-4c17-4fe6-8454-4be3bff6dda4)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/97540714-05ad-4f0a-9087-b42c36678096)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2c004b93-46a2-4081-9b2d-8e477077456d)

**Comment by kjk** [comment]
If you compile with  vs 2022 preview (https://visualstudio.microsoft.com/vs/preview/) it should be fine and require no changes.

It's just that the version of vs 2022 installed on GitHub's build servers is buggy when generating 32-bit code and I have no way of changing the version.

Hopefully eventually they'll fix that and update build server.

**Comment by GitHubRulesOK** [comment]
Catch '22 Vs 2022 says 
>The following are not supported:
32-bit and ARM32 operating systems.

**Comment by GitHubRulesOK** [comment]
HMmmm
 ITried the latest version however debug run fails with same WinDynCalls. updated for Win11 so I still have to make 2 sets of edits there and Caption.cpp

P.S that fail MSB3073 has popped-up only in most recent few days and 2 daily pre-release runs have failed too so unsure if related.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "cd ../out/dbg32\..\.. & go run ./do -gen-docs
:VCEnd" exited with code 9009.	SumatraPDF	C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	145	
Error	C2838	'DWMWA_CAPTION_COLOR': illegal qualified name in member declaration	utils	C:\Users\lez\source\repos\sumatrapdf\sumatrapdf-16101\sumatrapdf-master\src\utils\WinDynCalls.cpp	199	
Error	C2065	'DWMWA_CAPTION_COLOR': undeclared identifier	utils	C:\Users\lez\source\repos\sumatrapdf\sumatrapdf-16101\sumatrapdf-master\src\utils\WinDynCalls.cpp	199	
```

**Comment by kjk** [comment]
16105 or later should not crash there

**Comment by GitHubRulesOK** [comment]
@kjk 
16105 same 3 errors
I appreciate your attempts to humour an ailing platform but that Win 11 syntax is still not accepted on Win 10 Vs2019+tools v142
 is there a simple way to say IF win10 then skip this win 11 code as manually I have to
```
find src/utils/WinDynCalls.cpp
about line 200

// https://stackoverflow.com/questions/39261826/change-the-color-of-the-title-bar-caption-of-a-win32-application
//REMove for 32bit win 10
//HRESULT SetCaptionColor(HWND hwnd, COLORREF col) {
//    return SetWindowAttribute(hwnd, DWMWINDOWATTRIBUTE::DWMWA_CAPTION_COLOR, &col, sizeof(col));
//}

goto src/Caption.cpp
about line 175

//REMove for 32bit win 10
//    if (gGlobalPrefs->useTabs) {
//        COLORREF col = ThemeControlBackgroundColor();
//        dwm::SetCaptionColor(::GetParent(hwnd), col);
//    }
}
```

the 3rd issue seems to be I have NO GO as it throws up virus warnings I could not install GO in the past.

**Comment by GitHubRulesOK** [comment]
ahh that will be tomorrow mornings daily ?

however now I have got so close, it would be nice to bypass the GO limitation can I simply somehow block that step or is it essential it builds some support ?

**Comment by GitHubRulesOK** [comment]
Thanks 
I will try official however I have downloaded latest gox86 so will see if it runs!
but I prefer standalone portables (not installed) so may have to fiddle a shim to run on demand.

Great job done and F1 seems on first run not working (unpacking ??) but eventially appears twice as I also used menu :-)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/4a50cf22-8822-43a7-af86-8c77c734d480)

**Comment by GitHubRulesOK** [comment]
Just to comfirm I got an unofficial build by 
1 add a go.cmd pointing at standalone copy of go.exe
2 after several fails realised the bin folder are all 32 bit EXCEPT makeLZMA so run its SLN 1st with edit tools version to v142 !
3 add a custom version h to show it not official
4 add the blockers to Win11 specific entries as before.
5 be impressed that the help system is 1.3 MB exported and faster when wait for it to decompress first :-)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f46981b5-412f-4bdb-b816-03c6a857a502)

**Comment by kjk** [comment]
VS version on github is now 17.10.35122.118

I've disabled the work around for mis-compilation. Will have to see if it still crashes.
