### ISSUE TITLE
Faroese is missing on the translation page

### ISSUE THREAD

**Issue by hoghoj1** [sumatrapdfreader/sumatrapdf#4113]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/4112

<div type='discussions-op-text'>

<sup>Originally posted by **hoghoj1** February 28, 2024</sup>
Make a invitation to translate somewhere under Options/Change Language. I would love to make it possible to have a **Faroese translation**. This even the population is only 55 thousand!</div>
Please create Faroese on the translation page?

**Comment by kjk** [comment]
Done: https://www.apptranslator.org/app/SumatraPDF/fo

**Comment by hoghoj1** [comment]
Hi Krzysztof,
I've worked as a IT service provider since 1995. Have most of the time 
worked with people having reading problems, mostly dysletics. I am 
retired now (72), but I still like to provide something, as the Faroese 
nation is a very small one and those with possibilities should give 
something back.
I will start working on this issue now, hopefully to accomplish most of 
it in a small timeperiod as possible, thank you :-)

------ Original Meddelelse ------
Fra "Krzysztof Kowalczyk" ***@***.***>
Til "sumatrapdfreader/sumatrapdf" ***@***.***>
Cc "hoghoj1" ***@***.***>; "Author" ***@***.***>
Dato 29.02.2024 14:07:33
Emne Re: [sumatrapdfreader/sumatrapdf] Faroese is missing on the 
translation page (Issue #4113)
