### ISSUE TITLE
is SPDF still XP compatible?

### ISSUE THREAD

**Issue by besrml** [sumatrapdfreader/sumatrapdf#412]
Trying to use the 3.1 or the 3.1.1 version i get a popup warning with the advice of:
Not found the entry point of the procedure GetProcessHandleFromHwnd in the dinamic link library oleacc.dll
i'm already tried to use the compatibility mode to W2000 by suggestions from the web.
The 3.0 version work without problem

**Comment by kjk** [comment]
We do support XP and this function should be available in XP (https://msdn.microsoft.com/en-us/library/windows/desktop/dd318087(v=vs.85).aspx).

We don't support anything lower than XP (2000 etc.).
