### ISSUE TITLE
Problems with languages that are read from right to left (RTL), Hebrew and Arabic.

### ISSUE THREAD

**Issue by Y-PLONI** [sumatrapdfreader/sumatrapdf#4128]
**SumatraPDF version**
- Version [3.4.6]

**Describe the bug**
1. It is not possible to search for words in the document in a normal way. To search the document in languages from right to left, the word must be written in reverse.
2. In book display, it is not possible to display from right to left, the book opens from left to right, opposite of the way of reading in these languages.

There doesn't seem to be anything to add to what I wrote...

**Comment by GitHubRulesOK** [comment]
both will be possible but the search dpends on the document 

To view pages in reverse either set a key shortcut (see website manual, or search the many examples I answered) or use command CMD toggle manga
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/7d487584-7b4d-4cd2-8ad4-2231ce03d22f)

search is very dependent on correct file structure flags and writer method so often the wrong way round, and does vary from version to version so also look at the many answers on RTL or R2L

**Comment by Y-PLONI** [comment]
@GitHubRulesOK  Thanks for your reply, I'll check it out. Regarding your answer to the search, I would appreciate it if you could direct me to clearer sources.
I forgot to add another disturbing problem: when copying a word or a grouped sentence, the word is copied in reverse... Will the solution you write help this problem as well?

**Comment by GitHubRulesOK** [comment]
@Y-PLONI 
the primary issue with search was covered by https://github.com/sumatrapdfreader/sumatrapdf/issues/1870
thus 3.1.2 was most reliable for a long time
The only version that can be changed is current pre-release so that needs
 any sample that is **designed** to work to current ISO standards.

**Comment by Y-PLONI** [comment]
@GitHubRulesOK Thank you for the answer! I am excited to see how people dedicate their time to help others. I will check the solution in the latest version [latest pre-release: 3.6.15984]. Thanks again!

**Comment by kjk** [comment]
Nothing we can do without test file.
