### ISSUE TITLE
In properties, show whether the file is linearized or not

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#4130]
I have noticed, especially with huge PDF files, that searching text and jumping to a bookmark is much faster when the PDF is linearized. For this reason, I like to keep all my regularly used files linearized. However, Sumatra PDF doesn't tell me whether a PDF is linearized or not. So, I have to open the file in another PDF reader to know if the PDF is linearized.

I think that Sumatra PDF should also show whether the PDF is linearized or not, just like other PDF readers do.

Chrome:
<img width="294" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/c579b262-b514-48ad-a0ab-ea2ecf170d91">

Firefox:
<img width="253" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/c03542b6-82a1-48ef-8ac7-716098bd7123">

Sumatra PDF:
<img width="458" alt="image" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/691bc898-781b-49e2-b181-d78e652f48a5">

Note: "Fast Web View" is just another term for linearization.

**Comment by user1823** [comment]
Ok, I see. But I think that it would be more clear if it said something like `PDF Optimizations: None` if there were no optimizations.

By the way, what are other types of PDF optimization (apart from Linearization)?

**Comment by GitHubRulesOK** [comment]
@user1823 

your wish should be in tommorows pre-release

However you queried what other types?

```
 layoutData->AddProperty(_TRA("Fast Web View"), linearized);

        props.Append(_TRA("Tagged PDF"));
        props.Append("PDF/X (ISO 15930)");
        props.Append("PDF/A (ISO 19005)");
        props.Append("PDF/E (ISO 24517)");
```
Also the optional DRM permissions  such as not designed for accessibility or print etc.

**Comment by user1823** [comment]
@kjk, thanks for the change. But, I think that the info is now repetitive.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/040c58d3-0712-49a1-a36a-365923a77b4b)

Also, the colon after "Fast Web View" is missing.

**Comment by kjk** [comment]
@user1823 thanks, fixed
