### ISSUE TITLE
EPUB - 'Synchronization file cannot be opened' on double click

### ISSUE THREAD

**Issue by GooseOb** [sumatrapdfreader/sumatrapdf#4138]
**SumatraPDF version**
- Version 3.5.2, 64-bit

**Describe the bug**
Says 'Synchronization file cannot be opened' instead of select a word on double click in `.epub` files.

**Screenshots**
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/91154742/80bee38f-0e8c-48c7-abab-2910558374f7)

**Comment by GitHubRulesOK** [comment]
Interesting
 that should only happen with a PDF that has a synctex file in same folder

**Comment by GooseOb** [comment]
Seems like I've broken settings file. Deleting it fixed the issue.
