### ISSUE TITLE
can't seslect and copy in epub document!

### ISSUE THREAD

**Issue by TAVVANNA** [sumatrapdfreader/sumatrapdf#414]
using x64 version we can select and copy in pdf and djvu documents. but not working in epub documents.

**Comment by SumatraPeter** [comment]
Workaround for now is to switch from EbookUI to FixedPageUI from Settings > Advanced Options.

**Comment by leafcutterant** [comment]
So this is not intentional, right? I find the EbookUI a very efficient way of reading, but I have to keep it disabled because I continuously need to select parts of the document.

**Comment by SumatraPeter** [comment]
It's intentional.

**Comment by leafcutterant** [comment]
So it' some technical limitation I presume.
Anyway, thanks for the answer!

**Comment by GitHubRulesOK** [comment]
@kjk dup of https://github.com/sumatrapdfreader/sumatrapdf/issues/239

**Comment by kjk** [comment]
closing as duplicate
