### ISSUE TITLE
Support for Editable PDFs

### ISSUE THREAD

**Issue by ldustc** [sumatrapdfreader/sumatrapdf#4140]
There are some PDFS that support the form filling function, which is common in the visa application process, e.g.:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/144667313/ec112af5-cce8-4fa0-b327-ec24c98c0281)
However, when I opened it in Sumatra pdf, I cannot fill in the blanks:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/144667313/4af29e70-825c-4a7d-b0cf-cb0717cf8fe5)
I hope this feature can be added in the next version.

**Comment by GitHubRulesOK** [comment]
There has been an open issue raised some time ago by the developer however Forms in PDF are not simple especially commercial grades that use Adobe proprietary methods that only work correctly in Acrobat reader.

Yours Look simple enough so Acrobat or cheaper editors or heavey weight Readers should do that, and even MuPDF-GL would probably be enough, but why as many browsers can be used for simple or semi complex Cases

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/25bc35b5-a1a0-481e-9ba9-3adc08c7f3e4)

**Comment by GitHubRulesOK** [comment]
closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1249

related #2141

**Comment by mmikeww** [comment]
i came to request this feature, searching found this issue, saw your response, tried dropping the pdf into google chrome, and you are right, google chrome allows me to edit the pdf as well as save it with my edits!

**Comment by GitHubRulesOK** [comment]
@mmikeww you only need Windows own Acrobat Form Filler (MS EDGE) see the logo bottom right it is the New Acrobat powered reader supplied by Microsoft with Windows 11 Edge (or 10)

<img width="1178" height="698" alt="Image" src="https://github.com/user-attachments/assets/7ed57e66-8553-44db-a919-5b46a7b95c52" />
