### ISSUE TITLE
Close all

### ISSUE THREAD

**Issue by gamgamstylep** [sumatrapdfreader/sumatrapdf#4142]
**Is your feature request related to a problem? Please describe.**
I want to close all tabs

**Describe the solution you'd like**
Shortcut to close all Tabs e.g. CTRL + SHIFT + W

**Describe alternatives you've considered**
no alternatives

**Comment by tactilis** [comment]
> Describe alternatives you've considered
> no alternatives

It takes only a moment to do this:
- Right click on any tab -> Close Other Tabs
- Ctrl+W    (which closes the one remaining tab)

**Comment by kjk** [comment]
In next pre-release (15997 or later) (https://www.sumatrapdfreader.org/prerelease) I've implemented `Close All Tabs` and `Close Tabs To The Left`.

You can right-click on the tab for context menu or `Ctrl + K` for Command Palette.

It doesn't have a keyboard shortcut by default but you can assign it yourself. See https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts

```
Shortcuts [
	[
		Cmd = CmdCloseAllTabs
		Key = Ctrl + Shift + w
	]
]
```
