### ISSUE TITLE
Zoom pdf different than zoom contained jpg in pdf

### ISSUE THREAD

**Issue by schulzefan** [sumatrapdfreader/sumatrapdf#4144]
**SumatraPDF version**
- Version 3.4.6

Zoom pdf different than zoom contained jpg in pdf.

Create a pdf from a jpg containing scanned text ie. magazine or news paper.
Extract the jpg from the pdf.
Open both pdf and jpg in the SumatraPDF.

**Expected behavior**
Zoomed image should look the same when source image is the same. Maybe I am missing something.

**Screenshots**
Jagged edges when zooming pdf:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/164236149/e03c800e-6b98-402e-920f-067bddd3072e)
This is the same jpg inside the pdf, zoom quality is the same as the viewer used on the source web page:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/164236149/24c8b3e7-bd74-4c66-8b3c-754c03f54407)

**Comment by kjk** [comment]
I don't know how you created them, I don't know if you're viewing them at the same zoom in Sumatra.
