### ISSUE TITLE
Hangs on open with this file

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#4145]
**SumatraPDF version**
- Version 3.6.15987 64 bit pre release

**Describe the bug**
stops responding on open. Had to kill with taksmgr. Finally had to delete tab from config file
[Hamilton Beach 31243.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/14681499/Hamilton.Beach.31243.pdf)

**Comment by GitHubRulesOK** [comment]
Should not be a problem except it is 16880 objects then web enhanced because it is so slooooow to render,
even optimised it seems no better
[Hamilton.Beach.31243_Optimized.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/14681863/Hamilton.Beach.31243_Optimized.pdf)
