### ISSUE TITLE
The background color is inverted

### ISSUE THREAD

**Issue by RF023** [sumatrapdfreader/sumatrapdf#4146]
**SumatraPDF version**
- Version [e.g. 3.5.2,]

**Since the last update the reading pane is black
The letters are white while the background is black.

I would like to go back to the old settings. With Black text on a white reading window
How is that done?

Thanks in advance for your help

**Comment by GitHubRulesOK** [comment]
it should be as simple as press <kbd>I</kbd> for invert but ensure your settings colours are default range text #000000 to background #ffffff

**Comment by RF023** [comment]
Hi,   Thank you so much! 
It is fixed.
