### ISSUE TITLE
quit full screen mode by double clicking 

### ISSUE THREAD

**Issue by sergeM1313** [sumatrapdfreader/sumatrapdf#4149]
**SumatraPDF version**
- Version 3.5.2,

Doubble clicking is the way to mark the current position in a Latex file linked to the pdf in the editor. This feature does not work in full screen : a double click terminates the fulls screen mode. Then , in the normal mode, the feature work again. 
This is a little bothering. I wonder whether there is a simple way to remain in full screen and interact with a tex file.
Thanks in advance

**Comment by GitHubRulesOK** [comment]
Related to https://github.com/sumatrapdfreader/sumatrapdf/issues/3927 and https://github.com/sumatrapdfreader/sumatrapdf/issues/3886

**Comment by sergeM1313** [comment]
OK, I understand it is uneasy to solve. This anyway not a huge issue for me. Thanks for your rapid response.

**Comment by kjk** [comment]
I've improved it so that if double click happens over text, it'll select a word even in fullscreen.

**Comment by sergeM1313** [comment]
Great, Thank you
Serge
+33 (0) 4 42 25 20 36


De : Krzysztof Kowalczyk ***@***.***>
Envoyé : jeudi 4 avril 2024 21:32
À : sumatrapdfreader/sumatrapdf ***@***.***>
Cc : MAILLARD Serge ***@***.***>; State change ***@***.***>
Objet : Re: [sumatrapdfreader/sumatrapdf] quit full screen mode by double clicking (Issue #4149)


I've improved it so that if double click happens over text, it'll select a word even in fullscreen.

**Comment by kjk** [comment]
this was fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/2641ec280b7bbd88a2c3871c592c8216d2e9f053
