### ISSUE TITLE
Pressing Canc when editing annotation text deletes the entire annotation

### ISSUE THREAD

**Issue by The11thPlague** [sumatrapdfreader/sumatrapdf#4158]
**SumatraPDF version**
3.5.2 64-bit

**Describe the bug**
If you press Canc when editing the text in the Contents field of an annotation you inserted, the entire annotation is deleted.
If I want to delete 1 letter in front of the cursor and press Canc, it destroys the entire annotation.
I lost a lot of text I wrote because of this unexpected behavior.

**To Reproduce**
1. Create an annotation on a piece of text.
2. Write a bit of text in the annotation "Contents" field.
3. Press the Canc key on your keyboard.

**Expected behavior**
Pressing Canc when editing the text in the Contents field of an annotation should delete part of the text that is being edited.
The Canc key should work similarly to the Backspace key, not delete the entire annotation.
As an optional safeguard, when deleting an annotation with a lot of text content, ask for confirmation.

**File that reproduces the problem**
Any text pdf you are creating annotations for.

**Comment by A-Infor** [comment]
Canc?
Is this literally written in the key?

**Comment by kjk** [comment]
For most people it's `Delete` key.

This is already fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease
