### ISSUE TITLE
Can't render pages of PDF file

### ISSUE THREAD

**Issue by lcfarini** [sumatrapdfreader/sumatrapdf#416]
http://download.boulder.ibm.com/ibmdl/pub/software/rationalsdp/documentation/product_doc/Statemate/pdf461/user_guide.pdf

"Couldn't render the page" is shown for PDF pages 29 to 42.
PDF-XChange Viewer and Sumatra 1.8 can display these pages.

**Comment by ousia** [comment]
@lcfarini, mupdf-gl shows the following error for those pages:

```
warning: cannot find page size for page 39
warning: non-page object in page tree ()
```

**Comment by ousia** [comment]
[Issue reported upstream.](http://bugs.ghostscript.com/show_bug.cgi?id=696519)

**Comment by GitHubRulesOK** [comment]
@kjk
This file does not work in other applications it is classified as "bad file" "cant fix" in the MuPDF analysis.4 I sugest as Sumatra PDF renders the valid pages and it does not crash that this one be "Closed" as invalid PDF

**Comment by kjk** [comment]
Chrome displays those pages but If mupdf won't fix it, we won't be able to show them. Maybe you can convince mupdf to reverse their "won't fix" stance.
