### ISSUE TITLE
If you have the eggs, since it's eastern :-)

### ISSUE THREAD

**Issue by ONE11111111ONE** [sumatrapdfreader/sumatrapdf#4161]
Since Adobe says clearcut we are going AI many people are looking for alternatives.
The only thing Sumatra lacks for being the total replacement is OF COURSE 1000000 times mentioned here Signature and Comment Section.
Since it's just a Viewer and not an Editor.
Yet the author should think about it...there are only 2 alternatives besides being able to do this stuff and they are in a way not as good as sumatra pdf. 
Bigger community help and all is possible....you could replace adobe with some features for anyone. 
Wake up guys, AI is middle ages of digitalization.

**Comment by GitHubRulesOK** [comment]
1st Lebel "Comments" are already possible (admittedly still lowest level **I**ncremental **A**nnots thus IA not AI)
Digital Signatures (not what they seem, as like passwords are editable anyway thus NEITHER are security) Can also be added as image annotation which in some jurisdictions are SEEN as validity but in real world are also worthless. Signing is just annother added layer of this file has been modified thus simply write in text "I say this file was edited by me".
Sinatures depend on a SHA hash so simplest of all would have been the use of a system like VirusTotal that records in an International Register the Hash of the file at time of BUILD (time of signing)

**Comment by ONE11111111ONE** [comment]
1st of all i do not understand you fully, yet i try.
i give you an example i couldnt manage yet the easy way with sumatra. 
Write an objection and use a *.png file with my Signature. Finish.
If this is possible, would you be so kind to show me how to do it?

Otherwise , i am aware of the way with e.g. Paint.NET and so on...PDF24...

**Comment by GitHubRulesOK** [comment]
@ONE11111111ONE  see #3489

**Comment by ONE11111111ONE** [comment]
Alright, i see the Remarks thing is easy going. 
Yet the Signature "solution", No way man. If this would be as easy as the Remarks one ...there you go.

**Comment by GitHubRulesOK** [comment]
Image signature in a PDF are simply a "stamp" on a page.
It is no different, whatever way you do it. So you can get Acrobat to store your signature in their servers or in their application but its just an over stamped object, however complex you wish it to be. So it can be deleted and replaced with another stamp hence there is nothing especial about signing. It is simply add an editable object onto the page . 
That is why I said just write on the page "This is my Authorised copy" 

When "Working for Pay" that's all that my clients required as an authorised request for payment. Anybody can sign for Anybody else (I signed for my boss and their boss) but the ONLY copy "Invoice paid for" was the one signed-off by "The highest Company Employee" **C**hain of **A**uthority **and *stored* as a record of agreed for payment**.

Signing can only be based on "trust" the PDF objects are not themselves trustworthy.

**Comment by ONE11111111ONE** [comment]
I understand,
nobody wants do be dependent on Adobe Servers or anything similar. At least not me. Especially not when they now start artificial intelligence. I'm out with this sort of solution. 

Of course i understand all your points, seriously, for me it's just an which could make the program much easier to use and even it takes lots of implementation. It's worth it! :-)

**Comment by ONE11111111ONE** [comment]
I want to use my real Siganture which i use in Real Life which is stored as a *.png and that's it. Finished, no "trustworthy" Digital Signature Stuff, nothing.

**Comment by GitHubRulesOK** [comment]
The example I linked uses as stamp from clipboard so if your PNG is in the Clipboard it can be stamped (OR copied as required by anyone else including yourself). This may not be ideal but is much easier than Adobe methods.

Adobe signature as added in Reader DC on Left
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/568fe97b-9d9b-42f9-9025-249a3ba3c744)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/b8f4e556-388c-4ef7-97ef-47d2471a201c)

**Comment by ONE11111111ONE** [comment]
i am sitting here at 4:20 am and i am not with stupid and see what you do and write but cannot do it on myself. what the f. is this. 
THIS is what i mean man, whoever is the programmer of this , this man from Poland, there is so much stuff to enhance ... i am serious and it looks like on hold or not under current developemenent. 

Germans would just say, what is this, i better go to ...give you names ... PDF X-Change Editor, OR some random Linux stuff i don't know the names from. Yet this is for Windows here right. So...if it's not a big deal for you. maybe you can just make a screen capture video of the process. Even it is the solution, it is not comfortable enough and i want to get rid of thid adobe stuff.

**Comment by ONE11111111ONE** [comment]
Thanks for your help though.

**Comment by kjk** [comment]
Please don't freestyle like this.

The request is about adding ability to sing. That's it.

All that editorializing is neither welcomed nor helpful. It's noise.

**Comment by ONE11111111ONE** [comment]
Sorry Sir. Even some noise CAN be the truth and you cannot deny. 

Cheers for the Moment.

**Comment by GitHubRulesOK** [comment]
In summary with SumatraPDF 3.7 tool you can remove and add signatures using JS scripting so have provided a means to do so like this.

<img width="1700" height="680" alt="Image" src="https://github.com/user-attachments/assets/850b3bc2-6a9b-444e-bf40-081ed8622c66" />
