### ISSUE TITLE
Maybe use pdfium engine?

### ISSUE THREAD

**Issue by alexeik** [sumatrapdfreader/sumatrapdf#4171]
https://github.com/bblanchon/pdfium-binaries)](https://github.com/bblanchon/pdfium-binaries
you can check out demo in IrfanView, it is super fast engine.

**Comment by GitHubRulesOK** [comment]
Pdfium is Primarily copyright Google with code from Foxit ("LegalCopyright",   "Copyright $YEAR PDFium Authors.) and very limited in formats compared to Artifex MuPDF which actually includes many others as yet unused like DocX.

**Comment by kjk** [comment]
Sadly we would loose epub support so I have no short term plans to switch to pdfium.

**Comment by alexeik** [comment]
> Sadly we would loose epub support so I have no short term plans to switch to pdfium.

what it means?

**Comment by GitHubRulesOK** [comment]
@alexeik 
The core engine of SumatraPDF is Artifex MuPDF it provides all the main file viewer abilities such as render PDF ePub SVG ? HTML ? FB ? So by removing MuPDF you remove all other of its abilities like annotation etc.

**Comment by alexeik** [comment]
seems to be PDFium now faster.
i just check how ifran view renders PDF pages.. and was suprised .
