### ISSUE TITLE
Find box don't change the size.

### ISSUE THREAD

**Issue by RabahHouna** [sumatrapdfreader/sumatrapdf#4174]
**SumatraPDF version**
- Version 3.5.2
- Version 3.6.16008, Pre-release

**Describe the bug**

When I hide the toolbar and use the shortcut to search within the document, the application displays a find box. However, the find box remains small in size and does not adjust when the toolbar size is modified. This makes it difficult to use as the font size remains unchanged, causing inconvenience in typing the words to search.

**Comment by kjk** [comment]
Yeah, the dialogs are not sized to use a bigger font.

I just added `UIFontSize` setting and we should use that in all dialogs, but of course it's not easy in windows.

Here's a potential code: https://stackoverflow.com/questions/14370238/can-i-dynamically-change-the-font-size-of-a-dialog-window-created-with-c-in-vi

**Comment by kjk** [comment]
If you use `UIFontSize = N` advanced setting, dialogs should now respect that size.

Default is 12 (on my laptop) so try 14 or 16 for a bigger font.
