### ISSUE TITLE
How to get the number of pages of a book without opening it through the command line

### ISSUE THREAD

**Issue by primejava** [sumatrapdfreader/sumatrapdf#4177]
like the title

**Comment by GitHubRulesOK** [comment]
That's in effect impossible as you need to run a file utility request (they must open the file to read the contents)

Either you run windows FindStr to look for the page count text or a command line tool like GhostScript to show calculated number of pages that it finds.

HOWEVER just like DocX there are files where the number of pages will change when the contents are running live in screen this is common with Forms that self adjust especially scripted XFA ones which SumatraPDF does not run.
