### ISSUE TITLE
Request: Make available as a wlx plugin for FreeCommander / TotalCommander

### ISSUE THREAD

**Issue by Gitoffthelawn** [sumatrapdfreader/sumatrapdf#418]
There are some ancient SumatraPDF-based wlx plugins for viewing PDF files in FreeCommander and TotalCommander.

Is there an official SumatraPDF wlx plugin based on the current code?

If not, would anyone be willing to create one?

**Comment by vovcacik** [comment]
It would be better to ask the plugin authors for an update I think.

**Comment by Gitoffthelawn** [comment]
@vovcacik I'll ping them as well, but since those plugins have not been updated in over 5 years, I doubt they are interested in SumatraPDF any longer.

**Comment by kjk** [comment]
I don't have plans to work on such plugins.

**Comment by Gitoffthelawn** [comment]
@kjk And there are no maintained plugins that you know of, correct?

**Comment by kjk** [comment]
Sadly, I know nothing about those plugins.

**Comment by Gitoffthelawn** [comment]
@kjk Thanks.  I appreciate your reply.

Please know that such plugins are very useful.  At the same time, I understand and respect completely that you don't have plans to work on them.

If anyone else is interested in creating a new one (or updating an old one), that would be great!

**Comment by Gitoffthelawn** [comment]
@leha-bot Thanks for your interest.

Here is a link to the plugin simply named "Sumatra PDF based plugin": http://totalcmd.net/plugring/sumatra.html

It uses a version of SumatraPDF from 2010.  Here is the main support thread for it: http://www.ghisler.ch/board/viewtopic.php?t=27145

Here is the addon called "sLister": http://totalcmd.net/plugring/slister.html

It also uses a very old version of SumatraPDF.

Here is the official website for FreeCommander: http://freecommander.com/

Here is the official website for Total Commander: http://www.ghisler.com/

Here is the developer's guide for plugin development: http://www.ghisler.ch/wiki/index.php/Developer's_corner

WLX plugins are compatible with both FreeCommander and Total Commander.

**Comment by Kungergely** [comment]
@Gitoffthelawn In that very [Total Commander forum thread](http://www.ghisler.ch/board/viewtopic.php?t=27145&postdays=0&postorder=asc&start=75&sid=248e6f3b875fdab1e3920868c5c3701d) it's also possible to download both the source code and the 32+64-bit versions of the plugin. If someone feels like tinkering with it, they're most probably welcome to tinker with it.

**Comment by plicit** [comment]
sLister still works if you replace the SumatraPDF.exe in its install directory with an updated version.
