### ISSUE TITLE
Text selection sometimes doesn't work

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#4183]
**SumatraPDF version**
- v3.6.16019 64-bit

**Describe the bug**
I don't know how to reproduce this issue. But, sometimes, after opening a PDF, I can't select text or search for text. If I close and then re-open the same PDF, I am able to select and search text.

I am not sure if it is an issue with some specific files or it can occur with any file.

**Comment by kjk** [comment]
This could be side effect of https://github.com/sumatrapdfreader/sumatrapdf/commit/ea0b59294eed551774be556fc45f9030cc7cbcf8 

This should trigger only for getting annotations, not text of the page.

**Comment by user1823** [comment]
> This should trigger only for getting annotations, not text of the page.

I am seeing this problem with the text of the page, not the annotations. In fact, my PDFs don't usually contain annotations at all.

**Comment by kjk** [comment]
I can't reproduce in latest pre-release.

Does it still happen for you? If yes, I need at least one test document showing the problem and more information on how to reproduce this.

**Comment by user1823** [comment]
I think that the issue has been resolved.
