### ISSUE TITLE
Add page displaying only the text of all favorites

### ISSUE THREAD

**Issue by tadghh** [sumatrapdfreader/sumatrapdf#4185]
A page to view just the text of all favorites. Using cards as backgrounds for each favorited text. Also thinking that the cards background could be set per book to provide some sort of organization.

There are a lot of notes I'd like to make across many books, my library is pretty big so I wont always remember the books title. Having a page where I can view the selected/favorites text from each book would allow me to quickly review inforamtion that is important to me.

**Comment by GitHubRulesOK** [comment]
You need a document manager which then opens documents beyond your favorite extracts.

SumatraPDF works very well within many EDMS (Electronic document management systems) as it accepts complex command lines to got to or scroll to this or that.

I have adapted it many times into different systems but it is no a PIM in its own right there are too many different user  desires in that are for any one product to cover all user requirements.
