### ISSUE TITLE
Keep scroll position when moving a file to another window when RememberOpenedFiles = false

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#4186]
**Is your feature request related to a problem? Please describe.**
Many times, I want to see different PDFs side-by-side using the split-screen feature. For doing this, when I move one file to a new SumatraPDF window, the file loses its scroll position and goes back to the first page. This is very annoying.

**Describe the solution you'd like**
When a file is moved to another window, the scroll position should be preserved.

I have the following setting because I don't want the scroll position from the previous session to be restored. However, I want to preserve the scroll position in the same session.

> RememberOpenedFiles = false

**Comment by GitHubRulesOK** [comment]
You can open same file same page `-new-window` or other version via command line
```
ExternalViewers	[
		CommandLine = C:\Users\lez\Downloads\Apps\PDF\SumatraPDF\older\3.1.2\sumatrapdf.exe -page %p "%1"
		Name = v 3.1.2
		Filter = *.*
	]
]
```
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/8dda8a68-555a-458e-b871-62cf2c93ae02)

**Comment by user1823** [comment]
> You can open same file same page -new-window or other version via command line

Thanks for the suggestion. But, I think that remembering the page number and going to that page after opening the file in a new window is easier than managing two different versions.

I hope that a fix for this issue is available soon.

**Comment by kjk** [comment]
`RememberOpenedFiles` is `true` by default and I believe most people use that. In that case it works as you want.

No plans to make it work when `RememberOpenedFiles = false`.

**Comment by user1823** [comment]
> RememberOpenedFiles is true by default and I believe most people use that.

But that doesn't fit well with my use case. Most of my PDFs are quite large (>1000 pages) and I want to check different portions every time I open them. So, I don't want Sumatra to restore the last opened page when I open a PDF again. I believe that many people would have similar use cases. 

> No plans to make it work when RememberOpenedFiles = false.

I think that RememberOpenedFiles and retaining scroll position when moving the file between different windows are quite different things. So, I kindly request you to make it work even when RememberOpenedFiles = false.

In addition, I think that a "Move to New Window" option would be more useful than the current "Open in New Window" option. With the "Open in New Window" option, two copies of the same file get opened. With the proposed "Move to New Window" option, the current tab would be moved to a new window so that only a single copy of the file remains open.

**Comment by GitHubRulesOK** [comment]
@user1823 
MOVE to new window is simply drag the tab of the old window but that does require the master window has at least one more tab than home tab to hang on to.

@user1823 
If on the left **I initially had 2 tabs for same document one on page 1 one on page 3** then dragging page 3 off will leave page 1 and 3 as two separate views

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c747b4c1-8a3b-4d12-bd40-0b61aa79f5e0)

**Comment by user1823** [comment]
> MOVE to new window is simply drag the tab of the old window

Yes, that's what I usually do to move a tab to a new window. I just wanted to say that "Move to New Window" is more likely to be useful than "Open in New Window". I have no problem if you don't want to replace "Open" with "Move".

> If on the left I initially had 2 tabs for same document one on page 1 one on page 3 then dragging page 3 off will leave page 1 and 3 as two separate views

That doesn't happen when `RememberOpenedFiles = false` and this is the main problem I want to solve.

**Comment by GitHubRulesOK** [comment]
@user1823 

If STATE is NOT remember last page then open window can ONLY start at page 1 there is nothing other than "favourites" to store any last alternative preference. 
Perhaps when on a page you wish to use quickly then right click "add to favorites" (no need to add a description uless it helps like figure 2) but you will need to remove unwanted entries too.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9e49f0cc-4acd-4d64-993e-2bc4ac946b05)
