### ISSUE TITLE
Ask before closing multiple tabs

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#4188]
**Is your feature request related to a problem? Please describe.**
If I have multiple PDFs open in Sumatra out of which I want to close one PDF and I mistakenly click the X button at the top right of the window, all of the PDFs get closed.

**Describe the solution you'd like**
Almost all programs that support tabs ask the user before closing multiple tabs. SumatraPDF can also do the same.

<img width=300 src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/b6d7d9a6-4b58-40e8-88e9-7c6c74cca2ea">

**Comment by kjk** [comment]
That's why by default we remember the session and all files would be restored when you re-launch Sumeatra.

I don't plan to this confirmation.
