### ISSUE TITLE
Feature Request: Display long filename on tab mouse hover 

### ISSUE THREAD

**Issue by orestesgaolin** [sumatrapdfreader/sumatrapdf#419]
I think it would be useful to show small box with full file name when hovering a tab

**Comment by Dpunkt** [comment]
Would be a great Addition.

**Comment by GitHubRulesOK** [comment]
@kjk duplicated by part of https://github.com/sumatrapdfreader/sumatrapdf/issues/1188

**Comment by kjk** [comment]
consolidating as #1188
