### ISSUE TITLE
Tabs interface becomes unusable when there are a lot of documents open

### ISSUE THREAD

**Issue by 3e33** [sumatrapdfreader/sumatrapdf#4195]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
When there are many tabs, the tab interface becomes unusable.
- Can no longer see tab text
- It's too easy to click the close button by accident
- Moving tabs around to sort the tabs becomes difficult when you can't see tab titles
- The tab titles sometimes glitch and flow past the tab into one another

Because of all the issues this causes, I consider this a bug.

**To Reproduce**
Simply open more files than the window width can support. 
Meaning depending on the width of the window even a small amount of files will still cause this problem.

**Expected behavior**
Possible solutions might be:
- Minimum tab-width and scrollable tabs
- Tab sidebar
- Dropdown menu listing all the tabs

**Screenshots**
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/33631407/855a460c-0ff4-47f0-9284-b51123998129)

**Additional context**
It's the best PDF viewer otherwise. : )

**Comment by GitHubRulesOK** [comment]
Hover to read text
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/28c6e2e0-c605-46bd-9fec-deb69d5eeef0)

Use the dropdown list (via Control+K)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/5276a79e-7859-4ebf-9776-ee66cf455b45)


But really why not much simpler use 3 windows with as third as many tabs then you can view 3 at once. (2 is easier)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/cd410ab4-be4e-4b1d-a012-c8be308c7111)

**Comment by ArmanHayots** [comment]
Horizontal tabs layout may do the trick.

**Comment by kjk** [comment]
Please check latest [pre-release](https://www.sumatrapdfreader.org/prerelease).

On `Ctrl + Tab` I've implemented a tab selection via command palette, similar to your dropdown with list of tabs idea.

You can also use `Ctrl + K` for [command palette](https://www.sumatrapdfreader.org/docs/Command-Palette) and type `@`.

You can also bind `CmdSmartTabSwitch` to a different keyboard shortcut than `Ctrl + Tab` (see https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts)
