### ISSUE TITLE
Incorrect rendering of PDF vector graphics when printed

### ISSUE THREAD

**Issue by matheburg** [sumatrapdfreader/sumatrapdf#42]
I have an issue which is present in any Sumatra version with any printer and on any OS I have tested it (Windows XP and Windows 7).
 
The example vector graphics example1.pdf and example2.pdf are not printed correctly. Items are missing and textures are introduced which are not acceptable. I have illustrated this by a scan: after_printing.png; find all files at http://ge.tt/8Ipkv172.
 
Side facts:
  (1) The PDFs are correctly printed with Adobe's Acrobat Reader.
  (2) I could not find a printer setting in Sumatra which would have removed or changed the problem.
  (3) Sumatra renders the graphics correctly on the monitor.
  (4) The vector graphics were created with PStricks in Latex.

**Comment by kjk** [comment]
Should be fixed in 3.1
