### ISSUE TITLE
Feature Request: Search selected text in default internet browser

### ISSUE THREAD

**Issue by orestesgaolin** [sumatrapdfreader/sumatrapdf#420]
I mean something like below
![sumatra-request](https://cloud.githubusercontent.com/assets/16854239/12537317/633771a6-c2bc-11e5-880d-10cac9ee0a4a.png)

**Comment by GitHubRulesOK** [comment]
@kjk consolidate with #1280 ?

**Comment by kjk** [comment]
I've started on this functionality in d710475

Still more to do, you can track progress / add ideas in #1280
