### ISSUE TITLE
displaying Roman numerals and circled Arabic numerals as blocks

### ISSUE THREAD

**Issue by killads** [sumatrapdfreader/sumatrapdf#4204]
**SumatraPDF version**
- Version [3.5.2 64-bit]

**Describe the bug**
1.Many characters in EPUB documents cannot be displayed properly in SumatraPDF. On the second page of the attachment.
2.I opened the epub document using Calibre.The characters that cannot be displayed are Roman numerals and circled Arabic numerals.

**Screenshots**
![bug](https://github.com/sumatrapdfreader/sumatrapdf/assets/168253238/f3c7c932-8ab2-4d36-bd08-493e7c624a03)

**File that reproduces the problem**
[股权激励与股权架构设计-2022.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/15136937/-2022.zip)

**Comment by GitHubRulesOK** [comment]
Unsure if a MuPDF regression or SumatraPDF missing out a Font

As seen by Windows 10
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d1d6c372-4b81-4932-ae87-ed420c115318)
MuPDF 1.20
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/146d6d80-6e29-4585-9f1e-7c8d86c37e4f)
SumatraPDF pre-release 3.6.15963
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/c00b26ac-bd6e-432e-ae60-cd9c3945493e)

**Comment by kjk** [comment]
Comparing to mupdf-gl, we're not including font `Source Han Serif` and using `Droid Sans Fallback Full` instead.

However, `Source Han Serif` is 24 MB which is more than currently SumatraPDF.exe (16 MB).

Maybe the missing fonts are:
```
165, 0, Noto Sans Math
164, 0, Noto Music
166, 0, Noto Sans Symbols
167, 0, Noto Sans Symbols2
168, 0, Noto Sans Emoji
```

which are much more reasonable to include.
