### ISSUE TITLE
Tab bar too high with dpi vs. 3.5.2

### ISSUE THREAD

**Issue by atauzki** [sumatrapdfreader/sumatrapdf#4205]
**SumatraPDF version**
- Version 3.6.16051 pre-release

Menubar icon is getting to large. The screen resolution is 2560x1600, dpi is 158.

**Screenshots**
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/19769843/e91543af-2554-43c0-a439-5945c8385f57)

Not so large in 3.5.2
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/19769843/e6c282a5-20c5-4a4d-b92d-2e4776df5210)

**Comment by GitHubRulesOK** [comment]
Unclear what you mean as in tabs mode the Menu BAR  is not visible the Menu Icon for system and drag is Top Left in Title bar

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/35b778f5-1416-4491-a885-d905d4657faf)

**Comment by user1823** [comment]
I think that the OP is talking about the height of the tabs.

<img width=300 src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/ce5475da-43f7-4e9c-9208-cfa3371dc4cd">
<img width=300 src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/bd421e5d-d1b2-42b4-8d89-3c27fc0b0b7c">

The increase in this height seems to be a very recent change.

**Comment by atauzki** [comment]
> I think that the OP is talking about the height of the tabs.
> 
> <img width=300 src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/ce5475da-43f7-4e9c-9208-cfa3371dc4cd">
> <img width=300 src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/bd421e5d-d1b2-42b4-8d89-3c27fc0b0b7c">
> 
> The increase in this height seems to be a very recent change.
> 

just the menu icon itself，it's too big and takes up too much space.

**Comment by kjk** [comment]
Let me know if it's not fixed in next pre-release. I run at 100% and that probably only shows up in scaled displays.

**Comment by atauzki** [comment]
> Let me know if it's not fixed in next pre-release. I run at 100% and that probably only shows up in scaled displays.

Not changed, I just compiled it.

**Comment by kjk** [comment]
If you know how to compile / debug, can you step through `GetTabbarHeight()` in `Tabs.cpp` and tell me what it returns and why? What is factor, FontDyPx, etc.

**Comment by atauzki** [comment]
Current version:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/19769843/8cd45d8e-69ee-4704-91ed-dae1d1932741)

before `GetTabbarHeight` changes:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/19769843/13a23569-26f9-42d3-8c2d-f63bec059f4c)

**Comment by kjk** [comment]
@atauzki Thanks, that was very helpful.

My mistake was that `FontDyPx` is already in pixels, and I was incorrectly scaling it by DPI which is large in your setup.

I fixed that, hopefully. If that's still not right in your setup please provide the same info about values.

Looking at the numbers you provided the latest version should end up as `DpiScale(hwnd, kTabBarDy) * factor` but who know.

**Comment by atauzki** [comment]
that's fixed, the height is consistent with before.
