### ISSUE TITLE
Standard windows shortcuts for window controls don't work in 3.5.2

### ISSUE THREAD

**Issue by git-78** [sumatrapdfreader/sumatrapdf#4206]
Like in v3.1.2 (old ticket, fixed in the meantime: https://github.com/sumatrapdfreader/sumatrapdf/issues/1739 ), ALT+Space in tabbed mode in version 3.5.2 cannot open the window control menu.
Tested under Win10 64bit.

**Comment by kjk** [comment]
It works for me in 3.5.2.

Make sure you're not running software that hijacks `Alt + Space`  shortcut e.g. Microsoft's Powertoys. Check if it works in any other windows program.

**Comment by GitHubRulesOK** [comment]
@git-78 
as mentioned above With or without tabs (even none showing) Alt space drops down, but note it is the standard LH Alt not RH AltGr
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d5aa66aa-7082-4565-b651-48330c6db186)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9038c860-5c8d-4cc3-83ce-ce747953f042)

**Comment by git-78** [comment]
Don't know what to say... It works in any software I have on my laptop, but not with SumatraPDF (using Alt+Space, not AltGr+Space as @GitHubRulesOK reminded). I have powertoys, but it doesn't handle any shortcut (if I'm not wrong). The only specific thing that I have in mind is that my keyboard layout is in French, but that shouldn't have an impact on Alt and Space keys.

Any idea on how to debug that? I'm missing that shortcut a lot.

**Comment by kjk** [comment]
Does `Alt + 1`, `Alt + 2` etc. work for switching tabs?

If you can compile /debug Sumatra, see `FrameOnSysChar()`, `WM_SYSCHAR` in `SumatraPDF.cpp`

**Comment by git-78** [comment]
Waoh, I am a software developer myself, so I doubt of what I am writing here, but after weeks where it has not worked (and I've restarted sumatrapdf or rebooted my laptop several times), Alt-Space is now working. Absolutely not logical, I admit... and so ticket closed indeed.

@kjk , for Alt+1, Alt+2, I have a little query from French guy's point of view. In the French layout, contrary to the US one, the default behavior of the number keys 1, 2, ... 0 is not the number itself but the special chars. So, to get the equivalent of Alt+1 on a US keyboard, we have to use Alt+Shift+1, which is not convenient. Could the shortcuts be attached not to the localized char, but to the key itself? That would allow to manage all localized keyboard. In c# and java, this is what we do.

**Comment by kjk** [comment]
@git-78 I'm not opposed to `Alt + 1` change but I have no way of testing it so wont work on it. You can try to submit a PR for changing `FrameOnSysChar()` in that way.

Better yet, this should be done as `CmdSelectTab1` ... `CmdSelectTab8`, `CmdSelectTabLast` with default accelerators in `gBuiltInAccelerators` of `Accelerators.cpp`. That way user could bind this functionality to other keys.

Better yet, commands should allow an optional argument so we would have `CmdSelectTabByPos` with arguments `1` ... `8` and `last` but that's a non-trivial change.
