### ISSUE TITLE
Please add a command name for inverse search so we can configure a shortcut.

### ISSUE THREAD

**Issue by yashamon** [sumatrapdfreader/sumatrapdf#4209]
**Is your feature request related to a problem? Please describe.**
The double click shortcut for invoke inverse search is currently totally unusable, due to exiting full screen. It is also very awkward to start with.

**Describe the solution you'd like**
Please give a cmd name for "invoke inverse search" that we might configure shortcut for in advanced options.

**Comment by kjk** [comment]
Done. Added `CmdInvokeInverseSearch`. I don't have latex setup so let me know if it doesn't work.

**Comment by yashamon** [comment]
Thanks that works. Is it possible to bind mouse clicks atm?

**Comment by kjk** [comment]
No, only keyboard
