### ISSUE TITLE
Feature Request: 3 page view for ultrawide monitors

### ISSUE THREAD

**Issue by ntshrocha** [sumatrapdfreader/sumatrapdf#421]
![219-ultrawide-monitor-review-increased-productivity-with-three-microsoft-office-pages](https://cloud.githubusercontent.com/assets/5845648/12542296/53fa5644-c308-11e5-8051-2c554f80520b.jpg)

**Comment by GitHubRulesOK** [comment]
@kjk duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/246#

**Comment by kjk** [comment]
Consolidating into #246
