### ISSUE TITLE
How to Single Page

### ISSUE THREAD

**Issue by Birmis2K** [sumatrapdfreader/sumatrapdf#4214]
How do I open all .epub files by default as "single page" view?
 However once I do select that it always stays like that, which is good. But I want to open all new epub's by default as single page view.
 Is there a way to do this?

**Comment by kjk** [comment]
You can use menu `Settings` / `Options` and change `Default Layout` to `Single Page`

**Comment by Birmis2K** [comment]
Thank you, thank you so much, it works
