### ISSUE TITLE
shortcuts question

### ISSUE THREAD

**Issue by qilingjun1** [sumatrapdfreader/sumatrapdf#4216]
Dear originator ，how to add double clicking as a key to shortcuts
<img width="256" alt="1" src="https://github.com/sumatrapdfreader/sumatrapdf/assets/150302438/b7971eaf-1f0a-4983-a936-e30d8ba18bb9">

**Comment by GitHubRulesOK** [comment]
see https://github.com/sumatrapdfreader/sumatrapdf/issues/4209 Not currently possible
