### ISSUE TITLE
TextColor and BackgroundColor settings in FixedPageUI aren't working in Dark and Darker Themes

### ISSUE THREAD

**Issue by SNgari** [sumatrapdfreader/sumatrapdf#4217]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
FixedPageUI TextColor and BackgroundColor aren't working in Dark and Darker themes. The color change in settings doesn't reflect. 

**To Reproduce**
1. Go to the top three horizontal lines at the top left after the logo --> Settings --> Advanced Options..
2. Change Theme to Dark or Darker
3. Under FixedPageUI change TextColor(#ffffff) and BackgroundColor (#202525)
4. Save

**Expected behavior**
The text color and page background color change to match the new color codes

**Screenshots**
Expected behavior (works in Light theme only)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/22195775/eca0bdf2-1eed-4be5-9ce3-fda7f361d978)

Actual behavior (on Dark Theme)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/22195775/7e419e4f-9411-47b2-8be9-6c7b7fb1bc01)

**Additional context**
The background and text colors obtained from changing InvertColors to true doesn't work for me. They're still pretty bright and I like a darker/ higher contrast view.

**Comment by GitHubRulesOK** [comment]
Fixed in prerelease https://www.[sumatrapdfreader.org/prerelease](https://www.sumatrapdfreader.org/prerelease)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/3b79a197-f75a-428a-82a3-fb22534d5ed5)

**Comment by SNgari** [comment]
Thank you @GitHubRulesOK
