### ISSUE TITLE
Persistent tabs

### ISSUE THREAD

**Issue by chrkara** [sumatrapdfreader/sumatrapdf#4227]
**SumatraPDF version**
- Version 3.5.2 64bit

**Describe the bug**
When trying to close all the open pdf tabs by closing the window with the cross button top right, when I open a new pdf, all the previous tabs supposed to have been closed, reopen automatically, as well!

**To Reproduce**
1.Open several PDFs, - They open in seperate tabs
2.Press the cross button top right to close all the PDFs
3.Open a new pdf and you see all the previous seen PDFs loaded as well!

**Expected behavior**
When I close the sumatra window and consequently all the open PDFs -tabs,  I expect when opening a new PDF **not** to see all the previous PDFs loaded again to tabs! Now I am obliged to close seperately every tab, or else they will automatically load again the next time i wish to see a new PDF! I expect a behaviour similar to the behaviour of a browser 

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

**Screenshots**

**Additional context**

**Comment by GitHubRulesOK** [comment]
but its not a browser with different ways to open 
> In "On startup" settings, select "Continue where you left off."

SumatraPDF has a set of related options 1) remember Opened Files 2) Remember for all files
But most releavant to your query is **RestoreSession = true** which you need to set to false

**Comment by chrkara** [comment]
At last!! *Restore session = false*. I wonder who could possibly want to
see all the previous documents ever viewed to be loaded again, whenever
attempts to view a new document!
Thank you very much!

Στις Σάβ 11 Μαΐ 2024 στις 12:00 π.μ., ο/η GitHubRulesOK <
***@***.***> έγραψε:

**Comment by kjk** [comment]
Also this should be fixed in [pre-release](https://www.sumatrapdfreader.org/prerelease) even without disabling session restore.

**Comment by chrkara** [comment]
> Also this should be fixed in [pre-release](https://www.sumatrapdfreader.org/prerelease) even without disabling session restore.

I agree. This should be the normal behaviour without having to mess with the "advanced settings". Moreover if there is a need to be somehow set, the setting should be available throuth the GUI environment and not through the adbanced commands
