### ISSUE TITLE
Zooming out PDFs too slow with touchpad

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#4231]
**SumatraPDF version**
- v3.6.16081 Pre-release

Zooming in using the touchpad is fast but zooming out is much slower.

**Comment by kjk** [comment]
I've tested with ctrl + touchpad scroll on my thinkpad x1 and zoom out is the same speed as zoom in.

So please provide the exact way you zoom, your hardware, what kind of document (pdf, cbr etc.).

Quantify "much slower". Best, provide a screen recording.

Does it happen with every file e.g. does it happen with a simple, text only PDF?

**Comment by user1823** [comment]
> the exact way you zoom, your hardware, what kind of document (pdf, cbr etc.).

I am zooming using the pinch gesture on the touchpad. I am using Lenovo Ideapad 330S with Intel i3 8th gen and 4 GB RAM. I am testing on PDF documents.

> Quantify "much slower". Best, provide a screen recording.

https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/576e092f-b11c-4bd7-9bb0-e7db7cae4e20

The zoom in required a single pinch gesture but zooming out the same required multiple pinch gestures.

> Does it happen with every file e.g. does it happen with a simple, text only PDF?

Yes, it happens with every file, including text-only PDFs.

**Comment by kjk** [comment]
Ok, I see it with pinch gesture as well.
