### ISSUE TITLE
Include local help / manual with Sumatra

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#4234]
As requested in https://github.com/sumatrapdfreader/sumatrapdf/discussions/4228 (and other places).

First implementation will be: embed html files with manual in executable. When user requests, extract to a directory on disk and launch default browser.

In the future we might show them in sumatra.

Changes:
* [x] move docs .md files from website repo to sumatra repo
* [x] write Go script that converts .md files into .html files
* [x] packs the files into an archive
* [x] embed the archive in Sumatra executable
* [x] add commands / menu to trigger showing help
* [x] extract help to $APP_DATA/SumatraPDF/help/${Version}/...
* [x] launch browser pointing at that directory

**Comment by GitHubRulesOK** [comment]
Hmmm SumatraPDF can read its own HTML
Here the commands page and sidebar navigation so not there any need for conversion except its in English, and other pages may differ. the page can be sent to the Edge  for running JS

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/ec9ee7b3-b578-4e97-af4d-f7a8d836a9b5)

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/30a92000-d569-4db8-9048-0a655187915e)
