### ISSUE TITLE
Remove double-click to exit fullscreen

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#4236]
People complain because it interferes with double-click to select a word.

I've added it because people complain it's not possible to exit full screen mode without the keyboard (e.g. tablet mode) but it's possible with two finger tap in touch screen.

I'll limit the exit with double click / double tap to 5% area in top right corner.

**Comment by GitHubRulesOK** [comment]
closes ? related https://github.com/sumatrapdfreader/sumatrapdf/issues/3927

previous closed https://github.com/sumatrapdfreader/sumatrapdf/issues/4149 and https://github.com/sumatrapdfreader/sumatrapdf/issues/3886

**Comment by mirh** [comment]
This is certainly a godsend for tablets.. though I wished there was any way to guess/know this behavior in advance?
