### ISSUE TITLE
Advanced Option will call Winedt to open SumatraPDF-settings.txt

### ISSUE THREAD

**Issue by DailyShana** [sumatrapdfreader/sumatrapdf#4237]
**SumatraPDF version**
- Version 3.5.x
no problem in previous versions

**Describe the bug**
If Winedt is installed, open advance option will call winedt to open `SumatraPDF-settings.txt`

**To Reproduce**

0. Install Winedt, without setting any file type associations
1. Open SumatraPDF, click Menu->Settings->Advanced Options...
2. Click on 'Advanced Options...'
3. Winedt is called to open `SumatraPDF-settings.txt`

**Expected behavior**
the default txtfile editor of OS (notepad) is called to open `SumatraPDF-settings.txt`

**File that reproduces the problem**
N/A

**Screenshots**
N/A

**Additional context**
The command line of calling Winedt is `"C:\Program Files\WinEdt Team\WinEdt 11\WinEdt.exe" "[Open(|C:\***\SumatraPDF-settings.txt|);SelPar(1,8)]"`, it seems that SumatraPDF is using the default inverse-searching command line for Winedt: `"C:\Program Files\WinEdt Team\WinEdt 11\WinEdt.exe" "[Open(|%f|);SelPar(%l,8)]"` to open `SumatraPDF-settings.txt`

**Comment by kjk** [comment]
Already fixed in latest pre-release: https://www.sumatrapdfreader.org/prerelease
