### ISSUE TITLE
Printing 2-on-1

### ISSUE THREAD

**Issue by IanJermyn** [sumatrapdfreader/sumatrapdf#424]
- Version 3.1.1, and the portable pre-release version, both 64-bit, no longer print 2 pages to a sheet.
- The pages come out blank, or occasionally black (I have not been able to isolate what triggers the black pages). Printing one page to a sheet, whether one-sided or duplex, is fine.
- This problem never used to occur. It now occurs with every pdf file I have tried.
- It does not occur on printing from any other pdf reader that I have tried (Adobe, Foxit, Google).

This is really disabling, and will mean I have to stop using Sumatra PDF, which I otherwise think is superb.

**Comment by pischky** [comment]
I have the same Problem using Win7 and HP Laserjet 1320n. Please fix!

**Comment by GitHubRulesOK** [comment]
Consolidating under https://github.com/sumatrapdfreader/sumatrapdf/issues/625 whilst the trigger here is 2-on-1 the result is a blank page (more than likely due to insufficient memory to throw the 2 pages contents)
