### ISSUE TITLE
Errors build, last several days (last 3-5 days) 

### ISSUE THREAD

**Issue by Avtukhoff** [sumatrapdfreader/sumatrapdf#4243]
**SumatraPDF version**
- Version 3.6 x64 

**Describe the bug**
**Last several days open-source can't builded.** 

**Visual Studio 2022 output:**

Сборка начата в 17:21...
1>------ Сборка начата: проект: SumatraPDF, Конфигурация: Release x64 ------
2>------ Сборка начата: проект: SumatraPDF-dll, Конфигурация: Release x64 ------
1>"go" не является внутренней или внешней
1>командой, исполняемой программой или пакетным файлом.
1>C:\Program Files\Microsoft\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: выход из команды "cd ../out/rel64\..\.. & go run ./do -gen-docs
1>C:\Program Files\Microsoft\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :VCEnd" с кодом 9009.
1>Сборка проекта "SumatraPDF.vcxproj" завершена с ошибкой.
2>"go" не является внутренней или внешней
2>командой, исполняемой программой или пакетным файлом.
2>C:\Program Files\Microsoft\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: выход из команды "cd ../out/rel64 & ..\..\bin\MakeLZSA.exe InstallerData.dat libmupdf.dll:libmupdf.dll PdfFilter.dll:PdfFilter.dll PdfPreview.dll:PdfPreview.dll
2>C:\Program Files\Microsoft\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: cd ..\.. & go run ./do -gen-docs
2>C:\Program Files\Microsoft\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :VCEnd" с кодом 9009.
2>Сборка проекта "SumatraPDF-dll.vcxproj" завершена с ошибкой.
========== Сборка: успешно выполнено — 0 , со сбоем — 2, в актуальном состоянии — 16, пропущено — 0 ==========
========== Сборка завершено в 17:21 и заняло 33.311 с ==========

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++                 Please consider donating to VSColorOutput                    +++
+++                       https://mike-ward.net/donate/                          +++
+++            (this message can be turned off in the settings panel)            +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by kjk** [comment]
You need to have Go installed

**Comment by Avtukhoff** [comment]
> You need to have Go installed

https://go.dev/dl/  ?

**Comment by Avtukhoff** [comment]
> You need to have Go installed

Install, but I have no computer internet, show many errors.

**Comment by kjk** [comment]
Make sure to restart after installing Go to ensure it's in PATH. Verify that in cmd or powershell if you type `go version`  it workds.

**Comment by Avtukhoff** [comment]
> Make sure to restart after installing Go to ensure it's in PATH. Verify that in cmd or powershell if you type `go version` it works.

Go.exe works without restarting.
Go version - unknown command.

Need computer internet, go try to load from github.com

**Comment by Avtukhoff** [comment]
> Make sure to restart after installing Go to ensure it's in PATH. Verify that in cmd or powershell if you type `go version` it works.

I do build. I'm remove pre-build event. All build OK.

**Comment by GitHubRulesOK** [comment]
I had similar problem so downloaded and unpacked latest `go1.22.3.windows-386.zip`
it does not need install IF you use a cmd redirection

go.cmd
```
C:\Users\lez\source\repos\sumatrapdf\go1.22.3.windows-386\go\bin\go.exe %*
```

**Comment by kjk** [comment]
```
"https://proxy.golang.org/github.com/dustin/go-humanize/@v/v1.0.1.mod": dial tcp: lookup proxy.golang.org: no such host
```
Yeah, this is go trying to download dependencies for my Go code. This will happen only once but you do need internet connection for that.
