### ISSUE TITLE
hyperlink rendering problem

### ISSUE THREAD

**Issue by uncopyrightable** [sumatrapdfreader/sumatrapdf#4246]
if a hyperlink is wrapped, the tooltip maybe only contains a part of the link

![图片](https://github.com/sumatrapdfreader/sumatrapdf/assets/16853651/3e7eeb12-6cbb-4c08-86ba-5887a917ccae)

**Comment by GitHubRulesOK** [comment]
hyperlinks like URL cannot be broken by a space or other breaking punctuation such as a line feed 
Hyperlinks can be auto built by plaintext thus the author should always fit on own line or remaining space without line break
or be allocated to an area of their own. Browsers may be more tolerant with that longer construct

**Comment by kjk** [comment]
Nothing I can do without a test file. It can just be incorrectly created file.

**Comment by uncopyrightable** [comment]
[测试已经换行的超链接.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/15359777/default.pdf)
here's the test file @kjk

**Comment by uncopyrightable** [comment]
[测试已经换行的超链接.docx](https://github.com/sumatrapdfreader/sumatrapdf/files/15359824/default.docx)
and the origin docx is also here, I use MS-WORD to save it as pdf.

**Comment by GitHubRulesOK** [comment]
@uncopyrightable 
Problem is not there in current [pre-release](https://www.sumatrapdfreader.org/prerelease) so no issue to fix (can not alter old programs only current)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/2ae4c22e-0298-4c0e-b4f8-c1a61ba33536)

**Comment by kjk** [comment]
This is badly written PDF. If you use `Toggle Show Links` command via command palette (`Ctrl + K`) you'll see that there are 4 links in PDF. The one you're complaining about simply has the bad URL. Here' what's in PDF file:
```
/URI(https://stackoverflow.com/questions/14379753/what-does-mean-in-python-function-def)
```
(you can use https://web.imhex.werwolv.net/ to inspect).

Sumatra just shows what PDF tells us.

**Comment by GitHubRulesOK** [comment]
@kjk 
I think there is a secondary factor at play, as you comment there are 4 URIs but all are accounted for. The problem stems from AUTO-URI from the plain text which happens with one but not the other (in theory should be 6 hyperlinks) and that is perhaps because of hyphenation ?

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/1a1d16e8-053a-46ca-aa3f-75637bc8ad38)

```
12 0 obj
<</Subtype/Link/Rect[182.3 754.32 507.55 769.92]/BS<</W 0>>/F 4/A<</Type/Action/S/URI/URI(https://python3-cookbook.readthedocs.io/zh_CN/latest/c07/p03_attach_informatinal_matadata_to_function_arguments.html)>>/StructParent 1>>
endobj

13 0 obj
<</Subtype/Link/Rect[87.75 738.72 250.57 754.32]/BS<</W 0>>/F 4/A<</Type/Action/S/URI/URI(https://python3-cookbook.readthedocs.io/zh_CN/latest/c07/p03_attach_informatinal_matadata_to_function_arguments.html)>>/StructParent 2>>
endobj
16 0 obj
<</Subtype/Link/Rect[214.22 707.52 507.55 723.12]/BS<</W 0>>/F 4/A<</Type/Action/S/URI/URI(https://stackoverflow.com/questions/14379753/what-does-mean-in-python-function-def)>>/StructParent 3>>
endobj

17 0 obj
<</Subtype/Link/Rect[87.75 691.92 155.42 707.52]/BS<</W 0>>/F 4/A<</Type/Action/S/URI/URI(https://stackoverflow.com/questions/14379753/what-does-mean-in-python-function-def)>>/StructParent 4>>
endobj
```
