### ISSUE TITLE
there is a white line in dark mode and maximize window

### ISSUE THREAD

**Issue by umaybe** [sumatrapdfreader/sumatrapdf#4247]
**SumatraPDF version**
- Version [e.g. 3.5.2, pre-release]

**Describe the bug**
As shown,there is a white line in dark mode and maximize window.Is there anyway to remove it?
It doesn't appear in light mode or non-maximize window.

**Screenshots**
![1](https://github.com/sumatrapdfreader/sumatrapdf/assets/170118628/fb8e1129-27ba-4d0d-8d19-80df6f8cbd1d)

**Comment by GitHubRulesOK** [comment]
I think it is more of a "Windows border thing" here with split screen we can see it is not just SumatraPDF but other imaged views with dark canvas.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/fc41d9f2-7f5e-4fd5-832f-ac8daf3de37a)

**Comment by kjk** [comment]
I'm not sure I have control over that. When you click maximize button all that happens is windows positioning the window. I don't draw any white lines explicitly.

And even if it's under my control, I have no idea what would that be.

**Comment by MathisP75** [comment]
This issue actually occurs on light mode too, it's just not very visible. It's the window border itself being visible when the window is maximized, for some reason. There's something wacky going on that makes it draw a border there, I've never seen another application with this issue.
Light mode (no accent color on window borders):
![Screenshot 2024-12-03 154813](https://github.com/user-attachments/assets/f4b345d5-be1b-4184-900a-7fe7e16fbbfc)

Dark mode (no accent color on window borders):
![Screenshot 2024-12-03 154758](https://github.com/user-attachments/assets/56e33e3b-f348-4fbc-9cce-75e73fa0b83f)

Light mode (accent color on window borders):
![Screenshot 2024-12-03 154847](https://github.com/user-attachments/assets/6c3cd2f2-89b6-402b-aa30-856889b1ed4a)

Dark mode (accent color on window borders):
![Screenshot 2024-12-03 154859](https://github.com/user-attachments/assets/f9acc597-73cb-40d7-ad64-9201ec10497e)

**Comment by MathisP75** [comment]
It also seems like there are two borders, including one inside the application itself. The PDF can overlap it, as seen in this screenshot.
![Screenshot 2024-12-03 154859](https://github.com/user-attachments/assets/926e9baa-14fe-4022-96d1-a8b8af38a577)

**Comment by MathisP75** [comment]
There are also issues with borders elsewhere, not to mention the other issues with text color. I love this reader, but dark mode is just in a sad state right now.
![image](https://github.com/user-attachments/assets/ada1bc5b-5bf2-4043-8e3d-ee9ae9e2a5ee)

**Comment by MathisP75** [comment]
Why is this issue closed?

**Comment by GitHubRulesOK** [comment]
The Issue was closed as not Specific to SumatraPDF so here we see Acrobat has a Windows supplied yellow surround thus it is Windows bug not a PDF reader bug.

![Image](https://github.com/user-attachments/assets/b5db2f53-7e2d-465c-8579-050bce5ab437)

**Comment by MathisP75** [comment]
@GitHubRulesOK This is not the issue at all. The issue does not occur when the window is tiled in this way, only when it is maximized. See the screenshots I sent for reference. 

Sumatra does something hacky that draws a bottom border when the application is maximized (it should have no border). Half of this border is even drawn behind the PDF pages (see screenshots).

**Comment by GitHubRulesOK** [comment]
I agree SumatraPDF compiled in Windows Visual C has a more noticeable border than some others but the colour is provided by WINDOWS THEMING see it is thicker in MS EDGE

![Image](https://github.com/user-attachments/assets/01d90198-44bc-45a6-b705-42512c3f860e)

![Image](https://github.com/user-attachments/assets/49e9e351-44ec-4c2a-a394-a72a37cb5d1b)

**Comment by MathisP75** [comment]
@GitHubRulesOK The borders from Microsoft Edge have nothing to do with this issue, so I don't know why they are brought up. You can even see in your first screenshot that there is a yellow line at the bottom of Sumatra PDF. This line should not be there and is due to an issue in Sumatra itself.

**Comment by MathisP75** [comment]
> I'm not sure I have control over that. When you click maximize button all that happens is windows positioning the window. I don't draw any white lines explicitly.
> 
> And even if it's under my control, I have no idea what would that be.

It's from the title bar. You somehow put a title bar at the bottom of the application. I noticed this because of MicaForEveryone, which allows setting the title bar color to follow the system theme. If I set it to dark and use the mica material, the white bar is now dark and uses the mica effect.

![Image](https://github.com/user-attachments/assets/182d3d6d-a98e-44f3-8773-0b1139127250)

**Comment by GitHubRulesOK** [comment]
The title bar and outer boundary is the Windows UI controls Same as Windows controls colour of scroll bar, these are all part of the Windows VISUAL studio controls as used when building C++ apps.

Hence the comment 
>And even if it's under my control, I have no idea what would that be.
It is how windows works with its own control colours. you can set the colour in Windows settings.

**Comment by MathisP75** [comment]
@GitHubRulesOK So you are telling me that Windows is putting a title bar element at the bottom of the app? I highly doubt it, given how many other sketchy GUI stuff Sumatra does.

**Comment by MathisP75** [comment]
Also, I don't know that weird version of the app you have, but the white part you are showing is controlled by Sumatra itself, not by Windows.

**Comment by GitHubRulesOK** [comment]
I change the border in windows
![Image](https://github.com/user-attachments/assets/3374984e-449a-473c-85d2-7818a11359a3)

![Image](https://github.com/user-attachments/assets/dde3c763-2678-4ced-af98-eb49686c7413)

**Comment by MathisP75** [comment]
I am on the latest preview build of SumatraPDF on Windows 11, and my application does not act at all like you are showing. The title bar color is the same as the toolbar color, it's unaffected by my Windows theme.

**Comment by GitHubRulesOK** [comment]
@kjk there are potentially 2 ways to avoid the problem neither are ideal ?

Perhaps the easiest is
In full screen mode either overcompensate the window to loose the double bordering. or find out why it is at -8 -8
Here I used Windows controls to alter the window height a few pixels so it goes out of view at the bottom.
Hence the green background is SumatraPDF canvas colour boundary without the blue border seen!.

![Image](https://github.com/user-attachments/assets/2919d448-89c5-4f11-804b-3d68bad12d6c)

It seems that there are some negative values in effect as when fullscreen with task bar the WinSpy reported position from windows is
 `(-8,-8) - (1928,1048)  -  1936x1056`
and then the border is visible 

![Image](https://github.com/user-attachments/assets/7655082d-6bb4-4d76-8938-bcf88977a8b6)

**Comment by GitHubRulesOK** [comment]
@RayKoopa 
trying to understand the ramifications but below the maximised state is a related entry https://github.com/sumatrapdfreader/sumatrapdf/blob/6cc426b6a6006ebae3ae8dbd6bfa98e7b3d6b0fe/src/Caption.cpp#L708

**Comment by GitHubRulesOK** [comment]
@RayKoopa 
most of that code is atleast 8-10 years old so probably worked from XP /Vista to 7 with aero and posibly even Metro but clearly there is likely a difference today with  DPI++ and Win'25

**Comment by GitHubRulesOK** [comment]
@RayKoopa 
Thanks for the extensive trace back whilst that endorses my comments that it s windows behaviour provided the border from way back when it seems the problem is there are manty SumatraPDF users on various versions of Windows that are not metro+

Thus any change needs to consider those that do and those that dont, "if it aint broke dont fix it"

Is there a means to add a IF win=10+ then dont Allow
// the manager assumes that this is a fullscreen
 // window and hides the taskbar and any topmost window. A simple workaround is to
 // expand the non-client border at the expense of client area.

**Comment by MathisP75** [comment]
Windows versions lower than 10 have long been EOL, and connecting them to the internet is a potential security risk. I don't think they should be considered for future updates.

**Comment by GitHubRulesOK** [comment]
@RayKoopa 
I can compile 32bit and test on my windows 7 & 10 
but need to know clearly what source code change you made so as to edit my custom build as it too has to allow for dedicated win 10x32 compiling

**Comment by GitHubRulesOK** [comment]
@RayKoopa 
Ok am replicating changes but this slow coal driven decades old landfill device will take about an hour to build and copy to the other "more modern" windows 7 devices!

**Comment by GitHubRulesOK** [comment]
@RayKoopa 
Mixed results It may be my custom build but runs on 10 not 7 Hmm I will need to try without personal mods

Windows 10 
2 out of 3 tests seem better but see last one
Win10 Maximised with toolbar off
![Image](https://github.com/user-attachments/assets/c1a1a9cf-b4d7-466c-9a55-6de5a9474d27)

Win10 Maximised with toolbar on (border not seen)
![Image](https://github.com/user-attachments/assets/64aa67ed-897c-48ee-9c19-bd324f135a1e)

In "snap" mode the border is still visible when maximised to half of screen
![Image](https://github.com/user-attachments/assets/6d198ca6-6949-4ea5-92ea-ac179c07d3e1)
