### ISSUE TITLE
Menu has white background in Dark theme

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#4249]
**SumatraPDF version**
- Version 3.6.16155 pre-release

**Describe the bug**

On right-clicking the title bar, the menu that pops up has a white background.

<img width=250 src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/6684884e-0b35-4dc3-93ae-cbe9ecdc94ab">

**Expected behavior**
It should have a black/grey background, just like in other apps (for e.g. Windows Settings app)

<img width=250 src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/257bcf50-b460-45a5-982d-14cf1341ae8a">

It is obviously not a high-priority issue, but more consistent theme would definitely be better.

**Comment by kjk** [comment]
This is drawn by Windows and the cost of fixing it (if at all possible) is not worth it.
