### ISSUE TITLE
Feature Request: -print adding wildcards to the name pdf file

### ISSUE THREAD

**Issue by xrichard1** [sumatrapdfreader/sumatrapdf#425]
Hello
on the command line printing
currently, we can print only one file at once with
option : -print-to $printer_name $file.pdf

Can you add the following functionality
to print multiple pdf files with the same command
adding wildcards to the name of the pdf file (*file.pdf or ?file.pdf)
Thank you

**Comment by kjk** [comment]
Sumatra is not designed to be a tool for mass printing of PDFs. We don't have plans to add this.
