### ISSUE TITLE
如果有类似 Compare two versions of a PDF file 功能就好了

### ISSUE THREAD

**Issue by k22725** [sumatrapdfreader/sumatrapdf#4251]
https://helpx.adobe.com/acrobat/using/compare-documents.html        Acrobat Pro 的 比较文件（Compare two versions of a PDF file）无法全屏（cannot fullscreen）也不能打开epub文件；SumatraPDF虽然能打开epub文件但没有 比较文件（Compare two versions of a PDF file）功能。  Compare two versions of a PDF file 可以很方便地学习外语（把原文pdf和用google翻译过的pdf比较，便于学习英语。很多产品都没有中文说明书，比如一些乐器【MIDI键盘、合成器、音乐制作软件】），或者检查说明书的翻译（很多电子产品都有中英文的介绍，但往往英文部分都有部分错误）是否有错误

**Comment by GitHubRulesOK** [comment]
ENGLISH PLEASE (请说英语！?)

https://helpx.adobe.com/acrobat/using/compare-documents.html 

Acrobat Pro's Compare two versions of a PDF file cannot be full screen or open ePub files; 

SumatraPDF can open ePub files, but it does not have the Compare two versions of a PDF file.

Compare two versions of a PDF file is a convenient way to learn a foreign language (compare the original pdf with the pdf translated by Google to learn English.)

Many products do not have Chinese manuals, such as some musical instruments [MIDI keyboards, synthesizers, music production software]), or check the translation of the instructions  for errors (many electronic products have Chinese and English introductions, but often the English part has some errors)

**Comment by kjk** [comment]
no plans to do that
