### ISSUE TITLE
如果能在像Chrome一样按“Ctrl + W”关闭最后一个标签页的时候也把“整个窗口”关闭就好了

### ISSUE THREAD

**Issue by k22725** [sumatrapdfreader/sumatrapdf#4252]
没办法，就把“SumatraPDF Options → Advanced → Use tabs”前的✔去掉（让打开的每个文档独立，这样就可以用“Alt + F4”关闭单个文档，不过如果把“Theme”设成“Dark”或“Darker”，在Windows 11下SumatraPDF的 “标题栏”  还是 “白色” 的）
我用[AutoHotkey](https://www.autohotkey.com/) 让鼠标侧键 XButton1 实现根据当前程序的受否为 Chrome 实现 关闭标签页 或 关闭窗口 的功能
XButton1::
{
	if WinActive('ahk_exe chrome.exe') ;如果 当前程序是chrome
		send '^w'	;发送“Ctrl + W”键，关闭标签页
	else	send '!{F4}' ;否则 发送“Alt + F4”键，关闭窗口
}

**Comment by GitHubRulesOK** [comment]
No way, just remove the "SumatraPDF Options →Advanced → Use tabs" (✔ make each open document independent, so you can close a single document with "Alt + F4", but if you set the "Theme" to "Dark" or "Darker", the "title bar" of SumatraPDF will still be "white" under Windows 11) 

I used AutoHotkey to make the XButton1 mouse button implement the function of closing tabs or closing windows for Chrome depending on the current program's acceptance
```
XButton1:: 
{ 
if WinActive('ahk_exe chrome.exe') ; If the current program is chrome 
send '^w' ; Send "Ctrl + W" keys to close the tab 
else send '! {F4}' ; Otherwise, send the "Alt + F4" keys to close the window 
}
```

**Comment by GitHubRulesOK** [comment]
@k22725 

You should be able to use ONE KEY to call `"Exit Application"` which should close all windows

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/47fa372e-9cce-4b28-bd60-c76512b043d6)
