### ISSUE TITLE
Debug symbols not recognized

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4254]
I know you have been trying to resolve the crash reporting  so this is really a placeholder for current status
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/d0047979-70c9-414e-8dc8-0c771ff12ef1)

**SumatraPDF version**
- Current 32bit pre-release both installed and standalone Windows 10 32bit 

**Describe the bug**
Unable to download debug symbols (although I can access them independently by URL)

**To Reproduce**
1. Go to Debug Download Symbols
2. Click
3. See error

**Expected behavior**
Success message

**File that reproduces the problem**
N/A

**Screenshots**
as above

**Additional context**
Am running as a user with admin group rights to access system
but there should be no issue with standalone as I can CURL the symbols file and can TAR (windows 10+) to extract.  
curl -o %latest%\SumatraPDF-%latest%-32.pdb.zip   https://files2.sumatrapdfreader.org/software/sumatrapdf/prerel/%latest%/SumatraPDF-prerel-32.pdb.zip

**Comment by GitHubRulesOK** [comment]
Perhaps unrelated ?
Windows 7 32 bit also has same issue unable to download debug symbols HOWEVER prior to that I had some issues trying to update.

Correctly it saw a pre-release update was available and downloaded one.exe BUT it was unable to unpack the 3 dll support files by replacement I had to delete the 3 .dll files and move exe out of Program Files (leaving the folder empty for a re-install !!)

**Comment by kjk** [comment]
Can you post the relevant part of the log (`Ctrl + K`, "show log"). I want to know what URL is the app trying access.

**Comment by kjk** [comment]
On my machine it actually downloads the symbols. I just show the message because they don't work as expected:
```
DownloadAndUnzipSymbols: symDir: 'C:\Users\kjk\AppData\Local\SumatraPDF-data\crashinfo-prerel-3.6.16209-32', url: 'https://www.sumatrapdfreader.org/dl/prerel/16209/SumatraPDF-prerel-32.pdb.lzsa'
HttpGet: url: 'https://www.sumatrapdfreader.org/dl/prerel/16209/SumatraPDF-prerel-32.pdb.lzsa'
ExtractSymbols: dir 'C:\Users\kjk\AppData\Local\SumatraPDF-data\crashinfo-prerel-3.6.16209-32', size: 16240029
ExtractSymbols: file 0 is 'libmupdf.pdb'
ExtractSymbols: file 1 is 'SumatraPDF-dll.pdb'
ExtractSymbols: file 2 is 'SumatraPDF.pdb'
CrashHandlerDownloadSymbols: HasSymbols() false after downloading symbols, gSymbolPath:''s
```

**Comment by kjk** [comment]
Same for 64-bit, probably broken by my changes to `gSymbolsPath`

**Comment by GitHubRulesOK** [comment]
HMM tail end of log  (there were many earlier entries from other usage)
starting with last file opening and last attempt in win 10 32bit with current 3.6.16209

```
FileWatcherSubscribe: not starting a file watcher thread due to 32-bit miscompilation
FileWatcherSubscribe: not starting a file watcher thread due to 32-bit miscompilation
CreateControllerForEngineOrFile: 'C:\Users\lez\Downloads\demo\after_merge-fixed.pdf', 2 pages
LoadDocument: 125.55 ms, 2 pages for 'C:\Users\lez\Downloads\demo\after_merge-fixed.pdf'
DisplayModel::BuildPagesInfo started
DisplayModel::BuildPagesInfo took 0.01 ms
FileWatcherSubscribe: not starting a file watcher thread due to 32-bit miscompilation
CrashHandlerDownloadSymbols()
DownloadAndUnzipSymbols: symDir: 'C:\Users\lez\AppData\Local\SumatraPDF-data\crashinfo-prerel-3.6.16209-32', url: 'https://www.sumatrapdfreader.org/dl/prerel/16209/SumatraPDF-prerel-32.pdb.lzsa'
HttpGet: url: 'https://www.sumatrapdfreader.org/dl/prerel/16209/SumatraPDF-prerel-32.pdb.lzsa'
ExtractSymbols: dir 'C:\Users\lez\AppData\Local\SumatraPDF-data\crashinfo-prerel-3.6.16209-32', size: 16240029
ExtractSymbols: file 0 is 'libmupdf.pdb'
ExtractSymbols: file 1 is 'SumatraPDF-dll.pdb'
ExtractSymbols: file 2 is 'SumatraPDF.pdb'
CrashHandlerDownloadSymbols: HasSymbols() false after downloading symbols, gSymbolPath:''s
```
Yes there is a folder and 3 files for user C:\Users\lez\AppData\Local\SumatraPDF-data\crashinfo-prerel-3.6.16209-32
