### ISSUE TITLE
Verify pre-release fast auto-update for all users / admin

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#4255]
Last two releases when I click on check for updates and there is a new version, when I click on install it exits. I download latest pre-rel and it installs fine.

**Comment by GitHubRulesOK** [comment]
which version windows 7/8/10/11 and 32/64bit
Installed / official portable
from which version to which version pre-release to pre-release?
other interference like AntiVirus ?

**Comment by kjk** [comment]
Yes, I added `-silent` flag which was not the right thing to do. Will fix.

**Comment by rjbprime** [comment]
Hi all, been having issues with pre-rel version 3.6.16341 (nor a previous version I had as well) not fully updating when clicking install and relaunch. Clicking the Install and relaunch button closes SumatraPDF, but the new popup only shows a yellow window with SumatraPDF v3.6.16345 written in it and a close button. Clicking the close button, then reopening SumatraPDF brings up version 3.6.16341. If it helps, I have SumatraPDF installed for all users in ``C:\Program Files\SumatraPDF\`` and I am **not** running SumatraPDF as admin, nor is it bringing up the UAC Secure Desktop popup.

Could this be looked into again?

**Comment by kjk** [comment]
Hm, in theory the installer should detect installation for all users and re-launch itself elevated when needed but maybe I broke that logic for the fast self-update (which only applies to pre-release builds because I was annoyed when frequently updating pre-release; in release it'll show the window and require pressing of install button).

**Comment by rjbprime** [comment]
10-4. Looking forward to it.

**Comment by kjk** [comment]
Ok, I see 2 bugs in `RunInstaller`, when using `fastInstall` and updating installed application:
* should preserve installation status of search filter and preview dlls
* should detect all users install

**Comment by GitHubRulesOK** [comment]
@kjk not absolutely sure this is addressed but recent changes may still not be "as was"

Method is "altered" and latest all users update  on Win7 32bit I did not see options
and after update the previewer is not functional, So I have to download again to see the options were not switched on

![Untitled](https://github.com/user-attachments/assets/0dde2332-d46d-4d6e-b927-e2c613b7984a)

After fresh re-install sane pre-release with options on then preview is working

**Comment by kjk** [comment]
I don't follow. Can you describe this step-by-step:
* I do X
* I do Y
* this happens
* I expect that to happen

**Comment by GitHubRulesOK** [comment]
I check if update is available and accept the new version each time
But it could have been old behaviour (not always the following daily) today is different it says it fails but  actually replaces EXE ? and  previewer is still active. HOWEVER it is the previous version DLL as none were replaced only the exe

![Untitled](https://github.com/user-attachments/assets/d582b862-814b-475b-b26b-1bf905235bcb)
[sumatra-log.txt](https://github.com/user-attachments/files/16464496/sumatra-log.txt)

**Comment by GitHubRulesOK** [comment]
On widows 10 same update goes well HOWEVER it is automatic without user control apart from after this point it elevates where as before it elevated then asked for user chosen options.

![image](https://github.com/user-attachments/assets/82e81726-dcc6-4b60-a1ec-691157eacede)

**Comment by GitHubRulesOK** [comment]
Just to repeat same problem today
![image](https://github.com/user-attachments/assets/63406966-2187-474d-add4-211604542385)

**Comment by kjk** [comment]
I fixed an issue not properly handling previous all users install.

For pre-release it's by design that in auto-update you don't get to change option. It's designed for frequent updates so minimal effort.

There still might be issues in certain scenarios but I really need complete information, including if it was previously installed, as all users, cmd-line flags if used etc.

And I really need step-by-step instructions so that I don't have to guess the missing information.

**Comment by GitHubRulesOK** [comment]
previously installed as per all options for all users then on daily update does not ask for elevated rights.

**Comment by kjk** [comment]
Thanks, that should be fixed in next pre-release
