### ISSUE TITLE
Request for adding Santali Language

### ISSUE THREAD

**Issue by Prasanta-Hembram** [sumatrapdfreader/sumatrapdf#4259]
I request adding Santali language to SumatraPDF. I cannot find it in the list of languages: https://www.apptranslator.org/app/SumatraPDF

**Comment by GitHubRulesOK** [comment]
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3909
Somebody will need to add the translation see how discussions went for Faroese in  https://github.com/sumatrapdfreader/sumatrapdf/discussions/4112

**Comment by Prasanta-Hembram** [comment]
Sorry for reposting without re-searching😅😅. Will post here #3909
