### ISSUE TITLE
Home page select button

### ISSUE THREAD

**Issue by NabeelGhallawenji** [sumatrapdfreader/sumatrapdf#4260]
on the home page, I suggest adding a select button that gives me the ability to select a bunch of books together to delete them at once from the home page

**Comment by GitHubRulesOK** [comment]
@kjk 
I was surprised to find "clear history" or "not remember" both
 remove pined and favorite thumbnails from home screen

**Comment by kjk** [comment]
@NabeelGhallawenji is `clear history` in command palette (`Ctrl + K`) good enough? It removes everything.

What is the use case for "remove a lot but not everything"? Right click for context menu is pretty fast.

If you want faster, how about pressing e.g. `r` (for 'remove') when over a thumbnail? Not very discoverable but would be faster than explicit selection.

@GitHubRulesOK Its just as likely that someone will be surprised that `Clear history` didn't clear everything.
