### ISSUE TITLE
Very slow rendering of long, single page PDF documents.

### ISSUE THREAD

**Issue by izMoff** [sumatrapdfreader/sumatrapdf#4267]
**SumatraPDF version**
3.5.2 x64

**Describe the bug**
If i open a moderately large .pdf document that is not split into separate pages, it renders very slowly. It can take 30+ second to even zoom in and have the portion of the document currently inside the window to finish rendering, and then whenever i have to scroll up or down quickly enough, i have to wait another 10+ seconds for things to show up.

In fact, the latest version (3.5.2) started to frequently hang up and become unresponsive for 10-20 seconds when opening\scrolling through such a document, which is something that was not happening with the previous version i had (3.4.6).

I tried opening such documents in browsers and some other .pdf reader programs, and they handle them without much trouble.

**File that reproduces the problem**
Here's one of the files i'm experiencing bad performance with:
[Basic Usage - ImageMagick Examples.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/15424699/Basic.Usage.-.ImageMagick.Examples.pdf)

**Comment by kjk** [comment]
It's already fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease

For me it works roughly like in 3.4.6

**Comment by izMoff** [comment]
> It's already fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease
> 
> For me it works roughly like in 3.4.6

You mean hang ups were fixed? Well, that's good, but overall performance with single page documents was still very bad in 3.4.6 and older versions i used.

**Comment by GitHubRulesOK** [comment]
@izMoff 
Those PDF are corrupt Edge will not work and Acrobat tell you why
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/b173ea3e-e450-420b-a70c-bb2784695efc)

PDF has a natural limit of 200" or roughly 5 m and that "PAGE" is too long.
If you want lng as from here to Mars the units must be changed to light years of say 22.5 minutes worth.

**Comment by GitHubRulesOK** [comment]
It will work best as 35 pages HOWEVER there are lots and lots of hyperlinks.
[Basic Usage -- ImageMagick Examples.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/15425581/Basic.Usage.--.ImageMagick.Examples.pdf)

If that line between pages bothers you, simply  set advanced options to 0 gap
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/f713eaff-ad9d-4bb9-9460-a07c190f8b90)

**Comment by izMoff** [comment]
> Those PDF are corrupt Edge will not work

Edge opens it up for me. That's the kind of file browsers produce when i save a webpage as pdf.

I'm curious, what program did you used to split my pdf into pages? Do i need Acrobat or something to do that?

**Comment by GitHubRulesOK** [comment]
@izMoff 
I used Opera save as pageS not save as one page which is difficult to keep inside the 200" barrier unless you read the size of output and scale according to that.
Whilst all PDF readers need to read a whole file to collect fonts and images for one page. They dont expect to render the **U**niverseof **T**ext **F**onts  just parts of it at a time. The problem with a runtime MEDIA format like PDF is that each sc-roll of the dice / mice means recalculation.
