### ISSUE TITLE
Local manual and keyboard shortcuts don't open

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#4269]
**SumatraPDF version**
latest pre-release: [3.6.16254]

**Describe the bug**
F1 and "Keyboard shortcuts" don't open from help menu
html help files located in
C:\Users\Henry\AppData\Local\SumatraPDF\manual-3.6.16209

**Comment by kjk** [comment]
Yeah, somehow manual wasn't included in the executable.

**Comment by hme3** [comment]
still not working in 16266. I assume the links to local help are coded in .exe not configuration?

**Comment by GitHubRulesOK** [comment]
@hme3 

confirmed now active in prerel-3.6.16271
AppData/Local/SumatraPDF-data/crashinfo-prerel-3.6.16271-32/SumatraPDF-documentation.html

**Comment by kjk** [comment]
Sorry about that, fixed.

**Comment by GitHubRulesOK** [comment]
@kjk that was unexpected for portable to unpack in localappdata rather than the local subfolder

**Comment by kjk** [comment]
Yeah, maybe I'll change that but I don't want to create many directories there. Maybe will switch to `sumatrapdf-data` directory with sub-directories for stuff.
