### ISSUE TITLE
Auto-Copy a selected word

### ISSUE THREAD

**Issue by kzelda** [sumatrapdfreader/sumatrapdf#427]
Hi , i want to autocopy a selected word , then the GoldenDict dico will translate it automatically,
please can you add this feature please.

**Comment by GitHubRulesOK** [comment]
@kjk I suggest consolidate this one with wider discussion in #1351

**Comment by kjk** [comment]
Consolidate under #1351

**Comment by kjk** [comment]
Actually, consolidate under #1280
