### ISSUE TITLE
Option to make home tab smaller and unclosable

### ISSUE THREAD

**Issue by ElvishScout** [sumatrapdfreader/sumatrapdf#4272]
I am expecting something like this:

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/89697570/dec0a56a-f0d5-4a55-a843-a743d527aa23)

instead of keeping the home tab taking much space in the title bar or hiding it completely.

**Comment by kjk** [comment]
Unfortunately tabs control we use only supports tabs of the same width.

Would have to re-implement all tabs handling for that small change. I'm not opposed to that but I don't have plans to work on that myself.
