### ISSUE TITLE
provide x86-64-v3 (AVX2) version

### ISSUE THREAD

**Issue by enihcam** [sumatrapdfreader/sumatrapdf#4273]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

> I'm always frustrated that AVX2 instruction is not fully utilized.

**Describe the solution you'd like**
> Please compile an AXV2 version with the parameter: /arch:AVX2
> Also Visual Studio 2022 has in the Property Pages an Enhanced Parameter for AVX2 (/arch:AVX2).

**Describe alternatives you've considered**
> N/A

**Additional context**
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/7010097/125def33-2f0f-4a8b-a09e-5bf4345889c6)

**Comment by ArmanHayots** [comment]
I have no faith in autovectorization; anyway underlying libraries such as MuPDF also need to be rewritten and rebuilt to use vector extensions.

**Comment by kjk** [comment]
You can compile with AVX2 if you want to. It's too much work for me to provide AVX2 builds.
