### ISSUE TITLE
when view chm the file, the app crashed if you click favorites in menu.

### ISSUE THREAD

**Issue by cyantau** [sumatrapdfreader/sumatrapdf#4277]
**SumatraPDF version**
- Version [v3.6.16272 64-bit]

**Describe the bug**
when view chm the file, the app crashed if you click favorite in menu.

**To Reproduce**
1. open chm file;
2.' ctrl B'  to add favorite page.
3. click menu->favorites
4. crashed.

**Expected behavior**

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

**Screenshots**

**Additional context**

**Comment by GitHubRulesOK** [comment]
@kjk 
side note 32 bit installer did not work so manually updated from download

CHM is an odd one as depending on position Favorite command invokes the browser !!
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/da429cfc-eb86-4508-94d9-a2716f9f9067)
