### ISSUE TITLE
Please Add New Features For Opening PostScript (.PS) and Device Independent (.dvi) Documents

### ISSUE THREAD

**Issue by imAnkan** [sumatrapdfreader/sumatrapdf#428]
Unable to Open PostScript (.PS) and Device Independent (.dvi) Documents in SumatraPDF. Please Add New Features For Opening PostScript (.PS) and Device Independent (.dvi) Documents

**Comment by timofonic** [comment]
It would be nice to have, indeed.

**Comment by kjk** [comment]
We already support PS files if GhostScript is installed. We don't have palns to support .dvi documents
