### ISSUE TITLE
Many errors building last version 

### ISSUE THREAD

**Issue by Avtukhoff** [sumatrapdfreader/sumatrapdf#4281]
See errors.txt from Visual Studio 2022 build

**Comment by Avtukhoff** [comment]
[errors.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/15464825/errors.txt)

**Comment by kjk** [comment]
It builds for me and on github ci: https://github.com/sumatrapdfreader/sumatrapdf/actions

Next time reporting issues like this:
* trim the compiler output to just show the error
* which exact git revision you're compiling
* which project you're building, which arch (x64? arm?) and config (Debug? Release?)
* did you make any changes to the code?
* does it still fail if you make a completely new checkout of the sources?
