### ISSUE TITLE
Foxit PDF Reader 12 not detected by Sumatra PDF.

### ISSUE THREAD

**Issue by mkim0710** [sumatrapdfreader/sumatrapdf#4283]
I noticed that Sumatra PDF does not automatically detect Foxit PDF Reader 12. I was able to add Foxit PDF Reader 12 manually by editing the SumatraPDF-settings.txt file in the ExternalViewers section as follows:
```
ExternalViewers [
	[
		CommandLine = "C:/Program Files (x86)/Foxit Software/Foxit PDF Reader/FoxitPDFReader.exe" /A page=%p "%1"
		Name = Foxit P&DF Reader
		Filter = *.pdf
	]
]
```
Despite this workaround, I was not able to assign a keyboard shortcut when adding ExternalViewers in SumatraPDF-settings.txt. Since Sumatra PDF already has a Command ID CmdOpenWithFoxIt, I wanted to utilize it directly.

To address this issue, I edited ExternalViewers.cpp to add the registry value for Foxit PDF Reader 12's path and made a pull request:
https://github.com/sumatrapdfreader/sumatrapdf/pull/4282

Could you please review the pull request and make any necessary revisions?

Thank you very much for maintaining this great software!

FYI: Foxit PDF Reader 12.1.3.15356 is the last version with the Add Bookmark function but without bugs in the single-key accelerator.

**Comment by kjk** [comment]
merged, thanks
