### ISSUE TITLE
Ability to display more than 2 columns of pages at a time

### ISSUE THREAD

**Issue by boredace** [sumatrapdfreader/sumatrapdf#4285]
Very often I view large multi-page PDF documents and need to quickly skim through their content. Currently I am only able to zoom out and view the document in maximum of 2 columns. On a big 4K monitor this leaves a lot of empty space on both sides and requires me to scroll down to see through the document.

It would be very useful to implement ability to show more than 2 columns of pages. The number of columns should be limited by available space. This could be implemented similar to PowerPoint slide sorter view or to Word multi-column view.

**Comment by GitHubRulesOK** [comment]
related to original request that has been expanded ! https://github.com/sumatrapdfreader/sumatrapdf/issues/246
However closing this as all others are reflected under umbrella https://github.com/sumatrapdfreader/sumatrapdf/issues/4184
