### ISSUE TITLE
thumbnails disappearing from sumatrapdfcache

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#4286]
thumbnails disappearing from sumatrapdfcache dir. I open pdf's thumbnails are in home tab. Close and open app some, (not all) are missing ?
v3.6.16283 64-bit

**Comment by kjk** [comment]
Are the files on a network drive?

By missing do you mean that the thumbnail is gone or do you mean that it's there but shows as a blank (white) square?

**Comment by kjk** [comment]
Also, are you sure that the files those thumbnails were for are still available?

**Comment by hme3** [comment]
Local drive, and blank white square. When I look in the sumatrapdfcache dir there are only four files. When I open one of the files on home tab a new image is created. I think they might be being deleted when I close the tabs?

**Comment by VernonStow** [comment]
Same problem here, thumbnails randomly disappearing on a local drive, Windows 10 Home, starting with the portable x64 builds on 27 May. (I have since reverted to an older build.)

**Comment by sergsako** [comment]
@kjk Sorry to say, the latest SumatraPDF pre-release build version 16328, built on 2024-06-01, portable x64 on Win10 21H2, no thumbnails at all on the Home page and even NO sumatrapdfcache folder in the fresh program's folder appear (after open / read / close many times).

**Comment by kjk** [comment]
@sergsako sorry about that. I just refactored thumbnail code and broke saving of thumbnails. Should be fixed in next pre-release.

**Comment by Dharmainiciativ** [comment]
Sometimes, especially in ebook files, the first page may be blank, but the cover is on the next page. I suggest taking this into account when creating sketches.
