### ISSUE TITLE
Epub line overlap bug

### ISSUE THREAD

**Issue by saadat99** [sumatrapdfreader/sumatrapdf#4297]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
The first two line of each chapter overlaps each other. This only affects some epub files.

**To Reproduce**
1. Open the file
2. Click on a chapter
3. See error

**Expected behavior**
The line should be clearly visible

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

**Screenshots**
![Uploading Screenshot 2024-06-01 183319.png…]()

**Additional context**

**Comment by saadat99** [comment]
![Screenshot 2024-06-01 183319](https://github.com/sumatrapdfreader/sumatrapdf/assets/25175193/9458c2f4-6b55-4219-9b70-885607502ac8)

**Comment by kjk** [comment]
Most likely it's already fixed in pre-release: https://www.sumatrapdfreader.org/prerelease

If not, I need a the file that shows the problem.
