### ISSUE TITLE
Advanced Settings file changes Recently require quit and reload

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4298]
**SumatraPDF version**
- Version [e.g. 3.6, current pre-release]

**Describe the bug**
In the past making advanced setting changes some required restart SumatraPDF and many were instantly honoured.
More recently perhaps since setting restructured most setting changes require full application restart.

**To Reproduce**
For example
1. Add a highlight in one colour
2. Change default colour in settings
3. SAVE settings and add a second highlight
4. Colour is no longer changed to new it retains old colour

**Expected behavior**
This and many other settings would be accepted for use in next action

**File that reproduces the problem**
N/A
**Screenshots**

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/60b4eb40-57fd-4082-ae39-8aff3fee280f)

**Additional context**

**Comment by kjk** [comment]
If you're using 32-bit version it's because to fix the crash caused by mis-compilation I had to disable the thread that checks for file changes, which includes settings file.

**Comment by GitHubRulesOK** [comment]
Hmms forgot to specify in version that I am only using 32bit ! 
I dropped self build when you added the pre-release "fix"
so if I revert to my own v142 build again can I expect that to work ? as it takes a while to keep rebuild

**Comment by kjk** [comment]
No, the disabling is still in the code.

You'll have to remove:
```c++
    if (IsProcess32()) {
        // https://github.com/sumatrapdfreader/sumatrapdf/issues/4111
        logf("FileWatcherSubscribe: not starting a file watcher thread due to 32-bit miscompilation\n");
        return nullptr;
    }
```

in `FileWatcherSubscribe` function.

**Comment by GitHubRulesOK** [comment]
Perfect it worked so back in sync (ish)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/751552f5-aaa2-4a82-a2be-8c853efd592e)

P.S. am I right in thinking settings are portable with exe because its dbg ?
 and can I expect that mod affects no FI download of help or is that a dbg thing
