### ISSUE TITLE
Horrible toolbar icons

### ISSUE THREAD

**Issue by phalonen** [sumatrapdfreader/sumatrapdf#4299]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
After updating to 3.5.2 from some old version, the toolbar icons have become horrible, colorless, minimalistic "modern" brainrot. The fit buttons are particularly offensive, and the print button looks like a pacifier.

**Expected behavior**
Icons have colour like the old ones, actually illustrating the function of the button.

**Comment by GitHubRulesOK** [comment]
tends to be the way SVG vector icons need coomon apperance 
so Windows Edge ![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/a966d83a-55ac-4ae7-985c-956188864ba3) Font Awesome 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/15b60147-bbc9-4e9a-a1ba-eec945f6e732)

Tablier SVG icons as used in SumatraPDF 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/a87fa641-a6d7-4509-998a-c2577d7b8433)
