### ISSUE TITLE
Opened pages lost on update

### ISSUE THREAD

**Issue by TinchoteSK** [sumatrapdfreader/sumatrapdf#4300]
**SumatraPDF version**
- 3.5.2 64-bit

**Describe the bug**
After I updated to version 3.5.2 (from 3.4.6, if I'm not wrong), all the documents I had opened, opened. But I had several instances of the same pdf opened. After the update, all instances are now on the same page. That is, I had 4 versions of the same pdf opened at different pages, and now they are all open on the same page. 

**To Reproduce**
1. Open two instances of the same pdf, on version 3.4.6. 
2. Go to different pages on each instance. 
3. Update to version 3.5.2.
4. Open Sumatra
5. Now both documents are opened on the same page. 

**Expected behavior**
I would expect each document to open at the page where it was before the update.

**Comment by kjk** [comment]
This is fixed in pre-release https://www.sumatrapdfreader.org/prerelease
