### ISSUE TITLE
Please make a linux version and destroy the competition

### ISSUE THREAD

**Issue by alishabbirhussain** [sumatrapdfreader/sumatrapdf#4301]
Hey Author/Authors, I am a long time Windows user. I recently, moved to linux. But I am having difficulty reading pdfs. All the pdf readers are either clunky or lack some feature in some aspect. I tried to find Sumatra Pdf reader which I used to use on Windows, I cannot find any. Please help. A lot of Linux users would be happy to use this awesome software.

Thanks

**Comment by kjk** [comment]
You can try running SumatraPDF under wine (disable tabs). But I'm not planning to make non-Windows versions. See https://www.sumatrapdfreader.org/docs/Why-only-Windows
