### ISSUE TITLE
Unable to display emoji expressions.

### ISSUE THREAD

**Issue by Cold-Stars** [sumatrapdfreader/sumatrapdf#4302]
**SumatraPDF version**
- Version [v3.5.2 64-bit]

**Describe the bug**
Unable to display emoji expressions.

**To Reproduce**
1. Export resume-zh.md to PDF using typora.[resume-zh](https://github.com/CarlossShi/markdown-resume)
2. [resume-zh.pdf](https://github.com/user-attachments/files/15544978/resume-zh.pdf)

**Screenshots**
Open in SumatraPDF：
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/113192545/b354412b-d513-4aa4-a54b-2c9a253f9f91)
Open in Edge:
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/113192545/104099b4-b92d-4c1f-83de-4bf4220ade4a)

**Comment by kjk** [comment]
happens in pre-release. The character can be copy&pasted but doesn't show. No warnings from mupdf.

**Comment by GitHubRulesOK** [comment]
Hmm it is not just MuPDF it is other viewers too here is tracker view
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/dfe17ae2-87e8-4297-8dc8-a36cca6e8f8d)

**Comment by Cold-Stars** [comment]
I solved this problem. This problem occurs when using emoji in the markdown title. I use HTML code to set the title and add emoji, and this problem does not occur.
