### ISSUE TITLE
Make scroll wheel zoom in / out symmetrical

### ISSUE THREAD

**Issue by xzytozidx** [sumatrapdfreader/sumatrapdf#4306]
**SumatraPDF version**
- Version 3.6.16341 pre-release

**Describe the bug**
When I zoom in the document by holding down the Ctrl key or using the right mouse button and the scroll wheel, the zoom levels are not as specified in SumatraPDF-settings.txt. In addition, zooming in behaves differently than zooming out. The steps are different in size.
If I zoom with the keyboard, i.e. Ctrl and +/-, everything is fine and works as expected.

**To Reproduce**
As described above.

**Expected behavior**
Normal zoom behavior, with zoomin steps according to the set levels in SumatraPDF-settings.txt

**File that reproduces the problem**
Every pdf file.

**Additional context**
Version 3.5.2 64-bit works fine.

**Comment by kjk** [comment]
That's working as designed and is considered an improvement in 3.6.

This is a continuous zoom option that wasn't available before and some people wanted. 

Additionally, it zooms around the current mouse position which is also something people wanted (when e.g. zooming a map or a technical drawing, you can pick the point around which to zoom).

For step-wise zoom you still have: keyboard bindings, toolbar icons, menu, `Ctr + Y` dialog and `Ctrl + K` command palette.

**Comment by xzytozidx** [comment]
Thanks for your immediate answer! 
Alright, I see. When zooming in with the wheel it ads 50 % of the actual zoom level. I. e. when you are at 300 % zoom, next step will be 450 %. When zooming out it halves the zoom level.
For me that is not intuitive and doesn't feel right 😅

Maybe you could make this behavior optional or even configurable like the "classic" zoom levels. That would be great, as I love the right-click-scroll-wheel zooming feature and use it a lot.

**Comment by kjk** [comment]
Ok, so that part should be improved. Zooming steps should be symmetrical i.e. if you zoom in and then zoom out by the same value, you should end up at the same level. I didn't get the math on zoom out right.

Of course "same value" is not precise. This is mouse wheel so it's not precise.

Note to self: it's CanvasOnMouseWheel

**Comment by kjk** [comment]
It's not my math day: I need to find a transform that reverses:
```
100 => 50
50 => 33
25 => 20
10 => 9
3 => 2.91
```
i.e. given 50 it returns 100. I.e. for 50% zoom in, the corresponding zoom out is 33%.

**Comment by user1823** [comment]
> This is a continuous zoom option

Yes, it is continuous in the sense that any value of zoom can be achieved by zooming in and out multiple times. But, this doesn't work like other PDF readers. The zoom level still "jumps" in Sumatra.

See the following screen recordings which show how the zoom level changes in MS Edge and Sumatra when I use the pinch gesture on the touchpad on the same PDF file.

Edge:
<video src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/5808894f-fc18-433b-8204-6c8ca4c9ba04"></video>

Sumatra:

https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/44a322a9-0905-4111-a8c2-ce5960361223

> I didn't get the math on zoom out right.
> I need to find a transform that reverses:

Just wondering, do you really need to figure this out on your own? I am sure that many open-source programs will have code to handle zooming (e.g. Chromium browser). Can't you just copy the code from there?

**Comment by kjk** [comment]
Sure, which code exactly? Chrome has millions of lines of code.

**Comment by user1823** [comment]
Sorry, I can't guide you where to look because I am not a developer.

**Comment by user1823** [comment]
I hope this will be useful: http://dev.to/danburzo/pinch-me-i-m-zooming-gestures-in-the-dom-a0e

**Comment by kjk** [comment]
@user1823 thanks, this is good info, will try some of those ideas

**Comment by kjk** [comment]
@user1823 BTW: the video of Sumatra zooming is either not 3.6 or not  with ctrl + mouse wheel. in latest pre-release with ctrl + mousewheel or pinch zoom we zoom continuously, like the video from Edge.

**Comment by user1823** [comment]
> the video of Sumatra zooming is either not 3.6 or not with ctrl + mouse wheel. 

It was with touchpad pinch gesture.

Here is a video with ctrl + mouse wheel:

https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/b3357749-88bb-4741-8a70-67a21d49a50e

SumatraPDF version 3.6.16345

**Comment by GitHubRulesOK** [comment]
@user please test tomorrow 2AM UCT with3.6.1637 or later
