### ISSUE TITLE
Use a different keyboard shortcut for "delete annotation"

### ISSUE THREAD

**Issue by luyaozou** [sumatrapdfreader/sumatrapdf#4307]
**Is your feature request related to a problem? Please describe.**
At least in the version of v3.5.2 64-bit, when editing annotation to a pdf file, if I press the "Delete" key, the annotation is deleted. However, this key is regularly used when I want to edit the text. Therefore, it is quite often that a long paragraph of text is accidentally deleted, and I have to retype everything. 

**Describe the solution you'd like**
It may be better removing this keyboard shortcut conflict to avoid accidental deletion of annotation. 

**Describe alternatives you've considered**
Alternatively, it may be considered to also determine the focused GUI widget when the "delete" key is pressed. If the text edition widget is in focus, the "delete" key should be applied only to the text, instead of triggering the deletion of the whole annotation. 

Many thanks !

**Comment by kjk** [comment]
This was a bug that is already fixed in pre-release version https://www.sumatrapdfreader.org/prerelease
