### ISSUE TITLE
Continuous zoom doesn't work

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#4312]
SumatraPDF version 3.6.16350

**Describe the bug**
The continuous zoom in Sumatra doesn't work like other PDF readers. The zoom level still "jumps" in Sumatra.

**Expected behavior**

<video src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/5808894f-fc18-433b-8204-6c8ca4c9ba04"></video>(with touchpad pinch gesture)

Sumatra:
<video src="https://github.com/sumatrapdfreader/sumatrapdf/assets/92206575/c461959a-4ca1-452c-a441-e74e48d3cca9"></video>

In the above video, I am using Ctrl + mouse wheel but the zoom is not continuous.

In another example, the zoom level follows this sequence:
18% → 26% → 39% → 59% → 89% → 133% → 200% → 299%

**Comment by kjk** [comment]
Part of it is sensitivity issue: if I scroll slowly, I get lower increments.

That being said, there's one improvements: during scroll wheel zoom processing I should remember initial zoom level and zoom according to summed up values of scroll wheel delta.

Currently each delta is processed individually so it multiplies each zoom step, which is exponential i.e. faster zooming.

**Comment by user1823** [comment]
> if I scroll slowly, I get lower increments.

If I scroll slowly, I get less "number of increments". However, each increment is still of the same size. For example, after 107%, I always get 161%, no matter how slowly I scroll.

> during scroll wheel zoom processing I should remember initial zoom level

I don't think that this is the issue. Other PDF readers also seem to process each step individually. I am saying this because the amount of zoom is the same whether I scroll continuously or I stop scrolling in between and then start scrolling again.

**Comment by kjk** [comment]
I tweaked zoom by mouse wheel once more in https://github.com/sumatrapdfreader/sumatrapdf/commit/d4bae84007a39933b3ba8fb0086c3de21d18979c

Here's a zoom progression on my thinkpad with ctrl + touchpoint:
```
[python] RDBG: delta: 4, accumDelta: 4, factor: 1.040000, newZoom: 122.638870
[python] RDBG: delta: 4, accumDelta: 8, factor: 1.080000, newZoom: 127.355759
[python] RDBG: delta: 4, accumDelta: 12, factor: 1.120000, newZoom: 132.072632
[python] RDBG: delta: 4, accumDelta: 16, factor: 1.160000, newZoom: 136.789520
[python] RDBG: delta: 4, accumDelta: 20, factor: 1.200000, newZoom: 141.506409
[python] RDBG: delta: 4, accumDelta: 24, factor: 1.240000, newZoom: 146.223282
[python] RDBG: delta: 4, accumDelta: 28, factor: 1.280000, newZoom: 150.940155
[python] RDBG: delta: 4, accumDelta: 32, factor: 1.320000, newZoom: 155.657028
[python] RDBG: delta: 4, accumDelta: 36, factor: 1.360000, newZoom: 160.373917
[python] RDBG: delta: 4, accumDelta: 40, factor: 1.400000, newZoom: 165.090790
[python] RDBG: delta: 4, accumDelta: 44, factor: 1.440000, newZoom: 169.807678
```

This is when slowly zooming. Results may vary on different hardware or when zooming faster.

**Comment by user1823** [comment]
> I tweaked zoom by mouse wheel once more

Thanks! I will try it when the pre-release becomes available.

However, I want to highlight that **the main focus of the current issue is zoom by touchpad pinch gesture**, not zoom by mouse wheel.

**Comment by kjk** [comment]
I tweaked pinch zoom via touchpad as well.

It works fine for me but it is subjective and there's no one way to translate touchpad / scroll wheel events to zoom level increases.

**Comment by user1823** [comment]
I have tried the latest update and it is better than the previous implementation. It is still not perfect but I am satisfied.

> there's no one way to translate touchpad / scroll wheel events to zoom level increases.

Yes, but in such cases, doing what commonly-used software do is the best way. For zoom, re-using Chromium's code would have been the best because zoom in Chromium works very well and the code is also open-source.

But, your current implementation is reasonably good and we can leave it as it is unless some bug is identified.

Thanks for all the work on improving the zoom function.
