### ISSUE TITLE
Duplicate Entries Of SumatraPDF In Installed Programs List

### ISSUE THREAD

**Issue by planetkalpesh** [sumatrapdfreader/sumatrapdf#4316]
I am using the latest prerelease version of SumatraPDF. When I opened Control Panel < Programs < Programs & Features, I see duplicate entries of SumatraPDF. I have attached a screenshot.
![Screenshot 2024-06-12 065359](https://github.com/sumatrapdfreader/sumatrapdf/assets/27500826/f92f6d60-9f33-4e44-baa9-d23dd42b56e7)

**Comment by kjk** [comment]
Have you installed with admin privileges?

**Comment by GitHubRulesOK** [comment]
:-) easily done !!
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/7d3ff8fe-c709-4492-9885-873c7b4e2286)
Uninstall the working one usually the newer date) and both should disappear after a warning the earlier one is not there ?
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/75f4c69d-a08f-40cc-81f7-3f561d15bf89)
on reinstall as admin I as sole user only see the one
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/fac33a8d-644f-4bb4-bc16-3816814fc211)

**Comment by planetkalpesh** [comment]
I have uninstalled the working one (usually the newer date) and both disappeared. Now I have reinstalled SumatraPDF with admin privileges and now there is only one entry in the list.
