### ISSUE TITLE
Printing on Samsung Universal driver

### ISSUE THREAD

**Issue by jorsolis** [sumatrapdfreader/sumatrapdf#432]
Hi,
I found a problem when you try to print over a Samsung printer.
When you use specific printer driver it seams to work right but when you try to use one of the Samsung universal printer drivers the print file in the queue is about 4 times its current size, then it needs big amount of time to send this file (depending on network speed between printserver and printer).
It doesnt happen with Adobe acrobat or with specific printer's driver.
Let me know.

**Comment by landrix** [comment]
Here the same. The printdata are very large.

**Comment by kjk** [comment]
If it's specific to a specific driver, there's nothing I can do about it.
