### ISSUE TITLE
Command Palette does not follow dark themes

### ISSUE THREAD

**Issue by plutonium-239** [sumatrapdfreader/sumatrapdf#4320]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
When the theme is set to either "Dark" or "Darker", the command palette is still in light mode (black-on-white).

**To Reproduce**
1. Change to a dark theme 
2. Open command palette by <kbd>ctrl</kbd>+<kbd>k</kbd>

**Expected behavior**
Command palette is also dark.

**Screenshots**
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/29684689/e51eab9c-a9ef-474f-b839-e20ad7ad7ce0)

**Comment by kjk** [comment]
fixed in latest [pre-release](https://www.sumatrapdfreader.org/prerelease)
