### ISSUE TITLE
Dark Mode Icons Are Hard To Recognize

### ISSUE THREAD

**Issue by camblsoup** [sumatrapdfreader/sumatrapdf#4328]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
Not super sure if this is a bug or feature request but in my mind it's something that isn't working as it should so I considered it a bug. Sorry if this is the wrong place for it.

When you change the theme to either Dark or Darker the icons become very hard to recognize from their original forms, they seem to still be in black with a slight white outline which makes it extremely hard to distinguish what some of them actually are. Screenshot below shows difference between light and dark modes.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/107598389/001e1dc5-6eea-4a14-8ec7-3fed9a881ee8)
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/107598389/1685a107-0fa5-45d7-88f6-c99f21f8b6a7)

**Comment by tactilis** [comment]
This is fixed in the 3.6 pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by camblsoup** [comment]
oh great to know! I'll close the issue and update to the preview.

Thanks a ton!
