### ISSUE TITLE
Recent Annotation "fix" update may have caused last 2 daily runs to fail

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4332]
**SumatraPDF version**
- Version Daily pre-release

**Describe the bug**
Recent Annotation "fix" update may have caused last 3 daily runs to fail however on latest daily run it first mentions an error in test util ?
```
D:\a\sumatrapdf\sumatrapdf\src\utils\WinUtil.cpp(3038,5): error C3861: '__cpuid': identifier not found [D:\a\sumatrapdf\sumatrapdf\vs2022\test_util.vcxproj]
```

**To Reproduce**
1. Go to https://github.com/sumatrapdfreader/sumatrapdf/actions/workflows/daily.yml

**Expected behavior**
a daily version produced

https://github.com/sumatrapdfreader/sumatrapdf/actions/runs/9574687637

**Comment by kjk** [comment]
fixed
