### ISSUE TITLE
New keyboard shortcut

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4338]
Could you please add keyboard shortcuts to go forward 10 pages, and back 10 pages, this is very useful for navigating PDF books.

Thanks!

**Comment by GitHubRulesOK** [comment]
You could adapt an old script I provided to jump any number of pages https://github.com/sumatrapdfreader/sumatrapdf/issues/3167
so simply-FY as simply **<kbd> Alt </kbd><kbd> F </kbd><kbd> J </kbd>**

**Comment by H5820121** [comment]
Thank you for replying!
How do I change the keyboard shortcut?


‫בתאריך יום א׳, 23 ביוני 2024 ב-19:47 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by H5820121** [comment]
Thanks for the script, but it requires first opening the file menu and
there running the script, but I mean a keyboard shortcut that will do it
directly, so much more efficient and convenient.

‫בתאריך יום א׳, 23 ביוני 2024 ב-19:47 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by GitHubRulesOK** [comment]
For jump + - and choice in advanced settings add or replace the viewers section with the correct location for the script

ExternalViewers [
	[
		CommandLine = "C:\some folder\jump.cmd" %p "%1"
		Name = send Pages to &Jump
	]
	[
		CommandLine = "C:\Users\some folder\jump.cmd" -10 %p "%1"
		Name = Jump &-10 Pages
	]
	[
		CommandLine = "C:\Users\some folder\jump.cmd" +10 %p "%1"
		Name = Jump &+10 Pages
	]
]

Jump.cmd
```
@echo off
setlocal ENABLEDELAYEDEXPANSION

set "num=" & set "page=" & set "result=" & set "flag=" & set "jump=" & set "move="
rem for testing echo %1 "%~2" "%~3" &pause

if .%2==. goto help
set "first=%1"
set flag=%first:~0,1%
rem for testing echo %flag% & pause
set move=%first:~1%
if "%flag%"=="-" set "num=%2" & goto back
if "%flag%"=="+" set "num=%2" & goto forward

Title=PageJumper&color 9F&mode con cols=56 lines=8
set /a "num=%1"
if %num%==0 goto help

echo/ &echo  Current page is %num%
echo  Enter +## for jump forward pages and -## for jumpback
echo  For example current is %num% so + 10 is forward by 10
echo  Out of possible range can NOT work so +100 stays put.
echo/
set /p "jump=? Remember include + or - ? "
goto got

:back
shift & set "jump=-%move%" & goto got
exit /b

:forward
shift & set "jump=+%move%" & goto got
exit /b

:got
set /a "result=%num% %jump%"
rem for testing echo %result% &pause
if %result% LEQ 1 set "result=1"
rem for testing echo %result% &pause
"C:\Program Files\SumatraPDF\SumatraPDF.exe" -reuse-instance -page %result% "%~2"
exit /b

:help
echo Need both a current page number and filename
pause
:eof
```

**Comment by H5820121** [comment]
Thanks for the detailed reply I appreciate it very much!
But it still requires you to go to the file menu first, and there select
this option. If it were possible to set a shortcut key to activate it
directly, it would be much more efficient.

‫בתאריך יום א׳, 23 ביוני 2024 ב-22:24 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by GitHubRulesOK** [comment]
the shortcut is like all file menu shortcuts UNDERLINED  so 3 keys ALT + מ ? + plus or minus

**Comment by H5820121** [comment]
Great, as a temporary solution it's very good and now I'm using it, but
isn't it more elegant and quick to have such a useful thing built into
"SumatraPDF"!?
At a minimum, it will be possible in the advanced settings to set a
keyboard shortcut for External Viewers.

On this occasion I would like to thank you personally for all your help on
the forum, It's priceless!

‫בתאריך יום א׳, 23 ביוני 2024 ב-23:13 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by GitHubRulesOK** [comment]
The prior question I linked was where a previous "similar" request was made and rejected in that format, I have not closed this as "duplicate" and leaving open since @kjk has not commented but we will see ?

**Comment by GitHubRulesOK** [comment]
@kjk 
A possible soloution would be to have a user variable + - pages in settings that affect the <- and -> icons  (currently +1 -1)

Then the key CMDpage previous next (as tied to those icons) could be user assignable if they wish ? perhaps leave one of the other page commands as historic simpler +&-1

**Comment by H5820121** [comment]
Thank you for replying!
I will be happy to see it in 3.6 Pre-release.


‫בתאריך יום ב׳, 24 ביוני 2024 ב-20:18 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by kjk** [comment]
In pre-release 16374 or later (https://www.sumatrapdfreader.org/prerelease) you can do:

```
Shortcuts [
	[
		Cmd = CmdGoToNextPage 10
		Key = b
	]
]
```
This creates shortcut `b` for advancing 10 pages.

You can do same for `CmdGoToPrevPage`

See https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts

**Comment by H5820121** [comment]
@kjk <https://github.com/kjk>
Great, I use it and it helps me a lot and I'm sure it will help a lot of
others as well.
Thank you!


‫בתאריך שבת, 29 ביוני 2024 ב-23:32 מאת ‪Krzysztof Kowalczyk‬‏ <‪
***@***.***‬‏>:‬
