### ISSUE TITLE
On multi-monitor, the "About" dialog box always open on left monitor.

### ISSUE THREAD

**Issue by ehoffman2** [sumatrapdfreader/sumatrapdf#434]
Sumatra 3.1.1

I have multi-monitor setup (3 monitors), and currently Sumatra is opened on the center monitor (the one I mostly work on).

If I open the About dialog box, it always open at the same place on the top left of the left monitor instead of the current monitor.

Other dialog boxes doesn't have this issue (the ones I tried).  They open relative to the main window position.

**Comment by ehoffman2** [comment]
To add, this happen in the following condition:
- I have Windows explorer in the left monitor.  I double-click a PDF, and since PDF are associated with Sumatra, Sumatra open in center monitor, my main display.
- I go to about, and the about dialog open on left monitor.

If I start this by having the Windows explorer on the right monitor, while Sumatra was previously closed, then Sumatra open, in center monitor.  I go to About, and the About dialog appear on the right monitor.

This may have to do because the About dialog is created with no parent/owner:
```
void OnMenuAbout()
    [...]
    gHwndAbout = CreateWindow(
            ABOUT_CLASS_NAME, ABOUT_WIN_TITLE,
            WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU,
            CW_USEDEFAULT, CW_USEDEFAULT,
            CW_USEDEFAULT, CW_USEDEFAULT,
            nullptr, nullptr,
            GetModuleHandle(nullptr), nullptr);
    [...]

```
And thus, the default location seem to be based on which monitor the application was invoked from (From Windows Explore

**Comment by GitHubRulesOK** [comment]
@kjk 
Just to confirm that on 2 monitors its similar behavior in current SumatraPDF
That is SumatraPDF will display as per settings on any monitor but the about box is displayed relative to the monitor used at the time of launch, which could be a monitor with desktop shortcut (not just exploer windows).
Either understandable "per design" relative to launch pad or About could look at current working monitor and be placed above the canvas same as Document Properties does?
