### ISSUE TITLE
'j' and 'k' scrolling particularly slow.

### ISSUE THREAD

**Issue by simuleite** [sumatrapdfreader/sumatrapdf#4340]
**Is your feature request related to a problem? Please describe.**
I figured when I scrolled through keyboard j and k, it scrolled slowly. And there seem to be no options provided to control the speed of scrolling.

**Describe the solution you'd like**
I'd love to scroll faster with j and k. 
I have tried to set my mouse to move 10 lines at a time, but it only works when I use a touchpad (I'm using a laptop and there's no mouse).

**Comment by simuleite** [comment]
I found the same problem. #1680

**Comment by GitHubRulesOK** [comment]
@simuleite 
there are otherkeys for scroll such as up down arrow which have + SHIFT acceleration so unsure if you could add those as an settings option  like N M are shifted up and shifted down ??
