### ISSUE TITLE
Keyboard shortcut for copying path of current file

### ISSUE THREAD

**Issue by NoePfister** [sumatrapdfreader/sumatrapdf#4341]
**Is your feature request related to a problem? Please describe.**
I often need to copy the path of the current file. For this I need to right-click the tab and then select "copy path". This always takes a lot longer than needed for such a simple task-

**Describe the solution you'd like**
I would like that a Shortcut gets implemented for copying the current path of the file.

**Describe alternatives you've considered**
If a shortcut isn't possible, then maybe a butten directly in the taskbar is possible.

**Comment by GitHubRulesOK** [comment]
Highly unlikely to be added as a button (needs 100% maintenance and unlikely to be used by 99% users)
The current ability was the last greatest improvement its 2 clicks so shorter than leave mouse for 2 or 3 keys
**Functionality is CmdCopyFilePath so try assign that to a single key**

**Comment by kjk** [comment]
Using latest pre-release (https://www.sumatrapdfreader.org/prerelease) you can add your own shortcut (https://www.sumatrapdfreader.org/docs/Customizing-keyboard-shortcuts) for `CmdCopyFilePath` command.

You can also use `Ctrl + K` for command palette and type part of `copy file path`

**Comment by GitHubRulesOK** [comment]
@NoePfister 

Just to confirm while viewing with any tab in sight I can set CTRL + F  (or any other free single key) to capture the path&filename, naturally I need somewhere to use it.
```
Shortcuts [
	[
		Cmd = CmdCopyFilePath
		Key = Ctrl + F
	]
]
```
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/6867150f-4136-4bee-8ce6-85accf2e7ea1)
