### ISSUE TITLE
Add `Commands` section to advanced settings

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#4348]
Related to https://github.com/sumatrapdfreader/sumatrapdf/issues/4346

Maybe add a way to define new commands, like:
```
Commands [
  [
    Id = CmdTranslateSelectionWithGoogle
    Name = Translate Selection With Google
    Cmd = CmdLaunchBrowser https://translate.google.com/?op=translate&sl=auto&tl=${userlang}&text=${selection}
    Flags = selection
    Key = Ctrl + h
  ]
]
```
Flags would be `selection` to indicate this for handling selection, `viewer` (indicate this is like `ExternalViewer`) 

`Key` is optional because it could also be assigned via
```
Shortcuts [
  [
    Cmd = CmdTranslateSelectionWithGoogle
    Key = Ctrl + b
  ]
]
```

Those commands would show up in command palette.

The I could upgrade settings file and convert `SelectionHandlers` and `ExternalViewers` to `Commands` section and deprecate them.

**Comment by GitHubRulesOK** [comment]
@kjk there is also related https://github.com/sumatrapdfreader/sumatrapdf/issues/3998

**Comment by kjk** [comment]
So instead of adding `Commands`, I achieved the same functionality by:
* adding `Key`, for defining a keyboard shortcut, to `ExternalViewers` and `SelectionHandlers`
* adding `Name` to `Shortcuts`

Maybe will also add `Id` to `Shortcuts`, not sure of utility of it.
