### ISSUE TITLE
Error path

### ISSUE THREAD

**Issue by GilbertoSilverio** [sumatrapdfreader/sumatrapdf#435]
Hi,
Via the command line does not accept the path found:

"C:\Sumatra\sumatrapdf "+ALLTRIM(cFILE)

pdf file location : 
![image](https://cloud.githubusercontent.com/assets/17176595/12975280/892ff692-d0a1-11e5-80f9-5d5bf67503d2.png)

Error: 
![image](https://cloud.githubusercontent.com/assets/17176595/12975299/adb4783a-d0a1-11e5-95a9-5dc9ade0587f.png)

if retired space folder name acts:
NOVA TE = erro  
NOVA_TE = OK

Thanks.

**Comment by kjk** [comment]
You have to properly quote the argument. If path has a space, it has to be "foo bar.pdf", not just foo bar.pdf

**Comment by GilbertoSilverio** [comment]
Hy

How am i doing...


​How should be

Thanks




2016-02-11 18:02 GMT-02:00 Krzysztof Kowalczyk <notifications@github.com>:
