### ISSUE TITLE
how to remove this element?

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [sumatrapdfreader/sumatrapdf#4351]
![sshot-001](https://github.com/sumatrapdfreader/sumatrapdf/assets/73518754/44450d2a-050c-476c-a97a-b5874dbdc56b)

**Comment by kjk** [comment]
You can't

**Comment by subsubsubsubsubsub** [comment]
> You can't

the developers don’t give you the option to remove it, the poor design of this element spoils the design as a whole
