### ISSUE TITLE
Cannot open another file on the same path as a new tab

### ISSUE THREAD

**Issue by scscgit** [sumatrapdfreader/sumatrapdf#4356]
**SumatraPDF version**
- 3.5.2

**Describe the bug**
SumatraPDF assumes that a file on the same file path is always the same file. This often may not be the case, for example if you use an app that creates a temporary PDF file before opening it in your default viewer, as it may reuse the same path twice.

**To Reproduce**
1. Create a file with content A named path/a.pdf
2. Open the file
3. Replace the file, deleting it and creating a file with content B named path/a.pdf
4. Open the file

**Expected behavior**
This should be configurable, because some people may prefer each file only opening once. Some people may instead prefer the active tab updating its content whenever the file changes. In my case, I want the previous tab to stay open, and I want to open a second tab with the new file content.

Either the optional configuration just lets us open duplicates each time, or there could be an intelligent check using file size, date of last change, or a file hash.

**Additional context**
As another side-effect, when you use File / Save As..., the most up-to-date file is copied to a new location even if there is still an old document open in your memory. Honestly, I'd really like it if there were an option to export an open document "from memory" as a way of saving an otherwise lost file.

**Comment by kjk** [comment]
You can press `r` to reload the current tab.

**Comment by kjk** [comment]
Also, when you do `File / Open` menu or drag&drop, we open in a new tab.

Only double-clicking finds the tab.

I might add `compare sizes` logic and maybe open in a new tab if `ctrl` is pressed.

But I will not add a new settings for that. Too many settings is a bad thing.

**Comment by GitHubRulesOK** [comment]
@scscgit 

If I am reading your request correctly you have a HARDDISK.ext of A contents and you want to replace with HARDDISK.ext of B contents  then that is EDITING a file and there cannot be 2 different copies Which is why Syncronised drives cause problem as there are 2 candidates for the same disk sector!

**Comment by scscgit** [comment]
@GitHubRulesOK
I think you're talking about something else - I wasn't implying that both files are with the same filename **at the same time**, rather it's just the result of **editing** the file. The step 3 was "_Replace the file, deleting it and creating a file with content B named path/a.pdf_". Sure, one way to prevent it would be taking a lock on the file, but the current behavior without the lock is preferable.
> SumatraPDF looks for the signal the file has changed and replaces deleted contents A with new contents B.

Currently it ignores the changes, you have to manually reload the file. (I don't want it to reload, I'd switch to a different PDF viewer if it did.)

About the "Save As", I'm not sure why you talk about deleting file contents, we usually save to a new location. The problem is just that SumatraPDF doesn't save the file content that has been loaded in memory, even though that's what you typically expect from all apps with a "Save As" functionality (In Word, you'd never expect a different content to be saved than what's in the memory and displayed) (Some PDF viewers can for example annotate the file, effectively really editing it). If you have plenty of documents open without knowing which ones have been modified, using "Save As" is always risky, and for new users who don't double-check their newly created file, they may lose work by assuming they've saved the most current document.

> Only double-clicking finds the tab.

Yeah in that case it's opened by Explorer, but it can also be done by any other app. If we want to use SumatraPDF as a default PDF viewer, it needs to be able to work with temp files created by those apps. In the meantime I'll probably switch to using Edge...
