### ISSUE TITLE
FictionBook2: Poetry's tags

### ISSUE THREAD

**Issue by Skif-off** [sumatrapdfreader/sumatrapdf#436]
SumatraPDF vs. FictionBook Editor:
![123](https://cloud.githubusercontent.com/assets/6333198/13014184/0871d18e-d1cc-11e5-8fc9-cb24ff15b948.png)

I understand that SumatraPDF has basic support format FB2, but if SumatraPDF will read `<v></v>` as `<p></p>`, then it would be the easiest solution. Is it possible?

Test file:

```
<?xml version="1.0" encoding="utf-8"?>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0" xmlns:l="http://www.w3.org/1999/xlink">
 <description>
  <title-info>
   <genre>poetry</genre>
   <author>
    <nickname>x</nickname>
   </author>
   <book-title>Poetry-test</book-title>
   <lang>en</lang>
  </title-info>
  <document-info>
   <author>
    <nickname>x</nickname>
   </author>
   <program-used>FictionBook Editor Release 2.6.7</program-used>
   <date value="2016-02-12">12 February 2016</date>
   <id>0891E8AB-1FB3-443E-89C7-C72AE2601E27</id>
   <version>1.0</version>
  </document-info>
 </description>
 <body>
  <title>
   <p>Poetry's tags</p>
  </title>
  <section>
   <title>
    <p>For example</p>
   </title>
   <p>Max</p>
   <poem>
    <title>
     <p>The End</p>
    </title>
    <stanza>
     <v>This is the end</v>
     <v>Beautiful friend</v>
     <v>This is the end</v>
     <v>My only friend, the end</v>
    </stanza>
    <stanza>
     <v>Of our elaborate plans, the end</v>
     <v>Of everything that stands, the end</v>
     <v>No safety or surprise, the end</v>
     <v>...</v>
    </stanza>
    <text-author>The Doors</text-author>
   </poem>
   <p>Min</p>
   <poem>
    <stanza>
     <v>This is the end</v>
     <v>Beautiful friend</v>
     <v>This is the end</v>
     <v>My only friend, the end</v>
    </stanza>
    <stanza>
     <v>Of our elaborate plans, the end</v>
     <v>Of everything that stands, the end</v>
     <v>No safety or surprise, the end</v>
     <v>...</v>
    </stanza>
   </poem>
  </section>
 </body>
</FictionBook>
```

**Comment by Skif-off** [comment]
Maybe:
```
void Fb2Formatter::HandleHtmlTag(HtmlToken *t)
...
else if (t->NameIs("cite"))
        HandleTagAsHtml(t, "blockquote");
else if (t->NameIs("poem"))
        HandleTagAsHtml(t, "blockquote");
else if (t->NameIs("v"))
        HandleTagAsHtml(t, "p");

```
?

Maybe ```text-author``` -> ```<p align="right">``` too.

**Comment by GitHubRulesOK** [comment]
It always  perplexes me why it requires a dozen characters in <XML> </XML> simply to defile a space or enter key what is wrong with <PRE>the boy stood on the burning dock\n </PRE>

**Comment by Skif-off** [comment]
@GitHubRulesOK 
Well, yes, it looks more bulky, but structured text is good: we can easily convert XML to any format or get exactly needed info from tag.

**Comment by GitHubRulesOK** [comment]
I understand but the whole point of tags is to avoid confusion thus I see /p as < end paragraph > not < end poem > and why are single lines tagged with a v why is it not  < l > a line of a stanza</l>

**Comment by SumatraPeter** [comment]
There's no point debating why Dmitry Gribov chose `<v></v>` to denote "An individual line in a stanza" (as mentioned in the official [FB2 schema](https://github.com/gribuser/fb2/blob/master/FictionBook.xsd#L346)). The only question is whether Sumatra (or MuPDF, whichever's responsible) will support the FB2 schema properly or not (and perhaps [FB3](https://github.com/gribuser/FB3) as well).

**Comment by Skif-off** [comment]
MuPDF supports FictionBook2 since v.1.10, is it possible to replace internal `Fb2Formatter` on MuPDF engine?

**Comment by GitHubRulesOK** [comment]
Closing as legacy issue now well supported via MuPDF  engine
![image](https://user-images.githubusercontent.com/12754913/152653210-684d3df8-81a6-4ba8-9902-29035036b02a.png)
