### ISSUE TITLE
Setting to auto-capture text when highlighting and populate the annotation's contents with the highlighted text

### ISSUE THREAD

**Issue by shern15** [sumatrapdfreader/sumatrapdf#4360]
### Discussed in https://github.com/sumatrapdfreader/sumatrapdf/discussions/4359

I highlight a lot of text in my PDF textbooks and right now the only way I can find to populate a Highlight annotation's contents with the text I am highlighting is to CTRL + C the text before highlighting, then A, then CTRL + V into the Contents box when the Edit Annotation window appears.

It would be great if there was a Setting that I can enable so that I can just press 'a' (or whatever shortcut for the desired highlight color) and have the Contents box of the annotation automatically populated with the highlighted text.

Thank you for your time!

**Comment by GitHubRulesOK** [comment]
Hmm it was that way at one time but there were complaints about having to delete long contents !

You cant Please all of the readers all of the time, so agree it would be a nice option to paste or not paste the selection and currently there is the opposite  request to delete the clipboard change !!! So 3 different points of view so far.

Current PreRelease is **middle ground** highlight press A = AUTOclips the text for paste.
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/83ab57f3-abad-4040-90f3-4473cd93a4ad)

**Comment by GitHubRulesOK** [comment]
@kjk 

you proposed to add the auto paste along the lines of

```
Shortcuts [
	[
		Cmd = CmdCreateAnnotHighlight #00ff00 autopopulatecontent
		Key = a
	]
]
```
 but there is another request to not copy in first case so perhaps also needs a **"nocollectselection"**

**Comment by kjk** [comment]
The argument is `setcontent`

**Comment by GitHubRulesOK** [comment]
Nice still Works in newest supported Web Browsers (K-Meleon 76.5 in this case )
![image](https://github.com/user-attachments/assets/db6dc840-21d0-451d-857e-a3593009a5cc)
