### ISSUE TITLE
Text to Speech Engine

### ISSUE THREAD

**Issue by SNgari** [sumatrapdfreader/sumatrapdf#4361]
Can you kindly add a text to speech engine that can be used to read out loud the contents of the document opened? 

One that can start from any part of the document. Edge's Read aloud tool only starts from page 1 and you can't start anywhere else.

**Comment by GitHubRulesOK** [comment]
Not that simple as the page data is just binary numbers NOT text. So often the numbers are translated in Audio in wrong order or garbled but the ink number for those numbers still looks good as pixels. This is called character to font mapping  and the cause of many failures to read out loud. In addition not all visible characters have a font equivalence so some text cannot be read without OCR.

**Comment by GitHubRulesOK** [comment]
Edge can start Read Aloud on Page 2 no problem (other than the usual out of order!) just tested this discussion starting page 2 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/9b1a0a73-a3d0-421b-8f4e-56c6edea14d7)

**Comment by SNgari** [comment]
Thank you for explaining that. 

With the pdf I'm using, it always jumps to page 1 to start reading. I'll use my phone to get it to read out loud. Librera usually works well. 

Thank you.

**Comment by SNgari** [comment]
Thank you for explaining that. 

With the pdf I'm using, it always jumps to page 1 to start reading. I'll use my phone to get it to read out loud. Librera usually works well. 

Thank you.

**Comment by GitHubRulesOK** [comment]
@bin-2 one of the reasons SumatraPDF has often had issues with, and thus copy paste for TTS, has been the way PDF text objects are not in logical order and are often in differing boxes. Thus your TTS would need to do a Structured Text extraction then parse the page top to bottom and whilst JScript MuPDF does have such ability it is not the one seen by its PDF reader.

So here your TTS does not see the text that SumatraPDF has extracted on the right, but SumatraPDF has not been told to use SText order.  and in fairness my Balcon script also says the page is blank without text as that is part of the core issue with find text.

The first task of TTS needs to be sort the PDF page into human sounding top to bottom text order. PDFtoTEXT should be able to do that as a prerequisite.

<img width="749" height="496" alt="Image" src="https://github.com/user-attachments/assets/de456d24-9c07-443d-9450-31f0f2ab3adf" />

**Comment by GitHubRulesOK** [comment]
@Bin-2 

My comments were not intended to discourage your improvements to SumatraPDF
Simply point out any limitations .
HOWEVER to be accepted as a 3rd party improvement it needs to be FOCUSED on one aspect thus seperate annots docking and bookmarks and TTS into separate Pull Requests
Look at the most recent accepted was many files but only one thing was improved at that pull Request https://github.com/sumatrapdfreader/sumatrapdf/pull/5562
Same with pending PR it is focused on ONE task https://github.com/sumatrapdfreader/sumatrapdf/pull/5611
