### ISSUE TITLE
BUG in the keys of Up / Down

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4362]
In the latest versions of 3.6 (in the versions after June 30) there is a bug in the display of Fit Page & DisplayMode = single page , in the keys of Up / Down, in both the result is only a transition to the previous page.

**Comment by GitHubRulesOK** [comment]
I dont know if that is a bug Right and Left arrow are move next and previous pages
up and down are **"scroll"** (within page) which does not apply in fit page,
If you want that function remap the keys to duplicate right a page lefta page

**Comment by H5820121** [comment]
This is a bug, because in the versions up to the June 30 version it worked
correctly!

‫בתאריך יום ו׳, 5 ביולי 2024 ב-3:02 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬
