### ISSUE TITLE
Has the option to set a keyboard shortcut for ExternalViewers already been introduced to the pre-release version?

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4363]
Has the option to set a keyboard shortcut for ExternalViewers already been introduced to the pre-release version, what is the command?

**Comment by H5820121** [comment]
By the way, it would be very helpful if there was an orderly documentation of what was already added in the pre-distribution versions, the documentation on the website is not updated!

**Comment by GitHubRulesOK** [comment]
The documentation is regularly updated and downloaded as F1, but there can be a short delay and experimental features may not always be shown until released.

**Comment by H5820121** [comment]
1. For example, there is no documentation added, to the new CmdGoToNextPage
command.
2. And what with I asked "Has the option to set a keyboard shortcut for
ExternalViewers already been introduced to the pre-release version?"

‫בתאריך יום ו׳, 5 ביולי 2024 ב-3:13 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by GitHubRulesOK** [comment]
CmdGoToNextPage is there see this image where I typed cmdgoton
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/5e3165af-08ff-4f87-8874-f5f7e3cfded3)

and obviously there is no additional CMD for external apart from the previous 19 under `External app`

**Comment by H5820121** [comment]
The CmdGoToNextPage command is an old command, I mean there is no
documentation added of what has now been added *argument*:
[
        Cmd = CmdGoToNextPage *10*
        Key =
    ]

‫בתאריך יום ו׳, 5 ביולי 2024 ב-17:16 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by H5820121** [comment]
@GitHubRulesOK
 "19 under External app"
I don't understand what you mean,you can configure only up to 10 external
viewers,
What I ask is that they be given the option to set a keyboard shortcut.
Thanks!


‫בתאריך יום ו׳, 5 ביולי 2024 ב-18:45 מאת אברהם ברוך ***@***.***
‬‏>:‬

**Comment by GitHubRulesOK** [comment]
@H5820121 

`CmdGoToNextPage 10` is experimental (only in current pre-release) and experimental features are not always documented until released

In the documentation there are currently 19 different external viewer options
without the Custom File Open with anything else via shell or browser. 
Hence there is a need to decide on how all those & more extras may eventually be handled.
So the reduce from 3 to 1 or 2 issue is still open, as currently ALL extras, need 3 keys for their Custom HotKey Combination.
There is oportunity to rationalise expanding all existing 19 options and use more for between 100-200 Key combinations

**Comment by H5820121** [comment]
Great, thank you very much!

‫בתאריך יום ב׳, 15 ביולי 2024 ב-18:09 מאת ‪Krzysztof Kowalczyk‬‏ <‪
***@***.***‬‏>:‬

**Comment by GitHubRulesOK** [comment]
note toolbar icons support has now been added in latest 3.7 (pre-release)

**Comment by H5820121** [comment]
> note toolbar icons support has now been added in latest 3.7 (pre-release)

@GitHubRulesOK 
Could you please explain more what exactly you mean?

**Comment by Klaus1189** [comment]
https://www.sumatrapdfreader.org/prerelease
