### ISSUE TITLE
Please set a keyboard shortcut for ExternalViewers

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4366]
Is it possible please to give option to set a keyboard shortcut for ExternalViewers?
 Thanks!

**Comment by GitHubRulesOK** [comment]
closing as repeat of https://github.com/sumatrapdfreader/sumatrapdf/issues/4348

**Comment by GitHubRulesOK** [comment]
note this has now been added in latest 3.7 (pre-release)

**Comment by H5820121** [comment]
> note this has now been added in latest 3.7 (pre-release)

@GitHubRulesOK 
Could you please demonstrate this, so that I can better understand what you mean?

**Comment by Klaus1189** [comment]
https://www.sumatrapdfreader.org/prerelease

**Comment by GitHubRulesOK** [comment]
@H5820121 The uses of shortcuts and taskbar icons mean you can either press a key or click the text and it run any of your external commands so here I use my loupe.cmd but it can be anything via the keys or ToolbarText
```
	[
		CommandLine = "C:\Users\WDAGUtilityAccount\Desktop\Apps\Programming\c#\microscope\spyglass.exe"
		Name = &Magnifier
		Filter = *.*
		Key = Ctrl + Alt +m
		ToolbarText = Loupe
	]
	[
		CommandLine = "C:\Windows\System32\mshta.exe" "C:\Users\WDAGUtilityAccount\Desktop\Apps\PDF\SumatraPDF\18214\argtest.hta?file=%1"
		Name = &HTA
		Filter = *.*
		Key = h
		ToolbarText = Find
	]
```
<img width="965" height="549" alt="Image" src="https://github.com/user-attachments/assets/5113b543-2404-4a14-a3eb-0f90ccf50db9" />

**Comment by H5820121** [comment]
@GitHubRulesOK 
Thank you very much for the clear explanation!
