### ISSUE TITLE
Documentation HotKey F1

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4367]
**SumatraPDF version**
- Version pre-release

**Describe the bug**
Currently experimental key F1 is not listed in documentation

<html>
<body>
<h3 id="help" style="box-sizing: border-box; margin: 1rem 0px 0.3rem; letter-spacing: -0.01em; font-weight: 600; font-size: 1.25rem; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box;">Help</strong></h3></body>
</html>

```
   Command IDs    | Keyboard shortcuts | Command Palette  
----------------- |  ----------------- | ---------------
CmdHelpOpenManual |                    | Help: Manual
```

**Expected behavior**

```
   Command IDs    | Keyboard shortcuts | Command Palette  
----------------- |  ----------------- | ---------------
CmdHelpOpenManual |   F1               | Help: Manual
```

**Screenshots**

**Additional context**

**Comment by H5820121** [comment]
It would be very helpful that F1 of the pre-release version will also have
a record of what will be added up to that pre-release version, for the
benefit of users of the pre-release version so that they can test the
experimental features.

‫בתאריך שבת, 6 ביולי 2024 ב-23:01 מאת ‪GitHubRulesOK‬‏ <‪
***@***.***‬‏>:‬

**Comment by kjk** [comment]
@H5820121 it's included in `Version History` page (on website https://www.sumatrapdfreader.org/docs/Version-history)

**Comment by H5820121** [comment]
Thanks a lot!

‫בתאריך יום ג׳, 23 ביולי 2024 ב-17:50 מאת ‪Krzysztof Kowalczyk‬‏ <‪
***@***.***‬‏>:‬

**Comment by H5820121** [comment]
@kjk <https://github.com/kjk>
I think we'll forget, the new definition for ExternalViewers "Key = " :
ExternalViewers [
    [
        CommandLine =
        Name =
        Key =
    ]

‫בתאריך יום ג׳, 23 ביולי 2024 ב-17:58 מאת אברהם ברוך ***@***.***
‬‏>:‬

**Comment by kjk** [comment]
Thanks, added a note to version history
