### ISSUE TITLE
Google translation not working for multiple languages

### ISSUE THREAD

**Issue by xit77** [sumatrapdfreader/sumatrapdf#4368]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
Google translation with Korean language doesn't work. 
(Possibly some other languages too)

**To Reproduce**

1. Change language to Korean.
2. Open any document.
3. Try to translate any word using Google translate
4. It translate into wrong language.

**Expected behavior**

Translation into Korean

**File that reproduces the problem**

**Screenshots**

**Additional context**

Note that
"ko" is ISO-639 language code for Korean.
"kr" is ISO-3166 country code for Korea.

It seems that "tl=<lang>" parameter in Google translate URL is from UILanguage in setting,
and UILanguage seems like country code, not  language code.

I think you can just omit "tl=" parameter and default seems to be last used language or user's language.

**Comment by ngoclong19** [comment]
I think this is an issue with multiple languages.
For example, the query string `tl` in Google Translate is mapped to these values for Vietnamese, Chinese (Simplified), Chinese (Traditional) as `vn`, `cn`, `tw`, respectively.

According to MS document, it should be `vi`, `zh-CN`, or `zh-TW`.
`https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/70feba9f-294e-491e-b6eb-56532684c37f`
Google Translate seems to follow this convention.

Maybe the problem code lies in this file `do/trans_langs.go`.

**Comment by GitHubRulesOK** [comment]
Hmmm

@KJK there seems to be a need to separate ui code from query language
As @ngoclong19 has identified SumatraPDF uses `kr` and Google translate expects `ko` I had to manually switch Google from **K**anu**r**i

```
# You're not expected to change those manually
UiLanguage = kr
```
![image](https://github.com/user-attachments/assets/124184f2-cd01-407b-ab65-aa4dcaac6d27)

**Comment by GitHubRulesOK** [comment]
@xit77 
you need to provide an alternative until it is altered

![image](https://github.com/user-attachments/assets/5237b7b5-f83f-4ab4-bd47-9a8caba2cd1f)
```
SelectionHandlers [
  [
    URL = https://translate.google.com/?op=translate&sl=auto&tl=ko&text=${selection}
    Name = 구글 번역 (&T)
  ]
]
```

**Comment by xit77** [comment]
@GitHubRulesOK,

Thanks for looking into this issue and info about SelectionHandler.
I just tested with modified config and it works well -- It will be enough for me, for now.

**Comment by kjk** [comment]
I fixed all mentioned here (armenian, belarusian, catalan, czech, korean, vietnamese, chinese traditional and simplified) but possibly not all.

It's a matter of going through https://github.com/sumatrapdfreader/sumatrapdf/blob/master/do/trans_langs.go, finding corresponding https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes and veryfing that it's recognized by google translate's `tl=` arg.
