### ISSUE TITLE
characters in epub not displayed correctly

### ISSUE THREAD

**Issue by dbenham3** [sumatrapdfreader/sumatrapdf#4369]
**SumatraPDF version**
- Version [e.g. 3.5.1]

**Describe the bug**
i have an epub which has character 0x201C (double quotes), but it is display as 2 boxes

**Comment by GitHubRulesOK** [comment]
First ensure you test using pre-release as there cannot be changes to 3.5.1 unless you edit the ePub

2nd not all fonts support u+201C so a sample with that exact font style is needed to see if any other font change is needed for the unknown character.

**Comment by dbenham3** [comment]
I'm not editing the epub, but just displaying it.
I opened the file using 7zip and then display the contents to determine the character in error.
there is no mention of a font in either the chapter html file or the css file for it.
there is this though - "<meta content="text/html; charset=iso-8859-1" http-equiv="content-type"/>"

attached is the epub. (but as a .zip file)
[agatha christie - 1957 - 4-50 from paddington (miss marple).zip](https://github.com/user-attachments/files/16135378/agatha.christie.-.1957.-.4-50.from.paddington.miss.marple.zip)

**Comment by GitHubRulesOK** [comment]
@dbenham3 
Thanks

Hmm we have seen this before where it is not ideal to be using Unicode for devices that dont always have such default fonts.
Equally without declaration times and Helvetica in a PDF would behave similar, but here Edge will use my Sans Serif preference.
The use of sloping `"` is odd normally they would be paired for left and right but here both are the same and ideally should be simple keyboard characters for ease of search.

![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/1a05d52f-1eed-452b-a22d-be940efa74d3)

**Comment by dbenham3** [comment]
here's what it looks like in sumatra when i read it.
![screen print](https://github.com/sumatrapdfreader/sumatrapdf/assets/46389971/aa83255f-a40a-4dc7-aead-99503ca156f7)

**Comment by kjk** [comment]
Does it work correctly in any other epub viewer?

This is an econding issue. The file claims to be:
```
  <meta content="text/html; charset=iso-8859-1" http-equiv="content-type" />
```
but is really encoded with utf-8. We display what the file tells us, it just lies to us about the encoding.

If you remove this line from all `.html` files, it should show correctly.

It's possible to try to detect and correct this, but it would be heuristic that might break other, correct files, so I don't want to do it.

**Comment by dbenham3** [comment]
I don't have any other epub viewer.

I extracted the files and changed charset in chapter1 html, then zipped them up, don't it doesn't display at all, just the 3 images.

I've gone through other agatha christie epubs i have and some are ok, some have the same issue.

I'll write a java program to adjust the epub file, and see how I go.

thanks

**Comment by GitHubRulesOK** [comment]
@dbenham3 
For your info the epub like a DocX is a "set" of pages in a zip so when you extract to edit the files they need to be dropped back into the same zip location in a COPY to be in original "relative" positions then rename the zip to .epub

Here I only did one page manually in MS Notepad but you can use a find and replace editor like word with vba or even notepad with vbs sendkeys to handle multiple pages.

The key is to replace `'` and `"` with normal keyboard characters and save as ANSI rather than UTF8. then put the page back as an overwrite.

![image](https://github.com/user-attachments/assets/96b7e0c6-02e7-41d9-8d1b-6a51aa4de217)

**Comment by dbenham3** [comment]
ok, thanks.
you can close this issue
as there is no issue with Sumatra,
rather the issue is with epub file.

**Comment by dbenham3** [comment]
ok, thanks.
you can close this issue
as there is no issue with Sumatra,
rather the issue is with epub file.
