### ISSUE TITLE
feature request:night mode

### ISSUE THREAD

**Issue by marletto** [sumatrapdfreader/sumatrapdf#437]
normally, a pdf file is black character + white background, 
I wish to show pdf as white character + black background.

**Comment by adrsta** [comment]
Yes! that exactly the feature I am missing ;]

For me it would be enough just to swap those foreground with background colors.
That would work for a lot of simple documents already.

And extra would be to  make the links lighter (usually there are in dark blue or dark red).

**Comment by johndob** [comment]
I would like to have that too

**Comment by SicariusNoctis** [comment]
You can already do this. Add the following lines to your Advanced Options:

```
MainWindowBackground = #555555
UseSysColors = false

FixedPageUI [
	TextColor = #d7d7d7
	BackgroundColor = #2f2f2f
	SelectionColor = #f5fc0c
]
EbookUI [
	TextColor = #d7d7d7
	BackgroundColor = #2f2f2f
	UseFixedPageUI = false
]
```

**Comment by marletto** [comment]
@SicariusNoctis, thanks very much, solved my problem.
There is still a minor issue: how to customize the bookmark view's text color and background color?

**Comment by FSund** [comment]
This is available using Themes in the latest [pre-release](http://www.sumatrapdfreader.org/prerelease.html) version of Sumatra, v3.2.10662, via Settings -> Theme -> Dark/Darker.

**Comment by johndob** [comment]
and why is it missing in newer 3.2.10688 ?

**Comment by kjk** [comment]
Theming was an experiment but it's not ready and most likely I won't be able to make it ready for the next release so it was (temporarily?) removed.

**Comment by JJenkx** [comment]
I found the solution. My setup is all black boarders and black start-up screen and total black in full-screen with white text.

Setting/Advanced Options, add line **GradientColors** to **FixedPageUI** then choose your hex color. Here is my setup for all black and white.

    MainWindowBackground = #000000
    EscToExit = false
    ReuseInstance = false
    UseSysColors = false
    RestoreSession = true
    
    FixedPageUI [
    	TextColor = #ffffff
    	BackgroundColor = #000000[enter image description here][1]
    	SelectionColor = #f5fc0c
    	WindowMargin = 2 4 2 4
    	PageSpacing = 4 4
    	GradientColors = #000000
    ]

[![][1]][1]

[1]: https://i.stack.imgur.com/vMHOQ.png

**Comment by nimafazeli** [comment]
Hi,
I see that on the [website](https://www.sumatrapdfreader.org/docs/Command-line-arguments.html) the command line argument `-invert-colors` is flagged to be removed. I think it is a very useful feature and it should not be removed. 
My use case is that I build from source very often and I can implement the command line argument into a custom build script. Specially in the dim light and when my editor is also in a dark color scheme, suddenly switching to a bright screen is hard on eyes.

**Comment by GitHubRulesOK** [comment]
@kjk perhaps consolidate with "I can not create a dark theme" #1023

**Comment by kjk** [comment]
This falls under theming support i.e. #898
