### ISSUE TITLE
16406 crashes after install

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#4370]
crashinfo-prerel-3.6.16406-64\sumatrapdfcrash.txt
https://gist.github.com/hme3/a8def8c5ef1aa4ededde29fddb0bba0e

**Comment by GitHubRulesOK** [comment]
Hmmm
well I can emulate if I set a false command shortcut too so change bad shortcut and add a valid one like 

```
Shortcuts [
	[
		Cmd = 
		Key = Ctrl + F
	]
]
```
to avoid the crash change to following or a valid one
```
Shortcuts [
	[
		Cmd = CmdNone
		Key = Ctrl + F
	]
]
```

**Comment by R-Goc** [comment]
Still, a bad user config leading to a crash isn't good behavior. This should either do nothing or give a good message. 
The exception is at line 315 of commands.cpp
<HTML>
<head>
<title>Document</title></head>
<body>


  | Name | Value | Type
-- | -- | -- | --
◢ | parts | {first=0x0000000000000000 <NULL> nextPageSize=256 size=0 } | StrVec
  | ◢ first | 0x0000000000000000 <NULL> | StrVecPage *
  | next | <Unable to read memory> |  
  | pageSize | <Unable to read memory> |  
  | nStrings | <Unable to read memory> |  
  | currEnd | <Unable to read memory> |  
  | nextPageSize | 256 | int
  | size | 0 | int



</body>
</HTML>
Idk why the call stack in the report shows StrVec.cpp+178 while VS debugger just shows ParseCommand. 
Either a check for definition being a null byte(0 length string) should be added into ParseCommand or shortcut->cmd being a null byte.

**Comment by hme3** [comment]
That fixed it, but I don't remember putting that shortcut there.

**Comment by GitHubRulesOK** [comment]
@R-Goc 
currently Experimental shortkeys for commands is WIP (Work in progress). Thus you can see from recent commits we are only partway through changing number of parameters, thus I suspect this is a temporary hiccup in the current EV switch from 3 to 4 lines

**Comment by R-Goc** [comment]
Actually looks like this was never handled explicitly. It would just go down one of the early returns for a command not matching any known commands. But now 
```  
StrVec parts;
Split(parts, definition, " ", true, 2);
const char* cmd = parts[0];
```
happens before 
```
int cmdId = GetCommandIdByName(cmd);    
```
which(or it's earlier equivalent) would be giving an early return with -1 to signify that a command doesn't match
So the case where parts[0] is null slips through

**Comment by kjk** [comment]
Sorry about that, I pushed work in progress.

I've made emergency build **16409**. It doesn't yet show on pre-release page (cloudflare caching) but if you do `check for uppdated` from the app it should see and download it.
