### ISSUE TITLE
Font works in ToC but not in actual book 

### ISSUE THREAD

**Issue by unkn0w7n** [sumatrapdfreader/sumatrapdf#4377]
**SumatraPDF version**
- Version 3.5.2

**Describe the bug**
In windows OS, the font (telugu/Hindi) that shows up in the ToC/bookmarks bar dont show up in epub text. I would've ignored it if fonts did not work even in the ToC bar.

**Screenshots**
![image](https://github.com/user-attachments/assets/b3457024-78fe-431f-a392-d88334d2ca73)

**Additional context**
If its supposed to be a unicode thing, its in utf-8 only.

**If this is no a bug, please turn it into a feature request. If this is somehow related to javascript, which I heard that sumatra doesn't support, close this..**

**Comment by kjk** [comment]
Please try with pre-release https://www.sumatrapdfreader.org/prerelease - it has some font fixes.

If doesn't work in pre-release, I need the file to investigate (see https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports)

**Comment by unkn0w7n** [comment]
Its the same in pre-release too.

 the epub is in the [test.zip](https://github.com/user-attachments/files/16263344/test.zip).

**Comment by kjk** [comment]
Will be fixed in next [pre-release](https://www.sumatrapdfreader.org/prerelease) 16427 or later

**Comment by unkn0w7n** [comment]
so many changes! Thanks a lot.
