### ISSUE TITLE
Make enginedump part of SumatraPDF

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#4388]
EngineDump project often fails to compile because it's not part of default build in CI.

It's only a single file, so merge put it inside SumatraPDF itself, with `-engine-dump` cmd-line option.

Potentially only in debug build, as it's a debug functionality. On the other hand, it's not much code so maybe enable it always.

**Comment by R-Goc** [comment]
If added into Sumatra, would Escape() need fixing not to leak?

**Comment by kjk** [comment]
Wouldn't hurt but, again, it's a debug only code and the app exists after processing, so not a priority.

**Comment by kjk** [comment]
Not really finished (code is commented out). Will finish it if I ever need to run that code.
