### ISSUE TITLE
Scailing around center

### ISSUE THREAD

**Issue by JimmyRequa** [sumatrapdfreader/sumatrapdf#439]
When the size of a page  view is modified by pressing the + or - key or using the mouse to pick zoom controls, it would be more convenient if the center point of scaling were the center of the area displayed instead of the top left corner.  This would make it easier to get a closer look at what is interesting (by pressing +)  or to get a look at the context (by pressing -).

**Comment by GitHubRulesOK** [comment]
@kjk directly related to #481 where zoom on touch screen is applied in similar fashion

**Comment by GitHubRulesOK** [comment]
@kjk 
Without focus zoom naturally works around the common datum (top left)

With a selected word/image , marquee or scrolling mouse (with ConTRoL) the focus is shifted to zoom about that location.

IF the default zoom focus was shifted plus half viewport X & Y, this would seem more "natural" to most users.
ALSO if then it applies to pinch zoom, should (even if not fully addressing zoom about pinch point),  at least appear to be more acceptable to the majority.

**Comment by SumatraPeter** [comment]
I suggest closing this and consolidating with #481 as master.

**Comment by kjk** [comment]
Consolidate under #481
