### ISSUE TITLE
Changing the icon colors to white while using dark mode

### ISSUE THREAD

**Issue by epicfloppadev** [sumatrapdfreader/sumatrapdf#4390]
**Is your feature request related to a problem? Please describe.**
Well when using darkmode the icons are pixelated? (correct me) 
![image](https://github.com/user-attachments/assets/235c7669-6798-4612-b0c6-3d6c68205860)

**Describe the solution you'd like**
well just invert the colors on the icons

**Additional context**
thank you for reading this.

**Comment by kjk** [comment]
This is improved in [pre-release](https://www.sumatrapdfreader.org/prerelease) but in the end we're limited by what Microsoft's toolbar control allows.
