### ISSUE TITLE
Annotation: Copy Paste Error

### ISSUE THREAD

**Issue by CritterCritter** [sumatrapdfreader/sumatrapdf#4392]
**SumatraPDF version**
- Version [e.g. 3.5.2, pre-release]

**Describe the bug**
I want to copy a text from another PDF and paste it there as an annotation comment.
However, when I mark a text and press A on the marked text, then it is not possible to paste my copied text anymore - because it pastes the marked text instead, into the content field of annotation. 

**To Reproduce**
1. open pdf1
2. open pdf2 in a separate window 
3. copy a text from pdf1
4. mark a text in pdf2
5. Press A
6. Press Ctrl-V (or right click and "Insert") to paste text from step 3
7. It will paste text in step 4 instead

**Expected behavior**
I would expect that it pastes exactly what I've copied before. I cannot imagine at all why this could be intended behaviour!
I have to recopy and repaste in order to get it work.

**File that reproduces the problem**
Seem to work with any PDF

**Screenshots**
n/a

**Additional context**
I really love your small tool, you have done a great work here!

However, the annotation feature is not great. In fact I have two other remarks about it:
1.) It is very hard to find that feature, especially if you want to make comments (even though I knew it must be somewhere)! My only solution was to look for help and keyboard shortcuts instead. That's poor accessibility. I would STRONGLY expect a comment/annotation button instead - which is not greyed-out anymore as soon as you mark some text. You could also add a tooltip like "Annotation - Please mark some text first" (or similar).
2.) Many times after pasting a larger text into content field, I still need to edit that pasted immediately afterwards. While editing I sometimes use the Delete button. However, this button leads to an immediate deletion of whole annotation - without any warning. What the heck!? You can't imagine how often I've cursed that already! Why don't you disable that "Delete annotation" feature while one is editing in the comment field? That feature simply does not make sense there (especially without any warning)!

**Comment by GitHubRulesOK** [comment]
this may be different or similar to other apps with PDF self selection unlike Acrobat
In Okular you select text to highlight and that SELECTION will be available to add to comments. To override the selection you need to add other data to clipboard after that selection 

![image](https://github.com/user-attachments/assets/58bff781-045e-4cfb-b122-d8cca4ed9c2d)


 the steps above need to be 1 2 4 5 3 6

**Comment by kjk** [comment]
in [pre-release](https://www.sumatrapdfreader.org/prerelease) I disabled auto-copying to clipboard.

I added `copytoclipboard` argument to `CmdCreateAnnotHighlight` command (and similar) if someone wants that behavior.

**Comment by VicCoca** [comment]
Sorry for necroing but after having to resintall due to a corrupted installation this started happening again. I'm on the latest nightly, on Windows x64.

**Comment by kjk** [comment]
I cannot reproduce this behavior.

**Comment by GitHubRulesOK** [comment]
@VicCoca the current DEFAULT for highlighting has perhaps changed from your prior installation

when you select text for highlight the current setting is not to clip the text unless you add the option to the shortcut so see current help on customisation.

Also whilst searching text that is NOT actually "in page" like other comments/annotations then SumatraPDF currently does not see such characters as they are in effect an annotation overlay

**Comment by VicCoca** [comment]
> [@VicCoca](https://github.com/VicCoca) the current DEFAULT for highlighting has perhaps changed from your prior installation
> 
> when you select text for highlight the current setting is not to clip the text unless you add the option to the shortcut so see current help on customisation.

Would you mind telling me what exact option is causing this behaviour? This wouldn't be a big issue normally, but my clipboard is synced across devices and it's a bit annoying getting a popup accross my devices everytime I highlight text.

**Comment by kjk** [comment]
Here's a test:
* download latest portable version https://www.sumatrapdfreader.org/prerelease
* run it; this ensures default settings
* select text, press `a` to highlight it
* switch to notepad or any other app where you can paste text, press `Ctrl + v` to ensure that SumatraPDF DIDN'T copy text to a clipboard

If you get anything different with default settings, then I don't know what to tell you. It works for me.

Now do the same sequence with your version.

If `a` copies text to clipboard, I see 2 possibilities:
* you're using an older version. double-check (`Ctrl + K`, `about`) you have latest `v3.6.17044`
* you assigned a custom shortcut to `a`. `Ctrl + K`, `settings` to open advanced settings in notepad, look for `Shortcuts []` section. Is anything there?

**Comment by VicCoca** [comment]
So it turns out that, despite me uninstalling, reinstalling the latest version, etcetera, all along I've been using version 3.5.2. This is despite me updating the app and all that, I genuinely don't know what happened because the app itself didn't show up in thw Windows remove programs thing and I used BCUninstaller. 

Anyways, after installing the latest version (prerel) text no longer copies to clipboard!. 

I'll blame this on Windows 11.
