### ISSUE TITLE
WASD Support for Navigation Within Documents

### ISSUE THREAD

**Issue by Diamondragon** [sumatrapdfreader/sumatrapdf#440]
I've read the manual and settings info, but can't seem to find a way to customize navigation. I was wondering if such a thing might be possible. The arrow keys on my laptop are small and awkwardly placed, so it would be nice to be able to use WASD as substitute arrow keys (w = up, A = left, S = down, and D = right), since I'm used to those controls from games and other applications.

**Comment by kjk** [comment]
Currently it's not possible to customize keybindings.
