### ISSUE TITLE
Command to scroll to top and bottom of page

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4409]
Can you give please a command (with a shortcut key option) to scroll the page to the top of the page, where the position of the page on the X axis is saved (when the doc is in zoom) and only goes straight up, and a command to scroll to the bottom of the page.
This is very useful for documents that have footnotes, so you can go down to read the footnote with one click, and go back up with another one click.
Thank you!

**Comment by GitHubRulesOK** [comment]
The first one should be possible as is (such commands could not work in page mode as that is a  different fit) but for continuous mode you can use to go **t**op
```
	[
		Cmd = CmdGoToPrevPage 0
		Key = t
	]
```
Bottom  is not so easy in scroll or zoom as no fixed location other than above next top, so unknown back scroll required in any case without analyse window size and zoom. (you can see such problems with the concept of scroll "half" page)

@kjk I suspect would need a fresh command such as EOPBackScroll 100 ?

**Comment by kjk** [comment]
Sorry, no plans to do that.
