### ISSUE TITLE
Issues with text rendering on high-dpi display with 200% scaling

### ISSUE THREAD

**Issue by FSund** [sumatrapdfreader/sumatrapdf#441]
I understand Sumatra uses MuPDF to render documents, so this might be the wrong place to post this, but nevertheless.

I'm on Windows 10, and I use a small UHD (3840×2160) screen and a regular 24" 1080p screen. This means that I have to use 200% display scaling to be able to read anything on the UHD screen, since the dpi is so high. But it seems like Sumatra doesn't handle the scaling factor in the best way. 

Optimally you would want to render the text at the resolution of the screen, but scaled according to the scaling factor set in Windows settings. What Sumatra appears to do, is to just render at the "scaled resolution", meaning that on my 3840×2160 screen with 200% scaling, it renders text at 1920x1080, and just doubles the pixels.

To illustrate what I mean, I've made some pictures. I set the zoom level to 100% in Sumatra PDF, and opened the same pdf file on the two monitors, and took a screenshot of a part of text. I then pasted this in Paint, zoomed in, and turned on the grid.

On normal display without scaling (100% zoom):
![normal 100 screen](https://cloud.githubusercontent.com/assets/3352483/13136018/2be4bc14-d616-11e5-8349-e2cbd8fc19ea.png)

On UHD display with 200% scaling (100% zoom):
![200 4k screen](https://cloud.githubusercontent.com/assets/3352483/13136025/398b1232-d616-11e5-837e-649667713793.png)

As you see the pixels are simply doubled, and it doesn't look very nice.

To illustrate how I think scaling _should_ work, I also disabled dpi scaling for SumatraPDF.exe ([like this](https://cloud.githubusercontent.com/assets/3352483/13136005/fc225cd4-d615-11e5-90ea-79d8ce73924f.png)), and increased the zoom level to 200%.

On UHD display with display scaling disabled for Sumatra, with 200% zoom:
![200 4k with scaling disabled](https://cloud.githubusercontent.com/assets/3352483/13136035/55deed32-d616-11e5-9633-806ba7634405.png)

As you can see, the text in the final image looks gorgeous compared to the one with display scaling, and I would love for Sumatra to manage display scaling in way that achieves that. Nice and crisp text is one of the main reasons I went with a UHD display, and I would hate to have to abandon Sumatra to get my pdf's rendered in the best way.

**Comment by kjk** [comment]
Unfortunately I have no way to test with 2 monitors with 2 different DPIs.

**Comment by FSund** [comment]
If you have 2 or more monitors you can test scaling by increasing the scaling on one of the monitors. 

Alternatively, if you only have one monitor you can test it by changing the scaling on that monitor and seeing what happens.

The issue with scaling can be seen in the attached image. File Explorer scales like it should, but Sumatra just doubles the size of the pixels, and makes the text look blurry.
![sumatra_scaling](https://user-images.githubusercontent.com/3352483/30638326-553f59a8-9dfb-11e7-9822-fd1baf9eee1a.png)
