### ISSUE TITLE
BUG in V3.6.16501

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4412]
There is a bug in V3.6.16501 64-bit, 
commands :
[
		Cmd = CmdZoomFitWidth
		Key = 3
	]
	[
		Cmd = CmdZoomFitPage
		Key = 0
	]
Do not work properly.
In  V3.6.16490 64-bit everything worked properly.
Thanks!

**Comment by kjk** [comment]
What happens?

**Comment by kjk** [comment]
never mind, fixed
