### ISSUE TITLE
Installer didn't start automatically from update

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#4413]
3.6.16515 64-bit,
Ran check for update. Installer didn't start. File was downloaded to temp dir. Clicking on downloaded file, installer ran fine and installed.
Same thing happened on last previous pre release from earlier today. 3.6.16506 64-bit

**Comment by GitHubRulesOK** [comment]
Yes same with 32 bit 
related to changes for issue https://github.com/sumatrapdfreader/sumatrapdf/issues/4406

**Comment by kjk** [comment]
Should be fixed now
