### ISSUE TITLE
old path is retained.

### ISSUE THREAD

**Issue by gitfve** [sumatrapdfreader/sumatrapdf#4414]
**SumatraPDF version**
- Version [e.g. 3.6.16424]

**Describe the bug**

When a document is saved, the old path is retained.
Use CTRL+D to see the path.
Should change to the new path and name, after it is saved.

**Comment by GitHubRulesOK** [comment]
that's an old issue my own preference is that is not a bug but others feel different https://github.com/sumatrapdfreader/sumatrapdf/issues/93

**Comment by kjk** [comment]
Works as designed, see https://github.com/sumatrapdfreader/sumatrapdf/issues/93#issuecomment-2255632993
