### ISSUE TITLE
not remembering opened files

### ISSUE THREAD

**Issue by hme3** [sumatrapdfreader/sumatrapdf#4415]
3.6.16520 64-bit
open several files, close, open Sumatra, files not opened
NoHomeTab = false
ReloadModifiedDocuments = true
RememberOpenedFiles = true
RememberStatePerDocument = true
RestoreSession = true

**Comment by kjk** [comment]
using tabs?

**Comment by hme3** [comment]
Yes

**Comment by GitHubRulesOK** [comment]
confirmed as same in win10x32 behaviour
 prior session is not retained in 3.6.16525

**Comment by hme3** [comment]
3.6.16527 still not remembering opened tabs

**Comment by hme3** [comment]
Working in v3.6.16533
