### ISSUE TITLE
Add feature to open multiple (.pdf, .epub) files selected at once

### ISSUE THREAD

**Issue by tiagodmota** [sumatrapdfreader/sumatrapdf#4419]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to open multiples PDF files at once and alternate between them using CTRL + TAB shortcut.

**Describe the solution you'd like**
I want to select PDF files in a directory, press ENTER key and get Sumatra opened with all the tabs that shows each file.

**Describe alternatives you've considered**
I have to open manually each PDF file in order to populate Sumatra with the tabs.

**Comment by kjk** [comment]
It already works like that in [pre-release](https://www.sumatrapdfreader.org/prerelease), at least from Windows File Explorer:
* `Ctrl + click` to select multiple files in Explorer
* press `Enter`

If you have pre-release installed, it'll launch sumatrapdf with those files.

**Comment by GitHubRulesOK** [comment]
I dont think that's ever been a problem when default opener either using open or simply enter key

![image](https://github.com/user-attachments/assets/8cd9c52a-6947-43b6-b40a-dd2b14d3e5fe)

![image](https://github.com/user-attachments/assets/5aa9da37-96f9-4d17-95cc-e7e9d0e20aff)

**Comment by tiagodmota** [comment]
Actually, it only doesn't behavior as expected when all PDF files of a directory are selected.

**Comment by kjk** [comment]
It worked for me. I did `Ctrl + A` to select all files in Explorer and pressed `Enter`.

Explorer just called default app for each file. So each file for which SumatraPDF is a default handler will be sent to Sumatra.
