### ISSUE TITLE
Bright flash when switching pages with inverted colors

### ISSUE THREAD

**Issue by pulbitz** [sumatrapdfreader/sumatrapdf#4427]
**SumatraPDF version**
- 3.6.16592 pre-release

**Describe the bug**
My guess is that since the commit below, the flickering on page navigation has gotten worse, please check it out.

reafactor RenderCacheThread 
https://github.com/sumatrapdfreader/sumatrapdf/commit/464fa23cd50da8623b4a171f640986a82bb1bc1b

**To Reproduce**
1. I (invert colors in the document)
2. Ctrl+0 (Fit Page)
3. Left Arrow or Right Arrow (Next / Previous Page)

**Comment by kjk** [comment]
Hopefully this will fix it. If not, please provide a test document. I assume flashing will be more likely in documents that are slow to render.
