### ISSUE TITLE
i hope a function to always ontop 

### ISSUE THREAD

**Issue by relaxslow** [sumatrapdfreader/sumatrapdf#443]
because i 'm a programmer ,i always need to write and  read the pdf file at the same time.
i usually let sumatrapdf only takeup half of the screen . i need it always on top,

**Comment by kjk** [comment]
There are many Windows programs that can mark any window as "always on top" so I don't feel I need to include this directly in Sumatra.

**Comment by relaxslow** [comment]
good!i will try
