### ISSUE TITLE
Can not select the Chinese characters in a pdf(1.7) file

### ISSUE THREAD

**Issue by Honghe** [sumatrapdfreader/sumatrapdf#4430]
**SumatraPDF version**
- Version 3.5.2
- Windows 10 and 11

**Describe the bug**
Can not select the Chinese characters in a pdf(version 1.7) file.

**To Reproduce**
1. Open `demo_typst.pdf` file.
2. Try to select the Chinese characters and copy.

**Expected behavior**
The Chinese characters can be correctly selected and copied.

**File that reproduces the problem**
[demo_typst.pdf](https://github.com/user-attachments/files/16478782/demo_typst.pdf)

The PDF file is produced by https://github.com/typst/typst/issues/4663

**Screenshots**
https://github.com/user-attachments/assets/864eb28c-a8ff-49d4-bc5d-3ff65b467681

**Additional context**
None.

**Comment by GitHubRulesOK** [comment]
Selection of position is always a problem with PDF content as each word or letter can be a line in its own right / write
the letters/characters can be selected and extracted (read) but they will be interspersed with whitespaces of unknown characterisation.
```
bala
test 文
档
处
理
hehe
```
Here are the raw numbers for that page text (PDF uses binary numbers for letters from a list of characters)
```
BT
/F0 11 Tf
1 0 0 -1 70.86625 78.10648 Tm
[<00450044004F0044>]TJ
ET
/Gs0 gs
BT
1 0 0 -1 70.86625 98.86899 Tm
[<0057004800560057>]TJ
ET
/Gs0 gs
BT
/F1 11 Tf
1 0 0 -1 87.01713 98.86899 Tm
[-250.00003<1BBD1E990F3A2A3C>]TJ
ET
/Gs0 gs
BT
/F0 11 Tf
1 0 0 -1 70.86625 119.30922 Tm
[<004B0048004B0048>]TJ
ET
```
this is = Bala **[<00450044004F0044>]TJ**
this is = test **[<0057004800560057>]TJ** 
followed by large *gapping* **[-250.00003** and **<1BBD1E990F3A2A3C>]TJ** 文
档
处
理
finally is hehe **[<004B0048004B0048>]TJ**

We as humans can see which letters are to be considered words in a line and which are letters versus words but as charted numbers there are no human conventional "spaces" from the source.

**Comment by Honghe** [comment]
> Selection of position is always a problem with PDF content as each word or letter can be a line in its own right / write the letters/characters can be selected and extracted (read) but they will be interspersed with whitespaces of unknown characterisation. ![image](https://private-user-images.githubusercontent.com/12754913/354812372-5f70d60c-1e64-4ec2-bda4-bad8d2df6a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTYwMDgsIm5iZiI6MTcyMjY5NTcwOCwicGF0aCI6Ii8xMjc1NDkxMy8zNTQ4MTIzNzItNWY3MGQ2MGMtMWU2NC00ZWMyLWJkYTQtYmFkOGQyZGY2YTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE0MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDAwNzRkODRlY2Y5YWFkYTk3MDcyYzY4YzkyZjJiNjNkZTE5MTA4NGJkZTE4ZTY5YzAwMzFjMDAwZjM1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PiND14jnpzXmNK5YXDXcPOHaY8qElv8MVSOHaRl2hXk)
> 
> ```
> bala
> test 文
> 档
> 处
> 理
> hehe
> ```
> 
> Here are the raw numbers for that page text (PDF uses binary numbers for letters from a list of characters)
> 
> ```
> BT
> /F0 11 Tf
> 1 0 0 -1 70.86625 78.10648 Tm
> [<00450044004F0044>]TJ
> ET
> /Gs0 gs
> BT
> 1 0 0 -1 70.86625 98.86899 Tm
> [<0057004800560057>]TJ
> ET
> /Gs0 gs
> BT
> /F1 11 Tf
> 1 0 0 -1 87.01713 98.86899 Tm
> [-250.00003<1BBD1E990F3A2A3C>]TJ
> ET
> /Gs0 gs
> BT
> /F0 11 Tf
> 1 0 0 -1 70.86625 119.30922 Tm
> [<004B0048004B0048>]TJ
> ET
> ```
> 
> this is = Bala **[<0045 0044 004F 0044>]TJ** this is = test **[<0057004800560057>]TJ** followed by large _gapping_ **[-250.00003** and **<1BBD1E990F3A2A3C>]TJ** 文 档 处 理 finally is hehe **[<004B 0048 004B 0048>]TJ**
> 
> We as humans can see which letters are to be considered words in a line and which are letters versus words but as charted numbers there are no human conventional "spaces" from the source.
> 
> Even removing/ignoring that gap instruction makes no difference, in this case due to the surrounding structure descriptions ![image](https://private-user-images.githubusercontent.com/12754913/354813174-5616c667-3cb6-411c-94da-dea4e158b23c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTYwMDgsIm5iZiI6MTcyMjY5NTcwOCwicGF0aCI6Ii8xMjc1NDkxMy8zNTQ4MTMxNzQtNTYxNmM2NjctM2NiNi00MTFjLTk0ZGEtZGVhNGUxNThiMjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE0MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDg5YjZlYWZiNDQzZDBjYWFiMDZhYTgyOTM5OThhZjhkMmEyNTZjMjZjYTMzMzVmMWNhNDJkNTM4NjdmMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B6OvWT-UxgI9pFNu2vWQKwfiBwLhzRj3vx_BtojQzo0)
> 
> So what does make a difference is using a different set of numbers like SimSun ![image](https://private-user-images.githubusercontent.com/12754913/354813686-2284b0e8-4276-4536-81a4-4582bcae9b6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTYwMDgsIm5iZiI6MTcyMjY5NTcwOCwicGF0aCI6Ii8xMjc1NDkxMy8zNTQ4MTM2ODYtMjI4NGIwZTgtNDI3Ni00NTM2LTgxYTQtNDU4MmJjYWU5YjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE0MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjN2YxY2E0ZjliNzY5MWMwNDliMWUxZDYxYTRlNmUzYWE0Yjc2Yjg1ZTNjN2YzZTFiMzFlMWZiNWZiZDRiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gtZLHBDXIDt04gNoeosoVTQnpaY9DlcjKAZmxdqCqaw) ![image](https://private-user-images.githubusercontent.com/12754913/354813740-21bc548f-7c65-43c4-8481-47ea22268f1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTYwMDgsIm5iZiI6MTcyMjY5NTcwOCwicGF0aCI6Ii8xMjc1NDkxMy8zNTQ4MTM3NDAtMjFiYzU0OGYtN2M2NS00M2M0LTg0ODEtNDdlYTIyMjY4ZjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE0MzUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZTQ2NzBjM2U5YzVkOWUxYTA2OWZkZWIxZTdjOTQzNDVhNGE1NzM4OWY4ZmE0NzhhNzI3MjExZDY4ZjRiOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m3R0YFCBcZhAgxCN4snPd1_XtpeQQrsQNXmR_rqDkww) Naturally the whole area is different but looks and behaves better
> 
> ```
> BT
> -.007 Tc
> /F0 11 Tf
> 0 -9.8345 Td
> [<0045>1<0044>-1<004F0044>]TJ
> -.009 Tc
> 0 -22.038 Td
> [<0057>1<00480056>-1<0057>]TJ
> 0 Tc
> /F1 12 Tf
> 25.289 0 Td
> <1bb71e930f342a36>Tj
> -.007 Tc
> /F0 11 Tf
> -25.289 -28.2685 Td
> [<004B0048>1<004B0048>]TJ
> ET
> ```
Thanks, but I have 2 more questions:
1. The PDF file is generated by https://github.com/typst/typst/issues/4663, Do you have any suggestion to typst?
2. What is the debug tool for PDF in this pic?
![image](https://github.com/user-attachments/assets/71742ec7-bf41-48a3-845f-5acb21416473)

**Comment by kjk** [comment]
I haven't tested in 3.5.2 but in pre-release you CAN select the text.

Here's Chrome PDF reader selection:
```
t 文档处理
```

Here's SumatraPDF and mupdf selection:
```
t 文
档
处
理
```

The difference is that SumatraPDF / mupdf think characters are in a different line.

This is related to a heuristic deciding if characters are in a line. PDF really just sees a character and a position so it's judgement call if 2 chars belong to a word / line or are separate.

Chrome heuristic is better so I'll keep this open.

**Comment by kjk** [comment]
I've opened https://bugs.ghostscript.com/show_bug.cgi?id=707928

**Comment by GitHubRulesOK** [comment]
@Honghe 

The tool is an Editor where changing the KaiTi font with SimSun ensures the width of the characters are normalised.
the KaiTi font has always shown that problem with Mupdf/SumatraPDF see https://github.com/sumatrapdfreader/sumatrapdf/issues/3497

**Comment by kjk** [comment]
fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/cad932c3e03f0f79bbd3acc6c14964ac946cb20e
