### ISSUE TITLE
reflect custom zoom in UI

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#4432]
People are confused if it's not in menu / custom zoom e.g. ZoomLevels = 8.33 12.5 18 25 33.33 50 60 70 80 90 100 125 150 200 300 400 600 800 1000 1200 1600 2000 2400 3200 4800 6400

**Comment by GitHubRulesOK** [comment]
related ? https://github.com/sumatrapdfreader/sumatrapdf/issues/2502

**Comment by kjk** [comment]
@GitHubRulesOK yes, thanks
