### ISSUE TITLE
Auto-Update still seems to fail to recognise Win10 x 32 prior options

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4434]
**SumatraPDF version**
- Version pre-release 3.6.16616

**Describe the bug**
The latest change seems to correctly elevate (but still the user options are unseen)
and pre-view pane appears to be non functional after the auto install.

On downloading the formal 32bit copy the dialog shows elevation but no preview or ifilter as re-activated

![image](https://github.com/user-attachments/assets/50d242d6-0e68-4ff8-80a4-d54f8ecf201c)

**To Reproduce**
1. Update on win 7 x 32 to double check why that may be
2. See the dlls were not updated only the exe date changes
3. so the previewer is still working on windows 7 but not correct matched version ?
4. after some delay previews seem to fail there too
5. reinstall fresh and select options as was  so dlls are re-installed same version as exe
6. restart explorer and previews start working again

**Expected behavior**
Prior optional choices to be retained

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

**Screenshots**
see above

**Additional context**

**Comment by kjk** [comment]
Hmm, it works for me for 64-bit.

I can't test it because installing 32-bit build on 64-bit windows doesn't allow installing.

Could you run the installer with `-log` flag?

After it's done it should open default text editor with the log file which is saved to `%TEMP%` (in my case it was `C:\Users\kjk\AppData\Local\Temp\sumatra-install-log.txt`).

Please post the log as gist and link it here.

**Comment by GitHubRulesOK** [comment]
Catch 22 the AUTOupdate give me zero control over the process
If I set -log on the session that's about to update will it cascade to the installer ?

**Comment by kjk** [comment]
What I assume you're saying is that 32-bit installer doesn't properly detect current installation status of preview and search dll.

It shouldn't matter if installer runs from within Sumatra or if you download it and run.

Furthermore you can get the auto-update by adding `-fast-install` flag. So `SumatraPDF.exe -fast-install -log` should do exactly same thing as auto-update but with log.

**Comment by GitHubRulesOK** [comment]
Ok lets try without auto update as  its not out yet ?
 and in hindsight was not the right way to go about test? but may help or be a red herring

Seems different as it pauses for me to close and no re-install presumably same version
![image](https://github.com/user-attachments/assets/49420f0e-4ad5-4b27-9da5-aac77b2f0f4b)

Ahh end of log says
```
LogLastError: 0x0 (0) 'The process cannot access the file because it is being used by another process.'
  failed to copy 'C:\program files\sumatraPDF\SumatraPDF.exe' to dir 'C:\Program Files\SumatraPDF'
ExtractInstallerFiles() failed
```
[sumatra-install-log.txt](https://github.com/user-attachments/files/16487977/sumatra-install-log.txt)

I can roll back to day before yesterday and try auto update with today as the target
but is that the way to test by running the prior installed version with logging on ?

**Comment by GitHubRulesOK** [comment]
I rolled back to 16600 and previewer is not working although requested 
![image](https://github.com/user-attachments/assets/bf6166a8-073c-45a4-a345-eaad8a3881cc)

Restart Explorer and previewer works again
![image](https://github.com/user-attachments/assets/6dfa3d18-0879-412a-93ad-d7ee388d2190)

Run command asks to elevate ok elevated then returns and fails but clobbered previews
![image](https://github.com/user-attachments/assets/b5dc0f50-c069-437c-9334-13e1d8dfc1cb)

![image](https://github.com/user-attachments/assets/9a8b86b9-0f4e-4ab1-9b5b-6714e543d2f6)

similar problem it cannot overwrite itself 
```
CopySelfToDir(C:\Program Files\SumatraPDF)
LogLastError: 0x0 (0) 'The process cannot access the file because it is being used by another process.'
  failed to copy 'C:\program files\sumatraPDF\SumatraPDF.exe' to dir 'C:\Program Files\SumatraPDF'
ExtractInstallerFiles() failed
```


[sumatra-install-log.txt](https://github.com/user-attachments/files/16488019/sumatra-install-log.txt)

**Comment by GitHubRulesOK** [comment]
Lets try Emulation by rerun 61600 
reject install and then run update installer.exe  from temp ?
![image](https://github.com/user-attachments/assets/f4b912f2-8c12-46f7-bbeb-2f770d63495e)
![image](https://github.com/user-attachments/assets/faa9ad7f-2c8d-4134-ac22-e05e80f2b59a)

Again that was dirty 
```
ExtractInstallerFiles() to 'C:\Program Files\SumatraPDF'
CopySelfToDir(C:\Program Files\SumatraPDF)
LogLastError: 0x0 (0) 'The process cannot access the file because it is being used by another process.'
  failed to copy 'C:\Users\lez\AppData\Local\Temp\sumA704.tmp.exe' to dir 'C:\Program Files\SumatraPDF'
ExtractInstallerFiles() failed
```

Try again?

**Comment by kjk** [comment]
In both cases you do: `c:\program files\sumatraPDF\SumatraPDF.exe -fast-install ...`

It's failing because you're running the exe that is installed as an installer and it fails to copy onto itself. 

I should add a check for that but that is not supposed to work. You need to download the installer and run that.

That's why I insist on providing complete steps. 

I assumed that you've downloaded an installer and ran that. That's why those screenshots about failures are mysterious and I cannot reproduce them.

If you wrote:
> I ran `c:\program files\sumatraPDF\SumatraPDF.exe -fast-install`"

then I would be able to tell you right away that this is not supposed to work.

**Comment by kjk** [comment]
So here are the steps:
* download 32-bit installer to your Downloads folder
* make sure SumatraPDF is not running. A running .exe cannot be over-written so that's why those installations are failing
* run the installer with `-fast-install -log` flags

**Comment by kjk** [comment]
I can confirm that `-fast-install` fails if SumatraPDF is running. I have code in installer to kill the processes which for some reason doesn't work in `fast-install` but that's not typically an issue because that's used from within SumatraPDF itself which exists after running the installer.

If SumatraPDF is not running then `-fast-install -log` works.

**Comment by GitHubRulesOK** [comment]
I have seen that with exe running it does not work as per "normal" so ran again without any session active

Thus it Auto-updates as past expectation but it is still not previewing
[sumatra-install-log.txt](https://github.com/user-attachments/files/16488103/sumatra-install-log.txt)
![image](https://github.com/user-attachments/assets/051e0bdf-e7a8-40cf-b6c2-f4298960ad05)

**Comment by kjk** [comment]
Ok, I can reproduce:
* install with search filter
* run installer again with `-fast-install`

It doesn't propagate search / preview installation state

**Comment by GitHubRulesOK** [comment]
reset to 16600 and previewer is working as expected from manual install ensure no SumatraPDF is active, apart from previews and searches, the intended usage.

run 16616 with logging I expect will fail

**Comment by GitHubRulesOK** [comment]
[sumatra-install-log.txt](https://github.com/user-attachments/files/16488130/sumatra-install-log.txt)
