### ISSUE TITLE
Set opacity in CmdCreateAnnotHighlight

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4438]
The help says "Arguments can be: strings, numbers, booleans, colors (#rrggbb or #rrggbb**aa** format)."
But actually what works is #**aa**rrggbb, and like:
[
		Cmd = CmdCreateAnnotHighlight #28BDBDBD openedit
		Key = A
	] 
where 28 is opacity 40%
Thank you!

**Comment by GitHubRulesOK** [comment]
Must admit I wondered about that but had not tested what it currently uses 
However it has in past always been AlphaRGB
