### ISSUE TITLE
large icons option

### ISSUE THREAD

**Issue by czJanKrejci** [sumatrapdfreader/sumatrapdf#444]
Hello, first of all thanks for a great pdf reader, it is default on every computer I have. Now, with the arrival of touch screens it would be good to have a "large icons" option for the toolbar, like Libre Office have. It would be much more easier to navigate pdfs when you don't have mouse around.

Thanks for considering it.

Jan Krejčí

**Comment by EpicWolverine** [comment]
Sumatra has great touch support in other areas, but would benefit greatly from an option to enable larger icons and menus. It would also be nice if it could detect when Windows 10's Tablet Mode is switched on and automatically make the icons/menus larger like OneNote does, but I would be satisfied with an option to always have larger icons.

**Comment by kjk** [comment]
closing as dup of #734
