### ISSUE TITLE
Pre-Release Custom Icons with Highlighting a selection inconsistent

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4440]
**SumatraPDF version**
- Version pre-release 3.6.16629

**Describe the bug**
When selecting "Areas" to highlight they respond to custom shortcuts see [R] [G] [B] in the screenshot where red and blue were set by keyboard and green text was set by Icon after selection.

Only on occasions do the selection of an area work,  but is not repeatable every time

**To Reproduce**
1. Go to Custom Shortcut on toolbar after area selection and note if they are grey or black
2. Some times black but another occasion they are grey.

**Expected behavior**
Consistent availability

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

**Screenshots**
Working this time Box is selected and icons black
![image](https://github.com/user-attachments/assets/4eba8c11-a0cc-486e-8b5b-b5777983ce2a)

Another occasion (most often) Icons are grey
![image](https://github.com/user-attachments/assets/c1a8e5e4-80a2-4a72-94b2-c1ff57b62bc3)

**Additional context**

**Comment by kjk** [comment]
I'm not sure I understand but some commands are only available in specific condition. For example: "create a highlight annotation" is only available in PDF files when text is selected.

The state of the icon reflects that, just like the state of menu items, context menu and command palette.

I might not have gotten this right for every command but to decide that I need the `Shortcuts` definition, the context in which it is not available and explanation why you think it should be available.

**Comment by GitHubRulesOK** [comment]
Shortcuts are simple but the action is variable for a selected rectangle, 
Historically has always worked both in prior SMX and ever since new highlights introduced. Keys work / worked perfectly.
The anchoring to text should not be a differential except to fixate the size temporarily and resist movement by editors

```
	[
		Cmd = CmdCreateAnnotHighlight #ff0000 openedit
		Key = Shift + R
		ToolbarText = [R]
	]
	[
		Cmd = CmdCreateAnnotHighlight #00ff00 openedit
		Key = Shift + G
		ToolbarText = [G]
	]
	[
		Cmd = CmdCreateAnnotHighlight #800000ff openedit
		Key = Shift + B
		ToolbarText = [B]
	]
```
