### ISSUE TITLE
Crash when opening certain file - C0000005 ACCESS_VIOLATION

### ISSUE THREAD

**Issue by lansman** [sumatrapdfreader/sumatrapdf#4444]
**SumatraPDF version**
- Version 3.5.2 64 bit

**Describe the bug**
App crashes instantly when I open certain pdf file

**To Reproduce**
1. Open the file (by double clicking in Windows Explorer)
2. Get crash

No matter, whether other pdf files are already opened in the program or not

Important notice: at some moment I tried open the file via SumatraPDF menu (File - Open) and it worked, and even more: crashes stopped. Now the file is opened flawlessly, no matter via double click or program menu.

Another notice: the problem was only on my desktop PC. No issues on laptop. Both on Windows 11 Pro. Program version are the same.

**Expected behavior**
No crash.

**File that reproduces the problem**
Sorry, cannot provide it

**Additional context**
Exception: C0000005 ACCESS_VIOLATION
Faulting IP: 00007FF77C66AA5B 01:0000000000089A5B sumatrapdf.exe!HtmlWindow::OnSize+0x97 C:\Users\kjk\src\sumatrapdf\src\utils\HtmlWindow.cpp+1602
Fault reading address 00000000FFFFFFFF

Crash Log:
[2024-08-05_21-55_sumatrapdf_crash.txt](https://github.com/user-attachments/files/16500554/2024-08-05_21-55_sumatrapdf_crash.txt)

**Comment by kjk** [comment]
Most likely fixed in [pre-release](https://www.sumatrapdfreader.org/prerelease)
