### ISSUE TITLE
Tab list missing.

### ISSUE THREAD

**Issue by gitfve** [sumatrapdfreader/sumatrapdf#4446]
Tab list missing.

A lot have asked back to 2014, so maybe this time...

**When using a lot tab's it is not possible to find anything.**
Missing a list showing all open documents.
Just like in Notepad++

**Comment by kjk** [comment]
In latest [pre-release](https://www.sumatrapdfreader.org/prerelease) you can do `Ctrl + K` and then "@" or `Ctrl + Tab` / `Ctrl + Shift + Tab` (and `Space` to enable sticky mode)

**Comment by mrx23dot** [comment]
How do I disable this sticky tab selector?  
I cannot simply alt tab anymore, now I have to click too..

**Comment by GitHubRulesOK** [comment]
@mrx23dot perhaps best to compare with the announcement see https://github.com/sumatrapdfreader/sumatrapdf/discussions/4482
