### ISSUE TITLE
[unarr] tar archives are not valid

### ISSUE THREAD

**Issue by gen2brain** [sumatrapdfreader/sumatrapdf#445]
It seems unarr can't handle tar archives. I don't have problems with 7z, rar and zip. 

I compiled library like this:
    git clone https://github.com/zeniko/unarr && cd unarr
    mkdir lzma920 && cd lzma920 && curl -L http://www.7-zip.org/a/lzma920.tar.bz2 | tar -xjvp && cd ..
    curl -L http://zlib.net/zlib-1.2.8.tar.gz | tar -xzvp
    curl -L http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz | tar -xzvp
    curl -L https://gist.githubusercontent.com/gen2brain/89fe506863be3fb139e8/raw/8783a7d81e22ad84944d146c5e33beab6dffc641/unarr-makefile.patch | patch -p1
    CFLAGS="-DHAVE_7Z -DHAVE_ZLIB -DHAVE_BZIP2 -I./lzma920/C -I./zlib-1.2.8 -I./bzip2-1.0.6" make
    cd build/debug/

```
./unarr-test /tmp/test.tar.gz 
Parsing "/tmp/test.tar.gz":
Error: No valid RAR, ZIP, 7Z or TAR archive!
```

I tried with couple of different archives, and one with simple test file created with standard gnu tar.

**Comment by GitHubRulesOK** [comment]
@kjk potentially "off topic" unless its affecting current reading of .cbt files

**Comment by kjk** [comment]
You should try https://github.com/selmf/unarr as https://github.com/zeniko/unarr is not maintained.

Either way, this is not Sumatra project, you should report this to unrar project.
