### ISSUE TITLE
Change the Location of sumatrapdfcache Folder, that keeps PNG files

### ISSUE THREAD

**Issue by cricrazy** [sumatrapdfreader/sumatrapdf#4457]
**Is your feature request related to a problem? Please describe.**
I have large PDF files with more than 1000 pages in my `Downloads` folder on Windows 10. When I open it in SumatraPDF, it generates `sumatrapdfcache` folder in `Downloads` folder, with literally thousands of png files. It hanged my `Downloads` folder in File Explorer due to that. 

**Describe the solution you'd like**
Provide a way to change the default location of `sumatrapdfcache` folder and document it.

**Comment by kjk** [comment]
You can use `-appdata` cmd-line. See https://www.sumatrapdfreader.org/docs/Command-line-arguments

You have to always call sumatra with this arg, so probably create a shortcut

You can also disable generating thumbnails via `File / Options` uncheck `Remember opened files`. This won't show thumbnails on home page, though and will not have history of opened files.

**Comment by kjk** [comment]
Or you can install sumatra in which case this will not be in the same place as sumatra's executable.
