### ISSUE TITLE
Touchpad scrolling does not work

### ISSUE THREAD

**Issue by PowerSnail** [sumatrapdfreader/sumatrapdf#446]
I am using Surface Pro 3, running Win 10. Usually, when sliding two fingures on the touchpad of the typecover causes scrolling behavior in program. However, SumatraPDF does not seem to respond to it. 

Mouse scrolling and touch screen scrolling are all fine.

**Comment by relative2reasoning** [comment]
Similarly, my device is running Win 10 and scrolls normally with a mouse -- but touchpad scrolling actually causes Sumatra to scroll so fast it reaches the end of 1000+ page documents instantly, as if I had pressed the End key. The same thing happens with documents ranging any number of pages, and scrolling up on the touchpad also instantly returns to the first page of the document. It's a real bummer when I lose my place in a large textbook by forgetting about this bug :(

**Comment by EpicWolverine** [comment]
Have you updated to the latest version? This should be fixed as of 3.1. It works on my Surface Pro 3 with Windows 10.

**Comment by relative2reasoning** [comment]
I had been running the 3.2 64-bit preview version.
I also tried: 3.2 32-bit, 3.1 64-bit, 3.1 32-bit
All of them have various scrolling speed issues ranging from scrolling 3-10 pages with nothing but a light tilt on the touchpad, to scrolling to the end of the document with the same movement. I made sure to check my scroll speed setting in Windows; it is set to 3 lines per scroll and works normally on all other programs.

Device: Lenovo G780 non-touchscreen laptop, Win. 10 Home Ed.

**Comment by PowerSnail** [comment]
3.1.1 works great on Surface Pro 3, Windows 10.

I have not yet experienced any problems mentioned by others.

Thank you!

**Comment by GitHubRulesOK** [comment]
@kjk I dont think SumatraPDF can do much about this unless slow to a crawl, my own experience with this Toshiba synaptic touchpad is if I stroke it slow and gentle it behaves well but the faster I swipe or flick  with two fingers the more eratic the scroll response is. I have not looked further into changing the touch driver settings (where I can set the rate of scrolling) since I eventually got acoustomed to avoiding rash movements after reseting to default.

**Comment by GitHubRulesOK** [comment]
Consolidating with later Win10 touchpad comments #962
