### ISSUE TITLE
feature request: writer feature feature for epub ...

### ISSUE THREAD

**Issue by catafest-work** [sumatrapdfreader/sumatrapdf#4463]
**Is your feature request related to a problem? Please describe.**

I need a writer tool to create .epub files that can show images, text and more based on any .epub format type.

**Describe the solution you'd like**

Just a writer tool to create .epub file that can deal with images and all of .epub features

**Describe alternatives you've considered**

Some software I tried cannot deal to export images in epub format, cannot set to be resized to set on page.
I used python packages but are old without new epub 3.x.
I tested Google doc exporter, libre office, microsoft documents, and web writers software from web ...
None of these are perfect and most cannot export images into pages, images are visible just a part of the .epub readers. 

**Additional context**

I think is a easy to implement by this team and will be a great feature for all !

**Comment by kjk** [comment]
SumatraPDF is not a tool for writing ePub files.
