### ISSUE TITLE
BackgroundColor bug in custom themes

### ISSUE THREAD

**Issue by pulbitz** [sumatrapdfreader/sumatrapdf#4465]
**SumatraPDF version**
- 3.6.16719, pre-release

**Describe the bug**
I found a bug while using custom themes.
I set the BackgroundColor value to #000000, but it actually shows as #080808.
Here are the settings:

```
FixedPageUI [
	TextColor = #000000
	BackgroundColor = #bbbbbb
	GradientColors = #000000
	InvertColors = true
]

Themes [
	[
		Name = Custom
		TextColor = #bbbbbb
		BackgroundColor = #000000
		LinkColor = #8aa3b0
		ColorizeControls = true
	]
]
```

**Comment by kjk** [comment]
Please post a screenshot and describe how you determined the color value.

**Comment by kjk** [comment]
It's caused by `GradientColors` so don't use it. Consider colors in `FixedPageUI` only for backwards compat. You either use those or themes, not both.

**Comment by GitHubRulesOK** [comment]
If I test that same file without theming (even with gradient colours active) the paper default is pure  0 0 0

![image](https://github.com/user-attachments/assets/74f5f820-b2a2-490b-a7a7-014e2d2bab5b)

With a theme it is naturally affected
![image](https://github.com/user-attachments/assets/6ce2aa38-6e47-44a0-9e50-c32731300879)

@kjk However I have to agree that without gradient and simply with Custom B&W there is a noticeable 8 bit black ground difference (reminiscent of a MuPDF greys issue ?)

![image](https://github.com/user-attachments/assets/22b1218e-70af-4f08-9f15-ace4d83bfcda)

**Comment by kjk** [comment]
@pulbitz according to my color picker, the black background of that screenshot is pure black. Which part of the screenshot is not black for you?

This could be some monitor color profile thing but I know nothing about it.

All I can say is that when the background color is set to #000000, I paint #000000.

**Comment by kjk** [comment]
I can't repro this on my machine.

What happens if you delete your settings (so that they recreated in default state) and then add custom theme with background #000000?

**Comment by kjk** [comment]
Ok, you're talking about the color of the rendered page when 'invert colors' is used, not the color of window (surrounding frame).

That's because for old themes I wanted some contrast between the rendered page and window.

Not sure what to do.

Maybe not do that logic for custom themes but preserve for old themes.

Maybe add explicit `DocumentTextColor` and `DocumentBackgroundColor` but I don't want to introduce too many colors and they would be confusing because only applied in `invert colors` mode.
