### ISSUE TITLE
Search in long PDFs is terminated prematurely

### ISSUE THREAD

**Issue by user1823** [sumatrapdfreader/sumatrapdf#4468]
**SumatraPDF version**
- v3.6.16736

**Describe the bug**
When searching in long PDFs (in which searching takes more than a few seconds), the search terminates after about 1-2 seconds and, as a result, the search term is not found.

This bug is introduced in a very recent build.

**Comment by kjk** [comment]
Can you share a sample document?

I tried search in 200 page PDF and can't see a difference compared to 3.5.2

**Comment by user1823** [comment]
Try this [3700+ page PDF (224 MB)](https://archive.org/download/harrisons-principles-of-internal-medicine-twentieth-edition-vol.-1-vol.-2-pdfdrive.com/Harrison%E2%80%99s%20Principles%20of%20Internal%20Medicine%2C%20Twentieth%20Edition%20%28Vol.1%20%26%20Vol.2%29%20%28%20PDFDrive.com%20%29.pdf)

Based on further testing, it seems that the issue occurs only after I reach one search result and press F3 to go to the next one which is several hundred pages away.

**Comment by kjk** [comment]
Can you give example search query?

**Comment by user1823** [comment]
You can search for `inulin`. You will get 2 results initially but when going to the third result, the search will terminate prematurely.

**Comment by kjk** [comment]
Thanks, I can reproduce.
