### ISSUE TITLE
Crashes while trying to set a custom zoom

### ISSUE THREAD

**Issue by PrinceOC912** [sumatrapdfreader/sumatrapdf#4478]
**SumatraPDF version**
- Version 3.6.16757 pre-release 64-bit

**Describe the bug**
The program crashes if I try to set a custom zoom value when a keyboard shortcut is set to bring up the custom zoom dialog.
It works fine with the default shortcut Ctrl + Y (when CmdZoomCustom is not used)

**To Reproduce**
1. Click on menu icon select zoom and then custom zoom or use the custom keyboard shortcut 

**Expected behavior**
It doesn't crash and I am able to set a custom zoom. I tried many different shortcuts with different key modifiers eg. Ctrl Alt etc. It happens with any file whether it be PDF or DJVU. 

Crash gist: https://gist.github.com/PrinceOC912/b7e2480446bc2d52451b11b20ff7a756

**Comment by GitHubRulesOK** [comment]
Hmm 
In newest 16759 (there should not be much difference it was language and one minor change for building)
As you said  I used CTRL + Y with 550 and no crash 

I set a Key or an Icon no crash
```
	[
		Cmd = CmdZoomCustom 550
		Key = 5
		ToolbarText = 5
	]
```
![image](https://github.com/user-attachments/assets/b5bb5703-919b-4ebf-bc29-78cd1665e49f)

**Comment by PrinceOC912** [comment]
I went through the docs and it seems to be a change in versions 3.6+, before I was able to set z as a shortcut to bring up the zoom factor dialog and then set a custom value.
I remapped z to  Ctrl + Y using autohotkey to achieve my desired behavior.

**Comment by kjk** [comment]
Fixed, thanks for the report
