### ISSUE TITLE
can not read this pdf file ！

### ISSUE THREAD

**Issue by kbitlive** [sumatrapdfreader/sumatrapdf#448]
adobe reader  open this file  is ok ，but  sumatrapdf  can not open this file！

[如何使用工具提高PHP项目的生产力2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/145988/PHP.2.pdf)

**Comment by jddcef** [comment]
Here is another one that doesn't load http://ge.tt/8CNVghv2

**Comment by GitHubRulesOK** [comment]
@jddcef The one you link to is not a problem it is an abnormal scanned file (the first one is an odd type of MacOS compressed build that needs to be reflowed)
The layout would benefit from restructuring as single pages without the bad overlaps, I suggest getting a better source copy from the document scanners (Nebraska Library  ?)

**Comment by jddcef** [comment]
> @jddcef The one you link to is not a problem it is an abnormal scanned file (the first one is an odd type of MacOS compressed build that needs to be reflowed)
> The layout would benefit from restructuring as single pages without the bad overlaps, I suggest getting a better source copy from the document scanners (Nebraska Library ?)

The file opens in Adobe... I took the time to report it for Sumatra to improve and get stronger,  not because I need the file changed or anything. If the Sumatra app knows better about what is right or wrong it should then say something about it but still display it.
 But thanks for the info though.

**Comment by GitHubRulesOK** [comment]
@jddcef I Can read all 26 pages of your file in Adobe OR SumatraPDF my comment was that it could have been better scanned not that it needed changing to be able to read it.

**Comment by jddcef** [comment]
Sure, I understand now that you have explained it. 
I think my machine was low on free RAM, which was causing the issue, it does open fine now.

**Comment by GitHubRulesOK** [comment]
@kjk resolved with latest updates

![Untitled](https://user-images.githubusercontent.com/12754913/68898057-9c42da00-0726-11ea-82d4-0454e79486dd.png)

**Comment by kjk** [comment]
Thanks for verifying @GitHubRulesOK 
Is fixed in latest build https://www.sumatrapdfreader.org/dailybuilds.html
