### ISSUE TITLE
One potential as to why my Auto-Updates occasionally fail

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#4485]
**SumatraPDF version**
- Version pre-release

**Describe the bug**

As you know I am perhaps the most frequent user of one person AutoUpdates and have intermittent reasons they dont work as intended. So for reference I saw a recent one apparently self destruct in temp. However it seems it was Defender decided to "protect" me against my actions as this notification was pending from earlier. However the full direct download itself was not flagged !

![image](https://github.com/user-attachments/assets/eb4f6d92-a283-4d7d-8615-dba8aaec1c90)

**To Reproduce**

**Expected behavior**

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

**Screenshots**

**Additional context**

**Comment by kjk** [comment]
Good to know but there's nothing I can do about hence not a bug in Sumatra.
