### ISSUE TITLE
Invert Colors Shortcut "i" Doesn't Invert Colors

### ISSUE THREAD

**Issue by ryanlo713** [sumatrapdfreader/sumatrapdf#4487]
**SumatraPDF version**
- 3.6.16761 pre-release

**Describe the Bug**
The shortcut for inverting colors (`i`) is currently mapped to display the current page number instead, while the shortcut to show the current page number (`Shift + i`) incorrectly inverts the colors. This is a conflicting behavior which hampers the functionality for users expecting the standard shortcuts to work.

**To Reproduce**
1. Open any PDF document in SumatraPDF.
2. Press the `i` key.
3. Observe that the application displays the current page number instead of inverting colors.
4. Now press `Shift + i`.
5. Observe that instead of showing the current page number, it inverts the colors.

**Expected Behavior**
- Pressing the `i` key should invert the colors of the document.
- Pressing `Shift + i` should display the current page number correctly.

**File that Reproduces the Problem**
- This bug occurs on any PDF file and is not limited to a specific document.

**Comment by GitHubRulesOK** [comment]
that is the way it was introduced and then it caused problems as you can see from the many issues and discussions  basically it is WORSE when i than controled `I` by shift and you can set it any which way you wish.

**Comment by kjk** [comment]
This is an intentional change see https://www.sumatrapdfreader.org/docs/Version-history

`i` is too easy to press accidentally. Some people did it by accident and didn't understand what happened.
