### ISSUE TITLE
[question] how can I use inverse search on other document

### ISSUE THREAD

**Issue by chantisnake** [sumatrapdfreader/sumatrapdf#449]
I know in inverse search, Sumatra has the macro `%f` to pass the file name.

For example I have the `.tex` file in `~/appdata/local/temp/` and I want to search on the `.tex` file with the same file name in `~/latex/` folder, is there any way I can do that?

**Comment by chantisnake** [comment]
I have figured it out:

1. paste this code into the powershell profile:
```ps1
function Invoke-Sumatra-Inverse-Search {
    param($tempFileFullName, $lineNumber=0)
    $filename = $tempFileFullName.split('\')[-1]  # get the file name
    $fileFullName = "$latexPath\$filename"  # latex-path is the latex work space
    gvim --remote-silent +$lineNumber "$fileFullName" # the line to invoke inverse search
}
```

2. put this in inverse search command:
```
PowerShell Invoke-Sumatra-Inverse-Search %f %l
```

this is slow and will invoke an ugly powershell prompt.

**Comment by kjk** [comment]
Good to know you've figured it out.
