### ISSUE TITLE
Shortcut keys on a non-English keyboard

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4490]
When I set a shortcut key for example Key = h, then when the keyboard is Hebrew it is inactive, and if I set a Hebrew letter  instead of h, it does not help.
Is it possible that I set the VK key code of the key (or the Unicode code of the key), so that by doing so it will work when the keyboard is in Hebrew?
Thank you!

**Comment by kjk** [comment]
I tried to fix it (https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/Accelerators.cpp#L319) but it didn't work.

I don't know what's going on. If someone understands those kinds of keyboard issues, let me know how to fix it.

**Comment by H5820121** [comment]
@kjk
I greatly appreciate the effort to resolve this issue, which concerns many
users from all over the world who do not use an English keyboard. What's
interesting is that keyboard shortcuts such as Key = Ctrl + Alt +F do work
even on a Hebrew keyboard.
The problem is only when it is of one letter such as Key = h, which
unfortunately is the more convenient type of keyboard shortcut.

‫בתאריך יום ד׳, 21 באוג׳ 2024 ב-19:22 מאת ‪Krzysztof Kowalczyk‬‏ <‪
***@***.***‬‏>:‬

**Comment by GitHubRulesOK** [comment]
Hmm AFAIK the problem is simply graphical symbology so for example the key for 

US L would be this in Hebrew ![image](https://github.com/user-attachments/assets/d767437d-1b85-4ee4-b880-4dd8e0abc1ab) but the US translation of that key will still be L

**Comment by kjk** [comment]
Hopefully fixed

**Comment by H5820121** [comment]
> Hopefully fixed

@kjk I'm happy to report that I tested it and it works well, thanks!
