### ISSUE TITLE
The text in the PDF is displayed with huge margins that do not exist in reality

### ISSUE THREAD

**Issue by H5820121** [sumatrapdfreader/sumatrapdf#4491]
The text in the PDF is displayed with huge margins that do not exist in reality, in Adobe Acrobat and in the PDF-XChange Editor it is displayed correctly. This bug was not in version 3.5 it started in version 3.6.
I sent the file as an attachment to your email.
Thank you!

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/3a708482bfaed25e21656829eb6529824f8aea8f

**Comment by GitHubRulesOK** [comment]
@H5820121 

Sadly that has not reached formal release  Although the compilations was including a lot of MuPDF updates which reportedly resolved yours and similar boundary conditions Thus I see why you mentioned it in another related thread, however that was a different edge case.

**Comment by GitHubRulesOK** [comment]
@H5820121 
I dont have your sample but it sounds similar to a repeat of the Media/Cropbox issue in  https://github.com/sumatrapdfreader/sumatrapdf/issues/3834
