### ISSUE TITLE
Add an option to bypass recycle bin during delete

### ISSUE THREAD

**Issue by ludovicandrieux** [sumatrapdfreader/sumatrapdf#4495]
Hi,

This issues follows #2246 and commit 8f57f06cea31a8685956ef53c4533d7afc98c43e

I use the new 3.6 version and love the "CmdDeleteFile". Thanks a lot.
Can you plan to add a command llike "CmdForceDeleteFile" to bypass recycle bin ?

Thanks

**Comment by kjk** [comment]
Sumatra is not a file manager. Use `Show file in folder` if you want that.
