### ISSUE TITLE
Don't delete annotations via Del key when focus is in "Contents" text field

### ISSUE THREAD

**Issue by codeling** [sumatrapdfreader/sumatrapdf#4499]
**Is your feature request related to a problem? Please describe.**

I'm generally very happy with SumatraPDF, it's the fastest document reader under windows I have encountered so far, thanks a lot!

I'm now using it the first time to annotate a larger document, and I'm getting increasingly frustrated by the behavior of the Del key.
As far as I can tell, as soon as the "Annotations" window is open, one annotation is selected and the "Del" key is pressed, the annotation is removed, with no way to get it back.
My main grievance is that this also happens when I'm currently *editing* the text of the annotation via the "Contents" field. Since I'm very much used to using the Del key when editing text, I often inadvertently delete the whole currently selected annotation, just by editing its text; then I have no way back, and have to manually recreate it.

**Describe the solution you'd like**

From any other application I know, when I'm in a text field editing some text, the Del key actually works locally on just the text field contents. So my preferred solution would be that when the Contents text field has the focus, the Del key gets applied locally within the text field, and doesn't trigger a delete of the annotations.

**Describe alternatives you've considered**

Two other possible options to alleviate my issue come to mind:

- Provide an option (e.g. via the settings dialog) to completely disable deleting annotations via the Del key (there would still be  remaining the option to delete them via the button on the Annotations list).
- Possibility to undo the deletion of the annotation (customarily, via shortcut Ctrl+Z or some menu entry)

**Comment by kjk** [comment]
This has already been fixed in pre-release: https://www.sumatrapdfreader.org/prerelease

**Comment by KillianLobato** [comment]
Wow thanks! I was going a bit crazy with report grading and having my comments disapear when i was hitting del to correct whatever comment was editing! Hopefully the pre-release does not have new bugs that I encounter.
Keep up the brilliant work!
