### ISSUE TITLE
Subscript tags in MOBI format

### ISSUE THREAD

**Issue by David-Sims** [sumatrapdfreader/sumatrapdf#45]
I write mathematical essays in which it is convenient to use subscripted variables in the equations. For this purpose, I usually use the form

N<sub>1</sub>

to express N with a subscript of 1. But the sumatrapdf reader displays subscripts like superscripts, so what I see is

N<sup>1</sup>

Which is wrong!

Again, if the HTML says

N<sub>1</sub><sup>2</sup>

which should be displayed as N with a subscript 1, squared, instead I see what appears to be N raised to the power of 12. 

N<sup>12</sup>

Which is wrong!

So it would be nice if sumatrapdf would display superscripts as superscripts, and subscripts as subscripts in the EPUB and MOBI formats, which is what I most often use.

**Comment by GitHubRulesOK** [comment]
SumatraPDF distorts the super script in ePub too 
![image](https://user-images.githubusercontent.com/12754913/70401970-a86e3e80-1a29-11ea-9474-cc01eafa05bc.png)

[Superscript.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3937610/Superscript.zip)

**Comment by kjk** [comment]
Yeah. After releasing 3.2 I'll look into switching .epub rendering to mupdf's. Improving our code would be a lot of work and mupdf has already done it.

**Comment by GitHubRulesOK** [comment]
@kjk 
Latest crash report for above type of epub with superscript ?
[sumatrapdfcrash.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/6913709/sumatrapdfcrash.zip)


OP was Mobi subscript but did not have a sample to test in that style or format

**Comment by kjk** [comment]
@GitHubRulesOK the crash is not related to epub handling. Please open a new bug with a file that caused this crash.

**Comment by GitHubRulesOK** [comment]
Closing as Superscript sample is handled well by newer pre-release with MuPDF
