### ISSUE TITLE
Remember document position but not opened files

### ISSUE THREAD

**Issue by maik-s** [sumatrapdfreader/sumatrapdf#450]
It would be nice, if Sumatra remembers the document position (page number, scaling etc.) even though the option `remember opened files` is unchecked.

**Comment by kjk** [comment]
The purpose of this feature is privacy so remembering anything would defeat the purpose.

**Comment by maik-s** [comment]
but could we consider making this a user decision ? just by not disabling the checkbox. 
for privacy purposes a warning could inform the user .
