### ISSUE TITLE
Corrupted Install 3.6.16779

### ISSUE THREAD

**Issue by rjbprime** [sumatrapdfreader/sumatrapdf#4506]
**SumatraPDF version**
- Version 3.6.16779 pre-release

**Describe the bug**
Upon stating after install / update, presented with a Corrupted install notification

**To Reproduce**
1. Install / Update
2. Open program
3. See error

**Expected behavior**
Expected to work.

**File that reproduces the problem**
None.

**Screenshots**
![SumatraPDF Corrupted Install Notification](https://github.com/user-attachments/assets/b6bd8b7e-c0a7-4201-8f91-fea90869e2cb)

**Additional context**
none

**Comment by GitHubRulesOK** [comment]
can happen to me under certain circumstances and the simple solution is uninstall and reinstall because you probably installed for others  (or all users) and the dlls did not get replaced due to locked by file activity?

**Comment by rjbprime** [comment]
10-4. Usually install for all users, so yeah, I can understand. I did try uninstalling it with Hibit Uninstaller, to clean all configs and files with the uninstall, but upon reinstall, it was corrupted as well, hence why saying it was both install and update, as I updated first, got corrupted, clean uninstall, reinstall, corrupted.

**Comment by GitHubRulesOK** [comment]
I am running the 32bit installed version without any problems (except one edge case crash which I need to report) for about a week. Just for you I fired up the coked up 64 bit and updated and see all the dlls and exe are acounted for and runs without a problem thus it downloaded current 64bit installer and ran after asking for UAC elevation.

I thus have at that point to say there appears to be no generic issue with this version.

So either you have a bad download from 64bit? or you have more than one copy of dll(s) lurking somewhere ?

**Comment by rjbprime** [comment]
Double checked, rebooted, completely uninstalled all versions, done a search for the libmupdf.dll, made sure there were no traces of it on my system, cleaned the config folder to make sure there was nothing left. I then ran an admin command window, used the following commands ``%USER%\Downloads>SumatraPDF-prerel-64-install.exe -install -s -d "C:\Apps\Sumatra PDF\" -with-filter -with-preview -log -all-users``. It then proceeded to install and run correctly, and loads up multiple times fine.

On a side note, I do enjoy the new 3.6 Dark theme, looks more AMOLED like.

In anycase, I'll keep this open for a day or two, in case it corrupts again. Hopefully not, but things happen.

**Comment by GitHubRulesOK** [comment]
It is not just  libmupdf.dll but the other 2 that provide index filter and preview host support as used by explorer that could be locked.

Thus the exe may be same time or one second before the other 3 are installed 
![image](https://github.com/user-attachments/assets/688041e9-cbb6-4f81-addf-58b5747e93c3)
