### ISSUE TITLE
A bug in searching PDF files in Hebrew

### ISSUE THREAD

**Issue by IEUDI** [sumatrapdfreader/sumatrapdf#4507]
When conducting a search within a Hebrew document, the search fails, since the results are in the reverse order of the letters, for example a search of
 "עברית"
won't find the word
"עברית"
but only a search of
"תירבע"
will result in
"עברית"

**Comment by H5820121** [comment]
Download the new version on
https://www.sumatrapdfreader.org/prerelease
And there it has been fixed, but there are still problems with the Hebrew
search that I think sometimes misses Hebrew words, if you encounter this
please open an issue, and it is important that you attach the PDF file and
with a detailed explanation of the problem.

‫בתאריך יום א׳, 1 בספט׳ 2024 ב-11:31 מאת ‪IEUDI‬‏ ***@***.***
‬‏>:‬
