### ISSUE TITLE
Feature request: Button to save a copy of all opened PDFs to a chosen folder

### ISSUE THREAD

**Issue by Dynode** [sumatrapdfreader/sumatrapdf#451]
Too many times have I had opened lots of PDFs directly from a browser only to have to forcefully reset the PC, or only to have the PC crash, before I could finish skimming through the documents and saving the relevant ones (articles, presentations, datasheets, ...). When this happens, the Sumatra PDF Session is useless as the files are no longer present in memory.

Please, it would be nice with a "save opened documents to folder" button.

**Comment by kjk** [comment]
There's a reasonable work-around: save the file to disk. Direct browser integration via the plugin has been deprecated anyway due to changes in the browsers.
