### ISSUE TITLE
sumatraPDF copying the wrong URL?

### ISSUE THREAD

**Issue by nordicw0lf** [sumatrapdfreader/sumatrapdf#4513]
**SumatraPDF version**
- latest stable release

**Describe the bug**
in PDF files which have links in them, when I cliick on the "copy link address" option, it copies the wrong link

**To Reproduce**
it doesnt seem to be a wide spread issue, it happens only in my PC, for a reason which I dont know, doesnt happen on my laptop, only on my desktop.

**Expected behavior**
I expect sumatra PDF to copy the correct link

**File that reproduces the problem**
It happens with every PDF file that has links in it, it seems to happen only on my desktop PC though.

**Screenshots**
![scr1](https://github.com/user-attachments/assets/215bc46c-2328-4c65-8456-70334a79b67c)

**Additional context**
no further context, I have detailed pretty much everything.

**Comment by kjk** [comment]
No test file, nothing I can do.

If it happens on one computer but not the other, then the issue is with the coputer.
