### ISSUE TITLE
SumatraPDF-settings.txt no longer loaded after upgrade

### ISSUE THREAD

**Issue by bongbang** [sumatrapdfreader/sumatrapdf#4517]
**SumatraPDF version**
Version 3.5.2 64-bit Windows

**Describe the bug**
My old `SumatraPDF-settings.txt` in `%LOCALAPPDATA%\SumatraPDF` is no longer loaded or written to by Sumatra after the upgrade from 3.4.6 to 3.5.2.

My makeshift solution is to copy the file to `c:\Program Files (x86)\SumatraPDF\`, where the executable is, but I don't think new changes to Sumatra are being saved because Sumatra does not have permission to write to that location.

I know that the portable version of Sumatra puts the settings file where the executable is, but I didn't choose that option as far as I know. I don't remember being asked about it during the installation and I didn't make any changes to the default.

**To Reproduce**
Go to Settings > Options and make a change to, say, "Inverse search command line." Close Sumatra, relaunch, and see if the new setting is saved. 

**Expected behavior**
Settings should made should be saved to and loaded from `SumatraPDF-settings.txt` in `%LOCALAPPDATA%\SumatraPDF` as before.

**Additional context**
If I go to Settings > Advanced Options..., a new, empty `SumatraPDF-settings.txt` is opened in VS Code in `c:\Program Files (x86)\SumatraPDF\(x86)\SumatraPDF\`, which path doesn't currently exist. If I try to save, I can't for lack of permission. This behavior is very strange. I don't even know why Sumatra opens VS Code when my default editor for a .txt file is Vim.

**Comment by GitHubRulesOK** [comment]
The file as you say for an installed copy cannot be in program files it must be in the current users applications data area. for a portable 3.4 / 3.5 for a standalone (portable) copy outside a protected area it will be in that exe folder.

For 3.6+ "portable" currently it will also be in an app data area !!!! (thus not truly portable).

So in most above cases should be in c:\users\...\AppData\Local\SumatraPDF

**Comment by kjk** [comment]
It's a messed up installation. My recommendation is to install latest pre-release https://www.sumatrapdfreader.org/prerelease (it'll also fix opening settings with default .txt program).

It looks like you've installed just for current user but to %PROGRAMFILES%. Now Sumatra tries to save settings to %PROGRAMFILES% but doesn't have permissions.

**Comment by bianbiandashen** [comment]
C:\Users\bianlian\AppData\Local\Temp\sm -print-to "DASCOM TL-200Z" -print-settings 1-3,A4,simplex,shrink,monochrome,1x C:\Users\bianlian\AppData\Local\Temp\1_1.pdf 如果是这样命令行，我看SumatraPDF-settings.txt  会默认在C:\Users\bianlian\AppData\Local\Temp\ 生成，但是我调整了SumatraPDF-settings.txt 的信息 如： BitmapInterpolation = true
GraphicsAntiAlias = 2
TextAntiAlias = 2 试图减少锯齿感 但是没有生效 我用的是 3.5.2 的库

**Comment by bianbiandashen** [comment]
C:\Users\bianlian\AppData\Local\Temp\sm -print-to "DASCOM TL-200Z" -print-settings 1-3,A4,simplex,shrink,monochrome,1x C:\Users\bianlian\AppData\Local\Temp\1_1.pdf If this is the command line, I think SumatraPDF-settings.txt will be generated by default in C:\Users\bianlian\AppData\Local\Temp\, but I adjusted the information in SumatraPDF-settings.txt such as: BitmapInterpolation = true
GraphicsAntiAlias = 2
TextAntiAlias = 2 Tried to reduce aliasing but it didn't work. I used the 3.5.2 library

**Comment by GitHubRulesOK** [comment]
@bianbiandashen 
SumatraPDF would NOT normally be in the users temp folder
`C:\Users\bianlian\AppData\Local\Temp\sm`
it would normally look like this
![image](https://github.com/user-attachments/assets/be4a3e66-d3bb-4deb-a911-a3d9724b43b5)

SumatraPDF-settings.txt has NO graphics variables
<strike>BitmapInterpolation = true
GraphicsAntiAlias = 2
TextAntiAlias = 2 </strike>
