### ISSUE TITLE
Feature request: Option to have the program temporarily save local copies of documents opened straight from browser in memory -- to later be re-opened in session

### ISSUE THREAD

**Issue by Dynode** [sumatrapdfreader/sumatrapdf#452]
This is an alternative to Ticket 451: https://github.com/sumatrapdfreader/sumatrapdf/issues/451 

PDFs opened directly in memory from a browser can not be restored in Sumatra PDF session after a forceful reset of the PC or a PC crash. This of course if because the documents are no longer present in memory and were never saved to disk to begin with. Much time is lost by having to find which files were opened and re-visit document links.

(Often times when looking for information or skimming through dozens of articles for various projects, it is impractical to save or finish reading each document at a time.)

It would be nice to have an option for the following: The program temporarily save local copies of documents opened straight from the browser in memory. These files should then be opened in the session upon next time Sumatra PDF is started.

**Comment by kjk** [comment]
Browser integration (plugin) has been deprecated due to changes in web browsers.
