### ISSUE TITLE
"Error Loading" appears when opening a .cbz

### ISSUE THREAD

**Issue by Kamz064** [sumatrapdfreader/sumatrapdf#4527]
Hey all!

I am facing an issue with the software in which two of several pdf files does not load.
The rest of the files are running well.
I was reading a comic and it showed "error loading" when i tried to open the next chapter pdf file.
What can I do?

![Screenshot 2024-09-13 202947](https://github.com/user-attachments/assets/ab5b874a-20c9-451d-bcce-de384fa149c7)

Thank you!!

**Comment by GitHubRulesOK** [comment]
cbz is images in a zip NOT a PDF so try open the file with notepad (do not save it just look) if it start `%PDF` it should be a PDF if it starts `PK` then it may be a cbz and ***copy*** to `Chapter 18.cbz.zip` and double click it should show its contents.

**Comment by Kamz064** [comment]
> cbz and ***copy*** to `Chapter 18.cbz.zip` and double click it should show its contents.
> 
> simplest is go to the source but which one ?
> 
> I saw this one and saved the images into a zip folder then rename zip to cbz you then have a cleaner 13 copies of images 3 to  15 (rename if you wish before save as compressed.)
> ![image](https://github.com/user-attachments/assets/e660bbba-a62b-4002-908e-4f16b661134b)
> 
So, It starts with PK but I don't understand what to do next🙏🏾

**Comment by GitHubRulesOK** [comment]
no if the file is corrupt it will not work I downloaded those website images I found as a fresh set and put them in a zip folder then rename to .cbz 
[Read Manga Solo Leveling_ Ragnarok - Chapter 18 - Copy.zip](https://github.com/user-attachments/files/17001811/Read.Manga.Solo.Leveling_.Ragnarok.-.Chapter.18.-.Copy.zip)

**Comment by Kamz064** [comment]
> No if the file is corrupt (which is not a fault with SumatraPDF) it will not work
> I downloaded those website images I found as a fresh set and put them in a NEW zip folder then rename to .cbz
> Thus they may not be the same as your files but a working file.
> 
> [Read Manga Solo Leveling_ Ragnarok - Chapter 18 - Copy.zip](https://github.com/user-attachments/files/17001811/Read.Manga.Solo.Leveling_.Ragnarok.-.Chapter.18.-.Copy.zip)
> 

Ok thanks for the help 😊
