### ISSUE TITLE
Embedding in app not resizing

### ISSUE THREAD

**Issue by SkutchElectronics** [sumatrapdfreader/sumatrapdf#454]
I'm a Delphi programmer, I love this little reader but have had issues embedding it onto a panel in my test app.  The first problem, there was no example of using the command line to embed the app.  I discovered how this is done by using either ShellExec or CreateProcess and use> 'SumatraPDF.exe -plugin ' + IntToStr(window handle to plug into) + ' "full path and file name of PDF"'.  It docks into the panel fine, but when I resize the form it will not resize.  I set the panel to align to client, verified the panel size is changing, sent sumatra a resize message in the form's resize event trying both the following:
SendMessage(SumaHndl, WM_SIZE, SIZE_MAXIMIZED, MAKELPARAM(Panel1.Width, Panel1.Height));
Windows.SetWindowExtEx(SumaHndl, SumaPnl.Width, SumaPnl.Height, @OldSize);

SumaHndl is the handle of the SUMATRA_PDF_FRAME found after the embed process.  Panel1 is a standard panel that received the SumaPnl.  SumaPnl is a standard panel that sumatra is embedded onto.

**Comment by kjk** [comment]
Sumatra is not designed to be embedded (not to mention that there are licensing issue that you're most likely violating if your app is not under GPL).

**Comment by SkutchElectronics** [comment]
Sorry, I didn't state my intended purpose, I only need it for a couple of programs I personally use, do not distribute, hand have no intention of distributing, thereby not in violation of any gpl.
Secondly, it is made to park into web browsers through the -plugin option, and they can resize the window when they do, I just need to do that in my own app as well as I don't want to use a web browser to embed the program into it.  I've had too many issues arising from windows 10 and their stupid Microsoft Edge interface throwing things out into new windows; just wish Microsoft would stop trying to justify their jobs and just make a nice OS that works solidly. :(
