### ISSUE TITLE
Autohide the mouse cursor when inactive

### ISSUE THREAD

**Issue by planetkalpesh** [sumatrapdfreader/sumatrapdf#4541]
The mouse cursor should be automatically hidden after it is inactive. The inactive duration could be set in settings file in minutes.

**Comment by GitHubRulesOK** [comment]
Hiding mouse is usually only common in presentation software as it is not provided by Windows as a configurable setting.

It is in SumatraPDF presentation mode but not normal for other apps to hide it unless switched into editing mode as here.

The "hiding" for any other reason seems odd as usually you need to know where it is.

**Comment by kjk** [comment]
Not planning to do that. I don't know any other app that does that.
