### ISSUE TITLE
Unable to open epub file. Stuck on opening file

### ISSUE THREAD

**Issue by planetkalpesh** [sumatrapdfreader/sumatrapdf#4543]
**SumatraPDF version**
- SumatraPDF pre-release build version 16779, built on 2024-08-23
- 
**Describe the bug**
Unable to open epub file. Stuck on opening file

**File that reproduces the problem**
I have attached an epub file compressed in zip archive. Unzip it to access epub file. Here is the link;
https://www.mediafire.com/file/ntptaextblxkkj7/Willi-Hans_Steeb__Yorick_Hardy_-_Problems_and_Solutions_in_Quantum_Computing_and_Quantum_Information.zip/file

**Comment by kjk** [comment]
It's a large file so it takes time to load and layout but it opened for me in 7 secs.
