### ISSUE TITLE
The epub book includes svg images that don't display correctly

### ISSUE THREAD

**Issue by quicklwl** [sumatrapdfreader/sumatrapdf#4548]
**SumatraPDF version**
- Version [e.g. 3.5.2, pre-release]

**Describe the bug**
The epub book includes svg images that don't display correctly

**To Reproduce**
1. Go to  Istio & Envoy+内幕.epub
https://www.alipan.com/s/viMFq5pVTme
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
3. download this book
4. Open ...

**Comment by GitHubRulesOK** [comment]
such a link is no good 
use a copy of the epub and rename to zip
Then paste in your question

**Comment by quicklwl** [comment]
[Uploading Istio+&+Envoy+内幕.zip…]()
The SVG images in this book cannot be displayed

**Comment by GitHubRulesOK** [comment]
Apparently this is the Authors free version https://istio-insider.mygraphql.com/zh-cn/latest/
[istio-insider-mygraphql-com-en-latest.epub named.zip](https://github.com/user-attachments/files/17106704/istio-insider-mygraphql-com-en-latest.epub.named.zip)
[istio-insider-mygraphql-com-zh-cn-latest.epub named.zip](https://github.com/user-attachments/files/17106707/istio-insider-mygraphql-com-zh-cn-latest.epub.named.zip)

**Comment by quicklwl** [comment]
thank you

**Comment by GitHubRulesOK** [comment]
@kjk 
The "interactive e book" is supposed to be used as unpacked SVG images the Author states "right-click on the image in the browser and select Open Image in New Tab" thus does not expect it to be used in an ePub document reader.

>Interactive Books
It can be said that most of my writing time is not spent writing, but drawing. Therefore, using a computer to read the pictures is the correct way to open this book. Mobile phones are just a conspiracy to drain traffic. Most of the diagrams here are more complex, not PPT big pie charts. Therefore, it is basically not suitable for printing out paper books. But I'll let the graph interact with the reader:

Original drawings, mostly SVG images made with Draw.io: *.drawio.svg.
For complex diagrams, it is recommended to open with draw.io:

Some images provide a Open with draw.io link, which can be viewed in a more interactive way in the browser:
Where there is (underlined text), links to related documentation and lines of code.
Put the mouse on it and a hover window will pop up, prompting more information. Such as configuration file content.
If you don't like draw.io then just look at SVG:

>The correct posture to browse SVG images is to right-click on the image in the browser and select Open Image in New Tab. Large SVG image, middle mouse button pressed, free scroll/drag.
SVG images can click the link to directly jump to the corresponding source page (or related documents), sometimes accurate to the source line.
