### ISSUE TITLE
Wrong papersize when viewing PostScript file

### ISSUE THREAD

**Issue by Peter0** [sumatrapdfreader/sumatrapdf#455]
I luckily noticed that SumatraPDF also is able to open PostScript files.
Unfortunately, it shows the document **cropped**.

Ctrl-D shows as page size "29,7 x 21,0 cm **(A4)**" whereas the document's **bounding box** clearly states "%%BoundingBox: 20 79 774 1144", which translates to about 0.71, 2.79, 27.31, and 40.36 cm, resp. That is something like A3. Adding a scale command to the beginning of the document with scale factors of 0.7 lets the complete document appear.
Interestingly, in first instance, the bottom-right corner of the document is cropped. Naïvely, I'd expect the top-right corner being cropped, as the origin of PS' co-ordinates is bottom-left corner.

Please add support for papersizes other than A4.

I'm using SumatraPDF v3.1.1 64-bit

**Comment by Peter0** [comment]
Even Ghostscript's ps2pdf behaves the like.
It crops, if I don't force pagesize by means of "-sPAGESIZE#A3" parameter.
It crops also the bottom-right corner.
Conclusion: Maybe there is a flaw in the PS file.

**Comment by GitHubRulesOK** [comment]
Page definitions (like some image formats) can be taken from top left
so excess is taken as right and down (bottom right)
A4 Width is 210 mm / 25.4 = 8.2677... inches = approx 595 pts across
A4 Length is 297 mm / 25.4 = 11.6929....inches = approx 842 pts across
so you are right to presume any greater values are for a larger sheet
Bounding boxes for bleed gripper trim etc. are sometimes wrong or ignored
SumatraPDF uses any **installed** ghostscript for EPS and PS display so can be affected by any preset / default settings in GS or the files themselves

**Comment by GitHubRulesOK** [comment]
@kjk without a sample to test the original issue is difficult to confirm
However using a valid EPS and using SumatraPDF with recent GhostScript
Latest build 3.2.11874 saves at correct scaling :-)
![image](https://user-images.githubusercontent.com/12754913/71646336-cc4a3a80-2cde-11ea-9fe7-109b83ebcb14.png)
