### ISSUE TITLE
Add a button on the toolbar to enter fullscreen mode

### ISSUE THREAD

**Issue by threefcata** [sumatrapdfreader/sumatrapdf#4555]
I read PDF on a tablet in fullscreen mode. But I need to tap the menu item to enter fullscreen every time, which is a little tricky because the menu items are a little too small.

It'll be great to have a toolbar button to enter fullscreen mode.

An alternative would be double tapping. That'll provide a consistent experience with double tapping to exit fullscreen mode, but this way it's less obvious.

**Comment by GitHubRulesOK** [comment]
I thought the UI dialog font was configurable thus a tablet long hold should pull up larger context for full / exit ?
It is in pre-release here, but you can also add a button. 
![image](https://github.com/user-attachments/assets/093f6dde-43da-4643-86ca-57f4f4d957be)
