### ISSUE TITLE
EPUB opening crash

### ISSUE THREAD

**Issue by ryanKinoti** [sumatrapdfreader/sumatrapdf#4556]
**SumatraPDF version**
- V3.5.2

**Describe the bug**
EPUB file opening issue

**To Reproduce**
1. Open attached epub file
2. the app takes a few seconds before it unexpectedly crashes and generates the crash report

NB: make the reader the default pdf reader

**File that reproduces the problem**
Find attached epub file
[items.zip](https://github.com/user-attachments/files/17145237/items.zip)

**Additional context**
Link to gist with the crash report `https://gist.github.com/ryanKinoti/ba6be127dfcfac9da65e540fa1ab269c`

**Comment by kjk** [comment]
Thanks for the report.

Already fixed in [pre-release](https://www.sumatrapdfreader.org/prerelease)
