### ISSUE TITLE
Embedding in app not resizing

### ISSUE THREAD

**Issue by SkutchElectronics** [sumatrapdfreader/sumatrapdf#456]
In my original post I wrote:
I'm a Delphi programmer, I love this little reader but have had issues embedding it onto a panel in my test app. The first problem, there was no example of using the command line to embed the app. I discovered how this is done by using either ShellExec or CreateProcess and use> 'SumatraPDF.exe -plugin ' + IntToStr(window handle to plug into) + ' "full path and file name of PDF"'. It docks into the panel fine, but when I resize the form it will not resize. I set the panel to align to client, verified the panel size is changing, sent sumatra a resize message in the form's resize event trying both the following:
SendMessage(SumaHndl, WM_SIZE, SIZE_MAXIMIZED, MAKELPARAM(Panel1.Width, Panel1.Height));
Windows.SetWindowExtEx(SumaHndl, SumaPnl.Width, SumaPnl.Height, @OldSize);

SumaHndl is the handle of the SUMATRA_PDF_FRAME found after the embed process. Panel1 is a standard panel that received the SumaPnl. SumaPnl is a standard panel that sumatra is embedded onto.

Sorry, I didn't state my intended purpose, I only need it for a couple of programs I personally use, do not distribute, hand have no intention of distributing, thereby not in violation of any gpl - (try not being so paranoid, ask questions if something pops up red flags, lashing out and closing the thread is just rude!) -
Secondly, Sumatra is made to park into web browsers through the -plugin option, and they can resize the window when they do, I just need to do that in my own app as well as I don't want to use a web browser to embed the program into it; I have enough problems just getting a PDF viewer going, web browser add a whole new level of hassles to the mix and slow things down big time. I've had too many issues arising from windows 10 and their stupid Microsoft Edge interface throwing things out into new windows; just wish Microsoft would stop trying to justify their jobs and just make a nice OS that works solidly. :(

**Comment by kjk** [comment]
Like I said before, Sumatra is not designed for embedding. Whatever issue you have, you have to figure it out yourself.

**Comment by vgturtle127** [comment]
@SkutchElectronics He isn't trying to be rude, he is just unable to help you with your problem since he isn't a Delphi programmer (as far as I know), and also the plugin was depreciated since all web browsers now have a built-in PDF viewer.

Also, If you are trying to create a Delphi application that will house a C++ application, you are going to need to do more work than if you just created a PDF viewer from scratch in Delphi. I don't think Delphi has any libraries that support loading C++ libraries, but maybe. You should Google around and see if anybody has created such a library.

**Comment by SkutchElectronics** [comment]
I finally broke down and just purchased the PDFium component from winsoft.sk; a little bit of coding to get it together, but it is a true Delphi component, decent for $100.  A little disappointing about Sumatra though, nice little app.

**Comment by vgturtle127** [comment]
@SkutchElectronics Dang, I can't afford anything like that. I'm glad I am a C++ developer so I don't have to pay for squat. :wink:
