### ISSUE TITLE
Czech language not work, still in english

### ISSUE THREAD

**Issue by Fighter158** [sumatrapdfreader/sumatrapdf#4565]
**SumatraPDF version**
- Version [e.g. 3.5.2, pre-release]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

**Screenshots**

**Additional context**

**Comment by scscgit** [comment]
@Fighter158 You forgot to write any issue description.

And yes, I can also reproduce languages like `Slovak` and `Czech` not working.

**Comment by GitHubRulesOK** [comment]
Closing as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/3867
there is no 3.5.2 pre-release use 3.6 pre-release
![image](https://github.com/user-attachments/assets/615551db-12c2-4c96-9a8f-321b8d92351a)
