### ISSUE TITLE
Pages per sheet

### ISSUE THREAD

**Issue by BKSoftCraft** [sumatrapdfreader/sumatrapdf#4569]
How to set pages per sheet while printing with Command-line arguments

**Comment by GitHubRulesOK** [comment]
That is a windows Dialog setting depending on print driver. (Often non negotiable)
**FOR EXAMPLE** MS PDF will NOT allow more than 1 Page at a time.

What you are asking is in effect N-UP control 2 sheets on 1. This is best done using a N-UP command line tool (ideally one that does the printing like GhostScript).

**Comment by v3nus-py** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
