### ISSUE TITLE
I don't want to use darkmode. How can I do that?

### ISSUE THREAD

**Issue by minhthien2016** [sumatrapdfreader/sumatrapdf#4574]
I don't want to use darkmode. How can I do that?

![image](https://github.com/user-attachments/assets/c6adb82f-4752-40f2-8fcb-e50c991a2ac9)

**Comment by GitHubRulesOK** [comment]
perhaps you pressed the `I` key which will in 3.5.2 "invert" colours ? newer versions it would be Uppercase `I`

**Comment by minhthien2016** [comment]
Thank you very much.
