### ISSUE TITLE
Is there any option of saving (save instead of 'save as') currently opened pdf(s) in their respective folders?

### ISSUE THREAD

**Issue by kevivs** [sumatrapdfreader/sumatrapdf#460]
In specific cases of saving text highlighting available in prerelease version, can we enable 'save' file? (so that it overwrites the currently opened pdf without any prompt whatsover for each file in it's own folder location). 
This will be very, very convenient e.g in a use case when reading pdf books and highlighting texts but saving with one keystroke instead of going thru 'save as' scenario, which becomes **very **cumbersome as the folder location of previously saved file is remembered by Sumatra instead of file's current location and we have to navigate to file's own folder for each file opened while saving only the highlighted text.
Please enable 'save' atleast in pre-release.

**Comment by kjk** [comment]
I don't have plans to add such feature.
