### ISSUE TITLE
CHM help index not displayed

### ISSUE THREAD

**Issue by CarloDe** [sumatrapdfreader/sumatrapdf#461]
PDF Reader (SPR) does not display the index of CHM files.

Stats:
SPR v3.1.1-64 bit / SPR pre-relase build 1088-64 bit
Windows 7 Pro-64 bit / Windows 8.1 Pro-32 bit / Windows 10 Pro-64 bit
different CHM files from different companies

With Microsoft HTML Help, CHM file indexes are displayed correctly (difference see screenshot from Win10).

![screenshot](https://cloud.githubusercontent.com/assets/17760994/13665458/e541cbf6-e6ac-11e5-90f1-3dddd5a3b821.png)

As an example, I added a help file from WinMerge 2.14 (see http://winmerge.org/).
[WinMerge.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/166951/WinMerge.zip)

**Comment by GitHubRulesOK** [comment]
@kjk 
behaviour of file is working as expected from current SumatraPDF
i.e SumatraPDF is not a full replacement for MS Help Viewer which is available from File open
 but a lightweight viewer of the CHM file contents (in 2 alternative fashions)

![image](https://user-images.githubusercontent.com/12754913/72166420-18713b00-33c1-11ea-9cea-f270e7b759f6.png)

**Comment by kjk** [comment]
Sumatra doesn't support the index and there are no plans to add that.
