### ISSUE TITLE
annotations are too easy to delete  by accident

### ISSUE THREAD

**Issue by VladimirAlexiev** [sumatrapdfreader/sumatrapdf#4613]
**SumatraPDF version**
- Version 3.5.2 64bit

**Describe the bug**
DEL while editing annotation text deletes the whole annotation.

**To Reproduce**
1. select something
2. click "a" to make an annotation
3. rclick and select "edit highlight annotation"
4. start entering some text. Click DEL in the edit box 
5. The annotation disappears

**Screenshots**
This shows the state just before clicking Del:
![image](https://github.com/user-attachments/assets/9e3cdd3f-83bf-48c9-b776-a9dbb4149804) 

**Additional context**
This edit box is deficient in another way too:
I use a clipboard manager (Ditto). In all other programs, when I select a previous Copy text, it's pasted in the current text box.
But not in the Annotation editor: I also need to press Control-V

(Thematically related to #4612)

**Comment by GitHubRulesOK** [comment]
duplicate fixed and closed  in pre-release
checking

**Comment by VladimirAlexiev** [comment]
Thanks @GitHubRulesOK ! 
The prerelease is at https://www.sumatrapdfreader.org/prerelease, and it's immensely faster on startup
(I have like 20 PDFs opened, and I like they are reopened on restart).
