### ISSUE TITLE
Closing multiple tabs with mouse.

### ISSUE THREAD

**Issue by unkn0w7n** [sumatrapdfreader/sumatrapdf#4619]
**Is your feature request related to a problem? Please describe.**
I have too many tabs/windows open. Closing them at a time with mouse becomes a problem as the tabs readjust immediately.  Which requires me to move mouse around to close each of the rest.

**Describe the solution you'd like**
I want a delay in the tabs readjustment. Like we can see in web browsers. They take some delay. I can just keep the mouse stationary and keep clicking to close all/some tabs. After that delay they readjust to larger tabs.

**Describe alternatives you've considered**
OfCourse there is already a `Ctrl + W` here. But I think users would benefit from a mouse friendly feature too.

**Comment by GitHubRulesOK** [comment]
there are several ways the tabs move about as the numbers change so no easy way to keep closure box in one place thus by far the easiest is keep any wanted to one side or the other and use delete to right or delete to left (drag the wanted tabs first)

![image](https://github.com/user-attachments/assets/06403e47-b4b3-4c43-9cbc-910ed51acf59)

**Comment by unkn0w7n** [comment]
Okay.
