### ISSUE TITLE
Feature request : allow Sumatra to identify different file types with specific icons

### ISSUE THREAD

**Issue by Bluezy** [sumatrapdfreader/sumatrapdf#462]
Just a convenience feature really: different icons to distinguish at a glance between file types would be nice. 

As things stand, once a file type is associated with Sumatra, all pertinent files end up looking the same. The Sumatra yellow icon is very nice, but too much of it is... well, just too much !

The solution could be as simple as providing the current Sumatra icon in different colors, with the ability for the user to associate a specific color with a specific type. (When i say simple, I realize, of course, that, programmatically, it may not be quite so simple...)

While I have your attention, allow me to use the opportunity to thank you, all Sumatra programmers, for a very useful and very well done application. It is simply marvelous.

**Comment by SumatraPeter** [comment]
The devs have been waiting for _years_ for a graphics pro to donate file type icons. Unfortunately no-one has stepped up yet. If you know someone and can help get this done we'd all be grateful, believe me.

**Comment by GitHubRulesOK** [comment]
Topic covered by developer in #600 so am cross-referencing and closing
