### ISSUE TITLE
Caps lock disables 'f' for fullscreen

### ISSUE THREAD

**Issue by JoePalffy** [sumatrapdfreader/sumatrapdf#4622]
**SumatraPDF version**
- Version 3.5.2 64bit

**Describe the bug**
I usually full screen my manga when reading and I use the 'f' key for that, but today my caps lock was on by mistake and I could no longer go to fullscreen, anyway after a short panic and some research, I figured it out.
So hitting the 'f' key for fullscreen works, but hitting "F" does not ?
No other program that uses 'f' for fullscreen (like Chrome or MPC-HD) has that issue (I just tested it).
Please fix.

**To Reproduce**
1. open file
2. hit the 'f' key, notice that it works
3. enable Caps Lock and hit f again

**Expected behavior**
Both 'f' and 'F' should full screen the file I'm viewing.

**File that reproduces the problem**
If this is related to a specific PDF etc. file, please attach the file.

**Screenshots**

**Additional context**

**Comment by GitHubRulesOK** [comment]
since can only be fixed in a new version use the newer version where you set your own keys 

Hmm is that not version 3.5.2 ?

**Comment by JoePalffy** [comment]
No, it's definitely version 3.5.2 and I know I can add my own shortcuts, I did so already. The point is that I shouldn't have to add this one. I've never heard of keyboard shortcuts being caps sensitive.
Anyway thanks for the quick personal fix, but this is a problem for every user.

Also both `Shift + Ctrl + L` and `Shift + Ctrl + l` work, but any other 1 letter shortcuts like `n` or `p` don't work with caps lock on (as `N` or `P`) so this seems to be a somewhat global issue.
