### ISSUE TITLE
PNG image in xps file shows incorrectly

### ISSUE THREAD

**Issue by xinsheng** [sumatrapdfreader/sumatrapdf#463]
![1](https://cloud.githubusercontent.com/assets/1817983/13739838/635c3c84-ea08-11e5-897f-46cb3f085f61.jpg)

a png file cannot shows correctly when using sumatrapdf, it looks like display the height of the png not right.

**Comment by xinsheng** [comment]
because the xps file cannot upload, you can download from here:
http://pan.baidu.com/s/1i3RM4W9

**Comment by xinsheng** [comment]
at the source /mupdf/source/xps/xps-tile.c line 142,
the yscale is small than usual, so that the png show incorrectly, i cannot find out how correct the code :(

**Comment by SumatraPeter** [comment]
Since you've traced the bug, perhaps it's best to report it to the mupdf devs instead?

**Comment by GitHubRulesOK** [comment]
@kjk the recent changes shifted the above referenced line and original sample appears not available.

My test using a circular PNG in a document setting printed to an OXPS looks the same in both XPS viewer and SumatraPDF. the original xps may have had different internal image scale settings, but I can't replicate this issue without an original image.

![image](https://user-images.githubusercontent.com/12754913/70396722-7518b900-1a03-11ea-99cd-67f823a1f986.png)

**Comment by kjk** [comment]
Closing as can't make progress without the test case.
