### ISSUE TITLE
I want to convine diferents files to create a new one.

### ISSUE THREAD

**Issue by eldeejay** [sumatrapdfreader/sumatrapdf#464]
it would be nice and usefull to  have the possibility of convine to diferentes files to creat a new one. And defenitly, if it can combine to  diferents kind of file (for example: pdf and ePub or DjVu and MOVI, etc) will turn this free softwae  into the most amazing tool.

**Comment by kjk** [comment]
Sumatra is a reader, not an editor. I don't have plans to implement editor features.
