### ISSUE TITLE
Pressing Delete key when editing annotation text deletes the entire annotation

### ISSUE THREAD

**Issue by shayriggs** [sumatrapdfreader/sumatrapdf#4649]
**SumatraPDF version**
- Version 3.5.2 64-bit on Windows 10

**Describe the bug**
When editing the text content of an annotation, pressing the Delete key (not Backspace) deletes the entire annotation rather than deleting the character under (or to the right of) the cursor.

**To Reproduce**
1. Right-click on PDF and select “Create annotation under cursor” then “Text”.
2. Start typing into “Contents:” field.
3. Press Delete key.
4. Despair at lack of Undo.

**Expected behavior**
The Delete key should behave as it does in any other text field or text editor and delete the character to the right of the cursor. For what it’s worth, I think the Delete annotation button is sufficient for this purpose.

**Comment by GitHubRulesOK** [comment]
That was altered (fixed) in current pre-release 

Duplicate issue so closing when I find which one
