### ISSUE TITLE
feature request: allow printer controls embedded in pdf

### ISSUE THREAD

**Issue by arbyter1** [sumatrapdfreader/sumatrapdf#465]
A page containing a control like {@@tray-select:tray2} should  change to paper-tray 2 until another command is detected or until end of job.
The control itself should not print out.
I am searching for this feature a long time. 
 
Anybody helps me to implement such a feature?

**Comment by kjk** [comment]
As far as I can tell, there's no such thing in PDF standard.

**Comment by arbyter1** [comment]
The question was not, if it is a standard. I know, it is not standard.
The question is, if Sumatra PDF Reader could implement such a feature, 
because there is a great demand for such a feature.
The implementation doesn’t have to be free. Tell me the price, this 
would cost.

mit freundlichen Grüssen

Robert Hofer
Hofercomputing GmbH
Haldenstrasse 19

3550 Langnau

034 402 70 55

rh@hofercomputing.ch




------ Originalnachricht ------
Von: "Krzysztof Kowalczyk" <notifications@github.com>
An: "sumatrapdfreader/sumatrapdf" <sumatrapdf@noreply.github.com>
Cc: "arbyter1" <rh@hofercomputing.ch>
Gesendet: 16.03.2016 22:58:59
Betreff: Re: [sumatrapdf] feature request: allow printer controls 
embedded in pdf (#465)
