### ISSUE TITLE
how to open winafl.sln in Visual Studio

### ISSUE THREAD

**Issue by ak-nineteen47** [sumatrapdfreader/sumatrapdf#4657]
unable to open the Solution in Visual Studio Navigate to your build directory and open winafl.sln.

![winafl sln](https://github.com/user-attachments/assets/5ac6955d-f1e3-45d5-8cbe-5620442262e9)

**Comment by GitHubRulesOK** [comment]
I do not try to run a build from command line as the VS studio will run and resolve most of whatever you require from the IDE when you open the master SLN from 2022 using 2019 
![image](https://github.com/user-attachments/assets/10adc6d0-6bdf-45e3-ad1e-98dce0a1a820)

HOWEVER the main problem I have is 2019 32 bit is stuck with 1.42 tools not able to use 1.43 tools thus have first to set a few changes for 32bit compiling so first off need a 32 bit copy of MakeLZSA.sln or else it fails if 64bit EXE is not replaced.

**Comment by GitHubRulesOK** [comment]
Closing as question was migrated by OP to https://github.com/googleprojectzero/winafl/issues/450

**Comment by ak-nineteen47** [comment]
hey Ujjal, @GitHubRulesOK I was trying to follow your recommended steps, but I was unable to get it. I was doing this to get the bin32 & bin64 for winAFL. Can you help ?

**Comment by GitHubRulesOK** [comment]
Sorry I dont understand the C/CPP build systems thats why I use a prepared SLN then just run any of the many (12 ?) desired builds.

**Comment by ak-nineteen47** [comment]
it's okay. Let me try to get 32 bit copy of MakeLZSA.sln as suggested by you and follow.
Thanks @ak-nineteen47

**Comment by GitHubRulesOK** [comment]
@ak-nineteen47 
looking at the compiled date I think I use an earlier historic upload as shown here https://github.com/sumatrapdfreader/sumatrapdf/commit/77731d925244946485c7a3580959a13acf40ef0b
