### ISSUE TITLE
Forward search highlight colour

### ISSUE THREAD

**Issue by shimself** [sumatrapdfreader/sumatrapdf#466]
The settings file says the Forward search highlight colour is 6581ff, which I think is a sort of mid blue, but in fact of course it is mid yellow
Changing this to another value doesn't seem to affect it

I'm sure it's me but cannot figure it out, thanks

**Comment by kjk** [comment]
as the documentation says "customization options for how we show forward search results (used from LaTeX editors)" (http://www.sumatrapdfreader.org/settings.html).

**Comment by shimself** [comment]
*Thanks for the help - but it seems to me **
**
1 that changing the setting makes no difference*

*setting:*
*(ie bright yellow)*
*result*



*and 2**
**the pale yellow colour is the complement of 6581ff.  Images follow:**
**
**colorpicker**
****
**
**
**sumatra**
****
**
**
**the ini file:**
**
****
**
**Steve
**
**
*

On 16/03/2016 23:00, Krzysztof Kowalczyk wrote:
>
> as the documentation says "customization options for how we show 
> forward search results (used from LaTeX editors)" 
> (http://www.sumatrapdfreader.org/settings.html).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/sumatrapdfreader/sumatrapdf/issues/466#issuecomment-197570525>
>

-- 
Steve Hayes
90 rue d'Auvergne, 34200 SÈTE, France
             fixe +33 (0)4 30 41 65 40
         portable +33 (0)6 8 77 55 005
