### ISSUE TITLE
Proposal: Add Android Support for SumitraPDF

### ISSUE THREAD

**Issue by VR-Rathod** [sumatrapdfreader/sumatrapdf#4664]
### Overview
As mobile usage continues to rise, it’s crucial that SumitraPDF expands its capabilities to include seamless support for Android devices. This proposal outlines the vision for enabling SumitraPDF on Android, making it a versatile solution for reading, editing, and managing PDFs on the go.

### Key Benefits:

Wider Reach: Android is one of the most widely used mobile operating systems, and adding support will significantly increase SumitraPDF’s user base.
Enhanced User Experience: With mobile-friendly features like touch gestures, easy navigation, and offline capabilities, SumitraPDF can offer users an efficient PDF experience wherever they are.
Improved Productivity: Users can manage and annotate PDFs on their Android devices, boosting productivity in a mobile environment.
Implementation Ideas:

User Interface: Design a mobile-first UI, optimized for smaller screens with touch interaction support.

### Features to Include:
PDF viewing, annotation, and editing.
Bookmarking and easy document search.
Support for various PDF file types and sizes.
Cloud synchronization and offline modes.

**Comment by GitHubRulesOK** [comment]
That would be a very artificial view of a VR botnick in the real world it is not possible
SumatraPDF code is built on MuPDF dlls  for Microsoft hardware.
Google Android does not have the same abilities as a Desktop so Google never added a PDF viewer in that device but you are welcome on your own to boost the Android MuPDF  viewer I think it works there such that Adobe use its code for viewer.

even Apple have many issues in iOS and Althugh SumatraPDF works on Linux and Macs it is not "designed" to dos o.

**Comment by user1823** [comment]
On Android, you can use [MuPDF viewer](https://play.google.com/store/apps/details?id=com.artifex.mupdf.viewer.app) or [Chaka](https://f-droid.org/packages/net.timelegend.chaka.viewer.app), which is a fork of MuPDF viewer with additional features.

GitHub repos of both:
- https://github.com/ArtifexSoftware/mupdf-android-viewer
- https://github.com/elementdavv/chaka
