### ISSUE TITLE
add borderless window type

### ISSUE THREAD

**Issue by Puffolino** [sumatrapdfreader/sumatrapdf#467]
A borderless window would maximize the usable space for viewing PDF files without occupying the full screen. Hiding not only the function bar but also the caption and the border of the window would allow to use additional space for viewing.

This mode should be activated by an additional command line parameter.

**Comment by kjk** [comment]
I don't have plans to implement such feature.

**Comment by Puffolino** [comment]
Okay, understand that this is not that important, as full screen mode is a
workaround. I have a notebook which has a screen resolution of 1600x900 so
when displaying a document each pixel on top and bottom missing hurts (at
least a little bit). Thought it could be done easily by setting a
'borderless' flag, but maybe it has a greater impact than expected.

Maybe sometime in the future you may change your mind, who knows :)

Anyhow, thanks for your great work - I love the program.

Cheers,
Michael

2016-03-16 23:01 GMT+01:00 Krzysztof Kowalczyk <notifications@github.com>:

**Comment by denisz1** [comment]
+1 this would be nice as an "advanced setting"

**Comment by rohit-kumar-j** [comment]
This is not borderless, but you can use [winaero-tweaker](https://winaero.com/winaero-tweaker/) for coloring out the borders

**Comment by GitHubRulesOK** [comment]
@rohit-kumar-j 
try using F8 & F9 rather than long winded CTRL+Keys method

**Comment by rohit-kumar-j** [comment]
> @rohit-kumar-j try using F8 & F9 rather than long winded CTRL+Keys method

Nice @GitHubRulesOK! 

Wow, I just found this in the [docs](https://www.sumatrapdfreader.org/docs/Keyboard-shortcuts)
