### ISSUE TITLE
Oh my god, this is a really bad bug.

### ISSUE THREAD

**Issue by temeipu-offical** [sumatrapdfreader/sumatrapdf#4670]
**SumatraPDF version**
![image](https://github.com/user-attachments/assets/2434542f-f768-442a-aef1-d52800e4eeb6)

**Describe the bug**
我的天哪，每次打开pdf文件时，都会报该错误，如下图所示。

**Screenshots**
![Snipaste_2024-12-01_16-14-18](https://github.com/user-attachments/assets/8d198e26-2af7-4c7a-9952-ef061029a783)

**Comment by GitHubRulesOK** [comment]
>Every time I open a pdf file, I get that error as shown in the image below.
Generally I open Dozens per day of PDFs (even known bad ones) without any problems using the pre-release.

Can not do anything without the crash report OR you try to refresh the exe.

**Comment by kjk** [comment]
No test file, not crash report, nothing I can investigate.
