### ISSUE TITLE
Want to learn 

### ISSUE THREAD

**Issue by PrashantChoudhary13579** [sumatrapdfreader/sumatrapdf#4671]
Sir i am currently learning about the fuzzing and want to fuzz the sumatra PDF so that i can find out the vulnerabilities which are present in the sumatra PDF. For this I have to find out the target functions , Can you help me by giving some file names which work for parsing, opening, rendering, etc. 
Adding on, if I am writing the harness for some target functions. There is a problem i am facing as the harness file contains some header files and it is showing the error that no such file or directory is there. Please help and guide me .

**Comment by kjk** [comment]
Sorry, not an expert in fuzzing

**Comment by ISH2YU** [comment]
> Sir i am currently learning about the fuzzing and want to fuzz the sumatra PDF so that i can find out the vulnerabilities which are present in the sumatra PDF. For this I have to find out the target functions , Can you help me by giving some file names which work for parsing, opening, rendering, etc. Adding on, if I am writing the harness for some target functions. There is a problem i am facing as the harness file contains some header files and it is showing the error that no such file or directory is there. Please help and guide me .

hey you can target libmupdf.dll tahts its rendering library will help u fetch better results than directly fuzzing exe and thats how fuzzing is done
