### ISSUE TITLE
Support Adobe-style parameters

### ISSUE THREAD

**Issue by pablotheissen** [sumatrapdfreader/sumatrapdf#469]
I would wish for SumatraPDF to accept some of the [adobe-style parameters](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_open_parameters.pdf) for opening files, namely opening a file to a specific page number.

In Acrobat it would look like `Acrobat.exe /A "page=5" test.pdf`while SumatraPDF with the same parameters tries to open `/A` and `"page=5"` as files and obviously fails.

Background is, that some software (namely Citavi) simply appends the `/A "page=5"` to the default pdf reader and doesn't use different parameters for different pdf readers. Thus when opening PDF files from within Citavi, SumatraPDF also tries to open "/A" and "page=5" as files.

**Comment by ironjan** [comment]
I've got the same issue as you. However I'm unsure on how or even if this functionality should be added to sumatra. Sumatra follows the convention of using [dash-based command line arguments](https://www.sumatrapdfreader.org/docs/Command-line-arguments.html). 

There are two possible solutions in my mind:
 * Write a standalone app or "wrapper" that supports these arguments and passes them on, i.e. something along the likes `SumatrapdfAdobeArgument /A "page=5" "file.pdf"`delegates to `sumatra.exe -page 5 "file.pdf"`
* Add the support to sumatra. Somehow along the lines of "if the user tries to open three files that match `/A`, `page=<some number>`, `file.pdf`, open `file.pdf` at page 5".

I'm more a friend of the first variant. I also contacted the Citavi support and notified them about this issue. Perhaps they will add support for non-adobe readers.

**Comment by ironjan** [comment]
Also another thought on the wrapper: AFAIK Citavi does not ahve a setting on which PDF reader to open, i.e. it will always rely on the system default. Therefor the "SumatrapdfAdobeArgumentHandler" would have to be system default.

---
Update: Citavi answered: "Thank you for your enquiry. Citavi starts the default PDF viewer with command line parameters. Sumatra's parameter syntax differs from the one Acrobat (Reader) uses. A possible solution can be found here in the old forum: https://support.citavi.com/forum/viewtopic.php?f=163&t=17529&p=64255

In effect, it's neither a bug in Citavi nor an issue in Sumatra."

Even if this answer they are technically correct, I don't like this answer.

**Comment by GitHubRulesOK** [comment]
@kjk
Some of this desired behaviour was written for the older plugin and is still working in plugin-test
As far as I can tell if the "/A" was either discarded or used as a flag for accepting the plugin syntax then at least #page= and #nameddest= would be covered and working ??

https://github.com/sumatrapdfreader/sumatrapdf/blob/06836e3a1c61c438eb73bf3dd0c9cd26fe13e8b9/src/SumatraStartup.cpp#L365
