### ISSUE TITLE
Feature request: Button or menu choice to show the Frequently read page

### ISSUE THREAD

**Issue by Murplugg** [sumatrapdfreader/sumatrapdf#470]
Being able to go back to that page and open other frequently read documents would be a nice function. Perhaps a keyboard shortcut could do as well.

**Comment by sastools** [comment]
I agree with this. Can a toolbar item be added to just open a new tab with the Frequently Read page there?
Probably, it needs to be the first item on the toolbar and maybe could be called Home?

**Comment by SumatraPeter** [comment]
Essentially a duplicate of #406

**Comment by GitHubRulesOK** [comment]
@kjk ? consolidate with https://github.com/sumatrapdfreader/sumatrapdf/issues/406#

**Comment by kjk** [comment]
Consolidate as #406
