### ISSUE TITLE
freetext annotation scale modify and some freetext bug？

### ISSUE THREAD

**Issue by RyanLei-icer** [sumatrapdfreader/sumatrapdf#4727]
version：3.5.2-64bit
我想在创建freetext注释时能够调整dx与dy的尺寸。
目前只能在高级设置里调整部分选项，建议可以增加一些实用的参数，使得在阅读pdf文本时可以有更多的标注样式。

此外，我还发现在输入汉字时出现了部分文字丢失的bug？如图所示。
![图片](https://github.com/user-attachments/assets/8734affd-906c-411d-8f4c-4fa5cfcb0821)

**Comment by RyanLei-icer** [comment]
And when I want to press the delete key to delete a character after the cursor, it usually causes the currently edited freetext comment to be deleted directly, which does not feel good.

**Comment by GitHubRulesOK** [comment]
The MuPDF default free text is as you Show SumatraPDF uses that.
![image](https://github.com/user-attachments/assets/33be8b76-7c74-44eb-be0b-680cb804161f)

Current pre-release works as expected with backwards and forwards delete
![image](https://github.com/user-attachments/assets/82163929-9d91-42b1-816a-e6bb594cdfc7)
