### ISSUE TITLE
Need to implement .JXL support

### ISSUE THREAD

**Issue by Vonarak08** [sumatrapdfreader/sumatrapdf#4729]
got some .cbz, the picture format inside was .jxl. Sumatra pdf was unable to read the jxl files

**Comment by GitHubRulesOK** [comment]
jxl has been discussed before so will close if this is similar

**Comment by GitHubRulesOK** [comment]
Ah here it is the status was
 `Feedback from MuPDF is currently "RESOLVED WONTFIX"`

but will leave that open and close this as duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/1943
