### ISSUE TITLE
Add a home button for opening an ever opened pdf

### ISSUE THREAD

**Issue by lisyxx** [sumatrapdfreader/sumatrapdf#474]
Can sumatrapdf add a home button so that we can open an ever opened PDF easily? I think it is convenient for users to add a new tab button on the right side of tabs or a home page button on the toolbar, Just like chrome browser.

**Comment by ordinary-user** [comment]
I'm not sure what is being asked here - is it a recently-opened list? If so, it's already there at the opening screen; would your home button jump back to there? My idea of a home button would be to jump back to page 1 of a file. Not sure if either can fit into the minimalist toolbar that's present.

Yes, I know, I can always pull up bookmarks and jump to any page that way, but there aren't any function keys on my tablet when the keyboard's disconnected so it takes several punches at the menu to get the bookmarks list, then use it.

**Comment by GitHubRulesOK** [comment]
@kjk generally covered by latest enhancements to favorites and bookmarks
Re the comment about access on a tablet:-
these are now readily accesible by touching the screen until the context menu appears then one click to add favourite etc.
