### ISSUE TITLE
printing rotation

### ISSUE THREAD

**Issue by kicchy** [sumatrapdfreader/sumatrapdf#475]
I'm using SumatraPDF to print pdf by command line to printer Zebra LP 2824 Plus.
When the report is printed, it is rotated 90 degrees.
Is there a way to avoid the rotation?

**Comment by mmally** [comment]
I have exactly the same issue with a Zebra LP 2844 printer which uses a endless 84mm wide paper roll. Usually the pdf is 84x54mm and was printed 90° rotated. As a work around I made the pdf document twice as high so it is 84x108mm and not it is printed correctly and the printer cuts it at 54mm. It seems that the document is automatically rotated. A command line switch to prevent auto rotation would help.
