### ISSUE TITLE
Request: Spin a or many frequently read document(s) and add a button to delete the history

### ISSUE THREAD

**Issue by salahoued** [sumatrapdfreader/sumatrapdf#477]
First of all I would like to think you for the effort to make this app libre and open source, and to tell you that I very like it.
So, to delete the history of the frequently read documents I deactivat and activat the options of remenmbring that, then the history is deleted, but I would like to see in coming version a button in the home (like Hide the frequently read) to delete that.
An other suggestion, is to add a function to Spin and remove a spined document in the frequently read like in Firefox.
Thinks.

**Comment by kjk** [comment]
I don't have plans to implement that.
