### ISSUE TITLE
Subscript/superscript in fb2 and epub does not work

### ISSUE THREAD

**Issue by CaptainFlint** [sumatrapdfreader/sumatrapdf#478]
When FB2 or EPUB book contains a subscript or superscript it is displayed as normal text, without any change. So that 10<sup>2</sup> becomes 102, etc.

Version 3.1.1-x64.

**Comment by GitHubRulesOK** [comment]
@kjk consolidate as eBook issue #45

**Comment by kjk** [comment]
Consolidating under #45
