### ISSUE TITLE
Paper size in command line printing

### ISSUE THREAD

**Issue by Addisonstumpf** [sumatrapdfreader/sumatrapdf#479]
When printing from the command line, it appears to be defaulting to a4 paper size, which makes my printer very unhappy. If there's a way to force it to change paper size with -print-settings, I've been unable to find it. Is there a way to add that as an option?

**Comment by kjlaw89** [comment]
I just saw this bug myself and it sounds pretty similar to my issue. I think implementing a "Use original Paper Sizes" command line option would probably work, since I think that pulls the size from the actual print job (my issue #486)

**Comment by littletreex** [comment]
This bug or design flaw still exists and it is plaguing me currently. The printer thinks the job is coming to it as A4 and wants A4 to be loaded. I have verified that the printer installation is set for "letter", and I can print the same PDF to the "letter" tray from any other program capable of printing PDFs without issue. Please fix this, or tell me how to fix this with the current options.

**Comment by boekhoffm** [comment]
Any fix for this - I tried: -print-settings "color,fit,bin=1", but that didn't work at all.

**Comment by boekhoffm** [comment]
I found "paper=A4" option works!

The options are all listed in "ParseCommandLine.cpp"
