### ISSUE TITLE
Incorrect center of zoom when pinching to zoom

### ISSUE THREAD

**Issue by EpicWolverine** [sumatrapdfreader/sumatrapdf#481]
When zooming with a mouse (Ctrl+Scroll wheel), the PDF is zoomed by using the position of the mouse pointer as the center of the zoom as expected. However, when pinching to zoom with a touchscreen, the center of zoom is in the upper left corner, not the midpoint between the fingers. This makes pinching to zoom confusing and frustrating to use.

**Comment by GitHubRulesOK** [comment]
@kjk duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/953 but this may be better description ?

**Comment by GitHubRulesOK** [comment]
@kjk directly related to #439 where zoom using plus and minus is applied in similar fashion

**Comment by SumatraPeter** [comment]
Related forum topic: https://forum.sumatrapdfreader.org/t/pinch-to-zoom-and-pan-like-microsoft-edge/2784

**Comment by kjk** [comment]
Fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/485817ee9eb392e1f1b831c72ab936ec30d07d98

**Comment by EpicWolverine** [comment]
Thank you!
