### ISSUE TITLE
keystroke and/or dde command to toggle last two zoom

### ISSUE THREAD

**Issue by lollita** [sumatrapdfreader/sumatrapdf#482]
keystroke and/or dde command to toggle beetwen last two zoom used. f.e. "fit width" and "last custom zoom".

**Comment by GitHubRulesOK** [comment]
@kjk 
In effect this is similar to 483 (which has only the dde request) thus this is a better description.

In effect  both are a request to add an api, cli or dde method to collect the result of Ctrl Y (last zoom setting) but with the added feature of also showing some history of the previous setting.

**Comment by kjk** [comment]
closing as almost the same as #483
