### ISSUE TITLE
Feature: Detaching tabs to separate windows

### ISSUE THREAD

**Issue by ZaclR** [sumatrapdfreader/sumatrapdf#485]
Hi!

I'd really love to see that it's possible to "detach" tabs by moving them out of the main window, and open them as a separate window. I have multiple large screens, and this feature is one I use a LOT (i.e. in Chrome). It's one of the only things I'm missing in Sumatra, and I hope it will be implemented in a future release.

Thank you for your time.

**Comment by SumatraPeter** [comment]
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/18
