### ISSUE TITLE
SumatraPDF GetProcessHandleFromHwnd error(3.1, 3.1.1)

### ISSUE THREAD

**Issue by besrml** [sumatrapdfreader/sumatrapdf#490]
Looking in the website SPDF is listed as compatible with Windows XP, whe i opened allways i get a advice of: Entry point not found for the process GetProcessHandleFromHwnd in the dinamic link library oleacc.dll. 
The problem only get present upon start SPDF(3.1 and 3.1.1) and not after using it, is posible to close the warning and continue to use SPDF without problem, oleacc.dll is present and is the correct version and size.

**Comment by kjk** [comment]
We have plenty of users on XP.

According to https://msdn.microsoft.com/en-us/library/windows/desktop/dd318087(v=vs.85).aspx that function should be available in XP.

That leads me to conclude that your copy of XP is corrupted in some way. Or maybe it's XP SP2 or earlier (I only test with XP SP3).
