### ISSUE TITLE
Automatically open next file in folder when reading cbr/cbz; double tap on page to enter/exit fullscreen when reading cbr/cbz

### ISSUE THREAD

**Issue by nightcatimmortal** [sumatrapdfreader/sumatrapdf#491]
Dear Friends,

First of all, SumatraPDF is fantastic little program; it is so good that destroys all incentive to use any other reader in the system. However, lack of some specialized features prevent it from happening, yet. 

In general, it would be great if SumatraPDF provided additional features depending on filetype used. Namely, what I described in the title for cbr/cbz files. SumatraPDF is already very touch friendly, but when you enter fullscreen - there is no way to exit it without keyboard. And assigning a special button to read next file in a directory is impossible for some tablets, and not very comfortable for others - but this feature is only relevant for comics, nothing else.

Please consider adding requested features in next releases. Thank you for your wonderful work!

**Comment by GitHubRulesOK** [comment]
Just a reminder that on most tablets you need to **use two fingers tap to exit fullscreen**

**Comment by GitHubRulesOK** [comment]
Two issues
1) Exit full-screen should generally be possible with double tap, however as requested in the past by SumatraPeter an alternative exit means is now added to the context menu (usually a long hold on screen)
thus, this is now addressed in part.

2) closing / consolidating as next file in folder is now duplicated by 
Load next Comic book after finishing with current book #1416
