### ISSUE TITLE
Greatly reduces the scale of the sheet and the distortion of colors !!!

### ISSUE THREAD

**Issue by bigvovan** [sumatrapdfreader/sumatrapdf#492]
Greatly reduces the scale of the sheet and the distortion of colors !!!
In other pdf viewer lists the normal scale.
And on the same page color distortion.

PDF document is created with the program XnView - JPG
![12](https://cloud.githubusercontent.com/assets/7887236/14307532/748281f8-fbd8-11e5-8a75-94b853c72617.jpg)
 images of the same size and created in one program.

![2](https://cloud.githubusercontent.com/assets/7887236/14307460/d0d0058a-fbd7-11e5-9503-246dc9bc548d.png)

![1](https://cloud.githubusercontent.com/assets/7887236/14307431/9c294e0e-fbd7-11e5-8365-370a0c6fa6bf.png)

PDF file - http://www.ex.ua/878949358842

**Comment by bigvovan** [comment]
I would like to amend. It distorts the color is not your program. The fastest way to a problem in the image. First, I put on the image watermark. And this program has spoiled the image (Watermark Software 8). Then he created a pdf with these images through the program XnView.

**Comment by GitHubRulesOK** [comment]
@kjk if colors is not an issue then the residual issue is the mismatch of page sizes in continuous mode thus related to https://github.com/sumatrapdfreader/sumatrapdf/issues/152
