### ISSUE TITLE
How to use regular expression for searches?

### ISSUE THREAD

**Issue by llinfeng** [sumatrapdfreader/sumatrapdf#493]
Hi,

I found the phrase "regular expression" from repo, but was an clear how to make it work. I also saw mentioning that Sumatra PDF does work with regex from this post: http://superuser.com/questions/416244/is-there-any-pdf-reader-that-supports-word-searching-with-regular-expression

Could anyone give a working example?

Thank you!

All the best, 

-Linfeng

**Comment by kjk** [comment]
We don't support regex searches (and the post above puts Sumatra in the "no regex support" list).

**Comment by Foadsf** [comment]
This could actually be a great feature. You already have search so adding regex should be doable.

**Comment by Foadsf** [comment]
this could turn into a collaboration with [dnGREP ](https://github.com/dnGrep/dnGrep/issues/310) and [Okular](https://bugs.kde.org/show_bug.cgi?id=174314).

**Comment by GitHubRulesOK** [comment]
Hmm only just had time to test dnGREP today however it looks well developed to do exactly that task,
![image](https://user-images.githubusercontent.com/12754913/157771547-983f4818-47cd-4f94-a691-0fc881cc418d.png)

for locating results its way better than pdfgrep which can just report text as found
```
"C:\Downloads\IJITDM-2012-Kou (1) (1).pdf"
"C:\Downloads\Open files from _MULTIPLE_ tabs in Acrobat (or other app).pdf"
         GitHubRulesOK
         GitHubRulesOK
         GitHubRulesOK
        GitHubRulesOK
        GitHubRulesOK
    GitHubRulesOK:
         GitHubRulesOK
      GitHubRulesOK:
         GitHubRulesOK
"C:\Downloads\PLRM.pdf"
"C:\Downloads\Reopen Closed Tab.pdf"
         GitHubRulesOK
         GitHubRulesOK
         GitHubRulesOK
        GitHubRulesOK
        GitHubRulesOK
        GitHubRulesOK
    GitHubRulesOK:
          GitHubRulesOK
"C:\Downloads\rma_pos_fw.pdf"
```
