### ISSUE TITLE
PRC files can't open

### ISSUE THREAD

**Issue by Rhysanton** [sumatrapdfreader/sumatrapdf#495]
Can't open PRC files
I suppose it is misleading to say Sumatra pdf supports PRC files

**Comment by kjk** [comment]
We do support PalmDoc ebooks with .prc extension. If you have a .prc file that doesn't open, please first verify that it is a PalmDoc file and if you're certain it is, please provide such file to us so that we can debug the issue.

**Comment by Rhysanton** [comment]
Dear Krzysztof

My mistake
My file was corrupt and the software worked perfectly
Thank you very much for your support
Best
