### ISSUE TITLE
Program uses  page size of default printer for every printer as default

### ISSUE THREAD

**Issue by UTerror** [sumatrapdfreader/sumatrapdf#497]
SumatraPDF uses the printer page size of the default printer for every printer.

I have 2 printers (copy of the same printer). 1 is configured for booklet printing on A3, the other (= copy 1) is for normal printing on A4.

When I set the "copy 1" (=a4) as default printer and use the CLI print command to print a booklet on the printer configured for A3, I get an error on the printer because SumatraPDF always uses the page size of the default printer instead of the page size of the selected printer.

The same thing happens when opening a file normally and selecting print via the menu.
(So setting a printer configured for A3 printing as default will make A3 the default for every print job and will let me print my booklets, but it still is a bug :-) )

![sumatra1](https://cloud.githubusercontent.com/assets/9993756/14509581/48ec76de-01cd-11e6-852d-03b34bcc4ce1.jpg)
![sumatra2](https://cloud.githubusercontent.com/assets/9993756/14509582/48eeaa4e-01cd-11e6-8905-0b5d4f04f7a3.jpg)

**Comment by GitHubRulesOK** [comment]
It is not a bug
SumatraPDFask windows what is the current default page size, and as you point out windows will reply with the current default, so you could switch defaults before printing.
OR instruct SumatraPDF to apply a different standard paper size from A6 to A2 (both recent additions). A3 and A4 were available in 2015

-print-settings "paper=<page size>" : page size is A5 to A2 or letter
