### ISSUE TITLE
Add more info about PDF in "Properties" dialog

### ISSUE THREAD

**Issue by Symbian9** [sumatrapdfreader/sumatrapdf#498]
PLEASE, add more info about opened PDF in "Properties" dialog of SumatraPDF!
Here is short list
- Color space info
- Fonts info
- Resolution DPI info (if presented)
## \* other specific info

Think, it would be good if Sumatra can tell more about PDF properties needed for professional printing, and can be alternative to Adobe Acrobat

Here is example of professional PDF export
- http://sk1project.org/downloads/release_prepress.pdf
- https://facebook.com/308311182521658/photos/a.562085380477569.128234.308311182521658/1163467910339310/

More info of this file look here
![sK1 2.0 alpha test](https://z-m-scontent-ams3-1.xx.fbcdn.net/hphotos-xfp1/t31.0-8/fr/cp0/e15/q65/12967360_1163467910339310_7497176434405273378_o.png.jpg)
This file created and distributed for testing by developers of sK1 editor for desktop publishing tasks:
- http://github.com/sk1project/sk1-wx

**Comment by GitHubRulesOK** [comment]
The above links are out-of-date
Please edit and replace with a screenshot of PDF file information export output from SK1 editor
note that information available as used by a PDF exporter may not always be available in a PDF file without using the editors analyser mode (Sword)

**Comment by GitHubRulesOK** [comment]
In general information stored within a final PDF is of little value to a user colors are stored per item so telling a user there are both some rgb items and some cmyk objects is not helpful and does not confirm what color will be seen on a display or will be different shades from one printer to another.

It is of value within an editor or compiler app where it is of value to a compositor prior to conversion into PDF objects.

The fonts an editor uses may be Alice or Bob but then during conversion into PDF objects they are given compiler names that my look like CMTI17 which helps me "guess" it may be one variation of Times Italic.

Point sizes are very rarely available 17 is not = 17 pt as they can vary from glyph to glyph within a stream representing perhaps a paragraph, which depending on reflow, hyphening, ligatures or non breaking spaces could vary in number of words or lines displayed, so word count can itself be variable for a given stream of glyphs.

DPI on one page can vary from area to area so how can it help to know a page or file has 75 and 208 and 1200 dpi in different zones or some pages.
Analysis of page components can be painstakingly slow whether in detail  or in a granular fashion.

The most common preflight output from most readers is "Tell me are some objects poorly defined such as Fonts" but in a valid PDF file that should not happen.

Thus, the most useful properties info in a reader beyond the currently visible page size, could be confirmation that not all fonts can be resolved internally, so I am closing as duplicated by https://github.com/sumatrapdfreader/sumatrapdf/issues/350
