### ISSUE TITLE
PDF search filter (IFilter) not working in version 3

### ISSUE THREAD

**Issue by Ant70** [sumatrapdfreader/sumatrapdf#499]
With SumatraPDF version 3 installed, many PDF files aren't being returned by Windows’ search tool following a content search that should be. With SumatraPDF version 2, search results are as expected. There seems to be a problem involving the PDF IFilter. My system is Windows XP, Service Pack 3 (32-bit).

I’ve performed a number of complete installations and re-installations, on each occasion ensuring the the desktop search option is selected. The versions I've tested are 2.4, 2.5.2 and 3.1.1.

**Comment by kjk** [comment]
The filter code didn't change between releases. The most likely reason is that after installation, the OS didn't have the time to (re)index all the PDFs, hence the difference in results.

Either way, there's nothing I can do to investigate further without more information (at the very least I need at least one .pdf that is not indexed by version 3 and is indexed by earlier version and the exact search term being used).

**Comment by Ant70** [comment]
Thanks for the quick post, Krzysztof. Delayed indexing isn't the reason. The Indexing Service on my PC is switched off. Each search is run directly on file content. 

My original installation was version 2.4, which worked fine. In February, I installed version 3.1.1. I noticed the problem three days ago. Here are the steps I took, in order. 

1. Reinstalled version 3.1.1 (without uninstalling) -- _didn’t work_ 
2. Uninstalled and reinstalled v. 3.1.1 -- _didn't work_ 
3. Uninstalled v. 3.1.1 and reinstalled v. 2.4 -- _worked_ 
4. Uninstalled v. 2.4 and installed v. 3.1.1 -- _didn’t work_ 
5. Uninstalled v. 3.1.1 and installed v. 2.5.2 -- _worked_ 

All uninstallations were performed with Revo Uninstaller (with default preferences), so were more thorough than SumatraPDF's uninstall process alone. There was a restart after each installation and after each uninstallation. In addition, with version 3 installed, I also tried installing Adobe's own PDF search filter, without success. 

There are well over 1,000 PDF files on my PC. The searches didn’t return a single one of them other than those with the search term in the file name. (As you probably know, XP includes file names in a content search.) The search terms were elementary and inclusive (such as "the"). The problem isn’t due to a peculiarity affecting just a handful of files. It appears to involve the IFilter--not necessarily its code, but perhaps its installation. 

Something that may be relevant is that SumatraPDF's uninstaller would report that it couldn’t remove the search filter. However, when I checked the Program Files folder, the entire SumatraPDF program folder had been successfully deleted. 

If you still want sample PDF files, please let me know--likewise any other information. Please avoid marking the thread closed until I’ve had a chance to reply.
