### ISSUE TITLE
remove uninstall.exe

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#5]
SumatraPDF.exe /uninstall should be equivalent to uninstall.exe and we don't need a separate uninstall.exe binary.

Steps:
- [ ] accept /uninstall cmd-line arg in SumatraPDF.exe
- [ ] copy SumatraPDF.exe to temp dir under a unique name (sm~inst.exe) and re-execute that binary with /uninstall flag
- [ ] when run from temp dir, show uninstall UI (Uninstall.cpp)
- [ ] do the uninstallation and try to remove yourself from temp dir

**Comment by GitHubRulesOK** [comment]
@kjk this one ?

**Comment by kjk** [comment]
Good catch, this has indeed been done.
