### ISSUE TITLE
Feature: Right click on a folder menu

### ISSUE THREAD

**Issue by ReaderV** [sumatrapdfreader/sumatrapdf#501]
Could add a right click menu up on a folder menu that contains pics files  (.jpg, .png)  the option 'Browse with Sumatra' . Sumatra works GREAT as a pic viewer if you dag n drop on open Sumatra window a folder containing images.

**Comment by VictorVG** [comment]
I am fundamentally opposed. Lead to the widening of the context menu to the size of the deranged. If the person you need to use the Registry Editor to create such a record in his car, and do it massively mandatory - no. In the morgue!

**Comment by GitHubRulesOK** [comment]
@kjk 
I suspect that this can be closed as best done by the user
A) You are not entirely happy to be associating images or their folders (only cbX ) with SumatraPDF
B) You are not likely to expand registry settings to integrate external folder context actions
C) this is most easily doable by the user

Here I added a copy of the SumatraPDF shortcut into my send to folder
so I can send other folders to SumatraPDF that should be as clear as mud pie?
lets show it working
![image](https://user-images.githubusercontent.com/12754913/73995608-131bf780-4951-11ea-9a6e-e4486cd06d99.png)


1) Make a copy of your working SumatraPDF shortcut
2) in the windows explorer address bar enter `%AppData%\Microsoft\Windows\SendTo`
it should look something like this
![image](https://user-images.githubusercontent.com/12754913/73995875-f3d19a00-4951-11ea-8d65-3f9c895b399a.png)

**drag and drop the COPY of the shortcut into that folder**

![image](https://user-images.githubusercontent.com/12754913/73996048-6d698800-4952-11ea-9bbb-a8b3c6f5a00c.png)

Your done 
Just be very careful what objects you send into SumatraPDF
YOU are sending them at your own risk without SumatraPDF guidance.
