### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by mingchau** [sumatrapdfreader/sumatrapdf#502]
File uploaded: http://ge.tt/8Ov0QqZ2
Attached a picture: 
http://7xsyt1.com1.z0.glb.clouddn.com/problem%20in%20using%20SamatraPDF.png

**Comment by GitHubRulesOK** [comment]
Unfortunately the second link appears dead and I can't find any browser that will allow me to download from ge.tt 
You should be able to add a zip of any files under 10Mb by editing your original post

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Suggest closing this ancient issue for lack of sample file, just as has been done with many others.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter agreed
