### ISSUE TITLE
FileStates/FilePath should use relative paths

### ISSUE THREAD

**Issue by vb0** [sumatrapdfreader/sumatrapdf#503]
I'm using the portable version and in SumatraPDF-settings file the documents are described with full path (c:\ ...). This prevents the app from being really portable. Actually I'm not using a USB stick but I sync a folder between multiple machines but it's the same idea. As of now I am using the same folders on all computers and it works great to sync the progress (and the added books and everything) across but it would be good if we didn't have this limitation.

**Comment by VictorVG** [comment]
I support the idea. A similar problem was and Process Hacker - some settings using the absolute path that caused the problem. The problem decided to simply - if there is next to processshacker.exe processhacker.exe.settings.xml all paths settings using relative format.

And why for SumatraPDF not do likewise? For example it will have a number of independent sets of settings for any copy of the program and how to switch the script or manually copying already secondary task. I think that the application of this there exists a lot, so just gave one possible example.

**Comment by kjk** [comment]
No plans to change things here.
