### ISSUE TITLE
Feature proposal : darken foreground.

### ISSUE THREAD

**Issue by 5050** [sumatrapdfreader/sumatrapdf#504]
Hi, 

This may be a fad, or the result of anti-aliasing fine lines, but I feel that more and more documents use grey fonts or lines instead of black, sometime too much clear to be viewed or printed correctly.

A tool to darken foreground infos would be very welcome, like a single button "Darken" which would apply -10% light to all foreground colors and grey levels. (Perhaps with exclusion of pictures if it is easy to handle ?)

**Comment by VictorVG** [comment]
Just read https://github.com/sumatrapdfreader/sumatrapdf/tree/master/docs/settings for details :)

**Comment by GitHubRulesOK** [comment]
Whilst the idea of percentage darkening of greys to black seems "reasonable" this is related to the way a PDF is structured thus a line less than a pixel should be grey and fonts are anti-aliased thus small ones will be "grey"
Adobe Do additional enhancements but MuPDF tries to render as true as possible the PDF source data.

I am closing as duplicate of request #1591 to darken lines.
MuPDF in more recent builds have added some line enhancements but its unlikely to be bettered.
