### ISSUE TITLE
Better wording for "Remove document"

### ISSUE THREAD

**Issue by petrasteri** [sumatrapdfreader/sumatrapdf#508]
On the Frequently Read page (when we open SumatraPDF without any PDF file), when we right-click on any previously open file to open the contextual menu, we have "Remove Document" at the bottom.

I suggest to change this to **Remove Document Record** or **Remove Document History**.

**Comment by GitHubRulesOK** [comment]
Related to https://github.com/sumatrapdfreader/sumatrapdf/issues/283

**Comment by petrasteri** [comment]
Well, any change to this "request"?  Come on!  It's been 4 years.  Moreover, the change of the words is logical, isn't it?

You don't *remove* a document when the document is still there after the operation.  What we *remove* is just the record or history.

**Comment by cheesecracker** [comment]
> Related to #283

But this issue has nothing to do with #283.  It is NOT related to that.  Please "unrelate" this bug and reopen it.

**Comment by GitHubRulesOK** [comment]
@cheesecracker 
This issue was closed because it was addressed clicking on the thumbnail has been renamed
To `Remove From History`

The ***relationship** was your request to add that "remove" function to a cross in the corner so as to  `Remove From History` which was never "closed" and is still open.

**Comment by cheesecracker** [comment]
OK, I just found that there's a new version 3.3.3 which has the "Remove document" changed to "Remove From History"
So, indeed, **this issue is fixed**.

**Comment by GitHubRulesOK** [comment]
@cheesecracker we are currently in 3.4 pr-release, however many current changes like the most recent are catch-up with the changes towards using more of MuPDF for format support or potentially regressions caused by that large move.
