### ISSUE TITLE
Changing MainWindowBackground not working

### ISSUE THREAD

**Issue by alphatydeus** [sumatrapdfreader/sumatrapdf#509]
On Windows 10 after editing SumatraPdf-settings.txt value MainWindowBackground and restarting the program again the New color will not apply. I have UseSysColors = false. What could be the problem ?

**Comment by kjk** [comment]
What value did you use?

**Comment by alphatydeus** [comment]
I used a hex color similar to the default one. Example: #ff00ff
I even tried different colors. I must also say that it seams some kind of bug because when I launch the program I will see for an instance (some milliseconds) a colored window then it will load the default white. Maybe it is loading the system color for some reason. I mean the same as if was UseSysColors = true
Ask me more if you want. I want to change that brigth color with a darker one because my eyes hurt.
Thank you.

**Comment by kjk** [comment]
I just tested with latest version and a value like:
```
MainWindowBackground = #ff00ff
```
It changes the main window to pink, as expected. BTW: you don't need to restart, saving the file is enough to trigger the change.
