### ISSUE TITLE
When hovering over highlighted region, comment is only shown for about 5 seconds

### ISSUE THREAD

**Issue by petebachant** [sumatrapdfreader/sumatrapdf#512]
It would be great if the comment could be shown indefinitely.

**Comment by powerpuff88** [comment]
To add on: It would be pretty neat if users can click on a comment, read through it and then click somewhere else in the PDF to exit the comment box.

**Comment by archie-m-vist** [comment]
I'd like to see the ability to click comments for a draggable comment box that I can close when I'm done with it; this is useful when a comment might be relevant to multiple areas in the text, but is not repeated at every instance.

Of course, with lightweightness being a concern, I'd be happy for just petebachant's suggestion of indefinitely-visible mouseover comments. As it stands, long comments (such as errata in rulebooks or remarks on academic work) are simply too difficult to read.

**Comment by Paul2017C** [comment]
I love to see this feature too. It is annoying that the tip window is gone before the tip is read. This behavior is different from Adobe Reader too.

**Comment by Vsevolod-Shustov** [comment]
I'd love to see this feature implemented too.

**Comment by dany4president** [comment]
Any news on this feature?

**Comment by GitHubRulesOK** [comment]
All, not the ideal answer but until there is a change in timer,
you can right click a comment and select the "Copy Comment" option then paste into another window i.e. a web site like this or the editor your using at the time or quickly start Notepad / WordPad to right click again and paste

**Comment by Tangvaffel** [comment]
+1, it's a pain to read long comments in Sumatra

**Comment by sky5walk** [comment]
Yes, the short 'popup windows for comments' exists even in the latest prerelease.
I think this is a tooltip window and their display time can be extended via an api command, TTM_SETDELAYTIME message.
It would be more functional to display an editable text box for copy and paste.
Whatever approach is taken will be a necessary improvement to read commented pdf's!

**Comment by GitHubRulesOK** [comment]
5000ms is the current default
5000 is the MAX allowed since a tip is just a quick hint and a brief "comment" should be SHORT !

**Comment by sky5walk** [comment]
[infotips are tooltips with more to say...](https://docs.microsoft.com/en-us/windows/desktop/uxguide/ctrl-tooltips-and-infotips)

**Comment by SumatraPeter** [comment]
> 5000ms is the MAX allowed by Windows

@GitHubRulesOK: Can you point me to the MS doc where you read that the MAX possible timeout value for tooltip/infotip display is 5 secs. only?

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
at the time I would have relied on msdn info which mentions setting.default up to 5000, however it looks like searching stackexchange/superuser comments the max is 16bit~32k thus 32650 should hold it for 32.65 seconds

**Comment by Enna1** [comment]
Hi @GitHubRulesOK 
Under my test, we can add a statement in `void TooltipCtrl::Show(const WCHAR* text, Rect& rc, bool multiline)` to make the comment display for about 32 seconds.
```diff
diff --git a/src/wingui/TooltipCtrl.cpp b/src/wingui/TooltipCtrl.cpp
index 36d92d65c..dcc63d06e 100644
--- a/src/wingui/TooltipCtrl.cpp
+++ b/src/wingui/TooltipCtrl.cpp
@@ -68,7 +68,7 @@ void TooltipCtrl::Show(const WCHAR* text, Rect& rc, bool multiline) {
     ti.rect = rc.ToRECT();
     UINT msg = isShowing ? TTM_NEWTOOLRECT : TTM_ADDTOOL;
     SendMessageW(hwnd, msg, 0, (LPARAM)&ti);
-
+    SendMessageW(hwnd, TTM_SETDELAYTIME, TTDT_AUTOPOP, (LPARAM)32767);
     isShowing = true;
 }
```

**Comment by GitHubRulesOK** [comment]
@Enna1 
If that's holding tooltip for 32 seconds **and a click elsewhere closes it** (to move on) then that certainly would be a vast improvement

**Comment by GitHubRulesOK** [comment]
@kjk 
If the above apparent current max of 32.767 (=32kb-1) works across comments, bookmarks, other tooltips and dare I mention tab names 🙂 then can we close this issue as met by the system limit ?

**Comment by Enna1** [comment]
@GitHubRulesOK 
I build a x64 release version for this, you can download it at https://github.com/Enna1/sumatrapdf/releases/download/Enna1-patched/SumatraPDF.exe

**Comment by GitHubRulesOK** [comment]
@Enna1 Thanks that's promising

My test suggest there may be a second affected location

**32 seconds on first screen** OR comments
![image](https://user-images.githubusercontent.com/12754913/80913668-41d22000-8d3e-11ea-9ee1-9c4c577ccd8f.png)


**But only 5 seconds on bookmarks** OR Toolbar tips
![image](https://user-images.githubusercontent.com/12754913/80913689-704ffb00-8d3e-11ea-9e6a-8f842b933e83.png)

@kjk are there multiple related locations ?

**Comment by kjk** [comment]
@GitHubRulesOK The reason it doesn't work for bookmarks view is: tooltip control is used internally by tree view. Not sure if there's a way to access it.

**Comment by GitHubRulesOK** [comment]
@Enna1 , Thanks for your investigation
and
@kjk for the extended implementation
although toolbar icon "tooltips" are defaulting to 5 seconds, I think that is acceptable
