### ISSUE TITLE
Move C key action to another key

### ISSUE THREAD

**Issue by Forkest** [sumatrapdfreader/sumatrapdf#513]
> **c**      toggle between continous/non-continous mode

From time to time I press C accidentally when trying to copy with Ctrl+C, and the toggle gets annoying. For a long time I was unable to identify what causes it and had to switch the mode from the menu every time. Please move the keyboard shortcut to some another key.

**Comment by GitHubRulesOK** [comment]
Similar to request #89 

In effect Duplicated by multiple other requests to reassign keys thus am consolidating this request as also covered by the wider discussion in #809
