### ISSUE TITLE
Session manager

### ISSUE THREAD

**Issue by Alexander-SPb** [sumatrapdfreader/sumatrapdf#514]
I couldn't find any PDF viewer that can allow to save and manage sessions of opened documents. Excellent example is "Session manager" for Firefox, the other one is Notepad++ (but only save/open).
This feature is useful for technicians, that work in machinery and civil engineering and for programmers. 
Reason:
I have to work with first group of schemes and plans at the same time, then close them and open the second group, then again with the first. Sometimes I need to open several books on PHP or several CAD, again it would be comfortable to use saved sessions with last opened documents and PaGeS.

**Comment by kjk** [comment]
No plans to implement that any time soon.
