### ISSUE TITLE
Clicking on a link to folder

### ISSUE THREAD

**Issue by miloush** [sumatrapdfreader/sumatrapdf#515]
When the PDF document contains a link to a folder on the disk, a new Sumatra window opens with files in that folder as bookmarks.

There should be a way (Shift+click, right click, preferably just the default) for such links to open the actual folders (i.e. using Windows Explorer). I can't really see when the current behaviour would be the author's intention.

**Comment by GitHubRulesOK** [comment]
Without legacy sample am closing as not a known behaviour in current code
 a simple link to a folder or directory is ignored in MuPDF as not a file to open
