### ISSUE TITLE
Reload a document

### ISSUE THREAD

**Issue by cloz54** [sumatrapdfreader/sumatrapdf#516]
Hello,

I am writing latex files on a program that generates pdf documents.

The issue is that  I often like to see the progress of my file and when I use SumatraPDF for viewing I need to close the file and open it again. Therefore, a "Reload document" option, or better a hotkey  for doing it, would be a very useful addendum for SumatraPDF.

Thanks in advance and I have to say that I am very pleased with your product.

Best regards,
César Lozada

**Comment by kjk** [comment]
We already have it: 'r' (http://www.sumatrapdfreader.org/manual.html)

**Comment by HolgerJeromin** [comment]
Perhaps it needs an menu entry for easier detectability :)
