### ISSUE TITLE
UseSysColors = true

### ISSUE THREAD

**Issue by goldencut** [sumatrapdfreader/sumatrapdf#517]
When I set UseSysColors = true then images in pdf-files get inverted (see screenshot). I have darkish system color schema, maybe that's the reason?
OS: MS POSReady2009 (~Windows XP SP3)
SumatraPDF: ver 3.1.1
![sumatra-1](https://cloud.githubusercontent.com/assets/5072792/15262189/6b95371c-1969-11e6-974d-62f540cdb576.jpg)

PS. In default settings file the MainWindowBackground = #80fff200. What color is that?

**Comment by kjk** [comment]
As per http://www.sumatrapdfreader.org/settings.html: UseSysColors over-writes FixedPageUI.TextColor and FixedPageUI.BackgroundColor.

#80fff200 is http://www.colorpicker.com/fff200 with 50% opacity i.e. semi-transparent yellow.

**Comment by goldencut** [comment]
Thanks for prompt reply. Ok, I understand that when I tell the program to use system colors then it uses the colors that OS specifies for text and background but why it INVERTS the colors in pictures embedded in PDF files (like seen in the screenshot). Does my OS somehow specify to invert colors of pictures? This occurs nowhere in the OS or other programs than Sumatra.

PS. Thnks, ARGB makes sense... ;) The help only mentions the RGB but not the alpha. 
G.
