### ISSUE TITLE
 UseSysColors = true shanges colors of pictures in pdf documents

### ISSUE THREAD

**Issue by goldencut** [sumatrapdfreader/sumatrapdf#519]
As per [ticket #517](https://github.com/sumatrapdfreader/sumatrapdf/issues/517), which was closed, using system colors for the viewer also changes colors of pictures embedded in pdf documents. Which is a bug or an undocumented 'feature'.

**Comment by kjk** [comment]
The feature works as designed. It was designed for text only PDFs. I don't have plans to improve that further.

**Comment by goldencut** [comment]
Weird, but Ok then...
