### ISSUE TITLE
No pages amount information

### ISSUE THREAD

**Issue by Loreno10** [sumatrapdfreader/sumatrapdf#52]
I opened this pdf file: http://ge.tt/9HJTDJ72/v/0 and in the toolbar I could only see which page I'm viewing without the information about the total amount of pages in this pdf. However when I switched to another tab and then got back to that pdf the amount of pages was displayed correctly. Unfortuantely (or fortunately) I couldn't reproduce this bug again. It happened only with this one pdf file.

**Comment by GitHubRulesOK** [comment]
@kjk unfortunately historic samples on ge.tt appear to not be accessible. Unless you or someone other than I can reload the file, then the only info is the description which in this case was "one file". From other similar issues it suggests the page numbers may have been encrypted,  thus I would close this one as insufficient info
