### ISSUE TITLE
Feature Request: tablet toolbar

### ISSUE THREAD

**Issue by wuebbel** [sumatrapdfreader/sumatrapdf#520]
I am aware that the main author is reluctant to change the toolbar. I think I have an issue, though.

On my tablet, sumatra is my favorite pdf reader, partially due to the double-tap option for maximizing the view. I usually read large scientific books which have multiple internal links, usage of these is vital for references and such. Therefore, I need quick access to the back button, back one page does not help since references are usually in the appendix. 

The usual answer seems to be: Use the keyboard. Which is hard if you have none. The context menu is empty except for mark all. I do have magnifying options, though - which are completely useless since I will use the pinching gesture for that.

Any way of exchanging these?

Best wishes, Frank

**Comment by GitHubRulesOK** [comment]
> I do have magnifying options, though ... Any way of exchanging these?

So what you are requesting is to substitute your preferred back forward options for those toolbar slots
