### ISSUE TITLE
Some problems with 3.2.10488 (32 bit)

### ISSUE THREAD

**Issue by dgdegiorgi** [sumatrapdfreader/sumatrapdf#521]
Recently I noted that some pages are shown empty ant Fit width shows message

Couldn't render the page.

At the same time Visit Website does not open a page in browser.

Closing and restarting the reader solves all problems, but this could be symptoms for a memory problem, as it happens with many documents (more than 15) open simultaneously and no other errors are shown.

**Comment by kjk** [comment]
This most likely means the system doesn't have enough memory to render the file. Nothing we can do about it.
