### ISSUE TITLE
Broke Page Auto-Sizing Caused by Pages with Large Images

### ISSUE THREAD

**Issue by justinkterry** [sumatrapdfreader/sumatrapdf#524]
In advance, I use an ultra high resolution monitor, and windows 10 with scaling. This issue may be related to this fact, but these monitors are becoming so extraordinarily popular that it still needs to be fixed independent of this. 

The issue is as follows:
When I open up certain documents, like one with a solid picture of the first page and text in the rest, the pages are not shown in the same size in sumatra-pdf, even though they are in other pdf readers. This is a major problem for easily readability for obvious reasons, and if you don't open to the first page of the file, the other pages are so much smaller than the cover that it makes it seem like they aren't there (and so for a long time I just thought sumatrapdf couldn't open some pdfs). To see how severe the scaling issue is, I've included a print screen of an example. It makes reading quite the problem. 
![sumatra pdf bug 1](https://cloud.githubusercontent.com/assets/19422700/15348806/7e2ec2b4-1c9b-11e6-9436-5bac43276fb8.png)

Here's the pdf used in that example, if it helps you: http://www.filedropper.com/mathematicalmethodsmarylboas

**Comment by GitHubRulesOK** [comment]
Unfortunately the link does not work
That is an extreme case of a pdf composer not thinking outside their own box, why oh why would anyone want a refectory table size cover?

Please try recent [pre-release](https://www.sumatrapdfreader.org/prerelease.html) (portable should do), which handles such edge cases better, however that abhorrent miss match of page sizes will  likely cause multiple glitches in continuous page fit / zoom control unless you  stick to single page mode.

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: I would suggest #152 has fixed this and close. Can always be reopened if necessary on production of new sample that's still displayed badly.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
As a result of other "glitchy" files I don't' think the issue is fully addressed (hence the request for samples) however since it can always be reopened on sample submission, I will close as potentially a duplicate and unable to proceed without a sample
