### ISSUE TITLE
Tab Scrolling Arrows Blocking Closing Tabs

### ISSUE THREAD

**Issue by inferno596** [sumatrapdfreader/sumatrapdf#525]
In advance, I use an ultra high resolution monitor, and windows 10 with scaling. This issue may be related to this fact, but these monitors are becoming so extraordinarily popular that it still needs to be fixed independent of this. 

I don't know if this constitutes a bug or a feature request, but either way the issue is a royal pain:
When I have a lot of tabs open in sumatrapdf, if I try to close the farthest right tab, the scrolling arrows come up above the x on the tab to close it, blocking me from being able to close the tab. This only happens when I have the window in "half-screen mode", but that's something you often want to do in windows 10 so that you can look at a document and do something at the same time. This is really annoying and seems like a really simple fix. To make sure the issue is clear, I've made a 20 second recording of what happens: https://www.youtube.com/watch?v=R4R9JHxh1pw

**Comment by inferno596** [comment]
I just managed to reproduce it in a large number of tabs with sumatrapdf not being in the half-screen mode as well. I didn't know I could do that.

**Comment by kjk** [comment]
Unfortunately that's the behavior of Windows' tab control that we use.

**Comment by JohnPlayerSpecial** [comment]
I just googled the same "bug" and came here.
Now I realize I can Ctrl + W to close that tab.

Thanks

**Comment by rohitsankhe** [comment]
ok...But still the scroll buttons can be moved left and leave some padding.
Most of the time last open file will be closed 1st... so it would be quite good to have it fixed.
