### ISSUE TITLE
Comment feature

### ISSUE THREAD

**Issue by muralivnv** [sumatrapdfreader/sumatrapdf#528]
Thank you! Developers for creating such a simplified PDF viewer. I finally ditched Adobe reader as soon as I found about Sumatra, and I really like the advanced settings and simplicity in design and faster loading times.
But there is one thing that leaves a hole, the ability to add "comments" in PDF. If this option is available then I'm pretty sure that Sumatra will be much more useful to college students( as we add stuff in PDF).

And I don't care about form filling cause we can do it with chrome built in PDF plugin..

**Comment by allshebe** [comment]
My thoughts exactly. I'm not a student, but have several documents I use for work that I "maintain" (for myself) by adding comments to record "changes" in and additions to the original information.  Sumatra is MUCH faster than either Adobe or Foxit readers and, other than lacking the ability to comment, meets my needs at work perfectly (fast, clean, minimalistic - I don't need most of the bloating bells and whistles Adobe and Foxit wish I would use)

**Comment by dirq** [comment]
The comment icon shows in v3.1.2 but there is no tooltip to show the actual text within the comment.

**Comment by kjk** [comment]
consolidating under #453
