### ISSUE TITLE
Sumatra (portable version 3.0) crash

### ISSUE THREAD

**Issue by JNicoll** [sumatrapdfreader/sumatrapdf#53]
(on 32-bit XP Home)

I had downloaded and then tried to open the PDF from the "Duo Footprint PDF" link, for a file named "duo_footprint_tech.pdf", on this webpage (it's architectural details about a home lift):
http://www.stiltz.co.uk/drawings.html

Sumatra opened and showed a big white empty page, then there was quite a long pause, then a message box saying it had crashed and suggesting I click 'Cancel' to help you (somehow).  I clicked that but nothing else happened (though XP's Windows Explorer crashed immediately afterwards necessitating a reboot).  

On reboot I found - by good luck - in %TEMP% (which I look in on each startup to clear out dross) a folder named "SumatraPDF-symbols".   Do you need want me to zip this up, upload it somewhere and send you the URL?

**Comment by kjk** [comment]
Not enough information to make progress.
