### ISSUE TITLE
Graphic looks damaged in the view

### ISSUE THREAD

**Issue by VNabholz** [sumatrapdfreader/sumatrapdf#532]
![acrobat-view](https://cloud.githubusercontent.com/assets/5499690/15533414/d75e2ee6-2264-11e6-8452-77e4bc826e1d.JPG)
![sumatra-view](https://cloud.githubusercontent.com/assets/5499690/15533426/e1c65368-2264-11e6-979c-ca94dfe0f9fb.JPG)

the pdf file viewed with the sumatra-pdf-reader looks like that there are less colors used. With the Acrobat DC Viewer it looks ok.

I'm not able to add the PDF-File from my desktop because of this message from yout issue-tracker...
![issue-error](https://cloud.githubusercontent.com/assets/5499690/15533675/fb733a5a-2265-11e6-8adc-5883ca076717.JPG)
![pdf-file](https://cloud.githubusercontent.com/assets/5499690/15533681/0485b0f0-2266-11e6-9810-28893ead2d46.JPG)

[Anzeige.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/281354/Anzeige.zip)

**Comment by GitHubRulesOK** [comment]
@kjk same as similar this is now resolved by recent builds I suggest closure

**Comment by kjk** [comment]
Possibly fixed.
