### ISSUE TITLE
GetPaperSourceByName fails when Printer Name is more than 32 charaters

### ISSUE THREAD

**Issue by mpserellis** [sumatrapdfreader/sumatrapdf#535]
I was having a problem with using the command line option -print-settings bin="..", the application simply crashed. I managed to trace the issue to the GetPaperSourceByName function in Print.cpp.

The issue turned out to be that my printer name is really long (more than 32 characters) and after passing the name to the function PrintFile, it populates LPDEVMODE and then passes that struct to ApplyPrintSettings, which in turn passes it to GetPaperSourceByName. GetPaperSourceByName then uses the dmDeviceName from the struct, but because that has been truncated the call to DeviceCapabilities fails.

I got around the issue by passing the printer name to each of the above functions and now it works as expected. I am not however a c++ programmer so you would probably come up with a better solution.

Thank you very much for your fantastic program, it has helped provide a neat solution to my project.

**Comment by GitHubRulesOK** [comment]
Cross linking by referencing #497 #533 #534

**Comment by kjk** [comment]
I believe that the code in question is already fixed i.e. we pass the original printer name to `ApplyPrintSettings` (not the truncated name).
