### ISSUE TITLE
Viewer for JPG files

### ISSUE THREAD

**Issue by isidroco** [sumatrapdfreader/sumatrapdf#537]
Open dialog doesn't allow to open JPG files inspite that they ARE opened if dragged to sumatra; even then, you can't go to next/prev image. Ironically if images folder is compressed to .cb7 it can be navigated...
A folder with images should be treated as any .CBz
This issue is very useful and probably almost trivial to implement.

**Comment by SumatraPeter** [comment]
I made a similar sort of request some time back: https://github.com/sumatrapdfreader/sumatrapdf/issues/352

**Comment by isidroco** [comment]
Yep, this could be a great viewer, it almost seem to be cripled on purpose.

**Comment by GitHubRulesOK** [comment]
@kjk 
The ability to read a Zip Folder with images is naturally the format of CBZ (CBR CBT) and thus an integral feature of SumatraPDF comic book support, Equally the need to render images embeded in other zipped containers such as epub, fb2  etc is essential as a Book Reader application.

Many users working with contructing / deconstructing those and other reader related formats such as pdfLaTeX especially like to preview (test) image rendering in the reader interface for many reasons most easily done whilst the images are not bound within such containers.

I do appreciate SumatraPDF is not an Image Viewer and tends to restrict itself to common formats that are of known structure and dont cause crashes. However apart from those with ODD proprietory JPG 2k compression (which can even be found in PDF files) I have not found SumatraPDF to have problems rendering such images or folders.

**Comment by GitHubRulesOK** [comment]
@kjk 
I note this ability to open files with .Jpg extension has recently been enabled as part of new file handling and includes the ability to open next/previous in folder
if that feature is now stable I suggest this issue can be closed.

On the second aspect of "opening a folder of supported files" via menu I note that was temporarily enabled in RaMicro but did not function well and was subsequently dropped?

**Comment by kjk** [comment]
It's now possible to open file images:
* by drag&dropping a file on sumatra window
* via File / Open file dialog
* by drag&dropping a folder with image files

Let me know if I missed something.
