### ISSUE TITLE
Use Bookmarks pane to display file names of images inside archives

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#543]
Inspired by https://github.com/sumatrapdfreader/sumatrapdf/issues/542#issuecomment-222378544

Depending on how PDFs are authored, the Bookmarks pane can display links to every page in them which is quite useful. In a similar fashion it would be nice if we could press F12 while viewing any supported image archive and have the Bookmarks pane show up with the complete file names of all the images listed.

Clicking on any of the file names would naturally jump to that image, and more importantly knowing the file name of any particular image would make it very easy to extract it from the archive. Even ancient Comic Book Readers such as CDisplay have the ability to display the file name for each image, so this would be a good way to add such functionality to Sumatra IMO.

**Comment by SumatraPeter** [comment]
@kjk: Given your latest updates related to Favorites management, TOC editing etc., I thought I'd resurrect this since it seems like the code may be related. Any chance of this making it to 3.2? 🙂

**Comment by GitHubRulesOK** [comment]
@SumatraPeter It can already be done using favorites all be it in a very unfriendly and unweildy fashion that requires editing (cut and paste) the settings file for bulk entries.
.vbkm **would be the current way to go** (however I personally would prefer if vbkm was simply a means to call .bkm files

**Comment by SumatraPeter** [comment]
Oh wow, finally! Thank you so much @kjk. This calls for some 🍾 methinks. 😄
