### ISSUE TITLE
Problem with print

### ISSUE THREAD

**Issue by playaer** [sumatrapdfreader/sumatrapdf#546]
When pdf document the height is less than the width, the program turns the paper through 90 degrees

**Comment by GitHubRulesOK** [comment]
@kjk 
This is down to a known behaviour in SumatraPDF code that deliberately adds an "optimized" rotation
It would be useful to add an option to "NOT" rotate in SumatraPDF-settings.txt I have separately in the past suggested other methods such as a 90 180 270 setting see https://github.com/sumatrapdfreader/sumatrapdf/issues/1246

**Comment by GitHubRulesOK** [comment]
closing as duplicated by https://github.com/sumatrapdfreader/sumatrapdf/issues/1246
