### ISSUE TITLE
A merged document has form field line breaks & format removed from original document in SumatraPDF

### ISSUE THREAD

**Issue by willpom** [sumatrapdfreader/sumatrapdf#551]
Firstly thanks again for a great, simple program.

Secondly I have submitted a bug with PDFsam as it was this software I merged the documents; the developer suggested I submit here too as it only displays incorrectly in SumatraPDF as far as we can tell; I can feed back to them if necessary. [https://github.com/torakiki/pdfsam/issues/168#issuecomment-224917748](url)

Thirdly I know I can't fill forms out in SumatraPDF but have had no problems viewing them as read only in the past.

The issue is after merging a document containing a form the output doesn't display correctly in SumatraPDF when the form fields are pre-filled. It does display correctly though in Adobe Reader (tested by PDFsam developer) and several online PDF tools. I have overcome this for this particular document by removing the fields of the pre-filled so I can view correctly. Please find attached screen shots of what the original file pre-PDFsam merge and still built with pre-filled form fields and what appears after a merge; also the files.

![original](https://cloud.githubusercontent.com/assets/19729665/15941585/c0bc9d88-2e78-11e6-9746-63b3c93f1d3a.png)
![merged](https://cloud.githubusercontent.com/assets/19729665/15941588/c75a1af8-2e78-11e6-8384-90f164930008.png)
[Original.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/307668/Original.pdf)
[Merged.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/307669/Merged.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk Sadly have to report here is an example where latest builds have had a negative effect
3.1.2 rendered cell contents badly but content was at least visible.
In latest builds the contents are invisible
Unsure if its entirely down to MuPDF but since their viewer can't render the fields guess this needs to be tagged MuPDF bug and a bug report raised for future forms support.

**Comment by GitHubRulesOK** [comment]
I have revisited this issue and replied in https://github.com/torakiki/pdfsam/issues/168#issuecomment-672373335 
Whilst MuPDF has issues displaying the file as produced by SAMpdf once it is saved by another application (e.g) Edge then it works as a valid file in both MuPDF & SumatraPDF
![image](https://user-images.githubusercontent.com/12754913/89960791-ddc1d080-dc37-11ea-96d4-740a55a27f61.png)
I am thus closing this issue as a "Rogue file" and here is a working copy
[Merged from edge2.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/5059993/Merged.from.edge2.pdf)
