### ISSUE TITLE
Find command reports "No matches were found"...

### ISSUE THREAD

**Issue by jacko9000** [sumatrapdfreader/sumatrapdf#554]
... when I try to find the word "freezer" (and other words) in the PDF file located at:

http://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0ahUKEwj8ge6NzKrNAhUdOsAKHSLQCrIQFgglMAE&url=http%3A%2F%2Fwww.indesit.co.uk%2Findesit%2F_pdf%2Fmanuals%2F19508409600_UK.pdf&usg=AFQjCNGA0oZpq_pLvTrL9v-BFBtw1PUyew

I have tried the latest prerelease (2015-05-30), but still get the same problem.

If you need more information, please let me know.

Regards,
Jacko

**Comment by GitHubRulesOK** [comment]
Jacko
Unfortunatly that PDF file which was initially processed as an image  has been poorly ocr'd and no longer includes the normal text "freezer" it was corupted and in the case I inspected recorded as "2 22 2 2  2" this is not a failing in SumatraPDF as the english words are simply garbled so it is a failing by Indesit to ensure their file is not faulty , please contact them for a replacement file.

**Comment by jacko9000** [comment]
OK.  Thanks for checking.

Regards,
Jacko
