### ISSUE TITLE
Parallel running of 32 and 64 bit version.

### ISSUE THREAD

**Issue by dgdegiorgi** [sumatrapdfreader/sumatrapdf#555]
As the 64 bit version does not allow to print on Dell 5100 I tried to install both versions as follows:

Installing first 64bit version and move installation folder from Program Files (X86) to Program Files.
Then installing 32bit version.
Pin both to task bar with different names adjusting target.
Now almost all works: looking documents with 64-bit version: if print needed close 64 bit version and open 32 bit version who opens all the documents open in the other version. After successful printing close the 32bit version and reopen the 64bit one.

There is just a small problem: after doing the above now pdf documents listed in File explorer have an anonymous icon instead of the PDF one. Is there a known method to restore the right icon?

Many thank for any hints

Daniel

**Comment by kjk** [comment]
I don't know what the problem might be.
