### ISSUE TITLE
Incorrect toolbar colours

### ISSUE THREAD

**Issue by Marmotian** [sumatrapdfreader/sumatrapdf#558]
SumatraPDF-prerelease-10529.exe
WinXP SP3
16-bit colour

The colours on the toolbar are not rendering properly. See attached composite screenshot.

![s_pdf_3 2 10529](https://cloud.githubusercontent.com/assets/20144736/16358772/7090d20e-3ad3-11e6-870a-1ed353981a31.png)

**Comment by kjk** [comment]
This has already been fixed in pre-release builds: http://www.sumatrapdfreader.org/prerelease.html

**Comment by Marmotian** [comment]
Sorry, but it is _not_ fixed in the image pointed to by the download page you referenced, which is the same image as I identified in my bug report. Please do not assume that your pre-release users are idiots and incapable of determining which image they are using.
