### ISSUE TITLE
Selected tab needs more contrast when SumatraPDF window has the focus

### ISSUE THREAD

**Issue by suckerstate** [sumatrapdfreader/sumatrapdf#559]
When another program's window has the focus, the SumatraPDF tab colors become lighter and the selected tab is very distinct from the other tabs. But when SumatraPDF has the focus, the tabs become darker and, on my monitors, it is difficult to discern which tab is selected. I wish there was some way to get more contrast in the tab colors when SumatraPDF has the focus.

I am using SumatraPDF reader for Windows, v3.1.1 64-bit, on a Windows 10 computer.

This is the only PDF reader I have found that will automatically restore the same tabs that I was using when I closed it. I am very happy that I found it.

**Comment by Poddster** [comment]
related: #343 

On default Windows 10 theme I'm having a hard time telling apart the tabs.

Configurable tab colour would be nice, if possible?

**Comment by paulri** [comment]
I would like to make the same feature request. The selected and background tabs are all blue, and the selected tab is only a bit lighter, making it hard to see which one is selected. It woudl be nice if we could choose a color scheme, or simply adjust the colors for either tab. If this isn't practicable, then at least have the default color scheme be more contrasting, so it is more clear which tab is selected.

**Comment by ofaurax** [comment]
I would say that this has to do with the values in https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/Tabs.cpp#L326

**Comment by paulri** [comment]
> I would say that this has to do with the values in https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/Tabs.cpp#L326

OK--so is this something that end users can insert into the Advanced Options text file, and tinker with?

**Comment by ofaurax** [comment]
No, it seems the value are hard-coded. I was pointing the code line to ease the search for someone knowing how to hack it.

**Comment by paulri** [comment]
OK thanks anyways.

**Comment by Cantello** [comment]
Same here, on win7 it is also hard to tell, which tab is currently selected.

**Comment by ofaurax** [comment]
Ok, some I found how to modify this in the code, so I'll propose a patch.
Which color do you want for the selected tab?
Do you want to keep the current color and make it even lighter?
Or do you want another color, like yellow?

**Comment by ofaurax** [comment]
Which one do you prefer?
![sumatra1](https://cloud.githubusercontent.com/assets/271723/22544686/26ab3e24-e936-11e6-9767-b7bb356e0c01.png)
![sumatra2](https://cloud.githubusercontent.com/assets/271723/22544685/26aa4ca8-e936-11e6-9b75-b04cf9f860fc.png)
![sumatra3](https://cloud.githubusercontent.com/assets/271723/22544687/26afc728-e936-11e6-8b4c-c564ce68b730.png)

**Comment by 7ko** [comment]
For me, the last one, darker tab is the active tab.

**Comment by paulri** [comment]
I agree, having the active tab in a darker blue seems to make the most sense, and the yellow kind of grabs my attention. 

I like what you've done here, especially with the third option.

**Comment by kjk** [comment]
My plan was to go with gray and use light gray for active and possibly simplify the drawing code by using a simpler shape (get rid of rounded corners).

The simplest way is to copy some other popular program (IE Edge, Chrome etc.).

Here's how chrome looks:

<img width="580" alt="screen shot 2017-02-02 at 11 45 58 am" src="https://cloud.githubusercontent.com/assets/7935/22565567/70656e98-e93d-11e6-9138-9c0fabde9495.png">

Here's  style of Visual Studio Code:
<img width="491" alt="screen shot 2017-02-02 at 11 46 13 am" src="https://cloud.githubusercontent.com/assets/7935/22565572/78622a1e-e93d-11e6-8dad-c9cf8e257582.png">

For simplicity, I would go with Visual Studio Code-like scheme.

**Comment by ofaurax** [comment]
It works for VS because they have a grey background, but sumatra has a white one:
![sumatra4](https://cloud.githubusercontent.com/assets/271723/22592418/015c0704-ea1a-11e6-8cb1-45eed9245af4.png)

In any case, I think grey is better than blue for this case.

**Comment by ofaurax** [comment]
So, do I propose the 3rd blue option, or another white/grey possibility?

**Comment by kjk** [comment]
The gray/white variant looks good. The outside could be changed from white to darker gray to provide contrast for gray of un-selected tab.

**Comment by ofaurax** [comment]
> The outside could be changed

I need your help to locate the code responsible for that.
This way, I could propose a pull request with the full change.

**Comment by kjk** [comment]
I'm afraid I don't know this off the top of my head. I didn't write the tab rendering code.

**Comment by ofaurax** [comment]
I spent some time trying to understand how this works... and failed. 😢

If someone can help to locate the code responsible for the color of the background behind the tabs, this would be appreciated. I'm currently stuck.

Perhaps this background is the default one, and code should be added to change it, but I don't use MS technologies usually so I can't help.

**Comment by SumatraPeter** [comment]
Some might prefer the active tab to be lighter, while others might prefer it to be darker (in any case [it's currently theme-dependent](https://github.com/sumatrapdfreader/sumatrapdf/issues/343#issuecomment-158627342) when ideally it shouldn't be).

Perhaps it's overkill but I'd love to see this added to Advanced Options. Something like the following perhaps (with appropriate default values of course):

TabColor [
	ActiveTabActiveWindow = #000000
	InactiveTabActiveWindow = #000000
	HoverTabActiveWindow = #000000
	ActiveTabInactiveWindow = #000000
	InactiveTabInactiveWindow = #000000
	HoverTabInactiveWindow = #000000
]

**Comment by leafcutterant** [comment]
I too am finding this very problematic. Please, amke the selected tab lighter, or as @SumatraPeter proposed, make it a used-definable value.

The closing "X" on each tab is also barely visible when you have a dark theme and the SumatraPDF window is active.

**Comment by jimporter** [comment]
One way to minimize the confusion of which tab is active is for the active tab to visually meld with the toolbar below it, as seen in the Chrome screenshot earlier in this issue. Most of the tabbed UIs that I can think of do this, and then the inactive tabs are usually a more neutral color (e.g. grey).
