### ISSUE TITLE
Crash reporter: also report dlls injected later on

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#56]
At some point I moved enumeration of dlls reported in crash reports from time of crash to startup. That caused the dlls that were injected into the process later on to not be reported.

We should re-do BuildModulesInfo() at the time of the crash, and show injected dlls as a separate section  (to make it easier to determine weird software that might be the cause of crashes).

**Comment by GitHubRulesOK** [comment]
@kjk I guess recent changes either close or superceed these comments ?

**Comment by kjk** [comment]
This still needs to be done.
