### ISSUE TITLE
Associate other extensions wit Sumatra

### ISSUE THREAD

**Issue by drmnk** [sumatrapdfreader/sumatrapdf#560]
Hello! Sumatra is brilliant software, and I always install it on every computer that I touch.

But when I install it, I want to make all file extensions associate with it - fb2, djvu, xps... Cause afterward user may met problem with opening of this files.

Can you add this options to installator and settings?

**Comment by GitHubRulesOK** [comment]
@kjk superseeded by master https://github.com/sumatrapdfreader/sumatrapdf/issues/1248

**Comment by kjk** [comment]
Consolidate under #1248
