### ISSUE TITLE
Add continuous scrolling in epub files

### ISSUE THREAD

**Issue by iceorfire95** [sumatrapdfreader/sumatrapdf#564]
Currently, Sumatra PDF only opens epub files in single/double page mode. I like to read ebooks on my PC in continuous scroll mode that is the default in Calibre ebook reader, but I would like to switch to Sumatra PDF because it is so resource-friendly. I didn't find any options to change this in the settings and I hope to find this feature in future updates. Also, support for changing background and font color for epub viewing would be nice.

**Comment by iceorfire95** [comment]
Hi! Any updates on this? Also, if there is a way to do this myself by changing the Sumatra PDF settings.txt, I'll try to do it myself. If someone knows, please let me know.

**Comment by zezyx** [comment]
still can't continuous scrolling in epub files.

**Comment by GitHubRulesOK** [comment]
Scrolling and searching e-pub needs them to be read using the standard User Interface.

For those that have not tested out which they prefer you need to change an advanced option in settings, look for this EbookUI section  
    EbookUI [
    	FontName = Georgia
        	FontSize = 12.5
        	TextColor = #5f4b32
        	BackgroundColor = #fbf0d9
        	UseFixedPageUI = false
     ]
change that last value from `= false` to `= true`

**Comment by zezyx** [comment]
Problem solved. Thank you!
