### ISSUE TITLE
Tables are not showing.

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#565]
.epub files are not showing any tables where they should have been.
This is the screenshot of sumatra with no table
![sum](https://cloud.githubusercontent.com/assets/8469046/16609151/48e8990c-4371-11e6-9253-32215f541bc9.png)

This is screenshot from another reader of same page.
![red](https://cloud.githubusercontent.com/assets/8469046/16609165/64a42ff8-4371-11e6-8866-cc70e86859a9.png)

**Comment by GitHubRulesOK** [comment]
A broader discussion on enhancing ePub support including tables such as these was covered in
**This epub 3 file will not load and display correctly**. #849 so I am closing this as a duplicate of those requests
