### ISSUE TITLE
epub - Spurious link after images

### ISSUE THREAD

**Issue by typhoon71** [sumatrapdfreader/sumatrapdf#567]
When using sumatrapdf to read an epub there's a link after every image.
Happens to both the images at the start and those in the middle of chapters.
Doesn't happen in calibre (my "reference" epub reader, too bad it's heavy).

I noticed it when opening epubs made with webtoepub (chrome/firefox addon that creates epubs), here's the link to the issue: https://github.com/dteviot/WebToEpub/issues/22#issuecomment-228708779.
You should find some relevant info on how an epub reader should behave in this circustance.

**Comment by AsukaLangleyfag** [comment]
Offtopic: as dirty hack, you can remove 
`let desc = doc.createElementNS("http://www.w3.org/2000/svg","desc");`
`svg.appendChild(desc);`
`desc.appendChild(document.createTextNode(origin));`
from Util.js
As you might see, it's description for picture. But I also vote for this feature.

**Comment by typhoon71** [comment]
Ehm, dirty hack @ "plugin\js\Util.js"... but where is that?

**Comment by AsukaLangleyfag** [comment]
In the source code of WebToEpub. Or \js\Util.js of the actual plugin.

**Comment by typhoon71** [comment]
I suppose an hack like this it won't work on signed  plugin... which soon will be the norn, read enforced.

**Comment by belldandu** [comment]
@AsukaLangleyfag 

Did you read https://github.com/dteviot/WebToEpub/issues/22#issuecomment-228696707

> I'm going to assume however that said readers are attempting to parse random url's as ```<a>``` tags from what you are saying (which is NOT standard behavior and is a bug in these readers if they are).
> 
> The contents of the desc tag are also not supposed to be shown to the user via the reader unless the image has not been rendered. See https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc
> 
> > When the current SVG document fragment is rendered as SVG on visual media, desc elements are not rendered as part of the graphics.
> 
> This means that if an image exists within the svg and has been loaded then the desc tag is not rendered. 
> 
> So i do recommend reporting these as bugs to the epub readers developers. Because we do not create svg elements unless there is an image.

**Comment by AsukaLangleyfag** [comment]
Yes, this is wrong and shitty. And yes, I read it. I agree this is a bug in Sumatra PDF.

**Comment by belldandu** [comment]
Feature for disabling desc tag in svg element added. Issue has been closed on our end and labeled as "bug in reader" due to sumatrapdfs inability to meet the spec.

Said issue will not be reopened and i hope that someone gets around to fixing said bug because if it hadn't been for the fact that the users on bakabt asked about an option to disable the links i would have just slapped "bug in reader" and "wontfix" on the issue and left it there.

**Comment by GitHubRulesOK** [comment]
@typhoon71 @belldandu 
Epub handling is currently under review
Please supply a sample or two where WebToEpub.epub files are not handled well

**Comment by GitHubRulesOK** [comment]
closing as epub/svg engines have changed and samples are not available to show any continuing behaviour issue.
