### ISSUE TITLE
Purple toolbar icons on Win10

### ISSUE THREAD

**Issue by vanxining** [sumatrapdfreader/sumatrapdf#569]
The icons of the main toolbar are not transparent but with purple backgrounds.
I built the program from latest Git sources using VS2015 with Update 2 Community Edition.

My OS version:
>Win10 Pro 64bit 1511 10586.420

Source:
>commit 6ef0624c4ce6168d463fbb9614f92147d62b66af

Thanks!

![pdf](https://cloud.githubusercontent.com/assets/536291/16689772/2962e2ee-4557-11e6-99df-93f7d31f88d2.png)

**Comment by kjk** [comment]
Hmm, I've tested on my win 10 latest insider builds and it works. It could be that it's a bug present in earlier win 10 builds and fixed in latest insider builds.

Since you can compile the sources, could you change https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/Toolbar.cpp#L596
to:
```
bool useDibSection = false;
```
and see if it fixes the problem?

**Comment by vanxining** [comment]
If I change that line to
`bool useDibSection = false;`
the problem is gone.
This bug is not present in 3.1.1 downloaded from the official site.

**Comment by kjk** [comment]
Thanks for the information. Should be fixed in pre-release 10534 or later (http://www.sumatrapdfreader.org/prerelease.html)

**Comment by wigster** [comment]
Hi,

I have just updated my Win 10 to the new public Anniversary Update (10.14393.10) and this sort of toolbar-rendering problem has appeared (it was ok on the previous public version). I am running Sumatra 3.1.1 64-bit and I have 150% DPI scaling turned on as well as the dark mode, if that makes a difference.

![capture](https://cloud.githubusercontent.com/assets/10956987/17431962/d6d6d8ee-5afc-11e6-81a2-89c22b8bb2b2.JPG)

**Comment by kjk** [comment]
As the comment above says, this should be fixed in latest pre-release: http://www.sumatrapdfreader.org/prerelease.html

**Comment by kkkwong** [comment]
I also use Windows 10. I use the latest pre-release portable version and the toolbar looks okay when I launch the application. However, strange thing happens. Let me explain. I use two instances of Sumatrapdf, let's call them sumatrapdf1.exe and sumatrapdf2.exe (put in different folders). I open sumatrapdf1 to read a pdf, and set sumatrapdf2 as an external viewer in the advanced option. If I now try to open this pdf by sumatrapdf2 as an external viewer (through sumatrapdf1), then the toolbar of sumatrapdf2 becomes purple. (It looks good if I just launch sumatrapdf2.exe alone.)
