### ISSUE TITLE
Search over line breaks and syllabification

### ISSUE THREAD

**Issue by Pertekm** [sumatrapdfreader/sumatrapdf#571]
It would be great, if the search function supports syllabification (hyphenation).
So if searching for "sumatra" and the word is broken in the text in "sum-atra" over line breaks,
then it should find that position too.

See also http://forums.fofou.org/sumatrapdf/topic?id=3185022

Thanks for the nice sumatrapdf and greets from germany

**Comment by GitHubRulesOK** [comment]
Closing as duplicated by fuller description in Find words with soft hyphens #1189
