### ISSUE TITLE
unable to open a PDF file error message - unsupported features (XFA) 

### ISSUE THREAD

**Issue by JupitermarketingLTD** [sumatrapdfreader/sumatrapdf#572]
Opening a PDF file we are getting the above error.
This is happening more & more frequently.
How do we get around this?

**Comment by SumatraPeter** [comment]
[PDF (XFA) Forms](http://blogs.adobe.com/an_tai/archives/172) aren't supported by Sumatra and according to the devs they are unlikely to work on this feature.

**Comment by GitHubRulesOK** [comment]
@kjk I think this is another under the heading MuPDF "wontfix" e.g. dup of In Windows 10 64b I can't use SumatraPdf #588
