### ISSUE TITLE
can sumatra display the page by flipping horizontal?

### ISSUE THREAD

**Issue by retsyo** [sumatrapdfreader/sumatrapdf#574]
This function is useful while reading origami diagram, for example, on http://att.newsmth.net/att.php?p.99.205263.661.png, step 43 actually repeats 32-42( which is done on the right part) on the left part. It is helpful if the page can be seen by flipping horizontal

**Comment by retsyo** [comment]
anyone?

**Comment by kjk** [comment]
No, we don't have such functionality.
