### ISSUE TITLE
Epub/Mobi-Line returns incorrectly

### ISSUE THREAD

**Issue by tcdzyq** [sumatrapdfreader/sumatrapdf#575]
When reading epub/mobi ebooks in chinese, lines return at wrong place if the character is   ',',  '、 ', or '《', and so on, as in the  attached picture, thank you!
![wrong_line_feed_of_epub](https://cloud.githubusercontent.com/assets/20555689/17102572/da0626b2-52ac-11e6-81bd-0d853bcb2552.png)

**Comment by startewho** [comment]
I have the same problem. And when I use the `mupdf`, it shows the content correctly. Is there a possible the `mupdf` update its lib?

**Comment by SumatraPeter** [comment]
Just wanted to comment that "Epub/Mobi-Line breaks at wrong place" communicates the problem much better to me at least than "Epub/Mobi-Line returns incorrectly".

**Comment by GitHubRulesOK** [comment]
Closing as duplicated by #1200 which has link to a working fork.
