### ISSUE TITLE
NamedDests and page=XX don't open  Using plugin in Opera12

### ISSUE THREAD

**Issue by sbridger** [sumatrapdfreader/sumatrapdf#578]
Won't open to target
file:///C:/somepdf.pdf#nameddest=page.4
file:///C:/somepdf.pdf#page.4
file:///C:/somepdf.pdf#page=4
Not a very high priority since its obsolescent...
SumatraPDF Browser Plugin - 2.5.0.8625
C:\Program Files\SumatraPDF\npPdfViewer.dll

**Comment by kjk** [comment]
We don't plan any more work on the plugin.
