### ISSUE TITLE
Message that file has been updated.

### ISSUE THREAD

**Issue by RLS-MSC** [sumatrapdfreader/sumatrapdf#580]
I am not sure if it is possible since this reader does not lock the file for editing but it would be nice if the file was updated by another user on the network while being open in this reader that a message would pop up on the open file stating that the file has been updated so the most current file is always used.

**Comment by SumatraPeter** [comment]
You might want to read @kjk's comment here: https://github.com/sumatrapdfreader/sumatrapdf/issues/596#issuecomment-241282556

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Perhaps consolidate with #596 as mentioned above?

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
I think there is a subtle difference. in 596 a condition is triggered "Changes detected" that is not respected whereas this request is to intermitently go look see if there is a problem i.e potentially requires a different solution

**Comment by SumatraPeter** [comment]
@GitHubRulesOK: Ok, maybe not consolidate, but still very much a candidate for closure. Read carefully kjk's comment I linked to above. He says clearly that what _this_ user is requesting is not possible because Sumatra cannot detect changes made to PDFs opened from network drives.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
I grant you that since we have no reference as to the type of network system involved in this historic problem (seen since the days of dos/novell etc. onwards) it cannot progress unless the key issues of checking/notification are covered by other external solutions or means.
