### ISSUE TITLE
Purple toolbar icons in Win10 Anniversary Update

### ISSUE THREAD

**Issue by wigster** [sumatrapdfreader/sumatrapdf#581]
This seems to be issue #569 which was closed, so I am creating a new one.

After Win10 public anniversary update (10.14393.10) SumatraPDF icons have purple backgrounds (v3.1.1 64-bit). It was ok before the update.

I have 150% DPI scaling and the dark mode switched on, if that makes a difference.

Attaching a screenshot of what is happening.
![capture](https://cloud.githubusercontent.com/assets/10956987/17432076/8d5c0756-5afd-11e6-93b2-10b6ec15c7a5.JPG)

**Comment by kjk** [comment]
This should be fixed in latest pre-release: http://www.sumatrapdfreader.org/prerelease.html

In the future, please don't add duplicate comments.

**Comment by wigster** [comment]
Apologies, I understood that this was fixed in a new pre-release version of Windows not Sumatra.

Works great again. Thanks!
