### ISSUE TITLE
Problem with Print ==> Preferences

### ISSUE THREAD

**Issue by kenmk** [sumatrapdfreader/sumatrapdf#583]
Plain printing works fine.  Problem is that whenever I try to check the Print ==> Preferences the application fails (gracefully, saying that what just happened should not have done!!).  Happens with any file, so it's not file specific.

I am running Windows 10 Pro and trying to talk to a Konica Minolta 2450 colour laser printer.

All other applications I have can go through to the printer preferences without a problem.

**Comment by GitHubRulesOK** [comment]
Most likely a buggy print driver in 2016 ?
Old account so don't know if you receive this but can you test and report findings with the latest portable pre-release from https://www.sumatrapdfreader.org/prerelease.html ?

**Comment by kjk** [comment]
Can't do anything without more information.

If still happens, provide crash information which is now easy to obtain.
