### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by mmutoo** [sumatrapdfreader/sumatrapdf#585]
Dear Sir/Madam,
I would like to suggest a feature. It would be great if Sumatra could do autocrop on pages of a document, eliminating the empty margins and leaving the displayed document more neat and clean for reading.

Regards

**Comment by doncherry** [comment]
There is an excellent program exactly for this task: [Briss](http://briss.sourceforge.net/). I don’t think there’s any need to reinvent the wheel or to burden SumatraPDF with this feature.

**Comment by kjk** [comment]
Closing as dup #767
