### ISSUE TITLE
In Windows 10 64b  I can't use SumatraPdf

### ISSUE THREAD

**Issue by Hodaki89** [sumatrapdfreader/sumatrapdf#588]
In Windows 10 64b 
I can't use SumatraPdf, getting:
This document uses unsuported features (XFA) and might not render properly

Please wait...
If this message is not eventually replaced by the proper contents of the document, your PDF
viewer may not be able to display this type of document.
You can upgrade to the latest version of Adobe Reader for Windows®, Mac, or Linux® by
visiting http://www.adobe.com/go/reader_download.
For more assistance with Adobe Reader visit http://www.adobe.com/go/acrreader.
Windows is either a registered trademark or a trademark of Microsoft Corporation in the United States and/or other countries. Mac is a trademark.

**Comment by kjk** [comment]
Yes, XFA is not something sumatra supports.

**Comment by Hodaki89** [comment]
Thanks, yet it is confusing as it is not coming as SummatraPdf's message
but Adobe's and is offering an upgrade of Adobe

Regards

Andrzej
