### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by liuhong12th** [sumatrapdfreader/sumatrapdf#592]
The "save as" command's keyboard shortcut is actually "Ctrl + S", while it's showed as "Ctrl + A" in the main menu.

**Comment by SumatraPeter** [comment]
3.1.2 shows Ctrl+S here so probably this issue can be closed.

**Comment by kjk** [comment]
It looks like incorrect cn and tw translation. You can fix translations at http://www.apptranslator.org/app/SumatraPDF

**Comment by kjk** [comment]
I fixed the translation.
