### ISSUE TITLE
support e-ink screens (option to disable smooth text)

### ISSUE THREAD

**Issue by Lutwick** [sumatrapdfreader/sumatrapdf#599]
Hello,

this is a feature request:

I am currently experimenting with "the world's first e-ink monitor" 
(https://www.indiegogo.com/projects/paperlike-world-s-first-e-ink-monitor-13-3).
It operates best in pure black and white mode. Thus, for best quality
you need to disable smooth font rendering, which looks good on regular
displays but not on the b/w e-ink screen.

The Acrobat Reader has this option under Preferences->Page
Display->Rendering->Smooth Text. But as Acrobat locks opened files, I
cannot use it for TeX.

The PDF-XChange Viewer by Tracker Software also has this option under
Preferences->Rendering->Smoothing. While this viewer can open files
without locking, it is still somewhat useless because with each
automatic reload the scroll position is reset to the top.

Another great feature to support e-ink screens would also be the option
to override all font colors with black and all background colors with
white. Both Acrobat and PDF-XChange offer this under
Preferences->Accessibility.

Thanks!

**Comment by kjk** [comment]
Changing font rendering is way too much work for the benefit of esoteric hardware. I don't have bandwidth to do it nor access to hardware to test changes.

**Comment by Lutwick** [comment]
Fair enough!

I thought it might only be a simple switch somewhere in the code, as smoothening the fonts is probably much more computational effort than ommiting it alltogether.

Thanks anyway.

**Comment by AlisterH** [comment]
A lot of people find antialiased text very hard on their eyes, so this isn't just valuable for esoteric hardware.
Both mupdf and mupdf-gl currently allow antialiasing to be toggled on and off by pressing A.  I'm not sure if this was the case back in 2016 - any chance we'll ever see this in Sumatrapdf?
Thanks.

**Comment by kjk** [comment]
I just tried `A` in mupdf-gl and without anti-aliasing it looks terrible.

**Comment by AlisterH** [comment]
It'll depend on the font - a lot of modern fonts are rubbish.

**Comment by AlisterH** [comment]
For example this pdf uses a font that isn't too bad: ![image](https://github.com/user-attachments/assets/ed59a3fc-14b3-4257-a16e-96dc054abec4)

**Comment by GitHubRulesOK** [comment]
@AlisterH 
The question was alter fonts to suit monochrome screens by adjust the alias value which is not needed for most windows devices look at the RGB default there is no problem reading the different embedded and non imbedded vector font types 
![image](https://github.com/user-attachments/assets/9e0683d5-e353-4d68-b8d5-961dc9240bab)
Then add the TOGGLE A ability from MuPDF

Here is that remove Alias difference .

SumatraPDF ON, MuPDF ON, MuPDF OFF on a normal screen. (Clearly With Anti-Aliasing OFF text edge is aliased thus worse) the result of remove AA is that it will look more like e-ink hard edged mono.

![image](https://github.com/user-attachments/assets/dc490034-ea7f-4189-ab5f-2f9b2edaa72d)

**Comment by carl0988** [comment]
Indeed, Koodo-Reader doesn't have this problem at all. But it's too large. This issue hasn't been resolved in 10 years.

https://web.koodoreader.com/

**Comment by AlisterH** [comment]
Thanks for the hint about koodoreader, carl!

@GitHubRulesOK 

> (The common complaint is text edges are too soft, but the aim is to NOT have harsh stairs)

I would say "blurry", rather than "soft", but whatever.

> Clearly With Anti-Aliasing OFF text edge is aliased thus worse

The text in your second screenshot is actually large enough that it doesn't matter so much.  It is critical for smaller font sizes where the strokes are only one or two pixels wide - like all the gui fonts typically are on a desktop PC.
Some people who can't cope with antialiasing at these small sizes actually do enable it for larger sizes (when they're using a system that enables it e.g. Linux fontconfig rules).
