### ISSUE TITLE
selectable print scale

### ISSUE THREAD

**Issue by tomasherrmann** [sumatrapdfreader/sumatrapdf#60]
the problem:
I receive multi-page faxes a pdfs - for example 21cm width and lengh of 84cm. 
So sumatra prints a one page - scaled document. the text width meassures 6cm .

Is there a work around?
best would be for me: a "print what you see" - in other words: coulnd the print scale factor set to the view scaling?
thank you
Tomas

**Comment by zeniko** [comment]
The Print dialog offers to print the current selection if there is any. You can create a rectangular selection by pressing the Ctrl key while you start selecting.

**Comment by tomasherrmann** [comment]
wow thank you very much!

The Print dialog offers to print the current selection if there is any. You can create a rectangular selection by pressing the Ctrl key while you start selecting.

**Comment by GitHubRulesOK** [comment]
@kjk this appears to have been addressed (closed) by zeniko's comment to use print selection
