### ISSUE TITLE
Feature Request: command line option for document rotation while printing

### ISSUE THREAD

**Issue by VoidVolker** [sumatrapdfreader/sumatrapdf#602]
Command line option for document rotation while printing. Something like that:

```
-print-rotate-90 
-print-rotate90
-print-rotate-180
```

Or:

```
-print-rotate-left
-print-rotate-right
-print-rotate-down
```

**Comment by kjk** [comment]
Sumatra isn't great at printing so I don't want to add features that encourage people to print even more.

**Comment by VoidVolker** [comment]
Why? It is better for silent printing, then Acrobat Reader - because Acrobat Reader can't print silent and don't have option for closing after printing. Also, I din't find any other good and small free PDF viewer for printing.

**Comment by shaxish** [comment]
I totally agree to VoidVolker! We use Sumatra for Silent Printing and it works great. At the moment we rotate the PDF files with pdfjs. But it would be great to completly remove pdfjs (we can do that when sumatra has a rotate in command line).

**Comment by liudonghua123** [comment]
I would like this features too, I have a lot of landscape orientation pdf which I need to roate 90 to view it.
