### ISSUE TITLE
Please add  keyboard shoutcout to attach file to email

### ISSUE THREAD

**Issue by pimarplastics** [sumatrapdfreader/sumatrapdf#607]
Dear, It will be extreamly handy to add keyboard shourcut to attach files to email messages. 

Thanks in advance,
-Kamil

**Comment by GitHubRulesOK** [comment]
@kjk 
I suggest this is not an Issue since:=-
As you know the default english shortcut is <kbd>ALT</kbd> + <kbd>F</kbd><kbd>E</kbd>

**Comment by kjk** [comment]
Yes, this already is a shortcut.
