### ISSUE TITLE
fit to window button (no blank space right and left)

### ISSUE THREAD

**Issue by sevdimali** [sumatrapdfreader/sumatrapdf#608]
Can you add button for **fit pdf to window width**.

Now there is **fit a single page** button but when you click it there are blank space right and left, my suggestion is clear those blank space and user can see only pdf content (word, images etc.)

For now it is possible with **zoom in** button. But it is not more useful because user have to press 5 or 6 times to get this view. We can solve it with a single button.

For example when you view pdf with **microsoft edge** it has this button and it is very useful.

**Comment by pdgessler** [comment]
Do you mean the "Fit Width" button which is located next to the "Fit a Single Page" button?

![SumatraPDF Toolbar Screenshot](http://i.stack.imgur.com/wiauC.png)

This zoom mode is also accessible through the menus at "Zoom -> Fit Width" or by using the keyboard shortcut "Ctrl+2".

**Comment by sevdimali** [comment]
O confused :)
it works for some pdf...
For some files when you open a pdf and before **ctrl+2** when you click **Fit Width** or **Fit a Single Page** buttons it fits but as I expalined there are blank space but after ctrl+2  those buttons work.


But **ctrl+2** works all cases.

I will use **ctrl+2**.
