### ISSUE TITLE
Scrolling with Trackpad

### ISSUE THREAD

**Issue by wigster314** [sumatrapdfreader/sumatrapdf#61]
Running SPDF 3.1.10094z on Win 8.1 x64 Pro/Surface Pro 3.

When I try to scroll using the two-finger swipe on the touchpad of the TypeCover keyboard, SPDF registers the scroll request (the scroll bar on the right of the window moves appropriately) but the view of the document does not change.

At the same time, using the scroll wheel of the mouse and the touch screen scrolls the document perfectly ok.

**Comment by ldobl** [comment]
I have the exact same problem on the Surface Pro 3 with Windows 8.1.

**Comment by fhurtubise** [comment]
I have the same problem, running on a Dell inspiron 13" 7000 series.

**Comment by beta-test** [comment]
Same Problem here, running Windows 8.1 Pro and SumatraPDF 3 on a Acer-Notebook with a Synaptics Touchpad.

**Comment by Teroshan** [comment]
Same problem on a Aspire V3-371 laptop, Windows 8.1.

**Comment by kaysin** [comment]
Same problem on Dell XPS13-9343 laptop .. Windows 8.1 pro  and SumatraPDF 3 & 2.5.1

**Comment by jonathanmajh** [comment]
same on v3.0 stable and v3.1.10135 beta releases

Windows 8.1

Dell Inspiron 15 5548

**Comment by wigster** [comment]
Thanks. Indeed it seems to work well on the Surface Pro 3 now.

**Comment by Zequez** [comment]
For anyone finding this through Google, [the compiled pre-releases are here](http://www.sumatrapdfreader.org/prerelease.html). The download section in the website only seems to go up to 3.0.0, which was released a long time ago.
