### ISSUE TITLE
Advanced option to make "RememberStatePerDocument" a location-dependent setting

### ISSUE THREAD

**Issue by gjcdeluxe** [sumatrapdfreader/sumatrapdf#611]
Hi,
For me SumatraPDF fulfils two roles - as an ereader for ebooks and long documents where I need to know what page I was last up to, and also as a quick viewer for more ephemeral things, like a credit card statement or whatever.

For the former use, it is obviously necessary for the document's previous state to be recalled, but for the latter this is unhelpful - I often find myself loading up a document and staring at a blank page wondering why it hasn't loaded, only to realise it's because it's displaying blank space at the end of the last page of a bill, because I happen to have viewed it before.

So that both scenarios can be accommodated, would it be possible to add an advanced option that would allow me to only recall the document state for files stored within a particular folder and its subfolders? For example:
RememberStatePerDocumentOnlyIn = C:\User\Documents\Ebooks

Or if this would be easier to implement, perhaps only recall the document state for long documents? For example:
RememberStatePerDocumentWhenPagesExceed = 5

Cheers!
gjc

**Comment by kjk** [comment]
Such a setting wouldn't be useful to many people and adding settings isn't free it terms of programming time and increasing the size of the documentation.

**Comment by gjcdeluxe** [comment]
Understood, worth asking. Thanks anyway.

**Comment by GitHubRulesOK** [comment]
@gjcdeluxe 
There is an undocumented startup feature `-appdata` that as a by-product allows for this requirement.
You can have separate startup profiles for different uses, by keeping two (or more) settings.txt files in separate sub folders.
The limitations are it does not stop you from opening a PDF file in the session that remembers ebook file history, nor stop you from opening an ebook in a PDF session that forgets history.
It is also limited to allowing only **one or the other** when you start SumatraPDF

Thus an alternative method may be better, Lets leave the overall Settings > Options as NOT Remember Open Files but when an e-book is to be read you need "file open" in a session with history

One way to achieve this is to pass the current file to another SumatraPDF.exe with history enabled which could be done like this using ExternalViewer

![image](https://user-images.githubusercontent.com/12754913/73660085-6d863100-468f-11ea-99a3-633b7d4b9e93.png)

So going full circle it simply makes sense to use the system installed version **without** "Remember open files" and most simply have a second shortcut for drag and drop epubs etc that runs a portable copy with Remember open files activated.
