### ISSUE TITLE
Is it possible to open a url page:use javascript to control sumatrapdf

### ISSUE THREAD

**Issue by wideweide** [sumatrapdfreader/sumatrapdf#613]
Define a URL Protocol like this:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\spdf]
@="SumatraPDF"
"URL Protocol"="C:\\Program Files (x86)\\SumatraPDF.exe"

[HKEY_CLASSES_ROOT\spdf\DefaultIcon]
@="C:\\Program Files (x86)\\SumatraPDF.exe,1"

[HKEY_CLASSES_ROOT\spdf\shell]

[HKEY_CLASSES_ROOT\spdf\shell\open]

[HKEY_CLASSES_ROOT\spdf\shell\open\command]
@="C:\\Program Files (x86)\\SumatraPDF.exe \"%1\""
```
spdf://http://ip/some.pdf    = SumatraPDF.exe "http://ip/some.pdf"  
spdf://http://ip/some.pdf -url http://ip/control.jsp    = left show control.jsp,right show some.pdf  
in control.jsp:
provider some menu for business.... this is not important...
js code like this:
var sPDF = window.external;
sPDF.restrict=true;
///batch print...
sPDf.open('1.pdf')
sPDf.print();
sPDf.open('2.pdf')
sPDf.print();
.... some other functions

**Comment by kjk** [comment]
it's not possible.

**Comment by wideweide** [comment]
It is possible.

I know one product can do this: iStylePDF  http://www.istylepdf.com/dev/help/index.html

If you are interesting ,I can provider a demo.

but I am not sure,how to do this with sumatrapdf...

**Comment by kjk** [comment]
Like you said, it's a different program. It's not possible in Sumatra.

**Comment by wideweide** [comment]
ok,thanks.

another question : open pdf with a url is not support too?
sumatrapdf.exe http://192.168.7.30:8080/test.pdf

**Comment by kjk** [comment]
Also not supported.

**Comment by wideweide** [comment]
why not ?
It is very useful
