### ISSUE TITLE
text copied from sumatrapdf has extra line break

### ISSUE THREAD

**Issue by a1307743680** [sumatrapdfreader/sumatrapdf#614]
When copy paragraph with more than one line from sumatrapdf , an extra line break (in windows CR+LF) will be added at the end of each line. This issue doesn't appear in adobe reader. Even the pdf reader in win10 Edge doesn't have this issue.

**Comment by kjk** [comment]
You would have to provide a PDF that shows the problem and describe where exactly it happens.

When copying text out of PDF, determining the location of newlines and a few other things is inevitably a heuristic. We have tweaked those heuristics in the past and might tweak it more, but we need concrete examples of files where Sumatra gets it wrong.

**Comment by a1307743680** [comment]
Sorry for I can't describe in which situation or document this will happen. But I will show you my experience. 
Normally there is only one line break in one paragraph at the end of this paragraph. However, when copy from sumatrapdf, each end of line in this paragraph will have a line break.
For example: 
copy from adobe:
_Our country faces a vicious cycle of poverty, criminality, and incarceration that traps too many Americans and weakens too many communities. There are 2.2 million people behind bars in America today, compared to 500,000 just 30 years ago. The United States has less than five percent of the world’s population but over 25 percent of the world’s prisoners. Every year, we spend $80 billion to keep people locked up._
and copy from sumatrapdf
_Our country faces a vicious cycle of poverty, criminality, and incarceration that traps too many
Americans and weakens too many communities. There are 2.2 million people behind bars in
America today, compared to 500,000 just 30 years ago. The United States has less than five
percent of the world’s population but over 25 percent of the world’s prisoners. Every year, we
spend $80 billion to keep people locked up._
Due to the style it's hard to show difference in web page.
Here is this pdf document.
[IncomeN.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/471140/IncomeN.pdf)

**Comment by a1307743680** [comment]
It doesn't happen everywhere. In my test, pdf documents converted from microsoft word don't have this issue. In those documents, adobe and sumatrapdf perform similarly, which is both of them have extra line break. The document is 
[Income.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/471150/Income.pdf).
And the former document(IncomeN.pdf) is converted from it by a OCR software named ABBYYFineReaderPortable.
Though it might happen in several situation, I hope you can solve it.

**Comment by a1307743680** [comment]
I have provided the pdf show this problem in comment

2016-09-13 14:46 GMT+08:00 Krzysztof Kowalczyk <notifications@github.com>:

**Comment by kjk** [comment]
Sumatra behaves the same as Google Chrome (i.e. FoxIt).
