### ISSUE TITLE
Bookmarks do not collapse when set to collapse in the PDF

### ISSUE THREAD

**Issue by HdeJong0** [sumatrapdfreader/sumatrapdf#617]
When creating a PDF, you can specify for individual bookmarks that they should be collapsed or expanded. For example, when I use XSL-FO to create a PDF, this command creates a collapsed bookmark: 
fo:bookmark internal-destination="ID_000111" starting-state="hide"
(i.e. the children of this bookmark are hidden). 

This does not work in SumatraPDF 3.1.2. When I open a file, all bookmarks are expanded, regardless of their setting. 
[X1000 User Guide.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/474827/X1000.User.Guide.pdf)

I have attached a PDF that is set up to collapse all bookmarks. When I view this in Adobe Acrobat X, bookmarks are collapsed. In SumatraPDF, they are expanded.

**Comment by GitHubRulesOK** [comment]
@HdeJong0 when you start expanding a file SumatraPDF can keep a history of your last bookmarks position and setting

@kjk This worked as expected in 3.1.2
![image](https://user-images.githubusercontent.com/12754913/70461507-ab604200-1ab0-11ea-9cf9-f318ee0cb979.png)

**Comment by GitHubRulesOK** [comment]
@kjk recommend this be closed as it is still working perfectly in current release and pre-release versions

Document Outline is NOT shown by default and when it is set to show it CAN remember previous status

**Comment by kjk** [comment]
Yeah, in my testing things work as expected all around.

**Comment by HdeJong0** [comment]
> when you start expanding a file SumatraPDF can keep a history of your last bookmarks position and setting

Yes, but that's not what the bug is about. When I **create** a PDF, I can specify bookmarks to be expanded or collapsed. This information is stored in the PDF, and it controls the bookmark state when the file is opened for the first time. 
Acrobat reads this information, SumatraPDF doesn't.

**Comment by kjk** [comment]
It's fixed in latest code: https://www.sumatrapdfreader.org/prerelease.html
