### ISSUE TITLE
External Links Should Open

### ISSUE THREAD

**Issue by mplaut** [sumatrapdfreader/sumatrapdf#618]
I would like external links, particularly links to files on my computer, to open when clicked on. I would want them to open in a new tab but naturally this will depend on the settings of the program (ie if it is set to use tabs).

For security reasons, maybe it is better for this to be an option.

**Comment by kjk** [comment]
This is already possible but we restrict the type of files we open. See SafeFileTypes in https://github.com/sumatrapdfreader/sumatrapdf/blob/master/docs/sumatrapdfrestrict.ini and you can already disable it by setting it to *

**Comment by abma** [comment]
oh, thanks a lot for this info!

**Comment by mplaut** [comment]
Thank you for the answer. But I want especially PDF files that are linked to in a master PDF file to open in another tab of Sumatra. I have a master index file that links to hundreds of PDF files with links of the form:
file:///C:/Archive/directory1/directory2/file.pdf
I would like these to open in another tab of Sumatra when clicked on. 
When I installed a new version at first it was working as I wanted, but now it just selects (highlights) the links when I click on them.
