### ISSUE TITLE
PDF bookmark links not working

### ISSUE THREAD

**Issue by Sasstraliss** [sumatrapdfreader/sumatrapdf#619]
I have lots of PDFs, and most of the bookmark links work fine.

Some of my PDFs have bookmarks, but the links (to the particular pages) don't work at all when clicked. They work in Adobe Reader DC though, going to the appropriate section, so it must just be Sumatra.

Here's one of the culprit PDFs (yes I own it in hardcopy too, calm down :P)... https://1drv.ms/b/s!AmLJxqfRJ4Hemkk9QlNIzplvHjs8

**Comment by jiulun** [comment]
Indeed, this is a non-conforming PDF file.
If you open this file in a text editor, and search "Auto/Page". You will see find page object has /Auto/Page and pages object has /Auto/Pages. The requirement is a page or pages object shall have Type as Page or Pages respectively.
Solution 1: Search and replace "Auto/Page" as "Type/Page". This replace "Auto/Page" to "Type/Page" and "Auto/Pages" to "Type/Pages". 

Solution 2: In source code function pdf_lookup_page_number() in pdf-page.c. Relax the page type check. 
E.g.
Replace
`    if (strcmp(pdf_to_name(pdf_dict_gets(node, "Type")), "Page") != 0)
        fz_throw(ctx, FZ_ERROR_GENERIC, "invalid page object");
`
with a warning
`   if (strcmp(pdf_to_name(pdf_dict_gets(node, "Type")), "Page") != 0)
    {
        if (pdf_dict_gets(node, "Kids") != NULL)
            fz_throw(ctx, FZ_ERROR_GENERIC, "invalid page object");
        else
            fz_warn(ctx, "invalid page object");
    }
`
An addtional check is not pointing to a pages object.

Both solutios work well.

**Comment by bigeast** [comment]
I also have this problem, the bookmarks work fine in Adobe Reader DC but disappear in sumatraPDF.

There is no "Auto/Page" when edit in text editor.
