### ISSUE TITLE
Parmeter-print-settings "2x" doesn't work

### ISSUE THREAD

**Issue by noahzaozao** [sumatrapdfreader/sumatrapdf#621]
"D:\SumatraPDF-3.1.2\SumatraPDF.exe" -print-to-default -silent -exit-when-done -print-settings "2x" "test.pdf"

The print only shows there is 1 page to print , never can be more than 1. 
Am I wrongly using this parameter ?

@kjk @zeniko 

Thanks

**Comment by Rona111** [comment]
I also met this problem, Could anybody help me with how to use -print-settings "2x" to print 3times of pdf file?
@Philpax @campbeb @vszakats @kjk

**Comment by MarcoHe** [comment]
Hi,
same issue here. But this happens to me in GUI too. If i check sorted printing in print dialog then 
multiple copies is working well.
