### ISSUE TITLE
gray text near impossible to read

### ISSUE THREAD

**Issue by kaykingtoo** [sumatrapdfreader/sumatrapdf#623]
a lot of my pdf's come up in sumatra as light gray text;  near impossible to read.  I have to use one of my many other pdf readers - all of which - have the text nice dark black.  would be nice to use sumatra more often....

**Comment by kjk** [comment]
Please provide a sample PDF and preferably a name of the other software used for comparison and a screenshot that shows differences in rendering.

**Comment by GitHubRulesOK** [comment]
This comment about grey text has on occasion been addressed by recent improvements. 
Without a sample to compare if this issue is an exception I am closing as "no sample = no issue"
