### ISSUE TITLE
Some lines rendered too light

### ISSUE THREAD

**Issue by kuro68k** [sumatrapdfreader/sumatrapdf#624]
See the schematic on page 9 of this PDF: http://www.silabs.com/Support%20Documents/TechnicalDocs/AN383.pdf

Renders okay in Chrome and Adobe's software, but in Sumatra PDF the lines are very light and almost impossible to see when printed. I think it's due to them being very thin.

**Comment by kuro68k** [comment]
I checked Foxit too, it renders okay there. Well, it's not pretty but it's legible.

**Comment by kuro68k** [comment]
Is this the correct place to report this, or should I be looking somewhere else e.g. one of the libraries?

**Comment by kjk** [comment]
This code is from mupdf library but we have our own modifications.

Historically there have been several tweaks to rendering certain cases of thin lines, it's just hard to get all cases exactly right (not too thin and not too thick).

**Comment by kuro68k** [comment]
Thanks. If I find time I'll grab the source and experiment. Perhaps a parameter in the config file?

**Comment by kjk** [comment]
That would work. I believe Adobe Reader has a "Enhance thin lines" option (http://matslovesit.blogspot.com/2012/12/please-do-not-enhance-thin-lines-adobe.html)

**Comment by GitHubRulesOK** [comment]
@kjk there are several open issues about thin lines some of which have been addressed by latest MuPDF, I suggest those that have improved can be closed individually

![Untitled624](https://user-images.githubusercontent.com/12754913/68905794-4d06a480-073a-11ea-9b92-c16b9035de68.png)

**Comment by kjk** [comment]
Let's consider this fixed in latest https://www.sumatrapdfreader.org/dailybuilds.html
