### ISSUE TITLE
ErrorDataReceived - how to use this handler

### ISSUE THREAD

**Issue by tunminster** [sumatrapdfreader/sumatrapdf#626]
I am trying to add error handling method for process.Start method.

I like to kill the process if the process has stuck for any reason.  At the moment, the printing process stuck if there is a printer issue.  the process on the window task manager is staying there forever.

I think ErrorDataReceived event handler is to control the error event.  If there is any sample code that displays how to use ErrorDataReceived, that would be real helpful.

**Comment by kjk** [comment]
This is not related to Sumatra.
