### ISSUE TITLE
Download pages require JS - breaks without it

### ISSUE THREAD

**Issue by glamrock** [sumatrapdfreader/sumatrapdf#632]
Realized as I was trying to download, that links weren't displaying because I had javascript disabled for the site by default. While I whitelisted your site, it's a good idea to add a `<noscript>` section with links of available downloads:

```
<noscript>
  <p><a href="/dl/SumatraPDF-3.1.2-install.exe">installer</a> or 
  <a href="/dl/SumatraPDF-3.1.2.zip">portable (zip)</a> version.</p>

  <p>64-bit: <a href="/dl/SumatraPDF-3.1.2-64-install.exe">installer</a> or
  <a href="/dl/SumatraPDF-3.1.2-64.zip">portable (zip)</a> version.</p>
</noscript>
```

**Affected pages**: downloadafter.html, download-free-pdf-viewer.html

**Comment by yoursoftwarebug** [comment]
+1

What's the point of forcing user to enable Javascript?
