### ISSUE TITLE
Add "Delete" option

### ISSUE THREAD

**Issue by Shohreh** [sumatrapdfreader/sumatrapdf#633]
Hello

I'm running 3.1.2 on Windows 7.

I often use the Rename option (F2), but I think it'd be useful to also add a Delete option as an easy way to delete a PDF file after reading it directly from SumatraPDF.

Currently, I have to…
1.  close the document,
2) switch to a file manager (Total Commander, Windows Explorer, etc.),
3) find the file, and
4) delete it.

Cheers,

**Comment by Marmotian** [comment]
This can be done with the new settings available in 3.2.

* Create a batch file to do the actual delete function
* Open "SumatraPDF-settings.txt" with a Unicode text editor (I use Notepad++) wherever it lives on your system.
* Add this:
	[
		CommandLine = "full_path_2_a_batch_file_to_delete_argument(s)" "%1"
		Name = Delete &File
		Filter = *.pdf
	]

to the section:
ExternalViewers [
...
]

You can now delete the file you are viewing by holding down 'Alt' and hitting 'F' twice, or access it under the "File" menu using your mouse. If you're not comfortable being able to do it by keystrokes, remove the '&' and it will only be accessible by mouse.

If you want this to work with other filetypes, add them to the "Filter" line, separated by ';'.

**Comment by GitHubRulesOK** [comment]
The simplest way to delete files (which may or may not be locked against deletion is to stack a sequence foor running when session is terminated.
```
CommandLine = c:\windows\system32\cmd.exe /c "echo del "%1" >>%UserProfile%\desktop\DeleteMeList.cmd"
Name = Delete &File Later (after all are closed)
Filter = *.*
```

The file will be saved to your desktop where you can edit if you change your mind about an entry, I you are happy then double click it after all files are closed and all your troubles are deleted in one hit, dont forget to delete the temporary file itself, for the next run.

**Comment by kjk** [comment]
I don't want to re-implement file manager. In latest daily builds we have "File / Show in folder" menu, which you can invoke via `Alt-f`, `f` menu and since we don't lock most files you can delete currently viewed file via: `Alt-f`, `f`, `Del` and then go back to Sumatra and Ctrl-w to close the file.
