### ISSUE TITLE
Using sumatrapdf print XPS file to the HP printer setup multiplay appear blank pages

### ISSUE THREAD

**Issue by a875210** [sumatrapdfreader/sumatrapdf#634]
Use sumatrapdf print XPS file to the HP printer setup multiplay appear blank page, other printer is normal.Now 3.1.2 version of the original version 3.0 is can have problems such as how to solve?

使用sumatrapdf打印xps文件到HP的打印机设置多合一出现空白页，其他的打印机正常。原来3.0版本是可以的现在3.1.2版本有这样的问题请问怎么解决？

**Comment by GitHubRulesOK** [comment]
@kjk this old issue has no example of an xps file to check and my interpretation of the above description is the user got a "blank" page from such a format sent to an HP "multiplay" device.

I have no known problem.xps that causes print problems with a basic HP Multifunction printer, thus suggest this be closed unless more info on print driver / driver call or a failing file can be supplied
