### ISSUE TITLE
Printout look real bad!

### ISSUE THREAD

**Issue by gitfve** [sumatrapdfreader/sumatrapdf#636]
Hi
When printing out to ex a label printer the print is real bad. I have fiddled with the switch print as image but nothing can fix the bad printout.

I have now switched to Adobe and i hate it, but i need to have label printout working.

Version 3.1.2 64 bit. 

I dont know if it is a version problem or it is in all the version?

**Comment by SumatraPeter** [comment]
Have you tried 3.0?

**Comment by gitfve** [comment]
No i have not, why do you ask? Is something changed between?

**Comment by SumatraPeter** [comment]
Yes, see https://github.com/sumatrapdfreader/sumatrapdf/issues/329 for details about the changes made.

**Comment by gitfve** [comment]
OK, but what to do with the printout problem (I have fiddled with the switch, print as image but nothing can fix the bad printout.)? 
At the moment my solution was to install adobe and print my label from adobe....

Will there be a fix for the printout problem?

**Comment by SumatraPeter** [comment]
If you've tried 3.0 with both **Print as Image** turned off and on and the quality is equally bad, you should attach a sample PDF if required and perhaps scans showing the quality difference, and wait for Sumatra PDF's [primary developers](https://github.com/sumatrapdfreader/sumatrapdf/graphs/contributors) (kjk and zeniko) to respond. Only people with "sumatrapdfreader member" next to their names when they comment can tell you about the future of the app.

**Comment by gitfve** [comment]
I can see the help file for: http://www.sumatrapdfreader.org/settings3.0.html
have the switch: "PrintAsImage" but the help file for 3.2 have not!
Maybe is is therefore my test with this switch have no influence on my PrintOut! (the feature is removed in 3.2)

It display nice on the screen, only problem i barcode, and micro line  printing, it look bad on the printout in V3.2!

**Comment by SumatraPeter** [comment]
> Maybe is is therefore my test with this switch have no influence on my PrintOut! (the feature is removed in 3.2)

That's why I specifically mentioned using 3.0 above, which was the last version that provided both options to the user.

**Comment by gitfve** [comment]
Update.
Installed Sumatra 3.0 & 3.1.2 & Adobe. 
Run a test with a package label for GSL barcode and some small lines, and thin text!

Version 3.1.2: Printout look real bad.
Version 3.0: <Print as image enabled>: Printout look real bad.
Version 3.0 <Print as image disabled>: Printout look a little better, but cant be used as GLS label.
Adobe, Printout perfect!

My conclusion is to use Sumatra for a viewer and standard printout, and use Adobe for nice printing.
Sad conclusion:-(

**Comment by SumatraPeter** [comment]
> Version 3.0: : Printout look real bad.
Version 3.0 : Printout look a little better, but cant be used as GLS label.

Just to be clear, which instance did you try with _PrintAsImage = false_, and which one with _PrintAsImage = true_?

> My conclusion is to use Sumatra for a viewer and standard printout, and use Adobe for nice printing.
Sad conclusion:-(

Or you can try other PDF viewers also, such as Foxit or whatever. Anyway, your choice and maybe one day Sumatra's print quality will match Adobe's or even exceed it.

**Comment by gitfve** [comment]
edit: because "<>" wont work?...
Installed Sumatra 3.0 & 3.1.2 & Adobe.
Run a test with a package label for GSL barcode and some small lines, and thin text!

Version 3.1.2: Printout look real bad.
Version 3.0: "Print as image enabled": Printout look real bad.
Version 3.0 "Print as image disabled": Printout look a little better, but cant be used as GLS label.
Adobe, Printout perfect!

My conclusion is to use Sumatra for a viewer and standard printout, and use Adobe for nice printing.
Sad conclusion:-(

**Comment by GitHubRulesOK** [comment]
For anyone coming to this later the suggestion is to try the latest portable pre-release first to see if there is an improvement in image handling then also try **3.0 portable WITHOUT** Print> Advanced tab compatibility setting of "Print as image" (which is the only default method in the more recent copies including pre-release). So test with that check box empty!

**Comment by SumatraPeter** [comment]
The user who opened this issue found 3.0 with _Print as Image_ disabled to also be worse than Adobe.'s output, albeit better than with _Print as Image_ enabled. Frankly printing has never been Sumatra's strong suit, and I recall even kjk stating as much.

**Comment by GitHubRulesOK** [comment]
Duplicated Label printing quality issue consolidate with Bad printing quality #203 which has visual example
