### ISSUE TITLE
Не корректно показывает PDF размером 190 мб v3.1.2 64bit, также 32bit

### ISSUE THREAD

**Issue by grenyavolki** [sumatrapdfreader/sumatrapdf#637]
![2016-10-14_14-20-43](https://cloud.githubusercontent.com/assets/4752482/19385846/af040ec8-9219-11e6-8fc0-958ae4992720.jpg)

**Comment by kjk** [comment]
Nothing I can do without the PDF that shows the problem.

**Comment by grenyavolki** [comment]
https://www.dropbox.com/s/xq8vjhn6e95y5v8/%D0%91%D1%80%D0%B0%D0%B9%D0%B0%D0%BD%20%D0%9A%D0%BE%D0%BA%D1%81.%20%D0%A7%D1%83%D0%B4%D0%B5%D1%81%D0%B0%20%D0%B2%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9%20%28%D0%91%D0%B8-%D0%91%D0%B8-%D0%A1%D0%B8.%20%D0%AD%D0%BD%D1%86%D0%B8%D0%BA%D0%BB%D0%BE%D0%BF%D0%B5%D0%B4%D0%B8%D0%B8%29%20-%202013.pdf?dl=0
