### ISSUE TITLE
Missing Search function in certain ebook formats. 

### ISSUE THREAD

**Issue by mikeloeven** [sumatrapdfreader/sumatrapdf#639]
When opening a Epub or Mobi document there is no navigation / search bar at the top of the screen and pressing ctrl-f does not appear to do anything. Both of these formats have searchable text and most eBook readers support it. I have no idea why Sumatrapdf doesent seem capable of searching these documents though this could be a simple UI bug preventing the search dialogue from displaying

**Comment by SumatraPeter** [comment]
Same solution as given [here](https://github.com/sumatrapdfreader/sumatrapdf/issues/414#issuecomment-202132956).

**Comment by GitHubRulesOK** [comment]
@kk dup of https://github.com/sumatrapdfreader/sumatrapdf/issues/268

**Comment by GitHubRulesOK** [comment]
@kjk dup of https://github.com/sumatrapdfreader/sumatrapdf/issues/268

**Comment by kjk** [comment]
closing as duplicte
