### ISSUE TITLE
In EPUB's some spaces are missing when UseFixedPageUI = true

### ISSUE THREAD

**Issue by BurkSchu** [sumatrapdfreader/sumatrapdf#645]
When setting UseFixedPageUI = true, the layout of EPUB's misses some spaces, see attached screenshot.
![fehler epub](https://cloud.githubusercontent.com/assets/22975984/19590019/f344a2a4-976f-11e6-9ef7-555312d3048e.jpg)

**Comment by GitHubRulesOK** [comment]
@kjk without a sample this is not a fixable issue ?

**Comment by kjk** [comment]
Yes, not test file, no way to make progress.
