### ISSUE TITLE
Offer option to switch tabs in recently used order

### ISSUE THREAD

**Issue by timhandschack** [sumatrapdfreader/sumatrapdf#646]
When working with multiple documents a switching in recently used order is way more helpful than tabbing from left to right through all documents. Using ALT + number demands remembering the position and always is a different move with you fingers. Also, tabbing in recently used order is the more common approach, comparable to the OS'es application tabbing.
Many thanks.

**Comment by kjk** [comment]
Can you describe how other Windows applications handle this? What keyboard shortcut is used to switch between tabs?

**Comment by timhandschack** [comment]
The shortcut does not need to be changed but the tabbing order. The tabbing order most OSes / window manager are using for application switching is last used instead of “left to right”. That behavior shall be applied to tabbing of Sumatra tabs.

Tim Handschack // Software Designer
Allied Vision Technologies GmbH
Klaus–Groth–Str. 1, 22926 Ahrensburg, Germany
Phone: +49 (4102) 6688-135 // Fax: +49 (4102) 6688-10
www.alliedvision.com<http://www.alliedvision.com/>
President/CEO: Frank Grube | Registration Office: AG Jena HRB 208962 | Headquarters: Taschenweg 2a, 07646 Stadtroda, Germany

Von: Krzysztof Kowalczyk [mailto:notifications@github.com]
Gesendet: Freitag, 21. Oktober 2016 21:18
An: sumatrapdfreader/sumatrapdf
Cc: Tim Handschack; Author
Betreff: Re: [sumatrapdfreader/sumatrapdf] Offer option to switch tabs in recently used order (#646)


Can you describe how other Windows applications handle this? What keyboard shortcut is used to switch between tabs?

**Comment by GitHubRulesOK** [comment]
SumatraPDF does reorder Tabs with files into those most recently opened **see the priority of 1-7 in its history** however most users expect the **tabs** will stay exactly as they were saved so SumatraPDf can reopen them in the same sequence they were Historically opened. Very few Latin character users need tabs loaded backwards it is different for RTL readers but that's a different issue.

You can drag the tabs into whatever physical order you like and step all **from right to left or** left to right but adding bloat to store and control a historic list of openings and actions seems to defeat the concept of a lightweight viewer

![image](https://user-images.githubusercontent.com/12754913/73952012-5dbc5600-48f6-11ea-9a47-2d54f9db8e15.png)

**Comment by fisher-j** [comment]
I would also like to see this option implemented as an alternative to the left to right tab cycling behavior. To be clear, it is not necessary to reorder the tabs visually across the top. The desired behavior concerns the ctrl + tab shortcut (on windows). Instead of cycling through tabs in the order displayed, tabs are cycled through in the most recently viewed order. 

This behavior is intuitive for dealing with multiple documents: press ctrl + tab once to go back to the document you were looking at previously; twice to go to the document you viewed two documents ago. I often have many documents open, but am only actively switching between a small subset of these, and remembering the tab indexes myself is not desirable.

I know next to nothing about implementation in c, but it seems like updating a list of tab indexes each time a new tab is viewed wouldn't be too computationally intensive.

**Comment by GitHubRulesOK** [comment]
Interesting I jump around in Edge in random recent order usually skipping between pairs.
Sso I just used ctrl+tab to see how Microsoft chrome does it and sure enough in my locality it sequentially moves exactly one tab left to right as I expect it to do! 
I frequently drag tabs into the order I like to give priority so most important tab on the left then this one 🙂

**Comment by kjk** [comment]
A recommended way to switch between tabs would now be command palette (`Ctrl + K`)

**Comment by fisher-j** [comment]
The addition of the command palette is very nice, but it is not the same as switching tabs in the most recently viewed order using ctrl + tab (or ctrl + tab + tab to go two back, or ctrl + tab + tab + tab to go three back) when one does not not want to have to remember tab numbers or file names.

**Comment by thiagolucas22** [comment]
It will be really nice to cycle btw the same two tabs just using the same command (like alt + tab in windows). I normally need to compare small differences btw reports, and having to look were to click or ctrl+1 or ctrl+2 jeopardize the focus for details.

**Comment by GitHubRulesOK** [comment]
@thiagolucas22 
easiest way I think is drag the two tabs off to second window (close any home tab in that window)
now you can hold ctrl+tab for flicker diffing, afterwards if you wish drag back to main window

**Comment by holmesb** [comment]
No need for a separate keyboard shortcut IMO. People either prefer MRU or left-to-right switching in my experience. Can just have a tick-box option: "ctrl-tab most recent". Will default to off so no breaking change.
