### ISSUE TITLE
Please add color management support.

### ISSUE THREAD

**Issue by liuhuasong** [sumatrapdfreader/sumatrapdf#647]
When you open [http://www.color.org/version4pdf.pdf](http://www.color.org/version4pdf.pdf) in Sumatra PDF, it does not show the correct color.

In order to show the correct color, we must add color management support to Sumatra PDF.

[https://en.wikipedia.org/wiki/Little_CMS](https://en.wikipedia.org/wiki/Little_CMS) says:

> [Little CMS](http://www.littlecms.com/) is an open source color management system, released as a software library for use in other programs which will allow the use of International Color Consortium profiles. It is licensed under the terms of the MIT License.

**Comment by liuhuasong** [comment]
reference: [Is your system V4-ready?](http://www.color.org/version4ready.xalter)

**Comment by GitHubRulesOK** [comment]
![image](https://user-images.githubusercontent.com/12754913/73998340-3c408600-4959-11ea-80af-31cbd61ee407.png)

Passes closes
