### ISSUE TITLE
Printing both sides

### ISSUE THREAD

**Issue by Snootlab** [sumatrapdfreader/sumatrapdf#649]
Hello,
Sumatra is great but if you have a both sides printer, you have to go 3 windows far to select it.
Could you please just add a check box on the main print window ?
Thank you.

**Comment by TimMensch** [comment]
This bug is actually worse now: The printer preferences dialog _no longer allows you to select double sided printing_. I can't print double-sided from Sumatra at all now.

I had to open the PDF in Edge to be able to print double-sided at all. Sumatra needs to be able to send a request for double-sided printing directly, as other Windows apps do now.

**Comment by jgollenz** [comment]
This issue still exists

**Comment by petrasteri** [comment]
In terms of programming, I think the authors / developers just use the default print dialog without customization and as Windows evolves, content of the dialog changes as well:
https://docs.microsoft.com/en-us/windows/desktop/dlgbox/print-dialog-box

For the record, a good article here for those who have time to read and program:
https://www.codeproject.com/Articles/2585/%2FArticles%2F2585%2FAn-Easy-Way-to-Customise-the-Default-Print-Dialog

**Comment by GitHubRulesOK** [comment]
petrasteri is generally correct in that SumatraPDF simply passes to Windows the Selected Area or Page Ranges it is the Printer manufacturers' driver that processes layout, flipping and other handling
If a feature is missing it is worth looking for another printer driver, Out of necessity it will thus be down to manufacturer as to how many windows deep in their driver. Here in HP driver print on both sides is **on the first tab** of preferences

![image](https://user-images.githubusercontent.com/12754913/75610840-e94b9000-5b0c-11ea-9d30-eec425ff7e91.png)

**Comment by TimMensch** [comment]
FWIW, the current dialog _does_ work fine. This bug seems to be irrelevant now.

At the time, the dialog was _not_ the same, and/or some features were missing.

**Comment by GitHubRulesOK** [comment]
@TimMensch 
Thanks for confirmatory feedback, this issue was closed on basis of OP request to make a manufacturers setting more accessible !

**Comment by LinuxOnTheDesktop** [comment]
Can we re-open this bug report, or create a new report? For, it seems to me that Sumatra cannot print double-sidedly, which seems a serious failing to me (and one that pushes me back to Acrobat).

**Comment by GitHubRulesOK** [comment]
@LinuxOnTheDesktop 
Windows 11 ?? MS changed Print system for Worse like many "user requests for "Dark Side" enhancements it is the inverse to what it was!

SumatraPDF does not have access to the thousands of Acrobat paid Adobe staff in the same town 
![image](https://github.com/sumatrapdfreader/sumatrapdf/assets/12754913/8134cf1c-9888-4400-8a1c-ee1d00660ed4)
(SJ ), so as to keep up with what happens over at Redmond.
I dont think sending my Sister in Law, next-door to go and ask them to help out, would make any difference.

**Comment by LinuxOnTheDesktop** [comment]
@GitHubRulesOK

I use Windows _10_.

No, clearly, you need to get sis-in-law-on-the-case. More seriously: double-sided printing is a pretty essential feature, no?

**Comment by GitHubRulesOK** [comment]
@LinuxOnTheDesktop 
As pointed out before it is down to windows accepted drivers 
I have 16 printers listed as accessible and **only the HP one shown above is suitable for double sided**
The other 15 are virtual or single sided printers (use stock that is not designed to be turned over for printing even if I can)
