### ISSUE TITLE
Open CHM file on a named context

### ISSUE THREAD

**Issue by Hubel** [sumatrapdfreader/sumatrapdf#65]
When I use the command line argument `-nameddest $dest` with a CHM file, it does not open the specified context.

In [Windows API](http://msdn.microsoft.com/en-us/library/windows/desktop/ms670088(v=vs.85).aspx) the `HtmlHelp` method can be called with the command `HH_HELP_CONTEXT` and the context ID which opens the same file at the desired chapter.
Since the Windows Help does not close on Escape, I would like Sumatra to implement the context sensitivity.

**Comment by zeniko** [comment]
Thanks for the report. Please share an affected file as described in [submitting bug reports](https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports) and tell us one context ID so that we can reproduce and fix this issue.

**Comment by Hubel** [comment]
I created a small sample CHM file that contains topic IDs:
http://wikisend.com/download/102984/chmtest.zip

The list of IDs is contained as an XML file.

Using HtmlHelp, a topic can be open calling
`hh -mapid 2230 ms-its:chmtest.chm`

I would like to see the same page calling
`SumatraPDF.exe -nameddest 2230 chmtest.chm`

**Comment by Hubel** [comment]
In `ChmModel::GetNamedDest()` the destination name `2230` is compared to the list of internal filenames (e.g. `d34e81.htm`) in the CHM file and therefore not found.
It looks like the Map Aliases/IDs are not read from the CHM file.

**Comment by zeniko** [comment]
Thanks for the document. The next (pre)release version will also accept Alias topic IDs for the -named-dest command line argument for CHM documents so that you can use SumatraPDF in the same way as HtmlHelp.
