### ISSUE TITLE
 no color changes in fb2. 

### ISSUE THREAD

**Issue by modx-arseniy** [sumatrapdfreader/sumatrapdf#650]
after editing the advanced settings. windows 10 64 latest updates. 

I want darker colors or inverted. eyes get tired with the default yellow colors. Like icebookreaders colors
Strangely enough, but the key  "-invert-colors"  is not working

**Comment by modx-arseniy** [comment]
working option UseSysColors = true + dark and high contast theme in windows

**Comment by prstorero** [comment]
Have you tried the following?
![invertedpdf](https://cloud.githubusercontent.com/assets/7811371/20075329/6600b22e-a4f9-11e6-9b38-ecef0255b62e.png)

UseSysColors = false
TextColor = #ffffff
BackgroundColor = #000000

With these settings, UseSysColors = false gives me the inverted look I want and changing it to true makes it look like the original PDF again.

**Comment by GitHubRulesOK** [comment]
Currently in pre-release, -invert-colors and most color settings are working in FB2 just the same as other formats. so am closing this issue.
![image](https://user-images.githubusercontent.com/12754913/73712465-17060a80-4702-11ea-9577-26ca2d2c75c3.png)

If you're using high contrast modes then most colours will naturaly be inverted
![image](https://user-images.githubusercontent.com/12754913/73712278-83343e80-4701-11ea-9631-1db17d63f890.png)
