### ISSUE TITLE
Search function freeze

### ISSUE THREAD

**Issue by grimes2** [sumatrapdfreader/sumatrapdf#651]
Sumatrapdf v3.1.2 64bit
Windows 10

Steps to reproduce:
1. open a pdf document in start page
2. search function: insert a
3. close document tab
4. open another pdf document in start page
5. a is still in search function and the search function is not responsive

**Comment by SumatraPeter** [comment]
Can reproduce even with 2 PDFs opened one after the other from Explorer. Only pressing Ctrl+F again activates the search field again and allows one to alter/delete the previous search text.

**Comment by GitHubRulesOK** [comment]
@kjk 
still an issue in recent versions.
opening a second file will result with enter accepted on the page as go forward a page
You can use the stored search via the adjoining back/forward arrows !
However the main issue is you can not change the search to a new entry unless as @SumatraPeter observed you need to restart search with Ctrl+F
