### ISSUE TITLE
tab-switch hotkey: use <shift+h> and <shift+L>

### ISSUE THREAD

**Issue by heyuanpi** [sumatrapdfreader/sumatrapdf#652]
Hi,
Could you please leave a configuration to config tab-switch hotkey?
It's better to use  <shift+h> to switch to left tab, and <shift+L> to switch to right tab. 
This is more easy compared to default <ctrl+tab> and <shift+ctrl+tab>.

**Comment by kjk** [comment]
What other Windows software uses such shortcuts?

Usually we want to follow the conventions of the platform.

**Comment by heyuanpi** [comment]
Hi kjk,

I mean, may be you can leave an option for us to config this shortcuts.   
Of course you have your default settings.

sumutra pdf fans.

**Comment by GitHubRulesOK** [comment]
Shit H and L are currently assigned
Classing as Duplicate of other requests to change / customise all key values to something else
