### ISSUE TITLE
Reader opens itself as a pdf document

### ISSUE THREAD

**Issue by Bishop1601** [sumatrapdfreader/sumatrapdf#654]
When sumartra is started as an app out of Revelation Software's Open Insight the executable is fed the entire command line.  Sumartra is incorrectly trying to open itself as a pdf.  The command line looks like this  C:\Sumarta\Sumarta.exe 'C:\docs\doc1.pdf'.  When Sumarta opens, there will be 2 documents:  Sumarta.exe (with an error that it could not be opened) and Doc1.pdf.  The software should be smart enough to open itself as a pdf document.   Ideally, it should have an option to require a leading character(s) to indicate the document(s) to open.  Requiring a '-' in front of each document would keep the logic consistent and allow elemination of it trying to open itself.

**Comment by kjk** [comment]
It looks like an issue in how it's being called by the other program, not in how it parses the command line.

**Comment by Bishop1601** [comment]
Nope.  The same exact logic works fine for Word, Excel and  Powerpoint Viewer.

**Comment by Bishop1601** [comment]
I use the exact same command with 4 other apps and they all work correctly.  So while the command line may not be handled in the best manner, Sumatra should be smart enough to recognize where the parameter list starts.

-------- Original message --------
