### ISSUE TITLE
Setting EbookUI - Bookmark issue

### ISSUE THREAD

**Issue by gastopaul** [sumatrapdfreader/sumatrapdf#655]
Sumatrapdf v3.1.2 64bit
Windows 7

I set

EbookUI [
	FontName = Lucida Sans Unicode
	FontSize = 10
	TextColor = #ffff00
	BackgroundColor = #000000
	UseFixedPageUI = false
]

Then, when I open an ebook file with bookmarks, the background color of the bookmark window is black (so OK) but the text color still black, so it's impossible to read.

**Comment by BrutPitt** [comment]
At today I confirm this issue: in the bookmark, reading EPUB, the text remains BLACK whatever the value of **TextColor** in **EbookUI** section, while the background changes according to the value of **BackgroundColor**.
So, with the dark backgrounds, the bookmark text becomes illegible.
(With PDF documents the bookmark remains always with defaults colors, and this is OK.)

In Windows 10, with the setting:
EbookUI [
	FontName = Georgia
	FontSize = 12.5
	TextColor = #c0c0c0
	BackgroundColor = #000000
	UseFixedPageUI = false
]
This is the result:
![sumatrapdf](https://user-images.githubusercontent.com/16171743/37865391-1b288f56-2f7c-11e8-8777-d59a99dc2938.jpg)

**Comment by GitHubRulesOK** [comment]
@kjk I think that same as https://github.com/sumatrapdfreader/sumatrapdf/issues/1247# and #1095 this has been addressed
