### ISSUE TITLE
Toolbar: add "BACK|Forward" navigation button(s)

### ISSUE THREAD

**Issue by VitRom** [sumatrapdfreader/sumatrapdf#657]
At present the only ways to navigate back/forward after a jump from TOC or anything like this are
1) keyboard hotkeys [Alt]+[Left/Right] and
2) Menu/Navigation/Back (/Forward) commands.
IMHO this type of navigation is a more frequent use case when reading a complex documents with a TOC and a lot of internal links. But the only navigation related buttons on toolbar are back/forward **_search_** and prev/next **_page_** that are useless in this case and forces user to use abovementioned ways

$subj

PS. And the context menu, currently with a "sel all" and "copy" commands only, is a right place for this navigation function too.

**Comment by SumatraPeter** [comment]
https://github.com/sumatrapdfreader/sumatrapdf/wiki/Toolbar-design

**Comment by VitRom** [comment]
Er... I'm not about bells and whistles and not about blowing things up with a glows, spikes, animations and misc UFO-like floating crap. Just about "a quick access to frequently used functionality" and what exact this "frequently" is.

I and most of my colleagues reads a 99% of PDFs in the "Continious scroll" mode with a "Fit to page width" zoom. Most of times it's a different kinds of manuals and userguides viewed in a normal non-maximized windows placed aside to another windows we're working with. And a much faster way to go to the next/previous page is a brief scroll with a mouse wheel. So these two "Prev Pg/Next Pg" buttons are useless.

At the same time these abovementioned manuals contains a misc links, i.e. TOC, inter-references, footnotes. And after a several jumps through these links reader have to recall a page number where he has started his digging and either type it in the "Page:" filed either just scroll. This case these two buttons mentioned above are useless too.

And now pls review a described above assuming these two buttons calls a function I've asked for, "Prev/Back". Still no overbloat but much handy, isn't it?

**Comment by SumatraPeter** [comment]
Oh, don't get me wrong, I do think the toolbar needs an overhaul or ideally be user configurable. However I just provided the wiki link above to inform you about how the developers look at all such toolbar redesign requests.

**Comment by shaiay** [comment]
I made a very simple change to add this: https://github.com/shaiay/sumatrapdf/commit/413bf0ba07c6196127185451a35b12e247672585
However, currently it uses the same icons as prev & next page, so a bit confusing. Any help with nicer icons would be appreciated. Once I have better icons I will create a pull request

Seeing the discussion here, Should I replace the prev/next page with these? I too find them quite useless, but maybe others have grown attached to them?

A compromise to suit all could be to add a setting options for toggling between these two uses

**Comment by GitHubRulesOK** [comment]
It is easy to add custom keyboard shortcuts.

However
Configuring toolbar is tracked by https://github.com/sumatrapdfreader/sumatrapdf/issues/1956

**Comment by kjk** [comment]
Toolbar is now customizable. See https://www.sumatrapdfreader.org/docs/Customize-toolbar

You can add buttons for `CmdNavigateBack` and `CmdNavigateForward` [commands](https://www.sumatrapdfreader.org/docs/Commands)
