### ISSUE TITLE
When you use tabs, the toolbar disappears

### ISSUE THREAD

**Issue by jg-github** [sumatrapdfreader/sumatrapdf#658]
I'm using the latest beta (10551). As mentioned in the title, if I set the program to use tabs, the toolbar disappears. I'd like to be able to use both.

Thank you.

**Comment by GitHubRulesOK** [comment]
@kjk duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/549

**Comment by kjk** [comment]
consolidate as #549
