### ISSUE TITLE
Comic Book Archive (*.CBX) page sequence issue

### ISSUE THREAD

**Issue by Titokhan** [sumatrapdfreader/sumatrapdf#659]
As described [here](https://en.wikipedia.org/wiki/Comic_book_archive#Design), if the comic container doesn't follow the use of preceding zeros for all positions (example: using 01 rather than 1) then the viewer rearranges the pages. Most of the desktop readers ignore this & correctly display the page sequence. Can it be possible to fix this in the next update?

I've prepared a dummy CBZ file as example: http://ge.tt/8c4a25h2

Please notice the page number footer to get the rearranging issue.

**Comment by SumatraPeter** [comment]
+1 for [natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order) support.

**Comment by SumatraPeter** [comment]
This issue was recently brought up again [on the forum](http://forums.fofou.org/sumatrapdf/topic?id=3185419), where @kjk replied:

> Can you post a sample of the actual file names inside the .cbz file?
> 
> The problem here is that there are various ways to sort the names and a heuristic that works for one case might not work for another.

@kjk You can see the file linked to above for an example. Basically unless the requisite padding with leading zeroes is present Sumatra gets the sort order wrong. So we end up with something like 1.png, 10.png, 11.png, 2.png instead of the obvious correct (for humans) order.

You can see the references list of the Wikipedia article I've linked to above for more details if required. Martin Pools algorithm might also be of interest to you: https://github.com/sourcefrog/natsort

Finally, I just want to note that even Windows Explorer has used natural sort by default [since XP was released](https://support.microsoft.com/en-us/help/319827/the-sort-order-for-files-and-folders-whose-names-contain-numerals-is-different-in-windows-vista,-windows-xp,-and-windows-server-2003-than-it-is-in-windows-2000) more than a decade-and-a-half ago, and every other decent modern sequential image viewer/comic book reader I know of has been using natural sort for ages.

**Comment by SumatraPeter** [comment]
Link to another discussion [on the new forum](https://muut.com/sumatrapdf#!/general:file-ordering).

**Comment by glachancecmaisonneuve** [comment]
This should be closed now.  see https://github.com/sumatrapdfreader/sumatrapdf/pull/1060

**Comment by SumatraPeter** [comment]
Awesome, looking forward to the next stable release with this fix. :)

**Comment by SumatraPeter** [comment]
[Looks like](https://forum.sumatrapdfreader.org/t/sumatrapdf-11061-prerelease-cbr-page-order-bug/1572/10?u=sumatrapeter) #1060 didn't fix this after all. :(

**Comment by SumatraPeter** [comment]
Looks like #1060 didn't fix this after all. :(

Forum discussion [here](https://forum.sumatrapdfreader.org/t/sumatrapdf-11061-prerelease-cbr-page-order-bug/1572/10?u=sumatrapeter) @kjk @glachancecmaisonneuve 

P.S. [Here](https://github.com/sumatrapdfreader/sumatrapdf/files/2540347/SumatraPDF_3.2.11061_Image_Sort_Failure_Test_Archives.zip) are 10 archives (2 each for 7z/CB7, RAR4/CBR, RAR5/CBR, TAR/CBT and ZIP/CBZ) for testing. The "Good" ones have all the images inside in proper order (pages 1 to 10), whereas the "Bad" ones have been created specifically with the images in the wrong order (pages 6 to 10, then 1 to 5).

**Comment by SumatraPeter** [comment]
Looks like #1060 didn't fix this after all. :(

Forum discussion [here](https://forum.sumatrapdfreader.org/t/sumatrapdf-11061-prerelease-cbr-page-order-bug/1572/10?u=sumatrapeter) @kjk @glachancecmaisonneuve 

P.S. [Here](https://github.com/sumatrapdfreader/sumatrapdf/files/2540355/SumatraPeter_3.2.11061_Image_Sort_Failure_Test_Archives.zip) are 10 archives (2 each for 7z/CB7, RAR4/CBR, RAR5/CBR, TAR/CBT and ZIP/CBZ) for testing. The "Good" ones have all the images inside in proper order (pages 1 to 10), whereas the "Bad" ones have been created specifically with the images in the wrong order (pages 6 to 10, then 1 to 5).

**Comment by SumatraPeter** [comment]
Looks like #1060 didn't fix this after all. :(

Forum discussion [here](https://forum.sumatrapdfreader.org/t/sumatrapdf-11061-prerelease-cbr-page-order-bug/1572/10?u=sumatrapeter) @kjk @glachancecmaisonneuve 

P.S. [Here](https://github.com/sumatrapdfreader/sumatrapdf/files/2540361/SumatraPeter_3.2.11061_Image_Sort_Failure_Test_Archives.zip) are 10 archives (2 each for 7z/CB7, RAR4/CBR, RAR5/CBR, TAR/CBT and ZIP/CBZ) for testing. The "Good" ones have all the images inside in proper order (pages 1 to 10), whereas the "Bad" ones have been created specifically with the images in the wrong order (pages 6 to 10, then 1 to 5).

**Comment by SumatraPeter** [comment]
Looks like #1060 didn't fix this after all. :(

Forum discussion [here](https://forum.sumatrapdfreader.org/t/sumatrapdf-11061-prerelease-cbr-page-order-bug/1572/10?u=sumatrapeter) @kjk @glachancecmaisonneuve 

P.S. [Here](https://github.com/sumatrapdfreader/sumatrapdf/files/2540385/SumatraPeter_3.2.11061_Filename_Sort_Failure_Test_Archives.zip) are 6 archives for testing. The "Good" ones have all the images inside in proper order (pages 1 to 10), whereas the "Bad" ones have been created specifically with the images in the wrong order (pages 6 to 10, then 1 to 5).

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/87925939115ab8ee758045c9331cc4236d27497f

**Comment by SumatraPeter** [comment]
Thanks @kjk, this indeed looks like it's been fixed. [Here](https://github.com/sumatrapdfreader/sumatrapdf/files/2559671/SumatraPeter_3.2.11063_Filename_Sort_Success_Test_Archives.zip) are 5 archives (1 each for 7z/CB7, RAR4/CBR, RAR5/CBR, TAR/CBT and ZIP/CBZ) for testing, and my test results can be found in the [forum](https://forum.sumatrapdfreader.org/t/sumatrapdf-11061-prerelease-cbr-page-order-bug/1572/19?u=sumatrapeter).

**Comment by chiefgreenone** [comment]
Hi, @kjk. Using sumatrapdf 3.3, the files are sorted correctly, Thanks for this fix, but not with folders:
Chapter 1
Chapter 1.5
Chapter 2
Chapter 2.2
The files within a #.5 folder are shown before #'s files, 2.2 before 2, etc..
[folder_ordering_test.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/11433444/folder_ordering_test.zip)
