### ISSUE TITLE
"nj" digraph not shown in some pdf files

### ISSUE THREAD

**Issue by pgp** [sumatrapdfreader/sumatrapdf#66]
the digraph "nj" in some pdf files is not shown by SumatraPDF, while it is correctly shown in other readers such as Foxit and Adobe Reader.
Sample PDF page presenting the issue (notice the word "conjecture", becoming "coecture" in SumatraPDF):
https://drive.google.com/file/d/0B-3-sYT4VYjLZlpLbnFENnRyT0k/view?usp=sharing

**Comment by zeniko** [comment]
Thanks for the report and the linked document. Your document has managed to trigger an edge case I've never seen before and which SumatraPDF/MuPDF handle wrongly. This issue will be fixed in the next (pre)release build.
