### ISSUE TITLE
Buttons to close all tabs and to remove all frequently read

### ISSUE THREAD

**Issue by Remiol** [sumatrapdfreader/sumatrapdf#662]
Is there a possibility to add 2 icons/buttons:

1) close all tabs
2) remove all frequently read
?

**Comment by Remiol** [comment]
Please can you add an "x" on every single frequently read document in order to remove only a single one.

Thanks for the work you've done. You made 2 of the best software on the market: the silver searcher and sumatrapdf.

**Comment by kjk** [comment]
I believe you can remove a single document from frequently read list by using context-menu (right-click)

**Comment by Remiol** [comment]
wow.. haven't seen that. Thanks.
