### ISSUE TITLE
Disable DRM protection

### ISSUE THREAD

**Issue by ranyyy** [sumatrapdfreader/sumatrapdf#664]
DRM protection is stupid, please let your program not obey it (or at least add an option to disable it in "Advanced Settings").

**Comment by jimbo1qaz** [comment]
+1

**Comment by SumatraPeter** [comment]
Those who are unable to modify the code and recompile themselves but are willing to trust another user's compiled version can take a look at @ianamk's builds available on his [Mega account](https://mega.nz/#F!WwIiFDyZ!eA2g4lws9YNOuEI0a9Dkpw). Be sure to go through the ReadMe text file first to see a complete list of changes that have been made.

Disclaimer: Please note that _**no** support will be provided for these unofficial versions_ and you use them at your own risk.

**Comment by martinzoller** [comment]
I am also highly surprised that a free software PDF viewer would consider DRM settings, particularly those denying printing. Okular seems to ignore them. What is the rationale for this?

**Comment by GitHubRulesOK** [comment]
@martinzoller DRM was not officially disabled as such. Passwords are required to open and save changes. The internal restrictions are only suspended whilst the file is opened for commenting. Thus would in a pre-release be suspended. With the imminent 3.3 still in progress, we will have to see.
