### ISSUE TITLE
Would be nice to drag tabbed doc into a new window

### ISSUE THREAD

**Issue by pedwo** [sumatrapdfreader/sumatrapdf#666]
Tabbed view is great, but sometimes you want to compare against a different PDF, so it would be great to be able to drag a tab into it's own window. Switching tabbed view off is not what I want because it's likely that I will have several PDFs open.

**Comment by pdgessler** [comment]
See also #485 #413 #345 (all similar requests) and the main issue on this topic, #18

**Comment by GitHubRulesOK** [comment]
@kjk duplicate ?

**Comment by kjk** [comment]
Yep, closing as duplicate.
