### ISSUE TITLE
SumatraPDF-settings.txt can't get updated when it has been EFS encryped.

### ISSUE THREAD

**Issue by holmium** [sumatrapdfreader/sumatrapdf#670]
After I scroll some pages, or open a new PDF and then close SumatraPDF, SumatraPDF-settings.txt won't get updated when it has been EFS encryped, which causes SumatraPDF not able to remenber opened files.

OS: Windows 7 x86-64

![1](https://cloud.githubusercontent.com/assets/2255715/20593667/35223358-b26e-11e6-9680-5daa12c1d212.png)

**Comment by kjk** [comment]
Supporting EFS encryption of settings file is not something I plan to do. I'll accept PR if it's a simple thing but will not invest lots of time into making sure it works.
