### ISSUE TITLE
Scroll Up/Down Using Mouse, Hand Icon

### ISSUE THREAD

**Issue by nkormanik** [sumatrapdfreader/sumatrapdf#673]
I'm wondering how hard it would be to keep the Hand Icon stationary when scrolling, as opposed to it moving up and down the page.

It's tiresome continually moving the mouse cursor/hand icon from, say, top of page back to bottom of page, over and over, to keep scrolling (or vice versa the other direction).

All programs that I know of scroll the same way, with mouse cursor NOT remaining stationary.  Major bummer.

So, what's the thinking on this?

Thanks for a fine program!

Nicholas Kormanik

**Comment by kjk** [comment]
I don't really understand. There are many ways to scroll (by dragging with mouse, with a scroll-wheel, with touch gestures, with keyboard).

Scrolling by dragging with mouse moves the cursor. I don't see how it could work differently. What are the programs that do it differently, what scrolling method do you refer to and what exactly is the difference?

Also, maybe it's a typo, but your claims are contradictory. You want the cursor to stay in place like in other software where cursor doesn't stay in place?

**Comment by nkormanik** [comment]
As said, NO other program allows keeping the cursor in place and just scrolling.  I was just curious if you might know how to accomplish it.

I'll try to explain again.  Just scroll the page, up or down, but leave the mouse cursor stationary, don't move it.  The ONLY thing moving is the scrolling page, up or down.

As it stands now (all program that I know of) the mouse cursor also moves, along with the scrolling page.

I don't have a mouse wheel.  Maybe that's the issue.

**Comment by kjk** [comment]
I see. As a rule, we follow what other programs are doing because that's what people are used to doing.
