### ISSUE TITLE
when i double click  one page,the app is shutdown

### ISSUE THREAD

**Issue by uyong** [sumatrapdfreader/sumatrapdf#675]
when i double click one page, the app show busy state and no response, then it exit, no anything exception message. my current version is 3.1.2_64-bit and system is window10.

**Comment by kjk** [comment]
Please provide the file that causes the problem (see https://github.com/sumatrapdfreader/sumatrapdf/wiki/Submitting-bug-reports)

**Comment by uyong** [comment]
Later i test some other pdf files, and find this problem often happen.These pdf files contain pictures or the pdf file is consisted of picture, when i open it and double click one of picture, then the problem is happen.

**Comment by SumatraPeter** [comment]
Cannot replicate the issue with multiple test PDFs. Have you tried uninstalling and reinstalling the app?

**Comment by GitHubRulesOK** [comment]
@kjk without sample files this issue is unclear if still present in current releases or the users system/file formats

**Comment by kjk** [comment]
Can't make progress without test files that show the problem.
