### ISSUE TITLE
Feature request: 2 finger slide to change pdf tab

### ISSUE THREAD

**Issue by voloner** [sumatrapdfreader/sumatrapdf#677]
Hi I was wondering if it is possible to implement a feature that can change pdf tab using 2 finger slide. I was thinking that this was possible since scrolling and zooming is also a 2 finger gesture. If this is possible, this would make reading pdf really really productive and somewhat differentiate this to other pdf reader.
PS: I love Sumatra, both the pdf reader and the island ^.^

**Comment by kjk** [comment]
Is there any other software on Windows that behaves the way you describe?

If yes, let me know which.

If not, we wont implement novel UI gestures because people will not discover them and if they do, they'll be surprised by them.

**Comment by voloner** [comment]
There is none of which I know of. The closest would be Microsoft edge browser but it is for going back instead. Is it not possible to make the feature toggle able on or of? And isn't surprised a good thing?
