### ISSUE TITLE
Cannot exit full screen mode using Windows Tablet

### ISSUE THREAD

**Issue by kenkangxgwe** [sumatrapdfreader/sumatrapdf#678]
It seems that pressing <code>Esc</code> is the only way to exit full screen mode, but what if I use windows tablet? I can never exit any more once I enter the full screen mode.

**Comment by kantoniak** [comment]
You can enter/exit fullscreen tapping once with fingers, two to five works for me (Goclever Insignia 1010 Win).

**Comment by mirh** [comment]
Duplicate of #882 imo.

**Comment by kjk** [comment]
Closing as duplicate of #882.
