### ISSUE TITLE
"Fit Content" produces glitchy text

### ISSUE THREAD

**Issue by agyild** [sumatrapdfreader/sumatrapdf#683]
"Fit Content" option causes text to be displayed glitchy. Sometimes the bug occurs randomly but I was also able to reproduce the bug whenever I flipped a few pages forward then came back. It feels like Sumatra "forgets" the precise zooming amount and displays it with wrong precision but cannot be sure.
The first screenshot is the non-glitchy one or how it should look like, the second one is the glitchy one where characters look kind of quirky.
![Non-glitched](https://cloud.githubusercontent.com/assets/6077838/21030106/dd550f1a-bdad-11e6-93f2-1ab006713c83.png)
![Glitched](https://cloud.githubusercontent.com/assets/6077838/21030101/d5c22404-bdad-11e6-8181-5841957848c3.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
without the physical sample its difficult to comment on actual behaviour and comparing the above outputs just confirms that when scaled slightly differently the characters will align or miss pixel boundaries.
As far as I can tell this is unwanted but natural behaviour when fonts are anti-aliased at very slightly different percents.

**Comment by kjk** [comment]
Needs a sample document that shows the problem.
