### ISSUE TITLE
Tabs lost if closed incorrectly

### ISSUE THREAD

**Issue by harvcode** [sumatrapdfreader/sumatrapdf#684]
The tabs of previous pdfs are stored correctly if I close the program normally, however if my computer crashes for example all tabs are lost. It should remember the tabs even if the program is closed incorrectly, as web browsers do.

**Comment by NicolBolas** [comment]
Other situations that cause lost of tabs include Windows shutting down. As it often does to update, usually at night with nobody to stop it. This means every time Windows updates, you lose whatever you had open.

**Comment by kjk** [comment]
This has been fixed for the case of windows restart.

**Comment by TuggyNE** [comment]
Actually, it's apparently been fixed even for the case of an unexpected system hang and hard reset, as I inadvertently discovered today. Many thanks for not making me look up two dozen assorted PDFs to reopen!
