### ISSUE TITLE
whe I go to read some epub files, the background of the aplication it become pink

### ISSUE THREAD

**Issue by pavlouser** [sumatrapdfreader/sumatrapdf#689]
Only happens me with epub files, here one capture http://fotos.subefotos.com/026e3a29d52f4ff7f9adef07e6d26a5co.jpg 

Help, my virility it will be complicated!

**Comment by aadhilkh2010** [comment]
goto settings->advanced options ..... Here u see the content of setting file...Change the background color to whatever u want in EbookUI section.

# For documentation, see http://www.sumatrapdfreader.org/settings3.2.html

MainWindowBackground = #80fff200
EscToExit = false
ReuseInstance = false
UseSysColors = false
RestoreSession = true

FixedPageUI [
	TextColor = #ffffff
	BackgroundColor = #000000
	SelectionColor = #f5fc0c
	WindowMargin = 2 4 2 4
	PageSpacing = 4 4
]
EbookUI [
	FontName = Georgia
	FontSize = 12.5
	TextColor = #000000
	BackgroundColor = #ffffff
	UseFixedPageUI = false
]

**Comment by GitHubRulesOK** [comment]
@kjk 
I suggest this is no longer an issue and can be closed

**Comment by kjk** [comment]
Closing as per suggestion.
