### ISSUE TITLE
new command line option: -ini 'path to settings-file'

### ISSUE THREAD

**Issue by gschenck** [sumatrapdfreader/sumatrapdf#69]
For usecases as in #67 or to have several sessions of opened files it would be nice to give the path of the settings file at the command line or in a desktop shortcut.

**Comment by zeniko** [comment]
Thanks for the suggestion. I wouldn't mind adding something along the proposed line, however in the slightly more general form of `-appdata <path to settings folder>` (or `-profile <path to settings folder>`).

**Comment by gschenck** [comment]
Thanks, works as intended!
