### ISSUE TITLE
How to populate values by looping the labels in a table?

### ISSUE THREAD

**Issue by paing16** [sumatrapdfreader/sumatrapdf#691]
<img width="559" alt="problem" src="https://cloud.githubusercontent.com/assets/24623591/21287778/38972e9c-c4ae-11e6-9d93-053ed35a45d3.PNG">

I just need to know for the first 2 columns. I know I need to loop it but I am not sure how to loop it in a table with labels.

**Comment by kjk** [comment]
Not sure what does it have to do with Sumatra.
