### ISSUE TITLE
Не отображается содержимое PDF-файла

### ISSUE THREAD

**Issue by alexeev1983** [sumatrapdfreader/sumatrapdf#692]
https://yadi.sk/i/6W1pan6q33wq4A

**Comment by VictorVG** [comment]
И чего проверять? Файл не найден. Удалён или линк слетел.
Thats test? File not foun on Yandex Disk - is deleted or not shared.

**Comment by alexeev1983** [comment]
Вот новая ссылка на файл: https://yadi.sk/i/HWTG5obj3AGvz7

**Comment by alexeev1983** [comment]
В Sumatra PDF данный файл отображается как белый чистый лист....

**Comment by VictorVG** [comment]
Fixed in Git 0b64820549 

![1](https://cloud.githubusercontent.com/assets/906886/22181803/eefc8292-e0a4-11e6-882d-b877362778be.png)

Забирайте в удобной для вас сборке архивом:

  [**SumatraPDF v3.2 Git-0b64820549 Win32/Win64, P4/AMD64, MS VC++ 2015**](https://yadi.sk/d/v57misV5uY8Be) _last modified is Sun Jan 22 13:21:50 +0300 2017_

 [ **SumatraPDF x86 & x64 Combine v3.2 Git-0b64820549, P4/AMD64, MS VC++ 2015**](https://yadi.sk/d/HXrA31tR32HSxZ)  _last modified is Sun Jan 22 13:21:57 +0300 2017_

эти ссылки специально сделаны постоянными - при любых обновлениях обновляется содержимое архива так, чтобы сервис не снимал с файлов статус "публичный" (такая особенность у Яндекс Диска есть - при обновлении непрерывных архивов или замене файлов статус "публичный" с файла снимается).

**Comment by alexeev1983** [comment]
Спасибо огромное)))

**Comment by VictorVG** [comment]
Не за что. Думаю что данный баг можно закрыть как исправленный.

**Comment by alexeev1983** [comment]
Виктор, доброе утро! Обнаружил, что изначальный PDF-файл так и не открывается....Можете проверить? 22.01.2017, 16:06, "Виктор" <notifications@github.com>:Не за что. Думаю что данный баг можно закрыть как исправленный.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by VictorVG** [comment]
Не вопрос, давайте файл. Я ведь смотрел на вашем примере. Возможно он был повреждён, либо настройки...

**Comment by alexeev1983** [comment]
Файл вложил в письме...... 23.01.2017, 22:57, "Виктор" <notifications@github.com>:Не вопрос, давайте файл. Я ведь смотрел на вашем примере. Возможно он был повреждён, либо настройки...—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by VictorVG** [comment]
С гита письма ходят плохо, а ваш, аттач не пришёл.

**Comment by alexeev1983** [comment]
На какую почту вам переслать файл?


24.01.2017 17:59, Виктор пишет:

**Comment by VictorVG** [comment]
Можете кинуть линк через YD на vic4935 иначе улетит в спам, а его объём в последние дни зашкаливает - явно кто-то сплавил мои данные спамерам... :mad:

**Comment by alexeev1983** [comment]
Ссылка на файл через Яндекс-диск устроит?)


24.01.2017 20:22, Виктор пишет:

**Comment by alexeev1983** [comment]
https://yadi.sk/i/hFN6oM9A3AhPmQ - получили ссылку?!


24.01.2017 20:22, Виктор пишет:

**Comment by VictorVG** [comment]
Только что забрал. Вы этот файл не удаляйте, но на данном экземпляре PDF и у меня только белый фон, то самое и в официальном [**Artifex GSView 6.0 Beta**](http://www.gsview.com/downloads.html) собранном с MuPDF Version 1.7a 64 bit и Ghostscript DLL: GPL Ghostscript GIT PRERELEASE 9.19 64 bit. У меня стоит Ghostscript 9.20 64 bit:

![1](https://cloud.githubusercontent.com/assets/906886/22260166/38e7c71a-e279-11e6-91f0-4703d5dcc567.png)

Файл открывается в аддоне PDF View 1.6.481 DEV в SeaMonkey 2.46 (аддон использует HTML5), но кроме SumatraPDF его не может прочитать и STDU View v1.6.375:

![2](https://cloud.githubusercontent.com/assets/906886/22260554/b000d188-e27a-11e6-8fe8-5e6e9418d6da.png)

Я сейчас у приятелей в типографии его смотрел - Iceni Infix v7.xx при попытке его открыть аварийно завершается с предложением отправить крэш-репорт. Так что это файл так сделан, и видимо специально. (?)

Так что тут SumatraPDF не виновна, а причина в кривой реализации экспорта в компоненте FastReport для среды Дельфи. В мануале для данного компонента версии 4.6 есть только одно указание:

_Особенности экспорта: RichText объекты экспортируется как графические объекты._

а как реально они сделали трудно сказать, но поскольку GhostScript не может прочитать сформированные им документы (это и есть причина белого листа на экране),  редактор Iceni Infix PDF на нём падает с AV:

Infix caused an Access Violation (0xc0000005) 
in module Infix.exe at 0023:00834b5c.

Exception handler called in ExceptionAttacher.cpp - AfxWinMain.
Iceni Infix v7.1.1
Last PDF Opened - SESB_122502203_2016_12.pdf
Build:  v7.1.1:2016-11-16-10.38 

Write to location 00000000 caused an access violation.

Context:
EDI:    0xfffffdb8  ESI: 0x02f4e044  EAX:   0x01fffffb
EBX:    0xffffffff  ECX: 0x00000000  EDX:   0x00000038
EIP:    0x00834b5c  EBP: 0x0018ee40  SegCs: 0x00000023
EFlags: 0x00010a02  ESP: 0x0018edfc  SegSs: 0x0000002b

, а это значит не программы виноваты, а исходный файл отборно кривой....

**Comment by alexeev1983** [comment]
Ужас какой-то......файл не стану удалять....2 вьюера, которые точно открывают данный файл: adobe reader x11 (dc)и PDF-XChange Viewer  24.01.2017, 23:46, "Виктор" <notifications@github.com>:Только что забрал. Вы этот файл не удаляйте, но на данном экземпляре PDF и у меня только белый фон, то самое и в официальном Artifex GSView 6.0 Beta собранном с MuPDF Version 1.7a 64 bit и Ghostscript DLL: GPL Ghostscript GIT PRERELEASE 9.19 64 bit. У меня стоит Ghostscript 9.20 64 bit:Файл открывается в аддоне PDF View 1.6.481 DEV в SeaMonkey 2.46 (аддон использует HTML5), но кроме SumatraPDF его не может прочитать и STDU View v1.6.375:Я сейчас у приятелей в типографии его смотрел - Iceni Infix v7.xx при попытке его открыть аварийно завершается с предложением отправить крэш-репорт. Так что это файл так сделан, и видимо специально. (?)Так что тут SumatraPDF не виновна, а причина в кривой реализации экспорта в компоненте FastReport для среды Дельфи. В мануале для данного компонента версии 4.6 есть только одно указание:Особенности экспорта: RichText объекты экспортируется как графические объекты.а как реально они сделали трудно сказать, но поскольку GhostScript не может прочитать сформированные им документы (это и есть причина белого листа на экране), редактор Iceni Infix PDF на нём падает с AV:Infix caused an Access Violation (0xc0000005)in module Infix.exe at 0023:00834b5c.Exception handler called in ExceptionAttacher.cpp - AfxWinMain.Iceni Infix v7.1.1Last PDF Opened - SESB_122502203_2016_12.pdfBuild: v7.1.1:2016-11-16-10.38Write to location 00000000 caused an access violation.Context:EDI: 0xfffffdb8 ESI: 0x02f4e044 EAX: 0x01fffffbEBX: 0xffffffff ECX: 0x00000000 EDX: 0x00000038EIP: 0x00834b5c EBP: 0x0018ee40 SegCs: 0x00000023EFlags: 0x00010a02 ESP: 0x0018edfc SegSs: 0x0000002b, а это значит не программы виноваты, а исходный файл отборно кривой....—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by VictorVG** [comment]
Traker открывает, после правки в его редакторе и суматра документ [SESB_122502203_2016_12_edited.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/729717/SESB_122502203_2016_12_edited.pdf) читает:

![5](https://cloud.githubusercontent.com/assets/906886/22291821/48ca2808-e319-11e6-91eb-646588499a99.png)

и Инфикс не валится:

![1](https://cloud.githubusercontent.com/assets/906886/22291834/5f6506c8-e319-11e6-83a6-6d0305248ac3.png)

. А причина как я вам и сказал - это не настоящий PDF:

![7](https://cloud.githubusercontent.com/assets/906886/22291867/8fe7b19c-e319-11e6-9c7d-7d73f1949c0b.png)

 а архив картинок с некорректным PDF заголовком:

![6](https://cloud.githubusercontent.com/assets/906886/22291877/984f5f7e-e319-11e6-9b77-5cb7f7ca371e.png)

у меня в Far через ассоциации вызывается довольно удобная утилита (хотя и не всё читающая, особенно кириллицу - родной язык её автора японский) [**xdoc2txt**](http://ebstudio.info/home/xdoc2txt.html) один из лучших консольных конверторов для просмотра документов - и он не берёт оригинальный документ:

![2](https://cloud.githubusercontent.com/assets/906886/22291970/22518d5a-e31a-11e6-9e90-3ad16f9a4c14.png)

а в хексе видим, что xdoc2txt не смог декодировать этот контейнер - по адресу 0х00000000 он вывел код 0x0A обозначающий EOF (End Of File):

![3](https://cloud.githubusercontent.com/assets/906886/22292014/5d7e451c-e31a-11e6-9b62-af733dac668d.png)

ну а если файл исправить в PDF-XChange Editor то xdoc2txt его прочитает:

![8](https://cloud.githubusercontent.com/assets/906886/22292256/73486610-e31b-11e6-922a-ec50db08087e.png)

Файлы с некорректной структурой PDF читают некоторые программы, например Traker Software PDF-XChange Pro который при его редактировании (я убрал там личные данные плательщика) сохраняют его с восстановлением PDF-разметки что делает их читаемыми всеми, но это не обязательно. Adobe Acrobat/Reader, Traker Software PDF-XChange Editor/Viewer в таком случае отыскивают в структуре контейнера изображения и выводят их на экран, а MuPDF на которой построена SumatraPDF проверяет  документ на соответствие стандартам разметки PDF и спецификациям языка Post Script на которых те построены а т.к. обе группы стандартов были нарушены при создании документа то и выводит на экран пустую страницу что и предписано спецификациями стандартов.

**Comment by alexeev1983** [comment]
Отсюда следует, что лучше бы я заказывал в бумажном виде данную 
платежку....либо использовать PDF-XChange PDF Viewer......

Нет слов....спасибо огромное, что смогли объяснить что да как....;-)


25.01.2017 18:39, Виктор пишет:

**Comment by VictorVG** [comment]
Вот и я потому вчера отказался от похожего предложения телефонистов - пусть почтой бумагу пришлют, чем после мучится с её распечаткой.
