### ISSUE TITLE
Possibility to rename tabs instead of having the file name?

### ISSUE THREAD

**Issue by PJRay** [sumatrapdfreader/sumatrapdf#693]
I often have five or so documents open, and they often have duplicate names - say two main.pdf and three body.pdf documents (from different directories, of course). 

Would it be possible to add a feature where I can right-click on the tab, and get an option to rename the name shown on the tab? Possibly even with the program remembering the name for the file next time it is opened?

I'm thinking that my two tabs of 
- main.pdf 
- main.pdf

would instead be called something like

- Doc 2016 [main.pdf]
- Doc 2017 [main.pdf]

or whatever I might feel like renaming them.

**Comment by kjk** [comment]
I suspect people would expect this to rename the file itself (which you can already do from menu), so no plans to do that.

**Comment by AVR3331** [comment]
Too bad it is not possible to rename the tabs as part of their reading in Sumatra, without modifying the original files.
Alternatively, provide a display of file names in the tabs on multiple lines (over more height).
