### ISSUE TITLE
看图

### ISSUE THREAD

**Issue by GoGoogle** [sumatrapdfreader/sumatrapdf#695]
![image](https://cloud.githubusercontent.com/assets/9440508/21451401/e4926696-c939-11e6-855c-dd08e53c0a8d.png)

这是同一个文件，Adobe的渲染明显好一些。

sumatrapdf该如何调整才能达到相同效果？

**Comment by Jokder** [comment]
![haimiao](https://cloud.githubusercontent.com/assets/6039742/21451319/467126c8-c939-11e6-9c7a-791f59fc0194.jpg)

**Comment by Jokder** [comment]
![pdf-1](https://cloud.githubusercontent.com/assets/6039742/21451343/7050b74c-c939-11e6-9972-9e65f2740bbc.png)

**Comment by kjk** [comment]
can't do anything without having access to the document in question.

**Comment by GoGoogle** [comment]
[防落梁混凝土纵向挡块.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/670986/default.pdf)
thank u bro,this is my source pdf document.pictures in my pdf looks good with adobe,but it's dim in this.
