### ISSUE TITLE
Feature request: Close program when last tab is closed

### ISSUE THREAD

**Issue by jetelina** [sumatrapdfreader/sumatrapdf#697]
Hi,
I would like to have feature that when I close last one tab it would close whole program. Something like ExitOnLastTabClose.

When you have multiple PDFs open in tabs, you close then one by one and after closing last one you still need to click X to close main program. This may save click to people.

Thank you

Note: I have searched for this topic and it looks that Mitch Pemberton already requested this feature
http://forums.fofou.org/sumatrapdf/topic?id=2100384

**Comment by kjk** [comment]
It's really not that big of a deal to Alt-4 or click. Adding more preferences has a cost in complexity of the code and making other preferences harder to find.

**Comment by kuon** [comment]
This is a major pain for me, and currently is slow down my workflow a lot.

**Comment by kuon** [comment]
I realized that I can close the program with ESC when enabling it in the advanced preferences. So it works for me, cheers!
