### ISSUE TITLE
pdf-write.c, line 2075

### ISSUE THREAD

**Issue by Romeoly** [sumatrapdfreader/sumatrapdf#698]
When I try to compile SumatraPDF, it stops at ".\mupdf\source\pdf\pdf-write.c, line 2075", complaining about unsupported characters in the current code page (CP936).

It must be caused by **fprintf(opts->out, _"%%\316\274\341\277\246\n\n"_);**
I cannot figure out why and how I can fix it.

**Comment by kjk** [comment]
Use an English version of Visual Studio.

**Comment by Romeoly** [comment]
@kjk Thank you so much. 

I changed to English version, but it didn't work.  
IMHO, I guess it might be caused by VS2015. I changed 
**fprintf(opts->out, "%%\316\274\341\277\246\n\n");**
to its hex equivalence
**fprintf(opts->out, "%%\xCE\xBC\xE1\xBF\xA6\n\n");**
And it worked fine. 

It is interesting to me. I changed the language back to Chinese, and it still works fine.

I don't know why, and I can even tell whether such a modification is correct.
