### ISSUE TITLE
Unsupported URL Protocol Handlers

### ISSUE THREAD

**Issue by MFrie** [sumatrapdfreader/sumatrapdf#70]
**Problem:** Links with URL protocols other than "http", "https" or "mailto" do not seem to be supported. Tested with "ftp://" (File Transfer Protocol), "callto://" (Softphones / Skype) and "notes://" (IBM Lotus Notes).
![pdf_url_protocols](https://cloud.githubusercontent.com/assets/9334610/5817696/cb819f06-a0ae-11e4-8fbc-be02c9b05ec9.png)
**Recommendation:** SumatraPDF should not limit the supported URL protocols but should leave handling to the operating system or default browser.

**Comment by zeniko** [comment]
Certain URL protocols supported by Windows Explorer are dangerous to the point where a malicious document can trick a user into accidentally running arbitrary code. For security reasons, we thus don't support arbitrary URL protocols but only the most common and best tested ones (even FTP doesn't no longer belongs to these).

Should you encounter URLs with a less common protocol, you've currently got two work-around options:
* right-click the link, copy the URL and paste it into whatever is capable of handling it
* use [sumatrapdfrestrict.ini](https://raw.githubusercontent.com/sumatrapdfreader/sumatrapdf/master/docs/sumatrapdfrestrict.ini) and modify it to enable the protocols for which you need support
