### ISSUE TITLE
Number of copies in print screen doesn't work

### ISSUE THREAD

**Issue by mdureau** [sumatrapdfreader/sumatrapdf#700]
I am in a Windows 7, 64-bit environment and am using Sumatra PDF Version 3.1.2, 64-bit. When I try to print multiple copies of a .pdf file using the Number of Copies selector, I am only getting one copy printed regardless of the number I select. (Note: I had the same problem with Version 3.1.1 and upgraded hoping it solve the problem but it didn't.)

**Comment by kjk** [comment]
I don't know what is "Number of Copies" selector you're referring to.

**Comment by mdureau** [comment]
When I open a .PDF file in Sumatra and want to print it, I click on the Printer icon and get a Print screen with various options. One of those options is to select the Number of Copies of the file I want to print. As I explained, no matter what number greater than 1 is selected, only one copy of the file is printed.

Sent from my HTC

----- Reply message -----
