### ISSUE TITLE
Add support for varying DPI

### ISSUE THREAD

**Issue by ponchofiesta** [sumatrapdfreader/sumatrapdf#705]
Hi,
currently SumatraPDF works good if you set display scaling to e.g. 150%. But if you use varying scaling like I do, than you come into trouble. Think about two monitors, maybe a notebook with 150% scaling and a monitor with 100%. If you only use one at the same time, Sumatra looks sharp. But the sidebar width is wrong as it is calculated in pixel, not in a relative unit.
And if you use both monitors at the same time Sumatra is blurred on one of them in Windows 10. But Windows 10 supports it. Firefox and Chrome are working great with different scalings. They switch on the fly when dropping a window to another monitor. This is a Windows 10 feature AFAIK.

So please add better support for varying scalings.

And here is a blog post by Microsoft addressing this issue in general:
https://blogs.technet.microsoft.com/askcore/2016/08/16/display-scaling-changes-for-the-windows-10-anniversary-update/

An article describing how to write DPI aware applications:
https://msdn.microsoft.com/de-de/library/windows/desktop/dn469266(v=vs.85).aspx

Maybe this is related:
https://github.com/sumatrapdfreader/sumatrapdf/issues/441

**Comment by kjk** [comment]
Unfortunately I have no way to test with 2 monitors with 2 different DPIs.
