### ISSUE TITLE
Feature Request: Additional Keybindings for "go back"/"go forward" commands

### ISSUE THREAD

**Issue by jjokella** [sumatrapdfreader/sumatrapdf#706]
Hello,

as a frequent user of the **Alt+Right** / **Alt+Left** keybindings, I think it would be great to have additional keybindings for these commands, which allow my hands to stay in keyboard-position.

I am thinking of something like:
- **h**  _go back_
- **l**  _go forward_

Has this been considered? (Probably yes, but I would still be interested in the reasons not to do this)

I found a similar issue (but requesting toolbar support as solution): #657

**Comment by kjk** [comment]
Those are too easy to trigger by accident.
