### ISSUE TITLE
sumatra opens multiple past pdf windows randomly

### ISSUE THREAD

**Issue by ouchSumatra** [sumatrapdfreader/sumatrapdf#707]
Trying to remove &re-install but won't remove reader.. also just came acoss some random script
variating in notepad.. I have no idea how that came up.. just killed it fast..
Norton quick scan shows nothing unusual 
Going to rein-stall shortly after reboot... but doubt if i will get a clean install if some is still left..

**Comment by kjk** [comment]
I don't understand the issue.
