### ISSUE TITLE
Print Usabilty

### ISSUE THREAD

**Issue by fstaubach** [sumatrapdfreader/sumatrapdf#708]
When printing a PDF Document with it's own numeration (Latex Document, where Front, TOC etc. are in roman numbers and the actual content in arabien numbers) you don't have any idea which page is selected on the print dialog. For Adobe Reader e.g it counts the own pdf's numeration. Obviously Sumatra counts the page by its own numeration (starting from the first page till the end)
For the user, even for an experienced one it is not clear which pages are selected. So you waste a lot of paper if you want to print.

I would very appreciate it, if there is any information in front of the printing dialog so that you know, which page is getting selected by entering a number. I would recommend to use the Adobe System: Using the pdf's numeration per default. If you want to use the page number then use brackets.
If not I would be also already very happy if I get at least any information!

**Comment by kjk** [comment]
Unfortunately that would require custom print dialog which is way too much work.
