### ISSUE TITLE
Question: Git-21627370d7 is have problem on window Frequently Read - all items on this window not work. This is my error?

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#709]
[**Git-21627370d7**](https://github.com/sumatrapdfreader/sumatrapdf/commit/21627370d7a483ec445f33c450dbc462af8efe37) is have problem on window Frequently Read - all items on this window not work, but on v3.2 Git-8307b6c431 I can use MsClick for start any operation's. In Git-21627370d7 I can only use SumatraPDF main menu. 

Question - is my build error? I attached builded copy for check. IDE VS 2015 Update 3.

[**SumatraPDF-Git-21627370d7.zip**](https://github.com/sumatrapdfreader/sumatrapdf/files/721618/SumatraPDF-Git-21627370d7.zip)

**Comment by VictorVG** [comment]
Git-36559914a6 also have this phenomen. I test x86 and x64 fresh build's...

**Comment by VictorVG** [comment]
Maybe I'm wrong, but I think that the mouse messages in this window will not come because of what it was not manageable.

**Comment by kjk** [comment]
Fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/0b648205491cd948b487ad73ddc6f07baf3ac7bf

**Comment by VictorVG** [comment]
Big thanks. Test is Ok! Frequently Read window is woking success.
