### ISSUE TITLE
PDF printing from the command line does not return errors

### ISSUE THREAD

**Issue by LRFV** [sumatrapdfreader/sumatrapdf#71]
I use the following command to print PDF

d:\SumatraPDF.exe -silent -print-to "HP LaserJet Professional P1102w" D:\test.pdf

Result command line:
     Output => empty
     Error  => empty

It work fine, but if printer is not ready or the file is not available, the SumatraPDF application in silent mode does not return errors.
Is there any option to return this infomation of success or failure to print this file?

**Comment by zeniko** [comment]
SumatraPDF returns an error code in case of failure. In order to read it e.g. from the command line, run SumatraPDF.exe using START /WAIT and check the ERRORLEVEL afterwards:

    START /WAIT SumatraPDF.exe -silent -print-to "..." "..." & IF ERRORLEVEL 1 ECHO failure

Please see the documentation for START and ERRORLEVEL for further information.
