### ISSUE TITLE
Extremly tiny bookmarks font size on high DPI monitors

### ISSUE THREAD

**Issue by John500x** [sumatrapdfreader/sumatrapdf#710]
Hi, 
I use  Sumatra on 24" 3840x2160  resolution. PDF rendering is incredibly smooth but the Bookmarks are extremely tiny.  Any change in the monitor DPI settings in Windows 8.1 deteriorates at the same time Sumatra rendering quality (which seems to be based on DPI settings)  So I would desperately need to simply increase Bookmarks font size to around 200%. 

Other idea to circumvent the above problem would be an option for Sumatra to render PDFs basing on monitor native resolution set in Windows (independently of WINDOWS DPI settings). So I could set menu and bookmarks font size by Windows DPI settings without loosing rendering quality. Something like "Render PDFs for Monitor Resolution - Ignore DPI Settings"

Best regards,
John

**Comment by kflili** [comment]
Yes, this is the issue I also want to point out. When I drag the Sumatra to an extended 24-inchs monitor, the font size in Bookmarks becomes very tiny. 
Sumatra is very good pdf reader, Thanks for you guys hard work!

**Comment by GitHubRulesOK** [comment]
The font size for bookmaks can now be set using for example
TreeFontSize = 15

**Comment by kjk** [comment]
To note: this will be available in 3.3 and today can be had in pre-release builds https://www.sumatrapdfreader.org/prerelease.html
