### ISSUE TITLE
Add a shortcut for "Show Pages Continuously"

### ISSUE THREAD

**Issue by JohannesOehm** [sumatrapdfreader/sumatrapdf#712]
I am currently using SumatraPDF very often with normal papers as well as presentation slides. Therefore I use the "Show Pages Continuously"-Switch in the "View"-menu very often, and I would appreciate if you could add a shortcut for this purpose.

**Comment by sassjajc** [comment]
c currently toggles between continous/non-continous mode.

**Comment by JohannesOehm** [comment]
Great, thank you very much for letting me know. I see now that this shortcut is documented in the manual, which I haven't seen earlier. 
It would be still nice for other users to add the shortcut at the right side of the menu entry, since most of the other shortcuts are visible there.
