### ISSUE TITLE
Right-click file name in header for drop-down menu

### ISSUE THREAD

**Issue by firstmartyr** [sumatrapdfreader/sumatrapdf#713]
I can see a significant increase in functionality if something like a drop down menu was added to right-clicking the name of a file in the header (like in the tab view). A few options could be like the options given in the _File >..._ dropdown menu, such as:
> Rename
> Save as...
> Properties

But also, some other options would be really useful, such as 
> Open file location
> Open in new window
> Open with...

And also some really basic options could be added to the dropdown, such as _Close_

It would be wonderful to hear any feedback about my ideas, such as additional features that could be added to this menu to increase functionality.

**Comment by GitHubRulesOK** [comment]
@kjk related to https://github.com/sumatrapdfreader/sumatrapdf/issues/1188

**Comment by kjk** [comment]
I've added properties, show in folder, open in new window to context menu.

Not yet convinced about rename / save as / open with.... Will think about it.
