### ISSUE TITLE
Icons issue

### ISSUE THREAD

**Issue by drweb86** [sumatrapdfreader/sumatrapdf#716]
Hello guys

Thanks for your amazing tool. I'm using it sooo often.
Recently i looked at toolbar and saw some strange things
![default](https://cloud.githubusercontent.com/assets/4712173/22618519/9f28afca-eaef-11e6-9bfd-05eb9e87a4ea.png)

I'm on windows 10 x64.

**Comment by kjk** [comment]
This has been fixed in 3.1.2
