### ISSUE TITLE
Option to collapse bookmarks

### ISSUE THREAD

**Issue by eduardmanas** [sumatrapdfreader/sumatrapdf#718]
It would be nice if we could collapse all bookmarks in one go.

A document is usually structured in Chapters, and each chapter into several sections and subsections. 

When Sumatra PDF opens a document, the bookmark tree is fully expanded.  Depending on the document structure, the bookmark tree might be many levels deep.  This makes it hard to understand the document structure. 

Ideally, we should have a way to collapse these bookmarks, so we can work at Chapter level. When I then expand on a chapter, I would like to see the major sections of the chapter. If I then expand on a section, then I would like to see its subsections, and so on.

Many thanks

**Comment by dale-roberts** [comment]
Hi Eduard, I also wanted this, and was ready to roll up my sleeves and do some coding, but I went to look at the source code, and.... it is already there!!

To collapse ALL bookmarks (regardless of what level you are currently on, and even if there is not a single top-level bookmark), press SHIFT-NumpadDivide (the slant/forward-slash key). It MUST be the divide key on the the numeric keypad. The regular divide key will not work.

To re-expand ALL bookmarks, SHIFT-NumpadMultiply (the asterisk/star key).

For those searching, this is also related to request #83, from way back in 2015, which is also not marked as closed, even though the feature has been added (but perhaps not documented). I have pasted the pertinent code in response to that issue.

Hope this helps.
dale

**Comment by eduardmanas** [comment]
Hi Dale, thanks very much for the tip! 

Yes, the shortcuts Shift + / and Shift + * work as expected.  I am happy with that!

It would however be nice if there was a menu item for this.  And here I am thinking about the average user.  Shortcuts are not as easy to use as buttons/menu items, and to be fair, not very well documented either.

**Comment by digitaltrousers** [comment]
I'd like the default behaviour to be configurable, perhaps in %APPDATA%\SumatraPDF\SumatraPDF-settings.txt. I would prefer Eduard's suggestion as default behaviour. Also my laptop doesn't have a numpad so the keyboard shortcut is of limited use :)

**Comment by GitHubRulesOK** [comment]
The default is once they are opened and "remember these settings for each document" is true for them to re-open at the same level they were closed so for closure at level 1 
TocState = # # …
where # can be a number
The default of all open resets and deletes the different entries
So when first opened OR closed with all expanded there is no status for the TOC on file opening
Bookmarks can vary widely depending on the author, thus for some with a single root it may make sense to open one level up, but for those without a root it would be different, the one known layout that can NOT vary between sources is open ALL (if available !) perhaps the reason that is the default.

**Comment by PierreSaminadin** [comment]
Hi there
thanks for your work,, SumatraPDF is very nice.

as many user i have a laptop with no numpad so i can't use this shortcut
and i have a french keyboard.
it would be nice to be able to customize these shortcut or to use a FUNCTION key.

Best regards

Pierre

**Comment by GitHubRulesOK** [comment]
@kjk can we agree the rightclick and enter key enhancements will be kept in full release ?

**Comment by kjk** [comment]
Yes. To sum up:
* `Enter` toggles the collapsed / expanded state of currently selected node. When at root of tree, it collapses / expands the whole tree
* there's a context menu on bookmarks tree with Expand / Collapse items

**Comment by GitHubRulesOK** [comment]
@kjk you may note the open flag on a pull request showing should also have now been addressed
