### ISSUE TITLE
Rendering issue w/ layers in attached PDF

### ISSUE THREAD

**Issue by mqudsi** [sumatrapdfreader/sumatrapdf#719]
Hello all,

The attached PDF has some transparency and z-index issues when loaded in Sumatra PDF, but displays fine in other viewers.

I'm sorry, but I do not have much more technical information to provide.
[17BiFold0204-v03-A.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/758111/17BiFold0204-v03-A.pdf)

I am also unable to verify any of the open bugs already cover this rendering issue. My profuse apologies in advance if that is the case.

**Comment by jiulun** [comment]
MuPDF has a correct display. Sumatra PDF may need to merge the latest version of MuPDF.

**Comment by GitHubRulesOK** [comment]
@kjk was closed by recent updates to 1.16
![image](https://user-images.githubusercontent.com/12754913/71737402-72b34e80-2e4b-11ea-8bb2-b49361885b97.png)
