### ISSUE TITLE
IFilter Installation

### ISSUE THREAD

**Issue by habathcx** [sumatrapdfreader/sumatrapdf#72]
I found a document mentioning you can install the PDF iFilter by selecting a checkbox in the advanced options. It would appear it is no longer available in version 3.0. I had to manual regsvr32 the pdffilter.dll.

http://blog.kowalczyk.info/article/95h6/SumatraPDF-14-released.html

Is there a plan to add this option back in the future? We may be considering suggesting SumatraPDF as our default PDF iFilter, but ease of installation would be ideal.

Edit:

It looks like this commit hides it for OS with 64bit.

https://github.com/sumatrapdfreader/sumatrapdf/commit/ace4ef3ff3f495bd281185f13023f0aaa074bd59

This may be because the Windows Search process would run as a 64bit process.. but I think the option to install the 32 bit iFilter should be available as other products may wish to use it.

Thanks!

**Comment by zeniko** [comment]
This is likely a duplicate of https://code.google.com/p/sumatrapdf/issues/detail?id=1313 : You're using a 64-bit OS under which the current 32-bit IFilter won't work (and thus isn't offered by the installer).

**Comment by habathcx** [comment]
The 32-bit iFilter works fine on a 64-bit system as long as the process you are invoking the iFilter from is pinned to 32-bit. (Ideally Microsoft should run multiple hosting processes in 32 and 64 bit and try the other if one doesn't work). My indexing engine does this and it works well for working with random iFilters for an assortment of file types.

Just wondering if the option could be added back, maybe with a note that says "Install 32bit iFilter" or a warning that says 64bit windows search cannot use this ifilter.

Maybe an option to invoke the installer with /ifilter or something.. anything .. to make it easier than a manual regsrv32.

**Comment by zeniko** [comment]
Since most people won't be using a different indexing agent that Windows', having an "Install 32-bit IFilter" option seems more confusing than helpful to me. What should work, though, is invoking the installer with `/s /opt pdffilter` (invoke it with `/?` for a full list of available command line options).

**Comment by habathcx** [comment]
Yeah, I suppose you are correct. These installer options however, will make a world of difference for us, thanks for the info. We are going to start suggesting our customers use your PDF viewer in place of Adobe 11, as their 64/32 bit iFilters appear to be completely non-functional anymore.

Thanks for your help!
