### ISSUE TITLE
"Go to" menu addition 

### ISSUE THREAD

**Issue by wfjer** [sumatrapdfreader/sumatrapdf#720]
Please consider adding the following actions to "Go to" menu:
- Next Document [Ctrl+Shift+Right Arrow]
- Previous Document [Ctrl+Shift+Left Arrow]

Note: These actions have been available through the mentioned shortcuts, but I guess many people haven't used these powerful commands.

**Comment by mouslee** [comment]
The shotcuts of that action are `Ctrl+Tab` & `Ctrl+Shift+Tab` at present.

**Comment by kjk** [comment]
This menu is already pretty big. Adding more items has a usability cost.
