### ISSUE TITLE
PDF rotation

### ISSUE THREAD

**Issue by sappavive** [sumatrapdfreader/sumatrapdf#721]
Hi,
I kindly ask to add the "rotate pdf" feature.
Thanks

**Comment by kjk** [comment]
We already support rotation in Sumatra.

If you mean adding a tool to modify the PDF files then we don't have plans for that. Sumatra is a reader, not an editor.

**Comment by GitHubRulesOK** [comment]
Adobe Acrobat EDITOR is needed to rotate one page as it should modify the file contents
Adobe Reader 9 rotates ALL single pages at the same time just like SumatraPDF does
![image](https://user-images.githubusercontent.com/12754913/78713276-eca71800-7911-11ea-8ca5-0ca2b81ce11e.png)

**Comment by GitHubRulesOK** [comment]
If you want to permanently rotate a page within limits yu can edit the file from within SumatraPDF
I have described adding a QPDF rotation script at 
https://forum.sumatrapdfreader.org/t/please-add-tool-for-rotating-pages-permanently/411/5
