### ISSUE TITLE
Area zoom tool

### ISSUE THREAD

**Issue by marccu** [sumatrapdfreader/sumatrapdf#722]
Hi,
I need a tool for zooming area on page.
Please add this option on toolbar. 

Thanks,
Regards

**Comment by wtustin** [comment]
I come from Acrobat and have found the zooming by CTRL ok. But it would be nice if Sumatra had this feature that I used all of the time.

**Comment by GitHubRulesOK** [comment]
SumatraPDF uses CTRL Marque zoom too. It is different to Adobe way of doing things.
Mark your area of zoom with CTRL & Left button. Here it is that green rectangle towards lower right

![image](https://user-images.githubusercontent.com/12754913/73897688-d4b60800-487e-11ea-81eb-c8bd00b00e3a.png)


**Now either use SumatraPDF Zoom key** <kbd>**+**</kbd> **or the + icon to move through zoom steps till it is as large as you want it.**  You can change the number of step sizes in settings if you need / want to.


![image](https://user-images.githubusercontent.com/12754913/73897970-bf8da900-487f-11ea-97c7-25623800d288.png)
 
**Finally, left click on the selection once with mouse to dismiss it.**
