### ISSUE TITLE
Buttons for Page Rotate

### ISSUE THREAD

**Issue by jitenderdogra** [sumatrapdfreader/sumatrapdf#723]
Please add buttons for page rotate clockwise and counterclockwise beside the zoom in and zoom out buttons. It is cumbersome to open the menu or having to press three buttons each time i want to rotate the page.

Thank you.

**Comment by ChesterCloud** [comment]
I agree with you. This function should be there.

**Comment by gschenck** [comment]
You can use the shortcut StrgShift+ for rotating clockwise or StrgShift- for rotating other direction.

**Comment by Petewg** [comment]
Indeed, that's an highly needed feature, especially for landscaped pages.
Maybe, it'd be even better adding an `auto-rotate` advanced setting 
(f.e.: AutoRotateLandscapePages = right )
Of course, such an option would require sumatraPDF  be able to recognize page orientation. 

PS. (like every more-than-two-keys-combination), current key combination for rotate `Ctrl+Shift++`  is quite unhandy/complex-to-remember.

PS.2. no matter what, SumatraPDF is great!

**Comment by Petewg** [comment]
FYI.
I've found undocumented (?) shortcuts for page rotation that are quite simpler than complex `Ctrl+Shift+<+/->`  combination.
 - Numeric keypad: `*` (VK_MULTIPLY) --> clockwise (90) rotation 
- Numeric keypad:  `/`  (VK_DIVIDE) --> counterclockwise (-90) rotation.

mutch easier to use/remember; perhaps it should be added in  [manual](https://www.sumatrapdfreader.org/manual.html)?

**Comment by Massedil** [comment]
It could also be great to have the ability to rotate the document in the right clic menu.

**Comment by GitHubRulesOK** [comment]
**The shortest buttons for rotate are** 
Anti-clockwise=<kbd>**[**</kbd> 
and clockwise <kbd>**]**</kbd>

**Comment by kjk** [comment]
Added rotate buttons to toolbar in https://github.com/sumatrapdfreader/sumatrapdf/commit/72d9a9418e224362461ddf7598ed8601fbcd2aa2

**Comment by GitHubRulesOK** [comment]
Just for fun I tried this with a comic book, whilst screen was rotated it works but @ 90 degrees mouse movement is awkward, (may work better for touchscreen users)
![image](https://user-images.githubusercontent.com/12754913/107294500-6b566f80-6a65-11eb-9683-f14c2d80e7d7.png)

**Comment by Petewg** [comment]
> 
> 
> Added rotate buttons to toolbar in [72d9a94](https://github.com/sumatrapdfreader/sumatrapdf/commit/72d9a9418e224362461ddf7598ed8601fbcd2aa2)

Good! thank you!
(I 'd like to try it, but [Daily builds ](https://www.sumatrapdfreader.org/dailybuilds.html) are 64 bits only, and currently I am on a 32bits machine. Hope we'll see soon a 32 bits pre-release).
