### ISSUE TITLE
Error loading C:\..\..\..\..\..\..\..\..\iframemsg

### ISSUE THREAD

**Issue by johanrm1** [sumatrapdfreader/sumatrapdf#724]
Hi! am on latest level (have also tried the portabel prerelease(32bit)). 
I can see the PDF-page for a very short moment and then the page is replaced by an all grey page with one centralized line only.  The line reads:
Error loading C:\\Users\ego\AppData\Local\Microsoft\Windows\INetCasche\IE\5CO0ESZ0\iframemsg
 
The attached file is the only one experiencing the trouble.  Works OK with Adobe Acrob rdr
 
Johan
[Städbolagett_iframemsg.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/778550/Stadbolagett_iframemsg.pdf)

**Comment by GitHubRulesOK** [comment]
NOT AN ISSUE (CLOSE)

ITS NOT A PDF FILE, ITS A LINK TO A SCRIPT if your browser is set to allow Adobe to open scripted links then it WILL work for you in Acrobat as if its a PDF.
I dont want Sumatra to open unknown insecure scripts the same way
 
 


<script>if(window.parent){window.parent.yui.fire('iframe-message', {"id":"774666a9-c3ae-6840-c927-c782e6354aa2","data":"eyJyZXN1bHQiOm51bGwsImVycm9yIjp7ImNvZGUiOiJFQy00MDAxIiwidmFsaWRhdGlvbkVycm9ycyI6WyJ2aXJ1cyJdLCJyZXF1ZXN0SWQiOiI2ZjllYzU4Yi03ZmIwLWQzOWUtMDFlZS1lYTAwMWYwMTAwMDAiLCJyZXNvdXJjZSI6Ii93cy9kb3dubG9hZC9tYWlsYm94ZXMvQC5pZD09VmpKLW9iWEswWlI4QWZpQ0MzUHdVU0cyRDNCbElwaGlfbFd1ZnRTUmlWNld2aVBoZlhhcy14SXJrOEhkY1Vvd2RJRFgvbWVzc2FnZXMvQC5pZD09QU41THlBb0FBRFI4V0tUT2pRZTBxTGxWNHFBL2NvbnRlbnQvcGFydHMvQC5pZD09Mi9yYXcifX0"});}</script>

**Comment by kjk** [comment]
This is not a PDF file.
