### ISSUE TITLE
command line print produces other output than printing by user dialog

### ISSUE THREAD

**Issue by tfinnah** [sumatrapdfreader/sumatrapdf#726]
[2186_001.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/788024/2186_001.pdf)

We want to use the Sumatra PDF for printing out PDF-documents that are coming from SharePoint.
When printing out the PDF-document by user Dialog with "c:\program files\sumatrapdf.exe 'c:\temp\example.pdf'" everything works fine after pushing the print-button.

When we do the same thing using the command line Options "c:\program files\sumatrapdf.exe -print-to 'Smart Label Printer 650' 'c:\temp\example.pdf'" we get another Output. It is much smaller.

See the enclosure. Is there anything we could do for getting rid of that? I tried several print-Settings (fit, noscale, zoom, ...), but nothing leads to success.

Many thanks for your answer(s), Thomas

**Comment by kjk** [comment]
Unfortunately I have no way of debugging why this might happen.
