### ISSUE TITLE
save-dialog - near to open-dialog

### ISSUE THREAD

**Issue by tomasherrmann** [sumatrapdfreader/sumatrapdf#73]
hi,
is there a possibility to get a start "save-dialog" icon near to the open-dialog icon? 
I´d rather need the save/save-under-dialog(!) - the opening is easy done by "enter" or dbl-click on a file list.
Tomas

**Comment by kjk** [comment]
We don't have plans to add more icons to the toolbar. See https://github.com/sumatrapdfreader/sumatrapdf/wiki/Toolbar-design

**Comment by tomasherrmann** [comment]
Thank you for your answer - and you are wright! I can use ^s instead. 
greetings, Tomas

We don't have plans to add more icons to the toolbar. See https://github.com/sumatrapdfreader/sumatrapdf/wiki/Toolbar-design
