### ISSUE TITLE
Crash when opening files (reopen 729)

### ISSUE THREAD

**Issue by Dharmainiciativ** [sumatrapdfreader/sumatrapdf#730]
We are talking about your assembly 10605, on it all of the above bugs are present. OS Windows 7 x64
Added video down https://cloud.githubusercontent.com/assets/10089507/23460782/1aa10ea2-fe98-11e6-9542-295f5f7bd238.gif

**Comment by Dharmainiciativ** [comment]
![2017-03-01 17_29_22-clipboard](https://cloud.githubusercontent.com/assets/10089507/23464133/eabe17ae-fea4-11e6-8d3c-46b60a072b60.png)
Release Dirk Paehl (from 26.02.2017), it shows the files and epub fb2 only the table of contents and images. The text does not show them.

**Comment by VictorVG** [comment]
@kjk

Bug "No title for any tab" and crash exist on Windows 7 SP1 x64, WINE HQ v1.5 - 2.1 DEV x86 and AMD64, but Your say 

> **I cant reproduce the invisible title** nor other crashes, so closing this one.

![1](https://cloud.githubusercontent.com/assets/906886/23468374/b87d70b6-feb1-11e6-8d64-c488e41bfe4d.png)
![2](https://cloud.githubusercontent.com/assets/906886/23468376/b88d5094-feb1-11e6-9e68-f8c82931519d.png)
![3](https://cloud.githubusercontent.com/assets/906886/23468378/b8ab1386-feb1-11e6-8850-1db92f968b7a.png)
![4](https://cloud.githubusercontent.com/assets/906886/23468377/b8aa883a-feb1-11e6-8473-67a48e997c6b.png)

maybe we'll not understand each other and you can not reproduce the conditions of the error which I confirmed yet about a half dozen people? Let's see what is behind these phenomena - statistics reproducibility says that we're missing something.

**Comment by VictorVG** [comment]
@kjk 

Do Your check MSDN for exist call on any OS over Windows 10?

**Comment by kjk** [comment]
I can see in my crashlogs that there 2 crashes, one when opening a file and one in some ebooks.

That being said, I couldn't repro the crashes myself.

What would help:
* please share the files that cause a crash
* if you have ability to compile the code yourself, please compile debug version, get the program to crash and post the callstack of the crash

As to missing tab text, please open a separate bug for this. I can't repro this but so far I've only been able to test on win 10, so it's possible it only happens on win 7.

**Comment by Dharmainiciativ** [comment]
Files on which there is a drop https://yadi.sk/d/1brf6pY33EtYCg
Sumatrapdfcrash https://yadi.sk/d/-qenWpYp3EtYgE

**Comment by VictorVG** [comment]
@kjk 

Ok!

**Comment by VictorVG** [comment]
Yes, SumatraPDF-prerelease-10607-64.exe on Win7 SP1 x64 also have Access Violation (write in address 0x00000000 on main thread, function is unknown for VS2010 debugger)  then open group's files (I use for this test file list : 02-05-2015.cbr, 4.pdf, Down.7z, SESB_122502203_2016_12.pdf, SESB_122502203_2016_12_edited.pdf, chart1.pdf, example.fb2, internals-en.epub, jul-2015.cbr, sdjvuspec.djvu, test.cbr, test.djvu, testcase_encrypt.pdf (password "123" is don't known for SumatraPDF)). 

Screenshots:

Crash screen, _notes: I don't know opening file name on this event_
![crash](https://cloud.githubusercontent.com/assets/906886/23517994/11cceec2-ff83-11e6-83f3-ee03a8995650.png)

Debugger screenshot for main threads:

![crash_2](https://cloud.githubusercontent.com/assets/906886/23518096/68f4729c-ff83-11e6-9ae6-d6c90002b2a9.png)

and added full crash kit included both screenshot, downloaded symbol cashe (.PDB), crash dump - [**Crash.7z**](https://www.upload.ee/files/6736390/Crash.7z.html) (upload.ee, HTTPS).

**Comment by kjk** [comment]
Fixed in https://github.com/sumatrapdfreader/sumatrapdf/commit/50ad6a08ab215cc49abf989e9d08f4801065815e

This was only happening when using fixed page ui for ebooks, which is why I had trouble reproducing it.

**Comment by VictorVG** [comment]
@kjk 

Big thanks! v3.2 Git-fbc1826d32 all my test executed w/o crash, tab title text display for all tabs. :+1:
