### ISSUE TITLE
missing tab text (Win 7, X64)

### ISSUE THREAD

**Issue by gschenck** [sumatrapdfreader/sumatrapdf#732]
since v3.2.10605 64 bit the tab text is missing.

![grafik](https://cloud.githubusercontent.com/assets/2298241/23503816/748a36dc-ff3d-11e6-976a-a037f54d9a76.png)

**Comment by Dharmainiciativ** [comment]
This is also observed with other files, such as tab title in absence of the user djvu files. Attached is a sample file https://yadi.sk/d/6kMMy28A3EtnnP

**Comment by sastools** [comment]
I'm also observing the same (missing tab titles / graphics) on this release on W7-64 bit.

**Comment by VictorVG** [comment]
OS Win7 SP1 x64

Then use my samples [**test.zip**](https://www.upload.ee/files/6736097/Test.zip.html) have screenshots:

![1](https://cloud.githubusercontent.com/assets/906886/23514597/d4d10eea-ff78-11e6-994f-c382e6dbbdda.png)
![2](https://cloud.githubusercontent.com/assets/906886/23514598/d4d5acd4-ff78-11e6-8e36-4bf31772537e.png)
![3](https://cloud.githubusercontent.com/assets/906886/23514599/d4d695c2-ff78-11e6-8fce-8133a9da92f1.png)
![4](https://cloud.githubusercontent.com/assets/906886/23514600/d4de6766-ff78-11e6-81cb-26d20f1e2e0f.png)

Then I use SumatraPDF-prerelease-10607-64.exe title text also missing for all tabs:

![5](https://cloud.githubusercontent.com/assets/906886/23518494/a8f6756a-ff84-11e6-8c74-a4b46d871a88.png)
![6](https://cloud.githubusercontent.com/assets/906886/23518495/a8fcd022-ff84-11e6-9802-6422e35002f0.png)
![7](https://cloud.githubusercontent.com/assets/906886/23518497/a8fed458-ff84-11e6-8537-080e48225e58.png)
![8](https://cloud.githubusercontent.com/assets/906886/23518496/a8fea6ea-ff84-11e6-8272-42bedfbbf900.png)

I see this bug in development build v3.2 Git-a9999f9dec (all source files not modified, build used VS 2015 Update 3, buld server have Windows SDK 7.0/7.1, 10).

**Comment by kjk** [comment]
Should be fixed in latest pre-release 10609 or later.

**Comment by VictorVG** [comment]
@kjk 

Big thanks! v3.2 Git-fbc1826d32 all my test executed w/o crash, tab title text display for all tabs. :+1:
