### ISSUE TITLE
Installer graphics are missing / blank on 3.2.10607

### ISSUE THREAD

**Issue by sastools** [sumatrapdfreader/sumatrapdf#733]
On latest installer (3.2.10607), the main installer graphics / text are missing on Window 7 64-bit version.

![sumatrapdf_10607_installer](https://cloud.githubusercontent.com/assets/13813498/23516086/ca85af0a-ff31-11e6-915d-4872d0b3a544.png)

**Comment by VictorVG** [comment]
Is know - https://github.com/sumatrapdfreader/sumatrapdf/issues/729#issuecomment-282849918 :)

**Comment by VictorVG** [comment]
Thanks!
