### ISSUE TITLE
Improve toolbar icons

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#734]
@blake-mealey continuing discussion from https://github.com/sumatrapdfreader/sumatrapdf/pull/731

> The icon pack I used (https://material.io/icons/) looks much better with transparency, but obviously I had to modify them to work with the BMP format. I wasn't able to determine whether it is possible to switch to an image format which does support transparency. If you know that it is possible and could point me in the right direction, I'd be happy to implement that before submitting that PR.

Currently we use standard toolbar control. It only supports .bmp files but it does support transparency (pixels RGB(0xFF, 0, 0xFF) in the .bmp image are transparent in the toolbar).

My wishlist is to stop using windows toolbar control and instead paint the icons in code, preferably using a textual vector format, which would give us transparency and good looking dpi scaling for free.

We already have code in SvgPath.cpp to parse a subset of SVG path expression and draw it using GDI+, so it should be easy to extract relevant parts of the icon from .svg file and use in Sumatra.

**Comment by blake-mealey** [comment]
Would moving away from the windows toolbar control also involve this stuff? (https://code.msdn.microsoft.com/windowsapps/CppWindowsOwnerDrawnMenu-a9888b0c, https://msdn.microsoft.com/en-us/library/windows/desktop/ms647558(v=vs.85).aspx#_win32_Creating_Owner_Drawn_Menu_Items)

I don't have any prior experience with these libraries but I'd love implement a custom toolbar that would allow for more customization and better looking icons.

**Comment by kjk** [comment]
As background, with CreateWindow* you can either create "raw" windows, where you have to provide your WndProc (a function that processes windows messages sent to a window). Then you draw into that window on WM_PAINT message.

Or you can create one of the custom controls, like menu control or toolbar control. Those are also windows but the os paints them, provides most of the low-level handling and eposes a nicer, high-level interface (where "nicer" being relative; it's less work that doing everything from scratch but the API to custom controls is not how we would write code today).

Some custom controls allow for certain levels of customization. The above articles describe how to modify the look of standard menu control (as complicated as it looks, it's much less work than re-implementing menus from scratch).

For toolbar control, I don't think it allows for enough paint customization so it has to be done from scratch. There are 2 possibilities.

1. Write HWND-based control, similar in spirit and functionality to standard toolbar control. See LabelWithCloseWnd.[h|cpp] for a template of such style and an implementation of a simple control in this style.

2. HWND-less implementation.

Instead of using a HWND (which has some limitations e.g. it's not easy to alpha-blend HWND onto its parent HWND), you can draw toolbar elements directly onto parent window.

For ebook view I've build src\mui to make it such style a bit easier. I'm pointing this only as a source of ideas, I think I overdid some things and might re-implement ebook view in a similar, but hopefully simpler system.

We already draw a bunch of custom stuff in Canvas.cpp and toolbar controls could be drawn directly in there (WM_PAINT of WndProcCanvasFixedPageUI).

Currently the structure of main window is:
HWND_frame
   HWND_toolbar <-- current toolbar
   HWND_canvas <-- where we draw the PDF document and some other stuff
(and a bunch of other HWND-based windows).

After the change it would be:
HWND_frame
  HWND_canvas <- toolbar would be drawn directly into hwnd canvas

Solution 1. is probably easier as you would basically replace toolbar custom control (which is hwnd) with another hwnd-based window that just paints different things into that space, like use icons from .png image or draw them from vector data using SvgPath.cpp).

**Comment by kjk** [comment]
Continuing toolbar discussion in relation to theming (from #898)

The improvements we want in toolbar:

**What**: allow customizing colors of the icon (background/outline) and scale icons better with dpi
**How**: instead of using toolbar control (which only allows bitmaps) do custom drawing using vector (i.e. scalable) shapes

**What**: modernize the icons
**How**: find a nice SVG icon set with free license (e.g. material design icons)

**What**: allow toolbar customizability (especially adding back/forward buttons as it's a frequent request) but in general we should be flexible enough to remove/re-arrange the icons
**How**: extend settings to allow defining toolbar

As far as icon drawing, I would steal what Chrome does. Supporting SVG natively is too much work. Chrome designed a much simpler, limited format for vector icons:
* https://cs.chromium.org/chromium/src/components/vector_icons/ 
* https://cs.chromium.org/chromium/src/chrome/app/vector_icons/
* https://cs.chromium.org/chromium/src/ash/resources/vector_icons/
* and a few more places

Code that parses that format:
* https://cs.chromium.org/chromium/src/ui/gfx/vector_icon_types.h
* https://cs.chromium.org/chromium/src/ui/gfx/paint_vector_icon.h
* https://cs.chromium.org/chromium/src/ui/gfx/paint_vector_icon.cc

For the icons we could use chrome icons or write svg -> simple format converter

So the order would be:
* implement parser for .icon files
* implement drawing of the icon into hdc/bitmap at a given resolution
* re-implement toolbar using vector icons

**Comment by blake-mealey** [comment]
So, to be clear, would this require a full new toolbar, or just rendering vector images into bitmaps and drawing them in the places the current bitmaps are drawn?

**Comment by kjk** [comment]
Either way would work.

**Comment by az4726** [comment]
Hi there, I've been using this Sumatra for a while and thought I'd try creating the toolbar vector icons. Have a look and let me know what you think. Hopefully this issue can finally be closed.

I've also included an updated PDF file icon as the old one looks quite dated, and there are also a couple of new program icon vectors which you can have a look at.

[Sumatra PDF Icons.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/3214762/Sumatra.PDF.Icons.zip)

**Comment by GitHubRulesOK** [comment]
@kjk 
almost there ? (I would like scaling option for **users preference** NOT one based on Microsoft idea of system dpi scale)

From the above in addition to one or two rotate buttons and changing next /previous to back /forwards

> What: allow toolbar customizability (especially adding back/forward buttons as it's a frequent request) but in general we should be flexible enough to remove/re-arrange the icons
> How: extend settings to allow defining toolbar

**Comment by Petewg** [comment]
@kjk
Hi,
any plan about toolbar customization (not aesthetically), with the ability to add custom buttons to easing execution of currently existing shortcuts (e.g. rotation of page) and/or other custom commands?

**Comment by kjk** [comment]
Let's consider it fixed by the new vector icons.

**Comment by juanvisbalco** [comment]
Have the new icons been released already?

**Comment by GitHubRulesOK** [comment]
@juanvisbalco 
The icons discussed here are in the viewer toolbar (and have been SVG since after 3.2 which was the last version where you could skin (change images and or resize/colour) your own bitmap icons

**Comment by juanvisbalco** [comment]
I'm on version 3.2 and this is what my toolbar looks like:
![image](https://user-images.githubusercontent.com/955241/101697853-86e1d180-3a46-11eb-9246-5715b1488689.png)

**Comment by GitHubRulesOK** [comment]
search for toolbar_11.bmp in github or user forum to see how those can be replaced, but I no longer build new ones as we have a different system in pre-release that is not currently user changeable (unless you compile your own full build)
