### ISSUE TITLE
Implement theming for changing look of Sumatra

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#736]
@blake-mealey continuing from https://github.com/sumatrapdfreader/sumatrapdf/pull/731

> Where should I put the various theme structs (light, dark, etc)? Should I keep the current theme stored in gGlobalPrefs->theme? It seems like that would mean it is still part of the preferences file, but I also do not know how else to save current preferences. I suppose there could be a theme string in gGlobalPrefs which saves the current theme, but then the actual theme struct should be easily accessible from everywhere else, and I do not know where I would store it.

For now I would just make them as globals in `Menu.cpp`, since they are switchable from menu.
```
struct Theme { };

Theme g_themeLight = { ... };
Theme g_themeDark = { ... };

#define THEME_COUNT 2

Theme *g_themes[THEME_COUNT] = {
    g_themeLight,
    g_themeRight
};
```

If it becomes big, theme definitions could be moved to `Theme.cpp`.

We would need to add one setting "themeName" to remember selected theme, similar to gGlobalPrefs->uiLanguage.

**Comment by blake-mealey** [comment]
So I am having a few difficulties getting this to work simply from an organizational standpoint. I have the structs declared very similarly to how you described doing it above in `Menu.cpp`, I created the Settings > Theme > [...] menu, and I added the `themeName` property to `GlobalPrefs`. But now I need a way to get the current theme which is accessible from everywhere that `gGlobalPrefs` is. I was thinking of doing something like this in `GlobalPrefs.h`:

```
inline Theme* GetTheme() {
    for (int i = 0; i < THEME_COUNT; i++) {
        if (!strcmp(g_themes[i]->name, gGlobalPrefs->themeName)) {
            return g_themes[i];
        }
    }
}
inline void SetTheme(Theme *newTheme) {
    gGlobalPrefs->themeName = newTheme->name;
}
}
```

But, Theme, THEME_COUNT, g_themes, etc. are not accessible from `GlobalPrefs.h`. Is there a better place I can put them?

Also, if I update `gGlobalPrefs->themeName` during runtime, will it save the preferences file with that change, or do I need to call another method to do that?

**Comment by kjk** [comment]
Generically speaking, you can always export the things you need in one place from another place.

In this particular place I would have `Theme *GetThemeByName(char* name)` in `Menu.cpp`. 
`struct Theme` most likely has to be visible from many places, so it has to be in .h file. For now it could be Menu.h or we could put it in its own `Theme.h`.

Saving settings after change is explicit, look for `prefs::Save()` for other places we do it.

A style note: we don't use strcmp(), we have str::Eq() (and more) in StrUtil.[h|cpp]
