### ISSUE TITLE
Collapsable bookmarks tree feature

### ISSUE THREAD

**Issue by saatchiCEO** [sumatrapdfreader/sumatrapdf#74]
Sometimes a book may have a bookmark tree with lots and **lots** of nested branches, which SumatraPdf automatically unfolds with no way to collapse them back (*augh!*). In my opinion, a set of buttons `collapse`/`uncollapse` would have fixed the problem.

Thank you!

**Comment by zeniko** [comment]
Thanks for the suggestion. Please see https://code.google.com/p/sumatrapdf/issues/detail?id=1632#c1 for why there won't be any such buttons and for how you can already collapse/expand (part of) the bookmarks tree using the keyboard.

**Comment by kjk** [comment]
Also, we do not automatically expand the nodes.

On first opening, Sumatra honors the directions in the PDF file. 

On subsequent openings, we restore the state of the tree when the file was last closed.

**Comment by saatchiCEO** [comment]
Oh, thanks for pointing out, didn't know about the keys and the other issue's existence.
