### ISSUE TITLE
Rendering issues?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [sumatrapdfreader/sumatrapdf#744]
To load just a single page PDF, mostly text, some table, 13kb large on my computer I had to watch "please wait - rendering" for about half a minute, whereas with Chrome or Adobe Reader I could see it instantly. What gives?

**Comment by kjk** [comment]
Please provide the PDF file that is slow to render. That's the only way for us to investigate and fix the issue.

Also, which version of Sumatra are you using?

**Comment by Unrepentant-Atheist** [comment]
No can do, said pdf file has sensitive information. Version is 3.1.2 64bit

**Comment by kjk** [comment]
Sorry, can't do anything without a sample.
