### ISSUE TITLE
Color error if use themes Dark or Darker

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#745]
If user swith themes Dark or Darker then SumatraPDF after Git-https://github.com/sumatrapdfreader/sumatrapdf/commit/2f506a546a8b035ba7297af213da5089124178bb display color errors for any document's type (I found this optical bug in to PDF, DjVu, ePoob, ASCII/Text, FB2) - see samples:

Original color:

![original_color_2](https://cloud.githubusercontent.com/assets/906886/23793288/886b0258-059b-11e7-90da-0bafe50a5f18.png)

Error color:

![bug_color_4](https://cloud.githubusercontent.com/assets/906886/23793572/fb2936a6-059c-11e7-91aa-689866313e94.png)

Original color:

![original_color_3](https://cloud.githubusercontent.com/assets/906886/23793552/e395a704-059c-11e7-8194-65d30e540c3c.png)

Error color:

![bug_color_3](https://cloud.githubusercontent.com/assets/906886/23793570/fb23e3f4-059c-11e7-82ef-ce5fa541b65f.png)

Original color:

![original_color_4](https://cloud.githubusercontent.com/assets/906886/23793553/e3972c14-059c-11e7-82a8-c701ec2635c2.png)

Error color:

![bug_color_2](https://cloud.githubusercontent.com/assets/906886/23793571/fb2853f8-059c-11e7-8a3d-af78a86be152.png)

I suggest that the reason for the observed error is that the background layer is superimposed as an inverting texture on the main image, instead of overlaying the image on the background layer without color inversion.

This bug is exists only for themes Dark and Darker. I attached [**Samples.zip**](https://github.com/sumatrapdfreader/sumatrapdf/files/833810/Samples.zip) for testig.

**Comment by kjk** [comment]
Yes, that's a known issue. This issue is discussed in https://github.com/sumatrapdfreader/sumatrapdf/issues/743 (the part about "invert colors" being independent setting from theming)

**Comment by VictorVG** [comment]
Good. I saw it, I read it, but I did not dare write it. Let's unite them into a single unit in order not to be confused. At work with opticians I consulted and, according to them, the hypothesis about the nature of the phenomenon is quite plausible.

**Comment by GitHubRulesOK** [comment]
closing as covered by #743 and #1275
