### ISSUE TITLE
SumatraPDF and helper scripts

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#746]
This is meant for discussion/brainstorming.

SumatraPDF is great because quick, functional and bloat free. Many want extra features. But some requests are niche and bloaty. Other requests look broadly useful but no one works on them. In both cases one possible way forward is **external helper scripts**.

Some benefits with encouraging helper scripts: 
- Niche features can be had without bloating everyone's SumatraPDF.
- Non C++ devs can contribute scripts.
- Script popularity as indicator for what to add natively.
- Main devs can focus more on core functionality.

Many GitHub/forum requests are already easy to implement with [Autohotkey](https://autohotkey.com/) or similar tools. E.g. some wishes for keyboard shortcut, extra toolbar buttons, and attaching pdf to email. I have also made two more complex helper scripts: [sumatra_earmarks](http://nod5.dcmembers.com/sumatra_earmarks.html) and [sumatra_highlight_helper](http://nod5.dcmembers.com/sumatra_highlight_helper.html)

Some changes to SumatraPDF would ease the use of helper scripts. In general expose more information about viewed documents and make more commands and settings scriptable without having to open a window or navigate a menu. For example 
1 expose the Document Properties (ctrl+D) information without having to open that window
2 expose the cursor position (M) data (all three formats!) without having to trigger that keyboard shortcut and without showing the overlay
3 prerelease version: add a shortcut/command to silently save new highlights, without save as... popup window.

**Comment by kjk** [comment]
I'm not opposed to that.

My ambitious plan was to embed a JavaScript engine in Sumatra (e.g. duktape) and write as much of Sumatra in JavaScript and allow writing user scripts extending Sumatra in JavaScript.

That being said, it's a lot of work and I don't see myself working on that.

**Comment by nod5** [comment]
Continuing the brainstorm. Here are three use cases for [Autohotkey](https://autohotkey.com/) helper scripts.

**1. remap existing keyboard shortcut**
**2. make new keyboard shortcut for existing menu command**
Both are easy to implement already, often with only a single line per shortcut. Sample Autohotkey code below. Note that the sample script overrides the SumatraPDF ctrl+L shortcut to toggle presentation mode on/off.
```
#IfWinActive, ahk_exe SumatraPDF.exe
^L:: send ^+{+ 3}  ;ctrl+L to rotate left
^R:: send ^+{+}    ;ctrl+R to rotate right
^E:: send !fe      ;ctrl+E to attach pdf to email
#IfWinActive
```
Place a link to the Autohotkey somename.ahk script file in the Startup folder to autorun the script and activate the keyboard shortcuts on each boot.

Automating menu navigation is more fragile than shortcut remaps so the more commands that have direct keyboard shortcuts the better, even awkward ones like ctrl+alt+F22 help since they are so easy to remap into whatever more convenient shortcut the user wants.

**3. make new toolbar button for existing shortcut or menu command**
For users who prefer buttons over keyboard shortcuts and for users with tablets or convertible laptops with touch. 

We can easily create buttons and sticky them on top of SumatraPDF. However on each SumatraPDF refresh (or resize, or minimize/maximize, ...) the toolbar/page view move in front of the extra buttons. 

This "move in front" problem does not occur with scripts that sticky to some other applications. Something in how SumatraPDF refreshes the toolbar seem to cause it. The sample Autohotkey code below tries to work around the problem with a timer that redraws the buttons. But that results in visible flickering. How well the buttons fit on the toolbar will also vary with the native toolbar width and screen resolution. The buttons also only show in a single SumatraPDF window. So overall an imperfect solution.

```
app := "ahk_exe SumatraPDF.exe"
SetTimer, stick, 500
return

stick:
If (WinExist(app) and !stick)
{
;make child window with buttons on right side of SumatraPDF toolbar
WinGet, win, ID, % app
Gui, Margin, 0, 0
Gui, +ToolWindow -Caption -resize
Gui, Add, Button,y0 x0 h23 gb2, Email
Gui, Add, Button,yp x+1 gb3 hp, Left
Gui, Add, Button,yp x+1 gb4 hp, Right
Gui, +Owner%win%
Gui, +LastFound
DllCall("SetParent", "uint", WinExist(), "uint", win)
x := 620 , y := 0
Gui, Show, NA x%x% y%y% , sumatra_button
WinActivate, ahk_id %win%
stick=1
}
else if (!WinExist(app) and stick)
{
;destroy buttons on Sumatra closes
gui, destroy
stick =
}
else
{
;redraw buttons on top after SumatraPDF refresh
 Loop, 3
  GuiControl, MoveDraw, Button%A_Index%
} 
return

b2:
winactivate, % app
send !fe
return

b3:
winactivate, % app
send ^+{+ 3}
return

b4:
winactivate, % app
send ^+{+}
return
```

An alternative method is to hover buttons over SumatraPDF and use a timer to, with a small delay, move the buttons when SumatraPDF moves. Sumatra_earmarks does that. But when SumatraPDF is moved/resized quickly the delay effect is very visible and ugly.

Use case 3 could be more robust if SumatraPDF added native support for extra toolbar buttons, placed to the right on the toolbar. Here is a mockup of advanced settings variables for that
```
extrabutton1 = "Email", "C:\folder\icon1.ico", "C:\test\email pdf.ahk"
extrabutton2 = "Left", "C:\folder\leftarrow.ico", "C:\test\left.ahk"
extrabutton3 = "Right", "C:\folder\rightarrow.ico", "C:\test\right.ahk"

```
The idea is that press of the button "Left" the script "left.ahk" runs in the background and in turn executes commands like those exemplified earlier or some more advanced scripting.

**Comment by kjk** [comment]
We've added keyboard shortcuts customizability natively.

Configuring toolbar is tracked by https://github.com/sumatrapdfreader/sumatrapdf/issues/1956
