### ISSUE TITLE
Add strikethrough option

### ISSUE THREAD

**Issue by bngiarola** [sumatrapdfreader/sumatrapdf#748]
I'm loving using Sumatra and it'd be great if you could insert the strikethrough option. Notes, text, and signing tools would be great! Also, buttons for easy access in the tool bar.

**Comment by GitHubRulesOK** [comment]
Strikethrough was possible (akwardly) in old annotation by editing .smx file.
That is no longer possible with new annotation but has been replaced by a better system
![image](https://user-images.githubusercontent.com/12754913/89963777-72c8c780-dc40-11ea-9ca9-5dde249fe670.png)
