### ISSUE TITLE
request Ctrl+T for new tab with same doc and same page.

### ISSUE THREAD

**Issue by asdfasdf123123** [sumatrapdfreader/sumatrapdf#749]
Sometimes I need to compare two different pages of the same PDF. Opening the same document twice in sumatra presents a problem, when TABs are enabled, because when I try to open the same document the second time, it just brings the already opened document to the foreground.
 I'm doing that by keeping the same document open on two different TAB-s. But achieving that state of Sumatra can be problematic for less experienced users. I'm doing it by opening another pdf next to the already opened one, then Ctrl+Shift Left key navigates to the same document, then find the page I need to see. The task gets a little more problematic, if the document (of which pages I want to compare) sits alone in a folder. Then I have to put some other PDF next to it so I can use the previously described method. 
I suggest that Ctrl+T opens a tab with the same document on the same page. 
Thanks

**Comment by SumatraPeter** [comment]
If you want to compare two views of the same doc, wouldn't it be better to have them in [multiple windows](https://github.com/sumatrapdfreader/sumatrapdf/issues/18) that you can view together on-screen, or perhaps even a [split window feature](https://github.com/sumatrapdfreader/sumatrapdf/issues/345#issuecomment-155067483)?

**Comment by kjk** [comment]
Available in latest pre-release (https://www.sumatrapdfreader.org/prerelease.html).

I've implemented Ctrl-Shift-N which opens a new window showing a currently shown document (i.e. "duplicate in current window").

There's also Ctrl-N to open a new, empty window (like Chrome's Ctrl-N) and "File / New window" menu item.
