### ISSUE TITLE
Error Runtime floating

### ISSUE THREAD

**Issue by anandas** [sumatrapdfreader/sumatrapdf#75]
once time i open file after downloaad its work smoothly but when i close and reopening file it come with message R6002 floating point not supported.the issue on portable and installer edition please help me to fix this issue .however i am already as fans of sumatra pdf since three yeas ago but when i reextract portable edition to same folder there is no problem to reopened files
![untitled](https://cloud.githubusercontent.com/assets/5581707/5899745/fd3fda92-a592-11e4-9dff-44e623ab7483.JPG)
 here is the screenshoot

thanks

**Comment by zeniko** [comment]
This happens most likely due to a misconfiguration of your system. Please see e.g. http://forums.fofou.org/sumatrapdf/topic?id=3183804 for more details.
