### ISSUE TITLE
Multi monitor Issue

### ISSUE THREAD

**Issue by LoZio** [sumatrapdfreader/sumatrapdf#752]
Using 3.1.2 on Win10 x64
I work in my office with 2 monitors and open a PDF on my secondary monitor.
Bring the laptop to another location where I have no secondary monitor.
I open a PDF: the PDF goes to the no-more-existing second monitor where it was last time.
Expected: if there is only one monitor, use that.

**Comment by GitHubRulesOK** [comment]
@kjk it is very common for apps to open where they were last used and if a second monitor goes to standby or is removed they do not return to the mainscreen without a lot of fiddling about, so this is not just a SumatraPDF issue, However the more inteligent apps seem to be able to check if more than one monitor is active at startup and reset themselves in such cases.

**Comment by GitHubRulesOK** [comment]
@kjk apologies for what its worth SumatraPDF DOES appear to check andreset to left of main screen on a restart after shutown without second monitor, If you can confirm that is the case then this issue can be closed ?

**Comment by GitHubRulesOK** [comment]
@kjk 
I found on occasion with 2nd monitor off the Annotation Editor was sometimes out of sight, however I cant seem to replicate that behaviour with current pre-release. Perhaps since I restarted SumatraPDF with 2nd monitor off?

The logic for which monitor to appear on, seems to be more robust?

**Comment by LoZio** [comment]
Today's pre-release seems to work fine 3.4.13978

**Comment by kjk** [comment]
Good to hear. I did add some logic to ensure windows open on visible area so maybe that was the fix for this.

**Comment by LoZio** [comment]
Problem again: yesterday I closed Sumatra after reading some docs, using my 2 monitor setup.
Today I reopened the doc while on travel, only the laptop display, and the doc opens out of any visible region.
