### ISSUE TITLE
[Feature Request] Higher resolution for toolbar buttons

### ISSUE THREAD

**Issue by 63tjpm7z** [sumatrapdfreader/sumatrapdf#753]
![01](https://cloud.githubusercontent.com/assets/3512954/24072225/7b45cbf6-0bec-11e7-8c3c-f3b8cb688938.jpg)

I have setting up 150% scaling in Windows10
and SumatraPDF toolbar buttons pixelated

**Comment by bananakid** [comment]
I double that. Toolbar looks very outdated & fuzzy on any modern computer display (I'm using 200% scaling in Windows 10 with 15-inch 4K screen). Please update!

**Comment by SumatraPeter** [comment]
Related / duplicate of: https://github.com/sumatrapdfreader/sumatrapdf/issues/430

Also, looks like it's being worked on: https://github.com/sumatrapdfreader/sumatrapdf/issues/734

**Comment by kjk** [comment]
Closing as duplicate of #734
