### ISSUE TITLE
Fit Width does not work for some .pdf s

### ISSUE THREAD

**Issue by Fealthas** [sumatrapdfreader/sumatrapdf#754]
Fit width is used and it does not fill up all available space.

![image](https://cloud.githubusercontent.com/assets/25716039/24075030/868773e0-0bea-11e7-9edd-8dd2a201615f.png)

**Comment by kjk** [comment]
Most likely it's because the PDF has pages of different size and we picked constant scale factor for all pages for "fit width".

Either way, nothing I can do without access to a file that shows the problem.

**Comment by PeterPablo** [comment]
I can confirm in a document of mine that the observed behavior is due to at least one page of the PDF being with landscape orientation.
