### ISSUE TITLE
Space added when e-mail copied from PDF

### ISSUE THREAD

**Issue by SW-GitHub-2017** [sumatrapdfreader/sumatrapdf#755]
SumatraPDF Portable v3.1.2 (downloaded from portableapps.com)
OS: Windows XP Service Pack 3

When you click the e-mail address once, right-click and select "Copy Selection", the e-mail is copied, but a space is added to the very beginning of the e-mail address.

EXAMPLE:  If the e-mail was "123@xyz.com", then copied e-mail ends up being " 123@xyz.com".

**Comment by kjk** [comment]
Copying text from PDF relies on a bunch of heuristics. The space must have been there in the PDF document. We could strip it but then other people will complain that we strip the spaces when copying text.

Either way, there's nothing I can do without access to the file that shows the problem.

**Comment by SW-GitHub-2017** [comment]
Attached is a sample file that you can examine.

[E-mail_Test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/853869/E-mail_Test.pdf)

**Comment by SumatraPeter** [comment]
Just tested the attached PDF on Win10 using 3.2.10688 (pre-release):

1. Right-clicking e-mail and selecting Copy Link Address copies "mailto:123@xyz.com" to the clipboard (without the quotes).

2. Left-clicking e-mail, then right-clicking and selecting Copy Selection copies "123@xyz.com" to the clipboard (without the quotes).

    Note 2a: I guess normally left-clicking should open the default e-mail program, but I don't have one assigned so it just selects the text.

    Note 2b: Actually Copy Selection seems to copy as both image and text, so if I paste into Notepad it pastes "123@xyz.com", but if I paste into Paint or this comment form it pastes the following image: ![image](https://cloud.githubusercontent.com/assets/15380332/25713890/e17474bc-3113-11e7-8f13-7f8e189082ff.png) Interesting, huh?!
