### ISSUE TITLE
[Website] Add RSS feed for new releases.

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#758]
It'll be nice if you add RSS feed to your website, so the user can know when to download.
(I dislike application's update mechanismso I never use them.)

Or, why not release a software here, on Github /releases/? Github provides RSS feed.

**Comment by GitHubRulesOK** [comment]
@kjk is some .atom trigger needed to RSS Github or Website release ?

Anyway am closing as OP secondary request is a current github feature
![image](https://user-images.githubusercontent.com/12754913/126041237-055e3dbd-0a04-4b55-8619-37ff3f341d0e.png)

**Comment by GitHubRulesOK** [comment]
Ghost Account :-) or others 

Note above notification method and also Documentation now shows https://github.com/sumatrapdfreader/sumatrapdf/commit/30d2497114d65ad0cf414224fb8642fcb6b48842

[Version history
RSS/Atom feed.](https://www.sumatrapdfreader.org/docs/Version-history)
