### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by HoldOffHunger** [sumatrapdfreader/sumatrapdf#759]
I can't see Keywords in Sumatra when viewing document information.  They're suspiciously missing?

Works fine in Adobe.

P.S. Would be nice if the metadata was selectable so I can copy/paste these values instead of having to retype what I can already see on my screen.

**Comment by SumatraPeter** [comment]
> Would be nice if the metadata was selectable so I can copy/paste these values instead of having to retype what I can already see on my screen.

Are you talking about the Properties dialog (Ctrl+D)? Have you tried pressing Ctrl+C while the dialog's open, then pasting in any text editor?

**Comment by HoldOffHunger** [comment]
I can't ctrl+C on text that does not appear.

**Comment by SumatraPeter** [comment]
Just want to clarify that you don't need to select the text before pressing Ctrl+C to copy the contents of the Properties dialog to the clipboard.

In any case it's pointless raising any such complaint without providing an example of an offending document, so that the Sumatra developer can himself see why the code is failing to extract and display the keywords.

**Comment by HoldOffHunger** [comment]
Just to clarify, this is a continuation of the conversation posted to, and deleted from, the development Sumatra's Fofou bulletin board.  Documents were posted there, and deleted, by the Sumatra steering-committee.  It would be nice if they could repost what they deleted, I agree.

**Comment by SumatraPeter** [comment]
Can you link to the Fofou thread? There's no "steering-committee" for Sumatra - it's just Krzysztof Kowalczyk and for a while zeniko was a regular contributor too, although I don't know if he had admin access to the Fofou forum.

**Comment by tomarikawa** [comment]
I can confirm, that in version in SumatraPDF-3.1.2-64.zip There is no kexywords visble, nor are they included, when copied/pasted.

Without knowing the source-code, I assume getting the keywords in both window and copy/paste would be a very tiny and unrisky task

**Comment by kjk** [comment]
Without a test document I can't make progress.

**Comment by HoldOffHunger** [comment]
Here's a file with keywords: https://www.revoltlib.com/anarchism/anarchist-morality/view.pdf

Tested it out here: https://www.get-metadata.com/result/063f5010-483f-4552-b18e-355f6d26c6bf

Tons of keywords.

**Comment by dominiosc** [comment]
The metadata keywords not show
https://www.metadata2go.com/result/0be9b6ec-fccb-4b4b-a137-485b983007b9
https://apastyle.apa.org/instructional-aids/abstract-keywords-guide.pdf

in epub files neither the keywords nor the series
