### ISSUE TITLE
search problem

### ISSUE THREAD

**Issue by mesiarm** [sumatrapdfreader/sumatrapdf#76]
Hello, I found bug in search feature in SumatraPDF. It won´t find characters from other alphabets and it will find integral symbol if i am searching R for example.

**Comment by kjk** [comment]
You would have to provide a sample PDF document, what search query you're using, what happens and what you expect to happen.

There's nothing we can do without this information.

**Comment by GitHubRulesOK** [comment]
@kjk with improvements in Unicode searching such as previously mentioned string Zapowiadał
I would suggest without any specific conflicting example this has been recently addressed
