### ISSUE TITLE
Regression problem: "Error loading C:\User\file-path\file.pdf" when PDF opened in Sumatra 3.1.2

### ISSUE THREAD

**Issue by igor2x** [sumatrapdfreader/sumatrapdf#760]
Hi,
I have been using SumatraPDF for years. I have had installed SumatraPDF 3.0 portable and have been using it for years without an issue.

Today I have looked for new version, just to keep up with new versions. I downloaded SumatraPDF 3.1.2 portable and tested it. I have found one PDF file that can't be opened with SumatraPDF 3.1.2

Reproduce:
1. Open button from toolbar and selecting PDF file. Error is produced:
> Error loading C:\User\...file-path...\file.pdf

I also downloaded and tested:
- 3.1 64-bit portable
- 3.1.1 64-bit portable
- 3.1.2 64-bit portable and 32-bit portable
All above produces the same error when one particular PDF file is opened.

But in SumatraPDF 3.0 the same PDF file is opened successfully without a problem, so PDF is not corrupted or something.

Any idea how to debug what is wrong?

P.S. Sorry I can't upload PDF book, because it is from paid subscription.
Regards

**Comment by kjk** [comment]
Nothing I can do without access to the file. You can e-mail confidential files to me directly (see https://www.sumatrapdfreader.org/docs/How-to-submit-bug-reports-c992bbe9c7b14c0eac5b7493228d4ce4.html)

**Comment by igor2x** [comment]
I have sent the PDF file to your mail. Please properly destroy the file after testing.

**Comment by kjk** [comment]
Thanks, will do.

**Comment by GitHubRulesOK** [comment]
@kjk ? current status

**Comment by kjk** [comment]
I found the email and was able to open the file in latest build so the issue is fixed.
