### ISSUE TITLE
Did you delete the "inverse search" setting from "File-Settings"?

### ISSUE THREAD

**Issue by 724Cheers** [sumatrapdfreader/sumatrapdf#761]
In version of 3.1.1, I could set inverse search in "File-Setting".
But in version of 3.1.2, I cannot find the setting option.

**Comment by kjk** [comment]
This option is still there but we only show it in the UI after the first time you open a document with corresponding .ssynctex or .pdfsync file. The idea is that only small number of people use latex integration so we don't want to clutter the UI for most people with option they would never use.

You can get it back by setting `EnableTeXEnhancements = true` in advanced settings (https://www.sumatrapdfreader.org/settings.html)

You can also use -inverse-search cmd-line option (https://www.notion.so/Command-line-arguments-0c53a79e91394eccb7535ef6fed0678e) or InverseSearchCmdLine  advanced settings (https://www.sumatrapdfreader.org/settings.html)
