### ISSUE TITLE
file:// links don't work

### ISSUE THREAD

**Issue by abma** [sumatrapdfreader/sumatrapdf#763]
when clicking on file:// links nothing happens, sumatrapdf seems to ignore it.

see attachment as example:
[test.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/865432/test.pdf)

http:// links work as excepted...

**Comment by SumatraPeter** [comment]
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/618

**Comment by kjk** [comment]
See #618 for explanation.
