### ISSUE TITLE
Close button not in absolute corner when maximized

### ISSUE THREAD

**Issue by brnl** [sumatrapdfreader/sumatrapdf#764]
Hi,

First of all, my love for Sumatra PDF!

I have found out that on my 2nd monitor, which uses DPI scaling, the close button doesn't close the corner when maximized, which makes it possible to press a button on the program behind the Sumatra PDF window.

Example:
![image](https://cloud.githubusercontent.com/assets/3243133/24300719/a2e5b714-10ad-11e7-8f30-81ce73697c17.png)

As you can see, the close button is not lighting up 'red'. This 'close' tooltip is from Chrome, which is behind the Sumatra window. Clicking it will close Chrome.

Is this a problem of Sumatra or is it Windows 10?

Thanks.

**Comment by SumatraPeter** [comment]
> Is this a problem of Sumatra or is it Windows 10?

Why not just test with any two programs other than SumatraPDF to confirm? If it points to a Windows 10 bug then might be useful to confirm on at least one more dual monitor setup before proving a bug report via the Feedback Hub app to Microsoft.

**Comment by brnl** [comment]
Yeah, I'm sorry. Further tests points more to Windows rather than SumatraPDF specific.

Keep up the good work, I really love SumatraPDF!
