### ISSUE TITLE
Heading font is same as normal text

### ISSUE THREAD

**Issue by Atul2295** [sumatrapdfreader/sumatrapdf#766]
Dear developers,
                          Heading and normal text are having the same font size in epub files. So, please enable different font size for these two texts for the epub documents.
thanks

**Comment by GitHubRulesOK** [comment]
@kjk works with uncorrupted, well built files
![image](https://user-images.githubusercontent.com/12754913/72672309-ffffc100-3a4f-11ea-96e6-1cbd6109cc45.png)

**Comment by SumatraPeter** [comment]
The question is, which exact tags were used in the EPUBs the OP encountered (<h*N*>, font size, style, CSS etc. ...)? Without test docs it's difficult to know unless one tries various ways of creating what is interpreted as 'heading' text.

**Comment by GitHubRulesOK** [comment]
Am closing since without samples this independant issue cannot be adressed.
If any user has related problems ensure you supply sample when you report a fresh issue.
