### ISSUE TITLE
add close button (X) at upper-right corner on pdf-thumbnails in Frequently Read window

### ISSUE THREAD

**Issue by katpatuka** [sumatrapdfreader/sumatrapdf#768]
Maybe one could add a close button (**X**) at upper-right corner of pdf-thumbnails in **Frequently Read** window (similar to Firefox browser's **New Tab** window showing thumbnails of recently visited sites where a hover over a thumbnail displays a close button). 

Up to now one has to right-click on a thumnail and choose **Remove Document** to remove the thumbnail.

**Comment by SumatraPeter** [comment]
Duplicate of 283

**Comment by kjk** [comment]
closing as dup of 283
