### ISSUE TITLE
Newer erase page while rendering

### ISSUE THREAD

**Issue by aparamon** [sumatrapdfreader/sumatrapdf#769]
To reproduce:
0) Open a document with several pages which are heavy to render.
1) Press PgDn to switch to next page.
The contents of the page are soon erased, with message
"Формируется изображение, подождите..."
This is suboptimal as it distracts user attention, especially if pages constitute an animated sequence.

Please note that when file is modified on disc, such effect doesn't happen. Instead, a small indicator in the topright corner appears (correct). It is proposed to use the same mechanism for page switch.

**Comment by kjk** [comment]
Unfortunately, the alternative (showing the old page until we have a new one fully rendered) is worse. It would make the app seem unresponsive.

**Comment by aparamon** [comment]
An small indicator would allow to avoid flicker, and also clearly show that the application didn't freeze.
Maybe display the message in the page center as done currently, but do not erase the full page?
