### ISSUE TITLE
Printing PDF file causes printer to lock up.

### ISSUE THREAD

**Issue by ziddy** [sumatrapdfreader/sumatrapdf#77]
My office has a Xerox ColorQube 8700X PS printer. When I try to print a PDF from Sumatra (version 2.5.2), it locks up the printer and no print jobs will go through. When I print from Adobe, it works just fine.

Not sure if this issue has been fixed in version 3 (I realized just now that I had neglected to update), but I cannot test it as people will become very upset if the printer locks up again.

**Comment by kjk** [comment]
Unfortunately, in order to even start debugging this we would have to know if it happens for all PDF documents or just one and if it's still present in 3.0
