### ISSUE TITLE
online translation

### ISSUE THREAD

**Issue by srbarros** [sumatrapdfreader/sumatrapdf#771]
What about an option to translate a page at a time, by interacting with some online tool, like google translation tool, for example? I think it will be a usefull feature, even if the translation is made one word at a time!

**Comment by srbarros** [comment]
The translation is only possible if the document have text embedded into it.

**Comment by kjk** [comment]
Unfortunately I don't know of any freely available translation tool we can use. Google translation API is not free.

**Comment by GitHubRulesOK** [comment]
Just a comment that this feature is now available in pre-release version 3.4
