### ISSUE TITLE
EnableComments 

### ISSUE THREAD

**Issue by srbarros** [sumatrapdfreader/sumatrapdf#772]
What about enable comments into the text. It is not necessary to save into pdf/chm/else document, but to create a xml file contaning the comments and a kind of index to the proper place into document.

**Comment by srbarros** [comment]
The xml file containing the document can have the same name as the document, and be saved at same directory, to user know where his/her comments was saved.

**Comment by SumatraPeter** [comment]
The ability to add/edit comments has been a long-standing feature request. See for example https://github.com/sumatrapdfreader/sumatrapdf/issues/528 and especially [Adding notes and bookmarks in epub](http://forums.fofou.org/sumatrapdf/topic?id=2961322) for suggestions regarding external XML comment files.

**Comment by GitHubRulesOK** [comment]
@kjk A few mixed suggestions to either add comments as per standard adobe/mupdf comments icon OR a SumatraPDF enhancement to add external comments per file (possibly in xml format)
Either way  duplicates Feature request in Comment feature #528

**Comment by kjk** [comment]
Consolidating under #453
