### ISSUE TITLE
Can't go to destination page when click on bookmark of PDF file

### ISSUE THREAD

**Issue by doducmi** [sumatrapdfreader/sumatrapdf#775]
I opened PDF file using SumatraPDF and I can't go to destination page when click on bookmark, but those bookmarks still working fine in Google Chrome, FireFox and Foxit Reader.
In attach file, when click on CHAPTER 25, 26, 28... bookmark, this error will be occur.
Attach file here: http://ge.tt/2vl7ebj2

**Comment by ousia** [comment]
@doducmi, I’m afraid that those links try to launch a non-existing external file.

Do links from page 3 work as expected?

@kjk, I’m afraid the document might have been generated by merging single PDF documents (that were the chapters).

I think SumatraPDF is right in not launching a non-existing file.

**Comment by doducmi** [comment]
@ousia Yes, it did.
In SumatraPDF, when I click on "CHAPTER 3" bookmark, it moves to Chapter 3 exactly, but in Google Chrome or Foxit Reader, it moves to Chapter 33 :)) Hard to understand :))

**Comment by ousia** [comment]
@doducmi, if links in page 3 work as expected, I think the PDF document is at fault, not SumatraPDF.

**Comment by doducmi** [comment]
May be :)
