### ISSUE TITLE
Implement text selection and search in ebook mode

### ISSUE THREAD

**Issue by xStevex** [sumatrapdfreader/sumatrapdf#779]
# Select text on fb2, epub, mobi
I think is very useful feature when you can select text while reading e-books :)
For example, I often (and I am sure many others) while reading books make notations (especially if it is not fiction literature). When the text is small, so okay, I can by my hands write a note, but if I need just to copy a large amount text, it's problem. I just forced to open the online version of the e-book, where I can do it, or read e-book by any another programs from your [list](http://blog.kowalczyk.info/articles/epub-ebook-reader-viewer-for-windows.html). In both cases it's uncomfortable.
# Search text on fb2, epub, mobi
It also very useful feature for reading. 
# Epilogue
I understand that SumatraPDF focuses on work with PDF, but this two feature just must have for comfortable reading and working with text :)

**Comment by kjk** [comment]
Yes, I would like to implement those features but I can't provide any timeline for that.

**Comment by SumatraPeter** [comment]
Already requested many times, for example:

https://github.com/sumatrapdfreader/sumatrapdf/issues/414
https://github.com/sumatrapdfreader/sumatrapdf/issues/639

**Comment by GitHubRulesOK** [comment]
@kjk effectively dup of https://github.com/sumatrapdfreader/sumatrapdf/issues/239

**Comment by kjk** [comment]
closing as dupplicate
