### ISSUE TITLE
Toolbar buttons for "Go Back", "Go Forward" (in addition to "Previous Page", "Next Page")

### ISSUE THREAD

**Issue by Niels-75** [sumatrapdfreader/sumatrapdf#780]
Documents often contain links that navigate to another location in the document.
The reference can be clicked on to jump to the referenced location.
**Typically afterwards you want to jump back to the place from where you navigated.**
(For example a proof in a mathematical document contains a references to a bibitem, or section, or theorem, or equation, or whatsoever, at another page of the document.)

Today this backward (and forward) navigation is only available by keyboard action (Alt-Left, and Alt-Right).
**Backward (and forward) navigation shall be possible by mouse action.**

**Comment by shaiay** [comment]
I made a very simple change to add this: https://github.com/shaiay/sumatrapdf/commit/413bf0ba07c6196127185451a35b12e247672585
However, currently it uses the same icons as prev & next page, so a bit confusing. Any help with nicer icons would be appreciated. Once I have better icons I will create a pull request

**Comment by shaiay** [comment]
see #657

**Comment by FSund** [comment]
This would be a very nice addition.

I suggest that hotkey for this is Alt+Left/Right arrows, I think that's pretty standard in other PDF readers.

**Comment by GitHubRulesOK** [comment]
@kjk ? consolidate with #657
