### ISSUE TITLE
Full path in title not completely shown in some circumstances

### ISSUE THREAD

**Issue by urgrueA** [sumatrapdfreader/sumatrapdf#782]
With the FullPathInTitle option enabled, instead of the full path and filename, we might see only the start of the path in each tab unless the tab is wide enough, which is of limited usefulness. A tooltip showing the filename (or optionally the complete path and filename) would be a welcome addition.

**Comment by pdgessler** [comment]
See #336 (possible duplicate).

**Comment by kjk** [comment]
closing as dup of #1188
