### ISSUE TITLE
MathML Support

### ISSUE THREAD

**Issue by komawoyo** [sumatrapdfreader/sumatrapdf#784]
MathML Support would be nice

**Comment by kjk** [comment]
Not sure what you mean by this. 
MathML is not a document format. Do you have a document that shows lack of MathML support?

**Comment by komawoyo** [comment]
http://docs.mathjax.org/en/latest/misc/epub.html

Yes I have the following ebook. None of the equations are showing up
The Feynman Lectures on Physics, Vol. I The New Millennium Edition Mainly Mechanics, Radiation, and Heat, Feynman.epub

**Comment by petrasteri** [comment]
Well, if this continues, better rename this application and it should not be called Sumatra**PDF** anymore.
I chose this software because it's light.  Please don't let it become bloatware!

**Comment by komawoyo** [comment]
> Well, if this continues, better rename this application and it should not be called SumatraPDF anymore.
> I chose this software because it's light. Please don't let it become bloatware!

From the Readme: ""SumatraPDF is a multi-format (PDF, EPUB, MOBI, FB2, CHM, XPS, DjVu) reader""

**Comment by petrasteri** [comment]
> From the Readme: ""SumatraPDF is a multi-format (PDF, EPUB, MOBI, FB2, CHM, XPS, DjVu) reader""

Yes, but there's also the following sentence:
It’s small and starts up fast.

Why most people always like "Swiss Knife" software?
