### ISSUE TITLE
Git- 75e61ee build failure - can't found lib\openjp2

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#785]
Build failure then VC can't find lib\openjp2: [readme.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/932472/readme.txt)

**Comment by kjk** [comment]
Please follow https://github.com/sumatrapdfreader/sumatrapdf/blob/master/readme.md for checking out the code.

**Comment by VictorVG** [comment]
Do you think it's worth to clone the working copy again? I'll try why there will not accumulate errors?

**Comment by VictorVG** [comment]
Yes, you were right, but I did not notice it - the ./openjpeg directory is empty. Re-bent again and everything seemed to download. Thanks for the help!
