### ISSUE TITLE
Change background canvas color

### ISSUE THREAD

**Issue by SicariusNoctis** [sumatrapdfreader/sumatrapdf#787]
Not the background of the page, but the background behind that. I'd like an option, something like:

    CanvasBackgroundColor = #333333

To make sure we're on the same, ahem, _page_, here's a visual:

![Example image](http://i.imgur.com/ZSZTPth.png)

**Comment by p0te** [comment]
Defined as COL_PAGE_FRAME = 0x88,0x88,0x88 in colors.cpp. I beleive for the moment you could just change the value before building. Would be cool to see this as one of the options...

**Comment by GitHubRulesOK** [comment]
@SicariusNoctis 
perhaps a bit late (but suggest this can be closed ?)
see forum  for set gradientcolors or similar (one word)
sytax very specific however will accept 1 user preference color rather than 3

**Comment by kjk** [comment]
Yes, this can be changed with GradientColors option (http://www.sumatrapdfreader.org/settings.html)

**Comment by rjshaver** [comment]
I tried to get the bookmark (TOC) window to change color with GradientColors option but did not work on v. 3.1.2 64 bit.  I can use the color options in the Advanced Settings File to provide a gray theme  for pdf's but the bookmarks/table-of-contents continue to show up with the standard black text on white background.  Is there a way to get this to work?  I tried the setting: 
GradientColors = #2828aa #28aa28 #aa2828
I also tried commas between the hex numbers for colors.  Is this the correct method or not?  If not, is there a setting to alter this?  I understand there has been discussion of implementing some type of theme support.  If this goes forward, I would suggest dark, light, and gray.  Thanks so much.  This is a wonderful project.  It is such a lightweight pdf viewer along with other formats.

**Comment by lightexpensive** [comment]
> Yes, this can be changed with GradientColors option (http://www.sumatrapdfreader.org/settings.html)

I set the GradientColors in the code, how to show the effect immediately

**Comment by GitHubRulesOK** [comment]
@lightexpensive 
It should change as soon as you get it right, Settings >Advanced options
Under FixedPageUI[ ( e.g. before text colour) add
  GradientColors = #2828aa #28aa28 #aa2828
save settings (control+S) go back to SumatraPDF Window and press R to refresh
