### ISSUE TITLE
Restore recently closed tabs via keyboard shortcut

### ISSUE THREAD

**Issue by fabbra** [sumatrapdfreader/sumatrapdf#788]
Hi,

Not sure this has already been requested (at least I haven't found while searching the issues)...

It would be great to be able to use a **keystroke** (e.g. Ctrl+Shift+T, as in Firefox for example) to reopen (i.e. **restore the tab**) of a **previously closed document**.

Thanks,
Fab

**Comment by nisbahmumtaz** [comment]
Seconded, considering how large the "close X" tabs are. I find myself constantly accidentally closing 1 out of the 30+ tabs I always have at a time.

**Comment by PetraBaum** [comment]
I agree. It should be quite easy to implement and it can save quite some time, especially if the closed tab was opened a while back, so that it's no longer in the 'last opened' list.
Thanks for the lightweight reader, devs.

**Comment by Aliaksandr3by** [comment]
I opened +/-15 files in various time. I will be open more one, and i close unnecessary.
Last opened and last closed - It is not the same;
I accidentally close one book… oh! i don’t remember what of book I close… I don’t remember both name and author… . And I don’t remember when the file is get opened.
And more badly ctrl+W is keyboard shortcut for Close file, and ctrl+1/2… for change view.

i think it is very need feature restore last closed file, or list both last open (it already exists) and last closed

**Comment by WhiteChairFromIkea** [comment]
Maybe this feature could be listend into the canny?

**Comment by kjk** [comment]
Sure, feel free to add it.

**Comment by GitHubRulesOK** [comment]
This is a native windows feature if I open another file within SumatraPDF its added to windows history.
![image](https://user-images.githubusercontent.com/12754913/168173867-37124789-4c8d-482c-a491-5c7d3f35dd73.png)![image](https://user-images.githubusercontent.com/12754913/168174142-2897089c-b0fb-4f9b-9a80-f1516242a6ce.png)

**Comment by WhiteChairFromIkea** [comment]
Using ctrl + w / ctrl + shift + t is a fast way to do this. My use case: I work on a project, and I keep opened my main pdf documents in the first tabs (such as project task descriptions...). During the days I read bunch of random datasheets when comparing parts, needed for my project. The number of tabs after an hour of work becomes huge 30 or so. At some point, only first tabs become necessarry, so I use ctrl +w to close them. I do this by spamming thus hotkey at high rate, sometimes too many times and closing the tab which is needed. Ctrl + shift + t would save me in web browser, but there is no such hotkey in sumatra at the moment.

**Comment by GitHubRulesOK** [comment]
@WhiteChairFromIkea 
I understand that issue the point is that your scenario is quite common the frequent request is to store dozens of file names at a time. thus there will be an ever growing list of closures desired.
Windows recent does not include all object opened by SumatraPDF such as a Folder of files and the list is limited as it needs to be for efficiency (same as inside SumatraPDF) and "pinning" is the best way to retain frequently needed (frequently read)

The main issue becomes a desire to retain a separate list of "closures" so that they may be undone (Ctrl+Z or similar such as browsers use Ctrl+Shift+T) and thus the last closure is most important up to a limited depth, however that requires suitable code to maintain a "closure ranking" across all previously opened assets.

**Comment by WhiteChairFromIkea** [comment]
> 

Yes, I understand that this is not such a basic feature: CTRL+ SHIFT + T ("C+S+T" for future reference :D) must be implemented in a FIFO manner, reopened tab should be placed in the tab bar at such position, where it was closed. I mean this feature implementation relies under this: https://github.com/sumatrapdfreader/sumatrapdf/issues/2416#issuecomment-1129846712, so #2416 must be implemented first.

**Comment by kjk** [comment]
I've added `CmdReopenLastClosedFile` command with `Ctrl + Shift + T`  also available via Command Palette (`Ctrl + K`) as `Reopen Last Closed`.

**Comment by WhiteChairFromIkea** [comment]
Thank you very much! 🙂

**Comment by Butanium** [comment]
Hi,

I think I have the last version : 
![image](https://user-images.githubusercontent.com/55806347/177202468-cf108223-9042-4bd9-9aff-0e653175c2b9.png)

But I the shortcut doesn't work and the action doesn't appear in Command pallette : 
![image](https://user-images.githubusercontent.com/55806347/177202552-88841ffb-491c-4fb0-8a57-2e6aa9c19539.png)

**Comment by GitHubRulesOK** [comment]
@Butanium 
it should be working in https://www.sumatrapdfreader.org/prerelease
