### ISSUE TITLE
SumatraPDF not using default printer tray

### ISSUE THREAD

**Issue by dkmarsh99** [sumatrapdfreader/sumatrapdf#790]
I am printing a PDF to a printer using SumatraPDF. In the print driver I have specified a specific tray I want tthe print to go to. When I print from other programs - for example MS Word it prints to the tray that was specified in the driver. When I print from SumatraPDF it ignores the specific tray and prints to the main tray on the printer. Please help - How can I make sure it prints to the correct tray.

**Comment by kjk** [comment]
Looking at the code, we should use whatever tray is the default. But I would need more information:

* version of Sumatra and OS?
* printer name
* are you printing from the UI (File/Print menu) or from command-line
* if from command line, what is the exact command-line you use
* what do you mean by "in the printer driver I have specified a specific tray". Where did you specify it?
* if from UI, what do you select in tray selection ui:
![iodqjt0](https://cloud.githubusercontent.com/assets/7935/25354845/6b48fb32-28e9-11e7-851a-a4c3226cca73.png)

When printing from cmd-line, you can use `-print-settings "bin=2"` to print to e.g. tray 2.

**Comment by GitHubRulesOK** [comment]
@kjk without feedback for 6 years I think this is stale ?
