### ISSUE TITLE
Question: v3.2 Git-402009c948 have C++ error in to .\Src\EngineDump.cpp . How do you advise to do?

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#791]
Question: v3.2 Git-402009c948 have C++ error in to .\Src\EngineDump.cpp . How do you advise to do?

VC++ 2015/2017 print 23 error messages in ".\Src\EngineDump.cpp" this binary
is not going to, but the test went through. I just in case put alongside the
tested files SumatraPDF and PDB, but there were no failures and they were not
required.

How do you advise to do? Do not pay attention to the fact that this module is
not going to?

Compller error list (display both VC2015 and VC2017 for x86 and x64 build):
 
Severity Code Description Project File String Suppression State

Error C2059 syntax error: return enginedump .\Src\EngineDump.cpp 365
Error C2065 error pathUtf8: undefined enginedump identifier .\Src\EngineDump.cpp 367
Error C2059 syntax error: for enginedump .\Src\EngineDump.cpp 371
Error C2143 syntax error: no ")" before ";" Enginedump .\Src\EngineDump.cpp 371
Error C2143 syntax error: no ";" Before "<=" enginedump .\Src\EngineDump.cpp 371
Error C4430 missing the type specifier - assumed int. Note. C ++ does not support int by default enginedump .\Src\EngineDump.cpp 371
Error C2143 syntax error: no ";" Before "++" enginedump .\Src\EngineDump.cpp 371
Error C2086 int pageNo: Override enginedump .\Src\EngineDump.cpp 371
Error C2059 syntax error:) enginedump .\Src\EngineDump.cpp 371
Error C2143 syntax error: no ";" Before "{" enginedump .\Src\EngineDump.cpp 371
Error C2447 {: there is no function header (maybe a formal old type list is used) enginedump .\Src\EngineDump.cpp 371
Error C2059 syntax error: return enginedump .\Src\EngineDump.cpp 401
Error C2059 syntax error:} enginedump .\Src\EngineDump.cpp 402
Error C2143 syntax error: no ";" Before "}" enginedump .\Src\EngineDump.cpp 402
Error C2059 syntax error: public enginedump .\Src\EngineDump.cpp 404
Error C2143 syntax error: no ";" Before "{" enginedump .\Src\EngineDump.cpp 404
Error C2447 {: there is no function header (maybe a formal old type list is used) enginedump .\Src\EngineDump.cpp 404
Error C2065 error PasswordHolder: unannounced identifier enginedump .\Src\EngineDump.cpp 502
Error C2146 syntax error: no ";" Before the identifier "pwdUI" enginedump .\Src\EngineDump.cpp 502
Error C3861 pwdUI: identifier not found enginedump .\Src\EngineDump.cpp 502
Error C2065 error pwdUI: undefined enginedump identifier .\Src\EngineDump.cpp 503

**Comment by kjk** [comment]
Sorry about that, should be fixed now.

**Comment by VictorVG** [comment]
Big thanks!
