### ISSUE TITLE
Shortcut for "Show toolbar" is missing

### ISSUE THREAD

**Issue by 1xcodex1** [sumatrapdfreader/sumatrapdf#796]
Sure, this is just cosmetic, but the default key is F8.
Maybe you would like to add the label to the view menu.

**Comment by kjk** [comment]
Good point, thanks for the suggestion.
Fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/cf9d0e027c3ccc23807193f0237def7158a180d8
Should be available in latest pre-release soon (https://www.sumatrapdfreader.org/prerelease.html)
