### ISSUE TITLE
v3.2 Git-1793f72709 - the sub-menu Favorites is displayed instead of the sub-menu Options

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#797]
v3.2 Git-1793f72709: a typo in the main menu - the sub-menu Favorites is displayed instead of the sub-menu Options:

Sub-menu Favorites:

![1](https://cloud.githubusercontent.com/assets/906886/25568855/07e6b576-2e15-11e7-8d2f-f8f83f02571d.png)

Sub-menu Options:

![2](https://cloud.githubusercontent.com/assets/906886/25568857/154697e0-2e15-11e7-99b0-b792aed0f47a.png)

Also this typo exists in to v3.2 Git-cf9d0e027c

**Comment by kjk** [comment]
Sorry about that. Thanks for letting me know.

**Comment by VictorVG** [comment]
Mutual thanks. I myself at first did not understand what I see, but began to understand because I understood that something is not ordinary.
