### ISSUE TITLE
[Feature Request] Open current file in other program

### ISSUE THREAD

**Issue by danil-tolkachev** [sumatrapdfreader/sumatrapdf#798]
Please add context menu or keyboard shortcut for open current file in other program.

I'm using SumatraPDF as the main pdf reader because it's lightweight and has tabs. But sometimes I want to look on pdf in Adobe Reader with with subpixel rendering. It would be handy if the action for opening file in external program would be built into the program.

**Comment by kjk** [comment]
It's already there in File menu. We auto-detect most popular programs (like Adobe Reader) and you can add your own. See https://www.notion.so/Customize-external-viewers-15eb2979c4e4478296473898d3ce81fa

**Comment by danil-tolkachev** [comment]
Thank you. Sorry for inattention.
