### ISSUE TITLE
Update links in app's About dialog

### ISSUE THREAD

**Issue by SumatraPeter** [sumatrapdfreader/sumatrapdf#799]
**website**:  Would be better to link to https://www.sumatrapdfreader.org/ (https) directly instead of http

**manual**: Same as above, would be better to link to https://www.sumatrapdfreader.org/manual.html (https) directly instead of http

**forums**: Currently still links to http://blog.kowalczyk.info/forum_sumatra which in turn redirects to http://forums.fofou.org/sumatrapdf/. Should be updated to link to https://www.sumatrapdfreader.org/forum.html (https) instead.

**Comment by SumatraPeter** [comment]
@kjk So I see that https://www.sumatrapdfreader.org/forum.html now redirects to https://forum.sumatrapdfreader.org/. Would it make sense to update the app link to the latter to skip the redirection, or would it be best to leave it as the former?

**Comment by kjk** [comment]
Good point, fixed with https://github.com/sumatrapdfreader/sumatrapdf/commit/0b59d225f749a6530b1dca0fee7e5eafebb2702a
