### ISSUE TITLE
Zooming problem in MOBI file

### ISSUE THREAD

**Issue by ArijitB** [sumatrapdfreader/sumatrapdf#80]
can not zoom in any MOBI file using the methods written in manual

**Comment by BugZappr** [comment]
It's not working on .mobi's or .epub's for me either.  Just changing the font size would help on displays on really high resolution settings.

**Comment by GitHubRulesOK** [comment]
@kjk this is strictly not an open issue more the difference in the UI behaviour it may be worth explaining in the "manual" page that whilst zoom is available in chm mode, search is not, and neither are available in e-book mode.

**Comment by zydxhs** [comment]
It would be nice to have some common action buttons on the toolbar.

**Comment by GitHubRulesOK** [comment]
Closing as Mobi and ePub requirement to zoom in e-book mode is duplicated by #1281
