### ISSUE TITLE
Page Crop view (zoom feature that ignores page margins)

### ISSUE THREAD

**Issue by ersuman** [sumatrapdfreader/sumatrapdf#800]
Crop view: allow cropping extra whitespace on left, right, top, bottom of page while reading, scrolling
for this add a zoom feature "Crop view" along with "Fit a single page" and "Fit width"

See [WPS PDF viewer](https://play.google.com/store/apps/details?id=cn.wps.moffice_eng&hl=en) of android app as a reference

**Comment by SumatraPeter** [comment]
Seems very similar to or duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/585 and https://github.com/sumatrapdfreader/sumatrapdf/issues/767.

**Comment by kjk** [comment]
Closing as dup #767
