### ISSUE TITLE
SumatraPDF shows extra text from widget

### ISSUE THREAD

**Issue by ousia** [sumatrapdfreader/sumatrapdf#801]
@kjk 

here you have an uncompressed PDF file (with `.txt` extension instead of `.pdf`): [uncompressed-a.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/980909/uncompressed-a.txt).

I don’t know why, SumatraPDF displays too much from it. I’m not a PDF expert, but the widget may have an internal title. SumatraPDF displays it:

![sumatrapdf-display](https://cloud.githubusercontent.com/assets/203767/25772313/741cd3d6-3268-11e7-9022-494d24abce3a.png)

Evince displays the file right:

![evince-display](https://cloud.githubusercontent.com/assets/203767/25772312/741cbdc4-3268-11e7-942c-3bcfd9f5cd8e.png)

And also Adobe Reader displays only the content:

![adobe-display](https://cloud.githubusercontent.com/assets/203767/25772314/741ce0f6-3268-11e7-8e3e-b619ff4e1a4a.png)

BTW, I have tested it with `SumatraPDF-prerelease-10692.exe`.

**Comment by SumatraPeter** [comment]
Even Edge displays only "contents", although the font is completely different.

**Comment by ousia** [comment]
This is the object:

```
8 0 obj
<<
  /DA (/ttbf 11.9552 Tf 1.1955 Ts 0 0 0 rg 0 0 0 RG)
  /DV <FEFF0063006F006E00740065006E00740073>
  /F 4
  /FT /Tx
  /Ff 0
  /Kids 7 0 R
  /MaxLen 1024
  /Q 1
  /Subtype /Widget
  /T <FEFF00660069006C006C0069006E006600690065006C0064003A0031>
  /V <FEFF0063006F006E00740065006E00740073>
>>
endobj
```

`/T` might contain the text that shouldn’t be displayed. But I’m only guessing.

**Comment by jiulun** [comment]
Indeed, the background text is from object
```
13 0 obj
<<
  /Length 146
>>
stream
0 g 0 G
BT
/F1 11.955168 Tf 1 0 0 1 12.35367 16.39336 Tm [<0048001C0023>-27<00320048004801A2001C0023>-27<003200480048001C0023>-27<00320048>]TJ
ET
endstream
endobj
```
The size of the annotation widget (not only the text, but also includes the rectangle area) just big enough to cover the background text. 

Here, only the text from the widget not the whole box is rendered. So, the result is "contents" overlapping with the background text "lable" blabla.

**Comment by GitHubRulesOK** [comment]
@kjk unsure how you are handling closures due to current update of MuPDF engine but this is one of several that are potentially no longer an issue and can be closed  

![Untitled](https://user-images.githubusercontent.com/12754913/68897066-a95ec980-0724-11ea-9bb9-3bb4cbdd5fe9.png)

**Comment by kjk** [comment]
Thanks @GitHubRulesOK 
Fixed in latest build: https://www.sumatrapdfreader.org/dailybuilds.html
