### ISSUE TITLE
PDF previewer handler issue with Directory Opus

### ISSUE THREAD

**Issue by ou7yang** [sumatrapdfreader/sumatrapdf#803]
Hi, I'm using Directory Opus as my default explorer. And when I preview .pdf files within DO, the first page usually didn't display immediately unless I turn the page down a little or resize the viewer panel. DO use plugins to integrate pdf handlers( http://www.pretentiousname.com/activex/ ) and it works fine with other pdf software, like pdf x-change editor.

I have tried both the stable version 3.1.2 and the latest pre-release version, no luck.

Is there a way to fix it? Thanks！

**Comment by GitHubRulesOK** [comment]
Pretentious uses Active X Handlers such as those for
Adobe Reader (PDF)
Fox-It Reader (PDF)
SumatraPDF did not target that I.Explorer method though it did in the past  support NPAPI browsers such as FireFox

Some products wrap Open Source SumatraPDF however DoPus is a commercial product and up to them to decide a means to integrate. Some users have used both together, in various ways but the relevant threads are historically https://resource.dopus.com/search?q=sumatrapdf%20order%3Alatest

Primarily SumatraPDF preview is for Windows and if Outlook or others use its features that's their bonus.
