### ISSUE TITLE
Printing speed

### ISSUE THREAD

**Issue by tomurphy78** [sumatrapdfreader/sumatrapdf#805]
Hi

We're testing out SumatraPDF to print PDF's using the command line and like it, it does what we need except...

When we print to a network printer it's slow to print, in the command line and the program.  The same PDF prints also immediately from Adobe Reader.  The pdf we're trying to print is attached.

We're testing the pre-release version built on 2017-05-04, SumatraPDF-prerelease-10692.exe

Cheers
Tom
[Sales Order.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/988580/Sales.Order.pdf)

**Comment by kjk** [comment]
That's unlikely to change. Sumatra is slow for printing.

**Comment by tomurphy78** [comment]
That's a shame, but thank you for getting back to me.

Cheers
Tom
