### ISSUE TITLE
problem loading pdf-file from current directory

### ISSUE THREAD

**Issue by gschenck** [sumatrapdfreader/sumatrapdf#807]
If I call sumatrapdf (v3.2.10704 64-bit) from commandline like this:
`sumatrapdf foo.pdf`,
i get 
`Fehler beim Öffnen von C:\Windows\system32\foo.pdf`

Maybe this is related to sumatrapdfreader/sumatrapdf@c863232?

**Comment by kjk** [comment]
Yes, that's the reason. I have to delay doing that after getting file names.

**Comment by gschenck** [comment]
Works now, thank you!
