### ISSUE TITLE
Inconsistent selection highlighting in epub/mobi

### ISSUE THREAD

**Issue by Piolie** [sumatrapdfreader/sumatrapdf#808]
Hi, I've noticed inconsistent highlighting under the epub/mobi formats. For example, if after highlighting the text shown in the picture I click Ctrl+C, this is what goes to the clipboard: `iley-Blackwell.`.

![inconsistentselect](https://cloud.githubusercontent.com/assets/20274082/26206814/2bc2363c-3bbc-11e7-93c7-da6befbbf7ac.png)

I've seen it in many documents. Some are more inconsistent than others.

**Comment by GitHubRulesOK** [comment]
The selection needs to include the whole word which may include some surrounding space it is not going to match the rendered characters exactly as it is based on an aproximation of character spacing, so here the "," is included in the capture of the underlying characters but the highlighted area does not extend that far. this is common behaviour in the FixedUI when rendering PDF. CHM E-Books etc.
![image](https://user-images.githubusercontent.com/12754913/83198637-7ebfe580-a137-11ea-8515-19e1e63638eb.png)
