### ISSUE TITLE
Repair lost Preview Handler settings

### ISSUE THREAD

**Issue by bmix** [sumatrapdfreader/sumatrapdf#811]
What can we do, when Explorer lost the setting for the preview-handler? I have set SumatraPDF to be my Explorer preview handler during install, but PDF is not registered with any preview-handler anymore, Explorer seems to have lost memory about this. Not even Acrobat Reader's. I would like to reapply this setting. The installer seems to have no repair mode (just uninstall) and, after I wasted time to trick out Windows' stupid re-registering PDF with Edge (had to delete protected default registry entries) I am always happy, when I can ensure, that nothing touches the PDF file association. So I would like to have a way to reapply the preview handler setting to be Sumatra, while not touching the fila-associations.

**Comment by kjk** [comment]
Re-running the installer should re-enable it.

**Comment by hmmmmmm** [comment]
Hi! 

Just signed in here cause of a question with the preview handler, which I'm missing. I've also got in touch with the posting https://github.com/sumatrapdfreader/sumatrapdf/issues/457 which is suggesting, that there would be an option to activate/install the handler. Unfortunaly, the option from the screnshot in 457 is missing:

![grafik](https://user-images.githubusercontent.com/29543439/27287360-9ee6b29a-5503-11e7-9265-df043646e24b.png)

Sumatra was installed before and i decided to deinstall it an then re-running the installer as suggested. But there is no checkbox in options for the handler. What should I do to activate the handler. Maybe if it's only some modifications in the registry, I would be pleased if somebody can tell me.

Regards

**Comment by kjk** [comment]
The screenshot indicates you're running 32-bit version on 64-bit windows.

Download 64-bit version (https://www.sumatrapdfreader.org/download-free-pdf-viewer.html)

**Comment by hmmmmmm** [comment]
Thank you very much, that did the trick within Explorer. The option is now visible and after installing, the preview there is now available ... but ... my Outlook is in 32bit, as it is recommended from Microsoft (and I need it in 32 bit also because of some addons) ... there I'm missing the preview. Maybe I would need there the handler in 32bit? Is there also such a 32bit preview handler which can be installed simultaneously? Or ist it a completely different story with the handler between explorer and outlook?

**Comment by kjk** [comment]
Unfortunately I'm not familiar with how Outlook preview handlers work.

**Comment by hmmmmmm** [comment]
I think it's just the same, but the 64bit preview handler cannot work in 32bit outlook. Is inside the 32bit sumatra package also a 32bit handler included? If i would know the registry settings and the dll/exe ... maybe i can install it on a 32 bit machine and extract it from there and try to implement it manually on a 64bit machine?!

**Comment by Neustradamus** [comment]
@kjk: Latest good is 3.1.2, all recents do not work correctly.
Can you fix it?

**Comment by GitHubRulesOK** [comment]
@Neustradamus you read all the threads as to why one user may see results but not another user even on same installation and even in same folder. The system decides what is found by who and when in each folder and SumatraPDF has no control over that whatsoever.

SumatraPDF provides a decoder that decoder either runs or does not run under user control settings.
currently I am in a Sandbox that will have user limitations. SYSTEM does not automatically use added filters it also notoriously has security restrictions on which download files may be previewed but if I **remove the Mark of The Web** and search for pears in French it is only the derestricted files get listed.

<img width="352" height="154" alt="Image" src="https://github.com/user-attachments/assets/5aed993d-bf19-40c3-8c9b-6d27c9e939e1" />

<img width="826" height="239" alt="Image" src="https://github.com/user-attachments/assets/30242436-7dde-4c6b-9d27-7aa54b96aa1a" />


**Thus there is nothing to fix**
