### ISSUE TITLE
Rotate "Clockwise" and "Counter-Clockwise" instead of "left" and "right

### ISSUE THREAD

**Issue by senordee** [sumatrapdfreader/sumatrapdf#813]
The toolbar buttons should read **Clockwise** and **Counter-Clockwise** instead of **Right** and **Left**. 

Saying that the document will be rotated "Left" is ambiguous, since both directions can be considered to be "left". The proposed solution eliminates that ambiguity.

**Comment by SumatraPeter** [comment]
I have nothing against the suggestion being implemented by the dev, but just wanted to say that it's hardly all *that* difficult to understand as you make it out to be. Sumatra is not the only one either making use of such terminology. Here for example are screenshots from MS Paint:

![Rotation in Paint](https://user-images.githubusercontent.com/15380332/26982595-83749b6c-4d56-11e7-9f8f-6fc7d29bd484.png)

and from Word/PowerPoint 2016:

![Rotation in Word/PowerPoint 2016](https://user-images.githubusercontent.com/15380332/26982624-9b793d58-4d56-11e7-8361-5be219bd3535.png)

Adding "90°" to both items would also suffice IMO.

**Comment by kjk** [comment]
No plans to change left/right to clockwise/counter-clockwise. Personally I find left/right easier to understand.
