### ISSUE TITLE
Bug in 3.1.2 & 3.2.0 hyphenated words at end of line not handled properly

### ISSUE THREAD

**Issue by bobvance** [sumatrapdfreader/sumatrapdf#815]
Adobe reader 11 works on the document,
In first paragraph of the attached document,
for the line that is supposed to be continued to the next
"... For your conve-
nience..."
the new line is not honored and the "nience" overstrikes the "conve-"
It happens everywhere in the document where there is a hyphenated line continuation.

[Rain Bird Sprinkler Irrigation User Guide ESP-8si.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1039741/Rain.Bird.Sprinkler.Irrigation.User.Guide.ESP-8si.pdf)

**Comment by GitHubRulesOK** [comment]
I cant see a problem, plain text extraction should be OK (overstrike should not be possible unless there are imbedded backspaces.)
```
Congratulations on purchasing a Rain Bird ESP-Si solid state controller. This manual describes how to
install, operate, and maintain your controller. Please read these instructions carefully. For your conve-
nience, we have included a Quick Reference Guide below, so you can quickly find instructions for com-
mon tasks.
```
