### ISSUE TITLE
[Feature Request] Vectorized Icons for Windows 10 display scaling compatibility

### ISSUE THREAD

**Issue by ferrazrafael** [sumatrapdfreader/sumatrapdf#816]
It would be nice that Sumatra PDF Reader use vectorized (i.e: SVG) icons internally. When using displays with higher resolution and high DPI, windows 10 offers display scaling so the icons and text doesn't gets to small. In fact when I installed windows 10 on my machine its automatically changed the display scale to better suite it.

Today the icons gets pixillated
![sem titulo](https://cloud.githubusercontent.com/assets/2457862/26661708/b33622b0-4655-11e7-8c21-f064a81317eb.png)
 as showed in the image

**Comment by SumatraPeter** [comment]
https://github.com/sumatrapdfreader/sumatrapdf/issues/326
https://github.com/sumatrapdfreader/sumatrapdf/issues/430
https://github.com/sumatrapdfreader/sumatrapdf/issues/734
https://github.com/sumatrapdfreader/sumatrapdf/issues/753
and who knows how many more...

**Comment by kjk** [comment]
Closing as duplicate of #734
