### ISSUE TITLE
[Feature Request] Interop

### ISSUE THREAD

**Issue by Stretto** [sumatrapdfreader/sumatrapdf#818]
I would like to interop with sumatra. As of now I have to hack it up using the win32 api and peer in to Sumatra to get the page number, total pages, set the view etc.

it would be nice if there was some easy way to interact/control/automate Sumatra from an external app.

I don't mind the win32 message passing and Sumatra does handle a few basic commands but no way to get information such as the current page or even set the page. We could use callbacks such as

e.g.,
Send a WM_USER message representing "get page" along with the thread ID to receive the page. Then Sumatra receives the message then sends a new message to the thread with wparam = page...

**Comment by kjk** [comment]
We already implement a lot of DDE commands (https://www.sumatrapdfreader.org/docs/DDE-Commands-43ae651b446b4f09a725f2449150a43d.html)

For other stuff, I would need to understand the use case you're trying to address and a complete list of commands needed, not just one command.
