### ISSUE TITLE
restore session after crash

### ISSUE THREAD

**Issue by msjasinski** [sumatrapdfreader/sumatrapdf#821]
SumatraPDF normally restores the last session (i.e. all tabs opened before the last closing of the application). However, after a crash (irrespective of what ir results from - the app itself, operating system, lack of power supply), it starts with an empty tab.

It would be good for the app to offer some kind of recovery (or history other than the last 10 opened docs) of the opened documents.

**Comment by kjk** [comment]
This has already been fixed for windows reboot (https://github.com/sumatrapdfreader/sumatrapdf/commit/fc708368c224fcaa128b1d96ab9ad2ea5b2ec434).

You can get that in latest pre-release https://www.sumatrapdfreader.org/prerelease.html
