### ISSUE TITLE
Page isn't a document property

### ISSUE THREAD

**Issue by mirh** [sumatrapdfreader/sumatrapdf#825]
It may sound a bit dumb, but file > properties open the "_document_ properties" window. 
Yet, page format (which as long as I can see is page-specific) is shown there as if it was a global "variable".

**Comment by GitHubRulesOK** [comment]
@kjk 
Closing since "not an Issue" as SumatraPDF is no different in following the Adobe Acrobat Standard Reader behaviour of showing current page size and document fonts etc. combined under the common heading of **File > Properties**
![image](https://user-images.githubusercontent.com/12754913/82377401-8090f700-9a1b-11ea-8072-820e71a09a32.png)

**Comment by mirh** [comment]
I'm not really sure why adobe should set the benchmark of what is just and right, rather than context or grammar, but whatever.

**Comment by GitHubRulesOK** [comment]
@mirh 
I do acknowledge your valid point about nomenclature, however one yardstick I use for "issues" is does it vary from standard practice and since Adobe is the historic authority on PDF readers, if its good enough for them ... (even if two wrongs, don't make it a rite)

**Comment by mirh** [comment]
If the market leader does something with the format, clearly it should be followed. 
Wine and acpica people both develop against whatever the Windows implementation is, rather than the official docs or standards. 

But I don't really think "the interface" is part of the package, if I can explain.

**Comment by kjk** [comment]
It is weird but there's no other obvious place to put it so we'll follow Adobe Reader.

**Comment by GitHubRulesOK** [comment]
Industry standard practice is often irrational but often based on prior art
Foxit Reader follows Adobe in showing page size under the File Document Properties display
As do Tracker the authors of Xchange viewer/editor apps
VeryPDF reader is a DRM clone of SumatraPDF so obviously they share the same code

It is only those viewers that devote screen space to status bars (including some Adobe products and there followers) where one can expect to see current "page size" as a separate constantly changing dialog.
