### ISSUE TITLE
Tabs Closing Even When Remember Opened Files Is Selected

### ISSUE THREAD

**Issue by thehaajk** [sumatrapdfreader/sumatrapdf#827]
Hello,

This is probably the third time it's happened since installing, but I'll go sometimes a week or so with my tabs reopening as they should when I start Sumatra, and then I'll start it up again and my tabs will be gone. And I have the remember opened files option selected, and the program has never crashed, so I'm not sure why it's happening. Any help would be greatly appreciated.

Thank you,

**Comment by kjk** [comment]
Can it be that it happens when you have only one file opened (which is by design because it's easy to re-open last file from home page).

**Comment by thehaajk** [comment]
I'm not sure that's the case, because I've had on average maybe five files open at once. And then if I open Sumatra sometimes by clicking the icon on Windows or click on another file and it opens the program, only that file I just clicked is there, rather than all the rest that I last had open.

**Comment by GitHubRulesOK** [comment]
@kjk 
this seems to be duplicate of generic "tabs forgotten on reboot / un-expected closure of session" issue also see
https://github.com/sumatrapdfreader/sumatrapdf/issues/865 etc.

**Comment by kjk** [comment]
Closing as dup as per suggestion.
