### ISSUE TITLE
PDF-XChange Viewer has been deprecated; Add PDF-XChange Editor as File-menu entry

### ISSUE THREAD

**Issue by kbauer** [sumatrapdfreader/sumatrapdf#828]
## Summary 

As stated on [their homepage ](https://www.tracker-software.com/product/pdf-xchange-viewer), PDF-XChange Viewer will not be supported any longer. PDF-XChange Editor is declare the successor. 

Please add it to the "Open with ..." entries in the "File" menu. 

## Details

The simplest (but not-so-clean) solution might be modifiying `ExternalViewers.cpp/GetPDFXChangePath()` to detect the presence of PDFXChangeEditor. The detection method would be very similar, judging from the registry entry:

    [HKEY_LOCAL_MACHINE\SOFTWARE\Tracker Software\PDFXEditor\3.0]
    "InstallPath"="C:\\Program Files\\Tracker Software\\PDF Editor\\"

The executeable is called `PDFXEdit.exe` instead of `PDFXCview.exe`. 

## Workaround 

For the time being, installers for PDFXChange-Viewer are still available.

**Comment by SumatraPeter** [comment]
You can also add any PDF viewer/editor etc. yourself via Settings > Advanced Options.

https://www.sumatrapdfreader.org/docs/Customize-external-viewers-15eb2979c4e4478296473898d3ce81fa.html

**Comment by GitHubRulesOK** [comment]
@kjk 
Another where autodetect should now be changed, but I have not installed a copy of Exchange\PDFXEdit.exe to confirm

**Comment by kjk** [comment]
I think I tested with the latest PDF-XChange (installed via chocolatey) so it should be auto-detected in the latest daily build https://www.sumatrapdfreader.org/dailybuilds.html

**Comment by kjk** [comment]
or maybe not, need to double-check

**Comment by GitHubRulesOK** [comment]
@kjk I am an edge case 
I have set Xchange Editor to repair and it is default PDF handler
![image](https://user-images.githubusercontent.com/12754913/109231103-dc17be80-77bd-11eb-8a01-179aad4fd2c5.png)
 but Viewer is also installed
SumatraPDF shows only Open in PDF-XChange which opens the viewer version

**Comment by GitHubRulesOK** [comment]
@kjk 
Uninstalled viewer 
SumatraPDF does not detect unorthodox use of Tracker Installation even after it is repaired (that's understandable)
Uninstalled and reinstalled as custom Editor to default location
**SumatraPDF now auto detects Standard Install of Xchange Editor**

It would be the same for other unconventional portable installs,
 I can manually add the current default handler
Which is normally Open in Edge

**Comment by kjk** [comment]
Double-checked, seems to be working.
