### ISSUE TITLE
Opening blank false file/document

### ISSUE THREAD

**Issue by Grosfaaters** [sumatrapdfreader/sumatrapdf#831]
Using document management system "DocsVision" opening added pdf from DV file, opens 2 instances of SumatraPDF - one with correct PDF file, other blank with some registry entry , for example, " Error loading C:\Users\username\AppData\Local\Temp\{5B831268-C1F7-46E6-9499-44B663A1BABA}\0 "

And every time blank instance of SumatraPDF is above correct one. With other PDF softwares no such issues. And with SumatraPDF only in that particular document management system's case, what I could see for time what I use SumatraPDF

**Comment by kjk** [comment]
That looks like a problem in DocsVision, which is nothing I can do about.

Sumatra opens the file it is told to open. I don't know how DocsVision works but apparently it invokes Sumatra incorrectly.
