### ISSUE TITLE
Symbol "&" in "Change language" (Russian)

### ISSUE THREAD

**Issue by oleguka** [sumatrapdfreader/sumatrapdf#832]
Excess symbol "&" in Russian language.
![issure](https://user-images.githubusercontent.com/29583338/27354757-12d33f7e-5622-11e7-8171-99ac4a68217c.png)

**Comment by oleguka** [comment]
And in 'Basque language' this simbol
![bagg](https://user-images.githubusercontent.com/29583338/27395361-f9e14766-56c8-11e7-9345-8ce4d4f2d29c.jpg)

**Comment by oleguka** [comment]
Extra points '...' in German language

![german](https://user-images.githubusercontent.com/29583338/27397867-307eb314-56d1-11e7-8d2e-25c82fb22e76.png)

**Comment by SumatraPeter** [comment]
"&" is used to create a keyboard shortcut, so it probably got included by mistake. Not sure about the ellipsis.
