### ISSUE TITLE
Arrows in Margins

### ISSUE THREAD

**Issue by aidan-n** [sumatrapdfreader/sumatrapdf#835]
When reading a .epub file in Sumatra, there are always arrows in the margins, which can be distracting.

Do you know what the best way is to remove them?

**Comment by SumatraPeter** [comment]
If you go to `Settings > Advanced Options` and change:

```
EbookUI [
	UseFixedPageUI = false
]
```

to

```
EbookUI [
	UseFixedPageUI = true
]
```

then EPUBs will be displayed the same way as PDFs, which means no more arrows and you can also copy/search text and so on.
