### ISSUE TITLE
Problem with version 3.1.2, version 3.0 OK

### ISSUE THREAD

**Issue by xavbill** [sumatrapdfreader/sumatrapdf#837]
Hello,
Here is a problem with version 3.1.2, version 3.0 works fine.
Thanks.
Best regards.
Xavier
[erreur bvr.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1111101/erreur.bvr.pdf)
[facture.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1111105/facture.pdf)

**Comment by SumatraPeter** [comment]
See https://github.com/sumatrapdfreader/sumatrapdf/issues/329.

**Comment by GitHubRulesOK** [comment]
@kjk effectively duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/919

**Comment by kjk** [comment]
Consolidate as #919
