### ISSUE TITLE
thin lines were not printed

### ISSUE THREAD

**Issue by StefanWitzgall** [sumatrapdfreader/sumatrapdf#838]
I have a pdf-file produced with MikTeX which contains thin line in a picture
made within the LaTeX \picture-environment.
When printing the pdf-file with the pdf-viewer coming with MikTex
the lines were printed correctly but when printing it with Sumatra 3.0
some vertikal lines were left out and with Sumatra 3.12 some vertical
lines were much brighter i.e. rarely seen in contrast with the horizontal
ones. This is essential because the files were used for exercises in school!

Btw: FoxItReader behaves in a similar way.

Is this because MikTex-texworks uses the Poopler library?

(
Poppler is a free software utility library for rendering Portable Document Format (PDF) documents. Its development is supported by freedesktop.org. It is commonly used on Linux systems,[3] and is used by the PDF viewers of the open source GNOME and KDE desktop environments.
)

[6B_M4_20170629_Loesung.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1112415/6B_M4_20170629_Loesung.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk another thin line candidate for closure
![Untitled838](https://user-images.githubusercontent.com/12754913/68906624-d919cb80-073c-11ea-90a2-4f43590cebcc.png)

**Comment by kjk** [comment]
Thanks @GitHubRulesOK 
Fixed in latest build https://www.sumatrapdfreader.org/dailybuilds.html
