### ISSUE TITLE
Some text is showing in other position

### ISSUE THREAD

**Issue by LeaTex** [sumatrapdfreader/sumatrapdf#839]
There are a few lines of text that changes position in Sumatra, as you can see in the image (left is Suamtra, right is Chrome).

![sumatra-error](https://user-images.githubusercontent.com/6115573/27707440-bd418860-5ceb-11e7-9e9d-e7ae3b7e61a9.png)

[BIEN (MAL EN SUMATRA) Voucher - Resguardo 000002856-3138598.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1113365/BIEN.MAL.EN.SUMATRA.Voucher.-.Resguardo.000002856-3138598.pdf)

**Comment by LeaTex** [comment]
Any news?

**Comment by GitHubRulesOK** [comment]
@kjk 
another one addressed by recent updates
![image](https://user-images.githubusercontent.com/12754913/73223693-df75ec00-415e-11ea-8973-348003cb9b0a.png)

**Comment by LeaTex** [comment]
so it should be working now?
i'll wait for next release.

thanks!

**Comment by kjk** [comment]
You can already use a fixed version with pre-release https://www.sumatrapdfreader.org/prerelease.html
