### ISSUE TITLE
SyncTeX 2017 update

### ISSUE THREAD

**Issue by jlaurens** [sumatrapdfreader/sumatrapdf#841]
You will find latest SyncTeX pre release at

https://github.com/jlaurens/synctex/tree/2017

could you test it ASAP ?

Thanks in advance

**Comment by kjk** [comment]
The person who added synctex support to Sumatra is no longer involved with the project and I know nothing about it, so unless someone else steps in, I'll keep the current code.

**Comment by GitHubRulesOK** [comment]
@kjk 
I have to agree that if it works dont fix it, and I don't have time to check the many functional differences across dozens of editors that depend on the current version.

Jérôme Laurens  is the original author of pdfsync/synctex so should be in a position to test expected behaviors of current branch (2017+) version 2.x

There have been a few issues raised by SumatraPDF users that potentially might be closed by an update however I suspect that **if the update is not tested for legacy support** then there could be floods of it no longer behaves the same.

Perhaps at some time have a SumatraPDF **SyncTest** branch with a PullRequest for updating from Synctex that can allow some advanced users to compare new vs old behavior ?

**Comment by GitHubRulesOK** [comment]
Just an update that the current version of synctex with potentially improved cross platform support (NOTE will need to be tested against WSL, as that is the latest flurry of issues) is now found as [current branch (2020)](https://github.com/jlaurens/synctex) version 1.2x (variously 1.21 or 1.22 ! depending on some files regressed (currently 1.23 is Work In Progress.)

**Comment by kjk** [comment]
Updated synctex to 1.21
