### ISSUE TITLE
Global settings

### ISSUE THREAD

**Issue by cbesot** [sumatrapdfreader/sumatrapdf#845]
Hi,
We now use Sumatra instead of Acrobar Reader but there is a big problem : there's no (protected) global settings.

Are you planned to do that shortly?

Thanks.

**Comment by kjk** [comment]
I don't know what "protected global settings" is.

**Comment by GitHubRulesOK** [comment]
@kjk 
this seems to be a request for DRM control at corporate level, I suggest the short answer is NO as beyond SumatraPDFs current scope of design.

**Comment by kjk** [comment]
Closing as per suggestion.
