### ISSUE TITLE
Update Freetype2

### ISSUE THREAD

**Issue by akkatracker** [sumatrapdfreader/sumatrapdf#846]
Sumatra appears to be stuck with V2.5.5 - Freetype is sitting at V2.8

Not terribly experienced with Freetype but AFAIK there isn't too much (if anything) that would be breaking. 

Is there anything that looks like it could break (aside from patches here: https://github.com/sumatrapdfreader/sumatrapdf/blob/master/ext/_patches/freetype2.patch ) ? Otherwise I am happy to update, test and PR.

**Comment by kjk** [comment]
Please do give it a try.

I can't tell how easy or hard it might be - depends on the amount of changes.

Make sure to read up on how the build system works: https://www.sumatrapdfreader.org/docs/Our-build-system-3114db56b1a54b9bb026da6b92d36a80.html

**Comment by GitHubRulesOK** [comment]
@kjk closed SumatraPDF is now 2.10

**Comment by kjk** [comment]
Yes, we've updated freetype
