### ISSUE TITLE
Feature request: list all search results at once

### ISSUE THREAD

**Issue by randomizedthinking** [sumatrapdfreader/sumatrapdf#847]
When working with a large pdf file, it is time consuming to click through many hits. It would be nice if sumatra can list all search hits at once, so user can choose from the hit list. For instance, a list control can be added to the search box, when it is clicked, sumatra can search the whole file and list hits there.

Acrobat reader has such functions, yet not implemented user friendly.

Thanks.

**Comment by SumatraPeter** [comment]
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/154

**Comment by randomizedthinking** [comment]
Given that, will close this one now. Thanks.
