### ISSUE TITLE
Drag move toggle/remove

### ISSUE THREAD

**Issue by SultrySamthepennanceman** [sumatrapdfreader/sumatrapdf#848]
Hi there. I often read Tabletop game splatbooks and take key screenshots of stuff I find and like with Greenshot, a Screenshot program. The feature of SumatraPDF which I have been using for a long time now that changes a page you're reading if you hold and drag the mouse interferes with the ability to use Greenshot's regional screenshot tool, making it impossible for me to take cropped screenshots of the content I view in your software. 

Could you please make it so that the page drag or any other action that requires mouse input whilst in presentation, full screen, or just refular mode are togglable, or at least ensured to not interefere with screenshot programs like greenshot when attempting to drag the mouse across the screen prematurely ending a screenshot?

**Comment by GitHubRulesOK** [comment]
Do you mean that whilst using the region screenshot function in Sumatrapdf
it is fouled by Greenshot needing to use the same methods
![image](https://user-images.githubusercontent.com/12754913/79806565-9d74d480-8360-11ea-8cb9-8d5366a4e567.png)
![image](https://user-images.githubusercontent.com/12754913/79806779-212ec100-8361-11ea-9c06-581ba0218995.png)

I never have problems taking screenshots of regions, windows or fullscreen without Greenshot

It would be difficult to disable different specific mouse actions for numerous unknown applications perhaps best to approach Greenshot to get them to work with applications such as PDF viewers like Acrobat etc.

**Comment by kjk** [comment]
I have no problems doing screenshots using ShareX and I don't see why Greenshot should have problems.

Either way, no plans to add such feature.
