### ISSUE TITLE
Option to Hide the Left and Right Arrow when Reading .epub

### ISSUE THREAD

**Issue by Clivian** [sumatrapdfreader/sumatrapdf#85]
Since there are mouse and keyboard hotkeys available for turning pages, these buttons are not essential. I'd like to have the option to turn them off and make the app even more minimalistic.

**Comment by kjk** [comment]
There is a limit to how much customization we're going to provide and this is beyond that limit.

**Comment by aidan-n** [comment]
Does anyone know a pdf reader that can just purely show text then?
