### ISSUE TITLE
Setting to disable 'click to advance' in presentation mode

### ISSUE THREAD

**Issue by mgeorge** [sumatrapdfreader/sumatrapdf#850]
Could we please get a setting to disable the click to advance in presentation mode.

Use case:
I like to highlight keywords and important statements with the mouse when giving presentations.  Since we record the screen/audio this means the highlighting will also appear in the recording.

When I try to clear the selection with a click I often accidentally advance to the next slide.   I usually use the mouse wheel to advance, so don't use the click to advance feature.

**Comment by GitHubRulesOK** [comment]
I agree it is annoying, however if you use F11 (Full screen) it does not have the same behaviour
If you need the background to be dark then in most cases you can in FixedPageUI section add `GradientColors = #c0ffee` (actually that's a bird shell blue) or whatever to suit your mood.

**Comment by mgeorge** [comment]
Full screen solves the 'click to advance' problem, but means you only have the page-up and page-down keys to advance a page since the other options (space bar and mouse wheel) no longer advance the page.

If I remember I can just bang the escape key to cancel the selection, but I often forget.

It is not a major problem, but would be a nice feature to have available.

**Comment by GitHubRulesOK** [comment]
@mgeorge
Not trying to argue (just simply understand limits of differences)
Using F11 (tested in current pre-release) with continuous pages I still get page forward with spacebar and the mouse wheel rolls back and forwards between pages

The Big BONUS is that you can also use the ALT key to pull up menus bookmarks etc, it is much more useful than the very simplistic F5 "Presentation" mode

**Comment by mgeorge** [comment]
Thanks for that.

I hadn't noticed the setting for continuous mode since I had always just relied on hitting F5.  Turning that off and setting the background colour does what I need.

**Comment by GitHubRulesOK** [comment]
@mgeorge 
If your a happy bunny with those settings and thus the F5 mode difference is of less value , perhaps close this issue ?
