### ISSUE TITLE
Feature request: support tiling tabs

### ISSUE THREAD

**Issue by gylns** [sumatrapdfreader/sumatrapdf#851]
It will be convenient to tile two tabs in one window just like the [Tile Tabs](https://addons.mozilla.org/en-US/firefox/addon/tile-tabs/) add-on for firefox.

**Comment by SumatraPeter** [comment]
Seems to be a duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/345

**Comment by GitHubRulesOK** [comment]
Agreed dead duck link
