### ISSUE TITLE
Images get doubled in some epub files.

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#852]
I have an epub file of a novel with full page images. For a couple of particular instances, these images get doubled. By doubled I mean if page 2 has a full-page image, page 3 will have the exact same full-paged image. This occurs through out the novel.

Although I did not find any problems with the formatting of the words, I can't be sure either because I do not known how it's supposed to like in the first place.

I am using the portable version of Sumatra v3.1.2 x64 bit on Windows 7 SP1.

**Comment by SumatraPeter** [comment]
>I can't be sure either because I do not known how it's supposed to like in the first place

Should be easy enough to confirm. Just use any other good EPUB reader app (FBReader perhaps) and check whether the images are duplicated there as well. That way you'll know if the files are to blame or Sumatra.

**Comment by blacklash123** [comment]
@SumatraPeter
There aren't any duplicate images on an EPUB reader, nor on a web broswer such as Microsoft Edge.

**Comment by SumatraPeter** [comment]
> Could this HTML file be the root cause of the doubles?

Possibly, but I'm no EPUB expert. Thing is, if other EPUB readers are ignoring the file (what was it named?) then seems Sumatra should do so too.

**Comment by GitHubRulesOK** [comment]
With significant switch of ePub engine to MuPDF in pre-release
and Without a sample  to check for any retained behaviour I am closing
