### ISSUE TITLE
Build not working openjpg issues

### ISSUE THREAD

**Issue by Stretto** [sumatrapdfreader/sumatrapdf#858]
Not sure if there is something in transit but I downloaded the sources and tried to build and got all kinds of errors. Mainly openjpg stuff. I looked in the dir and there was nothing. I manually downloaded them and stuck them in the file and was able to finish building without issue. Not sure why they are not showing up in the zip file but they wern't there. Either bug in git or something else.

**Comment by kjk** [comment]
Follow checkout instructions: https://github.com/sumatrapdfreader/sumatrapdf/blob/master/readme.md
