### ISSUE TITLE
File Association does not work

### ISSUE THREAD

**Issue by ChesterCloud** [sumatrapdfreader/sumatrapdf#862]
Option which makes SumatraPDF 3.1.2 x64 default PDF reader on Windows 10 Pro x64 1703 Build with latest updates does not work. I don't know why, but default PDF reader still Microsoft Edge... I have to associate files manually via Control Panel or by right click of mouse "Open With" context menu...

**Comment by sandybeachit** [comment]
I had this issue but with adobe reader, i dont think its a Sumatra PDF issue, but more of a Windows issue.

**Comment by SumatraPeter** [comment]
Duplicate of https://github.com/sumatrapdfreader/sumatrapdf/issues/615.

**Comment by kjk** [comment]
Closing as dup.

**Comment by kjk** [comment]
This is now tracked by #1248
