### ISSUE TITLE
epub relative path evaluation is limited to "one down".

### ISSUE THREAD

**Issue by botmtl** [sumatrapdfreader/sumatrapdf#864]
[sumatraRelativePathEval.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/1229801/sumatraRelativePathEval.zip)

This might be symptom rather than the cause, but it's very consistent.  As soon as sumatra has to show an image that is two or more folders down, it cannot read that image.  

so <img src="img1.jpg" is fine
so <img src="../img1.jpg" is fine
so <img src="../../img1.jpg" is not fine

see attached epub.

**Comment by GitHubRulesOK** [comment]
Closing as all 3 pages in recent pre-release show a red band unlike previous engine behaviour
