### ISSUE TITLE
File position when force close

### ISSUE THREAD

**Issue by robertoglxda** [sumatrapdfreader/sumatrapdf#865]
Ok, maybe not an issue, but how the 'position remembering thing' works? I know that when i close Sumatra it remembers all the files that were opened at that time, and reopen them in the same position the next startup. But if for some reason Sumatra is force closed (maybe a bsod of Windows, maybe a loss of power) Sumatra doesn't seem to remember the last position. In my case it seems to take a previous position (i think from the last time it was correctly closed). Could be possible to save the files position every X minutes, with some settings?

P.S. Sorry for the english.

**Comment by GitHubRulesOK** [comment]
@kjk 
closing as addressed by the recent changes to address loss of power / windows update as discussed and resolved in SessionData gets deleted when opening new tab #1659
