### ISSUE TITLE
Can I recast color rendering? Or, say, to "remap" a color-code

### ISSUE THREAD

**Issue by llinfeng** [sumatrapdfreader/sumatrapdf#867]
With very little knowledge about the basic elements of Sumatra, I am looking for a Sumatra equivalent to the following use-case. It is implemented in Vim, as [this gist](https://gist.github.com/llinfeng/4000131dbfd6d37831aa3b3b135e91ae).
* Purpose: to have highlighting readable on a black-and-white E-ink screen. [Such monitor can only display colors in various gray scales colors.]
* The mapping that worked: redefine the color of highlighted text (the background) to be `LightYellow`, and leave the color of the texts as they are.

**Question**: can I conduct a similar remapping of color? Say, can I achieve any one of the following?
1. Substitute the display of darker colors (e.g. [hex #95ffff](http://www.colorhexa.com/95ffff)) to be "LightYellow" ([hex #FFFFE0](http://www.colorhexa.com/ffffe0));
2. Ignore the original *color* of any `highlights` and display such object (the color of the background) to be "LightYellow" ([hex #FFFFE0](http://www.colorhexa.com/ffffe0));
3. In a more complicated manner, re-code the coloring of the following elements as:
    * Texts in a highlighting environment: white, as [hex #ffffff](http://www.colorhexa.com/ffffff)
    * The background in the highlighting environment: LightYellow, as [hex #FFFFE0](http://www.colorhexa.com/ffffe0)

Note, I am aware that I can re-assign the color for the following elements, `TextColor`, `SelectionColor` and `BackgroundColor`, through the changing the corresponding variables defined in this file: `c:/Users/UserName/AppData/Roaming/SumatraPDF/SumatraPDF-settings.txt`. According to [the documentation](https://www.sumatrapdfreader.org/settings.html) for such setting-file, I only found an option to change the color of the highlighting invoked by a Forward search.

**Comment by GitHubRulesOK** [comment]
@llinfeng 
I only just noticed this unanswered query
I think that your requirements would be document specific.

The underlying requirement to have a piece of text in one colour set on a background field of another colour is generally met by the source file format. (e.g. down to the editor)

Thus whilst in a text editor it is possible to use syntax related alterations to marked words
that similar function would not be easy in a PDF **reader** interface that also handles  multiple filetypes.

To see the limitations imposed within a PDF reader use the much wider range of change objects / art colour control settings in **Acrobat Reader** and I don't think you would get many if any of those mentioned above.

I am closing this issue as globally converting document contents on the fly (whilst potentially possible in a few Ht(X)ML cases as seen in MarkDown browsers) would be considered way beyond the expectation of a multi-formats document **reader** application.
