### ISSUE TITLE
Question: Crowd Funding (Kickstarter etc)

### ISSUE THREAD

**Issue by versavius** [sumatrapdfreader/sumatrapdf#868]
I know you guys are buys and have your own lives and Sumatra PDF is awesome i was just wondering if you ever considering doing a crowd funding campaign such as on kickstarter to raise funds to pay a developer to a bunch of jobs you have planned for Sumatra PDF that you don't have time for?

Im not suggesting adding features that are outside of the scope of the project but using the funds to make Sumatra PDF even more awesome than it is.

Plus everyone knows who you are and what Sumatra PDF is so we all know where the money will go and you wont run off with the money like some projects.

Thanks for listening :)

**Comment by kjk** [comment]
No plans to do that. Creating and managing kickstarter campaign would be a lot of work in itself.
