### ISSUE TITLE
Not all text color changes for EPUB files

### ISSUE THREAD

**Issue by crisalis** [sumatrapdfreader/sumatrapdf#87]
When a EPUB file is open, text in the bookmarks list and in the current page / total pages area remains black no matter what value TextColor is set to in the EbookUI part of SumatraPDF-settings.txt.

I usually change the background to a dark color near black and the text to a white or gray color because I value my eyes, but if I do this with EPUB files, I can't see the current page, the total pages or the bookmarks because they remain black and thus can't be distinguished from the background.

**Comment by GitHubRulesOK** [comment]
@kjk I think you addressed this in recent commit
