### ISSUE TITLE
How about translate into English or other languages?

### ISSUE THREAD

**Issue by snowluliang** [sumatrapdfreader/sumatrapdf#871]
when you read a book ,you want to know what the mean of this words. you choose it ,sumatrapdf could translate it for you ?(╥╯^╰╥)

**Comment by petrasteri** [comment]
Beware of *cough, cough* bloatware

It's a good idea to have translation *assistant*.  But it's not a good idea that SumatraPDF becomes a "Swiss Knife".

Maybe an alternative solution would be some API between SumatraPDF and some online translation: when an translation is required, SumatraPDF sends the info to that online translation service.

**Comment by snowluliang** [comment]
Thanks a lot!

**Comment by GitHubRulesOK** [comment]
Consolidate under #1280
