### ISSUE TITLE
User adjustable scrolling speed

### ISSUE THREAD

**Issue by gonnafailgre** [sumatrapdfreader/sumatrapdf#873]
Hi, I'm running Windows 10, version 1607 with a "Precision touchpad". Can an option be added in "Options..." or "Advanced Options..." for changing the scroll rate? Changing the option in Windows for "Roll the wheel one notch to scroll the following number of lines: X" does not alter the scroll rate in SumatraPDF. 

Thank you

**Comment by ahmedsadman** [comment]
Yes, this would be very useful. The keyboard scroll in Sumatra is very much slow and annoying.

**Comment by leruu** [comment]
Just came here to say I'd love to have this feature since I have a "Precision Touchpad" now. Scrolling in Sumatra now feels kind of odd compared to almost all other programs.

**Comment by lordzsolt** [comment]
Came here to say I need this... I need to lift my finger multiple times from the scroll wheel to scroll one page...

**Comment by GitHubRulesOK** [comment]
Consolidating with #606

**Comment by GitHubRulesOK** [comment]
Note in current Windows 10
Both my Logiteh and Microsoft  mouse wheels respects Windows setting of 1 line at a time as certainly 1/3 of 3 lines at a time.
