### ISSUE TITLE
Previewer not working - is regression

### ISSUE THREAD

**Issue by DaveInCaz** [sumatrapdfreader/sumatrapdf#875]
The following issue was noted to be regression in the comments but was closed:

https://github.com/sumatrapdfreader/sumatrapdf/issues/393#issuecomment-326314739

Seems like the reason to close may not have been correct.

**Comment by kjk** [comment]
There's a lot in the linked issue, I don't know what you're referring to.

If you have a problem, open a bug and describe the problem in detail.
