### ISSUE TITLE
Enable preview handler when installing in silent mode

### ISSUE THREAD

**Issue by starise** [sumatrapdfreader/sumatrapdf#876]
I'm using [Chocolatey](https://chocolatey.org/packages/sumatrapdf.install) package manager to install Sumatra PDF in my system. Choco package uses the silent installation mode:

`SumatraPDF-$version-install.exe /S`

Anyway this isn't enough to enable Sumatra as default preview handler for the system. I found #811 where @kjk recommends reinstalling the software and enable the option, but in my case I'd need to achieve the same thing by passing some parameter in silent mode.

Any suggestion? Thank you.

**Comment by kjk** [comment]
Assuming it's the same as Sumatra installer, you can use "/opt pdfpreviewer" cmd-line option.

You can use "/h" or "/help" to see all installer options.

**Comment by starise** [comment]
Same installer: it's just a wrapper for the original one. Thank you very much for the help, issue solved in a minute. For who want to achieve the same result, this is the choco command to pass suggested above option to the installer.

```powershell
choco install sumatrapdf -ia "/opt pdfpreviewer"`
```

**Comment by acicovic** [comment]
@starise this doesn't seem to work for me. Any ideas?

**Comment by GitHubRulesOK** [comment]
@acicovic 
There are different version commands when you ask installer for /help
current is
![image](https://user-images.githubusercontent.com/12754913/120320024-96e1bc00-c2d9-11eb-945d-2cb1023e8f55.png)

**Comment by acicovic** [comment]
@GitHubRulesOK thanks, it worked.
