### ISSUE TITLE
[Feature request] Search selection text in search engine

### ISSUE THREAD

**Issue by Kristinita** [sumatrapdfreader/sumatrapdf#877]
### 1. Request

It would be nice, if would be possible search selection text in search engine, Google Search for example.

### 2. Justification

**If** I read a book:

    I constantly need to find out more information about words or phrases, which I do not know.

Now I need: select text → copy text → paste text in browser search bar → press <kbd>Enter</kbd>. It may take a lot of time.

### 3. Steps to reproduce

User open any book in any supported format in SumatraPDF → user select any text, for example, `Sasha Autumn` → user press any shortcut.

### 4. Expected behavior

**<https://www.google.com/search?q=Sasha%20Autumn>** page open in user default browser.

### 5. Examples on other apps

Demonstration of expected behavior in [**Sublime Text 3**](https://www.sublimetext.com/3) with [**Sublime Bang Search**](https://github.com/bsoun/bang-search) package.

![Demo](http://i.imgur.com/UszrlCj.gif)

Thanks.

**Comment by nod5** [comment]
Seems like a niche feature. I made it as a [helper script](#746) in this gist [SumatraHelper_google_selection.ahk](https://gist.github.com/nod5/210ddbdb46c91eddf7e6c29bcf617801)

**Comment by GitHubRulesOK** [comment]
@kjk consolidate into #1280 ?

**Comment by kjk** [comment]
Consolidate into #1280

**Comment by kjk** [comment]
I've started on this functionality in d710475

Still more to do, you can track progress / add ideas in #1280
