### ISSUE TITLE
SumatraPDF prerelease bug on highlight save to smx if right single quote char in pdf filename

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#878]
Tested in SumatraPDF prerelease version , SumatraPDF-prerelease-10740-install.exe from 2017-07-14 Win10

Settings used:  Advanced Settings: AnnotationDefaults: SaveIntoDocument = false  

In that mode highlights save to external files, e.g. filename.pdf.smx . That normally works.

**Steps to reproduce the crash:**  
1. Rename any pdf file a’a.pdf  
Note: that character is "right single quotation mark", see http://www.unicodemap.org/search.asp?search=%E2%80%99 .
2. select some segment of text and press H to highlight
3. Press control+S and save with the default filename given in the save dialog.

**Expected effect:** SumatraPDF should save the highlight to a’a.pdf.smx 

**Actual effect:** SumatraPDF freezes, a blue wheel spins forever. We can force exit with right click on 
SumatraPDF taskbar icon > Close Window. Then the popup "SumatraPDF is not responding." shows, with the options "Close the program" and "Wait for the program to respond".

Maybe the bug applies to more unusual characters, I haven't researched that.

**Comment by GitHubRulesOK** [comment]
Whilst many characters are allowed in windows LFN filenames there has been a tradition of many causing problems with scripting, I am guilty of often using & which I know can cause problems with DOS scripts. I used to curse web sites that used TM or R in a circle and don't start me on the difference between a hyphen  em or en. Best to tell the user they use non conventional characters at there own risk!
You could try capturing those that are not a-z or 1-0 and accept a few specials such as a'postrophe

**Comment by GitHubRulesOK** [comment]
@kjk confirmed its still a problem that Pre-release SumatraPDF hangs when attempting to make changes to write a’a.pdf.smx I can't post as the filename is unacceptable :-) (which realy says it all)
![image](https://user-images.githubusercontent.com/12754913/71791750-fe84d080-302d-11ea-8346-098d4d15392e.png)
so can only send a surrogate pdf (you would need to copy and paste the shown name)
[a’a.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4024506/a.a.pdf)
[a a.pdf.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4024513/a.a.pdf.zip)
