### ISSUE TITLE
SumatraPDF prerelease crash on highlight save to smx in some cases where two highlights overlap

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#879]
Tested in SumatraPDF prerelease version , SumatraPDF-prerelease-10740-install.exe from 2017-07-14 Win10  

Settings used: Advanced Settings: AnnotationDefaults: SaveIntoDocument = false  

In that mode highlights save to external files, e.g. filename.pdf.smx . That normally works.  

**Steps to reproduce the crash:**
1. Open any pdf file.
2. Select text starting on one line and continuing into the next line.
3. Press H to highlight the selection.
4. Press control+S and save with the default filename given in the save dialog.
5. Close SumatraPDF
6. Open the same pdf again.
7. Select only and all of the already highlighted text on the second line. 
8. Press the highlight keyboard shortcut H. The highlight on the selected text disappears.
9. Press control+S and save with the default filename given in the save dialog.

**Expected effect:** save the change in highlight to filename.pdf.smx

**Actual effect:** The error message "SumatraPDF crashed" is shown and SumatraPDF closes.

I suspect, though not certain, this bug began with #741 . Before the steps above saved two layers of highlight without crash, I think.

**Comment by GitHubRulesOK** [comment]
It would be good either for a large block or this case a few characters if the "helper app" searched for the nearest match to **user indicated** TOP LEFT of highlight say + or - 10 units then deleted that from .smx (cant please all of the people all of the time) but should be better than current case

**Comment by GitHubRulesOK** [comment]
@kjk just to confirm with latest rewritten builds this is still present (except it is now the A key) that when SumatraPDF attempts to overwrite a file with modified end of .smx as described above only then will the crash occur
