### ISSUE TITLE
Scanned document does not render correctly

### ISSUE THREAD

**Issue by wickles** [sumatrapdfreader/sumatrapdf#88]
I have a PDF that isn't rendering correctly. Please see ZIP file for documents:

https://mega.co.nz/#!IxBhkIKK!mFwBHEs2XFIwNFZczoh4LcpR7jVKFeJeBk4i7UPpias

See hw4sol.pdf specifically. It's a scanned document but it looks like it got split into multiple layers for some reason, and cuts out most of the original content. Renders correctly in STDU viewer, Chrome, Foxit, etc, and also seems to work fine in older versions, 2.0 and earlier. Did not work in 2.5.2. See images for difference:

in STDU Viewer:
![hw4sol-stdu](https://cloud.githubusercontent.com/assets/4229542/6095965/b1add686-af2b-11e4-8143-02a322c5b164.jpg)

In Sumatra:
![hw4sol-sumatra](https://cloud.githubusercontent.com/assets/4229542/6095964/b1ad8618-af2b-11e4-9d24-b81b449df82a.jpg)

**Comment by zeniko** [comment]
Thanks for the report and the linked document/screenshots. This is a bug in versions 2.5 and 3.0 which has been fixed for the 3.1 prerelease builds (available at http://www.sumatrapdfreader.org/prerelease.html for testing). See also issue #40 for the original report.

**Comment by wickles** [comment]
Thanks!
