### ISSUE TITLE
Close (only open) tab - program doesnt close

### ISSUE THREAD

**Issue by BigJonMX** [sumatrapdfreader/sumatrapdf#881]
No a bug i suspect, but certainly weird behaviour.
When closing the last, only open, tab, the program is expected to close - like ALL other software on the market. 
BUT this program shows a yellow page, or a recently opened list, does things that are unexpected, needs more clicks and interaction, and is generally really annoying.

Please fix this very irritating behaviour

**Comment by kjk** [comment]
This is the expected behavior.

**Comment by SumatraPeter** [comment]
>When closing the last, only open, tab, the program is expected to close - like ALL other software on the market.
I absolutely *hate* that so-called 'feature' in browsers. Thankfully Firefox has provided the _browser.tabs.closeWindowWithLastTab_ setting for as long as I can remember, and I always set it to false immediately after installing the browser on any of my systems.

**Comment by BigJonMX** [comment]
"expected" ?????? 
I dont understand. I can expect it, as thats what it does. But i dont know of ANY other software that behaves like this. So its weird, yes? 
Even if you like this unusual behaviour, why force it on everybody? Why not simply put an option for users to have it like ALL other software on the planet - or the way you like it ?

**Comment by daviewales** [comment]
Workaround: https://github.com/sumatrapdfreader/sumatrapdf/discussions/2533#discussioncomment-11912609
