### ISSUE TITLE
Installer parameter /register does not work

### ISSUE THREAD

**Issue by Yvan-Masson** [sumatrapdfreader/sumatrapdf#883]
Hi,

Many thanks for this wonderful software!

I am using Windows 10 64 bits and SumatraPDF 3.1.2 64 bits. When I use the installer parameter `/register`, files do not automatically open with SumatraPDF: when I double-click on a file, a choice is displayed. I really would like to avoid that when deploying SumatraPDF.

I had a look to the registry, and SumatraPDF is indeed mentioned in:

- HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\
- HKEY_LOCAL_MACHINE\SOFTWARE\Classes
- HKCU\SOFTWARE\Classes

Regards,
Yvan

**Comment by SumatraPeter** [comment]
Most likely related to the general issues with the installer reliably registering file associations under Win10: https://github.com/sumatrapdfreader/sumatrapdf/issues/615

**Comment by Yvan-Masson** [comment]
You are right, I missed this bug report. I think my bug report can be closed as a duplicate.

**Comment by kjk** [comment]
This is now tracked by #1248

But this particular issue won't be fixed. In Win 10 it's no longer possible to achieve that simply by writing to registry. User action is needed.
