### ISSUE TITLE
when print a file , its always in portrait orientation

### ISSUE THREAD

**Issue by lowols** [sumatrapdfreader/sumatrapdf#886]

**Comment by lowols** [comment]
@kjk

**Comment by GitHubRulesOK** [comment]
@kjk  this is down to understanding print driver usage (i dont think this is a specific SumatraPDF issue)
Here are ALL 4 outputs as expected when using all the settings of a suitable driver, check the driver has a "letter rotated" or "A4 rotated" or use custom page size as well as the simple portrait/landcape option

![untitled](https://user-images.githubusercontent.com/12754913/39790202-8e53f082-532c-11e8-83c9-6b1023a41da2.PNG)
