### ISSUE TITLE
Use `git checkout` to get the code?

### ISSUE THREAD

**Issue by i-give-up** [sumatrapdfreader/sumatrapdf#887]
In readme.md, it says to use the command below to get the code

```
git checkout --recursive git@github.com:sumatrapdfreader/sumatrapdf.git
```

Is it supposed to be `git clone` instead? I'm not too familiar with the various git commands so I wonder if there are some scenarios where `git checkout` works and `git clone` doesn't.

**Comment by kjk** [comment]
Sorry about it, it should be `git clone ...`. I updated readme.
