### ISSUE TITLE
[Feature Request] Open in another PDF reader button

### ISSUE THREAD

**Issue by jlanza** [sumatrapdfreader/sumatrapdf#888]
Sumatra is great for reading but sometimes you need editing something in the document or just include some text (typewriter, note, etc.). In this case you have to move to another PDF reader and you have to look for the location of the file you are reading.

It would be great to have a button or a shortcut that enables quick open in another pdf editor you configure. PDF X-Change has this option in the status bar in the right-botton part.

![sketch](https://user-images.githubusercontent.com/180640/30418436-3a37adda-9933-11e7-8470-fa03e22ec176.png)

I think this won't make Sumatra increase the resources needed and it should be easy to implement ;) (I wish I know and can help on that)

**Comment by jlanza** [comment]
You can forget it ;) I have seen that there is such an option under File. Why haven't I noticed it before. However it will be great to be changed in order to AdobePDF to one of you option.

**Comment by SumatraPeter** [comment]
>However it will be great to be changed in order to AdobePDF to one of you option.

You can add a link to any external viewer you want. You should take some time and read [Sumatra's documentation](https://www.sumatrapdfreader.org/docs/Customize-external-viewers-15eb2979c4e4478296473898d3ce81fa.html).

**Comment by jlanza** [comment]
Sorry for that.. I didn't found it :( Bad done from my side.
