### ISSUE TITLE
Shortcut edit for next page and previous page

### ISSUE THREAD

**Issue by abyvinod** [sumatrapdfreader/sumatrapdf#89]
Hi,

I love sumatraPDF reader. A big thank you to the developers!!!

I was wondering how to edit the next page and previous page shortcuts. I want to disable the response to right arrow/left arrow key presses. Thanks once again.

Cheers,
Abraham

**Comment by GitHubRulesOK** [comment]
In effect Duplicated by multiple other requests to reassign keys thus am consolidating this request as also covered by the wider discussion in #809
