### ISSUE TITLE
Got issue "We're sorry, SumatraPDF crashed" when printing pdf on tray

### ISSUE THREAD

**Issue by hungkoala** [sumatrapdfreader/sumatrapdf#891]
Command:
SumatraPDF.exe -print-to "Brother DCP-1610NW series Printer" -print-settings bin=2 Muster_10A.pdf

![screen shot 2017-09-15 at 10 08 11 am](https://user-images.githubusercontent.com/2076651/30464794-d2776034-99fd-11e7-96ae-0893926bbfac.png)

**Comment by GitHubRulesOK** [comment]
@kjk 
Unless you have a crash report from the event this issue may possibly be down to bad file, bad driver or an unknown build of SumatraPDF
I suggest without further info it be closed as can't progress
