### ISSUE TITLE
[unarr] Please add support for split rar files

### ISSUE THREAD

**Issue by bhechinger** [sumatrapdfreader/sumatrapdf#894]
It's very common to run across split rar files and so it would be super awesome if unarr could handle that.

```
foo.rar
foo.r00
foo.r01
foo.r02
....
foo.rNN
```

Thanks!

**Comment by GitHubRulesOK** [comment]
@kjk these files are less common nowadays they were a throwback to the days of floppys each file was then 360 kb or a headdy max of 2.88 MB 
Modern storage of GB means that up to those r99 files can be concatenated and still fit on one memory stick but WHY
The time taken to re-assemble the parts outweighs any modern advantages in the compression and using such a mecanism for files over 1.44 Mb is simply unnecessary.

I propose they are a dying legacy format with exceptionaly limited usage. Unless it is a native feature of rarlib with minimal overhead or someone can provide a modern valid usage for sending partial documents into outer-space I suggest this become wontfix

**Comment by kjk** [comment]
Agreed. We switched to unrar dll for RAR support. I don't plan more work on unarr.

There's more maintained unarr port at https://github.com/selmf/unarr

**Comment by bhechinger** [comment]
I understand the reason why you shouldn't split archives. I don't split archives, it's silly. The problem (and why I opened this issue) is that I have to work with archives that I haven't created and that are split. I would still like to see support for that.

**Comment by bhechinger** [comment]
Sorry, didn't see your message @kjk I'll go bother selmf instead. :)
