### ISSUE TITLE
Better Image scaling

### ISSUE THREAD

**Issue by wellivea1** [sumatrapdfreader/sumatrapdf#896]
When there are images within a pdf, or the pdf is just a jpg embedded in one, the scaling has much more aliasing when compared to opening (and even printing) in Firefox. I can try to provide an example, but it's pretty obvious. I assume sumatrapdf is using a scaler like bilinear (or even nearest-neighbor). It should be using a filter like lanczos/Sinc (EWA filtered, preferably). There are many open-source programs that have these filters like ImageMagick, mpv, etc. And even other document viewer programs have it, mostly ones for comics though. If its a matter of rendering speed, then it should be optional, or do it by default when printing(an option like "enable higher quality rendering (slower)".

**Comment by kjk** [comment]
Image scaling in PDF is handled by mupdf.

Without an example file and a screenshot showing a difference I can't do anything.
