### ISSUE TITLE
Theme Support Plan

### ISSUE THREAD

**Issue by blake-mealey** [sumatrapdfreader/sumatrapdf#898]
First of all I'd like to say that my motivation for adding theme support to Sumatra in the first place is motivated by wanting to give it a modern face-lift, so I am not just trying to change the colours of Sumatra, but to improve the appearance in general. That said, I'd like to go about adding theme support in a more organized and thoughtful manner. To do so I want to start a conversation about all of the things that adding themes will mean for Sumatra, how it will affect existing features, and so on.

If we could compile a comprehensive list of _every_ UI element that needs to be considered for themes, that would be great. Here is a list I came up with on my own, but if there are any others please let me know.

- Splash page
  - Frequently read
  - Program information
- About SumatraPDF window
- Document Properties window
- Tab bar and tabs
  - Active, inactive, hovered tabs
  - X button
- Toolbar and icons and widgets
- Document view
  - Background
  - Document
    - Text selection
    - URLs
    - Zoom: Fit Content bounding boxes
  - Find results popup
- E-Book UI
  - Background?
  - Document
  - Pages bar and number
  - Previous page/next page buttons
- Presentation view
  - Background
  - Document
- Favorites sidebar
  - Frame and X button
  - Content
- Bookmarks sidebar
 - Frame and X button
 - Content

I also have a few questions about some of these elements we should answer before diving into development:

Toolbar
- What to do about icons? Refreshing them with modern icons that use semi-transparency (as opposed to current all-or-nothing pixels) cannot properly be done with the current rendering.
- We also currently cannot change the colour of the toolbar, which takes away from the quality of a dark theme.
- Therefore, should we remake the toolbar with custom rendering? I do not know how to do this, so I would need some help getting started.

About, Properties windows
- Why are these custom rendering unlike all of the other windows?
- Should we change these to use the same rendering as all the other windows? This will result in a more consistent application.
- Should we change all the other windows to use custom rendering? That would be a lot of work, but it would give us full control over the theme of the entire application.
- Alternatively, can we already style the windows using custom rendering (Change foreground and background colours)? This would give us cohesion without nearly as much work.
- If we do need to work with all these other windows, they should be added to the list above.

How will a user switch themes? Previously we had added a Theme menu to the Settings menu with all of the theme options under it. This still seems like a good idea unless there are any better ones.

How should we handle the existing UseSysColors option? Should it be completely thrown out?

How should we handle the old yellow colours? I noticed in some comments on the old theme improvements issue that some people really wanted their old colours back. Maybe they are the minority and just need to get over themselves, or maybe we should maintain a "Legacy" theme which keeps those colours.

How to handle "dark mode" or "contrast mode" or whatever it is to be called? Should it be separate from the theme controls? I think so. Even with a dark theme, documents should be displayed with their correct colours by default.

Looking forward to all your input :-)

**Comment by kjk** [comment]
Re: toolbar, I've updated #734 with more information.

Re: properties window. All windows use some custom rendering. ebook mode is fully custom (using mui subsystem). PDF display is a mix of custom drawing and standard controls. I wouldn't touch that code. As long as it uses common colors, it doesn't matter how it's drawn.

re: switching themes. Theme menu is fine. That code is still there. It's just disabled because themes are not fully baked. It can be easily re-enabled. For easier testing you can create a configuration (a separate build type) that enables the menu. See premake5.lua, "configurations" and how to change per-configuration flags using "filter" directive.

Re: UseSysColors. My thinking is to remove it. It introduces visual bugs that I can't reproduce (i.e. "colors are bad when I use my custom theme") so it's a support burden.

Re: old colors. It's one of those things where someone will complain regardless. Once we have theming we can add "legacy" theme or describe the right values on a web page so that people can copy&paste into settings file.

re: dark mode. Yeah, that's separate from theming.

**Comment by blake-mealey** [comment]
Re: properties window. Does this mean we should make all windows change for the current theme? Or should popup windows stay white with black foreground? In this case, properties and about windows should be made to look the same as the other windows.

**Comment by kjk** [comment]
re: properties. No strong opinion on this i.e. what you think looks better.

**Comment by LinuxOnTheDesktop** [comment]
It seems to me that on Windows 10 (build 1909), using Windows dark mode, and with Sumatra 3.2 x64, _the 'hamburger' / options menu is rendered with considerably insufficient contrast_. For, it is barely visible. Partial screenshot: 

![image](https://user-images.githubusercontent.com/47056543/83979606-2b038800-a8ff-11ea-877b-a08bc2576ea2.png)

Toggling the 'advanced option' `UseSysColors` did not help.

(Apologies if I should paste this somewhere else, for instance, at #743.)

**Comment by andybloke** [comment]
Interesting. For me after the update Sumatra isn't using the system theme, also regardless of changing `UseSystemColors`. The difference between tabs has also become very hard to see.

![image](https://user-images.githubusercontent.com/18573450/84877474-d5f70d00-b088-11ea-902d-98dd8624912c.png)

**Comment by GitHubRulesOK** [comment]
@andybloke 
Linuxonthe desktop had activated a dark "storm grey" theme using windows (to be avoided as black on near black wont work) 
![image](https://user-images.githubusercontent.com/12754913/84915245-74e52e80-b0b4-11ea-857f-63767021ad35.png)
Windows theming  is soooooo sloooooow constantly changing those colors throughout all the background processes it can take a while for me to spot any change. Much more efficient for my laptop to leave it at highest contrast of black on white and optimised for speed.

**Contrast for tabs is a seperate issue and covered at https://github.com/sumatrapdfreader/sumatrapdf/issues/559**

**Comment by LinuxOnTheDesktop** [comment]
@GitHubRulesOK 

Windows 10 theming seems a mess: for one thing, it is hard to know what is controlling what. That said: so far as I know, all that I did was enable the full dark mode in Windows, i.e. set the 'window mode' to 'dark' and set the 'default app mode' to dark as well.

Still, I did have _one_ somewhat custom setting, namely, 'show the accent colour' on 'title bar and window borders'. Disabling that gave Sumatra a white titlebar and makes the hamburger menu more visible (and all this is odd, because the accent colour is blue, which is not a colour I get on titlebars howsoever I set that aforementioned 'accent colour' setting).

**Comment by Warfenix** [comment]
pls add a dark theme :(

**Comment by WhiteChairFromIkea** [comment]
I vote up for dark theme :) For mu personally, only toolbar color advanced config is missing, I think existing Icons would survive dark background of the toolbar (I also don't care about startup window (it looks bad with dark color). Here is my dark setup, only toolbar color is missing:   

![4812l](https://user-images.githubusercontent.com/46539653/133998001-8b4b606f-cb91-4116-b470-a69727d95a7f.png)

**Comment by vngmar** [comment]
Almost 5 years and no solution?

**Comment by GitHubRulesOK** [comment]
@vngmar 
Theming is a Windows thing and MS are not good at it so less decent teeming in Windows 10 than before
![image](https://user-images.githubusercontent.com/12754913/151668321-7545f59a-2597-4ce5-a5cb-4a590e7d0866.png)

**Comment by vngmar** [comment]
@GitHubRulesOK That is actually a pretty bad answer—blame shifting. It would be better to say "we are not interested in doing that right now."

**Comment by GitHubRulesOK** [comment]
@vngmar read the thread everyone is interested including now, but I cant read/write so someone needs to alter to suit Microsoft changing methods.
 However (apart from the only one overstretched dev fixing bugs etc), there is no-one offering such large graphics alterations except the sellers that don't provide/feedback of their changes, Do you know anyone skilled in taking on the task ?

**Comment by kjk** [comment]
Canny is for voting on features so that I know which features people want the most which will help me prioritize development work. 

See https://github.com/sumatrapdfreader/sumatrapdf/discussions/2562

**Comment by shrddr** [comment]
>How will a user switch themes?
it should automatically pick up the OS setting, commonly implemented with a three way switch:
- use system setting
- use light
- use dark

**Comment by AndreaPasqualini** [comment]
What about changing all the UI elements (e.g., titlebar, toolbars, menubars, buttons, popups) to [WinUI 3](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/)? I understand that this could entail a major code overhaul, and could therefore be a major development effort, but Microsoft's [WinUI 3 Gallery](https://apps.microsoft.com/store/detail/winui-3-gallery/9P3JFPWWDZRC) gives me the impression that adapting to OS-wide preferences (e.g., dark mode, transparency/translucency effects) would not be a problem anymore. SumatraPDF would also look more modern and "feel more at home" on Windows 11. It is my understanding that WinUI 3 is available for win32 apps, too, but it is not supported for any version of Windows prior to Windows 10 v1809. This might be a major roadblock, but I do not know how many SumatraPDF users are on these older platforms, in relative terms.

I am new to Windows development and I'm currently picking up the basics. In a few months time I might be able to submit prototype code to showcase the result, if the development team is interested.
