### ISSUE TITLE
Add setting for changing sidebar (and toolbar) font size

### ISSUE THREAD

**Issue by prog-rajkamal** [sumatrapdfreader/sumatrapdf#899]
I have 1080i Screen Laptop, while using sumatara at normal display. the sidebar and toolbar appears tiny. 

And there is no option to increase the size. 

Note: I can increase size of document.  I am talking about sidebar and toolbars

Screnshot:
![image](https://user-images.githubusercontent.com/11518519/31051420-3033e2c2-a685-11e7-9545-10c40a408b61.png)

Environment:

Sumatara v3.1.2 64bit
Windows 10 home v1703
Screen resolution: 1080 (Full HD)
Windows scaling: 100%

**Comment by SumatraPeter** [comment]
I'm sure the developer would appreciate the following:

- The exact version of Sumatra you're using
- The exact version and build of Windows you're using
- The current Windows scaling level
- A screenshot of the UI issue

**Comment by prog-rajkamal** [comment]
@SumatraPeter I have updated my original comment.

**Comment by SumatraPeter** [comment]
My guess is that #734 will eventually solve your problem when hopefully a customizable toolbar with SVG icons is implemented.

**Comment by prog-rajkamal** [comment]
@SumatraPeter thanks for frequent update. 

It is good to know that you are working on this.

**Comment by GitHubRulesOK** [comment]
The size of the fonts is a system thing are you sure you want them bigger, there is not much screen left for reading.
![image](https://user-images.githubusercontent.com/12754913/73903125-04b9d700-4890-11ea-8498-9385b8961e12.png)


The Icons you can change short term
I need bigger icons for my chubby fingers on a touch screen, so I use these available in two sizes
place them in the same folder as your advanced settings file. To make whichever size you prefer rename as simply toolbar_11.bmp (that is without the height suffix of -36 or -48)
[toolbar_11.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/4163099/toolbar_11.zip)


![image](https://user-images.githubusercontent.com/12754913/73903303-a50ffb80-4890-11ea-9434-1acff2c899bc.png)

**Comment by GitHubRulesOK** [comment]
@kjk
Font size is a Windows system wide controlled setting.
I am reluctant to close this issue myself as I am unsure if you intend over-riding it for Hires displays.

**Comment by GitHubRulesOK** [comment]
@kjk 
Thanks for allowing a new override for the sidebar (ToC & Favorites) Font size

I have shown above that the toolbar FontSize follows the windows default GUI settings
given that the toolbar font affects icon placements thus may be more problematic, If you are unlikely to provide a similar GUI over-ride then I sugest this issue may be closed ?

**Comment by kjk** [comment]
Consider this done thanks to `TreeFontSize` setting (https://www.sumatrapdfreader.org/settings/settings3.3.html)
For toolbar we can open a new bug.
