### ISSUE TITLE
"Find" feature not working properly in Farsi/Persian language pdf text

### ISSUE THREAD

**Issue by lingink** [sumatrapdfreader/sumatrapdf#900]
I can find a word within the text using Google Chrome and Foxit Reader; but  SumatraPDF can't find the same word.

**Comment by SumatraPeter** [comment]
Ideally you should provide a sample Farsi/Persian PDF and examples of certain words that are in the text but don't show up on searching. I'm sure it'll be a big help to the developer who I doubt is familiar with the language.

**Comment by GitHubRulesOK** [comment]
Without a sample this issue (whist possibly valid) simply can't be progressed
