### ISSUE TITLE
Stuck at rendering

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [sumatrapdfreader/sumatrapdf#901]
Can't seem to open this file http://www65.zippyshare.com/v/TU0C263l/file.html, but Foxit and Adobe Acrobat open it just fine.

**Comment by SumatraPeter** [comment]
[The file](https://github.com/sumatrapdfreader/sumatrapdf/files/1352643/_Python_inventwithpython_3rd.pdf) opens just fine and doesn't take long to render either, even on an old system:

![python](https://user-images.githubusercontent.com/15380332/31130861-3152c040-a876-11e7-895c-0a1f72619e1f.png)

**Comment by GitHubRulesOK** [comment]
@kjk closed

**Comment by kjk** [comment]
The file is no longer accessible so can't investigate.

**Comment by SumatraPeter** [comment]
> The file is no longer accessible so can't investigate.

Just wanted to mention that I mirrored the file on GitHub in my original response above. 🙂

As I noted above some years ago, the file opened fairly quickly for me in 3.1.2 64-bit, and if anything SumatraPDF-prerelease-12003-64 seems to open it even faster. Might have been a temporary problem with the reporter's PC... In any case there was no response and thus there was no point in keeping the issue open either.
