### ISSUE TITLE
Add MIDI support

### ISSUE THREAD

**Issue by InfiniteRegression** [sumatrapdfreader/sumatrapdf#902]
Would come in handy for musicians and for people who just want to control reading with a midi capable device. Simply allow one to assign a midi message to a common function like page up/down, home, end, etc.

**Comment by kjk** [comment]
No plans to do that.

**Comment by SumatraPeter** [comment]
I wonder if any Windows software already exists that'll run in the background and silently map MIDI messages to global hotkeys? If it does then with that as the middle layer you can obviously achieve what you want. If you can't find anything like that then perhaps someone at a site like DonationCoder will be able to help you out.

**Comment by rehael** [comment]
> I wonder if any Windows software already exists that'll run in the background and silently map MIDI messages to global hotkeys?

There is something like that – not very user friendly (requires scripting), but it's doable.

http://andersmalmgren.github.io/FreePIE/

https://gist.github.com/PWBENNETT/28ee05249d3da1de1b083075380148f4
