### ISSUE TITLE
/x installer option extracts to wrong directory

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#903]
Reported in https://forum.sumatrapdfreader.org/t/which-installer/461.

It's probably related to the directory change made for not locking the current directory.

**Comment by SumatraPeter** [comment]
> It's probably related to the directory change made for not locking the current directory.

Yikes! I was quite happy to see #536 finally fixed, so hopefully there's no regression there while trying to fix this issue.

**Comment by GitHubRulesOK** [comment]
@kjk I personally think this issue needs addressing during current builds, and ideally ? new installer could check and remove or warn of any historically dropped in SysWow64 by past behaviors.

**Comment by kjk** [comment]
This seems to be fixed.

**Comment by GitHubRulesOK** [comment]
@kjk I agree this issue should be closed /x works in the expected location 
Either a correctly opened cmd prompt (in the same directory) OR a shotcut with -X work both by default
The related new issue is that it appears it does not extract ALL files if the installer logic detects components active in the system, thus I had to reboot uninstall and close running SumatraPDF to ensure the /Xtraction expanded ALL files. But that is a potential issue to watch for during support.

**Comment by kjk** [comment]
Frankly, I don't see the utility of this option at all. I'm tempted to just remove it.

**Comment by GitHubRulesOK** [comment]
It helps some anti virus/trojan paranoids like me who prefer to extract installers to check contents before invocation :-)
ALSO a feature many users depend on when building portable loader/unloaders of features not in the portable version e.g. the previewer
