### ISSUE TITLE
settings file error

### ISSUE THREAD

**Issue by zredb** [sumatrapdfreader/sumatrapdf#907]
when put the portable sumatra into program files directory(Windows) with settings file, the sumatra can't read the password in settings file. it will require the user to input the password.

**Comment by SumatraPeter** [comment]
Probably because since Vista introduced UAC, apps launched without admin privileges do not have access to system folders. Just place the portable version somewhere else - why do you want to clutter your main Windows directory anyway?

**Comment by kjk** [comment]
Like @SumatraPeter said, settings file for portable version are stored in the same directory as executable and program files directory is protected by the system, so Sumatra can't create/update settings file.

You can either install non-portable version or put portable version in some other directory.

**Comment by ThiagoPSanches** [comment]
Windows XP does not have this concept ... and does not work that way on that operating system. Right?

**Comment by SumatraPeter** [comment]
@ThiagoPSanches: That's correct, XP doesn't have UAC. That said, if you're still using such an ancient unsupported OS you probably have other things to worry about...
