### ISSUE TITLE
Configurable tab color

### ISSUE THREAD

**Issue by ScottMaclure** [sumatrapdfreader/sumatrapdf#909]
Problem: Using tabs, the active tab is a lighter grey  vs a darker grey of the other tabs. When I have only 2 tabs open, I find it hard to tell which is which. 

Suggestion: It would be nice if I could configure the text/background colors of the active/inactive tabs. I'd make the active tab blue, and leave inactive as grey.

**Comment by SumatraPeter** [comment]
Can be marked as duplicate of (take your pick): https://github.com/sumatrapdfreader/sumatrapdf/issues/343, https://github.com/sumatrapdfreader/sumatrapdf/issues/559, https://github.com/sumatrapdfreader/sumatrapdf/issues/743, https://github.com/sumatrapdfreader/sumatrapdf/issues/898

**Comment by ScottMaclure** [comment]
Closing dupe
