### ISSUE TITLE
Add right-click menu option to open containing folder

### ISSUE THREAD

**Issue by febkor** [sumatrapdfreader/sumatrapdf#911]
Hello!

I appreciate the simplicity of Sumatra, but I think there is one feature that would add value to the end user without adding much complexity.

I find the ability to open the containing folder (e.g. as in Sublime Text) very valuable. This could be useful in Sumatra if I wanted to view/edit a non-pdf file that is in the same folder as the pdf that I am viewing. Instead of having to traverse through File Explorer to get there, it would very useful to open the containing folder from Sumatra directly. 

Right-clicking on an open pdf currently gives a menu containing the options to "Copy Selection", and to "Select All". Perhaps it would be appropriate to add "Open Containing Folder" to this menu? 

I appreciate you considering this. Thank you :)

**Comment by SumatraPeter** [comment]
Was requested [at least 5 years ago](http://forums.fofou.org/sumatrapdf/topic?id=2952321) if not earlier, but never implemented. I wouldn't mind having this feature either.

**Comment by GitHubRulesOK** [comment]
[update]
as a result of investigating where a user did NOT want SumatraPDF to open the containing folder

it appears File > Rename [F2] should (by default) automatically go to the files source folder and thanks to Peter the above suggestion to right-click new window should be the desired solution

in the case of File >Save As or File > Open the folder MAY NOT always be the one with the source document

**Comment by GitHubRulesOK** [comment]
@kjk possibly closed by new feature "show in folder" ?

**Comment by kjk** [comment]
Need to ponder if adding to context menu is warranted.

**Comment by GitHubRulesOK** [comment]
@kjk more than a few requests suggest file name and path to be shown when hovering over tab
If that were to be implimented, perhaps that could include right click (context) Open folder ?

**Comment by kjk** [comment]
Yes, that would also be a good option.

**Comment by SumatraPeter** [comment]
@kjk @GitHubRulesOK: I guess we can close this since 3.2+ has `File > Show in folder`.
