### ISSUE TITLE
Colors of the PDF file are different from Acrobat Reader 

### ISSUE THREAD

**Issue by thibolu** [sumatrapdfreader/sumatrapdf#914]
Steps to reproduce:
1 open the attached PDF file with Sumatra PDF
Results
The color of the map are different from Acrobat Reader rendering
Expected result:
The pdf file should be rendered similarly to  Acrobat Reader.

[515490.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1400449/515490.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk colour balance is much better in latest builds, this issue is resolved

![image](https://user-images.githubusercontent.com/12754913/73512381-49052d00-43e1-11ea-897d-7f30420c1c88.png)

**Comment by kjk** [comment]
Seems to be fixed.
