### ISSUE TITLE
PDF background not rendered correctly

### ISSUE THREAD

**Issue by thibolu** [sumatrapdfreader/sumatrapdf#915]
Steps to reproduce:
open the attached PDF file with Sumatra PDF
Results
the black background on the first page is not rendered correctly (lot of Gray parts)
Expected result:
The pdf file should be rendered similarly to Acrobat Reader.
[681655.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1400458/681655.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk transparency works well in the latest release this issue is resolved

![image](https://user-images.githubusercontent.com/12754913/73511899-58837680-43df-11ea-9370-0527e00b7cc8.png)

**Comment by kjk** [comment]
Seems to be fixed.
