### ISSUE TITLE
VS2015 Update 3 v14.0.25431.01 Build problem in Git-2ae79919f for x86/x64 cfg=Release

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#917]
Linker display error messages in to step for build _LIBCMT.lib(exe_winmain.obj) : error LNK2001: unknown external symbol "_WinMain@16"_ and _TestApp.exe : fatal error LNK1120: unknown external symbol: 1_ for Win32 Release and x64 Release build. All over binaries build success. Build log is attached: [**buildlog.txt**](https://github.com/sumatrapdfreader/sumatrapdf/files/1404518/buildlog.txt)

**Comment by kjk** [comment]
Should be fixed.

Please be advised that I no longer use VS 2015 and most likely soon it won't be able to compile SumatraPDF because it doesn't support latest C++ feature.

I recommend upgrading to latest VS 2017 for building Sumatra.

**Comment by VictorVG** [comment]
Thank you! 2017 is, only looking at the size of its offline copy (for version 15.4.1 it is 34 GB) and the number of errors in this studio is scary.

By the way, maybe you need a script creating an offline copy for 2017 studio - mkoffln2017.cmd.zip. However, in version 15.4.0 the guys made a mistake with the certificates, but it's easy to install them in the OS selection store from the ./certificates/ directory before starting the studio installation - otherwise the studio is not installed. In 15.5 they promised to correct it. Well, it is understandable to increase the volume of telemetry sent - in 2017 everything that is collected immediately is copied to Redmond - the CIA spies are over. :)

[mkoffln2017.cmd.zip](https://github.com/sumatrapdfreader/sumatrapdf/files/1404556/mkoffln2017.cmd.zip) (I recomened cURL 7.56 or never - starting v7.56 cURL can use OpenSSL and WinSSL - whats exists on local OS).
