### ISSUE TITLE
Feature request: window split

### ISSUE THREAD

**Issue by Svetlana-T** [sumatrapdfreader/sumatrapdf#918]
When reading a pdf file I would like to be able to split window (one at the top, one at the bottom).

This would allow to browse references for academic papers and publications easily, without having to remember which page I left off at.

**Comment by SumatraPeter** [comment]
The split window feature [has been rejected] (https://github.com/sumatrapdfreader/sumatrapdf/issues/345#issuecomment-155067483) earlier.

**Comment by Gryllida** [comment]
@kjk ping please?

**Comment by GitHubRulesOK** [comment]
This need to split current file in two 
either side by side 
or one over the other 
or two separate monitors 
has been addressed as <kbd>**CTRL**</kbd><kbd>**SHIFT**</kbd><kbd>**N**</kbd>

As it Is it attempts to go to the same destination however that may not be the current page
