### ISSUE TITLE
Print::ApplyPrintSettings might be missing setting DEVMODE.dmFields

### ISSUE THREAD

**Issue by ams-tschoening** [sumatrapdfreader/sumatrapdf#920]
I'm debugging some weird printer problems using SumatraPDF in some automated fashion and during reviewing the print code, I came across what I think is a possible bug or at least some behaviour not strictly following the docs.

`ApplyPrintSettings` is [setting fields](https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/Print.cpp#L759) of the provided `DEVMODE` structure as needed, but is not as well setting `dmFields` to indicate that a field has been set. According to the [docs](https://msdn.microsoft.com/de-de/library/windows/desktop/dd183565(v=vs.85).aspx), this needs to be done if one wants fields to be recognized by printer drivers:

> Specifies whether certain members of the DEVMODE structure have been initialized. If a member is initialized, its corresponding bit is set, otherwise the bit is clear.

So, the changes made by `ApplyPrintSettings` will most likely only be recognized if the corresponding fields in `dmFields` have already been set before. I don't think this is something you can rely on and the more correct approach is to set what you have actually changed, just to make sure.

The docs for [DocumentProperties](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183576(v=vs.85).aspx) say the same:

> Modify the appropriate members of the returned DEVMODE structure and indicate which members were changed by setting the corresponding bits in the dmFields member of the DEVMODE.

**Comment by kjk** [comment]
This has been fixed long time ago in https://github.com/sumatrapdfreader/sumatrapdf/commit/0cd60b11ea5f5255ae81032faf63642619fa8d0a
