### ISSUE TITLE
mathematical symbols in epub 3.0, sumatrapdf shows rudely 

### ISSUE THREAD

**Issue by librix** [sumatrapdfreader/sumatrapdf#926]
I have a epub/mobi book full of math symbols, when I use sumatrapdf open it, typography is rudely and some symbol appears error.I think it may a bug.

**Comment by SumatraPeter** [comment]
You should attach or link to the problem file(s) if possible, so that the dev can take a look at them (if the file isn't large you can attach it to your comment here on GitHub itself).

**Comment by librix** [comment]
thanks for your attention, I upload it to mega,so you can perview it with sumatrapdf. @SumatraPeter

**Comment by GitHubRulesOK** [comment]
@kjk similar to another issue where support for Superscript and Subscript were raised as the issue e-pub is not a good format for inline math here the authors workaround is to intersperse text with images causing some reader issues.
The title refers to file suposedly as epub 3.0 (which in general is stated as "not fully supported" by current MuPDF) I suggest that if other epub 3.0 readers behave better this issue might be flagged as "MuPDF" until any such 3.0 feature improvement is forthcoming

**Comment by GitHubRulesOK** [comment]
@kjk perhaps consolidate the sub/superscript issue #45 with this one which covers a wider range of math support issues

**Comment by kjk** [comment]
This should be fixed in latest pre-release https://www.sumatrapdfreader.org/prerelease
