### ISSUE TITLE
Long to start at first launch due to font loading

### ISSUE THREAD

**Issue by yannicka** [sumatrapdfreader/sumatrapdf#927]
Read: http://forums.fofou.org/sumatrapdf/topic?id=3185280

I've the same issue: when SumatraPDF loads for the first time on my Windows 10, it is slow to opens the PDF. It's because I've a lot of fonts on my computer. The same happens on Windows 8.1.

It would be good to load only needed fonts or cache fonts for a while (and have a button to clear the cache).

**Comment by GitHubRulesOK** [comment]
Above link no longer works but luckily archive copy shows

> SumatraPDF 3.1.2 x64 Windows 10 slow opening
> When I try to open a PDF file, it hangs on an blank screen and takes 10-20 seconds to display the pdf. I tried it in Windows 7 and 8.1 and it loads instaltly. I tried it in a fresh install of Windows 10 and loadds PDF instantly, but when I install my font collection (2000-3000 fonts), this problem of slow PDF opening appears. Only takes in Windows 10; in Windows 7 and 8.1 with the same fonts installed loads PDF instantly. Thanks and hope for a fix soon.

@yannicka if possible can you confirm if this is still a problem for you
or test a recent 3.2 or [pre-release](https://www.sumatrapdfreader.org/prerelease.html) for such behaviour

**Comment by yannicka** [comment]
I no longer use Windows, so I can't test, sorry.

**Comment by GitHubRulesOK** [comment]
@kjk 
unknown how Windows system font handling may have changed between versions, can you ascertain if this edge case issue is still valid ?

**Comment by kjk** [comment]
I don't see what I can do about it. 

When a font is missing, we scan system fonts for a match. 

To do that, we need to parse font files for their metadata. If there are thousands of fonts, that takes time.
