### ISSUE TITLE
Can't build after Git commit c89174f05

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#930]
VS 2017 v15.4.4 error's log is:

> Git commit c89174f05
> 
> x86:
> 
> Severity Code Description Project File String Suppression State
> Error MSB3073 exit the command "cd ../rel & ..\bin\MakeLZSA.exe InstallerData.dat SumatraPDF-no-MUPDF.exe: SumatraPDF.exe libmupdf.dll: libmupdf.dll PdfFilter.dll: PdfFilter.dll PdfPreview. dll: PdfPreview.dll Uninstaller.exe: uninstall.exe ..\mupdf\resources\fonts\droid\DroidSansFallback.ttf: DroidSansFallback.ttf
> : VCEnd "with code 2. Installer.\Microsoft Visual Studio\2017\...\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets 123
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 111
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 137
> Error C2440 <function-style-cast>: it is impossible to convert "initializer list" to "ByteWriterLE" MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 168
> Error C2228 The expression to the left of ".Write32" should represent the class, structure, or union of MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 168
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments utils C:\dev\SumatraPDF\source\src\utils\ZipUtil.cpp 129
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments utils C:\dev\SumatraPDF\source\src\utils\ZipUtil.cpp 145
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments utils C:\dev\SumatraPDF\source\src\utils\ZipUtil.cpp 224
> Error C2039 string_view: is not a member of the "std" signfile C:\dev\SumatraPDF\source\src\utils\BaseUtil.h 430
> Error C3646 AllocString: unknown override specifier signfile C:\dev\SumatraPDF\source\src\utils\BaseUtil.h 430
> Error C2059 syntax error: (signfile C:\dev\SumatraPDF\source\src\utils\BaseUtil.h 430
> Error C2238 unexpected tokens before ";" signfile C:\dev\SumatraPDF\source\src\utils\BaseUtil.h 430
> Error LNK1181 can not open the input file "C:\dev\SumatraPDF\source\rel\utils.lib" plugin-test C:\dev\SumatraPDF\source\vs2017\LINK 1
> Error LNK1181 can not open the input file "C:\dev\SumatraPDF\source\rel\utils.lib" enginedump C:\dev\SumatraPDF\source\vs2017\LINK 1
> Error LNK1181 can not open the input file "C:\dev\SumatraPDF\source\rel\utils.lib" SumatraPDF C:\dev\SumatraPDF\source\vs2017\LINK 1
> Error LNK1181 can not open the input file "C:\dev\SumatraPDF\source\rel\utils.lib" PdfPreview C:\dev\SumatraPDF\source\vs2017\LINK 1
> Error LNK1181 can not open the input file "C:\dev\SumatraPDF\source\rel\utils.lib" PdfFilter C:\dev\SumatraPDF\source\vs2017\LINK 1
> Error LNK1181 can not open the input file "C:\dev\SumatraPDF\source\rel\utils.lib" SumatraPDF-no-MUPDF C:\dev\SumatraPDF\source\vs2017\LINK 1
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 83
> 
> x64:
> 
> Severity Code Description Project File String Suppression State
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 83
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 111
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 137
> Error C2440 <function-style-cast>: it is impossible to convert "initializer list" to "ByteWriterLE" MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 168
> Error C2228 The expression to the left of ".Write32" should represent the class, structure, or union of MakeLZSA C:\dev\SumatraPDF\source\src\tools\MakeLzSA.cpp 168
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments utils C:\dev\SumatraPDF\source\src\utils\ZipUtil.cpp 129
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments utils C:\dev\SumatraPDF\source\src\utils\ZipUtil.cpp 145
> Error C2661 ByteWriterLE :: ByteWriterLE: there is no overloaded function that takes 2 arguments utils C:\dev\SumatraPDF\source\src\utils\ZipUtil.cpp 224
> Error LNK1181 can not open the input file "C:\dev\SumatraPDF\source\rel64\utils.lib" Uninstaller C:\dev\SumatraPDF\source\vs2017\LINK 1
> Error C2039 string_view: is not a member of the "std" signfile C:\dev\SumatraPDF\source\src\utils\BaseUtil.h 430
> Error C3646 AllocString: unknown override specifier signfile C:\dev\SumatraPDF\source\src\utils\BaseUtil.h 430
> Error C2059 syntax error: (signfile C:\dev\SumatraPDF\source\src\utils\BaseUtil.h 430
> Error C2238 unexpected tokens before ";" signfile C:\dev\SumatraPDF\source\src\utils\BaseUtil.h 430
> Error LNK1181 can not open the input file "C:\dev\SumatraPDF\source\rel64\utils

results - build filed. errors log's is attached [**Git-c89174f05_build_errors_log.zip**](https://github.com/sumatrapdfreader/sumatrapdf/files/1485711/Git-c89174f05_build_errors_log.zip) in to Zip. I don't have idea thats fix this errors...

**Comment by VictorVG** [comment]
SumatraPDF v3.2 Git c7743f83d

Git 8f49bab64 up to Git c7743f83d

x86 & x64 is have  some errors, but installer compiled and myy test check success (I write simple script for prevent human errors in test).

```
C2065 error uint16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 27
Error C2146 syntax error: no ";" before the identifier "vu16" test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 27
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 27
C2065 error uint32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 27
Error C2146 syntax error: no ";" before the identifier "vu32" test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 27
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 27
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 31
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 33
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 36
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 38
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 39
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 41
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 46
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 47
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 49
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 51
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 52
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 54
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 55
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 57
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 60
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 61
C2065 error uint16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 70
Error C2146 syntax error: no ";" before the identifier "vu16" test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 70
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 70
C2065 error uint32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 70
Error C2146 syntax error: no ";" before the identifier "vu32" test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 70
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 70
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 73
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 74
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 76
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 77
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 78
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 79
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 82
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 83
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 84
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 85
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 86
Error C2065 vu32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 87
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 90
Error C2065 vu16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 91
Error C2065 int16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 98
Error C2146 syntax error: no ";" before the identifier "v16" test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 98
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 98
Error C2065 int32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 98
Error C2146 syntax error: no ";" before identifier "v32" test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 98
C2065 v32 error: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 98
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 101
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 102
C2065 v16 error: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 104
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 105
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 106
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 107
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 110
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 111
C2065 v32 error: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 112
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 113
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 114
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 115
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 118
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 119
Error C2065 int16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 126
Error C2146 syntax error: no ";" before identifier "v16" test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 126
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 126
Error C2065 int32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 126
Error C2146 syntax error: no ";" before identifier "v32" test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 126
C2065 v32 error: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 126
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 129
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 130
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 132
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 133
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 134
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 135
C2065 v32 error: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 138
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 139
C2065 v32 error: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 140
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 141
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 142
Error C2065 v32: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 143
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 146
Error C2065 v16: undeclared identifier test_util .\SumatraPDF\source\src\utils\tests\ByteOrderDecoder_ut.cpp 147
Error C2039 string_view: is not a member of the "std" signfile .\SumatraPDF\source\src\utils\BaseUtil.h 438
Error C3646 AllocString: unknown signfile override specifier .\SumatraPDF\source\src\utils\BaseUtil.h 438
Error C2059 syntax error: (signfile .\SumatraPDF\source\src\utils\BaseUtil.h 438
Error C2238 unexpected tokens before ";" signfile .\SumatraPDF\source\src\utils\BaseUtil.h 438
```

Test start use this very simple script:

```
@echo off
7z x SumatraPDF_testkit.7z -aoa -y -r > nul
rm -f SumatraPDF_testkit.7z  > nul
cp -f ./SumatraPDF/SumatraPDF-3.2.exe ./x86/
cp -f ./SumatraPDF/SumatraPDF-3.2-x64.exe ./x64/
cp -f ./tcfg/true/SumatraPDF-settings.txt ./Тест/SumatraPDF/
mv -f ./x86/* ./Тест/SumatraPDF/ > nul & rm -fR ./x86 > nul
start /wait /d %~dp0Тест\SumatraPDF\ %~dp0Тест\SumatraPDF\SumatraPDF-3.2.exe
rm -fR %~dp0Тест\SumatraPDF\sumatrapdfcache > nul
cp -f ./tcfg/false/SumatraPDF-settings.txt ./Тест/SumatraPDF/
start /wait /d %~dp0Тест\SumatraPDF\ %~dp0Тест\SumatraPDF\SumatraPDF-3.2.exe
rm -fR %~dp0Тест\SumatraPDF\sumatrapdfcache > nul
rm -f %~dp0Тест\SumatraPDF\SumatraPDF-3.2.exe %~dp0Тест\SumatraPDF\UnRAR.dll > nul
cp -f ./tcfg/true/SumatraPDF-settings.txt ./Тест/SumatraPDF/
mv -f ./x64/* ./Тест/SumatraPDF/ > nul & rm -fR ./x64 > nul
start /wait /d %~dp0Тест\SumatraPDF\ %~dp0Тест\SumatraPDF\SumatraPDF-3.2-x64.exe
rm -fR %~dp0Тест\SumatraPDF\sumatrapdfcache > nul
cp -f ./tcfg/false/SumatraPDF-settings.txt ./Тест/SumatraPDF/
start /wait /d %~dp0Тест\SumatraPDF\ %~dp0Тест\SumatraPDF\SumatraPDF-3.2-x64.exe
rm -fR %~dp0Тест\SumatraPDF\sumatrapdfcache > nul
rm -f %~dp0Тест\SumatraPDF\SumatraPDF-3.2-x64.exe %~dp0Тест\SumatraPDF\UnRAR.dll > nul
rm -fR ./tcfg ./x64 ./x86 ./Тест ./test-kit.txt ./testcase_encrypt.txt test.cmd spdftest.cmd > nul
```

**Comment by kjk** [comment]
Should be fixed now.

**Comment by VictorVG** [comment]
Thanks!

**Comment by VictorVG** [comment]
Updating Git c7743f83d to Git 047d1dd97

While not buld, the rest build success. x86 and x64:

Error C2039 string_view: is not a member of the "std" signfile .\SumatraPDF\source\src\utils\BaseUtil.h 438
Error C3646 AllocString: unknown signfile override specifier .\SumatraPDF\source\src\utils\BaseUtil.h 438
Error C2059 syntax error: (signfile .\SumatraPDF\source\src\utils\BaseUtil.h 438
Error C2238 unexpected tokens before ";" signfile .\SumatraPDF\source\src\utils\BaseUtil.h 438

**Comment by kjk** [comment]
Make sure to use latest VS 2017. VS 2015 is no longer supported and possibly earlier versions of VS 2017.

**Comment by VictorVG** [comment]
I use VS 2017 v15.4.4

**Comment by VictorVG** [comment]
I can some errors :( and can't open .cbr archive RAR5 support remove.

**Comment by VictorVG** [comment]
Git 9c067e18038fe branch master, x86 and x64, VS 2017 v15.4.4 after remove and new cloning working copy ??????? 

30> .\SumatraPDF\source\src\utils\BaseUtil.h (438): error C2039: string_view: is not a member of "std"
30> C:\Program Files (x86)\Microsoft Visual Studio\2017\...\VC\Tools\MSVC\14.11.25503\include\codecvt (18): note: see the declaration "std"
30> .\SumatraPDF\source\src\utils\BaseUtil.h (438): error C3646: AllocString: unknown override specifier
30> .\SumatraPDF\source\src\utils\BaseUtil.h (438): error C2059: syntax error: (
30> .\SumatraPDF\source\src\utils\BaseUtil.h (438): error C2238: unexpected tokens before ";"
30> The build of the project "signfile.vcxproj" is completed with an error.

SDK:

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows]
"CurrentVersion"="8.1.23107"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A]
"ProductVersion"="7.0.30319"
"ProductName"="Microsoft Windows SDK for Visual Studio 2010"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx35Tools]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows SDK .NET Framework 3.5 Multi-targeting Utilities"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx35Tools-x64]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows SDK .NET Framework 3.5 Multi-targeting Utilities (x64)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx35Tools-x86]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows SDK .NET Framework 3.5 Multi-targeting Utilities"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx40Tools]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows SDK Tools for .NET Framework 4.0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx40Tools-x64]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows SDK Tools for .NET Framework 4.0 (x64)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-NetFx40Tools-x86]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows SDK Tools for .NET Framework 4.0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-SDKTools]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows Common Utilities"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-Win32Tools]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows Utilities for Win32 Development"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-WindowsHeadersLibs]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows Headers and Libraries"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.0A\WinSDK-WinSDKIntellisenseRefAssys]
"ProductVersion"="7.0.30319"
"ComponentName"="Windows Intellisense and Reference Assemblies"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.1A]
"ProductVersion"="7.1.51106"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v7.1A\XPSupport]
"ProductVersion"="7.1.51106"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools]
"ComponentName"="Windows SDK Multi-targeting Utilities for .NET Framework 3.5"
"ProductVersion"="8.0.50727"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools-x64]
"ProductVersion"="8.0.50727"
"ComponentName"="Windows SDK Multi-targeting Utilities for .NET Framework 3.5 (x64)"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx35Tools-x86]
"ProductVersion"="8.0.50727"
"ComponentName"="Windows SDK Multi-targeting Utilities for .NET Framework 3.5"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.1A]
"ProductVersion"="8.1.51636"
"ProductName"="Microsoft .NET Framework 4.5.1 SDK"

Also installed Windows 10 SDK v10.0.16699.15.

**Comment by VictorVG** [comment]
After remove rarfile SumatraPDF can't open RAR50 archive (used for RAR 5.0.x and neever, defaullt format for RAR v5.50) than have different format whats RAR29 archive (used for RAR v2.50 - v4.20, have different archive header structure thats RAR50). unarrlib don't support RAR5 archive - I find this string in to .ext/unarr/rar/rar.c : 

```
    if (memcmp(signature, "Rar!\x1A\x07\x00", sizeof(signature)) != 0) {
        if (memcmp(signature, "Rar!\x1A\x07\x01", sizeof(signature)) == 0)
            warn("RAR 5 format isn't supported");
```
which was known for a long time, but RAR5 was decoded earlier by unrar.dll, and now it is loaded into RAM, but it is not used. At least in the Process Hacker on the Modules tab of the properties of the SumatraPDF process, it is there, but it looks like it is blocked by unarr (?)

**Comment by kjk** [comment]
Yes, rar support is currently broken.

**Comment by VictorVG** [comment]
Can we fix it with simple methods?

**Comment by VictorVG** [comment]
Compile success 37/37, RAR5 support required work.

**Comment by VictorVG** [comment]
v3.2 Git-1eefe840e  - my tests were successful, but I noticed a curious phenomenon - if for the 64-bit edition use the UnRAR.DLL library with its original name UnRAR64.dll, then the transparent monochrome color layer and the color distortion can optionally be superimposed on the image in the RAR5 container of CBR. In my tests it turned out to be yellow, and to eliminate this phenomenon it was enough to rename the library to unrar.dll.

I do not know the reasons for this phenomenon, and I will naturally check its reproducibility, but one of the possible reasons is the probable error of calculations in the CPU / GPU cluster. So the machine was 100% occupied by the parallel task of rendering a complex 3D model using the ray tracing method with 67 dynamics sources of light (it seems that sometimes even the processing power of the Xeon E5-4650 + QUADRO K6000 + Tesla M40 system is not enough :)).

**Comment by VictorVG** [comment]
Exactly - for that, I then saw the computing load influence. The machine completed the calculations and the phenomenon disappeared. And it looked so interesting that I wanted to explore it. :)
