### ISSUE TITLE
Test some eBook is failure then EbookUI [ UseFixedPageUI = false]

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#931]
Then use default code setting's
```
EbookUI [
UseFixedPageUI = false
]
```
test eBook [**internals-en.epub.zip**](https://github.com/sumatrapdfreader/sumatrapdf/files/1493396/internals-en.epub.zip) is failure:

![2](https://user-images.githubusercontent.com/906886/33102432-cef68362-cf2d-11e7-95f7-912ea4275f98.png)

but STDUView 1.6.375 also frozen on this file and before crashed :) I certainly sent a bug report to STDUViewer developers about this on March 17, 2017 when I discovered in my program in addition to the hangup and a memory leak that causes it to fall, but they are heroically silent :), and in SumatraPDF with this file there are still problems did not have.

![1](https://user-images.githubusercontent.com/906886/33102430-cb18f78e-cf2d-11e7-87e0-95a04a1e61cd.png)

I use this test kit [**SuamtraPDF_testkit.7z**](https://yadi.sk/d/721Sovqb3Ez5Ww).

**Comment by VictorVG** [comment]
Git d8aeabe18 - crashed this Access Violation, Git 13ed8e928 don't have AV, but open internals-en.epub failre as Git 11e34c8ab and latest.

**Comment by kjk** [comment]
Yep, I broke it in https://github.com/sumatrapdfreader/sumatrapdf/commit/29ebfebdb2415c3943f40b9d1b93eb81711a4a00
 (probably StrSlice.[h|cpp] changes). Looking into it.

**Comment by VictorVG** [comment]
Big thanks! **Fixed**. I mark this ibc as FIXED.
