### ISSUE TITLE
Printing issue

### ISSUE THREAD

**Issue by vafs98** [sumatrapdfreader/sumatrapdf#936]
Hello team. 

I found an issue when I try to print. Is too slow, take at least 40 seconds to print each page. 

The reader is excellent but in my work I have to print documents with 60 pages or more. So, I really appreciate if this issue get solved. 

Thanks,

**Comment by GitHubRulesOK** [comment]
Consolidating with more recent https://github.com/sumatrapdfreader/sumatrapdf/issues/1021
