### ISSUE TITLE
Saved/Printed Microsoft Word's Tables rendering contain white outlines

### ISSUE THREAD

**Issue by TohonBear** [sumatrapdfreader/sumatrapdf#94]
In SumatraPDF, tables area contain some white outline, while not in Adobe Reader. Either print with PDF printers or save as PDF, it get same results.
http://ge.tt/6pJCzHA2/v/0

**Comment by GitHubRulesOK** [comment]
@kjk similar to https://github.com/sumatrapdfreader/sumatrapdf/issues/398 narrow single table divisions and boundaries may be rendering correctly in some pdf's. Again without a current sample this one is imposible to confirm.

**Comment by kjk** [comment]
Closing as lacking test document.
