### ISSUE TITLE
[Feature Request] Sort pages from right to left in Facing view

### ISSUE THREAD

**Issue by Arasteh** [sumatrapdfreader/sumatrapdf#942]
Hi,

For many documents in right-to-left scripts (Arabic, Persian, etc.) It’s very important to have them sorted from right to left. What happens now in facing pages mode, makes RTL pages shown in wrong order.

One thing I noticed, PDF documents exported from InDesign, are shown in their correct order. So I think there should be an option that when enabled, force RTL documents to be shown right to left.

I know that there is a DisplayR2L setting for each file in SumatraPDF-settings.txt. But when I change it to true, nothing changes and the setting goes back to false on next launch.

Thanks.

**Comment by a7749a** [comment]
I would like to second this request, as the the conventional way of typeseting in Traditional and Classical Chinese also used to be right to left pagewise (characters are aligned from top to bottom though), and I believe the specification of the PDF format also accounted for this issue.
Many thanks for your years of hard work devoted to such an incredibly fast viewer on Windows machines.

**Comment by rzumer** [comment]
Thirding, and please also make it possible in book view.

**Comment by GitHubRulesOK** [comment]
Closing as these points have now been duplicated in broader request (not just facing mode) Respect page direction metadata #126

**Comment by GitHubRulesOK** [comment]
Closing as these points have now been duplicated in broader request (not just facing mode) Respect page direction metadata #1264
