### ISSUE TITLE
Cppcheck results

### ISSUE THREAD

**Issue by Friedrich2** [sumatrapdfreader/sumatrapdf#946]
Dear developers,

I've checked the src folder with Cppcheck (version 1.61). The results are attached. Expecially the two error candidates found by the program could be of interest to you. Since Github does not support XML files, the file ending must be changed to .xml to read the file using Cppcheck.

Greetings

Friedrich2
[Cppcheck_results_SumatraPDF_xml.txt](https://github.com/sumatrapdfreader/sumatrapdf/files/1565663/Cppcheck_results_SumatraPDF_xml.txt)

**Comment by Friedrich2** [comment]
One of the errors (null pointer dereference) was made deliberately to assert some condition only in debug mode. The other concerned missing square brackets behind delete <pointer to array>. The warnings are still unresolved.

**Comment by GitHubRulesOK** [comment]
@kjk @Friedrich2 
Is this now closed ?

**Comment by kjk** [comment]
@GitHubRulesOK No, need to fix some more issues flagged by cppcheck

**Comment by kjk** [comment]
All cppcheck are now fixed.
