### ISSUE TITLE
Inverse search not working for Notepad++ x64

### ISSUE THREAD

**Issue by marko-pi** [sumatrapdfreader/sumatrapdf#951]
The inverse search does not work for Notepad++ x64.

First I was trying to replace "c:\program files (x86)" with "c:\program files".  However, program was returning InverseSearchCmdLine back to old version. 

After the restart, I succeeded to make the change but "c:\program files\notepad++\notepad++.exe".  However, it says "Cannot start inverse seach command."

The error does not go away after restarting.

I am using Windows 10.

**Comment by kjk** [comment]
Those things are usually configuration errors. You must get the integration command exactly right.

I'm not an expert on this and even if I was, you didn't provide the crucial information needed to debug the issue.

You might have a better luck asking in the forum https://forum.sumatrapdfreader.org/

**Comment by marko-pi** [comment]
When I start the very same command from the command prompt, there is no problem.  There is also no problem if I copy Notepad++ to x86 folder.  There is something buggy with the program.

If you are interested in detecting and removing the bug, I can provide more information.  Just tell me which information.
