### ISSUE TITLE
Pinch zooming is not working correctly

### ISSUE THREAD

**Issue by ghost** [sumatrapdfreader/sumatrapdf#953]
When trying to pinch zoom on a page, the display shifts to the top left corner of the page and starts zooming. This makes using it on a touch enabled device impossible (win 10 tablet).

**Comment by kjk** [comment]
closing as dup of #481

**Comment by kjk** [comment]
Fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/485817ee9eb392e1f1b831c72ab936ec30d07d98
