### ISSUE TITLE
Git 19e8b266b is have build error for both 32 and 64 bit edition

### ISSUE THREAD

**Issue by VictorVG** [sumatrapdfreader/sumatrapdf#956]
VC++ 15.4.5 genarated build error in to files:

src\utils\SerializeTxt.cpp string 136 - error C2440: static_cast: can't convert type "uint8_t *"  to "float *"
src\utils\SerializeTxt.cpp string 176 - error C2440: static_cast: can't convert  type"const uint8_t *" to "float *"
src\utils\SettingsUtil.cpp string 196 - error C2440: static_cast: can't convert type "const uint8_t *" to "float *"
src\utils\SettingsUtil.cpp string 283 - error C2440: static_cast:  can't convert type  "uint8_t *" to "float *"

then linked only

libmupdf.dll
all.exe
buildcmap.exe
cmapdump.exe
efi.exe
InstallerNoData.exe
MakeLZSA.exe
mudraw.exe
mutool.exe
TestApp.exe
unarr.exe

over binary and libs can't link's.

**Comment by kjk** [comment]
Should be fixed by https://github.com/sumatrapdfreader/sumatrapdf/commit/62b2ece0646d381ea6849fd994c76ee17730e5b8

**Comment by VictorVG** [comment]
Krzysztof! With the coming New Year and many thanks! I wish you health, happiness and success!
