### ISSUE TITLE
 duplex printing

### ISSUE THREAD

**Issue by ousia** [sumatrapdfreader/sumatrapdf#96]
I wonder how hard this feature would be to be implemented, but having duplex printing available in SumatraPDF would be great.

It is described at the bottom of page 364 from the PDF spec ([direct link](https://wwwimages2.adobe.com/content/dam/Adobe/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=364)).

Many thanks for your excellent work with SumatraPDF.

**Comment by kjk** [comment]
This is the domain of printer driver, not Sumatra.

**Comment by ousia** [comment]
@kjk, of course, the printer should be capable of duplex printing.

But SumatraPDF may command duplex printing (as Adobe Reader does). As explained before, this is also part of the PDF specification.

Programming is all Greek to me, but Windows GDI has a `DeviceCapabilities` function with a `DC_DUPLEX`parameter ([documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183552%28v=vs.85%29.aspx)).

Duplex printing can be enabled (or so it seems) with `dmDuplex` ([documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183565%28v=vs.85%29.aspx)).

**Comment by ousia** [comment]
Corrected the link to PDF documentation just now in the original post.

**Comment by GitHubRulesOK** [comment]
For command line users there is a possible "duplex" or "simplex" entry but may not always be there/work in some versions
e.g. I am not sure if it was available in version 3.0 which is the fallback version for non-image printing.
SumatraPDF print dialog is contrained by the print driver
mine is manual (no duplex handler)
![image](https://user-images.githubusercontent.com/12754913/88348826-5c68d380-cd46-11ea-8a42-00b6bb18a705.png)
