### ISSUE TITLE
Annotate pdf's

### ISSUE THREAD

**Issue by Aphexus** [sumatrapdfreader/sumatrapdf#961]
I use sumatra to view sheet music pdf's and it would be a great benefit to be able to "draw" on the pdf's directly using the mouse and add text. It would simply be an overlay on the pdf and could either be saved as part of the pdf or a separate file.

I need simply to add notes and draw simple mouse scribbles(arrows, lines, etc using mouse paths) which can be deleted if necessary... probably colorized. I imagine this would not be all that difficult to do. There probably exists some open source code that could be used to manage the bulk of the work. Unfortunately I have integrated sumatra pdf in my work flow so exporting to some app such as photoshop to deal with this stuff would add a huge amount of extra time.

Thanks.

**Comment by SumatraPeter** [comment]
You can do that easily with Edge on Win10 now. Sumatra's a _reader_ app, and while I can't speak for the dev, I doubt he's going to add any sort of editing capabilities to it.

**Comment by vgturtle127** [comment]
@SumatraPeter @Aphexus I think the main reason editing features aren't going to be added is for security reasons, because fillable forms being implemented probably means things like JavaScript and other stuff having to be implemented.

**Comment by kjk** [comment]
The reason they are not implemented is that it takes a lot of effort and currently there's no-one who has enough time to implement it.

**Comment by GitHubRulesOK** [comment]
@kjk 
Primarily a request for inking as in edge chromium

**Comment by GitHubRulesOK** [comment]
Above mentioned desires are the two most basic current annotations in browsers such as Edge and Firefox
I am closing as both items are covered in generic listing https://github.com/sumatrapdfreader/sumatrapdf/issues/2485
related https://github.com/sumatrapdfreader/sumatrapdf/issues/2154 and https://github.com/sumatrapdfreader/sumatrapdf/issues/1999
