### ISSUE TITLE
Delay loading of non-visibile documents at startup

### ISSUE THREAD

**Issue by kjk** [sumatrapdfreader/sumatrapdf#963]
From https://forum.sumatrapdfreader.org/t/feature-request-trying-not-to-load-all-pdfs-at-once-at-start/830/1

When re-opening Sumatra with lots of documents, it takes time and memory to load them all.

Only load the visible tab and delay opening of others until they're accessed.

**Comment by gujjwal00** [comment]
Yes! Please add this feature.

It is specially painful if some of previously opened files were password protected because then I cant see the new file until I enter password for each file or cancel the dialog popup.

**Comment by GitHubRulesOK** [comment]
@gujjwal00 
for password-protected files consider either using the whitelist option `DefaultPasswords = ` for general passwords or for an encrypted method per file answer yes to save password for this type of future reloading

**Comment by TheMrRandomDude** [comment]
Hi. What's the status of this feature request? I've just had this idea as well.

**Comment by kjk** [comment]
It's implemented in  latest pre-release https://www.sumatrapdfreader.org/prerelease

**Comment by GitHubRulesOK** [comment]
@kjk 
I appreciate this is a never-ending stories problem but with the lazy option setting could this one be lazily closed :-)
there are still several single issues for different formats (they too are are likely to see-saw in balancing one user need against another)

**Comment by kjk** [comment]
Yes, good point.
