### ISSUE TITLE
how to build SumatraPDF with annotations enabled, like in the pre-release builds?

### ISSUE THREAD

**Issue by nod5** [sumatrapdfreader/sumatrapdf#965]
I have VS Community 2017 (installed fresh today) and have without error built SumatraPDF in these forms:
- Debug Win32
- Release Win32
- ReleasePrefast Win32

But none of those builds have annotations (highlight) working. In the debug build SumatraPDF has the debug menu command "annotation from selection". But that command has no effect - the selected text get no highlight. And shortcut key H also has no effect.

I suspect I'm missing some configuration step. But what?

**Comment by kjk** [comment]
Annotation support is always enabled in debug builds see: https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/SumatraPDF.cpp#L3467

The shortcut has changed, it's 'a' now ('h' is now for navigating down https://github.com/sumatrapdfreader/sumatrapdf/blob/master/src/SumatraPDF.cpp#L3373)

**Comment by kjk** [comment]
Also, annotation support is likely buggy, which might explain menu not working. You can set a breakpoint at the the code I linked to above to see how / what it does currently.
