### ISSUE TITLE
Time for a new stable release

### ISSUE THREAD

**Issue by DrHurt** [sumatrapdfreader/sumatrapdf#966]
The latest stable version on the website is 3.1.2

There have been so many changes and improvements to code since then. The latest prerelease is outdated too.

For example, V3.1.2 has an issue with table of contents which is fixed in the latest prerelease. As a huge fan of Sumatra, I'd like to request a new stable release. 

Another thing: Please make bookmarks collapsed by default. Or add option to make it collapsed by default. I think it would be the logical thing to do. Let users expand what they want.

**Comment by GitHubRulesOK** [comment]
@kjk 
IMHO it may help to have a formal release post J2k updates

**Comment by DrHurt** [comment]
I would like to bump this. Even a 3rd party compile of the latest code!!

**Comment by GitHubRulesOK** [comment]
@kjk in hand / nearly complete / at beta level ?

**Comment by kjk** [comment]
Sorry but I can't make any promises about timelines.

**Comment by GitHubRulesOK** [comment]
@DrHurt pre-release have always been and more recently daily builds are **1st party** compile of source code
