### ISSUE TITLE
Does not release directory file handles upon closing

### ISSUE THREAD

**Issue by m-brooks** [sumatrapdfreader/sumatrapdf#967]
V3.1.2
When you close a tab in SumatraPDF, the application does not release the handle to the file's directory back to the operating system.
A symptom of this can be seen by opening a PDF, closing its tab but leaving the application running, then trying to rename the directory within which the PDF lives.
Confirmation that it is SumatraPDF that is holding the handle to the directory can be obtained via the SysInternals Handle utility from Microsoft.

**Comment by kjk** [comment]
This should be fixed in pre-release builds http://www.sumatrapdfreader.org/prerelease.html

**Comment by SumatraPeter** [comment]
For cross-reference see https://github.com/sumatrapdfreader/sumatrapdf/issues/536
