### ISSUE TITLE
Whilst in new forum "documentation" is missing from header

### ISSUE THREAD

**Issue by GitHubRulesOK** [sumatrapdfreader/sumatrapdf#968]
As per title 
whilst in forum users are not able to see the common link to "documentation" 
re-adding it might (or more likely not) reduce some of the FAQs

As an aside it may be useful to add pre release from that page to the "downloads" page

**Comment by kjk** [comment]
Thanks for noticing.

I've updated the forum header to look the same as website header.

**Comment by SumatraPeter** [comment]
> As an aside it may be useful to add pre release from that page to the "downloads" page

+1
