### ISSUE TITLE
allow printing in other paper sizes than the default

### ISSUE THREAD

**Issue by ousia** [sumatrapdfreader/sumatrapdf#97]
I use a printer that has a paper tray for DIN A4 sheets and an extra tray for manual paper feeding.

This tray for manual feeding is perfect for different paper sizes, especially those smaller than DIN A4 (such as envelopes).

Although SumatraPDF can print in paper from the extra tray, it always expects to be the default paper size (DIN A4).

Could you implement an option that prints on what the PDF pape size specifies? (Sorry, but otherwise, it is nearly impossible [or really hard] to print on other than the default paper size.)

Just in case it helps, Adobe names this option “Choose paper source by PDF page size”.

**Comment by ousia** [comment]
I have just discovered that evince implements it as “Select page size using document page size”.

**Comment by GitHubRulesOK** [comment]
Sumatra PDF starts loading its print setting from the default printer settings
prior to user changes for current printer this causes a number of issues not just this use doc size
https://github.com/sumatrapdfreader/sumatrapdf/issues/183 (don't really understand the issue)
https://github.com/sumatrapdfreader/sumatrapdf/issues/105 (don't know how to fix it.)

**Comment by GitHubRulesOK** [comment]
@ousia can you please test latest pre-release against your usage since there have been recent changes to page detection.
If those meet some of your needs (A default of attempt nearest page size), but not all (use internal pdf actions to change page size per page), it may be worth opening a renewed issue. But remember SumatraPDF is tied to what MuPDF does with such directives, and MuPDF-GL does not do printing.

**Comment by ousia** [comment]
@GitHubRulesOK, many thanks for your message.

I don’t have access to the printer I had more than six years ago.

Testing 3.3.1 with another printer I had at work, the problem is still there.

Page is centered both horizontally (which would be great to fix the issue) and vertically, which breaks printing again.

**Comment by GitHubRulesOK** [comment]
Hmm not sure if all recent changes were in  3.3.1 but agree the last printer related merge was prior to 3.3 so should be. This thread is "page size" (with bin selection based on PDF page size) which has changed a lot

However "centring" is more related to scale thus fit / none / shrink (and in part rotation) have greater effect on that output.

**Comment by ousia** [comment]
> However "centring" is more related to scale thus fit / none / shrink (and in part rotation) have greater effect on that output.

I don’t think so. This might be the way SumatraPDF has to deal with non-standard paper sizes.

As you told me not so long ago, SumatraPDF isn’t intended for printing.

Latest version isn’t intended for attachments (it cannot simply open them [this is a viewing feature, but its loss is clearly a regression]).

Link rectangles aren’t displayed in latest version (also another regression).

Maybe my main problem with SumatraPDF is that I intend to use it with PDF documents that include interactive features.

Sorry, but if the regressions are intended or not avoided, reporting anything would be wasting time (both yours and mine).
