### ISSUE TITLE
add top most

### ISSUE THREAD

**Issue by Aphexus** [sumatrapdfreader/sumatrapdf#970]
Very simple and useful at times. It's nice to be able to read something while watching a movie, say... but to interact with the movie the window has to have focus, which hides Sumatra unless one wants to jump through hoops resizing windows(which then screws things up permanently unless one jumps through more hoops).

A simple option that will toggle top most would be very convenient.

**Comment by kjk** [comment]
There are a good enough solution for this: AutoHotKey and TruboTop (https://www.howtogeek.com/196958/the-3-best-ways-to-make-a-window-always-on-top-on-windows/)

**Comment by Aphexus** [comment]
So your solution to add addition very simple functionality that doens't take much space is to force one to use additional software? I'm sorry, but everyone in the world doesn't use AHK and some don't want to use it... It is not a solution. Adding HWND_TOPMOST and a menu command is probably about 10 lines of code at most and MANY programs support it without AHK.

So, what you think is "good enough" is not good enough for me, and I'm the one that uses this damn software on a daily basis so I think I get to decide what is good enough for me.

**Comment by SumatraPeter** [comment]
> I'm the one that uses this damn software on a daily basis so I think I get to decide what is good enough for me.

I'll just say what the dev's probably too polite to say himself - yeah, you _do_ get to decide what's best for you, but you _don't_ get to throw a tantrum and _demand_ what someone else should code for you. Unless you've forgotten, Sumatra's a completely free and open source program that you paid the grand sum of Zero bucks for. If you don't like it or it doesn't fulfil your needs just use something else, or else feel free to make the required changes to the code yourself and either submit a patch to the dev, or just use your own personal modified version.

**Comment by Aphexus** [comment]
PeterPeterCocksuckerEater: Are you an idiot? Throwing a tantrum? When did I throw a tantrum? When some other idiot tells me I have to do it his way? Did I ever say they HAD to implement it? Instead, telling me they won't because some other program can add the feature is moronic and a cop out. It would have been honest to simply say "We don't want to do it cause we don't feel like it". But no, they had to play games like you are doing. 

But idiots are idiots... and yes, the code is trivial, moron. I would submit a patch, but seeing how assholes work, why would I contribute? Since this is the type of attitudes this place has... people who pretend to see what they want to justify some stupidity(again, show me were I demanded ANYTHING!), I will in no way contribute... why should I make your life easier when you obviously don't give a shit about making my life easier.
