### ISSUE TITLE
Color Handling Issues

### ISSUE THREAD

**Issue by SteveRMorris** [sumatrapdfreader/sumatrapdf#971]
Hi, as per this post below which has a link to the PDF & Image , Sumatra seems to be having some issue with displays the colors within this PDF. Looks fine with Adobe reader.

https://forum.sumatrapdfreader.org/t/missing-gray-scaling-but-looks-correct-with-adobe/866/4

Thanks in advance @kjk

**Comment by SteveRMorris** [comment]
Hi, any thoughts on this issue?

**Comment by SteveRMorris** [comment]
Is this the correct place to log issues, any idea how long until we could expect a response?

**Comment by kjk** [comment]
Yes, this is a place to report bugs.

That being said, there's no guarantee of response. There are 469 issues currently opened and only that much time to look at them.

**Comment by SteveRMorris** [comment]
Thanks for letting me know, I will wait in line

**Comment by GitHubRulesOK** [comment]
File for reference
[971 Pdf_issue.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/4420542/971.Pdf_issue.pdf)
![image](https://user-images.githubusercontent.com/12754913/78242143-66d23980-74d9-11ea-8295-f88e1818bc85.png)

Fixed in version 3.2
