### ISSUE TITLE
[Feature Request] Goto bookmark command line support

### ISSUE THREAD

**Issue by mail2nnv** [sumatrapdfreader/sumatrapdf#973]
It would be great if a calling program could specify from the command line a jump to a bookmark with the name, similar to moving to a page with the specified number

`sumatraPdf.exe test.pdf -bookmark Bookmark1`
or
`sumatraPdf.exe test.pdf -bookmark "My Bookmark"`

**Comment by GitHubRulesOK** [comment]
@mail2nnv 
This has been available for a long time (see my answer referencing the documentation in forum) 
https://forum.sumatrapdfreader.org/t/feature-request-goto-bookmark-commandline-support/905/2

So Not an issue and can be closed

**Comment by mail2nnv** [comment]
Thank you very much for clarification
