### ISSUE TITLE
Blank lines in printed pages

### ISSUE THREAD

**Issue by boom1** [sumatrapdfreader/sumatrapdf#975]
version of Sumatra: v3.1.2 64-bit
version of the OS: windows 10 64-bit
name of the printer: Xerox WorkCentre 7545 
can you open and see the file in Sumatra: yes
what exactly happens, are there any error messages: no error messages, but all PDF documents when printed have 2 millimeters blank lines each centimeter. Printing with Edge browser works fine.
if it happens only for some files but not the others: it happens for all PDFs (since update from Windows 7 to Windows 10)
is there anything different about the files that don’t print that jumps out? : No, (but it happens since update to Windows 10)
please attach the file that doesn’t print to bug report: E.g. this one: http://www.glsh.net/media/files/Druckertest.pdf

Here is a picture of the printout (showing the blank lines):
[Scan13-1.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1736137/Scan13-1.pdf)

**Comment by GitHubRulesOK** [comment]
@kjk dupe / consolidate with https://github.com/sumatrapdfreader/sumatrapdf/issues/919

**Comment by dsdsdfsdfsfsdfsfsdf** [comment]
I have same problem (regular horizontal white lines) when printing PDF files on a XEROX J-B271 printer. I print short PDF files of approx. 2-3 pages. SumatraPDF.exe in version 3.4.6 32-bit installation. I print through the command line according to the instructions: https://www.sumatrapdfreader.org/docs/Command-line-arguments
Where is problem? 
![image](https://user-images.githubusercontent.com/99869018/224956781-62fcb891-0d08-4b6d-a98a-cfa7013b9a4d.png) Thanks.
