### ISSUE TITLE
Building from source: Difference between "Release" and "ReleasePrefast" configurations?

### ISSUE THREAD

**Issue by stackflows** [sumatrapdfreader/sumatrapdf#976]
What is the difference between the "Release" and "ReleasePrefast" configurations in the VisualStudio solution and its projects?

**Comment by kjk** [comment]
Prefast enables extended code analysis. In this mode it tells you about problems in the code that are not caught by regular compilation mode. You can ignore that configuration unless you're contributing code.

See:
* https://msdn.microsoft.com/en-us/library/d3bbz7tz.aspx
* https://www.codeproject.com/Articles/167588/Using-PREfast-for-Static-Code-Analysis
