### ISSUE TITLE
Tabs menu interface when "Use tabs" is disabled.

### ISSUE THREAD

**Issue by kaovilai** [sumatrapdfreader/sumatrapdf#978]
option to Enable hamburger menu even if tabs are disabled for minimal interface.

Alternatively put menu interface in this location (click the top left icon in the title bar to open)
![image](https://user-images.githubusercontent.com/11228024/36558434-17956fb8-17d9-11e8-8d73-12dae7c8df2b.png)

**Comment by GitHubRulesOK** [comment]
With recent updates I consider this request is now relatively invalidated
Between the Windows control Icons on the left and the Control buttons on the right there might as well be tabs driven with the "hamburger" drop down so this is as minimal as it needs to be.

Yes you do get a few more pixels of height by auto-hiding the traditional key based menu but that's not designed for mouse users.

![image](https://user-images.githubusercontent.com/12754913/73961807-33be6000-4905-11ea-9348-04c562297ba4.png)
