### ISSUE TITLE
some pdf can not open correct, such as this one.

### ISSUE THREAD

**Issue by zhj2232006** [sumatrapdfreader/sumatrapdf#979]
when I try to open this pdf doc, sumatrapdf reader said: load error.
[ddd.pdf](https://github.com/sumatrapdfreader/sumatrapdf/files/1757230/ddd.pdf)

**Comment by SumatraPeter** [comment]
You try to open a damaged PDF that Firefox, Edge, Word, QPdf etc. all complain about, and then are surprised that Sumatra fails as well?
