### ISSUE TITLE
Openin other pdf viewer

### ISSUE THREAD

**Issue by Aphexus** [sumatrapdfreader/sumatrapdf#980]
I have acrobat installed but I would like to be able to open pdf in foxit from sumatra so I can edit it. How bout adding a setting to change the pdf editor location so it can be changed?

**Comment by SumatraPeter** [comment]
> How bout adding a setting to change the pdf editor location so it can be changed?

This is where reading the documentation helps. ;)

https://www.sumatrapdfreader.org/docs/Customize-external-viewers.html

**Comment by kjk** [comment]
We have code to auto-detect FoxIt location. Must have changed since we wrote that code. Need to update that code.

**Comment by GitHubRulesOK** [comment]
@kjk 
Generally I (in common with other portable users) run portable SumatraPDF
Equally foxit and tracker x-pdf apps are also run in a portable fashion, thus there is often no "uninstall" entry

from src/ExternalViewers.cpp

33 static WCHAR* GetFoxitPath() {
34    AutoFreeW path(ReadRegStr(
35        HKEY_LOCAL_MACHINE, L"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Foxit Reader", L"DisplayIcon"));
36 if (path && file::Exists(path))

however the portable closure does not always run in stealth so a more reliable reg key detection could be

[HKEY_LOCAL_MACHINE\SOFTWARE\Foxit Software\Foxit Reader]
"InstallPath"="Drive:\\Documents and Settings\\user\\path\\Foxit Software\\Foxit Reader"
"InstallAppName"="FoxitReader.exe"

**Comment by GitHubRulesOK** [comment]
@kjk 
Since the Foxit detection has recently been updated to include Foxit Phantom editor and for all other cases there is ability to add other variants manually, then perhaps this issue is currently addressed.

**Comment by kjk** [comment]
Foxit is most likely detected in latest daily build https://www.sumatrapdfreader.org/dailybuilds.html
