### ISSUE TITLE
Dimmed/unclear letters/text

### ISSUE THREAD

**Issue by atonra** [sumatrapdfreader/sumatrapdf#981]
The problem arises viewing PDF documents.
Text is kinda dimmed and unclear comparing with the one opened in Acrobat Reader for example.
In other words it is not sharp enough, try yourself, resizing it and you'll see it clearly.  And compare with the same ebook opened in acrobat reader. The text looks like the one opened in some djvu format..like it is a picture and not the real ebook font which can be resized in any way you'd like it to.
I really prefer sumatra reader, but don't wanna harm my vision, honestly. Meanwhile going back to acrobat, though don't like it....
Have been reading different programming books, so there's no need to attach any files.
And still more - the problem arises not only with the ordinary textfont, but also with the bold text blocks, and with the code examples in courier (usually prefered for rendering the code blocks).
Hope to see it fixed. 
Tryed the beta-prerelease --- problem remains.

**Comment by GitHubRulesOK** [comment]
@kjk 
without a sample the above descriptions are unmeasurable
I loaded a pdf with vector text and zooming In (the first screen grab) accept there are natural differences in the render but cannot say SumatraPDF is worse. In fact as can be seen in second zoomed out view Acrobat fails miserably to show all the contents.
The third view is zoomed in Raster text and to my eye SumatraPDF is crisper than acrobat.?

![image](https://user-images.githubusercontent.com/12754913/73225404-7db88080-4164-11ea-9e46-093224cf2455.png)

**Comment by kjk** [comment]
The issue is vague and text rendering quality is subjective.

Either way, we do whatever mupdf does.
