### ISSUE TITLE
EPUB: Not displaying hexadecimal entities from "toc.ncx" as their character

### ISSUE THREAD

**Issue by bmix** [sumatrapdfreader/sumatrapdf#984]
An entity like `&amp;#x2122;` gets displayed literally, not as the character, it encodes in the TOC (in this case it is the ™ (tm) character).

An offending piece of code, demonstrating the issue, would be:
```xml
<navPoint class="chapter" id="12345678-xxYY-ABAB-cdef-aaBBccDDeeFF" playOrder="15">
  <navLabel>
    <text>Totally Successfull Productname;#x2122;</text>
  </navLabel>
  <content src="Text/part123.html"/>
</navPoint>
```

**Comment by bmix** [comment]
I just saw, that Calibre's eBook reader does the same. So the issue may be somewhere else, which, honestly, I don't know.

**Comment by GitHubRulesOK** [comment]
as you can see below I inserted the correct code into the TOC and it renders as &#x2122;
what was wrong in the example code given is that it will not be correct unless it has the & prefix
![image](https://user-images.githubusercontent.com/12754913/86605360-837d8200-bf9e-11ea-8b83-42ca6749d8eb.png)
