### ISSUE TITLE
EPUB: Keep positioning of pages strict

### ISSUE THREAD

**Issue by bmix** [sumatrapdfreader/sumatrapdf#985]
When I open an ePub, and have two pages being displayed next to each other, it can happen, that a page, that has been displayed on the right side, gets displayed on the left side, when I turn pages. This is inconsistent and makes my eyes go wild ;-) It would be nice, if the pages would not "fly around". Thank you.

**Comment by kjk** [comment]
I'm not sure I understand. Could you post a screenshot of this happening (the 2 cases where the same page is shown on the right and then on the left after turning page).

Is there a specific scenario when this happens?

**Comment by bmix** [comment]
The pages are shifted by one and appear at different places, if using the TOC to navigate or by just turning the pages, one by one, from the beginning by browsing with cursor keys. It would aesthetically be much more pleasing, if the pages would always be at the same position in the UI layout.

This confuses the heck out of me while reading ;-)

To illustrate:
![01](https://user-images.githubusercontent.com/310157/36935651-9ded8faa-1efa-11e8-860a-8099fe75d086.jpg)

![02](https://user-images.githubusercontent.com/310157/36935655-a5209696-1efa-11e8-9ed7-dad8b4a89601.jpg)

**Comment by SumatraPeter** [comment]
A simple workaround could have been to switch between Facing and Book Views as required, but unfortunately the latter isn't applicable to EbookUI.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
I'm not sure it is as simple as facing/book since in current pre-release only facing is available and should move two pages at a time the pictures are too fuzzy to pick up page numbering or any other clues.
what is needed as usual is the sample to test in differing versions

**Comment by SumatraPeter** [comment]
Facing and Book View both do move 2 pages at a time. The difference is that Book View displays the cover page separately and then follows up with 1+2, 3+4 etc., whereas Facing simply displays Cover+1, 2+3 etc. So depending on the requirement, for example if you have a double-page spread, you can use the appropriate view to make sure both halves are displayed together properly.

Unfortunately like I said above, Book View isn't applicable to EbookUI and only Facing is available.

**Comment by GitHubRulesOK** [comment]
@SumatraPeter 
My understanding here is that it is use of bookmarks not facing/book that is at fault
pick page 14 bookmark then page 13 bookmark and you get the effect above
The request for "Strict" seems to omply a need for ODD to always be on the left (or right)

**Comment by SumatraPeter** [comment]
Do you have a sample epub exhibiting this issue?

**Comment by GitHubRulesOK** [comment]
I used the one from #1125 in double page mode
go to bookmark 3.2 it is then on left
click on 3.1 and 3.2 is naturally on the right
consider 3.2 as photo of man eating in above

**Comment by GitHubRulesOK** [comment]
Closing as with pre-release switch to MuPDF for ePEpub 
the OP request is addressed as odds and evens stay "strict" as book or facing
