### ISSUE TITLE
Support of pdf,jpg,png..etc processed with precomp

### ISSUE THREAD

**Issue by maadjordan** [sumatrapdfreader/sumatrapdf#986]
Is it possible to add support of files processed with precomp https://github.com/schnaader/precomp-cpp  it can reduce pdf files considerably and its open source. it can handle images too but main benefit is pdf files are processed with precomp prior reading as pdf

**Comment by GitHubRulesOK** [comment]
@kjk
I Recommend this be closed as similar to some other requests, it is not a current failing by SumatraPDF

Byte modification / encryption of standard files in this fashion is unlikely  to be included in mainstream apps i.e. not likely to be part of .PDF PNG or JPG standard (although it concede it could in the future)

**Comment by kjk** [comment]
Agreed, no plans to support precomp.
