### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by aeiouzy** [sumatrapdfreader/sumatrapdf#988]
pdf-write.c     
row 2075
//fprintf(opts->out, "%%\316\274\341\277\246\n\n");       //wrong
fprintf(opts->out, "%%\xC2\xB5\xC2\xB6\n\n");                  //ok---come from mupdf-1.12.0-source

**Comment by kjk** [comment]
You can disable that warning. It's caused by using non-english OS.

See https://github.com/sumatrapdfreader/sumatrapdf/pull/375 and https://github.com/sumatrapdfreader/sumatrapdf/issues/698

**Comment by marui888** [comment]
@aeiouzy.  Change to  %%\xC2\xB5\xC2\xB6\n\n  , then compiling worked successfully.   what happend?
