### ISSUE TITLE
#include <mupdf/fitz.h>  c2664 error

### ISSUE THREAD

**Issue by aeiouzy** [sumatrapdfreader/sumatrapdf#989]
stream.h   row243
fz_warn(stm->ctx, "read error; treating as end of file");        //error
context.h  row78
#define fz_warn(CTX, MSG, ...) fz_warn_imp(CTX, __FILE__, __LINE__, MSG, __VA_ARGS__)
void fz_warn_imp(fz_context *ctx, char *file, int line, const char *fmt, ...) __printflike(4, 5);

error C2664: “void fz_warn_imp(fz_context *,char *,int,const char *,...)”: 
无法将参数 2 从“const char [55]”转换为“char *”       //const char* can't convert to char*

**Comment by kjk** [comment]
Don't reopen the same issue https://github.com/sumatrapdfreader/sumatrapdf/issues/988
