### ISSUE TITLE
Doubleclick in the top-left

### ISSUE THREAD

**Issue by thany** [sumatrapdfreader/sumatrapdf#99]
Doubleclicking the top-left corner of the window should close it, as with every windows program. Except browsers, for some reason, but normal programs don't (and shouldn't) change the way Windows windows are meant to work.

The dreaded hamburger menu. It's been busted so many times. Please, do away with it. All it does at this point is needlessly change the way the window works, and hide the standard menu into submenus, making it _more_ tedious to navigate it.

**Comment by thany** [comment]
Suggestion: loose the hamburger menu. Then, invent a button on the button bar that discloses all the functionality the menu has in it, but reworked so it's easy to navigate. Just look at MSIE, they got it right when IE7 was introduced. They got a lot of things wrong, but the menu was fine.

**Comment by GitHubRulesOK** [comment]
@kjk duplicated by #162

**Comment by kjk** [comment]
Consolidate under #162
