### ISSUE TITLE
[Feature Request] Customisable Frequently Read

### ISSUE THREAD

**Issue by AlexBlandin** [sumatrapdfreader/sumatrapdf#993]
It would be nice to have more than 10 things on the page, especially since I often want to pin a lot of different pdfs at the same time. Even just an option in the settings file to set how many appear in the Frequently Read page would be fantastic (something like StartPageFileCount = 10 as a default, allowing us to make it go higher to 20, 50, or perhaps even higher?)

**Comment by weitzhandler** [comment]
Ditto.

I'd also like to have a pin button to be able to stick important documents to the top.

**Comment by GitHubRulesOK** [comment]
@kjk perhaps consolidate with #406

**Comment by SumatraPeter** [comment]
#406 is somewhat related, but not a duplicate. Consolidating might cause this separate request to be ignored.

**Comment by GitHubRulesOK** [comment]
Since the key points of Customize / more than 10 / pinning are all covered in 406 and that also requests that it be constantly accessible I am calling this as duplicate and closing

**Comment by meseri** [comment]
"Frequently Read" tab other problems:
deleted/moved file not removed from recent list, but cycled to last position;
links to recent files are missing little[×] in upper right corner, and every computer user knows, what it's supposed to do.(it's ok to ask confirmation when deleting first file link, but when deleting multiple links, doing multi-click menu for deleting each is pita)

**Comment by GitHubRulesOK** [comment]
@meseri as a duplicate this issue is closed 
for the open issue  please read https://github.com/sumatrapdfreader/sumatrapdf/issues/283
