### ISSUE TITLE
[Feature Request] H/L left/right scrolling option

### ISSUE THREAD

**Issue by rogershijin** [sumatrapdfreader/sumatrapdf#994]
For users who zoom in on their PDFs, shortcuts for left-right scrolling would be useful.  As this might be confusing for some users, perhaps this should be an optional setting that is by default off.

**Comment by digdig** [comment]
I would like to see this feature too.

**Comment by GitHubRulesOK** [comment]
@digdig please use latest pre-release
@kjk I think this was added some time ago but I cant find the commit in history
I think it was at the time highlight had to be moved from H to A so I have seen this feature available in latest Pre-release and unless anything further changes expect it to be in next formal release
So I suggest this has been addressed and can be closed

**Comment by digdig** [comment]
@GitHubRulesOK Can you give a link of the version that works with `HJKL` navigation? Thanks.

**Comment by digdig** [comment]
https://www.sumatrapdfreader.org/prerelease.html  I've found the link @GitHubRulesOK

**Comment by GitHubRulesOK** [comment]
@kjk apparently this is still working in pre-rel and thus can be closed ?
