### ISSUE TITLE
New feature request -> single page rotate

### ISSUE THREAD

**Issue by div4d** [sumatrapdfreader/sumatrapdf#996]
Hi,
in "Preview", mac app, there is a briliant feature that let you to rotate a single page, even in a multi page pdf. I really appreciate if this feature will be added in a new release!
Thanks

**Comment by GitHubRulesOK** [comment]
Duplicate request for a function from an editor application
see PDF rotation #721

**Comment by GitHubRulesOK** [comment]
If you want to permanently rotate a page within limits yu can edit the file from within SumatraPDF
I have described adding a QPDF rotation script at 
https://forum.sumatrapdfreader.org/t/please-add-tool-for-rotating-pages-permanently/411/5
