### ISSUE TITLE
Compile error C2039 'string_view': is not a member of 'std' in baseutil.h

### ISSUE THREAD

**Issue by jmporter34** [sumatrapdfreader/sumatrapdf#997]
I'm using Microsoft Visual Studio Community 2017 version 15.6.3 (just downloaded and installed the latest update).

I'm able to build all the projects in vs2017\SumatraPDF.sln.
But when I create a cpp file in my own project and #include "BaseUtil.h" (literally the only line in my cpp file at the moment), line 387 in baseutil.h generates "Compile error C2039 'string_view': is not a member of 'std'".

**Comment by kjk** [comment]
Most likely you didn't tell msvc that the  code is C++17 (https://github.com/sumatrapdfreader/sumatrapdf/blob/master/premake5.lua#L519).

But this is not related to Sumatra and I'm not here to solve compilation problems in your code.
